org.jgap.gp.function.LesserThan Class Reference
Public Member Functions
LesserThan (final GPConfiguration a_conf, Class a_type) throws InvalidConfigurationException
LesserThan (final GPConfiguration a_conf, Class a_type, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException
String toString ()
String getName ()
boolean execute_boolean (ProgramChromosome c, int n, Object[] args)
Class getChildType (IGPProgram a_ind, int a_index)
Object clone ()
boolean equals (Object a_other)
Private Attributes
Class m_type
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
The Lesser Than (x < y) operation.
Author
Klaus Meffert
Since
3.2
Definition at line 24 of file LesserThan.java.
Constructor & Destructor Documentation
org.jgap.gp.function.LesserThan.LesserThan (final GPConfiguration a_conf, Class a_type) throws InvalidConfigurationException [inline]
Definition at line 31 of file LesserThan.java.
Referenced by org.jgap.gp.function.LesserThan.clone(), and org.jgap.gp.function.LesserThan.equals().
org.jgap.gp.function.LesserThan.LesserThan (final GPConfiguration a_conf, Class a_type, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException [inline]
Definition at line 36 of file LesserThan.java.
References org.jgap.gp.CommandGene.BooleanClass, and org.jgap.gp.function.LesserThan.m_type.
Member Function Documentation
Object org.jgap.gp.function.LesserThan.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 94 of file LesserThan.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getSubChildTypes(), org.jgap.gp.CommandGene.getSubReturnType(), org.jgap.gp.function.LesserThan.LesserThan(), and org.jgap.gp.function.LesserThan.m_type.
boolean org.jgap.gp.function.LesserThan.equals (Object a_other) [inline]
Definition at line 113 of file LesserThan.java.
References org.jgap.gp.function.LesserThan.LesserThan(), and org.jgap.gp.function.LesserThan.m_type.
boolean org.jgap.gp.function.LesserThan.execute_boolean (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 58 of file LesserThan.java.
References org.jgap.gp.CommandGene.BooleanClass, org.jgap.gp.CommandGene.DoubleClass, org.jgap.gp.CommandGene.FloatClass, org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.CommandGene.LongClass, and org.jgap.gp.function.LesserThan.m_type.
Class org.jgap.gp.function.LesserThan.getChildType (IGPProgram a_ind, int a_index) [inline]
Definition at line 82 of file LesserThan.java.
References org.jgap.gp.function.LesserThan.m_type.
String org.jgap.gp.function.LesserThan.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 54 of file LesserThan.java.
String org.jgap.gp.function.LesserThan.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 44 of file LesserThan.java.
Member Data Documentation
final String org.jgap.gp.function.LesserThan.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file LesserThan.java.
Class org.jgap.gp.function.LesserThan.m_type [private]
Definition at line 29 of file LesserThan.java.
Referenced by org.jgap.gp.function.LesserThan.clone(), org.jgap.gp.function.LesserThan.equals(), org.jgap.gp.function.LesserThan.execute_boolean(), org.jgap.gp.function.LesserThan.getChildType(), and org.jgap.gp.function.LesserThan.LesserThan().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/LesserThan.java