org.jgap.gp.impl.JGAPTreeNode Class Reference
Public Member Functions
JGAPTreeNode (ProgramChromosome a_chrom, int a_index)
String getName ()
TreeNode getChildAt (int a_childIndex)
int getChildCount ()
TreeNode getParent ()
int getIndex (TreeNode a_node)
boolean getAllowsChildren ()
boolean isLeaf ()
Enumeration children ()
Private Attributes
ProgramChromosome m_chrom
int m_index
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Detailed Description
A CommandGene represented as a tree node.
Author
Klaus Meffert
Since
3.0
Definition at line 22 of file JGAPTreeNode.java.
Constructor & Destructor Documentation
org.jgap.gp.impl.JGAPTreeNode.JGAPTreeNode (ProgramChromosome a_chrom, int a_index) [inline]
Definition at line 31 of file JGAPTreeNode.java.
References org.jgap.gp.impl.JGAPTreeNode.m_chrom, and org.jgap.gp.impl.JGAPTreeNode.m_index.
Referenced by org.jgap.gp.impl.JGAPTreeNode.getChildAt(), and org.jgap.gp.impl.JGAPTreeNode.getParent().
Member Function Documentation
Enumeration org.jgap.gp.impl.JGAPTreeNode.children () [inline]
Returns
the children of the receiver as an Enumeration
Definition at line 107 of file JGAPTreeNode.java.
References org.jgap.gp.impl.JGAPTreeNode.getChildAt(), and org.jgap.gp.impl.JGAPTreeNode.getChildCount().
boolean org.jgap.gp.impl.JGAPTreeNode.getAllowsChildren () [inline]
Returns
true if the receiver allows children
Definition at line 93 of file JGAPTreeNode.java.
References org.jgap.gp.impl.JGAPTreeNode.getChildCount().
TreeNode org.jgap.gp.impl.JGAPTreeNode.getChildAt (int a_childIndex) [inline]
Parameters
a_childIndex index of the child to get
Returns
the child TreeNode at index a_childIndex
Definition at line 45 of file JGAPTreeNode.java.
References org.jgap.gp.impl.JGAPTreeNode.JGAPTreeNode(), org.jgap.gp.impl.JGAPTreeNode.m_chrom, and org.jgap.gp.impl.JGAPTreeNode.m_index.
Referenced by org.jgap.gp.impl.JGAPTreeNode.children(), and org.jgap.gp.impl.JGAPTreeNode.getIndex().
int org.jgap.gp.impl.JGAPTreeNode.getChildCount () [inline]
Returns
the number of children TreeNodes the receiver contains
Definition at line 54 of file JGAPTreeNode.java.
References org.jgap.gp.impl.ProgramChromosome.getChild(), org.jgap.gp.impl.JGAPTreeNode.m_chrom, and org.jgap.gp.impl.JGAPTreeNode.m_index.
Referenced by org.jgap.gp.impl.JGAPTreeNode.children(), org.jgap.gp.impl.JGAPTreeNode.getAllowsChildren(), org.jgap.gp.impl.JGAPTreeNode.getIndex(), and org.jgap.gp.impl.JGAPTreeNode.isLeaf().
int org.jgap.gp.impl.JGAPTreeNode.getIndex (TreeNode a_node) [inline]
Parameters
a_node the node to retrieve the index for
Returns
the index of node in the receivers children. If the receiver does not contain node, -1 will be returned
Definition at line 81 of file JGAPTreeNode.java.
References org.jgap.gp.impl.JGAPTreeNode.getChildAt(), and org.jgap.gp.impl.JGAPTreeNode.getChildCount().
String org.jgap.gp.impl.JGAPTreeNode.getName () [inline]
Definition at line 37 of file JGAPTreeNode.java.
References org.jgap.gp.impl.JGAPTreeNode.m_index.
TreeNode org.jgap.gp.impl.JGAPTreeNode.getParent () [inline]
Returns
the parent TreeNode of the receiver
Definition at line 71 of file JGAPTreeNode.java.
References org.jgap.gp.impl.ProgramChromosome.getParentNode(), org.jgap.gp.impl.JGAPTreeNode.JGAPTreeNode(), org.jgap.gp.impl.JGAPTreeNode.m_chrom, and org.jgap.gp.impl.JGAPTreeNode.m_index.
boolean org.jgap.gp.impl.JGAPTreeNode.isLeaf () [inline]
Returns
true if the receiver is a leaf
Definition at line 100 of file JGAPTreeNode.java.
References org.jgap.gp.impl.JGAPTreeNode.getChildCount().
Member Data Documentation
final String org.jgap.gp.impl.JGAPTreeNode.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file JGAPTreeNode.java.
ProgramChromosome org.jgap.gp.impl.JGAPTreeNode.m_chrom [private]
Definition at line 27 of file JGAPTreeNode.java.
Referenced by org.jgap.gp.impl.JGAPTreeNode.getChildAt(), org.jgap.gp.impl.JGAPTreeNode.getChildCount(), org.jgap.gp.impl.JGAPTreeNode.getParent(), and org.jgap.gp.impl.JGAPTreeNode.JGAPTreeNode().
int org.jgap.gp.impl.JGAPTreeNode.m_index [private]
Definition at line 29 of file JGAPTreeNode.java.
Referenced by org.jgap.gp.impl.JGAPTreeNode.getChildAt(), org.jgap.gp.impl.JGAPTreeNode.getChildCount(), org.jgap.gp.impl.JGAPTreeNode.getName(), org.jgap.gp.impl.JGAPTreeNode.getParent(), and org.jgap.gp.impl.JGAPTreeNode.JGAPTreeNode().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/impl/JGAPTreeNode.java