examples.gp.anttrail.IfFoodAheadElse Class Reference
Public Member Functions
IfFoodAheadElse (final GPConfiguration a_conf) throws InvalidConfigurationException
IfFoodAheadElse (final GPConfiguration a_conf, int a_lookAheadFields) throws InvalidConfigurationException
void execute_void (ProgramChromosome a_chrom, int a_n, Object[] a_args)
String toString ()
Private Attributes
int m_lookAheadFields
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.7 $`
Additional Inherited Members
Detailed Description
If food-ahead then execute <child 0> else execute <child 1>.
Author
Klaus Meffert
Since
3.01
Definition at line 22 of file IfFoodAheadElse.java.
Constructor & Destructor Documentation
examples.gp.anttrail.IfFoodAheadElse.IfFoodAheadElse (final GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Standard constructor for the classic ant problem. Looks ahead 1 field.
Parameters
a_conf the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.01
Definition at line 38 of file IfFoodAheadElse.java.
examples.gp.anttrail.IfFoodAheadElse.IfFoodAheadElse (final GPConfiguration a_conf, int a_lookAheadFields) throws InvalidConfigurationException [inline]
Allows to specify how many fields to look ahead.
Parameters
a_conf the configuration to use
a_lookAheadFields look ahead n fields
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.01
Definition at line 54 of file IfFoodAheadElse.java.
References examples.gp.anttrail.IfFoodAheadElse.m_lookAheadFields, and org.jgap.gp.CommandGene.VoidClass.
Member Function Documentation
void examples.gp.anttrail.IfFoodAheadElse.execute_void (ProgramChromosome a_chrom, int a_n, Object[] a_args) [inline]
Definition at line 60 of file IfFoodAheadElse.java.
References examples.gp.anttrail.AntMap.EMPTY, examples.gp.anttrail.AntMap.ERROR, examples.gp.anttrail.AntMap.FOOD, examples.gp.anttrail.AntMap.getHeight(), examples.gp.anttrail.AntCommand.getMap(), examples.gp.anttrail.AntMap.getWidth(), and examples.gp.anttrail.IfFoodAheadElse.m_lookAheadFields.
String examples.gp.anttrail.IfFoodAheadElse.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 111 of file IfFoodAheadElse.java.
References examples.gp.anttrail.IfFoodAheadElse.m_lookAheadFields.
Member Data Documentation
final String examples.gp.anttrail.IfFoodAheadElse.CVS_REVISION = `$Revision: 1.7 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file IfFoodAheadElse.java.
int examples.gp.anttrail.IfFoodAheadElse.m_lookAheadFields [private]
Definition at line 27 of file IfFoodAheadElse.java.
Referenced by examples.gp.anttrail.IfFoodAheadElse.execute_void(), examples.gp.anttrail.IfFoodAheadElse.IfFoodAheadElse(), and examples.gp.anttrail.IfFoodAheadElse.toString().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/anttrail/IfFoodAheadElse.java