org.jgap.gui.GUIManager Class Reference
Public Member Functions
void showFrame (final ConfigFrame a_parent, final Configurable a_con) throws Exception
Static Public Member Functions
static GUIManager getInstance ()
static void main (String[] args)
Private Member Functions
GUIManager ()
Private Attributes
ConfigFrame m_frame
List m_childFrames
List m_childCons
Configurable m_con
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.11 $`
static GUIManager m_gm
Detailed Description
Singleton GUIManager for the JGAP Configurator. Creates a ConfigFrame on request, for a Configurable. Currently it only creates a ConfigFrame for the root object, that is a Configuration itself. In the future it will do the same for objects on the Root ConfigFrame that are in turn Configurable.
Author
Siddhartha Azad
Klaus Meffert
Since
2.3
Definition at line 30 of file GUIManager.java.
Constructor & Destructor Documentation
org.jgap.gui.GUIManager.GUIManager () [inline], [private]
Constructor for the frame.
Author
Siddhartha Azad
Since
2.3
Definition at line 70 of file GUIManager.java.
References org.jgap.gui.GUIManager.m_childCons, org.jgap.gui.GUIManager.m_childFrames, and org.jgap.gui.GUIManager.m_frame.
Referenced by org.jgap.gui.GUIManager.getInstance().
Member Function Documentation
static GUIManager org.jgap.gui.GUIManager.getInstance () [inline], [static]
Returns
a singleton GUIManager instance
Author
Siddhartha Azad
Since
2.3
Definition at line 57 of file GUIManager.java.
References org.jgap.gui.GUIManager.GUIManager(), and org.jgap.gui.GUIManager.m_gm.
static void org.jgap.gui.GUIManager.main (String[] args) [inline], [static]
Main method for the GUI
Parameters
args not used
Exceptions
Exception
Author
Siddhartha Azad
Since
2.3
Definition at line 123 of file GUIManager.java.
References org.jgap.gui.GUIManager.showFrame().
void org.jgap.gui.GUIManager.showFrame (final ConfigFrame a_parent, final Configurable a_con) throws Exception [inline]
Create and show a new frame for a Configurable.
Parameters
a_con configurable to use
Author
Siddhartha Azad
Since
2.3
Definition at line 83 of file GUIManager.java.
References org.jgap.gui.GUIManager.m_con, and org.jgap.gui.GUIManager.m_frame.
Referenced by org.jgap.gui.GUIManager.main().
Member Data Documentation
final String org.jgap.gui.GUIManager.CVS_REVISION = `$Revision: 1.11 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 32 of file GUIManager.java.
List org.jgap.gui.GUIManager.m_childCons [private]
Definition at line 41 of file GUIManager.java.
Referenced by org.jgap.gui.GUIManager.GUIManager().
List org.jgap.gui.GUIManager.m_childFrames [private]
Definition at line 38 of file GUIManager.java.
Referenced by org.jgap.gui.GUIManager.GUIManager().
Configurable org.jgap.gui.GUIManager.m_con [private]
Definition at line 44 of file GUIManager.java.
Referenced by org.jgap.gui.GUIManager.showFrame().
ConfigFrame org.jgap.gui.GUIManager.m_frame [private]
Definition at line 35 of file GUIManager.java.
Referenced by org.jgap.gui.GUIManager.GUIManager(), and org.jgap.gui.GUIManager.showFrame().
GUIManager org.jgap.gui.GUIManager.m_gm [static], [private]
Singleton instance of GUIManager
Definition at line 49 of file GUIManager.java.
Referenced by org.jgap.gui.GUIManager.getInstance().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gui/GUIManager.java