org.jgap.gp.impl.GPPopulationTest Class Reference
Public Member Functions
void setUp ()
void testConstruct_0 () throws Exception
void testCreate_0 () throws Exception
void testCreate_1 () throws Exception
void testCreate_2 () throws Exception
void testCreate_3 () throws Exception
void testSerialize_0 () throws Exception
void testSort_0 () throws Exception
void testSetPrototype_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.5 $`
Additional Inherited Members
Detailed Description
Tests the GPPopulation class.
Author
Klaus Meffert
Since
3.0
Definition at line 25 of file GPPopulationTest.java.
Member Function Documentation
void org.jgap.gp.impl.GPPopulationTest.setUp () [inline]
Definition at line 35 of file GPPopulationTest.java.
static Test org.jgap.gp.impl.GPPopulationTest.suite () [inline], [static]
Definition at line 30 of file GPPopulationTest.java.
void org.jgap.gp.impl.GPPopulationTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 45 of file GPPopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.impl.GPPopulation.getPopSize(), org.jgap.gp.GPTestCase.m_gpconf, and org.jgap.gp.impl.GPPopulation.size().
void org.jgap.gp.impl.GPPopulationTest.testCreate_0 () throws Exception [inline]
Create population with no nodes available.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 60 of file GPPopulationTest.java.
References org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.GPPopulationTest.testCreate_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Todo
Todo adapt
Definition at line 85 of file GPPopulationTest.java.
References org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.GPPopulationTest.testCreate_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Todo
Todo adapt
Definition at line 112 of file GPPopulationTest.java.
References org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.GPPopulationTest.testCreate_3 () throws Exception [inline]
Given nodeset doesn't allow to build a valid program.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 146 of file GPPopulationTest.java.
References org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.GPPopulationTest.testSerialize_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 175 of file GPPopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.doSerialize(), and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.GPPopulationTest.testSetPrototype_0 () throws Exception [inline]
Todo
Todo assert that prototype is only set automatically if none is preset
Definition at line 210 of file GPPopulationTest.java.
void org.jgap.gp.impl.GPPopulationTest.testSort_0 () throws Exception [inline]
Sorting with population having null programs, which is allowed.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 198 of file GPPopulationTest.java.
References org.jgap.gp.GPTestCase.m_gpconf.
Member Data Documentation
final String org.jgap.gp.impl.GPPopulationTest.CVS_REVISION = `$Revision: 1.5 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file GPPopulationTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/gp/impl/GPPopulationTest.java