org.jgap.impl.BooleanGene Class Reference
Public Member Functions
BooleanGene () throws InvalidConfigurationException
BooleanGene (final Configuration a_config) throws InvalidConfigurationException
BooleanGene (final Configuration a_config, final boolean a_value) throws InvalidConfigurationException
BooleanGene (final Configuration a_config, final Boolean a_value) throws InvalidConfigurationException
void setAllele (final Object a_newValue)
String getPersistentRepresentation ()
void setValueFromPersistentRepresentation (String a_representation) throws UnsupportedRepresentationException
boolean booleanValue ()
void setToRandomValue (RandomGenerator a_numberGenerator)
int compareTo (Object a_other)
void applyMutation (int a_index, double a_percentage)
int hashCode ()
String toString ()
Protected Member Functions
Gene newGeneInternal ()
Object getInternalValue ()
Static Protected Attributes
static final Boolean TRUE_BOOLEAN = Boolean.valueOf(true)
static final Boolean FALSE_BOOLEAN = Boolean.valueOf(false)
Private Attributes
Boolean m_value
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.32 $`
Additional Inherited Members
Detailed Description
A Gene implementation that supports two possible values (alleles) for each gene: true and false.
NOTE: Since this Gene implementation only supports two different values (true and false), there's only a 50% chance that invocation of the setToRandomValue() method will actually change the value of this Gene (if it has a value). As a result, it may be desirable to use a higher overall mutation rate when this Gene implementation is in use.
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 29 of file BooleanGene.java.
Constructor & Destructor Documentation
org.jgap.impl.BooleanGene.BooleanGene () throws InvalidConfigurationException [inline]
Default constructor.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.4
Definition at line 62 of file BooleanGene.java.
Referenced by org.jgap.impl.BooleanGene.compareTo(), and org.jgap.impl.BooleanGene.newGeneInternal().
org.jgap.impl.BooleanGene.BooleanGene (final Configuration a_config) throws InvalidConfigurationException [inline]
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 74 of file BooleanGene.java.
org.jgap.impl.BooleanGene.BooleanGene (final Configuration a_config, final boolean a_value) throws InvalidConfigurationException [inline]
Parameters
a_config the configuration to use
a_value allele value to setup the gene with
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.4
Definition at line 87 of file BooleanGene.java.
References org.jgap.impl.BooleanGene.m_value.
org.jgap.impl.BooleanGene.BooleanGene (final Configuration a_config, final Boolean a_value) throws InvalidConfigurationException [inline]
Parameters
a_config the configuration to use
a_value allele value to setup the gene with
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.4
Definition at line 101 of file BooleanGene.java.
References org.jgap.impl.BooleanGene.m_value.
Member Function Documentation
void org.jgap.impl.BooleanGene.applyMutation (int a_index, double a_percentage) [inline]
Applies a mutation of a given intensity (percentage) onto the atomic element at given index
Parameters
a_index not used here
a_percentage percentage of mutation (greater than -1 and smaller than 1).
Author
Klaus Meffert
Since
1.1
Implements org.jgap.Gene.
Definition at line 353 of file BooleanGene.java.
References org.jgap.impl.BooleanGene.m_value.
boolean org.jgap.impl.BooleanGene.booleanValue () [inline]
Retrieves the boolean value of this Gene. This may be more convenient in some cases than the more general getAllele() method.
Returns
the boolean value of this Gene
Definition at line 219 of file BooleanGene.java.
Referenced by org.jgap.impl.job.MaxFunction.evaluate(), org.jgap.impl.BooleanGeneTest.testApplyMutation_0(), org.jgap.impl.BooleanGeneTest.testApplyMutation_1(), org.jgap.impl.SetGeneTest.testApplyMutation_10(), org.jgap.impl.BooleanGeneTest.testApplyMutation_10(), org.jgap.impl.BooleanGeneTest.testApplyMutation_2(), org.jgap.impl.SetGeneTest.testApplyMutation_3(), org.jgap.impl.BooleanGeneTest.testApplyMutation_3(), org.jgap.impl.SetGeneTest.testApplyMutation_4(), org.jgap.impl.BooleanGeneTest.testApplyMutation_4(), org.jgap.impl.SetGeneTest.testApplyMutation_5(), org.jgap.impl.BooleanGeneTest.testApplyMutation_5(), org.jgap.impl.SetGeneTest.testApplyMutation_6(), org.jgap.impl.BooleanGeneTest.testApplyMutation_6(), org.jgap.impl.SetGeneTest.testApplyMutation_7(), org.jgap.impl.BooleanGeneTest.testApplyMutation_7(), org.jgap.impl.SetGeneTest.testApplyMutation_8(), org.jgap.impl.BooleanGeneTest.testApplyMutation_8(), org.jgap.impl.SetGeneTest.testApplyMutation_9(), org.jgap.impl.BooleanGeneTest.testApplyMutation_9(), org.jgap.impl.BooleanGeneTest.testBooleanValue_0(), org.jgap.impl.BooleanGeneTest.testBooleanValue_1(), org.jgap.impl.BooleanGeneTest.testBooleanValue_2(), org.jgap.impl.BooleanGeneTest.testConstruct_1(), and org.jgap.impl.BooleanGeneTest.testConstruct_2().
int org.jgap.impl.BooleanGene.compareTo (Object a_other) [inline]
Compares this BooleanGene with the specified object for order. A false value is considered to be less than a true value. A null value is considered to be less than any non-null value.
Parameters
a_other the BooleanGene to be compared
Returns
a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than the specified object
Exceptions
ClassCastException if the specified object's type prevents it from being compared to this BooleanGene
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 264 of file BooleanGene.java.
References org.jgap.impl.BooleanGene.BooleanGene(), org.jgap.BaseGene.compareApplicationData(), org.jgap.BaseGene.getApplicationData(), org.jgap.BaseGene.isCompareApplicationData(), and org.jgap.impl.BooleanGene.m_value.
Object org.jgap.impl.BooleanGene.getInternalValue () [inline], [protected], [virtual]
Each Gene implementation holds its own m_value object keeping the allele value. In your Gene implementation, just return it with this method (see org.jgap.impl.BooleanGene for example)
Returns
the m_value object
Author
Klaus Meffert
Since
2.2
Implements org.jgap.BaseGene.
Definition at line 373 of file BooleanGene.java.
References org.jgap.impl.BooleanGene.m_value.
Referenced by org.jgap.impl.BooleanGene.getPersistentRepresentation(), org.jgap.impl.BooleanGene.hashCode(), and org.jgap.impl.BooleanGene.toString().
String org.jgap.impl.BooleanGene.getPersistentRepresentation () [inline]
Retrieves a string representation of this Gene that includes any information required to reconstruct it at a later time, such as its value and internal state. This string will be used to represent this Gene in XML persistence. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Returns
a string representation of this Gene's current state
Author
Neil Rotstan
Klaus Meffert
Implements org.jgap.IPersistentRepresentation.
Definition at line 158 of file BooleanGene.java.
References org.jgap.impl.BooleanGene.getInternalValue().
int org.jgap.impl.BooleanGene.hashCode () [inline]
Modified hashCode() function to return different hashcodes for differently ordered genes in a chromosome
Returns
-2 if no allele set, otherwise value return by BaseGene.hashCode()
Author
Klaus Meffert
Since
2.2
Definition at line 385 of file BooleanGene.java.
References org.jgap.impl.BooleanGene.getInternalValue().
Referenced by org.jgap.impl.SetGeneTest.testHashCode_0(), and org.jgap.impl.BooleanGeneTest.testHashCode_0().
Gene org.jgap.impl.BooleanGene.newGeneInternal () [inline], [protected], [virtual]
Provides an implementation-independent means for creating new Gene instances.
Returns
a new Gene instance of the same type and with the same setup as this concrete Gene
Author
Neil Rotstan
Klaus Meffert
Implements org.jgap.BaseGene.
Definition at line 125 of file BooleanGene.java.
References org.jgap.impl.BooleanGene.BooleanGene(), and org.jgap.BaseGene.getConfiguration().
void org.jgap.impl.BooleanGene.setAllele (final Object a_newValue) [inline]
Sets the value of this Gene to the new given value. This class expects the value to be a Boolean instance.
Parameters
a_newValue the new value of this Gene instance
Definition at line 140 of file BooleanGene.java.
References org.jgap.impl.BooleanGene.m_value.
void org.jgap.impl.BooleanGene.setToRandomValue (RandomGenerator a_numberGenerator) [inline]
Sets the value (allele) of this Gene to a random legal value. This method exists for the benefit of mutation and other operations that simply desire to randomize the value of a gene.
NOTE: Since this Gene implementation only supports two different values (true and false), there's only a 50% chance that invocation of this method will actually change the value of this Gene (if it has a value). As a result, it may be desirable to use a higher overall mutation rate when this Gene implementation is in use.
Parameters
a_numberGenerator The random number generator that should be used to create any random values. It's important to use this generator to maintain the user's flexibility to configure the genetic engine to use the random number generator of their choice
Implements org.jgap.Gene.
Definition at line 239 of file BooleanGene.java.
References org.jgap.impl.BooleanGene.FALSE_BOOLEAN, org.jgap.impl.BooleanGene.m_value, org.jgap.RandomGenerator.nextBoolean(), and org.jgap.impl.BooleanGene.TRUE_BOOLEAN.
void org.jgap.impl.BooleanGene.setValueFromPersistentRepresentation (String a_representation) throws UnsupportedRepresentationException [inline]
Sets the value and internal state of this Gene from the string representation returned by a previous invocation of the getPersistentRepresentation() method. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Parameters
a_representation the string representation retrieved from a prior call to the getPersistentRepresentation() method
Exceptions
UnsupportedOperationException to indicate that no implementation is provided for this method
UnsupportedRepresentationException if this Gene implementation does not support the given string representation
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Implements org.jgap.IPersistentRepresentation.
Definition at line 189 of file BooleanGene.java.
References org.jgap.impl.BooleanGene.FALSE_BOOLEAN, org.jgap.impl.BooleanGene.m_value, and org.jgap.impl.BooleanGene.TRUE_BOOLEAN.
String org.jgap.impl.BooleanGene.toString () [inline]
Returns
string representation of this Gene's value that may be useful for display purposes.
Author
Klaus Meffert
Since
2.4
Implements org.jgap.Gene.
Definition at line 401 of file BooleanGene.java.
References org.jgap.impl.BooleanGene.getInternalValue().
Member Data Documentation
final String org.jgap.impl.BooleanGene.CVS_REVISION = `$Revision: 1.32 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 32 of file BooleanGene.java.
final Boolean org.jgap.impl.BooleanGene.FALSE_BOOLEAN = Boolean.valueOf(false) [static], [protected]
Shared constant representing the `false` boolean value. Shared constants are used to save memory so that a new Boolean object doesn't have to be constructed each time.
Definition at line 46 of file BooleanGene.java.
Referenced by org.jgap.impl.BooleanGene.setToRandomValue(), and org.jgap.impl.BooleanGene.setValueFromPersistentRepresentation().
Boolean org.jgap.impl.BooleanGene.m_value [private]
References the internal boolean value of this Gene.
Definition at line 51 of file BooleanGene.java.
Referenced by org.jgap.impl.BooleanGene.applyMutation(), org.jgap.impl.BooleanGene.BooleanGene(), org.jgap.impl.BooleanGene.compareTo(), org.jgap.impl.BooleanGene.getInternalValue(), org.jgap.impl.BooleanGene.setAllele(), org.jgap.impl.BooleanGene.setToRandomValue(), and org.jgap.impl.BooleanGene.setValueFromPersistentRepresentation().
final Boolean org.jgap.impl.BooleanGene.TRUE_BOOLEAN = Boolean.valueOf(true) [static], [protected]
Shared constant representing the `true` boolean value. Shared constants are used to save memory so that a new Boolean object doesn't have to be constructed each time.
Definition at line 39 of file BooleanGene.java.
Referenced by org.jgap.impl.BooleanGene.setToRandomValue(), and org.jgap.impl.BooleanGene.setValueFromPersistentRepresentation().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/BooleanGene.java