examples.MinimizingFitnessFunctionCached Class Reference
Public Member Functions
MinimizingFitnessFunctionCached (int a_targetAmount)
double evaluate (IChromosome a_subject)
Static Public Member Functions
static int amountOfChange (IChromosome a_potentialSolution)
static int getNumberOfCoinsAtGene (IChromosome a_potentialSolution, int a_position)
static int getTotalNumberOfCoins (IChromosome a_potentialsolution)
Static Public Attributes
static final int MAX_BOUND = 4000
Protected Member Functions
double changeDifferenceBonus (double a_maxFitness, int a_changeDifference)
double computeCoinNumberPenalty (double a_maxFitness, int a_coins)
Private Attributes
final int m_targetAmount
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Detailed Description
For any Javadoc see MinimizingMakeChangeFitnessFunction.
Additionally, this fitness function is cached.
Author
Klaus Meffert
Since
3.2
Definition at line 21 of file MinimizingFitnessFunctionCached.java.
Constructor & Destructor Documentation
examples.MinimizingFitnessFunctionCached.MinimizingFitnessFunctionCached (int a_targetAmount) [inline]
Definition at line 30 of file MinimizingFitnessFunctionCached.java.
References examples.MinimizingFitnessFunctionCached.m_targetAmount, and examples.MinimizingFitnessFunctionCached.MAX_BOUND.
Member Function Documentation
static int examples.MinimizingFitnessFunctionCached.amountOfChange (IChromosome a_potentialSolution) [inline], [static]
Definition at line 115 of file MinimizingFitnessFunctionCached.java.
References examples.MinimizingFitnessFunctionCached.getNumberOfCoinsAtGene().
Referenced by examples.MinimizingFitnessFunctionCached.evaluate().
double examples.MinimizingFitnessFunctionCached.changeDifferenceBonus (double a_maxFitness, int a_changeDifference) [inline], [protected]
Definition at line 85 of file MinimizingFitnessFunctionCached.java.
Referenced by examples.MinimizingFitnessFunctionCached.evaluate().
double examples.MinimizingFitnessFunctionCached.computeCoinNumberPenalty (double a_maxFitness, int a_coins) [inline], [protected]
Definition at line 102 of file MinimizingFitnessFunctionCached.java.
Referenced by examples.MinimizingFitnessFunctionCached.evaluate().
double examples.MinimizingFitnessFunctionCached.evaluate (IChromosome a_subject) [inline]
Definition at line 38 of file MinimizingFitnessFunctionCached.java.
References examples.MinimizingFitnessFunctionCached.amountOfChange(), examples.MinimizingFitnessFunctionCached.changeDifferenceBonus(), examples.MinimizingFitnessFunctionCached.computeCoinNumberPenalty(), examples.MinimizingFitnessFunctionCached.getTotalNumberOfCoins(), examples.MinimizingFitnessFunctionCached.m_targetAmount, and examples.MinimizingFitnessFunctionCached.MAX_BOUND.
static int examples.MinimizingFitnessFunctionCached.getNumberOfCoinsAtGene (IChromosome a_potentialSolution, int a_position) [inline], [static]
Definition at line 124 of file MinimizingFitnessFunctionCached.java.
Referenced by examples.MinimizingFitnessFunctionCached.amountOfChange(), and examples.MinimizingFitnessFunctionCached.getTotalNumberOfCoins().
static int examples.MinimizingFitnessFunctionCached.getTotalNumberOfCoins (IChromosome a_potentialsolution) [inline], [static]
Returns the total number of coins represented by all of the genes in the given potential solution.
Parameters
a_potentialsolution the potential solution to evaluate
Returns
total number of coins represented by the given Chromosome
Author
Neil Rotstan
Since
1.0
Definition at line 141 of file MinimizingFitnessFunctionCached.java.
References examples.MinimizingFitnessFunctionCached.getNumberOfCoinsAtGene().
Referenced by examples.MinimizingFitnessFunctionCached.evaluate(), and examples.MinimizingMakeChangeCached.makeChangeForAmount().
Member Data Documentation
final String examples.MinimizingFitnessFunctionCached.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file MinimizingFitnessFunctionCached.java.
final int examples.MinimizingFitnessFunctionCached.m_targetAmount [private]
Definition at line 26 of file MinimizingFitnessFunctionCached.java.
Referenced by examples.MinimizingFitnessFunctionCached.evaluate(), and examples.MinimizingFitnessFunctionCached.MinimizingFitnessFunctionCached().
final int examples.MinimizingFitnessFunctionCached.MAX_BOUND = 4000 [static]
Definition at line 28 of file MinimizingFitnessFunctionCached.java.
Referenced by examples.MinimizingFitnessFunctionCached.evaluate(), examples.MinimizingMakeChangeCached.main(), and examples.MinimizingFitnessFunctionCached.MinimizingFitnessFunctionCached().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/MinimizingFitnessFunctionCached.java