org.jgap.eval.PopulationHistoryTest Class Reference
Public Member Functions
void testConstruct_0 ()
void testConstruct_1 ()
void testGetPopulation_0 ()
void testGetPopulation_1 () throws Exception
void testRemoveAllPopulations_0 () throws Exception
void testAddPopulation_0 () throws Exception
void testAddPopulation_1 () throws Exception
void testSetPopulations_0 () throws Exception
void testSetPopulations_1 () throws Exception
void testSize_0 () throws Exception
void testGetPopulations_0 () throws Exception
void testSerializable_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.13 $`
Additional Inherited Members
Detailed Description
Tests the PopulationHistory class.
Author
Klaus Meffert
Since
1.1
Definition at line 23 of file PopulationHistoryTest.java.
Member Function Documentation
static Test org.jgap.eval.PopulationHistoryTest.suite () [inline], [static]
Definition at line 28 of file PopulationHistoryTest.java.
void org.jgap.eval.PopulationHistoryTest.testAddPopulation_0 () throws Exception [inline]
Limited capacity for 2 Population objects.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 126 of file PopulationHistoryTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.eval.PopulationHistory.size().
void org.jgap.eval.PopulationHistoryTest.testAddPopulation_1 () throws Exception [inline]
Unlimited capacity of Population objects.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 148 of file PopulationHistoryTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.eval.PopulationHistory.size().
void org.jgap.eval.PopulationHistoryTest.testConstruct_0 () [inline]
Test if construction possible.
Author
Klaus Meffert
Since
2.1
Definition at line 39 of file PopulationHistoryTest.java.
void org.jgap.eval.PopulationHistoryTest.testConstruct_1 () [inline]
Test if construction fails correctly.
Author
Klaus Meffert
Since
2.1
Definition at line 52 of file PopulationHistoryTest.java.
void org.jgap.eval.PopulationHistoryTest.testGetPopulation_0 () [inline]
Author
Klaus Meffert
Since
2.1
Definition at line 65 of file PopulationHistoryTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.eval.PopulationHistoryTest.testGetPopulation_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 76 of file PopulationHistoryTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.equals().
void org.jgap.eval.PopulationHistoryTest.testGetPopulations_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 243 of file PopulationHistoryTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.eval.PopulationHistoryTest.testRemoveAllPopulations_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 107 of file PopulationHistoryTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.eval.PopulationHistory.size().
void org.jgap.eval.PopulationHistoryTest.testSerializable_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.5
Definition at line 268 of file PopulationHistoryTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.doSerialize().
void org.jgap.eval.PopulationHistoryTest.testSetPopulations_0 () throws Exception [inline]
Unlimited capacity of Population objects.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 170 of file PopulationHistoryTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.eval.PopulationHistoryTest.testSetPopulations_1 () throws Exception [inline]
Limited capacity of Population objects.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 195 of file PopulationHistoryTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.eval.PopulationHistoryTest.testSize_0 () throws Exception [inline]
Limited capacity of Population objects.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 219 of file PopulationHistoryTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.eval.PopulationHistory.size().
Member Data Documentation
final String org.jgap.eval.PopulationHistoryTest.CVS_REVISION = `$Revision: 1.13 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file PopulationHistoryTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/eval/PopulationHistoryTest.java