org.jgap.data.config.ConfigProperty Class Reference
Public Member Functions
ConfigProperty ()
String getName ()
void setName (final String a_name)
String getWidget ()
void setWidget (final String a_widget)
String getLabel ()
void setLabel (final String a_label)
void addValue (final String a_value)
Iterator getValuesIter ()
Private Attributes
String m_name
String m_widget
String m_label
List m_values
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.5 $`
Detailed Description
Represents a property to be shown on the configuration screen.
Author
Siddhartha Azad
Since
2.3
Definition at line 20 of file ConfigProperty.java.
Constructor & Destructor Documentation
org.jgap.data.config.ConfigProperty.ConfigProperty () [inline]
Default Constructor for a ConfigProperty.
Author
Siddhartha Azad
Since
2.3
Definition at line 42 of file ConfigProperty.java.
References org.jgap.data.config.ConfigProperty.m_label, org.jgap.data.config.ConfigProperty.m_name, org.jgap.data.config.ConfigProperty.m_values, and org.jgap.data.config.ConfigProperty.m_widget.
Member Function Documentation
void org.jgap.data.config.ConfigProperty.addValue (final String a_value) [inline]
Add a value into the values ArrayList. These values are added in case the display component is a ListBox or ComboBox or something that can have multiple values.
Parameters
a_value the value to add
Author
Siddhartha Azad
Since
2.3
Definition at line 130 of file ConfigProperty.java.
String org.jgap.data.config.ConfigProperty.getLabel () [inline]
Returns
label of the property
Author
Siddhartha Azad
Since
2.4
Definition at line 105 of file ConfigProperty.java.
References org.jgap.data.config.ConfigProperty.m_label.
Referenced by org.jgap.data.config.ConfigPropertyTest.testConstruct_0(), org.jgap.data.config.ConfigPropertyTest.testGetLabel_0(), and org.jgap.data.config.ConfigPropertyTest.testGetName_0().
String org.jgap.data.config.ConfigProperty.getName () [inline]
Returns
name associated with this property
Author
Siddhartha Azad
Since
2.3
Definition at line 56 of file ConfigProperty.java.
References org.jgap.data.config.ConfigProperty.m_name.
Referenced by org.jgap.data.config.ConfigPropertyTest.testConstruct_0(), and org.jgap.data.config.ConfigPropertyTest.testGetName_0().
Iterator org.jgap.data.config.ConfigProperty.getValuesIter () [inline]
Returns
iterator on the values ArrayList for this property
Author
Siddhartha Azad
Since
2.3
Definition at line 140 of file ConfigProperty.java.
Referenced by org.jgap.data.config.ConfigPropertyTest.testAddValue_0(), and org.jgap.data.config.ConfigPropertyTest.testConstruct_0().
String org.jgap.data.config.ConfigProperty.getWidget () [inline]
Returns
name of the widget associated with this property
Author
Siddhartha Azad
Since
2.3
Definition at line 84 of file ConfigProperty.java.
References org.jgap.data.config.ConfigProperty.m_widget.
Referenced by org.jgap.data.config.ConfigPropertyTest.testConstruct_0(), and org.jgap.data.config.ConfigPropertyTest.testGetWidget_0().
void org.jgap.data.config.ConfigProperty.setLabel (final String a_label) [inline]
Sets the label.
Parameters
a_label the label of this property, by default the same as the name of the property
Author
Siddhartha Azad
Since
2.4
Definition at line 117 of file ConfigProperty.java.
References org.jgap.data.config.ConfigProperty.m_label.
void org.jgap.data.config.ConfigProperty.setName (final String a_name) [inline]
Setter for the name of this property.
Parameters
a_name the name associated with this property. This name will be used as the key in the properties file for persisting configuration information
Author
Siddhartha Azad
Since
2.3
Definition at line 69 of file ConfigProperty.java.
References org.jgap.data.config.ConfigProperty.m_label, and org.jgap.data.config.ConfigProperty.m_name.
void org.jgap.data.config.ConfigProperty.setWidget (final String a_widget) [inline]
Sets the widget.
Parameters
a_widget either `JList` or `JTextField` for now
Author
Siddhartha Azad
Since
2.3
Definition at line 95 of file ConfigProperty.java.
References org.jgap.data.config.ConfigProperty.m_widget.
Member Data Documentation
final String org.jgap.data.config.ConfigProperty.CVS_REVISION = `$Revision: 1.5 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 22 of file ConfigProperty.java.
String org.jgap.data.config.ConfigProperty.m_label [private]
Definition at line 31 of file ConfigProperty.java.
Referenced by org.jgap.data.config.ConfigProperty.ConfigProperty(), org.jgap.data.config.ConfigProperty.getLabel(), org.jgap.data.config.ConfigProperty.setLabel(), and org.jgap.data.config.ConfigProperty.setName().
String org.jgap.data.config.ConfigProperty.m_name [private]
Definition at line 25 of file ConfigProperty.java.
Referenced by org.jgap.data.config.ConfigProperty.ConfigProperty(), org.jgap.data.config.ConfigProperty.getName(), and org.jgap.data.config.ConfigProperty.setName().
List org.jgap.data.config.ConfigProperty.m_values [private]
Definition at line 34 of file ConfigProperty.java.
Referenced by org.jgap.data.config.ConfigProperty.ConfigProperty().
String org.jgap.data.config.ConfigProperty.m_widget [private]
Definition at line 28 of file ConfigProperty.java.
Referenced by org.jgap.data.config.ConfigProperty.ConfigProperty(), org.jgap.data.config.ConfigProperty.getWidget(), and org.jgap.data.config.ConfigProperty.setWidget().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/data/config/ConfigProperty.java