examples.grid.mathProblemDistributed.MyGenotypeInitializer Class Reference
Public Member Functions
GPGenotype setupGenotype (JGAPRequestGP a_req, GPPopulation a_initialPop) throws Exception
void initPop (GPConfiguration conf, GridConfiguration gridConfig) throws Exception
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.7 $`
Detailed Description
Initializes the genotype on behalf of the workers in a grid.
Author
Klaus Meffert
Since
3.2
Definition at line 22 of file MyGenotypeInitializer.java.
Member Function Documentation
void examples.grid.mathProblemDistributed.MyGenotypeInitializer.initPop (GPConfiguration conf, GridConfiguration gridConfig) throws Exception [inline]
Initializes a partly or fully incomplete population on behalf of the worker.
Parameters
conf the GP configuration
gridConfig the grid configuration
Exceptions
Exception
Author
Klaus Meffert
Since
3.6
Definition at line 76 of file MyGenotypeInitializer.java.
Referenced by examples.grid.mathProblemDistributed.MyGenotypeInitializer.setupGenotype().
GPGenotype examples.grid.mathProblemDistributed.MyGenotypeInitializer.setupGenotype (JGAPRequestGP a_req, GPPopulation a_initialPop) throws Exception [inline]
Definition at line 27 of file MyGenotypeInitializer.java.
References org.jgap.Configuration.getPopulationSize(), and examples.grid.mathProblemDistributed.MyGenotypeInitializer.initPop().
Member Data Documentation
final String examples.grid.mathProblemDistributed.MyGenotypeInitializer.CVS_REVISION = `$Revision: 1.7 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file MyGenotypeInitializer.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/grid/mathProblemDistributed/MyGenotypeInitializer.java