org.jgap.impl.ThresholdSelectorTest Class Reference
Public Member Functions
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testConstruct_2 () throws Exception
void testConstruct_3 () throws Exception
void testAdd_0 () throws Exception
void testSelect_0 () throws Exception
void testSelect_1 () throws Exception
void testSelect_2 () throws Exception
void testSelect_3 () throws Exception
void testSelect_4 () throws Exception
void testSelect_5 () throws Exception
void testEmpty_0 () throws Exception
void testEmpty_1 () throws Exception
void testEmpty_2 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.19 $`
Additional Inherited Members
Detailed Description
Tests the ThresholdSelector class.
Author
Klaus Meffert
Since
2.0
Definition at line 25 of file ThresholdSelectorTest.java.
Member Function Documentation
static Test org.jgap.impl.ThresholdSelectorTest.suite () [inline], [static]
Definition at line 30 of file ThresholdSelectorTest.java.
void org.jgap.impl.ThresholdSelectorTest.testAdd_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 90 of file ThresholdSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.ThresholdSelectorTest.testConstruct_0 () throws Exception [inline]
Definition at line 35 of file ThresholdSelectorTest.java.
void org.jgap.impl.ThresholdSelectorTest.testConstruct_1 () throws Exception [inline]
Definition at line 46 of file ThresholdSelectorTest.java.
void org.jgap.impl.ThresholdSelectorTest.testConstruct_2 () throws Exception [inline]
Definition at line 57 of file ThresholdSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, org.jgap.JGAPTestCase.getNestedField(), and org.jgap.impl.ThresholdSelector.returnsUniqueChromosomes().
void org.jgap.impl.ThresholdSelectorTest.testConstruct_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 77 of file ThresholdSelectorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.ThresholdSelectorTest.testEmpty_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 338 of file ThresholdSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.ThresholdSelectorTest.testEmpty_1 () throws Exception [inline]
Test if method clear() does not affect original Population.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 360 of file ThresholdSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.ThresholdSelectorTest.testEmpty_2 () throws Exception [inline]
Test if method clear() does not affect return value.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 382 of file ThresholdSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.ThresholdSelectorTest.testSelect_0 () throws Exception [inline]
Test if below functionality available without error.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 114 of file ThresholdSelectorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.ThresholdSelectorTest.testSelect_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 136 of file ThresholdSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.ThresholdSelectorTest.testSelect_2 () throws Exception [inline]
Always select best chromosome if threshold is 1.0d.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 185 of file ThresholdSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.ThresholdSelectorTest.testSelect_3 () throws Exception [inline]
Never select best chromosome for granted if threshold is 0.0d.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 227 of file ThresholdSelectorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.ThresholdSelectorTest.testSelect_4 () throws Exception [inline]
Ensure that selected Chromosome's are not equal to added Chromosome's.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 263 of file ThresholdSelectorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.ThresholdSelectorTest.testSelect_5 () throws Exception [inline]
Always select best chromosome if threshold is 1.0d. Target population not empty.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 298 of file ThresholdSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
Member Data Documentation
final String org.jgap.impl.ThresholdSelectorTest.CVS_REVISION = `$Revision: 1.19 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file ThresholdSelectorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/ThresholdSelectorTest.java