org.jgap.impl.BulkFitnessOffsetRemoverTest Class Reference
Classes
class DummyFitnessFunction
Public Member Functions
void testDummyFitnessFunction_0 () throws Exception
void testDummyFitnessFunction_1 () throws Exception
void testConstructor_0 ()
void testConstructor_1 ()
void testEvaluate_0 () throws Exception
void testEvaluate_1 () throws Exception
void testEvaluate_2 () throws Exception
void testEvaluate_3 () throws Exception
void testGetAbsoluteFitness_0 () throws Exception
Static Public Member Functions
static Test suite ()
Private Attributes
final transient FitnessFunction m_fitnessFunction
final transient BulkFitnessFunction m_bulkFitnessFunction
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.12 $`
Additional Inherited Members
Detailed Description
Tests for the BulkFitnessOffsetRemover class.
Author
Achim Westermann
Since
2.2
Definition at line 21 of file BulkFitnessOffsetRemoverTest.java.
Member Function Documentation
static Test org.jgap.impl.BulkFitnessOffsetRemoverTest.suite () [inline], [static]
Definition at line 36 of file BulkFitnessOffsetRemoverTest.java.
void org.jgap.impl.BulkFitnessOffsetRemoverTest.testConstructor_0 () [inline]
Definition at line 99 of file BulkFitnessOffsetRemoverTest.java.
References org.jgap.impl.BulkFitnessOffsetRemoverTest.m_fitnessFunction.
void org.jgap.impl.BulkFitnessOffsetRemoverTest.testConstructor_1 () [inline]
Definition at line 104 of file BulkFitnessOffsetRemoverTest.java.
void org.jgap.impl.BulkFitnessOffsetRemoverTest.testDummyFitnessFunction_0 () throws Exception [inline]
Test the inner class DummyFitnessFunction that is needed for this test with IntegerGenes in a Chromosome.
Exceptions
Exception
Definition at line 47 of file BulkFitnessOffsetRemoverTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.BulkFitnessOffsetRemoverTest.m_fitnessFunction.
void org.jgap.impl.BulkFitnessOffsetRemoverTest.testDummyFitnessFunction_1 () throws Exception [inline]
Test the inner class DummyFitnessFunction that is needed for this test with a mix of IntegerGenes and DoubleGenes in a Chromosome.
Exceptions
Exception
Definition at line 76 of file BulkFitnessOffsetRemoverTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.BulkFitnessOffsetRemoverTest.m_fitnessFunction.
void org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_0 () throws Exception [inline]
Tests the method BulkFitnessOffsetRemover.evaluate(java.util.List) with a list of two Chromosomes with each one IntegerGene with the allele 100.
Author
Achim Westermann
Since
2.2
Exceptions
Exception
Definition at line 123 of file BulkFitnessOffsetRemoverTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.BulkFitnessOffsetRemoverTest.m_bulkFitnessFunction, and org.jgap.impl.BulkFitnessOffsetRemoverTest.m_fitnessFunction.
void org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_1 () throws Exception [inline]
Tests the method BulkFitnessOffsetRemover.evaluate(List) with a list of two Chromosomes with one IntegerGene with the allele 100. The IntegerGene is the same instance in both Chromosomes.
Author
Achim Westermann
Since
2.2
Exceptions
Exception
Definition at line 157 of file BulkFitnessOffsetRemoverTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.BulkFitnessOffsetRemoverTest.m_bulkFitnessFunction, and org.jgap.impl.BulkFitnessOffsetRemoverTest.m_fitnessFunction.
void org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_2 () throws Exception [inline]
Tests the method BulkFitnessOffsetRemover.evaluate(List) with a list of two Chromosomes with each one IntegerGene with the allele 200. The Chromosomes ar the same instance in the List that is evaluated.
Author
Achim Westermann
Since
2.2
Exceptions
Exception
Definition at line 189 of file BulkFitnessOffsetRemoverTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.BulkFitnessOffsetRemoverTest.m_bulkFitnessFunction, and org.jgap.impl.BulkFitnessOffsetRemoverTest.m_fitnessFunction.
void org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_3 () throws Exception [inline]
Tests the method BulkFitnessOffsetRemover.evaluate(List) with a list of two Chromosomes with each two NumberGenes.
                 chromosomeA
                / \
            IntegerGene DoubleGene => Fitness 4100.15
               | |
             100 4000.15
                 chromosomeB
                / \
            IntegerGene DoubleGene =>; Fitness 1234 + 14e-5
               | |
             1234 14e-5
Author
Achim Westermann
Since
2.2
Exceptions
Exception
Definition at line 229 of file BulkFitnessOffsetRemoverTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.Chromosome.getFitnessValue(), org.jgap.impl.BulkFitnessOffsetRemoverTest.m_bulkFitnessFunction, and org.jgap.impl.BulkFitnessOffsetRemoverTest.m_fitnessFunction.
void org.jgap.impl.BulkFitnessOffsetRemoverTest.testGetAbsoluteFitness_0 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 284 of file BulkFitnessOffsetRemoverTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.Chromosome.getFitnessValue().
Member Data Documentation
final String org.jgap.impl.BulkFitnessOffsetRemoverTest.CVS_REVISION = `$Revision: 1.12 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file BulkFitnessOffsetRemoverTest.java.
final transient BulkFitnessFunction org.jgap.impl.BulkFitnessOffsetRemoverTest.m_bulkFitnessFunction [private]
Initial value:
=
      new BulkFitnessOffsetRemover(m_fitnessFunction)
Definition at line 33 of file BulkFitnessOffsetRemoverTest.java.
Referenced by org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_0(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_1(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_2(), and org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_3().
final transient FitnessFunction org.jgap.impl.BulkFitnessOffsetRemoverTest.m_fitnessFunction [private]
Initial value:
=
      new DummyFitnessFunction()
Definition at line 28 of file BulkFitnessOffsetRemoverTest.java.
Referenced by org.jgap.impl.BulkFitnessOffsetRemoverTest.testConstructor_0(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testDummyFitnessFunction_0(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testDummyFitnessFunction_1(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_0(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_1(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_2(), and org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_3().
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/BulkFitnessOffsetRemoverTest.java