org.jgap.impl.SetGeneTest Class Reference
Public Member Functions
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testToString_0 () throws Exception
void testToString_1 () throws Exception
void testGetAllele_0 () throws Exception
void testEquals_0 () throws Exception
void testEquals_1 () throws Exception
void testEquals_2 () throws Exception
void testEquals_3 () throws Exception
void testEquals_4 () throws Exception
void testEquals_5 () throws Exception
void testSetAllele_0 () throws Exception
void testSetAllele_1 () throws Exception
void testSetAllele_2 () throws Exception
void testCompareTo_0 () throws Exception
void testCompareTo_1 () throws Exception
void testCompareTo_2 () throws Exception
void testCompareTo_3 () throws Exception
void testApplyMutation_0 () throws Exception
void testApplyMutation_1 () throws Exception
void testApplyMutation_2 () throws Exception
void testApplyMutation_3 () throws Exception
void testApplyMutation_4 () throws Exception
void testApplyMutation_5 () throws Exception
void testApplyMutation_6 () throws Exception
void testApplyMutation_7 () throws Exception
void testApplyMutation_8 () throws Exception
void testApplyMutation_9 () throws Exception
void testApplyMutation_10 () throws Exception
void testSetValueFromPersistentRepresentation_0 () throws Exception
void testSetValueFromPersistentRepresentation_1 () throws Exception
void testSetValueFromPersistentRepresentation_2 () throws Exception
void testSetValueFromPersistentRepresentation_3 () throws Exception
void testSetValueFromPersistentRepresentation_4 () throws Exception
void testSetValueFromPersistentRepresentation_5 () throws Exception
void testSetValueFromPersistentRepresentation_6 () throws Exception
void testGetPersistentRepresentation_0 () throws Exception
void testGetPersistentRepresentation_1 () throws Exception
void testGetPersistentRepresentation_2 () throws Exception
void testHashCode_0 () throws Exception
void testSetEnergy_0 () throws Exception
void testSetEnergy_1 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.7 $`
Additional Inherited Members
Detailed Description
Tests the SetGene class.
Author
Klaus Meffert
Since
3.0
Definition at line 22 of file SetGeneTest.java.
Member Function Documentation
static Test org.jgap.impl.SetGeneTest.suite () [inline], [static]
Definition at line 27 of file SetGeneTest.java.
void org.jgap.impl.SetGeneTest.testApplyMutation_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 246 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testApplyMutation_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 263 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testApplyMutation_10 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 390 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testApplyMutation_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 280 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testApplyMutation_3 () throws Exception [inline]
Todo
Todo from here on: adapt tests to SetGene
Author
Klaus Meffert
Exceptions
Exception
Definition at line 298 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testApplyMutation_4 () throws Exception [inline]
Author
Klaus Meffert
Exceptions
Exception
Definition at line 311 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testApplyMutation_5 () throws Exception [inline]
Author
Klaus Meffert
Exceptions
Exception
Definition at line 324 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testApplyMutation_6 () throws Exception [inline]
Author
Klaus Meffert
Exceptions
Exception
Definition at line 337 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testApplyMutation_7 () throws Exception [inline]
Author
Klaus Meffert
Exceptions
Exception
Definition at line 350 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testApplyMutation_8 () throws Exception [inline]
Author
Klaus Meffert
Exceptions
Exception
Definition at line 363 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testApplyMutation_9 () throws Exception [inline]
Author
Klaus Meffert
Exceptions
Exception
Definition at line 376 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testCompareTo_0 () throws Exception [inline]
Definition at line 196 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testCompareTo_1 () throws Exception [inline]
Definition at line 202 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testCompareTo_2 () throws Exception [inline]
Definition at line 210 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.SetGene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testCompareTo_3 () throws Exception [inline]
Definition at line 228 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.SetGene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testConstruct_0 () throws Exception [inline]
Definition at line 32 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getConfiguration().
void org.jgap.impl.SetGeneTest.testConstruct_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 44 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.SetGene.getInternalValue().
void org.jgap.impl.SetGeneTest.testEquals_0 () throws Exception [inline]
Definition at line 96 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testEquals_1 () throws Exception [inline]
Definition at line 103 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testEquals_2 () throws Exception [inline]
Definition at line 109 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.equals().
void org.jgap.impl.SetGeneTest.testEquals_3 () throws Exception [inline]
Definition at line 121 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testEquals_4 () throws Exception [inline]
Definition at line 127 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testEquals_5 () throws Exception [inline]
Definition at line 135 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testGetAllele_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 87 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.SetGeneTest.testGetPersistentRepresentation_0 () throws Exception [inline]
Author
Klaus Meffert
Exceptions
Exception
Definition at line 507 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testGetPersistentRepresentation_1 () throws Exception [inline]
Author
Klaus Meffert
Exceptions
Exception
Definition at line 520 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testGetPersistentRepresentation_2 () throws Exception [inline]
Author
Klaus Meffert
Exceptions
Exception
Definition at line 533 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testHashCode_0 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 546 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.BooleanGene.hashCode().
void org.jgap.impl.SetGeneTest.testSetAllele_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 149 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testSetAllele_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 167 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testSetAllele_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 187 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testSetEnergy_0 () throws Exception [inline]
Author
Klaus Meffert
Since
2.4
Exceptions
Exception
Definition at line 558 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getEnergy().
void org.jgap.impl.SetGeneTest.testSetEnergy_1 () throws Exception [inline]
Author
Klaus Meffert
Since
2.4
Exceptions
Exception
Definition at line 570 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getEnergy().
void org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_0 () throws Exception [inline]
Should be possible without exception.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 404 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 416 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 429 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 441 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_4 () throws Exception [inline]
Author
Klaus Meffert
Since
2.0
Exceptions
Exception
Definition at line 454 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_5 () throws Exception [inline]
Author
Klaus Meffert
Since
2.0
Exceptions
Exception
Definition at line 472 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_6 () throws Exception [inline]
Author
Klaus Meffert
Since
2.0
Exceptions
Exception
Definition at line 490 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SetGeneTest.testToString_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 56 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.toString().
void org.jgap.impl.SetGeneTest.testToString_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 71 of file SetGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.toString().
Member Data Documentation
final String org.jgap.impl.SetGeneTest.CVS_REVISION = `$Revision: 1.7 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file SetGeneTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/SetGeneTest.java