org.jgap.gp.function.Pop Class Reference
Public Member Functions
Pop (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException
Pop (final GPConfiguration a_conf, Class a_returnType, int a_subReturnType) throws InvalidConfigurationException
String toString ()
String getName ()
int execute_int (ProgramChromosome c, int n, Object[] args)
long execute_long (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
boolean isValid (ProgramChromosome a_program)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.9 $`
Additional Inherited Members
Detailed Description
Pops a value from the stack after it has been pushed onto it (PushCommand).
Author
Klaus Meffert
Since
3.0
Definition at line 23 of file Pop.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Pop.Pop (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 28 of file Pop.java.
Referenced by org.jgap.gp.function.Pop.clone().
org.jgap.gp.function.Pop.Pop (final GPConfiguration a_conf, Class a_returnType, int a_subReturnType) throws InvalidConfigurationException [inline]
Definition at line 33 of file Pop.java.
Member Function Documentation
Object org.jgap.gp.function.Pop.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 108 of file Pop.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), org.jgap.gp.CommandGene.getSubReturnType(), and org.jgap.gp.function.Pop.Pop().
double org.jgap.gp.function.Pop.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 72 of file Pop.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.CommandGene.getGPConfiguration().
float org.jgap.gp.function.Pop.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 80 of file Pop.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.CommandGene.getGPConfiguration().
int org.jgap.gp.function.Pop.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 53 of file Pop.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.CommandGene.getGPConfiguration().
long org.jgap.gp.function.Pop.execute_long (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 64 of file Pop.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.CommandGene.getGPConfiguration().
Object org.jgap.gp.function.Pop.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 88 of file Pop.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.CommandGene.getGPConfiguration().
String org.jgap.gp.function.Pop.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 49 of file Pop.java.
boolean org.jgap.gp.function.Pop.isValid (ProgramChromosome a_program) [inline]
Definition at line 96 of file Pop.java.
String org.jgap.gp.function.Pop.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 39 of file Pop.java.
Member Data Documentation
final String org.jgap.gp.function.Pop.CVS_REVISION = `$Revision: 1.9 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file Pop.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Pop.java