org.jgap.FitnessFunctionTest Class Reference
Classes
class FitnessFunctionImpl
Public Member Functions
void testGetFitnessValue_0 ()
void testGetFitnessValue_1 ()
void testGetFitnessValue_2 ()
void testLastComputedValue_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.16 $`
Additional Inherited Members
Detailed Description
Tests the FitnessFunction class.
Author
Klaus Meffert
Since
1.1
Definition at line 20 of file FitnessFunctionTest.java.
Member Function Documentation
static Test org.jgap.FitnessFunctionTest.suite () [inline], [static]
Definition at line 25 of file FitnessFunctionTest.java.
void org.jgap.FitnessFunctionTest.testGetFitnessValue_0 () [inline]
Definition at line 30 of file FitnessFunctionTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.FitnessFunction.getFitnessValue().
void org.jgap.FitnessFunctionTest.testGetFitnessValue_1 () [inline]
Definition at line 35 of file FitnessFunctionTest.java.
void org.jgap.FitnessFunctionTest.testGetFitnessValue_2 () [inline]
Definition at line 46 of file FitnessFunctionTest.java.
void org.jgap.FitnessFunctionTest.testLastComputedValue_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 62 of file FitnessFunctionTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.DELTA, org.jgap.FitnessFunction.getLastComputedFitnessValue(), and org.jgap.FitnessFunction.NO_FITNESS_VALUE.
Member Data Documentation
final String org.jgap.FitnessFunctionTest.CVS_REVISION = `$Revision: 1.16 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 23 of file FitnessFunctionTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/FitnessFunctionTest.java