org.jgap.gp.impl.GPPopulation Class Reference
Public Member Functions
GPPopulation () throws Exception
GPPopulation (GPConfiguration a_config, int a_size) throws InvalidConfigurationException
GPPopulation (GPPopulation a_pop) throws InvalidConfigurationException
GPPopulation (GPPopulation a_pop, boolean a_keepPrograms) throws InvalidConfigurationException
void sort (Comparator c)
void create (Class[] a_types, Class[][] a_argTypes, CommandGene[][] a_nodeSets, int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, boolean[] a_fullModeAllowed) throws InvalidConfigurationException
void create (Class[] a_types, Class[][] a_argTypes, CommandGene[][] a_nodeSets, int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, boolean[] a_fullModeAllowed, IProgramCreator a_programCreator) throws InvalidConfigurationException
void create (Class[] a_types, Class[][] a_argTypes, CommandGene[][] a_nodeSets, int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, boolean[] a_fullModeAllowed, IProgramCreator a_programCreator, int a_offset) throws InvalidConfigurationException
IGPProgram create (Class[] a_types, Class[][] a_argTypes, CommandGene[][] a_nodeSets, int[] a_minDepths, int[] a_maxDepths, int a_depth, boolean a_grow, int a_maxNodes, boolean[] a_fullModeAllowed, int a_tries) throws InvalidConfigurationException
IGPProgram create (int a_programIndex, Class[] a_types, Class[][] a_argTypes, CommandGene[][] a_nodeSets, int[] a_minDepths, int[] a_maxDepths, int a_depth, boolean a_grow, int a_maxNodes, boolean[] a_fullModeAllowed, int a_tries) throws InvalidConfigurationException
IGPProgram create (int a_programIndex, Class[] a_types, Class[][] a_argTypes, CommandGene[][] a_nodeSets, int[] a_minDepths, int[] a_maxDepths, int a_depth, boolean a_grow, int a_maxNodes, boolean[] a_fullModeAllowed, int a_tries, IProgramCreator a_programCreator) throws InvalidConfigurationException
int getPopSize ()
GPConfiguration getGPConfiguration ()
void setGPProgram (final int a_index, final IGPProgram a_program)
IGPProgram getGPProgram (int a_index)
void setGPPrograms (final GPPopulation a_pop)
void setGPPrograms (final IGPProgram[] a_progs)
void copyGPPrograms (final GPPopulation a_pop)
void setGPPrograms (final List a_pop)
IGPProgram[] getGPPrograms ()
int size ()
IGPProgram determineFittestProgram ()
IGPProgram determineFittestProgramComputed ()
List determineFittestChromosomes (final int a_numberOfPrograms)
void sortByFitness ()
float[] getFitnessRanks ()
float getFitnessRank (int a_index)
boolean isChanged ()
int compareTo (Object a_pop)
boolean equals (Object a_pop)
void addFittestProgram (final IGPProgram a_toAdd)
void clear ()
boolean isFirstEmpty ()
String getPersistentRepresentation ()
Static Public Attributes
static final double DELTA = 0.0000001d
Protected Member Functions
void setChanged (final boolean a_changed)
void setSorted (final boolean a_sorted)
boolean containedInArray (IGPProgram[] a_progs, IGPProgram a_prog)
String encode (String a_string)
String decode (String a_string)
Private Attributes
transient Logger LOGGER = Logger.getLogger(GPPopulation.class)
transient int warningPrototypeReused = 0
IGPProgram[] m_programs
float[] m_fitnessRank
int m_popSize
transient IGPProgram m_fittestProgram
GPConfiguration m_config
boolean m_changed
boolean m_sorted
IGPProgram m_fittestToAdd
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.43 $`
Detailed Description
Population for GP programs.
Author
Klaus Meffert
Since
3.0
Definition at line 26 of file GPPopulation.java.
Constructor & Destructor Documentation
org.jgap.gp.impl.GPPopulation.GPPopulation () throws Exception [inline]
Default constructor, only for dynamic instantiation.
Exceptions
Exception
Author
Klaus Meffert
Since
3.3.4
Definition at line 78 of file GPPopulation.java.
Referenced by org.jgap.gp.impl.GPPopulation.compareTo().
org.jgap.gp.impl.GPPopulation.GPPopulation (GPConfiguration a_config, int a_size) throws InvalidConfigurationException [inline]
Definition at line 89 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_config, org.jgap.gp.impl.GPPopulation.m_fitnessRank, org.jgap.gp.impl.GPPopulation.m_popSize, and org.jgap.gp.impl.GPPopulation.m_programs.
org.jgap.gp.impl.GPPopulation.GPPopulation (GPPopulation a_pop) throws InvalidConfigurationException [inline]
Definition at line 116 of file GPPopulation.java.
org.jgap.gp.impl.GPPopulation.GPPopulation (GPPopulation a_pop, boolean a_keepPrograms) throws InvalidConfigurationException [inline]
Parameters
a_pop the population to retrieve the parameters from
a_keepPrograms true copy programs of given population to this one
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Definition at line 129 of file GPPopulation.java.
References org.jgap.util.ICloneable.clone(), org.jgap.gp.impl.GPPopulation.m_changed, org.jgap.gp.impl.GPPopulation.m_config, org.jgap.gp.impl.GPPopulation.m_fitnessRank, org.jgap.gp.impl.GPPopulation.m_fittestProgram, org.jgap.gp.impl.GPPopulation.m_popSize, org.jgap.gp.impl.GPPopulation.m_programs, org.jgap.gp.impl.GPPopulation.m_sorted, and org.jgap.gp.impl.GPPopulation.setChanged().
Member Function Documentation
void org.jgap.gp.impl.GPPopulation.addFittestProgram (final IGPProgram a_toAdd) [inline]
Adds a GP program to this Population. Does nothing when given null. The injection is actually executed in method create(..)
Parameters
a_toAdd the program to add
Author
Klaus Meffert
Since
3.2
Definition at line 907 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_fittestToAdd.
void org.jgap.gp.impl.GPPopulation.clear () [inline]
Clears the list of programs. Normally, this should not be necessary. But especially in distributed computing, a fresh population has to be provided sometimes.
Author
Klaus Meffert
Since
3.2
Definition at line 921 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_changed, org.jgap.gp.impl.GPPopulation.m_fittestProgram, org.jgap.gp.impl.GPPopulation.m_programs, and org.jgap.gp.impl.GPPopulation.m_sorted.
int org.jgap.gp.impl.GPPopulation.compareTo (Object a_pop) [inline]
This method is not producing symmetric results as -1 is more often returned than 1 (see description of return value).
Parameters
a_pop the other population to compare
Returns
1: a_pop is null or having fewer programs or equal number of programs but at least one not contained. 0: both populations containing exactly the same programs. -1: this population contains fewer programs than a_pop
Author
Klaus Meffert
Since
2.6
Definition at line 831 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.containedInArray(), org.jgap.gp.impl.GPPopulation.GPPopulation(), org.jgap.gp.impl.GPPopulation.m_programs, and org.jgap.gp.impl.GPPopulation.size().
Referenced by org.jgap.gp.impl.GPPopulation.equals().
boolean org.jgap.gp.impl.GPPopulation.containedInArray (IGPProgram[] a_progs, IGPProgram a_prog) [inline], [protected]
Checks if a program is contained within an array of programs. Assumes that in the array no element will follow after the first null element.
Parameters
a_progs the array to search thru
a_prog the program to find
Returns
true: program found in array via equals-method
Author
Klaus Meffert
Since
3.0
Definition at line 866 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.equals().
Referenced by org.jgap.gp.impl.GPPopulation.compareTo().
void org.jgap.gp.impl.GPPopulation.copyGPPrograms (final GPPopulation a_pop) [inline]
Sets the GPPrograms of the given population to this population.
Parameters
a_pop the population to use as template
Author
Klaus Meffert
Since
3.3.3
Definition at line 610 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_programs, org.jgap.gp.impl.GPPopulation.setChanged(), and org.jgap.gp.impl.GPPopulation.size().
void org.jgap.gp.impl.GPPopulation.create (Class[] a_types, Class a_argTypes[][], CommandGene a_nodeSets[][], int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, boolean[] a_fullModeAllowed) throws InvalidConfigurationException [inline]
Creates a population.
Parameters
a_types the type for each chromosome, the length of the array represents the number of chromosomes
a_argTypes the types of the arguments to each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of arguments to the chromosome
a_nodeSets the nodes which are allowed to be used by each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of nodes
a_minDepths contains the minimum depth allowed for each chromosome
a_maxDepths contains the maximum depth allowed for each chromosome
a_maxNodes reserve space for a_maxNodes number of nodes
a_fullModeAllowed array of boolean values. For each chromosome there is one value indicating whether the full mode for creating chromosome generations during evolution is allowed (true) or not (false)
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 205 of file GPPopulation.java.
Referenced by org.jgap.gp.impl.GPPopulation.create().
void org.jgap.gp.impl.GPPopulation.create (Class[] a_types, Class a_argTypes[][], CommandGene a_nodeSets[][], int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, boolean[] a_fullModeAllowed, IProgramCreator a_programCreator) throws InvalidConfigurationException [inline]
Creates a population.
Parameters
a_types the type for each chromosome, the length of the array represents the number of chromosomes
a_argTypes the types of the arguments to each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of arguments to the chromosome
a_nodeSets the nodes which are allowed to be used by each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of nodes
a_minDepths contains the minimum depth allowed for each chromosome
a_maxDepths contains the maximum depth allowed for each chromosome
a_maxNodes reserve space for a_maxNodes number of nodes
a_fullModeAllowed array of boolean values. For each chromosome there is one value indicating whether the full mode for creating chromosome generations during evolution is allowed (true) or not (false)
a_programCreator service to create new programs with
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.2.2
Definition at line 238 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.create().
void org.jgap.gp.impl.GPPopulation.create (Class[] a_types, Class a_argTypes[][], CommandGene a_nodeSets[][], int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, boolean[] a_fullModeAllowed, IProgramCreator a_programCreator, int a_offset) throws InvalidConfigurationException [inline]
Creates a population.
Parameters
a_types the type for each chromosome, the length of the array represents the number of chromosomes
a_argTypes the types of the arguments to each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of arguments to the chromosome
a_nodeSets the nodes which are allowed to be used by each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of nodes
a_minDepths contains the minimum depth allowed for each chromosome
a_maxDepths contains the maximum depth allowed for each chromosome
a_maxNodes reserve space for a_maxNodes number of nodes
a_fullModeAllowed array of boolean values. For each chromosome there is one value indicating whether the full mode for creating chromosome generations during evolution is allowed (true) or not (false)
a_programCreator service to create new programs with
a_offset start index for new programs to put into the configuration
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.3.3
Todo
Todo add element of randomness
Todo
Todo 5: make configurable
Definition at line 274 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.create(), org.jgap.gp.impl.GPPopulation.getGPConfiguration(), org.jgap.gp.impl.GPPopulation.m_popSize, org.jgap.IHandler.perform(), org.jgap.gp.impl.GPPopulation.setChanged(), org.jgap.gp.impl.GPPopulation.setGPProgram(), and org.jgap.gp.impl.GPPopulation.warningPrototypeReused.
IGPProgram org.jgap.gp.impl.GPPopulation.create (Class[] a_types, Class a_argTypes[][], CommandGene a_nodeSets[][], int[] a_minDepths, int[] a_maxDepths, int a_depth, boolean a_grow, int a_maxNodes, boolean[] a_fullModeAllowed, int a_tries) throws InvalidConfigurationException [inline]
Creates a population.
Parameters
a_types Class[]
a_argTypes Class[][]
a_nodeSets CommandGene[][]
a_minDepths int[]
a_maxDepths int[]
a_depth int
a_grow boolean
a_maxNodes int
a_fullModeAllowed boolean[]
a_tries int
Returns
IGPProgram
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.2.2
Definition at line 413 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.create().
IGPProgram org.jgap.gp.impl.GPPopulation.create (int a_programIndex, Class[] a_types, Class a_argTypes[][], CommandGene a_nodeSets[][], int[] a_minDepths, int[] a_maxDepths, int a_depth, boolean a_grow, int a_maxNodes, boolean[] a_fullModeAllowed, int a_tries) throws InvalidConfigurationException [inline]
Parameters
a_programIndex int
a_types Class[]
a_argTypes Class[][]
a_nodeSets CommandGene[][]
a_minDepths int[]
a_maxDepths int[]
a_depth int
a_grow boolean
a_maxNodes int
a_fullModeAllowed boolean[]
a_tries int
Returns
IGPProgram
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.3
Definition at line 442 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.create().
IGPProgram org.jgap.gp.impl.GPPopulation.create (int a_programIndex, Class[] a_types, Class a_argTypes[][], CommandGene a_nodeSets[][], int[] a_minDepths, int[] a_maxDepths, int a_depth, boolean a_grow, int a_maxNodes, boolean[] a_fullModeAllowed, int a_tries, IProgramCreator a_programCreator) throws InvalidConfigurationException [inline]
Creates a valid IGPProgram. No fitness computation is initiated here!
Parameters
a_programIndex index of the program in the population
a_types the type of each chromosome, the length is the number of chromosomes
a_argTypes the types of the arguments to each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of arguments to the chromosome
a_nodeSets the nodes which are allowed to be used by each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of nodes
a_minDepths contains the minimum depth allowed for each chromosome
a_maxDepths contains the maximum depth allowed for each chromosome
a_depth the maximum depth of the program to create
a_grow true: grow mode, false: full mode
a_maxNodes reserve space for a_maxNodes number of nodes
a_fullModeAllowed array of boolean values. For each chromosome there is one value indicating whether the full mode for creating chromosomes during evolution is allowed (true) or not (false)
a_tries maximum number of tries to get a valid program
a_programCreator strategy class to create programs for the population
Returns
valid program
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 486 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.getGPConfiguration(), org.jgap.gp.impl.GPPopulation.m_fittestToAdd, and org.jgap.IHandler.perform().
String org.jgap.gp.impl.GPPopulation.decode (String a_string) [inline], [protected]
Definition at line 964 of file GPPopulation.java.
List org.jgap.gp.impl.GPPopulation.determineFittestChromosomes (final int a_numberOfPrograms) [inline]
Sorts the GPPrograms list and returns the fittest n GPPrograms in the population.
Parameters
a_numberOfPrograms number of top performer GPPrograms to be returned
Returns
list of the fittest n GPPrograms of the population, or the fittest x GPPrograms with x = number of GPPrograms in case n > x.
Author
Klaus Meffert
Since
3.0
Definition at line 743 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_changed, org.jgap.gp.impl.GPPopulation.m_programs, org.jgap.gp.impl.GPPopulation.m_sorted, and org.jgap.gp.impl.GPPopulation.sortByFitness().
IGPProgram org.jgap.gp.impl.GPPopulation.determineFittestProgram () [inline]
Determines the fittest GPProgram in the population (the one with the highest fitness value) and memorizes it. This is an optimized version compared to calling determineFittesPrograms(1).
Returns
the fittest GPProgram of the population
Author
Klaus Meffert
Since
3.0
Definition at line 657 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.DELTA, org.jgap.gp.impl.GPPopulation.getGPConfiguration(), org.jgap.gp.IGPFitnessEvaluator.isFitter(), org.jgap.gp.impl.GPPopulation.m_changed, org.jgap.gp.impl.GPPopulation.m_fittestProgram, org.jgap.gp.impl.GPPopulation.m_programs, org.jgap.IHandler.perform(), and org.jgap.gp.impl.GPPopulation.setChanged().
IGPProgram org.jgap.gp.impl.GPPopulation.determineFittestProgramComputed () [inline]
Determines the fittest GPProgram in the population, but only considers programs with already computed fitness value.
Returns
the fittest GPProgram of the population
Author
Klaus Meffert
Since
3.2
Definition at line 706 of file GPPopulation.java.
References org.jgap.FitnessFunction.DELTA, org.jgap.gp.impl.GPPopulation.getGPConfiguration(), org.jgap.gp.IGPFitnessEvaluator.isFitter(), org.jgap.gp.impl.GPPopulation.m_programs, and org.jgap.FitnessFunction.NO_FITNESS_VALUE.
String org.jgap.gp.impl.GPPopulation.encode (String a_string) [inline], [protected]
Definition at line 960 of file GPPopulation.java.
Referenced by org.jgap.gp.impl.GPPopulation.getPersistentRepresentation().
boolean org.jgap.gp.impl.GPPopulation.equals (Object a_pop) [inline]
The equals-method.
Parameters
a_pop the population instance to compare with
Returns
true: given object equal to comparing one
Author
Klaus Meffert
Since
3.0
Definition at line 887 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.compareTo().
Referenced by org.jgap.gp.impl.GPPopulation.containedInArray().
float org.jgap.gp.impl.GPPopulation.getFitnessRank (int a_index) [inline]
Definition at line 779 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_fitnessRank.
Referenced by org.jgap.gp.impl.FitnessProportionateSelection.select().
float [] org.jgap.gp.impl.GPPopulation.getFitnessRanks () [inline]
Definition at line 775 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_fitnessRank.
GPConfiguration org.jgap.gp.impl.GPPopulation.getGPConfiguration () [inline]
Returns
the GPConfiguration set
Author
Klaus Meffert
Since
3.0
Definition at line 544 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_config.
Referenced by org.jgap.gp.impl.GPGenotype.checkErroneousPop(), org.jgap.gp.impl.GPPopulation.create(), org.jgap.gp.impl.GPPopulation.determineFittestProgram(), org.jgap.gp.impl.GPPopulation.determineFittestProgramComputed(), and org.jgap.gp.impl.GPPopulation.sortByFitness().
IGPProgram org.jgap.gp.impl.GPPopulation.getGPProgram (int a_index) [inline]
Definition at line 566 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_programs.
Referenced by org.jgap.gp.impl.GPGenotype.calcFitness().
IGPProgram [] org.jgap.gp.impl.GPPopulation.getGPPrograms () [inline]
Definition at line 639 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_programs.
String org.jgap.gp.impl.GPPopulation.getPersistentRepresentation () [inline]
Returns
the persistent representation of the population, including all GP programs
Author
Klaus Meffert
Since
3.2.3
Definition at line 947 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.encode(), and org.jgap.gp.impl.GPPopulation.m_programs.
int org.jgap.gp.impl.GPPopulation.getPopSize () [inline]
Returns
fixed size of the population
Author
Klaus Meffert
Since
3.0
Definition at line 534 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_popSize.
Referenced by org.jgap.gp.impl.GPPopulationTest.testConstruct_0().
boolean org.jgap.gp.impl.GPPopulation.isChanged () [inline]
Returns
true: population's programs (maybe) were changed, false: not changed for sure
Since
3.0
Definition at line 803 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_changed.
boolean org.jgap.gp.impl.GPPopulation.isFirstEmpty () [inline]
Definition at line 930 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_programs, and org.jgap.gp.impl.GPPopulation.size().
void org.jgap.gp.impl.GPPopulation.setChanged (final boolean a_changed) [inline], [protected]
Mark that for the population the fittest program may have changed.
Parameters
a_changed true: population's fittest program may have changed, false: fittest program evaluated earlier is still valid
Author
Klaus Meffert
Since
3.0
Definition at line 792 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_changed, and org.jgap.gp.impl.GPPopulation.setSorted().
Referenced by org.jgap.gp.impl.GPPopulation.copyGPPrograms(), org.jgap.gp.impl.GPPopulation.create(), org.jgap.gp.impl.GPPopulation.determineFittestProgram(), org.jgap.gp.impl.GPPopulation.GPPopulation(), org.jgap.gp.impl.GPPopulation.setGPProgram(), org.jgap.gp.impl.GPPopulation.setGPPrograms(), and org.jgap.gp.impl.GPPopulation.sortByFitness().
void org.jgap.gp.impl.GPPopulation.setGPProgram (final int a_index, final IGPProgram a_program) [inline]
Sets the given GPProgram at the given index in the list of GPProgram's. If the given index is exceeding the list by one, the chromosome is appended.
Parameters
a_index the index to set the GPProgram in
a_program the GPProgram to be set
Author
Klaus Meffert
Since
3.0
Definition at line 559 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_programs, and org.jgap.gp.impl.GPPopulation.setChanged().
Referenced by org.jgap.gp.impl.GPPopulation.create().
void org.jgap.gp.impl.GPPopulation.setGPPrograms (final GPPopulation a_pop) [inline]
Sets the GPPrograms of the given population to this population.
Parameters
a_pop the population to use as template
Author
Klaus Meffert
Since
3.3.3
Definition at line 578 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_popSize, org.jgap.gp.impl.GPPopulation.m_programs, and org.jgap.gp.impl.GPPopulation.setChanged().
void org.jgap.gp.impl.GPPopulation.setGPPrograms (final IGPProgram[] a_progs) [inline]
Sets the GPPrograms of the given array to this population.
Parameters
a_progs the programs to set
Author
Klaus Meffert
Since
3.3.3
Definition at line 594 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_popSize, org.jgap.gp.impl.GPPopulation.m_programs, and org.jgap.gp.impl.GPPopulation.setChanged().
void org.jgap.gp.impl.GPPopulation.setGPPrograms (final List a_pop) [inline]
Sets the GPPrograms of the given population to this population.
Parameters
a_pop the population to use as template
Author
Klaus Meffert
Since
3.3.3
Definition at line 628 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_programs, org.jgap.gp.impl.GPPopulation.setChanged(), and org.jgap.gp.impl.GPPopulation.size().
void org.jgap.gp.impl.GPPopulation.setSorted (final boolean a_sorted) [inline], [protected]
Mark the population as sorted.
Parameters
a_sorted true: mark population as sorted
Author
Klaus Meffert
Since
3.0
Definition at line 814 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_sorted.
Referenced by org.jgap.gp.impl.GPPopulation.setChanged(), and org.jgap.gp.impl.GPPopulation.sortByFitness().
int org.jgap.gp.impl.GPPopulation.size () [inline]
Definition at line 643 of file GPPopulation.java.
Referenced by org.jgap.gp.impl.GPPopulation.compareTo(), org.jgap.gp.impl.GPPopulation.copyGPPrograms(), org.jgap.gp.impl.GPPopulation.isFirstEmpty(), org.jgap.gp.impl.GPPopulation.setGPPrograms(), and org.jgap.gp.impl.GPPopulationTest.testConstruct_0().
void org.jgap.gp.impl.GPPopulation.sort (Comparator c) [inline]
Sorts the population into `ascending` order using some criterion for `ascending`. A Comparator is given which will compare two individuals, and if one individual compares lower than another individual, the first individual will appear in the population before the second individual.
Parameters
c the Comparator to use
Author
Klaus Meffert
Since
3.0
Definition at line 169 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.m_fitnessRank, and org.jgap.gp.impl.GPPopulation.m_programs.
Referenced by org.jgap.gp.impl.GPPopulation.sortByFitness().
void org.jgap.gp.impl.GPPopulation.sortByFitness () [inline]
Sorts the programs within the population according to their fitness value using GPProgramFitnessComparator.
Author
Klaus Meffert
Since
3.0
Definition at line 764 of file GPPopulation.java.
References org.jgap.gp.impl.GPPopulation.getGPConfiguration(), org.jgap.gp.impl.GPPopulation.m_fittestProgram, org.jgap.gp.impl.GPPopulation.m_programs, org.jgap.gp.impl.GPPopulation.setChanged(), org.jgap.gp.impl.GPPopulation.setSorted(), and org.jgap.gp.impl.GPPopulation.sort().
Referenced by org.jgap.gp.impl.GPPopulation.determineFittestChromosomes().
Member Data Documentation
final String org.jgap.gp.impl.GPPopulation.CVS_REVISION = `$Revision: 1.43 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 29 of file GPPopulation.java.
final double org.jgap.gp.impl.GPPopulation.DELTA = 0.0000001d [static]
Definition at line 37 of file GPPopulation.java.
Referenced by org.jgap.gp.impl.GPPopulation.determineFittestProgram().
transient Logger org.jgap.gp.impl.GPPopulation.LOGGER = Logger.getLogger(GPPopulation.class) [private]
Definition at line 39 of file GPPopulation.java.
boolean org.jgap.gp.impl.GPPopulation.m_changed [private]
Indicates whether at least one of the programs has been changed (deleted, added, modified).
Definition at line 61 of file GPPopulation.java.
Referenced by org.jgap.gp.impl.GPPopulation.clear(), org.jgap.gp.impl.GPPopulation.determineFittestChromosomes(), org.jgap.gp.impl.GPPopulation.determineFittestProgram(), org.jgap.gp.impl.GPPopulation.GPPopulation(), org.jgap.gp.impl.GPPopulation.isChanged(), and org.jgap.gp.impl.GPPopulation.setChanged().
GPConfiguration org.jgap.gp.impl.GPPopulation.m_config [private]
Definition at line 55 of file GPPopulation.java.
Referenced by org.jgap.gp.impl.GPPopulation.getGPConfiguration(), and org.jgap.gp.impl.GPPopulation.GPPopulation().
float [] org.jgap.gp.impl.GPPopulation.m_fitnessRank [private]
Definition at line 49 of file GPPopulation.java.
Referenced by org.jgap.gp.impl.GPPopulation.getFitnessRank(), org.jgap.gp.impl.GPPopulation.getFitnessRanks(), org.jgap.gp.impl.GPPopulation.GPPopulation(), and org.jgap.gp.impl.GPPopulation.sort().
transient IGPProgram org.jgap.gp.impl.GPPopulation.m_fittestProgram [private]
Definition at line 53 of file GPPopulation.java.
Referenced by org.jgap.gp.impl.GPPopulation.clear(), org.jgap.gp.impl.GPPopulation.determineFittestProgram(), org.jgap.gp.impl.GPPopulation.GPPopulation(), and org.jgap.gp.impl.GPPopulation.sortByFitness().
IGPProgram org.jgap.gp.impl.GPPopulation.m_fittestToAdd [private]
Definition at line 68 of file GPPopulation.java.
Referenced by org.jgap.gp.impl.GPPopulation.addFittestProgram(), and org.jgap.gp.impl.GPPopulation.create().
int org.jgap.gp.impl.GPPopulation.m_popSize [private]
Definition at line 51 of file GPPopulation.java.
Referenced by org.jgap.gp.impl.GPPopulation.create(), org.jgap.gp.impl.GPPopulation.getPopSize(), org.jgap.gp.impl.GPPopulation.GPPopulation(), and org.jgap.gp.impl.GPPopulation.setGPPrograms().
IGPProgram [] org.jgap.gp.impl.GPPopulation.m_programs [private]
The array of GPProgram's that make-up the Genotype's population.
Definition at line 46 of file GPPopulation.java.
Referenced by org.jgap.gp.impl.GPPopulation.clear(), org.jgap.gp.impl.GPPopulation.compareTo(), org.jgap.gp.impl.GPPopulation.copyGPPrograms(), org.jgap.gp.impl.GPPopulation.determineFittestChromosomes(), org.jgap.gp.impl.GPPopulation.determineFittestProgram(), org.jgap.gp.impl.GPPopulation.determineFittestProgramComputed(), org.jgap.gp.impl.GPPopulation.getGPProgram(), org.jgap.gp.impl.GPPopulation.getGPPrograms(), org.jgap.gp.impl.GPPopulation.getPersistentRepresentation(), org.jgap.gp.impl.GPPopulation.GPPopulation(), org.jgap.gp.impl.GPPopulation.isFirstEmpty(), org.jgap.gp.impl.GPPopulation.setGPProgram(), org.jgap.gp.impl.GPPopulation.setGPPrograms(), org.jgap.gp.impl.GPPopulation.sort(), and org.jgap.gp.impl.GPPopulation.sortByFitness().
boolean org.jgap.gp.impl.GPPopulation.m_sorted [private]
Indicates that the list of GPPrograms has been sorted.
Definition at line 66 of file GPPopulation.java.
Referenced by org.jgap.gp.impl.GPPopulation.clear(), org.jgap.gp.impl.GPPopulation.determineFittestChromosomes(), org.jgap.gp.impl.GPPopulation.GPPopulation(), and org.jgap.gp.impl.GPPopulation.setSorted().
transient int org.jgap.gp.impl.GPPopulation.warningPrototypeReused = 0 [private]
Definition at line 41 of file GPPopulation.java.
Referenced by org.jgap.gp.impl.GPPopulation.create().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/impl/GPPopulation.java