org.jgap.audit.KeyedValue Class Reference
Public Member Functions
KeyedValue (final Comparable a_key, final Number a_value)
Comparable getKey ()
synchronized Number getValue ()
synchronized void setValue (final Number a_value)
boolean equals (final Object a_object)
int hashCode ()
Object clone ()
Private Attributes
Comparable m_key
Number m_value
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.5 $`
Additional Inherited Members
Detailed Description
A (key, value) tupel.
Author
Klaus Meffert
Since
2.3
Definition at line 22 of file KeyedValue.java.
Constructor & Destructor Documentation
org.jgap.audit.KeyedValue.KeyedValue (final Comparable a_key, final Number a_value) [inline]
Creates a new (key, value) tupel.
Parameters
a_key the key
a_value the value, could be null
Author
Klaus Meffert
Since
2.3
Definition at line 40 of file KeyedValue.java.
References org.jgap.audit.KeyedValue.m_key, and org.jgap.audit.KeyedValue.m_value.
Referenced by org.jgap.audit.KeyedValue.clone(), and org.jgap.audit.KeyedValue.equals().
Member Function Documentation
Object org.jgap.audit.KeyedValue.clone () [inline]
Returns
clone of the current instance
Author
Klaus Meffert
Since
2.3
Implements org.jgap.util.ICloneable.
Definition at line 136 of file KeyedValue.java.
References org.jgap.audit.KeyedValue.KeyedValue().
Referenced by org.jgap.audit.KeyedValueTest.testClone_0().
boolean org.jgap.audit.KeyedValue.equals (final Object a_object) [inline]
Tests if this object is equal to another.
Parameters
a_object the other object
Returns
true: this object is equal to other one
Author
Klaus Meffert
Since
2.3
Definition at line 87 of file KeyedValue.java.
References org.jgap.audit.KeyedValue.KeyedValue(), org.jgap.audit.KeyedValue.m_key, and org.jgap.audit.KeyedValue.m_value.
Referenced by org.jgap.audit.KeyedValueTest.testEquals_0(), org.jgap.audit.KeyedValueTest.testEquals_1(), and org.jgap.audit.KeyedValueTest.testEquals_2().
Comparable org.jgap.audit.KeyedValue.getKey () [inline]
Returns
key of the tupel
Author
Klaus Meffert
Since
2.3
Definition at line 51 of file KeyedValue.java.
References org.jgap.audit.KeyedValue.m_key.
Referenced by org.jgap.audit.KeyedValues.getIndex(), org.jgap.audit.KeyedValueTest.testClone_0(), org.jgap.audit.KeyedValueTest.testConstruct_0(), org.jgap.audit.KeyedValueTest.testConstruct_1(), and org.jgap.audit.KeyedValueTest.testConstruct_2().
synchronized Number org.jgap.audit.KeyedValue.getValue () [inline]
Returns
value of the tupel
Author
Klaus Meffert
Since
2.3
Definition at line 61 of file KeyedValue.java.
References org.jgap.audit.KeyedValue.m_value.
Referenced by org.jgap.audit.KeyedValueTest.testClone_0(), org.jgap.audit.KeyedValueTest.testConstruct_0(), org.jgap.audit.KeyedValueTest.testConstruct_1(), and org.jgap.audit.KeyedValueTest.testConstruct_2().
int org.jgap.audit.KeyedValue.hashCode () [inline]
Returns
hash code of the instance
Author
Klaus Meffert
Since
2.3
Definition at line 112 of file KeyedValue.java.
References org.jgap.audit.KeyedValue.m_key, and org.jgap.audit.KeyedValue.m_value.
Referenced by org.jgap.audit.KeyedValueTest.testConstruct_2(), and org.jgap.audit.KeyedValueTest.testHashcode_0().
synchronized void org.jgap.audit.KeyedValue.setValue (final Number a_value) [inline]
Sets the value for the key
Parameters
a_value the value to set for the key
Author
Klaus Meffert
Since
2.3
Definition at line 73 of file KeyedValue.java.
References org.jgap.audit.KeyedValue.m_value.
Member Data Documentation
final String org.jgap.audit.KeyedValue.CVS_REVISION = `$Revision: 1.5 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file KeyedValue.java.
Comparable org.jgap.audit.KeyedValue.m_key [private]
Definition at line 27 of file KeyedValue.java.
Referenced by org.jgap.audit.KeyedValue.equals(), org.jgap.audit.KeyedValue.getKey(), org.jgap.audit.KeyedValue.hashCode(), and org.jgap.audit.KeyedValue.KeyedValue().
Number org.jgap.audit.KeyedValue.m_value [private]
Definition at line 29 of file KeyedValue.java.
Referenced by org.jgap.audit.KeyedValue.equals(), org.jgap.audit.KeyedValue.getValue(), org.jgap.audit.KeyedValue.hashCode(), org.jgap.audit.KeyedValue.KeyedValue(), and org.jgap.audit.KeyedValue.setValue().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/audit/KeyedValue.java