org.jgap.data.DataTreeBuilder Class Reference
Public Member Functions
IDataCreators representGenotypeAsDocument (final Genotype a_subject) throws Exception
IDataElement representGenotypeAsElement (final Genotype a_subject) throws Exception
IDataCreators representChromosomeAsDocument (final IChromosome a_subject) throws Exception
IDataElement representChromosomeAsElement (final IChromosome a_subject) throws Exception
IDataElement representGenesAsElement (final Gene[] a_geneValues) throws Exception
IDataElement representGeneAsElement (final Gene a_gene) throws Exception
Static Public Member Functions
static synchronized DataTreeBuilder getInstance ()
Protected Member Functions
IDataElementList createTree ()
Private Member Functions
DataTreeBuilder ()
IDataElement representAlleleAsElement (final Gene a_gene) throws Exception
Private Attributes
Object m_lock
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.12 $`
static final String GENOTYPE_TAG = `genotype`
static final String CHROMOSOME_TAG = `chromosome`
static final String GENES_TAG = `genes`
static final String GENE_TAG = `gene`
static final String ALLELE_TAG = `allele`
static final String SIZE_ATTRIBUTE = `size`
static final String CLASS_ATTRIBUTE = `class`
static DataTreeBuilder m_instance
Detailed Description
Builds a tree structure from Genes, Chrosomes or from a Genotype.
Generated result is generic data type usable for concrete persistence strategies, including XML documents, writing an object to a file or stream etc.
Author
Klaus Meffert
Since
2.0
Definition at line 24 of file DataTreeBuilder.java.
Constructor & Destructor Documentation
org.jgap.data.DataTreeBuilder.DataTreeBuilder () [inline], [private]
Private constructor for Singleton
Definition at line 88 of file DataTreeBuilder.java.
Referenced by org.jgap.data.DataTreeBuilder.getInstance().
Member Function Documentation
IDataElementList org.jgap.data.DataTreeBuilder.createTree () [inline], [protected]
Definition at line 181 of file DataTreeBuilder.java.
Referenced by org.jgap.data.DataTreeBuilder.representChromosomeAsDocument(), and org.jgap.data.DataTreeBuilder.representGenotypeAsDocument().
static synchronized DataTreeBuilder org.jgap.data.DataTreeBuilder.getInstance () [inline], [static]
Returns
the singleton instance of this class
Author
Klaus Meffert
Since
2.0
Definition at line 77 of file DataTreeBuilder.java.
References org.jgap.data.DataTreeBuilder.DataTreeBuilder(), and org.jgap.data.DataTreeBuilder.m_instance.
IDataElement org.jgap.data.DataTreeBuilder.representAlleleAsElement (final Gene a_gene) throws Exception [inline], [private]
Represent an Allele as a generic data element
Parameters
a_gene the gene holding the allele
Exceptions
Exception
Returns
IDataElement created data element
Author
Klaus Meffert
Since
2.0
Definition at line 281 of file DataTreeBuilder.java.
References org.jgap.data.DataTreeBuilder.ALLELE_TAG.
Referenced by org.jgap.data.DataTreeBuilder.representGeneAsElement().
IDataCreators org.jgap.data.DataTreeBuilder.representChromosomeAsDocument (final IChromosome a_subject) throws Exception [inline]
Represent a Chromosome as a generic data type document, including its contained Gene instances.
Parameters
a_subject the chromosome to represent
Exceptions
Exception
Returns
a document object representing the given Chromosome
Author
Klaus Meffert
Since
2.0
Definition at line 164 of file DataTreeBuilder.java.
References org.jgap.data.DataTreeBuilder.createTree(), org.jgap.data.DataTreeBuilder.m_lock, and org.jgap.data.DataTreeBuilder.representChromosomeAsElement().
IDataElement org.jgap.data.DataTreeBuilder.representChromosomeAsElement (final IChromosome a_subject) throws Exception [inline]
Represent a Chromosome as a generic data element, including its contained Gene instances. This may be useful in scenarios where representation as an entire document is undesirable, such as when the representation of this Chromosome is to be combined with other elements in a single document.
Parameters
a_subject the chromosome to represent
Exceptions
Exception
Returns
an element object representing the given Chromosome
Author
Klaus Meffert
Since
2.0
Definition at line 199 of file DataTreeBuilder.java.
References org.jgap.data.DataTreeBuilder.CHROMOSOME_TAG, org.jgap.data.DataTreeBuilder.representGenesAsElement(), and org.jgap.data.DataTreeBuilder.SIZE_ATTRIBUTE.
Referenced by org.jgap.data.DataTreeBuilder.representChromosomeAsDocument(), and org.jgap.data.DataTreeBuilder.representGenotypeAsElement().
IDataElement org.jgap.data.DataTreeBuilder.representGeneAsElement (final Gene a_gene) throws Exception [inline]
Represent a Gene as a generic data element.
Parameters
a_gene the Gene to represent
Exceptions
Exception
Returns
an element object representing the given gene
Author
Klaus Meffert
Since
2.0
Definition at line 254 of file DataTreeBuilder.java.
References org.jgap.data.DataTreeBuilder.CLASS_ATTRIBUTE, org.jgap.data.DataTreeBuilder.GENE_TAG, and org.jgap.data.DataTreeBuilder.representAlleleAsElement().
Referenced by org.jgap.data.DataTreeBuilder.representGenesAsElement().
IDataElement org.jgap.data.DataTreeBuilder.representGenesAsElement (final Gene[] a_geneValues) throws Exception [inline]
Represent Genes as a generic data type element.
Parameters
a_geneValues the genes to represent
Exceptions
Exception
Returns
an element object representing the given genes
Author
Klaus Meffert
Since
2.0
Definition at line 229 of file DataTreeBuilder.java.
References org.jgap.data.DataTreeBuilder.GENES_TAG, and org.jgap.data.DataTreeBuilder.representGeneAsElement().
Referenced by org.jgap.data.DataTreeBuilder.representChromosomeAsElement().
IDataCreators org.jgap.data.DataTreeBuilder.representGenotypeAsDocument (final Genotype a_subject) throws Exception [inline]
Represent a Genotype as a generic data document, including its population of Chromosome instances.
Parameters
a_subject the genotype to represent
Exceptions
Exception
Returns
a generic document object representing the given Genotype
Author
Klaus Meffert
Since
2.0
Definition at line 102 of file DataTreeBuilder.java.
References org.jgap.data.DataTreeBuilder.createTree(), org.jgap.data.DataTreeBuilder.m_lock, and org.jgap.data.DataTreeBuilder.representGenotypeAsElement().
IDataElement org.jgap.data.DataTreeBuilder.representGenotypeAsElement (final Genotype a_subject) throws Exception [inline]
Represent a Genotype as a generic data element, including its population of Chromosome instances.
This may be useful in scenarios where representation as an entire document is undesirable, such as when the representation of this Genotype is to be combined with other elements in a single document.
Parameters
a_subject the genotype to represent
Exceptions
Exception
Returns
an element object representing the given Genotype
Author
Klaus Meffert
Since
2.0
Definition at line 132 of file DataTreeBuilder.java.
References org.jgap.data.DataTreeBuilder.GENOTYPE_TAG, org.jgap.Population.getChromosome(), org.jgap.data.DataTreeBuilder.representChromosomeAsElement(), and org.jgap.data.DataTreeBuilder.SIZE_ATTRIBUTE.
Referenced by org.jgap.data.DataTreeBuilder.representGenotypeAsDocument().
Member Data Documentation
final String org.jgap.data.DataTreeBuilder.ALLELE_TAG = `allele` [static], [private]
Definition at line 50 of file DataTreeBuilder.java.
Referenced by org.jgap.data.DataTreeBuilder.representAlleleAsElement().
final String org.jgap.data.DataTreeBuilder.CHROMOSOME_TAG = `chromosome` [static], [private]
Constant representing the name of the chromosome element tag.
Definition at line 38 of file DataTreeBuilder.java.
Referenced by org.jgap.data.DataTreeBuilder.representChromosomeAsElement().
final String org.jgap.data.DataTreeBuilder.CLASS_ATTRIBUTE = `class` [static], [private]
Constant representing the fully-qualified name of the concrete Gene class that was marshalled.
Definition at line 62 of file DataTreeBuilder.java.
Referenced by org.jgap.data.DataTreeBuilder.representGeneAsElement().
final String org.jgap.data.DataTreeBuilder.CVS_REVISION = `$Revision: 1.12 $` [static], [private]
Todo
Todo implement representGPGenotype..
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file DataTreeBuilder.java.
final String org.jgap.data.DataTreeBuilder.GENE_TAG = `gene` [static], [private]
Constant representing the name of the gene element tag.
Definition at line 48 of file DataTreeBuilder.java.
Referenced by org.jgap.data.DataTreeBuilder.representGeneAsElement().
final String org.jgap.data.DataTreeBuilder.GENES_TAG = `genes` [static], [private]
Constant representing the name of the gene element tag.
Definition at line 43 of file DataTreeBuilder.java.
Referenced by org.jgap.data.DataTreeBuilder.representGenesAsElement().
final String org.jgap.data.DataTreeBuilder.GENOTYPE_TAG = `genotype` [static], [private]
Constant representing the name of the genotype element tag.
Definition at line 33 of file DataTreeBuilder.java.
Referenced by org.jgap.data.DataTreeBuilder.representGenotypeAsElement().
DataTreeBuilder org.jgap.data.DataTreeBuilder.m_instance [static], [private]
Definition at line 69 of file DataTreeBuilder.java.
Referenced by org.jgap.data.DataTreeBuilder.getInstance().
Object org.jgap.data.DataTreeBuilder.m_lock [private]
Shared lock object used for synchronization purposes.
Definition at line 67 of file DataTreeBuilder.java.
Referenced by org.jgap.data.DataTreeBuilder.representChromosomeAsDocument(), and org.jgap.data.DataTreeBuilder.representGenotypeAsDocument().
final String org.jgap.data.DataTreeBuilder.SIZE_ATTRIBUTE = `size` [static], [private]
Constant representing the name of the size attribute that is added to genotype and chromosome elements to describe their size.
Definition at line 56 of file DataTreeBuilder.java.
Referenced by org.jgap.data.DataTreeBuilder.representChromosomeAsElement(), and org.jgap.data.DataTreeBuilder.representGenotypeAsElement().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/data/DataTreeBuilder.java