org.jgap.audit.Evaluator Class Reference
Classes
class ChromosomeData
class GenotypeData
class GenotypeDataAvg
Public Member Functions
Evaluator (final PermutingConfiguration a_conf)
boolean hasNext ()
Configuration next () throws InvalidConfigurationException
void setValue (double a_value, Comparable a_rowKey, Comparable a_columnKey)
Number getValue (Comparable rowKey, Comparable columnKey)
void setValue (int a_permutation, int a_run, double a_value, Comparable a_rowKey, Comparable a_columnKey)
Number getValue (int a_permutation, int a_run, Comparable rowKey, Comparable columnKey)
KeyedValues2D getData ()
KeyedValues2D calcAvgFitness (int a_permutation)
KeyedValues2D calcAvgFitnessImpr (int a_permutation)
int getNumberOfRuns (int a_permutation)
void storeGenotype (int a_permutation, int a_run, Genotype a_genotype)
void storePopulation (int a_permutation, int a_run, Population a_pop)
GenotypeData retrieveGenotype (int a_permutation, int a_run)
GenotypeDataAvg calcPerformance (int a_permutation)
List< GenotypeDataAvg > getGenotypeAverageData ()
Protected Member Functions
void addRunNumber (int a_permutation, int a_run)
Object createKey (int a_permutation, int a_run)
void calcAvgFitnessHelper (int a_permutation, final KeyedValues2D result)
Private Attributes
Map< Object, KeyedValues2D > m_permutationData
Map< Integer, Map > m_permutationRuns
KeyedValues2D m_data
PermutingConfiguration m_permConf
Map< String, GenotypeData > m_genotypeData
List< GenotypeDataAvg > m_genotypeDataAvg
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.12 $`
Detailed Description
Gathers statistical data and returns them on request.
Author
Klaus Meffert
Since
2.2
Definition at line 22 of file Evaluator.java.
Constructor & Destructor Documentation
org.jgap.audit.Evaluator.Evaluator (final PermutingConfiguration a_conf) [inline]
Definition at line 58 of file Evaluator.java.
References org.jgap.audit.Evaluator.m_data, org.jgap.audit.Evaluator.m_genotypeData, org.jgap.audit.Evaluator.m_genotypeDataAvg, org.jgap.audit.Evaluator.m_permConf, org.jgap.audit.Evaluator.m_permutationData, and org.jgap.audit.Evaluator.m_permutationRuns.
Member Function Documentation
void org.jgap.audit.Evaluator.addRunNumber (int a_permutation, int a_run) [inline], [protected]
Definition at line 116 of file Evaluator.java.
Referenced by org.jgap.audit.Evaluator.setValue(), and org.jgap.audit.Evaluator.storePopulation().
KeyedValues2D org.jgap.audit.Evaluator.calcAvgFitness (int a_permutation) [inline]
Calculates the average fitness value curve for a given permutation. If permutation -1 is given, a composition of all permutations available is created.
Parameters
a_permutation -1 to use all permutations
Returns
DefaultKeyedValues2D list of fitness values, one for each individual in the generation
Author
Klaus Meffert
Since
2.2
Definition at line 153 of file Evaluator.java.
References org.jgap.audit.Evaluator.calcAvgFitnessHelper().
void org.jgap.audit.Evaluator.calcAvgFitnessHelper (int a_permutation, final KeyedValues2D result) [inline], [protected]
Definition at line 173 of file Evaluator.java.
References org.jgap.audit.Evaluator.createKey(), org.jgap.audit.KeyedValues2D.getColumnKey(), org.jgap.audit.KeyedValues2D.getRowKey(), and org.jgap.audit.KeyedValues2D.getValue().
Referenced by org.jgap.audit.Evaluator.calcAvgFitness().
KeyedValues2D org.jgap.audit.Evaluator.calcAvgFitnessImpr (int a_permutation) [inline]
Returns a list of lists (i.e. a matrix) to use for output as a table
Parameters
a_data DefaultKeyedValues2D
Returns
List
Todo
Todo implement
Calculates average fitness value improvement per generation.
Parameters
a_permutation int
Returns
DefaultKeyedValues2D
Author
Klaus Meffert
Since
2.2
Todo
Todo implement
Todo
Todo is this method used resp. contained in calcPerformance?
Definition at line 242 of file Evaluator.java.
References org.jgap.audit.Evaluator.createKey().
GenotypeDataAvg org.jgap.audit.Evaluator.calcPerformance (int a_permutation) [inline]
Calculates performance metrics for a given permutation and run stored before with storeGenotype, like: average fitness, maximum fitness...
Parameters
a_permutation the permutation to compute the performance metrics for
Returns
computed statistical data
Author
Klaus Meffert
Since
2.2
Definition at line 351 of file Evaluator.java.
References org.jgap.audit.Evaluator.getNumberOfRuns(), org.jgap.audit.Evaluator.retrieveGenotype(), and org.jgap.audit.Evaluator.GenotypeData.size.
Object org.jgap.audit.Evaluator.createKey (int a_permutation, int a_run) [inline], [protected]
Definition at line 138 of file Evaluator.java.
Referenced by org.jgap.audit.Evaluator.calcAvgFitnessHelper(), org.jgap.audit.Evaluator.calcAvgFitnessImpr(), org.jgap.audit.Evaluator.getValue(), and org.jgap.audit.Evaluator.setValue().
KeyedValues2D org.jgap.audit.Evaluator.getData () [inline]
Definition at line 134 of file Evaluator.java.
References org.jgap.audit.Evaluator.m_data.
Referenced by org.jgap.audit.EvaluatorTest.testConstruct_1().
List<GenotypeDataAvg> org.jgap.audit.Evaluator.getGenotypeAverageData () [inline]
Returns
Averaged genotype data
Author
Klaus Meffert
Since
3.5
Definition at line 477 of file Evaluator.java.
References org.jgap.audit.Evaluator.m_genotypeDataAvg.
int org.jgap.audit.Evaluator.getNumberOfRuns (int a_permutation) [inline]
Parameters
a_permutation the permutation to determine the number of runs for
Returns
the number of runs for the given permutation
Definition at line 274 of file Evaluator.java.
Referenced by org.jgap.audit.Evaluator.calcPerformance(), and org.jgap.audit.EvaluatorTest.testGetNumberOfRuns_0().
Number org.jgap.audit.Evaluator.getValue (Comparable rowKey, Comparable columnKey) [inline]
Definition at line 86 of file Evaluator.java.
Referenced by org.jgap.audit.EvaluatorTest.testSetValue_0(), org.jgap.audit.EvaluatorTest.testSetValue_1(), org.jgap.audit.EvaluatorTest.testSetValue_2(), and org.jgap.audit.EvaluatorTest.testSetValue_3().
Number org.jgap.audit.Evaluator.getValue (int a_permutation, int a_run, Comparable rowKey, Comparable columnKey) [inline]
Definition at line 125 of file Evaluator.java.
References org.jgap.audit.Evaluator.createKey().
boolean org.jgap.audit.Evaluator.hasNext () [inline]
Definition at line 71 of file Evaluator.java.
Configuration org.jgap.audit.Evaluator.next () throws InvalidConfigurationException [inline]
Definition at line 75 of file Evaluator.java.
GenotypeData org.jgap.audit.Evaluator.retrieveGenotype (int a_permutation, int a_run) [inline]
Definition at line 336 of file Evaluator.java.
Referenced by org.jgap.audit.Evaluator.calcPerformance().
void org.jgap.audit.Evaluator.setValue (double a_value, Comparable a_rowKey, Comparable a_columnKey) [inline]
Definition at line 80 of file Evaluator.java.
void org.jgap.audit.Evaluator.setValue (int a_permutation, int a_run, double a_value, Comparable a_rowKey, Comparable a_columnKey) [inline]
Sets a specific value.
Parameters
a_permutation int
a_run int
a_value double
a_rowKey Comparable
a_columnKey Comparable
Author
Klaus Meffert
Since
2.2
Definition at line 102 of file Evaluator.java.
References org.jgap.audit.Evaluator.addRunNumber(), and org.jgap.audit.Evaluator.createKey().
void org.jgap.audit.Evaluator.storeGenotype (int a_permutation, int a_run, Genotype a_genotype) [inline]
Stores information contained in the given genotype.
Parameters
a_permutation int
a_run index of the run proceeded for the given genotype
a_genotype the genotype holding the population of chromosomes
Author
Klaus Meffert
Since
2.2
Definition at line 293 of file Evaluator.java.
References org.jgap.Genotype.getPopulation(), and org.jgap.audit.Evaluator.storePopulation().
void org.jgap.audit.Evaluator.storePopulation (int a_permutation, int a_run, Population a_pop) [inline]
Stores information contained in the given genotype.
Parameters
a_permutation int
a_run index of the run proceeded for the given genotype
a_pop the population holding the relevant chromosomes
Author
Klaus Meffert
Since
3.5 (originally named storeGenotype)
Todo
Todo implement
Definition at line 307 of file Evaluator.java.
References org.jgap.audit.Evaluator.addRunNumber().
Referenced by org.jgap.audit.Evaluator.storeGenotype().
Member Data Documentation
final String org.jgap.audit.Evaluator.CVS_REVISION = `$Revision: 1.12 $` [static], [private]
Todo
Todo implement: overall score calculation (out of best/avg. fitness value etc.)
String containing the CVS revision. Read out via reflection!
Definition at line 29 of file Evaluator.java.
KeyedValues2D org.jgap.audit.Evaluator.m_data [private]
For processinf without permutation
Definition at line 44 of file Evaluator.java.
Referenced by org.jgap.audit.Evaluator.Evaluator(), and org.jgap.audit.Evaluator.getData().
Map<String, GenotypeData> org.jgap.audit.Evaluator.m_genotypeData [private]
Genotype data per permutation per run
Definition at line 51 of file Evaluator.java.
Referenced by org.jgap.audit.Evaluator.Evaluator().
List<GenotypeDataAvg> org.jgap.audit.Evaluator.m_genotypeDataAvg [private]
Genotype data per permutation (averaged over all runs)
Definition at line 56 of file Evaluator.java.
Referenced by org.jgap.audit.Evaluator.Evaluator(), and org.jgap.audit.Evaluator.getGenotypeAverageData().
PermutingConfiguration org.jgap.audit.Evaluator.m_permConf [private]
Definition at line 46 of file Evaluator.java.
Referenced by org.jgap.audit.Evaluator.Evaluator().
Map<Object, KeyedValues2D> org.jgap.audit.Evaluator.m_permutationData [private]
Each data has its own data container
Definition at line 34 of file Evaluator.java.
Referenced by org.jgap.audit.Evaluator.Evaluator().
Map<Integer, Map> org.jgap.audit.Evaluator.m_permutationRuns [private]
Stores the run-numbers (indexes) for all permutations submitted
Definition at line 39 of file Evaluator.java.
Referenced by org.jgap.audit.Evaluator.Evaluator().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/audit/Evaluator.java