org.jgap.xml.XMLManager Class Reference
Static Public Member Functions
static Document representChromosomeAsDocument (final IChromosome a_subject)
static Document representGenotypeAsDocument (final Genotype a_subject)
static Element representGenesAsElement (final Gene[] a_geneValues, final Document a_xmlDocument)
static Element representChromosomeAsElement (final IChromosome a_subject, final Document a_xmlDocument)
static Element representGenotypeAsElement (final Genotype a_subject, final Document a_xmlDocument)
static Gene[] getGenesFromElement (Configuration a_activeConfiguration, Element a_xmlElement) throws ImproperXMLException, UnsupportedRepresentationException, GeneCreationException
static Chromosome getChromosomeFromElement (Configuration a_activeConfiguration, Element a_xmlElement) throws ImproperXMLException, InvalidConfigurationException, UnsupportedRepresentationException, GeneCreationException
static Genotype getGenotypeFromElement (Configuration a_activeConfiguration, Element a_xmlElement) throws ImproperXMLException, InvalidConfigurationException, UnsupportedRepresentationException, GeneCreationException
static Genotype getGenotypeFromDocument (Configuration a_activeConfiguration, Document a_xmlDocument) throws ImproperXMLException, InvalidConfigurationException, UnsupportedRepresentationException, GeneCreationException
static Chromosome getChromosomeFromDocument (Configuration a_activeConfiguration, Document a_xmlDocument) throws ImproperXMLException, InvalidConfigurationException, UnsupportedRepresentationException, GeneCreationException
static Document readFile (File file) throws IOException, org.xml.sax.SAXException
static void writeFile (Document doc, File file) throws IOException
Private Member Functions
XMLManager ()
Static Private Member Functions
static Element representAlleleAsElement (final Gene a_gene, final Document a_xmlDocument)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.21 $`
static final String GENOTYPE_TAG = `genotype`
static final String CHROMOSOME_TAG = `chromosome`
static final String GENES_TAG = `genes`
static final String GENE_TAG = `gene`
static final String ALLELE_TAG = `allele`
static final String SIZE_ATTRIBUTE = `size`
static final String CLASS_ATTRIBUTE = `class`
static final DocumentBuilder m_documentCreator
static final Object m_lock = new Object()
Detailed Description
The XMLManager performs marshalling of genetic entity instances (such as Chromosomes and Genotypes) to XML representations of those entities, as well as unmarshalling. All of the methods in this class are static, so no construction is required (or allowed).
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 33 of file XMLManager.java.
Constructor & Destructor Documentation
org.jgap.xml.XMLManager.XMLManager () [inline], [private]
Private constructor. All methods in this class are static, so no construction is allowed.
Definition at line 101 of file XMLManager.java.
Member Function Documentation
static Chromosome org.jgap.xml.XMLManager.getChromosomeFromDocument (Configuration a_activeConfiguration, Document a_xmlDocument) throws ImproperXMLException, InvalidConfigurationException, UnsupportedRepresentationException, GeneCreationException [inline], [static]
Unmarshall a Chromosome instance from a given XML Document representation. Its genes will be unmarshalled from the gene sub-elements.
Parameters
a_activeConfiguration the current active Configuration object that is to be used during construction of the Chromosome instances
a_xmlDocument the XML Document representation of the Chromosome
Returns
a new Chromosome instance setup with the data from the XML Document representation
Exceptions
ImproperXMLException if the given Document is improperly structured or missing data
InvalidConfigurationException if the given Configuration is in an inconsistent state
UnsupportedRepresentationException if the actively configured Gene implementation does not support the string representation of the alleles used in the given XML document
GeneCreationException if there is a problem creating or populating a Gene instance
Author
Neil Rotstan
Since
1.0
Definition at line 594 of file XMLManager.java.
static Chromosome org.jgap.xml.XMLManager.getChromosomeFromElement (Configuration a_activeConfiguration, Element a_xmlElement) throws ImproperXMLException, InvalidConfigurationException, UnsupportedRepresentationException, GeneCreationException [inline], [static]
Unmarshall a Chromosome instance from a given XML Element representation.
Parameters
a_activeConfiguration the current active Configuration object that is to be used during construction of the Chromosome
a_xmlElement the XML Element representation of the Chromosome
Returns
a new Chromosome instance setup with the data from the XML Element representation
Exceptions
ImproperXMLException if the given Element is improperly structured or missing data
InvalidConfigurationException if the given Configuration is in an inconsistent state
UnsupportedRepresentationException if the actively configured Gene implementation does not support the string representation of the alleles used in the given XML document
GeneCreationException if there is a problem creating or populating a Gene instance
Author
Neil Rotstan
Since
1.0
Definition at line 439 of file XMLManager.java.
static Gene [] org.jgap.xml.XMLManager.getGenesFromElement (Configuration a_activeConfiguration, Element a_xmlElement) throws ImproperXMLException, UnsupportedRepresentationException, GeneCreationException [inline], [static]
Unmarshall a Chromosome instance from a given XML Element representation.
Parameters
a_activeConfiguration current Configuration object
a_xmlElement the XML Element representation of the Chromosome
Returns
a new Chromosome instance setup with the data from the XML Element representation
Exceptions
ImproperXMLException if the given Element is improperly structured or missing data
UnsupportedRepresentationException if the actively configured Gene implementation does not support the string representation of the alleles used in the given XML document
GeneCreationException if there is a problem creating or populating a Gene instance
Author
Neil Rotstan
Since
1.0
Definition at line 316 of file XMLManager.java.
References org.jgap.xml.XMLManager.CLASS_ATTRIBUTE, org.jgap.xml.XMLManager.GENE_TAG, and org.jgap.xml.XMLManager.GENES_TAG.
static Genotype org.jgap.xml.XMLManager.getGenotypeFromDocument (Configuration a_activeConfiguration, Document a_xmlDocument) throws ImproperXMLException, InvalidConfigurationException, UnsupportedRepresentationException, GeneCreationException [inline], [static]
Unmarshall a Genotype instance from a given XML Document representation. Its population of Chromosomes will be unmarshalled from the Chromosome sub-elements.
Parameters
a_activeConfiguration the current active Configuration object that is to be used during construction of the Genotype and Chromosome instances
a_xmlDocument the XML Document representation of the Genotype
Returns
A new Genotype instance, complete with a population of Chromosomes, setup with the data from the XML Document representation
Exceptions
ImproperXMLException if the given Document is improperly structured or missing data
InvalidConfigurationException if the given Configuration is in an inconsistent state
UnsupportedRepresentationException if the actively configured Gene implementation does not support the string representation of the alleles used in the given XML document
GeneCreationException if there is a problem creating or populating a Gene instance
Author
Neil Rotstan
Since
1.0
Definition at line 550 of file XMLManager.java.
static Genotype org.jgap.xml.XMLManager.getGenotypeFromElement (Configuration a_activeConfiguration, Element a_xmlElement) throws ImproperXMLException, InvalidConfigurationException, UnsupportedRepresentationException, GeneCreationException [inline], [static]
Unmarshall a Genotype instance from a given XML Element representation. Its population of Chromosomes will be unmarshalled from the Chromosome sub-elements.
Parameters
a_activeConfiguration the current active Configuration object that is to be used during construction of the Genotype and Chromosome instances
a_xmlElement the XML Element representation of the Genotype
Returns
a new Genotype instance, complete with a population of Chromosomes, setup with the data from the XML Element representation
Exceptions
ImproperXMLException if the given Element is improperly structured or missing data
InvalidConfigurationException if the given Configuration is in an inconsistent state
UnsupportedRepresentationException if the actively configured Gene implementation does not support the string representation of the alleles used in the given XML document
GeneCreationException if there is a problem creating or populating a Gene instance
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 496 of file XMLManager.java.
static Document org.jgap.xml.XMLManager.readFile (File file) throws IOException, org.xml.sax.SAXException [inline], [static]
Reads in an XML file and returns a Document object.
Parameters
file the file to be read in
Exceptions
IOException
SAXException
Returns
Document
Author
Klaus Meffert
Since
2.0
Definition at line 624 of file XMLManager.java.
static Element org.jgap.xml.XMLManager.representAlleleAsElement (final Gene a_gene, final Document a_xmlDocument) [inline], [static], [private]
Parameters
a_gene Gene
a_xmlDocument Document
Returns
Element
Author
Klaus Meffert
Since
2.0
Definition at line 209 of file XMLManager.java.
References org.jgap.xml.XMLManager.ALLELE_TAG.
Referenced by org.jgap.xml.XMLManager.representGenesAsElement().
static Document org.jgap.xml.XMLManager.representChromosomeAsDocument (final IChromosome a_subject) [inline], [static]
Marshall a Chromosome instance to an XML Document representation, including its contained Gene instances.
Parameters
a_subject the chromosome to represent as an XML document
Returns
a Document object representing the given Chromosome
Author
Neil Rotstan
Since
1.0
Deprecated
Deprecated use XMLDocumentBuilder instead
Definition at line 115 of file XMLManager.java.
References org.jgap.xml.XMLManager.m_lock, and org.jgap.xml.XMLManager.representChromosomeAsElement().
static Element org.jgap.xml.XMLManager.representChromosomeAsElement (final IChromosome a_subject, final Document a_xmlDocument) [inline], [static]
Marshall a Chromosome instance to an XML Element representation, including its contained Genes as sub-elements. This may be useful in scenarios where representation as an entire Document is undesirable, such as when the representation of this Chromosome is to be combined with other elements in a single Document.
Parameters
a_subject the chromosome to represent as an XML element
a_xmlDocument a Document instance that will be used to create the Element instance. Note that the element will NOT be added to the document by this method
Returns
an Element object representing the given Chromosome
Author
Neil Rotstan
Since
1.0
Deprecated
Deprecated use XMLDocumentBuilder instead
Definition at line 234 of file XMLManager.java.
References org.jgap.xml.XMLManager.CHROMOSOME_TAG, org.jgap.IChromosome.getGenes(), org.jgap.xml.XMLManager.representGenesAsElement(), and org.jgap.xml.XMLManager.SIZE_ATTRIBUTE.
Referenced by org.jgap.xml.XMLManager.representChromosomeAsDocument(), and org.jgap.xml.XMLManager.representGenotypeAsElement().
static Element org.jgap.xml.XMLManager.representGenesAsElement (final Gene[] a_geneValues, final Document a_xmlDocument) [inline], [static]
Marshall an array of Genes to an XML Element representation.
Parameters
a_geneValues the genes to represent as an XML element
a_xmlDocument a Document instance that will be used to create the Element instance. Note that the element will NOT be added to the document by this method
Returns
an Element object representing the given genes
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Deprecated
Deprecated use XMLDocumentBuilder instead
Definition at line 169 of file XMLManager.java.
References org.jgap.xml.XMLManager.CLASS_ATTRIBUTE, org.jgap.xml.XMLManager.GENE_TAG, org.jgap.xml.XMLManager.GENES_TAG, and org.jgap.xml.XMLManager.representAlleleAsElement().
Referenced by org.jgap.xml.XMLManager.representChromosomeAsElement().
static Document org.jgap.xml.XMLManager.representGenotypeAsDocument (final Genotype a_subject) [inline], [static]
Marshall a Genotype to an XML Document representation, including its population of Chromosome instances.
Parameters
a_subject the genotype to represent as an XML document
Returns
a Document object representing the given Genotype
Author
Neil Rotstan
Since
1.0
Deprecated
Deprecated use XMLDocumentBuilder instead
Definition at line 141 of file XMLManager.java.
References org.jgap.xml.XMLManager.m_lock, and org.jgap.xml.XMLManager.representGenotypeAsElement().
static Element org.jgap.xml.XMLManager.representGenotypeAsElement (final Genotype a_subject, final Document a_xmlDocument) [inline], [static]
Marshall a Genotype instance into an XML Element representation, including its population of Chromosome instances as sub-elements. This may be useful in scenarios where representation as an entire Document is undesirable, such as when the representation of this Genotype is to be combined with other elements in a single Document.
Parameters
a_subject the genotype to represent as an XML element
a_xmlDocument a Document instance that will be used to create the Element instance. Note that the element will NOT be added to the document by this method
Returns
an Element object representing the given Genotype
Author
Neil Rotstan
Since
1.0
Deprecated
Deprecated use XMLDocumentBuilder instead
Definition at line 274 of file XMLManager.java.
References org.jgap.xml.XMLManager.GENOTYPE_TAG, org.jgap.Population.getChromosome(), org.jgap.xml.XMLManager.representChromosomeAsElement(), and org.jgap.xml.XMLManager.SIZE_ATTRIBUTE.
Referenced by org.jgap.xml.XMLManager.representGenotypeAsDocument().
static void org.jgap.xml.XMLManager.writeFile (Document doc, File file) throws IOException [inline], [static]
Writes an XML file from a Document object.
Parameters
doc the Document object to be written to file
file the file to be written
Exceptions
IOException
Author
Klaus Meffert
Since
2.0
Definition at line 639 of file XMLManager.java.
Member Data Documentation
final String org.jgap.xml.XMLManager.ALLELE_TAG = `allele` [static], [private]
Definition at line 57 of file XMLManager.java.
Referenced by org.jgap.xml.XMLManager.representAlleleAsElement().
final String org.jgap.xml.XMLManager.CHROMOSOME_TAG = `chromosome` [static], [private]
Constant representing the name of the chromosome XML element tag.
Definition at line 45 of file XMLManager.java.
Referenced by org.jgap.xml.XMLManager.representChromosomeAsElement().
final String org.jgap.xml.XMLManager.CLASS_ATTRIBUTE = `class` [static], [private]
Constant representing the fully-qualified name of the concrete Gene class that was marshalled.
Definition at line 69 of file XMLManager.java.
Referenced by org.jgap.xml.XMLManager.getGenesFromElement(), and org.jgap.xml.XMLManager.representGenesAsElement().
final String org.jgap.xml.XMLManager.CVS_REVISION = `$Revision: 1.21 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 35 of file XMLManager.java.
final String org.jgap.xml.XMLManager.GENE_TAG = `gene` [static], [private]
Constant representing the name of the gene XML element tag.
Definition at line 55 of file XMLManager.java.
Referenced by org.jgap.xml.XMLManager.getGenesFromElement(), and org.jgap.xml.XMLManager.representGenesAsElement().
final String org.jgap.xml.XMLManager.GENES_TAG = `genes` [static], [private]
Constant representing the name of the gene XML element tag.
Definition at line 50 of file XMLManager.java.
Referenced by org.jgap.xml.XMLManager.getGenesFromElement(), and org.jgap.xml.XMLManager.representGenesAsElement().
final String org.jgap.xml.XMLManager.GENOTYPE_TAG = `genotype` [static], [private]
Constant representing the name of the genotype XML element tag.
Definition at line 40 of file XMLManager.java.
Referenced by org.jgap.xml.XMLManager.representGenotypeAsElement().
final DocumentBuilder org.jgap.xml.XMLManager.m_documentCreator [static], [private]
Shared DocumentBuilder, which is used to create new DOM Document instances.
Definition at line 75 of file XMLManager.java.
final Object org.jgap.xml.XMLManager.m_lock = new Object() [static], [private]
Shared lock object used for synchronization purposes.
Definition at line 80 of file XMLManager.java.
Referenced by org.jgap.xml.XMLManager.representChromosomeAsDocument(), and org.jgap.xml.XMLManager.representGenotypeAsDocument().
final String org.jgap.xml.XMLManager.SIZE_ATTRIBUTE = `size` [static], [private]
Constant representing the name of the size XML attribute that is added to genotype and chromosome elements to describe their size.
Definition at line 63 of file XMLManager.java.
Referenced by org.jgap.xml.XMLManager.representChromosomeAsElement(), and org.jgap.xml.XMLManager.representGenotypeAsElement().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/xml/XMLManager.java