org.jgap.gp.function.Increment Class Reference
Classes
interface Compatible
Public Member Functions
Increment (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException
Increment (final GPConfiguration a_conf, Class a_returnType, int a_increment) throws InvalidConfigurationException
Increment (final GPConfiguration a_conf, Class a_returnType, int a_increment, int a_subReturnType, int a_subChildType) throws InvalidConfigurationException
String toString ()
String getName ()
int execute_int (ProgramChromosome c, int n, Object[] args)
long execute_long (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
int compareTo (Object a_other)
boolean equals (Object a_other)
Object clone ()
Private Attributes
int m_increment
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.12 $`
Additional Inherited Members
Detailed Description
The increment operation.
Author
Konrad Odell
Klaus Meffert
Since
3.0
Definition at line 25 of file Increment.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Increment.Increment (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException [inline]
Constructor for using an increment of 1.
Parameters
a_conf the configuration to use
a_returnType the type of the terminal to increment (e.g. IntegerClass)
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 42 of file Increment.java.
Referenced by org.jgap.gp.function.Increment.clone(), org.jgap.gp.function.Increment.compareTo(), and org.jgap.gp.function.Increment.equals().
org.jgap.gp.function.Increment.Increment (final GPConfiguration a_conf, Class a_returnType, int a_increment) throws InvalidConfigurationException [inline]
Constructor to freely choose increment.
Parameters
a_conf the configuration to use
a_returnType the type of the terminal to increment (e.g. IntegerClass)
a_increment the increment to use, may also be negative
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 58 of file Increment.java.
org.jgap.gp.function.Increment.Increment (final GPConfiguration a_conf, Class a_returnType, int a_increment, int a_subReturnType, int a_subChildType) throws InvalidConfigurationException [inline]
Definition at line 64 of file Increment.java.
References org.jgap.gp.function.Increment.m_increment.
Member Function Documentation
Object org.jgap.gp.function.Increment.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 161 of file Increment.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.function.Increment.Increment().
int org.jgap.gp.function.Increment.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.0
Definition at line 122 of file Increment.java.
References org.jgap.gp.function.Increment.Increment(), and org.jgap.gp.function.Increment.m_increment.
boolean org.jgap.gp.function.Increment.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Klaus Meffert
Since
3.0
Definition at line 142 of file Increment.java.
References org.jgap.gp.function.Increment.Increment(), and org.jgap.gp.function.Increment.m_increment.
double org.jgap.gp.function.Increment.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 102 of file Increment.java.
References org.jgap.gp.function.Increment.m_increment.
float org.jgap.gp.function.Increment.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 98 of file Increment.java.
References org.jgap.gp.function.Increment.m_increment.
int org.jgap.gp.function.Increment.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 90 of file Increment.java.
References org.jgap.gp.function.Increment.m_increment.
long org.jgap.gp.function.Increment.execute_long (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 94 of file Increment.java.
References org.jgap.gp.function.Increment.m_increment.
Object org.jgap.gp.function.Increment.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 106 of file Increment.java.
String org.jgap.gp.function.Increment.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 86 of file Increment.java.
String org.jgap.gp.function.Increment.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 71 of file Increment.java.
References org.jgap.gp.function.Increment.m_increment.
Member Data Documentation
final String org.jgap.gp.function.Increment.CVS_REVISION = `$Revision: 1.12 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file Increment.java.
int org.jgap.gp.function.Increment.m_increment [private]
Definition at line 30 of file Increment.java.
Referenced by org.jgap.gp.function.Increment.compareTo(), org.jgap.gp.function.Increment.equals(), org.jgap.gp.function.Increment.execute_double(), org.jgap.gp.function.Increment.execute_float(), org.jgap.gp.function.Increment.execute_int(), org.jgap.gp.function.Increment.execute_long(), org.jgap.gp.function.Increment.Increment(), and org.jgap.gp.function.Increment.toString().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Increment.java