org.jgap.distr.grid.RequestSplitStrategy Class Reference
Public Member Functions
RequestSplitStrategy (Configuration a_config)
Configuration getConfiguration ()
JGAPRequest[] split (JGAPRequest a_request) throws Exception
Private Attributes
Configuration m_config
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Detailed Description
Implementation of IRequestSplitStrategy to split a single request into multiple requests for workers.
Author
Klaus Meffert
Since
3.2
Definition at line 23 of file RequestSplitStrategy.java.
Constructor & Destructor Documentation
org.jgap.distr.grid.RequestSplitStrategy.RequestSplitStrategy (Configuration a_config) [inline]
Definition at line 30 of file RequestSplitStrategy.java.
References org.jgap.distr.grid.RequestSplitStrategy.m_config.
Member Function Documentation
Configuration org.jgap.distr.grid.RequestSplitStrategy.getConfiguration () [inline]
Definition at line 34 of file RequestSplitStrategy.java.
References org.jgap.distr.grid.RequestSplitStrategy.m_config.
Referenced by org.jgap.distr.grid.RequestSplitStrategy.split().
JGAPRequest [] org.jgap.distr.grid.RequestSplitStrategy.split (JGAPRequest a_request) throws Exception [inline]
Creates single requests to be sent to workers.
Returns
single requests to be computed by workers
Exceptions
Exception
Author
Klaus Meffert
Since
3.01
Todo
Todo support cloning of m_config
Definition at line 46 of file RequestSplitStrategy.java.
References org.jgap.distr.grid.RequestSplitStrategy.getConfiguration(), and org.jgap.distr.grid.JGAPRequest.newInstance().
Member Data Documentation
final String org.jgap.distr.grid.RequestSplitStrategy.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file RequestSplitStrategy.java.
Configuration org.jgap.distr.grid.RequestSplitStrategy.m_config [private]
Definition at line 28 of file RequestSplitStrategy.java.
Referenced by org.jgap.distr.grid.RequestSplitStrategy.getConfiguration(), and org.jgap.distr.grid.RequestSplitStrategy.RequestSplitStrategy().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/distr/grid/RequestSplitStrategy.java