org.jgap.gp.function.statistics.Mean Class Reference
Public Member Functions
Mean (final GPConfiguration a_conf, Class a_returnType, int a_arityInitial, int a_arityMin, int a_arityMax) throws InvalidConfigurationException
double execute_double (ProgramChromosome c, int n, Object[] args)
String toString ()
Object clone ()
Additional Inherited Members
Detailed Description
This class calculates the Mean of N numbers.
Author
Luis Garcia
Since
3.5
Definition at line 25 of file Mean.java.
Constructor & Destructor Documentation
org.jgap.gp.function.statistics.Mean.Mean (final GPConfiguration a_conf, Class a_returnType, int a_arityInitial, int a_arityMin, int a_arityMax) throws InvalidConfigurationException [inline]
Definition at line 27 of file Mean.java.
Referenced by org.jgap.gp.function.statistics.Mean.clone().
Member Function Documentation
Object org.jgap.gp.function.statistics.Mean.clone () [inline]
Returns
clone of the current object instance
Implements org.jgap.util.ICloneable.
Definition at line 58 of file Mean.java.
References org.jgap.gp.CommandGene.getArity(), org.jgap.gp.CommandGene.getArityMax(), org.jgap.gp.CommandGene.getArityMin(), org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.function.statistics.Mean.Mean().
double org.jgap.gp.function.statistics.Mean.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 35 of file Mean.java.
References org.jgap.gp.CommandGene.size().
String org.jgap.gp.function.statistics.Mean.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 45 of file Mean.java.
References org.jgap.gp.CommandGene.size().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/statistics/Mean.java