org.jgap.impl.StandardPostSelector Class Reference
Public Member Functions
StandardPostSelector () throws InvalidConfigurationException
StandardPostSelector (final Configuration a_config) throws InvalidConfigurationException
void select (final int a_howManyToSelect, final Population a_from_pop, final Population a_to_pop)
void empty ()
boolean returnsUniqueChromosomes ()
boolean equals (Object a_o)
Object clone ()
Protected Member Functions
void add (final IChromosome a_chromosomeToAdd)
Private Attributes
Population m_chromosomes
boolean m_needsSorting
FitnessValueComparator m_fitnessValueComparator
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
Implementation of a NaturalSelector that is suited for being processed after genetic operators have been executed. It takes all chromosomes with no fitness value computed to the next generation. Then it takes the top n chromosomes from the remaining input into the next generation. Which chromosomes are the best is decided by evaluating their fitness value.
Author
Klaus Meffert
Since
3.2
Definition at line 26 of file StandardPostSelector.java.
Constructor & Destructor Documentation
org.jgap.impl.StandardPostSelector.StandardPostSelector () throws InvalidConfigurationException [inline]
Default constructor.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.2
Definition at line 56 of file StandardPostSelector.java.
Referenced by org.jgap.impl.StandardPostSelector.clone(), and org.jgap.impl.StandardPostSelector.equals().
org.jgap.impl.StandardPostSelector.StandardPostSelector (final Configuration a_config) throws InvalidConfigurationException [inline]
Constructor.
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.2
Definition at line 70 of file StandardPostSelector.java.
References org.jgap.impl.StandardPostSelector.m_chromosomes, org.jgap.impl.StandardPostSelector.m_fitnessValueComparator, and org.jgap.impl.StandardPostSelector.m_needsSorting.
Member Function Documentation
void org.jgap.impl.StandardPostSelector.add (final IChromosome a_chromosomeToAdd) [inline], [protected]
Add a Chromosome instance to this selector's working pool of Chromosomes.
Parameters
a_chromosomeToAdd the specimen to add to the pool
Author
Klaus Meffert
Since
3.2
Definition at line 86 of file StandardPostSelector.java.
References org.jgap.impl.StandardPostSelector.m_needsSorting.
Referenced by org.jgap.impl.StandardPostSelector.select().
Object org.jgap.impl.StandardPostSelector.clone () [inline]
Returns
clone of the current object instance
Implements org.jgap.util.ICloneable.
Definition at line 216 of file StandardPostSelector.java.
References org.jgap.NaturalSelector.getConfiguration(), org.jgap.impl.StandardPostSelector.m_needsSorting, and org.jgap.impl.StandardPostSelector.StandardPostSelector().
void org.jgap.impl.StandardPostSelector.empty () [inline]
Empties out the working pool of chromosomes.
Author
Klaus Meffert
Since
3.2
Implements org.jgap.INaturalSelector.
Definition at line 184 of file StandardPostSelector.java.
References org.jgap.impl.StandardPostSelector.m_needsSorting.
boolean org.jgap.impl.StandardPostSelector.equals (Object a_o) [inline]
Definition at line 201 of file StandardPostSelector.java.
References org.jgap.Population.equals(), org.jgap.impl.StandardPostSelector.m_chromosomes, org.jgap.impl.StandardPostSelector.m_fitnessValueComparator, and org.jgap.impl.StandardPostSelector.StandardPostSelector().
boolean org.jgap.impl.StandardPostSelector.returnsUniqueChromosomes () [inline]
Returns
always true as no chromosome can be returnd multiple times
Author
Klaus Meffert
Since
3.2
Implements org.jgap.INaturalSelector.
Definition at line 197 of file StandardPostSelector.java.
void org.jgap.impl.StandardPostSelector.select (final int a_howManyToSelect, final Population a_from_pop, final Population a_to_pop) [inline]
Selects a given number of Chromosomes from the pool that will move on to the next generation population. This selection will be guided by the fitness values. The chromosomes with the best fitness value win.
Parameters
a_from_pop the population the Chromosomes will be selected from
a_to_pop the population the Chromosomes will be added to
a_howManyToSelect the number of Chromosomes to select
Author
Klaus Meffert
Since
1.1
Definition at line 108 of file StandardPostSelector.java.
References org.jgap.impl.StandardPostSelector.add(), org.jgap.FitnessFunction.DELTA, org.jgap.Population.getChromosome(), org.jgap.IChromosome.getFitnessValueDirectly(), org.jgap.impl.StandardPostSelector.m_fitnessValueComparator, org.jgap.impl.StandardPostSelector.m_needsSorting, and org.jgap.FitnessFunction.NO_FITNESS_VALUE.
Member Data Documentation
final String org.jgap.impl.StandardPostSelector.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 29 of file StandardPostSelector.java.
Population org.jgap.impl.StandardPostSelector.m_chromosomes [private]
Stores the chromosomes to be taken into account for selection
Definition at line 34 of file StandardPostSelector.java.
Referenced by org.jgap.impl.StandardPostSelector.equals(), and org.jgap.impl.StandardPostSelector.StandardPostSelector().
FitnessValueComparator org.jgap.impl.StandardPostSelector.m_fitnessValueComparator [private]
Comparator that is only concerned about fitness values
Definition at line 44 of file StandardPostSelector.java.
Referenced by org.jgap.impl.StandardPostSelector.equals(), org.jgap.impl.StandardPostSelector.select(), and org.jgap.impl.StandardPostSelector.StandardPostSelector().
boolean org.jgap.impl.StandardPostSelector.m_needsSorting [private]
Indicated whether the list of added chromosomes needs sorting
Definition at line 39 of file StandardPostSelector.java.
Referenced by org.jgap.impl.StandardPostSelector.add(), org.jgap.impl.StandardPostSelector.clone(), org.jgap.impl.StandardPostSelector.empty(), org.jgap.impl.StandardPostSelector.select(), and org.jgap.impl.StandardPostSelector.StandardPostSelector().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/StandardPostSelector.java