org.jgap.BaseGeneticOperator Class Reference
Public Member Functions
BaseGeneticOperator (Configuration a_configuration) throws InvalidConfigurationException
Configuration getConfiguration ()
boolean equals (final Object a_other)
Protected Attributes
IEvolutionMonitor m_monitor
boolean m_monitorActive
Private Attributes
Configuration m_configuration
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.7 $`
Additional Inherited Members
Detailed Description
Base class for any implementation of interface GeneticOperator. See MutationOperator or CrossoverOperator for examples.
Author
Klaus Meffert
Since
3.0
Definition at line 21 of file BaseGeneticOperator.java.
Constructor & Destructor Documentation
org.jgap.BaseGeneticOperator.BaseGeneticOperator (Configuration a_configuration) throws InvalidConfigurationException [inline]
The only constructor in this class. Sets the immutable configuration.
Parameters
a_configuration the configuration to set (must not be null)
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 39 of file BaseGeneticOperator.java.
References org.jgap.BaseGeneticOperator.getConfiguration(), org.jgap.BaseGeneticOperator.m_configuration, org.jgap.BaseGeneticOperator.m_monitor, and org.jgap.BaseGeneticOperator.m_monitorActive.
Member Function Documentation
boolean org.jgap.BaseGeneticOperator.equals (final Object a_other) [inline]
Compares this GeneticOperator against the specified object. The result is true if the argument is an instance of this class and is equal with respect to the data.
Parameters
a_other the object to compare against
Returns
true: if the objects are the same, false otherwise
Author
Klaus Meffert
Since
2.6
Todo
Todo also compare Configuration?
Definition at line 72 of file BaseGeneticOperator.java.
Referenced by org.jgap.impl.GreedyCrossover.findNext(), and org.jgap.impl.GreedyCrossover.operate().
Configuration org.jgap.BaseGeneticOperator.getConfiguration () [inline]
Todo
Todo make returned object immutable
Returns
the configuration set
Author
Klaus Meffert
Since
3.0
Definition at line 57 of file BaseGeneticOperator.java.
References org.jgap.BaseGeneticOperator.m_configuration.
Referenced by org.jgap.BaseGeneticOperator.BaseGeneticOperator(), org.jgap.impl.InversionOperator.operate(), org.jgap.impl.GaussianMutationOperator.operate(), org.jgap.impl.GreedyCrossover.operate(), org.jgap.impl.SwappingMutationOperator.operate(), org.jgap.impl.RangedSwappingMutationOperator.operate(), org.jgap.impl.TwoWayMutationOperator.operate(), org.jgap.impl.MutationOperator.operate(), org.jgap.impl.AveragingCrossoverOperator.operate(), org.jgap.impl.CrossoverOperator.operate(), org.jgap.impl.CrossoverOperatorTest.testConstruct_4(), org.jgap.impl.CrossoverOperatorTest.testConstruct_5(), org.jgap.impl.CrossoverOperatorTest.testConstruct_6(), org.jgap.impl.CrossoverOperatorTest.testConstruct_7(), org.jgap.impl.CrossoverOperatorTest.testConstruct_8(), and org.jgap.impl.CrossoverOperatorTest.testConstruct_9().
Member Data Documentation
final String org.jgap.BaseGeneticOperator.CVS_REVISION = `$Revision: 1.7 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file BaseGeneticOperator.java.
Configuration org.jgap.BaseGeneticOperator.m_configuration [private]
Definition at line 26 of file BaseGeneticOperator.java.
Referenced by org.jgap.BaseGeneticOperator.BaseGeneticOperator(), and org.jgap.BaseGeneticOperator.getConfiguration().
IEvolutionMonitor org.jgap.BaseGeneticOperator.m_monitor [protected]
Definition at line 28 of file BaseGeneticOperator.java.
Referenced by org.jgap.BaseGeneticOperator.BaseGeneticOperator().
boolean org.jgap.BaseGeneticOperator.m_monitorActive [protected]
Definition at line 30 of file BaseGeneticOperator.java.
Referenced by org.jgap.BaseGeneticOperator.BaseGeneticOperator(), org.jgap.impl.CrossoverOperator.doCrossover(), org.jgap.impl.InversionOperator.operate(), org.jgap.impl.GaussianMutationOperator.operate(), org.jgap.impl.GreedyCrossover.operate(), org.jgap.impl.TwoWayMutationOperator.operate(), org.jgap.impl.MutationOperator.operate(), org.jgap.impl.AveragingCrossoverOperator.operate(), org.jgap.impl.SwappingMutationOperator.operate(), org.jgap.impl.RangedSwappingMutationOperator.operate(), and org.jgap.impl.CrossoverOperator.operate().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/BaseGeneticOperator.java