org.jgap.util.XStreamPassThruConverter Class Reference
Public Member Functions
XStreamPassThruConverter (Mapper mapper, ReflectionProvider reflectionProvider, Class a_clazz)
XStreamPassThruConverter (XStream a_xstream, Class a_clazz)
boolean canConvert (Class type)
void marshal (Object source, HierarchicalStreamWriter writer, MarshallingContext context)
Object unmarshal (HierarchicalStreamReader reader, UnmarshallingContext context)
abstract Object doUnmarshal (UnmarshallingContext context) throws Exception
void setConfiguration (GPConfiguration a_conf)
GPConfiguration getConfiguration ()
Protected Member Functions
void marshalDefault (Object source, HierarchicalStreamWriter writer, MarshallingContext context)
Object unmarshalDefault (UnmarshallingContext context, Object a_obj)
void setConfiguration (Object a_obj, String a_fieldName) throws Exception
Private Attributes
Mapper m_mapper
ReflectionProvider m_reflectionProvider
AnnotationProvider m_annotationProvider
Class m_clazz
GPConfiguration m_conf
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.1 $`
Detailed Description
An abstract XSTream converter that offers services for default marshalling and unmarshalling of objects.
Author
Klaus Meffert
Since
3.3.4
Definition at line 30 of file XStreamPassThruConverter.java.
Constructor & Destructor Documentation
org.jgap.util.XStreamPassThruConverter.XStreamPassThruConverter (Mapper mapper, ReflectionProvider reflectionProvider, Class a_clazz) [inline]
Definition at line 45 of file XStreamPassThruConverter.java.
References org.jgap.util.XStreamPassThruConverter.m_annotationProvider, org.jgap.util.XStreamPassThruConverter.m_clazz, org.jgap.util.XStreamPassThruConverter.m_mapper, and org.jgap.util.XStreamPassThruConverter.m_reflectionProvider.
org.jgap.util.XStreamPassThruConverter.XStreamPassThruConverter (XStream a_xstream, Class a_clazz) [inline]
Definition at line 54 of file XStreamPassThruConverter.java.
Member Function Documentation
boolean org.jgap.util.XStreamPassThruConverter.canConvert (Class type) [inline]
Definition at line 58 of file XStreamPassThruConverter.java.
abstract Object org.jgap.util.XStreamPassThruConverter.doUnmarshal (UnmarshallingContext context) throws Exception [pure virtual]
Referenced by org.jgap.util.XStreamPassThruConverter.unmarshal().
GPConfiguration org.jgap.util.XStreamPassThruConverter.getConfiguration () [inline]
Definition at line 96 of file XStreamPassThruConverter.java.
References org.jgap.util.XStreamPassThruConverter.m_conf.
Referenced by org.jgap.util.XStreamPassThruConverter.setConfiguration().
void org.jgap.util.XStreamPassThruConverter.marshal (Object source, HierarchicalStreamWriter writer, MarshallingContext context) [inline]
Definition at line 62 of file XStreamPassThruConverter.java.
References org.jgap.util.XStreamPassThruConverter.marshalDefault().
void org.jgap.util.XStreamPassThruConverter.marshalDefault (Object source, HierarchicalStreamWriter writer, MarshallingContext context) [inline], [protected]
Definition at line 67 of file XStreamPassThruConverter.java.
References org.jgap.util.XStreamPassThruConverter.m_annotationProvider, org.jgap.util.XStreamPassThruConverter.m_mapper, and org.jgap.util.XStreamPassThruConverter.m_reflectionProvider.
Referenced by org.jgap.util.XStreamPassThruConverter.marshal().
void org.jgap.util.XStreamPassThruConverter.setConfiguration (GPConfiguration a_conf) [inline]
Definition at line 92 of file XStreamPassThruConverter.java.
References org.jgap.util.XStreamPassThruConverter.m_conf.
void org.jgap.util.XStreamPassThruConverter.setConfiguration (Object a_obj, String a_fieldName) throws Exception [inline], [protected]
Definition at line 100 of file XStreamPassThruConverter.java.
References org.jgap.util.XStreamPassThruConverter.getConfiguration().
Object org.jgap.util.XStreamPassThruConverter.unmarshal (HierarchicalStreamReader reader, UnmarshallingContext context) [inline]
Definition at line 74 of file XStreamPassThruConverter.java.
References org.jgap.util.XStreamPassThruConverter.doUnmarshal().
Object org.jgap.util.XStreamPassThruConverter.unmarshalDefault (UnmarshallingContext context, Object a_obj) [inline], [protected]
Definition at line 86 of file XStreamPassThruConverter.java.
References org.jgap.util.XStreamPassThruConverter.m_annotationProvider, org.jgap.util.XStreamPassThruConverter.m_mapper, and org.jgap.util.XStreamPassThruConverter.m_reflectionProvider.
Member Data Documentation
final String org.jgap.util.XStreamPassThruConverter.CVS_REVISION = `$Revision: 1.1 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 33 of file XStreamPassThruConverter.java.
AnnotationProvider org.jgap.util.XStreamPassThruConverter.m_annotationProvider [private]
Definition at line 39 of file XStreamPassThruConverter.java.
Referenced by org.jgap.util.XStreamPassThruConverter.marshalDefault(), org.jgap.util.XStreamPassThruConverter.unmarshalDefault(), and org.jgap.util.XStreamPassThruConverter.XStreamPassThruConverter().
Class org.jgap.util.XStreamPassThruConverter.m_clazz [private]
Definition at line 41 of file XStreamPassThruConverter.java.
Referenced by org.jgap.util.XStreamPassThruConverter.XStreamPassThruConverter().
GPConfiguration org.jgap.util.XStreamPassThruConverter.m_conf [private]
Definition at line 43 of file XStreamPassThruConverter.java.
Referenced by org.jgap.util.XStreamPassThruConverter.getConfiguration(), and org.jgap.util.XStreamPassThruConverter.setConfiguration().
Mapper org.jgap.util.XStreamPassThruConverter.m_mapper [private]
Definition at line 35 of file XStreamPassThruConverter.java.
Referenced by org.jgap.util.XStreamPassThruConverter.marshalDefault(), org.jgap.util.XStreamPassThruConverter.unmarshalDefault(), and org.jgap.util.XStreamPassThruConverter.XStreamPassThruConverter().
ReflectionProvider org.jgap.util.XStreamPassThruConverter.m_reflectionProvider [private]
Definition at line 37 of file XStreamPassThruConverter.java.
Referenced by org.jgap.util.XStreamPassThruConverter.marshalDefault(), org.jgap.util.XStreamPassThruConverter.unmarshalDefault(), and org.jgap.util.XStreamPassThruConverter.XStreamPassThruConverter().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/util/XStreamPassThruConverter.java