org.jgap.Configuration Class Reference
Classes
class ConfigurationConfigurable
Public Member Functions
Configuration ()
Configuration (String a_id, String a_name)
Configuration (final String a_name)
Configuration (final String a_configFileName, boolean a_ignore) throws ConfigException, InvalidConfigurationException
void setName (final String a_name)
String getName ()
synchronized void setFitnessFunction (final FitnessFunction a_functionToSet) throws InvalidConfigurationException
synchronized FitnessFunction getFitnessFunction ()
synchronized void setBulkFitnessFunction (final BulkFitnessFunction a_functionToSet) throws InvalidConfigurationException
synchronized BulkFitnessFunction getBulkFitnessFunction ()
void setSampleChromosome (final IChromosome a_sampleChromosomeToSet) throws InvalidConfigurationException
IChromosome getSampleChromosome ()
int getChromosomeSize ()
synchronized void setNaturalSelector (final NaturalSelector a_selectorToSet) throws InvalidConfigurationException
synchronized NaturalSelector getNaturalSelector ()
synchronized NaturalSelector getNaturalSelector (final boolean a_processBeforeGeneticOperators, final int a_index)
ChainOfSelectors getNaturalSelectors (final boolean a_processBeforeGeneticOperators)
int getNaturalSelectorsSize (final boolean a_processBeforeGeneticOperators)
void removeNaturalSelectors (final boolean a_processBeforeGeneticOperators)
synchronized void setRandomGenerator (final RandomGenerator a_generatorToSet) throws InvalidConfigurationException
synchronized RandomGenerator getRandomGenerator ()
synchronized void addGeneticOperator (final GeneticOperator a_operatorToAdd) throws InvalidConfigurationException
List getGeneticOperators ()
synchronized void setPopulationSize (final int a_sizeOfPopulation) throws InvalidConfigurationException
synchronized int getPopulationSize ()
void setEventManager (final IEventManager a_eventManagerToSet) throws InvalidConfigurationException
IEventManager getEventManager ()
void setChromosomePool (final IChromosomePool a_chromosomePoolToSet) throws InvalidConfigurationException
IChromosomePool getChromosomePool ()
synchronized void lockSettings () throws InvalidConfigurationException
boolean isLocked ()
synchronized void verifyStateIsValid () throws InvalidConfigurationException
void addNaturalSelector (NaturalSelector a_selector, boolean a_processBeforeGeneticOperators) throws InvalidConfigurationException
void setMinimumPopSizePercent (int a_minimumSizeGuaranteedPercent)
int getMinimumPopSizePercent ()
FitnessEvaluator getFitnessEvaluator ()
void setFitnessEvaluator (FitnessEvaluator a_fitnessEvaluator)
boolean isPreserveFittestIndividual ()
void setPreservFittestIndividual (boolean a_preserveFittest)
void incrementGenerationNr ()
int getGenerationNr ()
ConfigurationHandler getConfigurationHandler ()
String toString ()
boolean isKeepPopulationSizeConstant ()
void setKeepPopulationSizeConstant (boolean a_keepPopSizeConstant)
void setSelectFromPrevGen (double a_percentage)
double getSelectFromPrevGen ()
IJGAPFactory getJGAPFactory ()
void setJGAPFactory (IJGAPFactory a_factory)
void setBreeder (IBreeder a_breeder)
IBreeder getBreeder ()
void setAlwaysCaculateFitness (boolean a_alwaysCalculate)
boolean isAlwaysCalculateFitness ()
String getId ()
Object clone ()
Configuration newInstance (String a_id, String a_name)
boolean equals (Object a_other)
int compareTo (Object a_other)
void setMonitor (IEvolutionMonitor a_monitor)
IEvolutionMonitor getMonitor ()
void setUniqueKeysActive (boolean a_active)
boolean isUniqueKeysActive ()
Static Public Member Functions
static void reset ()
static void reset (final String a_id)
static void resetProperty (final String a_propName)
static void resetProperty (final String a_propName, final String a_id)
Static Public Attributes
static final String PROPERTY_JGAPFACTORY_CLASS = `JGAPFACTORYCLASS`
static final String PROPERTY_FITFUNC_INST = `JGAPFITFUNCINST`
static final String PROPERTY_BFITFNC_INST = `JGAPBFITFNCINST`
static final String PROPERTY_FITEVAL_INST = `JGAPFITEVALINST`
static final String PROPERTY_SAMPLE_CHROM_INST = `JGAPSAMPLECHRMINST`
static final String PROPERTY_EVENT_MGR_INST = `JGAPEVNTMGRINST`
static final String S_CONFIGURATION = `Configuration`
static final String S_CONFIGURATION_NAME = `Configuration name`
static final String S_POPULATION_SIZE = `Population size`
static final String S_MINPOPSIZE = `Minimum pop. size [%]`
static final String S_CHROMOSOME_SIZE = `Chromosome size`
static final String S_SAMPLE_CHROM = `Sample Chromosome`
static final String S_SIZE = `Size`
static final String S_TOSTRING = `toString`
static final String S_RANDOM_GENERATOR = `Random generator`
static final String S_EVENT_MANAGER = `Event manager`
static final String S_NONE = `none`
static final String S_CONFIGURATION_HANDLER = `Configuration handler`
static final String S_FITNESS_FUNCTION = `Fitness function`
static final String S_FITNESS_EVALUATOR = `Fitness evaluator`
static final String S_GENETIC_OPERATORS = `Genetic operators`
static final String S_NATURAL_SELECTORS = `Natural Selectors`
static final String S_PRE = `pre`
static final String S_POST = `post`
Protected Member Functions
void checkProperty (final String a_propname, final Object a_obj, final Object a_oldObj, final String a_errmsg)
String makeKey (final Object a_obj)
void verifyChangesAllowed () throws InvalidConfigurationException
String makeThreadKey ()
void setId (String a_id)
Object doClone (Object a_objToClone) throws Exception
Static Protected Member Functions
static String getThreadKey (Thread current, String a_id)
Private Member Functions
void readObject (ObjectInputStream a_inputStream) throws ClassNotFoundException, IOException
Private Attributes
ConfigurationConfigurable m_config = new ConfigurationConfigurable()
FitnessFunction m_objectiveFunction
FitnessEvaluator m_fitnessEvaluator
IBreeder m_breeder
int m_minPercentageSizePopulation
BulkFitnessFunction m_bulkObjectiveFunction
IChromosome m_sampleChromosome
RandomGenerator m_randomGenerator
IEventManager m_eventManager
transient IChromosomePool m_chromosomePool
List m_geneticOperators
int m_chromosomeSize
boolean m_settingsLocked
ChainOfSelectors m_preSelectors
ChainOfSelectors m_postSelectors
boolean m_preserveFittestIndividual
double m_selectFromPrevGen
int m_generationNr
transient RootConfigurationHandler m_conHandler
String m_name
boolean m_keepPopulationSizeConstant
IJGAPFactory m_factory
boolean m_alwaysCalculateFitness
transient String threadKey
boolean m_uniqueKeysActive
String m_id
IEvolutionMonitor m_monitor
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.102 $`
Detailed Description
The Configuration class represents the current configuration of plugins and parameters necessary to execute the genetic algorithm (such as fitness function, natural selector, genetic operators, and so on).
Note that, while during setup, the settings, flags, and other values may be set multiple times. But once the lockSettings() method is invoked, they cannot be changed. The default behavior of the Genotype constructor is to invoke this method, meaning that once a Configuration object is passed to a Genotype, it cannot be subsequently modified. There is no mechanism for unlocking the settings once they are locked.
Not all configuration options are required. See the documentation for each of the respective mutator methods to determine whether it is required to provide a value for that setting, and what the setting will default to if not.
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 44 of file Configuration.java.
Constructor & Destructor Documentation
org.jgap.Configuration.Configuration () [inline]
Definition at line 342 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.newInstance(), and org.jgap.audit.PermutingConfiguration.next().
org.jgap.Configuration.Configuration (String a_id, String a_name) [inline]
Initialize with default values.
Parameters
a_id unique id for the configuration within the current thread
a_name informative name of the configuration, may be null
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 356 of file Configuration.java.
References org.jgap.Configuration.m_alwaysCalculateFitness, org.jgap.Configuration.m_conHandler, org.jgap.Configuration.m_factory, org.jgap.Configuration.m_geneticOperators, org.jgap.Configuration.m_id, org.jgap.Configuration.m_keepPopulationSizeConstant, org.jgap.Configuration.m_postSelectors, org.jgap.Configuration.m_preSelectors, org.jgap.Configuration.m_selectFromPrevGen, org.jgap.Configuration.makeThreadKey(), org.jgap.Configuration.PROPERTY_JGAPFACTORY_CLASS, and org.jgap.Configuration.setName().
org.jgap.Configuration.Configuration (final String a_name) [inline]
Constructs a configuration with an informative name but without a unique ID. This practically prevents more than one configurations to be instantiated within the same thread.
Parameters
a_name informative name of the configuration, may be null
Author
Klaus Meffert
Definition at line 398 of file Configuration.java.
References org.jgap.Configuration.setName().
org.jgap.Configuration.Configuration (final String a_configFileName, boolean a_ignore) throws ConfigException, InvalidConfigurationException [inline]
Reads in the configuration from the given file.
Parameters
a_configFileName the config file from which to load the configuration
a_ignore just there to create distinct signatures :-(
Exceptions
ConfigException
InvalidConfigurationException
Author
Siddhartha Azad
Since
2.3
Definition at line 416 of file Configuration.java.
References org.jgap.Configuration.getConfigurationHandler().
Member Function Documentation
synchronized void org.jgap.Configuration.addGeneticOperator (final GeneticOperator a_operatorToAdd) throws InvalidConfigurationException [inline]
Adds a genetic operator for use in this algorithm. Genetic operators represent evolutionary steps that, when combined, make up the evolutionary process. Examples of genetic operators are reproduction, crossover, and mutation. During the evolution process, all of the genetic operators added via this method are invoked in the order they were added. At least one genetic operator must be provided.
Parameters
a_operatorToAdd the genetic operator to add.
Exceptions
InvalidConfigurationException if the genetic operator is null or if this Configuration object is locked
Author
Neil Rotstan
Since
1.0
Definition at line 904 of file Configuration.java.
References org.jgap.Configuration.verifyChangesAllowed().
Referenced by org.jgap.ConfigurationForTesting.ConfigurationForTesting(), and org.jgap.impl.DefaultConfiguration.DefaultConfiguration().
void org.jgap.Configuration.addNaturalSelector (NaturalSelector a_selector, boolean a_processBeforeGeneticOperators) throws InvalidConfigurationException [inline]
Adds a NaturalSelector to the ordered chain of registered NaturalSelector's. It's possible to execute the NaturalSelector before or after (registered) genetic operations have been applied. Normally, you would add a selector that is applied after the genetic operators are processed (a_processBeforeGeneticOperators = false).
Parameters
a_selector the selector to be added to the chain
a_processBeforeGeneticOperators true: execute NaturalSelector before any genetic operator will be applied, false: .. after..
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
1.1
Definition at line 1219 of file Configuration.java.
References org.jgap.Configuration.verifyChangesAllowed().
Referenced by org.jgap.ConfigurationForTesting.ConfigurationForTesting(), org.jgap.impl.DefaultConfiguration.DefaultConfiguration(), and org.jgap.Configuration.setNaturalSelector().
void org.jgap.Configuration.checkProperty (final String a_propname, final Object a_obj, final Object a_oldObj, final String a_errmsg) [inline], [protected]
Verifies that a property is not set. If not set, set it, otherwise throw a RuntimeException with a_errmsg as text.
Parameters
a_propname the property to check (the current thread will be considered as a part of the property's name, too)
a_obj the object that should be set in charge of the property
a_oldObj the old object that is set until now. Not used yet
a_errmsg the error message to throw in case the property is already set for the current thread
Author
Klaus Meffert
Since
3.0
Definition at line 558 of file Configuration.java.
References org.jgap.Configuration.makeKey(), and org.jgap.Configuration.threadKey.
Referenced by org.jgap.Configuration.setBulkFitnessFunction(), org.jgap.Configuration.setEventManager(), org.jgap.Configuration.setFitnessEvaluator(), org.jgap.Configuration.setFitnessFunction(), org.jgap.gp.impl.GPConfiguration.setFitnessFunction(), and org.jgap.Configuration.setSampleChromosome().
Object org.jgap.Configuration.clone () [inline]
Returns
deep clone of this instance
Author
Klaus Meffert
Since
3.2
Implements org.jgap.util.ICloneable.
Definition at line 1705 of file Configuration.java.
References org.jgap.Configuration.m_id, org.jgap.Configuration.m_name, and org.jgap.Configuration.newInstance().
Referenced by org.jgap.Configuration.newInstance(), org.jgap.impl.DefaultConfigurationTest.testClone_0(), org.jgap.ConfigurationTest.testClone_0(), org.jgap.ConfigurationTest.testClone_1(), and org.jgap.ConfigurationTest.testClone_2().
int org.jgap.Configuration.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.2
Definition at line 1823 of file Configuration.java.
References org.jgap.Configuration.Configuration(), org.jgap.Configuration.m_alwaysCalculateFitness, org.jgap.Configuration.m_breeder, org.jgap.Configuration.m_bulkObjectiveFunction, org.jgap.Configuration.m_chromosomeSize, org.jgap.Configuration.m_factory, org.jgap.Configuration.m_fitnessEvaluator, org.jgap.Configuration.m_generationNr, org.jgap.Configuration.m_geneticOperators, org.jgap.Configuration.m_keepPopulationSizeConstant, org.jgap.Configuration.m_minPercentageSizePopulation, org.jgap.Configuration.m_name, org.jgap.Configuration.m_objectiveFunction, org.jgap.Configuration.m_postSelectors, org.jgap.Configuration.m_preSelectors, org.jgap.Configuration.m_preserveFittestIndividual, org.jgap.Configuration.m_randomGenerator, org.jgap.Configuration.m_sampleChromosome, org.jgap.Configuration.m_selectFromPrevGen, org.jgap.Configuration.m_settingsLocked, and org.jgap.Configuration.threadKey.
Referenced by org.jgap.Configuration.equals().
Object org.jgap.Configuration.doClone (Object a_objToClone) throws Exception [inline], [protected]
Helper called from clone.
Parameters
a_objToClone the object to clone
Returns
cloned object or null, if cloning not possible
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Todo
Todo try cloning in a standard way
Definition at line 1787 of file Configuration.java.
References org.jgap.Configuration.getJGAPFactory().
Referenced by org.jgap.Configuration.newInstance(), and org.jgap.gp.impl.GPConfiguration.newInstanceGP().
boolean org.jgap.Configuration.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if seen as equal
Author
Klaus Meffert
Since
3.2
Definition at line 1810 of file Configuration.java.
References org.jgap.Configuration.compareTo().
IBreeder org.jgap.Configuration.getBreeder () [inline]
Returns
the breeder set or new standard breeder instance in case no breeder was set before.
Author
Klaus Meffert
Since
3.2
Definition at line 1555 of file Configuration.java.
References org.jgap.Configuration.m_breeder.
synchronized BulkFitnessFunction org.jgap.Configuration.getBulkFitnessFunction () [inline]
Retrieves the bulk fitness function previously setup in this Configuration object.
Returns
the bulk fitness function
Author
Neil Rotstan
Since
1.0
Definition at line 659 of file Configuration.java.
References org.jgap.Configuration.m_bulkObjectiveFunction.
IChromosomePool org.jgap.Configuration.getChromosomePool () [inline]
Retrieves the ChromosomePool instance, if any, that is associated with this configuration. The ChromosomePool is used to pool discarded Chromosome instances so that they may be recycled later, thereby saving memory and the time to construct them from scratch. The presence of a ChromosomePool instance is optional. If none exists, then new Chromosomes should be constructed each time one is needed.
Returns
the ChromosomePool instance associated this configuration, or null if none has been provided
Author
Neil Rotstan
Since
1.0
Definition at line 1045 of file Configuration.java.
References org.jgap.Configuration.m_chromosomePool.
Referenced by org.jgap.audit.PermutingConfiguration.next(), and org.jgap.impl.DefaultConfigurationTest.testConstruct_0().
int org.jgap.Configuration.getChromosomeSize () [inline]
Retrieves the chromosome size being used by this genetic algorithm. This value is set automatically when the sample chromosome is provided.
Returns
chromosome size used in this configuration
Author
Neil Rotstan
Since
1.0
Definition at line 724 of file Configuration.java.
References org.jgap.Configuration.m_chromosomeSize.
Referenced by org.jgap.impl.DefaultCrossoverRateCalculatorTest.testCalculateCurrentRate_0(), org.jgap.impl.DefaultMutationRateCalculatorTest.testCalculateCurrentRate_0(), org.jgap.impl.DefaultCrossoverRateCalculatorTest.testCalculateCurrentRate_01(), org.jgap.impl.DefaultMutationRateCalculatorTest.testCalculateCurrentRate_1(), org.jgap.ConfigurationTest.testGetChromosomeSize_0(), and org.jgap.Configuration.toString().
ConfigurationHandler org.jgap.Configuration.getConfigurationHandler () [inline]
Implementation of the Configurable interface.
Returns
ConfigurationHandler
Exceptions
ConfigException
Author
Siddhartha Azad
Definition at line 1317 of file Configuration.java.
References org.jgap.Configuration.m_conHandler.
Referenced by org.jgap.Configuration.Configuration(), and org.jgap.Configuration.toString().
IEventManager org.jgap.Configuration.getEventManager () [inline]
Retrieves the event manager associated with this configuration. The event manager is responsible for the management of event subscribers and event notifications.
Returns
the actively configured event manager instance
Since
1.0
Definition at line 1007 of file Configuration.java.
References org.jgap.Configuration.m_eventManager.
Referenced by org.jgap.audit.PermutingConfiguration.next(), org.jgap.impl.DefaultConfigurationTest.testConstruct_0(), org.jgap.ConfigurationTest.testGetter_0(), org.jgap.ConfigurationTest.testToString_0(), and org.jgap.Configuration.toString().
FitnessEvaluator org.jgap.Configuration.getFitnessEvaluator () [inline]
Returns
the assigned FitnessEvaluator
Author
Klaus Meffert
Since
2.0
Definition at line 1254 of file Configuration.java.
References org.jgap.Configuration.m_fitnessEvaluator.
Referenced by org.jgap.audit.PermutingConfiguration.next(), org.jgap.impl.DefaultConfigurationTest.testConstruct_0(), org.jgap.ConfigurationTest.testToString_0(), and org.jgap.Configuration.toString().
synchronized FitnessFunction org.jgap.Configuration.getFitnessFunction () [inline]
Retrieves the fitness function previously setup in this Configuration object.
Returns
the fitness function
Author
Neil Rotstan
Since
1.0
Definition at line 598 of file Configuration.java.
References org.jgap.Configuration.m_objectiveFunction.
Referenced by org.jgap.audit.PermutingConfiguration.next(), org.jgap.ConfigurationTest.testGetter_0(), and org.jgap.Configuration.toString().
int org.jgap.Configuration.getGenerationNr () [inline]
Definition at line 1306 of file Configuration.java.
References org.jgap.Configuration.m_generationNr.
Referenced by org.jgap.BreederBase.applyGeneticOperators(), org.jgap.BreederBase.applyNaturalSelectors(), org.jgap.impl.GABreeder.evolve(), org.jgap.impl.GABreeder.fillPopulationRandomlyToOriginalSize(), and org.jgap.ConfigurationTest.testGenerationNr_0().
List org.jgap.Configuration.getGeneticOperators () [inline]
Retrieves the genetic operators setup in this Configuration instance. Note that once this Configuration instance is locked, a new, immutable list of operators is used and any lists previously retrieved with this method will no longer reflect the actual list in use.
Returns
the list of genetic operators
Author
Neil Rotstan
Since
1.0
Definition at line 928 of file Configuration.java.
References org.jgap.Configuration.m_geneticOperators.
Referenced by org.jgap.ConfigurationTest.testAddGeneticOperator_2(), org.jgap.impl.DefaultConfigurationTest.testConstruct_0(), org.jgap.ConfigurationTest.testGetter_0(), org.jgap.ConfigurationTest.testToString_0(), and org.jgap.Configuration.toString().
String org.jgap.Configuration.getId () [inline]
Returns
the id of the configuration set
Author
Klaus Meffert
Since
3.1
Definition at line 1683 of file Configuration.java.
References org.jgap.Configuration.m_id.
Referenced by org.jgap.gp.impl.GPConfiguration.clone(), and org.jgap.ConfigurationTest.testConstruct_3().
IJGAPFactory org.jgap.Configuration.getJGAPFactory () [inline]
Returns
the JGAP factory registered
Author
Klaus Meffert
Definition at line 1500 of file Configuration.java.
References org.jgap.Configuration.m_factory.
Referenced by org.jgap.BaseChromosome.BaseChromosome(), org.jgap.BaseGene.BaseGene(), org.jgap.Configuration.doClone(), and org.jgap.ConfigurationTest.testKeepPopSizeConstant_0().
int org.jgap.Configuration.getMinimumPopSizePercent () [inline]
Definition at line 1244 of file Configuration.java.
References org.jgap.Configuration.m_minPercentageSizePopulation.
Referenced by org.jgap.impl.GABreeder.fillPopulationRandomlyToOriginalSize(), org.jgap.audit.PermutingConfiguration.next(), org.jgap.ConfigurationTest.testToString_0(), and org.jgap.Configuration.toString().
IEvolutionMonitor org.jgap.Configuration.getMonitor () [inline]
Returns
the monitor uses for auditing the evolution progress.
Author
Klaus Meffert
Since
3.5
Definition at line 1891 of file Configuration.java.
References org.jgap.Configuration.m_monitor.
String org.jgap.Configuration.getName () [inline]
Returns
informative name of the configuration
Author
Klaus Meffert
Since
2.3
Definition at line 495 of file Configuration.java.
References org.jgap.Configuration.m_name.
Referenced by org.jgap.gp.impl.GPConfiguration.clone(), org.jgap.distr.grid.gp.JGAPWorkerGP.doWork(), org.jgap.Configuration.makeKey(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), org.jgap.ConfigurationTest.testGetName_0(), org.jgap.ConfigurationTest.testGetName_1(), org.jgap.ConfigurationTest.testGetName_2(), org.jgap.ConfigurationTest.testToString_0(), and org.jgap.Configuration.toString().
synchronized NaturalSelector org.jgap.Configuration.getNaturalSelector () [inline]
Retrieves the natural selector setup in this Configuration instance.
Returns
the natural selector
Author
Neil Rotstan
Since
1.0
Deprecated
Deprecated use getNaturalSelectors(true) or getNaturalSelectors(false) to obtain the relevant chain of NaturalSelector's and then call the chain's get(index) method
Definition at line 761 of file Configuration.java.
References org.jgap.Configuration.getNaturalSelectors().
Referenced by org.jgap.ConfigurationTest.testGetNaturalSelector_1(), and org.jgap.ConfigurationTest.testGetNaturalSelector_4().
synchronized NaturalSelector org.jgap.Configuration.getNaturalSelector (final boolean a_processBeforeGeneticOperators, final int a_index) [inline]
Parameters
a_processBeforeGeneticOperators true: retrieve selector that is registered to be executed before genetic operators, false: get the one that is registered to be executed after genetic operators
a_index index of the selector to get
Returns
NaturalSelector
Author
Klaus Meffert
Since
1.1
Definition at line 778 of file Configuration.java.
ChainOfSelectors org.jgap.Configuration.getNaturalSelectors (final boolean a_processBeforeGeneticOperators) [inline]
Only use for read-only access! Especially don't call clear() for the returned ChainOfSelectors object!
Parameters
a_processBeforeGeneticOperators true: retrieve selector that is registered to be executed before genetic operators, false: get the one that is registered to be executed after genetic operators
Returns
ChainOfSelectors
Author
Klaus Meffert
Since
1.1
Definition at line 800 of file Configuration.java.
References org.jgap.Configuration.m_postSelectors, and org.jgap.Configuration.m_preSelectors.
Referenced by org.jgap.Configuration.getNaturalSelector(), org.jgap.Configuration.removeNaturalSelectors(), org.jgap.ConfigurationTest.testAddNaturalSelector_0(), org.jgap.ConfigurationTest.testAddNaturalSelector_1(), org.jgap.ConfigurationTest.testAddNaturalSelector_2(), org.jgap.impl.DefaultConfigurationTest.testConstruct_0(), org.jgap.ConfigurationTest.testGetter_0(), org.jgap.ConfigurationTest.testRemoveNaturalSelector_0(), org.jgap.ConfigurationTest.testRemoveNaturalSelector_1(), org.jgap.ConfigurationTest.testRemoveNaturalSelector_2(), org.jgap.ConfigurationTest.testRemoveNaturalSelector_3(), org.jgap.ConfigurationTest.testSetNaturalSelector_0(), and org.jgap.Configuration.toString().
int org.jgap.Configuration.getNaturalSelectorsSize (final boolean a_processBeforeGeneticOperators) [inline]
Parameters
a_processBeforeGeneticOperators true: retrieve selector that is registered to be executed before genetic operators, false: get the one that is registered to be executed after genetic operators
Returns
size of selector list (distinct by a_processBeforeGeneticOperators)
Author
Klaus Meffert
Since
1.1
Definition at line 819 of file Configuration.java.
Referenced by org.jgap.ConfigurationTest.testRemoveNaturalSelector_0(), org.jgap.ConfigurationTest.testRemoveNaturalSelector_1(), org.jgap.ConfigurationTest.testRemoveNaturalSelector_2(), and org.jgap.ConfigurationTest.testRemoveNaturalSelector_3().
synchronized int org.jgap.Configuration.getPopulationSize () [inline]
Retrieves the population size setup in this Configuration instance.
Returns
population size
Definition at line 963 of file Configuration.java.
Referenced by org.jgap.Genotype.evolve(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), org.jgap.audit.PermutingConfiguration.next(), examples.grid.mathProblemDistributed.MyGenotypeInitializer.setupGenotype(), org.jgap.ConfigurationTest.testGetPopulationSize_0(), org.jgap.ConfigurationTest.testGetter_0(), and org.jgap.Configuration.toString().
synchronized RandomGenerator org.jgap.Configuration.getRandomGenerator () [inline]
Retrieves the random generator setup in this Configuration instance.
Returns
the random generator
Author
Neil Rotstan
Since
1.0
Definition at line 884 of file Configuration.java.
References org.jgap.Configuration.m_randomGenerator.
Referenced by org.jgap.audit.PermutingConfiguration.next(), org.jgap.impl.DefaultConfigurationTest.testConstruct_0(), org.jgap.ConfigurationTest.testGetter_0(), org.jgap.ConfigurationTest.testToString_0(), and org.jgap.Configuration.toString().
IChromosome org.jgap.Configuration.getSampleChromosome () [inline]
Retrieves the sample Chromosome that contains the desired Gene setup for each respective gene position (locus).
Returns
sample Chromosome instance
Author
Neil Rotstan
Since
1.0
Definition at line 710 of file Configuration.java.
References org.jgap.Configuration.m_sampleChromosome.
Referenced by org.jgap.audit.PermutingConfiguration.next(), org.jgap.GenotypeTest.testEvolve_0(), org.jgap.ConfigurationTest.testGetter_0(), org.jgap.ConfigurationTest.testToString_0(), and org.jgap.Configuration.toString().
double org.jgap.Configuration.getSelectFromPrevGen () [inline]
Definition at line 1491 of file Configuration.java.
References org.jgap.Configuration.m_selectFromPrevGen.
Referenced by org.jgap.BreederBase.applyNaturalSelectors(), and org.jgap.GenotypeTest.testEvolve_2_3().
static String org.jgap.Configuration.getThreadKey (Thread current, String a_id) [inline], [static], [protected]
Builds a string considering the current thread and the given id.
Parameters
current the current Thread
a_id a hopefully unique id of the configuration
Returns
string built up
Author
Klaus Meffert
Since
3.01
Definition at line 1523 of file Configuration.java.
Referenced by org.jgap.Configuration.makeThreadKey(), org.jgap.Configuration.reset(), and org.jgap.Configuration.resetProperty().
void org.jgap.Configuration.incrementGenerationNr () [inline]
Definition at line 1302 of file Configuration.java.
References org.jgap.Configuration.m_generationNr.
boolean org.jgap.Configuration.isAlwaysCalculateFitness () [inline]
Returns
true: Chromosome.getFitnessValue() will always (re-)calculate the fitness value. This may be necessary in case of environments where the state changes without the chromosome to notice.
Author
Klaus Meffert
Since
3.2.2
Definition at line 1616 of file Configuration.java.
References org.jgap.Configuration.m_alwaysCalculateFitness.
Referenced by org.jgap.ConfigurationTest.testSetAlwaysCalculateFitness_0().
boolean org.jgap.Configuration.isKeepPopulationSizeConstant () [inline]
See setKeepPopulationSizeConstant and GABreeder::evolve(Population, Configuration) for detailled explanation.
Returns
true: population size will always be the same size (as given with Configuration.setPopulationSize(int)
Author
Klaus Meffert
Since
2.4
Definition at line 1462 of file Configuration.java.
References org.jgap.Configuration.m_keepPopulationSizeConstant.
Referenced by org.jgap.Genotype.evolve(), org.jgap.impl.GABreeder.keepPopSizeConstant(), and org.jgap.ConfigurationTest.testKeepPopSizeConstant_0().
boolean org.jgap.Configuration.isLocked () [inline]
Retrieves the lock status of this object.
Returns
true if this object has been locked by a previous successful call to the lockSettings() method, false otherwise
Author
Neil Rotstan
Since
1.0
Definition at line 1091 of file Configuration.java.
References org.jgap.Configuration.m_settingsLocked.
Referenced by org.jgap.ConfigurationTest.testGetter_0(), org.jgap.ConfigurationTest.testIsLocked_0(), org.jgap.ConfigurationTest.testLock_1(), org.jgap.ConfigurationTest.testVerifyStateIsValid_0(), org.jgap.ConfigurationTest.testVerifyStateIsValid_1(), org.jgap.ConfigurationTest.testVerifyStateIsValid_2(), org.jgap.ConfigurationTest.testVerifyStateIsValid_3(), org.jgap.ConfigurationTest.testVerifyStateIsValid_4(), org.jgap.ConfigurationTest.testVerifyStateIsValid_5(), org.jgap.ConfigurationTest.testVerifyStateIsValid_6(), and org.jgap.ConfigurationTest.testVerifyStateIsValid_7().
boolean org.jgap.Configuration.isPreserveFittestIndividual () [inline]
Returns
true: fittest chromosome should always be transferred to next generation
Author
Klaus Meffert
Since
2.1
Definition at line 1286 of file Configuration.java.
References org.jgap.Configuration.m_preserveFittestIndividual.
Referenced by org.jgap.impl.GABreeder.evolve(), and org.jgap.ConfigurationTest.testSetPreserveFittestIndividual_0().
boolean org.jgap.Configuration.isUniqueKeysActive () [inline]
Returns
true: use unique keys to allow tracking and monitoring
Author
Klaus Meffert
Since
3.5
Definition at line 1911 of file Configuration.java.
References org.jgap.Configuration.m_uniqueKeysActive.
Referenced by org.jgap.BaseChromosome.BaseChromosome(), and org.jgap.BaseGene.BaseGene().
synchronized void org.jgap.Configuration.lockSettings () throws InvalidConfigurationException [inline]
Locks all of the settings in this configuration object. Once this method is successfully invoked, none of the settings may be changed. There is no way to unlock this object once it is locked.
Prior to returning successfully, this method will first invoke the verifyStateIsValid() method to make sure that any required configuration options have been properly set. If it detects a problem, it will throw an InvalidConfigurationException and leave the object unlocked.
It's possible to test whether this object is locked through the isLocked() method.
It is ok to lock an object more than once. In that case, this method does nothing and simply returns.
Exceptions
InvalidConfigurationException if this Configuration object is in an invalid state at the time of invocation
Author
Neil Rotstan
Since
1.0
Definition at line 1071 of file Configuration.java.
References org.jgap.Configuration.m_settingsLocked, and org.jgap.Configuration.verifyStateIsValid().
String org.jgap.Configuration.makeKey (final Object a_obj) [inline], [protected]
Parameters
a_obj the object to make a key for, must not be null
Returns
key produced for the object (hashCode() is used, so it should be implemented properly!)
Author
Klaus Meffert
Since
3.0
Definition at line 583 of file Configuration.java.
References org.jgap.Configuration.getName().
Referenced by org.jgap.Configuration.checkProperty().
String org.jgap.Configuration.makeThreadKey () [inline], [protected]
Definition at line 1621 of file Configuration.java.
References org.jgap.Configuration.getThreadKey(), org.jgap.Configuration.m_id, and org.jgap.Configuration.threadKey.
Referenced by org.jgap.Configuration.Configuration(), and org.jgap.Configuration.readObject().
Configuration org.jgap.Configuration.newInstance (String a_id, String a_name) [inline]
Creates a new Configuration instance by cloning. Allows to preset the ID and the name.
Parameters
a_id new ID for clone
a_name new name for clone
Returns
deep clone of this instance
Author
Klaus Meffert
Since
3.2
Definition at line 1720 of file Configuration.java.
References org.jgap.util.ICloneable.clone(), org.jgap.Configuration.clone(), org.jgap.Configuration.Configuration(), org.jgap.Configuration.doClone(), org.jgap.Configuration.m_alwaysCalculateFitness, org.jgap.Configuration.m_breeder, org.jgap.Configuration.m_bulkObjectiveFunction, org.jgap.Configuration.m_chromosomeSize, org.jgap.Configuration.m_eventManager, org.jgap.Configuration.m_factory, org.jgap.Configuration.m_fitnessEvaluator, org.jgap.Configuration.m_geneticOperators, org.jgap.Configuration.m_keepPopulationSizeConstant, org.jgap.Configuration.m_minPercentageSizePopulation, org.jgap.Configuration.m_name, org.jgap.Configuration.m_objectiveFunction, org.jgap.Configuration.m_postSelectors, org.jgap.Configuration.m_preSelectors, org.jgap.Configuration.m_preserveFittestIndividual, org.jgap.Configuration.m_randomGenerator, org.jgap.Configuration.m_sampleChromosome, org.jgap.Configuration.m_selectFromPrevGen, and org.jgap.Configuration.m_settingsLocked.
Referenced by org.jgap.Configuration.clone(), and examples.grid.mathProblemDistributed.MyRequestSplitStrategy.split().
void org.jgap.Configuration.readObject (ObjectInputStream a_inputStream) throws ClassNotFoundException, IOException [inline], [private]
Sets a property in the bag.
Be aware that setting in unserializable value here leads to problems with distributed computing or other scenarios based on serialization!
Be aware that cloning may also lead to conflicts in case you use unsupported object types!
Parameters
a_propName name of the property to se the value for
a_value value of the property
Author
Klaus Meffert
Since
3.3.1
Parameters
a_propName name of the property to retrieve the value from
Returns
value of the property
Author
Klaus Meffert
Since
3.3.1 Deserialize the object. Needed to provide a unique ID for each thread the object is used in.
Parameters
a_inputStream the ObjectInputStream provided for deserialzation
Exceptions
ClassNotFoundException
IOException
Author
Klaus Meffert
Since
3.01
Definition at line 1669 of file Configuration.java.
References org.jgap.Configuration.makeThreadKey().
void org.jgap.Configuration.removeNaturalSelectors (final boolean a_processBeforeGeneticOperators) [inline]
Removes all natural selectors (either pre or post ones).
Parameters
a_processBeforeGeneticOperators true: remove all selectors processed before genetic operators, false: remove the ones processed afterwards
Author
Klaus Meffert
Since
2.3
Definition at line 839 of file Configuration.java.
References org.jgap.Configuration.getNaturalSelectors().
static void org.jgap.Configuration.reset () [inline], [static]
SHOULD NOT BE NECESSARY TO CALL UNDER NORMAL CIRCUMSTANCES. May be useful for unit tests.
Reset the configuration so that re-setting parameters such as fitness function is possible (without calling this method, an overwriting of a previously set fitness function results in a RuntimeException).
Author
Klaus Meffert
Since
3.0
Definition at line 440 of file Configuration.java.
Referenced by org.jgap.ConfigurationForTesting.ConfigurationForTesting().
static void org.jgap.Configuration.reset (final String a_id) [inline], [static]
Reset the configuration so that re-setting parameters such as fitness function is possible (without calling this method, an overwriting of a previously set fitness function results in a RuntimeException).
Parameters
a_id a hopefully unique id of the configuration
Author
Klaus Meffert
Since
3.0
Definition at line 454 of file Configuration.java.
References org.jgap.Configuration.getThreadKey(), org.jgap.Configuration.PROPERTY_BFITFNC_INST, org.jgap.Configuration.PROPERTY_EVENT_MGR_INST, org.jgap.Configuration.PROPERTY_FITEVAL_INST, org.jgap.Configuration.PROPERTY_FITFUNC_INST, org.jgap.Configuration.PROPERTY_SAMPLE_CHROM_INST, and org.jgap.Configuration.threadKey.
static void org.jgap.Configuration.resetProperty (final String a_propName) [inline], [static]
See Configuration.reset().
Parameters
a_propName the property to reset
Author
Klaus Meffert
Since
3.0
Definition at line 470 of file Configuration.java.
static void org.jgap.Configuration.resetProperty (final String a_propName, final String a_id) [inline], [static]
Definition at line 474 of file Configuration.java.
References org.jgap.Configuration.getThreadKey(), and org.jgap.Configuration.threadKey.
void org.jgap.Configuration.setAlwaysCaculateFitness (boolean a_alwaysCalculate) [inline]
If population size should be kept constant then this selector determines which of the chromosomes to select into the next generation.
Parameters
a_popConstantSelector the selector to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.2.2
Returns
the registered selector to keep population size constant. If none is set, the NewestChromosomesSelector is instantiated, assigned and returned
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.2.2
Parameters
a_alwaysCalculate true: Chromosome.getFitnessValue() will always (re-)calculate the fitness value. This may be necessary in case of environments where the state changes without the chromosome to notice.
Author
Klaus Meffert
Since
3.2.2
Definition at line 1604 of file Configuration.java.
References org.jgap.Configuration.m_alwaysCalculateFitness.
void org.jgap.Configuration.setBreeder (IBreeder a_breeder) [inline]
Parameters
a_breeder the breeder to use
Author
Klaus Meffert
Since
3.2
Definition at line 1543 of file Configuration.java.
References org.jgap.Configuration.m_breeder.
Referenced by org.jgap.impl.DefaultConfiguration.DefaultConfiguration().
synchronized void org.jgap.Configuration.setBulkFitnessFunction (final BulkFitnessFunction a_functionToSet) throws InvalidConfigurationException [inline]
Sets the bulk fitness function to be used for this genetic algorithm. The bulk fitness function may be used to evaluate and assign fitness values to the entire group of candidate Chromosomes in a single batch. This can be useful in cases where it's difficult to assign fitness values to a Chromosome in isolation from the other candidate Chromosomes.
Note that it is illegal to set both a bulk fitness function and a normal fitness function. Although one or the other is required, the two are mutually exclusive.
Parameters
a_functionToSet bulk fitness function to be used
Exceptions
InvalidConfigurationException if the bulk fitness function is null, the normal fitness function has already been set, or if this Configuration object is locked
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 624 of file Configuration.java.
References org.jgap.Configuration.checkProperty(), org.jgap.Configuration.m_bulkObjectiveFunction, org.jgap.Configuration.m_objectiveFunction, org.jgap.Configuration.PROPERTY_BFITFNC_INST, and org.jgap.Configuration.verifyChangesAllowed().
void org.jgap.Configuration.setChromosomePool (final IChromosomePool a_chromosomePoolToSet) throws InvalidConfigurationException [inline]
Sets the ChromosomePool that is to be associated with this configuration. The ChromosomePool is used to pool discarded Chromosome instances so that they may be recycled later, thereby saving memory and the time to construct them from scratch. The presence of a ChromosomePool is optional. If none exists, then a new Chromosome will be constructed each time one is needed.
Parameters
a_chromosomePoolToSet the ChromosomePool instance to use
Exceptions
InvalidConfigurationException if this object is locked
Author
Neil Rotstan
Since
1.0
Definition at line 1025 of file Configuration.java.
References org.jgap.Configuration.m_chromosomePool, and org.jgap.Configuration.verifyChangesAllowed().
Referenced by org.jgap.impl.DefaultConfiguration.DefaultConfiguration(), and org.jgap.audit.PermutingConfiguration.PermutingConfiguration().
void org.jgap.Configuration.setEventManager (final IEventManager a_eventManagerToSet) throws InvalidConfigurationException [inline]
Sets the event manager that is to be associated with this configuration. The event manager is responsible for the management of event subscribers and event notifications.
Parameters
a_eventManagerToSet the EventManager instance to use in this configuration
Exceptions
InvalidConfigurationException if the event manager is null or this Configuration object is locked
Author
Neil Rotstan
Since
1.0
Definition at line 981 of file Configuration.java.
References org.jgap.Configuration.checkProperty(), org.jgap.Configuration.m_eventManager, org.jgap.Configuration.PROPERTY_EVENT_MGR_INST, and org.jgap.Configuration.verifyChangesAllowed().
Referenced by org.jgap.ConfigurationForTesting.ConfigurationForTesting(), org.jgap.impl.DefaultConfiguration.DefaultConfiguration(), org.jgap.gp.impl.GPConfiguration.init(), and org.jgap.audit.PermutingConfiguration.PermutingConfiguration().
void org.jgap.Configuration.setFitnessEvaluator (FitnessEvaluator a_fitnessEvaluator) [inline]
Set the fitness evaluator (deciding if a given fitness value is better when it's higher or better when it's lower).
Parameters
a_fitnessEvaluator the FitnessEvaluator to be used
Author
Klaus Meffert
Since
2.0
Definition at line 1266 of file Configuration.java.
References org.jgap.Configuration.checkProperty(), org.jgap.Configuration.m_fitnessEvaluator, and org.jgap.Configuration.PROPERTY_FITEVAL_INST.
Referenced by org.jgap.ConfigurationForTesting.ConfigurationForTesting(), org.jgap.impl.DefaultConfiguration.DefaultConfiguration(), and org.jgap.audit.PermutingConfiguration.PermutingConfiguration().
synchronized void org.jgap.Configuration.setFitnessFunction (final FitnessFunction a_functionToSet) throws InvalidConfigurationException [inline]
Sets the fitness function to be used for this genetic algorithm. The fitness function is responsible for evaluating a given Chromosome and returning a positive integer that represents its worth as a candidate solution. These values are used as a guide by the natural to determine which Chromosome instances will be allowed to move on to the next round of evolution, and which will instead be eliminated.
Note that it is illegal to set both this fitness function and a bulk fitness function. Although one or the other must be set, the two are mutually exclusive.
Parameters
a_functionToSet fitness function to be used
Exceptions
InvalidConfigurationException if the fitness function is null, a bulk fitness function has already been set, or if this Configuration object is locked.
Author
Neil Rotstan
Since
1.1
Definition at line 520 of file Configuration.java.
References org.jgap.Configuration.checkProperty(), org.jgap.Configuration.m_bulkObjectiveFunction, org.jgap.Configuration.m_objectiveFunction, org.jgap.Configuration.PROPERTY_FITFUNC_INST, and org.jgap.Configuration.verifyChangesAllowed().
Referenced by org.jgap.ConfigurationForTesting.ConfigurationForTesting(), org.jgap.audit.PermutingConfiguration.next(), and org.jgap.audit.PermutingConfiguration.PermutingConfiguration().
void org.jgap.Configuration.setId (String a_id) [inline], [protected]
Only to be called by sub classes, such as GPConfiguration.
Parameters
a_id the id to set
Author
Klaus Meffert
Since
3.2
Definition at line 1695 of file Configuration.java.
References org.jgap.Configuration.m_id.
void org.jgap.Configuration.setJGAPFactory (IJGAPFactory a_factory) [inline]
Parameters
a_factory the IJGAPFactory to use
Author
Klaus Meffert
Since
3.01
Definition at line 1533 of file Configuration.java.
References org.jgap.Configuration.m_factory.
void org.jgap.Configuration.setKeepPopulationSizeConstant (boolean a_keepPopSizeConstant) [inline]
Allows to keep the population size constant during one evolution, even if there is no appropriate instance of NaturalSelector (such as WeightedRouletteSelector) registered with the Configuration.
See setKeepPopulationSizeConstant and GABreeder::evolve(Population, Configuration) for detailled explanation.
Parameters
a_keepPopSizeConstant true: population size will always be the same size (as given with Configuration.setPopulationSize(int)
Author
Klaus Meffert
Since
2.4
Definition at line 1480 of file Configuration.java.
References org.jgap.Configuration.m_keepPopulationSizeConstant.
Referenced by org.jgap.impl.DefaultConfiguration.DefaultConfiguration().
void org.jgap.Configuration.setMinimumPopSizePercent (int a_minimumSizeGuaranteedPercent) [inline]
Minimum size guaranteed for population. This is significant during evolution as natural selectors could select fewer chromosomes for the next generation than the initial population size was.
Parameters
a_minimumSizeGuaranteedPercent if zero or below then no ensurance for size given, see Genotype.evolve()
Author
Klaus Meffert
Definition at line 1240 of file Configuration.java.
References org.jgap.Configuration.m_minPercentageSizePopulation.
Referenced by org.jgap.impl.DefaultConfiguration.DefaultConfiguration(), and org.jgap.audit.PermutingConfiguration.PermutingConfiguration().
void org.jgap.Configuration.setMonitor (IEvolutionMonitor a_monitor) [inline]
Sets a monitor for auditing evolution progress.
Parameters
a_monitor the monitor to use
Author
Klaus Meffert
Since
3.5
Definition at line 1878 of file Configuration.java.
References org.jgap.Configuration.m_monitor, and org.jgap.Configuration.setUniqueKeysActive().
void org.jgap.Configuration.setName (final String a_name) [inline]
Parameters
a_name informative name of the configuration
Author
Klaus Meffert
Since
2.3
Definition at line 485 of file Configuration.java.
References org.jgap.Configuration.m_name.
Referenced by org.jgap.Configuration.Configuration(), and org.jgap.gp.impl.GPConfiguration.GPConfiguration().
synchronized void org.jgap.Configuration.setNaturalSelector (final NaturalSelector a_selectorToSet) throws InvalidConfigurationException [inline]
Sets the natural selector to be used for this genetic algorithm. The natural selector is responsible for actually selecting which Chromosome instances are allowed to move on to the next round of evolution (usually guided by the fitness values provided by the fitness function). This setting is required.
Parameters
a_selectorToSet the natural selector to be used
Exceptions
InvalidConfigurationException if the natural selector is null or this Configuration object is locked
Author
Neil Rotstan
Since
1.0
Deprecated
Deprecated use addNaturalSelector(false) instead
Definition at line 744 of file Configuration.java.
References org.jgap.Configuration.addNaturalSelector().
synchronized void org.jgap.Configuration.setPopulationSize (final int a_sizeOfPopulation) throws InvalidConfigurationException [inline]
Sets the population size to be used for this genetic algorithm. The population size is a fixed value that represents the number of Chromosomes contained within the Genotype (population). This setting is required.
Parameters
a_sizeOfPopulation population size to be used
Exceptions
InvalidConfigurationException if the population size is not positive or this object is locked
Author
Neil Rotstan
Since
1.0
Definition at line 946 of file Configuration.java.
References org.jgap.Configuration.verifyChangesAllowed().
Referenced by org.jgap.ConfigurationForTesting.ConfigurationForTesting(), examples.gp.monalisa.core.DrawingGPConfiguration.DrawingGPConfiguration(), and org.jgap.audit.PermutingConfiguration.PermutingConfiguration().
void org.jgap.Configuration.setPreservFittestIndividual (boolean a_preserveFittest) [inline]
Determines whether to save (keep) the fittest individual.
Parameters
a_preserveFittest true: always transfer fittest chromosome to next generation
Author
Klaus Meffert
Since
2.1
Definition at line 1298 of file Configuration.java.
References org.jgap.Configuration.m_preserveFittestIndividual.
synchronized void org.jgap.Configuration.setRandomGenerator (final RandomGenerator a_generatorToSet) throws InvalidConfigurationException [inline]
Sets the random generator to be used for this genetic algorithm. The random generator is responsible for generating random numbers, which are used throughout the process of genetic evolution and selection. This setting is required.
Parameters
a_generatorToSet random generator to be used
Exceptions
InvalidConfigurationException if the random generator is null or this object is locked
Author
Neil Rotstan
Since
1.0
Definition at line 863 of file Configuration.java.
References org.jgap.Configuration.m_randomGenerator, and org.jgap.Configuration.verifyChangesAllowed().
Referenced by org.jgap.impl.DefaultConfiguration.DefaultConfiguration(), org.jgap.gp.impl.GPConfiguration.init(), and org.jgap.audit.PermutingConfiguration.PermutingConfiguration().
void org.jgap.Configuration.setSampleChromosome (final IChromosome a_sampleChromosomeToSet) throws InvalidConfigurationException [inline]
Sets the sample Chromosome that is to be used as a guide for the construction of other Chromosomes. The Chromosome should be setup with each gene represented by the desired concrete Gene implementation for that gene position (locus). Anytime a new Chromosome is created, it will be constructed with the same Gene setup as that provided in this sample Chromosome.
Parameters
a_sampleChromosomeToSet Chromosome to be used as the sample
Exceptions
InvalidConfigurationException if the given Chromosome is null or this Configuration object is locked
Author
Neil Rotstan
Since
1.0
Definition at line 678 of file Configuration.java.
References org.jgap.Configuration.checkProperty(), org.jgap.Configuration.m_chromosomeSize, org.jgap.Configuration.m_sampleChromosome, org.jgap.Configuration.PROPERTY_SAMPLE_CHROM_INST, and org.jgap.Configuration.verifyChangesAllowed().
Referenced by org.jgap.ConfigurationForTesting.ConfigurationForTesting(), and org.jgap.audit.PermutingConfiguration.PermutingConfiguration().
void org.jgap.Configuration.setSelectFromPrevGen (double a_percentage) [inline]
Definition at line 1484 of file Configuration.java.
References org.jgap.Configuration.m_selectFromPrevGen.
Referenced by org.jgap.impl.DefaultConfiguration.DefaultConfiguration().
void org.jgap.Configuration.setUniqueKeysActive (boolean a_active) [inline]
Parameters
a_active true: use unique keys to allow tracking and monitoring
Author
Klaus Meffert
Since
3.5
Definition at line 1901 of file Configuration.java.
References org.jgap.Configuration.m_uniqueKeysActive.
Referenced by org.jgap.Configuration.setMonitor().
String org.jgap.Configuration.toString () [inline]
Returns
string representation of the configuration containing all configurable elements
Author
Klaus Meffert
Since
2.3
Definition at line 1328 of file Configuration.java.
References org.jgap.Configuration.getChromosomeSize(), org.jgap.Configuration.getConfigurationHandler(), org.jgap.Configuration.getEventManager(), org.jgap.Configuration.getFitnessEvaluator(), org.jgap.Configuration.getFitnessFunction(), org.jgap.Configuration.getGeneticOperators(), org.jgap.Configuration.getMinimumPopSizePercent(), org.jgap.Configuration.getName(), org.jgap.Configuration.getNaturalSelectors(), org.jgap.Configuration.getPopulationSize(), org.jgap.Configuration.getRandomGenerator(), org.jgap.Configuration.getSampleChromosome(), org.jgap.Configuration.S_CHROMOSOME_SIZE, org.jgap.Configuration.S_CONFIGURATION, org.jgap.Configuration.S_CONFIGURATION_HANDLER, org.jgap.Configuration.S_CONFIGURATION_NAME, org.jgap.Configuration.S_EVENT_MANAGER, org.jgap.Configuration.S_FITNESS_EVALUATOR, org.jgap.Configuration.S_FITNESS_FUNCTION, org.jgap.Configuration.S_GENETIC_OPERATORS, org.jgap.Configuration.S_MINPOPSIZE, org.jgap.Configuration.S_NATURAL_SELECTORS, org.jgap.Configuration.S_NONE, org.jgap.Configuration.S_POPULATION_SIZE, org.jgap.Configuration.S_POST, org.jgap.Configuration.S_PRE, org.jgap.Configuration.S_RANDOM_GENERATOR, org.jgap.Configuration.S_SAMPLE_CHROM, org.jgap.Configuration.S_SIZE, and org.jgap.Configuration.S_TOSTRING.
Referenced by org.jgap.ConfigurationTest.testToString_0().
void org.jgap.Configuration.verifyChangesAllowed () throws InvalidConfigurationException [inline], [protected]
Makes sure that this Configuration object isn't locked. If it is, then an exception is thrown with an appropriate message indicating that settings in this object may not be altered. This method should be invoked by any mutator method in this object prior to making any state alterations.
Exceptions
InvalidConfigurationException if this Configuration object is locked
Author
Neil Rotstan
Since
1.0
Definition at line 1195 of file Configuration.java.
References org.jgap.Configuration.m_settingsLocked.
Referenced by org.jgap.Configuration.addGeneticOperator(), org.jgap.Configuration.addNaturalSelector(), org.jgap.Configuration.setBulkFitnessFunction(), org.jgap.Configuration.setChromosomePool(), org.jgap.Configuration.setEventManager(), org.jgap.Configuration.setFitnessFunction(), org.jgap.gp.impl.GPConfiguration.setFitnessFunction(), org.jgap.Configuration.setPopulationSize(), org.jgap.Configuration.setRandomGenerator(), and org.jgap.Configuration.setSampleChromosome().
synchronized void org.jgap.Configuration.verifyStateIsValid () throws InvalidConfigurationException [inline]
Tests the state of this Configuration object to make sure it's valid. This generally consists of verifying that required settings have, in fact, been set. If this object is not in a valid state, then an exception will be thrown detailing the reason the state is not valid.
Exceptions
InvalidConfigurationException if the state of this Configuration is not valid. The error message in the exception will detail the reason for invalidity
Author
Neil Rotstan
Since
1.0
Definition at line 1108 of file Configuration.java.
References org.jgap.Configuration.m_bulkObjectiveFunction, org.jgap.Configuration.m_chromosomeSize, org.jgap.Configuration.m_config, org.jgap.Configuration.m_eventManager, org.jgap.Configuration.m_fitnessEvaluator, org.jgap.Configuration.m_geneticOperators, org.jgap.Configuration.m_objectiveFunction, org.jgap.Configuration.m_preSelectors, org.jgap.Configuration.m_randomGenerator, and org.jgap.Configuration.m_sampleChromosome.
Referenced by org.jgap.Configuration.lockSettings().
Member Data Documentation
final String org.jgap.Configuration.CVS_REVISION = `$Revision: 1.102 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 47 of file Configuration.java.
boolean org.jgap.Configuration.m_alwaysCalculateFitness [private]
See Chromosome class, field m_alwaysCalculate, for description
Author
Klaus Meffert
Since
3.2.2
Definition at line 313 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.Configuration(), org.jgap.Configuration.isAlwaysCalculateFitness(), org.jgap.Configuration.newInstance(), and org.jgap.Configuration.setAlwaysCaculateFitness().
IBreeder org.jgap.Configuration.m_breeder [private]
Performs the evolution.
Definition at line 138 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.getBreeder(), org.jgap.Configuration.newInstance(), and org.jgap.Configuration.setBreeder().
BulkFitnessFunction org.jgap.Configuration.m_bulkObjectiveFunction [private]
References the current bulk fitness function that will be used to evaluate chromosomes (in bulk) during the natural selection process. Note that only this or the normal fitness function may be set - the two are mutually exclusive.
Author
Neil Rotstan
Since
1.0
Definition at line 156 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.getBulkFitnessFunction(), org.jgap.Configuration.newInstance(), org.jgap.Configuration.setBulkFitnessFunction(), org.jgap.Configuration.setFitnessFunction(), and org.jgap.Configuration.verifyStateIsValid().
transient IChromosomePool org.jgap.Configuration.m_chromosomePool [private]
References the chromosome pool, if any, that is to be used to pool discarded Chromosome instances so that they may be recycled later, thereby saving memory and the time to construct them from scratch.
Author
Neil Rotstan
Since
1.0
Definition at line 204 of file Configuration.java.
Referenced by org.jgap.Configuration.getChromosomePool(), and org.jgap.Configuration.setChromosomePool().
int org.jgap.Configuration.m_chromosomeSize [private]
The number of genes that will be stored in each chromosome in the population.
Definition at line 221 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.getChromosomeSize(), org.jgap.Configuration.newInstance(), org.jgap.Configuration.setSampleChromosome(), and org.jgap.Configuration.verifyStateIsValid().
ConfigurationConfigurable org.jgap.Configuration.m_config = new ConfigurationConfigurable() [private]
Contains a bag of custom properties. Can be empty. A custom property is such that is not included in the standard JGAP configuration.
Since
3.3.1
Definition at line 116 of file Configuration.java.
Referenced by org.jgap.Configuration.verifyStateIsValid().
transient RootConfigurationHandler org.jgap.Configuration.m_conHandler [private]
The Configuration handler for this Configurable.
Author
Siddhartha Azad
Since
2.3
Definition at line 278 of file Configuration.java.
Referenced by org.jgap.Configuration.Configuration(), and org.jgap.Configuration.getConfigurationHandler().
IEventManager org.jgap.Configuration.m_eventManager [private]
References the event manager that is to be used for the notification of genetic events and the management of event subscribers.
Author
Neil Rotstan
Since
1.0
Definition at line 194 of file Configuration.java.
Referenced by org.jgap.Configuration.getEventManager(), org.jgap.Configuration.newInstance(), org.jgap.Configuration.setEventManager(), and org.jgap.Configuration.verifyStateIsValid().
IJGAPFactory org.jgap.Configuration.m_factory [private]
Holds the central configurable factory for creating default objects.
Author
Klaus Meffert
Since
2.6
Definition at line 305 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.Configuration(), org.jgap.Configuration.getJGAPFactory(), org.jgap.Configuration.newInstance(), and org.jgap.Configuration.setJGAPFactory().
FitnessEvaluator org.jgap.Configuration.m_fitnessEvaluator [private]
The fitness evaluator. See interface class FitnessEvaluator for details.
Since
2.0 (since 1.1 in class Genotype)
Definition at line 133 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.getFitnessEvaluator(), org.jgap.Configuration.newInstance(), org.jgap.Configuration.setFitnessEvaluator(), and org.jgap.Configuration.verifyStateIsValid().
int org.jgap.Configuration.m_generationNr [private]
Indicates how many times the evolve()-method in class Genotype has been called. Represents the number of the current population.
Author
Klaus Meffert
Since
2.2
Definition at line 270 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.getGenerationNr(), and org.jgap.Configuration.incrementGenerationNr().
List org.jgap.Configuration.m_geneticOperators [private]
Stores all of the GeneticOperator implementations that are to be used to operate upon the chromosomes of a population prior to natural selection. Operators will be executed in the order that they are added to this list.
Author
Klaus Meffert
Since
1.1
Definition at line 215 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.Configuration(), org.jgap.Configuration.getGeneticOperators(), org.jgap.Configuration.newInstance(), and org.jgap.Configuration.verifyStateIsValid().
String org.jgap.Configuration.m_id [private]
Unique ID for a configuration to distinguish it from other configurations instantiated within the same thread.
Author
Klaus Meffert
Since
3.01
Definition at line 333 of file Configuration.java.
Referenced by org.jgap.Configuration.clone(), org.jgap.Configuration.Configuration(), org.jgap.Configuration.getId(), org.jgap.Configuration.makeThreadKey(), and org.jgap.Configuration.setId().
boolean org.jgap.Configuration.m_keepPopulationSizeConstant [private]
True: population size will be kept constant at specified size in configuration. False: population size will grow dependently on used NaturalSelector's and GeneticOperator's. Default is TRUE
Author
Klaus Meffert
Since
2.4
Definition at line 297 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.Configuration(), org.jgap.Configuration.isKeepPopulationSizeConstant(), org.jgap.Configuration.newInstance(), and org.jgap.Configuration.setKeepPopulationSizeConstant().
int org.jgap.Configuration.m_minPercentageSizePopulation [private]
Minimum size guaranteed for population. If zero or below then no ensurance.
Author
Klaus Meffert
Definition at line 145 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.getMinimumPopSizePercent(), org.jgap.Configuration.newInstance(), and org.jgap.Configuration.setMinimumPopSizePercent().
IEvolutionMonitor org.jgap.Configuration.m_monitor [private]
Author
Klaus Meffert
Since
3.5
Definition at line 340 of file Configuration.java.
Referenced by org.jgap.Configuration.getMonitor(), and org.jgap.Configuration.setMonitor().
String org.jgap.Configuration.m_name [private]
Informative name for output.
Author
Klaus Meffert
Since
2.3
Definition at line 286 of file Configuration.java.
Referenced by org.jgap.Configuration.clone(), org.jgap.Configuration.compareTo(), org.jgap.Configuration.getName(), org.jgap.Configuration.newInstance(), and org.jgap.Configuration.setName().
FitnessFunction org.jgap.Configuration.m_objectiveFunction [private]
References the current fitness function that will be used to evaluate chromosomes during the natural selection process. Note that only this or the bulk fitness function may be set - the two are mutually exclusive.
Author
Neil Rotstan
Since
1.0
Definition at line 126 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.getFitnessFunction(), org.jgap.Configuration.newInstance(), org.jgap.Configuration.setBulkFitnessFunction(), org.jgap.Configuration.setFitnessFunction(), and org.jgap.Configuration.verifyStateIsValid().
ChainOfSelectors org.jgap.Configuration.m_postSelectors [private]
Ordered chain of NaturalSelector's which will be executed after applying Genetic Operators.
Author
Klaus Meffert
Since
1.1
Definition at line 247 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.Configuration(), org.jgap.Configuration.getNaturalSelectors(), and org.jgap.Configuration.newInstance().
ChainOfSelectors org.jgap.Configuration.m_preSelectors [private]
Ordered chain of NaturalSelector's which will be executed before applying Genetic Operators.
Author
Klaus Meffert
Since
1.1
Definition at line 238 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.Configuration(), org.jgap.Configuration.getNaturalSelectors(), org.jgap.Configuration.newInstance(), and org.jgap.Configuration.verifyStateIsValid().
boolean org.jgap.Configuration.m_preserveFittestIndividual [private]
Should the fittest chromosome in the population be preserved to the next generation when evolving (in Genotype.evolve()) ?
Definition at line 253 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.isPreserveFittestIndividual(), org.jgap.Configuration.newInstance(), and org.jgap.Configuration.setPreservFittestIndividual().
RandomGenerator org.jgap.Configuration.m_randomGenerator [private]
References the random number generator implementation that is to be used for the generation of any random numbers during the various genetic operations and processes.
Author
Neil Rotstan
Since
1.0
Definition at line 185 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.getRandomGenerator(), org.jgap.Configuration.newInstance(), org.jgap.Configuration.setRandomGenerator(), and org.jgap.Configuration.verifyStateIsValid().
IChromosome org.jgap.Configuration.m_sampleChromosome [private]
If population size should be kept constant then this selector determines which of the chromosomes to select into the next generation.
Author
Klaus Meffert
Since
3.2.2 References a Chromosome that serves as a sample of the Gene setup that is to be used. Each gene in the Chromosome should be represented with the desired Gene type.
Author
Neil Rotstan
Since
1.0
Definition at line 175 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.getSampleChromosome(), org.jgap.Configuration.newInstance(), org.jgap.Configuration.setSampleChromosome(), and org.jgap.Configuration.verifyStateIsValid().
double org.jgap.Configuration.m_selectFromPrevGen [private]
How many chromosomes should be selected from previous generation? The missing chromosomes will be filled up with randomly created new ones. 1 = all
Definition at line 261 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.Configuration(), org.jgap.Configuration.getSelectFromPrevGen(), org.jgap.Configuration.newInstance(), and org.jgap.Configuration.setSelectFromPrevGen().
boolean org.jgap.Configuration.m_settingsLocked [private]
Indicates whether the settings of this Configuration instance have been locked. Prior to locking, the settings may be set and reset as desired. Once this flag is set to true, no settings may be altered.
Definition at line 229 of file Configuration.java.
Referenced by org.jgap.Configuration.compareTo(), org.jgap.Configuration.isLocked(), org.jgap.Configuration.lockSettings(), org.jgap.Configuration.newInstance(), and org.jgap.Configuration.verifyChangesAllowed().
boolean org.jgap.Configuration.m_uniqueKeysActive [private]
True: Use unique keys, especially in Chromosomes, to allow tracking and monitoring of evolution progress.
Author
Klaus Meffert
Since
3.5
Definition at line 324 of file Configuration.java.
Referenced by org.jgap.Configuration.isUniqueKeysActive(), and org.jgap.Configuration.setUniqueKeysActive().
final String org.jgap.Configuration.PROPERTY_BFITFNC_INST = `JGAPBFITFNCINST` [static]
Definition at line 58 of file Configuration.java.
Referenced by org.jgap.Configuration.reset(), and org.jgap.Configuration.setBulkFitnessFunction().
final String org.jgap.Configuration.PROPERTY_EVENT_MGR_INST = `JGAPEVNTMGRINST` [static]
Definition at line 64 of file Configuration.java.
Referenced by org.jgap.Configuration.reset(), and org.jgap.Configuration.setEventManager().
final String org.jgap.Configuration.PROPERTY_FITEVAL_INST = `JGAPFITEVALINST` [static]
Definition at line 60 of file Configuration.java.
Referenced by org.jgap.Configuration.reset(), org.jgap.Configuration.setFitnessEvaluator(), org.jgap.PopulationTest.testDetermineFittestChromosome_3(), and org.jgap.GenotypeTest.testEvolve_10().
final String org.jgap.Configuration.PROPERTY_FITFUNC_INST = `JGAPFITFUNCINST` [static]
Definition at line 56 of file Configuration.java.
Referenced by org.jgap.audit.PermutingConfiguration.next(), org.jgap.Configuration.reset(), org.jgap.Configuration.setFitnessFunction(), and org.jgap.gp.impl.GPConfiguration.setFitnessFunction().
final String org.jgap.Configuration.PROPERTY_JGAPFACTORY_CLASS = `JGAPFACTORYCLASS` [static]
Constant for class name of JGAP Factory to use. Use as: System.setProperty(PROPERTY_JGAPFACTORY_CLASS, `myJGAPFactory`); If none such property set, class JGAPFactory will be used.
Definition at line 54 of file Configuration.java.
Referenced by org.jgap.Configuration.Configuration(), org.jgap.gp.impl.GPConfiguration.init(), org.jgap.JGAPTestCase.setUp(), org.jgap.ConfigurationTest.testConstruct_0(), org.jgap.ConfigurationTest.testConstruct_1(), and org.jgap.ConfigurationTest.testConstruct_2().
final String org.jgap.Configuration.PROPERTY_SAMPLE_CHROM_INST = `JGAPSAMPLECHRMINST` [static]
Definition at line 62 of file Configuration.java.
Referenced by org.jgap.Configuration.reset(), org.jgap.Configuration.setSampleChromosome(), org.jgap.xml.XMLManagerTest.testChromosome_0(), org.jgap.GenotypeTest.testEvolve_5_1(), org.jgap.GenotypeTest.testEvolve_5_2(), org.jgap.GenotypeTest.testEvolve_5_3(), and org.jgap.xml.XMLManagerTest.testGenotype_0().
final String org.jgap.Configuration.S_CHROMOSOME_SIZE = `Chromosome size` [static]
Definition at line 77 of file Configuration.java.
Referenced by org.jgap.Configuration.toString().
final String org.jgap.Configuration.S_CONFIGURATION = `Configuration` [static]
Constants for toString()
Definition at line 69 of file Configuration.java.
Referenced by org.jgap.ConfigurationTest.testToString_0(), and org.jgap.Configuration.toString().
final String org.jgap.Configuration.S_CONFIGURATION_HANDLER = `Configuration handler` [static]
Definition at line 91 of file Configuration.java.
Referenced by org.jgap.Configuration.toString().
final String org.jgap.Configuration.S_CONFIGURATION_NAME = `Configuration name` [static]
Definition at line 71 of file Configuration.java.
Referenced by org.jgap.ConfigurationTest.testToString_0(), and org.jgap.Configuration.toString().
final String org.jgap.Configuration.S_EVENT_MANAGER = `Event manager` [static]
Definition at line 87 of file Configuration.java.
Referenced by org.jgap.Configuration.toString().
final String org.jgap.Configuration.S_FITNESS_EVALUATOR = `Fitness evaluator` [static]
Definition at line 95 of file Configuration.java.
Referenced by org.jgap.ConfigurationTest.testToString_0(), and org.jgap.Configuration.toString().
final String org.jgap.Configuration.S_FITNESS_FUNCTION = `Fitness function` [static]
Definition at line 93 of file Configuration.java.
Referenced by org.jgap.Configuration.toString().
final String org.jgap.Configuration.S_GENETIC_OPERATORS = `Genetic operators` [static]
Definition at line 99 of file Configuration.java.
Referenced by org.jgap.Configuration.toString().
final String org.jgap.Configuration.S_MINPOPSIZE = `Minimum pop. size [%]` [static]
Definition at line 75 of file Configuration.java.
Referenced by org.jgap.ConfigurationTest.testToString_0(), and org.jgap.Configuration.toString().
final String org.jgap.Configuration.S_NATURAL_SELECTORS = `Natural Selectors` [static]
Definition at line 101 of file Configuration.java.
Referenced by org.jgap.Configuration.toString().
final String org.jgap.Configuration.S_NONE = `none` [static]
Definition at line 89 of file Configuration.java.
Referenced by org.jgap.Configuration.toString().
final String org.jgap.Configuration.S_POPULATION_SIZE = `Population size` [static]
Definition at line 73 of file Configuration.java.
Referenced by org.jgap.Configuration.toString().
final String org.jgap.Configuration.S_POST = `post` [static]
Definition at line 105 of file Configuration.java.
Referenced by org.jgap.Configuration.toString().
final String org.jgap.Configuration.S_PRE = `pre` [static]
Definition at line 103 of file Configuration.java.
Referenced by org.jgap.Configuration.toString().
final String org.jgap.Configuration.S_RANDOM_GENERATOR = `Random generator` [static]
Definition at line 85 of file Configuration.java.
Referenced by org.jgap.ConfigurationTest.testToString_0(), and org.jgap.Configuration.toString().
final String org.jgap.Configuration.S_SAMPLE_CHROM = `Sample Chromosome` [static]
Definition at line 79 of file Configuration.java.
Referenced by org.jgap.ConfigurationTest.testToString_0(), and org.jgap.Configuration.toString().
final String org.jgap.Configuration.S_SIZE = `Size` [static]
Definition at line 81 of file Configuration.java.
Referenced by org.jgap.ConfigurationTest.testToString_0(), and org.jgap.Configuration.toString().
final String org.jgap.Configuration.S_TOSTRING = `toString` [static]
Definition at line 83 of file Configuration.java.
Referenced by org.jgap.ConfigurationTest.testToString_0(), and org.jgap.Configuration.toString().
transient String org.jgap.Configuration.threadKey [private]
Definition at line 315 of file Configuration.java.
Referenced by org.jgap.Configuration.checkProperty(), org.jgap.Configuration.compareTo(), org.jgap.Configuration.makeThreadKey(), org.jgap.Configuration.reset(), and org.jgap.Configuration.resetProperty().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/Configuration.java