org.jgap.impl.IntegerGene Class Reference
Public Member Functions
IntegerGene () throws InvalidConfigurationException
IntegerGene (final Configuration a_config) throws InvalidConfigurationException
IntegerGene (final Configuration a_config, final int a_lowerBounds, final int a_upperBounds) throws InvalidConfigurationException
String getPersistentRepresentation ()
void setValueFromPersistentRepresentation (final String a_representation) throws UnsupportedRepresentationException
int intValue ()
void setToRandomValue (final RandomGenerator a_numberGenerator)
void applyMutation (final int a_index, final double a_percentage)
int hashCode ()
String toString ()
int getLowerBounds ()
int getUpperBounds ()
Protected Member Functions
Gene newGeneInternal ()
int compareToNative (final Object a_o1, final Object a_o2)
void mapValueToWithinBounds ()
Static Protected Attributes
static final long INTEGER_RANGE
Private Attributes
int m_upperBounds
int m_lowerBounds
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.46 $`
Additional Inherited Members
Detailed Description
A Gene implementation that supports an integer values for its allele. Upper and lower bounds may optionally be provided to restrict the range of legal values allowed by this Gene instance.
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 24 of file IntegerGene.java.
Constructor & Destructor Documentation
org.jgap.impl.IntegerGene.IntegerGene () throws InvalidConfigurationException [inline]
Constructs a new IntegerGene with default settings. No bounds will be put into effect for values (alleles) of this Gene instance, other than the standard range of integer values.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Neil Rostan
Klaus Meffert
Since
1.0
Definition at line 60 of file IntegerGene.java.
Referenced by org.jgap.impl.IntegerGene.newGeneInternal().
org.jgap.impl.IntegerGene.IntegerGene (final Configuration a_config) throws InvalidConfigurationException [inline]
Constructs a new IntegerGene with default settings. No bounds will be put into effect for values (alleles) of this Gene instance, other than the standard range of integer values.
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 76 of file IntegerGene.java.
org.jgap.impl.IntegerGene.IntegerGene (final Configuration a_config, final int a_lowerBounds, final int a_upperBounds) throws InvalidConfigurationException [inline]
Constructs a new IntegerGene with the specified lower and upper bounds for values (alleles) of this Gene instance.
Parameters
a_config the configuration to use
a_lowerBounds the lowest value that this Gene may possess, inclusive
a_upperBounds the highest value that this Gene may possess, inclusive
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.0
Definition at line 95 of file IntegerGene.java.
References org.jgap.impl.IntegerGene.m_lowerBounds, and org.jgap.impl.IntegerGene.m_upperBounds.
Member Function Documentation
void org.jgap.impl.IntegerGene.applyMutation (final int a_index, final double a_percentage) [inline]
See interface Gene for description.
Parameters
a_index ignored (because there is only 1 atomic element)
a_percentage percentage of mutation (greater than -1 and smaller than 1)
Author
Klaus Meffert
David Kemp
Since
1.1
Definition at line 331 of file IntegerGene.java.
References org.jgap.BaseGene.getAllele(), org.jgap.impl.IntegerGene.intValue(), org.jgap.impl.IntegerGene.m_lowerBounds, org.jgap.impl.IntegerGene.m_upperBounds, and org.jgap.impl.NumberGene.setAllele().
int org.jgap.impl.IntegerGene.compareToNative (final Object a_o1, final Object a_o2) [inline], [protected]
Compares to objects by first casting them into their expected type (e.g. Integer for IntegerGene) and then calling the compareTo-method of the casted type.
Parameters
a_o1 first object to be compared, always is not null
a_o2 second object to be compared, always is not null
Returns
a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than the object provided for comparison
Author
Neil Rostan
Since
1.0
Definition at line 276 of file IntegerGene.java.
int org.jgap.impl.IntegerGene.getLowerBounds () [inline]
Returns
the lower bounds of the integer gene
Author
Klaus Meffert
Since
2.6
Definition at line 384 of file IntegerGene.java.
References org.jgap.impl.IntegerGene.m_lowerBounds.
Referenced by org.jgap.impl.IntegerGeneTest.testGetBounds_0(), org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_2(), and org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_3().
String org.jgap.impl.IntegerGene.getPersistentRepresentation () [inline]
Retrieves a string representation of this Gene that includes any information required to reconstruct it at a later time, such as its value and internal state. This string will be used to represent this Gene in XML persistence. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Returns
string representation of this Gene's current state
Author
Neil Rostan
Since
1.0
Implements org.jgap.IPersistentRepresentation.
Definition at line 137 of file IntegerGene.java.
References org.jgap.impl.NumberGene.getInternalValue(), org.jgap.impl.IntegerGene.m_lowerBounds, org.jgap.impl.IntegerGene.m_upperBounds, and org.jgap.Gene.PERSISTENT_FIELD_DELIMITER.
Referenced by org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_6().
int org.jgap.impl.IntegerGene.getUpperBounds () [inline]
Returns
the upper bounds of the integer gene
Author
Klaus Meffert
Since
2.6
Definition at line 394 of file IntegerGene.java.
References org.jgap.impl.IntegerGene.m_upperBounds.
Referenced by org.jgap.impl.IntegerGeneTest.testGetBounds_0(), org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_2(), and org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_3().
int org.jgap.impl.IntegerGene.hashCode () [inline]
Modified hashCode() function to return different hashcodes for differently ordered genes in a chromosome.
Returns
-1 if no allele set, otherwise value return by BaseGene.hashCode()
Author
Klaus Meffert
Since
2.2
Definition at line 350 of file IntegerGene.java.
References org.jgap.impl.NumberGene.getInternalValue().
int org.jgap.impl.IntegerGene.intValue () [inline]
Retrieves the int value of this Gene, which may be more convenient in some cases than the more general getAllele() method.
Returns
the int value of this Gene
Author
Neil Rostan
Since
1.0
Definition at line 239 of file IntegerGene.java.
References org.jgap.BaseGene.getAllele().
Referenced by org.jgap.impl.IntegerGene.applyMutation(), org.jgap.impl.GreedyCrossover.distance(), examples.supergene.NickelsPenniesSupergene.isValid(), org.jgap.impl.IntegerGeneTest.testApplyMutation_0(), org.jgap.impl.IntegerGeneTest.testApplyMutationSupportsFullIntegerRange(), org.jgap.impl.IntegerGeneTest.testIntValue_0(), org.jgap.impl.IntegerGeneTest.testIntValue_1(), org.jgap.impl.IntegerGeneTest.testSetAllele_2(), org.jgap.impl.IntegerGeneTest.testSetAllele_3(), org.jgap.impl.IntegerGeneTest.testSetToRandomValue_3(), and org.jgap.impl.IntegerGeneTest.testSetToRandomValue_4().
void org.jgap.impl.IntegerGene.mapValueToWithinBounds () [inline], [protected], [virtual]
Maps the value of this IntegerGene to within the bounds specified by the m_upperBounds and m_lowerBounds instance variables. The value's relative position within the integer range will be preserved within the bounds range (in other words, if the value is about halfway between the integer max and min, then the resulting value will be about halfway between the upper bounds and lower bounds). If the value is null or is already within the bounds, it will be left unchanged.
Author
Neil Rostan
Klaus Meffert
Since
1.0
Implements org.jgap.impl.NumberGene.
Definition at line 293 of file IntegerGene.java.
References org.jgap.BaseGene.getAllele(), org.jgap.BaseGene.getConfiguration(), org.jgap.impl.IntegerGene.m_lowerBounds, org.jgap.impl.IntegerGene.m_upperBounds, org.jgap.impl.NumberGene.setAllele(), and org.jgap.impl.IntegerGene.setToRandomValue().
Gene org.jgap.impl.IntegerGene.newGeneInternal () [inline], [protected], [virtual]
Provides implementation-independent means for creating new Gene instances.
Returns
a new Gene instance of the same type and with the same setup as this concrete Gene
Author
Klaus Meffert
Since
2.6 (was newGene since 1.0, moved to BaseGene)
Implements org.jgap.BaseGene.
Definition at line 113 of file IntegerGene.java.
References org.jgap.BaseGene.getConfiguration(), org.jgap.impl.IntegerGene.IntegerGene(), org.jgap.impl.IntegerGene.m_lowerBounds, and org.jgap.impl.IntegerGene.m_upperBounds.
void org.jgap.impl.IntegerGene.setToRandomValue (final RandomGenerator a_numberGenerator) [inline]
Sets the value (allele) of this Gene to a random Integer value between the lower and upper bounds (if any) of this Gene.
Parameters
a_numberGenerator the random number generator that should be used to create any random values. It's important to use this generator to maintain the user's flexibility to configure the genetic engine to use the random number generator of their choice
Author
Neil Rostan
Klaus Meffert
David Kemp
Since
1.0
Definition at line 257 of file IntegerGene.java.
References org.jgap.impl.IntegerGene.m_lowerBounds, org.jgap.impl.IntegerGene.m_upperBounds, org.jgap.RandomGenerator.nextDouble(), and org.jgap.impl.NumberGene.setAllele().
Referenced by org.jgap.impl.IntegerGene.mapValueToWithinBounds().
void org.jgap.impl.IntegerGene.setValueFromPersistentRepresentation (final String a_representation) throws UnsupportedRepresentationException [inline]
Sets the value and internal state of this Gene from the string representation returned by a previous invocation of the getPersistentRepresentation() method. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Parameters
a_representation the string representation retrieved from a prior call to the getPersistentRepresentation() method
Exceptions
UnsupportedOperationException to indicate that no implementation is provided for this method
UnsupportedRepresentationException if this Gene implementation does not support the given string representation
Author
Neil Rostan
Since
1.0
Definition at line 171 of file IntegerGene.java.
References org.jgap.impl.IntegerGene.m_lowerBounds, org.jgap.impl.IntegerGene.m_upperBounds, org.jgap.Gene.PERSISTENT_FIELD_DELIMITER, and org.jgap.impl.NumberGene.setAllele().
String org.jgap.impl.IntegerGene.toString () [inline]
Returns
string representation of this Gene's value that may be useful for display purposes
Author
Klaus Meffert
Since
2.4
Implements org.jgap.Gene.
Definition at line 366 of file IntegerGene.java.
References org.jgap.impl.NumberGene.getInternalValue(), org.jgap.impl.IntegerGene.m_lowerBounds, and org.jgap.impl.IntegerGene.m_upperBounds.
Member Data Documentation
final String org.jgap.impl.IntegerGene.CVS_REVISION = `$Revision: 1.46 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file IntegerGene.java.
final long org.jgap.impl.IntegerGene.INTEGER_RANGE [static], [protected]
Initial value:
= (long) Integer.MAX_VALUE
      - (long) Integer.MIN_VALUE
Represents the constant range of values supported by integers.
Definition at line 32 of file IntegerGene.java.
int org.jgap.impl.IntegerGene.m_lowerBounds [private]
The lower bounds of values represented by this Gene. If not explicitly provided by the user, this should be set to Integer.MIN_VALUE
Definition at line 45 of file IntegerGene.java.
Referenced by org.jgap.impl.IntegerGene.applyMutation(), org.jgap.impl.IntegerGene.getLowerBounds(), org.jgap.impl.IntegerGene.getPersistentRepresentation(), org.jgap.impl.IntegerGene.IntegerGene(), org.jgap.impl.IntegerGene.mapValueToWithinBounds(), org.jgap.impl.IntegerGene.newGeneInternal(), org.jgap.impl.IntegerGene.setToRandomValue(), org.jgap.impl.IntegerGene.setValueFromPersistentRepresentation(), and org.jgap.impl.IntegerGene.toString().
int org.jgap.impl.IntegerGene.m_upperBounds [private]
The upper bounds of values represented by this Gene. If not explicitly provided by the user, this should be set to Integer.MAX_VALUE.
Definition at line 39 of file IntegerGene.java.
Referenced by org.jgap.impl.IntegerGene.applyMutation(), org.jgap.impl.IntegerGene.getPersistentRepresentation(), org.jgap.impl.IntegerGene.getUpperBounds(), org.jgap.impl.IntegerGene.IntegerGene(), org.jgap.impl.IntegerGene.mapValueToWithinBounds(), org.jgap.impl.IntegerGene.newGeneInternal(), org.jgap.impl.IntegerGene.setToRandomValue(), org.jgap.impl.IntegerGene.setValueFromPersistentRepresentation(), and org.jgap.impl.IntegerGene.toString().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/IntegerGene.java