org.jgap.distr.Culture Class Reference
Public Member Functions
Culture (final int a_size)
CultureMemoryCell set (final int a_index, final double a_value, final int a_historySize, final String a_name)
CultureMemoryCell set (final int a_index, final Object a_value, final int a_historySize, final String a_infotext)
CultureMemoryCell set (final String a_name, final Object a_value, final int a_historySize)
CultureMemoryCell get (final int a_index)
CultureMemoryCell get (final String a_name)
boolean contains (final String a_name)
int size ()
String toString ()
void clear ()
List getMemoryNames ()
boolean equals (Object a_other)
int compareTo (Object a_other)
void setMatrixWidth (int a_width)
CultureMemoryCell setMatrix (int a_x, int a_y, Object a_value)
CultureMemoryCell getMatrix (int a_x, int a_y)
Private Attributes
CultureMemoryCell[] m_memory
List m_memoryNames = new Vector()
int m_size
int m_width
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.16 $`
Detailed Description
Culture is a memory not being bound to a generation, but possibly persistent during the whole history of a genotype (over all generations). See GPConfiguration for current support of culture with Genetic Programming.
Also see http://cs.gmu.edu/~sean/papers/culture-gp96.pdf
Author
Klaus Meffert
Since
2.3
Definition at line 25 of file Culture.java.
Constructor & Destructor Documentation
org.jgap.distr.Culture.Culture (final int a_size) [inline]
Constructor.
Parameters
a_size the size of the memory in cells (CultureMemoryCell instances)
Author
Klaus Meffert
Since
2.3
Definition at line 60 of file Culture.java.
References org.jgap.distr.Culture.m_memory, org.jgap.distr.Culture.m_size, and org.jgap.distr.Culture.m_width.
Referenced by org.jgap.distr.Culture.compareTo().
Member Function Documentation
void org.jgap.distr.Culture.clear () [inline]
Clears the memory.
Author
Klaus Meffert
Since
3.0
Definition at line 246 of file Culture.java.
References org.jgap.distr.Culture.m_memory, and org.jgap.distr.Culture.m_size.
int org.jgap.distr.Culture.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.0
Definition at line 287 of file Culture.java.
References org.jgap.distr.Culture.Culture(), org.jgap.distr.Culture.m_memory, org.jgap.distr.Culture.m_memoryNames, and org.jgap.distr.Culture.m_size.
Referenced by org.jgap.distr.Culture.equals().
boolean org.jgap.distr.Culture.contains (final String a_name) [inline]
Checks if a memory cell with the given name exists.
Parameters
a_name the name of the cell to check
Returns
true: cell excists
Author
Klaus Meffert
Since
3.2
Definition at line 195 of file Culture.java.
Referenced by org.jgap.distr.CultureTest.testContains_0(), org.jgap.distr.CultureTest.testContains_1(), org.jgap.distr.CultureTest.testContains_2(), and org.jgap.distr.CultureTest.testContains_3().
boolean org.jgap.distr.Culture.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if the objects are regarded as equal
Author
Klaus Meffert
Since
3.0
Definition at line 269 of file Culture.java.
References org.jgap.distr.Culture.compareTo().
CultureMemoryCell org.jgap.distr.Culture.get (final int a_index) [inline]
Retrieves the memory cell at the given index.
Parameters
a_index index of the memory cell to read out
Returns
stored memory cell at given index
Author
Klaus Meffert
Since
2.3
Definition at line 159 of file Culture.java.
References org.jgap.distr.Culture.m_memory, and org.jgap.distr.Culture.size().
Referenced by org.jgap.distr.CultureTest.testClear_0(), org.jgap.distr.CultureTest.testToString_0(), and org.jgap.distr.CultureTest.testToString_1().
CultureMemoryCell org.jgap.distr.Culture.get (final String a_name) [inline]
Retrieves the memory cell at the given index.
Parameters
a_name name of the memory cell to read out
Returns
stored memory cell for given name, or null if name unknown
Author
Klaus Meffert
Since
3.0
Definition at line 175 of file Culture.java.
References org.jgap.distr.Culture.m_memory.
CultureMemoryCell org.jgap.distr.Culture.getMatrix (int a_x, int a_y) [inline]
Reads a value from the matrix memory that was previously stored with setMatrix(...).
Parameters
a_x the first coordinate of the matrix (width)
a_y the second coordinate of the matrix (height)
Returns
read value
Author
Klaus Meffert
Since
3.2
Definition at line 354 of file Culture.java.
References org.jgap.distr.Culture.m_width.
List org.jgap.distr.Culture.getMemoryNames () [inline]
Returns
cloned list of symbolic memory names
Author
Klaus Meffert
Since
3.0
Definition at line 257 of file Culture.java.
References org.jgap.distr.Culture.m_memoryNames.
Referenced by org.jgap.distr.CultureTest.testClear_0().
CultureMemoryCell org.jgap.distr.Culture.set (final int a_index, final double a_value, final int a_historySize, final String a_name) [inline]
Sets a memory cell with a given value. The memory cell will be newly created for that.
Parameters
a_index index of the memory cell
a_value value to set in the memory
a_historySize size of history to use, or less than 1 for turning history off
a_name informative name of the memory cell
Returns
newly created memory cell set with the given value
Author
Klaus Meffert
Since
2.3
Definition at line 83 of file Culture.java.
References org.jgap.distr.Culture.m_memory, and org.jgap.distr.Culture.size().
CultureMemoryCell org.jgap.distr.Culture.set (final int a_index, final Object a_value, final int a_historySize, final String a_infotext) [inline]
Sets a memory cell with a given value. The memory cell will be newly created for that.
Parameters
a_index index of the memory cell
a_value value to set in the memory
a_historySize size of history to use, or less than 1 for turning history off
a_infotext informative name of the memory cell
Returns
newly created memory cell set with the given value
Author
Klaus Meffert
Since
3.0
Definition at line 108 of file Culture.java.
References org.jgap.distr.Culture.m_memory, and org.jgap.distr.Culture.size().
CultureMemoryCell org.jgap.distr.Culture.set (final String a_name, final Object a_value, final int a_historySize) [inline]
Sets a memory cell with a given value. The memory cell will be newly created for that.
Parameters
a_name named index of the memory cell
a_value value to set in the memory
a_historySize size of history to use, or less than 1 for turning history off
Returns
newly created memory cell set with the given value
Author
Klaus Meffert
Since
3.0
Definition at line 132 of file Culture.java.
References org.jgap.distr.Culture.m_memory.
CultureMemoryCell org.jgap.distr.Culture.setMatrix (int a_x, int a_y, Object a_value) [inline]
Stores a value in the matrix memory. Use setMatrixWidth(int) beforehand!
Parameters
a_x the first coordinate of the matrix (width)
a_y the second coordinate of the matrix (height)
a_value the value to store
Returns
created or used memory cell
Author
Klaus Meffert
Since
3.2
Definition at line 332 of file Culture.java.
References org.jgap.distr.Culture.m_memory, and org.jgap.distr.Culture.m_width.
void org.jgap.distr.Culture.setMatrixWidth (int a_width) [inline]
Sets the width of the matrix memory. Important to call before using setMatrix/getMatrix!
Parameters
a_width the width the matrix should have
Author
Klaus Meffert
Since
3.2
Definition at line 310 of file Culture.java.
References org.jgap.distr.Culture.m_width, and org.jgap.distr.Culture.size().
int org.jgap.distr.Culture.size () [inline]
Returns
size of the memory
Author
Klaus Meffert
Since
2.3
Definition at line 209 of file Culture.java.
Referenced by org.jgap.distr.Culture.get(), org.jgap.distr.Culture.set(), org.jgap.distr.Culture.setMatrixWidth(), and org.jgap.distr.CultureTest.testConstruct_2().
String org.jgap.distr.Culture.toString () [inline]
Returns
String representation of the cultural memory
Author
Klaus Meffert
Since
2.3
Definition at line 219 of file Culture.java.
References org.jgap.distr.Culture.m_memory.
Referenced by org.jgap.distr.CultureTest.testToString_0(), and org.jgap.distr.CultureTest.testToString_1().
Member Data Documentation
final String org.jgap.distr.Culture.CVS_REVISION = `$Revision: 1.16 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file Culture.java.
CultureMemoryCell [] org.jgap.distr.Culture.m_memory [private]
The storage to use.
Definition at line 33 of file Culture.java.
Referenced by org.jgap.distr.Culture.clear(), org.jgap.distr.Culture.compareTo(), org.jgap.distr.Culture.Culture(), org.jgap.distr.Culture.get(), org.jgap.distr.Culture.set(), org.jgap.distr.Culture.setMatrix(), and org.jgap.distr.Culture.toString().
List org.jgap.distr.Culture.m_memoryNames = new Vector() [private]
Storage for named indices.
Definition at line 38 of file Culture.java.
Referenced by org.jgap.distr.Culture.compareTo(), and org.jgap.distr.Culture.getMemoryNames().
int org.jgap.distr.Culture.m_size [private]
Number of memory cells available.
Definition at line 43 of file Culture.java.
Referenced by org.jgap.distr.Culture.clear(), org.jgap.distr.Culture.compareTo(), and org.jgap.distr.Culture.Culture().
int org.jgap.distr.Culture.m_width [private]
Width of a matrixed memory (optional, but necessary to set if you want to treat the memory as a matrix).
Definition at line 49 of file Culture.java.
Referenced by org.jgap.distr.Culture.Culture(), org.jgap.distr.Culture.getMatrix(), org.jgap.distr.Culture.setMatrix(), and org.jgap.distr.Culture.setMatrixWidth().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/distr/Culture.java