org.jgap.gp.function.Not Class Reference
Public Member Functions
Not (final GPConfiguration a_conf) throws InvalidConfigurationException
String toString ()
String getName ()
boolean execute_boolean (ProgramChromosome c, int n, Object[] args)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.6 $`
Additional Inherited Members
Detailed Description
The boolean not operation.
Author
Klaus Meffert
Since
3.0
Definition at line 23 of file Not.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Not.Not (final GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Definition at line 28 of file Not.java.
References org.jgap.gp.CommandGene.BooleanClass.
Referenced by org.jgap.gp.function.Not.clone().
Member Function Documentation
Object org.jgap.gp.function.Not.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 59 of file Not.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.function.Not.Not().
boolean org.jgap.gp.function.Not.execute_boolean (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 47 of file Not.java.
String org.jgap.gp.function.Not.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 43 of file Not.java.
String org.jgap.gp.function.Not.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 33 of file Not.java.
Member Data Documentation
final String org.jgap.gp.function.Not.CVS_REVISION = `$Revision: 1.6 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file Not.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Not.java