org.jgap.gp.function.statistics.Variance Class Reference
Public Member Functions
Variance (GPConfiguration a_conf, int a_arityInitial, int a_arityMin, int a_arityMax, Class a_returnType) throws InvalidConfigurationException
String toString ()
double execute_double (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
Object clone ()
String getName ()
Additional Inherited Members
Detailed Description
Computes the variance of the available values. The unbiased `sample variance` definitional formula is used:
variance = sum((x_i - mean)^2) / (n - 1)
Author
Luis Garcia
Since
3.5
Definition at line 27 of file Variance.java.
Constructor & Destructor Documentation
org.jgap.gp.function.statistics.Variance.Variance (GPConfiguration a_conf, int a_arityInitial, int a_arityMin, int a_arityMax, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 29 of file Variance.java.
Referenced by org.jgap.gp.function.statistics.Variance.clone().
Member Function Documentation
Object org.jgap.gp.function.statistics.Variance.clone () [inline]
Returns
clone of the current object instance
Implements org.jgap.util.ICloneable.
Definition at line 70 of file Variance.java.
References org.jgap.gp.CommandGene.getArity(), org.jgap.gp.CommandGene.getArityMax(), org.jgap.gp.CommandGene.getArityMin(), org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.function.statistics.Variance.Variance().
double org.jgap.gp.function.statistics.Variance.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 51 of file Variance.java.
References org.jgap.gp.CommandGene.size().
float org.jgap.gp.function.statistics.Variance.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 61 of file Variance.java.
References org.jgap.gp.CommandGene.size().
String org.jgap.gp.function.statistics.Variance.getName () [inline]
Definition at line 82 of file Variance.java.
String org.jgap.gp.function.statistics.Variance.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 38 of file Variance.java.
References org.jgap.gp.CommandGene.size().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/statistics/Variance.java