org.jgap.distr.grid.JGAPRequest Class Reference
Public Member Functions
JGAPRequest (String a_name, int a_id, Configuration a_config, IWorkerEvolveStrategy a_strategy)
JGAPRequest (String a_name, int a_id, Configuration a_config)
JGAPRequest (String a_name, int a_id, Configuration a_config, Population a_pop, IWorkerEvolveStrategy a_strategy)
JGAPRequest (String a_name, int a_id, Configuration a_config, Population a_pop)
void setEvolveStrategy (IWorkerEvolveStrategy a_evolveStrategy)
IWorkerEvolveStrategy getWorkerEvolveStrategy ()
void setWorkerReturnStrategy (IWorkerReturnStrategy a_strategy)
IWorkerReturnStrategy getWorkerReturnStrategy ()
GridWorkerFeedback getWorkerFeedback ()
void setWorkerFeedback (GridWorkerFeedback a_feedback)
void setGenotypeInitializer (IGenotypeInitializer a_initializer)
IGenotypeInitializer getGenotypeInitializer ()
void setPopulation (Population a_pop)
Configuration getConfiguration ()
void setConfiguration (Configuration a_conf)
Population getPopulation ()
Object clone ()
JGAPRequest newInstance (String a_name, int a_ID)
Private Attributes
Configuration m_config
Population m_pop
IWorkerEvolveStrategy m_evolveStrategy
IWorkerReturnStrategy m_returnStrategy
IGenotypeInitializer m_genotypeInitializer
GridWorkerFeedback m_workerFeedback
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.10 $`
Additional Inherited Members
Detailed Description
An instance that creates single requests to be sent to a worker.
Author
Klaus Meffert
Since
3.1
Definition at line 23 of file JGAPRequest.java.
Constructor & Destructor Documentation
org.jgap.distr.grid.JGAPRequest.JGAPRequest (String a_name, int a_id, Configuration a_config, IWorkerEvolveStrategy a_strategy) [inline]
Constructor.
Parameters
a_name String
a_id int
a_config Configuration
a_strategy the strategy to choose for evolution
Author
Klaus Meffert
Since
3.1
Definition at line 52 of file JGAPRequest.java.
References org.jgap.distr.grid.JGAPRequest.m_config, and org.jgap.distr.grid.JGAPRequest.m_evolveStrategy.
Referenced by org.jgap.distr.grid.JGAPRequest.newInstance().
org.jgap.distr.grid.JGAPRequest.JGAPRequest (String a_name, int a_id, Configuration a_config) [inline]
Constructor.
Parameters
a_name session name
a_id request id
a_config Configuration
Author
Klaus Meffert
Since
3.1
Definition at line 69 of file JGAPRequest.java.
org.jgap.distr.grid.JGAPRequest.JGAPRequest (String a_name, int a_id, Configuration a_config, Population a_pop, IWorkerEvolveStrategy a_strategy) [inline]
Constructor. Allows to specify a preset population with which the genotype will be initialized.
Parameters
a_name session name
a_id request id
a_config Configuration
a_pop Population
a_strategy the strategy to choose for evolution
Author
Klaus Meffert
Since
3.2
Definition at line 86 of file JGAPRequest.java.
References org.jgap.distr.grid.JGAPRequest.m_pop.
org.jgap.distr.grid.JGAPRequest.JGAPRequest (String a_name, int a_id, Configuration a_config, Population a_pop) [inline]
Constructor. Allows to specify a preset population with which the genotype will be initialized.
Parameters
a_name session name
a_id request id
a_config Configuration
a_pop Population
Author
Klaus Meffert
Since
3.2
Definition at line 104 of file JGAPRequest.java.
Member Function Documentation
Object org.jgap.distr.grid.JGAPRequest.clone () [inline]
Returns
deep clone of current instance
Author
Klaus Meffert
Since
3.2
Implements org.jgap.util.ICloneable.
Definition at line 228 of file JGAPRequest.java.
References org.jgap.distr.grid.JGAPRequest.newInstance().
Configuration org.jgap.distr.grid.JGAPRequest.getConfiguration () [inline]
Returns
the configuration set
Author
Klaus Meffert
Since
3.1
Definition at line 195 of file JGAPRequest.java.
References org.jgap.distr.grid.JGAPRequest.m_config.
Referenced by org.jgap.distr.grid.DefaultWorkerReturnStrategy.assembleResult(), and org.jgap.distr.grid.JGAPRequest.newInstance().
IGenotypeInitializer org.jgap.distr.grid.JGAPRequest.getGenotypeInitializer () [inline]
Returns
the IGenotypeInitializer set
Author
Klaus Meffert
Since
3.2
Definition at line 171 of file JGAPRequest.java.
References org.jgap.distr.grid.JGAPRequest.m_genotypeInitializer.
Referenced by org.jgap.distr.grid.JGAPWorker.doWork(), and org.jgap.distr.grid.JGAPRequest.newInstance().
Population org.jgap.distr.grid.JGAPRequest.getPopulation () [inline]
Returns
the population used to initialize new requests. May be null or empty
Author
Klaus Meffert
Since
3.2
Definition at line 218 of file JGAPRequest.java.
References org.jgap.distr.grid.JGAPRequest.m_pop.
Referenced by org.jgap.distr.grid.JGAPRequest.newInstance().
IWorkerEvolveStrategy org.jgap.distr.grid.JGAPRequest.getWorkerEvolveStrategy () [inline]
Returns
the evolve strategy set
Author
Klaus Meffert
Since
3.2
Definition at line 128 of file JGAPRequest.java.
References org.jgap.distr.grid.JGAPRequest.m_evolveStrategy.
Referenced by org.jgap.distr.grid.JGAPWorker.doWork(), and org.jgap.distr.grid.JGAPRequest.newInstance().
GridWorkerFeedback org.jgap.distr.grid.JGAPRequest.getWorkerFeedback () [inline]
Definition at line 146 of file JGAPRequest.java.
References org.jgap.distr.grid.JGAPRequest.m_workerFeedback.
IWorkerReturnStrategy org.jgap.distr.grid.JGAPRequest.getWorkerReturnStrategy () [inline]
Returns
the strategy which part of a result is returned by a worker
Author
Klaus Meffert
Since
3.2
Definition at line 142 of file JGAPRequest.java.
References org.jgap.distr.grid.JGAPRequest.m_returnStrategy.
Referenced by org.jgap.distr.grid.JGAPRequest.newInstance().
JGAPRequest org.jgap.distr.grid.JGAPRequest.newInstance (String a_name, int a_ID) [inline]
Creates a new instance using the given name and ID. Reason for this method: ID cannot be set other than with construction!
Parameters
a_name the name to set
a_ID unique ID to set
Returns
newly created JGAPRequest object
Author
Klaus Meffert
Since
3.2
Definition at line 244 of file JGAPRequest.java.
References org.jgap.distr.grid.JGAPRequest.getConfiguration(), org.jgap.distr.grid.JGAPRequest.getGenotypeInitializer(), org.jgap.distr.grid.JGAPRequest.getPopulation(), org.jgap.distr.grid.JGAPRequest.getWorkerEvolveStrategy(), org.jgap.distr.grid.JGAPRequest.getWorkerReturnStrategy(), and org.jgap.distr.grid.JGAPRequest.JGAPRequest().
Referenced by org.jgap.distr.grid.JGAPRequest.clone(), org.jgap.distr.grid.RequestSplitStrategy.split(), and org.jgap.distr.grid.SampleSplitStrategy.split().
void org.jgap.distr.grid.JGAPRequest.setConfiguration (Configuration a_conf) [inline]
Set a modified configuration. Should only be used to re-set a configuration because some parts have not been serialized.
Parameters
a_conf the Configuration to set
Author
Klaus Meffert
Since
3.2
Definition at line 207 of file JGAPRequest.java.
References org.jgap.distr.grid.JGAPRequest.m_config.
void org.jgap.distr.grid.JGAPRequest.setEvolveStrategy (IWorkerEvolveStrategy a_evolveStrategy) [inline]
Sets the strategy to use for executing the evolution with a worker for a single request.
Parameters
a_evolveStrategy the evolve strategy to use
Author
Klaus Meffert
Since
3.2
Definition at line 118 of file JGAPRequest.java.
References org.jgap.distr.grid.JGAPRequest.m_evolveStrategy.
void org.jgap.distr.grid.JGAPRequest.setGenotypeInitializer (IGenotypeInitializer a_initializer) [inline]
Parameters
a_initializer the IGenotypeInitializer to use
Author
Klaus Meffert
Since
3.2
Definition at line 160 of file JGAPRequest.java.
References org.jgap.distr.grid.JGAPRequest.m_genotypeInitializer.
void org.jgap.distr.grid.JGAPRequest.setPopulation (Population a_pop) [inline]
Sets the Population to store in this request so that it can be passed to workers.
Parameters
a_pop the Population to store
Author
Klaus Meffert
Since
3.2
Definition at line 184 of file JGAPRequest.java.
References org.jgap.distr.grid.JGAPRequest.m_pop.
void org.jgap.distr.grid.JGAPRequest.setWorkerFeedback (GridWorkerFeedback a_feedback) [inline]
Definition at line 150 of file JGAPRequest.java.
References org.jgap.distr.grid.JGAPRequest.m_workerFeedback.
void org.jgap.distr.grid.JGAPRequest.setWorkerReturnStrategy (IWorkerReturnStrategy a_strategy) [inline]
Definition at line 132 of file JGAPRequest.java.
References org.jgap.distr.grid.JGAPRequest.m_returnStrategy.
Member Data Documentation
final String org.jgap.distr.grid.JGAPRequest.CVS_REVISION = `$Revision: 1.10 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file JGAPRequest.java.
Configuration org.jgap.distr.grid.JGAPRequest.m_config [private]
Definition at line 29 of file JGAPRequest.java.
Referenced by org.jgap.distr.grid.JGAPRequest.getConfiguration(), org.jgap.distr.grid.JGAPRequest.JGAPRequest(), and org.jgap.distr.grid.JGAPRequest.setConfiguration().
IWorkerEvolveStrategy org.jgap.distr.grid.JGAPRequest.m_evolveStrategy [private]
Definition at line 33 of file JGAPRequest.java.
Referenced by org.jgap.distr.grid.JGAPRequest.getWorkerEvolveStrategy(), org.jgap.distr.grid.JGAPRequest.JGAPRequest(), and org.jgap.distr.grid.JGAPRequest.setEvolveStrategy().
IGenotypeInitializer org.jgap.distr.grid.JGAPRequest.m_genotypeInitializer [private]
Definition at line 37 of file JGAPRequest.java.
Referenced by org.jgap.distr.grid.JGAPRequest.getGenotypeInitializer(), and org.jgap.distr.grid.JGAPRequest.setGenotypeInitializer().
Population org.jgap.distr.grid.JGAPRequest.m_pop [private]
Definition at line 31 of file JGAPRequest.java.
Referenced by org.jgap.distr.grid.JGAPRequest.getPopulation(), org.jgap.distr.grid.JGAPRequest.JGAPRequest(), and org.jgap.distr.grid.JGAPRequest.setPopulation().
IWorkerReturnStrategy org.jgap.distr.grid.JGAPRequest.m_returnStrategy [private]
Definition at line 35 of file JGAPRequest.java.
Referenced by org.jgap.distr.grid.JGAPRequest.getWorkerReturnStrategy(), and org.jgap.distr.grid.JGAPRequest.setWorkerReturnStrategy().
GridWorkerFeedback org.jgap.distr.grid.JGAPRequest.m_workerFeedback [private]
Definition at line 39 of file JGAPRequest.java.
Referenced by org.jgap.distr.grid.JGAPRequest.getWorkerFeedback(), and org.jgap.distr.grid.JGAPRequest.setWorkerFeedback().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/distr/grid/JGAPRequest.java