org.jgap.impl.DoubleGene Class Reference
Public Member Functions
DoubleGene () throws InvalidConfigurationException
DoubleGene (final Configuration a_config) throws InvalidConfigurationException
DoubleGene (final Configuration a_config, final double a_lowerBound, final double a_upperBound) throws InvalidConfigurationException
String getPersistentRepresentation ()
void setValueFromPersistentRepresentation (String a_representation) throws UnsupportedRepresentationException
double doubleValue ()
void setToRandomValue (RandomGenerator a_numberGenerator)
void applyMutation (int index, double a_percentage)
int hashCode ()
String toString ()
double getLowerBound ()
double getUpperBound ()
Protected Member Functions
Gene newGeneInternal ()
int compareToNative (Object o1, Object o2)
void mapValueToWithinBounds ()
Private Attributes
double m_upperBound
double m_lowerBound
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.40 $`
Additional Inherited Members
Detailed Description
A Gene implementation that supports a double values for its allele. Upper and lower bounds may optionally be provided to restrict the range of legal values allowed by this Gene instance.
Partly copied from IntegerGene.
Author
Klaus Meffert
Since
1.1
Definition at line 24 of file DoubleGene.java.
Constructor & Destructor Documentation
org.jgap.impl.DoubleGene.DoubleGene () throws InvalidConfigurationException [inline]
Constructs a new DoubleGene with default settings. No bounds will be put into effect for values (alleles) of this Gene instance, other than the standard range of double values.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Neil Rotstan
Klaus Meffert
Since
1.1
Definition at line 54 of file DoubleGene.java.
Referenced by org.jgap.impl.DoubleGene.newGeneInternal().
org.jgap.impl.DoubleGene.DoubleGene (final Configuration a_config) throws InvalidConfigurationException [inline]
Constructs a new DoubleGene with default settings. No bounds will be put into effect for values (alleles) of this Gene instance, other than the standard range of double values.
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 70 of file DoubleGene.java.
org.jgap.impl.DoubleGene.DoubleGene (final Configuration a_config, final double a_lowerBound, final double a_upperBound) throws InvalidConfigurationException [inline]
Constructs a new DoubleGene with the specified lower and upper bounds for values (alleles) of this Gene instance.
Parameters
a_config the configuration to use
a_lowerBound the lowest value that this Gene may possess, inclusively
a_upperBound the highest value that this Gene may possess, inclusively
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.0
Definition at line 90 of file DoubleGene.java.
References org.jgap.impl.DoubleGene.m_lowerBound, and org.jgap.impl.DoubleGene.m_upperBound.
Member Function Documentation
void org.jgap.impl.DoubleGene.applyMutation (int index, double a_percentage) [inline]
See interface Gene for description.
Parameters
index ignored (because there is only 1 atomic element)
a_percentage percentage of mutation (greater than -1 and smaller than 1)
Author
Klaus Meffert
Since
1.1
Implements org.jgap.Gene.
Definition at line 328 of file DoubleGene.java.
References org.jgap.impl.DoubleGene.doubleValue(), org.jgap.impl.DoubleGene.m_lowerBound, org.jgap.impl.DoubleGene.m_upperBound, and org.jgap.impl.NumberGene.setAllele().
int org.jgap.impl.DoubleGene.compareToNative (Object o1, Object o2) [inline], [protected], [virtual]
Compares to objects by first casting them into their expected type (e.g. Integer for IntegerGene) and then calling the compareTo-method of the casted type.
Parameters
o1 first object to be compared, which is always not null
o2 second object to be compared, which is always not null
Returns
a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than the object provided for comparison
Since
1.1
Implements org.jgap.impl.NumberGene.
Definition at line 271 of file DoubleGene.java.
double org.jgap.impl.DoubleGene.doubleValue () [inline]
Retrieves the double value of this Gene, which may be more convenient in some cases than the more general getAllele() method.
Returns
the double value of this Gene
Since
1.1
Definition at line 236 of file DoubleGene.java.
References org.jgap.BaseGene.getAllele().
Referenced by org.jgap.impl.DoubleGene.applyMutation(), org.jgap.impl.DoubleGeneTest.testApplyMutation_0(), org.jgap.impl.DoubleGeneTest.testApplyMutation_6(), org.jgap.impl.DoubleGeneTest.testDoubleValue_0(), org.jgap.impl.DoubleGeneTest.testDoubleValue_1(), org.jgap.impl.DoubleGeneTest.testSetAllele_4(), org.jgap.impl.DoubleGeneTest.testSetAllele_5(), org.jgap.impl.DoubleGeneTest.testSetAllele_6(), org.jgap.impl.CompositeGeneTest.testSetToRandomValue_1(), org.jgap.impl.CompositeGeneTest.testSetToRandomValue_2(), org.jgap.impl.DoubleGeneTest.testSetToRandomValue_3(), and org.jgap.impl.DoubleGeneTest.testSetToRandomValue_4().
double org.jgap.impl.DoubleGene.getLowerBound () [inline]
Returns
the lower bound set
Author
Klaus Meffert
Since
3.0
Definition at line 375 of file DoubleGene.java.
References org.jgap.impl.DoubleGene.m_lowerBound.
Referenced by org.jgap.impl.DoubleGeneTest.testBounds_0(), and org.jgap.impl.DoubleGeneTest.testBounds_1().
String org.jgap.impl.DoubleGene.getPersistentRepresentation () [inline]
Retrieves a string representation of this Gene that includes any information required to reconstruct it at a later time, such as its value and internal state. This string will be used to represent this Gene in XML persistence. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Returns
a string representation of this Gene's current state
Author
Klaus Meffert
Since
1.1
Implements org.jgap.IPersistentRepresentation.
Definition at line 133 of file DoubleGene.java.
References org.jgap.impl.NumberGene.getInternalValue(), org.jgap.impl.DoubleGene.m_lowerBound, org.jgap.impl.DoubleGene.m_upperBound, and org.jgap.Gene.PERSISTENT_FIELD_DELIMITER.
double org.jgap.impl.DoubleGene.getUpperBound () [inline]
Returns
the upper bound set
Author
Klaus Meffert
Since
3.0
Definition at line 384 of file DoubleGene.java.
References org.jgap.impl.DoubleGene.m_upperBound.
Referenced by org.jgap.impl.DoubleGeneTest.testBounds_0(), and org.jgap.impl.DoubleGeneTest.testBounds_1().
int org.jgap.impl.DoubleGene.hashCode () [inline]
Modified hashCode() function to return different hashcodes for differently ordered genes in a chromosome.
Returns
-3 if no allele set, otherwise value return by BaseGene.hashCode()
Author
Klaus Meffert
Since
2.2
Definition at line 342 of file DoubleGene.java.
References org.jgap.impl.NumberGene.getInternalValue().
Referenced by org.jgap.impl.DoubleGeneTest.testHashCode_0(), and org.jgap.impl.DoubleGeneTest.testHashCode_1().
void org.jgap.impl.DoubleGene.mapValueToWithinBounds () [inline], [protected], [virtual]
Maps the value of this DoubleGene to within the bounds specified by the m_upperBounds and m_lowerBounds instance variables. The value's relative position within the double range will be preserved within the bounds range (in other words, if the value is about halfway between the double max and min, then the resulting value will be about halfway between the upper bounds and lower bounds). If the value is null or is already within the bounds, it will be left unchanged.
Author
Neil Rotstan
Klaus Meffert
Since
1.1
Implements org.jgap.impl.NumberGene.
Definition at line 288 of file DoubleGene.java.
References org.jgap.BaseGene.getAllele(), org.jgap.BaseGene.getConfiguration(), org.jgap.impl.DoubleGene.m_lowerBound, org.jgap.impl.DoubleGene.m_upperBound, org.jgap.RandomGenerator.nextDouble(), and org.jgap.impl.NumberGene.setAllele().
Gene org.jgap.impl.DoubleGene.newGeneInternal () [inline], [protected], [virtual]
Provides an implementation-independent means for creating new Gene instances.
Returns
a new Gene instance of the same type and with the same setup as this concrete Gene
Author
Klaus Meffert
Since
1.1
Implements org.jgap.BaseGene.
Definition at line 108 of file DoubleGene.java.
References org.jgap.impl.DoubleGene.DoubleGene(), org.jgap.BaseGene.getConfiguration(), org.jgap.impl.DoubleGene.m_lowerBound, and org.jgap.impl.DoubleGene.m_upperBound.
void org.jgap.impl.DoubleGene.setToRandomValue (RandomGenerator a_numberGenerator) [inline]
Sets the value (allele) of this Gene to a random Double value between the lower and upper bounds (if any) of this Gene.
Parameters
a_numberGenerator the random number generator that should be used to create any random values. It's important to use this generator to maintain the user's flexibility to configure the genetic engine to use the random number generator of their choice
Author
Klaus Meffert
Since
1.1
Implements org.jgap.Gene.
Definition at line 252 of file DoubleGene.java.
References org.jgap.impl.DoubleGene.m_lowerBound, org.jgap.impl.DoubleGene.m_upperBound, org.jgap.RandomGenerator.nextDouble(), and org.jgap.impl.NumberGene.setAllele().
void org.jgap.impl.DoubleGene.setValueFromPersistentRepresentation (String a_representation) throws UnsupportedRepresentationException [inline]
Sets the value and internal state of this Gene from the string representation returned by a previous invocation of the getPersistentRepresentation() method. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Parameters
a_representation the string representation retrieved from a prior call to the getPersistentRepresentation() method
Exceptions
UnsupportedOperationException to indicate that no implementation is provided for this method
UnsupportedRepresentationException if this Gene implementation does not support the given string representation
Author
Klaus Meffert
Since
1.1
Todo
Todo unify first part of method with IntegerGene
Implements org.jgap.IPersistentRepresentation.
Definition at line 167 of file DoubleGene.java.
References org.jgap.impl.DoubleGene.m_lowerBound, org.jgap.impl.DoubleGene.m_upperBound, org.jgap.Gene.PERSISTENT_FIELD_DELIMITER, and org.jgap.impl.NumberGene.setAllele().
String org.jgap.impl.DoubleGene.toString () [inline]
Returns
string representation of this Gene's value that may be useful for display purposes
Author
Klaus Meffert
Since
2.4
Implements org.jgap.Gene.
Definition at line 358 of file DoubleGene.java.
References org.jgap.impl.NumberGene.getInternalValue(), org.jgap.impl.DoubleGene.m_lowerBound, and org.jgap.impl.DoubleGene.m_upperBound.
Member Data Documentation
final String org.jgap.impl.DoubleGene.CVS_REVISION = `$Revision: 1.40 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file DoubleGene.java.
double org.jgap.impl.DoubleGene.m_lowerBound [private]
The lower bounds of values represented by this Gene. If not explicitly provided by the user, this should be set to Double.MIN_VALUE
Definition at line 39 of file DoubleGene.java.
Referenced by org.jgap.impl.DoubleGene.applyMutation(), org.jgap.impl.DoubleGene.DoubleGene(), org.jgap.impl.DoubleGene.getLowerBound(), org.jgap.impl.DoubleGene.getPersistentRepresentation(), org.jgap.impl.DoubleGene.mapValueToWithinBounds(), org.jgap.impl.DoubleGene.newGeneInternal(), org.jgap.impl.DoubleGene.setToRandomValue(), org.jgap.impl.DoubleGene.setValueFromPersistentRepresentation(), and org.jgap.impl.DoubleGene.toString().
double org.jgap.impl.DoubleGene.m_upperBound [private]
The upper bounds of values represented by this Gene. If not explicitly provided by the user, this should be set to Double.MAX_VALUE.
Definition at line 33 of file DoubleGene.java.
Referenced by org.jgap.impl.DoubleGene.applyMutation(), org.jgap.impl.DoubleGene.DoubleGene(), org.jgap.impl.DoubleGene.getPersistentRepresentation(), org.jgap.impl.DoubleGene.getUpperBound(), org.jgap.impl.DoubleGene.mapValueToWithinBounds(), org.jgap.impl.DoubleGene.newGeneInternal(), org.jgap.impl.DoubleGene.setToRandomValue(), org.jgap.impl.DoubleGene.setValueFromPersistentRepresentation(), and org.jgap.impl.DoubleGene.toString().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/DoubleGene.java