org.jgap.impl.DefaultCrossoverRateCalculatorTest Class Reference
Public Member Functions
void setUp ()
void testCalculateCurrentRate_0 () throws Exception
void testCalculateCurrentRate_01 () throws Exception
void testCalculateCurrentRate_1 () throws Exception
void testToBePermutated_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.12 $`
Additional Inherited Members
Detailed Description
Tests the DefaultCrossoverRateCalculator class.
Author
Klaus Meffert
Since
2.0
Definition at line 21 of file DefaultCrossoverRateCalculatorTest.java.
Member Function Documentation
void org.jgap.impl.DefaultCrossoverRateCalculatorTest.setUp () [inline]
Definition at line 31 of file DefaultCrossoverRateCalculatorTest.java.
static Test org.jgap.impl.DefaultCrossoverRateCalculatorTest.suite () [inline], [static]
Definition at line 26 of file DefaultCrossoverRateCalculatorTest.java.
void org.jgap.impl.DefaultCrossoverRateCalculatorTest.testCalculateCurrentRate_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 43 of file DefaultCrossoverRateCalculatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.getChromosomeSize().
void org.jgap.impl.DefaultCrossoverRateCalculatorTest.testCalculateCurrentRate_01 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 59 of file DefaultCrossoverRateCalculatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.getChromosomeSize().
void org.jgap.impl.DefaultCrossoverRateCalculatorTest.testCalculateCurrentRate_1 () throws Exception [inline]
If there are zero chromosomes in the config., the crossover rate nevertheless should be 1, because Random needs positive integers as input (see CrossoverOperator.operate for calling Random class)
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 78 of file DefaultCrossoverRateCalculatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DefaultCrossoverRateCalculatorTest.testToBePermutated_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 91 of file DefaultCrossoverRateCalculatorTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.IUniversalRateCalculator.toBePermutated().
Member Data Documentation
final String org.jgap.impl.DefaultCrossoverRateCalculatorTest.CVS_REVISION = `$Revision: 1.12 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file DefaultCrossoverRateCalculatorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/DefaultCrossoverRateCalculatorTest.java