examples.monalisa.core.SingleMutationOperator Class Reference
Public Member Functions
SingleMutationOperator (final Configuration a_config, final int a_desiredMutationRate) throws InvalidConfigurationException
void operate (final Population a_population, final List a_candidateChromosomes)
Private Member Functions
void mutateGene (final Gene a_gene, final RandomGenerator a_generator)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Detailed Description
Mutates only one gene of each chromosome.
Author
Yann N. Dauphin
Since
3.4
Definition at line 22 of file SingleMutationOperator.java.
Constructor & Destructor Documentation
examples.monalisa.core.SingleMutationOperator.SingleMutationOperator (final Configuration a_config, final int a_desiredMutationRate) throws InvalidConfigurationException [inline]
Definition at line 27 of file SingleMutationOperator.java.
Member Function Documentation
void examples.monalisa.core.SingleMutationOperator.mutateGene (final Gene a_gene, final RandomGenerator a_generator) [inline], [private]
Definition at line 163 of file SingleMutationOperator.java.
Referenced by examples.monalisa.core.SingleMutationOperator.operate().
void examples.monalisa.core.SingleMutationOperator.operate (final Population a_population, final List a_candidateChromosomes) [inline]
Todo
Todo move to base class, refactor
Definition at line 34 of file SingleMutationOperator.java.
References examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfGenesPerPolygon(), examples.monalisa.core.SingleMutationOperator.mutateGene(), and examples.monalisa.core.GAInitialChromosomeFactory.POINTS.
Member Data Documentation
final String examples.monalisa.core.SingleMutationOperator.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file SingleMutationOperator.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/monalisa/core/SingleMutationOperator.java