org.jgap.gp.terminal.False Class Reference
Public Member Functions
False (final GPConfiguration a_conf) throws InvalidConfigurationException
False (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException
CommandGene applyMutation (int index, double a_percentage) throws InvalidConfigurationException
Object clone ()
String toString ()
String getName ()
boolean execute_boolean (ProgramChromosome c, int n, Object[] args)
Class getChildType (IGPProgram a_ind, int a_index)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.9 $`
Additional Inherited Members
Detailed Description
The boolean value false.
Author
Klaus Meffert
Since
3.0
Definition at line 23 of file False.java.
Constructor & Destructor Documentation
org.jgap.gp.terminal.False.False (final GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Definition at line 28 of file False.java.
References org.jgap.gp.CommandGene.BooleanClass.
Referenced by org.jgap.gp.terminal.False.clone().
org.jgap.gp.terminal.False.False (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 33 of file False.java.
Member Function Documentation
CommandGene org.jgap.gp.terminal.False.applyMutation (int a_index, double a_percentage) throws InvalidConfigurationException [inline]
Mutates a CommandGene.
Parameters
a_index references the part of a multipart object, normally not relevant
a_percentage the mutation rate (0.0 to 1.0)
Returns
the mutant
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IMutateable.
Definition at line 38 of file False.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.CommandGene.getReturnType().
Object org.jgap.gp.terminal.False.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 52 of file False.java.
References org.jgap.gp.terminal.False.False(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.CommandGene.getReturnType().
boolean org.jgap.gp.terminal.False.execute_boolean (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 75 of file False.java.
Class org.jgap.gp.terminal.False.getChildType (IGPProgram a_ind, int a_index) [inline]
Definition at line 79 of file False.java.
String org.jgap.gp.terminal.False.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 71 of file False.java.
String org.jgap.gp.terminal.False.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 61 of file False.java.
Member Data Documentation
final String org.jgap.gp.terminal.False.CVS_REVISION = `$Revision: 1.9 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file False.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/terminal/False.java