org.jgap.gp.function.ReadTerminalIndexed Class Reference
Public Member Functions
ReadTerminalIndexed (final GPConfiguration a_conf, Class a_returnType, int a_index) throws InvalidConfigurationException
ReadTerminalIndexed (final GPConfiguration a_conf, Class a_returnType, int a_index, int a_subReturnType) throws InvalidConfigurationException
String toString ()
String getName ()
int execute_int (ProgramChromosome c, int n, Object[] args)
long execute_long (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
int compareTo (Object a_other)
boolean equals (Object a_other)
Object clone ()
Private Attributes
int m_index
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.6 $`
Additional Inherited Members
Detailed Description
Reads a value from the internal indexed memory.
Author
Klaus Meffert
Since
3.2
Definition at line 24 of file ReadTerminalIndexed.java.
Constructor & Destructor Documentation
org.jgap.gp.function.ReadTerminalIndexed.ReadTerminalIndexed (final GPConfiguration a_conf, Class a_returnType, int a_index) throws InvalidConfigurationException [inline]
Definition at line 34 of file ReadTerminalIndexed.java.
Referenced by org.jgap.gp.function.ReadTerminalIndexed.clone(), org.jgap.gp.function.ReadTerminalIndexed.compareTo(), and org.jgap.gp.function.ReadTerminalIndexed.equals().
org.jgap.gp.function.ReadTerminalIndexed.ReadTerminalIndexed (final GPConfiguration a_conf, Class a_returnType, int a_index, int a_subReturnType) throws InvalidConfigurationException [inline]
Definition at line 40 of file ReadTerminalIndexed.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.function.ReadTerminalIndexed.m_index.
Member Function Documentation
Object org.jgap.gp.function.ReadTerminalIndexed.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 191 of file ReadTerminalIndexed.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), org.jgap.gp.CommandGene.getSubReturnType(), org.jgap.gp.function.ReadTerminalIndexed.m_index, and org.jgap.gp.function.ReadTerminalIndexed.ReadTerminalIndexed().
int org.jgap.gp.function.ReadTerminalIndexed.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.0
Definition at line 152 of file ReadTerminalIndexed.java.
References org.jgap.gp.function.ReadTerminalIndexed.m_index, and org.jgap.gp.function.ReadTerminalIndexed.ReadTerminalIndexed().
boolean org.jgap.gp.function.ReadTerminalIndexed.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Klaus Meffert
Since
3.0
Definition at line 172 of file ReadTerminalIndexed.java.
References org.jgap.gp.function.ReadTerminalIndexed.m_index, and org.jgap.gp.function.ReadTerminalIndexed.ReadTerminalIndexed().
double org.jgap.gp.function.ReadTerminalIndexed.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 99 of file ReadTerminalIndexed.java.
References org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.function.ReadTerminalIndexed.m_index.
float org.jgap.gp.function.ReadTerminalIndexed.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 114 of file ReadTerminalIndexed.java.
References org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.function.ReadTerminalIndexed.m_index.
int org.jgap.gp.function.ReadTerminalIndexed.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 64 of file ReadTerminalIndexed.java.
References org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.function.ReadTerminalIndexed.m_index.
long org.jgap.gp.function.ReadTerminalIndexed.execute_long (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 84 of file ReadTerminalIndexed.java.
References org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.function.ReadTerminalIndexed.m_index.
Object org.jgap.gp.function.ReadTerminalIndexed.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 129 of file ReadTerminalIndexed.java.
References org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.function.ReadTerminalIndexed.m_index.
String org.jgap.gp.function.ReadTerminalIndexed.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 60 of file ReadTerminalIndexed.java.
String org.jgap.gp.function.ReadTerminalIndexed.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 50 of file ReadTerminalIndexed.java.
References org.jgap.gp.function.ReadTerminalIndexed.m_index.
Member Data Documentation
final String org.jgap.gp.function.ReadTerminalIndexed.CVS_REVISION = `$Revision: 1.6 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file ReadTerminalIndexed.java.
int org.jgap.gp.function.ReadTerminalIndexed.m_index [private]
Index of the memory cell to read.
Definition at line 32 of file ReadTerminalIndexed.java.
Referenced by org.jgap.gp.function.ReadTerminalIndexed.clone(), org.jgap.gp.function.ReadTerminalIndexed.compareTo(), org.jgap.gp.function.ReadTerminalIndexed.equals(), org.jgap.gp.function.ReadTerminalIndexed.execute_double(), org.jgap.gp.function.ReadTerminalIndexed.execute_float(), org.jgap.gp.function.ReadTerminalIndexed.execute_int(), org.jgap.gp.function.ReadTerminalIndexed.execute_long(), org.jgap.gp.function.ReadTerminalIndexed.execute_object(), org.jgap.gp.function.ReadTerminalIndexed.ReadTerminalIndexed(), and org.jgap.gp.function.ReadTerminalIndexed.toString().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/ReadTerminalIndexed.java