org.jgap.data.config.MetaConfig Class Reference
Public Member Functions
List getConfigProperty (String className)
Reader getReader (String a_filename) throws IOException
Static Public Member Functions
static MetaConfig getInstance () throws MetaConfigException, IOException
Protected Member Functions
void init () throws MetaConfigException, IOException
Private Member Functions
MetaConfig () throws MetaConfigException, IOException
boolean isComment (String line)
void parseLine (String a_line) throws MetaConfigException
void handleClass (final String a_token)
void handleProperty (final String a_token) throws MetaConfigException
void handleValues (final String a_token) throws MetaConfigException
void endState () throws MetaConfigException
void add (final String currName, ConfigProperty a_cp)
Private Attributes
Hashtable m_metaMap = new Hashtable()
int m_state
String m_currName
ConfigProperty m_currProperty
Static Private Attributes
static final String METACON_FILENAME = `jgap-meta.con`
static final String CN = `MetaConfig`
static MetaConfig instance
static final int INIT = 0
static final int CLASS = 1
static final int PROPERTY = 2
static final int VALUES = 3
Detailed Description
This class provides an interface to the configuration information to create a JGAP Configuration GUI.
Author
Siddhartha Azad
Since
2.4
Definition at line 23 of file MetaConfig.java.
Constructor & Destructor Documentation
org.jgap.data.config.MetaConfig.MetaConfig () throws MetaConfigException, IOException [inline], [private]
Definition at line 59 of file MetaConfig.java.
References org.jgap.data.config.MetaConfig.INIT, org.jgap.data.config.MetaConfig.init(), and org.jgap.data.config.MetaConfig.m_state.
Referenced by org.jgap.data.config.MetaConfig.getInstance().
Member Function Documentation
void org.jgap.data.config.MetaConfig.add (final String currName, ConfigProperty a_cp) [inline], [private]
Add a new ConfigProperty for a certain class to the hashtable of properties.
Parameters
currName name of the class to which the property belongs
a_cp the ConfigProperty to be added to the class
Author
Siddhartha Azad
Since
2.4
Definition at line 275 of file MetaConfig.java.
References org.jgap.data.config.MetaConfig.m_metaMap.
Referenced by org.jgap.data.config.MetaConfig.endState(), org.jgap.data.config.MetaConfig.handleClass(), and org.jgap.data.config.MetaConfig.handleProperty().
void org.jgap.data.config.MetaConfig.endState () throws MetaConfigException [inline], [private]
Called once the EOF is encountered while parsing the file.
Exceptions
MetaConfigException if parsing ends in an invalid state
Author
Siddhartha Azad
Since
2.4
Definition at line 253 of file MetaConfig.java.
References org.jgap.data.config.MetaConfig.add(), org.jgap.data.config.MetaConfig.m_currName, org.jgap.data.config.MetaConfig.m_currProperty, org.jgap.data.config.MetaConfig.m_state, org.jgap.data.config.MetaConfig.METACON_FILENAME, org.jgap.data.config.MetaConfig.PROPERTY, and org.jgap.data.config.MetaConfig.VALUES.
Referenced by org.jgap.data.config.MetaConfig.init().
List org.jgap.data.config.MetaConfig.getConfigProperty (String className) [inline]
Read the meta-config file and load it in memory.
Parameters
className the name of the class of which the properties are required
Returns
the list of properties for this class, if class is registered, otherwise null
Author
Siddhartha Azad
Since
2.4
Definition at line 77 of file MetaConfig.java.
static MetaConfig org.jgap.data.config.MetaConfig.getInstance () throws MetaConfigException, IOException [inline], [static]
Definition at line 51 of file MetaConfig.java.
References org.jgap.data.config.MetaConfig.instance, and org.jgap.data.config.MetaConfig.MetaConfig().
Referenced by org.jgap.data.config.MetaConfigTest.testSingleton_0().
Reader org.jgap.data.config.MetaConfig.getReader (String a_filename) throws IOException [inline]
Returns a reader to a file
Parameters
a_filename the file to retrieve a reader for
Exceptions
IOException
Returns
the Reader
Author
Klaus Meffert
Since
3.0
Definition at line 116 of file MetaConfig.java.
Referenced by org.jgap.data.config.MetaConfig.init().
void org.jgap.data.config.MetaConfig.handleClass (final String a_token) [inline], [private]
Handle the state when a 'class' tag is found.
Author
Siddhartha Azad
Since
2.4
Definition at line 185 of file MetaConfig.java.
References org.jgap.data.config.MetaConfig.add(), org.jgap.data.config.MetaConfig.CLASS, org.jgap.data.config.MetaConfig.m_currName, org.jgap.data.config.MetaConfig.m_currProperty, and org.jgap.data.config.MetaConfig.m_state.
Referenced by org.jgap.data.config.MetaConfig.parseLine().
void org.jgap.data.config.MetaConfig.handleProperty (final String a_token) throws MetaConfigException [inline], [private]
Handle the state when a 'property' tag is found.
Exceptions
MetaConfigException
Author
Siddhartha Azad
Since
2.4
Definition at line 201 of file MetaConfig.java.
References org.jgap.data.config.MetaConfig.add(), org.jgap.data.config.MetaConfig.m_currName, org.jgap.data.config.MetaConfig.m_currProperty, org.jgap.data.config.MetaConfig.m_state, org.jgap.data.config.MetaConfig.PROPERTY, and org.jgap.data.config.MetaConfig.VALUES.
Referenced by org.jgap.data.config.MetaConfig.parseLine().
void org.jgap.data.config.MetaConfig.handleValues (final String a_token) throws MetaConfigException [inline], [private]
Handle the state when a 'values' tag is found.
Parameters
a_token the rhs of the values property
Exceptions
MetaConfigException
Author
Siddhartha Azad
Since
2.4
Definition at line 232 of file MetaConfig.java.
References org.jgap.data.config.MetaConfig.m_state, and org.jgap.data.config.MetaConfig.VALUES.
Referenced by org.jgap.data.config.MetaConfig.parseLine().
void org.jgap.data.config.MetaConfig.init () throws MetaConfigException, IOException [inline], [protected]
Read the meta-config file and load it in memory. Having to read my own property file without using the Java Property class since I need to preserve the order of these properties, plus I have duplicate labels.
Exceptions
MetaConfigException
IOException
Author
Siddhartha Azad
Since
2.4
Definition at line 92 of file MetaConfig.java.
References org.jgap.data.config.MetaConfig.endState(), org.jgap.data.config.MetaConfig.getReader(), org.jgap.data.config.MetaConfig.isComment(), org.jgap.data.config.MetaConfig.METACON_FILENAME, and org.jgap.data.config.MetaConfig.parseLine().
Referenced by org.jgap.data.config.MetaConfig.MetaConfig().
boolean org.jgap.data.config.MetaConfig.isComment (String line) [inline], [private]
Check whether a line is a comment. Any line starting with a '#' is a comment.
Returns
true if a line is a comment, false if it is not
Author
Siddhartha Azad
Since
2.4
Definition at line 130 of file MetaConfig.java.
Referenced by org.jgap.data.config.MetaConfig.init().
void org.jgap.data.config.MetaConfig.parseLine (String a_line) throws MetaConfigException [inline], [private]
Parse a line. This method is dispatches lines to other methods, hence acting like a state machine.
Exceptions
MetaConfigException
Author
Siddhartha Azad
Since
2.4
Definition at line 147 of file MetaConfig.java.
References org.jgap.data.config.MetaConfig.CLASS, org.jgap.data.config.MetaConfig.CN, org.jgap.data.config.MetaConfig.handleClass(), org.jgap.data.config.MetaConfig.handleProperty(), org.jgap.data.config.MetaConfig.handleValues(), org.jgap.data.config.MetaConfig.INIT, org.jgap.data.config.MetaConfig.m_state, org.jgap.data.config.MetaConfig.METACON_FILENAME, org.jgap.data.config.MetaConfig.PROPERTY, and org.jgap.data.config.MetaConfig.VALUES.
Referenced by org.jgap.data.config.MetaConfig.init().
Member Data Documentation
final int org.jgap.data.config.MetaConfig.CLASS = 1 [static], [private]
Definition at line 40 of file MetaConfig.java.
Referenced by org.jgap.data.config.MetaConfig.handleClass(), and org.jgap.data.config.MetaConfig.parseLine().
final String org.jgap.data.config.MetaConfig.CN = `MetaConfig` [static], [private]
Definition at line 27 of file MetaConfig.java.
Referenced by org.jgap.data.config.MetaConfig.parseLine().
final int org.jgap.data.config.MetaConfig.INIT = 0 [static], [private]
Definition at line 38 of file MetaConfig.java.
Referenced by org.jgap.data.config.MetaConfig.MetaConfig(), and org.jgap.data.config.MetaConfig.parseLine().
MetaConfig org.jgap.data.config.MetaConfig.instance [static], [private]
Definition at line 30 of file MetaConfig.java.
Referenced by org.jgap.data.config.MetaConfig.getInstance().
String org.jgap.data.config.MetaConfig.m_currName [private]
Definition at line 47 of file MetaConfig.java.
Referenced by org.jgap.data.config.MetaConfig.endState(), org.jgap.data.config.MetaConfig.handleClass(), and org.jgap.data.config.MetaConfig.handleProperty().
ConfigProperty org.jgap.data.config.MetaConfig.m_currProperty [private]
Definition at line 49 of file MetaConfig.java.
Referenced by org.jgap.data.config.MetaConfig.endState(), org.jgap.data.config.MetaConfig.handleClass(), and org.jgap.data.config.MetaConfig.handleProperty().
Hashtable org.jgap.data.config.MetaConfig.m_metaMap = new Hashtable() [private]
Definition at line 33 of file MetaConfig.java.
Referenced by org.jgap.data.config.MetaConfig.add().
int org.jgap.data.config.MetaConfig.m_state [private]
Definition at line 36 of file MetaConfig.java.
Referenced by org.jgap.data.config.MetaConfig.endState(), org.jgap.data.config.MetaConfig.handleClass(), org.jgap.data.config.MetaConfig.handleProperty(), org.jgap.data.config.MetaConfig.handleValues(), org.jgap.data.config.MetaConfig.MetaConfig(), and org.jgap.data.config.MetaConfig.parseLine().
final String org.jgap.data.config.MetaConfig.METACON_FILENAME = `jgap-meta.con` [static], [private]
Definition at line 25 of file MetaConfig.java.
Referenced by org.jgap.data.config.MetaConfig.endState(), org.jgap.data.config.MetaConfig.init(), and org.jgap.data.config.MetaConfig.parseLine().
final int org.jgap.data.config.MetaConfig.PROPERTY = 2 [static], [private]
Definition at line 42 of file MetaConfig.java.
Referenced by org.jgap.data.config.MetaConfig.endState(), org.jgap.data.config.MetaConfig.handleProperty(), and org.jgap.data.config.MetaConfig.parseLine().
final int org.jgap.data.config.MetaConfig.VALUES = 3 [static], [private]
Definition at line 44 of file MetaConfig.java.
Referenced by org.jgap.data.config.MetaConfig.endState(), org.jgap.data.config.MetaConfig.handleProperty(), org.jgap.data.config.MetaConfig.handleValues(), and org.jgap.data.config.MetaConfig.parseLine().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/data/config/MetaConfig.java