examples.gp.tictactoe.PutStone1 Class Reference
Public Member Functions
PutStone1 (final GPConfiguration a_conf, Board a_board, int a_color) throws InvalidConfigurationException
PutStone1 (final GPConfiguration a_conf, Board a_board, int a_color, int a_subReturnType, int a_subChildType) throws InvalidConfigurationException
String toString ()
void execute_void (ProgramChromosome c, int n, Object[] args)
Class getChildType (IGPProgram a_ind, int a_chromNum)
Object clone ()
Protected Member Functions
void check (ProgramChromosome a_program)
Private Attributes
Board m_board
int m_color
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
Puts a stone on a board. Accepts one parameters, representing X and Y coordinates on the board at the same time.
Author
Klaus Meffert
Since
3.2?
Definition at line 24 of file PutStone1.java.
Constructor & Destructor Documentation
examples.gp.tictactoe.PutStone1.PutStone1 (final GPConfiguration a_conf, Board a_board, int a_color) throws InvalidConfigurationException [inline]
Definition at line 33 of file PutStone1.java.
Referenced by examples.gp.tictactoe.PutStone1.clone().
examples.gp.tictactoe.PutStone1.PutStone1 (final GPConfiguration a_conf, Board a_board, int a_color, int a_subReturnType, int a_subChildType) throws InvalidConfigurationException [inline]
Definition at line 38 of file PutStone1.java.
References examples.gp.tictactoe.PutStone1.m_board, examples.gp.tictactoe.PutStone1.m_color, and org.jgap.gp.CommandGene.VoidClass.
Member Function Documentation
void examples.gp.tictactoe.PutStone1.check (ProgramChromosome a_program) [inline], [protected]
Definition at line 69 of file PutStone1.java.
References examples.gp.tictactoe.Board.getLastColor(), examples.gp.tictactoe.PutStone1.m_board, and examples.gp.tictactoe.PutStone1.m_color.
Referenced by examples.gp.tictactoe.PutStone1.execute_void().
Object examples.gp.tictactoe.PutStone1.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 97 of file PutStone1.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getSubChildType(), org.jgap.gp.CommandGene.getSubReturnType(), examples.gp.tictactoe.PutStone1.m_board, examples.gp.tictactoe.PutStone1.m_color, and examples.gp.tictactoe.PutStone1.PutStone1().
void examples.gp.tictactoe.PutStone1.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 50 of file PutStone1.java.
References examples.gp.tictactoe.PutStone1.check(), org.jgap.gp.impl.ProgramChromosome.getGene(), org.jgap.gp.CommandGene.getName(), examples.gp.tictactoe.Board.HEIGHT, examples.gp.tictactoe.PutStone1.m_color, and examples.gp.tictactoe.Board.WIDTH.
Class examples.gp.tictactoe.PutStone1.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Determines which type a specific child of this command has.
Parameters
a_ind ignored here
a_chromNum index of child
Returns
type of the a_chromNum'th child
Author
Klaus Meffert
Since
3.2
Definition at line 85 of file PutStone1.java.
References org.jgap.gp.CommandGene.IntegerClass.
String examples.gp.tictactoe.PutStone1.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 46 of file PutStone1.java.
Member Data Documentation
final String examples.gp.tictactoe.PutStone1.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file PutStone1.java.
Board examples.gp.tictactoe.PutStone1.m_board [private]
Definition at line 29 of file PutStone1.java.
Referenced by examples.gp.tictactoe.PutStone1.check(), examples.gp.tictactoe.PutStone1.clone(), and examples.gp.tictactoe.PutStone1.PutStone1().
int examples.gp.tictactoe.PutStone1.m_color [private]
Definition at line 31 of file PutStone1.java.
Referenced by examples.gp.tictactoe.PutStone1.check(), examples.gp.tictactoe.PutStone1.clone(), examples.gp.tictactoe.PutStone1.execute_void(), and examples.gp.tictactoe.PutStone1.PutStone1().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/tictactoe/PutStone1.java