org.jgap.BaseGeneTest Class Reference
Classes
class AppDataForTesting
class BaseGeneImpl
Public Member Functions
void testConstruct_0 () throws Exception
void testToString_0 () throws Exception
void testToString_1 () throws Exception
void testToString_2 () throws Exception
void testGetAllele_0 () throws Exception
void testSize_0 () throws Exception
void testEquals_0 () throws Exception
void testEquals_1 () throws Exception
void testEquals_2 () throws Exception
void testEquals_3 () throws Exception
void testCleanup_0 () throws Exception
void testHashCode_0 () throws Exception
void testHashCode_1 () throws Exception
void testSetEnergy_0 () throws Exception
void testSetEnergy_1 () throws Exception
void testSetApplicationData_0 () throws Exception
void testSetApplicationData_1 () throws Exception
void testSetApplicationData_2 () throws Exception
void testIsCompareApplicationData_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.28 $`
Additional Inherited Members
Detailed Description
Tests the BaseGene class.
Author
Klaus Meffert
Since
2.3
Definition at line 21 of file BaseGeneTest.java.
Member Function Documentation
static Test org.jgap.BaseGeneTest.suite () [inline], [static]
Definition at line 26 of file BaseGeneTest.java.
void org.jgap.BaseGeneTest.testCleanup_0 () throws Exception [inline]
Simple cleanup should be possible without exception.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 189 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.BaseGeneTest.testConstruct_0 () throws Exception [inline]
Following should be possible without exception.
Exceptions
Exception
Author
Klaus Meffert
Since
2.3
Definition at line 38 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.BaseGeneTest.testEquals_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 116 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.BaseGeneTest.testEquals_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 131 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.BaseGeneTest.testEquals_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 146 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.BaseGeneTest.testEquals_3 () throws Exception [inline]
Compare application data.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Todo
Todo use other than JGAPFactory to be able to receive a null CompareToHandler for the application data object
Definition at line 163 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.BaseGeneTest.testGetAllele_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 91 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.BaseGeneTest.testHashCode_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.3
Definition at line 202 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.BaseGeneTest.testHashCode_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 214 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.BaseGeneTest.testIsCompareApplicationData_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 338 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.BaseGeneTest.testSetApplicationData_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 259 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.BaseGeneTest.testSetApplicationData_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2.2
Todo
Todo find the one chromosome
Definition at line 277 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.BaseGeneTest.testSetApplicationData_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.3
Todo
Todo find the one chromosome
Definition at line 304 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.BaseGeneTest.testSetEnergy_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 227 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.DELTA.
void org.jgap.BaseGeneTest.testSetEnergy_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 241 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.DELTA.
void org.jgap.BaseGeneTest.testSize_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 104 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.size().
void org.jgap.BaseGeneTest.testToString_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.3
Definition at line 49 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseGene.S_APPLICATION_DATA, and org.jgap.Gene.toString().
void org.jgap.BaseGeneTest.testToString_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.3
Definition at line 62 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseGene.S_APPLICATION_DATA, and org.jgap.Gene.toString().
void org.jgap.BaseGeneTest.testToString_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 76 of file BaseGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseGene.S_APPLICATION_DATA, and org.jgap.Gene.toString().
Member Data Documentation
final String org.jgap.BaseGeneTest.CVS_REVISION = `$Revision: 1.28 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file BaseGeneTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/BaseGeneTest.java