examples.gp.paintedDesert.PaintedDesertProblem Class Reference
Classes
class AntFitnessFunction
Public Member Functions
PaintedDesertProblem (GPConfiguration a_conf) throws InvalidConfigurationException
GPGenotype create () throws InvalidConfigurationException
void resetAnts ()
Static Public Member Functions
static void main (String[] args)
Private Member Functions
int[][] readMap (String a_filename) throws Exception
GPFitnessFunction createFitFunc ()
Static Private Member Functions
static void displaySolution (int[][] a_antmap, int[][] a_origMap)
Private Attributes
int[][] m_map
Ant[] m_ants
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.5 $`
static AntMap m_antMap
static int m_maxx
static int m_maxy
static int m_popSize
static int m_maxMoves = 300
Additional Inherited Members
Detailed Description
The Painted Desert problem from Koza's `Evolution of Emergent Cooperative
Behavior using Genetic Programming`. The problem is to create the same genetic program for a group of ants that will move three colors of sand into columns of like sand.
Author
Scott Mueller
Since
3.2
Definition at line 30 of file PaintedDesertProblem.java.
Constructor & Destructor Documentation
examples.gp.paintedDesert.PaintedDesertProblem.PaintedDesertProblem (GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Creates the Painted Desert Problem using the GPConfiguration.
Parameters
a_conf the GP configuration
Exceptions
InvalidConfigurationException
Definition at line 75 of file PaintedDesertProblem.java.
Referenced by examples.gp.paintedDesert.PaintedDesertProblem.main().
Member Function Documentation
GPGenotype examples.gp.paintedDesert.PaintedDesertProblem.create () throws InvalidConfigurationException [inline], [virtual]
Sets up the functions to use and other parameters. Then creates the initial genotype.
Returns
the genotype created
Exceptions
InvalidConfigurationException
Author
Scott Mueller
Implements org.jgap.gp.GPProblem.
Definition at line 89 of file PaintedDesertProblem.java.
References org.jgap.gp.GPProblem.getGPConfiguration(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.CommandGene.VoidClass.
GPFitnessFunction examples.gp.paintedDesert.PaintedDesertProblem.createFitFunc () [inline], [private]
Definition at line 402 of file PaintedDesertProblem.java.
static void examples.gp.paintedDesert.PaintedDesertProblem.displaySolution (int a_antmap[][], int a_origMap[][]) [inline], [static], [private]
Display ant map as found by GP.
Parameters
a_antmap the map containing the ants and grains of sand
a_origMap the original map
Definition at line 350 of file PaintedDesertProblem.java.
References examples.gp.paintedDesert.PaintedDesertProblem.m_maxx, and examples.gp.paintedDesert.PaintedDesertProblem.m_maxy.
static void examples.gp.paintedDesert.PaintedDesertProblem.main (String[] args) [inline], [static]
Runs the Painted Desert Problem
Parameters
args The location of the ant map file is optional
Exceptions
Exception
Author
Scott Mueller
Definition at line 232 of file PaintedDesertProblem.java.
References org.jgap.gp.IGPProgram.getApplicationData(), examples.gp.paintedDesert.PaintedDesertProblem.m_antMap, and examples.gp.paintedDesert.PaintedDesertProblem.PaintedDesertProblem().
int [][] examples.gp.paintedDesert.PaintedDesertProblem.readMap (String a_filename) throws Exception [inline], [private]
Reads the map from a file. The first line contains the number of X and Y locations and the number of Ants on the map. A 'b' at a location represents a Black grain of sand. A 's' represents a striped grain of sands. A 'g' represents a grey grain of sand. An 'A' represents an Ant. A 'B' represents an Ant and a black grain of sand at the same location. A 'S' represents an Ant and a striped grain of sand at the same location. A 'G' represents an Ant and a grey grain of sand at the same location.
A side effect of this function is setting the m_ants member variable.
Parameters
a_filename The location of the file containing the map information.
Returns
An array of the sand locations read in from the map.
Exceptions
Exception
Definition at line 137 of file PaintedDesertProblem.java.
References examples.gp.paintedDesert.AntMap.BLACK, examples.gp.paintedDesert.AntMap.EMPTY, examples.gp.paintedDesert.AntMap.GRAY, examples.gp.paintedDesert.PaintedDesertProblem.m_ants, examples.gp.paintedDesert.PaintedDesertProblem.m_maxx, examples.gp.paintedDesert.PaintedDesertProblem.m_maxy, examples.gp.paintedDesert.PaintedDesertProblem.m_popSize, and examples.gp.paintedDesert.AntMap.STRIPED.
void examples.gp.paintedDesert.PaintedDesertProblem.resetAnts () [inline]
Resets the ants to initial positions. So they can be run with the next version of the program.
Definition at line 449 of file PaintedDesertProblem.java.
References examples.gp.paintedDesert.PaintedDesertProblem.m_popSize.
Member Data Documentation
final String examples.gp.paintedDesert.PaintedDesertProblem.CVS_REVISION = `$Revision: 1.5 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 33 of file PaintedDesertProblem.java.
AntMap examples.gp.paintedDesert.PaintedDesertProblem.m_antMap [static], [private]
Holds the AntMap object used to hold the initial and current map of sand and Ants.
Definition at line 48 of file PaintedDesertProblem.java.
Referenced by examples.gp.paintedDesert.PaintedDesertProblem.main().
Ant [] examples.gp.paintedDesert.PaintedDesertProblem.m_ants [private]
Set by readMap and passed to the AntMap constructor
Definition at line 42 of file PaintedDesertProblem.java.
Referenced by examples.gp.paintedDesert.PaintedDesertProblem.readMap().
int [][] examples.gp.paintedDesert.PaintedDesertProblem.m_map [private]
Local copy of the map read into from the file.
Definition at line 37 of file PaintedDesertProblem.java.
int examples.gp.paintedDesert.PaintedDesertProblem.m_maxMoves = 300 [static], [private]
Maximum number of moves allowed.
Definition at line 68 of file PaintedDesertProblem.java.
int examples.gp.paintedDesert.PaintedDesertProblem.m_maxx [static], [private]
The maximum number of locations in the East or X direction.
Definition at line 53 of file PaintedDesertProblem.java.
Referenced by examples.gp.paintedDesert.PaintedDesertProblem.displaySolution(), and examples.gp.paintedDesert.PaintedDesertProblem.readMap().
int examples.gp.paintedDesert.PaintedDesertProblem.m_maxy [static], [private]
The maximum number of locaitons in the North or Y direction.
Definition at line 58 of file PaintedDesertProblem.java.
Referenced by examples.gp.paintedDesert.PaintedDesertProblem.displaySolution(), and examples.gp.paintedDesert.PaintedDesertProblem.readMap().
int examples.gp.paintedDesert.PaintedDesertProblem.m_popSize [static], [private]
The number of ants in the map.
Definition at line 63 of file PaintedDesertProblem.java.
Referenced by examples.gp.paintedDesert.PaintedDesertProblem.readMap(), and examples.gp.paintedDesert.PaintedDesertProblem.resetAnts().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/paintedDesert/PaintedDesertProblem.java