org.jgap.Population Class Reference
Public Member Functions
Population (final Configuration a_config) throws InvalidConfigurationException
Population (final Configuration a_config, final IChromosome[] a_chromosomes) throws InvalidConfigurationException
Population (final Configuration a_config, final IChromosome a_chromosome) throws InvalidConfigurationException
Population (final Configuration a_config, final int a_size) throws InvalidConfigurationException
Population () throws InvalidConfigurationException
Configuration getConfiguration ()
void addChromosome (final IChromosome a_toAdd)
void addChromosomes (final Population a_population)
void setChromosomes (final List a_chromosomes)
void setChromosome (final int a_index, final IChromosome a_chromosome)
List< IChromosome > getChromosomes ()
IChromosome getChromosome (final int a_index)
int size ()
Iterator iterator ()
IChromosome[] toChromosomes ()
IChromosome determineFittestChromosome ()
IChromosome determineFittestChromosome (int a_startIndex, int a_endIndex)
boolean isChanged ()
boolean contains (final IChromosome a_chromosome)
void keepPopSizeConstant () throws InvalidConfigurationException
List determineFittestChromosomes (final int a_numberOfChromosomes)
void sortByFitness ()
List getGenome (final boolean a_resolveCompositeGenes)
boolean isSorted ()
boolean equals (Object a_pop)
int compareTo (Object a_pop)
Object clone ()
void clear ()
String getPersistentRepresentation ()
void setValueFromPersistentRepresentation (String a_representation) throws UnsupportedRepresentationException
int hashCode ()
Static Public Attributes
static final String CHROM_DELIMITER = `~`
static final String CHROM_DELIMITER_HEADING = `[`
static final String CHROM_DELIMITER_CLOSING = `]`
Protected Member Functions
void setChanged (final boolean a_changed)
void setSorted (final boolean a_sorted)
void sort (Comparator a_comparator)
IChromosome createChromosome (String a_chromClassName, String a_persistentRepresentation) throws Exception
Static Protected Member Functions
static final List split (String a_string) throws UnsupportedRepresentationException
Private Member Functions
void addCompositeGene (final List a_result, final Gene a_gene)
void addAtomicGene (final List a_result, final Gene a_gene)
Private Attributes
List< IChromosome > m_chromosomes
IChromosome m_fittestChromosome
boolean m_changed
boolean m_sorted
Configuration m_config
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.66 $`
Detailed Description
Makes up the population of a generation during evolution. Represented by a list of chromosomes held in the Genotype.
Author
Klaus Meffert
Since
2.0
Definition at line 26 of file Population.java.
Constructor & Destructor Documentation
org.jgap.Population.Population (final Configuration a_config) throws InvalidConfigurationException [inline]
Definition at line 73 of file Population.java.
org.jgap.Population.Population (final Configuration a_config, final IChromosome[] a_chromosomes) throws InvalidConfigurationException [inline]
Definition at line 87 of file Population.java.
References org.jgap.Population.m_chromosomes, and org.jgap.Population.setChanged().
org.jgap.Population.Population (final Configuration a_config, final IChromosome a_chromosome) throws InvalidConfigurationException [inline]
Definition at line 109 of file Population.java.
References org.jgap.Population.m_chromosomes, and org.jgap.Population.setChanged().
org.jgap.Population.Population (final Configuration a_config, final int a_size) throws InvalidConfigurationException [inline]
Definition at line 131 of file Population.java.
References org.jgap.Population.m_chromosomes, org.jgap.Population.m_config, and org.jgap.Population.setChanged().
org.jgap.Population.Population () throws InvalidConfigurationException [inline]
Definition at line 148 of file Population.java.
Referenced by org.jgap.Population.clone(), and org.jgap.Population.compareTo().
Member Function Documentation
void org.jgap.Population.addAtomicGene (final List a_result, final Gene a_gene) [inline], [private]
Helper method for addCompositeGene.
Parameters
a_result List
a_gene Gene
Author
Klaus Meffert
Since
2.3
Definition at line 588 of file Population.java.
Referenced by org.jgap.Population.addCompositeGene(), and org.jgap.Population.getGenome().
void org.jgap.Population.addChromosome (final IChromosome a_toAdd) [inline]
Adds a Chromosome to this Population. Does nothing when given null.
Parameters
a_toAdd the Chromosome to add
Author
Klaus Meffert
Since
2.0
Definition at line 165 of file Population.java.
References org.jgap.Population.m_chromosomes, and org.jgap.Population.setChanged().
Referenced by org.jgap.Population.setChromosome().
void org.jgap.Population.addChromosomes (final Population a_population) [inline]
Adds all the Chromosomes in the given Population. Does nothing on null or an empty Population.
Parameters
a_population the Population to add
Author
Klaus Meffert
Since
2.0
Definition at line 183 of file Population.java.
References org.jgap.Population.m_chromosomes, and org.jgap.Population.setChanged().
void org.jgap.Population.addCompositeGene (final List a_result, final Gene a_gene) [inline], [private]
Adds all the genes of a CompositeGene to a result list.
Note: Method calls itself recursively.
Parameters
a_result the list to add to
a_gene the gene to start with
Author
Klaus Meffert
Since
2.3
Definition at line 567 of file Population.java.
References org.jgap.Population.addAtomicGene().
Referenced by org.jgap.Population.getGenome().
void org.jgap.Population.clear () [inline]
Clears the list of chromosomes. Normally, this should not be necessary. But especially in distributed computing, a fresh population has to be provided sometimes.
Author
Klaus Meffert
Since
3.2
Definition at line 686 of file Population.java.
References org.jgap.Population.m_changed, org.jgap.Population.m_fittestChromosome, and org.jgap.Population.m_sorted.
Object org.jgap.Population.clone () [inline]
Returns
deeply cloned population instance
Author
Klaus Meffert
Since
3.2
Implements org.jgap.util.ICloneable.
Definition at line 659 of file Population.java.
References org.jgap.util.ICloneable.clone(), org.jgap.Population.m_chromosomes, org.jgap.Population.m_config, org.jgap.Population.m_fittestChromosome, org.jgap.Population.Population(), and org.jgap.Population.size().
Referenced by org.jgap.audit.EvolutionMonitor.nextCycle().
int org.jgap.Population.compareTo (Object a_pop) [inline]
This method is not producing symmetric results as -1 is more often returned than 1 (see description of return value).
Parameters
a_pop the other population to compare
Returns
1: a_pop is null or having fewer chromosomes or equal number of chromosomes but at least one not contained. 0: both populations containing exactly the same chromosomes. -1: this population contains fewer chromosomes than a_pop
Author
Klaus Meffert
Since
2.6
Definition at line 629 of file Population.java.
References org.jgap.Population.m_chromosomes, org.jgap.Population.Population(), and org.jgap.Population.size().
Referenced by org.jgap.Population.equals(), and org.jgap.PopulationTest.testCompareTo_0().
boolean org.jgap.Population.contains (final IChromosome a_chromosome) [inline]
Determines whether the given chromosome is contained within the population.
Parameters
a_chromosome the chromosome to check
Returns
true: chromosome contained within population
Author
Klaus Meffert
Since
2.1
Definition at line 406 of file Population.java.
Referenced by org.jgap.impl.GABreeder.reAddFittest(), org.jgap.NaturalSelectorExt.selectChromosome(), and org.jgap.impl.WeightedRouletteSelector.selectChromosomes().
IChromosome org.jgap.Population.createChromosome (String a_chromClassName, String a_persistentRepresentation) throws Exception [inline], [protected]
Creates a new Chromosome instance.
Taken and adapted from CompositeGene.
Parameters
a_chromClassName name of the Chromosome class
a_persistentRepresentation persistent representation of the Chromosome to create (could be obtained via getPersistentRepresentation)
Returns
newly created Chromosome
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 785 of file Population.java.
References org.jgap.Population.getConfiguration().
Referenced by org.jgap.Population.setValueFromPersistentRepresentation().
IChromosome org.jgap.Population.determineFittestChromosome () [inline]
Determines the fittest Chromosome in the Population (the one with the highest fitness value) and memorizes it. This is an optimized version compared to calling determineFittesChromosomes(1).
Returns
the fittest Chromosome of the Population
Author
Klaus Meffert
Since
2.0
Definition at line 303 of file Population.java.
References org.jgap.Population.getConfiguration(), org.jgap.Population.m_changed, org.jgap.Population.m_fittestChromosome, and org.jgap.Population.setChanged().
Referenced by org.jgap.audit.EvaluatorTest.testCalcPerformance_0(), org.jgap.audit.EvaluatorTest.testCalcPerformance_2(), org.jgap.PopulationTest.testDetermineFittestChromosome_0(), org.jgap.PopulationTest.testDetermineFittestChromosome_1(), org.jgap.PopulationTest.testDetermineFittestChromosome_2(), org.jgap.PopulationTest.testDetermineFittestChromosome_2_0(), org.jgap.PopulationTest.testDetermineFittestChromosome_3(), org.jgap.PopulationTest.testDetermineFittestChromosome_5(), org.jgap.PopulationTest.testDetermineFittestChromosomes_2(), and org.jgap.PopulationTest.testDetermineFittestChromosomes_3().
IChromosome org.jgap.Population.determineFittestChromosome (int a_startIndex, int a_endIndex) [inline]
Determines the fittest Chromosome in the population (the one with the highest fitness value) within the given indices and memorizes it. This is an optimized version compared to calling determineFittesChromosomes(1).
Parameters
a_startIndex index to begin the evaluation with
a_endIndex index to end the evaluation with
Returns
the fittest Chromosome of the population within the given indices
Author
Klaus Meffert
Since
3.0
Definition at line 342 of file Population.java.
References org.jgap.Population.getConfiguration(), org.jgap.FitnessEvaluator.isFitter(), org.jgap.Population.m_chromosomes, and org.jgap.Population.m_fittestChromosome.
List org.jgap.Population.determineFittestChromosomes (final int a_numberOfChromosomes) [inline]
Sorts the Chromosome list and returns the fittest n Chromosomes in the population.
Parameters
a_numberOfChromosomes number of top performer chromosomes to be returned
Returns
list of the fittest n Chromosomes of the population, or the fittest x Chromosomes with x = number of chromosomes in case n > x.
Author
Charles Kevin Hill
Since
2.4
Definition at line 479 of file Population.java.
References org.jgap.Population.getChromosomes(), org.jgap.Population.m_changed, org.jgap.Population.m_sorted, and org.jgap.Population.sortByFitness().
Referenced by org.jgap.PopulationTest.testDetermineFittestChromosome_4(), and org.jgap.PopulationTest.testDetermineFittestChromosomes_1().
boolean org.jgap.Population.equals (Object a_pop) [inline]
The equals-method.
Parameters
a_pop the population instance to compare with
Returns
true: given object equal to comparing one
Author
Klaus Meffert
Since
2.6
Definition at line 605 of file Population.java.
References org.jgap.Population.compareTo().
Referenced by org.jgap.eval.PopulationHistory.equals(), org.jgap.impl.StandardPostSelector.equals(), org.jgap.impl.BestChromosomesSelector.equals(), and org.jgap.eval.PopulationHistoryTest.testGetPopulation_1().
IChromosome org.jgap.Population.getChromosome (final int a_index) [inline]
Parameters
a_index the index of the Chromosome to be returned
Returns
Chromosome at given index in the Population
Author
Klaus Meffert
Since
2.0
Definition at line 257 of file Population.java.
Referenced by org.jgap.Population.hashCode(), org.jgap.data.DataTreeBuilder.representGenotypeAsElement(), org.jgap.xml.XMLManager.representGenotypeAsElement(), org.jgap.impl.StandardPostSelector.select(), org.jgap.NaturalSelectorExt.select(), org.jgap.PopulationTest.testGetChromosome_0(), org.jgap.impl.FittestPopulationMergerTest.testMergePopulations_0(), and org.jgap.PopulationTest.testSetChromosome_1().
List<IChromosome> org.jgap.Population.getChromosomes () [inline]
Returns
the list of Chromosome's in the Population. Don't modify the retrieved list by using clear(), remove(int) etc. If you do so, you need to call setChanged(true)
Author
Klaus Meffert
Since
2.0
Definition at line 246 of file Population.java.
References org.jgap.Population.m_chromosomes.
Referenced by org.jgap.impl.BestChromosomesSelector.add(), org.jgap.Population.determineFittestChromosomes(), org.jgap.Population.getGenome(), org.jgap.Population.sort(), and org.jgap.PopulationTest.testGetChromosomes_0().
Configuration org.jgap.Population.getConfiguration () [inline]
Definition at line 153 of file Population.java.
References org.jgap.Population.m_config.
Referenced by org.jgap.Population.createChromosome(), org.jgap.Population.determineFittestChromosome(), org.jgap.Population.keepPopSizeConstant(), org.jgap.impl.FittestPopulationMerger.mergePopulations(), and org.jgap.Population.sortByFitness().
List org.jgap.Population.getGenome (final boolean a_resolveCompositeGenes) [inline]
Returns the genotype of the population, i.e. the list of genes in the Population.
Parameters
a_resolveCompositeGenes true: split encountered CompositeGenes into their single (atomic) genes
Returns
genotype of the population
Author
Klaus Meffert
Since
2.3
Definition at line 536 of file Population.java.
References org.jgap.Population.addAtomicGene(), org.jgap.Population.addCompositeGene(), and org.jgap.Population.getChromosomes().
String org.jgap.Population.getPersistentRepresentation () [inline]
Returns a persistent representation of this chromosome, see interface Gene for description. Similar to CompositeGene's routine. But does not include all information of the chromosome (yet).
Returns
string representation of this Chromosome's relevant parts of its current state
Exceptions
UnsupportedOperationException
Author
Klaus Meffert
Since
3.2
Implements org.jgap.IPersistentRepresentation.
Definition at line 705 of file Population.java.
References org.jgap.Population.CHROM_DELIMITER, org.jgap.Population.CHROM_DELIMITER_CLOSING, org.jgap.Population.CHROM_DELIMITER_HEADING, and org.jgap.Population.m_chromosomes.
Referenced by org.jgap.PopulationTest.testPersistentRepresentation_1().
int org.jgap.Population.hashCode () [inline]
Definition at line 854 of file Population.java.
References org.jgap.Population.getChromosome(), and org.jgap.Population.size().
boolean org.jgap.Population.isChanged () [inline]
Returns
true: population's chromosomes (maybe) were changed, false: not changed for sure
Since
2.6
Definition at line 382 of file Population.java.
References org.jgap.Population.m_changed.
Referenced by org.jgap.PopulationTest.testDetermineFittestChromosomes_3(), org.jgap.PopulationTest.testGetGenome_1(), org.jgap.PopulationTest.testGetGenome_2(), and org.jgap.PopulationTest.testSortByFitness_1().
boolean org.jgap.Population.isSorted () [inline]
Definition at line 592 of file Population.java.
References org.jgap.Population.m_sorted.
Referenced by org.jgap.PopulationTest.testSortByFitness_1().
Iterator org.jgap.Population.iterator () [inline]
Returns
Iterator for the Chromosome list in the Population. Please be aware that using remove() forces you to call setChanged(true)
Author
Klaus Meffert
Since
2.0
Definition at line 278 of file Population.java.
void org.jgap.Population.keepPopSizeConstant () throws InvalidConfigurationException [inline]
Cares that the population size does not exceed the maximum size given in the configuration.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.2
Todo
Todo use dedicated selector for that
Definition at line 438 of file Population.java.
References org.jgap.Population.getConfiguration(), and org.jgap.Population.size().
void org.jgap.Population.setChanged (final boolean a_changed) [inline], [protected]
Mark that for the population the fittest chromosome may have changed.
Parameters
a_changed true: population's fittest chromosome may have changed, false: fittest chromosome evaluated earlier is still valid
Author
Klaus Meffert
Since
2.2
Definition at line 371 of file Population.java.
References org.jgap.Population.m_changed, and org.jgap.Population.setSorted().
Referenced by org.jgap.Population.addChromosome(), org.jgap.Population.addChromosomes(), org.jgap.Population.determineFittestChromosome(), org.jgap.Population.Population(), org.jgap.Population.setChromosome(), org.jgap.Population.setChromosomes(), org.jgap.Population.setValueFromPersistentRepresentation(), and org.jgap.Population.sortByFitness().
void org.jgap.Population.setChromosome (final int a_index, final IChromosome a_chromosome) [inline]
Sets in the given Chromosome on the given index in the list of chromosomes. If the given index is exceeding the list by one, the chromosome is appended.
Parameters
a_index the index to set the Chromosome in
a_chromosome the Chromosome to be set
Author
Klaus Meffert
Since
2.0
Definition at line 226 of file Population.java.
References org.jgap.Population.addChromosome(), org.jgap.Population.m_chromosomes, and org.jgap.Population.setChanged().
void org.jgap.Population.setChromosomes (final List a_chromosomes) [inline]
Replaces all chromosomes in the population with the give list of chromosomes.
Parameters
a_chromosomes the chromosomes to make the population up from
Author
Klaus Meffert
Definition at line 208 of file Population.java.
References org.jgap.Population.m_chromosomes, and org.jgap.Population.setChanged().
void org.jgap.Population.setSorted (final boolean a_sorted) [inline], [protected]
Mark the population as sorted.
Parameters
a_sorted true: mark population as sorted
Author
Klaus Meffert
Since
2.6
Definition at line 394 of file Population.java.
References org.jgap.Population.m_sorted.
Referenced by org.jgap.Population.setChanged(), and org.jgap.Population.sortByFitness().
void org.jgap.Population.setValueFromPersistentRepresentation (String a_representation) throws UnsupportedRepresentationException [inline]
Counterpart of getPersistentRepresentation.
Parameters
a_representation the string representation retrieved from a prior call to the getPersistentRepresentation() method
Exceptions
UnsupportedRepresentationException
Author
Klaus Meffert
Since
3.2
Implements org.jgap.IPersistentRepresentation.
Definition at line 739 of file Population.java.
References org.jgap.Population.CHROM_DELIMITER, org.jgap.Population.createChromosome(), org.jgap.Population.m_chromosomes, org.jgap.Population.setChanged(), and org.jgap.Population.split().
int org.jgap.Population.size () [inline]
Returns
number of Chromosome's in the Population
Author
Klaus Meffert
Since
2.0
Definition at line 267 of file Population.java.
Referenced by org.jgap.impl.GABreeder.bulkFunctionEvaluation(), org.jgap.Population.clone(), org.jgap.Population.compareTo(), org.jgap.impl.GABreeder.fillPopulationRandomlyToOriginalSize(), org.jgap.Population.hashCode(), org.jgap.Population.keepPopSizeConstant(), org.jgap.impl.InversionOperator.operate(), org.jgap.impl.GaussianMutationOperator.operate(), org.jgap.impl.GreedyCrossover.operate(), org.jgap.impl.TwoWayMutationOperator.operate(), org.jgap.impl.MutationOperator.operate(), org.jgap.impl.AveragingCrossoverOperator.operate(), org.jgap.impl.CrossoverOperator.operate(), org.jgap.PopulationTest.testAddChromosome_1(), org.jgap.PopulationTest.testAddChromosomes_1(), org.jgap.PopulationTest.testConstruct_3(), org.jgap.PopulationTest.testDetermineFittestChromosome_2_0(), org.jgap.PopulationTest.testIterator_0(), org.jgap.impl.FittestPopulationMergerTest.testMergePopulations_0(), org.jgap.PopulationTest.testPersistentRepresentation_2(), org.jgap.PopulationTest.testPersistentRepresentation_5(), org.jgap.PopulationTest.testSetChromosome_0(), org.jgap.PopulationTest.testSetChromosome_1(), org.jgap.PopulationTest.testSetChromosomes_0(), and org.jgap.PopulationTest.testSize_0().
void org.jgap.Population.sort (Comparator a_comparator) [inline], [protected]
Sorts the chromosomes within the population utilzing the given comparator.
Parameters
a_comparator the comparator to utilize for sorting
Author
Klaus Meffert
Since
2.6
Definition at line 521 of file Population.java.
References org.jgap.Population.getChromosomes().
Referenced by org.jgap.Population.sortByFitness().
void org.jgap.Population.sortByFitness () [inline]
Sorts the chromosomes within the population according to their fitness value using ChromosomFitnessComparator. The fittest chromosome is then at index 0.
Author
Klaus Meffert
Since
2.6
Definition at line 502 of file Population.java.
References org.jgap.Population.getConfiguration(), org.jgap.Population.m_chromosomes, org.jgap.Population.m_fittestChromosome, org.jgap.Population.setChanged(), org.jgap.Population.setSorted(), and org.jgap.Population.sort().
Referenced by org.jgap.Population.determineFittestChromosomes().
static final List org.jgap.Population.split (String a_string) throws UnsupportedRepresentationException [inline], [static], [protected]
Splits the input a_string into individual chromosome representations.
Taken and adapted from CompositeGene.
Parameters
a_string the string to split
Returns
the elements of the returned array are the persistent representation strings of the population's components
Exceptions
UnsupportedRepresentationException
Author
Klaus Meffert
Since
3.2
Definition at line 809 of file Population.java.
References org.jgap.Population.CHROM_DELIMITER_CLOSING, and org.jgap.Population.CHROM_DELIMITER_HEADING.
Referenced by org.jgap.Population.setValueFromPersistentRepresentation().
IChromosome [] org.jgap.Population.toChromosomes () [inline]
Returns
the Population converted into a list of Chromosome's
Author
Klaus Meffert, Dan Clark
Since
2.0
Definition at line 288 of file Population.java.
Member Data Documentation
final String org.jgap.Population.CHROM_DELIMITER = `~` [static]
Definition at line 54 of file Population.java.
Referenced by org.jgap.Population.getPersistentRepresentation(), org.jgap.Population.setValueFromPersistentRepresentation(), org.jgap.PopulationTest.testPersistentRepresentation_4(), org.jgap.PopulationTest.testPersistentRepresentation_5(), and org.jgap.PopulationTest.testPersistentRepresentation_6().
final String org.jgap.Population.CHROM_DELIMITER_CLOSING = `]` [static]
Represents the closing delimiter that is used to separate chromosomes in the persistent representation.
Definition at line 66 of file Population.java.
Referenced by org.jgap.Population.getPersistentRepresentation(), org.jgap.Population.split(), and org.jgap.PopulationTest.testPersistentRepresentation_5().
final String org.jgap.Population.CHROM_DELIMITER_HEADING = `[` [static]
Represents the heading delimiter that is used to separate chromosomes in the persistent representation.
Definition at line 60 of file Population.java.
Referenced by org.jgap.Population.getPersistentRepresentation(), and org.jgap.Population.split().
final String org.jgap.Population.CVS_REVISION = `$Revision: 1.66 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 29 of file Population.java.
boolean org.jgap.Population.m_changed [private]
Indicates whether at least one of the chromosomes has been changed (deleted, added, modified).
Definition at line 45 of file Population.java.
Referenced by org.jgap.Population.clear(), org.jgap.Population.determineFittestChromosome(), org.jgap.Population.determineFittestChromosomes(), org.jgap.Population.isChanged(), and org.jgap.Population.setChanged().
List<IChromosome> org.jgap.Population.m_chromosomes [private]
The array of Chromosomes that makeup the Genotype's population.
Definition at line 34 of file Population.java.
Referenced by org.jgap.Population.addChromosome(), org.jgap.Population.addChromosomes(), org.jgap.Population.clone(), org.jgap.Population.compareTo(), org.jgap.Population.determineFittestChromosome(), org.jgap.Population.getChromosomes(), org.jgap.Population.getPersistentRepresentation(), org.jgap.Population.Population(), org.jgap.Population.setChromosome(), org.jgap.Population.setChromosomes(), org.jgap.Population.setValueFromPersistentRepresentation(), and org.jgap.Population.sortByFitness().
Configuration org.jgap.Population.m_config [private]
Definition at line 52 of file Population.java.
Referenced by org.jgap.Population.clone(), org.jgap.Population.getConfiguration(), and org.jgap.Population.Population().
IChromosome org.jgap.Population.m_fittestChromosome [private]
The fittest Chromosome of the population.
Definition at line 39 of file Population.java.
Referenced by org.jgap.Population.clear(), org.jgap.Population.clone(), org.jgap.Population.determineFittestChromosome(), and org.jgap.Population.sortByFitness().
boolean org.jgap.Population.m_sorted [private]
Indicates that the list of Chromosomes has been sorted.
Definition at line 50 of file Population.java.
Referenced by org.jgap.Population.clear(), org.jgap.Population.determineFittestChromosomes(), org.jgap.Population.isSorted(), and org.jgap.Population.setSorted().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/Population.java