examples.distinctGenes.MyChromosome Class Reference
Public Member Functions
MyChromosome () throws InvalidConfigurationException
MyChromosome (final Configuration a_configuration) throws InvalidConfigurationException
MyChromosome (final Configuration a_configuration, final int a_desiredSize) throws InvalidConfigurationException
MyChromosome (final Configuration a_configuration, final Gene a_sampleGene, final int a_desiredSize) throws InvalidConfigurationException
MyChromosome (final Configuration a_configuration, final Gene[] a_initialGenes) throws InvalidConfigurationException
MyChromosome (final Configuration a_configuration, Gene a_sampleGene, int a_desiredSize, IGeneConstraintChecker a_constraintChecker) throws InvalidConfigurationException
boolean isHandlerFor (Object a_obj, Class a_class)
Object perform (Object a_obj, Class a_class, Object a_params) throws Exception
Static Public Member Functions
static IChromosome randomInitialMyChromosome (Configuration a_configuration) throws InvalidConfigurationException
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Detailed Description
Sample class: Descendent of Chromosome that creates Chromosomes with n CompositeGenes. All but one CompositeGene's have 4 sub-genes, the last one has only 3 sub-genes.
Author
Klaus Meffert
Since
3.0
Definition at line 23 of file MyChromosome.java.
Constructor & Destructor Documentation
examples.distinctGenes.MyChromosome.MyChromosome () throws InvalidConfigurationException [inline]
Definition at line 28 of file MyChromosome.java.
Referenced by examples.distinctGenes.MyChromosome.randomInitialMyChromosome().
examples.distinctGenes.MyChromosome.MyChromosome (final Configuration a_configuration) throws InvalidConfigurationException [inline]
Definition at line 33 of file MyChromosome.java.
examples.distinctGenes.MyChromosome.MyChromosome (final Configuration a_configuration, final int a_desiredSize) throws InvalidConfigurationException [inline]
Definition at line 38 of file MyChromosome.java.
examples.distinctGenes.MyChromosome.MyChromosome (final Configuration a_configuration, final Gene a_sampleGene, final int a_desiredSize) throws InvalidConfigurationException [inline]
Definition at line 44 of file MyChromosome.java.
examples.distinctGenes.MyChromosome.MyChromosome (final Configuration a_configuration, final Gene[] a_initialGenes) throws InvalidConfigurationException [inline]
Definition at line 50 of file MyChromosome.java.
examples.distinctGenes.MyChromosome.MyChromosome (final Configuration a_configuration, Gene a_sampleGene, int a_desiredSize, IGeneConstraintChecker a_constraintChecker) throws InvalidConfigurationException [inline]
Definition at line 56 of file MyChromosome.java.
Member Function Documentation
boolean examples.distinctGenes.MyChromosome.isHandlerFor (Object a_obj, Class a_class) [inline]
Definition at line 63 of file MyChromosome.java.
Object examples.distinctGenes.MyChromosome.perform (Object a_obj, Class a_class, Object a_params) throws Exception [inline]
Definition at line 73 of file MyChromosome.java.
References examples.distinctGenes.MyChromosome.randomInitialMyChromosome().
static IChromosome examples.distinctGenes.MyChromosome.randomInitialMyChromosome (Configuration a_configuration) throws InvalidConfigurationException [inline], [static]
Definition at line 78 of file MyChromosome.java.
References examples.distinctGenes.MyChromosome.MyChromosome().
Referenced by examples.distinctGenes.MyChromosome.perform().
Member Data Documentation
final String examples.distinctGenes.MyChromosome.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file MyChromosome.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/distinctGenes/MyChromosome.java