examples.grid.evolutionDistributed.LocalEvolutionDemo Class Reference
Public Member Functions
LocalEvolutionDemo () throws Exception
Static Public Member Functions
static void main (String[] args)
Protected Member Functions
MyRequest assembleWorkRequest ()
void evolve () throws Exception
Private Attributes
GridConfiguration m_localconfig
IClientEvolveStrategy m_clientEvolver
MyRequest m_req
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Detailed Description
Demonstrates how the grid configuration can be used to do the whole evolution locally (i.e. stand alone without server and workers).
Our aim: We can recycle any code written for the grid. We don't have to rewrite or add a single line of code!
This class is still under development! It will evolve together with the framework.
Author
Klaus Meffert
Since
3.2
Definition at line 27 of file LocalEvolutionDemo.java.
Constructor & Destructor Documentation
examples.grid.evolutionDistributed.LocalEvolutionDemo.LocalEvolutionDemo () throws Exception [inline]
Definition at line 37 of file LocalEvolutionDemo.java.
References examples.grid.evolutionDistributed.LocalEvolutionDemo.assembleWorkRequest(), examples.grid.evolutionDistributed.LocalEvolutionDemo.evolve(), examples.grid.evolutionDistributed.LocalEvolutionDemo.m_clientEvolver, examples.grid.evolutionDistributed.LocalEvolutionDemo.m_localconfig, and examples.grid.evolutionDistributed.LocalEvolutionDemo.m_req.
Referenced by examples.grid.evolutionDistributed.LocalEvolutionDemo.main().
Member Function Documentation
MyRequest examples.grid.evolutionDistributed.LocalEvolutionDemo.assembleWorkRequest () [inline], [protected]
Definition at line 50 of file LocalEvolutionDemo.java.
References examples.grid.evolutionDistributed.LocalEvolutionDemo.m_localconfig.
Referenced by examples.grid.evolutionDistributed.LocalEvolutionDemo.LocalEvolutionDemo().
void examples.grid.evolutionDistributed.LocalEvolutionDemo.evolve () throws Exception [inline], [protected]
Definition at line 63 of file LocalEvolutionDemo.java.
References examples.grid.evolutionDistributed.LocalEvolutionDemo.m_localconfig, and examples.grid.evolutionDistributed.LocalEvolutionDemo.m_req.
Referenced by examples.grid.evolutionDistributed.LocalEvolutionDemo.LocalEvolutionDemo().
static void examples.grid.evolutionDistributed.LocalEvolutionDemo.main (String[] args) [inline], [static]
Definition at line 88 of file LocalEvolutionDemo.java.
References examples.grid.evolutionDistributed.LocalEvolutionDemo.LocalEvolutionDemo().
Member Data Documentation
final String examples.grid.evolutionDistributed.LocalEvolutionDemo.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 29 of file LocalEvolutionDemo.java.
IClientEvolveStrategy examples.grid.evolutionDistributed.LocalEvolutionDemo.m_clientEvolver [private]
Definition at line 33 of file LocalEvolutionDemo.java.
Referenced by examples.grid.evolutionDistributed.LocalEvolutionDemo.LocalEvolutionDemo().
GridConfiguration examples.grid.evolutionDistributed.LocalEvolutionDemo.m_localconfig [private]
Definition at line 31 of file LocalEvolutionDemo.java.
Referenced by examples.grid.evolutionDistributed.LocalEvolutionDemo.assembleWorkRequest(), examples.grid.evolutionDistributed.LocalEvolutionDemo.evolve(), and examples.grid.evolutionDistributed.LocalEvolutionDemo.LocalEvolutionDemo().
MyRequest examples.grid.evolutionDistributed.LocalEvolutionDemo.m_req [private]
Definition at line 35 of file LocalEvolutionDemo.java.
Referenced by examples.grid.evolutionDistributed.LocalEvolutionDemo.evolve(), and examples.grid.evolutionDistributed.LocalEvolutionDemo.LocalEvolutionDemo().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/grid/evolutionDistributed/LocalEvolutionDemo.java