org.jgap.impl.CompositeGenePersistentReprTest Class Reference
Public Member Functions
void testRepresentation () throws Exception
Static Public Member Functions
static Test suite ()
Private Member Functions
CompositeGene createSampleNestedGene (int a_seed) throws Exception
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
Test persistent representation of the CompositeGene.
Author
Audrius Meskauskas
Klaus Meffert
Since
2.1
Definition at line 25 of file CompositeGenePersistentReprTest.java.
Member Function Documentation
CompositeGene org.jgap.impl.CompositeGenePersistentReprTest.createSampleNestedGene (int a_seed) throws Exception [inline], [private]
Definition at line 50 of file CompositeGenePersistentReprTest.java.
References org.jgap.impl.StringGene.ALPHABET_CHARACTERS_UPPER, org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.GENE_DELIMITER.
Referenced by org.jgap.impl.CompositeGenePersistentReprTest.testRepresentation().
static Test org.jgap.impl.CompositeGenePersistentReprTest.suite () [inline], [static]
Definition at line 30 of file CompositeGenePersistentReprTest.java.
void org.jgap.impl.CompositeGenePersistentReprTest.testRepresentation () throws Exception [inline]
Definition at line 35 of file CompositeGenePersistentReprTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGenePersistentReprTest.createSampleNestedGene().
Member Data Documentation
final String org.jgap.impl.CompositeGenePersistentReprTest.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file CompositeGenePersistentReprTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/CompositeGenePersistentReprTest.java