org.jgap.distr.WorkerCommand Class Reference
Public Member Functions
WorkerCommand (final String a_name)
CommandResult execute (final Object a_parameters) throws Exception
String getName ()
long getAgeMillis ()
Static Private Member Functions
static long getCurrentMilliseconds ()
Private Attributes
String m_name
long m_timeCreated
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.5 $`
Detailed Description
Command sent by an IMaster instance to an IWorker instance.
Author
Klaus Meffert
Since
2.3
Definition at line 21 of file WorkerCommand.java.
Constructor & Destructor Documentation
org.jgap.distr.WorkerCommand.WorkerCommand (final String a_name) [inline]
Definition at line 38 of file WorkerCommand.java.
References org.jgap.distr.WorkerCommand.getCurrentMilliseconds(), org.jgap.distr.WorkerCommand.m_name, and org.jgap.distr.WorkerCommand.m_timeCreated.
Member Function Documentation
CommandResult org.jgap.distr.WorkerCommand.execute (final Object a_parameters) throws Exception [inline]
Todo
Todo implement
Definition at line 44 of file WorkerCommand.java.
long org.jgap.distr.WorkerCommand.getAgeMillis () [inline]
Definition at line 59 of file WorkerCommand.java.
References org.jgap.distr.WorkerCommand.getCurrentMilliseconds(), and org.jgap.distr.WorkerCommand.m_timeCreated.
static long org.jgap.distr.WorkerCommand.getCurrentMilliseconds () [inline], [static], [private]
Definition at line 50 of file WorkerCommand.java.
Referenced by org.jgap.distr.WorkerCommand.getAgeMillis(), and org.jgap.distr.WorkerCommand.WorkerCommand().
String org.jgap.distr.WorkerCommand.getName () [inline]
Definition at line 55 of file WorkerCommand.java.
References org.jgap.distr.WorkerCommand.m_name.
Member Data Documentation
final String org.jgap.distr.WorkerCommand.CVS_REVISION = `$Revision: 1.5 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file WorkerCommand.java.
String org.jgap.distr.WorkerCommand.m_name [private]
Informative name
Definition at line 29 of file WorkerCommand.java.
Referenced by org.jgap.distr.WorkerCommand.getName(), and org.jgap.distr.WorkerCommand.WorkerCommand().
long org.jgap.distr.WorkerCommand.m_timeCreated [private]
Time the command was created (i.e. the constructor was called) in milliseconds. For statistical and purposes and for allowing to set a timeout
Definition at line 36 of file WorkerCommand.java.
Referenced by org.jgap.distr.WorkerCommand.getAgeMillis(), and org.jgap.distr.WorkerCommand.WorkerCommand().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/distr/WorkerCommand.java