examples.supergene.AbstractSupergeneTest Class Reference
Public Member Functions
abstract int makeChangeForAmount (int a_targetChangeAmount) throws Exception
IChromosome report (SupergeneChangeFitnessFunction a_fitnessFunction, Genotype a_population)
int test ()
Static Public Member Functions
static int amountOfChange (int a_numQuarters, int a_numDimes, int a_numNickels, int a_numPennies)
Static Public Attributes
static final int DIMES = 0
static final int QUARTERS = 1
static final int NICKELS = 2
static final int PENNIES = 3
static int MAX_ALLOWED_EVOLUTIONS = 200
static int POPULATION_SIZE = 2000
static boolean REPORT_ENABLED = true
static boolean EXISTING_SOLUTIONS_ONLY = false
Protected Member Functions
Gene getDimesGene (Configuration a_conf)
Gene getNickelsGene (Configuration a_conf)
Gene getPenniesGene (Configuration a_conf)
Gene getQuartersGene (Configuration a_conf)
int solve (Configuration a_conf, int a_targetChangeAmount, SupergeneChangeFitnessFunction a_fitnessFunction, Gene[] a_sampleGenes) throws InvalidConfigurationException
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.5 $`
Detailed Description
Abstract class for testing Supergene performance.
Author
Neil Rotstan
Klaus Meffert
Audrius Meskauskas
Since
2.0
Definition at line 23 of file AbstractSupergeneTest.java.
Member Function Documentation
static int examples.supergene.AbstractSupergeneTest.amountOfChange (int a_numQuarters, int a_numDimes, int a_numNickels, int a_numPennies) [inline], [static]
Compute the money value from the coin information.
Definition at line 108 of file AbstractSupergeneTest.java.
Referenced by examples.supergene.Force.solve().
Gene examples.supergene.AbstractSupergeneTest.getDimesGene (Configuration a_conf) [inline], [protected]
Parameters
a_conf the configuration to use
Returns
created Dimes gene instance
Definition at line 64 of file AbstractSupergeneTest.java.
Referenced by examples.supergene.SupergeneSample.makeChangeForAmount().
Gene examples.supergene.AbstractSupergeneTest.getNickelsGene (Configuration a_conf) [inline], [protected]
Parameters
a_conf the configuration to use
Returns
created Nickels gene instance
Definition at line 76 of file AbstractSupergeneTest.java.
Referenced by examples.supergene.SupergeneSample.makeChangeForAmount().
Gene examples.supergene.AbstractSupergeneTest.getPenniesGene (Configuration a_conf) [inline], [protected]
Parameters
a_conf the configuration to use
Returns
created Pennies (1) gene instance
Definition at line 88 of file AbstractSupergeneTest.java.
Referenced by examples.supergene.SupergeneSample.makeChangeForAmount().
Gene examples.supergene.AbstractSupergeneTest.getQuartersGene (Configuration a_conf) [inline], [protected]
Parameters
a_conf the configuration to use
Returns
created Quarters gene instance
Definition at line 100 of file AbstractSupergeneTest.java.
Referenced by examples.supergene.SupergeneSample.makeChangeForAmount().
abstract int examples.supergene.AbstractSupergeneTest.makeChangeForAmount (int a_targetChangeAmount) throws Exception [pure virtual]
Executes the genetic algorithm to determine the minimum number of coins necessary to make up the given target amount of change. The solution will then be written to System.out.
Parameters
a_targetChangeAmount the target amount of change for which this method is attempting to produce the minimum number of coins
Returns
absolute difference between the required and computed change amount
Exceptions
Exception
Implemented in examples.supergene.SupergeneSample.
Referenced by examples.supergene.AbstractSupergeneTest.test().
IChromosome examples.supergene.AbstractSupergeneTest.report (SupergeneChangeFitnessFunction a_fitnessFunction, Genotype a_population) [inline]
Write report on eveluation to the given stream.
Parameters
a_fitnessFunction p_SupergeneChangeFitnessFunction
a_population Genotype
Returns
Chromosome
Definition at line 135 of file AbstractSupergeneTest.java.
References examples.supergene.AbstractSupergeneTest.DIMES, examples.supergene.AbstractChangeFitnessFunction.getTotalNumberOfCoins(), examples.supergene.AbstractSupergeneTest.NICKELS, examples.supergene.AbstractSupergeneTest.PENNIES, examples.supergene.AbstractSupergeneTest.QUARTERS, and examples.supergene.AbstractSupergeneTest.REPORT_ENABLED.
Referenced by examples.supergene.AbstractSupergeneTest.solve().
int examples.supergene.AbstractSupergeneTest.solve (Configuration a_conf, int a_targetChangeAmount, SupergeneChangeFitnessFunction a_fitnessFunction, Gene[] a_sampleGenes) throws InvalidConfigurationException [inline], [protected]
Find and print the solution, return the solution error.
Parameters
a_conf the configuration to use
Returns
absolute difference between the required and computed change
Definition at line 210 of file AbstractSupergeneTest.java.
References examples.supergene.AbstractSupergeneTest.MAX_ALLOWED_EVOLUTIONS, examples.supergene.AbstractSupergeneTest.POPULATION_SIZE, and examples.supergene.AbstractSupergeneTest.report().
Referenced by examples.supergene.SupergeneSample.makeChangeForAmount().
int examples.supergene.AbstractSupergeneTest.test () [inline]
Test the method, returns the sum of all differences between the required and obtained excange amount. One exception counts as 1000 on the error score.
Definition at line 169 of file AbstractSupergeneTest.java.
References examples.supergene.AbstractSupergeneTest.EXISTING_SOLUTIONS_ONLY, examples.supergene.AbstractSupergeneTest.makeChangeForAmount(), examples.supergene.AbstractSupergeneTest.REPORT_ENABLED, and examples.supergene.Force.solve().
Referenced by examples.supergene.SupergeneSample.main().
Member Data Documentation
final String examples.supergene.AbstractSupergeneTest.CVS_REVISION = `$Revision: 1.5 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file AbstractSupergeneTest.java.
final int examples.supergene.AbstractSupergeneTest.DIMES = 0 [static]
Gene index for the dimes gene
Definition at line 30 of file AbstractSupergeneTest.java.
Referenced by examples.supergene.AbstractChangeFitnessFunction.amountOfChange(), examples.supergene.AbstractChangeFitnessFunction.getTotalNumberOfCoins(), examples.supergene.SupergeneSample.makeChangeForAmount(), and examples.supergene.AbstractSupergeneTest.report().
boolean examples.supergene.AbstractSupergeneTest.EXISTING_SOLUTIONS_ONLY = false [static]
If set to true (required for strict tests), only tasks with existing solutions will be submitted as a test tasks.
Definition at line 162 of file AbstractSupergeneTest.java.
Referenced by examples.supergene.AbstractSupergeneTest.test().
int examples.supergene.AbstractSupergeneTest.MAX_ALLOWED_EVOLUTIONS = 200 [static]
The total number of times we'll let the population evolve.
Definition at line 50 of file AbstractSupergeneTest.java.
Referenced by examples.supergene.AbstractSupergeneTest.solve().
final int examples.supergene.AbstractSupergeneTest.NICKELS = 2 [static]
Gene index for the nickels gene Only used in the alternative presentation
Definition at line 40 of file AbstractSupergeneTest.java.
Referenced by examples.supergene.AbstractChangeFitnessFunction.amountOfChange(), examples.supergene.AbstractChangeFitnessFunction.getTotalNumberOfCoins(), and examples.supergene.AbstractSupergeneTest.report().
final int examples.supergene.AbstractSupergeneTest.PENNIES = 3 [static]
Gene index for the pennies gene. Only used in the alternative presentation
Definition at line 45 of file AbstractSupergeneTest.java.
Referenced by examples.supergene.AbstractChangeFitnessFunction.amountOfChange(), examples.supergene.AbstractChangeFitnessFunction.getTotalNumberOfCoins(), and examples.supergene.AbstractSupergeneTest.report().
int examples.supergene.AbstractSupergeneTest.POPULATION_SIZE = 2000 [static]
Chromosome size.
Definition at line 55 of file AbstractSupergeneTest.java.
Referenced by examples.supergene.AbstractSupergeneTest.solve().
final int examples.supergene.AbstractSupergeneTest.QUARTERS = 1 [static]
Gene index for the quarters gene.
Definition at line 35 of file AbstractSupergeneTest.java.
Referenced by examples.supergene.AbstractChangeFitnessFunction.amountOfChange(), examples.supergene.AbstractChangeFitnessFunction.getTotalNumberOfCoins(), examples.supergene.SupergeneSample.makeChangeForAmount(), and examples.supergene.AbstractSupergeneTest.report().
boolean examples.supergene.AbstractSupergeneTest.REPORT_ENABLED = true [static]
Definition at line 57 of file AbstractSupergeneTest.java.
Referenced by examples.supergene.AbstractSupergeneTest.report(), and examples.supergene.AbstractSupergeneTest.test().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/supergene/AbstractSupergeneTest.java