org.jgap.gp.function.statistics.Kurtosis Class Reference
Public Member Functions
Kurtosis (GPConfiguration a_conf, int a_arityInitial, int a_arityMin, int a_arityMax, Class a_returnType) throws InvalidConfigurationException
String toString ()
double execute_double (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
String getName ()
Object clone ()
Additional Inherited Members
Detailed Description
Computes the Kurtosis of the available values.
We use the following (unbiased) formula to define kurtosis:
kurtosis = { [n(n+1) / (n -1)(n - 2)(n-3)] sum[(x_i - mean)^4] / std^4 } - [3(n-1)^2 / (n-2)(n-3)]
where n is the number of values, and std is the Standard Deviation
Author
Luis Garcia
Since
3.5
Definition at line 31 of file Kurtosis.java.
Constructor & Destructor Documentation
org.jgap.gp.function.statistics.Kurtosis.Kurtosis (GPConfiguration a_conf, int a_arityInitial, int a_arityMin, int a_arityMax, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 33 of file Kurtosis.java.
Referenced by org.jgap.gp.function.statistics.Kurtosis.clone().
Member Function Documentation
Object org.jgap.gp.function.statistics.Kurtosis.clone () [inline]
Returns
clone of the current object instance
Implements org.jgap.util.ICloneable.
Definition at line 78 of file Kurtosis.java.
References org.jgap.gp.CommandGene.getArity(), org.jgap.gp.CommandGene.getArityMax(), org.jgap.gp.CommandGene.getArityMin(), org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.function.statistics.Kurtosis.Kurtosis().
double org.jgap.gp.function.statistics.Kurtosis.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 53 of file Kurtosis.java.
References org.jgap.gp.CommandGene.size().
float org.jgap.gp.function.statistics.Kurtosis.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 63 of file Kurtosis.java.
References org.jgap.gp.CommandGene.size().
String org.jgap.gp.function.statistics.Kurtosis.getName () [inline]
Definition at line 73 of file Kurtosis.java.
String org.jgap.gp.function.statistics.Kurtosis.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 40 of file Kurtosis.java.
References org.jgap.gp.CommandGene.size().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/statistics/Kurtosis.java