org.jgap.gp.impl.ProgramChromosomeTest Class Reference
Public Member Functions
void setUp ()
void testConstruct_0 () throws Exception
void testGrowNode_0 () throws Exception
void testGrowNode_1 () throws Exception
void testGrowNode_2 () throws Exception
void testGrowNode_3 () throws Exception
void testGrowNode_4 () throws Exception
void testGrowNode_4_2 () throws Exception
void testGrowNode_4_3 () throws Exception
void testGrowNode_5 () throws Exception
void testToStringNorm_0 () throws Exception
void testToStringNorm_1 () throws Exception
void testToStringNorm_2 () throws Exception
void testToStringNorm_3 () throws Exception
void testToStringNorm_4 () throws Exception
void testToStringNorm_5 () throws Exception
void testToStringNorm_6 () throws Exception
void testToStringNorm_7 () throws Exception
void testToStringNorm_8 () throws Exception
void testToStringNorm_9 () throws Exception
void testToStringNorm_A () throws Exception
void testToStringNorm_B () throws Exception
void testToStringNorm_C () throws Exception
void testToString_0 () throws Exception
void testToString_1 () throws Exception
void testRedepth_0 () throws Exception
void testGetDepth_0 () throws Exception
void testGetDepth_1 () throws Exception
void testGetDepth_2 () throws Exception
void testSerialize_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.14 $`
Additional Inherited Members
Detailed Description
Tests the ProgramChromosome class.
Author
Klaus Meffert
Since
3.0
Definition at line 23 of file ProgramChromosomeTest.java.
Member Function Documentation
void org.jgap.gp.impl.ProgramChromosomeTest.setUp () [inline]
Definition at line 33 of file ProgramChromosomeTest.java.
static Test org.jgap.gp.impl.ProgramChromosomeTest.suite () [inline], [static]
Definition at line 28 of file ProgramChromosomeTest.java.
void org.jgap.gp.impl.ProgramChromosomeTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.3
Definition at line 43 of file ProgramChromosomeTest.java.
References org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testGetDepth_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 673 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.impl.ProgramChromosome.getDepth(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testGetDepth_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 691 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.impl.ProgramChromosome.getDepth(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testGetDepth_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 711 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.impl.ProgramChromosome.getDepth(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_0 () throws Exception [inline]
Produce a valid program. Random numbers preset to optimum (= hit at first number returned by generator).
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 62 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.GPTestCase.CMD_ADD, org.jgap.gp.GPTestCase.CMD_FOR, org.jgap.gp.GPTestCase.CMD_NOP, org.jgap.gp.impl.ProgramChromosome.getNode(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_1 () throws Exception [inline]
Produce a valid program. Random numbers preset to sub-optimum (multiple requests to generator necessary).
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 96 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.GPTestCase.CMD_ADD, org.jgap.gp.GPTestCase.CMD_FOR, org.jgap.gp.GPTestCase.CMD_NOP, org.jgap.gp.impl.ProgramChromosome.getNode(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_2 () throws Exception [inline]
Produce a valid program that is similar to computing Fibonacci.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 135 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.GPTestCase.CMD_FORX, org.jgap.gp.GPTestCase.CMD_NOP, org.jgap.gp.impl.ProgramChromosome.getNode(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_3 () throws Exception [inline]
Produce a valid program that is similar to computing Fibonacci.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 173 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.GPTestCase.CMD_FOR, org.jgap.gp.GPTestCase.CMD_NOP, org.jgap.gp.impl.ProgramChromosome.getDepth(), org.jgap.gp.impl.ProgramChromosome.getNode(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_4 () throws Exception [inline]
Produce a valid program. Random numbers preset to optimum (= hit at first number returned by generator).
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 214 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.GPTestCase.CMD_SUB_I_I, org.jgap.gp.GPTestCase.CMD_TERM0, org.jgap.gp.impl.ProgramChromosome.getNode(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_4_2 () throws Exception [inline]
Mutate arity of sub program: Increase arity from 2 to 3.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 242 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.GPTestCase.CMD_TERM0, org.jgap.gp.impl.ProgramChromosome.getNode(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_4_3 () throws Exception [inline]
Mutate arity of sub program: Reduce arity from 3 to 2.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 280 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.GPTestCase.CMD_SUB_I_I, org.jgap.gp.GPTestCase.CMD_TERM0, org.jgap.gp.impl.ProgramChromosome.getNode(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_5 () throws Exception [inline]
Produce a valid program. Random numbers preset to optimum (= hit at first number returned by generator).
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 316 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.GPTestCase.CMD_SUB_I_I, org.jgap.gp.GPTestCase.CMD_TERM0, org.jgap.gp.impl.ProgramChromosome.getNode(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testRedepth_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 654 of file ProgramChromosomeTest.java.
References org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testSerialize_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 736 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.doSerialize(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testToString_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 618 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testToString_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 635 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 345 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.GPTestCase.m_gpconf, and org.jgap.gp.impl.ProgramChromosome.toStringNorm().
void org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 359 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 375 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 392 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 409 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 428 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 449 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_7 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 469 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_8 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 495 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_9 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.6
Definition at line 519 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_A () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.6
Definition at line 540 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_B () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.6
Definition at line 565 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_C () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.6
Definition at line 590 of file ProgramChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
Member Data Documentation
final String org.jgap.gp.impl.ProgramChromosomeTest.CVS_REVISION = `$Revision: 1.14 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file ProgramChromosomeTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/gp/impl/ProgramChromosomeTest.java