org.jgap.gp.function.IncrementMemory Class Reference
Public Member Functions
IncrementMemory (final GPConfiguration a_conf, Class a_returnType, String a_memoryName, int a_initialValue) throws InvalidConfigurationException
IncrementMemory (final GPConfiguration a_conf, Class a_returnType, String a_memoryName, int a_initialValue, int a_increment) throws InvalidConfigurationException
String toString ()
String getName ()
int execute_int (ProgramChromosome c, int n, Object[] args)
int compareTo (Object a_other)
boolean equals (Object a_other)
Object clone ()
Private Attributes
int m_increment
String m_memoryName
int m_initialValue
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.6 $`
Additional Inherited Members
Detailed Description
Increments the value of a memory cell and returns the incremented value. Allows presetting a value in case the memory cell is not initialized.
Author
Klaus Meffert
Since
3.2
Definition at line 25 of file IncrementMemory.java.
Constructor & Destructor Documentation
org.jgap.gp.function.IncrementMemory.IncrementMemory (final GPConfiguration a_conf, Class a_returnType, String a_memoryName, int a_initialValue) throws InvalidConfigurationException [inline]
Constructor for using an increment of 1.
Parameters
a_conf the configuration to use
a_returnType the type of the terminal to increment (e.g. IntegerClass)
a_memoryName name of the memory cell
a_initialValue initial value of the memory cell
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.2
Definition at line 49 of file IncrementMemory.java.
Referenced by org.jgap.gp.function.IncrementMemory.clone(), org.jgap.gp.function.IncrementMemory.compareTo(), and org.jgap.gp.function.IncrementMemory.equals().
org.jgap.gp.function.IncrementMemory.IncrementMemory (final GPConfiguration a_conf, Class a_returnType, String a_memoryName, int a_initialValue, int a_increment) throws InvalidConfigurationException [inline]
Constructor to freely choose increment.
Parameters
a_conf the configuration to use
a_returnType the type of the terminal to increment (e.g. IntegerClass)
a_memoryName name of the memory cell
a_initialValue initial value of the memory cell
a_increment the increment to use, may also be negative
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.2
Definition at line 68 of file IncrementMemory.java.
References org.jgap.gp.function.IncrementMemory.m_increment, org.jgap.gp.function.IncrementMemory.m_initialValue, and org.jgap.gp.function.IncrementMemory.m_memoryName.
Member Function Documentation
Object org.jgap.gp.function.IncrementMemory.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 167 of file IncrementMemory.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), org.jgap.gp.function.IncrementMemory.IncrementMemory(), org.jgap.gp.function.IncrementMemory.m_increment, org.jgap.gp.function.IncrementMemory.m_initialValue, and org.jgap.gp.function.IncrementMemory.m_memoryName.
int org.jgap.gp.function.IncrementMemory.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.2
Definition at line 120 of file IncrementMemory.java.
References org.jgap.gp.function.IncrementMemory.IncrementMemory(), org.jgap.gp.function.IncrementMemory.m_increment, and org.jgap.gp.function.IncrementMemory.m_memoryName.
boolean org.jgap.gp.function.IncrementMemory.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Klaus Meffert
Since
3.2
Definition at line 142 of file IncrementMemory.java.
References org.jgap.gp.function.IncrementMemory.IncrementMemory(), org.jgap.gp.function.IncrementMemory.m_increment, and org.jgap.gp.function.IncrementMemory.m_memoryName.
int org.jgap.gp.function.IncrementMemory.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 97 of file IncrementMemory.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.function.IncrementMemory.m_initialValue, and org.jgap.gp.function.IncrementMemory.m_memoryName.
String org.jgap.gp.function.IncrementMemory.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 93 of file IncrementMemory.java.
References org.jgap.gp.function.IncrementMemory.m_memoryName.
String org.jgap.gp.function.IncrementMemory.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 78 of file IncrementMemory.java.
References org.jgap.gp.function.IncrementMemory.m_increment, and org.jgap.gp.function.IncrementMemory.m_memoryName.
Member Data Documentation
final String org.jgap.gp.function.IncrementMemory.CVS_REVISION = `$Revision: 1.6 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file IncrementMemory.java.
int org.jgap.gp.function.IncrementMemory.m_increment [private]
Definition at line 30 of file IncrementMemory.java.
Referenced by org.jgap.gp.function.IncrementMemory.clone(), org.jgap.gp.function.IncrementMemory.compareTo(), org.jgap.gp.function.IncrementMemory.equals(), org.jgap.gp.function.IncrementMemory.IncrementMemory(), and org.jgap.gp.function.IncrementMemory.toString().
int org.jgap.gp.function.IncrementMemory.m_initialValue [private]
Definition at line 34 of file IncrementMemory.java.
Referenced by org.jgap.gp.function.IncrementMemory.clone(), org.jgap.gp.function.IncrementMemory.execute_int(), and org.jgap.gp.function.IncrementMemory.IncrementMemory().
String org.jgap.gp.function.IncrementMemory.m_memoryName [private]
Definition at line 32 of file IncrementMemory.java.
Referenced by org.jgap.gp.function.IncrementMemory.clone(), org.jgap.gp.function.IncrementMemory.compareTo(), org.jgap.gp.function.IncrementMemory.equals(), org.jgap.gp.function.IncrementMemory.execute_int(), org.jgap.gp.function.IncrementMemory.getName(), org.jgap.gp.function.IncrementMemory.IncrementMemory(), and org.jgap.gp.function.IncrementMemory.toString().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/IncrementMemory.java