examples.gp.Fibonacci Class Reference
Classes
class FormulaFitnessFunction
Public Member Functions
Fibonacci (GPConfiguration a_conf) throws InvalidConfigurationException
GPGenotype create () throws InvalidConfigurationException
Static Public Member Functions
static void main (String[] args)
static void writeToStream (IGPProgram prog) throws Exception
static Object readFromStream () throws Exception
Static Private Member Functions
static int fib_iter (int a_index)
static int fib_array (int a_index)
static int fib (int a_index)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.34 $`
static final int NUMFIB = 10
static PersistableObject po
static final String PERSISTFILENAME = `c:\\xstreamtest.xml`
Additional Inherited Members
Detailed Description
Example demonstrating Genetic Programming (GP) capabilities of JGAP.
Here, the Fibonacci sequence is calculated (only integers are used).
Please note: We try to find a program that computes Fibonacci iteratively.
This example utilizes a INodeValidator (see FibonacciNodeValidator).
Each new best solution found will be displayed as a graphical tree representing the GP. The tree is written to a PNG-imagefile onto harddisk.
Author
Klaus Meffert
Since
3.0
Definition at line 35 of file Fibonacci.java.
Constructor & Destructor Documentation
examples.gp.Fibonacci.Fibonacci (GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Definition at line 55 of file Fibonacci.java.
References examples.gp.Fibonacci.PERSISTFILENAME, and examples.gp.Fibonacci.po.
Referenced by examples.gp.Fibonacci.main().
Member Function Documentation
GPGenotype examples.gp.Fibonacci.create () throws InvalidConfigurationException [inline], [virtual]
Sets up the functions to use and other parameters. Then creates the initial genotype.
Returns
the genotype created
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Todo
Todo allow to optionally preset a static program in each chromosome
Implements org.jgap.gp.GPProblem.
Definition at line 71 of file Fibonacci.java.
References examples.gp.Fibonacci.fib_iter(), org.jgap.gp.GPProblem.getGPConfiguration(), org.jgap.gp.CommandGene.IntegerClass, examples.gp.Fibonacci.NUMFIB, and org.jgap.gp.CommandGene.VoidClass.
static int examples.gp.Fibonacci.fib (int a_index) [inline], [static], [private]
Definition at line 169 of file Fibonacci.java.
static int examples.gp.Fibonacci.fib_array (int a_index) [inline], [static], [private]
Definition at line 153 of file Fibonacci.java.
static int examples.gp.Fibonacci.fib_iter (int a_index) [inline], [static], [private]
Definition at line 134 of file Fibonacci.java.
Referenced by examples.gp.Fibonacci.create().
static void examples.gp.Fibonacci.main (String[] args) [inline], [static]
Starts the example.
Parameters
args ignored
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
New best solution found.
Parameters
a_firedEvent GeneticEvent
Definition at line 185 of file Fibonacci.java.
References examples.gp.Fibonacci.Fibonacci(), org.jgap.gp.impl.GPGenotype.getAllTimeBest(), examples.gp.Fibonacci.readFromStream(), and examples.gp.Fibonacci.writeToStream().
static Object examples.gp.Fibonacci.readFromStream () throws Exception [inline], [static]
Definition at line 387 of file Fibonacci.java.
References examples.gp.Fibonacci.PERSISTFILENAME.
Referenced by examples.gp.Fibonacci.main().
static void examples.gp.Fibonacci.writeToStream (IGPProgram prog) throws Exception [inline], [static]
Definition at line 361 of file Fibonacci.java.
References examples.gp.Fibonacci.PERSISTFILENAME.
Referenced by examples.gp.Fibonacci.main().
Member Data Documentation
final String examples.gp.Fibonacci.CVS_REVISION = `$Revision: 1.34 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 38 of file Fibonacci.java.
final int examples.gp.Fibonacci.NUMFIB = 10 [static], [private]
Definition at line 46 of file Fibonacci.java.
Referenced by examples.gp.Fibonacci.FormulaFitnessFunction.computeRawFitness(), and examples.gp.Fibonacci.create().
final String examples.gp.Fibonacci.PERSISTFILENAME = `c:\\xstreamtest.xml` [static], [private]
Definition at line 53 of file Fibonacci.java.
Referenced by examples.gp.Fibonacci.Fibonacci(), examples.gp.Fibonacci.readFromStream(), and examples.gp.Fibonacci.writeToStream().
PersistableObject examples.gp.Fibonacci.po [static], [private]
Definition at line 52 of file Fibonacci.java.
Referenced by examples.gp.Fibonacci.Fibonacci().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/Fibonacci.java