org.jgap.impl.BooleanGeneTest Class Reference
Public Member Functions
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testConstruct_2 () throws Exception
void testConstruct_3 () throws Exception
void testConstruct_4 () throws Exception
void testToString_0 () throws Exception
void testToString_1 () throws Exception
void testToString_2 () throws Exception
void testGetAllele_0 () throws Exception
void testGetAllele_1 () throws Exception
void testGetAllele_2 () throws Exception
void testEquals_0 () throws Exception
void testEquals_1 () throws Exception
void testEquals_2 () throws Exception
void testEquals_3 () throws Exception
void testEquals_4 () throws Exception
void testEquals_5 () throws Exception
void testBooleanValue_0 () throws Exception
void testBooleanValue_1 () throws Exception
void testBooleanValue_2 () throws Exception
void testSetAllele_0 () throws Exception
void testSetAllele_1 () throws Exception
void testSetAllele_2 () throws Exception
void testSetAllele_3 () throws Exception
void testCompareTo_0 () throws Exception
void testCompareTo_1 () throws Exception
void testCompareTo_2 () throws Exception
void testCompareTo_3 () throws Exception
void testCompareTo_4 () throws Exception
void testCompareTo_5 () throws Exception
void testCompareTo_6 () throws Exception
void testCompareTo_6_2 () throws Exception
void testCompareTo_6_3 () throws Exception
void testCompareTo_7 () throws Exception
void testApplyMutation_0 () throws Exception
void testApplyMutation_1 () throws Exception
void testApplyMutation_2 () throws Exception
void testApplyMutation_3 () throws Exception
void testApplyMutation_4 () throws Exception
void testApplyMutation_5 () throws Exception
void testApplyMutation_6 () throws Exception
void testApplyMutation_7 () throws Exception
void testApplyMutation_8 () throws Exception
void testApplyMutation_9 () throws Exception
void testApplyMutation_10 () throws Exception
void testSetValueFromPersistentRepresentation_0 () throws Exception
void testSetValueFromPersistentRepresentation_1 () throws Exception
void testSetValueFromPersistentRepresentation_2 () throws Exception
void testSetValueFromPersistentRepresentation_3 () throws Exception
void testSetValueFromPersistentRepresentation_4 () throws Exception
void testSetValueFromPersistentRepresentation_5 () throws Exception
void testSetValueFromPersistentRepresentation_6 () throws Exception
void testGetPersistentRepresentation_0 () throws Exception
void testGetPersistentRepresentation_1 () throws Exception
void testGetPersistentRepresentation_2 () throws Exception
void testHashCode_0 () throws Exception
void testSetEnergy_0 () throws Exception
void testSetEnergy_1 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.22 $`
Additional Inherited Members
Detailed Description
Tests the BooleanGene class.
Author
Klaus Meffert
Since
1.1
Definition at line 22 of file BooleanGeneTest.java.
Member Function Documentation
static Test org.jgap.impl.BooleanGeneTest.suite () [inline], [static]
Definition at line 27 of file BooleanGeneTest.java.
void org.jgap.impl.BooleanGeneTest.testApplyMutation_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 408 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testApplyMutation_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 421 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testApplyMutation_10 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 539 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testApplyMutation_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 434 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testApplyMutation_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 447 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testApplyMutation_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 460 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testApplyMutation_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 473 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testApplyMutation_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 486 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testApplyMutation_7 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 499 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testApplyMutation_8 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 512 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testApplyMutation_9 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 525 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testBooleanValue_0 () throws Exception [inline]
Definition at line 193 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testBooleanValue_1 () throws Exception [inline]
Definition at line 200 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testBooleanValue_2 () throws Exception [inline]
Definition at line 207 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testCompareTo_0 () throws Exception [inline]
Definition at line 263 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testCompareTo_1 () throws Exception [inline]
Definition at line 269 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testCompareTo_2 () throws Exception [inline]
Definition at line 277 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testCompareTo_3 () throws Exception [inline]
Definition at line 291 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testCompareTo_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 307 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testCompareTo_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 322 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testCompareTo_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 336 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testCompareTo_6_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 354 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testCompareTo_6_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 374 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testCompareTo_7 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 394 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testConstruct_0 () throws Exception [inline]
Definition at line 32 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testConstruct_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 46 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testConstruct_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 60 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.BooleanGene.booleanValue(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testConstruct_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 74 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testConstruct_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 90 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testEquals_0 () throws Exception [inline]
Definition at line 148 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testEquals_1 () throws Exception [inline]
Definition at line 155 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testEquals_2 () throws Exception [inline]
Definition at line 161 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testEquals_3 () throws Exception [inline]
Definition at line 171 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testEquals_4 () throws Exception [inline]
Definition at line 177 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testEquals_5 () throws Exception [inline]
Definition at line 185 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testGetAllele_0 () throws Exception [inline]
Definition at line 123 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testGetAllele_1 () throws Exception [inline]
Definition at line 130 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testGetAllele_2 () throws Exception [inline]
Definition at line 137 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testGetPersistentRepresentation_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 658 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testGetPersistentRepresentation_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 671 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testGetPersistentRepresentation_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 684 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testHashCode_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 697 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.BooleanGene.hashCode().
void org.jgap.impl.BooleanGeneTest.testSetAllele_0 () throws Exception [inline]
Set Allele to null, no exception should occur.
Exceptions
Exception
Definition at line 224 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testSetAllele_1 () throws Exception [inline]
Definition at line 230 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testSetAllele_2 () throws Exception [inline]
Set Allele to boolean value, no exception should occur.
Exceptions
Exception
Definition at line 246 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testSetAllele_3 () throws Exception [inline]
Set Allele to boolean value, no exception should occur.
Exceptions
Exception
Definition at line 257 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testSetEnergy_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 709 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getEnergy().
void org.jgap.impl.BooleanGeneTest.testSetEnergy_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 721 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getEnergy().
void org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 552 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 569 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 582 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 595 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 608 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 625 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 642 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BooleanGeneTest.testToString_0 () throws Exception [inline]
Definition at line 97 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.toString().
void org.jgap.impl.BooleanGeneTest.testToString_1 () throws Exception [inline]
Definition at line 104 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.toString().
void org.jgap.impl.BooleanGeneTest.testToString_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 117 of file BooleanGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.toString().
Member Data Documentation
final String org.jgap.impl.BooleanGeneTest.CVS_REVISION = `$Revision: 1.22 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file BooleanGeneTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/BooleanGeneTest.java