org.jgap.ConfigurationTest Class Reference
Public Member Functions
void setUp ()
void testAddGeneticOperator_0 ()
void testAddGeneticOperator_1 ()
void testAddGeneticOperator_2 () throws Exception
void testVerifyStateIsValid_0 () throws Exception
void testVerifyStateIsValid_1 () throws Exception
void testVerifyStateIsValid_2 () throws Exception
void testVerifyStateIsValid_3 () throws Exception
void testVerifyStateIsValid_4 () throws Exception
void testVerifyStateIsValid_5 () throws Exception
void testVerifyStateIsValid_6 () throws Exception
void testVerifyStateIsValid_7 () throws Exception
void testVerifyStateIsValid_8 () throws Exception
void testVerifyStateIsValid_9 () throws Exception
void testIsLocked_0 () throws Exception
void testGetter_0 () throws Exception
void testSetNaturalSelector_0 () throws Exception
void testGetNaturalSelector_0 ()
void testGetNaturalSelector_1 () throws Exception
void testGetNaturalSelector_2 () throws Exception
void testGetNaturalSelector_3 () throws Exception
void testGetNaturalSelector_4 () throws Exception
void testAddNaturalSelector_0 () throws Exception
void testAddNaturalSelector_1 () throws Exception
void testAddNaturalSelector_2 () throws Exception
void testAddNaturalSelector_3 () throws Exception
void testAddNaturalSelector_4 () throws Exception
void testSetFitnessFunction_0 ()
void testSetFitnessFunction_1 () throws Exception
void testSetFitnessFunction_2 () throws Exception
void testSetFitnessFunction_3 () throws Exception
void testSetFitnessFunction_4 () throws Exception
void testSetFitnessEvaluator_0 ()
void testSetPreserveFittestIndividual_0 ()
void testGenerationNr_0 ()
void testSetBulkFitnessFunction_0 ()
void testSetBulkFitnessFunction_1 () throws Exception
void testSetBulkFitnessFunction_2 () throws Exception
void testSetBulkFitnessFunction_3 () throws Exception
void testSetBulkFitnessFunction_4 () throws Exception
void testSetBulkFitnessFunction_5 () throws Exception
void testSetBulkFitnessFunction_6 () throws Exception
void testGetPopulationSize_0 () throws Exception
void testSetPopulationSize_1 () throws Exception
void testSetRandomGenerator_0 ()
void testSetEventManager_0 ()
void testSetEventManager_1 () throws Exception
void testSetEventManager_2 () throws Exception
void testSetEventManager_3 () throws Exception
void testLock_0 () throws Exception
void testLock_1 () throws Exception
void testSetSampleChromosome_0 () throws Exception
void testGetChromosomeSize_0 () throws Exception
void testToString_0 () throws Exception
void testToString_1 () throws Exception
void testGetName_0 ()
void testGetName_1 ()
void testGetName_2 ()
void testKeepPopSizeConstant_0 ()
void testConstruct_0 ()
void testConstruct_1 ()
void testConstruct_2 ()
void testConstruct_3 ()
void testClone_0 () throws Exception
void testClone_1 () throws Exception
void testClone_2 () throws Exception
void testRemoveNaturalSelector_0 () throws Exception
void testRemoveNaturalSelector_1 () throws Exception
void testRemoveNaturalSelector_2 () throws Exception
void testSetAlwaysCalculateFitness_0 () throws Exception
void testRemoveNaturalSelector_3 () throws Exception
Static Public Member Functions
static Test suite ()
Private Member Functions
String trimString (String s1)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.46 $`
Additional Inherited Members
Detailed Description
Tests the Configuration class.
Author
Klaus Meffert
Since
1.1
Definition at line 22 of file ConfigurationTest.java.
Member Function Documentation
void org.jgap.ConfigurationTest.setUp () [inline]
Definition at line 32 of file ConfigurationTest.java.
static Test org.jgap.ConfigurationTest.suite () [inline], [static]
Definition at line 27 of file ConfigurationTest.java.
void org.jgap.ConfigurationTest.testAddGeneticOperator_0 () [inline]
Author
Klaus Meffert
Definition at line 42 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testAddGeneticOperator_1 () [inline]
Author
Klaus Meffert
Definition at line 55 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testAddGeneticOperator_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 71 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.getGeneticOperators().
void org.jgap.ConfigurationTest.testAddNaturalSelector_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 436 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.getNaturalSelectors().
void org.jgap.ConfigurationTest.testAddNaturalSelector_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 449 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.getNaturalSelectors().
void org.jgap.ConfigurationTest.testAddNaturalSelector_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 462 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.getNaturalSelectors().
void org.jgap.ConfigurationTest.testAddNaturalSelector_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 485 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testAddNaturalSelector_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 501 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testClone_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 1222 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.Configuration.clone(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testClone_1 () throws Exception [inline]
Cloning multiple times in a row must be possible.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 1252 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.Configuration.clone(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testClone_2 () throws Exception [inline]
Clone after settings locked.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 1279 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.Configuration.clone(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testConstruct_0 () [inline]
Construct with valid System property for JGAPFactory set.
Author
Klaus Meffert
Since
2.6
Definition at line 1165 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.PROPERTY_JGAPFACTORY_CLASS.
void org.jgap.ConfigurationTest.testConstruct_1 () [inline]
Construct with invalid System property for JGAPFactory set.
Author
Klaus Meffert
Since
2.6
Definition at line 1178 of file ConfigurationTest.java.
References org.jgap.Configuration.PROPERTY_JGAPFACTORY_CLASS.
void org.jgap.ConfigurationTest.testConstruct_2 () [inline]
Construct with no System property for JGAPFactory set.
Author
Klaus Meffert
Since
3.0
Definition at line 1195 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.PROPERTY_JGAPFACTORY_CLASS.
void org.jgap.ConfigurationTest.testConstruct_3 () [inline]
Construct with explicit ID given.
Author
Klaus Meffert
Since
3.2
Definition at line 1207 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.Configuration.getId().
void org.jgap.ConfigurationTest.testGenerationNr_0 () [inline]
Author
Klaus Meffert
Definition at line 622 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.getGenerationNr().
void org.jgap.ConfigurationTest.testGetChromosomeSize_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 892 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.getChromosomeSize().
void org.jgap.ConfigurationTest.testGetName_0 () [inline]
Author
Klaus Meffert
Definition at line 1119 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.getName().
void org.jgap.ConfigurationTest.testGetName_1 () [inline]
Author
Klaus Meffert
Definition at line 1127 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.getName().
void org.jgap.ConfigurationTest.testGetName_2 () [inline]
Author
Klaus Meffert
Definition at line 1138 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.getName().
void org.jgap.ConfigurationTest.testGetNaturalSelector_0 () [inline]
Tests a deprecated function!
Definition at line 368 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testGetNaturalSelector_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 380 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.getNaturalSelector().
void org.jgap.ConfigurationTest.testGetNaturalSelector_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 392 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testGetNaturalSelector_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 407 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testGetNaturalSelector_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 424 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.getNaturalSelector().
void org.jgap.ConfigurationTest.testGetPopulationSize_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 736 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.getPopulationSize().
void org.jgap.ConfigurationTest.testGetter_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 320 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.Configuration.getEventManager(), org.jgap.Configuration.getFitnessFunction(), org.jgap.Configuration.getGeneticOperators(), org.jgap.Configuration.getNaturalSelectors(), org.jgap.Configuration.getPopulationSize(), org.jgap.Configuration.getRandomGenerator(), org.jgap.Configuration.getSampleChromosome(), and org.jgap.Configuration.isLocked().
void org.jgap.ConfigurationTest.testIsLocked_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 297 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.isLocked().
void org.jgap.ConfigurationTest.testKeepPopSizeConstant_0 () [inline]
Author
Klaus Meffert
Since
2.4
Definition at line 1147 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.Configuration.getJGAPFactory(), and org.jgap.Configuration.isKeepPopulationSizeConstant().
void org.jgap.ConfigurationTest.testLock_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 833 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testLock_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 848 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.isLocked().
void org.jgap.ConfigurationTest.testRemoveNaturalSelector_0 () throws Exception [inline]
Exposes bug 1642378.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 1309 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.Configuration.getNaturalSelectors(), and org.jgap.Configuration.getNaturalSelectorsSize().
void org.jgap.ConfigurationTest.testRemoveNaturalSelector_1 () throws Exception [inline]
Exposes bug 1642378.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 1327 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.Configuration.getNaturalSelectors(), and org.jgap.Configuration.getNaturalSelectorsSize().
void org.jgap.ConfigurationTest.testRemoveNaturalSelector_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 1343 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.Configuration.getNaturalSelectors(), and org.jgap.Configuration.getNaturalSelectorsSize().
void org.jgap.ConfigurationTest.testRemoveNaturalSelector_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 1381 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.Configuration.getNaturalSelectors(), and org.jgap.Configuration.getNaturalSelectorsSize().
void org.jgap.ConfigurationTest.testSetAlwaysCalculateFitness_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2.2
Definition at line 1362 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.isAlwaysCalculateFitness().
void org.jgap.ConfigurationTest.testSetBulkFitnessFunction_0 () [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 636 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testSetBulkFitnessFunction_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 650 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testSetBulkFitnessFunction_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 666 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testSetBulkFitnessFunction_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 682 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testSetBulkFitnessFunction_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 694 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testSetBulkFitnessFunction_5 () throws Exception [inline]
Setting the same bulk fitness function should be possible without error.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 713 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testSetBulkFitnessFunction_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 726 of file ConfigurationTest.java.
void org.jgap.ConfigurationTest.testSetEventManager_0 () [inline]
Author
Klaus Meffert
Definition at line 776 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testSetEventManager_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 792 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testSetEventManager_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 805 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testSetEventManager_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 823 of file ConfigurationTest.java.
void org.jgap.ConfigurationTest.testSetFitnessEvaluator_0 () [inline]
Author
Klaus Meffert
Definition at line 597 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testSetFitnessFunction_0 () [inline]
Author
Klaus Meffert
Definition at line 516 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testSetFitnessFunction_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 532 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testSetFitnessFunction_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 550 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testSetFitnessFunction_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 569 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testSetFitnessFunction_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 588 of file ConfigurationTest.java.
void org.jgap.ConfigurationTest.testSetNaturalSelector_0 () throws Exception [inline]
Tests a deprecated function!
Exceptions
Exception
Definition at line 356 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.getNaturalSelectors().
void org.jgap.ConfigurationTest.testSetPopulationSize_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 749 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testSetPreserveFittestIndividual_0 () [inline]
Author
Klaus Meffert
Definition at line 610 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.isPreserveFittestIndividual().
void org.jgap.ConfigurationTest.testSetRandomGenerator_0 () [inline]
Author
Klaus Meffert
Definition at line 763 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testSetSampleChromosome_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 875 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testToString_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 909 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.Configuration.getEventManager(), org.jgap.Configuration.getFitnessEvaluator(), org.jgap.Configuration.getGeneticOperators(), org.jgap.Configuration.getMinimumPopSizePercent(), org.jgap.Configuration.getName(), org.jgap.Configuration.getRandomGenerator(), org.jgap.Configuration.getSampleChromosome(), org.jgap.Configuration.S_CONFIGURATION, org.jgap.Configuration.S_CONFIGURATION_NAME, org.jgap.Configuration.S_FITNESS_EVALUATOR, org.jgap.Configuration.S_MINPOPSIZE, org.jgap.Configuration.S_RANDOM_GENERATOR, org.jgap.Configuration.S_SAMPLE_CHROM, org.jgap.Configuration.S_SIZE, org.jgap.Configuration.S_TOSTRING, org.jgap.Configuration.toString(), and org.jgap.ConfigurationTest.trimString().
void org.jgap.ConfigurationTest.testToString_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1007 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.ConfigurationTest.trimString().
void org.jgap.ConfigurationTest.testVerifyStateIsValid_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 84 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.isLocked().
void org.jgap.ConfigurationTest.testVerifyStateIsValid_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 101 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.isLocked().
void org.jgap.ConfigurationTest.testVerifyStateIsValid_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 120 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.isLocked().
void org.jgap.ConfigurationTest.testVerifyStateIsValid_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 140 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.isLocked().
void org.jgap.ConfigurationTest.testVerifyStateIsValid_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 161 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.isLocked().
void org.jgap.ConfigurationTest.testVerifyStateIsValid_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 183 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.isLocked().
void org.jgap.ConfigurationTest.testVerifyStateIsValid_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 207 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.isLocked().
void org.jgap.ConfigurationTest.testVerifyStateIsValid_7 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 228 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.isLocked().
void org.jgap.ConfigurationTest.testVerifyStateIsValid_8 () throws Exception [inline]
Configuration with sample chromosome that contains no genes.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 256 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ConfigurationTest.testVerifyStateIsValid_9 () throws Exception [inline]
Configuration with sample chromosome that has a gene with allele value null.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 280 of file ConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
String org.jgap.ConfigurationTest.trimString (String s1) [inline], [private]
Parameters
s1 String
Returns
String
Author
Klaus Meffert
Since
2.4
Definition at line 1069 of file ConfigurationTest.java.
Referenced by org.jgap.ConfigurationTest.testToString_0(), and org.jgap.ConfigurationTest.testToString_1().
Member Data Documentation
final String org.jgap.ConfigurationTest.CVS_REVISION = `$Revision: 1.46 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file ConfigurationTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/ConfigurationTest.java