examples.supergene.AbstractChangeFitnessFunction Class Reference
Public Member Functions
AbstractChangeFitnessFunction (int a_targetAmount)
double evaluate (IChromosome a_subject)
int amountOfChange (IChromosome a_potentialSolution)
int getNumberOfCoinsAtGene (IChromosome a_potentialSolution, int a_code)
int getTotalNumberOfCoins (IChromosome a_potentialsolution)
abstract Gene getResponsibleGene (IChromosome a_chromosome, int a_code)
Private Attributes
final int m_targetAmount
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Detailed Description
Sample fitness function for the MakeChange example, including supergenes.
Author
Neil Rotstan
Klaus Meffert
Audrius Meskauskas
Since
2.0
Definition at line 24 of file AbstractChangeFitnessFunction.java.
Constructor & Destructor Documentation
examples.supergene.AbstractChangeFitnessFunction.AbstractChangeFitnessFunction (int a_targetAmount) [inline]
Definition at line 31 of file AbstractChangeFitnessFunction.java.
References examples.supergene.AbstractChangeFitnessFunction.m_targetAmount.
Member Function Documentation
int examples.supergene.AbstractChangeFitnessFunction.amountOfChange (IChromosome a_potentialSolution) [inline]
Calculates the total amount of change (in cents) represented by the given potential solution and returns that amount.
Parameters
a_potentialSolution the potential solution to evaluate
Returns
the total amount of change (in cents) represented by the given solution
Definition at line 97 of file AbstractChangeFitnessFunction.java.
References examples.supergene.AbstractSupergeneTest.DIMES, examples.supergene.AbstractChangeFitnessFunction.getNumberOfCoinsAtGene(), examples.supergene.AbstractSupergeneTest.NICKELS, examples.supergene.AbstractSupergeneTest.PENNIES, and examples.supergene.AbstractSupergeneTest.QUARTERS.
Referenced by examples.supergene.AbstractChangeFitnessFunction.evaluate().
double examples.supergene.AbstractChangeFitnessFunction.evaluate (IChromosome a_subject) [inline]
Determine the fitness of the given Chromosome instance. The higher the return value, the more fit the instance. This method should always return the same fitness value for two equivalent Chromosome instances.
Parameters
a_subject the Chromosome instance to evaluate
Returns
positive integer reflecting the fitness rating of the given Chromosome
Since
2.0
Definition at line 50 of file AbstractChangeFitnessFunction.java.
References examples.supergene.AbstractChangeFitnessFunction.amountOfChange(), examples.supergene.AbstractChangeFitnessFunction.getTotalNumberOfCoins(), and examples.supergene.AbstractChangeFitnessFunction.m_targetAmount.
int examples.supergene.AbstractChangeFitnessFunction.getNumberOfCoinsAtGene (IChromosome a_potentialSolution, int a_code) [inline]
Retrieves the number of coins represented by the given potential solution at the given gene position.
Parameters
a_potentialSolution the potential solution to evaluate
a_code index of gene
Returns
the number of coins represented by the potential solution at the given gene position
Definition at line 119 of file AbstractChangeFitnessFunction.java.
References examples.supergene.AbstractChangeFitnessFunction.getResponsibleGene().
Referenced by examples.supergene.AbstractChangeFitnessFunction.amountOfChange(), and examples.supergene.AbstractChangeFitnessFunction.getTotalNumberOfCoins().
abstract Gene examples.supergene.AbstractChangeFitnessFunction.getResponsibleGene (IChromosome a_chromosome, int a_code) [pure virtual]
Get the gene, responsible for the number of coins, corresponding this code.
Parameters
a_chromosome Chromosome to evaluate
a_code index of Gene
Returns
responsible gene
Implemented in examples.supergene.SupergeneChangeFitnessFunction.
Referenced by examples.supergene.AbstractChangeFitnessFunction.getNumberOfCoinsAtGene().
int examples.supergene.AbstractChangeFitnessFunction.getTotalNumberOfCoins (IChromosome a_potentialsolution) [inline]
Returns the total number of coins represented by all of the genes in the given potential solution.
Parameters
a_potentialsolution the potential solution to evaluate
Returns
the total number of coins represented by the given Chromosome
Definition at line 132 of file AbstractChangeFitnessFunction.java.
References examples.supergene.AbstractSupergeneTest.DIMES, examples.supergene.AbstractChangeFitnessFunction.getNumberOfCoinsAtGene(), examples.supergene.AbstractSupergeneTest.NICKELS, examples.supergene.AbstractSupergeneTest.PENNIES, and examples.supergene.AbstractSupergeneTest.QUARTERS.
Referenced by examples.supergene.AbstractChangeFitnessFunction.evaluate(), and examples.supergene.AbstractSupergeneTest.report().
Member Data Documentation
final String examples.supergene.AbstractChangeFitnessFunction.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file AbstractChangeFitnessFunction.java.
final int examples.supergene.AbstractChangeFitnessFunction.m_targetAmount [private]
Definition at line 29 of file AbstractChangeFitnessFunction.java.
Referenced by examples.supergene.AbstractChangeFitnessFunction.AbstractChangeFitnessFunction(), and examples.supergene.AbstractChangeFitnessFunction.evaluate().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/supergene/AbstractChangeFitnessFunction.java