org.jgap.impl.MapGene Class Reference
Public Member Functions
MapGene () throws InvalidConfigurationException
MapGene (final Configuration a_config) throws InvalidConfigurationException
MapGene (final Configuration a_config, final Map a_alleles) throws InvalidConfigurationException
void addAllele (final Object a_key, final Object a_value)
void addAllele (final Object a_value)
void addAllele (final int a_value)
void addAlleles (final Map a_alleles)
void removeAlleles (final Object a_key)
Map getAlleles ()
void setToRandomValue (final RandomGenerator a_numberGenerator)
void applyMutation (final int a_index, final double a_percentage)
void setValueFromPersistentRepresentation (final String a_representation) throws UnsupportedRepresentationException
String getPersistentRepresentation () throws UnsupportedOperationException
void setAllele (Object a_newValue)
int compareTo (Object a_other)
int hashCode ()
String toString ()
Protected Member Functions
Gene newGeneInternal ()
Object getInternalValue ()
Private Attributes
THashMap m_geneMap
Object m_value
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.26 $`
Additional Inherited Members
Detailed Description
Creates a gene instance in which individual alleles have both a label (key) and a value with a distinct meaning. This allows to realize a gene with a set of valid values instead of a range of values. For example, IntegerGene only allows for values having a continuous range, and does not have a function where it is possible to specify setValue...
This implementation does not support specifying a range of valid integer values. Instead it is planned to provide a constraint checker plugin later on. With this, the current implementation will stay unchanged and can be as performant as possible without losing flexibility.
See Also
class examples.MapGeneExample
Author
Johnathan Kool, Organisation: RSMAS, University of Miami
Klaus Meffert
Since
2.4
Definition at line 34 of file MapGene.java.
Constructor & Destructor Documentation
org.jgap.impl.MapGene.MapGene () throws InvalidConfigurationException [inline]
Default constructor.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Since
2.4
Definition at line 64 of file MapGene.java.
Referenced by org.jgap.impl.MapGene.compareTo(), and org.jgap.impl.MapGene.newGeneInternal().
org.jgap.impl.MapGene.MapGene (final Configuration a_config) throws InvalidConfigurationException [inline]
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 76 of file MapGene.java.
References org.jgap.impl.MapGene.m_geneMap.
org.jgap.impl.MapGene.MapGene (final Configuration a_config, final Map a_alleles) throws InvalidConfigurationException [inline]
Constructor setting up valid alleles directly.
Parameters
a_config the configuration to use
a_alleles the valid alleles of the gene
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.4
Definition at line 92 of file MapGene.java.
References org.jgap.impl.MapGene.addAlleles(), and org.jgap.impl.MapGene.m_geneMap.
Member Function Documentation
void org.jgap.impl.MapGene.addAllele (final Object a_key, final Object a_value) [inline]
Adds a potential allele value to the collection.
Parameters
a_key the key to be added, e.g. a descriptive string value
a_value the Integer value to be added
Since
2.4
Definition at line 119 of file MapGene.java.
Referenced by org.jgap.impl.MapGene.setValueFromPersistentRepresentation().
void org.jgap.impl.MapGene.addAllele (final Object a_value) [inline]
Adds a potential allele value to the collection.
Parameters
a_value the value to be added, also used as key
Author
Klaus Meffert
Since
2.4
Definition at line 131 of file MapGene.java.
void org.jgap.impl.MapGene.addAllele (final int a_value) [inline]
Convenience method for addAllele (Object's that are Integer's)
Parameters
a_value the int value to be added, also used as key
Author
Klaus Meffert
Since
2.4
Definition at line 143 of file MapGene.java.
void org.jgap.impl.MapGene.addAlleles (final Map a_alleles) [inline]
Add a set of potential allele values to the collection
Parameters
a_alleles the set of alleles to be added
Since
2.4
Definition at line 154 of file MapGene.java.
Referenced by org.jgap.impl.MapGene.MapGene().
void org.jgap.impl.MapGene.applyMutation (final int a_index, final double a_percentage) [inline]
See interface Gene for description of applyMutation.
For this kind of gene, providing an index and a percentage of mutation would have no significance because the individual allele forms are independent of one another. In mutating, they can only change from one form to another. It may be possible to weight the likelihood of mutation to different forms, but that is not implemented currently.
Parameters
a_index ignored here
a_percentage ignored here
Author
Klaus Meffert
Johnathan Kool
Since
2.4
Definition at line 222 of file MapGene.java.
References org.jgap.BaseGene.getConfiguration(), and org.jgap.impl.MapGene.setToRandomValue().
int org.jgap.impl.MapGene.compareTo (Object a_other) [inline]
Compares this NumberGene with the specified object (which must also be a NumberGene) for order, which is determined by the number value of this Gene compared to the one provided for comparison.
Parameters
a_other the NumberGene to be compared to this NumberGene
Returns
a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than the object provided for comparison
Exceptions
ClassCastException if the specified object's type prevents it from being compared to this Gene
Author
Klaus Meffert
Johnathan Kool
Since
2.4
Definition at line 420 of file MapGene.java.
References org.jgap.impl.MapGene.m_geneMap, org.jgap.impl.MapGene.m_value, and org.jgap.impl.MapGene.MapGene().
Referenced by org.jgap.impl.MapGeneTest.testCompareTo_0(), org.jgap.impl.MapGeneTest.testCompareTo_1(), org.jgap.impl.MapGeneTest.testCompareTo_2(), and org.jgap.impl.MapGeneTest.testCompareTo_3().
Map org.jgap.impl.MapGene.getAlleles () [inline]
Returns
the map of alleles
Author
Klaus Meffert
Since
3.0
Definition at line 180 of file MapGene.java.
References org.jgap.impl.MapGene.m_geneMap.
Referenced by org.jgap.impl.MapGeneTest.testRemoveAlleles_0(), org.jgap.impl.MapGeneTest.testRemoveAlleles_1(), and org.jgap.impl.MapGeneTest.testSetToRandomValue_1().
Object org.jgap.impl.MapGene.getInternalValue () [inline], [protected], [virtual]
Returns
the internal value of the gene
Since
2.4
Implements org.jgap.BaseGene.
Definition at line 537 of file MapGene.java.
References org.jgap.impl.MapGene.m_value.
Referenced by org.jgap.impl.MapGene.hashCode().
String org.jgap.impl.MapGene.getPersistentRepresentation () throws UnsupportedOperationException [inline]
Retrieves a string representation of this Gene that includes any information required to reconstruct it at a later time, such as its value and internal state. This string will be used to represent this Gene in XML persistence. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Returns
string representation of this Gene's current state
Exceptions
UnsupportedOperationException to indicate that no implementation is provided for this method
Author
Neil Rostan
Klaus Meffert
Since
2.4
Implements org.jgap.IPersistentRepresentation.
Definition at line 352 of file MapGene.java.
References org.jgap.Gene.PERSISTENT_FIELD_DELIMITER.
int org.jgap.impl.MapGene.hashCode () [inline]
Modified hashCode() function to return different hashcodes for differently ordered genes in a chromosome
Returns
-1 if no allele set, otherwise value return by BaseGene.hashCode()
Author
Klaus Meffert
Since
2.4
Definition at line 549 of file MapGene.java.
References org.jgap.impl.MapGene.getInternalValue().
Gene org.jgap.impl.MapGene.newGeneInternal () [inline], [protected], [virtual]
Implements org.jgap.BaseGene.
Definition at line 99 of file MapGene.java.
References org.jgap.BaseGene.getAllele(), org.jgap.BaseGene.getConfiguration(), org.jgap.impl.MapGene.m_geneMap, and org.jgap.impl.MapGene.MapGene().
void org.jgap.impl.MapGene.removeAlleles (final Object a_key) [inline]
Removes a potential allele or set of alleles from the collection.
Parameters
a_key the unique value(s) of the object(s) to be removed
Since
2.4
Definition at line 170 of file MapGene.java.
void org.jgap.impl.MapGene.setAllele (Object a_newValue) [inline]
Sets the value (allele) of this Gene to the new given value. This class expects the value to be an instance of current type (e.g. Integer).
Parameters
a_newValue the new value of this Gene instance
Author
Johnathan Kool, Klaus Meffert
Since
2.4
Implements org.jgap.Gene.
Definition at line 383 of file MapGene.java.
References org.jgap.impl.MapGene.m_geneMap, and org.jgap.impl.MapGene.m_value.
void org.jgap.impl.MapGene.setToRandomValue (final RandomGenerator a_numberGenerator) [inline]
Sets the allele value to be a random value using a defined random number generator. If no valid alleles are defined, any allele is allowed. Then, a new Integer with random value is set as random value. Override this method if you want a different behaviour, such as a Double instead of the Integer type.
Parameters
a_numberGenerator the random generator to use
Author
Klaus Meffert
Since
2.4
Definition at line 196 of file MapGene.java.
References org.jgap.impl.MapGene.m_geneMap, org.jgap.impl.MapGene.m_value, and org.jgap.RandomGenerator.nextInt().
Referenced by org.jgap.impl.MapGene.applyMutation().
void org.jgap.impl.MapGene.setValueFromPersistentRepresentation (final String a_representation) throws UnsupportedRepresentationException [inline]
Sets the value and internal state of this Gene from the string representation returned by a previous invocation of the getPersistentRepresentation() method. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Parameters
a_representation the string representation retrieved from a prior call to the getPersistentRepresentation() method.
Exceptions
UnsupportedOperationException to indicate that no implementation is provided for this method
UnsupportedRepresentationException if this Gene implementation does not support the given string representation.
Author
Neil Rostan
Klaus Meffert
Since
2.4
Definition at line 248 of file MapGene.java.
References org.jgap.impl.MapGene.addAllele(), org.jgap.impl.MapGene.m_value, and org.jgap.Gene.PERSISTENT_FIELD_DELIMITER.
String org.jgap.impl.MapGene.toString () [inline]
Retrieves a string representation of this Gene's value that may be useful for display purposes.
Returns
a string representation of this Gene's value
Author
Klaus Meffert
Since
2.4
Implements org.jgap.Gene.
Definition at line 567 of file MapGene.java.
References org.jgap.impl.MapGene.m_geneMap.
Referenced by org.jgap.impl.MapGeneTest.testToString_0(), org.jgap.impl.MapGeneTest.testToString_1(), org.jgap.impl.MapGeneTest.testToString_2(), org.jgap.impl.MapGeneTest.testToString_3(), org.jgap.impl.MapGeneTest.testToString_4(), and org.jgap.impl.MapGeneTest.testToString_5().
Member Data Documentation
final String org.jgap.impl.MapGene.CVS_REVISION = `$Revision: 1.26 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 37 of file MapGene.java.
THashMap org.jgap.impl.MapGene.m_geneMap [private]
Container for valid alleles
Definition at line 42 of file MapGene.java.
Referenced by org.jgap.impl.MapGene.compareTo(), org.jgap.impl.MapGene.getAlleles(), org.jgap.impl.MapGene.MapGene(), org.jgap.impl.MapGene.newGeneInternal(), org.jgap.impl.MapGene.setAllele(), org.jgap.impl.MapGene.setToRandomValue(), and org.jgap.impl.MapGene.toString().
Object org.jgap.impl.MapGene.m_value [private]
Represents the constant range of values supported by integers.
Definition at line 47 of file MapGene.java.
Referenced by org.jgap.impl.MapGene.compareTo(), org.jgap.impl.MapGene.getInternalValue(), org.jgap.impl.MapGene.setAllele(), org.jgap.impl.MapGene.setToRandomValue(), and org.jgap.impl.MapGene.setValueFromPersistentRepresentation().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/MapGene.java