examples.gp.monalisa.gui.GeneticDrawingView Class Reference
Public Member Functions
GeneticDrawingView (SingleFrameApplication app)
void showAboutBox ()
void chooseImage () throws IOException
void startEvolution ()
ImageIcon scaleToImageLabel (Image image)
BufferedImage getTargetImage ()
boolean isEvolutionActivated ()
boolean isSaveToFile ()
FittestDrawingView getFittestDrawingView ()
JFreeChart getChart ()
Private Member Functions
void initComponents ()
Private Attributes
javax.swing.JPanel chartPanel
javax.swing.JButton chooseImage
javax.swing.JPanel mainPanel
javax.swing.JMenuBar menuBar
javax.swing.JToggleButton startEvolution
javax.swing.JLabel targetImageLabel
JDialog aboutBox
javax.swing.JCheckBox saveCheckBox
javax.swing.JLabel targetSaveDirLabel
javax.swing.JLabel targetSaveDirEdit
BufferedImage targetImage = null
boolean isEvolutionActivated = false
FittestDrawingView fittestDrawingView = null
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Detailed Description
The application's main frame.
Author
Yann N. Dauphin
Since
3.4
Definition at line 29 of file GeneticDrawingView.java.
Constructor & Destructor Documentation
examples.gp.monalisa.gui.GeneticDrawingView.GeneticDrawingView (SingleFrameApplication app) [inline]
Definition at line 34 of file GeneticDrawingView.java.
References examples.gp.monalisa.gui.GeneticDrawingView.fittestDrawingView, examples.gp.monalisa.gui.GeneticDrawingView.initComponents(), and examples.gp.monalisa.gui.GeneticDrawingView.targetImage.
Member Function Documentation
void examples.gp.monalisa.gui.GeneticDrawingView.chooseImage () throws IOException [inline]
Definition at line 59 of file GeneticDrawingView.java.
References examples.gp.monalisa.gui.GeneticDrawingView.mainPanel, examples.gp.monalisa.gui.GeneticDrawingView.scaleToImageLabel(), and examples.gp.monalisa.gui.GeneticDrawingView.targetImage.
Referenced by examples.gp.monalisa.gui.GeneticDrawingView.initComponents().
JFreeChart examples.gp.monalisa.gui.GeneticDrawingView.getChart () [inline]
Definition at line 121 of file GeneticDrawingView.java.
References examples.gp.monalisa.gui.GeneticDrawingView.chartPanel.
FittestDrawingView examples.gp.monalisa.gui.GeneticDrawingView.getFittestDrawingView () [inline]
Definition at line 117 of file GeneticDrawingView.java.
References examples.gp.monalisa.gui.GeneticDrawingView.fittestDrawingView.
BufferedImage examples.gp.monalisa.gui.GeneticDrawingView.getTargetImage () [inline]
Definition at line 105 of file GeneticDrawingView.java.
References examples.gp.monalisa.gui.GeneticDrawingView.targetImage.
Referenced by examples.gp.monalisa.gui.EvolutionRunnable.run().
void examples.gp.monalisa.gui.GeneticDrawingView.initComponents () [inline], [private]
This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 133 of file GeneticDrawingView.java.
References examples.gp.monalisa.gui.GeneticDrawingView.chartPanel, examples.gp.monalisa.gui.GeneticDrawingView.chooseImage(), examples.gp.monalisa.gui.GeneticDrawingView.mainPanel, examples.gp.monalisa.gui.GeneticDrawingView.menuBar, examples.gp.monalisa.gui.GeneticDrawingView.saveCheckBox, examples.gp.monalisa.gui.GeneticDrawingView.startEvolution(), examples.gp.monalisa.gui.GeneticDrawingView.targetImageLabel, examples.gp.monalisa.gui.GeneticDrawingView.targetSaveDirEdit, and examples.gp.monalisa.gui.GeneticDrawingView.targetSaveDirLabel.
Referenced by examples.gp.monalisa.gui.GeneticDrawingView.GeneticDrawingView().
boolean examples.gp.monalisa.gui.GeneticDrawingView.isEvolutionActivated () [inline]
Definition at line 109 of file GeneticDrawingView.java.
Referenced by examples.gp.monalisa.gui.GeneticDrawingView.startEvolution().
boolean examples.gp.monalisa.gui.GeneticDrawingView.isSaveToFile () [inline]
Definition at line 113 of file GeneticDrawingView.java.
Referenced by examples.gp.monalisa.gui.EvolutionRunnable.run().
ImageIcon examples.gp.monalisa.gui.GeneticDrawingView.scaleToImageLabel (Image image) [inline]
Scale an image to fit the size of the targetImageLabel.
Definition at line 92 of file GeneticDrawingView.java.
References examples.gp.monalisa.gui.GeneticDrawingView.targetImageLabel.
Referenced by examples.gp.monalisa.gui.GeneticDrawingView.chooseImage().
void examples.gp.monalisa.gui.GeneticDrawingView.showAboutBox () [inline]
Definition at line 49 of file GeneticDrawingView.java.
References examples.gp.monalisa.gui.GeneticDrawingView.aboutBox.
void examples.gp.monalisa.gui.GeneticDrawingView.startEvolution () [inline]
Definition at line 71 of file GeneticDrawingView.java.
References examples.gp.monalisa.gui.GeneticDrawingView.isEvolutionActivated(), and examples.gp.monalisa.gui.GeneticDrawingView.targetImage.
Referenced by examples.gp.monalisa.gui.GeneticDrawingView.initComponents().
Member Data Documentation
JDialog examples.gp.monalisa.gui.GeneticDrawingView.aboutBox [private]
Definition at line 290 of file GeneticDrawingView.java.
Referenced by examples.gp.monalisa.gui.GeneticDrawingView.showAboutBox().
javax.swing.JPanel examples.gp.monalisa.gui.GeneticDrawingView.chartPanel [private]
Definition at line 277 of file GeneticDrawingView.java.
Referenced by examples.gp.monalisa.gui.GeneticDrawingView.getChart(), and examples.gp.monalisa.gui.GeneticDrawingView.initComponents().
javax.swing.JButton examples.gp.monalisa.gui.GeneticDrawingView.chooseImage [private]
Definition at line 279 of file GeneticDrawingView.java.
final String examples.gp.monalisa.gui.GeneticDrawingView.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 32 of file GeneticDrawingView.java.
FittestDrawingView examples.gp.monalisa.gui.GeneticDrawingView.fittestDrawingView = null [private]
Definition at line 302 of file GeneticDrawingView.java.
Referenced by examples.gp.monalisa.gui.GeneticDrawingView.GeneticDrawingView(), and examples.gp.monalisa.gui.GeneticDrawingView.getFittestDrawingView().
boolean examples.gp.monalisa.gui.GeneticDrawingView.isEvolutionActivated = false [private]
Definition at line 300 of file GeneticDrawingView.java.
Referenced by examples.gp.monalisa.gui.EvolutionRunnable.run().
javax.swing.JPanel examples.gp.monalisa.gui.GeneticDrawingView.mainPanel [private]
Definition at line 281 of file GeneticDrawingView.java.
Referenced by examples.gp.monalisa.gui.GeneticDrawingView.chooseImage(), and examples.gp.monalisa.gui.GeneticDrawingView.initComponents().
javax.swing.JMenuBar examples.gp.monalisa.gui.GeneticDrawingView.menuBar [private]
Definition at line 283 of file GeneticDrawingView.java.
Referenced by examples.gp.monalisa.gui.GeneticDrawingView.initComponents().
javax.swing.JCheckBox examples.gp.monalisa.gui.GeneticDrawingView.saveCheckBox [private]
Definition at line 292 of file GeneticDrawingView.java.
Referenced by examples.gp.monalisa.gui.GeneticDrawingView.initComponents().
javax.swing.JToggleButton examples.gp.monalisa.gui.GeneticDrawingView.startEvolution [private]
Definition at line 285 of file GeneticDrawingView.java.
BufferedImage examples.gp.monalisa.gui.GeneticDrawingView.targetImage = null [private]
Definition at line 298 of file GeneticDrawingView.java.
Referenced by examples.gp.monalisa.gui.GeneticDrawingView.chooseImage(), examples.gp.monalisa.gui.GeneticDrawingView.GeneticDrawingView(), examples.gp.monalisa.gui.GeneticDrawingView.getTargetImage(), and examples.gp.monalisa.gui.GeneticDrawingView.startEvolution().
javax.swing.JLabel examples.gp.monalisa.gui.GeneticDrawingView.targetImageLabel [private]
Definition at line 287 of file GeneticDrawingView.java.
Referenced by examples.gp.monalisa.gui.GeneticDrawingView.initComponents(), and examples.gp.monalisa.gui.GeneticDrawingView.scaleToImageLabel().
javax.swing.JLabel examples.gp.monalisa.gui.GeneticDrawingView.targetSaveDirEdit [private]
Definition at line 296 of file GeneticDrawingView.java.
Referenced by examples.gp.monalisa.gui.GeneticDrawingView.initComponents().
javax.swing.JLabel examples.gp.monalisa.gui.GeneticDrawingView.targetSaveDirLabel [private]
Definition at line 294 of file GeneticDrawingView.java.
Referenced by examples.gp.monalisa.gui.GeneticDrawingView.initComponents().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/monalisa/gui/GeneticDrawingView.java