org.jgap.audit.KeyedValues2D Class Reference
Public Member Functions
KeyedValues2D ()
KeyedValues2D (final boolean a_sortRowKeys)
int getRowCount ()
int getColumnCount ()
Number getValue (final int a_row, final int a_column)
Comparable getRowKey (final int a_row)
int getRowIndex (final Comparable a_key)
List getRowKeys ()
Comparable getColumnKey (final int a_column)
List getColumnKeys ()
Number getValue (final Comparable a_rowKey, final Comparable a_columnKey)
void setValue (final Number a_value, final Comparable a_rowKey, final Comparable a_columnKey)
boolean equals (final Object a_object)
int hashCode ()
Object clone ()
Private Attributes
List m_rowKeys
List m_columnKeys
List m_rows
boolean m_sortRowKeys
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.7 $`
Additional Inherited Members
Detailed Description
A collection of (row, column) tupels
Author
Klaus Meffert
Since
2.3
Definition at line 22 of file KeyedValues2D.java.
Constructor & Destructor Documentation
org.jgap.audit.KeyedValues2D.KeyedValues2D () [inline]
Constructor setting behavior: non-sorted keys
Author
Klaus Meffert
Since
2.3
Definition at line 45 of file KeyedValues2D.java.
Referenced by org.jgap.audit.KeyedValues2D.equals().
org.jgap.audit.KeyedValues2D.KeyedValues2D (final boolean a_sortRowKeys) [inline]
Constructor.
Parameters
a_sortRowKeys true: row keys should be sorted
Author
Klaus Meffert
Since
2.3
Definition at line 57 of file KeyedValues2D.java.
References org.jgap.audit.KeyedValues2D.m_columnKeys, org.jgap.audit.KeyedValues2D.m_rowKeys, org.jgap.audit.KeyedValues2D.m_rows, and org.jgap.audit.KeyedValues2D.m_sortRowKeys.
Member Function Documentation
Object org.jgap.audit.KeyedValues2D.clone () [inline]
Returns
clone of the current instance
Author
Klaus Meffert
Since
2.3
Implements org.jgap.util.ICloneable.
Definition at line 293 of file KeyedValues2D.java.
Referenced by org.jgap.audit.KeyedValues2DTest.testClone_0().
boolean org.jgap.audit.KeyedValues2D.equals (final Object a_object) [inline]
Tests if this object is equal to another
Parameters
a_object other object.
Returns
true: this object is equal to the other one
Author
Klaus Meffert
Since
2.3
Definition at line 235 of file KeyedValues2D.java.
References org.jgap.audit.KeyedValues2D.getColumnCount(), org.jgap.audit.KeyedValues2D.getColumnKeys(), org.jgap.audit.KeyedValues2D.getRowCount(), org.jgap.audit.KeyedValues2D.getRowKeys(), org.jgap.audit.KeyedValues2D.getValue(), and org.jgap.audit.KeyedValues2D.KeyedValues2D().
Referenced by org.jgap.audit.KeyedValues2DTest.testEquals_0(), org.jgap.audit.KeyedValues2DTest.testEquals_1(), org.jgap.audit.KeyedValues2DTest.testEquals_2(), org.jgap.audit.KeyedValues2DTest.testEquals_3(), and org.jgap.audit.KeyedValues2DTest.testEquals_4().
int org.jgap.audit.KeyedValues2D.getColumnCount () [inline]
Returns
the number of columns
Author
Klaus Meffert
Since
2.3
Definition at line 80 of file KeyedValues2D.java.
Referenced by org.jgap.audit.KeyedValues2D.equals(), and org.jgap.audit.KeyedValues2DTest.testConstruct_0().
Comparable org.jgap.audit.KeyedValues2D.getColumnKey (final int a_column) [inline]
Parameters
a_column the column
Returns
key for the given column
Author
Klaus Meffert
Since
2.3
Definition at line 152 of file KeyedValues2D.java.
Referenced by org.jgap.audit.Evaluator.calcAvgFitnessHelper(), and org.jgap.audit.KeyedValues2DTest.testClone_0().
List org.jgap.audit.KeyedValues2D.getColumnKeys () [inline]
Returns
the column keys
Author
Klaus Meffert
Since
2.3
Definition at line 162 of file KeyedValues2D.java.
References org.jgap.audit.KeyedValues2D.m_columnKeys.
Referenced by org.jgap.audit.KeyedValues2D.equals().
int org.jgap.audit.KeyedValues2D.getRowCount () [inline]
Returns
the number of rows
Author
Klaus Meffert
Since
2.3
Definition at line 70 of file KeyedValues2D.java.
Referenced by org.jgap.audit.KeyedValues2D.equals(), and org.jgap.audit.KeyedValues2DTest.testConstruct_0().
int org.jgap.audit.KeyedValues2D.getRowIndex (final Comparable a_key) [inline]
Parameters
a_key the row key
Returns
row index for the given key
Author
Klaus Meffert
Since
2.3
Definition at line 125 of file KeyedValues2D.java.
References org.jgap.audit.KeyedValues2D.m_rowKeys, and org.jgap.audit.KeyedValues2D.m_sortRowKeys.
Referenced by org.jgap.audit.KeyedValues2D.getValue(), and org.jgap.audit.KeyedValues2D.setValue().
Comparable org.jgap.audit.KeyedValues2D.getRowKey (final int a_row) [inline]
Parameters
a_row the row index, starting at 0
Returns
key for the given row
Author
Klaus Meffert
Since
2.3
Definition at line 113 of file KeyedValues2D.java.
Referenced by org.jgap.audit.Evaluator.calcAvgFitnessHelper(), org.jgap.audit.KeyedValues2DTest.testClone_0(), org.jgap.audit.KeyedValues2DTest.testSetValue_0(), and org.jgap.audit.KeyedValues2DTest.testSetValue_02().
List org.jgap.audit.KeyedValues2D.getRowKeys () [inline]
Returns
row keys
Author
Klaus Meffert
Since
2.3
Definition at line 140 of file KeyedValues2D.java.
References org.jgap.audit.KeyedValues2D.m_rowKeys.
Referenced by org.jgap.audit.KeyedValues2D.equals().
Number org.jgap.audit.KeyedValues2D.getValue (final int a_row, final int a_column) [inline]
Returns the value for a given row and column
Parameters
a_row the row index
a_column the column index
Returns
value at given row and column
Author
Klaus Meffert
Since
2.3
Definition at line 95 of file KeyedValues2D.java.
References org.jgap.audit.KeyedValues2D.m_columnKeys, and org.jgap.audit.KeyedValues2D.m_rows.
Referenced by org.jgap.audit.Evaluator.calcAvgFitnessHelper(), org.jgap.audit.KeyedValues2D.equals(), org.jgap.audit.KeyedValues2DTest.testClone_0(), org.jgap.audit.KeyedValues2DTest.testGetValue_0(), org.jgap.audit.KeyedValues2DTest.testSetValue_0(), org.jgap.audit.KeyedValues2DTest.testSetValue_02(), org.jgap.audit.KeyedValues2DTest.testSetValue_1(), org.jgap.audit.KeyedValues2DTest.testSetValue_2(), and org.jgap.audit.KeyedValues2DTest.testSetValue_3().
Number org.jgap.audit.KeyedValues2D.getValue (final Comparable a_rowKey, final Comparable a_columnKey) [inline]
Parameters
a_rowKey the row key
a_columnKey the column key
Returns
value for the given row and column keys
Author
Klaus Meffert
Since
2.3
Definition at line 175 of file KeyedValues2D.java.
References org.jgap.audit.KeyedValues2D.getRowIndex(), and org.jgap.audit.KeyedValues2D.m_rows.
int org.jgap.audit.KeyedValues2D.hashCode () [inline]
Returns
hash code of the instance
Author
Klaus Meffert
Since
2.3
Definition at line 279 of file KeyedValues2D.java.
void org.jgap.audit.KeyedValues2D.setValue (final Number a_value, final Comparable a_rowKey, final Comparable a_columnKey) [inline]
Sets a value.
Parameters
a_value the value
a_rowKey the row key
a_columnKey the column key
Author
Klaus Meffert
Since
2.3
Definition at line 199 of file KeyedValues2D.java.
References org.jgap.audit.KeyedValues2D.getRowIndex(), org.jgap.audit.KeyedValues2D.m_rows, and org.jgap.audit.KeyedValues2D.m_sortRowKeys.
Member Data Documentation
final String org.jgap.audit.KeyedValues2D.CVS_REVISION = `$Revision: 1.7 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file KeyedValues2D.java.
List org.jgap.audit.KeyedValues2D.m_columnKeys [private]
The column keys
Definition at line 31 of file KeyedValues2D.java.
Referenced by org.jgap.audit.KeyedValues2D.getColumnKeys(), org.jgap.audit.KeyedValues2D.getValue(), and org.jgap.audit.KeyedValues2D.KeyedValues2D().
List org.jgap.audit.KeyedValues2D.m_rowKeys [private]
The row keys
Definition at line 28 of file KeyedValues2D.java.
Referenced by org.jgap.audit.KeyedValues2D.getRowIndex(), org.jgap.audit.KeyedValues2D.getRowKeys(), and org.jgap.audit.KeyedValues2D.KeyedValues2D().
List org.jgap.audit.KeyedValues2D.m_rows [private]
The row data
Definition at line 34 of file KeyedValues2D.java.
Referenced by org.jgap.audit.KeyedValues2D.getValue(), org.jgap.audit.KeyedValues2D.KeyedValues2D(), and org.jgap.audit.KeyedValues2D.setValue().
boolean org.jgap.audit.KeyedValues2D.m_sortRowKeys [private]
Should row keys be sorted by their comparable order?
Definition at line 37 of file KeyedValues2D.java.
Referenced by org.jgap.audit.KeyedValues2D.getRowIndex(), org.jgap.audit.KeyedValues2D.KeyedValues2D(), and org.jgap.audit.KeyedValues2D.setValue().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/audit/KeyedValues2D.java