org.jgap.BaseRateCalculator Class Reference
Public Member Functions
BaseRateCalculator (Configuration a_config) throws InvalidConfigurationException
Configuration getConfiguration ()
Private Attributes
transient Configuration m_config
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
Base class for rate calculators.
Author
Klaus Meffert
Since
3.0
Definition at line 18 of file BaseRateCalculator.java.
Constructor & Destructor Documentation
org.jgap.BaseRateCalculator.BaseRateCalculator (Configuration a_config) throws InvalidConfigurationException [inline]
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 32 of file BaseRateCalculator.java.
References org.jgap.BaseRateCalculator.m_config.
Member Function Documentation
Configuration org.jgap.BaseRateCalculator.getConfiguration () [inline]
Returns
the configuration used
Author
Klaus Meffert
Since
3.0
Definition at line 46 of file BaseRateCalculator.java.
References org.jgap.BaseRateCalculator.m_config.
Referenced by org.jgap.impl.DefaultCrossoverRateCalculator.calculateCurrentRate(), org.jgap.impl.DefaultMutationRateCalculator.calculateCurrentRate(), org.jgap.BaseRateCalculatorTest.testGetConfiguration_0(), and org.jgap.impl.DefaultMutationRateCalculator.toBePermutated().
Member Data Documentation
final String org.jgap.BaseRateCalculator.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 21 of file BaseRateCalculator.java.
transient Configuration org.jgap.BaseRateCalculator.m_config [private]
Definition at line 23 of file BaseRateCalculator.java.
Referenced by org.jgap.BaseRateCalculator.BaseRateCalculator(), and org.jgap.BaseRateCalculator.getConfiguration().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/BaseRateCalculator.java