org.jgap.distr.CultureMemoryCellTest Class Reference
Public Member Functions
void testToString_0 ()
void testToString_1 ()
void testToString_2 ()
void testSetDouble_0 ()
void testSetValue_0 ()
void testSerialize_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.11 $`
Additional Inherited Members
Detailed Description
Tests the CultureMemoryCell class.
Author
Klaus Meffert
Since
2.3
Definition at line 22 of file CultureMemoryCellTest.java.
Member Function Documentation
static Test org.jgap.distr.CultureMemoryCellTest.suite () [inline], [static]
Definition at line 27 of file CultureMemoryCellTest.java.
void org.jgap.distr.CultureMemoryCellTest.testSerialize_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 141 of file CultureMemoryCellTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.doSerialize().
void org.jgap.distr.CultureMemoryCellTest.testSetDouble_0 () [inline]
Author
Klaus Meffert
Since
2.3
Definition at line 85 of file CultureMemoryCellTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.DELTA, org.jgap.distr.CultureMemoryCell.getCurrentValue(), and org.jgap.distr.CultureMemoryCell.getCurrentValueAsDouble().
void org.jgap.distr.CultureMemoryCellTest.testSetValue_0 () [inline]
Definition at line 99 of file CultureMemoryCellTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.distr.CultureMemoryCell.getCurrentValue(), org.jgap.distr.CultureMemoryCell.getReadAccessed(), and org.jgap.distr.CultureMemoryCell.getVersion().
void org.jgap.distr.CultureMemoryCellTest.testToString_0 () [inline]
Author
Klaus Meffert
Since
2.3
Definition at line 36 of file CultureMemoryCellTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.distr.CultureMemoryCell.toString().
void org.jgap.distr.CultureMemoryCellTest.testToString_1 () [inline]
Author
Klaus Meffert
Since
2.3
Definition at line 53 of file CultureMemoryCellTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.distr.CultureMemoryCell.toString().
void org.jgap.distr.CultureMemoryCellTest.testToString_2 () [inline]
Empty cell.
Author
Klaus Meffert
Since
2.3
Definition at line 74 of file CultureMemoryCellTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.distr.CultureMemoryCell.toString().
Member Data Documentation
final String org.jgap.distr.CultureMemoryCellTest.CVS_REVISION = `$Revision: 1.11 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file CultureMemoryCellTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/distr/CultureMemoryCellTest.java