org.jgap.data.DataTreeBuilderTest Class Reference
Public Member Functions
void setUp ()
void testRepresentGenotypeAsDocument_0 () throws Exception
void testRepresentChromosomeAsDocument_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.12 $`
static final int NUM_CHROMS = 5
static final int NUM_GENES = 2
Additional Inherited Members
Detailed Description
Tests the DataTreeBuilder class
Author
Klaus Meffert
Siddhartha Azad
Since
1.0
Definition at line 23 of file DataTreeBuilderTest.java.
Member Function Documentation
void org.jgap.data.DataTreeBuilderTest.setUp () [inline]
Definition at line 39 of file DataTreeBuilderTest.java.
static Test org.jgap.data.DataTreeBuilderTest.suite () [inline], [static]
Definition at line 34 of file DataTreeBuilderTest.java.
void org.jgap.data.DataTreeBuilderTest.testRepresentChromosomeAsDocument_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 112 of file DataTreeBuilderTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.data.IDataElementList.getLength(), org.jgap.data.IDataElement.getTagName(), and org.jgap.data.DataTreeBuilderTest.NUM_GENES.
void org.jgap.data.DataTreeBuilderTest.testRepresentGenotypeAsDocument_0 () throws Exception [inline]
Create a Genotype and represent it as a document, and verify that the representation is as expected.
Exceptions
Exception
Definition at line 49 of file DataTreeBuilderTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.data.IDataElementList.getLength(), org.jgap.data.IDataElement.getTagName(), org.jgap.data.DataTreeBuilderTest.NUM_CHROMS, and org.jgap.data.DataTreeBuilderTest.NUM_GENES.
Member Data Documentation
final String org.jgap.data.DataTreeBuilderTest.CVS_REVISION = `$Revision: 1.12 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file DataTreeBuilderTest.java.
final int org.jgap.data.DataTreeBuilderTest.NUM_CHROMS = 5 [static], [private]
Definition at line 29 of file DataTreeBuilderTest.java.
Referenced by org.jgap.data.DataTreeBuilderTest.testRepresentGenotypeAsDocument_0().
final int org.jgap.data.DataTreeBuilderTest.NUM_GENES = 2 [static], [private]
Definition at line 32 of file DataTreeBuilderTest.java.
Referenced by org.jgap.data.DataTreeBuilderTest.testRepresentChromosomeAsDocument_0(), and org.jgap.data.DataTreeBuilderTest.testRepresentGenotypeAsDocument_0().
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/data/DataTreeBuilderTest.java