org.jgap.gp.function.ADF Class Reference
Public Member Functions
ADF (final GPConfiguration a_conf, int a_chromosomeNum, int a_arity) throws InvalidConfigurationException
int getChromosomeNum ()
String toString ()
int getArity (IGPProgram a_individual)
int execute_int (ProgramChromosome c, int n, Object[] args)
boolean execute_boolean (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
Class getChildType (IGPProgram a_ind, int i)
boolean isValid (ProgramChromosome a_chrom)
int compareTo (Object a_other)
boolean equals (Object a_other)
Private Attributes
int m_chromosomeNum
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.19 $`
Additional Inherited Members
Detailed Description
Automatically Defined Function (ADF). Works with output of other chromosomes. An ADF is automatically created by ProgramChromosome. For more information about ADFs see John Koza's book on Genetic Programming. Or google for `Koza ADF`. For a German explanation, see see http://www.tu-chemnitz.de/informatik/ThIS/seminare/ws01/gp/singer.pdf or http://www.tu-chemnitz.de/informatik/ThIS/seminare/ws01/gp/forbriger.pdf or http://www.klaus-meffert.de/download/genetische_programmierung_mit_java.pdf
Author
Klaus Meffert
Since
3.0
Definition at line 32 of file ADF.java.
Constructor & Destructor Documentation
org.jgap.gp.function.ADF.ADF (final GPConfiguration a_conf, int a_chromosomeNum, int a_arity) throws InvalidConfigurationException [inline]
Constructor.
Parameters
a_conf the configuration to use
a_chromosomeNum the index of the chromosome to execute
a_arity the arity of the ADF
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 53 of file ADF.java.
References org.jgap.gp.function.ADF.m_chromosomeNum.
Referenced by org.jgap.gp.function.ADF.compareTo(), and org.jgap.gp.function.ADF.equals().
Member Function Documentation
int org.jgap.gp.function.ADF.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.0
Definition at line 164 of file ADF.java.
References org.jgap.gp.function.ADF.ADF(), and org.jgap.gp.function.ADF.m_chromosomeNum.
boolean org.jgap.gp.function.ADF.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Klaus Meffert
Since
3.0
Definition at line 184 of file ADF.java.
References org.jgap.gp.function.ADF.ADF(), and org.jgap.gp.function.ADF.m_chromosomeNum.
boolean org.jgap.gp.function.ADF.execute_boolean (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 101 of file ADF.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.function.ADF.m_chromosomeNum.
double org.jgap.gp.function.ADF.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 121 of file ADF.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.function.ADF.m_chromosomeNum.
float org.jgap.gp.function.ADF.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 111 of file ADF.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.function.ADF.m_chromosomeNum.
int org.jgap.gp.function.ADF.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 89 of file ADF.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.function.ADF.m_chromosomeNum.
Object org.jgap.gp.function.ADF.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 131 of file ADF.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.function.ADF.m_chromosomeNum.
int org.jgap.gp.function.ADF.getArity (IGPProgram a_individual) [inline]
Definition at line 82 of file ADF.java.
References org.jgap.gp.function.ADF.m_chromosomeNum, and org.jgap.gp.IGPProgram.size().
Class org.jgap.gp.function.ADF.getChildType (IGPProgram a_ind, int i) [inline]
Definition at line 141 of file ADF.java.
References org.jgap.gp.function.ADF.m_chromosomeNum.
int org.jgap.gp.function.ADF.getChromosomeNum () [inline]
Returns
the index of the chromosome to execute
Author
Klaus Meffert
Since
3.0
Definition at line 65 of file ADF.java.
References org.jgap.gp.function.ADF.m_chromosomeNum.
boolean org.jgap.gp.function.ADF.isValid (ProgramChromosome a_chrom) [inline]
Todo
Todo enhance
Definition at line 145 of file ADF.java.
String org.jgap.gp.function.ADF.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 69 of file ADF.java.
References org.jgap.gp.function.ADF.m_chromosomeNum, and org.jgap.gp.CommandGene.size().
Member Data Documentation
final String org.jgap.gp.function.ADF.CVS_REVISION = `$Revision: 1.19 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 37 of file ADF.java.
int org.jgap.gp.function.ADF.m_chromosomeNum [private]
Definition at line 39 of file ADF.java.
Referenced by org.jgap.gp.function.ADF.ADF(), org.jgap.gp.function.ADF.compareTo(), org.jgap.gp.function.ADF.equals(), org.jgap.gp.function.ADF.execute_boolean(), org.jgap.gp.function.ADF.execute_double(), org.jgap.gp.function.ADF.execute_float(), org.jgap.gp.function.ADF.execute_int(), org.jgap.gp.function.ADF.execute_object(), org.jgap.gp.function.ADF.getArity(), org.jgap.gp.function.ADF.getChildType(), org.jgap.gp.function.ADF.getChromosomeNum(), and org.jgap.gp.function.ADF.toString().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/ADF.java