org.jgap.impl.SwappingMutationOperator Class Reference
Public Member Functions
SwappingMutationOperator () throws InvalidConfigurationException
SwappingMutationOperator (final Configuration a_config) throws InvalidConfigurationException
SwappingMutationOperator (final Configuration a_config, final IUniversalRateCalculator a_mutationRateCalculator) throws InvalidConfigurationException
SwappingMutationOperator (final Configuration a_config, final int a_desiredMutationRate) throws InvalidConfigurationException
void operate (final Population a_population, List a_candidateChromosomes)
void setStartOffset (final int a_offset)
int getStartOffset ()
Protected Member Functions
IChromosome operate (final IChromosome a_chrom, final int a_rate, final RandomGenerator a_generator)
Gene[] operate (final RandomGenerator a_generator, final int a_target_gene, final Gene[] a_genes)
Private Attributes
int m_startOffset = 1
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.21 $`
Additional Inherited Members
Detailed Description
Swaps the genes instead of mutating them. This kind of operator is required by Traveling Salesman Problem.
See J. Grefenstette, R. Gopal, R. Rosmaita, and D. Gucht. Genetic algorithms for the traveling salesman problem. In Proceedings of the Second International Conference on Genetic Algorithms. Lawrence Eribaum Associates, Mahwah, NJ, 1985. and also Sushil J. Louis & Gong Li }
Author
Audrius Meskauskas
Neil Rotstan
Klaus Meffert
Since
2.0
Definition at line 31 of file SwappingMutationOperator.java.
Constructor & Destructor Documentation
org.jgap.impl.SwappingMutationOperator.SwappingMutationOperator () throws InvalidConfigurationException [inline]
Constructs a new instance of this operator.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Definition at line 47 of file SwappingMutationOperator.java.
org.jgap.impl.SwappingMutationOperator.SwappingMutationOperator (final Configuration a_config) throws InvalidConfigurationException [inline]
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 59 of file SwappingMutationOperator.java.
org.jgap.impl.SwappingMutationOperator.SwappingMutationOperator (final Configuration a_config, final IUniversalRateCalculator a_mutationRateCalculator) throws InvalidConfigurationException [inline]
Constructs a new instance of this operator with a specified mutation rate calculator, which results in dynamic mutation being turned on.
Parameters
a_config the configuration to use
a_mutationRateCalculator calculator for dynamic mutation rate computation
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0 (previously: without a_config)
Definition at line 77 of file SwappingMutationOperator.java.
org.jgap.impl.SwappingMutationOperator.SwappingMutationOperator (final Configuration a_config, final int a_desiredMutationRate) throws InvalidConfigurationException [inline]
Constructs a new instance of this MutationOperator with the given mutation rate.
Parameters
a_config the configuration to use
a_desiredMutationRate desired rate of mutation, expressed as the denominator of the 1 / X fraction. For example, 1000 would result in 1/1000 genes being mutated on average. A mutation rate of zero disables mutation entirely
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0 (previously: without a_config)
Definition at line 98 of file SwappingMutationOperator.java.
Member Function Documentation
int org.jgap.impl.SwappingMutationOperator.getStartOffset () [inline]
Gets a number of genes at the start of chromosome, that are excluded from the swapping. In the Salesman task, the first city in the list should (where the salesman leaves from) probably should not change as it is part of the list. The default value is 1.
Returns
the start offset
Author
Audrius Meskauskas
Since
2.0
Definition at line 254 of file SwappingMutationOperator.java.
References org.jgap.impl.SwappingMutationOperator.m_startOffset.
Referenced by org.jgap.impl.SwappingMutationOperatorTest.testStartoffset_0().
void org.jgap.impl.SwappingMutationOperator.operate (final Population a_population, List a_candidateChromosomes) [inline]
Parameters
a_population the population of chromosomes from the current evolution prior to exposure to any genetic operators. Chromosomes in this array should not be modified. Please, notice, that the call in Genotype.evolve() to the implementations of GeneticOperator overgoes this due to performance issues
a_candidateChromosomes the pool of chromosomes that have been selected for the next evolved population
Author
Audrius Meskauskas
Klaus Meffert
Since
2.0
Definition at line 117 of file SwappingMutationOperator.java.
References org.jgap.BaseGeneticOperator.getConfiguration(), org.jgap.impl.MutationOperator.getMutationRate(), org.jgap.impl.MutationOperator.getMutationRateCalc(), and org.jgap.impl.MutationOperator.m_mutationRateCalc.
Referenced by org.jgap.impl.SwappingMutationOperator.operate().
IChromosome org.jgap.impl.SwappingMutationOperator.operate (final IChromosome a_chrom, final int a_rate, final RandomGenerator a_generator) [inline], [protected]
Operate on the given chromosome with the given mutation rate.
Parameters
a_chrom chromosome to operate
a_rate mutation rate
a_generator random generator to use (must not be null)
Returns
mutated chromosome of null if no mutation has occured.
Author
Audrius Meskauskas
Since
2.0
Definition at line 165 of file SwappingMutationOperator.java.
References org.jgap.util.ICloneable.clone(), org.jgap.BaseGeneticOperator.m_monitorActive, org.jgap.impl.SwappingMutationOperator.m_startOffset, org.jgap.RandomGenerator.nextInt(), and org.jgap.impl.SwappingMutationOperator.operate().
Gene [] org.jgap.impl.SwappingMutationOperator.operate (final RandomGenerator a_generator, final int a_target_gene, final Gene[] a_genes) [inline], [protected]
Operate on the given array of genes. This method is only called when it is already clear that the mutation must occur under the given mutation rate.
Parameters
a_generator a random number generator that may be needed to perform a mutation
a_target_gene an index of gene in the chromosome that will mutate
a_genes the array of all genes in the chromosome
Returns
the mutated gene array
Author
Audrius Meskauskas
Since
2.0
Definition at line 211 of file SwappingMutationOperator.java.
References org.jgap.BaseGeneticOperator.m_monitorActive, and org.jgap.impl.SwappingMutationOperator.m_startOffset.
void org.jgap.impl.SwappingMutationOperator.setStartOffset (final int a_offset) [inline]
Sets a number of genes at the start of chromosome, that are excluded from the swapping. In the Salesman task, the first city in the list should (where the salesman leaves from) probably should not change as it is part of the list. The default value is 1.
Parameters
a_offset the offset to set
Author
Audrius Meskauskas
Since
2.0
Definition at line 239 of file SwappingMutationOperator.java.
References org.jgap.impl.SwappingMutationOperator.m_startOffset.
Member Data Documentation
final String org.jgap.impl.SwappingMutationOperator.CVS_REVISION = `$Revision: 1.21 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 34 of file SwappingMutationOperator.java.
int org.jgap.impl.SwappingMutationOperator.m_startOffset = 1 [private]
Definition at line 36 of file SwappingMutationOperator.java.
Referenced by org.jgap.impl.SwappingMutationOperator.getStartOffset(), org.jgap.impl.SwappingMutationOperator.operate(), and org.jgap.impl.SwappingMutationOperator.setStartOffset().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/SwappingMutationOperator.java