org.jgap.data.DataElementTest Class Reference
Public Member Functions
void testAppendChild_0 () throws Exception
void testGetElementsByTagName_0 () throws Exception
void testGetNodeType_0 () throws Exception
void testAttributes_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
Tests for DataElement class
Author
Klaus Meffert
Since
2.6
Definition at line 22 of file DataElementTest.java.
Member Function Documentation
static Test org.jgap.data.DataElementTest.suite () [inline], [static]
Definition at line 27 of file DataElementTest.java.
void org.jgap.data.DataElementTest.testAppendChild_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 37 of file DataElementTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.data.DataElement.getChildNodes().
void org.jgap.data.DataElementTest.testAttributes_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 86 of file DataElementTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.data.DataElement.getAttributes(), and org.jgap.data.DataElement.getNodeValue().
void org.jgap.data.DataElementTest.testGetElementsByTagName_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 51 of file DataElementTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.data.DataElement.getTagName().
void org.jgap.data.DataElementTest.testGetNodeType_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 74 of file DataElementTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.data.DataElement.getNodeType(), and org.jgap.data.DataElement.getNodeValue().
Member Data Documentation
final String org.jgap.data.DataElementTest.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file DataElementTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/data/DataElementTest.java