org.jgap.gp.impl.GPGenotype Class Reference
Classes
class GPFitnessComparator
Public Member Functions
GPGenotype () throws InvalidConfigurationException
GPGenotype (GPConfiguration a_configuration, GPPopulation a_population, Class[] a_types, Class[][] a_argTypes, CommandGene[][] a_nodeSets, int[] a_minDepths, int[] a_maxDepths, int a_maxNodes) throws InvalidConfigurationException
GPGenotype (GPConfiguration a_configuration, GPPopulation a_population, Class[] a_types, Class[][] a_argTypes, CommandGene[][] a_nodeSets, int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, IGPPopulationInitializer a_popCreator) throws InvalidConfigurationException
GPConfiguration getGPConfiguration ()
void evolve (int a_evolutions)
void calcFitness ()
IGPProgram getAllTimeBest ()
void outputSolution (IGPProgram a_best)
void evolve ()
GPPopulation getGPPopulation ()
double getTotalFitness ()
void run ()
synchronized IGPProgram getFittestProgram ()
synchronized IGPProgram getFittestProgramComputed ()
void setGPConfiguration (GPConfiguration a_configuration)
boolean equals (Object a_other)
int compareTo (Object a_other)
int hashCode ()
void setVerboseOutput (boolean a_verbose)
void putVariable (Variable a_var)
Variable getVariable (String a_varName)
void addFittestProgram (final IGPProgram a_toAdd)
void fillPopulation (final int a_num) throws InvalidConfigurationException
Static Public Member Functions
static GPGenotype randomInitialGenotype (final GPConfiguration a_conf, Class[] a_types, Class[][] a_argTypes, CommandGene[][] a_nodeSets, int a_maxNodes, boolean a_verboseOutput) throws InvalidConfigurationException
static GPGenotype randomInitialGenotype (final GPConfiguration a_conf, Class[] a_types, Class[][] a_argTypes, CommandGene[][] a_nodeSets, int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, boolean a_verboseOutput) throws InvalidConfigurationException
static GPGenotype randomInitialGenotype (final GPConfiguration a_conf, Class[] a_types, Class[][] a_argTypes, CommandGene[][] a_nodeSets, int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, boolean[] a_fullModeAllowed, boolean a_verboseOutput) throws InvalidConfigurationException
static GPGenotype randomInitialGenotype (final GPConfiguration a_conf, Class[] a_types, Class[][] a_argTypes, CommandGene[][] a_nodeSets, int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, boolean[] a_fullModeAllowed, boolean a_verboseOutput, IPopulationCreator a_popCreator) throws InvalidConfigurationException
static GPConfiguration getStaticGPConfiguration ()
static void setStaticGPConfiguration (GPConfiguration a_configuration)
static void checkErroneousPop (GPPopulation pop, String s)
static void checkErroneousPop (GPPopulation a_pop, String a_s, boolean a_clearFitness)
static void checkErroneousPop (GPPopulation a_pop, String a_s, boolean a_clearFitness, boolean a_active)
static void checkErroneousProg (IGPProgram prog, String s)
static void checkErroneousProg (IGPProgram a_prog, String a_s, boolean a_clearFitness)
static void checkErroneousProg (IGPProgram a_prog, String s, boolean a_clearFitness, boolean a_active)
static Map< String, CommandGene > verifyChildNodes (GPConfiguration a_conf, Class[] a_types, CommandGene[][] a_nodeSets)
static Map< CommandGene, int[]> verifyDepthsForNodes (GPPopulation a_pop, GPConfiguration a_conf, Class[] a_types, int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, CommandGene[][] a_nodeSets)
Protected Member Functions
void init ()
void setGPPopulation (GPPopulation a_pop)
Static Protected Member Functions
static boolean nodeExists (CommandGene[] a_functionSet, Class a_returnType, int a_subReturnType)
static void outputWarning (Map< String, CommandGene > invalidNodes)
static void outputDepthInfo (Map< CommandGene, int[]> a_invalidDepths)
Private Member Functions
IGPProgram cloneProgram (IGPProgram a_original)
void writeToFile (IGPProgram i1, IGPProgram i2, IGPProgram inew, String header)
StringBuffer getProgramString (IGPProgram i1)
Private Attributes
GPPopulation m_population
GPConfiguration m_configuration
double m_bestFitness
double m_totalFitness
IGPProgram m_allTimeBest
double m_allTimeBestFitness
boolean m_fullModeAllowed []
Class[] m_types
Class[][] m_argTypes
CommandGene[][] m_nodeSets
int[] m_minDepths
int[] m_maxDepths
int m_maxNodes
boolean m_verbose
Map m_variables
IGPProgram m_fittestToAdd
boolean m_cloneWarningGPProgramShown
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.60 $`
static transient Logger LOGGER = Logger.getLogger(GPGenotype.class)
static transient GPConfiguration m_staticConfiguration
Detailed Description
Genotype for GP Programs.
Author
Klaus Meffert
Since
3.0
Definition at line 29 of file GPGenotype.java.
Constructor & Destructor Documentation
org.jgap.gp.impl.GPGenotype.GPGenotype () throws InvalidConfigurationException [inline]
Default constructor. Ony use with dynamic instantiation.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 121 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.init().
Referenced by org.jgap.gp.impl.GPGenotype.compareTo(), and org.jgap.gp.impl.GPGenotype.randomInitialGenotype().
org.jgap.gp.impl.GPGenotype.GPGenotype (GPConfiguration a_configuration, GPPopulation a_population, Class[] a_types, Class a_argTypes[][], CommandGene a_nodeSets[][], int[] a_minDepths, int[] a_maxDepths, int a_maxNodes) throws InvalidConfigurationException [inline]
Preferred constructor to use, if not using the static method randomInitialGenotype.
Parameters
a_configuration the configuration to use
a_population the initialized population to use
a_types the type for each chromosome, the length of the array represents the number of chromosomes
a_argTypes the types of the arguments to each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of arguments to the chromosome
a_nodeSets the nodes which are allowed to be used by each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of nodes
a_minDepths contains the minimum depth allowed for each chromosome
a_maxDepths contains the maximum depth allowed for each chromosome
a_maxNodes reserve space for a_maxNodes number of nodes
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 150 of file GPGenotype.java.
org.jgap.gp.impl.GPGenotype.GPGenotype (GPConfiguration a_configuration, GPPopulation a_population, Class[] a_types, Class a_argTypes[][], CommandGene a_nodeSets[][], int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, IGPPopulationInitializer a_popCreator) throws InvalidConfigurationException [inline]
See above constructor. Parameter a_popCreator is used in grid context only.
Parameters
a_configuration GPConfiguration
a_population GPPopulation
a_types Class[]
a_argTypes Class[][]
a_nodeSets CommandGene[][]
a_minDepths int[]
a_maxDepths int[]
a_maxNodes int
a_popCreator IPopulationCreator
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.6
Definition at line 176 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.getGPConfiguration(), org.jgap.gp.impl.GPGenotype.init(), org.jgap.gp.impl.GPGenotype.m_allTimeBestFitness, org.jgap.gp.impl.GPGenotype.m_argTypes, org.jgap.gp.impl.GPGenotype.m_maxDepths, org.jgap.gp.impl.GPGenotype.m_maxNodes, org.jgap.gp.impl.GPGenotype.m_minDepths, org.jgap.gp.impl.GPGenotype.m_nodeSets, org.jgap.gp.impl.GPGenotype.m_types, org.jgap.gp.impl.GPGenotype.m_variables, org.jgap.FitnessFunction.NO_FITNESS_VALUE, org.jgap.gp.impl.GPGenotype.setGPConfiguration(), and org.jgap.gp.impl.GPGenotype.setGPPopulation().
Member Function Documentation
void org.jgap.gp.impl.GPGenotype.addFittestProgram (final IGPProgram a_toAdd) [inline]
Adds a GP program to this Genotype. Does nothing when given null. The injection is actually executed in method create(..) of GPPopulation.
Parameters
a_toAdd the program to add
Author
Klaus Meffert
Since
3.2
Definition at line 1180 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.m_fittestToAdd.
Referenced by org.jgap.gp.impl.GPGenotype.calcFitness().
void org.jgap.gp.impl.GPGenotype.calcFitness () [inline]
Calculates the fitness value of all programs, of the best solution as well as the total fitness (sum of all fitness values).
Author
Klaus Meffert
Since
3.0
Todo
Todo get information from fitness function how calculation happened. In case of Robocode: return the robot competed against, in case the -enemies option was used without -battleAll
Todo
Todo do something similar here as with Genotype.preserveFittestChromosome
Todo
Todo introduce global value object to be passed to the listener
Todo
Todo should not happen but does with ensureUniqueness(..)
Definition at line 557 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.addFittestProgram(), org.jgap.gp.impl.GPGenotype.getGPConfiguration(), org.jgap.gp.impl.GPGenotype.getGPPopulation(), org.jgap.gp.impl.GPPopulation.getGPProgram(), org.jgap.gp.IGPFitnessEvaluator.isFitter(), org.jgap.gp.impl.GPGenotype.m_allTimeBest, org.jgap.gp.impl.GPGenotype.m_allTimeBestFitness, org.jgap.gp.impl.GPGenotype.m_bestFitness, org.jgap.gp.impl.GPGenotype.m_cloneWarningGPProgramShown, org.jgap.gp.impl.GPGenotype.m_totalFitness, org.jgap.gp.impl.GPGenotype.m_verbose, org.jgap.FitnessFunction.NO_FITNESS_VALUE, org.jgap.gp.impl.GPGenotype.outputSolution(), org.jgap.IHandler.perform(), and org.jgap.gp.IGPProgram.toStringNorm().
Referenced by org.jgap.gp.impl.GPGenotype.evolve(), and org.jgap.gp.impl.GPGenotype.run().
static void org.jgap.gp.impl.GPGenotype.checkErroneousPop (GPPopulation pop, String s) [inline], [static]
Disabling a chromosome is equivalent to not declaring it. However, if you skip a declaration, indices will shift. With this method it is easier skipping a chromosome.
Parameters
a_index index of the chromosome to disable.
Author
Klaus Meffert
Since
3.2.2
Parameters
a_index index of the chromosome to check.
Returns
true if chromosome disabled
Author
Klaus Meffert
Since
3.2.2
Definition at line 1251 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.checkErroneousPop(), org.jgap.gp.impl.GPGenotype.evolve(), and org.jgap.gp.impl.GPGenotype.randomInitialGenotype().
static void org.jgap.gp.impl.GPGenotype.checkErroneousPop (GPPopulation a_pop, String a_s, boolean a_clearFitness) [inline], [static]
Definition at line 1255 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.checkErroneousPop(), and org.jgap.gp.impl.GPPopulation.getGPConfiguration().
static void org.jgap.gp.impl.GPGenotype.checkErroneousPop (GPPopulation a_pop, String a_s, boolean a_clearFitness, boolean a_active) [inline], [static]
Definition at line 1264 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.checkErroneousProg().
static void org.jgap.gp.impl.GPGenotype.checkErroneousProg (IGPProgram prog, String s) [inline], [static]
Definition at line 1282 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.checkErroneousPop(), org.jgap.gp.impl.GPGenotype.checkErroneousProg(), and org.jgap.gp.impl.GPGenotype.evolve().
static void org.jgap.gp.impl.GPGenotype.checkErroneousProg (IGPProgram a_prog, String a_s, boolean a_clearFitness) [inline], [static]
Definition at line 1286 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.checkErroneousProg(), and org.jgap.gp.IGPProgram.getGPConfiguration().
static void org.jgap.gp.impl.GPGenotype.checkErroneousProg (IGPProgram a_prog, String s, boolean a_clearFitness, boolean a_active) [inline], [static]
Todo
Todo impl. cache
Definition at line 1295 of file GPGenotype.java.
References org.jgap.gp.GPFitnessFunction.NO_FITNESS_VALUE.
IGPProgram org.jgap.gp.impl.GPGenotype.cloneProgram (IGPProgram a_original) [inline], [private]
Definition at line 1131 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.getGPConfiguration(), and org.jgap.IHandler.perform().
Referenced by org.jgap.gp.impl.GPGenotype.evolve().
int org.jgap.gp.impl.GPGenotype.compareTo (Object a_other) [inline]
Compares this Genotype against the specified object. The result is true if the argument is an instance of the Genotype class, has exactly the same number of programs as the given Genotype, and, for each GPProgram in this Genotype, there is an equal program in the given Genotype. The programs do not need to appear in the same order within the populations.
Parameters
a_other the object to compare against
Returns
a negative number if this genotype is `less than` the given genotype, zero if they are equal to each other, and a positive number if this genotype is `greater than` the given genotype
Author
Klaus Meffert
Since
3.0
Definition at line 1045 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.getGPPopulation(), and org.jgap.gp.impl.GPGenotype.GPGenotype().
Referenced by org.jgap.gp.impl.GPGenotype.equals().
boolean org.jgap.gp.impl.GPGenotype.equals (Object a_other) [inline]
Compares this entity against the specified object.
Parameters
a_other the object to compare against
Returns
true: if the objects are the same, false otherwise
Author
Klaus Meffert
Since
3.0
Definition at line 1021 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.compareTo().
void org.jgap.gp.impl.GPGenotype.evolve (int a_evolutions) [inline]
Evolves the population n times.
Parameters
a_evolutions number of evolution
Author
Klaus Meffert
Since
3.0
Definition at line 524 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.calcFitness(), org.jgap.gp.impl.GPGenotype.evolve(), org.jgap.gp.impl.GPGenotype.getGPConfiguration(), and org.jgap.gp.impl.GPGenotype.m_verbose.
void org.jgap.gp.impl.GPGenotype.evolve () [inline]
Evolve the population by one generation. Probabilistically reproduces and crosses individuals into a new population which then overwrites the original population.
Author
Klaus Meffert
Since
3.0
Todo
Todo use program creator in case such is registered and returns a non-null program
Todo
Todo instead of re-using prototype, create a program anyway (ignoring the validator) in case it is the last try. Or even better: Make the validator return a defect rate!
Definition at line 696 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.checkErroneousPop(), org.jgap.gp.impl.GPGenotype.checkErroneousProg(), org.jgap.gp.impl.GPGenotype.cloneProgram(), org.jgap.gp.impl.GPGenotype.getGPConfiguration(), org.jgap.gp.impl.GPGenotype.getGPPopulation(), org.jgap.gp.impl.GPGenotype.m_argTypes, org.jgap.gp.impl.GPGenotype.m_fittestToAdd, org.jgap.gp.impl.GPGenotype.m_fullModeAllowed, org.jgap.gp.impl.GPGenotype.m_maxDepths, org.jgap.gp.impl.GPGenotype.m_maxNodes, org.jgap.gp.impl.GPGenotype.m_minDepths, org.jgap.gp.impl.GPGenotype.m_nodeSets, org.jgap.gp.impl.GPGenotype.m_types, org.jgap.RandomGenerator.nextInt(), org.jgap.gp.impl.GPGenotype.setGPPopulation(), and org.jgap.gp.impl.GPGenotype.writeToFile().
Referenced by org.jgap.gp.impl.GPGenotype.evolve(), and org.jgap.gp.impl.GPGenotype.run().
void org.jgap.gp.impl.GPGenotype.fillPopulation (final int a_num) throws InvalidConfigurationException [inline]
Fills up the population with random programs if necessary.
Parameters
a_num the number of programs to add
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.2
Todo
Todo care about
Todo
Todo implement filling up population
Definition at line 1195 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.getGPConfiguration().
IGPProgram org.jgap.gp.impl.GPGenotype.getAllTimeBest () [inline]
Returns
the all-time best solution found
Author
Klaus Meffert
Since
3.0
Definition at line 647 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.m_allTimeBest.
Referenced by examples.gp.Fibonacci.main().
synchronized IGPProgram org.jgap.gp.impl.GPGenotype.getFittestProgram () [inline]
Retrieves the GPProgram in the population with the best fitness value.
Returns
the GPProgram with the highest fitness value, or null if there are no programs in this Genotype
Author
Klaus Meffert
Since
3.0
Definition at line 959 of file GPGenotype.java.
References org.jgap.gp.IGPProgram.getFitnessValue(), org.jgap.gp.impl.GPGenotype.getGPConfiguration(), org.jgap.gp.impl.GPGenotype.getGPPopulation(), org.jgap.gp.impl.GPGenotype.m_allTimeBest, and org.jgap.FitnessFunction.NO_FITNESS_VALUE.
synchronized IGPProgram org.jgap.gp.impl.GPGenotype.getFittestProgramComputed () [inline]
Retrieves the GPProgram in the population with the highest fitness value. Only considers programs for which the fitness value has already been computed.
Returns
the GPProgram with the best fitness value, or null if there are no programs with known fitness value in this Genotype
Author
Klaus Meffert
Since
3.2
Definition at line 993 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.getGPPopulation().
GPConfiguration org.jgap.gp.impl.GPGenotype.getGPConfiguration () [inline]
Definition at line 470 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.m_configuration.
Referenced by org.jgap.gp.impl.GPGenotype.calcFitness(), org.jgap.gp.impl.GPGenotype.cloneProgram(), org.jgap.gp.impl.GPGenotype.evolve(), org.jgap.gp.impl.GPGenotype.fillPopulation(), org.jgap.gp.impl.GPGenotype.getFittestProgram(), org.jgap.gp.impl.GPGenotype.GPGenotype(), and examples.gp.monalisa.gui.EvolutionRunnable.run().
GPPopulation org.jgap.gp.impl.GPGenotype.getGPPopulation () [inline]
Definition at line 914 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.m_population.
Referenced by org.jgap.gp.impl.GPGenotype.calcFitness(), org.jgap.gp.impl.GPGenotype.compareTo(), org.jgap.gp.impl.GPGenotype.evolve(), org.jgap.gp.impl.GPGenotype.getFittestProgram(), org.jgap.gp.impl.GPGenotype.getFittestProgramComputed(), and org.jgap.gp.impl.GPGenotype.hashCode().
StringBuffer org.jgap.gp.impl.GPGenotype.getProgramString (IGPProgram i1) [inline], [private]
Utility function.
Parameters
i1 program to get textual representation for
Returns
textual representation of the given program
Author
Klaus Meffert
Definition at line 1365 of file GPGenotype.java.
References org.jgap.gp.CommandGene.toString().
Referenced by org.jgap.gp.impl.GPGenotype.writeToFile().
static GPConfiguration org.jgap.gp.impl.GPGenotype.getStaticGPConfiguration () [inline], [static]
Returns
the static configuration to use with Genetic Programming
Author
Klaus Meffert
Since
3.2
Definition at line 480 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.m_staticConfiguration.
double org.jgap.gp.impl.GPGenotype.getTotalFitness () [inline]
Returns
the total fitness, that is the fitness over all chromosomes
Author
Klaus Meffert
Since
3.0
Definition at line 924 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.m_totalFitness.
Referenced by org.jgap.gp.impl.FitnessProportionateSelection.select().
Variable org.jgap.gp.impl.GPGenotype.getVariable (String a_varName) [inline]
Parameters
a_varName name of variable to retriebe
Returns
Variable instance or null, if not found
Author
Klaus Meffert
Since
3.2
Definition at line 1167 of file GPGenotype.java.
int org.jgap.gp.impl.GPGenotype.hashCode () [inline]
Definition at line 1106 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.getGPPopulation().
void org.jgap.gp.impl.GPGenotype.init () [inline], [protected]
Definition at line 230 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.GPGenotype().
static boolean org.jgap.gp.impl.GPGenotype.nodeExists (CommandGene[] a_functionSet, Class a_returnType, int a_subReturnType) [inline], [static], [protected]
Is there a node with the needed return type and sub return type within the given function set?
Parameters
a_functionSet collection of available nodes
a_returnType needed return type
a_subReturnType needed sub return type
Returns
true: node found
Author
Klaus Meffert
Since
3.4.4
Definition at line 1465 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.verifyChildNodes().
static void org.jgap.gp.impl.GPGenotype.outputDepthInfo (Map< CommandGene, int[]> a_invalidDepths) [inline], [static], [protected]
Outputs the nodes that are never used because they would result in creating GP programs which would not satisfy the depth constraints given in configuration.
Parameters
a_invalidDepths impossible depths for nodes
Author
Klaus Meffert
Since
3.4.4
Definition at line 1511 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.randomInitialGenotype().
void org.jgap.gp.impl.GPGenotype.outputSolution (IGPProgram a_best) [inline]
Outputs the best solution until now.
Parameters
a_best the fittest ProgramChromosome
Author
Klaus Meffert
Since
3.0
Definition at line 659 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.calcFitness().
static void org.jgap.gp.impl.GPGenotype.outputWarning (Map< String, CommandGene > invalidNodes) [inline], [static], [protected]
Outputs the nodes that are never used.
Parameters
invalidNodes never used nodes
Author
Klaus Meffert
Since
3.4.4
Definition at line 1486 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.randomInitialGenotype().
void org.jgap.gp.impl.GPGenotype.putVariable (Variable a_var) [inline]
Stores a Variable.
Parameters
a_var the Variable to store
Author
Klaus Meffert
Since
3.2
Definition at line 1156 of file GPGenotype.java.
static GPGenotype org.jgap.gp.impl.GPGenotype.randomInitialGenotype (final GPConfiguration a_conf, Class[] a_types, Class a_argTypes[][], CommandGene a_nodeSets[][], int a_maxNodes, boolean a_verboseOutput) throws InvalidConfigurationException [inline], [static]
Creates a genotype with initial population for the world set.
Parameters
a_conf the configuration to use
a_types the type of each chromosome, the length is the number of chromosomes
a_argTypes the types of the arguments to each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of arguments to the chromosome
a_nodeSets the nodes which are allowed to be used by each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of nodes. Note that it is not necessary to include the arguments of a chromosome as terminals in the chromosome's node set. This is done automatically
a_maxNodes reserve space for a_maxNodes number of nodes
a_verboseOutput true: output status information to console
Returns
created genotype with initialized population
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 260 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.randomInitialGenotype().
static GPGenotype org.jgap.gp.impl.GPGenotype.randomInitialGenotype (final GPConfiguration a_conf, Class[] a_types, Class a_argTypes[][], CommandGene a_nodeSets[][], int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, boolean a_verboseOutput) throws InvalidConfigurationException [inline], [static]
Creates a genotype with initial population for the world set.
Parameters
a_conf the configuration to use
a_types the type of each chromosome, the length is the number of chromosomes
a_argTypes the types of the arguments to each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of arguments to the chromosome
a_nodeSets the nodes which are allowed to be used by each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of nodes. Note that it is not necessary to include the arguments of a chromosome as terminals in the chromosome's node set. This is done automatically
a_minDepths array of minimum depths to use: for each chromosome one entry
a_maxDepths array of maximum depths to use: for each chromosome one entry
a_maxNodes reserve space for a_maxNodes number of nodes
a_verboseOutput true: output status information to console
Returns
created genotype with initialized population
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 301 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.randomInitialGenotype().
static GPGenotype org.jgap.gp.impl.GPGenotype.randomInitialGenotype (final GPConfiguration a_conf, Class[] a_types, Class a_argTypes[][], CommandGene a_nodeSets[][], int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, boolean[] a_fullModeAllowed, boolean a_verboseOutput) throws InvalidConfigurationException [inline], [static]
Creates a genotype with a randomly created initial population.
Parameters
a_conf the configuration to use
a_types the type of each chromosome, the length is the number of chromosomes
a_argTypes the types of the arguments to each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of arguments to the chromosome
a_nodeSets the nodes which are allowed to be used by each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of nodes. Note that it is not necessary to include the arguments of a chromosome as terminals in the chromosome's node set. This is done automatically
a_minDepths array of minimum depths to use: for each chromosome one entry
a_maxDepths array of maximum depths to use: for each chromosome one entry
a_maxNodes reserve space for a_maxNodes number of nodes
a_fullModeAllowed array of boolean values. For each chromosome there is one value indicating whether the full mode for creating chromosome generations during evolution is allowed (true) or not (false)
a_verboseOutput true: output status information to console
Returns
created genotype with initialized population
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 352 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.randomInitialGenotype().
static GPGenotype org.jgap.gp.impl.GPGenotype.randomInitialGenotype (final GPConfiguration a_conf, Class[] a_types, Class a_argTypes[][], CommandGene a_nodeSets[][], int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, boolean[] a_fullModeAllowed, boolean a_verboseOutput, IPopulationCreator a_popCreator) throws InvalidConfigurationException [inline], [static]
Allows to use a custom mechanism for population creation.
Parameters
a_conf the configuration to use
a_types the type of each chromosome, the length is the number of chromosomes
a_argTypes the types of the arguments to each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of arguments to the chromosome
a_nodeSets the nodes which are allowed to be used by each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of nodes. Note that it is not necessary to include the arguments of a chromosome as terminals in the chromosome's node set. This is done automatically
a_minDepths array of minimum depths to use: for each chromosome one entry
a_maxDepths array of maximum depths to use: for each chromosome one entry
a_maxNodes reserve space for a_maxNodes number of nodes
a_fullModeAllowed array of boolean values. For each chromosome there is one value indicating whether the full mode for creating chromosome generations during evolution is allowed (true) or not (false)
a_verboseOutput true: output status information to console
a_popCreator mechanism fior creating the population
Returns
GPGenotype
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.2.2
Todo
Todo remove unused nodes from configuration
Todo
Todo optimize access to map
Definition at line 397 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.checkErroneousPop(), org.jgap.gp.impl.GPGenotype.GPGenotype(), org.jgap.gp.impl.GPGenotype.m_variables, org.jgap.gp.impl.GPGenotype.outputDepthInfo(), org.jgap.gp.impl.GPGenotype.outputWarning(), org.jgap.gp.impl.GPGenotype.verifyChildNodes(), and org.jgap.gp.impl.GPGenotype.verifyDepthsForNodes().
void org.jgap.gp.impl.GPGenotype.run () [inline]
Default implementation of method to run GPGenotype as a thread.
Author
Klaus Meffert
Since
3.0
Definition at line 934 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.calcFitness(), and org.jgap.gp.impl.GPGenotype.evolve().
void org.jgap.gp.impl.GPGenotype.setGPConfiguration (GPConfiguration a_configuration) [inline]
Sets the configuration to use with the Genetic Algorithm.
Parameters
a_configuration the configuration to use
Author
Klaus Meffert
Since
3.0
Definition at line 1008 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.m_configuration.
Referenced by org.jgap.gp.impl.GPGenotype.GPGenotype().
void org.jgap.gp.impl.GPGenotype.setGPPopulation (GPPopulation a_pop) [inline], [protected]
Definition at line 997 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.m_population.
Referenced by org.jgap.gp.impl.GPGenotype.evolve(), and org.jgap.gp.impl.GPGenotype.GPGenotype().
static void org.jgap.gp.impl.GPGenotype.setStaticGPConfiguration (GPConfiguration a_configuration) [inline], [static]
Sets the static configuration to use with the Genetic Programming.
Parameters
a_configuration the static configuration to use
Author
Klaus Meffert
Since
3.2
Definition at line 492 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.m_staticConfiguration.
void org.jgap.gp.impl.GPGenotype.setVerboseOutput (boolean a_verbose) [inline]
Parameters
a_verbose true: output status information to console
Author
Klaus Meffert
Since
3.0
Definition at line 1127 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.m_verbose.
static Map<String, CommandGene> org.jgap.gp.impl.GPGenotype.verifyChildNodes (GPConfiguration a_conf, Class[] a_types, CommandGene a_nodeSets[][]) [inline], [static]
Determine impossible functions and terminals to obtimize creation of GP programs.
Parameters
a_conf GP configuration
a_types Class[]
a_nodeSets CommandGene[][]
Returns
Map
Author
Klaus Meffert
Since
3.4.4
Definition at line 1396 of file GPGenotype.java.
References org.jgap.gp.CommandGene.getSubChildTypes(), and org.jgap.gp.impl.GPGenotype.nodeExists().
Referenced by org.jgap.gp.impl.GPGenotype.randomInitialGenotype().
static Map<CommandGene, int[]> org.jgap.gp.impl.GPGenotype.verifyDepthsForNodes (GPPopulation a_pop, GPConfiguration a_conf, Class[] a_types, int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, CommandGene a_nodeSets[][]) [inline], [static]
Todo
Todo impl
Todo
Todo impl
Definition at line 1532 of file GPGenotype.java.
References org.jgap.gp.CommandGene.getReturnType(), org.jgap.gp.CommandGene.getSubChildType(), and org.jgap.gp.CommandGene.getSubReturnType().
Referenced by org.jgap.gp.impl.GPGenotype.randomInitialGenotype().
void org.jgap.gp.impl.GPGenotype.writeToFile (IGPProgram i1, IGPProgram i2, IGPProgram inew, String header) [inline], [private]
Write three GP programs being involved in crossover as a string to a file for debug purposes.
Parameters
i1 first program
i2 second program
inew resulting program
header text for header text
Author
Klaus Meffert
Definition at line 1335 of file GPGenotype.java.
References org.jgap.gp.impl.GPGenotype.getProgramString().
Referenced by org.jgap.gp.impl.GPGenotype.evolve().
Member Data Documentation
final String org.jgap.gp.impl.GPGenotype.CVS_REVISION = `$Revision: 1.60 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 32 of file GPGenotype.java.
transient Logger org.jgap.gp.impl.GPGenotype.LOGGER = Logger.getLogger(GPGenotype.class) [static], [private]
Definition at line 34 of file GPGenotype.java.
IGPProgram org.jgap.gp.impl.GPGenotype.m_allTimeBest [private]
Best solution found
Definition at line 61 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.calcFitness(), org.jgap.gp.impl.GPGenotype.getAllTimeBest(), and org.jgap.gp.impl.GPGenotype.getFittestProgram().
double org.jgap.gp.impl.GPGenotype.m_allTimeBestFitness [private]
Definition at line 63 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.calcFitness(), and org.jgap.gp.impl.GPGenotype.GPGenotype().
Class [][] org.jgap.gp.impl.GPGenotype.m_argTypes [private]
Argument types for ADF's
Definition at line 78 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.evolve(), and org.jgap.gp.impl.GPGenotype.GPGenotype().
double org.jgap.gp.impl.GPGenotype.m_bestFitness [private]
Fitness value of the best solution
Definition at line 51 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.calcFitness().
boolean org.jgap.gp.impl.GPGenotype.m_cloneWarningGPProgramShown [private]
Definition at line 110 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.calcFitness().
GPConfiguration org.jgap.gp.impl.GPGenotype.m_configuration [private]
The current configuration instance
Definition at line 44 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.getGPConfiguration(), and org.jgap.gp.impl.GPGenotype.setGPConfiguration().
IGPProgram org.jgap.gp.impl.GPGenotype.m_fittestToAdd [private]
Definition at line 108 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.addFittestProgram(), and org.jgap.gp.impl.GPGenotype.evolve().
boolean org.jgap.gp.impl.GPGenotype.m_fullModeAllowed[] [private]
Is full mode with program construction allowed?
Definition at line 68 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.evolve().
int [] org.jgap.gp.impl.GPGenotype.m_maxDepths [private]
Maximum depth per each chromosome
Definition at line 93 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.evolve(), and org.jgap.gp.impl.GPGenotype.GPGenotype().
int org.jgap.gp.impl.GPGenotype.m_maxNodes [private]
Maximum number of nodes allowed per chromosome (when exceeded program aborts)
Definition at line 99 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.evolve(), and org.jgap.gp.impl.GPGenotype.GPGenotype().
int [] org.jgap.gp.impl.GPGenotype.m_minDepths [private]
Minimum depth per each chromosome
Definition at line 88 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.evolve(), and org.jgap.gp.impl.GPGenotype.GPGenotype().
CommandGene [][] org.jgap.gp.impl.GPGenotype.m_nodeSets [private]
Available GP-functions.
Definition at line 83 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.evolve(), and org.jgap.gp.impl.GPGenotype.GPGenotype().
GPPopulation org.jgap.gp.impl.GPGenotype.m_population [private]
The array of GPProgram's that make-up this GPGenotype's population
Definition at line 39 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.getGPPopulation(), and org.jgap.gp.impl.GPGenotype.setGPPopulation().
transient GPConfiguration org.jgap.gp.impl.GPGenotype.m_staticConfiguration [static], [private]
Definition at line 46 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.getStaticGPConfiguration(), and org.jgap.gp.impl.GPGenotype.setStaticGPConfiguration().
double org.jgap.gp.impl.GPGenotype.m_totalFitness [private]
Sum of fitness values over all chromosomes
Definition at line 56 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.calcFitness(), and org.jgap.gp.impl.GPGenotype.getTotalFitness().
Class [] org.jgap.gp.impl.GPGenotype.m_types [private]
Return type per chromosome
Definition at line 73 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.evolve(), and org.jgap.gp.impl.GPGenotype.GPGenotype().
Map org.jgap.gp.impl.GPGenotype.m_variables [private]
Definition at line 106 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.GPGenotype(), and org.jgap.gp.impl.GPGenotype.randomInitialGenotype().
boolean org.jgap.gp.impl.GPGenotype.m_verbose [private]
True: Output status information to console
Definition at line 104 of file GPGenotype.java.
Referenced by org.jgap.gp.impl.GPGenotype.calcFitness(), org.jgap.gp.impl.GPGenotype.evolve(), and org.jgap.gp.impl.GPGenotype.setVerboseOutput().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/impl/GPGenotype.java