org.jgap.data.DataElement Class Reference
Public Member Functions
DataElement (final String a_tagName)
void setAttribute (final String a_name, final String a_value) throws Exception
void appendChild (final IDataElement a_newChild) throws Exception
String getTagName ()
IDataElementList getElementsByTagName (final String a_name)
short getNodeType ()
String getNodeValue () throws Exception
IDataElementList getChildNodes ()
String getAttribute (final String a_name)
Map getAttributes ()
Private Attributes
IDataElementList m_elements
Map m_attributes
String m_tagName
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.6 $`
Additional Inherited Members
Detailed Description
Element owning a tag name and holding attributes. Used by the DataTreeBuilder.
Author
Klaus Meffert
Since
2.0
Definition at line 21 of file DataElement.java.
Constructor & Destructor Documentation
org.jgap.data.DataElement.DataElement (final String a_tagName) [inline]
Definition at line 32 of file DataElement.java.
References org.jgap.data.DataElement.m_attributes, org.jgap.data.DataElement.m_elements, and org.jgap.data.DataElement.m_tagName.
Member Function Documentation
void org.jgap.data.DataElement.appendChild (final IDataElement a_newChild) throws Exception [inline]
Definition at line 43 of file DataElement.java.
String org.jgap.data.DataElement.getAttribute (final String a_name) [inline]
Definition at line 75 of file DataElement.java.
Map org.jgap.data.DataElement.getAttributes () [inline]
Implements org.jgap.data.IDataElement.
Definition at line 79 of file DataElement.java.
References org.jgap.data.DataElement.m_attributes.
Referenced by org.jgap.data.DataElementTest.testAttributes_0().
IDataElementList org.jgap.data.DataElement.getChildNodes () [inline]
Implements org.jgap.data.IDataElement.
Definition at line 71 of file DataElement.java.
References org.jgap.data.DataElement.m_elements.
Referenced by org.jgap.data.DataElementTest.testAppendChild_0().
IDataElementList org.jgap.data.DataElement.getElementsByTagName (final String a_name) [inline]
Definition at line 52 of file DataElement.java.
References org.jgap.data.IDataElementList.item(), and org.jgap.data.DataElement.m_elements.
short org.jgap.data.DataElement.getNodeType () [inline]
Definition at line 62 of file DataElement.java.
Referenced by org.jgap.data.DataElementTest.testGetNodeType_0().
String org.jgap.data.DataElement.getNodeValue () throws Exception [inline]
Definition at line 66 of file DataElement.java.
Referenced by org.jgap.data.DataElementTest.testAttributes_0(), and org.jgap.data.DataElementTest.testGetNodeType_0().
String org.jgap.data.DataElement.getTagName () [inline]
Implements org.jgap.data.IDataElement.
Definition at line 48 of file DataElement.java.
References org.jgap.data.DataElement.m_tagName.
Referenced by org.jgap.data.DataElementTest.testGetElementsByTagName_0().
void org.jgap.data.DataElement.setAttribute (final String a_name, final String a_value) throws Exception [inline]
Definition at line 38 of file DataElement.java.
Member Data Documentation
final String org.jgap.data.DataElement.CVS_REVISION = `$Revision: 1.6 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file DataElement.java.
Map org.jgap.data.DataElement.m_attributes [private]
Definition at line 28 of file DataElement.java.
Referenced by org.jgap.data.DataElement.DataElement(), and org.jgap.data.DataElement.getAttributes().
IDataElementList org.jgap.data.DataElement.m_elements [private]
Definition at line 26 of file DataElement.java.
Referenced by org.jgap.data.DataElement.DataElement(), org.jgap.data.DataElement.getChildNodes(), and org.jgap.data.DataElement.getElementsByTagName().
String org.jgap.data.DataElement.m_tagName [private]
Definition at line 30 of file DataElement.java.
Referenced by org.jgap.data.DataElement.DataElement(), and org.jgap.data.DataElement.getTagName().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/data/DataElement.java