org.jgap.perf.TestOverallPerformanceFitnessFunc Class Reference
Public Member Functions
TestOverallPerformanceFitnessFunc (int a_targetAmount)
double evaluate (IChromosome a_subject)
Static Public Member Functions
static int amountOfChange (IChromosome a_potentialSolution)
static int getNumberOfCoinsAtGene (IChromosome a_potentialSolution, int a_position)
static int getTotalNumberOfCoins (IChromosome a_potentialsolution)
Private Attributes
final int m_targetAmount
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
Sample fitness function for the MakeChange example.
Author
Klaus Meffert
Since
2.0
Definition at line 20 of file TestOverallPerformanceFitnessFunc.java.
Constructor & Destructor Documentation
org.jgap.perf.TestOverallPerformanceFitnessFunc.TestOverallPerformanceFitnessFunc (int a_targetAmount) [inline]
Definition at line 28 of file TestOverallPerformanceFitnessFunc.java.
References org.jgap.perf.TestOverallPerformanceFitnessFunc.m_targetAmount.
Member Function Documentation
static int org.jgap.perf.TestOverallPerformanceFitnessFunc.amountOfChange (IChromosome a_potentialSolution) [inline], [static]
Calculates the total amount of change (in cents) represented by the given potential solution and returns that amount. Here we use `fantasy` coins just to have more genes and bloat the time consumed for test performance test
Parameters
a_potentialSolution the pontential solution to evaluate
Returns
the total amount of change (in cents) represented by the given solution
Definition at line 91 of file TestOverallPerformanceFitnessFunc.java.
References org.jgap.perf.TestOverallPerformanceFitnessFunc.getNumberOfCoinsAtGene().
Referenced by org.jgap.perf.TestOverallPerformanceFitnessFunc.evaluate().
double org.jgap.perf.TestOverallPerformanceFitnessFunc.evaluate (IChromosome a_subject) [inline], [virtual]
Determine the fitness of the given Chromosome instance. The higher the return value, the more fit the instance. This method should always return the same fitness value for two equivalent Chromosome instances.
Parameters
a_subject the Chromosome instance to evaluate
Returns
a positive integer reflecting the fitness rating of the given Chromosome
Implements org.jgap.FitnessFunction.
Definition at line 45 of file TestOverallPerformanceFitnessFunc.java.
References org.jgap.perf.TestOverallPerformanceFitnessFunc.amountOfChange(), org.jgap.perf.TestOverallPerformanceFitnessFunc.getTotalNumberOfCoins(), and org.jgap.perf.TestOverallPerformanceFitnessFunc.m_targetAmount.
static int org.jgap.perf.TestOverallPerformanceFitnessFunc.getNumberOfCoinsAtGene (IChromosome a_potentialSolution, int a_position) [inline], [static]
Retrieves the number of coins represented by the given potential solution at the given gene position.
Parameters
a_potentialSolution the potential solution to evaluate
a_position the gene position to evaluate
Returns
the number of coins represented by the potential solution at the given gene position
Definition at line 116 of file TestOverallPerformanceFitnessFunc.java.
References org.jgap.IChromosome.getGene().
Referenced by org.jgap.perf.TestOverallPerformanceFitnessFunc.amountOfChange(), and org.jgap.perf.TestOverallPerformanceFitnessFunc.getTotalNumberOfCoins().
static int org.jgap.perf.TestOverallPerformanceFitnessFunc.getTotalNumberOfCoins (IChromosome a_potentialsolution) [inline], [static]
Returns the total number of coins represented by all of the genes in the given potential solution.
Parameters
a_potentialsolution the potential solution to evaluate
Returns
the total number of coins represented by the given Chromosome
Definition at line 130 of file TestOverallPerformanceFitnessFunc.java.
References org.jgap.perf.TestOverallPerformanceFitnessFunc.getNumberOfCoinsAtGene().
Referenced by org.jgap.perf.TestOverallPerformanceFitnessFunc.evaluate().
Member Data Documentation
final String org.jgap.perf.TestOverallPerformanceFitnessFunc.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file TestOverallPerformanceFitnessFunc.java.
final int org.jgap.perf.TestOverallPerformanceFitnessFunc.m_targetAmount [private]
Definition at line 26 of file TestOverallPerformanceFitnessFunc.java.
Referenced by org.jgap.perf.TestOverallPerformanceFitnessFunc.evaluate(), and org.jgap.perf.TestOverallPerformanceFitnessFunc.TestOverallPerformanceFitnessFunc().
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/perf/TestOverallPerformanceFitnessFunc.java