org.jgap.data.config.RootConfigurationHandler Class Reference
Public Member Functions
String getName ()
List getConfigProperties ()
String getNS ()
void readConfig () throws ConfigException, InvalidConfigurationException
void setConfigurable (Configurable a_configurable)
void setConfigProperty (Object a_configurable, String a_propertyName, String a_value) throws IllegalAccessException
Static Public Member Functions
static Field getPrivateField (Object a_instance, String a_fieldName)
static void configureClass (String className) throws ConfigException
Private Attributes
Configurable m_configurable
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.12 $`
static final String CONFIG_NAMESPACE = `org.jgap.Configuration`
static final String GENETIC_OPS = `GeneticOperators`
static final String NATURAL_SELS = `NaturalSelectors`
Additional Inherited Members
Detailed Description
The ConfigurationHandler for the Configuration class itself. This is the entry point for a Configuration. In other words this is for dynamically building up a Configuration.
Author
Siddhartha Azad
Klaus Meffert
Since
2.3
Definition at line 26 of file RootConfigurationHandler.java.
Member Function Documentation
static void org.jgap.data.config.RootConfigurationHandler.configureClass (String className) throws ConfigException [inline], [static]
Retrieve all instances of a certain property from the config file reader and configure each of these.
Parameters
className the name of the property to configure
Exceptions
ConfigException
Author
Siddhartha Azad
Since
2.4
Definition at line 210 of file RootConfigurationHandler.java.
Referenced by org.jgap.data.config.RootConfigurationHandler.readConfig().
List org.jgap.data.config.RootConfigurationHandler.getConfigProperties () [inline]
Return the information to generate the GUI for configuring this class.
Returns
a list of ConfigProperty objects
Since
2.3
Implements org.jgap.data.config.ConfigurationHandler.
Definition at line 57 of file RootConfigurationHandler.java.
Referenced by org.jgap.data.config.RootConfigurationHandlerTest.testConstruct_0().
String org.jgap.data.config.RootConfigurationHandler.getName () [inline]
Returns
Name of this Configuration Object (name of what you are configuring) to be used in the properties file.
Since
2.3
Implements org.jgap.data.config.ConfigurationHandler.
Definition at line 48 of file RootConfigurationHandler.java.
String org.jgap.data.config.RootConfigurationHandler.getNS () [inline]
Get the namespace to be used in the config file for the Configurable this ConfigurationHandler belongs to.
Returns
the namespace of the Configurable
Author
Siddhartha Azad
Since
2.3
Implements org.jgap.data.config.ConfigurationHandler.
Definition at line 69 of file RootConfigurationHandler.java.
References org.jgap.data.config.RootConfigurationHandler.CONFIG_NAMESPACE.
Referenced by org.jgap.data.config.RootConfigurationHandlerTest.testGetNameSpace_0().
static Field org.jgap.data.config.RootConfigurationHandler.getPrivateField (Object a_instance, String a_fieldName) [inline], [static]
Helper method: Read a private field.
Parameters
a_instance the instance the field is contained with
a_fieldName the name of the field to read
Returns
the Field object or null, if none found
Author
Klaus Meffert
Since
2.6
Definition at line 190 of file RootConfigurationHandler.java.
Referenced by org.jgap.data.config.RootConfigurationHandler.setConfigProperty(), org.jgap.data.config.RootConfigurationHandlerTest.testGetPrivateField_0(), and org.jgap.data.config.RootConfigurationHandlerTest.testGetPrivateField_1().
void org.jgap.data.config.RootConfigurationHandler.readConfig () throws ConfigException, InvalidConfigurationException [inline]
Method that will populate an Configurable with the properties in the config file.
Exceptions
ConfigException
InvalidConfigurationException
Author
Siddhartha Azad
Since
2.3
Implements org.jgap.data.config.ConfigurationHandler.
Definition at line 83 of file RootConfigurationHandler.java.
References org.jgap.data.config.RootConfigurationHandler.CONFIG_NAMESPACE, org.jgap.data.config.RootConfigurationHandler.configureClass(), org.jgap.data.config.RootConfigurationHandler.GENETIC_OPS, org.jgap.data.config.RootConfigurationHandler.m_configurable, org.jgap.data.config.RootConfigurationHandler.NATURAL_SELS, and org.jgap.data.config.RootConfigurationHandler.setConfigProperty().
void org.jgap.data.config.RootConfigurationHandler.setConfigProperty (Object a_configurable, String a_propertyName, String a_value) throws IllegalAccessException [inline]
Sets the property of a configurable to a given value. Uses reflection to do so. Queries the method getConfigVarName for the name of the field hosting the configurable properties.
Parameters
a_configurable the configurable to use
a_propertyName the property to set
a_value the value to assign to the property
Exceptions
IllegalAccessException
Author
Klaus Meffert
Since
2.6
Definition at line 129 of file RootConfigurationHandler.java.
References org.jgap.data.config.RootConfigurationHandler.getPrivateField().
Referenced by org.jgap.data.config.RootConfigurationHandler.readConfig().
void org.jgap.data.config.RootConfigurationHandler.setConfigurable (Configurable a_configurable) [inline]
Set the Configurable to which this ConfigurationHandler belongs.
Parameters
a_configurable the Configurable to which this ConfigurationHandler belongs
Author
Siddhartha Azad
Since
2.3
Implements org.jgap.data.config.ConfigurationHandler.
Definition at line 112 of file RootConfigurationHandler.java.
References org.jgap.data.config.RootConfigurationHandler.m_configurable.
Member Data Documentation
final String org.jgap.data.config.RootConfigurationHandler.CONFIG_NAMESPACE = `org.jgap.Configuration` [static], [private]
Definition at line 32 of file RootConfigurationHandler.java.
Referenced by org.jgap.data.config.RootConfigurationHandler.getNS(), and org.jgap.data.config.RootConfigurationHandler.readConfig().
final String org.jgap.data.config.RootConfigurationHandler.CVS_REVISION = `$Revision: 1.12 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 29 of file RootConfigurationHandler.java.
final String org.jgap.data.config.RootConfigurationHandler.GENETIC_OPS = `GeneticOperators` [static], [private]
Definition at line 36 of file RootConfigurationHandler.java.
Referenced by org.jgap.data.config.RootConfigurationHandler.readConfig().
Configurable org.jgap.data.config.RootConfigurationHandler.m_configurable [private]
Definition at line 40 of file RootConfigurationHandler.java.
Referenced by org.jgap.data.config.RootConfigurationHandler.readConfig(), and org.jgap.data.config.RootConfigurationHandler.setConfigurable().
final String org.jgap.data.config.RootConfigurationHandler.NATURAL_SELS = `NaturalSelectors` [static], [private]
Definition at line 38 of file RootConfigurationHandler.java.
Referenced by org.jgap.data.config.RootConfigurationHandler.readConfig().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/data/config/RootConfigurationHandler.java