org.jgap.distr.CultureMemoryCell Class Reference
Public Member Functions
CultureMemoryCell ()
CultureMemoryCell (final String a_name)
CultureMemoryCell (final String a_name, final int a_historySize)
void setName (final String a_name)
String getName ()
void setValue (final Object a_value)
void setDouble (final double a_value)
double getCurrentValueAsDouble ()
Object getCurrentValue ()
List getHistory ()
int getVersion ()
int getReadAccessed ()
int getReadAccessedCurrentVersion ()
void setHistorySize (final int a_size)
int getHistorySize ()
String toString ()
long getVersionTimeMilliseconds ()
boolean equals (Object a_other)
int compareTo (Object a_other)
Protected Member Functions
void incrementVersion ()
void keepHistory (final Object a_value, final int a_version, final String a_name)
CultureMemoryCell getNewInstance (final Object a_value, final int a_version, final String a_name)
void trimHistory (final int a_size)
void toStringRecursive (StringBuffer a_result, final int a_historySize)
Private Attributes
String m_name
int m_version
Object m_value
int m_readAccessed
int m_historySize
int m_internalHistorySize
CultureMemoryCell m_previousVersion
List m_history
long m_dateTimeVersion
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.13 $`
Detailed Description
Represents a memory cell used within org.jgap.distr.Culture, a special form of memory.
CultureMemoryCell also stores metadata along with the value-to-store, like date/time of setting a value, change history.
Author
Klaus Meffert
Since
2.3
Definition at line 26 of file CultureMemoryCell.java.
Constructor & Destructor Documentation
org.jgap.distr.CultureMemoryCell.CultureMemoryCell () [inline]
Default constructor.
Author
Klaus Meffert
Since
2.3
Definition at line 84 of file CultureMemoryCell.java.
Referenced by org.jgap.distr.CultureMemoryCell.compareTo(), org.jgap.distr.CultureMemoryCell.getNewInstance(), org.jgap.distr.CultureMemoryCell.getReadAccessedCurrentVersion(), and org.jgap.distr.CultureMemoryCell.toStringRecursive().
org.jgap.distr.CultureMemoryCell.CultureMemoryCell (final String a_name) [inline]
Sets history size to 3.
Parameters
a_name informative name of the memory cell
Author
Klaus Meffert
Since
2.3
Definition at line 95 of file CultureMemoryCell.java.
org.jgap.distr.CultureMemoryCell.CultureMemoryCell (final String a_name, final int a_historySize) [inline]
Allows to freely specify informative name of memory cell as well as size of history to keep.
Parameters
a_name informative name of the memory cell
a_historySize size of history to keep. Use values less than 1 for turning history logging off
Author
Klaus Meffert
Since
2.3
Definition at line 109 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.getHistorySize(), org.jgap.distr.CultureMemoryCell.m_history, org.jgap.distr.CultureMemoryCell.setHistorySize(), and org.jgap.distr.CultureMemoryCell.setName().
Member Function Documentation
int org.jgap.distr.CultureMemoryCell.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.0
Definition at line 420 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.CultureMemoryCell(), org.jgap.distr.CultureMemoryCell.m_historySize, org.jgap.distr.CultureMemoryCell.m_value, and org.jgap.distr.CultureMemoryCell.m_version.
Referenced by org.jgap.distr.CultureMemoryCell.equals().
boolean org.jgap.distr.CultureMemoryCell.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if the objects are regarded as equal
Author
Klaus Meffert
Since
3.0
Definition at line 404 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.compareTo().
Object org.jgap.distr.CultureMemoryCell.getCurrentValue () [inline]
Returns
current memory value
Author
Klaus Meffert
Since
2.3
Definition at line 185 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.m_readAccessed, and org.jgap.distr.CultureMemoryCell.m_value.
Referenced by org.jgap.distr.CultureMemoryCell.getCurrentValueAsDouble(), org.jgap.distr.CultureMemoryCellTest.testSetDouble_0(), and org.jgap.distr.CultureMemoryCellTest.testSetValue_0().
double org.jgap.distr.CultureMemoryCell.getCurrentValueAsDouble () [inline]
Convenience method to retrieve a primitive double value from memory easily. Here a ClassCastException could occur!
Returns
double value representing current memory value
Author
Klaus Meffert
Since
2.3
Definition at line 175 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.getCurrentValue().
Referenced by org.jgap.distr.CultureMemoryCellTest.testSetDouble_0().
List org.jgap.distr.CultureMemoryCell.getHistory () [inline]
Returns
list of most recent entries (except current entry). The item at index 0 is the oldest, the item at highest index is the youngest one.
Author
Klaus Meffert
Since
2.3
Definition at line 197 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.m_history.
Referenced by org.jgap.distr.CultureMemoryCell.setHistorySize(), and org.jgap.distr.CultureMemoryCell.toStringRecursive().
int org.jgap.distr.CultureMemoryCell.getHistorySize () [inline]
Returns
size of the history
Author
Klaus Meffert
Since
2.3
Definition at line 340 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.m_historySize.
Referenced by org.jgap.distr.CultureMemoryCell.CultureMemoryCell(), and org.jgap.distr.CultureMemoryCell.toString().
String org.jgap.distr.CultureMemoryCell.getName () [inline]
Returns
informative name of the memory cell
Author
Klaus Meffert
Since
2.3
Definition at line 132 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.m_name.
Referenced by org.jgap.distr.CultureMemoryCell.setValue(), and org.jgap.distr.CultureMemoryCell.toStringRecursive().
CultureMemoryCell org.jgap.distr.CultureMemoryCell.getNewInstance (final Object a_value, final int a_version, final String a_name) [inline], [protected]
Creates a new instance of CultureMemoryCell preset with the given parameters. Used for creating history entries.
Parameters
a_value memory value to store
a_version version of the value
a_name name to store
Returns
new instance of CultureMemoryCell
Author
Klaus Meffert
Since
2.3
Definition at line 255 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.CultureMemoryCell().
Referenced by org.jgap.distr.CultureMemoryCell.keepHistory(), and org.jgap.distr.CultureMemoryCell.setValue().
int org.jgap.distr.CultureMemoryCell.getReadAccessed () [inline]
Returns
number of times the memory cell has been read accessed
Author
Klaus Meffert
Since
2.3
Definition at line 271 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.m_readAccessed.
Referenced by org.jgap.distr.CultureMemoryCell.getReadAccessedCurrentVersion(), org.jgap.distr.CultureMemoryCellTest.testSetValue_0(), and org.jgap.distr.CultureMemoryCell.toStringRecursive().
int org.jgap.distr.CultureMemoryCell.getReadAccessedCurrentVersion () [inline]
Returns
number of read accesses since current value has been set. Calculated by subtracting number of read accesses for prior version from total number of read accesses
Author
Klaus Meffert
Since
2.3
Definition at line 283 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.CultureMemoryCell(), org.jgap.distr.CultureMemoryCell.getReadAccessed(), org.jgap.distr.CultureMemoryCell.m_history, and org.jgap.distr.CultureMemoryCell.m_historySize.
int org.jgap.distr.CultureMemoryCell.getVersion () [inline]
Returns
version of memory value, read only
Author
Klaus Meffert
Since
2.3
Definition at line 207 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.m_version.
Referenced by org.jgap.distr.CultureMemoryCell.setValue(), org.jgap.distr.CultureMemoryCellTest.testSetValue_0(), and org.jgap.distr.CultureMemoryCell.toStringRecursive().
long org.jgap.distr.CultureMemoryCell.getVersionTimeMilliseconds () [inline]
Returns
time in milliseconds when the current version has been created
Author
Klaus Meffert
Since
3.0
Definition at line 392 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.m_dateTimeVersion.
void org.jgap.distr.CultureMemoryCell.incrementVersion () [inline], [protected]
Increment version number and keep track of current time.
Author
Klaus Meffert
Since
2.3
Definition at line 217 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.m_dateTimeVersion, and org.jgap.distr.CultureMemoryCell.m_version.
Referenced by org.jgap.distr.CultureMemoryCell.setValue().
void org.jgap.distr.CultureMemoryCell.keepHistory (final Object a_value, final int a_version, final String a_name) [inline], [protected]
Puts an entry into history. Stores all information as a new CultureMemoryCell instance.
Parameters
a_value memory value to store
a_version version of the value
a_name name to store
Author
Klaus Meffert
Since
2.3
Definition at line 234 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.getNewInstance(), org.jgap.distr.CultureMemoryCell.m_historySize, and org.jgap.distr.CultureMemoryCell.trimHistory().
Referenced by org.jgap.distr.CultureMemoryCell.setValue().
void org.jgap.distr.CultureMemoryCell.setDouble (final double a_value) [inline]
Convenience method to store a primitive double easily.
Parameters
a_value double value to store
Author
Klaus Meffert
Since
2.3
Definition at line 163 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.setValue().
void org.jgap.distr.CultureMemoryCell.setHistorySize (final int a_size) [inline]
Sets the size of the history and scales down the history log it is larger than the given size.
Parameters
a_size new size of the history log = how many entries to store
Author
Klaus Meffert
Since
2.3
Definition at line 306 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.getHistory(), org.jgap.distr.CultureMemoryCell.m_historySize, and org.jgap.distr.CultureMemoryCell.trimHistory().
Referenced by org.jgap.distr.CultureMemoryCell.CultureMemoryCell().
void org.jgap.distr.CultureMemoryCell.setName (final String a_name) [inline]
Sets the informative name of the memory cell.
Parameters
a_name informative name
Author
Klaus Meffert
Since
2.3
Definition at line 122 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.m_name.
Referenced by org.jgap.distr.CultureMemoryCell.CultureMemoryCell().
void org.jgap.distr.CultureMemoryCell.setValue (final Object a_value) [inline]
Sets a new memory value.
Parameters
a_value the memory value to set
Author
Klaus Meffert
Since
2.3
Definition at line 143 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.getName(), org.jgap.distr.CultureMemoryCell.getNewInstance(), org.jgap.distr.CultureMemoryCell.getVersion(), org.jgap.distr.CultureMemoryCell.incrementVersion(), org.jgap.distr.CultureMemoryCell.keepHistory(), org.jgap.distr.CultureMemoryCell.m_historySize, org.jgap.distr.CultureMemoryCell.m_previousVersion, and org.jgap.distr.CultureMemoryCell.m_value.
Referenced by org.jgap.distr.CultureMemoryCell.setDouble().
String org.jgap.distr.CultureMemoryCell.toString () [inline]
Returns
String representation of the cultural memory cell including all important information (also history log).
Author
Klaus Meffert
Since
2.3
Definition at line 351 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.getHistorySize(), and org.jgap.distr.CultureMemoryCell.toStringRecursive().
Referenced by org.jgap.distr.CultureMemoryCellTest.testToString_0(), org.jgap.distr.CultureMemoryCellTest.testToString_1(), and org.jgap.distr.CultureMemoryCellTest.testToString_2().
void org.jgap.distr.CultureMemoryCell.toStringRecursive (StringBuffer a_result, final int a_historySize) [inline], [protected]
Recursive part of toString().
Parameters
a_result gathered result so far and modified here
a_historySize history size just for information purpose
Author
Klaus Meffert
Since
2.3
Definition at line 365 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.CultureMemoryCell(), org.jgap.distr.CultureMemoryCell.getHistory(), org.jgap.distr.CultureMemoryCell.getName(), org.jgap.distr.CultureMemoryCell.getReadAccessed(), org.jgap.distr.CultureMemoryCell.getVersion(), and org.jgap.distr.CultureMemoryCell.m_value.
Referenced by org.jgap.distr.CultureMemoryCell.toString().
void org.jgap.distr.CultureMemoryCell.trimHistory (final int a_size) [inline], [protected]
Trims the history to the given size.
Parameters
a_size new size of history
Author
Klaus Meffert
Since
2.3
Definition at line 326 of file CultureMemoryCell.java.
References org.jgap.distr.CultureMemoryCell.m_history.
Referenced by org.jgap.distr.CultureMemoryCell.keepHistory(), and org.jgap.distr.CultureMemoryCell.setHistorySize().
Member Data Documentation
final String org.jgap.distr.CultureMemoryCell.CVS_REVISION = `$Revision: 1.13 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 29 of file CultureMemoryCell.java.
long org.jgap.distr.CultureMemoryCell.m_dateTimeVersion [private]
Time in milliseconds when the version number is incremented (e.g. when setting the value of the cell)
Definition at line 76 of file CultureMemoryCell.java.
Referenced by org.jgap.distr.CultureMemoryCell.getVersionTimeMilliseconds(), and org.jgap.distr.CultureMemoryCell.incrementVersion().
List org.jgap.distr.CultureMemoryCell.m_history [private]
History of memory values
Definition at line 70 of file CultureMemoryCell.java.
Referenced by org.jgap.distr.CultureMemoryCell.CultureMemoryCell(), org.jgap.distr.CultureMemoryCell.getHistory(), org.jgap.distr.CultureMemoryCell.getReadAccessedCurrentVersion(), and org.jgap.distr.CultureMemoryCell.trimHistory().
int org.jgap.distr.CultureMemoryCell.m_historySize [private]
How many historical values should be kept for evaluation purposes? Values less than one turn history feature off
Definition at line 57 of file CultureMemoryCell.java.
Referenced by org.jgap.distr.CultureMemoryCell.compareTo(), org.jgap.distr.CultureMemoryCell.getHistorySize(), org.jgap.distr.CultureMemoryCell.getReadAccessedCurrentVersion(), org.jgap.distr.CultureMemoryCell.keepHistory(), org.jgap.distr.CultureMemoryCell.setHistorySize(), and org.jgap.distr.CultureMemoryCell.setValue().
int org.jgap.distr.CultureMemoryCell.m_internalHistorySize [private]
Definition at line 59 of file CultureMemoryCell.java.
String org.jgap.distr.CultureMemoryCell.m_name [private]
Informative name of the memory cell (optional)
Definition at line 34 of file CultureMemoryCell.java.
Referenced by org.jgap.distr.CultureMemoryCell.getName(), and org.jgap.distr.CultureMemoryCell.setName().
CultureMemoryCell org.jgap.distr.CultureMemoryCell.m_previousVersion [private]
If history logging turned off, we need to keep the prior version for evaluation purpose, e.g. see getReadAccessedCurrentVersion
Definition at line 65 of file CultureMemoryCell.java.
Referenced by org.jgap.distr.CultureMemoryCell.setValue().
int org.jgap.distr.CultureMemoryCell.m_readAccessed [private]
How many times has the memory cell been read out?
Definition at line 51 of file CultureMemoryCell.java.
Referenced by org.jgap.distr.CultureMemoryCell.getCurrentValue(), and org.jgap.distr.CultureMemoryCell.getReadAccessed().
Object org.jgap.distr.CultureMemoryCell.m_value [private]
Value of the memory cell
Definition at line 46 of file CultureMemoryCell.java.
Referenced by org.jgap.distr.CultureMemoryCell.compareTo(), org.jgap.distr.CultureMemoryCell.getCurrentValue(), org.jgap.distr.CultureMemoryCell.setValue(), and org.jgap.distr.CultureMemoryCell.toStringRecursive().
int org.jgap.distr.CultureMemoryCell.m_version [private]
Version of the memory value, i.e. how many times has setValue(..) been called)? First version (no value assigned) is zero, second version (first time a value is assigned to the memory) is 1 etc.
Definition at line 41 of file CultureMemoryCell.java.
Referenced by org.jgap.distr.CultureMemoryCell.compareTo(), org.jgap.distr.CultureMemoryCell.getVersion(), and org.jgap.distr.CultureMemoryCell.incrementVersion().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/distr/CultureMemoryCell.java