org.jgap.gp.CrossMethod Class Reference
Public Member Functions
CrossMethod (GPConfiguration a_configuration)
GPConfiguration getConfiguration ()
abstract IGPProgram[] operate (final IGPProgram a_i1, final IGPProgram a_i2)
Private Attributes
GPConfiguration m_configuration
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.8 $`
Detailed Description
Abstract base class for GP-crossing over implementations.
Author
Klaus Meffert
Since
3.0
Definition at line 21 of file CrossMethod.java.
Constructor & Destructor Documentation
org.jgap.gp.CrossMethod.CrossMethod (GPConfiguration a_configuration) [inline]
Definition at line 28 of file CrossMethod.java.
References org.jgap.gp.CrossMethod.m_configuration.
Member Function Documentation
GPConfiguration org.jgap.gp.CrossMethod.getConfiguration () [inline]
Definition at line 32 of file CrossMethod.java.
References org.jgap.gp.CrossMethod.m_configuration.
Referenced by org.jgap.gp.impl.BranchTypingCross.clone(), org.jgap.gp.impl.BranchTypingCross.doCross(), and org.jgap.gp.impl.BranchTypingCross.operate().
abstract IGPProgram [] org.jgap.gp.CrossMethod.operate (final IGPProgram a_i1, final IGPProgram a_i2) [pure virtual]
Crosses two individuals.
Parameters
a_i1 the first individual to cross
a_i2 the second individual to cross
Returns
an array of the two resulting individuals
Author
Klaus Meffert
Since
3.0
Implemented in org.jgap.gp.impl.BranchTypingCross.
Member Data Documentation
final String org.jgap.gp.CrossMethod.CVS_REVISION = `$Revision: 1.8 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file CrossMethod.java.
GPConfiguration org.jgap.gp.CrossMethod.m_configuration [private]
Definition at line 26 of file CrossMethod.java.
Referenced by org.jgap.gp.CrossMethod.CrossMethod(), and org.jgap.gp.CrossMethod.getConfiguration().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/CrossMethod.java