examples.gp.monalisa.core.commands.DrawPolygon Class Reference
Public Member Functions
DrawPolygon (GPConfiguration a_conf) throws InvalidConfigurationException
void execute_void (ProgramChromosome a_chrom, int a_n, Object[] a_args)
Class getChildType (IGPProgram a_ind, int a_chromNum)
ApplicationData getAppData (ProgramChromosome a_chrom)
String toString ()
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
Draws a polygon with a certain fill color.
Author
Yann N. Dauphin
Klaus Meffert (statistics data)
Since
3.4
Definition at line 26 of file DrawPolygon.java.
Constructor & Destructor Documentation
examples.gp.monalisa.core.commands.DrawPolygon.DrawPolygon (GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Definition at line 31 of file DrawPolygon.java.
Referenced by examples.gp.monalisa.core.commands.DrawPolygon.clone().
Member Function Documentation
Object examples.gp.monalisa.core.commands.DrawPolygon.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4.1
Definition at line 77 of file DrawPolygon.java.
References examples.gp.monalisa.core.commands.DrawPolygon.DrawPolygon(), and org.jgap.gp.CommandGene.getGPConfiguration().
void examples.gp.monalisa.core.commands.DrawPolygon.execute_void (ProgramChromosome a_chrom, int a_n, Object[] a_args) [inline]
Definition at line 37 of file DrawPolygon.java.
References examples.gp.monalisa.core.commands.DrawPolygon.getAppData(), and examples.gp.monalisa.core.ApplicationData.graphics.
ApplicationData examples.gp.monalisa.core.commands.DrawPolygon.getAppData (ProgramChromosome a_chrom) [inline]
Definition at line 58 of file DrawPolygon.java.
Referenced by examples.gp.monalisa.core.commands.DrawPolygon.execute_void().
Class examples.gp.monalisa.core.commands.DrawPolygon.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Definition at line 51 of file DrawPolygon.java.
String examples.gp.monalisa.core.commands.DrawPolygon.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 65 of file DrawPolygon.java.
Member Data Documentation
final String examples.gp.monalisa.core.commands.DrawPolygon.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 29 of file DrawPolygon.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/monalisa/core/commands/DrawPolygon.java