org.jgap.gp.function.Push Class Reference
Public Member Functions
Push (final GPConfiguration a_conf, Class a_type) throws InvalidConfigurationException
Push (final GPConfiguration a_conf, Class a_type, int a_subReturnType, int a_subChildType) throws InvalidConfigurationException
String toString ()
String getName ()
void execute_void (ProgramChromosome c, int n, Object[] args)
int execute_int (ProgramChromosome c, int n, Object[] args)
long execute_long (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
boolean isAffectGlobalState ()
boolean isValid (ProgramChromosome a_program)
Class getChildType (IGPProgram a_ind, int a_chromNum)
int compareTo (Object a_other)
boolean equals (Object a_other)
Object clone ()
Protected Member Functions
void pushIt (Object a_value)
Private Attributes
Class m_type
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.13 $`
Additional Inherited Members
Detailed Description
Pushes a value onto the stack.
Author
Klaus Meffert
Since
3.0
Definition at line 24 of file Push.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Push.Push (final GPConfiguration a_conf, Class a_type) throws InvalidConfigurationException [inline]
Definition at line 31 of file Push.java.
Referenced by org.jgap.gp.function.Push.clone(), org.jgap.gp.function.Push.compareTo(), and org.jgap.gp.function.Push.equals().
org.jgap.gp.function.Push.Push (final GPConfiguration a_conf, Class a_type, int a_subReturnType, int a_subChildType) throws InvalidConfigurationException [inline]
Definition at line 36 of file Push.java.
References org.jgap.gp.function.Push.m_type, and org.jgap.gp.CommandGene.VoidClass.
Member Function Documentation
Object org.jgap.gp.function.Push.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 173 of file Push.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getSubChildType(), org.jgap.gp.CommandGene.getSubReturnType(), org.jgap.gp.function.Push.m_type, and org.jgap.gp.function.Push.Push().
int org.jgap.gp.function.Push.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.0
Definition at line 134 of file Push.java.
References org.jgap.gp.function.Push.m_type, and org.jgap.gp.function.Push.Push().
boolean org.jgap.gp.function.Push.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Klaus Meffert
Since
3.0
Definition at line 154 of file Push.java.
References org.jgap.gp.function.Push.m_type, and org.jgap.gp.function.Push.Push().
double org.jgap.gp.function.Push.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 83 of file Push.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.function.Push.pushIt().
float org.jgap.gp.function.Push.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 90 of file Push.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.function.Push.pushIt().
int org.jgap.gp.function.Push.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 65 of file Push.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.function.Push.pushIt().
long org.jgap.gp.function.Push.execute_long (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 74 of file Push.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.function.Push.pushIt().
Object org.jgap.gp.function.Push.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 97 of file Push.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.function.Push.pushIt().
void org.jgap.gp.function.Push.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 57 of file Push.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.function.Push.pushIt().
Class org.jgap.gp.function.Push.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Definition at line 121 of file Push.java.
References org.jgap.gp.function.Push.m_type.
String org.jgap.gp.function.Push.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 53 of file Push.java.
boolean org.jgap.gp.function.Push.isAffectGlobalState () [inline]
Todo
Todo use this information
Definition at line 104 of file Push.java.
boolean org.jgap.gp.function.Push.isValid (ProgramChromosome a_program) [inline]
Todo
Todo consider n (execute_int...)
Definition at line 108 of file Push.java.
void org.jgap.gp.function.Push.pushIt (Object a_value) [inline], [protected]
Helper method.
Parameters
a_value the value to push onto the stack
Definition at line 117 of file Push.java.
References org.jgap.gp.CommandGene.getGPConfiguration().
Referenced by org.jgap.gp.function.Push.execute_double(), org.jgap.gp.function.Push.execute_float(), org.jgap.gp.function.Push.execute_int(), org.jgap.gp.function.Push.execute_long(), org.jgap.gp.function.Push.execute_object(), and org.jgap.gp.function.Push.execute_void().
String org.jgap.gp.function.Push.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 43 of file Push.java.
Member Data Documentation
final String org.jgap.gp.function.Push.CVS_REVISION = `$Revision: 1.13 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file Push.java.
Class org.jgap.gp.function.Push.m_type [private]
Definition at line 29 of file Push.java.
Referenced by org.jgap.gp.function.Push.clone(), org.jgap.gp.function.Push.compareTo(), org.jgap.gp.function.Push.equals(), org.jgap.gp.function.Push.getChildType(), and org.jgap.gp.function.Push.Push().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Push.java