examples.gp.SimpleExample Class Reference
Classes
class SimpleFitnessFunction
Public Member Functions
GPGenotype create () throws InvalidConfigurationException
void start () throws Exception
Static Public Member Functions
static void main (String[] args) throws Exception
Static Protected Attributes
static Variable vx
Additional Inherited Members
Detailed Description
Simple example of Genetic Programming to discover the formula (X > 0) OR (X == -8) OR (X == - 5) given a set of inputs from -10 to 10 and expected outputs (true or false).
The fitness function used in this example cares about deviation from the expected result as well as the complexity of the solution (the easier the solution, the better it is, mutatis mutandis).
Author
Klaus Meffert
Since
3.5
Definition at line 32 of file SimpleExample.java.
Member Function Documentation
GPGenotype examples.gp.SimpleExample.create () throws InvalidConfigurationException [inline], [virtual]
Returns
newly created GPGenotype
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.GPProblem.
Definition at line 37 of file SimpleExample.java.
References org.jgap.gp.CommandGene.BooleanClass, org.jgap.gp.GPProblem.getGPConfiguration(), org.jgap.gp.CommandGene.IntegerClass, and examples.gp.SimpleExample.vx.
Referenced by examples.gp.SimpleExample.start().
static void examples.gp.SimpleExample.main (String[] args) throws Exception [inline], [static]
Definition at line 133 of file SimpleExample.java.
void examples.gp.SimpleExample.start () throws Exception [inline]
New best solution found.
Parameters
a_firedEvent GeneticEvent
Definition at line 78 of file SimpleExample.java.
References examples.gp.SimpleExample.create().
Member Data Documentation
Variable examples.gp.SimpleExample.vx [static], [protected]
Definition at line 35 of file SimpleExample.java.
Referenced by examples.gp.SimpleExample.create().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/SimpleExample.java