org.jgap.impl.ChainOfSelectorsTest Class Reference
Public Member Functions
void testConstruct_0 ()
void testClear_0 ()
void testClear_1 () throws Exception
void testClear_2 () throws Exception
void testIterator_0 () throws Exception
void testAddNaturalSelector_0 () throws Exception
void testEquals_0 () throws Exception
void testEquals_1 () throws Exception
void testHashCode_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.13 $`
Additional Inherited Members
Detailed Description
Tests the ChainOfSelectors class.
Since
1.1
Author
Klaus Meffert
Definition at line 22 of file ChainOfSelectorsTest.java.
Member Function Documentation
static Test org.jgap.impl.ChainOfSelectorsTest.suite () [inline], [static]
Definition at line 27 of file ChainOfSelectorsTest.java.
void org.jgap.impl.ChainOfSelectorsTest.testAddNaturalSelector_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 114 of file ChainOfSelectorsTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.ChainOfSelectorsTest.testClear_0 () [inline]
Author
Klaus Meffert
Since
2.2
Definition at line 44 of file ChainOfSelectorsTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.ChainOfSelectors.isEmpty().
void org.jgap.impl.ChainOfSelectorsTest.testClear_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 57 of file ChainOfSelectorsTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.ChainOfSelectors.isEmpty(), and org.jgap.impl.ChainOfSelectors.size().
void org.jgap.impl.ChainOfSelectorsTest.testClear_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 74 of file ChainOfSelectorsTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.ChainOfSelectors.isEmpty(), and org.jgap.impl.ChainOfSelectors.size().
void org.jgap.impl.ChainOfSelectorsTest.testConstruct_0 () [inline]
Author
Klaus Meffert
Since
2.2
Definition at line 36 of file ChainOfSelectorsTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.ChainOfSelectorsTest.testEquals_0 () throws Exception [inline]
Todo
Todo improve: 2 unsame selectors of same class with same params should make the chain equal!
Definition at line 126 of file ChainOfSelectorsTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.ChainOfSelectors.equals().
void org.jgap.impl.ChainOfSelectorsTest.testEquals_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 151 of file ChainOfSelectorsTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.ChainOfSelectors.equals().
void org.jgap.impl.ChainOfSelectorsTest.testHashCode_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 163 of file ChainOfSelectorsTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.ChainOfSelectors.hashCode().
void org.jgap.impl.ChainOfSelectorsTest.testIterator_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 93 of file ChainOfSelectorsTest.java.
References org.jgap.JGAPTestCase.conf.
Member Data Documentation
final String org.jgap.impl.ChainOfSelectorsTest.CVS_REVISION = `$Revision: 1.13 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file ChainOfSelectorsTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/ChainOfSelectorsTest.java