org.jgap.gp.CommandGene Class Reference
Classes
enum COMMAND_TYPE
Public Member Functions
CommandGene () throws Exception
CommandGene (final GPConfiguration a_conf, final int a_arity, final Class a_returnType) throws InvalidConfigurationException
CommandGene (final GPConfiguration a_conf, final int a_arity, final Class a_returnType, final int a_subReturnType, final int[] a_childSubTypes) throws InvalidConfigurationException
CommandGene (final GPConfiguration a_conf, final int a_arity, final Class a_returnType, final int a_subReturnType) throws InvalidConfigurationException
CommandGene (final GPConfiguration a_conf, final int a_arity, final Class a_returnType, final int a_subReturnType, final int a_childSubType) throws InvalidConfigurationException
void setAllele (Object a_newValue)
Object getAllele ()
void setToRandomValue (RandomGenerator a_numberGenerator)
void cleanup ()
int size ()
int getArity (IGPProgram a_indvividual)
void dynamizeArity ()
int compareTo (Object a_other)
boolean equals (Object a_other)
abstract String toString ()
Object execute (ProgramChromosome c, int n, Object[] args)
Class getReturnType ()
void setReturnType (Class a_type)
boolean execute_boolean (ProgramChromosome c, int n, Object[] args)
void execute_void (ProgramChromosome c, int n, Object[] args)
int execute_int (ProgramChromosome c, int n, Object[] args)
long execute_long (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
String getName ()
Class getChildType (IGPProgram a_ind, int a_chromNum)
int hashCode ()
boolean isIntegerType ()
boolean isFloatType ()
boolean isAffectGlobalState ()
boolean isValid (ProgramChromosome a_program)
boolean isValid (ProgramChromosome a_program, int a_index)
void setNoValidation (boolean a_noValidation)
GPConfiguration getGPConfiguration ()
void setApplicationData (final Object a_newData)
Object getApplicationData ()
void setCompareApplicationData (final boolean a_doCompare)
boolean isCompareApplicationData ()
double getEnergy ()
void setEnergy (final double a_energy)
int getSubReturnType ()
int getSubChildType (int a_childNum)
int[] getSubChildTypes ()
void ensureUniqueness (ProgramChromosome a_program)
void ensureUniqueness (ProgramChromosome a_program, int a_maxCount)
boolean ensureUniqueness2 (ProgramChromosome a_program, int a_maxCount)
String getPersistentRepresentation ()
void setValueFromPersistentRepresentation (final String a_representation) throws UnsupportedRepresentationException
Public Attributes
int nodeIndex
Static Public Attributes
static final double DELTA = 0.0000001
static final Class BooleanClass = Boolean.class
static final Class IntegerClass = Integer.class
static final Class LongClass = Long.class
static final Class FloatClass = Float.class
static final Class DoubleClass = Double.class
static final Class VoidClass = Void.class
static final Class CharacterClass = Character.class
Protected Member Functions
void init ()
void setArity (int a_arity)
void setArityMin (int a_arityMin)
void setArityMax (int a_arityMax)
int getArityMin ()
int getArityMax ()
Object getInternalValue ()
void check (ProgramChromosome a_program)
void check (ProgramChromosome a_program, int a_index)
CommandGene.COMMAND_TYPE getCommandType ()
String getPersistentRepresentationExt ()
void setValueFromString (int a_index, String a_value)
Private Attributes
GPConfiguration m_configuration
boolean m_noValidation
Class m_returnType
int m_arity
int m_arityMin
int m_arityMax
boolean m_integerType
boolean m_floatType
double m_energy
Object m_applicationData
boolean m_compareAppData
int m_subReturnType
int[] m_subChildTypes
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.40 $`
Detailed Description
Abstract base class for all GP commands.
A CommandGene represents a node within a GP program. A node either is a terminal (like a constant), or a function (having input parameters).
A CommandGene can hold additional CommandGene's, it acts sort of like a
Composite (also see CompositeGene for a comparable concept, although for a GA).
Author
Klaus Meffert
Since
3.0
Definition at line 31 of file CommandGene.java.
Constructor & Destructor Documentation
org.jgap.gp.CommandGene.CommandGene () throws Exception [inline]
Default constructor, only for dynamic instantiation.
Exceptions
Exception
Author
Klaus Meffert
Since
3.3.4
Definition at line 153 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.compareTo(), and org.jgap.gp.CommandGene.equals().
org.jgap.gp.CommandGene.CommandGene (final GPConfiguration a_conf, final int a_arity, final Class a_returnType) throws InvalidConfigurationException [inline]
Parameters
a_conf the configuration to use
a_arity the number of children of the node
a_returnType type of the return value of the node
Exceptions
InvalidConfigurationException
Definition at line 164 of file CommandGene.java.
References org.jgap.gp.CommandGene.DoubleClass, org.jgap.gp.CommandGene.FloatClass, org.jgap.gp.CommandGene.init(), org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.CommandGene.LongClass, org.jgap.gp.CommandGene.m_arity, org.jgap.gp.CommandGene.m_configuration, org.jgap.gp.CommandGene.m_floatType, org.jgap.gp.CommandGene.m_integerType, and org.jgap.gp.CommandGene.m_returnType.
org.jgap.gp.CommandGene.CommandGene (final GPConfiguration a_conf, final int a_arity, final Class a_returnType, final int a_subReturnType, final int[] a_childSubTypes) throws InvalidConfigurationException [inline]
Allows specifying a sub return type and sub child types.
Parameters
a_conf the configuration to use
a_arity the number of children of the node
a_returnType type of the return value of the node
a_subReturnType sub type of the return type, optional usage
a_childSubTypes sub types of the childs, optional usage
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.2
Definition at line 201 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_subChildTypes, and org.jgap.gp.CommandGene.m_subReturnType.
org.jgap.gp.CommandGene.CommandGene (final GPConfiguration a_conf, final int a_arity, final Class a_returnType, final int a_subReturnType) throws InvalidConfigurationException [inline]
Allows specifying a sub return type.
Parameters
a_conf the configuration to use
a_arity the number of children of the node
a_returnType type of the return value of the node
a_subReturnType sub type of the return type, optional usage
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.2
Definition at line 245 of file CommandGene.java.
org.jgap.gp.CommandGene.CommandGene (final GPConfiguration a_conf, final int a_arity, final Class a_returnType, final int a_subReturnType, final int a_childSubType) throws InvalidConfigurationException [inline]
Command with one child: Allows specifying a sub return type and a sub child type. Convenience version of the called constructor.
Parameters
a_conf the configuration to use
a_arity the number of children of the node
a_returnType type of the return value of the node
a_subReturnType sub type of the return type, optional usage
a_childSubType sub type of a child, optional usage
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.2
Definition at line 265 of file CommandGene.java.
Member Function Documentation
void org.jgap.gp.CommandGene.check (ProgramChromosome a_program) [inline], [protected]
Definition at line 700 of file CommandGene.java.
References org.jgap.gp.CommandGene.isValid(), and org.jgap.gp.CommandGene.m_noValidation.
Referenced by examples.gp.tictactoe.IsOwnColor.execute_boolean(), org.jgap.gp.function.IfElse.execute_boolean(), org.jgap.gp.function.ADF.execute_boolean(), org.jgap.gp.function.Pop.execute_double(), org.jgap.gp.function.Push.execute_double(), org.jgap.gp.function.ReadTerminal.execute_double(), org.jgap.gp.function.ReadTerminalIndexed.execute_double(), org.jgap.gp.function.ADF.execute_double(), org.jgap.gp.function.SubProgram.execute_double(), org.jgap.gp.function.Pop.execute_float(), org.jgap.gp.function.Push.execute_float(), org.jgap.gp.function.ReadTerminal.execute_float(), org.jgap.gp.function.ADF.execute_float(), org.jgap.gp.function.ReadTerminalIndexed.execute_float(), org.jgap.gp.function.SubProgram.execute_float(), examples.gp.tictactoe.ReadBoard.execute_int(), org.jgap.gp.function.Pop.execute_int(), org.jgap.gp.function.ReadTerminalIndexed.execute_int(), org.jgap.gp.function.ReadTerminal.execute_int(), org.jgap.gp.function.Push.execute_int(), org.jgap.gp.function.IfElse.execute_int(), org.jgap.gp.function.ADF.execute_int(), examples.gp.tictactoe.IfColor.execute_int(), org.jgap.gp.function.SubProgram.execute_int(), org.jgap.gp.function.Pop.execute_long(), org.jgap.gp.function.Push.execute_long(), org.jgap.gp.function.ReadTerminal.execute_long(), org.jgap.gp.function.ReadTerminalIndexed.execute_long(), org.jgap.gp.function.SubProgram.execute_long(), org.jgap.gp.function.Pop.execute_object(), org.jgap.gp.function.Push.execute_object(), org.jgap.gp.function.ReadTerminal.execute_object(), org.jgap.gp.function.ReadTerminalIndexed.execute_object(), org.jgap.gp.function.ADF.execute_object(), org.jgap.gp.function.SubProgram.execute_object(), org.jgap.gp.function.ForXLoop.execute_void(), org.jgap.gp.function.Push.execute_void(), examples.gp.tictactoe.CountStones.execute_void(), examples.gp.tictactoe.IfIsOccupied.execute_void(), examples.gp.tictactoe.IfIsFree.execute_void(), examples.gp.paintedDesert.IfLessThanZero.execute_void(), examples.gp.tictactoe.TransferBoardToMemory.execute_void(), examples.gp.paintedDesert.IfLessThanOrEqual.execute_void(), org.jgap.gp.function.ExchangeMemory.execute_void(), org.jgap.gp.function.TransferMemory.execute_void(), examples.gp.tictactoe.IfColor.execute_void(), examples.gp.tictactoe.EvaluateBoard.execute_void(), org.jgap.gp.function.IfElse.execute_void(), and org.jgap.gp.function.SubProgram.execute_void().
void org.jgap.gp.CommandGene.check (ProgramChromosome a_program, int a_index) [inline], [protected]
Definition at line 709 of file CommandGene.java.
References org.jgap.gp.CommandGene.isValid(), and org.jgap.gp.CommandGene.m_noValidation.
void org.jgap.gp.CommandGene.cleanup () [inline]
Definition at line 287 of file CommandGene.java.
int org.jgap.gp.CommandGene.compareTo (Object a_other) [inline]
The compareTo-method. Considers application data when the configuration asks for this.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.0
Todo
Todo do it more precisely
Definition at line 377 of file CommandGene.java.
References org.jgap.gp.CommandGene.CommandGene(), org.jgap.gp.CommandGene.m_applicationData, org.jgap.gp.CommandGene.m_compareAppData, org.jgap.gp.CommandGene.m_subChildTypes, org.jgap.gp.CommandGene.m_subReturnType, and org.jgap.gp.CommandGene.size().
void org.jgap.gp.CommandGene.dynamizeArity () [inline]
Adaptation of the arity so that it represents a value within the interval [m_arityMin, m_arityMax].
Override if necessary. See CommandDynamicArity for an implementation.
Author
Klaus Meffert
Since
3.4
Definition at line 332 of file CommandGene.java.
void org.jgap.gp.CommandGene.ensureUniqueness (ProgramChromosome a_program) [inline]
Ensures that the calling command is unique within the program. Call it on first place from the execute method.
Parameters
a_program the program to validate
Author
Klaus Meffert
Since
3.3
Definition at line 856 of file CommandGene.java.
void org.jgap.gp.CommandGene.ensureUniqueness (ProgramChromosome a_program, int a_maxCount) [inline]
Ensures that the calling command is unique within the program. Throws an exception if uniqueness is violated. Call it on first place from the execute method.
Parameters
a_program the program to validate
a_maxCount maximum number of allowed occurences
Author
Klaus Meffert
Since
3.4
Definition at line 875 of file CommandGene.java.
boolean org.jgap.gp.CommandGene.ensureUniqueness2 (ProgramChromosome a_program, int a_maxCount) [inline]
Ensures that the calling command is unique within the program. Returns false if uniqueness is violated. Call it on first place from the execute method.
Parameters
a_program the program to validate
a_maxCount maximum number of allowed occurences
Returns
false: uniqueness constraint violated
Author
Klaus Meffert
Since
3.4
Definition at line 898 of file CommandGene.java.
boolean org.jgap.gp.CommandGene.equals (Object a_other) [inline]
The equals-method. Considers application data when the configuration asks for this.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Klaus Meffert
Since
3.0
Definition at line 408 of file CommandGene.java.
References org.jgap.gp.CommandGene.CommandGene(), org.jgap.gp.CommandGene.m_applicationData, org.jgap.gp.CommandGene.m_compareAppData, org.jgap.gp.CommandGene.m_returnType, org.jgap.gp.CommandGene.m_subChildTypes, org.jgap.gp.CommandGene.m_subReturnType, and org.jgap.gp.CommandGene.size().
Referenced by org.jgap.gp.function.EqualsTest.testEquals_0(), org.jgap.gp.function.LesserThanTest.testEquals_0(), and org.jgap.gp.function.GreaterThanTest.testEquals_0().
Object org.jgap.gp.CommandGene.execute (ProgramChromosome c, int n, Object[] args) [inline]
Executes this node without knowing its return type.
Parameters
c the current Chromosome which is executing
n the index of the Function in the Chromosome's Function array which is executing
args the arguments to the current Chromosome which is executing
Returns
the object which wraps the return value of this node, or null if the return type is null or unknown
Exceptions
UnsupportedOperationException if the type of this node is not boolean
Author
Klaus Meffert
Since
3.0
Definition at line 448 of file CommandGene.java.
References org.jgap.gp.CommandGene.BooleanClass, org.jgap.gp.CommandGene.DoubleClass, org.jgap.gp.CommandGene.execute_boolean(), org.jgap.gp.CommandGene.execute_double(), org.jgap.gp.CommandGene.execute_float(), org.jgap.gp.CommandGene.execute_int(), org.jgap.gp.CommandGene.execute_long(), org.jgap.gp.CommandGene.execute_object(), org.jgap.gp.CommandGene.execute_void(), org.jgap.gp.CommandGene.FloatClass, org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.CommandGene.LongClass, org.jgap.gp.CommandGene.m_returnType, and org.jgap.gp.CommandGene.VoidClass.
boolean org.jgap.gp.CommandGene.execute_boolean (ProgramChromosome c, int n, Object[] args) [inline]
Executes this node as a boolean. Override to implement.
Parameters
c ignored here
n ignored here
args ignored here
Returns
nothing but exception
Exceptions
UnsupportedOperationException
Author
Klaus Meffert
Since
3.0
Definition at line 507 of file CommandGene.java.
References org.jgap.gp.CommandGene.getName().
Referenced by org.jgap.gp.CommandGene.execute().
double org.jgap.gp.CommandGene.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Executes this node as a double. Override to implement.
Parameters
c ignored here
n ignored here
args ignored here
Returns
nothing but exception
Exceptions
UnsupportedOperationException
Author
Klaus Meffert
Since
3.0
Definition at line 591 of file CommandGene.java.
References org.jgap.gp.CommandGene.getName().
Referenced by org.jgap.gp.CommandGene.execute().
float org.jgap.gp.CommandGene.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Executes this node as a float. Override to implement.
Parameters
c ignored here
n ignored here
args ignored here
Returns
nothing but exception
Exceptions
UnsupportedOperationException
Author
Klaus Meffert
Since
3.0
Definition at line 574 of file CommandGene.java.
References org.jgap.gp.CommandGene.getName().
Referenced by org.jgap.gp.CommandGene.execute().
int org.jgap.gp.CommandGene.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Executes this node as an integer. Override to implement.
Parameters
c ignored here
n ignored here
args ignored here
Returns
nothing but exception
Exceptions
UnsupportedOperationException
Author
Klaus Meffert
Since
3.0
Definition at line 540 of file CommandGene.java.
References org.jgap.gp.CommandGene.getName().
Referenced by org.jgap.gp.CommandGene.execute().
long org.jgap.gp.CommandGene.execute_long (ProgramChromosome c, int n, Object[] args) [inline]
Executes this node as a long. Override to implement.
Parameters
c ignored here
n ignored here
args ignored here
Returns
nothing but exception
Exceptions
UnsupportedOperationException
Author
Klaus Meffert
Since
3.0
Definition at line 557 of file CommandGene.java.
References org.jgap.gp.CommandGene.getName().
Referenced by org.jgap.gp.CommandGene.execute().
Object org.jgap.gp.CommandGene.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Executes this node as an object. Override to implement.
Parameters
c ignored here
n ignored here
args ignored here
Returns
nothing but exception
Exceptions
UnsupportedOperationException
Author
Klaus Meffert
Since
3.0
Definition at line 608 of file CommandGene.java.
References org.jgap.gp.CommandGene.getName().
Referenced by org.jgap.gp.CommandGene.execute().
void org.jgap.gp.CommandGene.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Executes this node, returning nothing. Override to implement.
Parameters
c ignored here
n ignored here
args ignored here
Exceptions
UnsupportedOperationException
Author
Klaus Meffert
Since
3.0
Definition at line 523 of file CommandGene.java.
References org.jgap.gp.CommandGene.getName().
Referenced by org.jgap.gp.CommandGene.execute().
Object org.jgap.gp.CommandGene.getAllele () [inline]
Definition at line 278 of file CommandGene.java.
Object org.jgap.gp.CommandGene.getApplicationData () [inline]
Retrieves the application-specific data that is attached to this Gene. Attaching application-specific data may be useful for some applications when it comes time to distinguish a Gene from another. JGAP ignores this data functionally.
Returns
the application-specific data previously attached to this Gene, or null if there is no data attached
Author
Klaus Meffert
Since
3.0
Definition at line 760 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_applicationData.
Referenced by examples.gp.anttrail.AntCommand.getMap(), and examples.gp.paintedDesert.AntCommand.getMap().
int org.jgap.gp.CommandGene.getArity (IGPProgram a_indvividual) [inline]
Arity of the command. Override if necessary. The arity is the number of children a node has.
Parameters
a_indvividual the invididual the command's arity may depend on (in most cases the arity will not depend on the individual)
Returns
arity of the command
Author
Klaus Meffert
Since
3.0
Definition at line 307 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_arity.
Referenced by org.jgap.gp.function.statistics.Mean.clone(), org.jgap.gp.function.Mean.clone(), org.jgap.gp.function.statistics.StandardDeviation.clone(), org.jgap.gp.function.statistics.Variance.clone(), org.jgap.gp.function.statistics.Skewness.clone(), org.jgap.gp.function.statistics.Kurtosis.clone(), org.jgap.gp.function.IfDyn.clone(), org.jgap.gp.function.ForLoop.clone(), org.jgap.gp.impl.ProgramChromosome.growOrFullNode(), org.jgap.gp.function.ForLoopTest.testClone_1(), org.jgap.gp.function.LesserThanTest.testClone_1(), org.jgap.gp.function.EqualsTest.testClone_1(), org.jgap.gp.function.GreaterThanTest.testClone_1(), org.jgap.gp.function.ForLoopTest.testClone_2(), and org.jgap.gp.CommandGeneTest.testSize_0().
int org.jgap.gp.CommandGene.getArityMax () [inline], [protected]
Definition at line 363 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_arityMax.
Referenced by org.jgap.gp.function.statistics.Mean.clone(), org.jgap.gp.function.Mean.clone(), org.jgap.gp.function.statistics.StandardDeviation.clone(), org.jgap.gp.function.statistics.Variance.clone(), org.jgap.gp.function.statistics.Skewness.clone(), org.jgap.gp.function.statistics.Kurtosis.clone(), org.jgap.gp.function.IfDyn.clone(), and org.jgap.gp.CommandDynamicArity.dynamizeArity().
int org.jgap.gp.CommandGene.getArityMin () [inline], [protected]
Definition at line 359 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_arityMin.
Referenced by org.jgap.gp.function.statistics.Mean.clone(), org.jgap.gp.function.Mean.clone(), org.jgap.gp.function.statistics.StandardDeviation.clone(), org.jgap.gp.function.statistics.Variance.clone(), org.jgap.gp.function.statistics.Skewness.clone(), org.jgap.gp.function.statistics.Kurtosis.clone(), org.jgap.gp.function.IfDyn.clone(), and org.jgap.gp.CommandDynamicArity.dynamizeArity().
Class org.jgap.gp.CommandGene.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Gets the type of node allowed from the given child number. Should be overridden in subclasses.
Parameters
a_ind the individual the child belongs to
a_chromNum the chromosome number
Returns
the type of node allowed for that child, or null of no child exists
Author
Klaus Meffert
Since
3.0
Definition at line 629 of file CommandGene.java.
References org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.CommandGene.m_arity.
Referenced by org.jgap.gp.impl.ProgramChromosome.growOrFullNode().
CommandGene.COMMAND_TYPE org.jgap.gp.CommandGene.getCommandType () [inline], [protected]
The type of the command this gene represents. Overwrite in sub classes. This is optional and allows fine-tuning of GP program creating. For example, you could have a function as a part of a desired GP program that only does some analysis stuff and not any execution. E.g. take a game like Noughts and Crosses (Tic Tac Toe). There, a first part could be analysing the current state of the board and a second part could cope with exploiting the analysis results to execute a command (like put stone onto board at specific position).
Returns
type of the command this gene represents
Author
Klaus Meffert
Since
3.4.3
Definition at line 920 of file CommandGene.java.
References org.jgap.gp.CommandGene.COMMAND_TYPE.COMMAND_TYPE_UNDEFINED.
double org.jgap.gp.CommandGene.getEnergy () [inline]
Returns
energy of the gene
Author
Klaus Meffert
Since
2.3
Definition at line 795 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_energy.
GPConfiguration org.jgap.gp.CommandGene.getGPConfiguration () [inline]
Returns
the configuration set
Author
Klaus Meffert
Since
3.0
Definition at line 728 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_configuration.
Referenced by examples.gp.anttrail.Left.applyMutation(), examples.gp.anttrail.Right.applyMutation(), org.jgap.gp.function.Add.applyMutation(), org.jgap.gp.function.Multiply.applyMutation(), org.jgap.gp.function.Or.applyMutation(), org.jgap.gp.function.Divide.applyMutation(), org.jgap.gp.function.Subtract.applyMutation(), org.jgap.gp.function.Xor.applyMutation(), examples.gp.paintedDesert.GO_W.applyMutation(), org.jgap.gp.function.And.applyMutation(), org.jgap.gp.terminal.False.applyMutation(), org.jgap.gp.terminal.True.applyMutation(), examples.gp.paintedDesert.GO_E.applyMutation(), examples.gp.paintedDesert.GO_S.applyMutation(), examples.gp.paintedDesert.GO_N.applyMutation(), examples.gp.anttrail.TurnToFood.applyMutation(), examples.gp.paintedDesert.Y.applyMutation(), examples.gp.paintedDesert.X.applyMutation(), examples.gp.anttrail.IfFoodAheadRight.applyMutation(), examples.gp.anttrail.IfFoodAheadLeft.applyMutation(), examples.gp.monalisa.core.commands.PolygonConstructor.applyMutation(), org.jgap.gp.terminal.Terminal.applyMutation(), org.jgap.gp.function.SubProgram.applyMutation(), org.jgap.gp.function.Add.clone(), org.jgap.gp.function.Multiply.clone(), org.jgap.gp.function.Divide.clone(), org.jgap.gp.function.Subtract.clone(), org.jgap.gp.terminal.True.clone(), org.jgap.gp.terminal.False.clone(), org.jgap.gp.function.statistics.Mean.clone(), org.jgap.gp.function.And.clone(), org.jgap.gp.function.Mean.clone(), org.jgap.gp.function.Not.clone(), examples.gp.tictactoe.IsOwnColor.clone(), examples.gp.monalisa.core.commands.ColorConstructor.clone(), org.jgap.gp.function.RandomGenerator.clone(), examples.gp.monalisa.core.commands.PointConstructor.clone(), org.jgap.gp.function.Round.clone(), org.jgap.gp.function.statistics.StandardDeviation.clone(), org.jgap.gp.function.Max.clone(), org.jgap.gp.function.Min.clone(), examples.gp.tictactoe.ReadBoard.clone(), org.jgap.gp.function.statistics.Variance.clone(), org.jgap.gp.function.Log.clone(), org.jgap.gp.function.ArcSine.clone(), org.jgap.gp.function.ArcCosine.clone(), org.jgap.gp.function.ArcTangent.clone(), org.jgap.gp.function.Tangent.clone(), org.jgap.gp.function.Xor.clone(), org.jgap.gp.function.Abs.clone(), org.jgap.gp.function.Ceil.clone(), org.jgap.gp.function.Floor.clone(), org.jgap.gp.function.statistics.Skewness.clone(), org.jgap.gp.function.Cosine.clone(), org.jgap.gp.function.Sine.clone(), org.jgap.gp.function.Or.clone(), examples.gp.monalisa.core.commands.DrawPolygon.clone(), org.jgap.gp.function.statistics.Kurtosis.clone(), org.jgap.gp.function.Exp.clone(), org.jgap.gp.function.IfDyn.clone(), examples.gp.tictactoe.TransferBoardToMemory.clone(), org.jgap.gp.function.Add3.clone(), org.jgap.gp.terminal.Constant.clone(), org.jgap.gp.function.Multiply3.clone(), org.jgap.gp.function.Add4.clone(), org.jgap.gp.function.Pow.clone(), org.jgap.gp.function.GreaterThan.clone(), org.jgap.gp.function.LesserThan.clone(), org.jgap.gp.function.Equals.clone(), examples.gp.tictactoe.PutStone1.clone(), examples.gp.tictactoe.PutStone.clone(), org.jgap.gp.function.Modulo.clone(), examples.gp.tictactoe.IfIsFree.clone(), org.jgap.gp.function.Pop.clone(), examples.gp.tictactoe.IfIsOccupied.clone(), org.jgap.gp.function.Tupel.clone(), examples.gp.tictactoe.IfColor.clone(), examples.gp.monalisa.core.commands.PolygonConstructor.clone(), org.jgap.gp.function.CharacterProvider.clone(), org.jgap.gp.function.ResetMatrix.clone(), examples.gp.tictactoe.CountStones.clone(), examples.gp.tictactoe.EvaluateBoard.clone(), org.jgap.gp.function.If.clone(), org.jgap.gp.function.AddAndStore.clone(), org.jgap.gp.function.Loop.clone(), org.jgap.gp.function.ForXLoop.clone(), org.jgap.gp.function.Switch.clone(), org.jgap.gp.function.TransferMemory.clone(), org.jgap.gp.function.Increment.clone(), org.jgap.gp.function.ExchangeMemory.clone(), org.jgap.gp.function.IncrementMemory.clone(), org.jgap.gp.function.IfElse.clone(), org.jgap.gp.function.Push.clone(), org.jgap.gp.function.ReadTerminal.clone(), org.jgap.gp.function.ReadTerminalIndexed.clone(), org.jgap.gp.function.SubProgram.clone(), org.jgap.gp.function.ForLoop.clone(), org.jgap.gp.terminal.Terminal.clone(), org.jgap.gp.CommandDynamicArity.dynamizeArity(), org.jgap.gp.function.Pop.execute_double(), org.jgap.gp.function.ReadTerminal.execute_double(), org.jgap.gp.function.ReadTerminalIndexed.execute_double(), org.jgap.gp.function.Pop.execute_float(), org.jgap.gp.function.ReadTerminal.execute_float(), org.jgap.gp.function.ReadTerminalIndexed.execute_float(), org.jgap.gp.function.Pop.execute_int(), org.jgap.gp.function.ReadTerminalIndexed.execute_int(), org.jgap.gp.function.ReadTerminal.execute_int(), org.jgap.gp.function.IncrementMemory.execute_int(), org.jgap.gp.function.Pop.execute_long(), org.jgap.gp.function.ReadTerminal.execute_long(), org.jgap.gp.function.ReadTerminalIndexed.execute_long(), org.jgap.gp.function.Pop.execute_object(), org.jgap.gp.function.ReadTerminal.execute_object(), org.jgap.gp.function.ReadTerminalIndexed.execute_object(), org.jgap.gp.function.AddAndStore.execute_void(), examples.gp.tictactoe.TransferBoardToMemory.execute_void(), org.jgap.gp.function.ResetMatrix.execute_void(), org.jgap.gp.function.TransferMemory.execute_void(), org.jgap.gp.function.ExchangeMemory.execute_void(), examples.gp.tictactoe.EvaluateBoard.execute_void(), org.jgap.gp.function.ForLoop.execute_void(), org.jgap.gp.function.ForLoop.init(), org.jgap.gp.function.Push.pushIt(), org.jgap.gp.function.ReadTerminalIndexed.ReadTerminalIndexed(), org.jgap.gp.terminal.Terminal.setRandomValue(), and examples.gp.tictactoe.CountStones.store().
Object org.jgap.gp.CommandGene.getInternalValue () [inline], [protected]
Definition at line 638 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.hashCode().
String org.jgap.gp.CommandGene.getName () [inline]
Definition at line 613 of file CommandGene.java.
References org.jgap.gp.CommandGene.toString().
Referenced by org.jgap.gp.CommandGene.execute_boolean(), org.jgap.gp.CommandGene.execute_double(), org.jgap.gp.CommandGene.execute_float(), org.jgap.gp.CommandGene.execute_int(), org.jgap.gp.CommandGene.execute_long(), org.jgap.gp.CommandGene.execute_object(), examples.gp.tictactoe.PutStone1.execute_void(), org.jgap.gp.CommandGene.execute_void(), examples.gp.anttrail.AntTreeBranchRenderer.getBranchColor(), examples.gp.anttrail.AntTreeNodeRenderer.getNodeColor(), and org.jgap.gp.CommandGene.getPersistentRepresentation().
String org.jgap.gp.CommandGene.getPersistentRepresentation () [inline]
Returns
the persistent representation of the chromosome, including all genes
Author
Klaus Meffert
Since
3.3
Definition at line 931 of file CommandGene.java.
References org.jgap.gp.CommandGene.getName(), org.jgap.gp.CommandGene.getPersistentRepresentationExt(), org.jgap.gp.CommandGene.m_arity, org.jgap.gp.CommandGene.m_returnType, org.jgap.gp.CommandGene.m_subChildTypes, and org.jgap.gp.CommandGene.m_subReturnType.
String org.jgap.gp.CommandGene.getPersistentRepresentationExt () [inline], [protected]
Override in your sub classes of CommandGene if you have to add additional information to be persisted.
Returns
additional infos
Author
Klaus Meffert
Since
3.3
Definition at line 958 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.getPersistentRepresentation().
Class org.jgap.gp.CommandGene.getReturnType () [inline]
Returns
the return type of this node
Author
Klaus Meffert
Since
3.0
Definition at line 479 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_returnType.
Referenced by org.jgap.gp.function.Add.applyMutation(), org.jgap.gp.function.Subtract.applyMutation(), org.jgap.gp.function.Divide.applyMutation(), org.jgap.gp.function.Multiply.applyMutation(), org.jgap.gp.terminal.False.applyMutation(), org.jgap.gp.terminal.True.applyMutation(), org.jgap.gp.terminal.Terminal.applyMutation(), org.jgap.gp.function.Add.clone(), org.jgap.gp.function.Subtract.clone(), org.jgap.gp.function.Divide.clone(), org.jgap.gp.function.Multiply.clone(), org.jgap.gp.terminal.True.clone(), org.jgap.gp.terminal.False.clone(), org.jgap.gp.function.statistics.Mean.clone(), org.jgap.gp.function.And.clone(), org.jgap.gp.function.Mean.clone(), org.jgap.gp.function.RandomGenerator.clone(), org.jgap.gp.function.Round.clone(), org.jgap.gp.function.statistics.StandardDeviation.clone(), org.jgap.gp.function.Max.clone(), org.jgap.gp.function.Min.clone(), org.jgap.gp.function.statistics.Variance.clone(), org.jgap.gp.function.ArcCosine.clone(), org.jgap.gp.function.ArcSine.clone(), org.jgap.gp.function.ArcTangent.clone(), org.jgap.gp.function.Log.clone(), org.jgap.gp.function.Tangent.clone(), org.jgap.gp.function.Abs.clone(), org.jgap.gp.function.Floor.clone(), org.jgap.gp.function.statistics.Skewness.clone(), org.jgap.gp.function.Ceil.clone(), org.jgap.gp.function.Sine.clone(), org.jgap.gp.function.Cosine.clone(), org.jgap.gp.function.statistics.Kurtosis.clone(), org.jgap.gp.function.Exp.clone(), org.jgap.gp.function.IfDyn.clone(), org.jgap.gp.function.Add3.clone(), org.jgap.gp.terminal.Constant.clone(), org.jgap.gp.function.Multiply3.clone(), org.jgap.gp.function.Add4.clone(), org.jgap.gp.function.Pow.clone(), org.jgap.gp.function.Modulo.clone(), org.jgap.gp.function.Pop.clone(), org.jgap.gp.function.Tupel.clone(), org.jgap.gp.function.CharacterProvider.clone(), org.jgap.gp.function.If.clone(), org.jgap.gp.function.Increment.clone(), org.jgap.gp.function.IncrementMemory.clone(), org.jgap.gp.function.ReadTerminal.clone(), org.jgap.gp.function.ReadTerminalIndexed.clone(), org.jgap.gp.terminal.Terminal.clone(), org.jgap.gp.terminal.Terminal.execute_object(), org.jgap.gp.function.If.getChildType(), org.jgap.gp.CommandGene.getChildType(), org.jgap.gp.terminal.Terminal.setRandomValue(), org.jgap.gp.terminal.Terminal.toString(), and org.jgap.gp.impl.GPGenotype.verifyDepthsForNodes().
int org.jgap.gp.CommandGene.getSubChildType (int a_childNum) [inline]
Parameters
a_childNum the index of the child
Returns
the sub type of the given child
Author
Klaus Meffert
Since
3.2
Definition at line 828 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_subChildTypes.
Referenced by examples.gp.tictactoe.PutStone1.clone(), org.jgap.gp.function.Loop.clone(), org.jgap.gp.function.Push.clone(), org.jgap.gp.function.ForLoop.clone(), and org.jgap.gp.impl.GPGenotype.verifyDepthsForNodes().
int [] org.jgap.gp.CommandGene.getSubChildTypes () [inline]
Returns
sub type for all children
Author
Klaus Meffert
Since
3.2
Definition at line 843 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_subChildTypes.
Referenced by org.jgap.gp.function.SubProgram.applyMutation(), examples.gp.tictactoe.ReadBoard.clone(), org.jgap.gp.function.GreaterThan.clone(), org.jgap.gp.function.LesserThan.clone(), org.jgap.gp.function.Equals.clone(), examples.gp.tictactoe.PutStone.clone(), examples.gp.tictactoe.IfIsFree.clone(), examples.gp.tictactoe.IfIsOccupied.clone(), examples.gp.tictactoe.IfColor.clone(), org.jgap.gp.function.IfElse.clone(), org.jgap.gp.function.SubProgram.clone(), and org.jgap.gp.impl.GPGenotype.verifyChildNodes().
int org.jgap.gp.CommandGene.getSubReturnType () [inline]
Returns
sub return type
Author
Klaus Meffert
Since
3.2
Definition at line 817 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_subReturnType.
Referenced by org.jgap.gp.function.SubProgram.applyMutation(), examples.gp.tictactoe.IsOwnColor.clone(), examples.gp.tictactoe.ReadBoard.clone(), examples.gp.tictactoe.TransferBoardToMemory.clone(), org.jgap.gp.terminal.Constant.clone(), org.jgap.gp.function.GreaterThan.clone(), org.jgap.gp.function.LesserThan.clone(), org.jgap.gp.function.Equals.clone(), examples.gp.tictactoe.PutStone1.clone(), examples.gp.tictactoe.PutStone.clone(), examples.gp.tictactoe.IfIsFree.clone(), examples.gp.tictactoe.IfIsOccupied.clone(), org.jgap.gp.function.Pop.clone(), examples.gp.tictactoe.IfColor.clone(), org.jgap.gp.function.CharacterProvider.clone(), examples.gp.tictactoe.CountStones.clone(), examples.gp.tictactoe.EvaluateBoard.clone(), org.jgap.gp.function.Loop.clone(), org.jgap.gp.function.IfElse.clone(), org.jgap.gp.function.Push.clone(), org.jgap.gp.function.ReadTerminal.clone(), org.jgap.gp.function.ReadTerminalIndexed.clone(), org.jgap.gp.function.SubProgram.clone(), org.jgap.gp.function.ForLoop.clone(), org.jgap.gp.terminal.Terminal.clone(), and org.jgap.gp.impl.GPGenotype.verifyDepthsForNodes().
int org.jgap.gp.CommandGene.hashCode () [inline]
Retrieves the hash code value for a CommandGene. Override if another hashCode() implementation is necessary or more appropriate than this default implementation.
Returns
this Gene's hash code
Author
Klaus Meffert
Since
3.0
Definition at line 652 of file CommandGene.java.
References org.jgap.gp.CommandGene.getInternalValue().
void org.jgap.gp.CommandGene.init () [inline], [protected]
Initializations, called from each Constructor.
Definition at line 142 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.CommandGene().
boolean org.jgap.gp.CommandGene.isAffectGlobalState () [inline]
Returns
true: command affects global state (i.e. stack or memory)
Author
Klaus Meffert
Since
3.0
Definition at line 678 of file CommandGene.java.
boolean org.jgap.gp.CommandGene.isCompareApplicationData () [inline]
Definition at line 785 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_compareAppData.
boolean org.jgap.gp.CommandGene.isFloatType () [inline]
Definition at line 668 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_floatType.
boolean org.jgap.gp.CommandGene.isIntegerType () [inline]
Definition at line 664 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_integerType.
boolean org.jgap.gp.CommandGene.isValid (ProgramChromosome a_program) [inline]
Subclasses capable of validating programs should overwrite this method. See class Push as a sample.
Parameters
a_program the ProgramChromosome to validate
Returns
true: a_program is (superficially) valid with the current Command
Author
Klaus Meffert
Since
3.0
Definition at line 692 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.check().
boolean org.jgap.gp.CommandGene.isValid (ProgramChromosome a_program, int a_index) [inline]
Definition at line 696 of file CommandGene.java.
void org.jgap.gp.CommandGene.setAllele (Object a_newValue) [inline]
Definition at line 273 of file CommandGene.java.
void org.jgap.gp.CommandGene.setApplicationData (final Object a_newData) [inline]
This sets the application-specific data that is attached to this Gene. Attaching application-specific data may be useful for some applications when it comes time to distinguish a Gene from another. JGAP ignores this data functionally.
Parameters
a_newData the new application-specific data to attach to this Gene
Author
Klaus Meffert
Since
3.0
Definition at line 744 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_applicationData.
void org.jgap.gp.CommandGene.setArity (int a_arity) [inline], [protected]
Should only be used by class CommandDynamicArity or a similar class.
Parameters
a_arity the arity to set, overrides the current arity.
Author
Klaus Meffert
Since
3.4
Definition at line 319 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_arity.
Referenced by org.jgap.gp.CommandDynamicArity.dynamizeArity().
void org.jgap.gp.CommandGene.setArityMax (int a_arityMax) [inline], [protected]
Should only be used by class CommandDynamicArity or a similar class.
Parameters
a_arityMax the maximal arity possible
Author
Klaus Meffert
Since
3.4
Definition at line 355 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_arityMax.
Referenced by org.jgap.gp.CommandDynamicArity.CommandDynamicArity().
void org.jgap.gp.CommandGene.setArityMin (int a_arityMin) [inline], [protected]
Should only be used by class CommandDynamicArity or a similar class.
Parameters
a_arityMin the minimal arity possible
Author
Klaus Meffert
Since
3.4
Definition at line 344 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_arityMin.
Referenced by org.jgap.gp.CommandDynamicArity.CommandDynamicArity().
void org.jgap.gp.CommandGene.setCompareApplicationData (final boolean a_doCompare) [inline]
Should we also consider the application data when comparing? Default is `false` as `true` means a Gene is losing its identity when application data is set differently!
Parameters
a_doCompare true: consider application data in method compareTo and equals
Author
Klaus Meffert
Since
2.4
Definition at line 775 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_compareAppData.
void org.jgap.gp.CommandGene.setEnergy (final double a_energy) [inline]
Sets the energy of the gene.
Parameters
a_energy the energy to set
Author
Klaus Meffert
Since
2.3
Definition at line 807 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_energy.
void org.jgap.gp.CommandGene.setNoValidation (boolean a_noValidation) [inline]
Definition at line 718 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_noValidation.
void org.jgap.gp.CommandGene.setReturnType (Class a_type) [inline]
Sets the return type of this node.
Parameters
a_type the type to set the return type to
Author
Klaus Meffert
Since
3.0
Definition at line 491 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_returnType.
void org.jgap.gp.CommandGene.setToRandomValue (RandomGenerator a_numberGenerator) [inline]
Definition at line 282 of file CommandGene.java.
void org.jgap.gp.CommandGene.setValueFromPersistentRepresentation (final String a_representation) throws UnsupportedRepresentationException [inline]
Parameters
a_representation String
Exceptions
UnsupportedRepresentationException
Author
Klaus Meffert
Since
3.3
Todo
Todo finish
Definition at line 970 of file CommandGene.java.
void org.jgap.gp.CommandGene.setValueFromString (int a_index, String a_value) [inline], [protected]
Override in your sub classes of CommandGene if you have to add additional information to be persisted.
Parameters
a_index index of the parameter in the range 0..n-1 (n=number of parameters)
a_value string value of the parameter
Author
Klaus Meffert
Since
3.3
Definition at line 1043 of file CommandGene.java.
int org.jgap.gp.CommandGene.size () [inline]
Definition at line 292 of file CommandGene.java.
References org.jgap.gp.CommandGene.m_arity.
Referenced by org.jgap.gp.function.SubProgram.applyMutation(), org.jgap.gp.CommandGene.compareTo(), org.jgap.gp.function.ForXLoop.equals(), org.jgap.gp.CommandGene.equals(), org.jgap.gp.function.IfDyn.execute_boolean(), org.jgap.gp.function.statistics.Mean.execute_double(), org.jgap.gp.function.Mean.execute_double(), org.jgap.gp.function.statistics.Skewness.execute_double(), org.jgap.gp.function.statistics.StandardDeviation.execute_double(), org.jgap.gp.function.statistics.Variance.execute_double(), org.jgap.gp.function.statistics.Kurtosis.execute_double(), org.jgap.gp.function.statistics.Skewness.execute_float(), org.jgap.gp.function.statistics.StandardDeviation.execute_float(), org.jgap.gp.function.statistics.Variance.execute_float(), org.jgap.gp.function.statistics.Kurtosis.execute_float(), org.jgap.gp.function.Tupel.execute_object(), org.jgap.gp.function.ForLoop.execute_object(), org.jgap.gp.function.IfDyn.execute_void(), org.jgap.gp.CommandGeneTest.testSize_0(), org.jgap.gp.function.statistics.StandardDeviation.toString(), org.jgap.gp.function.IfDyn.toString(), org.jgap.gp.function.statistics.Variance.toString(), org.jgap.gp.function.statistics.Kurtosis.toString(), org.jgap.gp.function.statistics.Mean.toString(), org.jgap.gp.function.Mean.toString(), org.jgap.gp.function.statistics.Skewness.toString(), and org.jgap.gp.function.ADF.toString().
abstract String org.jgap.gp.CommandGene.toString () [pure virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implemented in org.jgap.gp.terminal.Terminal, examples.gp.anttrail.TurnToFood, org.jgap.gp.function.SubProgram, org.jgap.gp.function.ForLoop, examples.gp.anttrail.IfFoodAheadLeft, examples.gp.anttrail.IfFoodAheadRight, examples.gp.anttrail.IfFoodAheadElse, examples.gp.anttrail.Move, org.jgap.gp.function.WriteToMatrix, org.jgap.gp.function.AddAndStoreTerminal, org.jgap.gp.function.IncrementMemory, org.jgap.gp.function.CountMatrix, examples.gp.monalisa.core.commands.PolygonConstructor, org.jgap.gp.function.ReplaceInMatrix, org.jgap.gp.function.Increment, org.jgap.gp.function.StoreTerminal, org.jgap.gp.function.ADF, examples.gp.tictactoe.EvaluateBoard, org.jgap.gp.function.And, examples.gp.paintedDesert.X, examples.gp.monalisa.core.commands.DrawPolygon, examples.gp.tictactoe.IfColor, org.jgap.gp.function.StoreTerminalIndexed, examples.gp.paintedDesert.Y, org.jgap.gp.function.ReadFromMatrix, org.jgap.gp.terminal.False, org.jgap.gp.terminal.True, org.jgap.gp.function.ResetMatrix, org.jgap.gp.function.statistics.Skewness, examples.gp.anttrail.Left, examples.gp.anttrail.Right, org.jgap.gp.function.ExchangeMemory, org.jgap.gp.function.TransferMemory, examples.gp.paintedDesert.GO_E, examples.gp.paintedDesert.GO_N, examples.gp.paintedDesert.GO_S, org.jgap.gp.function.Loop, examples.gp.paintedDesert.LoopUntil, org.jgap.gp.function.Add, org.jgap.gp.function.Divide, org.jgap.gp.function.Multiply, org.jgap.gp.function.Subtract, examples.gp.paintedDesert.GO_W, examples.gp.monalisa.core.commands.PointConstructor, examples.gp.paintedDesert.MoveRandom, org.jgap.gp.function.CharacterProvider, examples.gp.monalisa.core.commands.ColorConstructor, examples.gp.paintedDesert.Carrying, examples.gp.paintedDesert.Drop, examples.gp.paintedDesert.IfLessThanOrEqual, org.jgap.gp.function.If, org.jgap.gp.function.ReadTerminal, org.jgap.gp.terminal.Variable, examples.gp.paintedDesert.IfDrop, examples.gp.paintedDesert.MayPickUp, org.jgap.gp.function.ReadTerminalIndexed, examples.gp.paintedDesert.IfLessThanZero, examples.gp.paintedDesert.MayDropSand, examples.gp.paintedDesert.SandColor, examples.gp.paintedDesert.Pickup, examples.gp.paintedDesert.SandAtLocation, examples.gp.paintedDesert.SandBelongsHere, examples.gp.tictactoe.IfIsFree, examples.gp.tictactoe.IfIsOccupied, examples.gp.tictactoe.PutStone, examples.gp.tictactoe.PutStone1, org.jgap.gp.function.Mean, org.jgap.gp.function.Tupel, org.jgap.gp.function.Xor, org.jgap.gp.function.AddAndStore, org.jgap.gp.function.Or, org.jgap.gp.function.statistics.Mean, examples.gp.tictactoe.CountStones, org.jgap.gp.function.LesserThan, org.jgap.gp.terminal.NOP, org.jgap.gp.function.Equals, org.jgap.gp.function.GreaterThan, org.jgap.gp.function.IfElse, org.jgap.gp.function.Push, org.jgap.gp.terminal.Constant, examples.gp.tictactoe.TransferBoardToMemory, org.jgap.gp.function.statistics.Kurtosis, org.jgap.gp.function.Switch, examples.gp.tictactoe.IsOwnColor, org.jgap.gp.function.Pop, org.jgap.gp.function.ForXLoop, org.jgap.gp.function.statistics.Variance, examples.gp.tictactoe.ReadBoard, org.jgap.gp.function.IfDyn, org.jgap.gp.terminal.Argument, org.jgap.gp.function.Ceil, org.jgap.gp.function.Floor, org.jgap.gp.function.Modulo, org.jgap.gp.function.RandomGenerator, org.jgap.gp.function.Abs, org.jgap.gp.function.Add3, org.jgap.gp.function.Add4, org.jgap.gp.function.ArcCosine, org.jgap.gp.function.ArcSine, org.jgap.gp.function.ArcTangent, org.jgap.gp.function.Cosine, org.jgap.gp.function.Exp, org.jgap.gp.function.Log, org.jgap.gp.function.Max, org.jgap.gp.function.Min, org.jgap.gp.function.Multiply3, org.jgap.gp.function.Not, org.jgap.gp.function.Pow, org.jgap.gp.function.Round, org.jgap.gp.function.Sine, org.jgap.gp.function.statistics.StandardDeviation, and org.jgap.gp.function.Tangent.
Referenced by org.jgap.gp.CommandGene.getName(), org.jgap.gp.impl.GPGenotype.getProgramString(), and org.jgap.gp.CommandGeneTest.testToString_0().
Member Data Documentation
final Class org.jgap.gp.CommandGene.BooleanClass = Boolean.class [static]
Definition at line 49 of file CommandGene.java.
Referenced by org.jgap.gp.function.And.And(), examples.gp.SimpleExample.create(), examples.gp.KarubProblem.create(), examples.gp.tictactoe.TicTacToeMain.create(), examples.gp.island.IslandGPThread.create(), examples.gp.symbolicRegression.SymbolicRegression.create(), org.jgap.gp.function.Equals.Equals(), org.jgap.gp.CommandGene.execute(), org.jgap.gp.function.Equals.execute_boolean(), org.jgap.gp.function.GreaterThan.execute_boolean(), org.jgap.gp.function.IfElse.execute_boolean(), org.jgap.gp.function.LesserThan.execute_boolean(), org.jgap.gp.function.If.execute_int(), org.jgap.gp.function.IfElse.execute_int(), examples.gp.paintedDesert.IfLessThanZero.execute_void(), examples.gp.paintedDesert.IfLessThanOrEqual.execute_void(), org.jgap.gp.function.IfElse.execute_void(), org.jgap.gp.terminal.False.False(), org.jgap.gp.function.Switch.getChildType(), org.jgap.gp.function.GreaterThan.GreaterThan(), examples.gp.tictactoe.IsOwnColor.IsOwnColor(), org.jgap.gp.function.LesserThan.LesserThan(), examples.gp.paintedDesert.LoopUntil.LoopUntil(), examples.gp.paintedDesert.MayDropSand.MayDropSand(), examples.gp.paintedDesert.MayPickUp.MayPickUp(), org.jgap.gp.function.Not.Not(), org.jgap.gp.function.Or.Or(), examples.gp.paintedDesert.SandAtLocation.SandAtLocation(), examples.gp.paintedDesert.SandBelongsHere.SandBelongsHere(), org.jgap.gp.terminal.True.True(), and org.jgap.gp.function.Xor.Xor().
final Class org.jgap.gp.CommandGene.CharacterClass = Character.class [static]
Definition at line 61 of file CommandGene.java.
Referenced by org.jgap.gp.function.ReadFromMatrix.ReadFromMatrix().
final String org.jgap.gp.CommandGene.CVS_REVISION = `$Revision: 1.40 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 34 of file CommandGene.java.
final double org.jgap.gp.CommandGene.DELTA = 0.0000001 [static]
Delta, useful for comparing doubles and floats.
Definition at line 47 of file CommandGene.java.
Referenced by org.jgap.gp.terminal.Terminal.applyMutation(), org.jgap.gp.function.Equals.execute_boolean(), org.jgap.gp.function.Modulo.execute_double(), and org.jgap.gp.function.Modulo.execute_float().
final Class org.jgap.gp.CommandGene.DoubleClass = Double.class [static]
Definition at line 57 of file CommandGene.java.
Referenced by examples.gp.symbolicRegression.AndD.AndD(), org.jgap.gp.terminal.Terminal.applyMutation(), org.jgap.gp.CommandGene.CommandGene(), examples.gp.symbolicRegression.SymbolicRegression.create(), org.jgap.gp.CommandGene.execute(), org.jgap.gp.function.IfElse.execute_boolean(), org.jgap.gp.function.Equals.execute_boolean(), org.jgap.gp.function.GreaterThan.execute_boolean(), org.jgap.gp.function.LesserThan.execute_boolean(), org.jgap.gp.function.If.execute_int(), org.jgap.gp.function.IfElse.execute_int(), org.jgap.gp.terminal.Terminal.execute_object(), org.jgap.gp.function.ForXLoop.execute_void(), org.jgap.gp.function.AddAndStore.execute_void(), examples.gp.paintedDesert.IfLessThanZero.execute_void(), examples.gp.paintedDesert.IfLessThanOrEqual.execute_void(), org.jgap.gp.function.StoreTerminalIndexed.execute_void(), org.jgap.gp.function.StoreTerminal.execute_void(), org.jgap.gp.function.AddAndStoreTerminal.execute_void(), org.jgap.gp.function.IfElse.execute_void(), org.jgap.gp.function.ForLoop.execute_void(), examples.gp.symbolicRegression.NotD.NotD(), examples.gp.symbolicRegression.OrD.OrD(), org.jgap.gp.terminal.Terminal.setRandomValue(), org.jgap.gp.terminal.Terminal.toString(), and examples.gp.symbolicRegression.XorD.XorD().
final Class org.jgap.gp.CommandGene.FloatClass = Float.class [static]
Definition at line 55 of file CommandGene.java.
Referenced by org.jgap.gp.terminal.Terminal.applyMutation(), org.jgap.gp.CommandGene.CommandGene(), examples.gp.monalisa.core.DrawingProblem.create(), examples.gp.MathProblem.create(), examples.grid.mathProblemDistributed.ClientEvolveStrategy.createVariable(), org.jgap.gp.CommandGene.execute(), org.jgap.gp.function.IfElse.execute_boolean(), org.jgap.gp.function.Equals.execute_boolean(), org.jgap.gp.function.GreaterThan.execute_boolean(), org.jgap.gp.function.LesserThan.execute_boolean(), org.jgap.gp.function.If.execute_int(), org.jgap.gp.function.IfElse.execute_int(), org.jgap.gp.terminal.Terminal.execute_object(), org.jgap.gp.function.ForXLoop.execute_void(), org.jgap.gp.function.AddAndStore.execute_void(), examples.gp.paintedDesert.IfLessThanZero.execute_void(), examples.gp.paintedDesert.IfLessThanOrEqual.execute_void(), org.jgap.gp.function.StoreTerminalIndexed.execute_void(), org.jgap.gp.function.StoreTerminal.execute_void(), org.jgap.gp.function.AddAndStoreTerminal.execute_void(), org.jgap.gp.function.IfElse.execute_void(), org.jgap.gp.function.ForLoop.execute_void(), examples.gp.monalisa.core.commands.ColorConstructor.getChildType(), examples.grid.mathProblemDistributed.ClientEvolveStrategy.getNodeSets(), org.jgap.gp.terminal.Terminal.setRandomValue(), org.jgap.gp.function.Switch.Switch(), and org.jgap.gp.terminal.Terminal.toString().
final Class org.jgap.gp.CommandGene.IntegerClass = Integer.class [static]
Definition at line 51 of file CommandGene.java.
Referenced by org.jgap.gp.terminal.Terminal.applyMutation(), examples.gp.paintedDesert.Carrying.Carrying(), org.jgap.gp.CommandGene.CommandGene(), org.jgap.gp.function.CountMatrix.CountMatrix(), examples.gp.SimpleExample.create(), examples.gp.monalisa.core.DrawingProblem.create(), examples.gp.KarubProblem.create(), examples.gp.Fibonacci.create(), examples.gp.tictactoe.TicTacToeMain.create(), examples.gp.island.IslandGPThread.create(), examples.gp.paintedDesert.PaintedDesertProblem.create(), examples.gp.anttrail.AntTrailProblem.create(), examples.gp.symbolicRegression.SymbolicRegression.create(), examples.gp.paintedDesert.Drop.Drop(), examples.gp.tictactoe.EvaluateBoard.EvaluateBoard(), org.jgap.gp.CommandGene.execute(), org.jgap.gp.function.Equals.execute_boolean(), org.jgap.gp.function.GreaterThan.execute_boolean(), org.jgap.gp.function.IfElse.execute_boolean(), org.jgap.gp.function.LesserThan.execute_boolean(), org.jgap.gp.function.If.execute_int(), org.jgap.gp.function.IfElse.execute_int(), org.jgap.gp.terminal.Terminal.execute_object(), org.jgap.gp.function.ForXLoop.execute_void(), org.jgap.gp.function.AddAndStore.execute_void(), examples.gp.tictactoe.IfIsFree.execute_void(), examples.gp.tictactoe.IfIsOccupied.execute_void(), examples.gp.paintedDesert.IfLessThanZero.execute_void(), examples.gp.paintedDesert.IfLessThanOrEqual.execute_void(), org.jgap.gp.function.StoreTerminalIndexed.execute_void(), examples.gp.tictactoe.IfColor.execute_void(), org.jgap.gp.function.StoreTerminal.execute_void(), org.jgap.gp.function.AddAndStoreTerminal.execute_void(), org.jgap.gp.function.IfElse.execute_void(), org.jgap.gp.function.ForLoop.execute_void(), examples.gp.monalisa.core.commands.PointConstructor.getChildType(), examples.gp.paintedDesert.X.getChildType(), examples.gp.tictactoe.IsOwnColor.getChildType(), examples.gp.tictactoe.PutStone1.getChildType(), examples.gp.tictactoe.PutStone.getChildType(), org.jgap.gp.function.ReadFromMatrix.getChildType(), org.jgap.gp.function.ReplaceInMatrix.getChildType(), org.jgap.gp.function.CountMatrix.getChildType(), examples.gp.paintedDesert.Pickup.Pickup(), examples.gp.tictactoe.ReadBoard.ReadBoard(), org.jgap.gp.function.ReplaceInMatrix.ReplaceInMatrix(), examples.gp.paintedDesert.SandColor.SandColor(), org.jgap.gp.terminal.Terminal.setRandomValue(), org.jgap.gp.GPTestCase.setUp(), org.jgap.gp.terminal.Terminal.Terminal(), org.jgap.gp.impl.GPConfigurationTest.testClone_0(), org.jgap.gp.impl.GPConfigurationTest.testClone_1(), org.jgap.gp.impl.GPGenotypeTest.testConfigurationInstance_0(), org.jgap.gp.impl.GPPopulationTest.testCreate_1(), org.jgap.gp.impl.GPPopulationTest.testCreate_2(), org.jgap.gp.impl.GPPopulationTest.testCreate_3(), org.jgap.gp.impl.GPProgramTest.testExecute_0(), org.jgap.gp.impl.ProgramChromosomeTest.testGetDepth_0(), org.jgap.gp.impl.ProgramChromosomeTest.testGetDepth_1(), org.jgap.gp.impl.ProgramChromosomeTest.testGetDepth_2(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_0(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_1(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_2(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_3(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_4(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_4_2(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_4_3(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_5(), org.jgap.gp.impl.GPGenotypeTest.testRandomInitialize_0(), org.jgap.gp.impl.ProgramChromosomeTest.testRedepth_0(), org.jgap.gp.impl.GPGenotypeTest.testReferenceProblem_0(), org.jgap.gp.impl.GPProgramTest.testSerialize_0(), org.jgap.gp.impl.ProgramChromosomeTest.testSerialize_0(), org.jgap.gp.impl.ProgramChromosomeTest.testToString_0(), org.jgap.gp.impl.ProgramChromosomeTest.testToString_1(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_0(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_1(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_2(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_3(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_4(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_5(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_6(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_7(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_8(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_9(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_A(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_B(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_C(), org.jgap.gp.terminal.Terminal.toString(), examples.gp.paintedDesert.X.X(), and examples.gp.paintedDesert.Y.Y().
final Class org.jgap.gp.CommandGene.LongClass = Long.class [static]
Definition at line 53 of file CommandGene.java.
Referenced by org.jgap.gp.terminal.Terminal.applyMutation(), org.jgap.gp.CommandGene.CommandGene(), org.jgap.gp.CommandGene.execute(), org.jgap.gp.function.Equals.execute_boolean(), org.jgap.gp.function.GreaterThan.execute_boolean(), org.jgap.gp.function.IfElse.execute_boolean(), org.jgap.gp.function.LesserThan.execute_boolean(), org.jgap.gp.function.If.execute_int(), org.jgap.gp.function.IfElse.execute_int(), org.jgap.gp.terminal.Terminal.execute_object(), org.jgap.gp.function.ForXLoop.execute_void(), org.jgap.gp.function.AddAndStore.execute_void(), examples.gp.paintedDesert.IfLessThanZero.execute_void(), examples.gp.paintedDesert.IfLessThanOrEqual.execute_void(), org.jgap.gp.function.StoreTerminalIndexed.execute_void(), examples.gp.tictactoe.IfColor.execute_void(), org.jgap.gp.function.StoreTerminal.execute_void(), org.jgap.gp.function.AddAndStoreTerminal.execute_void(), org.jgap.gp.function.IfElse.execute_void(), org.jgap.gp.function.ForLoop.execute_void(), org.jgap.gp.terminal.Terminal.setRandomValue(), and org.jgap.gp.terminal.Terminal.toString().
Object org.jgap.gp.CommandGene.m_applicationData [private]
Application-specific data that is attached to the Gene. This data may assist the application in labelling this Gene. JGAP ignores the data, aside from allowing it to be set and retrieved and considering it in clone and compareTo.
Since
3.0
Definition at line 122 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.compareTo(), org.jgap.gp.CommandGene.equals(), org.jgap.gp.CommandGene.getApplicationData(), and org.jgap.gp.CommandGene.setApplicationData().
int org.jgap.gp.CommandGene.m_arity [private]
The arity of this node. Arity is the number of children of the node. An arity if zero means: there are no children. A terminal has an arity of zero.
Definition at line 101 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.CommandGene(), org.jgap.gp.CommandGene.getArity(), org.jgap.gp.CommandGene.getChildType(), org.jgap.gp.CommandGene.getPersistentRepresentation(), org.jgap.gp.CommandGene.setArity(), and org.jgap.gp.CommandGene.size().
int org.jgap.gp.CommandGene.m_arityMax [private]
Definition at line 105 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.getArityMax(), and org.jgap.gp.CommandGene.setArityMax().
int org.jgap.gp.CommandGene.m_arityMin [private]
Definition at line 103 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.getArityMin(), and org.jgap.gp.CommandGene.setArityMin().
boolean org.jgap.gp.CommandGene.m_compareAppData [private]
Method compareTo and equals: Should we also consider the application data when comparing? Default is `false` as `true` means a Gene's losing its identity when application data is set differently!
Since
3.0
Definition at line 131 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.compareTo(), org.jgap.gp.CommandGene.equals(), org.jgap.gp.CommandGene.isCompareApplicationData(), and org.jgap.gp.CommandGene.setCompareApplicationData().
GPConfiguration org.jgap.gp.CommandGene.m_configuration [private]
Definition at line 84 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.CommandGene(), and org.jgap.gp.CommandGene.getGPConfiguration().
double org.jgap.gp.CommandGene.m_energy [private]
Energy of a gene, see RFE 1102206
Definition at line 112 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.getEnergy(), and org.jgap.gp.CommandGene.setEnergy().
boolean org.jgap.gp.CommandGene.m_floatType [private]
Definition at line 109 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.CommandGene(), and org.jgap.gp.CommandGene.isFloatType().
boolean org.jgap.gp.CommandGene.m_integerType [private]
Definition at line 107 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.CommandGene(), and org.jgap.gp.CommandGene.isIntegerType().
boolean org.jgap.gp.CommandGene.m_noValidation [private]
Should isValid() be called? True = no!
Definition at line 89 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.check(), and org.jgap.gp.CommandGene.setNoValidation().
Class org.jgap.gp.CommandGene.m_returnType [private]
The return type of this node.
Definition at line 94 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.CommandGene(), org.jgap.gp.CommandGene.equals(), org.jgap.gp.CommandGene.execute(), org.jgap.gp.CommandGene.getPersistentRepresentation(), org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.CommandGene.setReturnType().
int [] org.jgap.gp.CommandGene.m_subChildTypes [private]
Definition at line 135 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.CommandGene(), org.jgap.gp.CommandGene.compareTo(), org.jgap.gp.CommandGene.equals(), org.jgap.gp.CommandGene.getPersistentRepresentation(), org.jgap.gp.CommandGene.getSubChildType(), and org.jgap.gp.CommandGene.getSubChildTypes().
int org.jgap.gp.CommandGene.m_subReturnType [private]
Definition at line 133 of file CommandGene.java.
Referenced by org.jgap.gp.CommandGene.CommandGene(), org.jgap.gp.CommandGene.compareTo(), org.jgap.gp.CommandGene.equals(), org.jgap.gp.CommandGene.getPersistentRepresentation(), and org.jgap.gp.CommandGene.getSubReturnType().
int org.jgap.gp.CommandGene.nodeIndex
Definition at line 137 of file CommandGene.java.
final Class org.jgap.gp.CommandGene.VoidClass = Void.class [static]
Definition at line 59 of file CommandGene.java.
Referenced by org.jgap.gp.function.AddAndStore.AddAndStore(), org.jgap.gp.function.AddAndStoreTerminal.AddAndStoreTerminal(), examples.gp.anttrail.AntCommand.AntCommand(), examples.gp.tictactoe.CountStones.CountStones(), examples.gp.Fibonacci.create(), examples.gp.tictactoe.TicTacToeMain.create(), examples.gp.paintedDesert.PaintedDesertProblem.create(), examples.gp.anttrail.AntTrailProblem.create(), org.jgap.gp.GPProblem.createTree(), examples.gp.tictactoe.EvaluateBoard.EvaluateBoard(), org.jgap.gp.function.ExchangeMemory.ExchangeMemory(), org.jgap.gp.CommandGene.execute(), org.jgap.gp.function.Equals.execute_boolean(), org.jgap.gp.function.ForLoop.ForLoop(), org.jgap.gp.function.ForXLoop.ForXLoop(), org.jgap.gp.function.Loop.getChildType(), examples.gp.paintedDesert.IfDrop.getChildType(), org.jgap.gp.function.ForXLoop.getChildType(), examples.gp.paintedDesert.LoopUntil.getChildType(), examples.gp.tictactoe.IfIsFree.getChildType(), examples.gp.tictactoe.IfIsOccupied.getChildType(), examples.gp.paintedDesert.IfLessThanZero.getChildType(), examples.gp.paintedDesert.IfLessThanOrEqual.getChildType(), examples.gp.tictactoe.IfColor.getChildType(), org.jgap.gp.function.IfElse.getChildType(), org.jgap.gp.function.ForLoop.getChildType(), examples.gp.paintedDesert.GO_E.GO_E(), examples.gp.paintedDesert.GO_N.GO_N(), examples.gp.paintedDesert.GO_S.GO_S(), examples.gp.paintedDesert.GO_W.GO_W(), examples.gp.tictactoe.IfColor.IfColor(), examples.gp.paintedDesert.IfDrop.IfDrop(), org.jgap.gp.function.IfElse.IfElse(), examples.gp.anttrail.IfFoodAheadElse.IfFoodAheadElse(), examples.gp.anttrail.IfFoodAheadLeft.IfFoodAheadLeft(), examples.gp.anttrail.IfFoodAheadRight.IfFoodAheadRight(), examples.gp.tictactoe.IfIsFree.IfIsFree(), examples.gp.tictactoe.IfIsOccupied.IfIsOccupied(), examples.gp.paintedDesert.IfLessThanOrEqual.IfLessThanOrEqual(), examples.gp.paintedDesert.IfLessThanZero.IfLessThanZero(), org.jgap.gp.function.Loop.Loop(), examples.gp.paintedDesert.MoveRandom.MoveRandom(), org.jgap.gp.terminal.NOP.NOP(), org.jgap.gp.function.Push.Push(), examples.gp.tictactoe.PutStone.PutStone(), examples.gp.tictactoe.PutStone1.PutStone1(), org.jgap.gp.function.ResetMatrix.ResetMatrix(), org.jgap.gp.impl.ProgramChromosome.selectNode(), org.jgap.gp.GPTestCase.setUp(), org.jgap.gp.function.StoreTerminal.StoreTerminal(), org.jgap.gp.function.StoreTerminalIndexed.StoreTerminalIndexed(), org.jgap.gp.impl.GPGenotypeTest.testRandomInitialize_0(), examples.gp.tictactoe.TransferBoardToMemory.TransferBoardToMemory(), org.jgap.gp.function.TransferMemory.TransferMemory(), examples.gp.anttrail.TurnToFood.TurnToFood(), examples.gp.FibonacciNodeValidator.validate(), and org.jgap.gp.function.WriteToMatrix.WriteToMatrix().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/CommandGene.java