org.jgap.impl.GreedyCrossoverTest Class Reference
Public Member Functions
void setUp ()
void testOperate_0 () throws Exception
void testOperate_1 () throws Exception
void testOperate_2 () throws Exception
void testOperate_3 () throws Exception
void testOperate_4 () throws Exception
void testOperate_5 () throws Exception
void testOperate_6 () throws Exception
void testStartoffset_0 () throws Exception
void testIsSerializable_0 () throws Exception
void testDoSerialize_0 () throws Exception
void testEquals_0 () throws Exception
void testCompareTo_0 () throws Exception
Static Public Member Functions
static Test suite ()
Private Member Functions
Chromosome chromosome (int[] a_genes) throws Exception
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.22 $`
Additional Inherited Members
Detailed Description
Teste the GreedyCrossover class.
Author
Klaus Meffert
Since
2.1
Definition at line 22 of file GreedyCrossoverTest.java.
Member Function Documentation
Chromosome org.jgap.impl.GreedyCrossoverTest.chromosome (int[] a_genes) throws Exception [inline], [private]
Make a chromosome from the array of integer genes.
Parameters
a_genes input genes
Returns
chromosome containing input genes
Exceptions
Exception
Author
Audrius Meskauskas
Since
2.1
Definition at line 433 of file GreedyCrossoverTest.java.
References org.jgap.JGAPTestCase.conf.
Referenced by org.jgap.impl.GreedyCrossoverTest.testOperate_4().
void org.jgap.impl.GreedyCrossoverTest.setUp () [inline]
Definition at line 32 of file GreedyCrossoverTest.java.
static Test org.jgap.impl.GreedyCrossoverTest.suite () [inline], [static]
Definition at line 27 of file GreedyCrossoverTest.java.
void org.jgap.impl.GreedyCrossoverTest.testCompareTo_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 508 of file GreedyCrossoverTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.GreedyCrossover.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.GreedyCrossoverTest.testDoSerialize_0 () throws Exception [inline]
Ensures that the operator and all objects contained implement Serializable
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 481 of file GreedyCrossoverTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.doSerialize().
void org.jgap.impl.GreedyCrossoverTest.testEquals_0 () throws Exception [inline]
Test equals with classcast object.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 496 of file GreedyCrossoverTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.GreedyCrossoverTest.testIsSerializable_0 () throws Exception [inline]
Ensures the operator is implementing Serializable
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 468 of file GreedyCrossoverTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.isSerializable().
void org.jgap.impl.GreedyCrossoverTest.testOperate_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 43 of file GreedyCrossoverTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.GreedyCrossoverTest.testOperate_1 () throws Exception [inline]
Same as testOperate_0 except op.setStartOffset(1) instead of 0.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 95 of file GreedyCrossoverTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.GreedyCrossoverTest.testOperate_2 () throws Exception [inline]
Test with CompositeGene.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 145 of file GreedyCrossoverTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.GreedyCrossoverTest.testOperate_3 () throws Exception [inline]
Test with CompositeGene and two identical Genes in a Chromosome.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 193 of file GreedyCrossoverTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.GreedyCrossoverTest.testOperate_4 () throws Exception [inline]
Test the example from the literature. This test tests the crossover main algorithm, not the whole operator.
Exceptions
Exception
Author
Audrius Meskauskas
Since
2.1
Definition at line 249 of file GreedyCrossoverTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.GreedyCrossoverTest.chromosome(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.GreedyCrossoverTest.testOperate_5 () throws Exception [inline]
Tests if population size grows expectedly after two consecutive calls.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 316 of file GreedyCrossoverTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.GreedyCrossoverTest.testOperate_6 () throws Exception [inline]
Tests if error thrown because of wrong length of gene.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 375 of file GreedyCrossoverTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.GreedyCrossoverTest.testStartoffset_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 449 of file GreedyCrossoverTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.GreedyCrossover.getStartOffset().
Member Data Documentation
final String org.jgap.impl.GreedyCrossoverTest.CVS_REVISION = `$Revision: 1.22 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file GreedyCrossoverTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/GreedyCrossoverTest.java