org.jgap.GenotypeTest.Test2Function Class Reference
Public Member Functions
double evaluate (IChromosome ic)
Double getX (IChromosome a_potentialSolution)
Double getY (IChromosome a_potentialSolution)
Additional Inherited Members
Detailed Description
Definition at line 1556 of file GenotypeTest.java.
Member Function Documentation
double org.jgap.GenotypeTest.Test2Function.evaluate (IChromosome a_subject) [inline], [virtual]
Determine the fitness of the given Chromosome instance. The higher the return value, the more fit the instance. This method should always return the same fitness value for two equivalent Chromosome instances.
Parameters
a_subject the Chromosome instance to evaluate
Returns
positive double reflecting the fitness rating of the given Chromosome. Note that if a non-positive double is returned, a RuntimeException should be generated
Author
Neil Rotstan
Klaus Meffert
Since
2.0 (until 1.1: return type int)
Implements org.jgap.FitnessFunction.
Definition at line 1566 of file GenotypeTest.java.
References org.jgap.GenotypeTest.Test2Function.getX(), and org.jgap.GenotypeTest.Test2Function.getY().
Double org.jgap.GenotypeTest.Test2Function.getX (IChromosome a_potentialSolution) [inline]
Definition at line 1581 of file GenotypeTest.java.
References org.jgap.IChromosome.getGene().
Referenced by org.jgap.GenotypeTest.Test2Function.evaluate().
Double org.jgap.GenotypeTest.Test2Function.getY (IChromosome a_potentialSolution) [inline]
Definition at line 1587 of file GenotypeTest.java.
References org.jgap.IChromosome.getGene().
Referenced by org.jgap.GenotypeTest.Test2Function.evaluate().
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/GenotypeTest.java