examples.grid.mathProblemDistributed.MyRequestSplitStrategy Class Reference
Public Member Functions
MyRequestSplitStrategy (GPConfiguration a_config)
GPConfiguration getConfiguration ()
JGAPRequestGP[] split (JGAPRequestGP a_request) throws Exception
Private Attributes
GPConfiguration m_config
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.7 $`
Detailed Description
Sample implementation of IRequestSplitStrategy to split a single request into multiple requests for workers.
Author
Klaus Meffert
Since
3.2
Definition at line 24 of file MyRequestSplitStrategy.java.
Constructor & Destructor Documentation
examples.grid.mathProblemDistributed.MyRequestSplitStrategy.MyRequestSplitStrategy (GPConfiguration a_config) [inline]
Definition at line 31 of file MyRequestSplitStrategy.java.
References examples.grid.mathProblemDistributed.MyRequestSplitStrategy.m_config.
Member Function Documentation
GPConfiguration examples.grid.mathProblemDistributed.MyRequestSplitStrategy.getConfiguration () [inline]
Definition at line 35 of file MyRequestSplitStrategy.java.
References examples.grid.mathProblemDistributed.MyRequestSplitStrategy.m_config.
Referenced by examples.grid.mathProblemDistributed.MyRequestSplitStrategy.split().
JGAPRequestGP [] examples.grid.mathProblemDistributed.MyRequestSplitStrategy.split (JGAPRequestGP a_request) throws Exception [inline]
Creates single requests to be sent to workers. Here, each request consists of a number of chromosome from the original population (determined here) plus the rest of the chromosomes to be initialized randomly at each worker.
Parameters
a_request the request to split
Returns
single requests to be computed by workers
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 51 of file MyRequestSplitStrategy.java.
References examples.grid.mathProblemDistributed.MyRequestSplitStrategy.getConfiguration(), and org.jgap.Configuration.newInstance().
Member Data Documentation
final String examples.grid.mathProblemDistributed.MyRequestSplitStrategy.CVS_REVISION = `$Revision: 1.7 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file MyRequestSplitStrategy.java.
GPConfiguration examples.grid.mathProblemDistributed.MyRequestSplitStrategy.m_config [private]
Definition at line 29 of file MyRequestSplitStrategy.java.
Referenced by examples.grid.mathProblemDistributed.MyRequestSplitStrategy.getConfiguration(), and examples.grid.mathProblemDistributed.MyRequestSplitStrategy.MyRequestSplitStrategy().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/grid/mathProblemDistributed/MyRequestSplitStrategy.java