examples.monalisa.core.GAConfiguration Class Reference
Public Member Functions
GAConfiguration (BufferedImage a_target, int a_maxPolygons) throws InvalidConfigurationException
BufferedImage getTarget ()
int getMaxPolygons ()
GAPhenotypeExpresser getPhenotypeExpresser ()
Object clone ()
Private Attributes
final GAPhenotypeExpresser m_phenotypeExpresser
final BufferedImage m_target
final int m_maxPolygons
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Detailed Description
Encapsulates the settings of the genetic algorithm.
Author
Yann N. Dauphin
Since
3.4
Definition at line 24 of file GAConfiguration.java.
Constructor & Destructor Documentation
examples.monalisa.core.GAConfiguration.GAConfiguration (BufferedImage a_target, int a_maxPolygons) throws InvalidConfigurationException [inline]
Definition at line 35 of file GAConfiguration.java.
References examples.monalisa.core.GAInitialChromosomeFactory.create(), examples.monalisa.core.GAConfiguration.m_maxPolygons, examples.monalisa.core.GAConfiguration.m_phenotypeExpresser, and examples.monalisa.core.GAConfiguration.m_target.
Referenced by examples.monalisa.core.GAConfiguration.clone().
Member Function Documentation
Object examples.monalisa.core.GAConfiguration.clone () [inline]
Definition at line 81 of file GAConfiguration.java.
References examples.monalisa.core.GAConfiguration.GAConfiguration(), examples.monalisa.core.GAConfiguration.m_maxPolygons, and examples.monalisa.core.GAConfiguration.m_target.
int examples.monalisa.core.GAConfiguration.getMaxPolygons () [inline]
Definition at line 72 of file GAConfiguration.java.
References examples.monalisa.core.GAConfiguration.m_maxPolygons.
GAPhenotypeExpresser examples.monalisa.core.GAConfiguration.getPhenotypeExpresser () [inline]
Definition at line 76 of file GAConfiguration.java.
References examples.monalisa.core.GAConfiguration.m_phenotypeExpresser.
BufferedImage examples.monalisa.core.GAConfiguration.getTarget () [inline]
Definition at line 68 of file GAConfiguration.java.
References examples.monalisa.core.GAConfiguration.m_target.
Referenced by examples.monalisa.core.PolygonMutationOperator.operate().
Member Data Documentation
final String examples.monalisa.core.GAConfiguration.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file GAConfiguration.java.
final int examples.monalisa.core.GAConfiguration.m_maxPolygons [private]
Definition at line 33 of file GAConfiguration.java.
Referenced by examples.monalisa.core.GAConfiguration.clone(), examples.monalisa.core.GAConfiguration.GAConfiguration(), and examples.monalisa.core.GAConfiguration.getMaxPolygons().
final GAPhenotypeExpresser examples.monalisa.core.GAConfiguration.m_phenotypeExpresser [private]
Definition at line 29 of file GAConfiguration.java.
Referenced by examples.monalisa.core.GAConfiguration.GAConfiguration(), and examples.monalisa.core.GAConfiguration.getPhenotypeExpresser().
final BufferedImage examples.monalisa.core.GAConfiguration.m_target [private]
Definition at line 31 of file GAConfiguration.java.
Referenced by examples.monalisa.core.GAConfiguration.clone(), examples.monalisa.core.GAConfiguration.GAConfiguration(), and examples.monalisa.core.GAConfiguration.getTarget().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/monalisa/core/GAConfiguration.java