org.jgap.impl.AveragingCrossoverOperatorTest Class Reference
Public Member Functions
void setUp ()
void testOperate_0 () throws Exception
void testOperate_1 () throws Exception
void testOperate_2 () throws Exception
void testOperate_3 () throws Exception
void testOperate_4 () throws Exception
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testConstruct_2 () throws Exception
void testIsSerializable_0 () throws Exception
void testDoSerialize_0 () throws Exception
void testEquals_0 () throws Exception
void testCompareTo_0 () throws Exception
void testCompareTo_1 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.23 $`
Additional Inherited Members
Detailed Description
Tests the AveragingCrossoverOperator class.
Author
Klaus Meffert
Since
2.0
Definition at line 22 of file AveragingCrossoverOperatorTest.java.
Member Function Documentation
void org.jgap.impl.AveragingCrossoverOperatorTest.setUp () [inline]
Definition at line 32 of file AveragingCrossoverOperatorTest.java.
static Test org.jgap.impl.AveragingCrossoverOperatorTest.suite () [inline], [static]
Definition at line 27 of file AveragingCrossoverOperatorTest.java.
void org.jgap.impl.AveragingCrossoverOperatorTest.testCompareTo_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 389 of file AveragingCrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.AveragingCrossoverOperator.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.AveragingCrossoverOperatorTest.testCompareTo_1 () throws Exception [inline]
Crossover rate (setter introduced in 2.6).
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 415 of file AveragingCrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.AveragingCrossoverOperator.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.AveragingCrossoverOperatorTest.testConstruct_0 () throws Exception [inline]
Following should be possible without exception.
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 309 of file AveragingCrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.AveragingCrossoverOperatorTest.testConstruct_1 () throws Exception [inline]
Following should be possible without exception.
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 322 of file AveragingCrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.AveragingCrossoverOperatorTest.testConstruct_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 334 of file AveragingCrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.AveragingCrossoverOperatorTest.testDoSerialize_0 () throws Exception [inline]
Ensures that Object and all objects contained implement Serializable
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 361 of file AveragingCrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.doSerialize().
void org.jgap.impl.AveragingCrossoverOperatorTest.testEquals_0 () throws Exception [inline]
Test equals with classcast object.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 377 of file AveragingCrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.AveragingCrossoverOperatorTest.testIsSerializable_0 () throws Exception [inline]
Ensures Object is implementing Serializable.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 348 of file AveragingCrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.isSerializable().
void org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 43 of file AveragingCrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_1 () throws Exception [inline]
Tests if crossing over produces same results for two operate-runs.
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 93 of file AveragingCrossoverOperatorTest.java.
References org.jgap.Chromosome.clone(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.isChromosomesEqual().
void org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_2 () throws Exception [inline]
Using CompositeGene as first crossover candidate.
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 142 of file AveragingCrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.getAllele().
void org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_3 () throws Exception [inline]
Considers crossover rate calculator
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 199 of file AveragingCrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_4 () throws Exception [inline]
Using CompositeGene as second crossover candidate.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 253 of file AveragingCrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.getAllele().
Member Data Documentation
final String org.jgap.impl.AveragingCrossoverOperatorTest.CVS_REVISION = `$Revision: 1.23 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file AveragingCrossoverOperatorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/AveragingCrossoverOperatorTest.java