org.jgap.gp.function.statistics.StandardDeviation Class Reference
Public Member Functions
StandardDeviation (GPConfiguration a_conf, int a_arityInitial, int a_arityMin, int a_arityMax, Class a_returnType) throws InvalidConfigurationException
String toString ()
double execute_double (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
Object clone ()
String getName ()
Additional Inherited Members
Detailed Description
This class computes the sample standard deviation of existing values.
Author
Luis Garcia
Since
3.5
Definition at line 24 of file StandardDeviation.java.
Constructor & Destructor Documentation
org.jgap.gp.function.statistics.StandardDeviation.StandardDeviation (GPConfiguration a_conf, int a_arityInitial, int a_arityMin, int a_arityMax, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 26 of file StandardDeviation.java.
Referenced by org.jgap.gp.function.statistics.StandardDeviation.clone().
Member Function Documentation
Object org.jgap.gp.function.statistics.StandardDeviation.clone () [inline]
Returns
clone of the current object instance
Implements org.jgap.util.ICloneable.
Definition at line 66 of file StandardDeviation.java.
References org.jgap.gp.CommandGene.getArity(), org.jgap.gp.CommandGene.getArityMax(), org.jgap.gp.CommandGene.getArityMin(), org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.function.statistics.StandardDeviation.StandardDeviation().
double org.jgap.gp.function.statistics.StandardDeviation.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 46 of file StandardDeviation.java.
References org.jgap.gp.CommandGene.size().
float org.jgap.gp.function.statistics.StandardDeviation.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 56 of file StandardDeviation.java.
References org.jgap.gp.CommandGene.size().
String org.jgap.gp.function.statistics.StandardDeviation.getName () [inline]
Definition at line 78 of file StandardDeviation.java.
String org.jgap.gp.function.statistics.StandardDeviation.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 33 of file StandardDeviation.java.
References org.jgap.gp.CommandGene.size().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/statistics/StandardDeviation.java