org.jgap.distr.grid.common.CommonConfiguration Class Reference
Public Member Functions
CommonConfiguration ()
CommonConfiguration (String a_workDir, String a_libDir)
void setWorkDir (String a_workDir)
String getWorkDir ()
void setLibDir (String a_libDir)
String getLibDir ()
void setServerAddress (String a_server)
String getServerAddress ()
Private Attributes
transient Logger LOGGER = Logger.getLogger(CommonConfiguration.class)
String m_workDir
String m_libDir
String m_server
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Detailed Description
Author
Klaus Meffert
Since
3.2
Definition at line 23 of file CommonConfiguration.java.
Constructor & Destructor Documentation
org.jgap.distr.grid.common.CommonConfiguration.CommonConfiguration () [inline]
Definition at line 45 of file CommonConfiguration.java.
org.jgap.distr.grid.common.CommonConfiguration.CommonConfiguration (String a_workDir, String a_libDir) [inline]
Definition at line 48 of file CommonConfiguration.java.
References org.jgap.distr.grid.common.CommonConfiguration.setLibDir(), and org.jgap.distr.grid.common.CommonConfiguration.setWorkDir().
Member Function Documentation
String org.jgap.distr.grid.common.CommonConfiguration.getLibDir () [inline]
Definition at line 88 of file CommonConfiguration.java.
References org.jgap.distr.grid.common.CommonConfiguration.m_libDir.
String org.jgap.distr.grid.common.CommonConfiguration.getServerAddress () [inline]
Definition at line 96 of file CommonConfiguration.java.
References org.jgap.distr.grid.common.CommonConfiguration.m_server.
String org.jgap.distr.grid.common.CommonConfiguration.getWorkDir () [inline]
Definition at line 69 of file CommonConfiguration.java.
References org.jgap.distr.grid.common.CommonConfiguration.m_workDir.
void org.jgap.distr.grid.common.CommonConfiguration.setLibDir (String a_libDir) [inline]
Definition at line 73 of file CommonConfiguration.java.
References org.jgap.distr.grid.common.CommonConfiguration.m_libDir.
Referenced by org.jgap.distr.grid.common.CommonConfiguration.CommonConfiguration().
void org.jgap.distr.grid.common.CommonConfiguration.setServerAddress (String a_server) [inline]
Definition at line 92 of file CommonConfiguration.java.
References org.jgap.distr.grid.common.CommonConfiguration.m_server.
void org.jgap.distr.grid.common.CommonConfiguration.setWorkDir (String a_workDir) [inline]
Definition at line 54 of file CommonConfiguration.java.
References org.jgap.distr.grid.common.CommonConfiguration.m_workDir.
Referenced by org.jgap.distr.grid.common.CommonConfiguration.CommonConfiguration().
Member Data Documentation
final String org.jgap.distr.grid.common.CommonConfiguration.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file CommonConfiguration.java.
transient Logger org.jgap.distr.grid.common.CommonConfiguration.LOGGER = Logger.getLogger(CommonConfiguration.class) [private]
Definition at line 28 of file CommonConfiguration.java.
String org.jgap.distr.grid.common.CommonConfiguration.m_libDir [private]
Directory where the libraries to compute work units reside
Definition at line 38 of file CommonConfiguration.java.
Referenced by org.jgap.distr.grid.common.CommonConfiguration.getLibDir(), and org.jgap.distr.grid.common.CommonConfiguration.setLibDir().
String org.jgap.distr.grid.common.CommonConfiguration.m_server [private]
Connect string to the server
Definition at line 43 of file CommonConfiguration.java.
Referenced by org.jgap.distr.grid.common.CommonConfiguration.getServerAddress(), and org.jgap.distr.grid.common.CommonConfiguration.setServerAddress().
String org.jgap.distr.grid.common.CommonConfiguration.m_workDir [private]
Working directory
Definition at line 33 of file CommonConfiguration.java.
Referenced by org.jgap.distr.grid.common.CommonConfiguration.getWorkDir(), and org.jgap.distr.grid.common.CommonConfiguration.setWorkDir().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/distr/grid/common/CommonConfiguration.java