org.jgap.eval.PopulationHistory Class Reference
Public Member Functions
PopulationHistory (final int a_maxSize)
Population getPopulation (final int a_count)
void addPopulation (final Population a_population)
void removeAllPopulations ()
int size ()
List getPopulations ()
void setPopulations (final List a_populations)
boolean equals (Object a_other)
Private Attributes
List m_populations
int m_maxSize
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.7 $`
Detailed Description
Container for holding a given number of populations. Serves as a history object for later evaluation.
Author
Klaus Meffert
Since
2.0
Definition at line 23 of file PopulationHistory.java.
Constructor & Destructor Documentation
org.jgap.eval.PopulationHistory.PopulationHistory (final int a_maxSize) [inline]
Constructor.
Parameters
a_maxSize the maximum number of Population objects to hold, or zero if there is no limit.
Author
Klaus Meffert
Since
2.0
Definition at line 41 of file PopulationHistory.java.
References org.jgap.eval.PopulationHistory.m_maxSize, and org.jgap.eval.PopulationHistory.m_populations.
Referenced by org.jgap.eval.PopulationHistory.equals().
Member Function Documentation
void org.jgap.eval.PopulationHistory.addPopulation (final Population a_population) [inline]
Adds a population to the history. If the maximum size of this container is exceeded, then the population added earliest is removed.
Parameters
a_population the population to be added
Author
Klaus Meffert
Since
2.0
Definition at line 68 of file PopulationHistory.java.
References org.jgap.eval.PopulationHistory.m_maxSize.
boolean org.jgap.eval.PopulationHistory.equals (Object a_other) [inline]
Parameters
a_other other object to compare to
Returns
true other object seen as equal
Author
Klaus Meffert
Since
3.5
Definition at line 120 of file PopulationHistory.java.
References org.jgap.Population.equals(), org.jgap.eval.PopulationHistory.getPopulation(), org.jgap.eval.PopulationHistory.PopulationHistory(), and org.jgap.eval.PopulationHistory.size().
Population org.jgap.eval.PopulationHistory.getPopulation (final int a_count) [inline]
Definition at line 50 of file PopulationHistory.java.
References org.jgap.eval.PopulationHistory.m_populations.
Referenced by org.jgap.eval.PopulationHistory.equals().
List org.jgap.eval.PopulationHistory.getPopulations () [inline]
Definition at line 91 of file PopulationHistory.java.
References org.jgap.eval.PopulationHistory.m_populations.
void org.jgap.eval.PopulationHistory.removeAllPopulations () [inline]
Author
Klaus Meffert
Since
2.0
Definition at line 83 of file PopulationHistory.java.
References org.jgap.eval.PopulationHistory.m_populations.
void org.jgap.eval.PopulationHistory.setPopulations (final List a_populations) [inline]
Sets the list of populations to the list provided.
Parameters
a_populations list of populations to be set
Author
Klaus Meffert
Since
2.0
Definition at line 103 of file PopulationHistory.java.
References org.jgap.eval.PopulationHistory.m_maxSize, and org.jgap.eval.PopulationHistory.m_populations.
int org.jgap.eval.PopulationHistory.size () [inline]
Definition at line 87 of file PopulationHistory.java.
Referenced by org.jgap.eval.PopulationHistory.equals(), org.jgap.eval.PopulationHistoryTest.testAddPopulation_0(), org.jgap.eval.PopulationHistoryTest.testAddPopulation_1(), org.jgap.eval.PopulationHistoryTest.testRemoveAllPopulations_0(), and org.jgap.eval.PopulationHistoryTest.testSize_0().
Member Data Documentation
final String org.jgap.eval.PopulationHistory.CVS_REVISION = `$Revision: 1.7 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file PopulationHistory.java.
int org.jgap.eval.PopulationHistory.m_maxSize [private]
Definition at line 30 of file PopulationHistory.java.
Referenced by org.jgap.eval.PopulationHistory.addPopulation(), org.jgap.eval.PopulationHistory.PopulationHistory(), and org.jgap.eval.PopulationHistory.setPopulations().
List org.jgap.eval.PopulationHistory.m_populations [private]
Definition at line 28 of file PopulationHistory.java.
Referenced by org.jgap.eval.PopulationHistory.getPopulation(), org.jgap.eval.PopulationHistory.getPopulations(), org.jgap.eval.PopulationHistory.PopulationHistory(), org.jgap.eval.PopulationHistory.removeAllPopulations(), and org.jgap.eval.PopulationHistory.setPopulations().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/eval/PopulationHistory.java