examples.monalisa.gui.GeneticDrawingView Class Reference
Public Member Functions
GeneticDrawingView (SingleFrameApplication app)
void showAboutBox ()
void chooseImage () throws IOException
void startEvolution () throws InvalidConfigurationException
ImageIcon scaleToImageLabel (Image a_image)
BufferedImage getTargetImage ()
boolean isEvolutionActivated ()
FittestDrawingView getFittestDrawingView ()
JFreeChart getChart ()
Private Member Functions
void initComponents ()
Private Attributes
javax.swing.JPanel chartPanel
javax.swing.JButton chooseImage
javax.swing.JPanel mainPanel
javax.swing.JMenuBar menuBar
javax.swing.JToggleButton startEvolution
javax.swing.JLabel targetImageLabel
JDialog aboutBox
BufferedImage targetImage
boolean isEvolutionActivated
FittestDrawingView fittestDrawingView
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Detailed Description
The application's main frame.
Author
Yann N. Dauphin
Since
3.4
Definition at line 33 of file GeneticDrawingView.java.
Constructor & Destructor Documentation
examples.monalisa.gui.GeneticDrawingView.GeneticDrawingView (SingleFrameApplication app) [inline]
Definition at line 38 of file GeneticDrawingView.java.
References examples.monalisa.gui.GeneticDrawingView.fittestDrawingView, examples.monalisa.gui.GeneticDrawingView.initComponents(), and examples.monalisa.gui.GeneticDrawingView.targetImage.
Member Function Documentation
void examples.monalisa.gui.GeneticDrawingView.chooseImage () throws IOException [inline]
Definition at line 63 of file GeneticDrawingView.java.
References examples.monalisa.gui.GeneticDrawingView.mainPanel, examples.monalisa.gui.GeneticDrawingView.scaleToImageLabel(), and examples.monalisa.gui.GeneticDrawingView.targetImage.
Referenced by examples.monalisa.gui.GeneticDrawingView.initComponents().
JFreeChart examples.monalisa.gui.GeneticDrawingView.getChart () [inline]
Definition at line 128 of file GeneticDrawingView.java.
References examples.monalisa.gui.GeneticDrawingView.chartPanel.
FittestDrawingView examples.monalisa.gui.GeneticDrawingView.getFittestDrawingView () [inline]
Definition at line 124 of file GeneticDrawingView.java.
References examples.monalisa.gui.GeneticDrawingView.fittestDrawingView.
BufferedImage examples.monalisa.gui.GeneticDrawingView.getTargetImage () [inline]
Definition at line 116 of file GeneticDrawingView.java.
References examples.monalisa.gui.GeneticDrawingView.targetImage.
void examples.monalisa.gui.GeneticDrawingView.initComponents () [inline], [private]
This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 140 of file GeneticDrawingView.java.
References examples.monalisa.gui.GeneticDrawingView.chartPanel, examples.monalisa.gui.GeneticDrawingView.chooseImage(), examples.monalisa.gui.GeneticDrawingView.mainPanel, examples.monalisa.gui.GeneticDrawingView.menuBar, examples.monalisa.gui.GeneticDrawingView.startEvolution(), and examples.monalisa.gui.GeneticDrawingView.targetImageLabel.
Referenced by examples.monalisa.gui.GeneticDrawingView.GeneticDrawingView().
boolean examples.monalisa.gui.GeneticDrawingView.isEvolutionActivated () [inline]
Definition at line 120 of file GeneticDrawingView.java.
Referenced by examples.monalisa.gui.GeneticDrawingView.startEvolution().
ImageIcon examples.monalisa.gui.GeneticDrawingView.scaleToImageLabel (Image a_image) [inline]
Scale an image to fit the size of the targetImageLabel.
Parameters
a_image the image to scale
Returns
scaled image
Definition at line 103 of file GeneticDrawingView.java.
References examples.monalisa.gui.GeneticDrawingView.targetImageLabel.
Referenced by examples.monalisa.gui.GeneticDrawingView.chooseImage().
void examples.monalisa.gui.GeneticDrawingView.showAboutBox () [inline]
Definition at line 53 of file GeneticDrawingView.java.
References examples.monalisa.gui.GeneticDrawingView.aboutBox.
void examples.monalisa.gui.GeneticDrawingView.startEvolution () throws InvalidConfigurationException [inline]
Definition at line 75 of file GeneticDrawingView.java.
References examples.monalisa.gui.GeneticDrawingView.isEvolutionActivated(), and examples.monalisa.gui.GeneticDrawingView.targetImage.
Referenced by examples.monalisa.gui.GeneticDrawingView.initComponents().
Member Data Documentation
JDialog examples.monalisa.gui.GeneticDrawingView.aboutBox [private]
Definition at line 275 of file GeneticDrawingView.java.
Referenced by examples.monalisa.gui.GeneticDrawingView.showAboutBox().
javax.swing.JPanel examples.monalisa.gui.GeneticDrawingView.chartPanel [private]
Definition at line 262 of file GeneticDrawingView.java.
Referenced by examples.monalisa.gui.GeneticDrawingView.getChart(), and examples.monalisa.gui.GeneticDrawingView.initComponents().
javax.swing.JButton examples.monalisa.gui.GeneticDrawingView.chooseImage [private]
Definition at line 264 of file GeneticDrawingView.java.
final String examples.monalisa.gui.GeneticDrawingView.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 36 of file GeneticDrawingView.java.
FittestDrawingView examples.monalisa.gui.GeneticDrawingView.fittestDrawingView [private]
Definition at line 281 of file GeneticDrawingView.java.
Referenced by examples.monalisa.gui.GeneticDrawingView.GeneticDrawingView(), and examples.monalisa.gui.GeneticDrawingView.getFittestDrawingView().
boolean examples.monalisa.gui.GeneticDrawingView.isEvolutionActivated [private]
Definition at line 279 of file GeneticDrawingView.java.
Referenced by examples.monalisa.gui.EvolutionRunnable.run().
javax.swing.JPanel examples.monalisa.gui.GeneticDrawingView.mainPanel [private]
Definition at line 266 of file GeneticDrawingView.java.
Referenced by examples.monalisa.gui.GeneticDrawingView.chooseImage(), and examples.monalisa.gui.GeneticDrawingView.initComponents().
javax.swing.JMenuBar examples.monalisa.gui.GeneticDrawingView.menuBar [private]
Definition at line 268 of file GeneticDrawingView.java.
Referenced by examples.monalisa.gui.GeneticDrawingView.initComponents().
javax.swing.JToggleButton examples.monalisa.gui.GeneticDrawingView.startEvolution [private]
Definition at line 270 of file GeneticDrawingView.java.
BufferedImage examples.monalisa.gui.GeneticDrawingView.targetImage [private]
Definition at line 277 of file GeneticDrawingView.java.
Referenced by examples.monalisa.gui.GeneticDrawingView.chooseImage(), examples.monalisa.gui.GeneticDrawingView.GeneticDrawingView(), examples.monalisa.gui.GeneticDrawingView.getTargetImage(), and examples.monalisa.gui.GeneticDrawingView.startEvolution().
javax.swing.JLabel examples.monalisa.gui.GeneticDrawingView.targetImageLabel [private]
Definition at line 272 of file GeneticDrawingView.java.
Referenced by examples.monalisa.gui.GeneticDrawingView.initComponents(), and examples.monalisa.gui.GeneticDrawingView.scaleToImageLabel().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/monalisa/gui/GeneticDrawingView.java