org.jgap.distr.grid.JGAPWorkers Class Reference
Public Member Functions
JGAPWorkers (String[] args) throws Exception
void getNeededFiles (GridNodeWorkerConfig a_config)
JGAPWorkers (GridNodeWorkerConfig a_config) throws Exception
Static Public Member Functions
static void main (String[] args) throws Exception
Protected Member Functions
void startWork (GridNodeWorkerConfig a_config) throws Exception
Private Attributes
Class m_workerClass
Class m_workerFeedbackClaas
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.6 $`
static final String className = JGAPWorkers.class.getName()
static Logger log = Logger.getLogger(className)
Detailed Description
A worker receives work units from a JGAPServer and sends back computed solutions to a JGAPServer.
Author
Klaus Meffert
Since
3.01
Definition at line 25 of file JGAPWorkers.java.
Constructor & Destructor Documentation
org.jgap.distr.grid.JGAPWorkers.JGAPWorkers (String[] args) throws Exception [inline]
Definition at line 37 of file JGAPWorkers.java.
References org.jgap.distr.grid.JGAPWorkers.getNeededFiles(), and org.jgap.distr.grid.JGAPWorkers.startWork().
Referenced by org.jgap.distr.grid.JGAPWorkers.main().
org.jgap.distr.grid.JGAPWorkers.JGAPWorkers (GridNodeWorkerConfig a_config) throws Exception [inline]
Definition at line 66 of file JGAPWorkers.java.
References org.jgap.distr.grid.JGAPWorkers.startWork().
Member Function Documentation
void org.jgap.distr.grid.JGAPWorkers.getNeededFiles (GridNodeWorkerConfig a_config) [inline]
Get jar and other files needed for computation from server .
Parameters
a_config GridNodeWorkerConfig
Todo
Todo
Definition at line 55 of file JGAPWorkers.java.
Referenced by org.jgap.distr.grid.JGAPWorkers.JGAPWorkers().
static void org.jgap.distr.grid.JGAPWorkers.main (String[] args) throws Exception [inline], [static]
Convenience method to start a worker or multiple instances of it. For possible parameters see method parseCommonOptions in class org.homedns.dade.jcgrid.cmd.MainCmd. The most important parameters are: -n <session name=`` without=`` spaces>=``> -s <server ip=`` address>=``> -d <working directory>=``> -c <number of=`` workers=`` to=`` run>=``>
Parameters
args see above
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 119 of file JGAPWorkers.java.
References org.jgap.distr.grid.JGAPWorkers.JGAPWorkers().
void org.jgap.distr.grid.JGAPWorkers.startWork (GridNodeWorkerConfig a_config) throws Exception [inline], [protected]
Definition at line 71 of file JGAPWorkers.java.
Referenced by org.jgap.distr.grid.JGAPWorkers.JGAPWorkers().
Member Data Documentation
final String org.jgap.distr.grid.JGAPWorkers.className = JGAPWorkers.class.getName() [static], [private]
Definition at line 33 of file JGAPWorkers.java.
final String org.jgap.distr.grid.JGAPWorkers.CVS_REVISION = `$Revision: 1.6 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file JGAPWorkers.java.
Logger org.jgap.distr.grid.JGAPWorkers.log = Logger.getLogger(className) [static], [private]
Definition at line 35 of file JGAPWorkers.java.
Class org.jgap.distr.grid.JGAPWorkers.m_workerClass [private]
Definition at line 29 of file JGAPWorkers.java.
Class org.jgap.distr.grid.JGAPWorkers.m_workerFeedbackClaas [private]
Definition at line 31 of file JGAPWorkers.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/distr/grid/JGAPWorkers.java