org.jgap.impl.GaussianRandomGenerator Class Reference
Public Member Functions
GaussianRandomGenerator ()
GaussianRandomGenerator (final double a_standardDeviation)
void setGaussianStdDeviation (final double a_standardDeviation)
double getGaussianStdDeviation ()
int nextInt ()
int nextInt (final int a_ceiling)
long nextLong ()
double nextDouble ()
float nextFloat ()
boolean nextBoolean ()
Private Member Functions
void init ()
double nextGaussian ()
void readObject (ObjectInputStream a_inputStream) throws IOException, ClassNotFoundException
Private Attributes
Random m_rn
double m_standardDeviation
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.21 $`
static final double DELTA = 0.0000001
Additional Inherited Members
Detailed Description
Gaussian deviation serving as basis for randomly finding a number.
Author
Klaus Meffert
Since
1.1
Definition at line 22 of file GaussianRandomGenerator.java.
Constructor & Destructor Documentation
org.jgap.impl.GaussianRandomGenerator.GaussianRandomGenerator () [inline]
Definition at line 37 of file GaussianRandomGenerator.java.
org.jgap.impl.GaussianRandomGenerator.GaussianRandomGenerator (final double a_standardDeviation) [inline]
Constructor speicifying the (obliagtory) standard deviation.
Parameters
a_standardDeviation the standard deviation to use
Definition at line 46 of file GaussianRandomGenerator.java.
References org.jgap.impl.GaussianRandomGenerator.init(), and org.jgap.impl.GaussianRandomGenerator.setGaussianStdDeviation().
Member Function Documentation
double org.jgap.impl.GaussianRandomGenerator.getGaussianStdDeviation () [inline]
Definition at line 67 of file GaussianRandomGenerator.java.
References org.jgap.impl.GaussianRandomGenerator.m_standardDeviation.
Referenced by org.jgap.impl.GaussianRandomGeneratorTest.testGetGaussianStdDeviation_0().
void org.jgap.impl.GaussianRandomGenerator.init () [inline], [private]
Initializations on construction.
Definition at line 55 of file GaussianRandomGenerator.java.
References org.jgap.impl.GaussianRandomGenerator.m_rn.
Referenced by org.jgap.impl.GaussianRandomGenerator.GaussianRandomGenerator().
boolean org.jgap.impl.GaussianRandomGenerator.nextBoolean () [inline]
Returns the next pseudorandom, uniformly distributed boolean value from this random number generator's sequence. The general contract of nextBoolean is that one boolean value is pseudorandomly generated and returned. The values true and false are produced with (approximately) equal probability.
Returns
a pseudorandom boolean value
Author
Neil Rotstan
Since
1.0
Implements org.jgap.RandomGenerator.
Definition at line 106 of file GaussianRandomGenerator.java.
References org.jgap.impl.GaussianRandomGenerator.nextGaussian().
double org.jgap.impl.GaussianRandomGenerator.nextDouble () [inline]
Returns the next pseudorandom, uniformly distributed double value between 0.0 and 1.0 from this random number generator's sequence.
Returns
a psuedorandom double value GREATER/EQUAL 0 AND LESS THAN 1
Author
Neil Rotstan
Since
1.0
Implements org.jgap.RandomGenerator.
Definition at line 98 of file GaussianRandomGenerator.java.
References org.jgap.impl.GaussianRandomGenerator.nextGaussian().
float org.jgap.impl.GaussianRandomGenerator.nextFloat () [inline]
Returns the next pseudorandom, uniformly distributed float value between 0.0 and 1.0 from this random number generator's sequence.
Returns
a psuedorandom float value
Author
Neil Rotstan
Since
1.0
Implements org.jgap.RandomGenerator.
Definition at line 102 of file GaussianRandomGenerator.java.
References org.jgap.impl.GaussianRandomGenerator.nextGaussian().
double org.jgap.impl.GaussianRandomGenerator.nextGaussian () [inline], [private]
Returns
the next randomly distributed gaussian with current standard deviation, will be greater/equal zero
Definition at line 114 of file GaussianRandomGenerator.java.
Referenced by org.jgap.impl.GaussianRandomGenerator.nextBoolean(), org.jgap.impl.GaussianRandomGenerator.nextDouble(), org.jgap.impl.GaussianRandomGenerator.nextFloat(), org.jgap.impl.GaussianRandomGenerator.nextInt(), and org.jgap.impl.GaussianRandomGenerator.nextLong().
int org.jgap.impl.GaussianRandomGenerator.nextInt () [inline]
Returns
positive integer value
Implements org.jgap.RandomGenerator.
Definition at line 74 of file GaussianRandomGenerator.java.
References org.jgap.impl.GaussianRandomGenerator.nextGaussian().
int org.jgap.impl.GaussianRandomGenerator.nextInt (final int a_ceiling) [inline]
Parameters
a_ceiling the upper boundary excluded
Returns
positive integer value between 0 and (ceiling - 1)
Definition at line 84 of file GaussianRandomGenerator.java.
References org.jgap.impl.GaussianRandomGenerator.nextGaussian().
long org.jgap.impl.GaussianRandomGenerator.nextLong () [inline]
Returns
positive long value
Implements org.jgap.RandomGenerator.
Definition at line 92 of file GaussianRandomGenerator.java.
References org.jgap.impl.GaussianRandomGenerator.nextGaussian().
void org.jgap.impl.GaussianRandomGenerator.readObject (ObjectInputStream a_inputStream) throws IOException, ClassNotFoundException [inline], [private]
When deserializing, initialize the seed because otherwise we could get duplicate evolution results when doing distributed computing!
Parameters
a_inputStream the ObjectInputStream provided for deserialzation
Exceptions
IOException
ClassNotFoundException
Author
Klaus Meffert
Since
3.01
Definition at line 132 of file GaussianRandomGenerator.java.
void org.jgap.impl.GaussianRandomGenerator.setGaussianStdDeviation (final double a_standardDeviation) [inline]
Definition at line 59 of file GaussianRandomGenerator.java.
References org.jgap.impl.GaussianRandomGenerator.DELTA, and org.jgap.impl.GaussianRandomGenerator.m_standardDeviation.
Referenced by org.jgap.impl.GaussianRandomGenerator.GaussianRandomGenerator().
Member Data Documentation
final String org.jgap.impl.GaussianRandomGenerator.CVS_REVISION = `$Revision: 1.21 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file GaussianRandomGenerator.java.
final double org.jgap.impl.GaussianRandomGenerator.DELTA = 0.0000001 [static], [private]
Definition at line 28 of file GaussianRandomGenerator.java.
Referenced by org.jgap.impl.GaussianRandomGenerator.setGaussianStdDeviation().
Random org.jgap.impl.GaussianRandomGenerator.m_rn [private]
Definition at line 30 of file GaussianRandomGenerator.java.
Referenced by org.jgap.impl.GaussianRandomGenerator.init().
double org.jgap.impl.GaussianRandomGenerator.m_standardDeviation [private]
Standard deviation of the gaussian deviation
Definition at line 35 of file GaussianRandomGenerator.java.
Referenced by org.jgap.impl.GaussianRandomGenerator.getGaussianStdDeviation(), and org.jgap.impl.GaussianRandomGenerator.setGaussianStdDeviation().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/GaussianRandomGenerator.java