org.jgap.gp.function.ResetMatrix Class Reference
Public Member Functions
ResetMatrix (final GPConfiguration a_conf, String a_matrixName, char a_filler) throws InvalidConfigurationException
String toString ()
String getName ()
void execute_void (ProgramChromosome c, int n, Object[] args)
int compareTo (Object a_other)
boolean equals (Object a_other)
Object clone ()
Private Attributes
String m_matrixName
char m_filler
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
Resets a two-dimensional matrix in internal memory by setting each cell to an initial value.
Author
Klaus Meffert
Since
3.4.3
Definition at line 25 of file ResetMatrix.java.
Constructor & Destructor Documentation
org.jgap.gp.function.ResetMatrix.ResetMatrix (final GPConfiguration a_conf, String a_matrixName, char a_filler) throws InvalidConfigurationException [inline]
Allows setting a sub child type.
Parameters
a_conf the configuration to use
a_matrixName name of the matrix
a_filler the character to fill the matrix with
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.4.3
Definition at line 49 of file ResetMatrix.java.
References org.jgap.gp.function.ResetMatrix.m_filler, org.jgap.gp.function.ResetMatrix.m_matrixName, and org.jgap.gp.CommandGene.VoidClass.
Referenced by org.jgap.gp.function.ResetMatrix.clone(), org.jgap.gp.function.ResetMatrix.compareTo(), and org.jgap.gp.function.ResetMatrix.equals().
Member Function Documentation
Object org.jgap.gp.function.ResetMatrix.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4.3
Implements org.jgap.util.ICloneable.
Definition at line 128 of file ResetMatrix.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.function.ResetMatrix.m_filler, org.jgap.gp.function.ResetMatrix.m_matrixName, and org.jgap.gp.function.ResetMatrix.ResetMatrix().
int org.jgap.gp.function.ResetMatrix.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.4.3
Definition at line 90 of file ResetMatrix.java.
References org.jgap.gp.function.ResetMatrix.m_filler, org.jgap.gp.function.ResetMatrix.m_matrixName, and org.jgap.gp.function.ResetMatrix.ResetMatrix().
boolean org.jgap.gp.function.ResetMatrix.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Klaus Meffert
Since
3.4.3
Definition at line 109 of file ResetMatrix.java.
References org.jgap.gp.function.ResetMatrix.m_filler, org.jgap.gp.function.ResetMatrix.m_matrixName, and org.jgap.gp.function.ResetMatrix.ResetMatrix().
void org.jgap.gp.function.ResetMatrix.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 75 of file ResetMatrix.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.function.ResetMatrix.m_filler, and org.jgap.gp.function.ResetMatrix.m_matrixName.
String org.jgap.gp.function.ResetMatrix.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.4.3
Definition at line 70 of file ResetMatrix.java.
References org.jgap.gp.function.ResetMatrix.m_filler, and org.jgap.gp.function.ResetMatrix.m_matrixName.
String org.jgap.gp.function.ResetMatrix.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 60 of file ResetMatrix.java.
References org.jgap.gp.function.ResetMatrix.m_filler, and org.jgap.gp.function.ResetMatrix.m_matrixName.
Member Data Documentation
final String org.jgap.gp.function.ResetMatrix.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file ResetMatrix.java.
char org.jgap.gp.function.ResetMatrix.m_filler [private]
Definition at line 36 of file ResetMatrix.java.
Referenced by org.jgap.gp.function.ResetMatrix.clone(), org.jgap.gp.function.ResetMatrix.compareTo(), org.jgap.gp.function.ResetMatrix.equals(), org.jgap.gp.function.ResetMatrix.execute_void(), org.jgap.gp.function.ResetMatrix.getName(), org.jgap.gp.function.ResetMatrix.ResetMatrix(), and org.jgap.gp.function.ResetMatrix.toString().
String org.jgap.gp.function.ResetMatrix.m_matrixName [private]
Symbolic name of the matrix. Must correspond with a chosen name for ReadFromMatrix.
Definition at line 34 of file ResetMatrix.java.
Referenced by org.jgap.gp.function.ResetMatrix.clone(), org.jgap.gp.function.ResetMatrix.compareTo(), org.jgap.gp.function.ResetMatrix.equals(), org.jgap.gp.function.ResetMatrix.execute_void(), org.jgap.gp.function.ResetMatrix.getName(), org.jgap.gp.function.ResetMatrix.ResetMatrix(), and org.jgap.gp.function.ResetMatrix.toString().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/ResetMatrix.java