org.jgap.impl.salesman.Salesman Class Reference
Public Member Functions
abstract double distance (Gene a_from, Gene a_to)
abstract IChromosome createSampleChromosome (Object a_initial_data)
FitnessFunction createFitnessFunction (final Object a_initial_data)
Configuration createConfiguration (final Object a_initial_data) throws InvalidConfigurationException
int getMaxEvolution ()
void setMaxEvolution (final int a_maxEvolution)
int getPopulationSize ()
void setPopulationSize (final int a_populationSize)
IChromosome findOptimalPath (final Object a_initial_data) throws Exception
void setStartOffset (final int a_offset)
int getStartOffset ()
Configuration getConfiguration ()
Private Attributes
Configuration m_config
int m_maxEvolution = 128
int m_populationSize = 512
int m_startOffset = 1
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.22 $`
Detailed Description
The class solves the travelling salesman problem. The traveling salesman problem, or TSP for short, is this: given a finite number of 'cities' along with the cost of travel between each pair of them, find the cheapest way of visiting all the cities and returning to your starting point.)
Author
Audrius Meskauskas
Neil Rotstan, Klaus Meffert (reused code fragments)
Since
2.0
See Also
J. Grefenstette, R. Gopal, R. Rosmaita, and D. Gucht. Genetic algorithms for the traveling salesman problem. In Proceedings of the Second International Conference on Genetic Algorithms. Lawrence Eribaum Associates, Mahwah, NJ, 1985.
Sushil J. Louis & Gong Li (explanatory material)
TPS web site
Definition at line 45 of file Salesman.java.
Member Function Documentation
Configuration org.jgap.impl.salesman.Salesman.createConfiguration (final Object a_initial_data) throws InvalidConfigurationException [inline]
Create a configuration. The configuration should not contain operators for odrinary crossover and mutations, as they make chromosoms invalid in this task. The special operators SwappingMutationOperator and GreedyCrossober should be used instead.
Parameters
a_initial_data the same object as was passed to findOptimalPath. It can be used to specify the task more precisely if the class is used for solving multiple tasks
Returns
created configuration
Exceptions
InvalidConfigurationException
Author
Audrius Meskauskas
Since
2.0
Definition at line 121 of file Salesman.java.
Referenced by org.jgap.impl.salesman.Salesman.findOptimalPath().
FitnessFunction org.jgap.impl.salesman.Salesman.createFitnessFunction (final Object a_initial_data) [inline]
Return the fitness function to use.
Parameters
a_initial_data the same object as was passed to findOptimalPath. It can be used to specify the task more precisely if the class is used for solving multiple tasks
Returns
an applicable fitness function
Author
Audrius Meskauskas
Since
2.0
Definition at line 100 of file Salesman.java.
Referenced by org.jgap.impl.salesman.Salesman.findOptimalPath().
abstract IChromosome org.jgap.impl.salesman.Salesman.createSampleChromosome (Object a_initial_data) [pure virtual]
Override this method to create a single sample chromosome, representing a list of `cities`. Each gene corresponds a single `city` and can appear only once. By default, the first gene corresponds a `city` where the salesman starts the journey. It never changes its position. This can be changed by setting other start offset with setStartOffset(). Other genes will be shuffled to create the initial random population.
Parameters
a_initial_data the same object as was passed to findOptimalPath. It can be used to specify the task more precisely if the class is used for solving multiple tasks
Returns
a sample chromosome
Author
Audrius Meskauskas
Since
2.0
Implemented in org.jgap.impl.salesman.TravellingSalesmanTest.TravellingSalesmanForTesting.
Referenced by org.jgap.impl.salesman.Salesman.findOptimalPath().
abstract double org.jgap.impl.salesman.Salesman.distance (Gene a_from, Gene a_to) [pure virtual]
Override this method to compute the distance between `cities`, indicated by these two given genes. The algorithm is not dependent on the used type of genes.
Parameters
a_from first gene, representing a city
a_to second gene, representing a city
Returns
the distance between two cities represented as genes
Author
Audrius Meskauskas
Since
2.0
Implemented in org.jgap.impl.salesman.TravellingSalesmanTest.TravellingSalesmanForTesting.
IChromosome org.jgap.impl.salesman.Salesman.findOptimalPath (final Object a_initial_data) throws Exception [inline]
Executes the genetic algorithm to determine the optimal path between the cities.
Parameters
a_initial_data can be a record with fields, specifying the task more precisely if the class is used to solve multiple tasks. It is passed to createFitnessFunction, createSampleChromosome and createConfiguration
Exceptions
Exception
Returns
chromosome representing the optimal path between cities
Author
Audrius Meskauskas
Since
2.0
Definition at line 198 of file Salesman.java.
References org.jgap.impl.salesman.Salesman.createConfiguration(), org.jgap.impl.salesman.Salesman.createFitnessFunction(), org.jgap.impl.salesman.Salesman.createSampleChromosome(), org.jgap.impl.salesman.Salesman.getMaxEvolution(), org.jgap.impl.salesman.Salesman.getPopulationSize(), and org.jgap.impl.salesman.Salesman.m_config.
Configuration org.jgap.impl.salesman.Salesman.getConfiguration () [inline]
Definition at line 285 of file Salesman.java.
References org.jgap.impl.salesman.Salesman.m_config.
Referenced by org.jgap.impl.salesman.TravellingSalesmanTest.TravellingSalesmanForTesting.createSampleChromosome().
int org.jgap.impl.salesman.Salesman.getMaxEvolution () [inline]
Returns
maximal number of iterations for population to evolve
Author
Audrius Meskauskas
Since
2.0
Definition at line 148 of file Salesman.java.
References org.jgap.impl.salesman.Salesman.m_maxEvolution.
Referenced by org.jgap.impl.salesman.Salesman.findOptimalPath().
int org.jgap.impl.salesman.Salesman.getPopulationSize () [inline]
Returns
population size for this solution
Since
2.0
Definition at line 168 of file Salesman.java.
References org.jgap.impl.salesman.Salesman.m_populationSize.
Referenced by org.jgap.impl.salesman.Salesman.findOptimalPath().
int org.jgap.impl.salesman.Salesman.getStartOffset () [inline]
Gets a number of genes at the start of chromosome, that are excluded from the swapping. In the Salesman task, the first city in the list should (where the salesman leaves from) probably should not change as it is part of the list. The default value is 1.
Returns
start offset for chromosome
Since
2.0
Definition at line 281 of file Salesman.java.
References org.jgap.impl.salesman.Salesman.m_startOffset.
Referenced by org.jgap.impl.salesman.TravellingSalesmanTest.testSetStartOffset_0().
void org.jgap.impl.salesman.Salesman.setMaxEvolution (final int a_maxEvolution) [inline]
Set the maximal number of iterations for population to evolve (default 512).
Parameters
a_maxEvolution sic
Author
Audrius Meskauskas
Since
2.0
Definition at line 159 of file Salesman.java.
References org.jgap.impl.salesman.Salesman.m_maxEvolution.
void org.jgap.impl.salesman.Salesman.setPopulationSize (final int a_populationSize) [inline]
Set an population size for this solution (default 512)
Parameters
a_populationSize sic
Since
2.0
Definition at line 179 of file Salesman.java.
References org.jgap.impl.salesman.Salesman.m_populationSize.
void org.jgap.impl.salesman.Salesman.setStartOffset (final int a_offset) [inline]
Sets a number of genes at the start of chromosome, that are excluded from the swapping. In the Salesman task, the first city in the list should (where the salesman leaves from) probably should not change as it is part of the list. The default value is 1.
Parameters
a_offset start offset for chromosome
Since
2.0
Definition at line 267 of file Salesman.java.
References org.jgap.impl.salesman.Salesman.m_startOffset.
Member Data Documentation
final String org.jgap.impl.salesman.Salesman.CVS_REVISION = `$Revision: 1.22 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 48 of file Salesman.java.
Configuration org.jgap.impl.salesman.Salesman.m_config [private]
Definition at line 50 of file Salesman.java.
Referenced by org.jgap.impl.salesman.Salesman.findOptimalPath(), and org.jgap.impl.salesman.Salesman.getConfiguration().
int org.jgap.impl.salesman.Salesman.m_maxEvolution = 128 [private]
Definition at line 52 of file Salesman.java.
Referenced by org.jgap.impl.salesman.Salesman.getMaxEvolution(), and org.jgap.impl.salesman.Salesman.setMaxEvolution().
int org.jgap.impl.salesman.Salesman.m_populationSize = 512 [private]
Definition at line 54 of file Salesman.java.
Referenced by org.jgap.impl.salesman.Salesman.getPopulationSize(), and org.jgap.impl.salesman.Salesman.setPopulationSize().
int org.jgap.impl.salesman.Salesman.m_startOffset = 1 [private]
Definition at line 255 of file Salesman.java.
Referenced by org.jgap.impl.salesman.Salesman.getStartOffset(), and org.jgap.impl.salesman.Salesman.setStartOffset().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/salesman/Salesman.java