org.jgap.xml.XMLDocumentBuilderTest Class Reference
Public Member Functions
void testBuildDocument_0 () throws Exception
void testBuildDocument_1 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.6 $`
static final String FILENAME_WRITE = `GAtestWrite.xml`
Additional Inherited Members
Detailed Description
Tests the XMLDocumentBuilder class.
Author
Klaus Meffert
Since
1.0
Definition at line 24 of file XMLDocumentBuilderTest.java.
Member Function Documentation
static Test org.jgap.xml.XMLDocumentBuilderTest.suite () [inline], [static]
Definition at line 31 of file XMLDocumentBuilderTest.java.
void org.jgap.xml.XMLDocumentBuilderTest.testBuildDocument_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 41 of file XMLDocumentBuilderTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.xml.XMLDocumentBuilder.buildDocument(), and org.jgap.JGAPTestCase.conf.
void org.jgap.xml.XMLDocumentBuilderTest.testBuildDocument_1 () throws Exception [inline]
Artifically create a null node
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 67 of file XMLDocumentBuilderTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.xml.XMLDocumentBuilder.buildDocument(), and org.jgap.JGAPTestCase.conf.
Member Data Documentation
final String org.jgap.xml.XMLDocumentBuilderTest.CVS_REVISION = `$Revision: 1.6 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file XMLDocumentBuilderTest.java.
final String org.jgap.xml.XMLDocumentBuilderTest.FILENAME_WRITE = `GAtestWrite.xml` [static], [private]
Definition at line 29 of file XMLDocumentBuilderTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/xml/XMLDocumentBuilderTest.java