org.jgap.distr.grid.SampleSplitStrategy Class Reference
Public Member Functions
SampleSplitStrategy (Configuration a_config)
Configuration getConfiguration ()
JGAPRequest[] split (JGAPRequest a_request) throws Exception
Private Attributes
Configuration m_config
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Additional Inherited Members
Detailed Description
Sample implementation of IRequestSplitStrategy. Here, a request is transformed into 20 single requests, each to be computed by a worker.
Author
Klaus Meffert
Since
3.2
Definition at line 21 of file SampleSplitStrategy.java.
Constructor & Destructor Documentation
org.jgap.distr.grid.SampleSplitStrategy.SampleSplitStrategy (Configuration a_config) [inline]
Definition at line 28 of file SampleSplitStrategy.java.
References org.jgap.distr.grid.SampleSplitStrategy.m_config.
Member Function Documentation
Configuration org.jgap.distr.grid.SampleSplitStrategy.getConfiguration () [inline]
Definition at line 32 of file SampleSplitStrategy.java.
References org.jgap.distr.grid.SampleSplitStrategy.m_config.
Referenced by org.jgap.distr.grid.SampleSplitStrategy.split().
JGAPRequest [] org.jgap.distr.grid.SampleSplitStrategy.split (JGAPRequest a_request) throws Exception [inline]
Creates 20 single requests out of one. The single requests are each processed by one worker at a time.
Parameters
a_request the request to split
Returns
single requests to be computed by workers
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Implements org.jgap.distr.grid.IRequestSplitStrategy.
Definition at line 47 of file SampleSplitStrategy.java.
References org.jgap.distr.grid.SampleSplitStrategy.getConfiguration(), and org.jgap.distr.grid.JGAPRequest.newInstance().
Member Data Documentation
final String org.jgap.distr.grid.SampleSplitStrategy.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file SampleSplitStrategy.java.
Configuration org.jgap.distr.grid.SampleSplitStrategy.m_config [private]
Definition at line 26 of file SampleSplitStrategy.java.
Referenced by org.jgap.distr.grid.SampleSplitStrategy.getConfiguration(), and org.jgap.distr.grid.SampleSplitStrategy.SampleSplitStrategy().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/distr/grid/SampleSplitStrategy.java