org.jgap.impl.MapGeneTest Class Reference
Public Member Functions
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testConstruct_2 () throws Exception
void testConstruct_3 () throws Exception
void testToString_0 () throws Exception
void testToString_1 () throws Exception
void testToString_2 () throws Exception
void testToString_3 () throws Exception
void testToString_4 () throws Exception
void testToString_5 () throws Exception
void testGetAllele_0 () throws Exception
void testEquals_0 () throws Exception
void testEquals_1 () throws Exception
void testEquals_2 () throws Exception
void testEquals_3 () throws Exception
void testEquals_4 () throws Exception
void testEquals_4_2 () throws Exception
void testEquals_5 () throws Exception
void testSetAllele_0 () throws Exception
void testSetAllele_1 () throws Exception
void testSetAllele_2 () throws Exception
void testNewGene_0 () throws Exception
void testNewGene_1 () throws Exception
void testNewGene_2 () throws Exception
void testNewGene_3 () throws Exception
void testCleanup () throws Exception
void testPersistentRepresentation_0 () throws Exception
void testPersistentRepresentation_1 () throws Exception
void testPersistentRepresentation_2 () throws Exception
void testPersistentRepresentation_3 () throws Exception
void testPersistentRepresentation_4 () throws Exception
void testPersistentRepresentation_5 () throws Exception
void testPersistentRepresentation_6 () throws Exception
void testCompareTo_0 () throws Exception
void testCompareTo_1 () throws Exception
void testCompareTo_2 () throws Exception
void testCompareTo_3 () throws Exception
void testRemoveAlleles_0 () throws Exception
void testRemoveAlleles_1 () throws Exception
void testSetToRandomValue_0 () throws Exception
void testSetToRandomValue_1 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.19 $`
Additional Inherited Members
Detailed Description
Tests the MapGene class
Author
Klaus Meffert
Since
2.4
Definition at line 24 of file MapGeneTest.java.
Member Function Documentation
static Test org.jgap.impl.MapGeneTest.suite () [inline], [static]
Definition at line 29 of file MapGeneTest.java.
void org.jgap.impl.MapGeneTest.testCleanup () throws Exception [inline]
Definition at line 296 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testCompareTo_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 466 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.MapGene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testCompareTo_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 482 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.MapGene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testCompareTo_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 497 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.MapGene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testCompareTo_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 513 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.MapGene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testConstruct_0 () throws Exception [inline]
Definition at line 34 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.MapGeneTest.testConstruct_1 () throws Exception [inline]
Definition at line 40 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.MapGeneTest.testConstruct_2 () throws Exception [inline]
Definition at line 51 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testConstruct_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 68 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testEquals_0 () throws Exception [inline]
Definition at line 158 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testEquals_1 () throws Exception [inline]
Definition at line 166 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testEquals_2 () throws Exception [inline]
Definition at line 172 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testEquals_3 () throws Exception [inline]
Definition at line 180 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testEquals_4 () throws Exception [inline]
Definition at line 186 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testEquals_4_2 () throws Exception [inline]
Definition at line 196 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testEquals_5 () throws Exception [inline]
Definition at line 208 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testGetAllele_0 () throws Exception [inline]
Definition at line 134 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.MapGeneTest.testNewGene_0 () throws Exception [inline]
Exceptions
Exception
Since
2.5
Definition at line 242 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseGene.newGene(), and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.MapGeneTest.testNewGene_1 () throws Exception [inline]
Exceptions
Exception
Since
2.5
Definition at line 259 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.newGene().
void org.jgap.impl.MapGeneTest.testNewGene_2 () throws Exception [inline]
Exceptions
Exception
Since
2.5
Definition at line 270 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf, org.jgap.BaseGene.equals(), and org.jgap.BaseGene.newGene().
void org.jgap.impl.MapGeneTest.testNewGene_3 () throws Exception [inline]
Exceptions
Exception
Since
3.6
Definition at line 285 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf, org.jgap.BaseGene.equals(), and org.jgap.BaseGene.newGene().
void org.jgap.impl.MapGeneTest.testPersistentRepresentation_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 313 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testPersistentRepresentation_1 () throws Exception [inline]
Should be possible without exception
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 340 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testPersistentRepresentation_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 353 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseGene.getAllele(), and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.MapGeneTest.testPersistentRepresentation_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 378 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.Gene.getAllele(), and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.MapGeneTest.testPersistentRepresentation_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 399 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testPersistentRepresentation_5 () throws Exception [inline]
Possible without exception.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 423 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testPersistentRepresentation_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 440 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testRemoveAlleles_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 532 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.MapGene.getAlleles().
void org.jgap.impl.MapGeneTest.testRemoveAlleles_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 548 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.MapGene.getAlleles().
void org.jgap.impl.MapGeneTest.testSetAllele_0 () throws Exception [inline]
Set Allele to null, no exception should occur
Exceptions
Exception
Definition at line 220 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testSetAllele_1 () throws Exception [inline]
Definition at line 226 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testSetAllele_2 () throws Exception [inline]
Definition at line 232 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MapGeneTest.testSetToRandomValue_0 () throws Exception [inline]
Todo
Todo add test for applyMutation
Exceptions
Exception
Definition at line 573 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.MapGeneTest.testSetToRandomValue_1 () throws Exception [inline]
Definition at line 580 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.MapGene.getAlleles().
void org.jgap.impl.MapGeneTest.testToString_0 () throws Exception [inline]
Definition at line 75 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.MapGene.toString().
void org.jgap.impl.MapGeneTest.testToString_1 () throws Exception [inline]
Definition at line 81 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.MapGene.toString().
void org.jgap.impl.MapGeneTest.testToString_2 () throws Exception [inline]
Definition at line 88 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.MapGene.toString().
void org.jgap.impl.MapGeneTest.testToString_3 () throws Exception [inline]
Definition at line 96 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.MapGene.toString().
void org.jgap.impl.MapGeneTest.testToString_4 () throws Exception [inline]
Using different types as keys. Order of adding alleles not important!
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 111 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.MapGene.toString().
void org.jgap.impl.MapGeneTest.testToString_5 () throws Exception [inline]
Using different types as keys. Order of adding alleles not important!
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 126 of file MapGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.MapGene.toString().
Member Data Documentation
final String org.jgap.impl.MapGeneTest.CVS_REVISION = `$Revision: 1.19 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file MapGeneTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/MapGeneTest.java