org.jgap.impl.InversionOperator Class Reference
Public Member Functions
InversionOperator () throws InvalidConfigurationException
InversionOperator (Configuration a_config) throws InvalidConfigurationException
void operate (final Population a_population, final List a_candidateChromosomes)
int compareTo (final Object a_other)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.11 $`
Additional Inherited Members
Detailed Description
The inversion operator randomly selects one chromosomes from the population and inverses it by randomly picking a splitting locus on which to swap the first part with the last part of the chromosome.
Author
Klaus Meffert
Since
2.3
Definition at line 23 of file InversionOperator.java.
Constructor & Destructor Documentation
org.jgap.impl.InversionOperator.InversionOperator () throws InvalidConfigurationException [inline]
Default constructor.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.3
Definition at line 38 of file InversionOperator.java.
Referenced by org.jgap.impl.InversionOperator.compareTo().
org.jgap.impl.InversionOperator.InversionOperator (Configuration a_config) throws InvalidConfigurationException [inline]
Constructs a new instance of this operator.
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 53 of file InversionOperator.java.
Member Function Documentation
int org.jgap.impl.InversionOperator.compareTo (final Object a_other) [inline]
Compares the given GeneticOperator to this GeneticOperator.
Parameters
a_other the instance against which to compare this instance
Returns
a negative number if this instance is `less than` the given instance, zero if they are equal to each other, and a positive number if this is `greater than` the given instance
Author
Klaus Meffert
Since
2.6
Definition at line 124 of file InversionOperator.java.
References org.jgap.impl.InversionOperator.InversionOperator().
Referenced by org.jgap.impl.InversionOperatorTest.testCompareTo_0().
void org.jgap.impl.InversionOperator.operate (final Population a_population, final List a_candidateChromosomes) [inline]
Parameters
a_population the population to operate on
a_candidateChromosomes resulting chromosomes
Author
Klaus Meffert
Since
2.3
Implements org.jgap.GeneticOperator.
Definition at line 65 of file InversionOperator.java.
References org.jgap.util.ICloneable.clone(), org.jgap.BaseGeneticOperator.getConfiguration(), org.jgap.BaseGeneticOperator.m_monitorActive, and org.jgap.Population.size().
Member Data Documentation
final String org.jgap.impl.InversionOperator.CVS_REVISION = `$Revision: 1.11 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file InversionOperator.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/InversionOperator.java