org.jgap.util.randomX Class Reference
Public Member Functions
void setSeed ()
abstract byte nextByte ()
int nextInt ()
long nextLong ()
float nextFloat ()
double nextDouble ()
double nextGaussian ()
boolean nextBit ()
void nextByte (byte buf[], int buflen)
void nextByte (byte buf[])
short nextShort ()
Private Attributes
int nbits = 0
boolean iset = false
double gset
byte b
Detailed Description
Abstract superclass for emulations of java.util.Random with
various underlying generators.  These generators provide a
superset of the methods of the built-in Java generator, and
allow easy replacement of the low-level byte-stream random
generator without the need to reimplement the higher-level
calls.
The nature of the data returned by the functions in this class depends upon the generator provided by the class derived from it. If the generator is algorithmic, the data are pseudorandom; if a hardware generator is employed, genuine random data may be obtained. For brevity, in this document, we use random to refer to the data returned, whatever its actual source.
Designed and implemented in July 1996 by John Walker, kelvin@fourmilab.ch.
See Also
java.util.Random
Definition at line 25 of file randomX.java.
Member Function Documentation
boolean org.jgap.util.randomX.nextBit () [inline]
Returns
the next random bit, as a boolean.
Definition at line 130 of file randomX.java.
References org.jgap.util.randomX.b, org.jgap.util.randomX.nbits, and org.jgap.util.randomX.nextByte().
abstract byte org.jgap.util.randomX.nextByte () [pure virtual]
Return next [pseudo]random byte from low level generator. All generators derived from this class must implement nextByte().
Implemented in org.jgap.util.randomLEcuyer, org.jgap.util.randomMCG, org.jgap.util.randomJava, org.jgap.util.randomLCG, and org.jgap.util.randomHotBits.
Referenced by org.jgap.util.randomX.nextBit(), org.jgap.util.randomX.nextByte(), and org.jgap.util.randomX.nextShort().
void org.jgap.util.randomX.nextByte (byte buf[], int buflen) [inline]
    Fill a portion of an array of bytes with random data.
Parameters
buf array of byte to fill.
buflen number of bytes to store.
Definition at line 150 of file randomX.java.
References org.jgap.util.randomX.nextByte().
void org.jgap.util.randomX.nextByte (byte buf[]) [inline]
    Fill an array of bytes with random data.
Parameters
buf array of bytes to fill.
Definition at line 163 of file randomX.java.
References org.jgap.util.randomX.nextByte().
double org.jgap.util.randomX.nextDouble () [inline]
Returns
the next random, uniformly distributed, double value, greater than or equal to 0 and less than 1.
Definition at line 94 of file randomX.java.
References org.jgap.util.randomX.nextLong().
Referenced by org.jgap.util.randomX.nextGaussian().
float org.jgap.util.randomX.nextFloat () [inline]
Returns
the next random, uniformly distributed, float value, greater than or equal to 0 and less than 1.
Definition at line 87 of file randomX.java.
References org.jgap.util.randomX.nextInt().
double org.jgap.util.randomX.nextGaussian () [inline]
Returns
the next Gaussian (normal, or bell-curve) distributed random value, with mean of 0.0 and standard deviation 1.0.
Definition at line 105 of file randomX.java.
References org.jgap.util.randomX.gset, org.jgap.util.randomX.iset, and org.jgap.util.randomX.nextDouble().
int org.jgap.util.randomX.nextInt () [inline]
Returns
the next random, uniformly distributed, int value.
Definition at line 73 of file randomX.java.
References org.jgap.util.randomX.nextShort().
Referenced by org.jgap.util.randomX.nextFloat(), and org.jgap.util.randomX.nextLong().
long org.jgap.util.randomX.nextLong () [inline]
Returns
the next random, uniformly distributed, long value.
Definition at line 80 of file randomX.java.
References org.jgap.util.randomX.nextInt().
Referenced by org.jgap.util.randomX.nextDouble().
short org.jgap.util.randomX.nextShort () [inline]
Returns
the next random, uniformly distributed, short value.
Definition at line 170 of file randomX.java.
References org.jgap.util.randomX.nextByte().
Referenced by org.jgap.util.randomX.nextInt().
void org.jgap.util.randomX.setSeed () [inline]
Reset when seed changes. A generator which supports seed must call this method by super.setSeed() when its own setSeed(long) method is called. This allows randomX to discard any buffered data in the nextBit() and nextGaussian() methods so that subsequent calls will immediately reflect the new seed.
If a derived class does not permit specification of a seed (hardware-based generators, for example), it should declare:
private void setSeed(long seed) { }
which will hide the setSeed method from its users and cause a compile-time error if a program attempts to specify a seed.
Definition at line 49 of file randomX.java.
References org.jgap.util.randomX.iset, and org.jgap.util.randomX.nbits.
Member Data Documentation
byte org.jgap.util.randomX.b [private]
Definition at line 126 of file randomX.java.
Referenced by org.jgap.util.randomX.nextBit().
double org.jgap.util.randomX.gset [private]
Definition at line 99 of file randomX.java.
Referenced by org.jgap.util.randomX.nextGaussian().
boolean org.jgap.util.randomX.iset = false [private]
Definition at line 28 of file randomX.java.
Referenced by org.jgap.util.randomX.nextGaussian(), and org.jgap.util.randomX.setSeed().
int org.jgap.util.randomX.nbits = 0 [private]
Definition at line 27 of file randomX.java.
Referenced by org.jgap.util.randomX.nextBit(), and org.jgap.util.randomX.setSeed().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/util/randomX.java