examples.knapsack.KnapsackFitnessFunction Class Reference
Public Member Functions
KnapsackFitnessFunction (double a_knapsackVolume)
double evaluate (IChromosome a_subject)
Static Public Member Functions
static double getTotalVolume (IChromosome a_potentialSolution)
static int getNumberOfItemsAtGene (IChromosome a_potentialSolution, int a_position)
static int getTotalNumberOfItems (IChromosome a_potentialSolution)
Static Public Attributes
static final double MAX_BOUND = 1000000000.0d
Protected Member Functions
double volumeDifferenceBonus (double a_maxFitness, double a_volumeDifference)
double computeItemNumberPenalty (double a_maxFitness, int a_items)
Private Attributes
final double m_knapsackVolume
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.5 $`
static final double ZERO_DIFFERENCE_FITNESS = Math.sqrt(MAX_BOUND)
Detailed Description
Fitness function for the knapsack example.
Author
Klaus Meffert
Since
2.3
Definition at line 20 of file KnapsackFitnessFunction.java.
Constructor & Destructor Documentation
examples.knapsack.KnapsackFitnessFunction.KnapsackFitnessFunction (double a_knapsackVolume) [inline]
Definition at line 31 of file KnapsackFitnessFunction.java.
References examples.knapsack.KnapsackFitnessFunction.m_knapsackVolume, and examples.knapsack.KnapsackFitnessFunction.MAX_BOUND.
Member Function Documentation
double examples.knapsack.KnapsackFitnessFunction.computeItemNumberPenalty (double a_maxFitness, int a_items) [inline], [protected]
Calculates the penalty to apply to the fitness value based on the amount of items in the solution.
Parameters
a_maxFitness upper boundary for fitness value possible
a_items number of items in the solution
Returns
a penalty for the fitness value based on the number of items
Author
Klaus Meffert
Since
2.3
Definition at line 121 of file KnapsackFitnessFunction.java.
Referenced by examples.knapsack.KnapsackFitnessFunction.evaluate().
double examples.knapsack.KnapsackFitnessFunction.evaluate (IChromosome a_subject) [inline]
Determine the fitness of the given Chromosome instance. The higher the return value, the more fit the instance. This method should always return the same fitness value for two equivalent Chromosome instances.
Parameters
a_subject the Chromosome instance to evaluate
Returns
a positive double reflecting the fitness rating of the given Chromosome
Author
Klaus Meffert
Since
2.3
Definition at line 51 of file KnapsackFitnessFunction.java.
References examples.knapsack.KnapsackFitnessFunction.computeItemNumberPenalty(), examples.knapsack.KnapsackFitnessFunction.getTotalNumberOfItems(), examples.knapsack.KnapsackFitnessFunction.getTotalVolume(), examples.knapsack.KnapsackFitnessFunction.m_knapsackVolume, examples.knapsack.KnapsackFitnessFunction.MAX_BOUND, and examples.knapsack.KnapsackFitnessFunction.volumeDifferenceBonus().
static int examples.knapsack.KnapsackFitnessFunction.getNumberOfItemsAtGene (IChromosome a_potentialSolution, int a_position) [inline], [static]
Retrieves the number of items represented by the given potential solution at the given gene position.
Parameters
a_potentialSolution the potential solution to evaluate
a_position the gene position to evaluate
Returns
the number of items represented by the potential solution at the given gene position
Author
Klaus Meffert
Since
2.3
Definition at line 168 of file KnapsackFitnessFunction.java.
Referenced by examples.knapsack.KnapsackFitnessFunction.getTotalNumberOfItems(), and examples.knapsack.KnapsackFitnessFunction.getTotalVolume().
static int examples.knapsack.KnapsackFitnessFunction.getTotalNumberOfItems (IChromosome a_potentialSolution) [inline], [static]
Returns the total number of items represented by all of the genes in the given potential solution.
Parameters
a_potentialSolution the potential solution to evaluate
Returns
the total number of items represented by the given Chromosome
Author
Klaus Meffert
Since
2.3
Definition at line 185 of file KnapsackFitnessFunction.java.
References examples.knapsack.KnapsackFitnessFunction.getNumberOfItemsAtGene().
Referenced by examples.knapsack.KnapsackFitnessFunction.evaluate().
static double examples.knapsack.KnapsackFitnessFunction.getTotalVolume (IChromosome a_potentialSolution) [inline], [static]
Calculates the total amount of change (in cents) represented by the given potential solution and returns that amount.
Parameters
a_potentialSolution the potential solution to evaluate
Returns
the total amount of change (in cents) represented by the given solution
Author
Klaus Meffert
Since
2.3
Definition at line 147 of file KnapsackFitnessFunction.java.
References examples.knapsack.KnapsackFitnessFunction.getNumberOfItemsAtGene().
Referenced by examples.knapsack.KnapsackFitnessFunction.evaluate().
double examples.knapsack.KnapsackFitnessFunction.volumeDifferenceBonus (double a_maxFitness, double a_volumeDifference) [inline], [protected]
Bonus calculation of fitness value.
Parameters
a_maxFitness maximum fitness value appliable
a_volumeDifference volume difference in ccm for the items problem
Returns
bonus for given volume difference
Author
Klaus Meffert
Since
2.3
Definition at line 98 of file KnapsackFitnessFunction.java.
Referenced by examples.knapsack.KnapsackFitnessFunction.evaluate().
Member Data Documentation
final String examples.knapsack.KnapsackFitnessFunction.CVS_REVISION = `$Revision: 1.5 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 23 of file KnapsackFitnessFunction.java.
final double examples.knapsack.KnapsackFitnessFunction.m_knapsackVolume [private]
Definition at line 25 of file KnapsackFitnessFunction.java.
Referenced by examples.knapsack.KnapsackFitnessFunction.evaluate(), and examples.knapsack.KnapsackFitnessFunction.KnapsackFitnessFunction().
final double examples.knapsack.KnapsackFitnessFunction.MAX_BOUND = 1000000000.0d [static]
Definition at line 27 of file KnapsackFitnessFunction.java.
Referenced by examples.knapsack.KnapsackFitnessFunction.evaluate(), examples.knapsack.KnapsackFitnessFunction.KnapsackFitnessFunction(), and examples.knapsack.KnapsackMain.main().
final double examples.knapsack.KnapsackFitnessFunction.ZERO_DIFFERENCE_FITNESS = Math.sqrt(MAX_BOUND) [static], [private]
Definition at line 29 of file KnapsackFitnessFunction.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/knapsack/KnapsackFitnessFunction.java