org.jgap.data.config.ConfigPropertyTest Class Reference
Public Member Functions
void testConstruct_0 () throws Exception
void testGetName_0 () throws Exception
void testGetWidget_0 () throws Exception
void testGetLabel_0 () throws Exception
void testAddValue_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
static final int NUM_CHROMS = 5
static final int NUM_GENES = 2
Additional Inherited Members
Detailed Description
Tests the ConfigProperty class
Author
Klaus Meffert
Since
3.0
Definition at line 21 of file ConfigPropertyTest.java.
Member Function Documentation
static Test org.jgap.data.config.ConfigPropertyTest.suite () [inline], [static]
Definition at line 32 of file ConfigPropertyTest.java.
void org.jgap.data.config.ConfigPropertyTest.testAddValue_0 () throws Exception [inline]
Definition at line 69 of file ConfigPropertyTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.data.config.ConfigProperty.getValuesIter().
void org.jgap.data.config.ConfigPropertyTest.testConstruct_0 () throws Exception [inline]
Definition at line 37 of file ConfigPropertyTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.data.config.ConfigProperty.getLabel(), org.jgap.data.config.ConfigProperty.getName(), org.jgap.data.config.ConfigProperty.getValuesIter(), and org.jgap.data.config.ConfigProperty.getWidget().
void org.jgap.data.config.ConfigPropertyTest.testGetLabel_0 () throws Exception [inline]
Definition at line 62 of file ConfigPropertyTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.data.config.ConfigProperty.getLabel().
void org.jgap.data.config.ConfigPropertyTest.testGetName_0 () throws Exception [inline]
Definition at line 45 of file ConfigPropertyTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.data.config.ConfigProperty.getLabel(), and org.jgap.data.config.ConfigProperty.getName().
void org.jgap.data.config.ConfigPropertyTest.testGetWidget_0 () throws Exception [inline]
Definition at line 55 of file ConfigPropertyTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.data.config.ConfigProperty.getWidget().
Member Data Documentation
final String org.jgap.data.config.ConfigPropertyTest.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file ConfigPropertyTest.java.
final int org.jgap.data.config.ConfigPropertyTest.NUM_CHROMS = 5 [static], [private]
Definition at line 27 of file ConfigPropertyTest.java.
final int org.jgap.data.config.ConfigPropertyTest.NUM_GENES = 2 [static], [private]
Definition at line 30 of file ConfigPropertyTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/data/config/ConfigPropertyTest.java