org.jgap.util.FileKit Class Reference
Classes
class MyFileNameFilter
Static Public Member Functions
static void copyFile (String source, String dest) throws FileNotFoundException, IOException
static void copyFile (String source, String dest, int a_offset) throws FileNotFoundException, IOException
static String getFilename (String name_and_path)
static String getFilename (String name_and_path, String fileseparator)
static String getCurrentDir () throws IOException
static String addSubDir (String dir, String subDir, boolean makeNice)
static String addFilename (String dir, String a_filename)
static String getConformPath (String path, boolean makeNice)
static String getConformPath (String path)
static String getConformPath (String path, String a_fileseparator)
static String getNiceURL (String url, String separator)
static String removeDoubleSeparators (String dir)
static boolean directoryExists (String a_dir)
static boolean existsFile (String a_filename)
static boolean deleteFile (String a_filename)
static boolean deleteFile (File a_file)
static boolean deleteDirectory (File a_dir)
static ClassLoader loadJar (String a_filename) throws Exception
static Manifest getManifestOfJar (String a_filename) throws Exception
static String getJGAPVersion (Manifest a_JGAPManifest)
static String getModuleVersion (Manifest a_JGAPManifest)
static String getVersionOfModule (String a_filename) throws Exception
static String getVersionOfJGAP (String a_filename) throws Exception
static String toJarFileName (String a_filename)
static void createDirectory (String a_dirname) throws IOException
static Vector readFile (String a_filename) throws IOException
static String getTempDir ()
static String[] listFilesInDir (String a_dir, String a_mask) throws Exception
Static Public Attributes
static String fileseparator = System.getProperty(`file.separator`)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.12 $`
Detailed Description
Contains helper functions related to the file system.
Author
Klaus Meffert
Definition at line 23 of file FileKit.java.
Member Function Documentation
static String org.jgap.util.FileKit.addFilename (String dir, String a_filename) [inline], [static]
Definition at line 155 of file FileKit.java.
References org.jgap.util.FileKit.getConformPath().
static String org.jgap.util.FileKit.addSubDir (String dir, String subDir, boolean makeNice) [inline], [static]
Adds a subdir to a given dir and returns the resulting dir.
Parameters
dir the original dir
subDir the subdir to add
makeNice true: call getNiceDir afterwards
Returns
dir with subdir added
Author
Klaus Meffert
Since
3.2
Definition at line 149 of file FileKit.java.
References org.jgap.util.FileKit.getConformPath().
static void org.jgap.util.FileKit.copyFile (String source, String dest) throws FileNotFoundException, IOException [inline], [static]
Copies a complete file.
Parameters
source source file name
dest destination file name or destination path (filename then taken from source)
Exceptions
FileNotFoundException
IOException
Author
Klaus Meffert
Since
3.2
Definition at line 41 of file FileKit.java.
static void org.jgap.util.FileKit.copyFile (String source, String dest, int a_offset) throws FileNotFoundException, IOException [inline], [static]
Copies a file.
Parameters
source source file name
dest destination file name or destination path (filename then taken from source)
a_offset start offset of file to copy (0 is begin of file)
Exceptions
FileNotFoundException
IOException
Author
Klaus Meffert
Since
3.2
Definition at line 59 of file FileKit.java.
References org.jgap.util.FileKit.getFilename().
static void org.jgap.util.FileKit.createDirectory (String a_dirname) throws IOException [inline], [static]
Creates a directory, and if necessary, any of its parent directories.
Parameters
a_dirname name of the dir to create
Exceptions
IOException
Author
Klaus Meffert
Since
3.2
Definition at line 442 of file FileKit.java.
static boolean org.jgap.util.FileKit.deleteDirectory (File a_dir) [inline], [static]
Deletes a directory from disk, also if it is non-empty.
Parameters
a_dir name of file to delete
Returns
true if deletion successful
Author
Klaus Meffert
Since
3.4.3
Definition at line 294 of file FileKit.java.
static boolean org.jgap.util.FileKit.deleteFile (String a_filename) [inline], [static]
Deletes a file from disk.
Parameters
a_filename name of file to delete
Returns
true if deletion successful
Definition at line 260 of file FileKit.java.
References org.jgap.util.FileKit.getConformPath().
static boolean org.jgap.util.FileKit.deleteFile (File a_file) [inline], [static]
Deletes a file from disk.
Parameters
a_file name of file to delete
Returns
true if deletion successful
Author
Klaus Meffert
Since
3.4.3
Definition at line 275 of file FileKit.java.
static boolean org.jgap.util.FileKit.directoryExists (String a_dir) [inline], [static]
Definition at line 243 of file FileKit.java.
static boolean org.jgap.util.FileKit.existsFile (String a_filename) [inline], [static]
Definition at line 248 of file FileKit.java.
References org.jgap.util.FileKit.getConformPath().
static String org.jgap.util.FileKit.getConformPath (String path, boolean makeNice) [inline], [static]
Definition at line 160 of file FileKit.java.
References org.jgap.util.FileKit.fileseparator, and org.jgap.util.FileKit.getNiceURL().
Referenced by org.jgap.util.FileKit.addFilename(), org.jgap.util.FileKit.addSubDir(), org.jgap.util.FileKit.deleteFile(), org.jgap.util.FileKit.existsFile(), and org.jgap.util.FileKit.getConformPath().
static String org.jgap.util.FileKit.getConformPath (String path) [inline], [static]
Definition at line 169 of file FileKit.java.
References org.jgap.util.FileKit.fileseparator, and org.jgap.util.FileKit.getConformPath().
static String org.jgap.util.FileKit.getConformPath (String path, String a_fileseparator) [inline], [static]
Definition at line 173 of file FileKit.java.
References org.jgap.util.FileKit.removeDoubleSeparators().
static String org.jgap.util.FileKit.getCurrentDir () throws IOException [inline], [static]
Returns
current directory of the application
Exceptions
IOException
Author
Klaus Meffert
Since
3.2
Definition at line 132 of file FileKit.java.
static String org.jgap.util.FileKit.getFilename (String name_and_path) [inline], [static]
Definition at line 82 of file FileKit.java.
References org.jgap.util.FileKit.fileseparator.
Referenced by org.jgap.util.FileKit.copyFile().
static String org.jgap.util.FileKit.getFilename (String name_and_path, String fileseparator) [inline], [static]
Extract file name from a given path+filename.
Parameters
name_and_path input
fileseparator Slash or Backslash
Returns
extracted file nmame
Author
Klaus Meffert
Since
3.2
Todo
Todo possibly use File.getName() instead?
Definition at line 96 of file FileKit.java.
References org.jgap.util.FileKit.fileseparator.
static String org.jgap.util.FileKit.getJGAPVersion (Manifest a_JGAPManifest) [inline], [static]
Parameters
a_JGAPManifest manifest with JGAP-specific information
Returns
version the jar file is working with (or version of the JGAP library in case the file is the JGAP library)
Author
Klaus Meffert
Since
3.2
Definition at line 357 of file FileKit.java.
Referenced by org.jgap.util.FileKit.getVersionOfJGAP().
static Manifest org.jgap.util.FileKit.getManifestOfJar (String a_filename) throws Exception [inline], [static]
Retrieve the manifest included in the given jar.
Parameters
a_filename jar file name
Returns
Manifest included in the given jar
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 338 of file FileKit.java.
Referenced by org.jgap.util.FileKit.getVersionOfJGAP(), and org.jgap.util.FileKit.getVersionOfModule().
static String org.jgap.util.FileKit.getModuleVersion (Manifest a_JGAPManifest) [inline], [static]
Parameters
a_JGAPManifest Manifest with JGAP-specific information
Returns
version of the module represented by the jar
Author
Klaus Meffert
Since
3.2
Definition at line 369 of file FileKit.java.
Referenced by org.jgap.util.FileKit.getVersionOfModule().
static String org.jgap.util.FileKit.getNiceURL (String url, String separator) [inline], [static]
Makes an URL nice by bringing it into a normalized (i.e. convenient) form.
Parameters
url any URL
separator the separator to remove duplicates of
Returns
prettified URL
Author
Klaus Meffert
Since
3.2
Definition at line 197 of file FileKit.java.
References org.jgap.util.FileKit.removeDoubleSeparators().
Referenced by org.jgap.util.FileKit.getConformPath().
static String org.jgap.util.FileKit.getTempDir () [inline], [static]
Returns
temporary directory
Author
Klaus Meffert
Since
3.3.3
Definition at line 483 of file FileKit.java.
static String org.jgap.util.FileKit.getVersionOfJGAP (String a_filename) throws Exception [inline], [static]
See getJGAPVersion.
Parameters
a_filename name of a JGAP jar
Returns
version the jar file is working wit (or version of the JGAP library in case the file is the JGAP library)
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 405 of file FileKit.java.
References org.jgap.util.FileKit.getJGAPVersion(), and org.jgap.util.FileKit.getManifestOfJar().
static String org.jgap.util.FileKit.getVersionOfModule (String a_filename) throws Exception [inline], [static]
See getModuleVersion.
Parameters
a_filename name of a JGAP jar
Returns
version of the module represented by the jar
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 384 of file FileKit.java.
References org.jgap.util.FileKit.getManifestOfJar(), and org.jgap.util.FileKit.getModuleVersion().
static String [] org.jgap.util.FileKit.listFilesInDir (String a_dir, String a_mask) throws Exception [inline], [static]
Returns the files within a directory that match a given pattern. No directories are returned.
Parameters
a_dir String
a_mask String
Returns
String[]
Exceptions
Exception
Author
Klaus Meffert
Since
3.3.4
Definition at line 499 of file FileKit.java.
static ClassLoader org.jgap.util.FileKit.loadJar (String a_filename) throws Exception [inline], [static]
Loads a jar file and returns a class loader to access the jar's classes.
Parameters
a_filename the full jar file name, e.g.: C:/jgap/lib/ext/ashcroft.jar
Returns
ClassLoader the class loader with which to access the loaded classes, e.g. by <classloader>.loadClass(<classname including package>), e.g.: cl.loadClass(`com.thoughtworks.ashcroft.runtime.JohnAshcroft`);
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 320 of file FileKit.java.
static Vector org.jgap.util.FileKit.readFile (String a_filename) throws IOException [inline], [static]
Reads a text file.
Parameters
a_filename name of text file
Returns
list of read text lines
Exceptions
IOException
Author
Klaus Meffert
Since
3.2
Definition at line 464 of file FileKit.java.
static String org.jgap.util.FileKit.removeDoubleSeparators (String dir) [inline], [static]
Removes duplicate separators from an URL.
Parameters
dir name of directory including file name
Returns
prettified URL
Author
Klaus Meffert
Since
3.2
Definition at line 222 of file FileKit.java.
References org.jgap.util.FileKit.fileseparator.
Referenced by org.jgap.util.FileKit.getConformPath(), and org.jgap.util.FileKit.getNiceURL().
static String org.jgap.util.FileKit.toJarFileName (String a_filename) [inline], [static]
Converts an ordinary file name into a jar filename that can be used with JarClassLoader.
Parameters
a_filename the name to convert
Returns
converted name
Author
Klaus Meffert
Since
3.2
Definition at line 425 of file FileKit.java.
Member Data Documentation
final String org.jgap.util.FileKit.CVS_REVISION = `$Revision: 1.12 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file FileKit.java.
String org.jgap.util.FileKit.fileseparator = System.getProperty(`file.separator`) [static]
Definition at line 27 of file FileKit.java.
Referenced by org.jgap.util.FileKit.getConformPath(), org.jgap.util.FileKit.getFilename(), org.jgap.util.FileKit.removeDoubleSeparators(), and org.jgap.util.FileKitTest.replaceSeparator().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/util/FileKit.java