org.jgap.impl.StringGene Class Reference
Public Member Functions
StringGene () throws InvalidConfigurationException
StringGene (final Configuration a_config) throws InvalidConfigurationException
StringGene (final Configuration a_config, final int a_minLength, final int a_maxLength) throws InvalidConfigurationException
StringGene (final Configuration a_config, final int a_minLength, final int a_maxLength, final String a_alphabet) throws InvalidConfigurationException
void setToRandomValue (final RandomGenerator a_numberGenerator)
void setValueFromPersistentRepresentation (final String a_representation) throws UnsupportedRepresentationException
String getPersistentRepresentation () throws UnsupportedOperationException
String getBusinessKey ()
void setAllele (final Object a_newValue)
int compareTo (Object a_other)
int size ()
int getMaxLength ()
int getMinLength ()
void setMinLength (int m_minLength)
void setMaxLength (int m_maxLength)
String getAlphabet ()
void setAlphabet (String a_alphabet)
String toString ()
String stringValue ()
void applyMutation (int index, double a_percentage)
Static Public Attributes
static final String ALPHABET_CHARACTERS_UPPER
static final String ALPHABET_CHARACTERS_LOWER
static final String ALPHABET_CHARACTERS_DIGITS = `0123456789`
static final String ALPHABET_CHARACTERS_SPECIAL = `+.*/\\,;@`
Protected Member Functions
Gene newGeneInternal ()
Object getInternalValue ()
Private Member Functions
boolean isValidAlphabet (String a_value, String a_alphabet)
Private Attributes
int m_minLength
int m_maxLength
String m_alphabet
String m_value
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.58 $`
Detailed Description
A Gene implementation that supports a string for its allele. The valid alphabet as well as the minimum and maximum length of the string can be specified.
An alphabet == null indicates that all characters are seen as valid.
 An alphabet == `` indicates that no character is seen to be valid.
Partly copied from IntegerGene.
Author
Klaus Meffert
Audrius Meskauskas
Since
1.1
Definition at line 27 of file StringGene.java.
Constructor & Destructor Documentation
org.jgap.impl.StringGene.StringGene () throws InvalidConfigurationException [inline]
Default constructor, sets minimum and maximum length to arbitrary. You need to set the valid alphabet later!
Do not use this constructor with a sample chromosome set in the configuration.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
1.1
Definition at line 66 of file StringGene.java.
Referenced by org.jgap.impl.StringGene.compareTo(), and org.jgap.impl.StringGene.newGeneInternal().
org.jgap.impl.StringGene.StringGene (final Configuration a_config) throws InvalidConfigurationException [inline]
Default constructor, sets minimum and maximum length to arbitrary. You need to set the valid alphabet later!
Do not use this constructor with a sample chromosome set in the configuration.
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 83 of file StringGene.java.
org.jgap.impl.StringGene.StringGene (final Configuration a_config, final int a_minLength, final int a_maxLength) throws InvalidConfigurationException [inline]
Constructor, allows to specify minimum and maximum lengths of the string held by this gene. You need to set the valid alphabet later!
Do not use this constructor with a sample chromosome set in the configuration.
Parameters
a_config the configuration to use
a_minLength minimum valid length of allele
a_maxLength maximum valid length of allele
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
1.1
Definition at line 102 of file StringGene.java.
org.jgap.impl.StringGene.StringGene (final Configuration a_config, final int a_minLength, final int a_maxLength, final String a_alphabet) throws InvalidConfigurationException [inline]
Constructor, allows to specify minimum and maximum lengths of the string held by this gene, as well as the valid alphabet. This constructor can be used to construct a sample chromosome with a configuration.
Parameters
a_config the configuration to use
a_minLength minimum valid length of an allele
a_maxLength maximum valid length of an allele
a_alphabet valid alphabet for an allele
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.0
Definition at line 122 of file StringGene.java.
References org.jgap.impl.StringGene.m_maxLength, org.jgap.impl.StringGene.m_minLength, and org.jgap.impl.StringGene.setAlphabet().
Member Function Documentation
void org.jgap.impl.StringGene.applyMutation (int index, double a_percentage) [inline]
Applies a mutation of a given intensity (percentage) onto the atomic element at given index (NumberGenes only have one atomic element).
Parameters
index index of atomic element, between 0 and size()-1
a_percentage percentage of mutation (greater than -1 and smaller than 1).
Author
Klaus Meffert
Since
1.1
Implements org.jgap.Gene.
Definition at line 568 of file StringGene.java.
References org.jgap.BaseGene.getConfiguration(), org.jgap.impl.StringGene.m_alphabet, org.jgap.impl.StringGene.setAllele(), and org.jgap.impl.StringGene.stringValue().
int org.jgap.impl.StringGene.compareTo (Object a_other) [inline]
Compares this StringGene with the specified object (which must also be a StringGene) for order, which is determined by the String value of this Gene compared to the one provided for comparison.
Parameters
a_other the StringGene to be compared to this StringGene
Returns
a negative int, zero, or a positive int as this object is less than, equal to, or greater than the object provided for comparison
Exceptions
ClassCastException if the specified object's type prevents it from being compared to this StringGene
Author
Klaus Meffert
Since
1.1
Definition at line 409 of file StringGene.java.
References org.jgap.BaseGene.compareApplicationData(), org.jgap.BaseGene.getApplicationData(), org.jgap.BaseGene.isCompareApplicationData(), org.jgap.impl.StringGene.m_value, and org.jgap.impl.StringGene.StringGene().
String org.jgap.impl.StringGene.getAlphabet () [inline]
Definition at line 472 of file StringGene.java.
References org.jgap.impl.StringGene.m_alphabet.
Referenced by org.jgap.impl.StringGeneTest.testConstruct_0(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_5(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_5_2(), and org.jgap.impl.StringGeneTest.testSetAlphabet_1().
String org.jgap.impl.StringGene.getBusinessKey () [inline]
Returns
business key
Author
Klaus Meffert
Since
3.2
Implements org.jgap.IBusinessKey.
Definition at line 331 of file StringGene.java.
References org.jgap.impl.StringGene.m_maxLength, org.jgap.impl.StringGene.m_minLength, org.jgap.impl.StringGene.m_value, and org.jgap.Gene.PERSISTENT_FIELD_DELIMITER.
Object org.jgap.impl.StringGene.getInternalValue () [inline], [protected], [virtual]
Each Gene implementation holds its own m_value object keeping the allele value. In your Gene implementation, just return it with this method (see org.jgap.impl.BooleanGene for example)
Returns
the m_value object
Author
Klaus Meffert
Since
2.2
Implements org.jgap.BaseGene.
Definition at line 616 of file StringGene.java.
References org.jgap.impl.StringGene.m_value.
int org.jgap.impl.StringGene.getMaxLength () [inline]
Definition at line 456 of file StringGene.java.
References org.jgap.impl.StringGene.m_maxLength.
Referenced by org.jgap.impl.StringGeneTest.testConstruct_0(), and org.jgap.impl.StringGeneTest.testSetMinMaxLength_0().
int org.jgap.impl.StringGene.getMinLength () [inline]
Definition at line 460 of file StringGene.java.
References org.jgap.impl.StringGene.m_minLength.
Referenced by org.jgap.impl.StringGeneTest.testConstruct_0(), and org.jgap.impl.StringGeneTest.testSetMinMaxLength_0().
String org.jgap.impl.StringGene.getPersistentRepresentation () throws UnsupportedOperationException [inline]
Retrieves a string representation of this Gene that includes any information required to reconstruct it at a later time, such as its value and internal state. This string will be used to represent this Gene in XML persistence. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Returns
string representation of this Gene's current state
Exceptions
UnsupportedOperationException to indicate that no implementation is provided for this method
Author
Klaus Meffert
Since
1.1
Implements org.jgap.IPersistentRepresentation.
Definition at line 306 of file StringGene.java.
References org.jgap.BaseGene.encode(), org.jgap.impl.StringGene.m_alphabet, org.jgap.impl.StringGene.m_maxLength, org.jgap.impl.StringGene.m_minLength, org.jgap.impl.StringGene.m_value, and org.jgap.Gene.PERSISTENT_FIELD_DELIMITER.
Referenced by org.jgap.impl.StringGeneTest.testPersistentRepresentation_7(), and org.jgap.impl.StringGeneTest.testPersistentRepresentation_9().
boolean org.jgap.impl.StringGene.isValidAlphabet (String a_value, String a_alphabet) [inline], [private]
Checks whether a string value is valid concerning a given alphabet.
Parameters
a_value the value to check
a_alphabet the valid alphabet to check against
Returns
true: given string value is valid
Author
Klaus Meffert
Since
1.1
Definition at line 535 of file StringGene.java.
Referenced by org.jgap.impl.StringGene.setAllele(), and org.jgap.impl.StringGene.setValueFromPersistentRepresentation().
Gene org.jgap.impl.StringGene.newGeneInternal () [inline], [protected], [virtual]
Provides an implementation-independent means for creating new Gene instances.
Returns
a new Gene instance of the same type and with the same setup as this concrete Gene
Author
Klaus Meffert
Since
1.1
Implements org.jgap.BaseGene.
Definition at line 383 of file StringGene.java.
References org.jgap.BaseGene.getConfiguration(), org.jgap.BaseGene.getConstraintChecker(), org.jgap.impl.StringGene.m_alphabet, org.jgap.impl.StringGene.m_maxLength, org.jgap.impl.StringGene.m_minLength, and org.jgap.impl.StringGene.StringGene().
void org.jgap.impl.StringGene.setAllele (final Object a_newValue) [inline]
Sets the value (allele) of this Gene to the new given value. This class expects the value to be a String instance. If the value is shorter or longer than the minimum or maximum length or any character is not within the valid alphabet an exception is thrown.
Parameters
a_newValue the new value of this Gene instance
Author
Klaus Meffert
Since
1.1
Definition at line 347 of file StringGene.java.
References org.jgap.BaseGene.getConstraintChecker(), org.jgap.impl.StringGene.isValidAlphabet(), org.jgap.impl.StringGene.m_alphabet, org.jgap.impl.StringGene.m_maxLength, org.jgap.impl.StringGene.m_minLength, and org.jgap.impl.StringGene.m_value.
Referenced by org.jgap.impl.StringGene.applyMutation(), and org.jgap.impl.StringGene.setToRandomValue().
void org.jgap.impl.StringGene.setAlphabet (String a_alphabet) [inline]
Sets the valid alphabet of the StringGene. The caller needs to care that there are no doublettes in the alphabet. Otherwise there is no guarantee for correct functioning of the class!
Parameters
a_alphabet valid alphabet for allele
Author
Klaus Meffert
Since
1.1
Definition at line 485 of file StringGene.java.
References org.jgap.impl.StringGene.m_alphabet.
Referenced by org.jgap.impl.StringGene.StringGene().
void org.jgap.impl.StringGene.setMaxLength (int m_maxLength) [inline]
Definition at line 468 of file StringGene.java.
References org.jgap.impl.StringGene.m_maxLength.
void org.jgap.impl.StringGene.setMinLength (int m_minLength) [inline]
Definition at line 464 of file StringGene.java.
References org.jgap.impl.StringGene.m_minLength.
void org.jgap.impl.StringGene.setToRandomValue (final RandomGenerator a_numberGenerator) [inline]
Sets the value (allele) of this Gene to a random String according to the valid alphabet and boundaries of length.
Parameters
a_numberGenerator the random number generator that should be used to create any random values. It's important to use this generator to maintain the user's flexibility to configure the genetic engine to use the random number generator of their choice
Author
Klaus Meffert
Since
1.1
Definition at line 153 of file StringGene.java.
References org.jgap.impl.StringGene.m_alphabet, org.jgap.impl.StringGene.m_maxLength, org.jgap.impl.StringGene.m_minLength, and org.jgap.impl.StringGene.setAllele().
void org.jgap.impl.StringGene.setValueFromPersistentRepresentation (final String a_representation) throws UnsupportedRepresentationException [inline]
Sets the value and internal state of this Gene from the string representation returned by a previous invocation of the getPersistentRepresentation() method. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Parameters
a_representation the string representation retrieved from a prior call to the getPersistentRepresentation() method
Exceptions
UnsupportedRepresentationException if this Gene implementation does not support the given string representation
Author
Klaus Meffert
Since
1.1
Definition at line 205 of file StringGene.java.
References org.jgap.BaseGene.decode(), org.jgap.impl.StringGene.isValidAlphabet(), org.jgap.impl.StringGene.m_alphabet, org.jgap.impl.StringGene.m_maxLength, org.jgap.impl.StringGene.m_minLength, org.jgap.impl.StringGene.m_value, and org.jgap.Gene.PERSISTENT_FIELD_DELIMITER.
int org.jgap.impl.StringGene.size () [inline]
Returns
the size of the gene, i.e the number of atomic elements. Always 1 for numbers
Since
1.1
Implements org.jgap.Gene.
Definition at line 452 of file StringGene.java.
String org.jgap.impl.StringGene.stringValue () [inline]
Retrieves the String value of this Gene, which may be more convenient in some cases than the more general getAllele() method.
Returns
the String value of this Gene
Since
1.1
Definition at line 522 of file StringGene.java.
References org.jgap.impl.StringGene.m_value.
Referenced by org.jgap.impl.StringGene.applyMutation(), org.jgap.impl.StringGeneTest.testSetAllele_5(), and org.jgap.impl.StringGeneTest.testSetAllele_6().
String org.jgap.impl.StringGene.toString () [inline]
Retrieves a string representation of this StringGene's value that may be useful for display purposes.
Returns
a string representation of this StringGene's value
Author
Klaus Meffert
Since
1.1
Implements org.jgap.Gene.
Definition at line 498 of file StringGene.java.
References org.jgap.impl.StringGene.m_value.
Referenced by org.jgap.impl.StringGeneTest.testToString_1(), and org.jgap.impl.StringGeneTest.testToString_2().
Member Data Documentation
final String org.jgap.impl.StringGene.ALPHABET_CHARACTERS_DIGITS = `0123456789` [static]
Definition at line 36 of file StringGene.java.
final String org.jgap.impl.StringGene.ALPHABET_CHARACTERS_LOWER [static]
Initial value:
=
      "abcdefghijklmnopqrstuvwxyz"
Definition at line 33 of file StringGene.java.
Referenced by org.jgap.impl.StringGeneTest.testApplyMutation_4(), org.jgap.impl.StringGeneTest.testApplyMutation_5(), and org.jgap.impl.StringGeneTest.testSetToRandomValue_5().
final String org.jgap.impl.StringGene.ALPHABET_CHARACTERS_SPECIAL = `+.*/\\,;@` [static]
Definition at line 38 of file StringGene.java.
final String org.jgap.impl.StringGene.ALPHABET_CHARACTERS_UPPER [static]
Initial value:
=
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
Definition at line 30 of file StringGene.java.
Referenced by org.jgap.impl.CompositeGenePersistentReprTest.createSampleNestedGene(), org.jgap.impl.StringGeneTest.testSetToRandomValue_0(), and org.jgap.impl.StringGeneTest.testSetToRandomValue_1().
final String org.jgap.impl.StringGene.CVS_REVISION = `$Revision: 1.58 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 41 of file StringGene.java.
String org.jgap.impl.StringGene.m_alphabet [private]
Definition at line 47 of file StringGene.java.
Referenced by org.jgap.impl.StringGene.applyMutation(), org.jgap.impl.StringGene.getAlphabet(), org.jgap.impl.StringGene.getPersistentRepresentation(), org.jgap.impl.StringGene.newGeneInternal(), org.jgap.impl.StringGene.setAllele(), org.jgap.impl.StringGene.setAlphabet(), org.jgap.impl.StringGene.setToRandomValue(), and org.jgap.impl.StringGene.setValueFromPersistentRepresentation().
int org.jgap.impl.StringGene.m_maxLength [private]
Definition at line 45 of file StringGene.java.
Referenced by org.jgap.impl.StringGene.getBusinessKey(), org.jgap.impl.StringGene.getMaxLength(), org.jgap.impl.StringGene.getPersistentRepresentation(), org.jgap.impl.StringGene.newGeneInternal(), org.jgap.impl.StringGene.setAllele(), org.jgap.impl.StringGene.setMaxLength(), org.jgap.impl.StringGene.setToRandomValue(), org.jgap.impl.StringGene.setValueFromPersistentRepresentation(), and org.jgap.impl.StringGene.StringGene().
int org.jgap.impl.StringGene.m_minLength [private]
Definition at line 43 of file StringGene.java.
Referenced by org.jgap.impl.StringGene.getBusinessKey(), org.jgap.impl.StringGene.getMinLength(), org.jgap.impl.StringGene.getPersistentRepresentation(), org.jgap.impl.StringGene.newGeneInternal(), org.jgap.impl.StringGene.setAllele(), org.jgap.impl.StringGene.setMinLength(), org.jgap.impl.StringGene.setToRandomValue(), org.jgap.impl.StringGene.setValueFromPersistentRepresentation(), and org.jgap.impl.StringGene.StringGene().
String org.jgap.impl.StringGene.m_value [private]
References the internal String value (allele) of this Gene.
Definition at line 52 of file StringGene.java.
Referenced by org.jgap.impl.StringGene.compareTo(), org.jgap.impl.StringGene.getBusinessKey(), org.jgap.impl.StringGene.getInternalValue(), org.jgap.impl.StringGene.getPersistentRepresentation(), org.jgap.impl.StringGene.setAllele(), org.jgap.impl.StringGene.setValueFromPersistentRepresentation(), org.jgap.impl.StringGene.stringValue(), and org.jgap.impl.StringGene.toString().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/StringGene.java