org.jgap.gp.GPProblem Class Reference
Public Member Functions
GPProblem (GPConfiguration a_conf) throws InvalidConfigurationException
GPProblem ()
abstract GPGenotype create () throws InvalidConfigurationException
void showTree (IGPProgram a_prog, String a_filename) throws InvalidConfigurationException
void showTree (IGPProgram a_prog, String a_filename, TreeBranchRenderer a_treeBranchRenderer, TreeNodeRenderer a_treeNodeRenderer) throws InvalidConfigurationException
TreeNode createTree (IGPProgram a_prog) throws InvalidConfigurationException
GPConfiguration getGPConfiguration ()
Protected Member Functions
void setGPConfiguration (GPConfiguration a_conf)
Private Attributes
GPConfiguration m_conf
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.8 $`
Detailed Description
Abstract base class for all GP problems. See packages examples.gp and examples.grid for sample implementations.
Author
Klaus Meffert
Since
3.0
Definition at line 29 of file GPProblem.java.
Constructor & Destructor Documentation
org.jgap.gp.GPProblem.GPProblem (GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Definition at line 35 of file GPProblem.java.
References org.jgap.gp.GPProblem.m_conf.
org.jgap.gp.GPProblem.GPProblem () [inline]
Default constructor for dynamic instantiation.
Author
Klaus Meffert
Since
3.2
Definition at line 49 of file GPProblem.java.
Member Function Documentation
abstract GPGenotype org.jgap.gp.GPProblem.create () throws InvalidConfigurationException [pure virtual]
Returns
newly created GPGenotype
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Implemented in examples.gp.tictactoe.TicTacToeMain, examples.gp.symbolicRegression.SymbolicRegression, examples.gp.anttrail.AntTrailProblem, examples.gp.paintedDesert.PaintedDesertProblem, examples.gp.island.IslandGPThread, examples.gp.Fibonacci, examples.gp.MathProblem, examples.gp.KarubProblem, examples.gp.monalisa.core.DrawingProblem, and examples.gp.SimpleExample.
TreeNode org.jgap.gp.GPProblem.createTree (IGPProgram a_prog) throws InvalidConfigurationException [inline]
Creates a tree out of a given GP program.
Parameters
a_prog the GPGenotype to visualize a tree for
Returns
the TreeNode object corresponding to the GP program
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 137 of file GPProblem.java.
References org.jgap.gp.GPProblem.m_conf, and org.jgap.gp.CommandGene.VoidClass.
Referenced by org.jgap.gp.GPProblem.showTree().
GPConfiguration org.jgap.gp.GPProblem.getGPConfiguration () [inline]
Returns
the GPConfiguration set
Author
Klaus Meffert
Since
3.0
Definition at line 173 of file GPProblem.java.
References org.jgap.gp.GPProblem.m_conf.
Referenced by examples.gp.SimpleExample.create(), examples.gp.monalisa.core.DrawingProblem.create(), examples.gp.KarubProblem.create(), examples.gp.MathProblem.create(), examples.gp.Fibonacci.create(), examples.gp.island.IslandGPThread.create(), examples.gp.paintedDesert.PaintedDesertProblem.create(), examples.gp.anttrail.AntTrailProblem.create(), and examples.gp.symbolicRegression.SymbolicRegression.create().
void org.jgap.gp.GPProblem.setGPConfiguration (GPConfiguration a_conf) [inline], [protected]
Sets the configuration. Only use in case of dynamic instantiation (in case constructor with parameter GPConfiguration is not used).
Parameters
a_conf the configuration to set
Author
Klaus Meffert
Since
3.2
Definition at line 186 of file GPProblem.java.
References org.jgap.gp.GPProblem.m_conf.
void org.jgap.gp.GPProblem.showTree (IGPProgram a_prog, String a_filename) throws InvalidConfigurationException [inline]
Creates a graphical tree out of a given GP program and saves it to a file.
Parameters
a_prog the GP program to visualize a tree for
a_filename the name of the file to save the tree in
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 73 of file GPProblem.java.
References org.jgap.gp.GPProblem.createTree().
void org.jgap.gp.GPProblem.showTree (IGPProgram a_prog, String a_filename, TreeBranchRenderer a_treeBranchRenderer, TreeNodeRenderer a_treeNodeRenderer) throws InvalidConfigurationException [inline]
Creates a tree out of a given GP program and saves it to a file. Allows to preset the tree renderers.
Parameters
a_prog the GP program to visualize a tree for
a_filename the name of the file to save the tree in
a_treeBranchRenderer renderer for the tree's branches
a_treeNodeRenderer renderer for the tree's nodes
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 107 of file GPProblem.java.
References org.jgap.gp.GPProblem.createTree().
Member Data Documentation
final String org.jgap.gp.GPProblem.CVS_REVISION = `$Revision: 1.8 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 31 of file GPProblem.java.
GPConfiguration org.jgap.gp.GPProblem.m_conf [private]
Definition at line 33 of file GPProblem.java.
Referenced by org.jgap.gp.GPProblem.createTree(), org.jgap.gp.GPProblem.getGPConfiguration(), org.jgap.gp.GPProblem.GPProblem(), and org.jgap.gp.GPProblem.setGPConfiguration().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/GPProblem.java