org.jgap.impl.JGAPFactory Class Reference
Public Member Functions
JGAPFactory (boolean a_useCaching)
void setParameters (final Collection a_parameters)
Collection getParameters ()
RandomGenerator createRandomGenerator ()
int registerCloneHandler (final ICloneHandler a_cloneHandler)
ICloneHandler removeCloneHandler (final int a_index)
ICloneHandler getCloneHandlerFor (final Object a_obj, final Class a_classToClone)
int registerInitializer (final IInitializer a_chromIniter)
IInitializer removeInitializer (final int a_index)
IInitializer getInitializerFor (final Object a_obj, final Class a_class)
void setGeneticOperatorConstraint (final IGeneticOperatorConstraint a_constraint)
IGeneticOperatorConstraint getGeneticOperatorConstraint ()
ICompareToHandler getCompareToHandlerFor (Object a_obj, Class a_classToCompareTo)
int registerCompareToHandler (ICompareToHandler a_compareToHandler)
ICompareToHandler removeCompareToHandler (final int a_index)
boolean isUseCaching ()
Object clone ()
boolean equals (Object a_other)
int compareTo (Object a_other)
String getUniqueKey (String a_context)
Protected Member Functions
IHandler findHandlerFor (final Object a_obj, final Class a_class, final List a_list, final IHandler a_default, final String a_listID)
Private Attributes
List m_parameters
List m_cloneHandlers
List m_initer
List m_compareHandlers
ICloneHandler m_defaultCloneHandler
IInitializer m_defaultIniter
ICompareToHandler m_defaultComparer
IGeneticOperatorConstraint m_geneticOpConstraint
transient LRUCache m_cache
boolean m_useCaching
Map< String, Long > m_lastKeys
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.19 $`
Additional Inherited Members
Detailed Description
Central factory for creating default objects to use, e.g. random generators. Could be made configurable. An instance of JGAPFactory can be accessed via
Genotype.getConfiguration().getJGAPFactory();
To use your own factory class instead, use:
System.setProperty(Configuration.PROPERTY_JGAPFACTORY_CLASS, `myFactory`);
 with `myFactory` representing the name of your class to use.
Author
Klaus Meffert
Since
2.6
Definition at line 31 of file JGAPFactory.java.
Constructor & Destructor Documentation
org.jgap.impl.JGAPFactory.JGAPFactory (boolean a_useCaching) [inline]
Definition at line 58 of file JGAPFactory.java.
References org.jgap.impl.JGAPFactory.m_cache, org.jgap.impl.JGAPFactory.m_cloneHandlers, org.jgap.impl.JGAPFactory.m_compareHandlers, org.jgap.impl.JGAPFactory.m_defaultCloneHandler, org.jgap.impl.JGAPFactory.m_defaultComparer, org.jgap.impl.JGAPFactory.m_defaultIniter, org.jgap.impl.JGAPFactory.m_initer, org.jgap.impl.JGAPFactory.m_lastKeys, and org.jgap.impl.JGAPFactory.m_useCaching.
Referenced by org.jgap.impl.JGAPFactory.compareTo().
Member Function Documentation
Object org.jgap.impl.JGAPFactory.clone () [inline]
Returns
clone of the current object instance
Todo
Todo check if it works this way
Implements org.jgap.util.ICloneable.
Definition at line 339 of file JGAPFactory.java.
int org.jgap.impl.JGAPFactory.compareTo (Object a_other) [inline]
Parameters
a_other other object to compare
Returns
as always
Author
Klaus Meffert
Since
3.2
Definition at line 371 of file JGAPFactory.java.
References org.jgap.impl.JGAPFactory.JGAPFactory(), org.jgap.impl.JGAPFactory.m_cloneHandlers, org.jgap.impl.JGAPFactory.m_compareHandlers, org.jgap.impl.JGAPFactory.m_defaultCloneHandler, org.jgap.impl.JGAPFactory.m_defaultComparer, org.jgap.impl.JGAPFactory.m_geneticOpConstraint, and org.jgap.impl.JGAPFactory.m_initer.
Referenced by org.jgap.impl.JGAPFactory.equals().
RandomGenerator org.jgap.impl.JGAPFactory.createRandomGenerator () [inline]
Returns
newly created instance of a RandomGenerator
Implements org.jgap.IJGAPFactory.
Definition at line 94 of file JGAPFactory.java.
Referenced by org.jgap.impl.JGAPFactoryTest.testCreateRandomGenerator_0().
boolean org.jgap.impl.JGAPFactory.equals (Object a_other) [inline]
The equals-method
Parameters
a_other sic
Returns
sic
Author
Klaus Meffert
Since
3.2
Definition at line 356 of file JGAPFactory.java.
References org.jgap.impl.JGAPFactory.compareTo().
IHandler org.jgap.impl.JGAPFactory.findHandlerFor (final Object a_obj, final Class a_class, final List a_list, final IHandler a_default, final String a_listID) [inline], [protected]
Helper: Finds a handler for a given Object or Class, returns the default handler, if one is provided. Uses an LRU cache to speedup things!
Parameters
a_obj the object to find a handler for (maybe null)
a_class the class to find a handler for (maybe null)
a_list list of available handlers
a_default a default handler to return in none other is found
a_listID arbitrary unique string for accessing the cache
Returns
the handler found, or null if none registered
Author
Klaus Meffert
Since
2.6
Definition at line 268 of file JGAPFactory.java.
References org.jgap.IHandler.isHandlerFor(), and org.jgap.impl.JGAPFactory.m_useCaching.
Referenced by org.jgap.impl.JGAPFactory.getCloneHandlerFor(), org.jgap.impl.JGAPFactory.getCompareToHandlerFor(), and org.jgap.impl.JGAPFactory.getInitializerFor().
ICloneHandler org.jgap.impl.JGAPFactory.getCloneHandlerFor (final Object a_obj, final Class a_classToClone) [inline]
Retrieves a clone handler capable of clone the given class.
Parameters
a_obj the object to clone (maybe null)
a_classToClone the class to clone an object of (maybe null)
Returns
the clone handler found capable of clone the given class, or null if none registered
Author
Klaus Meffert
Since
2.6
Definition at line 139 of file JGAPFactory.java.
References org.jgap.impl.JGAPFactory.findHandlerFor(), org.jgap.impl.JGAPFactory.m_cloneHandlers, and org.jgap.impl.JGAPFactory.m_defaultCloneHandler.
Referenced by org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_0(), org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_1(), org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_2(), org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_3(), org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_4(), org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_5(), org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_6(), and org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_7().
ICompareToHandler org.jgap.impl.JGAPFactory.getCompareToHandlerFor (Object a_obj, Class a_classToCompareTo) [inline]
Retrieves a handler capable of comparing two instances of the given class.
Parameters
a_obj the object to compare (maybe null)
a_classToCompareTo the class instances to compare (maybe null)
Returns
the handler found capable of comparing instances of the given class, or null if none registered
Author
Klaus Meffert
Since
2.6
Implements org.jgap.IJGAPFactory.
Definition at line 216 of file JGAPFactory.java.
References org.jgap.impl.JGAPFactory.findHandlerFor(), org.jgap.impl.JGAPFactory.m_compareHandlers, and org.jgap.impl.JGAPFactory.m_defaultComparer.
IGeneticOperatorConstraint org.jgap.impl.JGAPFactory.getGeneticOperatorConstraint () [inline]
Implements org.jgap.IJGAPFactory.
Definition at line 201 of file JGAPFactory.java.
References org.jgap.impl.JGAPFactory.m_geneticOpConstraint.
IInitializer org.jgap.impl.JGAPFactory.getInitializerFor (final Object a_obj, final Class a_class) [inline]
Retrieves an initializer capable of initializing the Object of the given class.
Parameters
a_obj the object to init (maybe null)
a_class the object class to init (maybe null)
Returns
new instance (should be!) of initialized object
Author
Klaus Meffert
Since
2.6
Definition at line 188 of file JGAPFactory.java.
References org.jgap.impl.JGAPFactory.findHandlerFor(), org.jgap.impl.JGAPFactory.m_defaultIniter, and org.jgap.impl.JGAPFactory.m_initer.
Collection org.jgap.impl.JGAPFactory.getParameters () [inline]
Returns
Collection of generic parameters
Author
Klaus Meffert
Since
3.0
Definition at line 90 of file JGAPFactory.java.
References org.jgap.impl.JGAPFactory.m_parameters.
Referenced by org.jgap.impl.JGAPFactoryTest.testSetParameters_0().
String org.jgap.impl.JGAPFactory.getUniqueKey (String a_context) [inline]
Returns a unique key for the given context. The key uses the current date and time and a GUID. Thus it is quite probable, that the key is unique worldwide.
Parameters
a_context the context to get the next key for, like `Chromosome`.
Returns
the unique key for the given context
Author
Klaus Meffert
Since
3.5
Definition at line 401 of file JGAPFactory.java.
boolean org.jgap.impl.JGAPFactory.isUseCaching () [inline]
Returns
true: caching used, false: no caching used
Author
Klaus Meffert
Since
3.0
Definition at line 335 of file JGAPFactory.java.
References org.jgap.impl.JGAPFactory.m_useCaching.
Referenced by org.jgap.impl.JGAPFactoryTest.testConstruct_0(), and org.jgap.impl.JGAPFactoryTest.testConstruct_1().
int org.jgap.impl.JGAPFactory.registerCloneHandler (final ICloneHandler a_cloneHandler) [inline]
Registers a clone handler that could be retrieved by getCloneHandlerFor(Class).
Parameters
a_cloneHandler the ICloneHandler to register
Returns
index of the added clone handler, needed when removeCloneHandler will be called
Author
Klaus Meffert
Since
2.6
Definition at line 109 of file JGAPFactory.java.
int org.jgap.impl.JGAPFactory.registerCompareToHandler (ICompareToHandler a_compareToHandler) [inline]
Registers a compareTo-handler that could be retrieved by getCompareToHandlerFor(Class).
Parameters
a_compareToHandler the ICompareToHandler to register
Returns
index of the added handler, needed when removeCompareToHandler will be called
Author
Klaus Meffert
Since
2.6
Implements org.jgap.IJGAPFactory.
Definition at line 235 of file JGAPFactory.java.
int org.jgap.impl.JGAPFactory.registerInitializer (final IInitializer a_chromIniter) [inline]
Registers an initializer that could be retrieved by getInitializerFor(Class).
Parameters
a_chromIniter the IChromosomeInitializer to register
Returns
index of the added initializer, needed when removeChromosomeInitializer will be called
Author
Klaus Meffert
Since
2.6
Definition at line 158 of file JGAPFactory.java.
ICloneHandler org.jgap.impl.JGAPFactory.removeCloneHandler (final int a_index) [inline]
Removes a clone handler at a given index (which is obtained from registerCloneHandler).
Parameters
a_index the index of the clone handler to remove
Returns
the removed ICloneHandler, or Exception if not successfull
Author
Klaus Meffert
Since
2.6
Definition at line 124 of file JGAPFactory.java.
Referenced by org.jgap.impl.JGAPFactoryTest.testRegisterCloneHandler_0().
ICompareToHandler org.jgap.impl.JGAPFactory.removeCompareToHandler (final int a_index) [inline]
Removes a compareTo-handler at a given index (which is obtained from registerCompareToHandler).
Parameters
a_index the index of the handler to remove
Returns
the removed handler, or Exception if not successfull
Author
Klaus Meffert
Since
2.6
Definition at line 250 of file JGAPFactory.java.
Referenced by org.jgap.impl.JGAPFactoryTest.testRegisterCompareToHandler_0().
IInitializer org.jgap.impl.JGAPFactory.removeInitializer (final int a_index) [inline]
Removes an initializer at a given index (which is obtained from registerInitializer).
Parameters
a_index the index of the initializer to remove
Returns
the removed IInitializer, or null if not successfull
Author
Klaus Meffert
Since
2.6
Definition at line 173 of file JGAPFactory.java.
Referenced by org.jgap.impl.JGAPFactoryTest.testRegisterInitializer_0().
void org.jgap.impl.JGAPFactory.setGeneticOperatorConstraint (final IGeneticOperatorConstraint a_constraint) [inline]
Definition at line 196 of file JGAPFactory.java.
References org.jgap.impl.JGAPFactory.m_geneticOpConstraint.
void org.jgap.impl.JGAPFactory.setParameters (final Collection a_parameters) [inline]
Allows setting (generic because unknown) parameters for creating objects.
Parameters
a_parameters Collection of generic parameters
Author
Klaus Meffert
Since
2.6
Definition at line 80 of file JGAPFactory.java.
References org.jgap.impl.JGAPFactory.m_parameters.
Member Data Documentation
final String org.jgap.impl.JGAPFactory.CVS_REVISION = `$Revision: 1.19 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 34 of file JGAPFactory.java.
transient LRUCache org.jgap.impl.JGAPFactory.m_cache [private]
Definition at line 52 of file JGAPFactory.java.
Referenced by org.jgap.impl.JGAPFactory.JGAPFactory().
List org.jgap.impl.JGAPFactory.m_cloneHandlers [private]
Definition at line 38 of file JGAPFactory.java.
Referenced by org.jgap.impl.JGAPFactory.compareTo(), org.jgap.impl.JGAPFactory.getCloneHandlerFor(), and org.jgap.impl.JGAPFactory.JGAPFactory().
List org.jgap.impl.JGAPFactory.m_compareHandlers [private]
Definition at line 42 of file JGAPFactory.java.
Referenced by org.jgap.impl.JGAPFactory.compareTo(), org.jgap.impl.JGAPFactory.getCompareToHandlerFor(), and org.jgap.impl.JGAPFactory.JGAPFactory().
ICloneHandler org.jgap.impl.JGAPFactory.m_defaultCloneHandler [private]
Definition at line 44 of file JGAPFactory.java.
Referenced by org.jgap.impl.JGAPFactory.compareTo(), org.jgap.impl.JGAPFactory.getCloneHandlerFor(), and org.jgap.impl.JGAPFactory.JGAPFactory().
ICompareToHandler org.jgap.impl.JGAPFactory.m_defaultComparer [private]
Definition at line 48 of file JGAPFactory.java.
Referenced by org.jgap.impl.JGAPFactory.compareTo(), org.jgap.impl.JGAPFactory.getCompareToHandlerFor(), and org.jgap.impl.JGAPFactory.JGAPFactory().
IInitializer org.jgap.impl.JGAPFactory.m_defaultIniter [private]
Definition at line 46 of file JGAPFactory.java.
Referenced by org.jgap.impl.JGAPFactory.getInitializerFor(), and org.jgap.impl.JGAPFactory.JGAPFactory().
IGeneticOperatorConstraint org.jgap.impl.JGAPFactory.m_geneticOpConstraint [private]
Definition at line 50 of file JGAPFactory.java.
Referenced by org.jgap.impl.JGAPFactory.compareTo(), org.jgap.impl.JGAPFactory.getGeneticOperatorConstraint(), and org.jgap.impl.JGAPFactory.setGeneticOperatorConstraint().
List org.jgap.impl.JGAPFactory.m_initer [private]
Definition at line 40 of file JGAPFactory.java.
Referenced by org.jgap.impl.JGAPFactory.compareTo(), org.jgap.impl.JGAPFactory.getInitializerFor(), and org.jgap.impl.JGAPFactory.JGAPFactory().
Map<String,Long> org.jgap.impl.JGAPFactory.m_lastKeys [private]
Definition at line 56 of file JGAPFactory.java.
Referenced by org.jgap.impl.JGAPFactory.JGAPFactory().
List org.jgap.impl.JGAPFactory.m_parameters [private]
Definition at line 36 of file JGAPFactory.java.
Referenced by org.jgap.impl.JGAPFactory.getParameters(), and org.jgap.impl.JGAPFactory.setParameters().
boolean org.jgap.impl.JGAPFactory.m_useCaching [private]
Definition at line 54 of file JGAPFactory.java.
Referenced by org.jgap.impl.JGAPFactory.findHandlerFor(), org.jgap.impl.JGAPFactory.isUseCaching(), and org.jgap.impl.JGAPFactory.JGAPFactory().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/JGAPFactory.java