org.jgap.gp.function.ReadTerminal Class Reference
Public Member Functions
ReadTerminal (final GPConfiguration a_conf, Class a_returnType, String a_storageName) throws InvalidConfigurationException
ReadTerminal (final GPConfiguration a_conf, Class a_returnType, String a_storageName, int a_subReturnType) throws InvalidConfigurationException
String toString ()
String getName ()
int execute_int (ProgramChromosome c, int n, Object[] args)
long execute_long (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
boolean isValid (ProgramChromosome a_program)
int compareTo (Object a_other)
boolean equals (Object a_other)
Object clone ()
Private Attributes
String m_storageName
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.15 $`
Additional Inherited Members
Detailed Description
Reads a value from the internal memory.
Author
Klaus Meffert
Since
3.0
Definition at line 24 of file ReadTerminal.java.
Constructor & Destructor Documentation
org.jgap.gp.function.ReadTerminal.ReadTerminal (final GPConfiguration a_conf, Class a_returnType, String a_storageName) throws InvalidConfigurationException [inline]
Definition at line 35 of file ReadTerminal.java.
Referenced by org.jgap.gp.function.ReadTerminal.clone(), org.jgap.gp.function.ReadTerminal.compareTo(), and org.jgap.gp.function.ReadTerminal.equals().
org.jgap.gp.function.ReadTerminal.ReadTerminal (final GPConfiguration a_conf, Class a_returnType, String a_storageName, int a_subReturnType) throws InvalidConfigurationException [inline]
Definition at line 41 of file ReadTerminal.java.
References org.jgap.gp.function.ReadTerminal.m_storageName.
Member Function Documentation
Object org.jgap.gp.function.ReadTerminal.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 178 of file ReadTerminal.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), org.jgap.gp.CommandGene.getSubReturnType(), org.jgap.gp.function.ReadTerminal.m_storageName, and org.jgap.gp.function.ReadTerminal.ReadTerminal().
int org.jgap.gp.function.ReadTerminal.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.0
Definition at line 139 of file ReadTerminal.java.
References org.jgap.gp.function.ReadTerminal.m_storageName, and org.jgap.gp.function.ReadTerminal.ReadTerminal().
boolean org.jgap.gp.function.ReadTerminal.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Klaus Meffert
Since
3.0
Definition at line 159 of file ReadTerminal.java.
References org.jgap.gp.function.ReadTerminal.m_storageName, and org.jgap.gp.function.ReadTerminal.ReadTerminal().
double org.jgap.gp.function.ReadTerminal.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 93 of file ReadTerminal.java.
References org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.function.ReadTerminal.m_storageName.
float org.jgap.gp.function.ReadTerminal.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 104 of file ReadTerminal.java.
References org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.function.ReadTerminal.m_storageName.
int org.jgap.gp.function.ReadTerminal.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 65 of file ReadTerminal.java.
References org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.function.ReadTerminal.m_storageName.
long org.jgap.gp.function.ReadTerminal.execute_long (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 82 of file ReadTerminal.java.
References org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.function.ReadTerminal.m_storageName.
Object org.jgap.gp.function.ReadTerminal.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 115 of file ReadTerminal.java.
References org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.function.ReadTerminal.m_storageName.
String org.jgap.gp.function.ReadTerminal.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 61 of file ReadTerminal.java.
boolean org.jgap.gp.function.ReadTerminal.isValid (ProgramChromosome a_program) [inline]
Definition at line 125 of file ReadTerminal.java.
String org.jgap.gp.function.ReadTerminal.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 51 of file ReadTerminal.java.
References org.jgap.gp.function.ReadTerminal.m_storageName.
Member Data Documentation
final String org.jgap.gp.function.ReadTerminal.CVS_REVISION = `$Revision: 1.15 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file ReadTerminal.java.
String org.jgap.gp.function.ReadTerminal.m_storageName [private]
Symbolic name of the storage. Must correspond with a chosen name for an other command working with memory (otherwise it would make no sense).
Definition at line 33 of file ReadTerminal.java.
Referenced by org.jgap.gp.function.ReadTerminal.clone(), org.jgap.gp.function.ReadTerminal.compareTo(), org.jgap.gp.function.ReadTerminal.equals(), org.jgap.gp.function.ReadTerminal.execute_double(), org.jgap.gp.function.ReadTerminal.execute_float(), org.jgap.gp.function.ReadTerminal.execute_int(), org.jgap.gp.function.ReadTerminal.execute_long(), org.jgap.gp.function.ReadTerminal.execute_object(), org.jgap.gp.function.ReadTerminal.ReadTerminal(), and org.jgap.gp.function.ReadTerminal.toString().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/ReadTerminal.java