org.jgap.audit.PermutingConfiguration Class Reference
Public Member Functions
PermutingConfiguration ()
void init ()
PermutingConfiguration (Configuration a_conf) throws InvalidConfigurationException
void addRandomGeneratorSlot (RandomGenerator a_randomGenerator)
void addNaturalSelector (NaturalSelector a_naturalSel, boolean a_egal)
void addNaturalSelectorSlot (NaturalSelector a_naturalSelector)
synchronized void addGeneticOperator (GeneticOperator a_geneticOp)
void addGeneticOperatorSlot (GeneticOperator a_geneticOperator)
void addFitnessFunctionSlot (FitnessFunction a_fitnessFunction)
Configuration next () throws InvalidConfigurationException
boolean hasNext ()
Private Member Functions
List nextList (int index, List list)
Private Attributes
List m_randomGeneratorSlots
int m_randomGeneratorIndex
List m_naturalSelectorSlots
int m_naturalSelectorIndex
List m_geneticOperatorSlots
int m_geneticOperatorIndex
List m_fitnessFunctionSlots
int m_fitnessFunctionIndex
int m_componentIndex
Configuration m_configuration
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.9 $`
Additional Inherited Members
Detailed Description
Configuration that allows for permutating several components of it for evaluation/auditing purposes.
Author
Klaus Meffert
Since
2.2
Definition at line 22 of file PermutingConfiguration.java.
Constructor & Destructor Documentation
org.jgap.audit.PermutingConfiguration.PermutingConfiguration () [inline]
Definition at line 50 of file PermutingConfiguration.java.
References org.jgap.audit.PermutingConfiguration.init().
org.jgap.audit.PermutingConfiguration.PermutingConfiguration (Configuration a_conf) throws InvalidConfigurationException [inline]
Initializes the configuration by preselecting important parameters from the input configuration object
Parameters
a_conf Configuration
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.2
Definition at line 76 of file PermutingConfiguration.java.
References org.jgap.Configuration.setChromosomePool(), org.jgap.Configuration.setEventManager(), org.jgap.Configuration.setFitnessEvaluator(), org.jgap.Configuration.setFitnessFunction(), org.jgap.Configuration.setMinimumPopSizePercent(), org.jgap.Configuration.setPopulationSize(), org.jgap.Configuration.setRandomGenerator(), and org.jgap.Configuration.setSampleChromosome().
Member Function Documentation
void org.jgap.audit.PermutingConfiguration.addFitnessFunctionSlot (FitnessFunction a_fitnessFunction) [inline]
Definition at line 119 of file PermutingConfiguration.java.
synchronized void org.jgap.audit.PermutingConfiguration.addGeneticOperator (GeneticOperator a_geneticOp) [inline]
Definition at line 110 of file PermutingConfiguration.java.
void org.jgap.audit.PermutingConfiguration.addGeneticOperatorSlot (GeneticOperator a_geneticOperator) [inline]
Definition at line 115 of file PermutingConfiguration.java.
void org.jgap.audit.PermutingConfiguration.addNaturalSelector (NaturalSelector a_naturalSel, boolean a_egal) [inline]
Definition at line 101 of file PermutingConfiguration.java.
void org.jgap.audit.PermutingConfiguration.addNaturalSelectorSlot (NaturalSelector a_naturalSelector) [inline]
Definition at line 106 of file PermutingConfiguration.java.
void org.jgap.audit.PermutingConfiguration.addRandomGeneratorSlot (RandomGenerator a_randomGenerator) [inline]
Definition at line 97 of file PermutingConfiguration.java.
boolean org.jgap.audit.PermutingConfiguration.hasNext () [inline]
Definition at line 247 of file PermutingConfiguration.java.
References org.jgap.audit.PermutingConfiguration.m_componentIndex, and org.jgap.audit.PermutingConfiguration.m_geneticOperatorSlots.
Referenced by org.jgap.audit.EvaluatorTest.testHasNext_0(), and org.jgap.audit.PermutingConfigurationTest.testPermute_0().
void org.jgap.audit.PermutingConfiguration.init () [inline]
Definition at line 55 of file PermutingConfiguration.java.
References org.jgap.audit.PermutingConfiguration.m_componentIndex, org.jgap.audit.PermutingConfiguration.m_fitnessFunctionIndex, org.jgap.audit.PermutingConfiguration.m_fitnessFunctionSlots, org.jgap.audit.PermutingConfiguration.m_geneticOperatorIndex, org.jgap.audit.PermutingConfiguration.m_geneticOperatorSlots, org.jgap.audit.PermutingConfiguration.m_naturalSelectorIndex, org.jgap.audit.PermutingConfiguration.m_naturalSelectorSlots, org.jgap.audit.PermutingConfiguration.m_randomGeneratorIndex, and org.jgap.audit.PermutingConfiguration.m_randomGeneratorSlots.
Referenced by org.jgap.audit.PermutingConfiguration.PermutingConfiguration().
Configuration org.jgap.audit.PermutingConfiguration.next () throws InvalidConfigurationException [inline]
Todo
Todo make permutation below computed dynamic and not static
Todo
Todo introduce new parameters: populationSize, setPreservFittestIndividual, MAX_ALLOWED_EVOLUTIONS
Todo
Todo allow for `false`
Todo
Todo BulkFitnessOffsetRemover vs. FitnessFunction
Definition at line 123 of file PermutingConfiguration.java.
References org.jgap.Configuration.Configuration(), org.jgap.Configuration.getChromosomePool(), org.jgap.Configuration.getEventManager(), org.jgap.Configuration.getFitnessEvaluator(), org.jgap.Configuration.getFitnessFunction(), org.jgap.Configuration.getMinimumPopSizePercent(), org.jgap.Configuration.getPopulationSize(), org.jgap.Configuration.getRandomGenerator(), org.jgap.Configuration.getSampleChromosome(), org.jgap.audit.PermutingConfiguration.m_componentIndex, org.jgap.audit.PermutingConfiguration.m_configuration, org.jgap.audit.PermutingConfiguration.m_fitnessFunctionIndex, org.jgap.audit.PermutingConfiguration.m_fitnessFunctionSlots, org.jgap.audit.PermutingConfiguration.m_geneticOperatorIndex, org.jgap.audit.PermutingConfiguration.m_geneticOperatorSlots, org.jgap.audit.PermutingConfiguration.m_naturalSelectorIndex, org.jgap.audit.PermutingConfiguration.m_naturalSelectorSlots, org.jgap.audit.PermutingConfiguration.m_randomGeneratorIndex, org.jgap.audit.PermutingConfiguration.m_randomGeneratorSlots, org.jgap.audit.PermutingConfiguration.nextList(), org.jgap.Configuration.PROPERTY_FITFUNC_INST, and org.jgap.Configuration.setFitnessFunction().
List org.jgap.audit.PermutingConfiguration.nextList (int index, List list) [inline], [private]
Returns a subset of a given list acording to the index given. If a bit in the binary number represented by the index is set then the element at this index in the list will be included in the result list
Parameters
index int
list List
Returns
List
Definition at line 227 of file PermutingConfiguration.java.
Referenced by org.jgap.audit.PermutingConfiguration.next().
Member Data Documentation
final String org.jgap.audit.PermutingConfiguration.CVS_REVISION = `$Revision: 1.9 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file PermutingConfiguration.java.
int org.jgap.audit.PermutingConfiguration.m_componentIndex [private]
Definition at line 43 of file PermutingConfiguration.java.
Referenced by org.jgap.audit.PermutingConfiguration.hasNext(), org.jgap.audit.PermutingConfiguration.init(), and org.jgap.audit.PermutingConfiguration.next().
Configuration org.jgap.audit.PermutingConfiguration.m_configuration [private]
The resulting configuration as determined by permutation.
Definition at line 48 of file PermutingConfiguration.java.
Referenced by org.jgap.audit.PermutingConfiguration.next().
int org.jgap.audit.PermutingConfiguration.m_fitnessFunctionIndex [private]
Definition at line 41 of file PermutingConfiguration.java.
Referenced by org.jgap.audit.PermutingConfiguration.init(), and org.jgap.audit.PermutingConfiguration.next().
List org.jgap.audit.PermutingConfiguration.m_fitnessFunctionSlots [private]
Definition at line 39 of file PermutingConfiguration.java.
Referenced by org.jgap.audit.PermutingConfiguration.init(), and org.jgap.audit.PermutingConfiguration.next().
int org.jgap.audit.PermutingConfiguration.m_geneticOperatorIndex [private]
Definition at line 37 of file PermutingConfiguration.java.
Referenced by org.jgap.audit.PermutingConfiguration.init(), and org.jgap.audit.PermutingConfiguration.next().
List org.jgap.audit.PermutingConfiguration.m_geneticOperatorSlots [private]
Definition at line 35 of file PermutingConfiguration.java.
Referenced by org.jgap.audit.PermutingConfiguration.hasNext(), org.jgap.audit.PermutingConfiguration.init(), and org.jgap.audit.PermutingConfiguration.next().
int org.jgap.audit.PermutingConfiguration.m_naturalSelectorIndex [private]
Definition at line 33 of file PermutingConfiguration.java.
Referenced by org.jgap.audit.PermutingConfiguration.init(), and org.jgap.audit.PermutingConfiguration.next().
List org.jgap.audit.PermutingConfiguration.m_naturalSelectorSlots [private]
Definition at line 31 of file PermutingConfiguration.java.
Referenced by org.jgap.audit.PermutingConfiguration.init(), and org.jgap.audit.PermutingConfiguration.next().
int org.jgap.audit.PermutingConfiguration.m_randomGeneratorIndex [private]
Definition at line 29 of file PermutingConfiguration.java.
Referenced by org.jgap.audit.PermutingConfiguration.init(), and org.jgap.audit.PermutingConfiguration.next().
List org.jgap.audit.PermutingConfiguration.m_randomGeneratorSlots [private]
Definition at line 27 of file PermutingConfiguration.java.
Referenced by org.jgap.audit.PermutingConfiguration.init(), and org.jgap.audit.PermutingConfiguration.next().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/audit/PermutingConfiguration.java