org.jgap.gp.function.ArcTangent Class Reference
Classes
interface Compatible
Public Member Functions
ArcTangent (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException
String toString ()
String getName ()
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
The arc tangent command.
Author
Klaus Meffert
Since
3.3.4
Definition at line 23 of file ArcTangent.java.
Constructor & Destructor Documentation
org.jgap.gp.function.ArcTangent.ArcTangent (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 28 of file ArcTangent.java.
Referenced by org.jgap.gp.function.ArcTangent.clone().
Member Function Documentation
Object org.jgap.gp.function.ArcTangent.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 72 of file ArcTangent.java.
References org.jgap.gp.function.ArcTangent.ArcTangent(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.CommandGene.getReturnType().
double org.jgap.gp.function.ArcTangent.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 52 of file ArcTangent.java.
float org.jgap.gp.function.ArcTangent.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 47 of file ArcTangent.java.
Object org.jgap.gp.function.ArcTangent.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 57 of file ArcTangent.java.
String org.jgap.gp.function.ArcTangent.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.3.4
Definition at line 43 of file ArcTangent.java.
String org.jgap.gp.function.ArcTangent.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 33 of file ArcTangent.java.
Member Data Documentation
final String org.jgap.gp.function.ArcTangent.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file ArcTangent.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/ArcTangent.java