org.jgap.impl.TwoWayMutationOperatorTest Class Reference
Classes
class GeneticOperatorConstraintForTesting
Public Member Functions
void setUp ()
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testConstruct_2 () throws Exception
void testConstruct_3 () throws Exception
void testOperate_0 () throws Exception
void testOperate_0_2 () throws Exception
void testOperate_1 () throws Exception
void testOperate_2 () throws Exception
void testOperate_3 () throws Exception
void testOperate_3_1 () throws Exception
void testOperate_4 () throws Exception
void testOperate_5 () throws Exception
void testOperate_5_2 () throws Exception
void testOperate_6 () throws Exception
void testOperate_6_2 () throws Exception
void testOperate_8 () throws Exception
void testIsSerializable_0 () throws Exception
void testDoSerialize_0 () throws Exception
void testEquals_0 () throws Exception
void testCompareTo_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
Tests the TwoWayMutationOperator class.
Author
Klaus Meffert
Since
3.1
Definition at line 24 of file TwoWayMutationOperatorTest.java.
Member Function Documentation
void org.jgap.impl.TwoWayMutationOperatorTest.setUp () [inline]
Definition at line 34 of file TwoWayMutationOperatorTest.java.
static Test org.jgap.impl.TwoWayMutationOperatorTest.suite () [inline], [static]
Definition at line 29 of file TwoWayMutationOperatorTest.java.
void org.jgap.impl.TwoWayMutationOperatorTest.testCompareTo_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 564 of file TwoWayMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.impl.TwoWayMutationOperator.compareTo().
void org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 45 of file TwoWayMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.TwoWayMutationOperator.getMutationRate(), and org.jgap.impl.TwoWayMutationOperator.getMutationRateCalc().
void org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 58 of file TwoWayMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 73 of file TwoWayMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.TwoWayMutationOperator.getMutationRate(), and org.jgap.impl.TwoWayMutationOperator.getMutationRateCalc().
void org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 86 of file TwoWayMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.TwoWayMutationOperator.getMutationRate(), and org.jgap.impl.TwoWayMutationOperator.getMutationRateCalc().
void org.jgap.impl.TwoWayMutationOperatorTest.testDoSerialize_0 () throws Exception [inline]
Ensures that operator and all objects contained implement Serializable.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 527 of file TwoWayMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.doSerialize().
void org.jgap.impl.TwoWayMutationOperatorTest.testEquals_0 () throws Exception [inline]
Test equals with classcast object.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 552 of file TwoWayMutationOperatorTest.java.
void org.jgap.impl.TwoWayMutationOperatorTest.testIsSerializable_0 () throws Exception [inline]
Ensures operator is implementing Serializable.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 514 of file TwoWayMutationOperatorTest.java.
References org.jgap.JGAPTestCase.isSerializable().
void org.jgap.impl.TwoWayMutationOperatorTest.testOperate_0 () throws Exception [inline]
Ensure that size of mutated set of chromosomes equals the size of original chromosomes.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 102 of file TwoWayMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.TwoWayMutationOperatorTest.testOperate_0_2 () throws Exception [inline]
Ensure that size of mutated set of chromosomes equals the size of original chromosomes.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 122 of file TwoWayMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.TwoWayMutationOperatorTest.testOperate_1 () throws Exception [inline]
Mutating with different types of genes contained in the population should be possible without exception.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 158 of file TwoWayMutationOperatorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.TwoWayMutationOperatorTest.testOperate_2 () throws Exception [inline]
NullpointerException because of null Configuration.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 180 of file TwoWayMutationOperatorTest.java.
void org.jgap.impl.TwoWayMutationOperatorTest.testOperate_3 () throws Exception [inline]
Tests if population size grows expectedly after two consecutive calls.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 203 of file TwoWayMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.impl.TwoWayMutationOperatorTest.testOperate_3_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert (adapted from Dan Clark's test of MutationOperator)
Since
3.1
Definition at line 255 of file TwoWayMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.BaseChromosome.getGene().
void org.jgap.impl.TwoWayMutationOperatorTest.testOperate_4 () throws Exception [inline]
Ensure that nothing is done.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 312 of file TwoWayMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.impl.TwoWayMutationOperatorTest.testOperate_5 () throws Exception [inline]
Mutation, especially tested for an IntegerGene.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 340 of file TwoWayMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.impl.TwoWayMutationOperatorTest.testOperate_5_2 () throws Exception [inline]
Mutation, especially tested for an IntegerGene. Uses a CompositeGene.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 385 of file TwoWayMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.impl.TwoWayMutationOperatorTest.testOperate_6 () throws Exception [inline]
Following should be possible without exception.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 439 of file TwoWayMutationOperatorTest.java.
void org.jgap.impl.TwoWayMutationOperatorTest.testOperate_6_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 453 of file TwoWayMutationOperatorTest.java.
void org.jgap.impl.TwoWayMutationOperatorTest.testOperate_8 () throws Exception [inline]
Considers IGeneticOperatorConstraint. Here, the mutation of a BooleanGene is forbidden by that constraint.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 470 of file TwoWayMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals().
Member Data Documentation
final String org.jgap.impl.TwoWayMutationOperatorTest.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file TwoWayMutationOperatorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/TwoWayMutationOperatorTest.java