org.jgap.gp.impl.ProgramChromosome Class Reference
Classes
class NodeInfo
Public Member Functions
ProgramChromosome (GPConfiguration a_conf, int a_size) throws InvalidConfigurationException
ProgramChromosome (GPConfiguration a_conf, int a_size, IGPProgram a_ind) throws InvalidConfigurationException
ProgramChromosome (GPConfiguration a_conf, int a_size, CommandGene[] a_functionSet, Class[] a_argTypes, IGPProgram a_ind) throws InvalidConfigurationException
ProgramChromosome (GPConfiguration a_conf, CommandGene[] a_initialGenes) throws InvalidConfigurationException
ProgramChromosome (final GPConfiguration a_conf) throws InvalidConfigurationException
ProgramChromosome () throws InvalidConfigurationException
void setArgTypes (Class[] a_argTypes)
synchronized Object clone ()
void cleanup ()
void growOrFull (final int a_num, final int a_depth, final Class a_type, final Class[] a_argTypes, final CommandGene[] a_functionSet, boolean a_grow, int a_tries)
String toString (final int a_startNode)
String toStringNorm (final int a_startNode)
String getBusinessKey ()
String toStringDebug ()
boolean isPossible (Class a_returnType, int a_subReturnType, CommandGene[] a_nodeSet, boolean a_function, boolean a_growing)
void redepth ()
int getChild (int a_index, int a_child)
int getChild (CommandGene a_node, int a_child)
CommandGene[] getFunctionSet ()
void setFunctionSet (CommandGene[] a_functionSet)
CommandGene[] getFunctions ()
void setFunctions (CommandGene[] a_functions) throws InvalidConfigurationException
int getSize (int a_index)
int getDepth (int a_index)
int getParentNode (int a_child)
CommandGene getNode (Class a_type, boolean a_exactMatch)
CommandGene getNode (Class a_type, boolean a_exactMatch, int a_startIndex)
boolean execute_boolean (Object[] args)
boolean execute_boolean (int n, int child, Object[] args)
void execute_void (Object[] args)
void execute_void (int n, int child, Object[] args)
int execute_int (Object[] args)
int execute_int (int n, int child, Object[] args)
long execute_long (Object[] args)
long execute_long (int n, int child, Object[] args)
float execute_float (Object[] args)
float execute_float (int n, int child, Object[] args)
double execute_double (Object[] args)
double execute_double (int n, int child, Object[] args)
Object execute_object (Object[] args)
Object execute_object (int n, int child, Object[] args)
Object execute (Object[] args)
Object execute (int n, int child, Object[] args)
void setGene (int index, CommandGene a_gene)
Class[] getArgTypes ()
int getArity ()
int size ()
int compareTo (Object a_other)
boolean equals (Object a_other)
void setCompareApplicationData (boolean a_doCompare)
boolean isCompareApplicationData ()
Object getApplicationData ()
synchronized CommandGene getGene (int a_locus)
String getPersistentRepresentation ()
void setValueFromPersistentRepresentation (final String a_representation) throws UnsupportedRepresentationException
boolean contains (CommandGene[] a_functionSet, CommandGene a_function)
boolean contains (CommandGene[] a_functionSet, Class a_function)
int contains (CommandGene[] a_functionSet, CommandGene a_function, int a_limit)
Protected Member Functions
CommandGene selectNode (int a_chromIndex, Class a_returnType, int a_subReturnType, CommandGene[] a_functionSet, boolean a_function, boolean a_growing)
CommandGene[] growOrFullNode (int a_num, int a_depth, Class a_returnType, int a_subReturnType, CommandGene[] a_functionSet, CommandGene a_rootNode, int a_recurseLevel, boolean a_grow, int a_childNum, boolean a_validateNode)
int redepth (int a_index)
String encode (String a_string)
String decode (String a_string)
CommandGene createGene (String a_geneClassName, String a_persistentRepresentation) throws Exception
Static Protected Member Functions
static final List split (String a_string) throws UnsupportedRepresentationException
Private Member Functions
void init () throws InvalidConfigurationException
void init (final int a_size) throws InvalidConfigurationException
CommandGene[] remove (CommandGene[] a_functionSet, CommandGene node)
Private Attributes
CommandGene[] m_functionSet
int[] m_depth
Class[] argTypes
transient int m_index
transient int m_maxDepth
CommandGene[] m_genes
Object m_applicationData
boolean m_compareAppData
Map< NodeInfo, Boolean > m_possibleNodes = new HashMap()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.52 $`
static transient Logger LOGGER = Logger.getLogger(ProgramChromosome.class)
Additional Inherited Members
Detailed Description
Chromosome representing a single GP Program.
Author
Klaus Meffert
Since
3.0
Definition at line 27 of file ProgramChromosome.java.
Constructor & Destructor Documentation
org.jgap.gp.impl.ProgramChromosome.ProgramChromosome (GPConfiguration a_conf, int a_size) throws InvalidConfigurationException [inline]
Definition at line 84 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.init().
org.jgap.gp.impl.ProgramChromosome.ProgramChromosome (GPConfiguration a_conf, int a_size, IGPProgram a_ind) throws InvalidConfigurationException [inline]
Definition at line 94 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.init().
org.jgap.gp.impl.ProgramChromosome.ProgramChromosome (GPConfiguration a_conf, int a_size, CommandGene[] a_functionSet, Class[] a_argTypes, IGPProgram a_ind) throws InvalidConfigurationException [inline]
Definition at line 108 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.argTypes, org.jgap.gp.impl.ProgramChromosome.init(), and org.jgap.gp.impl.ProgramChromosome.m_functionSet.
org.jgap.gp.impl.ProgramChromosome.ProgramChromosome (GPConfiguration a_conf, CommandGene[] a_initialGenes) throws InvalidConfigurationException [inline]
Definition at line 126 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.init(), and org.jgap.gp.impl.ProgramChromosome.m_genes.
org.jgap.gp.impl.ProgramChromosome.ProgramChromosome (final GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Definition at line 139 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.init().
org.jgap.gp.impl.ProgramChromosome.ProgramChromosome () throws InvalidConfigurationException [inline]
Default constructor. Only use for dynamic instantiation.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 153 of file ProgramChromosome.java.
Referenced by org.jgap.gp.impl.ProgramChromosome.clone(), and org.jgap.gp.impl.ProgramChromosome.compareTo().
Member Function Documentation
void org.jgap.gp.impl.ProgramChromosome.cleanup () [inline]
Clean up the chromosome.
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IGPChromosome.
Definition at line 216 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_genes.
Referenced by org.jgap.gp.impl.ProgramChromosome.execute_boolean(), org.jgap.gp.impl.ProgramChromosome.execute_double(), org.jgap.gp.impl.ProgramChromosome.execute_float(), org.jgap.gp.impl.ProgramChromosome.execute_int(), org.jgap.gp.impl.ProgramChromosome.execute_long(), org.jgap.gp.impl.ProgramChromosome.execute_object(), and org.jgap.gp.impl.ProgramChromosome.execute_void().
synchronized Object org.jgap.gp.impl.ProgramChromosome.clone () [inline]
Definition at line 173 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.argTypes, org.jgap.gp.impl.ProgramChromosome.getFunctionSet(), org.jgap.gp.BaseGPChromosome.getGPConfiguration(), org.jgap.gp.BaseGPChromosome.getIndividual(), org.jgap.gp.impl.ProgramChromosome.m_depth, org.jgap.gp.impl.ProgramChromosome.m_genes, org.jgap.gp.impl.ProgramChromosome.ProgramChromosome(), and org.jgap.gp.impl.ProgramChromosome.size().
Referenced by org.jgap.gp.impl.ProgramChromosome.growOrFullNode().
int org.jgap.gp.impl.ProgramChromosome.compareTo (Object a_other) [inline]
Compares the given chromosome to this chromosome. This chromosome is considered to be `less than` the given chromosome if it has a fewer number of genes or if any of its gene values (alleles) are less than their corresponding gene values in the other chromosome.
Parameters
a_other the chromosome against which to compare this chromosome
Returns
a negative number if this chromosome is `less than` the given chromosome, zero if they are equal to each other, and a positive number if this chromosome is `greater than` the given chromosome
Author
Klaus Meffert
Since
3.0
Todo
Todo compare m_functionSet
Definition at line 1200 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.getApplicationData(), org.jgap.gp.impl.ProgramChromosome.isCompareApplicationData(), org.jgap.gp.impl.ProgramChromosome.m_genes, org.jgap.gp.impl.ProgramChromosome.ProgramChromosome(), and org.jgap.gp.impl.ProgramChromosome.size().
Referenced by org.jgap.gp.impl.ProgramChromosome.equals().
boolean org.jgap.gp.impl.ProgramChromosome.contains (CommandGene[] a_functionSet, CommandGene a_function) [inline]
Checks if a function or terminal of the class of the given instance exists within a_functionSet
Parameters
a_functionSet the set of functions to check
a_function the commandgene to check for via its class
Returns
true if a_function's class exists within a_functionSet
Author
Klaus Meffert
Since
3.6
Definition at line 1496 of file ProgramChromosome.java.
Referenced by examples.gp.tictactoe.SingleNodeValidator.isAllowed().
boolean org.jgap.gp.impl.ProgramChromosome.contains (CommandGene[] a_functionSet, Class a_function) [inline]
Checks if a function or terminal of the class of the given instance exists within a_functionSet
Parameters
a_functionSet the set of functions to check
a_function the commandgene to check for via its class
Returns
true if a_function's class exists within a_functionSet
Author
Klaus Meffert
Since
3.6
Definition at line 1511 of file ProgramChromosome.java.
int org.jgap.gp.impl.ProgramChromosome.contains (CommandGene[] a_functionSet, CommandGene a_function, int a_limit) [inline]
Checks if a function or terminal of the class of the given instance exists within a_functionSet at least a_limit times
Parameters
a_functionSet the set of functions to check
a_function the commandgene to check for via its class
a_limit if a_limit occurrences of a_function were detected, exit
Returns
true if a_function's class exists at least a_limit times within a_functionSet
Author
Klaus Meffert
Since
3.6
Definition at line 1534 of file ProgramChromosome.java.
CommandGene org.jgap.gp.impl.ProgramChromosome.createGene (String a_geneClassName, String a_persistentRepresentation) throws Exception [inline], [protected]
Creates a new instance of gene.
Parameters
a_geneClassName name of the gene class
a_persistentRepresentation persistent representation of the gene to create (could be obtained via getPersistentRepresentation)
Returns
newly created gene
Exceptions
Exception
Author
Klaus Meffert
Since
3.3
Definition at line 1437 of file ProgramChromosome.java.
References org.jgap.gp.BaseGPChromosome.getGPConfiguration().
Referenced by org.jgap.gp.impl.ProgramChromosome.setValueFromPersistentRepresentation().
String org.jgap.gp.impl.ProgramChromosome.decode (String a_string) [inline], [protected]
Definition at line 1352 of file ProgramChromosome.java.
Referenced by org.jgap.gp.impl.ProgramChromosome.setValueFromPersistentRepresentation().
String org.jgap.gp.impl.ProgramChromosome.encode (String a_string) [inline], [protected]
Definition at line 1348 of file ProgramChromosome.java.
Referenced by org.jgap.gp.impl.ProgramChromosome.getPersistentRepresentation().
boolean org.jgap.gp.impl.ProgramChromosome.equals (Object a_other) [inline]
Compares this chromosome against the specified object.
Parameters
a_other the object to compare against
Returns
true: if the objects are the same, false otherwise
Author
Klaus Meffert
Since
3.0
Definition at line 1267 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.compareTo().
Object org.jgap.gp.impl.ProgramChromosome.execute (Object[] args) [inline]
Executes this node without knowing its return type.
Parameters
args the arguments for execution
Returns
the Object which wraps the return value of this node, or null if the return type is null or unknown
Author
Klaus Meffert
Since
3.0
Definition at line 1149 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_genes.
Object org.jgap.gp.impl.ProgramChromosome.execute (int n, int child, Object[] args) [inline]
Definition at line 1153 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.execute_object().
boolean org.jgap.gp.impl.ProgramChromosome.execute_boolean (Object[] args) [inline]
Executes this node as a boolean.
Parameters
args the arguments for execution
Returns
the boolean return value of this node
Exceptions
UnsupportedOperationException if the type of this node is not boolean
Author
Klaus Meffert
Since
3.0
Definition at line 964 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.cleanup(), and org.jgap.gp.impl.ProgramChromosome.m_genes.
boolean org.jgap.gp.impl.ProgramChromosome.execute_boolean (int n, int child, Object[] args) [inline]
Executes this node as a boolean.
Parameters
n the index of the parent node
child the child number of the node to execute
args the arguments for execution
Returns
the boolean return value of this node
Exceptions
UnsupportedOperationException if the type of this node is not boolean
Author
Klaus Meffert
Since
3.0
Definition at line 983 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.getChild(), and org.jgap.gp.impl.ProgramChromosome.m_genes.
double org.jgap.gp.impl.ProgramChromosome.execute_double (Object[] args) [inline]
Executes this node as a double.
Parameters
args the arguments for execution
Returns
the double return value of this node
Exceptions
UnsupportedOperationException if this node's type is not double
Author
Klaus Meffert
Since
3.0
Definition at line 1100 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.cleanup(), and org.jgap.gp.impl.ProgramChromosome.m_genes.
double org.jgap.gp.impl.ProgramChromosome.execute_double (int n, int child, Object[] args) [inline]
Definition at line 1106 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.getChild(), and org.jgap.gp.impl.ProgramChromosome.m_genes.
float org.jgap.gp.impl.ProgramChromosome.execute_float (Object[] args) [inline]
Executes this node as a float.
Parameters
args the arguments for execution
Returns
the float return value of this node
Exceptions
UnsupportedOperationException if the type of this node is not float
Author
Klaus Meffert
Since
3.0
Definition at line 1076 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.cleanup(), and org.jgap.gp.impl.ProgramChromosome.m_genes.
float org.jgap.gp.impl.ProgramChromosome.execute_float (int n, int child, Object[] args) [inline]
Definition at line 1082 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.getChild(), and org.jgap.gp.impl.ProgramChromosome.m_genes.
int org.jgap.gp.impl.ProgramChromosome.execute_int (Object[] args) [inline]
Executes this node as an integer.
Parameters
args the arguments for execution
Returns
the integer return value of this node
Exceptions
UnsupportedOperationException if the type of this node is not integer
Author
Klaus Meffert
Since
3.0
Definition at line 1026 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.cleanup(), and org.jgap.gp.impl.ProgramChromosome.m_genes.
int org.jgap.gp.impl.ProgramChromosome.execute_int (int n, int child, Object[] args) [inline]
Definition at line 1032 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.getChild(), and org.jgap.gp.impl.ProgramChromosome.m_genes.
long org.jgap.gp.impl.ProgramChromosome.execute_long (Object[] args) [inline]
Executes this node as a long.
Parameters
args the arguments for execution
Returns
the long return value of this node
Exceptions
UnsupportedOperationException if the type of this node is not long
Author
Klaus Meffert
Since
3.0
Definition at line 1052 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.cleanup(), and org.jgap.gp.impl.ProgramChromosome.m_genes.
long org.jgap.gp.impl.ProgramChromosome.execute_long (int n, int child, Object[] args) [inline]
Definition at line 1058 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.getChild(), and org.jgap.gp.impl.ProgramChromosome.m_genes.
Object org.jgap.gp.impl.ProgramChromosome.execute_object (Object[] args) [inline]
Executes this node as an object.
Parameters
args the arguments for execution
Returns
the object return value of this node
Exceptions
UnsupportedOperationException if the type of this node is not of type Object
Author
Klaus Meffert
Since
3.0
Definition at line 1125 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.cleanup(), and org.jgap.gp.impl.ProgramChromosome.m_genes.
Referenced by org.jgap.gp.impl.ProgramChromosome.execute().
Object org.jgap.gp.impl.ProgramChromosome.execute_object (int n, int child, Object[] args) [inline]
Definition at line 1131 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.getChild(), and org.jgap.gp.impl.ProgramChromosome.m_genes.
void org.jgap.gp.impl.ProgramChromosome.execute_void (Object[] args) [inline]
Executes this node, returning nothing.
Parameters
args the arguments for execution
Exceptions
UnsupportedOperationException if the type of this node is not void
Author
Klaus Meffert
Since
3.0
Definition at line 1000 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.cleanup(), and org.jgap.gp.impl.ProgramChromosome.m_genes.
void org.jgap.gp.impl.ProgramChromosome.execute_void (int n, int child, Object[] args) [inline]
Definition at line 1005 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.getChild(), and org.jgap.gp.impl.ProgramChromosome.m_genes.
Object org.jgap.gp.impl.ProgramChromosome.getApplicationData () [inline]
Retrieves the application-specific data that is attached to this Chromosome. Attaching application-specific data may be useful for some applications when it comes time to evaluate this Chromosome in the fitness function. JGAP ignores this data functionally.
Returns
the application-specific data previously attached to this Chromosome, or null if there is no data attached
Author
Klaus Meffert
Since
3.0
Definition at line 1311 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_applicationData.
Referenced by org.jgap.gp.impl.ProgramChromosome.compareTo().
Class [] org.jgap.gp.impl.ProgramChromosome.getArgTypes () [inline]
Definition at line 1164 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.argTypes.
int org.jgap.gp.impl.ProgramChromosome.getArity () [inline]
Definition at line 1168 of file ProgramChromosome.java.
Referenced by org.jgap.gp.impl.ProgramChromosome.isPossible(), org.jgap.gp.impl.ProgramChromosome.selectNode(), org.jgap.gp.impl.ProgramChromosome.toString(), org.jgap.gp.impl.ProgramChromosome.toStringDebug(), and org.jgap.gp.impl.ProgramChromosome.toStringNorm().
String org.jgap.gp.impl.ProgramChromosome.getBusinessKey () [inline]
Returns
business key of the chromosome
Author
Klaus Meffert
Since
3.4
Implements org.jgap.IBusinessKey.
Definition at line 398 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.toStringNorm().
int org.jgap.gp.impl.ProgramChromosome.getChild (int a_index, int a_child) [inline]
Gets the a_child'th child of the a_index'th node in this chromosome. This is the same as the a_child'th node whose depth is one more than the depth of the a_index'th node.
Parameters
a_index the node number of the parent
a_child the child number (starting from 0) of the parent
Returns
the node number of the child, or -1 if not found
Author
Klaus Meffert
Since
3.01
Implements org.jgap.gp.IGPChromosome.
Definition at line 786 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.getFunctions(), and org.jgap.gp.impl.ProgramChromosome.m_depth.
Referenced by org.jgap.gp.impl.ProgramChromosome.execute_boolean(), org.jgap.gp.impl.ProgramChromosome.execute_double(), org.jgap.gp.impl.ProgramChromosome.execute_float(), org.jgap.gp.impl.ProgramChromosome.execute_int(), org.jgap.gp.impl.ProgramChromosome.execute_long(), org.jgap.gp.impl.ProgramChromosome.execute_object(), org.jgap.gp.impl.ProgramChromosome.execute_void(), org.jgap.gp.impl.JGAPTreeNode.getChildCount(), org.jgap.gp.impl.ProgramChromosome.toString(), org.jgap.gp.impl.ProgramChromosome.toStringDebug(), and org.jgap.gp.impl.ProgramChromosome.toStringNorm().
int org.jgap.gp.impl.ProgramChromosome.getChild (CommandGene a_node, int a_child) [inline]
Definition at line 804 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.getFunctions(), org.jgap.gp.impl.ProgramChromosome.m_depth, and org.jgap.gp.impl.ProgramChromosome.m_genes.
int org.jgap.gp.impl.ProgramChromosome.getDepth (int a_index) [inline]
Gets the depth of the branch starting at the a_index'th node.
Parameters
a_index the index of the node at which to check the depth
Returns
the depth of the branch starting at the a_index'th node
Author
Klaus Meffert
Since
3.0
Definition at line 877 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_depth, and org.jgap.gp.impl.ProgramChromosome.m_genes.
Referenced by org.jgap.gp.impl.ProgramChromosome.selectNode(), org.jgap.gp.impl.GPProgramTest.testExecute_0(), org.jgap.gp.impl.ProgramChromosomeTest.testGetDepth_0(), org.jgap.gp.impl.ProgramChromosomeTest.testGetDepth_1(), org.jgap.gp.impl.ProgramChromosomeTest.testGetDepth_2(), and org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_3().
CommandGene [] org.jgap.gp.impl.ProgramChromosome.getFunctions () [inline]
Implements org.jgap.gp.IGPChromosome.
Definition at line 838 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_genes.
Referenced by org.jgap.gp.impl.ProgramChromosome.getChild(), org.jgap.gp.impl.ProgramChromosome.toString(), and org.jgap.gp.impl.ProgramChromosome.toStringNorm().
CommandGene [] org.jgap.gp.impl.ProgramChromosome.getFunctionSet () [inline]
Returns
set of CommandGene instances allowed
Author
Klaus Meffert
Since
3.2.1
Implements org.jgap.gp.IGPChromosome.
Definition at line 830 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_functionSet.
Referenced by org.jgap.gp.impl.ProgramChromosome.clone(), and org.jgap.gp.impl.ProgramChromosome.growOrFull().
synchronized CommandGene org.jgap.gp.impl.ProgramChromosome.getGene (int a_locus) [inline]
Returns the Gene at the given index (locus) within the Chromosome. The first gene is at index zero and the last gene is at the index equal to the size of this Chromosome - 1.
Parameters
a_locus index of the gene value to be returned
Returns
Gene at the given index
Author
Klaus Meffert
Since
3.0
Definition at line 1326 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_genes.
Referenced by examples.gp.tictactoe.PutStone1.execute_void(), org.jgap.gp.impl.BranchTypingCrossTest.testOperate_0(), org.jgap.gp.impl.BranchTypingCrossTest.testOperate_1(), org.jgap.gp.impl.BranchTypingCrossTest.testOperate_2(), and org.jgap.gp.impl.GPGenotypeTest.testReferenceProblem_0().
CommandGene org.jgap.gp.impl.ProgramChromosome.getNode (Class a_type, boolean a_exactMatch) [inline]
Checks whether a node with a given type is contained in the program.
Parameters
a_type the type to look for
a_exactMatch true: look for exactly the given type: false: also look for sub types
Returns
true specific node found
Author
Klaus Meffert
Since
3.2.1
Definition at line 924 of file ProgramChromosome.java.
Referenced by org.jgap.gp.impl.ProgramChromosome.redepth(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_0(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_1(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_2(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_3(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_4(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_4_2(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_4_3(), and org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_5().
CommandGene org.jgap.gp.impl.ProgramChromosome.getNode (Class a_type, boolean a_exactMatch, int a_startIndex) [inline]
Definition at line 928 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_genes, and org.jgap.gp.impl.ProgramChromosome.size().
int org.jgap.gp.impl.ProgramChromosome.getParentNode (int a_child) [inline]
Gets the node which is the parent of the given node in this chromosome. If the child is at depth d then the parent is the first function at depth d-1 when iterating backwards through the function list starting from the child.
Parameters
a_child the child node
Returns
the parent node, or null if the child is the root node
Author
Klaus Meffert
Since
3.0
Definition at line 901 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_depth, and org.jgap.gp.impl.ProgramChromosome.m_genes.
Referenced by org.jgap.gp.impl.JGAPTreeNode.getParent().
String org.jgap.gp.impl.ProgramChromosome.getPersistentRepresentation () [inline]
Returns
the persistent representation of the chromosome, including all genes
Author
Klaus Meffert
Since
3.3
Implements org.jgap.gp.IGPChromosome.
Definition at line 1363 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.encode(), and org.jgap.gp.impl.ProgramChromosome.m_genes.
int org.jgap.gp.impl.ProgramChromosome.getSize (int a_index) [inline]
Gets the number of nodes in the branch starting at the a_index'th node.
Parameters
a_index the index of the node at which to start counting
Returns
the number of nodes in the branch starting at the a_index'th node
Author
Klaus Meffert
Since
3.0
Definition at line 856 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_depth, and org.jgap.gp.impl.ProgramChromosome.m_genes.
void org.jgap.gp.impl.ProgramChromosome.growOrFull (final int a_num, final int a_depth, final Class a_type, final Class[] a_argTypes, final CommandGene[] a_functionSet, boolean a_grow, int a_tries) [inline]
Initialize this chromosome using the grow or the full method.
Parameters
a_num the chromosome's index in the individual of this chromosome
a_depth the maximum depth of the chromosome to create
a_type the type of the chromosome to create
a_argTypes the array of argument types for this chromosome
a_functionSet the set of nodes valid to pick from
a_grow true: use grow method; false: use full method
a_tries maximum number of tries for creating a valid program
Author
Klaus Meffert
Since
3.0
Definition at line 240 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.argTypes, org.jgap.gp.impl.ProgramChromosome.getFunctionSet(), org.jgap.gp.BaseGPChromosome.getGPConfiguration(), org.jgap.gp.impl.ProgramChromosome.growOrFullNode(), org.jgap.gp.impl.ProgramChromosome.m_functionSet, org.jgap.gp.impl.ProgramChromosome.m_index, org.jgap.gp.impl.ProgramChromosome.m_maxDepth, org.jgap.gp.impl.ProgramChromosome.redepth(), and org.jgap.gp.impl.ProgramChromosome.setFunctionSet().
CommandGene [] org.jgap.gp.impl.ProgramChromosome.growOrFullNode (int a_num, int a_depth, Class a_returnType, int a_subReturnType, CommandGene[] a_functionSet, CommandGene a_rootNode, int a_recurseLevel, boolean a_grow, int a_childNum, boolean a_validateNode) [inline], [protected]
Create a tree of nodes using the grow or the full method.
Parameters
a_num the chromosome's index in the individual of this chromosome
a_depth the maximum depth of the tree to create
a_returnType the return type the lastly evaluated node must have
a_subReturnType the sub return type to look for
a_functionSet the set of function valid to pick from
a_rootNode null, or parent node of the node to develop
a_recurseLevel 0 for first call
a_grow true: use grow method; false: use full method
a_childNum index of the child in the parent node to which it belongs (-1 if node is root node)
a_validateNode true: check if node selected is valid (when called recursively a_validateNode is set to true)
Returns
possible modified set of functions (e.g. to avoid having a unique command more than once)
Author
Klaus Meffert
Since
3.0
Todo
Todo we could optionally use the clone handler
Definition at line 591 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.clone(), org.jgap.gp.CommandGene.getArity(), org.jgap.gp.CommandGene.getChildType(), org.jgap.gp.BaseGPChromosome.getCommandOfClass(), org.jgap.gp.impl.GPConfiguration.getDynamizeArityProb(), org.jgap.gp.BaseGPChromosome.getGPConfiguration(), org.jgap.gp.BaseGPChromosome.getIndividual(), org.jgap.gp.impl.GPConfiguration.isNoCommandGeneCloning(), org.jgap.gp.impl.ProgramChromosome.m_depth, org.jgap.gp.impl.ProgramChromosome.m_genes, org.jgap.gp.impl.ProgramChromosome.m_index, org.jgap.gp.impl.ProgramChromosome.m_maxDepth, org.jgap.RandomGenerator.nextDouble(), org.jgap.gp.impl.ProgramChromosome.selectNode(), and org.jgap.gp.impl.GPConfiguration.validateNode().
Referenced by org.jgap.gp.impl.ProgramChromosome.growOrFull().
void org.jgap.gp.impl.ProgramChromosome.init () throws InvalidConfigurationException [inline], [private]
Definition at line 158 of file ProgramChromosome.java.
References org.jgap.gp.BaseGPChromosome.getGPConfiguration().
Referenced by org.jgap.gp.impl.ProgramChromosome.ProgramChromosome().
void org.jgap.gp.impl.ProgramChromosome.init (final int a_size) throws InvalidConfigurationException [inline], [private]
Definition at line 163 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_depth, and org.jgap.gp.impl.ProgramChromosome.m_genes.
boolean org.jgap.gp.impl.ProgramChromosome.isCompareApplicationData () [inline]
Definition at line 1295 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_compareAppData.
Referenced by org.jgap.gp.impl.ProgramChromosome.compareTo().
boolean org.jgap.gp.impl.ProgramChromosome.isPossible (Class a_returnType, int a_subReturnType, CommandGene[] a_nodeSet, boolean a_function, boolean a_growing) [inline]
Determines whether there exists a function or terminal in the given node set with the given return and sub return type.
Parameters
a_returnType the return type to look for
a_subReturnType the sub return type to look for
a_nodeSet the array of nodes to look through
a_function true to look for a function, false to look for a terminal
a_growing true: grow mode, false: full mode
Returns
true if such a node exists, false otherwise
Author
Klaus Meffert
Since
3.0
Definition at line 440 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.getArity(), and org.jgap.gp.BaseGPChromosome.getIndividual().
void org.jgap.gp.impl.ProgramChromosome.redepth () [inline]
Recalculate the depth of each node.
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IGPChromosome.
Definition at line 728 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_depth.
Referenced by org.jgap.gp.impl.ProgramChromosome.growOrFull(), and org.jgap.gp.impl.ProgramChromosome.redepth().
int org.jgap.gp.impl.ProgramChromosome.redepth (int a_index) [inline], [protected]
Calculate the depth of the next node and the indices of the children of the current node. The depth of the next node is just one plus the depth of the current node. The index of the first child is always the next node. The index of the second child is found by recursively calling this method on the tree starting with the first child.
Parameters
a_index the index of the reference depth
Returns
the index of the next node of the same depth as the current node (i.e. the next sibling node)
Author
Klaus Meffert
Since
3.0
Definition at line 748 of file ProgramChromosome.java.
References org.jgap.gp.BaseGPChromosome.getIndividual(), org.jgap.gp.impl.ProgramChromosome.getNode(), org.jgap.gp.impl.ProgramChromosome.m_depth, and org.jgap.gp.impl.ProgramChromosome.redepth().
CommandGene [] org.jgap.gp.impl.ProgramChromosome.remove (CommandGene[] a_functionSet, CommandGene node) [inline], [private]
Definition at line 1330 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.size().
CommandGene org.jgap.gp.impl.ProgramChromosome.selectNode (int a_chromIndex, Class a_returnType, int a_subReturnType, CommandGene[] a_functionSet, boolean a_function, boolean a_growing) [inline], [protected]
Randomly chooses a valid node from the functions set.
Parameters
a_chromIndex index of the chromosome in the individual (0..n-1)
a_returnType the return type of node to choose
a_subReturnType the sub return type to look for
a_functionSet the functions to use
a_function true to choose a function, false to choose a terminal
a_growing true to ignore the function parameter, false otherwise
Returns
the node chosen
Author
Klaus Meffert
Since
3.0
Definition at line 490 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.getArity(), org.jgap.gp.impl.ProgramChromosome.getDepth(), org.jgap.gp.BaseGPChromosome.getGPConfiguration(), org.jgap.gp.BaseGPChromosome.getIndividual(), org.jgap.gp.ISingleNodeValidator.isAllowed(), org.jgap.gp.impl.ProgramChromosome.m_index, and org.jgap.gp.CommandGene.VoidClass.
Referenced by org.jgap.gp.impl.ProgramChromosome.growOrFullNode().
void org.jgap.gp.impl.ProgramChromosome.setArgTypes (Class[] a_argTypes) [inline]
Definition at line 169 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.argTypes.
void org.jgap.gp.impl.ProgramChromosome.setCompareApplicationData (boolean a_doCompare) [inline]
Should we also consider the application data when comparing? Default is `false` as `true` means a Chromosome is losing its identity when application data is set differently!
Parameters
a_doCompare true: consider application data in method compareTo
Author
Klaus Meffert
Since
3.0
Definition at line 1285 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_compareAppData.
void org.jgap.gp.impl.ProgramChromosome.setFunctions (CommandGene[] a_functions) throws InvalidConfigurationException [inline]
Definition at line 842 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_genes.
void org.jgap.gp.impl.ProgramChromosome.setFunctionSet (CommandGene[] a_functionSet) [inline]
Definition at line 834 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_functionSet.
Referenced by org.jgap.gp.impl.ProgramChromosome.growOrFull().
void org.jgap.gp.impl.ProgramChromosome.setGene (int index, CommandGene a_gene) [inline]
Definition at line 1157 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_genes.
void org.jgap.gp.impl.ProgramChromosome.setValueFromPersistentRepresentation (final String a_representation) throws UnsupportedRepresentationException [inline]
Parameters
a_representation String
Exceptions
UnsupportedRepresentationException
Author
Klaus Meffert
Since
3.3
Definition at line 1393 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.createGene(), org.jgap.gp.impl.ProgramChromosome.decode(), org.jgap.gp.impl.ProgramChromosome.m_genes, and org.jgap.gp.impl.ProgramChromosome.split().
int org.jgap.gp.impl.ProgramChromosome.size () [inline]
Returns
number of functions and terminals present
Author
Klaus Meffert
Since
3.0
Definition at line 1178 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.m_genes.
Referenced by org.jgap.gp.impl.ProgramChromosome.clone(), org.jgap.gp.impl.ProgramChromosome.compareTo(), org.jgap.gp.impl.ProgramChromosome.getNode(), and org.jgap.gp.impl.ProgramChromosome.remove().
static final List org.jgap.gp.impl.ProgramChromosome.split (String a_string) throws UnsupportedRepresentationException [inline], [static], [protected]
Splits a_string into individual gene representations.
Parameters
a_string the string to split
Returns
the elements of the returned array are the persistent representation strings of the gene's components
Exceptions
UnsupportedRepresentationException
Author
Klaus Meffert
Since
3.3
Definition at line 1459 of file ProgramChromosome.java.
Referenced by org.jgap.gp.impl.ProgramChromosome.setValueFromPersistentRepresentation().
String org.jgap.gp.impl.ProgramChromosome.toString (final int a_startNode) [inline]
Output program in left-hand notion (e.g.: `+ X Y` for `X + Y`).
Parameters
a_startNode node to start with
Returns
output in left-hand notion
Author
Klaus Meffert
Since
3.0
Definition at line 298 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.getArity(), org.jgap.gp.impl.ProgramChromosome.getChild(), org.jgap.gp.impl.ProgramChromosome.getFunctions(), org.jgap.gp.BaseGPChromosome.getIndividual(), and org.jgap.gp.impl.ProgramChromosome.m_genes.
Referenced by org.jgap.gp.impl.ProgramChromosome.toStringNorm().
String org.jgap.gp.impl.ProgramChromosome.toStringDebug () [inline]
Returns
debug representation of progrm chromosome, containing class names of all children
Author
Klaus Meffert
Since
3.4
Definition at line 409 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.getArity(), org.jgap.gp.impl.ProgramChromosome.getChild(), org.jgap.gp.BaseGPChromosome.getIndividual(), org.jgap.gp.impl.ProgramChromosome.m_genes, and org.jgap.gp.impl.ProgramChromosome.toStringNorm().
String org.jgap.gp.impl.ProgramChromosome.toStringNorm (final int a_startNode) [inline]
Output program in `natural` notion (e.g.: `X + Y` for `X + Y`).
Parameters
a_startNode the node to start with, e.g. 0 for a complete dump of the program
Returns
output in normalized notion
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IGPChromosome.
Definition at line 350 of file ProgramChromosome.java.
References org.jgap.gp.impl.ProgramChromosome.getArity(), org.jgap.gp.impl.ProgramChromosome.getChild(), org.jgap.gp.impl.ProgramChromosome.getFunctions(), org.jgap.gp.BaseGPChromosome.getIndividual(), org.jgap.gp.impl.ProgramChromosome.m_genes, and org.jgap.gp.impl.ProgramChromosome.toString().
Referenced by org.jgap.gp.impl.ProgramChromosome.getBusinessKey(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_0(), and org.jgap.gp.impl.ProgramChromosome.toStringDebug().
Member Data Documentation
Class [] org.jgap.gp.impl.ProgramChromosome.argTypes [private]
Array to hold the types of the arguments to this Chromosome.
Definition at line 55 of file ProgramChromosome.java.
Referenced by org.jgap.gp.impl.ProgramChromosome.clone(), org.jgap.gp.impl.ProgramChromosome.getArgTypes(), org.jgap.gp.impl.ProgramChromosome.growOrFull(), org.jgap.gp.impl.ProgramChromosome.ProgramChromosome(), and org.jgap.gp.impl.ProgramChromosome.setArgTypes().
final String org.jgap.gp.impl.ProgramChromosome.CVS_REVISION = `$Revision: 1.52 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 30 of file ProgramChromosome.java.
transient Logger org.jgap.gp.impl.ProgramChromosome.LOGGER = Logger.getLogger(ProgramChromosome.class) [static], [private]
Definition at line 40 of file ProgramChromosome.java.
Object org.jgap.gp.impl.ProgramChromosome.m_applicationData [private]
Application-specific data that is attached to this Chromosome. This data may assist the application in evaluating this Chromosome in the fitness function. JGAP does not operate on the data, aside from allowing it to be set and retrieved, and considering it with comparations (if user opted in to do so).
Definition at line 73 of file ProgramChromosome.java.
Referenced by org.jgap.gp.impl.ProgramChromosome.getApplicationData().
boolean org.jgap.gp.impl.ProgramChromosome.m_compareAppData [private]
Method compareTo(): Should we also consider the application data when comparing? Default is `false` as `true` means a Chromosome's losing its identity when application data is set differently!
Since
3.0
Definition at line 82 of file ProgramChromosome.java.
Referenced by org.jgap.gp.impl.ProgramChromosome.isCompareApplicationData(), and org.jgap.gp.impl.ProgramChromosome.setCompareApplicationData().
int [] org.jgap.gp.impl.ProgramChromosome.m_depth [private]
Array to hold the depths of each node.
Definition at line 50 of file ProgramChromosome.java.
Referenced by org.jgap.gp.impl.ProgramChromosome.clone(), org.jgap.gp.impl.ProgramChromosome.getChild(), org.jgap.gp.impl.ProgramChromosome.getDepth(), org.jgap.gp.impl.ProgramChromosome.getParentNode(), org.jgap.gp.impl.ProgramChromosome.getSize(), org.jgap.gp.impl.ProgramChromosome.growOrFullNode(), org.jgap.gp.impl.ProgramChromosome.init(), and org.jgap.gp.impl.ProgramChromosome.redepth().
CommandGene [] org.jgap.gp.impl.ProgramChromosome.m_functionSet [private]
The list of allowed functions/terminals.
Definition at line 45 of file ProgramChromosome.java.
Referenced by org.jgap.gp.impl.ProgramChromosome.getFunctionSet(), org.jgap.gp.impl.ProgramChromosome.growOrFull(), org.jgap.gp.impl.ProgramChromosome.ProgramChromosome(), and org.jgap.gp.impl.ProgramChromosome.setFunctionSet().
CommandGene [] org.jgap.gp.impl.ProgramChromosome.m_genes [private]
The array of genes contained in this chromosome.
Definition at line 64 of file ProgramChromosome.java.
Referenced by org.jgap.gp.impl.ProgramChromosome.cleanup(), org.jgap.gp.impl.ProgramChromosome.clone(), org.jgap.gp.impl.ProgramChromosome.compareTo(), org.jgap.gp.impl.ProgramChromosome.execute(), org.jgap.gp.impl.ProgramChromosome.execute_boolean(), org.jgap.gp.impl.ProgramChromosome.execute_double(), org.jgap.gp.impl.ProgramChromosome.execute_float(), org.jgap.gp.impl.ProgramChromosome.execute_int(), org.jgap.gp.impl.ProgramChromosome.execute_long(), org.jgap.gp.impl.ProgramChromosome.execute_object(), org.jgap.gp.impl.ProgramChromosome.execute_void(), org.jgap.gp.impl.ProgramChromosome.getChild(), org.jgap.gp.impl.ProgramChromosome.getDepth(), org.jgap.gp.impl.ProgramChromosome.getFunctions(), org.jgap.gp.impl.ProgramChromosome.getGene(), org.jgap.gp.impl.ProgramChromosome.getNode(), org.jgap.gp.impl.ProgramChromosome.getParentNode(), org.jgap.gp.impl.ProgramChromosome.getPersistentRepresentation(), org.jgap.gp.impl.ProgramChromosome.getSize(), org.jgap.gp.impl.ProgramChromosome.growOrFullNode(), org.jgap.gp.impl.ProgramChromosome.init(), org.jgap.gp.impl.ProgramChromosome.ProgramChromosome(), org.jgap.gp.impl.ProgramChromosome.setFunctions(), org.jgap.gp.impl.ProgramChromosome.setGene(), org.jgap.gp.impl.ProgramChromosome.setValueFromPersistentRepresentation(), org.jgap.gp.impl.ProgramChromosome.size(), org.jgap.gp.impl.ProgramChromosome.toString(), org.jgap.gp.impl.ProgramChromosome.toStringDebug(), and org.jgap.gp.impl.ProgramChromosome.toStringNorm().
transient int org.jgap.gp.impl.ProgramChromosome.m_index [private]
Definition at line 57 of file ProgramChromosome.java.
Referenced by org.jgap.gp.impl.ProgramChromosome.growOrFull(), org.jgap.gp.impl.ProgramChromosome.growOrFullNode(), and org.jgap.gp.impl.ProgramChromosome.selectNode().
transient int org.jgap.gp.impl.ProgramChromosome.m_maxDepth [private]
Definition at line 59 of file ProgramChromosome.java.
Referenced by org.jgap.gp.impl.ProgramChromosome.growOrFull(), and org.jgap.gp.impl.ProgramChromosome.growOrFullNode().
Map<NodeInfo,Boolean> org.jgap.gp.impl.ProgramChromosome.m_possibleNodes = new HashMap() [private]
Definition at line 423 of file ProgramChromosome.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/impl/ProgramChromosome.java