examples.gp.tictactoe.ReadBoard Class Reference
Public Member Functions
ReadBoard (final GPConfiguration a_conf, Board a_board) throws InvalidConfigurationException
ReadBoard (final GPConfiguration a_conf, Board a_board, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException
String toString ()
String getName ()
int execute_int (ProgramChromosome c, int n, Object[] args)
Object clone ()
Private Attributes
Board m_board
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
Definition at line 17 of file ReadBoard.java.
Constructor & Destructor Documentation
examples.gp.tictactoe.ReadBoard.ReadBoard (final GPConfiguration a_conf, Board a_board) throws InvalidConfigurationException [inline]
Definition at line 24 of file ReadBoard.java.
Referenced by examples.gp.tictactoe.ReadBoard.clone().
examples.gp.tictactoe.ReadBoard.ReadBoard (final GPConfiguration a_conf, Board a_board, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException [inline]
Definition at line 29 of file ReadBoard.java.
References org.jgap.gp.CommandGene.IntegerClass, and examples.gp.tictactoe.ReadBoard.m_board.
Member Function Documentation
Object examples.gp.tictactoe.ReadBoard.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 67 of file ReadBoard.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getSubChildTypes(), org.jgap.gp.CommandGene.getSubReturnType(), examples.gp.tictactoe.ReadBoard.m_board, and examples.gp.tictactoe.ReadBoard.ReadBoard().
int examples.gp.tictactoe.ReadBoard.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 50 of file ReadBoard.java.
References org.jgap.gp.CommandGene.check().
String examples.gp.tictactoe.ReadBoard.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 46 of file ReadBoard.java.
String examples.gp.tictactoe.ReadBoard.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 36 of file ReadBoard.java.
Member Data Documentation
final String examples.gp.tictactoe.ReadBoard.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 20 of file ReadBoard.java.
Board examples.gp.tictactoe.ReadBoard.m_board [private]
Definition at line 22 of file ReadBoard.java.
Referenced by examples.gp.tictactoe.ReadBoard.clone(), and examples.gp.tictactoe.ReadBoard.ReadBoard().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/tictactoe/ReadBoard.java