org.jgap.impl.JGAPFactoryTest Class Reference
Public Member Functions
void testConstruct_0 ()
void testConstruct_1 ()
void testSetParameters_0 ()
void testRegisterCloneHandler_0 ()
void testRegisterCompareToHandler_0 ()
void testRegisterInitializer_0 ()
void testCreateRandomGenerator_0 ()
void testGetCloneHandlerFor_0 ()
void testGetCloneHandlerFor_1 ()
void testGetCloneHandlerFor_2 ()
void testGetCloneHandlerFor_3 ()
void testGetCloneHandlerFor_4 ()
void testGetCloneHandlerFor_5 ()
void testGetCloneHandlerFor_6 () throws Exception
void testGetCloneHandlerFor_7 () throws Exception
void testIsSerializable_0 () throws Exception
void testDoSerialize_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.5 $`
Additional Inherited Members
Detailed Description
Tests the JGAPFactory class.
Author
Klaus Meffert
Since
3.0
Definition at line 22 of file JGAPFactoryTest.java.
Member Function Documentation
static Test org.jgap.impl.JGAPFactoryTest.suite () [inline], [static]
Definition at line 27 of file JGAPFactoryTest.java.
void org.jgap.impl.JGAPFactoryTest.testConstruct_0 () [inline]
Author
Klaus Meffert
Since
3.0
Definition at line 36 of file JGAPFactoryTest.java.
References org.jgap.impl.JGAPFactory.isUseCaching().
void org.jgap.impl.JGAPFactoryTest.testConstruct_1 () [inline]
Author
Klaus Meffert
Since
3.0
Definition at line 45 of file JGAPFactoryTest.java.
References org.jgap.impl.JGAPFactory.isUseCaching().
void org.jgap.impl.JGAPFactoryTest.testCreateRandomGenerator_0 () [inline]
Author
Klaus Meffert
Since
3.1
Definition at line 121 of file JGAPFactoryTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.impl.JGAPFactory.createRandomGenerator().
void org.jgap.impl.JGAPFactoryTest.testDoSerialize_0 () throws Exception [inline]
Ensures that JGAPFactory and all objects contained implement Serializable correctly.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 267 of file JGAPFactoryTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.doSerialize().
void org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_0 () [inline]
Without caching.
Author
Klaus Meffert
Since
3.1
Definition at line 133 of file JGAPFactoryTest.java.
References org.jgap.impl.JGAPFactory.getCloneHandlerFor().
void org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_1 () [inline]
With caching.
Author
Klaus Meffert
Since
3.1
Definition at line 146 of file JGAPFactoryTest.java.
References org.jgap.impl.JGAPFactory.getCloneHandlerFor().
void org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_2 () [inline]
Type with no handler registered, caching active.
Author
Klaus Meffert
Since
3.1
Definition at line 162 of file JGAPFactoryTest.java.
References org.jgap.impl.JGAPFactory.getCloneHandlerFor().
void org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_3 () [inline]
Type with no handler registered, no caching
Author
Klaus Meffert
Since
3.1
Definition at line 176 of file JGAPFactoryTest.java.
References org.jgap.impl.JGAPFactory.getCloneHandlerFor().
void org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_4 () [inline]
Null type, no caching.
Author
Klaus Meffert
Since
3.1
Definition at line 190 of file JGAPFactoryTest.java.
References org.jgap.impl.JGAPFactory.getCloneHandlerFor().
void org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_5 () [inline]
Null type, with caching.
Author
Klaus Meffert
Since
3.1
Definition at line 203 of file JGAPFactoryTest.java.
References org.jgap.impl.JGAPFactory.getCloneHandlerFor().
void org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_6 () throws Exception [inline]
Request for an unsupported object instance.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 218 of file JGAPFactoryTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.JGAPFactory.getCloneHandlerFor().
void org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_7 () throws Exception [inline]
Request for a supported object instance.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 235 of file JGAPFactoryTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.JGAPFactory.getCloneHandlerFor().
void org.jgap.impl.JGAPFactoryTest.testIsSerializable_0 () throws Exception [inline]
Ensures JGAPFactory is implementing Serializable.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 252 of file JGAPFactoryTest.java.
References org.jgap.JGAPTestCase.isSerializable().
void org.jgap.impl.JGAPFactoryTest.testRegisterCloneHandler_0 () [inline]
Author
Klaus Meffert
Since
3.0
Definition at line 67 of file JGAPFactoryTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.impl.JGAPFactory.removeCloneHandler().
void org.jgap.impl.JGAPFactoryTest.testRegisterCompareToHandler_0 () [inline]
Author
Klaus Meffert
Since
3.0
Definition at line 85 of file JGAPFactoryTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.impl.JGAPFactory.removeCompareToHandler().
void org.jgap.impl.JGAPFactoryTest.testRegisterInitializer_0 () [inline]
Author
Klaus Meffert
Since
3.0
Definition at line 103 of file JGAPFactoryTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.impl.JGAPFactory.removeInitializer().
void org.jgap.impl.JGAPFactoryTest.testSetParameters_0 () [inline]
Author
Klaus Meffert
Since
3.0
Definition at line 54 of file JGAPFactoryTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.impl.JGAPFactory.getParameters().
Member Data Documentation
final String org.jgap.impl.JGAPFactoryTest.CVS_REVISION = `$Revision: 1.5 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file JGAPFactoryTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/JGAPFactoryTest.java