examples.audit.CoinsExampleFitnessFunction Class Reference
Public Member Functions
CoinsExampleFitnessFunction (int a_targetAmount)
double evaluate (IChromosome a_subject)
Static Public Member Functions
static int amountOfChange (IChromosome a_potentialSolution)
static int getNumberOfCoinsAtGene (IChromosome a_potentialSolution, int a_position)
static int getTotalNumberOfCoins (IChromosome a_potentialsolution)
Static Public Attributes
static final int MAX_BOUND = 1000
Protected Member Functions
double computeCoinNumberBonus (int a_coins)
Private Attributes
final int m_targetAmount
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Detailed Description
Sample fitness function for the coins example.
Author
Klaus Meffert
Since
2.2
Definition at line 20 of file CoinsExampleFitnessFunction.java.
Constructor & Destructor Documentation
examples.audit.CoinsExampleFitnessFunction.CoinsExampleFitnessFunction (int a_targetAmount) [inline]
Definition at line 29 of file CoinsExampleFitnessFunction.java.
References examples.audit.CoinsExampleFitnessFunction.m_targetAmount, and examples.audit.CoinsExampleFitnessFunction.MAX_BOUND.
Member Function Documentation
static int examples.audit.CoinsExampleFitnessFunction.amountOfChange (IChromosome a_potentialSolution) [inline], [static]
Calculates the total amount of change (in cents) represented by the given potential solution and returns that amount.
Parameters
a_potentialSolution the pontential solution to evaluate
Returns
the total amount of change (in cents) represented by the given solution
Author
Klaus Meffert
Since
2.2
Definition at line 100 of file CoinsExampleFitnessFunction.java.
References examples.audit.CoinsExampleFitnessFunction.getNumberOfCoinsAtGene().
Referenced by examples.audit.CoinsExampleFitnessFunction.evaluate().
double examples.audit.CoinsExampleFitnessFunction.computeCoinNumberBonus (int a_coins) [inline], [protected]
Definition at line 85 of file CoinsExampleFitnessFunction.java.
References examples.audit.CoinsExampleFitnessFunction.MAX_BOUND.
Referenced by examples.audit.CoinsExampleFitnessFunction.evaluate().
double examples.audit.CoinsExampleFitnessFunction.evaluate (IChromosome a_subject) [inline]
Determine the fitness of the given Chromosome instance. The higher the return value, the more fit the instance. This method should always return the same fitness value for two equivalent Chromosome instances.
Parameters
a_subject the Chromosome instance to evaluate
Returns
a positive integer reflecting the fitness rating of the given Chromosome
Author
Klaus Meffert
Since
2.2
Definition at line 50 of file CoinsExampleFitnessFunction.java.
References examples.audit.CoinsExampleFitnessFunction.amountOfChange(), examples.audit.CoinsExampleFitnessFunction.computeCoinNumberBonus(), examples.audit.CoinsExampleFitnessFunction.getTotalNumberOfCoins(), examples.audit.CoinsExampleFitnessFunction.m_targetAmount, and examples.audit.CoinsExampleFitnessFunction.MAX_BOUND.
static int examples.audit.CoinsExampleFitnessFunction.getNumberOfCoinsAtGene (IChromosome a_potentialSolution, int a_position) [inline], [static]
Retrieves the number of coins represented by the given potential solution at the given gene position.
Parameters
a_potentialSolution the potential solution to evaluate
a_position the gene position to evaluate
Returns
the number of coins represented by the potential solution at the given gene position.
Author
Klaus Meffert
Since
2.2
Definition at line 121 of file CoinsExampleFitnessFunction.java.
Referenced by examples.audit.CoinsExampleFitnessFunction.amountOfChange(), and examples.audit.CoinsExampleFitnessFunction.getTotalNumberOfCoins().
static int examples.audit.CoinsExampleFitnessFunction.getTotalNumberOfCoins (IChromosome a_potentialsolution) [inline], [static]
Returns the total number of coins represented by all of the genes in the given potential solution.
Parameters
a_potentialsolution The potential solution to evaluate.
Returns
The total number of coins represented by the given Chromosome.
Since
2.2
Definition at line 137 of file CoinsExampleFitnessFunction.java.
References examples.audit.CoinsExampleFitnessFunction.getNumberOfCoinsAtGene().
Referenced by examples.audit.CoinsExampleFitnessFunction.evaluate().
Member Data Documentation
final String examples.audit.CoinsExampleFitnessFunction.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 23 of file CoinsExampleFitnessFunction.java.
final int examples.audit.CoinsExampleFitnessFunction.m_targetAmount [private]
Definition at line 25 of file CoinsExampleFitnessFunction.java.
Referenced by examples.audit.CoinsExampleFitnessFunction.CoinsExampleFitnessFunction(), and examples.audit.CoinsExampleFitnessFunction.evaluate().
final int examples.audit.CoinsExampleFitnessFunction.MAX_BOUND = 1000 [static]
Definition at line 27 of file CoinsExampleFitnessFunction.java.
Referenced by examples.audit.CoinsExampleFitnessFunction.CoinsExampleFitnessFunction(), examples.audit.CoinsExampleFitnessFunction.computeCoinNumberBonus(), examples.audit.CoinsExampleFitnessFunction.evaluate(), and examples.audit.CoinsExample.main().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/audit/CoinsExampleFitnessFunction.java