org.jgap.distr.Breeder Class Reference
Public Member Functions
Breeder (final IPopulationMerger a_populationMerger)
void run ()
void start ()
void stop ()
boolean isRunning ()
boolean canBeStarted ()
boolean canBeStopped ()
Protected Member Functions
void informParent ()
Private Member Functions
void evalOneGeneration () throws Exception
synchronized void pause (final int a_milliSec)
Private Attributes
Breeder m_master
Breeder[] m_workers
Genotype m_genotype
IPopulationMerger m_populationMerger
transient boolean m_running
transient boolean m_stopped = true
transient MeanBuffer m_meanBuffer = new MeanBuffer(40)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.13 $`
Detailed Description
Breeds populations using a GA that will be executed either on a single server or on multiple servers, whose results will be merged/synchronized later on.
A breeder is part of a fractal structure (fractal because each Breeder can be parent and/or child of other Breeder's).
Author
Klaus Meffert
Since
2.0
Definition at line 25 of file Breeder.java.
Constructor & Destructor Documentation
org.jgap.distr.Breeder.Breeder (final IPopulationMerger a_populationMerger) [inline]
Definition at line 56 of file Breeder.java.
References org.jgap.distr.Breeder.m_populationMerger.
Member Function Documentation
boolean org.jgap.distr.Breeder.canBeStarted () [inline]
Definition at line 155 of file Breeder.java.
References org.jgap.distr.Breeder.m_running.
boolean org.jgap.distr.Breeder.canBeStopped () [inline]
Definition at line 159 of file Breeder.java.
References org.jgap.distr.Breeder.m_running.
void org.jgap.distr.Breeder.evalOneGeneration () throws Exception [inline], [private]
Evaluate one generation and memorize the time needed. This is important for load balancing and calculating the performance of a system
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 99 of file Breeder.java.
References org.jgap.distr.Breeder.informParent().
Referenced by org.jgap.distr.Breeder.run().
void org.jgap.distr.Breeder.informParent () [inline], [protected]
Todo
Todo implement
Definition at line 107 of file Breeder.java.
Referenced by org.jgap.distr.Breeder.evalOneGeneration().
boolean org.jgap.distr.Breeder.isRunning () [inline]
Definition at line 151 of file Breeder.java.
References org.jgap.distr.Breeder.m_running.
synchronized void org.jgap.distr.Breeder.pause (final int a_milliSec) [inline], [private]
Pauses the Breeder. This is important if a user providing a system for running the GA does not want to make available 100% of his CPU resources.
Parameters
a_milliSec number of milliseconds to wait
Author
Klaus Meffert
Since
2.0
Definition at line 119 of file Breeder.java.
Referenced by org.jgap.distr.Breeder.run().
void org.jgap.distr.Breeder.run () [inline]
Runs the evolution.
Author
Klaus Meffert
Since
2.0
Definition at line 67 of file Breeder.java.
References org.jgap.distr.Breeder.evalOneGeneration(), org.jgap.distr.Breeder.m_running, org.jgap.distr.Breeder.m_stopped, and org.jgap.distr.Breeder.pause().
void org.jgap.distr.Breeder.start () [inline]
Definition at line 128 of file Breeder.java.
References org.jgap.distr.Breeder.m_running.
void org.jgap.distr.Breeder.stop () [inline]
Todo
Todo implement
Definition at line 136 of file Breeder.java.
References org.jgap.distr.Breeder.m_genotype, and org.jgap.distr.Breeder.m_running.
Member Data Documentation
final String org.jgap.distr.Breeder.CVS_REVISION = `$Revision: 1.13 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file Breeder.java.
Genotype org.jgap.distr.Breeder.m_genotype [private]
Todo
Todo use
The Genotype this Breeder is responsible for
Definition at line 43 of file Breeder.java.
Referenced by org.jgap.distr.Breeder.stop().
Breeder org.jgap.distr.Breeder.m_master [private]
The parent Breeder to report to
Definition at line 33 of file Breeder.java.
transient MeanBuffer org.jgap.distr.Breeder.m_meanBuffer = new MeanBuffer(40) [private]
Definition at line 54 of file Breeder.java.
IPopulationMerger org.jgap.distr.Breeder.m_populationMerger [private]
Todo
Todo construct somewhere
Helper class for merging together two Populations into one.
Definition at line 48 of file Breeder.java.
Referenced by org.jgap.distr.Breeder.Breeder().
transient boolean org.jgap.distr.Breeder.m_running [private]
Todo
Todo use
Definition at line 50 of file Breeder.java.
Referenced by org.jgap.distr.Breeder.canBeStarted(), org.jgap.distr.Breeder.canBeStopped(), org.jgap.distr.Breeder.isRunning(), org.jgap.distr.Breeder.run(), org.jgap.distr.Breeder.start(), and org.jgap.distr.Breeder.stop().
transient boolean org.jgap.distr.Breeder.m_stopped = true [private]
Definition at line 52 of file Breeder.java.
Referenced by org.jgap.distr.Breeder.run().
Breeder [] org.jgap.distr.Breeder.m_workers [private]
Todo
Todo use
The child Breeder's doing work for us and reporting to this Breeder.
Definition at line 38 of file Breeder.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/distr/Breeder.java