examples.supergene.Force Class Reference
Static Public Member Functions
static boolean solve (int a_sum)
static void main (String[] args)
Static Public Attributes
static boolean REPORT_ENABLED = true
Private Member Functions
Force ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Detailed Description
Solve the change problem using force method. This class was used to verify if the solution exists in general.
Author
Audrius Meskauskas
Definition at line 18 of file Force.java.
Constructor & Destructor Documentation
examples.supergene.Force.Force () [inline], [private]
Definition at line 24 of file Force.java.
Member Function Documentation
static void examples.supergene.Force.main (String[] args) [inline], [static]
Test the Force method itself.
Parameters
args ignored
Definition at line 67 of file Force.java.
References examples.supergene.Force.solve().
static boolean examples.supergene.Force.solve (int a_sum) [inline], [static]
Check the existence of a soulution.
Parameters
a_sum the sum needed
Returns
true if the change can be expressed in coins, satisfying pennies mod 2 = nickels mod 2
Author
Audrius Meskauskas
Definition at line 37 of file Force.java.
References examples.supergene.AbstractSupergeneTest.amountOfChange(), and examples.supergene.Force.REPORT_ENABLED.
Referenced by examples.supergene.Force.main(), and examples.supergene.AbstractSupergeneTest.test().
Member Data Documentation
final String examples.supergene.Force.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 20 of file Force.java.
boolean examples.supergene.Force.REPORT_ENABLED = true [static]
Definition at line 22 of file Force.java.
Referenced by examples.supergene.Force.solve().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/supergene/Force.java