org.jgap.audit.EvaluatorTest Class Reference
Public Member Functions
void setUp ()
void testStoreGenotype_0 () throws Exception
void testCalcPerformance_0 () throws Exception
void testCalcPerformance_1 () throws Exception
void testGetNumberOfRuns_0 () throws Exception
void testCalcPerformance_2 () throws Exception
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testHasNext_0 () throws Exception
void testNext_0 () throws Exception
void testSetValue_0 () throws Exception
void testSetValue_1 () throws Exception
void testSetValue_2 () throws Exception
void testSetValue_3 () throws Exception
void testCalcAvgFitness_0 () throws Exception
void testCalcAvgFitness_1 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.14 $`
Additional Inherited Members
Detailed Description
Tests the Evaluator class.
Author
Klaus Meffert
Since
2.2
Definition at line 22 of file EvaluatorTest.java.
Member Function Documentation
void org.jgap.audit.EvaluatorTest.setUp () [inline]
Definition at line 27 of file EvaluatorTest.java.
static Test org.jgap.audit.EvaluatorTest.suite () [inline], [static]
Definition at line 31 of file EvaluatorTest.java.
void org.jgap.audit.EvaluatorTest.testCalcAvgFitness_0 () throws Exception [inline]
Consider one permutation.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 436 of file EvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.DELTA.
void org.jgap.audit.EvaluatorTest.testCalcAvgFitness_1 () throws Exception [inline]
Consider all permutations.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 466 of file EvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.DELTA.
void org.jgap.audit.EvaluatorTest.testCalcPerformance_0 () throws Exception [inline]
Definition at line 72 of file EvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.Population.determineFittestChromosome().
void org.jgap.audit.EvaluatorTest.testCalcPerformance_1 () throws Exception [inline]
Definition at line 102 of file EvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.DELTA.
void org.jgap.audit.EvaluatorTest.testCalcPerformance_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 183 of file EvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.Population.determineFittestChromosome().
void org.jgap.audit.EvaluatorTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 286 of file EvaluatorTest.java.
void org.jgap.audit.EvaluatorTest.testConstruct_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 302 of file EvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.audit.Evaluator.getData().
void org.jgap.audit.EvaluatorTest.testGetNumberOfRuns_0 () throws Exception [inline]
Definition at line 153 of file EvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.audit.Evaluator.getNumberOfRuns().
void org.jgap.audit.EvaluatorTest.testHasNext_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 317 of file EvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.audit.PermutingConfiguration.hasNext().
void org.jgap.audit.EvaluatorTest.testNext_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 331 of file EvaluatorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.audit.EvaluatorTest.testSetValue_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 351 of file EvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.audit.Evaluator.getValue().
void org.jgap.audit.EvaluatorTest.testSetValue_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 370 of file EvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.audit.Evaluator.getValue().
void org.jgap.audit.EvaluatorTest.testSetValue_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 390 of file EvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.audit.Evaluator.getValue().
void org.jgap.audit.EvaluatorTest.testSetValue_3 () throws Exception [inline]
Test for overwriting an already set value.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 414 of file EvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.audit.Evaluator.getValue().
void org.jgap.audit.EvaluatorTest.testStoreGenotype_0 () throws Exception [inline]
Definition at line 36 of file EvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.DELTA.
Member Data Documentation
final String org.jgap.audit.EvaluatorTest.CVS_REVISION = `$Revision: 1.14 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file EvaluatorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/audit/EvaluatorTest.java