org.jgap.impl.GaussianRandomGeneratorTest Class Reference
Public Member Functions
void testGeneral ()
void testConstruct_0 ()
void testConstruct_1 ()
void testGetGaussianStdDeviation_0 () throws Exception
void testNextInt_0 () throws Exception
void testNextInt_1 () throws Exception
void testNextInt_2 () throws Exception
void testNextLong_0 () throws Exception
void testNextDouble_0 () throws Exception
void testNextFloat_0 () throws Exception
void testSerialize_0 () throws Exception
void testSerialize_1 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.18 $`
Additional Inherited Members
Detailed Description
Tests the GaussianRandomGenerator class.
Author
Klaus Meffert
Since
1.1
Definition at line 23 of file GaussianRandomGeneratorTest.java.
Member Function Documentation
static Test org.jgap.impl.GaussianRandomGeneratorTest.suite () [inline], [static]
Definition at line 28 of file GaussianRandomGeneratorTest.java.
void org.jgap.impl.GaussianRandomGeneratorTest.testConstruct_0 () [inline]
Author
Klaus Meffert
Definition at line 50 of file GaussianRandomGeneratorTest.java.
void org.jgap.impl.GaussianRandomGeneratorTest.testConstruct_1 () [inline]
Author
Klaus Meffert
Definition at line 63 of file GaussianRandomGeneratorTest.java.
References org.jgap.JGAPTestCase.DELTA.
void org.jgap.impl.GaussianRandomGeneratorTest.testGeneral () [inline]
Check if construction and calculation in general possible
Author
Klaus Meffert
Definition at line 37 of file GaussianRandomGeneratorTest.java.
void org.jgap.impl.GaussianRandomGeneratorTest.testGetGaussianStdDeviation_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Todo
Todo finish
Definition at line 82 of file GaussianRandomGeneratorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.DELTA, and org.jgap.impl.GaussianRandomGenerator.getGaussianStdDeviation().
void org.jgap.impl.GaussianRandomGeneratorTest.testNextDouble_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 186 of file GaussianRandomGeneratorTest.java.
References org.jgap.JGAPTestCase.DELTA.
void org.jgap.impl.GaussianRandomGeneratorTest.testNextFloat_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 214 of file GaussianRandomGeneratorTest.java.
References org.jgap.JGAPTestCase.DELTA.
void org.jgap.impl.GaussianRandomGeneratorTest.testNextInt_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 98 of file GaussianRandomGeneratorTest.java.
void org.jgap.impl.GaussianRandomGeneratorTest.testNextInt_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 114 of file GaussianRandomGeneratorTest.java.
void org.jgap.impl.GaussianRandomGeneratorTest.testNextInt_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 138 of file GaussianRandomGeneratorTest.java.
void org.jgap.impl.GaussianRandomGeneratorTest.testNextLong_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 162 of file GaussianRandomGeneratorTest.java.
void org.jgap.impl.GaussianRandomGeneratorTest.testSerialize_0 () throws Exception [inline]
Tests serializability capabilities with default constructor.
Exceptions
Exception
Author
Klaus Meffert
Since
3.01
Todo
Todo fix test as Java 5 uses java.util.concurrent.AtomicLong instead of sun.misc.AtomicLong
Definition at line 254 of file GaussianRandomGeneratorTest.java.
References org.jgap.JGAPTestCase.doSerialize(), and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.GaussianRandomGeneratorTest.testSerialize_1 () throws Exception [inline]
Tests serializability capabilities with non-default constructor.
Exceptions
Exception
Author
Klaus Meffert
Since
3.01
Todo
Todo fix test as Java 5 uses java.util.concurrent.AtomicLong instead of sun.misc.AtomicLong
Definition at line 277 of file GaussianRandomGeneratorTest.java.
References org.jgap.JGAPTestCase.doSerialize(), and org.jgap.JGAPTestCase.privateAccessor.
Member Data Documentation
final String org.jgap.impl.GaussianRandomGeneratorTest.CVS_REVISION = `$Revision: 1.18 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file GaussianRandomGeneratorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/GaussianRandomGeneratorTest.java