org.jgap.impl.GABreeder Class Reference
Public Member Functions
GABreeder ()
Population evolve (Population a_pop, Configuration a_conf)
Configuration getLastConfiguration ()
Population getLastPopulation ()
Object clone ()
Population bulkFunctionEvaluation (Configuration a_conf, BulkFitnessFunction a_bulkFunction, Population a_pop, boolean a_monitorActive) throws InvalidConfigurationException
Protected Member Functions
void keepPopSizeConstant (Population a_pop, Configuration a_conf)
IChromosome reAddFittest (Population a_pop, IChromosome a_fittest)
void updateChromosomes (Population a_pop, Configuration a_conf)
Private Member Functions
void fillPopulationRandomlyToOriginalSize (Configuration a_conf, Population pop)
Population removeEvaluatedChromosomes (Population a_from_pop, Configuration a_config) throws InvalidConfigurationException
Population removeChromosomesWithoutFitnessValue (Population a_from_pop, Configuration a_config) throws InvalidConfigurationException
Private Attributes
transient Configuration m_lastConf
transient Population m_lastPop
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.21 $`
Additional Inherited Members
Detailed Description
Breeder for genetic algorithms. Runs the evolution process.
Author
Klaus Meffert
Vasilis
Since
3.5
Definition at line 24 of file GABreeder.java.
Constructor & Destructor Documentation
org.jgap.impl.GABreeder.GABreeder () [inline]
Definition at line 37 of file GABreeder.java.
Referenced by org.jgap.impl.GABreeder.clone().
Member Function Documentation
Population org.jgap.impl.GABreeder.bulkFunctionEvaluation (Configuration a_conf, BulkFitnessFunction a_bulkFunction, Population a_pop, boolean a_monitorActive) throws InvalidConfigurationException [inline]
Todo
Todo utilize jobs: bulk fitness function is not so important for a prototype!
Definition at line 349 of file GABreeder.java.
References org.jgap.Chromosome.clone(), org.jgap.impl.GABreeder.fillPopulationRandomlyToOriginalSize(), org.jgap.impl.GABreeder.keepPopSizeConstant(), org.jgap.FitnessFunction.NO_FITNESS_VALUE, org.jgap.impl.GABreeder.removeChromosomesWithoutFitnessValue(), org.jgap.impl.GABreeder.removeEvaluatedChromosomes(), and org.jgap.Population.size().
Referenced by org.jgap.impl.GABreeder.evolve().
Object org.jgap.impl.GABreeder.clone () [inline], [virtual]
Returns
deep clone of this instance
Author
Klaus Meffert
Since
3.2
Implements org.jgap.BreederBase.
Definition at line 272 of file GABreeder.java.
References org.jgap.impl.GABreeder.GABreeder().
Population org.jgap.impl.GABreeder.evolve (Population a_pop, Configuration a_conf) [inline]
Evolves the population of chromosomes within a genotype. This will execute all of the genetic operators added to the present active configuration and then invoke the natural selector to choose which chromosomes will be included in the next generation population.
Parameters
a_pop the population to evolve
a_conf the configuration to use for evolution
Returns
evolved population
Author
Klaus Meffert
Since
3.2
Todo
Todo utilize jobs. In pop do also utilize jobs, especially for fitness computation
Implements org.jgap.IBreeder.
Definition at line 56 of file GABreeder.java.
References org.jgap.BreederBase.applyGeneticOperators(), org.jgap.BreederBase.applyNaturalSelectors(), org.jgap.impl.GABreeder.bulkFunctionEvaluation(), org.jgap.impl.GABreeder.fillPopulationRandomlyToOriginalSize(), org.jgap.Configuration.getGenerationNr(), org.jgap.Configuration.isPreserveFittestIndividual(), org.jgap.impl.GABreeder.keepPopSizeConstant(), org.jgap.impl.GABreeder.m_lastConf, org.jgap.impl.GABreeder.m_lastPop, org.jgap.FitnessFunction.NO_FITNESS_VALUE, org.jgap.impl.GABreeder.reAddFittest(), and org.jgap.impl.GABreeder.updateChromosomes().
void org.jgap.impl.GABreeder.fillPopulationRandomlyToOriginalSize (Configuration a_conf, Population pop) [inline], [private]
Todo
Todo utilize jobs as initialization may be time-consuming as invalid combinations may have to be filtered out
Definition at line 217 of file GABreeder.java.
References org.jgap.Configuration.getGenerationNr(), org.jgap.Configuration.getMinimumPopSizePercent(), and org.jgap.Population.size().
Referenced by org.jgap.impl.GABreeder.bulkFunctionEvaluation(), and org.jgap.impl.GABreeder.evolve().
Configuration org.jgap.impl.GABreeder.getLastConfiguration () [inline]
Definition at line 258 of file GABreeder.java.
References org.jgap.impl.GABreeder.m_lastConf.
Population org.jgap.impl.GABreeder.getLastPopulation () [inline]
Definition at line 262 of file GABreeder.java.
References org.jgap.impl.GABreeder.m_lastPop.
void org.jgap.impl.GABreeder.keepPopSizeConstant (Population a_pop, Configuration a_conf) [inline], [protected]
Cares that population size is kept constant and does not exceed the desired size.
Parameters
a_pop Population
a_conf Configuration
Definition at line 283 of file GABreeder.java.
References org.jgap.Configuration.isKeepPopulationSizeConstant().
Referenced by org.jgap.impl.GABreeder.bulkFunctionEvaluation(), and org.jgap.impl.GABreeder.evolve().
IChromosome org.jgap.impl.GABreeder.reAddFittest (Population a_pop, IChromosome a_fittest) [inline], [protected]
Definition at line 293 of file GABreeder.java.
References org.jgap.Population.contains().
Referenced by org.jgap.impl.GABreeder.evolve().
Population org.jgap.impl.GABreeder.removeChromosomesWithoutFitnessValue (Population a_from_pop, Configuration a_config) throws InvalidConfigurationException [inline], [private]
Definition at line 334 of file GABreeder.java.
References org.jgap.IChromosome.getFitnessValueDirectly(), and org.jgap.FitnessFunction.NO_FITNESS_VALUE.
Referenced by org.jgap.impl.GABreeder.bulkFunctionEvaluation().
Population org.jgap.impl.GABreeder.removeEvaluatedChromosomes (Population a_from_pop, Configuration a_config) throws InvalidConfigurationException [inline], [private]
Definition at line 319 of file GABreeder.java.
References org.jgap.IChromosome.getFitnessValueDirectly(), and org.jgap.FitnessFunction.NO_FITNESS_VALUE.
Referenced by org.jgap.impl.GABreeder.bulkFunctionEvaluation().
void org.jgap.impl.GABreeder.updateChromosomes (Population a_pop, Configuration a_conf) [inline], [protected]
Definition at line 305 of file GABreeder.java.
Referenced by org.jgap.impl.GABreeder.evolve().
Member Data Documentation
final String org.jgap.impl.GABreeder.CVS_REVISION = `$Revision: 1.21 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file GABreeder.java.
transient Configuration org.jgap.impl.GABreeder.m_lastConf [private]
Definition at line 29 of file GABreeder.java.
Referenced by org.jgap.impl.GABreeder.evolve(), and org.jgap.impl.GABreeder.getLastConfiguration().
transient Population org.jgap.impl.GABreeder.m_lastPop [private]
Definition at line 31 of file GABreeder.java.
Referenced by org.jgap.impl.GABreeder.evolve(), and org.jgap.impl.GABreeder.getLastPopulation().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/GABreeder.java