examples.gp.paintedDesert.Ant Class Reference
Public Member Functions
Ant (int x, int y)
void setXpos (int m_xpos)
int getXpos ()
void setYpos (int m_ypos)
int getYpos ()
int getCarrying ()
boolean isCarrying ()
void setPickedUpFromXLoc (int pickedUpFromXLoc)
int getPickedUpFromXLoc ()
void setPickedUpFromYLoc (int pickedUpFromYLoc)
int getPickedUpFromYLoc ()
int drop (AntMap antmap)
int pickup (AntMap antmap)
int moveRandom (AntMap map)
int goE (AntMap map)
int goW (AntMap map)
int goN (AntMap map)
int goS (AntMap map)
boolean mayPickup (AntMap map)
boolean sandAtLocation (AntMap map)
boolean sandBelongsHere (AntMap map)
int sandColor (AntMap map)
void incrementMoveCounter ()
int getMoves ()
void reset ()
Private Attributes
int m_xpos
int m_ypos
int m_moves
int m_maxMoves = 500
int m_carrying = AntMap.EMPTY
int m_pickedUpFromXLoc = -1
int m_pickedUpFromYLoc = -1
int m_initX
int m_initY
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Detailed Description
Represents the Ant. Contains the rules about how an Ant behaves.
Author
Scott Mueller
Since
3.2
Definition at line 18 of file Ant.java.
Constructor & Destructor Documentation
examples.gp.paintedDesert.Ant.Ant (int x, int y) [inline]
Constructs the Ant at an initial location.
Parameters
x Initial x location
y Initial y locaiton
Definition at line 74 of file Ant.java.
References examples.gp.paintedDesert.Ant.m_initX, examples.gp.paintedDesert.Ant.m_initY, and examples.gp.paintedDesert.Ant.reset().
Member Function Documentation
int examples.gp.paintedDesert.Ant.drop (AntMap antmap) [inline]
Drops the sand at the current location if possible.
Returns
the color of sand the ant is carrying whether or not it could be dropped at the current location.
Definition at line 170 of file Ant.java.
References examples.gp.paintedDesert.AntMap.atLocation(), examples.gp.paintedDesert.AntMap.EMPTY, and examples.gp.paintedDesert.Ant.m_carrying.
int examples.gp.paintedDesert.Ant.getCarrying () [inline]
Returns the grain of sand the ant is carrying. Returns EMPTY if no sand is being carried.
Returns
The color of sand
Definition at line 117 of file Ant.java.
References examples.gp.paintedDesert.Ant.m_carrying.
int examples.gp.paintedDesert.Ant.getMoves () [inline]
Identifies the number of moves the ant has performed
Returns
Definition at line 344 of file Ant.java.
References examples.gp.paintedDesert.Ant.m_moves.
int examples.gp.paintedDesert.Ant.getPickedUpFromXLoc () [inline]
Returns the x location where the sand was picked up.
Returns
Definition at line 145 of file Ant.java.
References examples.gp.paintedDesert.Ant.m_pickedUpFromXLoc.
int examples.gp.paintedDesert.Ant.getPickedUpFromYLoc () [inline]
Returns the Y locaiton where the sand was picked up.
Returns
The Y location
Definition at line 161 of file Ant.java.
References examples.gp.paintedDesert.Ant.m_pickedUpFromYLoc.
int examples.gp.paintedDesert.Ant.getXpos () [inline]
Returns the x location of the ant.
Returns
The x location.
Definition at line 92 of file Ant.java.
References examples.gp.paintedDesert.Ant.m_xpos.
Referenced by examples.gp.paintedDesert.Ant.goE(), examples.gp.paintedDesert.Ant.goW(), examples.gp.paintedDesert.Ant.sandBelongsHere(), and examples.gp.paintedDesert.Ant.sandColor().
int examples.gp.paintedDesert.Ant.getYpos () [inline]
Returns the y location of the ant.
Returns
The y location
Definition at line 108 of file Ant.java.
References examples.gp.paintedDesert.Ant.m_ypos.
Referenced by examples.gp.paintedDesert.Ant.goN(), examples.gp.paintedDesert.Ant.goS(), examples.gp.paintedDesert.Ant.pickup(), and examples.gp.paintedDesert.Ant.sandAtLocation().
int examples.gp.paintedDesert.Ant.goE (AntMap map) [inline]
Instructs the ant to go east, if possible.
Definition at line 246 of file Ant.java.
References examples.gp.paintedDesert.AntMap.getWidth(), examples.gp.paintedDesert.Ant.getXpos(), examples.gp.paintedDesert.Ant.incrementMoveCounter(), and examples.gp.paintedDesert.Ant.sandColor().
int examples.gp.paintedDesert.Ant.goN (AntMap map) [inline]
Instructs the ant to go north, if possible
Parameters
map
Returns
The color of the sand at the new location
Definition at line 272 of file Ant.java.
References examples.gp.paintedDesert.AntMap.getHeight(), examples.gp.paintedDesert.Ant.getYpos(), examples.gp.paintedDesert.Ant.incrementMoveCounter(), and examples.gp.paintedDesert.Ant.sandColor().
int examples.gp.paintedDesert.Ant.goS (AntMap map) [inline]
Instructs the ant to go south, if possible
Parameters
map
Returns
The color of the sand at the new location
Definition at line 285 of file Ant.java.
References examples.gp.paintedDesert.Ant.getYpos(), examples.gp.paintedDesert.Ant.incrementMoveCounter(), and examples.gp.paintedDesert.Ant.sandColor().
int examples.gp.paintedDesert.Ant.goW (AntMap map) [inline]
Instructs the ant to go west, if possible
Parameters
map
Returns
The color of the sand at the new location
Definition at line 259 of file Ant.java.
References examples.gp.paintedDesert.Ant.getXpos(), examples.gp.paintedDesert.Ant.incrementMoveCounter(), and examples.gp.paintedDesert.Ant.sandColor().
void examples.gp.paintedDesert.Ant.incrementMoveCounter () [inline]
Increments the move counter for the ant
Definition at line 333 of file Ant.java.
References examples.gp.paintedDesert.Ant.m_maxMoves, and examples.gp.paintedDesert.Ant.m_moves.
Referenced by examples.gp.paintedDesert.Ant.goE(), examples.gp.paintedDesert.Ant.goN(), examples.gp.paintedDesert.Ant.goS(), examples.gp.paintedDesert.Ant.goW(), and examples.gp.paintedDesert.Ant.moveRandom().
boolean examples.gp.paintedDesert.Ant.isCarrying () [inline]
Identifies if the ant is carrying any sand.
Returns
The color of sand
Definition at line 125 of file Ant.java.
References examples.gp.paintedDesert.AntMap.EMPTY, and examples.gp.paintedDesert.Ant.m_carrying.
boolean examples.gp.paintedDesert.Ant.mayPickup (AntMap map) [inline]
Identifies whether the ant could pickup sand
Parameters
map
Returns
Definition at line 298 of file Ant.java.
int examples.gp.paintedDesert.Ant.moveRandom (AntMap map) [inline]
Randomly moves the ant.
Parameters
map The map of locations of sand
Returns
The sand at the new location of the Ant.
Definition at line 200 of file Ant.java.
References examples.gp.paintedDesert.AntMap.ANT_AT_POSITION, examples.gp.paintedDesert.AntMap.getHeight(), examples.gp.paintedDesert.AntMap.getMap(), examples.gp.paintedDesert.Ant.incrementMoveCounter(), and examples.gp.paintedDesert.Ant.sandColor().
int examples.gp.paintedDesert.Ant.pickup (AntMap antmap) [inline]
Picks up the sand at the current location, if the ant is not carrying any sand and there is sand at the location
Parameters
antmap The map of locations of sand
Returns
The sand color at the location whether or not the Ant could pick up the sand.
Definition at line 185 of file Ant.java.
References examples.gp.paintedDesert.AntMap.atLocation(), examples.gp.paintedDesert.AntMap.EMPTY, examples.gp.paintedDesert.Ant.getYpos(), examples.gp.paintedDesert.Ant.m_carrying, examples.gp.paintedDesert.Ant.m_pickedUpFromXLoc, and examples.gp.paintedDesert.Ant.m_pickedUpFromYLoc.
void examples.gp.paintedDesert.Ant.reset () [inline]
Resets the ant to its original location on the map.
Definition at line 352 of file Ant.java.
References examples.gp.paintedDesert.AntMap.EMPTY, examples.gp.paintedDesert.Ant.m_carrying, examples.gp.paintedDesert.Ant.m_initX, examples.gp.paintedDesert.Ant.m_initY, examples.gp.paintedDesert.Ant.m_moves, examples.gp.paintedDesert.Ant.m_pickedUpFromXLoc, examples.gp.paintedDesert.Ant.m_pickedUpFromYLoc, examples.gp.paintedDesert.Ant.m_xpos, and examples.gp.paintedDesert.Ant.m_ypos.
Referenced by examples.gp.paintedDesert.Ant.Ant().
boolean examples.gp.paintedDesert.Ant.sandAtLocation (AntMap map) [inline]
Identifies whether there is sand at the location
Parameters
map
Returns
true if sand at location
Definition at line 307 of file Ant.java.
References examples.gp.paintedDesert.Ant.getYpos().
boolean examples.gp.paintedDesert.Ant.sandBelongsHere (AntMap map) [inline]
Identifies that sand the ant is carrying, belongs in this column
Parameters
map
Returns
Definition at line 316 of file Ant.java.
References examples.gp.paintedDesert.Ant.getXpos().
int examples.gp.paintedDesert.Ant.sandColor (AntMap map) [inline]
Identifies the color of the sand at the ant's location
Parameters
map
Returns
Definition at line 325 of file Ant.java.
References examples.gp.paintedDesert.Ant.getXpos().
Referenced by examples.gp.paintedDesert.Ant.goE(), examples.gp.paintedDesert.Ant.goN(), examples.gp.paintedDesert.Ant.goS(), examples.gp.paintedDesert.Ant.goW(), and examples.gp.paintedDesert.Ant.moveRandom().
void examples.gp.paintedDesert.Ant.setPickedUpFromXLoc (int pickedUpFromXLoc) [inline]
Parameters
m_lastMove Stores the x location where the sand was picked up.
Definition at line 137 of file Ant.java.
void examples.gp.paintedDesert.Ant.setPickedUpFromYLoc (int pickedUpFromYLoc) [inline]
Sets the y location where the sand was picked up.
Parameters
pickedUpFromYLoc The y location
Definition at line 153 of file Ant.java.
void examples.gp.paintedDesert.Ant.setXpos (int m_xpos) [inline]
Sets the x location of the ant.
Parameters
m_xpos
Definition at line 84 of file Ant.java.
References examples.gp.paintedDesert.Ant.m_xpos.
void examples.gp.paintedDesert.Ant.setYpos (int m_ypos) [inline]
Sets the y location of the ant.
Parameters
m_ypos The y location
Definition at line 100 of file Ant.java.
References examples.gp.paintedDesert.Ant.m_ypos.
Member Data Documentation
final String examples.gp.paintedDesert.Ant.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 20 of file Ant.java.
int examples.gp.paintedDesert.Ant.m_carrying = AntMap.EMPTY [private]
The grain of sand, if any, that the Ant is carrying.
Definition at line 45 of file Ant.java.
Referenced by examples.gp.paintedDesert.Ant.drop(), examples.gp.paintedDesert.Ant.getCarrying(), examples.gp.paintedDesert.Ant.isCarrying(), examples.gp.paintedDesert.Ant.pickup(), and examples.gp.paintedDesert.Ant.reset().
int examples.gp.paintedDesert.Ant.m_initX [private]
The initial x location of the ant. This is used when the ant is reset back to it's original location.
Definition at line 61 of file Ant.java.
Referenced by examples.gp.paintedDesert.Ant.Ant(), and examples.gp.paintedDesert.Ant.reset().
int examples.gp.paintedDesert.Ant.m_initY [private]
The initial y locaiton of the Ant. This is used when the ant is reset back to it's original location.
Definition at line 67 of file Ant.java.
Referenced by examples.gp.paintedDesert.Ant.Ant(), and examples.gp.paintedDesert.Ant.reset().
int examples.gp.paintedDesert.Ant.m_maxMoves = 500 [private]
The maximum number of moves an Ant is allowed to move in a particular program.
Definition at line 40 of file Ant.java.
Referenced by examples.gp.paintedDesert.Ant.incrementMoveCounter().
int examples.gp.paintedDesert.Ant.m_moves [private]
The number of moves the ant has made
Definition at line 35 of file Ant.java.
Referenced by examples.gp.paintedDesert.Ant.getMoves(), examples.gp.paintedDesert.Ant.incrementMoveCounter(), and examples.gp.paintedDesert.Ant.reset().
int examples.gp.paintedDesert.Ant.m_pickedUpFromXLoc = -1 [private]
The x location the ant picked up the sand from.
Definition at line 50 of file Ant.java.
Referenced by examples.gp.paintedDesert.Ant.getPickedUpFromXLoc(), examples.gp.paintedDesert.Ant.pickup(), and examples.gp.paintedDesert.Ant.reset().
int examples.gp.paintedDesert.Ant.m_pickedUpFromYLoc = -1 [private]
The y location the ant picked up the sand from.
Definition at line 55 of file Ant.java.
Referenced by examples.gp.paintedDesert.Ant.getPickedUpFromYLoc(), examples.gp.paintedDesert.Ant.pickup(), and examples.gp.paintedDesert.Ant.reset().
int examples.gp.paintedDesert.Ant.m_xpos [private]
The x position of the Ant
Definition at line 25 of file Ant.java.
Referenced by examples.gp.paintedDesert.Ant.getXpos(), examples.gp.paintedDesert.Ant.reset(), and examples.gp.paintedDesert.Ant.setXpos().
int examples.gp.paintedDesert.Ant.m_ypos [private]
The y position of the Ant
Definition at line 30 of file Ant.java.
Referenced by examples.gp.paintedDesert.Ant.getYpos(), examples.gp.paintedDesert.Ant.reset(), and examples.gp.paintedDesert.Ant.setYpos().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/paintedDesert/Ant.java