org.jgap.BreederBase Class Reference
Public Member Functions
BreederBase ()
abstract Object clone ()
int compareTo (Object a_other)
Public Attributes
int select
int merge
Protected Member Functions
Population applyNaturalSelectors (Configuration a_config, Population a_pop, boolean a_processBeforeGeneticOperators)
void applyGeneticOperators (Configuration a_config, Population a_pop)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.10 $`
Additional Inherited Members
Detailed Description
Abstract base class for breeders.
Author
Klaus Meffert
Since
3.2
Definition at line 23 of file BreederBase.java.
Constructor & Destructor Documentation
org.jgap.BreederBase.BreederBase () [inline]
Definition at line 33 of file BreederBase.java.
Member Function Documentation
void org.jgap.BreederBase.applyGeneticOperators (Configuration a_config, Population a_pop) [inline], [protected]
Applies all GeneticOperators registered with the Configuration.
Parameters
a_config the configuration to use
a_pop the population to use as input
Author
Klaus Meffert
Since
3.2
Todo
Todo utilize jobs: integrate job into GeneticOperator
Definition at line 126 of file BreederBase.java.
References org.jgap.Configuration.getGenerationNr().
Referenced by org.jgap.impl.GABreeder.evolve().
Population org.jgap.BreederBase.applyNaturalSelectors (Configuration a_config, Population a_pop, boolean a_processBeforeGeneticOperators) [inline], [protected]
Applies all NaturalSelectors registered with the Configuration.
Parameters
a_config the configuration to use
a_pop the population to use as input
a_processBeforeGeneticOperators true apply NaturalSelectors applicable before GeneticOperators, false: apply the ones applicable after GeneticOperators
Returns
selected part of input population
Author
Klaus Meffert
Since
3.2
Todo
Todo optionally use working pool
Todo
Todo utilize jobs: integrate job into NaturalSelector!
Definition at line 49 of file BreederBase.java.
References org.jgap.Configuration.getGenerationNr(), and org.jgap.Configuration.getSelectFromPrevGen().
Referenced by org.jgap.impl.GABreeder.evolve().
abstract Object org.jgap.BreederBase.clone () [pure virtual]
Returns
deep clone of this instance
Author
Klaus Meffert
Since
3.2
Implements org.jgap.util.ICloneable.
Implemented in org.jgap.impl.GABreeder.
int org.jgap.BreederBase.compareTo (Object a_other) [inline]
Parameters
a_other object to compare to
Returns
as always
Author
Klaus Meffert
Since
3.2
Definition at line 178 of file BreederBase.java.
Member Data Documentation
final String org.jgap.BreederBase.CVS_REVISION = `$Revision: 1.10 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file BreederBase.java.
int org.jgap.BreederBase.merge
Definition at line 30 of file BreederBase.java.
int org.jgap.BreederBase.select
Definition at line 28 of file BreederBase.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/BreederBase.java