examples.math.cmd.DivideOperator Class Reference
Public Member Functions
DivideOperator ()
DivideOperator (Operand theLeft, Operand theRight)
double calcuate ()
void accept (MathVisitor theVisitor)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.1 $`
Additional Inherited Members
Detailed Description
The divide operator.
Author
Michael Grove
Since
3.4.2
Definition at line 20 of file DivideOperator.java.
Constructor & Destructor Documentation
examples.math.cmd.DivideOperator.DivideOperator () [inline]
Definition at line 25 of file DivideOperator.java.
Referenced by examples.math.cmd.DivideOperator.clone().
examples.math.cmd.DivideOperator.DivideOperator (Operand theLeft, Operand theRight) [inline]
Definition at line 29 of file DivideOperator.java.
Member Function Documentation
void examples.math.cmd.DivideOperator.accept (MathVisitor theVisitor) [inline]
Implements examples.math.cmd.Operand.
Definition at line 37 of file DivideOperator.java.
double examples.math.cmd.DivideOperator.calcuate () [inline]
Implements examples.math.cmd.Operator.
Definition at line 33 of file DivideOperator.java.
References examples.math.cmd.MathOperator.getLeftOperand(), and examples.math.cmd.MathOperator.getRightOperand().
Object examples.math.cmd.DivideOperator.clone () [inline], [virtual]
Implements examples.math.cmd.MathOperator.
Definition at line 41 of file DivideOperator.java.
References examples.math.cmd.DivideOperator.DivideOperator().
Member Data Documentation
final String examples.math.cmd.DivideOperator.CVS_REVISION = `$Revision: 1.1 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 23 of file DivideOperator.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/math/cmd/DivideOperator.java