org.jgap.gp.function.Tupel Class Reference
Public Member Functions
Tupel (final GPConfiguration a_conf, Class[] a_types) throws InvalidConfigurationException
Tupel (final GPConfiguration a_conf, Class[] a_types, Class a_returnType) throws InvalidConfigurationException
String toString ()
String getName ()
Object execute_object (ProgramChromosome c, int n, Object[] args)
int compareTo (Object a_other)
boolean equals (Object a_other)
Object clone ()
Private Attributes
Class[] m_types
Object[] m_values
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Additional Inherited Members
Detailed Description
Holds a tupel of n values of arbitrary type. Useful to server as a return type with more than one component.
Author
Klaus Meffert
Since
3.4.3
Definition at line 25 of file Tupel.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Tupel.Tupel (final GPConfiguration a_conf, Class[] a_types) throws InvalidConfigurationException [inline]
Definition at line 34 of file Tupel.java.
Referenced by org.jgap.gp.function.Tupel.clone(), org.jgap.gp.function.Tupel.compareTo(), and org.jgap.gp.function.Tupel.equals().
org.jgap.gp.function.Tupel.Tupel (final GPConfiguration a_conf, Class[] a_types, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 39 of file Tupel.java.
References org.jgap.gp.function.Tupel.m_types.
Member Function Documentation
Object org.jgap.gp.function.Tupel.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4.3
Implements org.jgap.util.ICloneable.
Definition at line 119 of file Tupel.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), org.jgap.gp.function.Tupel.m_types, and org.jgap.gp.function.Tupel.Tupel().
int org.jgap.gp.function.Tupel.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.4.3
Definition at line 79 of file Tupel.java.
References org.jgap.gp.function.Tupel.m_types, and org.jgap.gp.function.Tupel.Tupel().
boolean org.jgap.gp.function.Tupel.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Klaus Meffert
Since
3.4.3
Definition at line 99 of file Tupel.java.
References org.jgap.gp.function.Tupel.m_types, and org.jgap.gp.function.Tupel.Tupel().
Object org.jgap.gp.function.Tupel.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 60 of file Tupel.java.
References org.jgap.gp.function.Tupel.m_values, and org.jgap.gp.CommandGene.size().
String org.jgap.gp.function.Tupel.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 56 of file Tupel.java.
String org.jgap.gp.function.Tupel.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 46 of file Tupel.java.
References org.jgap.gp.function.Tupel.m_types.
Member Data Documentation
final String org.jgap.gp.function.Tupel.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file Tupel.java.
Class [] org.jgap.gp.function.Tupel.m_types [private]
Definition at line 30 of file Tupel.java.
Referenced by org.jgap.gp.function.Tupel.clone(), org.jgap.gp.function.Tupel.compareTo(), org.jgap.gp.function.Tupel.equals(), org.jgap.gp.function.Tupel.toString(), and org.jgap.gp.function.Tupel.Tupel().
Object [] org.jgap.gp.function.Tupel.m_values [private]
Definition at line 32 of file Tupel.java.
Referenced by org.jgap.gp.function.Tupel.execute_object().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Tupel.java