org.jgap.gp.function.Xor Class Reference
Public Member Functions
Xor (final GPConfiguration a_conf) throws InvalidConfigurationException
CommandGene applyMutation (int index, double a_percentage) throws InvalidConfigurationException
String toString ()
String getName ()
boolean execute_boolean (ProgramChromosome c, int n, Object[] args)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.7 $`
Additional Inherited Members
Detailed Description
The boolean xor operation.
Author
Klaus Meffert
Since
3.0
Definition at line 23 of file Xor.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Xor.Xor (final GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Definition at line 29 of file Xor.java.
References org.jgap.gp.CommandGene.BooleanClass.
Referenced by org.jgap.gp.function.Xor.clone().
Member Function Documentation
CommandGene org.jgap.gp.function.Xor.applyMutation (int index, double a_percentage) throws InvalidConfigurationException [inline]
Definition at line 34 of file Xor.java.
References org.jgap.gp.CommandGene.getGPConfiguration().
Object org.jgap.gp.function.Xor.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 72 of file Xor.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.function.Xor.Xor().
boolean org.jgap.gp.function.Xor.execute_boolean (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 60 of file Xor.java.
String org.jgap.gp.function.Xor.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 56 of file Xor.java.
String org.jgap.gp.function.Xor.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 46 of file Xor.java.
Member Data Documentation
final String org.jgap.gp.function.Xor.CVS_REVISION = `$Revision: 1.7 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file Xor.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Xor.java