org.jgap.impl.WeightedRouletteSelector Class Reference
Classes
class WeightedRouletteSelConfig
Public Member Functions
WeightedRouletteSelector () throws InvalidConfigurationException
WeightedRouletteSelector (Configuration a_config) throws InvalidConfigurationException
synchronized void selectChromosomes (int a_howManyToSelect, Population a_to_pop)
synchronized void empty ()
boolean returnsUniqueChromosomes ()
void setDoubletteChromosomesAllowed (final boolean a_doublettesAllowed)
boolean getDoubletteChromosomesAllowed ()
Object clone ()
boolean equals (Object o)
Protected Member Functions
synchronized void add (final IChromosome a_chromosomeToAdd)
Private Member Functions
IChromosome spinWheel (final RandomGenerator a_generator, final double[] a_fitnessValues, double[] a_counterValues, final IChromosome[] a_chromosomes)
void scaleFitnessValues ()
Private Attributes
THashMap m_wheel = new THashMap()
double m_totalNumberOfUsedSlots
transient Pool m_counterPool
WeightedRouletteSelConfig m_config = new WeightedRouletteSelConfig()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.44 $`
static final double DELTA = 0.000001d
static final BigDecimal ZERO_BIG_DECIMAL = new BigDecimal(0.0d)
Additional Inherited Members
Detailed Description
A basic implementation of NaturalSelector that models a roulette wheel. When a Chromosome is added, it gets a number of `slots` on the wheel equal to its fitness value. When the select method is invoked, the wheel is `spun` and the Chromosome occupying the spot on which it lands is selected. Then the wheel is spun again and again until the requested number of Chromosomes have been selected. Since Chromosomes with higher fitness values get more slots on the wheel, there's a higher statistical probability that they'll be chosen, but it's not guaranteed.
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 33 of file WeightedRouletteSelector.java.
Constructor & Destructor Documentation
org.jgap.impl.WeightedRouletteSelector.WeightedRouletteSelector () throws InvalidConfigurationException [inline]
Default constructor.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.0
Definition at line 77 of file WeightedRouletteSelector.java.
Referenced by org.jgap.impl.WeightedRouletteSelector.clone(), and org.jgap.impl.WeightedRouletteSelector.equals().
org.jgap.impl.WeightedRouletteSelector.WeightedRouletteSelector (Configuration a_config) throws InvalidConfigurationException [inline]
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 90 of file WeightedRouletteSelector.java.
References org.jgap.impl.WeightedRouletteSelector.m_counterPool.
Member Function Documentation
synchronized void org.jgap.impl.WeightedRouletteSelector.add (final IChromosome a_chromosomeToAdd) [inline], [protected], [virtual]
Add a chromosome instance to this selector's working pool of chromosomes.
Parameters
a_chromosomeToAdd the chromosom to add to the pool
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Implements org.jgap.NaturalSelectorExt.
Definition at line 106 of file WeightedRouletteSelector.java.
References org.jgap.impl.Pool.acquirePooledObject(), org.jgap.impl.WeightedRouletteSelector.m_counterPool, and org.jgap.impl.WeightedRouletteSelector.m_wheel.
Object org.jgap.impl.WeightedRouletteSelector.clone () [inline]
Returns
deep clone of this instance
Author
Klaus Meffert
Since
3.2
Implements org.jgap.util.ICloneable.
Definition at line 419 of file WeightedRouletteSelector.java.
References org.jgap.NaturalSelector.getConfiguration(), org.jgap.impl.WeightedRouletteSelector.m_wheel, and org.jgap.impl.WeightedRouletteSelector.WeightedRouletteSelector().
synchronized void org.jgap.impl.WeightedRouletteSelector.empty () [inline]
Empty out the working pool of Chromosomes.
Author
Neil Rotstan
Since
1.0
Implements org.jgap.INaturalSelector.
Definition at line 333 of file WeightedRouletteSelector.java.
References org.jgap.impl.WeightedRouletteSelector.m_totalNumberOfUsedSlots.
boolean org.jgap.impl.WeightedRouletteSelector.equals (Object o) [inline]
Definition at line 432 of file WeightedRouletteSelector.java.
References org.jgap.impl.WeightedRouletteSelector.m_config, org.jgap.impl.WeightedRouletteSelector.m_counterPool, org.jgap.impl.WeightedRouletteSelector.m_totalNumberOfUsedSlots, org.jgap.impl.WeightedRouletteSelector.m_wheel, and org.jgap.impl.WeightedRouletteSelector.WeightedRouletteSelector().
boolean org.jgap.impl.WeightedRouletteSelector.getDoubletteChromosomesAllowed () [inline]
Returns
TRUE: doublette chromosomes allowed to be added by the selector
Author
Klaus Meffert
Since
2.0
Definition at line 409 of file WeightedRouletteSelector.java.
Referenced by org.jgap.impl.WeightedRouletteSelector.spinWheel().
boolean org.jgap.impl.WeightedRouletteSelector.returnsUniqueChromosomes () [inline]
Returns
always false as some Chromosome's could be returnd multiple times
Author
Klaus Meffert
Since
2.0
Implements org.jgap.INaturalSelector.
Definition at line 385 of file WeightedRouletteSelector.java.
void org.jgap.impl.WeightedRouletteSelector.scaleFitnessValues () [inline], [private]
Definition at line 344 of file WeightedRouletteSelector.java.
References org.jgap.impl.WeightedRouletteSelector.ZERO_BIG_DECIMAL.
Referenced by org.jgap.impl.WeightedRouletteSelector.selectChromosomes().
synchronized void org.jgap.impl.WeightedRouletteSelector.selectChromosomes (int a_howManyToSelect, Population a_to_pop) [inline]
Select a given number of Chromosomes from the pool that will move on to the next generation population. This selection should be guided by the fitness values, but fitness should be treated as a statistical probability of survival, not as the sole determining factor. In other words, Chromosomes with higher fitness values should be more likely to be selected than those with lower fitness values, but it should not be guaranteed.
Parameters
a_howManyToSelect the number of Chromosomes to select
a_to_pop the population the Chromosomes will be added to
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 158 of file WeightedRouletteSelector.java.
References org.jgap.Population.contains(), org.jgap.NaturalSelector.getConfiguration(), org.jgap.NaturalSelector.m_monitorActive, org.jgap.impl.WeightedRouletteSelector.m_totalNumberOfUsedSlots, org.jgap.IHandler.perform(), org.jgap.impl.WeightedRouletteSelector.scaleFitnessValues(), and org.jgap.impl.WeightedRouletteSelector.spinWheel().
void org.jgap.impl.WeightedRouletteSelector.setDoubletteChromosomesAllowed (final boolean a_doublettesAllowed) [inline]
Not supported by this selector! Please do not use it.
Parameters
a_doublettesAllowed do not use
Author
Klaus Meffert
Since
2.0
Definition at line 397 of file WeightedRouletteSelector.java.
IChromosome org.jgap.impl.WeightedRouletteSelector.spinWheel (final RandomGenerator a_generator, final double[] a_fitnessValues, double[] a_counterValues, final IChromosome[] a_chromosomes) [inline], [private]
This method `spins` the wheel and returns the Chromosome that is `landed upon.` Each time a chromosome is selected, one instance of it is removed from the wheel so that it cannot be selected again.
Parameters
a_generator the random number generator to be used during the spinning process
a_fitnessValues an array of fitness values of the respective Chromosomes
a_counterValues an array of total counter values of the respective Chromosomes
a_chromosomes the respective Chromosome instances from which selection is to occur
Returns
selected Chromosome from the roulette wheel
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 252 of file WeightedRouletteSelector.java.
References org.jgap.impl.WeightedRouletteSelector.DELTA, org.jgap.NaturalSelector.getConfiguration(), org.jgap.impl.WeightedRouletteSelector.getDoubletteChromosomesAllowed(), and org.jgap.impl.WeightedRouletteSelector.m_totalNumberOfUsedSlots.
Referenced by org.jgap.impl.WeightedRouletteSelector.selectChromosomes().
Member Data Documentation
final String org.jgap.impl.WeightedRouletteSelector.CVS_REVISION = `$Revision: 1.44 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 36 of file WeightedRouletteSelector.java.
final double org.jgap.impl.WeightedRouletteSelector.DELTA = 0.000001d [static], [private]
Definition at line 39 of file WeightedRouletteSelector.java.
Referenced by org.jgap.impl.WeightedRouletteSelector.spinWheel().
WeightedRouletteSelConfig org.jgap.impl.WeightedRouletteSelector.m_config = new WeightedRouletteSelConfig() [private]
Definition at line 65 of file WeightedRouletteSelector.java.
Referenced by org.jgap.impl.WeightedRouletteSelector.equals().
transient Pool org.jgap.impl.WeightedRouletteSelector.m_counterPool [private]
An internal pool in which discarded SlotCounter instances can be stored so that they can be reused over and over again, thus saving memory and the overhead of constructing new ones each time.
Definition at line 62 of file WeightedRouletteSelector.java.
Referenced by org.jgap.impl.WeightedRouletteSelector.add(), org.jgap.impl.WeightedRouletteSelector.equals(), and org.jgap.impl.WeightedRouletteSelector.WeightedRouletteSelector().
double org.jgap.impl.WeightedRouletteSelector.m_totalNumberOfUsedSlots [private]
Keeps track of the total number of slots that are in use on the roulette wheel. This is equal to the combined fitness values of all Chromosome instances that have been added to this wheel.
Definition at line 55 of file WeightedRouletteSelector.java.
Referenced by org.jgap.impl.WeightedRouletteSelector.empty(), org.jgap.impl.WeightedRouletteSelector.equals(), org.jgap.impl.WeightedRouletteSelector.selectChromosomes(), and org.jgap.impl.WeightedRouletteSelector.spinWheel().
THashMap org.jgap.impl.WeightedRouletteSelector.m_wheel = new THashMap() [private]
Represents the `roulette wheel.` Each key in the Map is a Chromosome and each value is an instance of the SlotCounter inner class, which keeps track of how many slots on the wheel each Chromosome is occupying.
Definition at line 48 of file WeightedRouletteSelector.java.
Referenced by org.jgap.impl.WeightedRouletteSelector.add(), org.jgap.impl.WeightedRouletteSelector.clone(), and org.jgap.impl.WeightedRouletteSelector.equals().
final BigDecimal org.jgap.impl.WeightedRouletteSelector.ZERO_BIG_DECIMAL = new BigDecimal(0.0d) [static], [private]
Definition at line 41 of file WeightedRouletteSelector.java.
Referenced by org.jgap.impl.WeightedRouletteSelector.scaleFitnessValues().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/WeightedRouletteSelector.java