org.jgap.impl.CrossoverOperatorTest Class Reference
Classes
class GeneticOperatorConstraintForTesting
Public Member Functions
void setUp ()
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testConstruct_2 () throws Exception
void testConstruct_4 () throws Exception
void testConstruct_5 () throws Exception
void testConstruct_6 () throws Exception
void testConstruct_7 () throws Exception
void testConstruct_8 () throws Exception
void testConstruct_9 () throws Exception
void testOperate_0 () throws Exception
void testOperate_0_2 () throws Exception
void testOperate_1 () throws Exception
void testOperate_2 () throws Exception
void testOperate_3 () throws Exception
void testIsSerializable_0 () throws Exception
void testDoSerialize_0 () throws Exception
void testDoSerialize_1 () throws Exception
void testEquals_0 () throws Exception
void testCompareTo_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.33 $`
Additional Inherited Members
Detailed Description
Tests the CrossoverOperator class.
Author
Klaus Meffert
Since
1.1
Definition at line 22 of file CrossoverOperatorTest.java.
Member Function Documentation
void org.jgap.impl.CrossoverOperatorTest.setUp () [inline]
Definition at line 32 of file CrossoverOperatorTest.java.
static Test org.jgap.impl.CrossoverOperatorTest.suite () [inline], [static]
Definition at line 27 of file CrossoverOperatorTest.java.
void org.jgap.impl.CrossoverOperatorTest.testCompareTo_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 557 of file CrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.CrossoverOperator.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CrossoverOperatorTest.testConstruct_0 () throws Exception [inline]
Following should be possible without error.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 43 of file CrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CrossoverOperatorTest.testConstruct_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 57 of file CrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CrossoverOperatorTest.testConstruct_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 72 of file CrossoverOperatorTest.java.
void org.jgap.impl.CrossoverOperatorTest.testConstruct_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.3.2
Definition at line 88 of file CrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseGeneticOperator.getConfiguration(), org.jgap.impl.CrossoverOperator.getCrossOverRate(), and org.jgap.impl.CrossoverOperator.isAllowFullCrossOver().
void org.jgap.impl.CrossoverOperatorTest.testConstruct_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.3.2
Definition at line 102 of file CrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseGeneticOperator.getConfiguration(), org.jgap.impl.CrossoverOperator.getCrossOverRate(), and org.jgap.impl.CrossoverOperator.isAllowFullCrossOver().
void org.jgap.impl.CrossoverOperatorTest.testConstruct_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.3.2
Definition at line 116 of file CrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseGeneticOperator.getConfiguration(), org.jgap.impl.CrossoverOperator.getCrossOverRate(), and org.jgap.impl.CrossoverOperator.isAllowFullCrossOver().
void org.jgap.impl.CrossoverOperatorTest.testConstruct_7 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.3.2
Definition at line 130 of file CrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, org.jgap.BaseGeneticOperator.getConfiguration(), org.jgap.impl.CrossoverOperator.getCrossOverRatePercent(), and org.jgap.impl.CrossoverOperator.isAllowFullCrossOver().
void org.jgap.impl.CrossoverOperatorTest.testConstruct_8 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.3.2
Definition at line 144 of file CrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, org.jgap.BaseGeneticOperator.getConfiguration(), org.jgap.impl.CrossoverOperator.getCrossOverRatePercent(), and org.jgap.impl.CrossoverOperator.isAllowFullCrossOver().
void org.jgap.impl.CrossoverOperatorTest.testConstruct_9 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.3.2
Definition at line 158 of file CrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, org.jgap.BaseGeneticOperator.getConfiguration(), org.jgap.impl.CrossoverOperator.getCrossOverRatePercent(), and org.jgap.impl.CrossoverOperator.isAllowFullCrossOver().
void org.jgap.impl.CrossoverOperatorTest.testDoSerialize_0 () throws Exception [inline]
Ensures that the operator and all objects contained implement Serializable. Here, we use a null configuration.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 493 of file CrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.doSerialize().
void org.jgap.impl.CrossoverOperatorTest.testDoSerialize_1 () throws Exception [inline]
Ensures that the operator and all objects contained implement Serializable. Here, we set a configuration.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 512 of file CrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.doSerialize().
void org.jgap.impl.CrossoverOperatorTest.testEquals_0 () throws Exception [inline]
Test equals with classcast object.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 545 of file CrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CrossoverOperatorTest.testIsSerializable_0 () throws Exception [inline]
Ensures the operator is implementing Serializable.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 479 of file CrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.isSerializable().
void org.jgap.impl.CrossoverOperatorTest.testOperate_0 () throws Exception [inline]
Use flat crossover rate and just exchange two alleles via crossover.
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 174 of file CrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CrossoverOperatorTest.testOperate_0_2 () throws Exception [inline]
Consider crossover rate calculator.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 240 of file CrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CrossoverOperatorTest.testOperate_1 () throws Exception [inline]
Tests if crossing over produces same results for two operate-runs.
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 306 of file CrossoverOperatorTest.java.
References org.jgap.Chromosome.clone(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.isChromosomesEqual().
void org.jgap.impl.CrossoverOperatorTest.testOperate_2 () throws Exception [inline]
Test with CompositeGene.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 357 of file CrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.getAllele().
void org.jgap.impl.CrossoverOperatorTest.testOperate_3 () throws Exception [inline]
Considers IGeneticOperatorConstraint. Here, the crossing over of a BooleanGene is forbidden by that constraint.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 416 of file CrossoverOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
Member Data Documentation
final String org.jgap.impl.CrossoverOperatorTest.CVS_REVISION = `$Revision: 1.33 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file CrossoverOperatorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/CrossoverOperatorTest.java