org.jgap.audit.KeyedValues2DTest Class Reference
Public Member Functions
void setUp ()
void testSerializable_0 () throws Exception
void testConstruct_0 () throws Exception
void testSetValue_0 () throws Exception
void testSetValue_02 () throws Exception
void testSetValue_1 () throws Exception
void testSetValue_2 () throws Exception
void testSetValue_3 () throws Exception
void testGetValue_0 () throws Exception
void testClone_0 () throws Exception
void testEquals_0 () throws Exception
void testEquals_1 () throws Exception
void testEquals_2 () throws Exception
void testEquals_3 () throws Exception
void testEquals_4 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
Tests for KeyedValues2D class
Author
Klaus Meffert
Since
3.0
Definition at line 22 of file KeyedValues2DTest.java.
Member Function Documentation
void org.jgap.audit.KeyedValues2DTest.setUp () [inline]
Definition at line 27 of file KeyedValues2DTest.java.
static Test org.jgap.audit.KeyedValues2DTest.suite () [inline], [static]
Definition at line 31 of file KeyedValues2DTest.java.
void org.jgap.audit.KeyedValues2DTest.testClone_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 178 of file KeyedValues2DTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.audit.KeyedValues2D.clone(), org.jgap.audit.KeyedValues2D.getColumnKey(), org.jgap.audit.KeyedValues2D.getRowKey(), and org.jgap.audit.KeyedValues2D.getValue().
void org.jgap.audit.KeyedValues2DTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 58 of file KeyedValues2DTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.audit.KeyedValues2D.getColumnCount(), and org.jgap.audit.KeyedValues2D.getRowCount().
void org.jgap.audit.KeyedValues2DTest.testEquals_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 198 of file KeyedValues2DTest.java.
References org.jgap.audit.KeyedValues2D.equals().
void org.jgap.audit.KeyedValues2DTest.testEquals_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 212 of file KeyedValues2DTest.java.
References org.jgap.audit.KeyedValues2D.equals().
void org.jgap.audit.KeyedValues2DTest.testEquals_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 230 of file KeyedValues2DTest.java.
References org.jgap.audit.KeyedValues2D.equals().
void org.jgap.audit.KeyedValues2DTest.testEquals_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 250 of file KeyedValues2DTest.java.
References org.jgap.audit.KeyedValues2D.equals().
void org.jgap.audit.KeyedValues2DTest.testEquals_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 270 of file KeyedValues2DTest.java.
References org.jgap.audit.KeyedValues2D.equals().
void org.jgap.audit.KeyedValues2DTest.testGetValue_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 164 of file KeyedValues2DTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.audit.KeyedValues2D.getValue().
void org.jgap.audit.KeyedValues2DTest.testSerializable_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 42 of file KeyedValues2DTest.java.
void org.jgap.audit.KeyedValues2DTest.testSetValue_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 71 of file KeyedValues2DTest.java.
References org.jgap.audit.KeyedValues2D.getRowKey(), and org.jgap.audit.KeyedValues2D.getValue().
void org.jgap.audit.KeyedValues2DTest.testSetValue_02 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 94 of file KeyedValues2DTest.java.
References org.jgap.audit.KeyedValues2D.getRowKey(), and org.jgap.audit.KeyedValues2D.getValue().
void org.jgap.audit.KeyedValues2DTest.testSetValue_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 117 of file KeyedValues2DTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.audit.KeyedValues2D.getValue().
void org.jgap.audit.KeyedValues2DTest.testSetValue_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 132 of file KeyedValues2DTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.audit.KeyedValues2D.getValue().
void org.jgap.audit.KeyedValues2DTest.testSetValue_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 147 of file KeyedValues2DTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.audit.KeyedValues2D.getValue().
Member Data Documentation
final String org.jgap.audit.KeyedValues2DTest.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file KeyedValues2DTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/audit/KeyedValues2DTest.java