org.jgap.gp.function.Exp Class Reference
Classes
interface Compatible
Public Member Functions
Exp (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException
String toString ()
String getName ()
int execute_int (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.9 $`
Additional Inherited Members
Detailed Description
The exponential operation.
Author
Klaus Meffert
Since
3.0
Definition at line 23 of file Exp.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Exp.Exp (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 28 of file Exp.java.
Referenced by org.jgap.gp.function.Exp.clone().
Member Function Documentation
Object org.jgap.gp.function.Exp.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 80 of file Exp.java.
References org.jgap.gp.function.Exp.Exp(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.CommandGene.getReturnType().
double org.jgap.gp.function.Exp.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 59 of file Exp.java.
float org.jgap.gp.function.Exp.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 53 of file Exp.java.
int org.jgap.gp.function.Exp.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 47 of file Exp.java.
Object org.jgap.gp.function.Exp.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 65 of file Exp.java.
String org.jgap.gp.function.Exp.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 43 of file Exp.java.
String org.jgap.gp.function.Exp.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 33 of file Exp.java.
Member Data Documentation
final String org.jgap.gp.function.Exp.CVS_REVISION = `$Revision: 1.9 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file Exp.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Exp.java