examples.gp.KarubProblem Class Reference
Classes
class FormulaFitnessFunction
Public Member Functions
KarubProblem (GPConfiguration a_conf) throws InvalidConfigurationException
GPGenotype create () throws InvalidConfigurationException
Static Public Member Functions
static void main (String[] args) throws Exception
Static Public Attributes
static Variable vx
Additional Inherited Members
Detailed Description
Sort of minimal GP problem definition. Does not stop when best solution found. Discovers a very simple formula (see comments in code!).
Only there to show the general setup.
Inspired by user Karub (who wrote most of the code in this class), therefor `KarubProblem`
Author
Klaus Meffert
Since
3.5
Definition at line 39 of file KarubProblem.java.
Constructor & Destructor Documentation
examples.gp.KarubProblem.KarubProblem (GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Definition at line 43 of file KarubProblem.java.
Referenced by examples.gp.KarubProblem.main().
Member Function Documentation
GPGenotype examples.gp.KarubProblem.create () throws InvalidConfigurationException [inline], [virtual]
Returns
newly created GPGenotype
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.GPProblem.
Definition at line 48 of file KarubProblem.java.
References org.jgap.gp.CommandGene.BooleanClass, org.jgap.gp.GPProblem.getGPConfiguration(), org.jgap.gp.CommandGene.IntegerClass, and examples.gp.KarubProblem.vx.
static void examples.gp.KarubProblem.main (String[] args) throws Exception [inline], [static]
Definition at line 67 of file KarubProblem.java.
References examples.gp.KarubProblem.KarubProblem().
Member Data Documentation
Variable examples.gp.KarubProblem.vx [static]
Definition at line 41 of file KarubProblem.java.
Referenced by examples.gp.KarubProblem.create().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/KarubProblem.java