org.jgap.impl.job.SimpleJobConsumer Class Reference
Public Member Functions
void pushJobToGrid (IJob a_job)
void waitForAllJobs ()
EvolveResult[] getResults ()
void init () throws Exception
Static Public Member Functions
static void main (String[] args) throws Exception
Private Attributes
List m_jobs = new Vector()
List m_results = new Vector()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.6 $`
Detailed Description
Sample implementation of a service that generates jobs, takes them, executes them, receives results from finished jobs and merges the results in order to start a new round of evolution.
Author
Klaus Meffert
Since
3.2
Definition at line 25 of file SimpleJobConsumer.java.
Member Function Documentation
EvolveResult [] org.jgap.impl.job.SimpleJobConsumer.getResults () [inline]
Definition at line 63 of file SimpleJobConsumer.java.
References org.jgap.impl.job.SimpleJobConsumer.m_results.
void org.jgap.impl.job.SimpleJobConsumer.init () throws Exception [inline]
Definition at line 75 of file SimpleJobConsumer.java.
static void org.jgap.impl.job.SimpleJobConsumer.main (String[] args) throws Exception [inline], [static]
Definition at line 112 of file SimpleJobConsumer.java.
void org.jgap.impl.job.SimpleJobConsumer.pushJobToGrid (IJob a_job) [inline]
Definition at line 33 of file SimpleJobConsumer.java.
void org.jgap.impl.job.SimpleJobConsumer.waitForAllJobs () [inline]
Definition at line 40 of file SimpleJobConsumer.java.
References org.jgap.impl.job.IJob.isFinished(), and org.jgap.impl.job.SimpleJobConsumer.m_jobs.
Member Data Documentation
final String org.jgap.impl.job.SimpleJobConsumer.CVS_REVISION = `$Revision: 1.6 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file SimpleJobConsumer.java.
List org.jgap.impl.job.SimpleJobConsumer.m_jobs = new Vector() [private]
Definition at line 30 of file SimpleJobConsumer.java.
Referenced by org.jgap.impl.job.SimpleJobConsumer.waitForAllJobs().
List org.jgap.impl.job.SimpleJobConsumer.m_results = new Vector() [private]
Definition at line 31 of file SimpleJobConsumer.java.
Referenced by org.jgap.impl.job.SimpleJobConsumer.getResults().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/job/SimpleJobConsumer.java