examples.grid.mathProblemDistributed.SampleFitnessFunction Class Reference
Public Member Functions
SampleFitnessFunction ()
void init ()
double computeRawFitness (final IGPProgram ind)
Protected Member Functions
double evaluate (final IGPProgram a_subject)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.8 $`
static Logger log = Logger.getLogger(SampleFitnessFunction.class)
Detailed Description
Fitness function for our example.
Author
Klaus Meffert
Since
3.2
Definition at line 23 of file SampleFitnessFunction.java.
Constructor & Destructor Documentation
examples.grid.mathProblemDistributed.SampleFitnessFunction.SampleFitnessFunction () [inline]
Definition at line 36 of file SampleFitnessFunction.java.
References examples.grid.mathProblemDistributed.SampleFitnessFunction.init().
Member Function Documentation
double examples.grid.mathProblemDistributed.SampleFitnessFunction.computeRawFitness (final IGPProgram ind) [inline]
Definition at line 56 of file SampleFitnessFunction.java.
References examples.grid.mathProblemDistributed.SampleFitnessFunction.init().
Referenced by examples.grid.mathProblemDistributed.SampleFitnessFunction.evaluate().
double examples.grid.mathProblemDistributed.SampleFitnessFunction.evaluate (final IGPProgram a_subject) [inline], [protected]
Definition at line 52 of file SampleFitnessFunction.java.
References examples.grid.mathProblemDistributed.SampleFitnessFunction.computeRawFitness().
void examples.grid.mathProblemDistributed.SampleFitnessFunction.init () [inline]
Definition at line 40 of file SampleFitnessFunction.java.
Referenced by examples.grid.mathProblemDistributed.SampleFitnessFunction.computeRawFitness(), and examples.grid.mathProblemDistributed.SampleFitnessFunction.SampleFitnessFunction().
Member Data Documentation
final String examples.grid.mathProblemDistributed.SampleFitnessFunction.CVS_REVISION = `$Revision: 1.8 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file SampleFitnessFunction.java.
Logger examples.grid.mathProblemDistributed.SampleFitnessFunction.log = Logger.getLogger(SampleFitnessFunction.class) [static], [private]
Definition at line 28 of file SampleFitnessFunction.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/grid/mathProblemDistributed/SampleFitnessFunction.java