org.jgap.BaseGene Class Reference
Public Member Functions
BaseGene (Configuration a_configuration) throws InvalidConfigurationException
Object getAllele ()
int hashCode ()
void cleanup ()
String toString ()
int size ()
boolean equals (final Object a_other)
double getEnergy ()
void setEnergy (final double a_energy)
void setApplicationData (final Object a_newData)
Object getApplicationData ()
void setCompareApplicationData (final boolean a_doCompare)
boolean isCompareApplicationData ()
void setConstraintChecker (final IGeneConstraintChecker a_constraintChecker)
IGeneConstraintChecker getConstraintChecker ()
Gene newGene ()
Configuration getConfiguration ()
String getBusinessKey ()
String getUniqueID ()
void setUniqueIDTemplate (String a_templateID, int a_index)
String getUniqueIDTemplate (int a_index)
Static Public Attributes
static final String S_APPLICATION_DATA = `Application data`
static final double DELTA = 0.0000001
Protected Member Functions
abstract Object getInternalValue ()
int compareApplicationData (final Object a_appdata1, final Object a_appdata2)
abstract Gene newGeneInternal ()
String encode (String a_string)
String decode (String a_string)
Private Attributes
double m_energy
Object m_applicationData
boolean m_compareAppData
Configuration m_configuration
String m_uniqueID
Map< Integer, String > m_uniqueIDTemplates
IGeneConstraintChecker m_geneAlleleChecker
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.28 $`
Detailed Description
Abstract base class for all genes. Provides default implementations.
Author
Klaus Meffert
Since
2.2
Definition at line 23 of file BaseGene.java.
Constructor & Destructor Documentation
org.jgap.BaseGene.BaseGene (Configuration a_configuration) throws InvalidConfigurationException [inline]
Parameters
a_configuration the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 82 of file BaseGene.java.
References org.jgap.Configuration.getJGAPFactory(), org.jgap.Configuration.isUniqueKeysActive(), org.jgap.BaseGene.m_configuration, org.jgap.BaseGene.m_uniqueID, and org.jgap.BaseGene.m_uniqueIDTemplates.
Member Function Documentation
void org.jgap.BaseGene.cleanup () [inline]
Executed by the genetic engine when this Gene instance is no longer needed and should perform any necessary resource cleanup. If you need a special cleanup, override this method.
Author
Klaus Meffert
Since
1.0
Implements org.jgap.Gene.
Definition at line 138 of file BaseGene.java.
int org.jgap.BaseGene.compareApplicationData (final Object a_appdata1, final Object a_appdata2) [inline], [protected]
Definition at line 306 of file BaseGene.java.
References org.jgap.BaseGene.getConfiguration().
Referenced by org.jgap.impl.NumberGene.compareTo(), org.jgap.impl.BooleanGene.compareTo(), org.jgap.impl.StringGene.compareTo(), org.jgap.impl.FixedBinaryGene.compareTo(), org.jgap.impl.CompositeGene.compareTo(), and org.jgap.BaseGene.equals().
String org.jgap.BaseGene.decode (String a_string) [inline], [protected]
Definition at line 426 of file BaseGene.java.
Referenced by org.jgap.supergenes.AbstractSupergene.createValidator(), org.jgap.impl.StringGene.setValueFromPersistentRepresentation(), org.jgap.impl.CompositeGene.setValueFromPersistentRepresentation(), and org.jgap.supergenes.AbstractSupergene.setValueFromPersistentRepresentation().
String org.jgap.BaseGene.encode (String a_string) [inline], [protected]
Definition at line 422 of file BaseGene.java.
Referenced by org.jgap.impl.StringGene.getPersistentRepresentation(), org.jgap.impl.CompositeGene.getPersistentRepresentation(), and org.jgap.supergenes.AbstractSupergene.getPersistentRepresentation().
boolean org.jgap.BaseGene.equals (final Object a_other) [inline]
Compares this Gene with the given object and returns true if the other object is a Gene of the same type and has the same value (allele) as this Gene. Otherwise it returns false.
Parameters
a_other the object to compare to this Gene for equality
Returns
true if this Gene is equal to the given object, false otherwise
Author
Klaus Meffert
Since
1.1
Definition at line 193 of file BaseGene.java.
References org.jgap.BaseGene.compareApplicationData(), org.jgap.Gene.getApplicationData(), org.jgap.BaseGene.getApplicationData(), and org.jgap.BaseGene.isCompareApplicationData().
Referenced by org.jgap.impl.CompositeGene.addGene(), org.jgap.impl.SetGeneTest.testEquals_2(), org.jgap.impl.CompositeGeneTest.testEquals_5(), org.jgap.impl.CompositeGeneTest.testEquals_5_2(), org.jgap.impl.IntegerGeneTest.testEquals_8(), org.jgap.impl.IntegerGeneTest.testEquals_9(), org.jgap.impl.IntegerGeneTest.testEquals_9_2(), org.jgap.impl.IntegerGeneTest.testEquals_9_3(), org.jgap.impl.CompositeGeneTest.testNewGene_0(), org.jgap.impl.FixedBinaryGeneTest.testNewGene_0(), org.jgap.impl.MapGeneTest.testNewGene_2(), and org.jgap.impl.MapGeneTest.testNewGene_3().
Object org.jgap.BaseGene.getAllele () [inline]
Retrieves the allele value represented by this Gene.
Returns
the allele value of this Gene
Since
1.0
Implements org.jgap.Gene.
Definition at line 103 of file BaseGene.java.
References org.jgap.BaseGene.getInternalValue().
Referenced by org.jgap.impl.IntegerGene.applyMutation(), org.jgap.impl.MutipleIntegerGene.applyMutation(), org.jgap.impl.DoubleGene.doubleValue(), org.jgap.BaseGene.getBusinessKey(), org.jgap.impl.IntegerGene.intValue(), org.jgap.impl.DoubleGene.mapValueToWithinBounds(), org.jgap.impl.IntegerGene.mapValueToWithinBounds(), org.jgap.impl.MutipleIntegerGene.mapValueToWithinBounds(), org.jgap.impl.NumberGeneTest.NumberGeneImpl.mapValueToWithinBounds(), org.jgap.impl.MapGene.newGeneInternal(), org.jgap.impl.SetGeneTest.testGetAllele_0(), org.jgap.impl.MapGeneTest.testGetAllele_0(), org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange(), org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange2(), org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange3(), org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange4(), org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange5(), org.jgap.impl.IntegerGeneTest.testMapValueToWithinBoundsSupportsFullIntegerRange(), org.jgap.impl.InversionOperatorTest.testOperate_2(), org.jgap.impl.CompositeGeneTest.testPersistentPresentation_1(), org.jgap.impl.MapGeneTest.testPersistentRepresentation_2(), org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_2(), org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_3(), org.jgap.impl.CompositeGeneTest.testSetAllele_4(), org.jgap.impl.CompositeGeneTest.testSetAllele_5(), org.jgap.impl.StringGeneTest.testSetToRandomValue_0(), org.jgap.impl.StringGeneTest.testSetToRandomValue_3(), org.jgap.impl.StringGeneTest.testSetToRandomValue_4(), org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_1(), org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_1(), org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_2(), org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_2(), org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_3(), and org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_3().
Object org.jgap.BaseGene.getApplicationData () [inline]
Retrieves the application-specific data that is attached to this Gene. Attaching application-specific data may be useful for some applications when it comes time to distinguish a Gene from another. JGAP ignores this data functionally.
Returns
the application-specific data previously attached to this Gene, or null if there is no data attached
Author
Klaus Meffert
Since
2.4
Implements org.jgap.Gene.
Definition at line 278 of file BaseGene.java.
References org.jgap.BaseGene.m_applicationData.
Referenced by org.jgap.impl.NumberGene.compareTo(), org.jgap.impl.BooleanGene.compareTo(), org.jgap.impl.StringGene.compareTo(), org.jgap.impl.FixedBinaryGene.compareTo(), org.jgap.impl.CompositeGene.compareTo(), org.jgap.BaseGene.equals(), org.jgap.BaseGene.newGene(), and org.jgap.BaseGene.toString().
String org.jgap.BaseGene.getBusinessKey () [inline]
Returns
business key
Author
Klaus Meffert
Since
3.2
Implements org.jgap.IBusinessKey.
Definition at line 413 of file BaseGene.java.
References org.jgap.BaseGene.getAllele(), and org.jgap.Gene.PERSISTENT_FIELD_DELIMITER.
Configuration org.jgap.BaseGene.getConfiguration () [inline]
Returns
the configuration set
Author
Klaus Meffert
Since
3.0
Implements org.jgap.Gene.
Definition at line 409 of file BaseGene.java.
References org.jgap.BaseGene.m_configuration.
Referenced by org.jgap.impl.SetGene.applyMutation(), org.jgap.impl.MapGene.applyMutation(), org.jgap.supergenes.AbstractSupergene.applyMutation(), org.jgap.impl.StringGene.applyMutation(), org.jgap.impl.FixedBinaryGene.clone(), org.jgap.BaseGene.compareApplicationData(), org.jgap.impl.SetGene.compareTo(), org.jgap.impl.CompositeGene.createGene(), org.jgap.supergenes.AbstractSupergene.createGene(), org.jgap.supergenes.AbstractSupergene.createValidator(), org.jgap.impl.DoubleGene.mapValueToWithinBounds(), org.jgap.impl.IntegerGene.mapValueToWithinBounds(), org.jgap.impl.MutipleIntegerGene.mapValueToWithinBounds(), org.jgap.impl.SetGene.newGeneInternal(), org.jgap.impl.FixedBinaryGene.newGeneInternal(), org.jgap.impl.MapGene.newGeneInternal(), org.jgap.impl.DoubleGene.newGeneInternal(), org.jgap.impl.IntegerGene.newGeneInternal(), org.jgap.impl.MutipleIntegerGene.newGeneInternal(), org.jgap.impl.BooleanGene.newGeneInternal(), org.jgap.supergenes.AbstractSupergene.newGeneInternal(), org.jgap.impl.StringGene.newGeneInternal(), org.jgap.impl.CompositeGene.newGeneInternal(), org.jgap.impl.NumberGeneTest.NumberGeneImpl.newGeneInternal(), org.jgap.impl.FixedBinaryGene.substring(), and org.jgap.impl.SetGeneTest.testConstruct_0().
IGeneConstraintChecker org.jgap.BaseGene.getConstraintChecker () [inline]
Returns
IGeneConstraintChecker the constraint checker to be used whenever method setAllele(Object) is called.
Author
Klaus Meffert
Since
2.5 (moved from CompositeGene, where it was since 2.0)
Definition at line 370 of file BaseGene.java.
References org.jgap.BaseGene.m_geneAlleleChecker.
Referenced by org.jgap.BaseGene.newGene(), org.jgap.impl.StringGene.newGeneInternal(), org.jgap.impl.CompositeGene.newGeneInternal(), org.jgap.impl.FixedBinaryGene.setAllele(), org.jgap.impl.NumberGene.setAllele(), org.jgap.impl.StringGene.setAllele(), org.jgap.impl.CompositeGene.setAllele(), org.jgap.impl.DoubleGeneTest.testNewGene_0(), org.jgap.impl.NumberGeneTest.testSetConstraintChecker_0(), org.jgap.impl.FixedBinaryGeneTest.testSetConstraintChecker_0(), org.jgap.impl.DoubleGeneTest.testSetConstraintChecker_0(), org.jgap.impl.CompositeGeneTest.testSetConstraintChecker_0(), and org.jgap.impl.StringGeneTest.testSetConstraintChecker_0().
double org.jgap.BaseGene.getEnergy () [inline]
Returns
energy of the gene
Author
Klaus Meffert
Since
2.3
Implements org.jgap.Gene.
Definition at line 235 of file BaseGene.java.
References org.jgap.BaseGene.m_energy.
Referenced by org.jgap.BaseGene.newGene(), org.jgap.impl.NumberGeneTest.testSetEnergy_0(), org.jgap.impl.SetGeneTest.testSetEnergy_0(), org.jgap.impl.BooleanGeneTest.testSetEnergy_0(), org.jgap.impl.DoubleGeneTest.testSetEnergy_0(), org.jgap.impl.IntegerGeneTest.testSetEnergy_0(), org.jgap.impl.CompositeGeneTest.testSetEnergy_0(), org.jgap.impl.StringGeneTest.testSetEnergy_0(), org.jgap.impl.FixedBinaryGeneTest.testSetEnergy_0(), org.jgap.impl.NumberGeneTest.testSetEnergy_1(), org.jgap.impl.SetGeneTest.testSetEnergy_1(), org.jgap.impl.BooleanGeneTest.testSetEnergy_1(), org.jgap.impl.DoubleGeneTest.testSetEnergy_1(), org.jgap.impl.IntegerGeneTest.testSetEnergy_1(), org.jgap.impl.CompositeGeneTest.testSetEnergy_1(), org.jgap.impl.StringGeneTest.testSetEnergy_1(), and org.jgap.impl.FixedBinaryGeneTest.testSetEnergy_1().
abstract Object org.jgap.BaseGene.getInternalValue () [protected], [pure virtual]
Each Gene implementation holds its own m_value object keeping the allele value. In your Gene implementation, just return it with this method (see org.jgap.impl.BooleanGene for example)
Returns
the m_value object
Author
Klaus Meffert
Since
2.2
Implemented in org.jgap.impl.CompositeGene, org.jgap.supergenes.AbstractSupergene, org.jgap.impl.StringGene, org.jgap.impl.MapGene, org.jgap.impl.FixedBinaryGene, org.jgap.impl.BooleanGene, org.jgap.impl.SetGene, and org.jgap.impl.NumberGene.
Referenced by org.jgap.BaseGene.getAllele(), org.jgap.BaseGene.hashCode(), and org.jgap.BaseGene.toString().
String org.jgap.BaseGene.getUniqueID () [inline]
Returns
unique ID of the gene, which allows to distinct this instance from others, in the best case worldwide
Author
Klaus Meffert
Since
3.5
Implements org.jgap.IUniqueKey.
Definition at line 437 of file BaseGene.java.
References org.jgap.BaseGene.m_uniqueID.
String org.jgap.BaseGene.getUniqueIDTemplate (int a_index) [inline]
Parameters
a_index the index of the template to retrieve the key for
Returns
String
Author
Klaus Meffert
Since
3.5
Implements org.jgap.IUniqueKey.
Definition at line 465 of file BaseGene.java.
int org.jgap.BaseGene.hashCode () [inline]
Retrieves the hash code value for a Gene. Override if another hashCode() implementation is necessary or more appropriate than this default implementation.
Returns
this Gene's hash code
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 118 of file BaseGene.java.
References org.jgap.BaseGene.getInternalValue().
boolean org.jgap.BaseGene.isCompareApplicationData () [inline]
Implements org.jgap.Gene.
Definition at line 302 of file BaseGene.java.
References org.jgap.BaseGene.m_compareAppData.
Referenced by org.jgap.impl.NumberGene.compareTo(), org.jgap.impl.BooleanGene.compareTo(), org.jgap.impl.StringGene.compareTo(), org.jgap.impl.FixedBinaryGene.compareTo(), org.jgap.impl.CompositeGene.compareTo(), and org.jgap.BaseGene.equals().
Gene org.jgap.BaseGene.newGene () [inline]
Provides implementation-independent means for creating new Gene instances. The new instance that is created and returned should be setup with any implementation-dependent configuration that this Gene instance is setup with (aside from the actual value, of course). For example, if this Gene were setup with bounds on its value, then the Gene instance returned from this method should also be setup with those same bounds. This is important, as the JGAP core will invoke this method on each Gene in the sample Chromosome in order to create each new Gene in the same respective gene position for a new Chromosome.
Returns
a new Gene instance of the same type and with the same setup as this concrete Gene
Author
Neil Rostan
Klaus Meffert
Since
2.6 (since 1.0 in IntegerGene)
Todo
Todo clone app.data
Implements org.jgap.Gene.
Definition at line 392 of file BaseGene.java.
References org.jgap.BaseGene.getApplicationData(), org.jgap.BaseGene.getConstraintChecker(), org.jgap.BaseGene.getEnergy(), and org.jgap.BaseGene.newGeneInternal().
Referenced by org.jgap.supergenes.SupergenePersistentRepresentationTest.testNewGene_0(), org.jgap.impl.MapGeneTest.testNewGene_0(), org.jgap.impl.IntegerGeneTest.testNewGene_0(), org.jgap.impl.DoubleGeneTest.testNewGene_0(), org.jgap.impl.CompositeGeneTest.testNewGene_0(), org.jgap.impl.StringGeneTest.testNewGene_0(), org.jgap.impl.FixedBinaryGeneTest.testNewGene_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testNewGene_1(), org.jgap.impl.MapGeneTest.testNewGene_1(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testNewGene_2(), org.jgap.impl.MapGeneTest.testNewGene_2(), and org.jgap.impl.MapGeneTest.testNewGene_3().
abstract Gene org.jgap.BaseGene.newGeneInternal () [protected], [pure virtual]
Implemented in org.jgap.impl.NumberGeneTest.NumberGeneImpl, org.jgap.impl.CompositeGene, org.jgap.impl.StringGene, org.jgap.supergenes.AbstractSupergene, org.jgap.impl.BooleanGene, org.jgap.impl.MutipleIntegerGene, org.jgap.impl.IntegerGene, org.jgap.impl.DoubleGene, org.jgap.impl.MapGene, org.jgap.impl.FixedBinaryGene, and org.jgap.impl.SetGene.
Referenced by org.jgap.BaseGene.newGene().
void org.jgap.BaseGene.setApplicationData (final Object a_newData) [inline]
This sets the application-specific data that is attached to this Gene. Attaching application-specific data may be useful for some applications when it comes time to distinguish a Gene from another. JGAP ignores this data functionally.
Parameters
a_newData the new application-specific data to attach to this Gene
Author
Klaus Meffert
Since
2.4
Definition at line 262 of file BaseGene.java.
References org.jgap.BaseGene.m_applicationData.
void org.jgap.BaseGene.setCompareApplicationData (final boolean a_doCompare) [inline]
Should we also consider the application data when comparing? Default is `false` as `true` means a Gene is losing its identity when application data is set differently!
Parameters
a_doCompare true: consider application data in method compareTo
Author
Klaus Meffert
Since
2.4
Definition at line 292 of file BaseGene.java.
References org.jgap.BaseGene.m_compareAppData.
void org.jgap.BaseGene.setConstraintChecker (final IGeneConstraintChecker a_constraintChecker) [inline]
Sets the constraint checker to be used for this gene whenever method setAllele(Object) is called.
Parameters
a_constraintChecker the constraint checker to be set
Author
Klaus Meffert
Since
2.5 (moved from CompositeGene, where it was since 2.0)
Implements org.jgap.Gene.
Definition at line 358 of file BaseGene.java.
References org.jgap.BaseGene.m_geneAlleleChecker.
void org.jgap.BaseGene.setEnergy (final double a_energy) [inline]
Sets the energy of the gene
Parameters
a_energy the energy to set
Author
Klaus Meffert
Since
2.3
Definition at line 246 of file BaseGene.java.
References org.jgap.BaseGene.m_energy.
void org.jgap.BaseGene.setUniqueIDTemplate (String a_templateID, int a_index) [inline]
A template is a gene that is the logical predecessor of the current gene. A template can occur in mutation or crossing over. In the latter case can be at least two template genes. This is why in this setter method the parameter a_index exists.
Parameters
a_templateID the unique ID of the template
a_index the index of the template, e.g. in crossing over for the second candidate gene this is 2
Author
Klaus Meffert
Since
3.5
Implements org.jgap.IUniqueKey.
Definition at line 454 of file BaseGene.java.
int org.jgap.BaseGene.size () [inline]
Returns
the size of the gene, i.e the number of atomic elements. Always 1 for non-composed Gene types. Override for composed Gene types
Author
Neil Rotstan
Since
1.0
Implements org.jgap.Gene.
Definition at line 178 of file BaseGene.java.
String org.jgap.BaseGene.toString () [inline]
Retrieves a string representation of this Gene's value that may be useful for display purposes.
Returns
a string representation of this Gene's value
Author
Klaus Meffert
Since
1.0
Implements org.jgap.Gene.
Definition at line 152 of file BaseGene.java.
References org.jgap.BaseGene.getApplicationData(), org.jgap.BaseGene.getInternalValue(), and org.jgap.BaseGene.S_APPLICATION_DATA.
Referenced by org.jgap.impl.SetGene.getPersistentRepresentation(), org.jgap.impl.NumberGeneTest.NumberGeneImpl.getPersistentRepresentation(), org.jgap.impl.SetGeneTest.testToString_0(), and org.jgap.impl.SetGeneTest.testToString_1().
Member Data Documentation
final String org.jgap.BaseGene.CVS_REVISION = `$Revision: 1.28 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file BaseGene.java.
final double org.jgap.BaseGene.DELTA = 0.0000001 [static]
Delta, useful for comparing doubles and floats.
Definition at line 36 of file BaseGene.java.
Object org.jgap.BaseGene.m_applicationData [private]
Application-specific data that is attached to the Gene. This data may assist the application in labelling this Gene. JGAP ignores the data, aside from allowing it to be set and retrieved and considering it in clone() and compareTo().
Since
2.4
Definition at line 49 of file BaseGene.java.
Referenced by org.jgap.BaseGene.getApplicationData(), and org.jgap.BaseGene.setApplicationData().
boolean org.jgap.BaseGene.m_compareAppData [private]
Method compareTo(): Should we also consider the application data when comparing? Default is `false` as `true` means a Gene's losing its identity when application data is set differently!
Since
2.4
Definition at line 58 of file BaseGene.java.
Referenced by org.jgap.BaseGene.isCompareApplicationData(), and org.jgap.BaseGene.setCompareApplicationData().
Configuration org.jgap.BaseGene.m_configuration [private]
Definition at line 60 of file BaseGene.java.
Referenced by org.jgap.BaseGene.BaseGene(), and org.jgap.BaseGene.getConfiguration().
double org.jgap.BaseGene.m_energy [private]
Energy of a gene, see RFE 1102206
Definition at line 39 of file BaseGene.java.
Referenced by org.jgap.BaseGene.getEnergy(), and org.jgap.BaseGene.setEnergy().
IGeneConstraintChecker org.jgap.BaseGene.m_geneAlleleChecker [private]
Optional helper class for checking if a given allele value to be set for a given gene is valid. If not, the allele value may not be set for the gene or the gene type (e.g. IntegerGene) is not allowed in general!
Since
2.5 (moved from CompositeGene, where it was since 2.0)
Definition at line 348 of file BaseGene.java.
Referenced by org.jgap.BaseGene.getConstraintChecker(), and org.jgap.BaseGene.setConstraintChecker().
String org.jgap.BaseGene.m_uniqueID [private]
Unique ID of the gene that allows to distinct it from other genes. In the best case, this ID is unique worldwide.
Definition at line 66 of file BaseGene.java.
Referenced by org.jgap.BaseGene.BaseGene(), and org.jgap.BaseGene.getUniqueID().
Map<Integer,String> org.jgap.BaseGene.m_uniqueIDTemplates [private]
In case mutation, crossing over etc. happened, this sequence gives evidence about the parent(s) of the current gene.
Definition at line 72 of file BaseGene.java.
Referenced by org.jgap.BaseGene.BaseGene().
final String org.jgap.BaseGene.S_APPLICATION_DATA = `Application data` [static]
Constants for toString()
Definition at line 31 of file BaseGene.java.
Referenced by org.jgap.BaseGeneTest.testToString_0(), org.jgap.impl.NumberGeneTest.testToString_0(), org.jgap.BaseGeneTest.testToString_1(), org.jgap.BaseGeneTest.testToString_2(), and org.jgap.BaseGene.toString().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/BaseGene.java