org.jgap.gp.impl.GPProgramInfo Class Reference
Public Member Functions
GPProgramInfo (GPProgram a_prog, boolean a_found)
String getToStringNorm ()
double getFitnessValue ()
boolean isFound ()
void setFound (boolean a_found)
boolean equals (Object a_other)
int compareTo (Object a_other)
Private Attributes
double m_fitnessValue
String m_toStringNorm
boolean m_found
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Detailed Description
Holds information about a program. Used for caching GP programs during GP evolution.
Author
Klaus Meffert
Since
3.2
Definition at line 19 of file GPProgramInfo.java.
Constructor & Destructor Documentation
org.jgap.gp.impl.GPProgramInfo.GPProgramInfo (GPProgram a_prog, boolean a_found) [inline]
Definition at line 29 of file GPProgramInfo.java.
References org.jgap.gp.impl.GPProgramInfo.m_fitnessValue, org.jgap.gp.impl.GPProgramInfo.m_found, and org.jgap.gp.impl.GPProgramInfo.m_toStringNorm.
Referenced by org.jgap.gp.impl.GPProgramInfo.compareTo(), and org.jgap.gp.impl.GPProgramInfo.equals().
Member Function Documentation
int org.jgap.gp.impl.GPProgramInfo.compareTo (Object a_other) [inline]
Definition at line 62 of file GPProgramInfo.java.
References org.jgap.gp.impl.GPProgramInfo.GPProgramInfo(), and org.jgap.gp.impl.GPProgramInfo.m_toStringNorm.
boolean org.jgap.gp.impl.GPProgramInfo.equals (Object a_other) [inline]
Definition at line 51 of file GPProgramInfo.java.
References org.jgap.gp.impl.GPProgramInfo.GPProgramInfo(), and org.jgap.gp.impl.GPProgramInfo.m_toStringNorm.
double org.jgap.gp.impl.GPProgramInfo.getFitnessValue () [inline]
Definition at line 39 of file GPProgramInfo.java.
References org.jgap.gp.impl.GPProgramInfo.m_fitnessValue.
Referenced by org.jgap.gp.impl.GPProgram.growOrFull().
String org.jgap.gp.impl.GPProgramInfo.getToStringNorm () [inline]
Definition at line 35 of file GPProgramInfo.java.
References org.jgap.gp.impl.GPProgramInfo.m_toStringNorm.
boolean org.jgap.gp.impl.GPProgramInfo.isFound () [inline]
Definition at line 43 of file GPProgramInfo.java.
References org.jgap.gp.impl.GPProgramInfo.m_found.
void org.jgap.gp.impl.GPProgramInfo.setFound (boolean a_found) [inline]
Definition at line 47 of file GPProgramInfo.java.
References org.jgap.gp.impl.GPProgramInfo.m_found.
Member Data Documentation
final String org.jgap.gp.impl.GPProgramInfo.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 21 of file GPProgramInfo.java.
double org.jgap.gp.impl.GPProgramInfo.m_fitnessValue [private]
Definition at line 23 of file GPProgramInfo.java.
Referenced by org.jgap.gp.impl.GPProgramInfo.getFitnessValue(), and org.jgap.gp.impl.GPProgramInfo.GPProgramInfo().
boolean org.jgap.gp.impl.GPProgramInfo.m_found [private]
Definition at line 27 of file GPProgramInfo.java.
Referenced by org.jgap.gp.impl.GPProgramInfo.GPProgramInfo(), org.jgap.gp.impl.GPProgramInfo.isFound(), and org.jgap.gp.impl.GPProgramInfo.setFound().
String org.jgap.gp.impl.GPProgramInfo.m_toStringNorm [private]
Definition at line 25 of file GPProgramInfo.java.
Referenced by org.jgap.gp.impl.GPProgramInfo.compareTo(), org.jgap.gp.impl.GPProgramInfo.equals(), org.jgap.gp.impl.GPProgramInfo.getToStringNorm(), and org.jgap.gp.impl.GPProgramInfo.GPProgramInfo().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/impl/GPProgramInfo.java