examples.gp.MathProblem Class Reference
Classes
class FormulaFitnessFunction
Public Member Functions
MathProblem (GPConfiguration a_conf) throws InvalidConfigurationException
GPGenotype create () throws InvalidConfigurationException
Static Public Member Functions
static void main (String[] args) throws Exception
Static Public Attributes
static Variable vx
Static Protected Attributes
static Float[] x = new Float[20]
static float[] y = new float[20]
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.25 $`
Additional Inherited Members
Detailed Description
Example demonstrating Genetic Programming (GP) capabilities of JGAP. Also demonstrates usage of ADF's.
 The problem is to find a formula for a given truth table (X/Y-pairs).
The setup of the GP is done in method main and specifically in method create()
The problem solving process is started via gp.evolve(800) in the main method, with 800 the maximum number of evolutions to take place.
The evaluation of the evolved formula is done in fitness function FormulaFitnessFunction, which is implemented in this class, MathProblem
 For details, please see the mentioned methods and the fitness function.
Author
Klaus Meffert
Since
3.0
Definition at line 38 of file MathProblem.java.
Constructor & Destructor Documentation
examples.gp.MathProblem.MathProblem (GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Definition at line 49 of file MathProblem.java.
Referenced by examples.gp.MathProblem.main().
Member Function Documentation
GPGenotype examples.gp.MathProblem.create () throws InvalidConfigurationException [inline], [virtual]
This method is used for setting up the commands and terminals that can be used to solve the problem. In this example an ADF (an automatically defined function) is used for demonstration purpuses. Using an ADF is optional. If you want to use one, care about the places marked with `ADF-relevant:` below. If you do not want to use an ADF, please remove the below places (and reduce the outer size of the arrays `types`, `argTypes` and `nodeSets` to one). Please notice, that the variables types, argTypes and nodeSets correspond to each other: they have the same number of elements and the element at the i'th index of each variable corresponds to the i'th index of the other variables!
Returns
GPGenotype
Exceptions
InvalidConfigurationException
Implements org.jgap.gp.GPProblem.
Definition at line 70 of file MathProblem.java.
References org.jgap.gp.CommandGene.FloatClass, org.jgap.gp.GPProblem.getGPConfiguration(), examples.gp.MathProblem.vx, examples.gp.MathProblem.x, and examples.gp.MathProblem.y.
static void examples.gp.MathProblem.main (String[] args) throws Exception [inline], [static]
Starts the example.
Parameters
args ignored
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 154 of file MathProblem.java.
References examples.gp.MathProblem.MathProblem().
Member Data Documentation
final String examples.gp.MathProblem.CVS_REVISION = `$Revision: 1.25 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 41 of file MathProblem.java.
Variable examples.gp.MathProblem.vx [static]
Definition at line 43 of file MathProblem.java.
Referenced by examples.gp.MathProblem.create().
Float [] examples.gp.MathProblem.x = new Float[20] [static], [protected]
Definition at line 45 of file MathProblem.java.
Referenced by examples.gp.MathProblem.FormulaFitnessFunction.computeRawFitness(), and examples.gp.MathProblem.create().
float [] examples.gp.MathProblem.y = new float[20] [static], [protected]
Definition at line 47 of file MathProblem.java.
Referenced by examples.gp.MathProblem.FormulaFitnessFunction.computeRawFitness(), and examples.gp.MathProblem.create().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/MathProblem.java