org.jgap.supergenes.SupergenePersistentRepresentationTest Class Reference
Classes
class TestClass
Public Member Functions
void setUp ()
void testRepresentation () throws Exception
void testValidatorPers_0 ()
void testGetGenes_0 () throws Exception
void testSize_0 () throws Exception
void testIsValid_0 () throws Exception
void testReset_0 () throws Exception
void testPers_0 () throws Exception
void testToString_0 () throws Exception
void testToString_1 () throws Exception
void testToString_2 () throws Exception
void testCompareTo_0 () throws Exception
void testCompareTo_1 () throws Exception
void testCompareTo_2 () throws Exception
void testCompareTo_3 () throws Exception
void testEquals_0 () throws Exception
void testNewGene_0 () throws Exception
void testNewGene_1 () throws Exception
void testNewGene_2 () throws Exception
void testSetAllele_0 () throws Exception
void testSetAllele_1 () throws Exception
void testSetAllele_2 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.17 $`
Additional Inherited Members
Detailed Description
Test persistent representation of the AbstractSupergene.
Author
Meskauskas Audrius
Since
2.0
Definition at line 23 of file SupergenePersistentRepresentationTest.java.
Member Function Documentation
void org.jgap.supergenes.SupergenePersistentRepresentationTest.setUp () [inline]
Definition at line 34 of file SupergenePersistentRepresentationTest.java.
static Test org.jgap.supergenes.SupergenePersistentRepresentationTest.suite () [inline], [static]
Definition at line 28 of file SupergenePersistentRepresentationTest.java.
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testCompareTo_0 () throws Exception [inline]
Definition at line 183 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.supergenes.AbstractSupergene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testCompareTo_1 () throws Exception [inline]
Definition at line 191 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testCompareTo_2 () throws Exception [inline]
Definition at line 203 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.supergenes.AbstractSupergene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testCompareTo_3 () throws Exception [inline]
Definition at line 212 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.supergenes.AbstractSupergene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testEquals_0 () throws Exception [inline]
Definition at line 223 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.supergenes.AbstractSupergene.compareTo(), org.jgap.JGAPTestCase.conf, and org.jgap.supergenes.AbstractSupergene.equals().
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testGetGenes_0 () throws Exception [inline]
Definition at line 88 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.supergenes.AbstractSupergene.geneAt(), and org.jgap.supergenes.AbstractSupergene.getGenes().
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testIsValid_0 () throws Exception [inline]
Definition at line 107 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.supergenes.InstantiableSupergeneForTesting.isValid().
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testNewGene_0 () throws Exception [inline]
Definition at line 233 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.newGene().
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testNewGene_1 () throws Exception [inline]
Definition at line 242 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.newGene().
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testNewGene_2 () throws Exception [inline]
Definition at line 254 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.newGene().
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testPers_0 () throws Exception [inline]
Definition at line 131 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testRepresentation () throws Exception [inline]
Definition at line 39 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.supergenes.AbstractSupergene.equals().
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testReset_0 () throws Exception [inline]
Todo
Todo care that m_immutable is filled
Definition at line 122 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testSetAllele_0 () throws Exception [inline]
Definition at line 263 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.supergenes.AbstractSupergene.size().
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testSetAllele_1 () throws Exception [inline]
Definition at line 270 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testSetAllele_2 () throws Exception [inline]
Definition at line 286 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.supergenes.AbstractSupergene.geneAt().
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testSize_0 () throws Exception [inline]
Definition at line 98 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.supergenes.AbstractSupergene.size().
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testToString_0 () throws Exception [inline]
Definition at line 143 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testToString_1 () throws Exception [inline]
Definition at line 155 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testToString_2 () throws Exception [inline]
Definition at line 167 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.toString().
void org.jgap.supergenes.SupergenePersistentRepresentationTest.testValidatorPers_0 () [inline]
Definition at line 80 of file SupergenePersistentRepresentationTest.java.
References org.jgap.JGAPTestCase.conf, org.jgap.supergenes.Validator.getConfiguration(), and org.jgap.supergenes.Validator.getPersistent().
Member Data Documentation
final String org.jgap.supergenes.SupergenePersistentRepresentationTest.CVS_REVISION = `$Revision: 1.17 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file SupergenePersistentRepresentationTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/supergenes/SupergenePersistentRepresentationTest.java