examples.energy.CoinsEnergy Class Reference
Classes
class EnergyGeneConstraintChecker
Static Public Member Functions
static void makeChangeForAmount (int a_targetChangeAmount, double a_maxWeight) throws Exception
static void main (String[] args) throws Exception
Static Protected Member Functions
static int getValue (String[] args, int index)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.10 $`
static final int MAX_ALLOWED_EVOLUTIONS = 200
Detailed Description
THIS EXAMPLE IS NOT IMPLEMENTED FULLY! For general description, see examples.MinimizingMakeChange.
Additionally, each to coin an energy value is assigned (new feature since JGAP version 2.4). Energy is interpreted here as weight of a coin. You could think of a coins holder that wants a low total weight as possible and that is capable of only holding a given maximum weight.
Author
Klaus Meffert
Since
2.4
Definition at line 26 of file CoinsEnergy.java.
Member Function Documentation
static int examples.energy.CoinsEnergy.getValue (String[] args, int index) [inline], [static], [protected]
Definition at line 161 of file CoinsEnergy.java.
Referenced by examples.energy.CoinsEnergy.main().
static void examples.energy.CoinsEnergy.main (String[] args) throws Exception [inline], [static]
Main method. A single command-line argument is expected, which is the amount of change to create (in other words, 75 would be equal to 75 cents).
Parameters
args amount of change in cents to create
Exceptions
Exception
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 149 of file CoinsEnergy.java.
References examples.energy.CoinsEnergy.getValue(), and examples.energy.CoinsEnergy.makeChangeForAmount().
static void examples.energy.CoinsEnergy.makeChangeForAmount (int a_targetChangeAmount, double a_maxWeight) throws Exception [inline], [static]
Executes the genetic algorithm to determine the minimum number of coins necessary to make up the given target amount of change. The solution will then be written to System.out.
Parameters
a_targetChangeAmount the target amount of change for which this method is attempting to produce the minimum number of coins
a_maxWeight the maximum weight allowed in sum over all coins
Exceptions
Exception
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 49 of file CoinsEnergy.java.
References examples.energy.CoinsEnergyFitnessFunction.getTotalNumberOfCoins(), and examples.energy.CoinsEnergy.MAX_ALLOWED_EVOLUTIONS.
Referenced by examples.energy.CoinsEnergy.main().
Member Data Documentation
final String examples.energy.CoinsEnergy.CVS_REVISION = `$Revision: 1.10 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file CoinsEnergy.java.
final int examples.energy.CoinsEnergy.MAX_ALLOWED_EVOLUTIONS = 200 [static], [private]
The total number of times we'll let the population evolve.
Definition at line 33 of file CoinsEnergy.java.
Referenced by examples.energy.CoinsEnergy.makeChangeForAmount().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/energy/CoinsEnergy.java