org.jgap.impl.PoolTest Class Reference
Public Member Functions
void testConstruct_0 ()
void testClear_0 ()
void testAcquirePooledObject_0 ()
void testReleaseAllObjects_0 ()
void testReleaseAllObjects_1 ()
void testSize_0 ()
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.8 $`
Additional Inherited Members
Detailed Description
Tests the Pool class.
Since
1.1
Author
Klaus Meffert
Definition at line 24 of file PoolTest.java.
Member Function Documentation
static Test org.jgap.impl.PoolTest.suite () [inline], [static]
Definition at line 29 of file PoolTest.java.
void org.jgap.impl.PoolTest.testAcquirePooledObject_0 () [inline]
Author
Klaus Meffert
Definition at line 60 of file PoolTest.java.
References org.jgap.impl.Pool.acquirePooledObject(), org.jgap.JGAPTestCase.assertEquals(), and org.jgap.impl.Pool.size().
void org.jgap.impl.PoolTest.testClear_0 () [inline]
Author
Klaus Meffert
Definition at line 44 of file PoolTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.impl.Pool.size().
void org.jgap.impl.PoolTest.testConstruct_0 () [inline]
Author
Klaus Meffert
Definition at line 37 of file PoolTest.java.
void org.jgap.impl.PoolTest.testReleaseAllObjects_0 () [inline]
Author
Klaus Meffert
Definition at line 74 of file PoolTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.impl.Pool.size().
void org.jgap.impl.PoolTest.testReleaseAllObjects_1 () [inline]
Author
Klaus Meffert
Definition at line 83 of file PoolTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.impl.Pool.size().
void org.jgap.impl.PoolTest.testSize_0 () [inline]
Author
Klaus Meffert
Definition at line 98 of file PoolTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.impl.Pool.size().
Member Data Documentation
final String org.jgap.impl.PoolTest.CVS_REVISION = `$Revision: 1.8 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file PoolTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/PoolTest.java