org.jgap.gp.function.Mean Class Reference
Public Member Functions
Mean (final GPConfiguration a_conf, Class a_returnType, int a_arityInitial, int a_arityMin, int a_arityMax) throws InvalidConfigurationException
double execute_double (ProgramChromosome c, int n, Object[] args)
String toString ()
Object clone ()
Additional Inherited Members
Detailed Description
This class calculates the Mean of N numbers.
Author
Luis Garcia
Since
3.5
Definition at line 26 of file Mean.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Mean.Mean (final GPConfiguration a_conf, Class a_returnType, int a_arityInitial, int a_arityMin, int a_arityMax) throws InvalidConfigurationException [inline]
Definition at line 28 of file Mean.java.
Member Function Documentation
Object org.jgap.gp.function.Mean.clone () [inline]
Returns
clone of the current object instance
Implements org.jgap.util.ICloneable.
Definition at line 59 of file Mean.java.
References org.jgap.gp.CommandGene.getArity(), org.jgap.gp.CommandGene.getArityMax(), org.jgap.gp.CommandGene.getArityMin(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.CommandGene.getReturnType().
double org.jgap.gp.function.Mean.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 36 of file Mean.java.
References org.jgap.gp.CommandGene.size().
String org.jgap.gp.function.Mean.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 46 of file Mean.java.
References org.jgap.gp.CommandGene.size().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Mean.java