org.jgap.gp.function.Pow Class Reference
Classes
interface Compatible
Public Member Functions
Pow (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException
String toString ()
String getName ()
int execute_int (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.8 $`
Additional Inherited Members
Detailed Description
The power operation.
Author
Klaus Meffert
Since
3.0
Definition at line 23 of file Pow.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Pow.Pow (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 28 of file Pow.java.
Referenced by org.jgap.gp.function.Pow.clone().
Member Function Documentation
Object org.jgap.gp.function.Pow.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 87 of file Pow.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.function.Pow.Pow().
double org.jgap.gp.function.Pow.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 63 of file Pow.java.
float org.jgap.gp.function.Pow.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 55 of file Pow.java.
int org.jgap.gp.function.Pow.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 47 of file Pow.java.
Object org.jgap.gp.function.Pow.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 71 of file Pow.java.
String org.jgap.gp.function.Pow.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 43 of file Pow.java.
String org.jgap.gp.function.Pow.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 33 of file Pow.java.
Member Data Documentation
final String org.jgap.gp.function.Pow.CVS_REVISION = `$Revision: 1.8 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file Pow.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Pow.java