examples.equalDistribution.MainClass Class Reference
Public Member Functions
MainClass () throws Exception
void doEvolution (Genotype a_genotype)
void printSolution (IChromosome a_solution)
void makeVents ()
Static Public Member Functions
static void main (String[] args)
Protected Member Functions
Genotype configureJGAP () throws Exception
Private Attributes
Vent[] m_vents
int m_numEvolutions
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Detailed Description
Given 64 vents with different weights. Try to make 8 group with each groups having (nearly) the same weight as the other groups.
Here, each vent has a similar weight with a small deviation. But the deviation could also be significant (then, good solutions are harder to find).
The proposed way of solving this problem is quite easy in its structure. There is potential for optimzations!
Author
Klaus Meffert
Since
3.2
Definition at line 28 of file MainClass.java.
Constructor & Destructor Documentation
examples.equalDistribution.MainClass.MainClass () throws Exception [inline]
Constructor.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 47 of file MainClass.java.
References examples.equalDistribution.MainClass.configureJGAP(), examples.equalDistribution.MainClass.doEvolution(), and examples.equalDistribution.MainClass.makeVents().
Referenced by examples.equalDistribution.MainClass.main().
Member Function Documentation
Genotype examples.equalDistribution.MainClass.configureJGAP () throws Exception [inline], [protected]
Sets up the configuration for the problem.
Returns
configured genotype
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 64 of file MainClass.java.
References examples.equalDistribution.MainClass.m_numEvolutions, and examples.equalDistribution.MainClass.m_vents.
Referenced by examples.equalDistribution.MainClass.MainClass().
void examples.equalDistribution.MainClass.doEvolution (Genotype a_genotype) [inline]
Does the evolution until finished.
Parameters
a_genotype the genotype to evolve
Author
Klaus Meffert
Since
3.2
Definition at line 124 of file MainClass.java.
References examples.equalDistribution.MainClass.m_numEvolutions, and examples.equalDistribution.MainClass.printSolution().
Referenced by examples.equalDistribution.MainClass.MainClass().
static void examples.equalDistribution.MainClass.main (String[] args) [inline], [static]
Start the example
Parameters
args ignored
Author
Klaus Meffert
Since
3.2
Definition at line 199 of file MainClass.java.
References examples.equalDistribution.MainClass.MainClass().
void examples.equalDistribution.MainClass.makeVents () [inline]
Create vents with different weights.
Author
Klaus Meffert
Since
3.2
Definition at line 182 of file MainClass.java.
References examples.equalDistribution.MainClass.m_vents.
Referenced by examples.equalDistribution.MainClass.MainClass().
void examples.equalDistribution.MainClass.printSolution (IChromosome a_solution) [inline]
Parameters
a_solution a solution to print to the console
Author
Klaus Meffert
Since
3.2
Definition at line 154 of file MainClass.java.
References examples.equalDistribution.MainClass.m_vents.
Referenced by examples.equalDistribution.MainClass.doEvolution().
Member Data Documentation
final String examples.equalDistribution.MainClass.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 30 of file MainClass.java.
int examples.equalDistribution.MainClass.m_numEvolutions [private]
Definition at line 37 of file MainClass.java.
Referenced by examples.equalDistribution.MainClass.configureJGAP(), and examples.equalDistribution.MainClass.doEvolution().
Vent [] examples.equalDistribution.MainClass.m_vents [private]
Holds the available vents, each with a specific weight
Definition at line 35 of file MainClass.java.
Referenced by examples.equalDistribution.MainClass.configureJGAP(), examples.equalDistribution.MainClass.makeVents(), and examples.equalDistribution.MainClass.printSolution().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/equalDistribution/MainClass.java