org.jgap.impl.TournamentSelector Class Reference
Classes
class FitnessValueComparator
class TournamentSelectorConfigurable
Public Member Functions
TournamentSelector () throws InvalidConfigurationException
TournamentSelector (final Configuration a_config, final int a_tournament_size, final double a_probability) throws InvalidConfigurationException
void setTournamentSize (final int a_tournament_size)
int getTournamentSize ()
double getProbability ()
void setProbability (final double a_probability)
void selectChromosomes (final int a_howManyToSelect, Population a_to_pop)
boolean returnsUniqueChromosomes ()
void empty ()
Protected Member Functions
void add (final IChromosome a_chromosomeToAdd)
Private Member Functions
void init ()
Private Attributes
TournamentSelectorConfigurable m_config = new TournamentSelectorConfigurable()
List m_chromosomes
FitnessValueComparator m_fitnessValueComparator
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.24 $`
Additional Inherited Members
Detailed Description
Implementation of a NaturalSelector that plays tournaments to determine the chromosomes to be taken to the next generation.
The tournament size can be adjusted as well as the probability for selecting an individual.
Author
Klaus Meffert
Since
2.0
Definition at line 26 of file TournamentSelector.java.
Constructor & Destructor Documentation
org.jgap.impl.TournamentSelector.TournamentSelector () throws InvalidConfigurationException [inline]
Default constructor.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Siddhartha Azad
Klaus Meffert
Definition at line 51 of file TournamentSelector.java.
References org.jgap.Genotype.getStaticConfiguration(), and org.jgap.impl.TournamentSelector.init().
org.jgap.impl.TournamentSelector.TournamentSelector (final Configuration a_config, final int a_tournament_size, final double a_probability) throws InvalidConfigurationException [inline]
Parameters
a_config the configuration to use
a_tournament_size the size of each tournament to play
a_probability probability for selecting the best individuals
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.0
Definition at line 72 of file TournamentSelector.java.
References org.jgap.impl.TournamentSelector.init().
Member Function Documentation
void org.jgap.impl.TournamentSelector.add (final IChromosome a_chromosomeToAdd) [inline], [protected], [virtual]
Parameters
a_chromosomeToAdd the chromosome to add
Author
Klaus Meffert
Since
2.0
Implements org.jgap.NaturalSelectorExt.
Definition at line 182 of file TournamentSelector.java.
void org.jgap.impl.TournamentSelector.empty () [inline]
Empty out the working pool of Chromosomes. This will be invoked after each evolution cycle so that the natural selector can be reused for the next one.
Author
Neil Rotstan
Since
1.0
Implements org.jgap.INaturalSelector.
Definition at line 171 of file TournamentSelector.java.
double org.jgap.impl.TournamentSelector.getProbability () [inline]
Definition at line 100 of file TournamentSelector.java.
Referenced by org.jgap.impl.TournamentSelectorTest.testSetProbability_0().
int org.jgap.impl.TournamentSelector.getTournamentSize () [inline]
Definition at line 96 of file TournamentSelector.java.
Referenced by org.jgap.impl.TournamentSelectorTest.testSetTournametSize_0().
void org.jgap.impl.TournamentSelector.init () [inline], [private]
Definition at line 57 of file TournamentSelector.java.
References org.jgap.impl.TournamentSelector.m_chromosomes, and org.jgap.impl.TournamentSelector.m_fitnessValueComparator.
Referenced by org.jgap.impl.TournamentSelector.TournamentSelector().
boolean org.jgap.impl.TournamentSelector.returnsUniqueChromosomes () [inline]
Returns
false as we allow to return the same chromosome multiple times
Author
Klaus Meffert
Since
2.0
Implements org.jgap.INaturalSelector.
Definition at line 167 of file TournamentSelector.java.
Referenced by org.jgap.impl.TournamentSelectorTest.testReturnsUniqueChromosomes_0().
void org.jgap.impl.TournamentSelector.selectChromosomes (final int a_howManyToSelect, Population a_to_pop) [inline]
Select a given number of Chromosomes from the pool that will move on to the next generation population. This selection will be guided by the fitness values. The chromosomes with the best fitness value win.
Parameters
a_howManyToSelect int
a_to_pop the population the Chromosomes will be added to
Author
Klaus Meffert
Since
2.0
Definition at line 123 of file TournamentSelector.java.
References org.jgap.NaturalSelector.getConfiguration(), org.jgap.impl.TournamentSelector.m_config, and org.jgap.impl.TournamentSelector.m_fitnessValueComparator.
void org.jgap.impl.TournamentSelector.setProbability (final double a_probability) [inline]
Definition at line 104 of file TournamentSelector.java.
void org.jgap.impl.TournamentSelector.setTournamentSize (final int a_tournament_size) [inline]
Definition at line 89 of file TournamentSelector.java.
Member Data Documentation
final String org.jgap.impl.TournamentSelector.CVS_REVISION = `$Revision: 1.24 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 29 of file TournamentSelector.java.
List org.jgap.impl.TournamentSelector.m_chromosomes [private]
Definition at line 34 of file TournamentSelector.java.
Referenced by org.jgap.impl.TournamentSelector.init().
TournamentSelectorConfigurable org.jgap.impl.TournamentSelector.m_config = new TournamentSelectorConfigurable() [private]
Definition at line 32 of file TournamentSelector.java.
Referenced by org.jgap.impl.TournamentSelector.selectChromosomes().
FitnessValueComparator org.jgap.impl.TournamentSelector.m_fitnessValueComparator [private]
Comparator that is only concerned about fitness values
Definition at line 39 of file TournamentSelector.java.
Referenced by org.jgap.impl.TournamentSelector.init(), and org.jgap.impl.TournamentSelector.selectChromosomes().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/TournamentSelector.java