org.jgap.data.DataElementsDocumentTest Class Reference
Public Member Functions
void testConstruct_0 () throws Exception
void testNewDocument_0 () throws Exception
void testAppendChild_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Additional Inherited Members
Detailed Description
Tests for DataElementsDocument class
Author
Klaus Meffert
Since
2.6
Definition at line 22 of file DataElementsDocumentTest.java.
Member Function Documentation
static Test org.jgap.data.DataElementsDocumentTest.suite () [inline], [static]
Definition at line 27 of file DataElementsDocumentTest.java.
void org.jgap.data.DataElementsDocumentTest.testAppendChild_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 60 of file DataElementsDocumentTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.data.DataElementsDocument.getTree().
void org.jgap.data.DataElementsDocumentTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 37 of file DataElementsDocumentTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.data.DataElementsDocument.getTree().
void org.jgap.data.DataElementsDocumentTest.testNewDocument_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 49 of file DataElementsDocumentTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.data.DataElementsDocument.newDocument().
Member Data Documentation
final String org.jgap.data.DataElementsDocumentTest.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file DataElementsDocumentTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/data/DataElementsDocumentTest.java