org.jgap.impl.RangedSwappingMutationOperator Class Reference
Public Member Functions
RangedSwappingMutationOperator () throws InvalidConfigurationException
RangedSwappingMutationOperator (final Configuration a_config, int a_range) throws InvalidConfigurationException
RangedSwappingMutationOperator (final Configuration a_config, final IUniversalRateCalculator a_mutationRateCalculator, int a_range) throws InvalidConfigurationException
RangedSwappingMutationOperator (final Configuration a_config, final int a_desiredMutationRate, int a_range) throws InvalidConfigurationException
void operate (final Population a_population, List a_candidateChromosomes)
void setStartOffset (final int a_offset)
int getStartOffset ()
void setRange (final int a_range)
int getRange ()
Protected Member Functions
IChromosome operate (final IChromosome a_chrom, final int a_rate, final RandomGenerator a_generator)
Gene[] operate (final RandomGenerator a_generator, final int a_target_gene, final Gene[] a_genes)
Private Attributes
int m_startOffset = 0
int m_range = 0
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
Swaps the genes instead of mutating them. This kind of operator is required by Traveling Salesman Problem. Copied and modified from SwappingMutationOperator. This implementation takes a range as parameter and uses it to only swap genes that are -/+ range indexes away from the gene being mutated. This basically allows for local searches before propagating through the entire problem space. Seems to work much better/quicker than a random swapping across the entire chromosome.
Author
Audrius Meskauskas
Neil Rotstan
Klaus Meffert
Florian Hafner
Since
3.3.2
Definition at line 30 of file RangedSwappingMutationOperator.java.
Constructor & Destructor Documentation
org.jgap.impl.RangedSwappingMutationOperator.RangedSwappingMutationOperator () throws InvalidConfigurationException [inline]
Constructs a new instance of this operator.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.3.2
Definition at line 49 of file RangedSwappingMutationOperator.java.
References org.jgap.impl.RangedSwappingMutationOperator.m_range.
org.jgap.impl.RangedSwappingMutationOperator.RangedSwappingMutationOperator (final Configuration a_config, int a_range) throws InvalidConfigurationException [inline]
Parameters
a_config the configuration to use
a_range the maximum range to use for considering genes to be swapped. The range is computed as the difference of the indices between two genes
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.3.2
Definition at line 65 of file RangedSwappingMutationOperator.java.
References org.jgap.impl.RangedSwappingMutationOperator.m_range.
org.jgap.impl.RangedSwappingMutationOperator.RangedSwappingMutationOperator (final Configuration a_config, final IUniversalRateCalculator a_mutationRateCalculator, int a_range) throws InvalidConfigurationException [inline]
Constructs a new instance of this operator with a specified mutation rate calculator, which results in dynamic mutation being turned on.
Parameters
a_config the configuration to use
a_mutationRateCalculator calculator for dynamic mutation rate computation
a_range the maximum range to use for considering genes to be swapped. The range is computed as the difference of the indices between two genes
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.3.2
Definition at line 89 of file RangedSwappingMutationOperator.java.
References org.jgap.impl.RangedSwappingMutationOperator.m_range.
org.jgap.impl.RangedSwappingMutationOperator.RangedSwappingMutationOperator (final Configuration a_config, final int a_desiredMutationRate, int a_range) throws InvalidConfigurationException [inline]
Constructs a new instance of this MutationOperator with the given mutation rate.
Parameters
a_config the configuration to use
a_desiredMutationRate desired rate of mutation, expressed as the denominator of the 1 / X fraction. For example, 1000 would result in 1/1000 genes being mutated on average. A mutation rate of zero disables mutation entirely
a_range the maximum range to use for considering genes to be swapped. The range is computed as the difference of the indices between two genes
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.3.2
Definition at line 114 of file RangedSwappingMutationOperator.java.
References org.jgap.impl.RangedSwappingMutationOperator.m_range.
Member Function Documentation
int org.jgap.impl.RangedSwappingMutationOperator.getRange () [inline]
Gets the mutation range.
Returns
the start offset
Author
Audrius Meskauskas
Since
3.3.2
Definition at line 305 of file RangedSwappingMutationOperator.java.
References org.jgap.impl.RangedSwappingMutationOperator.m_range.
int org.jgap.impl.RangedSwappingMutationOperator.getStartOffset () [inline]
Gets a number of genes at the start of chromosome, that are excluded from the swapping. In the Salesman task, the first city in the list should (where the salesman leaves from) probably should not change as it is part of the list. The default value is 1.
Returns
the start offset
Author
Audrius Meskauskas
Since
3.3.2
Definition at line 280 of file RangedSwappingMutationOperator.java.
References org.jgap.impl.RangedSwappingMutationOperator.m_startOffset.
void org.jgap.impl.RangedSwappingMutationOperator.operate (final Population a_population, List a_candidateChromosomes) [inline]
Parameters
a_population the population of chromosomes from the current evolution prior to exposure to any genetic operators. Chromosomes in this array should not be modified. Please, notice, that the call in Genotype.evolve() to the implementations of GeneticOperator overgoes this due to performance issues
a_candidateChromosomes the pool of chromosomes that have been selected for the next evolved population
Author
Audrius Meskauskas
Klaus Meffert
Since
3.3.2
Definition at line 134 of file RangedSwappingMutationOperator.java.
References org.jgap.BaseGeneticOperator.getConfiguration(), org.jgap.impl.MutationOperator.getMutationRate(), org.jgap.impl.MutationOperator.getMutationRateCalc(), and org.jgap.impl.MutationOperator.m_mutationRateCalc.
Referenced by org.jgap.impl.RangedSwappingMutationOperator.operate().
IChromosome org.jgap.impl.RangedSwappingMutationOperator.operate (final IChromosome a_chrom, final int a_rate, final RandomGenerator a_generator) [inline], [protected]
Operate on the given chromosome with the given mutation rate.
Parameters
a_chrom chromosome to operate
a_rate mutation rate
a_generator random generator to use (must not be null)
Returns
mutated chromosome of null if no mutation has occured.
Author
Audrius Meskauskas
Florian Hafner
Since
3.3.2
Definition at line 183 of file RangedSwappingMutationOperator.java.
References org.jgap.util.ICloneable.clone(), org.jgap.BaseGeneticOperator.m_monitorActive, org.jgap.impl.RangedSwappingMutationOperator.m_range, org.jgap.impl.RangedSwappingMutationOperator.m_startOffset, org.jgap.RandomGenerator.nextInt(), and org.jgap.impl.RangedSwappingMutationOperator.operate().
Gene [] org.jgap.impl.RangedSwappingMutationOperator.operate (final RandomGenerator a_generator, final int a_target_gene, final Gene[] a_genes) [inline], [protected]
Operate on the given array of genes. This method is only called when it is already clear that the mutation must occur under the given mutation rate.
Parameters
a_generator a random number generator that may be needed to perform a mutation
a_target_gene an index of gene in the chromosome that will mutate
a_genes the array of all genes in the chromosome
Returns
the mutated gene array
Author
Florian Hafner
Since
3.3.2
Definition at line 231 of file RangedSwappingMutationOperator.java.
References org.jgap.BaseGeneticOperator.m_monitorActive, and org.jgap.impl.RangedSwappingMutationOperator.m_range.
void org.jgap.impl.RangedSwappingMutationOperator.setRange (final int a_range) [inline]
Sets the mutation range. This specifies the genes before and after which a subject gene is allowed to swap with
Parameters
a_range the offset to set
Author
Audrius Meskauskas
Since
3.3.2
Definition at line 293 of file RangedSwappingMutationOperator.java.
References org.jgap.impl.RangedSwappingMutationOperator.m_range.
void org.jgap.impl.RangedSwappingMutationOperator.setStartOffset (final int a_offset) [inline]
Sets a number of genes at the start of chromosome, that are excluded from the swapping. In the Salesman task, the first city in the list should (where the salesman leaves from) probably should not change as it is part of the list. The default value is 1.
Parameters
a_offset the offset to set
Author
Audrius Meskauskas
Since
3.3.2
Definition at line 265 of file RangedSwappingMutationOperator.java.
References org.jgap.impl.RangedSwappingMutationOperator.m_startOffset.
Member Data Documentation
final String org.jgap.impl.RangedSwappingMutationOperator.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 33 of file RangedSwappingMutationOperator.java.
int org.jgap.impl.RangedSwappingMutationOperator.m_range = 0 [private]
Definition at line 37 of file RangedSwappingMutationOperator.java.
Referenced by org.jgap.impl.RangedSwappingMutationOperator.getRange(), org.jgap.impl.RangedSwappingMutationOperator.operate(), org.jgap.impl.RangedSwappingMutationOperator.RangedSwappingMutationOperator(), and org.jgap.impl.RangedSwappingMutationOperator.setRange().
int org.jgap.impl.RangedSwappingMutationOperator.m_startOffset = 0 [private]
Definition at line 35 of file RangedSwappingMutationOperator.java.
Referenced by org.jgap.impl.RangedSwappingMutationOperator.getStartOffset(), org.jgap.impl.RangedSwappingMutationOperator.operate(), and org.jgap.impl.RangedSwappingMutationOperator.setStartOffset().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/RangedSwappingMutationOperator.java