org.jgap.Genotype Class Reference
Public Member Functions
Genotype (Configuration a_configuration, IChromosome[] a_initialChromosomes) throws InvalidConfigurationException
Genotype (Configuration a_configuration, Population a_population) throws InvalidConfigurationException
Genotype (Configuration a_configuration) throws InvalidConfigurationException
synchronized IChromosome[] getChromosomes ()
Population getPopulation ()
synchronized IChromosome getFittestChromosome ()
synchronized IChromosome getFittestChromosome (int a_startIndex, int a_endIndex)
synchronized List getFittestChromosomes (int a_numberOfChromosomes)
synchronized void evolve ()
void evolve (int a_numberOfEvolutions)
List< String > evolve (IEvolutionMonitor a_monitor)
String toString ()
void fillPopulation (final int a_num) throws InvalidConfigurationException
boolean equals (Object a_other)
void applyGeneticOperators ()
Configuration getConfiguration ()
int hashCode ()
void run ()
List< IEvolveJob > getEvolves (IPopulationSplitter a_splitter) throws Exception
void mergeResults (IPopulationMerger a_merger, EvolveResult[] a_results) throws Exception
void setUseMonitor (boolean a_useMonitor)
void setMonitor (IEvolutionMonitor a_monitor)
Static Public Member Functions
static Genotype randomInitialGenotype (Configuration a_configuration) throws InvalidConfigurationException
static Configuration getStaticConfiguration ()
static void setStaticConfiguration (Configuration a_configuration)
Protected Member Functions
void applyNaturalSelectors (boolean a_processBeforeGeneticOperators)
void setPopulation (Population a_pop)
void applyGeneticOperator (GeneticOperator a_operator, Population a_population, List a_chromosomes)
void keepPopSizeConstant (Population a_pop, int a_maxSize)
Private Attributes
Configuration m_activeConfiguration
Population m_population
boolean m_useMonitor
IEvolutionMonitor m_monitor
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.109 $`
static transient Configuration m_staticConfiguration
Detailed Description
Genotypes are fixed-length populations of chromosomes. As an instance of a Genotype is evolved, all of its Chromosomes are also evolved. A Genotype may be constructed normally via constructor, or the static randomInitialGenotype() method can be used to generate a Genotype with a randomized Chromosome population.
Please note that among all created Genotype instances there may only be one configuration, used by all Genotype instances.
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 33 of file Genotype.java.
Constructor & Destructor Documentation
org.jgap.Genotype.Genotype (Configuration a_configuration, IChromosome[] a_initialChromosomes) throws InvalidConfigurationException [inline]
Constructs a new Genotype instance with the given array of Chromosomes and the given active Configuration instance. Note that the Configuration object must be in a valid state when this method is invoked, or a InvalidConfigurationException will be thrown.
Parameters
a_configuration the Configuration object to use
a_initialChromosomes the Chromosome population to be managed by this Genotype instance
Exceptions
InvalidConfigurationException if the given Configuration object is in an invalid state
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Deprecated
Deprecated use Genotype(Configuration, Population) instead
Definition at line 76 of file Genotype.java.
Referenced by org.jgap.Genotype.equals(), and org.jgap.Genotype.randomInitialGenotype().
org.jgap.Genotype.Genotype (Configuration a_configuration, Population a_population) throws InvalidConfigurationException [inline]
Constructs a new Genotype instance with the given array of Chromosomes and the given active Configuration instance. Note that the Configuration object must be in a valid state when this method is invoked, or a InvalidconfigurationException will be thrown.
Parameters
a_configuration the Configuration object to use
a_population the Chromosome population to be managed by this Genotype instance
Exceptions
InvalidConfigurationException
Author
Neil Rotstan
Klaus Meffert
Since
2.0
Definition at line 98 of file Genotype.java.
References org.jgap.Genotype.m_activeConfiguration, and org.jgap.Genotype.m_population.
org.jgap.Genotype.Genotype (Configuration a_configuration) throws InvalidConfigurationException [inline]
Don't use this constructor, it's only for internal use.
Parameters
a_configuration not used here!
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 136 of file Genotype.java.
Member Function Documentation
void org.jgap.Genotype.applyGeneticOperator (GeneticOperator a_operator, Population a_population, List a_chromosomes) [inline], [protected]
Overwritable method that calls a GeneticOperator to operate on a given population and asks him to store the result in the list of chromosomes. Override this method if you want to ensure that a_chromosomes is not part of a_population resp. if you want to use a different list.
Parameters
a_operator the GeneticOperator to call
a_population the population to use
a_chromosomes the list of Chromosome objects to return
Author
Klaus Meffert
Since
2.4
Definition at line 587 of file Genotype.java.
Referenced by org.jgap.Genotype.applyGeneticOperators().
void org.jgap.Genotype.applyGeneticOperators () [inline]
Applies all GeneticOperators registered with the Configuration.
Author
Klaus Meffert
Since
3.0
Definition at line 501 of file Genotype.java.
References org.jgap.Genotype.applyGeneticOperator(), org.jgap.Genotype.getChromosomes(), and org.jgap.Genotype.getPopulation().
void org.jgap.Genotype.applyNaturalSelectors (boolean a_processBeforeGeneticOperators) [inline], [protected]
Applies all NaturalSelectors registered with the Configuration.
Parameters
a_processBeforeGeneticOperators true apply NaturalSelectors applicable before GeneticOperators, false: apply the ones applicable after GeneticOperators
Author
Klaus Meffert
Since
2.0
Todo
Todo optionally use working pool
Definition at line 442 of file Genotype.java.
References org.jgap.Genotype.getConfiguration(), org.jgap.Genotype.getPopulation(), org.jgap.Genotype.m_activeConfiguration, and org.jgap.Genotype.setPopulation().
boolean org.jgap.Genotype.equals (Object a_other) [inline]
Compares this Genotype against the specified object. The result is true if the argument is an instance of the Genotype class, has exactly the same number of chromosomes as the given Genotype, and, for each Chromosome in this Genotype, there is an equal chromosome in the given Genotype. The chromosomes do not need to appear in the same order within the population.
Parameters
a_other the object to compare against
Returns
true if the objects are the same, false otherwise
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 397 of file Genotype.java.
References org.jgap.Genotype.Genotype(), org.jgap.Genotype.getChromosomes(), and org.jgap.Genotype.getPopulation().
Referenced by org.jgap.xml.XMLManagerTest.testGetGenotypeFromDocument_1().
synchronized void org.jgap.Genotype.evolve () [inline]
Evolves the population of Chromosomes within this Genotype. This will execute all of the genetic operators added to the present active configuration and then invoke the natural selector to choose which chromosomes will be included in the next generation population. Note that the population size not always remains constant (dependent on the NaturalSelectors used!). To consecutively call this method, use evolve(int)!!!
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 231 of file Genotype.java.
References org.jgap.Genotype.getConfiguration(), org.jgap.Genotype.getPopulation(), and org.jgap.Genotype.setPopulation().
Referenced by org.jgap.Genotype.evolve(), and org.jgap.Genotype.run().
void org.jgap.Genotype.evolve (int a_numberOfEvolutions) [inline]
Evolves this Genotype the specified number of times. This is equivalent to invoking the standard evolve() method the given number of times in a row.
Parameters
a_numberOfEvolutions the number of times to evolve this Genotype before returning
Author
Klaus Meffert
Since
1.1
Definition at line 248 of file Genotype.java.
References org.jgap.Genotype.evolve(), org.jgap.Genotype.getPopulation(), org.jgap.Configuration.getPopulationSize(), org.jgap.Configuration.isKeepPopulationSizeConstant(), org.jgap.Genotype.keepPopSizeConstant(), and org.jgap.Genotype.m_activeConfiguration.
List<String> org.jgap.Genotype.evolve (IEvolutionMonitor a_monitor) [inline]
Evolves this genotype until the given monitor asks to quit the evolution cycle.
Parameters
a_monitor the monitor used to decide when to stop evolution
Returns
messages of the registered evolution monitor. May indicate why the evolution was asked to be stopped. May be empty, depending on the implementation of the used monitor
Author
Klaus Meffert
Since
3.4.4
Definition at line 271 of file Genotype.java.
References org.jgap.Genotype.evolve(), org.jgap.Genotype.getConfiguration(), and org.jgap.Genotype.getPopulation().
void org.jgap.Genotype.fillPopulation (final int a_num) throws InvalidConfigurationException [inline]
Fills up the population with random chromosomes if necessary.
Parameters
a_num the number of chromosomes to add
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.2
Definition at line 354 of file Genotype.java.
References org.jgap.Genotype.getConfiguration(), and org.jgap.Genotype.getPopulation().
synchronized IChromosome [] org.jgap.Genotype.getChromosomes () [inline]
Retrieves the array of Chromosomes that make up the population of this Genotype instance.
Returns
the Population of Chromosomes
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Deprecated
Deprecated uses getPopulation() instead
Definition at line 151 of file Genotype.java.
References org.jgap.Genotype.getPopulation().
Referenced by org.jgap.Genotype.applyGeneticOperators(), and org.jgap.Genotype.equals().
Configuration org.jgap.Genotype.getConfiguration () [inline]
Definition at line 535 of file Genotype.java.
References org.jgap.Genotype.m_activeConfiguration.
Referenced by org.jgap.Genotype.applyNaturalSelectors(), org.jgap.Genotype.evolve(), org.jgap.Genotype.fillPopulation(), org.jgap.Genotype.getEvolves(), and org.jgap.Genotype.mergeResults().
List<IEvolveJob> org.jgap.Genotype.getEvolves (IPopulationSplitter a_splitter) throws Exception [inline]
Splits a population into pieces that can be evolved independently.
Parameters
a_splitter splits the population
Returns
list of IEvolveJob objects
Exceptions
Exception
Author
Klaus Meffert
Definition at line 644 of file Genotype.java.
References org.jgap.Genotype.getConfiguration(), and org.jgap.Genotype.getPopulation().
synchronized IChromosome org.jgap.Genotype.getFittestChromosome () [inline]
Retrieves the Chromosome in the Population with the highest fitness value.
Returns
the Chromosome with the highest fitness value, or null if there are no chromosomes in this Genotype
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 182 of file Genotype.java.
References org.jgap.Genotype.getPopulation().
synchronized IChromosome org.jgap.Genotype.getFittestChromosome (int a_startIndex, int a_endIndex) [inline]
Retrieves the Chromosome in the Population with the highest fitness value within the given indices.
Parameters
a_startIndex the index to start the determination with
a_endIndex the index to end the determination with
Returns
the Chromosome with the highest fitness value within the given indices, or null if there are no chromosomes in this Genotype
Author
Klaus Meffert
Since
3.0
Definition at line 198 of file Genotype.java.
References org.jgap.Genotype.getPopulation().
synchronized List org.jgap.Genotype.getFittestChromosomes (int a_numberOfChromosomes) [inline]
Retrieves the top n Chromsomes in the population (the ones with the best fitness values).
Parameters
a_numberOfChromosomes the number of chromosomes desired
Returns
the list of Chromosomes with the highest fitness values, or null if there are no chromosomes in this Genotype
Author
Charles Kevin Hill
Since
2.4
Definition at line 214 of file Genotype.java.
References org.jgap.Genotype.getPopulation().
Population org.jgap.Genotype.getPopulation () [inline]
Returns
the current population of chromosomes
Author
Klaus Meffert
Since
2.1
Definition at line 167 of file Genotype.java.
References org.jgap.Genotype.m_population.
Referenced by org.jgap.Genotype.applyGeneticOperators(), org.jgap.Genotype.applyNaturalSelectors(), org.jgap.GenotypeTest.doTestEvolve_5(), org.jgap.Genotype.equals(), org.jgap.Genotype.evolve(), org.jgap.Genotype.fillPopulation(), org.jgap.Genotype.getChromosomes(), org.jgap.Genotype.getEvolves(), org.jgap.Genotype.getFittestChromosome(), org.jgap.Genotype.getFittestChromosomes(), org.jgap.Genotype.hashCode(), org.jgap.audit.Evaluator.storeGenotype(), org.jgap.GenotypeTest.testEvolve_1(), and org.jgap.Genotype.toString().
static Configuration org.jgap.Genotype.getStaticConfiguration () [inline], [static]
Returns
the configuration to use with the Genetic Algorithm
Author
Klaus Meffert
Since
2.0
Definition at line 520 of file Genotype.java.
References org.jgap.Genotype.m_staticConfiguration.
Referenced by org.jgap.ChromosomeForTesting.ChromosomeForTesting(), org.jgap.ChromosomeForTesting2.ChromosomeForTesting2(), org.jgap.impl.CrossoverOperator.CrossoverOperator(), org.jgap.impl.GreedyCrossover.GreedyCrossover(), org.jgap.NaturalSelectorExt.NaturalSelectorExt(), org.jgap.impl.TournamentSelector.TournamentSelector(), and org.jgap.impl.TwoWayMutationOperator.TwoWayMutationOperator().
int org.jgap.Genotype.hashCode () [inline]
Definition at line 555 of file Genotype.java.
References org.jgap.Genotype.getPopulation().
void org.jgap.Genotype.keepPopSizeConstant (Population a_pop, int a_maxSize) [inline], [protected]
Cares that the population size does not exceed the given maximum size.
Parameters
a_pop the population to keep constant in size
a_maxSize the maximum size allowed for the population
Author
Klaus Meffert
Since
2.5
Todo
Todo use StandardPostSelector instead?
Definition at line 602 of file Genotype.java.
Referenced by org.jgap.Genotype.evolve().
void org.jgap.Genotype.mergeResults (IPopulationMerger a_merger, EvolveResult[] a_results) throws Exception [inline]
Todo
Todo use/enhance IPopulationMerger
Definition at line 673 of file Genotype.java.
References org.jgap.Genotype.getConfiguration(), and org.jgap.Genotype.setPopulation().
static Genotype org.jgap.Genotype.randomInitialGenotype (Configuration a_configuration) throws InvalidConfigurationException [inline], [static]
Convenience method that returns a newly constructed Genotype instance configured according to the given Configuration instance. The population of Chromosomes will be created according to the setup of the sample Chromosome in the Configuration object, but the gene values (alleles) will be set to random legal values.
Parameters
a_configuration the current active Configuration object
Returns
a newly constructed Genotype instance
Exceptions
IllegalArgumentException if the given Configuration object is null
InvalidConfigurationException if the given Configuration instance is not in a valid state
Author
Neil Rotstan
Klaus Meffert
Since
2.3
Definition at line 321 of file Genotype.java.
References org.jgap.Genotype.Genotype().
void org.jgap.Genotype.run () [inline]
If used in a Thread: runs the evolution forever. You have to implement a listener to stop computation sometime. See examples.simpleBooleanThreaded for a possible implementation of such a listener.
Author
Klaus Meffert
Since
3.01
Definition at line 624 of file Genotype.java.
References org.jgap.Genotype.evolve(), org.jgap.Genotype.m_monitor, and org.jgap.Genotype.m_useMonitor.
void org.jgap.Genotype.setMonitor (IEvolutionMonitor a_monitor) [inline]
Sets the evolution monitor to use, activate it via setUseMonitor(true). Only to be used when running Genotype as a thread.
Parameters
a_monitor the IEvolutionMonitor to use
Author
Klaus Meffert
Since
3.6
Definition at line 716 of file Genotype.java.
References org.jgap.Genotype.m_monitor.
void org.jgap.Genotype.setPopulation (Population a_pop) [inline], [protected]
Definition at line 570 of file Genotype.java.
References org.jgap.Genotype.m_population.
Referenced by org.jgap.Genotype.applyNaturalSelectors(), org.jgap.Genotype.evolve(), and org.jgap.Genotype.mergeResults().
static void org.jgap.Genotype.setStaticConfiguration (Configuration a_configuration) [inline], [static]
Sets the configuration to use with the Genetic Algorithm.
Parameters
a_configuration the configuration to use
Author
Klaus Meffert
Since
2.0
Definition at line 531 of file Genotype.java.
References org.jgap.Genotype.m_staticConfiguration.
void org.jgap.Genotype.setUseMonitor (boolean a_useMonitor) [inline]
Use an evolution monitor, only to be used when running Genotype as a thread. Otherwise use method evolve(IEvolutionMonitor)
Parameters
a_useMonitor true: use evolution monitor, set it via setMonitor
Author
Klaus Meffert
Since
3.6
Definition at line 703 of file Genotype.java.
References org.jgap.Genotype.m_useMonitor.
String org.jgap.Genotype.toString () [inline]
Returns
string representation of this Genotype instance, useful for display or debug purposes
Author
Neil Rotstan
Since
1.0
Definition at line 292 of file Genotype.java.
References org.jgap.Genotype.getPopulation().
Member Data Documentation
final String org.jgap.Genotype.CVS_REVISION = `$Revision: 1.109 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 36 of file Genotype.java.
Configuration org.jgap.Genotype.m_activeConfiguration [private]
The current Configuration instance.
Since
1.0
Definition at line 42 of file Genotype.java.
Referenced by org.jgap.Genotype.applyNaturalSelectors(), org.jgap.Genotype.evolve(), org.jgap.Genotype.Genotype(), and org.jgap.Genotype.getConfiguration().
IEvolutionMonitor org.jgap.Genotype.m_monitor [private]
Definition at line 57 of file Genotype.java.
Referenced by org.jgap.Genotype.run(), and org.jgap.Genotype.setMonitor().
Population org.jgap.Genotype.m_population [private]
The array of Chromosomes that make-up the Genotype's population.
Since
2.0
Definition at line 50 of file Genotype.java.
Referenced by org.jgap.Genotype.Genotype(), org.jgap.Genotype.getPopulation(), and org.jgap.Genotype.setPopulation().
transient Configuration org.jgap.Genotype.m_staticConfiguration [static], [private]
Definition at line 44 of file Genotype.java.
Referenced by org.jgap.Genotype.getStaticConfiguration(), and org.jgap.Genotype.setStaticConfiguration().
boolean org.jgap.Genotype.m_useMonitor [private]
Use an enolution monitor
Since
3.6
Definition at line 55 of file Genotype.java.
Referenced by org.jgap.Genotype.run(), and org.jgap.Genotype.setUseMonitor().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/Genotype.java