org.jgap.impl.SwappingMutationOperatorTest Class Reference
Public Member Functions
void setUp ()
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testConstruct_2 () throws Exception
void testConstruct_3 () throws Exception
void testConstruct_4 () throws Exception
void testOperate_0 () throws Exception
void testOperate_1 () throws Exception
void testOperate_2 () throws Exception
void testOperate_3 () throws Exception
void testOperate_4 () throws Exception
void testOperate_5 () throws Exception
void testStartoffset_0 () throws Exception
void testIsSerializable_0 () throws Exception
void testDoSerialize_0 () throws Exception
void testEquals_0 () throws Exception
Static Public Member Functions
static Test suite ()
Private Member Functions
long checksum (Gene[] a_genes)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.19 $`
Additional Inherited Members
Detailed Description
Tests the SwappingMutationOperator class.
Author
Klaus Meffert
Since
2.1
Definition at line 25 of file SwappingMutationOperatorTest.java.
Member Function Documentation
long org.jgap.impl.SwappingMutationOperatorTest.checksum (Gene[] a_genes) [inline], [private]
Definition at line 306 of file SwappingMutationOperatorTest.java.
Referenced by org.jgap.impl.SwappingMutationOperatorTest.testOperate_4().
void org.jgap.impl.SwappingMutationOperatorTest.setUp () [inline]
Definition at line 35 of file SwappingMutationOperatorTest.java.
static Test org.jgap.impl.SwappingMutationOperatorTest.suite () [inline], [static]
Definition at line 30 of file SwappingMutationOperatorTest.java.
void org.jgap.impl.SwappingMutationOperatorTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 46 of file SwappingMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.MutationOperator.getMutationRate(), and org.jgap.impl.MutationOperator.getMutationRateCalc().
void org.jgap.impl.SwappingMutationOperatorTest.testConstruct_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 59 of file SwappingMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.MutationOperator.getMutationRate(), and org.jgap.impl.MutationOperator.getMutationRateCalc().
void org.jgap.impl.SwappingMutationOperatorTest.testConstruct_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 72 of file SwappingMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.MutationOperator.getMutationRate(), and org.jgap.impl.MutationOperator.getMutationRateCalc().
void org.jgap.impl.SwappingMutationOperatorTest.testConstruct_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 85 of file SwappingMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.MutationOperator.getMutationRate(), and org.jgap.impl.MutationOperator.getMutationRateCalc().
void org.jgap.impl.SwappingMutationOperatorTest.testConstruct_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 99 of file SwappingMutationOperatorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SwappingMutationOperatorTest.testDoSerialize_0 () throws Exception [inline]
Ensures that the operator and all objects contained implement Serializable
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 352 of file SwappingMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.doSerialize().
void org.jgap.impl.SwappingMutationOperatorTest.testEquals_0 () throws Exception [inline]
Test equals with classcast object.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 368 of file SwappingMutationOperatorTest.java.
void org.jgap.impl.SwappingMutationOperatorTest.testIsSerializable_0 () throws Exception [inline]
Ensures the operator is implementing Serializable
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 339 of file SwappingMutationOperatorTest.java.
References org.jgap.JGAPTestCase.isSerializable().
void org.jgap.impl.SwappingMutationOperatorTest.testOperate_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 112 of file SwappingMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SwappingMutationOperatorTest.testOperate_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Todo
Todo assert result is correct
Definition at line 153 of file SwappingMutationOperatorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.SwappingMutationOperatorTest.testOperate_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 172 of file SwappingMutationOperatorTest.java.
void org.jgap.impl.SwappingMutationOperatorTest.testOperate_3 () throws Exception [inline]
Tests if population size grows expectedly after two consecutive calls.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 195 of file SwappingMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.impl.SwappingMutationOperatorTest.testOperate_4 () throws Exception [inline]
Check if none of the genes is lost during swapping. The checksum must stay the same. This step tests the swapping part, not the the whole operator.
Exceptions
Exception
Author
Audrius Meskauskas
Since
2.0
Definition at line 252 of file SwappingMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.impl.SwappingMutationOperatorTest.checksum().
void org.jgap.impl.SwappingMutationOperatorTest.testOperate_5 () throws Exception [inline]
Nothing to do. Test that nothing is done.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 286 of file SwappingMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.impl.SwappingMutationOperatorTest.testStartoffset_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 320 of file SwappingMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.impl.SwappingMutationOperator.getStartOffset().
Member Data Documentation
final String org.jgap.impl.SwappingMutationOperatorTest.CVS_REVISION = `$Revision: 1.19 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file SwappingMutationOperatorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/SwappingMutationOperatorTest.java