examples.monalisa.core.GAInitialChromosomeFactory Class Reference
Static Public Member Functions
static IChromosome create (GAConfiguration a_conf) throws InvalidConfigurationException
static int getGenomeSize (GAConfiguration a_conf)
static int getNumberOfPointGenes (GAConfiguration a_conf)
static int getNumberOfColorGenes (GAConfiguration a_conf)
static int getNumberOfGenesPerPolygon ()
static int getNumberOfColorGenesPerPolygon ()
static int getNumberOfGenesPerPoint ()
Static Public Attributes
static final int POINTS = 5
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Detailed Description
Creates a suitable initial chromosome.
Author
Yann N. Dauphin
Since
3.4
Definition at line 23 of file GAInitialChromosomeFactory.java.
Member Function Documentation
static IChromosome examples.monalisa.core.GAInitialChromosomeFactory.create (GAConfiguration a_conf) throws InvalidConfigurationException [inline], [static]
Definition at line 32 of file GAInitialChromosomeFactory.java.
References examples.monalisa.core.GAInitialChromosomeFactory.getGenomeSize(), examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfColorGenesPerPolygon(), and examples.monalisa.core.GAInitialChromosomeFactory.POINTS.
Referenced by examples.monalisa.core.GAConfiguration.GAConfiguration().
static int examples.monalisa.core.GAInitialChromosomeFactory.getGenomeSize (GAConfiguration a_conf) [inline], [static]
Definition at line 58 of file GAInitialChromosomeFactory.java.
References examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfColorGenes(), and examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfPointGenes().
Referenced by examples.monalisa.core.GAInitialChromosomeFactory.create().
static int examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfColorGenes (GAConfiguration a_conf) [inline], [static]
Definition at line 66 of file GAInitialChromosomeFactory.java.
References examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfColorGenesPerPolygon().
Referenced by examples.monalisa.core.GAInitialChromosomeFactory.getGenomeSize().
static int examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfColorGenesPerPolygon () [inline], [static]
Definition at line 75 of file GAInitialChromosomeFactory.java.
Referenced by examples.monalisa.core.GAInitialChromosomeFactory.create(), examples.monalisa.core.GAPhenotypeExpresser.expressPolygon(), examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfColorGenes(), and examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfGenesPerPolygon().
static int examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfGenesPerPoint () [inline], [static]
Definition at line 79 of file GAInitialChromosomeFactory.java.
Referenced by examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfGenesPerPolygon(), examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfPointGenes(), and examples.monalisa.core.PointMutationOperator.operate().
static int examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfGenesPerPolygon () [inline], [static]
Definition at line 70 of file GAInitialChromosomeFactory.java.
References examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfColorGenesPerPolygon(), examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfGenesPerPoint(), and examples.monalisa.core.GAInitialChromosomeFactory.POINTS.
Referenced by examples.monalisa.core.SingleMutationOperator.operate(), and examples.monalisa.core.PolygonMutationOperator.operate().
static int examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfPointGenes (GAConfiguration a_conf) [inline], [static]
Definition at line 62 of file GAInitialChromosomeFactory.java.
References examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfGenesPerPoint(), and examples.monalisa.core.GAInitialChromosomeFactory.POINTS.
Referenced by examples.monalisa.core.GAInitialChromosomeFactory.getGenomeSize().
Member Data Documentation
final String examples.monalisa.core.GAInitialChromosomeFactory.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file GAInitialChromosomeFactory.java.
final int examples.monalisa.core.GAInitialChromosomeFactory.POINTS = 5 [static]
Number of points in a polygon.
Definition at line 30 of file GAInitialChromosomeFactory.java.
Referenced by examples.monalisa.core.GAInitialChromosomeFactory.create(), examples.monalisa.core.GAPhenotypeExpresser.expressPolygon(), examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfGenesPerPolygon(), examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfPointGenes(), examples.monalisa.core.SingleMutationOperator.operate(), examples.monalisa.core.PointMutationOperator.operate(), and examples.monalisa.core.PolygonMutationOperator.operate().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/monalisa/core/GAInitialChromosomeFactory.java