org.jgap.gp.terminal.Constant Class Reference
Public Member Functions
Constant (final GPConfiguration a_conf, Class a_type, Object a_value) throws InvalidConfigurationException
Constant (final GPConfiguration a_conf, Class a_type, Object a_value, int a_subReturnType) throws InvalidConfigurationException
String toString ()
String getName ()
int execute_int (ProgramChromosome c, int n, Object[] args)
long execute_long (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
Object clone ()
Private Attributes
Object m_value
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.8 $`
Additional Inherited Members
Detailed Description
A constant remaining the same value all time.
Author
Klaus Meffert
Since
3.0
Definition at line 23 of file Constant.java.
Constructor & Destructor Documentation
org.jgap.gp.terminal.Constant.Constant (final GPConfiguration a_conf, Class a_type, Object a_value) throws InvalidConfigurationException [inline]
Definition at line 30 of file Constant.java.
Referenced by org.jgap.gp.terminal.Constant.clone().
org.jgap.gp.terminal.Constant.Constant (final GPConfiguration a_conf, Class a_type, Object a_value, int a_subReturnType) throws InvalidConfigurationException [inline]
Definition at line 35 of file Constant.java.
References org.jgap.gp.terminal.Constant.m_value.
Member Function Documentation
Object org.jgap.gp.terminal.Constant.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.6
Implements org.jgap.util.ICloneable.
Definition at line 84 of file Constant.java.
References org.jgap.gp.terminal.Constant.Constant(), org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), org.jgap.gp.CommandGene.getSubReturnType(), and org.jgap.gp.terminal.Constant.m_value.
double org.jgap.gp.terminal.Constant.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 68 of file Constant.java.
References org.jgap.gp.terminal.Constant.m_value.
float org.jgap.gp.terminal.Constant.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 64 of file Constant.java.
References org.jgap.gp.terminal.Constant.m_value.
int org.jgap.gp.terminal.Constant.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 56 of file Constant.java.
References org.jgap.gp.terminal.Constant.m_value.
long org.jgap.gp.terminal.Constant.execute_long (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 60 of file Constant.java.
References org.jgap.gp.terminal.Constant.m_value.
Object org.jgap.gp.terminal.Constant.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 72 of file Constant.java.
References org.jgap.gp.terminal.Constant.m_value.
String org.jgap.gp.terminal.Constant.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 52 of file Constant.java.
String org.jgap.gp.terminal.Constant.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 42 of file Constant.java.
Member Data Documentation
final String org.jgap.gp.terminal.Constant.CVS_REVISION = `$Revision: 1.8 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file Constant.java.
Object org.jgap.gp.terminal.Constant.m_value [private]
Definition at line 28 of file Constant.java.
Referenced by org.jgap.gp.terminal.Constant.clone(), org.jgap.gp.terminal.Constant.Constant(), org.jgap.gp.terminal.Constant.execute_double(), org.jgap.gp.terminal.Constant.execute_float(), org.jgap.gp.terminal.Constant.execute_int(), org.jgap.gp.terminal.Constant.execute_long(), and org.jgap.gp.terminal.Constant.execute_object().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/terminal/Constant.java