examples.gp.monalisa.core.commands.PointConstructor Class Reference
Public Member Functions
PointConstructor (GPConfiguration a_conf) throws InvalidConfigurationException
Object execute_object (ProgramChromosome a_chrom, int a_n, Object[] a_args)
Class getChildType (IGPProgram a_ind, int a_chromNum)
String toString ()
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
A point, consisting of an X and a Y coordinate.
Author
Yann N. Dauphin
Since
3.4
Definition at line 27 of file PointConstructor.java.
Constructor & Destructor Documentation
examples.gp.monalisa.core.commands.PointConstructor.PointConstructor (GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Definition at line 32 of file PointConstructor.java.
Referenced by examples.gp.monalisa.core.commands.PointConstructor.clone().
Member Function Documentation
Object examples.gp.monalisa.core.commands.PointConstructor.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4.1
Definition at line 65 of file PointConstructor.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), and examples.gp.monalisa.core.commands.PointConstructor.PointConstructor().
Object examples.gp.monalisa.core.commands.PointConstructor.execute_object (ProgramChromosome a_chrom, int a_n, Object[] a_args) [inline]
Definition at line 40 of file PointConstructor.java.
Class examples.gp.monalisa.core.commands.PointConstructor.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Definition at line 48 of file PointConstructor.java.
References org.jgap.gp.CommandGene.IntegerClass.
String examples.gp.monalisa.core.commands.PointConstructor.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 53 of file PointConstructor.java.
Member Data Documentation
final String examples.gp.monalisa.core.commands.PointConstructor.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 30 of file PointConstructor.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/monalisa/core/commands/PointConstructor.java