org.jgap.impl.BulkFitnessOffsetRemover Class Reference
Public Member Functions
BulkFitnessOffsetRemover (final FitnessFunction a_ff)
void evaluate (final Population a_chromosomes)
double getAbsoluteFitness (final IChromosome a_individuum)
Object clone ()
Private Attributes
FitnessFunction m_ff
double m_previousOffset
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.12 $`
Additional Inherited Members
Detailed Description
Takes away the fitness offset of the population to evolve. The fitness function values of the population of org.jgap.IChromosome instances will start from a minimum of 1 afterwards.
The removal of an offset in the fitness values of a population strengthens the `survival of the fittest` effect of a selector that performs selection upon fitness values. A high offset in the fitness values of a population lowers the relative difference between the fitness values of the Chromosomes in a population.
Example of applicability
You are optimizing a black box with n parameters that are mapped to org.jgap.IChromosome instances each having n org.jgap.Gene instances.
 You want to minimize the answer time of the black box and provide a org.jgap.FitnessFunction#evaluate(org.jgap.IChromosome) that takes the genes out of the chromosome, put's it's org.jgap.Gene#getAllele() values to the parameters and measures the answer time of the black box (by invoking it's service to optimize).
 The longer the time takes, the worse it's fitness is, so you have to invert the measured times to fitness values:
<font color="#0011EE">
class BlackBoxOptimizer extends org.jgap.FitnessFunction{
  private BlackBox bbox;
  <font color="#999999">//Additional code: constructors</font>
  <font color="#999999">...</font>
  public double evaluate(org.jgap.IChromosome chromosome){
    double fitness = 0;
    <font color="#999999">// get the Gene[] & put the parameters into the box.
    ...
    </font>
    long duration = System.currentTimeMillis();
<font color="#999999">
// You certainly will use an advanced StopWatch...</font>
    this.bbox.service();
<font color="#999999">// The black boxes service to optimize.</font>
    duration = System.currentTimeMillis()-duration;
    <font color="#999999">// transform the time into fitness value:</font>
    fitness = double.MAX_VALUE - (double)duration;
    return fitness;
  }
}
</font>
We might get the following results (each row stands for a Chromosome, the table is a population):
duration fitness piece of fitness cake
2000 9218868437227403311 33.333333333333336949106088992532 %
3000 9218868437227402311 33.333333333333333333333333333333 %
4000 9218868437227401311 33.333333333333329717560577674135 %
If any org.jgap.NaturalSelector performs selection based upon the fitness values, it will have to put those values in relation to each other. As a fact, the probability to select the Chromosome that contained the black box parameters that caused an answer time of 4000 ms is `equal` to the probability to select the Chromosome that caused a black box answer time to be 2000 ms!
Of course one could work around that problem by replacing the Integer.MAX_VALUE transformation by a fixed maximum value the black box would need for the service. But what, if you have no guaranteed maximum answer time for the service of the black box ? Even if you have got one, it will be chosen sufficently high above the average answer time thus letting your fitness function return values with a high offset in the fitness.
This is, what happens, if you use this instance for fitness evaluation:
duration fitness piece of fitness cake
2000 2001 66.63 %
3000 1001 33.33 %
4000 1 0.03 %
Example of usage
This example shows how to use this instance for cutting fitness offsets. It is the same example as used above.
<font color="#0011EE">
class BlackBoxOptimizer extends org.jgap.FitnessFunction{
  <font color="#999999">// Additional code: constructors
  ...</font>
  public double evaluate(org.jgap.IChromosome chromosome){
    <font color="#999999">.... // As shown above.</font>
  }
  public void startOptimization(org.jgap.Configuration gaConf)
      throws InvalidConfigurationException{
    <font color="#999999">
    // The given Configuration may be preconfigured with
    // NaturalSelector & GeneticOperator instances,.
    // But should not contain a FitnessFunction or BulkFitnessFunction!
</font>
    gaConf.setBulkFitnessFunction(new BulkFitnessOffsetRemover(this));
    <font color="#999999">// Why does it work? We implement FitnessFunction!
    // Still to do here:
    // - Create a sample chromosome according to your blackbox & set it to
     // the configuration.
    // - Create a random inital Genotype.
    // - loop over a desired amount of generations invoking
     // aGenotype.evolve()..</font>
  }
}
</font>
Author
Achim Westermann
Since
2.2
Definition at line 223 of file BulkFitnessOffsetRemover.java.
Constructor & Destructor Documentation
org.jgap.impl.BulkFitnessOffsetRemover.BulkFitnessOffsetRemover (final FitnessFunction a_ff) [inline]
Definition at line 261 of file BulkFitnessOffsetRemover.java.
References org.jgap.impl.BulkFitnessOffsetRemover.m_ff.
Referenced by org.jgap.impl.BulkFitnessOffsetRemover.clone().
Member Function Documentation
Object org.jgap.impl.BulkFitnessOffsetRemover.clone () [inline]
Returns
deep clone of current instance
Author
Klaus Meffert
Since
3.2
Implements org.jgap.util.ICloneable.
Definition at line 461 of file BulkFitnessOffsetRemover.java.
References org.jgap.impl.BulkFitnessOffsetRemover.BulkFitnessOffsetRemover(), org.jgap.FitnessFunction.clone(), and org.jgap.impl.BulkFitnessOffsetRemover.m_ff.
void org.jgap.impl.BulkFitnessOffsetRemover.evaluate (final Population a_chromosomes) [inline]
Definition at line 271 of file BulkFitnessOffsetRemover.java.
References org.jgap.impl.BulkFitnessOffsetRemover.m_previousOffset.
double org.jgap.impl.BulkFitnessOffsetRemover.getAbsoluteFitness (final IChromosome a_individuum) [inline]
Using this instance to remove the fitness offset in the populations brings the advantage of getting a selection more sensitive to the differences of fitness of the chromosomes.
The disadvantage is, that the fitness values are modified. The modification is good for jgap's selection method but bad for the guys that want to see the success of your work, or need a proof that a GA improves over time:
 The value of org.jgap.Genotype#getFittestChromosome() does not seem to increase over the generations. Most often it becomes worse. This is caused by the fact, that all Chromosomes are getting better over time (the fitness interval of all Chromosomes gets narrower) and the offset that may be cut becomes bigger.
If you want to get an absolute value independant from the offset that is cut off from the chromosome's fitness value, this method has to be used.
Stop reading here because a
Mathematical Proof
is following. How can it work to get the absolute value for all Chromosomes fitness values? Some Chromosomes may have lived for many generations and everytime their fitness was evaluated here, the old offset was added and a new one was calculated and subtracted from the fitness value.
Each bulk fitness evaluation a Chromosome experiences, it's fitness value F get's an addition of the old offset O$_{\mbox{(n-\/1)}}$ and a substraction by the new offset O$_{\mbox{n}}$ .
 $_{\mbox{n}}$ is the generation index.
F$_{\mbox{1}}$ = F$_{\mbox{0}}$ + O$_{\mbox{0}}$ - O$_{\mbox{1}}$
F$_{\mbox{2}}$ = F$_{\mbox{1}}$ + O$_{\mbox{1}}$ - O$_{\mbox{2}}$
F$_{\mbox{3}}$ = F$_{\mbox{2}}$ + O$_{\mbox{2}}$ - O$_{\mbox{3}}$
=>
1) F$_{\mbox{n}}$ = F$_{\mbox{(n-1)}}$
+ O$_{\mbox{(n-1)}}$ - O$_{\mbox{n}}$
2) F$_{\mbox{(n-1)}}$ = F$_{\mbox{(n-2)}}$
+ O$_{\mbox{(n-2)}}$ - O$_{\mbox{(n-1)}}$
2 in 1)
   F$_{\mbox{n}}$ = (F$_{\mbox{(n-2)}}$ + O$_{\mbox{(n-2)}}$
O$_{\mbox{(n-1)}}$) + O$_{\mbox{(n-1)}}$ - O$_{\mbox{n}}$
   F$_{\mbox{n}}$ = F$_{\mbox{(n-2)}}$ + O$_{\mbox{(n-2)}}$ - O$_{\mbox{n}}$
We made a step over 2 generations: With the current offset and the
fitness & offset of the
"preprevious" generation we can calculate the current fitness.
We can assume that this generation stepping works for farer steps
$_{\mbox{m}}$ (just continue step 2) until you have a generation step value
high enough ;-))
=> F$_{\mbox{n}}$ = F$_{\mbox{(n-m)}}$ + O$_{\mbox{(n-m)}}$ - O$_{\mbox{n}}$
We want to get the original absolute value of fitness:
3) m := n
=> F$_{\mbox{n}}$ = F$_{\mbox{0}}$ + O$_{\mbox{0}}$ - O$_{\mbox{n}}$
solved to F$_{\mbox{0}}$ our original value:
F$_{\mbox{0}}$ = F$_{\mbox{n}}$ + O$_{\mbox{n}}$ - O$_{\mbox{0}}$
And our initial offset O$_{\mbox{0}}$ is zero!
This shows, that it is possible to compute the original fitness value of a Chromosome from it's current fitness value and the previous offset regardless of the amounts of generations between original evaluation and the current generation.
Parameters
a_individuum any Chromosome that is normally being evaluated by this BulkFitnessFunction
Returns
the original fitness value as returned by the registered fitnessFunction instance.
Definition at line 434 of file BulkFitnessOffsetRemover.java.
References org.jgap.impl.BulkFitnessOffsetRemover.m_previousOffset.
Member Data Documentation
final String org.jgap.impl.BulkFitnessOffsetRemover.CVS_REVISION = `$Revision: 1.12 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 226 of file BulkFitnessOffsetRemover.java.
FitnessFunction org.jgap.impl.BulkFitnessOffsetRemover.m_ff [private]
Definition at line 232 of file BulkFitnessOffsetRemover.java.
Referenced by org.jgap.impl.BulkFitnessOffsetRemover.BulkFitnessOffsetRemover(), and org.jgap.impl.BulkFitnessOffsetRemover.clone().
double org.jgap.impl.BulkFitnessOffsetRemover.m_previousOffset [private]
Todo
Todo This constructor is planned but not possible yet, as the Configuration permits bulk fitness function and simple fitness function both existing in it at the same time.
The last generations offset. This has to be stored because Chromosomes that were put into the new generation's candidate list already have the fitness value without offset from their previous evaluation.
We try to avoid evaluations of the fitness function as it might be expensive, so we reuse fitness values. If a Chromosome already has a fitness value >0 this previousOffset is added to it's fitness to allow comparing this Chromosome's fitness with newly evaluated Chromosomes (which still have the offset from the evaluation).
Definition at line 259 of file BulkFitnessOffsetRemover.java.
Referenced by org.jgap.impl.BulkFitnessOffsetRemover.evaluate(), and org.jgap.impl.BulkFitnessOffsetRemover.getAbsoluteFitness().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/BulkFitnessOffsetRemover.java