org.jgap.gp.impl.TournamentSelector Class Reference
Public Member Functions
TournamentSelector ()
TournamentSelector (int a_tournament_size)
void setTournamentSize (int a_tournament_size)
IGPProgram select (GPGenotype a_genotype)
Object clone ()
Private Attributes
int m_tournament_size
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.7 $`
Additional Inherited Members
Detailed Description
A GP tournament selector. The winner is determined by letting fight a number of opponents against each other. The best of all wins.
Author
Javier Meseguer
Enrique D. Martí
Klaus Meffert
Since
3.2
Definition at line 27 of file TournamentSelector.java.
Constructor & Destructor Documentation
org.jgap.gp.impl.TournamentSelector.TournamentSelector () [inline]
Constructor with default tournament size.
Since
3.2
Definition at line 39 of file TournamentSelector.java.
Referenced by org.jgap.gp.impl.TournamentSelector.clone().
org.jgap.gp.impl.TournamentSelector.TournamentSelector (int a_tournament_size) [inline]
Preferred Constructor.
Parameters
a_tournament_size the size of the tournament
Since
3.2
Definition at line 50 of file TournamentSelector.java.
References org.jgap.gp.impl.TournamentSelector.setTournamentSize().
Member Function Documentation
Object org.jgap.gp.impl.TournamentSelector.clone () [inline]
Returns
deep clone of this instance
Author
Klaus Meffert
Since
3.2
Definition at line 114 of file TournamentSelector.java.
References org.jgap.gp.impl.TournamentSelector.m_tournament_size, and org.jgap.gp.impl.TournamentSelector.TournamentSelector().
IGPProgram org.jgap.gp.impl.TournamentSelector.select (GPGenotype a_genotype) [inline]
Does the tournament selection.
Parameters
a_genotype the genotype containing the competers
Returns
program that won the tournament
Author
Javier Meseguer
Enrique D. Martí
Klaus Meffert
Since
3.2
Definition at line 75 of file TournamentSelector.java.
References org.jgap.gp.IGPFitnessEvaluator.isFitter(), org.jgap.gp.impl.TournamentSelector.m_tournament_size, and org.jgap.RandomGenerator.nextDouble().
void org.jgap.gp.impl.TournamentSelector.setTournamentSize (int a_tournament_size) [inline]
Parameters
a_tournament_size the size of the tournament
Author
Klaus Meffert
Since
3.4
Definition at line 60 of file TournamentSelector.java.
References org.jgap.gp.impl.TournamentSelector.m_tournament_size.
Referenced by org.jgap.gp.impl.TournamentSelector.TournamentSelector().
Member Data Documentation
final String org.jgap.gp.impl.TournamentSelector.CVS_REVISION = `$Revision: 1.7 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 30 of file TournamentSelector.java.
int org.jgap.gp.impl.TournamentSelector.m_tournament_size [private]
Definition at line 32 of file TournamentSelector.java.
Referenced by org.jgap.gp.impl.TournamentSelector.clone(), org.jgap.gp.impl.TournamentSelector.select(), and org.jgap.gp.impl.TournamentSelector.setTournamentSize().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/impl/TournamentSelector.java