org.jgap.ConfigurationForTesting Class Reference
Classes
class MyAppData
Public Member Functions
ConfigurationForTesting () throws InvalidConfigurationException
synchronized void setRandomGenerator (RandomGenerator a_generatorToSet) throws InvalidConfigurationException
Static Public Attributes
static final double STATIC_FITNESS_VALUE = 2.3d
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Additional Inherited Members
Detailed Description
Ready-to-go Implementation of org.jgap.Configuration with all important parameters already set.
Author
Klaus Meffert
Since
2.2
Definition at line 22 of file ConfigurationForTesting.java.
Constructor & Destructor Documentation
org.jgap.ConfigurationForTesting.ConfigurationForTesting () throws InvalidConfigurationException [inline]
Default constructor.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.2
Definition at line 37 of file ConfigurationForTesting.java.
References org.jgap.Configuration.addGeneticOperator(), org.jgap.Configuration.addNaturalSelector(), org.jgap.Configuration.reset(), org.jgap.Configuration.setEventManager(), org.jgap.Configuration.setFitnessEvaluator(), org.jgap.Configuration.setFitnessFunction(), org.jgap.Configuration.setPopulationSize(), org.jgap.ConfigurationForTesting.setRandomGenerator(), org.jgap.Configuration.setSampleChromosome(), and org.jgap.ConfigurationForTesting.STATIC_FITNESS_VALUE.
Member Function Documentation
synchronized void org.jgap.ConfigurationForTesting.setRandomGenerator (RandomGenerator a_generatorToSet) throws InvalidConfigurationException [inline]
Allows to set the random generator freely, also to null (normally forbidden).
Parameters
a_generatorToSet the random generator to set
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 70 of file ConfigurationForTesting.java.
Referenced by org.jgap.ConfigurationForTesting.ConfigurationForTesting().
Member Data Documentation
final String org.jgap.ConfigurationForTesting.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file ConfigurationForTesting.java.
final double org.jgap.ConfigurationForTesting.STATIC_FITNESS_VALUE = 2.3d [static]
Definition at line 27 of file ConfigurationForTesting.java.
Referenced by org.jgap.ConfigurationForTesting.ConfigurationForTesting().
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/ConfigurationForTesting.java