org.jgap.gp.function.Multiply Class Reference
Classes
interface Compatible
Public Member Functions
Multiply (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException
CommandGene applyMutation (int index, double a_percentage) throws InvalidConfigurationException
Object clone ()
String toString ()
String getName ()
int execute_int (ProgramChromosome c, int n, Object[] args)
long execute_long (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.9 $`
Additional Inherited Members
Detailed Description
The multiply operation.
Author
Klaus Meffert
Since
3.0
Definition at line 23 of file Multiply.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Multiply.Multiply (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 28 of file Multiply.java.
Referenced by org.jgap.gp.function.Multiply.clone().
Member Function Documentation
CommandGene org.jgap.gp.function.Multiply.applyMutation (int a_index, double a_percentage) throws InvalidConfigurationException [inline]
Mutates a CommandGene.
Parameters
a_index references the part of a multipart object, normally not relevant
a_percentage the mutation rate (0.0 to 1.0)
Returns
the mutant
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IMutateable.
Definition at line 33 of file Multiply.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.CommandGene.getReturnType().
Object org.jgap.gp.function.Multiply.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 47 of file Multiply.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.function.Multiply.Multiply().
double org.jgap.gp.function.Multiply.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 82 of file Multiply.java.
float org.jgap.gp.function.Multiply.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 78 of file Multiply.java.
int org.jgap.gp.function.Multiply.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 70 of file Multiply.java.
long org.jgap.gp.function.Multiply.execute_long (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 74 of file Multiply.java.
Object org.jgap.gp.function.Multiply.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 86 of file Multiply.java.
String org.jgap.gp.function.Multiply.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 66 of file Multiply.java.
String org.jgap.gp.function.Multiply.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 56 of file Multiply.java.
Member Data Documentation
final String org.jgap.gp.function.Multiply.CVS_REVISION = `$Revision: 1.9 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file Multiply.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Multiply.java