org.jgap.data.config.ConfigFileReader Class Reference
Public Member Functions
String getValue (final String a_name)
List getValues (final String a_name)
void setNS (final String a_ns)
void setFileName (final String a_fileName) throws ConfigException
Static Public Member Functions
static ConfigFileReader instance ()
Private Member Functions
ConfigFileReader ()
void load () throws ConfigException
Private Attributes
String m_fileName
Properties m_props
String m_ns
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.6 $`
static ConfigFileReader m_cfReader
Detailed Description
This is a Singleton Helper class to read a JGAP config file and provide a simple interface to the config properties.
Author
Siddhartha Azad
Since
2.3
Definition at line 22 of file ConfigFileReader.java.
Constructor & Destructor Documentation
org.jgap.data.config.ConfigFileReader.ConfigFileReader () [inline], [private]
Private Constructor.
Author
Siddhartha Azad
Since
2.3
Definition at line 59 of file ConfigFileReader.java.
References org.jgap.data.config.ConfigFileReader.m_props.
Referenced by org.jgap.data.config.ConfigFileReader.instance().
Member Function Documentation
String org.jgap.data.config.ConfigFileReader.getValue (final String a_name) [inline]
Retrieve the value for the property with the name as in param name.
Parameters
a_name name of the property of which the value is required
Returns
value for the property with the name as in param name, null if property not found
Author
Siddhartha Azad
Since
2.3
Definition at line 72 of file ConfigFileReader.java.
References org.jgap.data.config.ConfigFileReader.m_ns.
List org.jgap.data.config.ConfigFileReader.getValues (final String a_name) [inline]
Retrieve the values for the property with the name as in param name.
Parameters
a_name the name of the property of which the value is required
Returns
ArrayList of Strings with values for the property with the name as in param name, null if property not found
Author
Siddhartha Azad
Definition at line 87 of file ConfigFileReader.java.
References org.jgap.data.config.ConfigFileReader.m_ns.
static ConfigFileReader org.jgap.data.config.ConfigFileReader.instance () [inline], [static]
Method to create and access the Singleton ConfigFileReader instance.
Returns
instance of the ConfigFileReader
Author
Siddhartha Azad
Since
2.3
Definition at line 46 of file ConfigFileReader.java.
References org.jgap.data.config.ConfigFileReader.ConfigFileReader(), and org.jgap.data.config.ConfigFileReader.m_cfReader.
void org.jgap.data.config.ConfigFileReader.load () throws ConfigException [inline], [private]
Load the config properties file into a Properties instance.
Exceptions
ConfigException
Author
Siddhartha Azad
Since
2.3
Definition at line 147 of file ConfigFileReader.java.
References org.jgap.data.config.ConfigFileReader.m_fileName.
Referenced by org.jgap.data.config.ConfigFileReader.setFileName().
void org.jgap.data.config.ConfigFileReader.setFileName (final String a_fileName) throws ConfigException [inline]
Set the config file to load from. Everytime this method is called, properties are reloaded from the config file.
Parameters
a_fileName Name of the config file.
Exceptions
ConfigException
Author
Siddhartha Azad
Since
2.3
Definition at line 134 of file ConfigFileReader.java.
References org.jgap.data.config.ConfigFileReader.load(), and org.jgap.data.config.ConfigFileReader.m_fileName.
void org.jgap.data.config.ConfigFileReader.setNS (final String a_ns) [inline]
Set the namespace for the properties that are being read from the config file at this point.
Parameters
a_ns namespace for the properties being read
Author
Siddhartha Azad
Definition at line 120 of file ConfigFileReader.java.
References org.jgap.data.config.ConfigFileReader.m_ns.
Member Data Documentation
final String org.jgap.data.config.ConfigFileReader.CVS_REVISION = `$Revision: 1.6 $` [static], [private]
Definition at line 23 of file ConfigFileReader.java.
ConfigFileReader org.jgap.data.config.ConfigFileReader.m_cfReader [static], [private]
Singleton Instance of ConfigFileReader
Definition at line 37 of file ConfigFileReader.java.
Referenced by org.jgap.data.config.ConfigFileReader.instance().
String org.jgap.data.config.ConfigFileReader.m_fileName [private]
Definition at line 26 of file ConfigFileReader.java.
Referenced by org.jgap.data.config.ConfigFileReader.load(), and org.jgap.data.config.ConfigFileReader.setFileName().
String org.jgap.data.config.ConfigFileReader.m_ns [private]
Definition at line 32 of file ConfigFileReader.java.
Referenced by org.jgap.data.config.ConfigFileReader.getValue(), org.jgap.data.config.ConfigFileReader.getValues(), and org.jgap.data.config.ConfigFileReader.setNS().
Properties org.jgap.data.config.ConfigFileReader.m_props [private]
Definition at line 29 of file ConfigFileReader.java.
Referenced by org.jgap.data.config.ConfigFileReader.ConfigFileReader().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/data/config/ConfigFileReader.java