org.jgap.gp.GPProgramBase Class Reference
Public Member Functions
GPProgramBase () throws Exception
GPProgramBase (GPConfiguration a_conf) throws InvalidConfigurationException
GPProgramBase (IGPProgram a_prog) throws InvalidConfigurationException
GPConfiguration getGPConfiguration ()
boolean equals (Object a_other)
double calcFitnessValue ()
double getFitnessValue ()
double getFitnessValueDirectly ()
void setFitnessValue (double a_fitness)
void setTypes (Class[] a_types)
Class[] getTypes ()
Class getType (int a_index)
void setArgTypes (Class[][] a_argTypes)
Class[][] getArgTypes ()
Class[] getArgType (int a_index)
void setNodeSets (CommandGene[][] a_nodeSets)
CommandGene[][] getNodeSets ()
CommandGene[] getNodeSet (int a_index)
void setMaxDepths (int[] a_maxDepths)
int[] getMaxDepths ()
void setMinDepths (int[] a_minDepths)
int[] getMinDepths ()
void setMaxNodes (int a_maxNodes)
int getMaxNodes ()
void setApplicationData (Object a_data)
Object getApplicationData ()
abstract Object clone ()
Private Attributes
double m_fitnessValue = FitnessFunction.NO_FITNESS_VALUE
GPConfiguration m_conf
Class[] m_types
Class[][] m_argTypes
CommandGene[][] m_nodeSets
int[] m_minDepths
int[] m_maxDepths
int m_maxNodes
Object m_applicationData
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.14 $`
Additional Inherited Members
Detailed Description
Base class for GPProgram's. See org.jgap.gp.impl.GPProgram for an implementation.
Author
Klaus Meffert
Since
3.0
Definition at line 22 of file GPProgramBase.java.
Constructor & Destructor Documentation
org.jgap.gp.GPProgramBase.GPProgramBase () throws Exception [inline]
Default constructor, only for dynamic instantiation.
Exceptions
Exception
Author
Klaus Meffert
Since
3.3.4
Definition at line 75 of file GPProgramBase.java.
org.jgap.gp.GPProgramBase.GPProgramBase (GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Definition at line 79 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_conf.
org.jgap.gp.GPProgramBase.GPProgramBase (IGPProgram a_prog) throws InvalidConfigurationException [inline]
Definition at line 87 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_argTypes, org.jgap.gp.GPProgramBase.m_maxDepths, org.jgap.gp.GPProgramBase.m_maxNodes, org.jgap.gp.GPProgramBase.m_minDepths, org.jgap.gp.GPProgramBase.m_nodeSets, and org.jgap.gp.GPProgramBase.m_types.
Member Function Documentation
double org.jgap.gp.GPProgramBase.calcFitnessValue () [inline]
Returns
fitness value of this program determined via the registered fitness function
Author
Klaus Meffert
Since
3.0
Definition at line 126 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.getGPConfiguration(), org.jgap.gp.GPProgramBase.m_fitnessValue, and org.jgap.gp.GPFitnessFunction.NO_FITNESS_VALUE.
Referenced by org.jgap.gp.GPProgramBase.getFitnessValue().
abstract Object org.jgap.gp.GPProgramBase.clone () [pure virtual]
Returns
deep clone of this instance
Author
Klaus Meffert
Since
3.2
Implements org.jgap.util.ICloneable.
Implemented in org.jgap.gp.impl.GPProgram.
boolean org.jgap.gp.GPProgramBase.equals (Object a_other) [inline]
Compares this entity against the specified object.
Parameters
a_other the object to compare against
Returns
true: if the objects are the same, false otherwise
Author
Klaus Meffert
Since
3.0
Definition at line 111 of file GPProgramBase.java.
Object org.jgap.gp.GPProgramBase.getApplicationData () [inline]
Returns
the application data object set
Author
Klaus Meffert
Since
3.01
Implements org.jgap.gp.IGPProgram.
Definition at line 250 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_applicationData.
Referenced by org.jgap.gp.impl.GPProgram.clone().
Class [] org.jgap.gp.GPProgramBase.getArgType (int a_index) [inline]
Definition at line 192 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_argTypes.
Referenced by org.jgap.gp.impl.GPProgram.growOrFull().
Class [][] org.jgap.gp.GPProgramBase.getArgTypes () [inline]
Implements org.jgap.gp.IGPProgram.
Definition at line 188 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_argTypes.
Referenced by org.jgap.gp.impl.GPProgram.clone(), and org.jgap.gp.impl.GPProgram.growOrFull().
double org.jgap.gp.GPProgramBase.getFitnessValue () [inline]
Returns
fitness value of this program, cached access
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IGPProgram.
Definition at line 149 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.calcFitnessValue(), and org.jgap.gp.GPProgramBase.m_fitnessValue.
double org.jgap.gp.GPProgramBase.getFitnessValueDirectly () [inline]
Returns
computed fitness value of this program, may be unitialized
Author
Klaus Meffert
Since
3.2
Definition at line 164 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_fitnessValue.
Referenced by org.jgap.gp.impl.GPProgram.clone().
GPConfiguration org.jgap.gp.GPProgramBase.getGPConfiguration () [inline]
Implements org.jgap.gp.IGPProgram.
Definition at line 98 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_conf.
Referenced by org.jgap.gp.GPProgramBase.calcFitnessValue(), org.jgap.gp.impl.GPProgram.clone(), org.jgap.gp.impl.GPProgram.growOrFull(), and org.jgap.gp.impl.GPProgram.putToCache().
int [] org.jgap.gp.GPProgramBase.getMaxDepths () [inline]
Implements org.jgap.gp.IGPProgram.
Definition at line 212 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_maxDepths.
Referenced by org.jgap.gp.impl.GPProgram.clone(), and org.jgap.gp.impl.GPProgram.growOrFull().
int org.jgap.gp.GPProgramBase.getMaxNodes () [inline]
Implements org.jgap.gp.IGPProgram.
Definition at line 228 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_maxNodes.
Referenced by org.jgap.gp.impl.GPProgram.clone().
int [] org.jgap.gp.GPProgramBase.getMinDepths () [inline]
Implements org.jgap.gp.IGPProgram.
Definition at line 220 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_minDepths.
Referenced by org.jgap.gp.impl.GPProgram.clone(), and org.jgap.gp.impl.GPProgram.growOrFull().
CommandGene [] org.jgap.gp.GPProgramBase.getNodeSet (int a_index) [inline]
Definition at line 204 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_nodeSets.
Referenced by org.jgap.gp.impl.GPProgram.growOrFull().
CommandGene [][] org.jgap.gp.GPProgramBase.getNodeSets () [inline]
Implements org.jgap.gp.IGPProgram.
Definition at line 200 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_nodeSets.
Referenced by org.jgap.gp.impl.GPProgram.clone(), and org.jgap.gp.impl.GPProgram.growOrFull().
Class org.jgap.gp.GPProgramBase.getType (int a_index) [inline]
Definition at line 180 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_types.
Referenced by org.jgap.gp.impl.GPProgram.growOrFull().
Class [] org.jgap.gp.GPProgramBase.getTypes () [inline]
Implements org.jgap.gp.IGPProgram.
Definition at line 176 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_types.
Referenced by org.jgap.gp.impl.GPProgram.clone(), org.jgap.gp.impl.GPProgram.GPProgram(), and org.jgap.gp.impl.GPProgram.growOrFull().
void org.jgap.gp.GPProgramBase.setApplicationData (Object a_data) [inline]
Sets the application data object.
Parameters
a_data the object to set
Author
Klaus Meffert
Since
3.01
Implements org.jgap.gp.IGPProgram.
Definition at line 240 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_applicationData.
void org.jgap.gp.GPProgramBase.setArgTypes (Class a_argTypes[][]) [inline]
Implements org.jgap.gp.IGPProgram.
Definition at line 184 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_argTypes.
Referenced by org.jgap.gp.impl.GPProgram.GPProgram().
void org.jgap.gp.GPProgramBase.setFitnessValue (double a_fitness) [inline]
Implements org.jgap.gp.IGPProgram.
Definition at line 168 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_fitnessValue.
Referenced by org.jgap.gp.impl.GPProgram.growOrFull().
void org.jgap.gp.GPProgramBase.setMaxDepths (int[] a_maxDepths) [inline]
Implements org.jgap.gp.IGPProgram.
Definition at line 208 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_maxDepths.
Referenced by org.jgap.gp.impl.GPProgram.GPProgram().
void org.jgap.gp.GPProgramBase.setMaxNodes (int a_maxNodes) [inline]
Implements org.jgap.gp.IGPProgram.
Definition at line 224 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_maxNodes.
Referenced by org.jgap.gp.impl.GPProgram.GPProgram().
void org.jgap.gp.GPProgramBase.setMinDepths (int[] a_minDepths) [inline]
Implements org.jgap.gp.IGPProgram.
Definition at line 216 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_minDepths.
Referenced by org.jgap.gp.impl.GPProgram.GPProgram().
void org.jgap.gp.GPProgramBase.setNodeSets (CommandGene a_nodeSets[][]) [inline]
Implements org.jgap.gp.IGPProgram.
Definition at line 196 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_nodeSets.
Referenced by org.jgap.gp.impl.GPProgram.GPProgram().
void org.jgap.gp.GPProgramBase.setTypes (Class[] a_types) [inline]
Implements org.jgap.gp.IGPProgram.
Definition at line 172 of file GPProgramBase.java.
References org.jgap.gp.GPProgramBase.m_types.
Referenced by org.jgap.gp.impl.GPProgram.GPProgram().
Member Data Documentation
final String org.jgap.gp.GPProgramBase.CVS_REVISION = `$Revision: 1.14 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file GPProgramBase.java.
Object org.jgap.gp.GPProgramBase.m_applicationData [private]
Free to use data object.
Definition at line 65 of file GPProgramBase.java.
Referenced by org.jgap.gp.GPProgramBase.getApplicationData(), and org.jgap.gp.GPProgramBase.setApplicationData().
Class [][] org.jgap.gp.GPProgramBase.m_argTypes [private]
Argument types for ADF's
Definition at line 39 of file GPProgramBase.java.
Referenced by org.jgap.gp.GPProgramBase.getArgType(), org.jgap.gp.GPProgramBase.getArgTypes(), org.jgap.gp.GPProgramBase.GPProgramBase(), and org.jgap.gp.GPProgramBase.setArgTypes().
GPConfiguration org.jgap.gp.GPProgramBase.m_conf [private]
Definition at line 29 of file GPProgramBase.java.
Referenced by org.jgap.gp.GPProgramBase.getGPConfiguration(), and org.jgap.gp.GPProgramBase.GPProgramBase().
double org.jgap.gp.GPProgramBase.m_fitnessValue = FitnessFunction.NO_FITNESS_VALUE [private]
Definition at line 27 of file GPProgramBase.java.
Referenced by org.jgap.gp.GPProgramBase.calcFitnessValue(), org.jgap.gp.GPProgramBase.getFitnessValue(), org.jgap.gp.GPProgramBase.getFitnessValueDirectly(), and org.jgap.gp.GPProgramBase.setFitnessValue().
int [] org.jgap.gp.GPProgramBase.m_maxDepths [private]
Maximum depth per each chromosome
Definition at line 54 of file GPProgramBase.java.
Referenced by org.jgap.gp.GPProgramBase.getMaxDepths(), org.jgap.gp.GPProgramBase.GPProgramBase(), and org.jgap.gp.GPProgramBase.setMaxDepths().
int org.jgap.gp.GPProgramBase.m_maxNodes [private]
Maximum number of nodes allowed per chromosome (when exceeded program aborts)
Definition at line 60 of file GPProgramBase.java.
Referenced by org.jgap.gp.GPProgramBase.getMaxNodes(), org.jgap.gp.GPProgramBase.GPProgramBase(), and org.jgap.gp.GPProgramBase.setMaxNodes().
int [] org.jgap.gp.GPProgramBase.m_minDepths [private]
Minimum depth per each chromosome
Definition at line 49 of file GPProgramBase.java.
Referenced by org.jgap.gp.GPProgramBase.getMinDepths(), org.jgap.gp.GPProgramBase.GPProgramBase(), and org.jgap.gp.GPProgramBase.setMinDepths().
CommandGene [][] org.jgap.gp.GPProgramBase.m_nodeSets [private]
Available GP-functions.
Definition at line 44 of file GPProgramBase.java.
Referenced by org.jgap.gp.GPProgramBase.getNodeSet(), org.jgap.gp.GPProgramBase.getNodeSets(), org.jgap.gp.GPProgramBase.GPProgramBase(), and org.jgap.gp.GPProgramBase.setNodeSets().
Class [] org.jgap.gp.GPProgramBase.m_types [private]
Return type per chromosome.
Definition at line 34 of file GPProgramBase.java.
Referenced by org.jgap.gp.GPProgramBase.getType(), org.jgap.gp.GPProgramBase.getTypes(), org.jgap.gp.GPProgramBase.GPProgramBase(), and org.jgap.gp.GPProgramBase.setTypes().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/GPProgramBase.java