examples.gp.tictactoe.IsOwnColor Class Reference
Public Member Functions
IsOwnColor (final GPConfiguration a_conf, int a_color) throws InvalidConfigurationException
IsOwnColor (final GPConfiguration a_conf, int a_color, int a_subReturnType, int a_subChildType) throws InvalidConfigurationException
String toString ()
boolean execute_boolean (ProgramChromosome c, int n, Object[] args)
String getName ()
Object clone ()
Class getChildType (IGPProgram a_ind, int a_chromNum)
Private Attributes
int m_color
int m_subChildType
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
Definition at line 17 of file IsOwnColor.java.
Constructor & Destructor Documentation
examples.gp.tictactoe.IsOwnColor.IsOwnColor (final GPConfiguration a_conf, int a_color) throws InvalidConfigurationException [inline]
Definition at line 26 of file IsOwnColor.java.
Referenced by examples.gp.tictactoe.IsOwnColor.clone().
examples.gp.tictactoe.IsOwnColor.IsOwnColor (final GPConfiguration a_conf, int a_color, int a_subReturnType, int a_subChildType) throws InvalidConfigurationException [inline]
Definition at line 31 of file IsOwnColor.java.
References org.jgap.gp.CommandGene.BooleanClass, examples.gp.tictactoe.IsOwnColor.m_color, and examples.gp.tictactoe.IsOwnColor.m_subChildType.
Member Function Documentation
Object examples.gp.tictactoe.IsOwnColor.clone () [inline]
Returns
clone of the current object instance
Implements org.jgap.util.ICloneable.
Definition at line 59 of file IsOwnColor.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getSubReturnType(), examples.gp.tictactoe.IsOwnColor.IsOwnColor(), examples.gp.tictactoe.IsOwnColor.m_color, and examples.gp.tictactoe.IsOwnColor.m_subChildType.
boolean examples.gp.tictactoe.IsOwnColor.execute_boolean (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 43 of file IsOwnColor.java.
References org.jgap.gp.CommandGene.check(), and examples.gp.tictactoe.IsOwnColor.m_color.
Class examples.gp.tictactoe.IsOwnColor.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Definition at line 69 of file IsOwnColor.java.
References org.jgap.gp.CommandGene.IntegerClass.
String examples.gp.tictactoe.IsOwnColor.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 55 of file IsOwnColor.java.
String examples.gp.tictactoe.IsOwnColor.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 39 of file IsOwnColor.java.
Member Data Documentation
final String examples.gp.tictactoe.IsOwnColor.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 20 of file IsOwnColor.java.
int examples.gp.tictactoe.IsOwnColor.m_color [private]
Definition at line 22 of file IsOwnColor.java.
Referenced by examples.gp.tictactoe.IsOwnColor.clone(), examples.gp.tictactoe.IsOwnColor.execute_boolean(), and examples.gp.tictactoe.IsOwnColor.IsOwnColor().
int examples.gp.tictactoe.IsOwnColor.m_subChildType [private]
Definition at line 24 of file IsOwnColor.java.
Referenced by examples.gp.tictactoe.IsOwnColor.clone(), and examples.gp.tictactoe.IsOwnColor.IsOwnColor().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/tictactoe/IsOwnColor.java