examples.gp.monalisa.gui.EvolutionRunnable Class Reference
Public Member Functions
EvolutionRunnable (GeneticDrawingView a_view)
void run ()
Protected Attributes
final GeneticDrawingView m_view
Static Protected Attributes
static boolean initView
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
static transient Logger LOGGER = Logger.getLogger(EvolutionRunnable.class)
Detailed Description
Class in charge of actually running the evolution process.
Author
Yann N. Dauphin
Since
3.4
Definition at line 30 of file EvolutionRunnable.java.
Constructor & Destructor Documentation
examples.gp.monalisa.gui.EvolutionRunnable.EvolutionRunnable (GeneticDrawingView a_view) [inline]
Definition at line 41 of file EvolutionRunnable.java.
References examples.gp.monalisa.gui.EvolutionRunnable.m_view.
Member Function Documentation
void examples.gp.monalisa.gui.EvolutionRunnable.run () [inline]
Updates the chart in the main view.
Parameters
a_firedEvent the event
Display best solution in fittestChromosomeView's mainPanel.
Parameters
a_firedEvent the event
Definition at line 46 of file EvolutionRunnable.java.
References org.jgap.gp.IGPProgram.getApplicationData(), org.jgap.gp.IGPProgram.getFitnessValue(), org.jgap.gp.impl.GPGenotype.getGPConfiguration(), examples.gp.monalisa.gui.GeneticDrawingView.getTargetImage(), examples.gp.monalisa.gui.EvolutionRunnable.initView, examples.gp.monalisa.gui.GeneticDrawingView.isEvolutionActivated, examples.gp.monalisa.gui.GeneticDrawingView.isSaveToFile(), and examples.gp.monalisa.gui.EvolutionRunnable.m_view.
Member Data Documentation
final String examples.gp.monalisa.gui.EvolutionRunnable.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 33 of file EvolutionRunnable.java.
boolean examples.gp.monalisa.gui.EvolutionRunnable.initView [static], [protected]
Definition at line 39 of file EvolutionRunnable.java.
Referenced by examples.gp.monalisa.gui.EvolutionRunnable.run().
transient Logger examples.gp.monalisa.gui.EvolutionRunnable.LOGGER = Logger.getLogger(EvolutionRunnable.class) [static], [private]
Definition at line 35 of file EvolutionRunnable.java.
final GeneticDrawingView examples.gp.monalisa.gui.EvolutionRunnable.m_view [protected]
Definition at line 37 of file EvolutionRunnable.java.
Referenced by examples.gp.monalisa.gui.EvolutionRunnable.EvolutionRunnable(), and examples.gp.monalisa.gui.EvolutionRunnable.run().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/monalisa/gui/EvolutionRunnable.java