org.jgap.impl.DoubleGeneTest Class Reference
Classes
class GeneConstraintChecker
Public Member Functions
void setUp ()
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testConstruct_2 () throws Exception
void testConstruct_3 () throws Exception
void testToString_0 () throws Exception
void testToString_1 () throws Exception
void testToString_2 () throws Exception
void testGetAllele_0 () throws Exception
void testGetAllele_1 () throws Exception
void testGetAllele_2 () throws Exception
void testEquals_0 () throws Exception
void testEquals_1 () throws Exception
void testEquals_2 () throws Exception
void testEquals_3 () throws Exception
void testEquals_4 () throws Exception
void testEquals_5 () throws Exception
void testEquals_6 () throws Exception
void testEquals_7 () throws Exception
void testEquals_8 () throws Exception
void testDoubleValue_0 () throws Exception
void testDoubleValue_1 () throws Exception
void testSetAllele_0 () throws Exception
void testSetAllele_1 () throws Exception
void testSetAllele_2 () throws Exception
void testSetAllele_3 () throws Exception
void testSetAllele_4 () throws Exception
void testSetAllele_5 () throws Exception
void testSetAllele_6 () throws Exception
void testNewGene_0 () throws Exception
void testPersistentRepresentation_0 () throws Exception
void testPersistentRepresentation_1 () throws Exception
void testPersistentRepresentation_2 () throws Exception
void testPersistentRepresentation_3 () throws Exception
void testPersistentRepresentation_4 () throws Exception
void testPersistentRepresentation_5 () throws Exception
void testCleanup_0 () throws Exception
void testSetToRandomValue_0 () throws Exception
void testSetToRandomValue_1 () throws Exception
void testSetToRandomValue_2 () throws Exception
void testSetToRandomValue_3 () throws Exception
void testSetToRandomValue_4 () throws Exception
void testCompareToNative_0 () throws Exception
void testCompareToNative_1 () throws Exception
void testCompareToNative_2 () throws Exception
void testCompareToNative_3 () throws Exception
void testCompareToNative_4 () throws Exception
void testApplyMutation_0 () throws Exception
void testApplyMutation_1 () throws Exception
void testApplyMutation_2 () throws Exception
void testApplyMutation_3 () throws Exception
void testApplyMutation_4 () throws Exception
void testApplyMutation_5 () throws Exception
void testApplyMutation_6 () throws Exception
void testApplyMutation_7 () throws Exception
void testSetConstraintChecker_0 () throws Exception
void testHashCode_0 () throws Exception
void testHashCode_1 () throws Exception
void testSetEnergy_0 () throws Exception
void testSetEnergy_1 () throws Exception
void testBounds_0 () throws Exception
void testBounds_1 () throws Exception
void testMapValueToWithinBoundsSupportsFullDoubleRange () throws Exception
void testMapValueToWithinBoundsSupportsFullDoubleRange2 () throws Exception
void testMapValueToWithinBoundsSupportsFullDoubleRange3 () throws Exception
void testMapValueToWithinBoundsSupportsFullDoubleRange4 () throws Exception
void testMapValueToWithinBoundsSupportsFullDoubleRange5 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.42 $`
Additional Inherited Members
Detailed Description
Tests the DoubleGene class.
Author
Klaus Meffert
Since
1.1
Definition at line 22 of file DoubleGeneTest.java.
Member Function Documentation
void org.jgap.impl.DoubleGeneTest.setUp () [inline]
Definition at line 27 of file DoubleGeneTest.java.
static Test org.jgap.impl.DoubleGeneTest.suite () [inline], [static]
Definition at line 31 of file DoubleGeneTest.java.
void org.jgap.impl.DoubleGeneTest.testApplyMutation_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 713 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.impl.DoubleGene.doubleValue().
void org.jgap.impl.DoubleGeneTest.testApplyMutation_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 726 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.DELTA.
void org.jgap.impl.DoubleGeneTest.testApplyMutation_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 740 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.DELTA.
void org.jgap.impl.DoubleGeneTest.testApplyMutation_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 754 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.DELTA.
void org.jgap.impl.DoubleGeneTest.testApplyMutation_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 768 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.DELTA.
void org.jgap.impl.DoubleGeneTest.testApplyMutation_5 () throws Exception [inline]
Exceed bounds for applyMutation to force randomized setting of allele.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 783 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.DELTA.
void org.jgap.impl.DoubleGeneTest.testApplyMutation_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 797 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.impl.DoubleGene.doubleValue().
void org.jgap.impl.DoubleGeneTest.testApplyMutation_7 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 810 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testBounds_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 909 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, org.jgap.impl.DoubleGene.getLowerBound(), and org.jgap.impl.DoubleGene.getUpperBound().
void org.jgap.impl.DoubleGeneTest.testBounds_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 922 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, org.jgap.impl.DoubleGene.getLowerBound(), and org.jgap.impl.DoubleGene.getUpperBound().
void org.jgap.impl.DoubleGeneTest.testCleanup_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 549 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testCompareToNative_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 638 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.DoubleGeneTest.testCompareToNative_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 653 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.DoubleGeneTest.testCompareToNative_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 668 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.DoubleGeneTest.testCompareToNative_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 683 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.DoubleGeneTest.testCompareToNative_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 698 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.DoubleGeneTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 41 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testConstruct_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 54 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testConstruct_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 65 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testConstruct_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 77 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testDoubleValue_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 276 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.impl.DoubleGene.doubleValue().
void org.jgap.impl.DoubleGeneTest.testDoubleValue_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 288 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.impl.DoubleGene.doubleValue().
void org.jgap.impl.DoubleGeneTest.testEquals_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 161 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testEquals_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 174 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testEquals_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 185 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testEquals_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 196 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testEquals_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 207 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testEquals_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 220 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testEquals_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 233 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testEquals_7 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 246 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testEquals_8 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 260 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testGetAllele_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 125 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.DoubleGeneTest.testGetAllele_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 137 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.DoubleGeneTest.testGetAllele_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 149 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.DoubleGeneTest.testHashCode_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 847 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.DoubleGene.hashCode().
void org.jgap.impl.DoubleGeneTest.testHashCode_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 859 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.DoubleGene.hashCode().
void org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.4.4
Definition at line 943 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.4.4
Definition at line 960 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.4.4
Definition at line 978 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.4.4
Definition at line 995 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.4.4
Definition at line 1012 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.DoubleGeneTest.testNewGene_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 411 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseGene.getConstraintChecker(), org.jgap.BaseGene.newGene(), and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.DoubleGeneTest.testPersistentRepresentation_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 436 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testPersistentRepresentation_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 452 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testPersistentRepresentation_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 463 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testPersistentRepresentation_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 480 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testPersistentRepresentation_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 503 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testPersistentRepresentation_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 526 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testSetAllele_0 () throws Exception [inline]
Set allele to null, no exception should occur.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 307 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testSetAllele_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 318 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testSetAllele_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 335 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testSetAllele_3 () throws Exception [inline]
Call setAllele with need of mapping to bounds.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 355 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DoubleGeneTest.testSetAllele_4 () throws Exception [inline]
Call setAllele with need of mapping to bounds.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 369 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.impl.DoubleGene.doubleValue().
void org.jgap.impl.DoubleGeneTest.testSetAllele_5 () throws Exception [inline]
Call setAllele with need of mapping to bounds.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 384 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.impl.DoubleGene.doubleValue().
void org.jgap.impl.DoubleGeneTest.testSetAllele_6 () throws Exception [inline]
Call setAllele with need of mapping to bounds.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 399 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.impl.DoubleGene.doubleValue().
void org.jgap.impl.DoubleGeneTest.testSetConstraintChecker_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 828 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getConstraintChecker().
void org.jgap.impl.DoubleGeneTest.testSetEnergy_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 878 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getEnergy().
void org.jgap.impl.DoubleGeneTest.testSetEnergy_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 890 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getEnergy().
void org.jgap.impl.DoubleGeneTest.testSetToRandomValue_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 563 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.DoubleGeneTest.testSetToRandomValue_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 576 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.DoubleGeneTest.testSetToRandomValue_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Todo
Todo test needed any longer?
Definition at line 590 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.DoubleGeneTest.testSetToRandomValue_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 606 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.DoubleGene.doubleValue().
void org.jgap.impl.DoubleGeneTest.testSetToRandomValue_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 622 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.DoubleGene.doubleValue().
void org.jgap.impl.DoubleGeneTest.testToString_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 89 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.toString().
void org.jgap.impl.DoubleGeneTest.testToString_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 101 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.toString().
void org.jgap.impl.DoubleGeneTest.testToString_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 114 of file DoubleGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.toString().
Member Data Documentation
final String org.jgap.impl.DoubleGeneTest.CVS_REVISION = `$Revision: 1.42 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file DoubleGeneTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/DoubleGeneTest.java