org.jgap.gp.function.GreaterThan Class Reference
Public Member Functions
GreaterThan (final GPConfiguration a_conf, Class a_type) throws InvalidConfigurationException
GreaterThan (final GPConfiguration a_conf, Class a_type, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException
String toString ()
String getName ()
boolean execute_boolean (ProgramChromosome c, int n, Object[] args)
Class getChildType (IGPProgram a_ind, int a_index)
Object clone ()
boolean equals (Object a_other)
Private Attributes
Class m_type
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.5 $`
Additional Inherited Members
Detailed Description
The Greater Than (x > y) operation.
Author
Klaus Meffert
Since
3.2
Definition at line 24 of file GreaterThan.java.
Constructor & Destructor Documentation
org.jgap.gp.function.GreaterThan.GreaterThan (final GPConfiguration a_conf, Class a_type) throws InvalidConfigurationException [inline]
Definition at line 31 of file GreaterThan.java.
Referenced by org.jgap.gp.function.GreaterThan.clone(), and org.jgap.gp.function.GreaterThan.equals().
org.jgap.gp.function.GreaterThan.GreaterThan (final GPConfiguration a_conf, Class a_type, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException [inline]
Definition at line 36 of file GreaterThan.java.
References org.jgap.gp.CommandGene.BooleanClass, and org.jgap.gp.function.GreaterThan.m_type.
Member Function Documentation
Object org.jgap.gp.function.GreaterThan.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 93 of file GreaterThan.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getSubChildTypes(), org.jgap.gp.CommandGene.getSubReturnType(), org.jgap.gp.function.GreaterThan.GreaterThan(), and org.jgap.gp.function.GreaterThan.m_type.
boolean org.jgap.gp.function.GreaterThan.equals (Object a_other) [inline]
The equals method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Frank Pape
Since
3.4.3
Definition at line 112 of file GreaterThan.java.
References org.jgap.gp.function.GreaterThan.GreaterThan(), and org.jgap.gp.function.GreaterThan.m_type.
boolean org.jgap.gp.function.GreaterThan.execute_boolean (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 57 of file GreaterThan.java.
References org.jgap.gp.CommandGene.BooleanClass, org.jgap.gp.CommandGene.DoubleClass, org.jgap.gp.CommandGene.FloatClass, org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.CommandGene.LongClass, and org.jgap.gp.function.GreaterThan.m_type.
Class org.jgap.gp.function.GreaterThan.getChildType (IGPProgram a_ind, int a_index) [inline]
Definition at line 81 of file GreaterThan.java.
References org.jgap.gp.function.GreaterThan.m_type.
String org.jgap.gp.function.GreaterThan.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 53 of file GreaterThan.java.
String org.jgap.gp.function.GreaterThan.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 43 of file GreaterThan.java.
Member Data Documentation
final String org.jgap.gp.function.GreaterThan.CVS_REVISION = `$Revision: 1.5 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file GreaterThan.java.
Class org.jgap.gp.function.GreaterThan.m_type [private]
Definition at line 29 of file GreaterThan.java.
Referenced by org.jgap.gp.function.GreaterThan.clone(), org.jgap.gp.function.GreaterThan.equals(), org.jgap.gp.function.GreaterThan.execute_boolean(), org.jgap.gp.function.GreaterThan.getChildType(), and org.jgap.gp.function.GreaterThan.GreaterThan().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/GreaterThan.java