examples.gp.tictactoe.PutStone Class Reference
Public Member Functions
PutStone (final GPConfiguration a_conf, Board a_board, int a_color) throws InvalidConfigurationException
PutStone (final GPConfiguration a_conf, Board a_board, int a_color, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException
String toString ()
void execute_void (ProgramChromosome c, int n, Object[] args)
Class getChildType (IGPProgram a_ind, int a_chromNum)
Object clone ()
Protected Member Functions
void check (ProgramChromosome a_program)
Private Attributes
Board m_board
int m_color
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.5 $`
Additional Inherited Members
Detailed Description
Puts a stone on a board. Accepts two parameters, representing X and Y coordinates on the board.
Author
Klaus Meffert
Since
3.2
Definition at line 24 of file PutStone.java.
Constructor & Destructor Documentation
examples.gp.tictactoe.PutStone.PutStone (final GPConfiguration a_conf, Board a_board, int a_color) throws InvalidConfigurationException [inline]
Definition at line 33 of file PutStone.java.
Referenced by examples.gp.tictactoe.PutStone.clone().
examples.gp.tictactoe.PutStone.PutStone (final GPConfiguration a_conf, Board a_board, int a_color, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException [inline]
Definition at line 38 of file PutStone.java.
References examples.gp.tictactoe.PutStone.m_board, examples.gp.tictactoe.PutStone.m_color, and org.jgap.gp.CommandGene.VoidClass.
Member Function Documentation
void examples.gp.tictactoe.PutStone.check (ProgramChromosome a_program) [inline], [protected]
Definition at line 70 of file PutStone.java.
References examples.gp.tictactoe.Board.getLastColor(), examples.gp.tictactoe.PutStone.m_board, and examples.gp.tictactoe.PutStone.m_color.
Referenced by examples.gp.tictactoe.PutStone.execute_void().
Object examples.gp.tictactoe.PutStone.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 100 of file PutStone.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getSubChildTypes(), org.jgap.gp.CommandGene.getSubReturnType(), examples.gp.tictactoe.PutStone.m_board, examples.gp.tictactoe.PutStone.m_color, and examples.gp.tictactoe.PutStone.PutStone().
void examples.gp.tictactoe.PutStone.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 50 of file PutStone.java.
References examples.gp.tictactoe.PutStone.check(), and examples.gp.tictactoe.PutStone.m_color.
Class examples.gp.tictactoe.PutStone.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Determines which type a specific child of this command has.
Parameters
a_ind ignored here
a_chromNum index of child
Returns
type of the a_chromNum'th child
Author
Klaus Meffert
Since
3.2
Definition at line 86 of file PutStone.java.
References org.jgap.gp.CommandGene.IntegerClass.
String examples.gp.tictactoe.PutStone.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 46 of file PutStone.java.
Member Data Documentation
final String examples.gp.tictactoe.PutStone.CVS_REVISION = `$Revision: 1.5 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file PutStone.java.
Board examples.gp.tictactoe.PutStone.m_board [private]
Definition at line 29 of file PutStone.java.
Referenced by examples.gp.tictactoe.PutStone.check(), examples.gp.tictactoe.PutStone.clone(), and examples.gp.tictactoe.PutStone.PutStone().
int examples.gp.tictactoe.PutStone.m_color [private]
Definition at line 31 of file PutStone.java.
Referenced by examples.gp.tictactoe.PutStone.check(), examples.gp.tictactoe.PutStone.clone(), examples.gp.tictactoe.PutStone.execute_void(), and examples.gp.tictactoe.PutStone.PutStone().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/tictactoe/PutStone.java