org.jgap.util.NumberKitTest Class Reference
Public Member Functions
NumberKitTest ()
void testNiceDecimalNumber_0 () throws Exception
void testNiceDecimalNumber_1 () throws Exception
void testNiceDecimalNumber_2 () throws Exception
void testNiceDecimalNumber_3 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.1 $`
Additional Inherited Members
Detailed Description
Tests the NumberKit class.
Author
Klaus Meffert
Since
3.3.3
Definition at line 22 of file NumberKitTest.java.
Constructor & Destructor Documentation
org.jgap.util.NumberKitTest.NumberKitTest () [inline]
Definition at line 31 of file NumberKitTest.java.
Member Function Documentation
static Test org.jgap.util.NumberKitTest.suite () [inline], [static]
Definition at line 27 of file NumberKitTest.java.
void org.jgap.util.NumberKitTest.testNiceDecimalNumber_0 () throws Exception [inline]
Todo
Todo this is not an optimal result
Definition at line 34 of file NumberKitTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.util.NumberKitTest.testNiceDecimalNumber_1 () throws Exception [inline]
Definition at line 41 of file NumberKitTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.util.NumberKitTest.testNiceDecimalNumber_2 () throws Exception [inline]
Definition at line 51 of file NumberKitTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.util.NumberKitTest.testNiceDecimalNumber_3 () throws Exception [inline]
Definition at line 58 of file NumberKitTest.java.
References org.jgap.JGAPTestCase.assertEquals().
Member Data Documentation
final String org.jgap.util.NumberKitTest.CVS_REVISION = `$Revision: 1.1 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file NumberKitTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/util/NumberKitTest.java