org.jgap.gp.function.ExchangeMemory Class Reference
Public Member Functions
ExchangeMemory (final GPConfiguration a_conf, String a_firstStorageName, String a_secondStorageName) throws InvalidConfigurationException
String toString ()
String getName ()
void execute_void (ProgramChromosome c, int n, Object[] args)
boolean isAffectGlobalState ()
boolean isValid (ProgramChromosome a_program)
Class getChildType (IGPProgram a_ind, int a_chromNum)
int compareTo (Object a_other)
boolean equals (Object a_other)
Object clone ()
Private Attributes
String m_sourceStorageName
String m_targetStorageName
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
Exchanges the values of two memory cells.
Author
Klaus Meffert
Since
3.2
Definition at line 24 of file ExchangeMemory.java.
Constructor & Destructor Documentation
org.jgap.gp.function.ExchangeMemory.ExchangeMemory (final GPConfiguration a_conf, String a_firstStorageName, String a_secondStorageName) throws InvalidConfigurationException [inline]
Definition at line 37 of file ExchangeMemory.java.
References org.jgap.gp.function.ExchangeMemory.m_sourceStorageName, org.jgap.gp.function.ExchangeMemory.m_targetStorageName, and org.jgap.gp.CommandGene.VoidClass.
Referenced by org.jgap.gp.function.ExchangeMemory.clone(), org.jgap.gp.function.ExchangeMemory.compareTo(), and org.jgap.gp.function.ExchangeMemory.equals().
Member Function Documentation
Object org.jgap.gp.function.ExchangeMemory.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 164 of file ExchangeMemory.java.
References org.jgap.gp.function.ExchangeMemory.ExchangeMemory(), org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.function.ExchangeMemory.m_sourceStorageName, and org.jgap.gp.function.ExchangeMemory.m_targetStorageName.
int org.jgap.gp.function.ExchangeMemory.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.2
Definition at line 117 of file ExchangeMemory.java.
References org.jgap.gp.function.ExchangeMemory.ExchangeMemory(), org.jgap.gp.function.ExchangeMemory.m_sourceStorageName, and org.jgap.gp.function.ExchangeMemory.m_targetStorageName.
boolean org.jgap.gp.function.ExchangeMemory.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Klaus Meffert
Since
3.2
Definition at line 139 of file ExchangeMemory.java.
References org.jgap.gp.function.ExchangeMemory.ExchangeMemory(), org.jgap.gp.function.ExchangeMemory.m_sourceStorageName, and org.jgap.gp.function.ExchangeMemory.m_targetStorageName.
void org.jgap.gp.function.ExchangeMemory.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 76 of file ExchangeMemory.java.
References org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.function.ExchangeMemory.m_sourceStorageName, and org.jgap.gp.function.ExchangeMemory.m_targetStorageName.
Class org.jgap.gp.function.ExchangeMemory.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Definition at line 104 of file ExchangeMemory.java.
String org.jgap.gp.function.ExchangeMemory.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 72 of file ExchangeMemory.java.
boolean org.jgap.gp.function.ExchangeMemory.isAffectGlobalState () [inline]
Todo
Todo subclass from new abstract class MemoryCommand?
Definition at line 95 of file ExchangeMemory.java.
boolean org.jgap.gp.function.ExchangeMemory.isValid (ProgramChromosome a_program) [inline]
Definition at line 100 of file ExchangeMemory.java.
String org.jgap.gp.function.ExchangeMemory.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 58 of file ExchangeMemory.java.
References org.jgap.gp.function.ExchangeMemory.m_sourceStorageName, and org.jgap.gp.function.ExchangeMemory.m_targetStorageName.
Member Data Documentation
final String org.jgap.gp.function.ExchangeMemory.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file ExchangeMemory.java.
String org.jgap.gp.function.ExchangeMemory.m_sourceStorageName [private]
Symbolic name of the storage. Must correspond with a chosen name for ReadTerminalCommand.
Definition at line 33 of file ExchangeMemory.java.
Referenced by org.jgap.gp.function.ExchangeMemory.clone(), org.jgap.gp.function.ExchangeMemory.compareTo(), org.jgap.gp.function.ExchangeMemory.equals(), org.jgap.gp.function.ExchangeMemory.ExchangeMemory(), org.jgap.gp.function.ExchangeMemory.execute_void(), and org.jgap.gp.function.ExchangeMemory.toString().
String org.jgap.gp.function.ExchangeMemory.m_targetStorageName [private]
Definition at line 35 of file ExchangeMemory.java.
Referenced by org.jgap.gp.function.ExchangeMemory.clone(), org.jgap.gp.function.ExchangeMemory.compareTo(), org.jgap.gp.function.ExchangeMemory.equals(), org.jgap.gp.function.ExchangeMemory.ExchangeMemory(), org.jgap.gp.function.ExchangeMemory.execute_void(), and org.jgap.gp.function.ExchangeMemory.toString().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/ExchangeMemory.java