org.jgap.gp.function.Loop Class Reference
Public Member Functions
Loop (final GPConfiguration a_conf, Class a_typeVar, int a_count) throws InvalidConfigurationException
Loop (final GPConfiguration a_conf, Class a_typeVar, int a_count, int a_subReturnType, int a_subChildType) throws InvalidConfigurationException
String toString ()
String getName ()
void execute_void (ProgramChromosome c, int n, Object[] args)
boolean isValid (ProgramChromosome a_program)
Class getChildType (IGPProgram a_ind, int a_chromNum)
int compareTo (Object a_other)
boolean equals (Object a_other)
Object clone ()
Private Attributes
Class m_typeVar
int m_count
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.8 $`
Additional Inherited Members
Detailed Description
A loop that executes a given number of times.
Author
Klaus Meffert
Since
3.01
Definition at line 24 of file Loop.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Loop.Loop (final GPConfiguration a_conf, Class a_typeVar, int a_count) throws InvalidConfigurationException [inline]
Constructor.
Parameters
a_conf the configuration to use
a_typeVar Class of the loop counter terminal (e.g. IntegerClass)
a_count the number of loops to perform
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.01
Definition at line 44 of file Loop.java.
Referenced by org.jgap.gp.function.Loop.clone(), org.jgap.gp.function.Loop.compareTo(), and org.jgap.gp.function.Loop.equals().
org.jgap.gp.function.Loop.Loop (final GPConfiguration a_conf, Class a_typeVar, int a_count, int a_subReturnType, int a_subChildType) throws InvalidConfigurationException [inline]
Definition at line 49 of file Loop.java.
References org.jgap.gp.function.Loop.m_count, org.jgap.gp.function.Loop.m_typeVar, and org.jgap.gp.CommandGene.VoidClass.
Member Function Documentation
Object org.jgap.gp.function.Loop.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 137 of file Loop.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getSubChildType(), org.jgap.gp.CommandGene.getSubReturnType(), org.jgap.gp.function.Loop.Loop(), org.jgap.gp.function.Loop.m_count, and org.jgap.gp.function.Loop.m_typeVar.
int org.jgap.gp.function.Loop.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.01
Definition at line 96 of file Loop.java.
References org.jgap.gp.function.Loop.Loop(), org.jgap.gp.function.Loop.m_count, and org.jgap.gp.function.Loop.m_typeVar.
boolean org.jgap.gp.function.Loop.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Klaus Meffert
Since
3.01
Definition at line 117 of file Loop.java.
References org.jgap.gp.function.Loop.Loop(), org.jgap.gp.function.Loop.m_count, and org.jgap.gp.function.Loop.m_typeVar.
void org.jgap.gp.function.Loop.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 71 of file Loop.java.
References org.jgap.gp.function.Loop.m_count.
Class org.jgap.gp.function.Loop.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Definition at line 83 of file Loop.java.
References org.jgap.gp.CommandGene.VoidClass.
String org.jgap.gp.function.Loop.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 67 of file Loop.java.
boolean org.jgap.gp.function.Loop.isValid (ProgramChromosome a_program) [inline]
Definition at line 79 of file Loop.java.
String org.jgap.gp.function.Loop.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 57 of file Loop.java.
References org.jgap.gp.function.Loop.m_count.
Member Data Documentation
final String org.jgap.gp.function.Loop.CVS_REVISION = `$Revision: 1.8 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file Loop.java.
int org.jgap.gp.function.Loop.m_count [private]
Definition at line 31 of file Loop.java.
Referenced by org.jgap.gp.function.Loop.clone(), org.jgap.gp.function.Loop.compareTo(), org.jgap.gp.function.Loop.equals(), org.jgap.gp.function.Loop.execute_void(), org.jgap.gp.function.Loop.Loop(), and org.jgap.gp.function.Loop.toString().
Class org.jgap.gp.function.Loop.m_typeVar [private]
Definition at line 29 of file Loop.java.
Referenced by org.jgap.gp.function.Loop.clone(), org.jgap.gp.function.Loop.compareTo(), org.jgap.gp.function.Loop.equals(), and org.jgap.gp.function.Loop.Loop().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Loop.java