org.jgap.distr.Problem Class Reference
Public Member Functions
Problem ()
Problem (FitnessFunction a_fitFunc, int a_popSize, Chromosome[] a_initialChroms) throws IllegalArgumentException
void setID (Object a_ID)
Object getID ()
int getPopulationSize ()
FitnessFunction getFitnessFunction ()
Chromosome[] getChromosomes ()
Private Attributes
FitnessFunction m_fitFunc
int m_populationSize
Object m_ID
Chromosome[] m_initialChroms
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Detailed Description
A problem to be solved by a worker.
Author
Klaus Meffert
Since
3.0
Definition at line 20 of file Problem.java.
Constructor & Destructor Documentation
org.jgap.distr.Problem.Problem () [inline]
Definition at line 32 of file Problem.java.
org.jgap.distr.Problem.Problem (FitnessFunction a_fitFunc, int a_popSize, Chromosome[] a_initialChroms) throws IllegalArgumentException [inline]
Parameters
a_fitFunc the fitness function to use
a_popSize the population size to use by/suggest to the worker
a_initialChroms initial chromosomes to use (e.g. from previous evolutions), or empty
Exceptions
IllegalArgumentException
Author
Klaus Meffert
Since
3.0
Definition at line 45 of file Problem.java.
References org.jgap.distr.Problem.m_fitFunc, org.jgap.distr.Problem.m_initialChroms, and org.jgap.distr.Problem.m_populationSize.
Member Function Documentation
Chromosome [] org.jgap.distr.Problem.getChromosomes () [inline]
Returns
Chromosome[] initial chromosomes to use, may be empty
Author
Klaus Meffert
Since
3.0
Definition at line 104 of file Problem.java.
References org.jgap.distr.Problem.m_initialChroms.
Referenced by org.jgap.distr.ProblemTest.testConstruct_3().
FitnessFunction org.jgap.distr.Problem.getFitnessFunction () [inline]
Returns
FitnessFunction to use
Author
Klaus Meffert
Since
3.0
Definition at line 94 of file Problem.java.
References org.jgap.distr.Problem.m_fitFunc.
Referenced by org.jgap.distr.ProblemTest.testConstruct_3().
Object org.jgap.distr.Problem.getID () [inline]
Returns
internal ID of the problem, should be unique
Author
Klaus Meffert
Since
3.0
Definition at line 74 of file Problem.java.
References org.jgap.distr.Problem.m_ID.
Referenced by org.jgap.distr.ProblemTest.testGetID_0().
int org.jgap.distr.Problem.getPopulationSize () [inline]
Returns
population size to use
Author
Klaus Meffert
Since
3.0
Definition at line 84 of file Problem.java.
References org.jgap.distr.Problem.m_populationSize.
Referenced by org.jgap.distr.ProblemTest.testConstruct_3().
void org.jgap.distr.Problem.setID (Object a_ID) [inline]
Parameters
a_ID internal ID of the problem, should be unique
Author
Klaus Meffert
Since
3.0
Definition at line 64 of file Problem.java.
References org.jgap.distr.Problem.m_ID.
Member Data Documentation
final String org.jgap.distr.Problem.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 22 of file Problem.java.
FitnessFunction org.jgap.distr.Problem.m_fitFunc [private]
Definition at line 24 of file Problem.java.
Referenced by org.jgap.distr.Problem.getFitnessFunction(), and org.jgap.distr.Problem.Problem().
Object org.jgap.distr.Problem.m_ID [private]
Definition at line 28 of file Problem.java.
Referenced by org.jgap.distr.Problem.getID(), and org.jgap.distr.Problem.setID().
Chromosome [] org.jgap.distr.Problem.m_initialChroms [private]
Definition at line 30 of file Problem.java.
Referenced by org.jgap.distr.Problem.getChromosomes(), and org.jgap.distr.Problem.Problem().
int org.jgap.distr.Problem.m_populationSize [private]
Definition at line 26 of file Problem.java.
Referenced by org.jgap.distr.Problem.getPopulationSize(), and org.jgap.distr.Problem.Problem().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/distr/Problem.java