org.jgap.impl.Pool Class Reference
Public Member Functions
Pool ()
synchronized Object acquirePooledObject ()
synchronized void releaseObject (final Object a_objectToPool)
synchronized void releaseAllObjects (final Collection a_objectsToPool)
synchronized int size ()
synchronized void clear ()
Private Attributes
List m_pooledObjects
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.9 $`
Detailed Description
A simple, generic pool class that can be used to pool any kind of object. Objects can be released to this pool, either individually or as a Collection, and then later acquired again. It is not necessary for an object to have been originally acquired from the pool in order for it to be released to the pool. If there are no objects present in the pool, an attempt to acquire one will return null. The number of objects available in the pool can be determined with the size() method. Finally, it should be noted that the pool does not attempt to perform any kind of cleanup or re-initialization on the objects to restore them to some clean state when they are released to the pool; it's up to the user to reset any necessary state in the object prior to the release call (or just after the acquire call).
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 32 of file Pool.java.
Constructor & Destructor Documentation
org.jgap.impl.Pool.Pool () [inline]
Constructor.
Author
Neil Rotstan
Since
1.0
Definition at line 48 of file Pool.java.
References org.jgap.impl.Pool.m_pooledObjects.
Member Function Documentation
synchronized Object org.jgap.impl.Pool.acquirePooledObject () [inline]
Attempts to acquire an Object instance from the pool. It should be noted that no cleanup or re-initialization occurs on these objects, so it's up to the caller to reset the state of the returned Object if that's desirable.
Returns
an Object instance from the pool or null if no Object instances are available in the pool
Author
Neil Rotstan
Since
1.0
Definition at line 64 of file Pool.java.
References org.jgap.impl.Pool.m_pooledObjects.
Referenced by org.jgap.impl.WeightedRouletteSelector.add(), and org.jgap.impl.PoolTest.testAcquirePooledObject_0().
synchronized void org.jgap.impl.Pool.clear () [inline]
Empties out this pool of all objects.
Author
Neil Rotstan
Since
1.0
Definition at line 125 of file Pool.java.
synchronized void org.jgap.impl.Pool.releaseAllObjects (final Collection a_objectsToPool) [inline]
Releases a Collection of objects to the pool. It's not required that the objects in the Collection originated from the pool - any objects can be released to it.
Parameters
a_objectsToPool the Collection of objects to release into the pool
Author
Neil Rotstan
Since
1.0
Definition at line 101 of file Pool.java.
synchronized void org.jgap.impl.Pool.releaseObject (final Object a_objectToPool) [inline]
Releases an object to the pool. It's not required that the Object originated from the pool - any Object can be released to it.
Parameters
a_objectToPool the Object instance to be released into the pool
Author
Neil Rotstan
Since
1.0
Definition at line 87 of file Pool.java.
synchronized int org.jgap.impl.Pool.size () [inline]
Retrieves the number of objects currently available in this pool.
Returns
the number of objects in this pool
Author
Neil Rotstan
Since
1.0
Definition at line 115 of file Pool.java.
Referenced by org.jgap.impl.PoolTest.testAcquirePooledObject_0(), org.jgap.impl.PoolTest.testClear_0(), org.jgap.impl.PoolTest.testReleaseAllObjects_0(), org.jgap.impl.PoolTest.testReleaseAllObjects_1(), and org.jgap.impl.PoolTest.testSize_0().
Member Data Documentation
final String org.jgap.impl.Pool.CVS_REVISION = `$Revision: 1.9 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 35 of file Pool.java.
List org.jgap.impl.Pool.m_pooledObjects [private]
The objects currently in the pool.
Definition at line 40 of file Pool.java.
Referenced by org.jgap.impl.Pool.acquirePooledObject(), and org.jgap.impl.Pool.Pool().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/Pool.java