org.jgap.impl.NumberGeneTest Class Reference
Classes
class NumberGeneImpl
Public Member Functions
void testConstruct_0 () throws Exception
void testToString_0 () throws Exception
void testToString_1 () throws Exception
void testGetAllele_0 () throws Exception
void testGetAllele_1 () throws Exception
void testGetAllele_2 () throws Exception
void testHashCode_0 () throws Exception
void testHashCode_1 () throws Exception
void testHashCode_2 () throws Exception
void testEquals_0 () throws Exception
void testEquals_1 () throws Exception
void testEquals_2 () throws Exception
void testEquals_3 () throws Exception
void testEquals_4 () throws Exception
void testEquals_5 () throws Exception
void testSetAllele_0 () throws Exception
void testSetAllele_1 () throws Exception
void testSetAllele_2 () throws Exception
void testSetAllele_3 () throws Exception
void testNewGene_0 () throws Exception
void testCompareTo_0 () throws Exception
void testCompareTo_1 () throws Exception
void testCompareTo_2 () throws Exception
void testCompareTo_3 () throws Exception
void testSetConstraintChecker_0 () throws Exception
void testSetEnergy_0 () throws Exception
void testSetEnergy_1 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.27 $`
Additional Inherited Members
Detailed Description
Tests the (abstract) NumberGene class.
Author
Klaus Meffert
Since
1.1
Definition at line 24 of file NumberGeneTest.java.
Member Function Documentation
static Test org.jgap.impl.NumberGeneTest.suite () [inline], [static]
Definition at line 29 of file NumberGeneTest.java.
void org.jgap.impl.NumberGeneTest.testCompareTo_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 342 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testCompareTo_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 360 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testCompareTo_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 380 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testCompareTo_3 () throws Exception [inline]
Using application data.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 402 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 40 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testEquals_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 164 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testEquals_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 178 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testEquals_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 190 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testEquals_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 202 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testEquals_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 214 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testEquals_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 228 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testGetAllele_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 82 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.NumberGeneTest.testGetAllele_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 95 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.NumberGeneTest.testGetAllele_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 108 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.NumberGeneTest.testHashCode_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 121 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testHashCode_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 134 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testHashCode_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 149 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testNewGene_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 319 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.NumberGeneTest.testSetAllele_0 () throws Exception [inline]
Set Allele to null, no exception should occur
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 245 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testSetAllele_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 257 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testSetAllele_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 275 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testSetAllele_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 294 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.NumberGeneTest.testSetConstraintChecker_0 () throws Exception [inline]
Definition at line 420 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getConstraintChecker().
void org.jgap.impl.NumberGeneTest.testSetEnergy_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 439 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getEnergy().
void org.jgap.impl.NumberGeneTest.testSetEnergy_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 451 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getEnergy().
void org.jgap.impl.NumberGeneTest.testToString_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 53 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseGene.S_APPLICATION_DATA, and org.jgap.Gene.toString().
void org.jgap.impl.NumberGeneTest.testToString_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 67 of file NumberGeneTest.java.
References org.jgap.JGAPTestCase.conf.
Member Data Documentation
final String org.jgap.impl.NumberGeneTest.CVS_REVISION = `$Revision: 1.27 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file NumberGeneTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/NumberGeneTest.java