org.jgap.gp.function.Round Class Reference
Public Member Functions
Round (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException
String toString ()
String getName ()
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
Returns the closest value to the argument.
Author
Klaus Meffert
Since
3.3.4
Definition at line 23 of file Round.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Round.Round (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 28 of file Round.java.
Referenced by org.jgap.gp.function.Round.clone().
Member Function Documentation
Object org.jgap.gp.function.Round.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 65 of file Round.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.function.Round.Round().
double org.jgap.gp.function.Round.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 52 of file Round.java.
float org.jgap.gp.function.Round.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 47 of file Round.java.
String org.jgap.gp.function.Round.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.3.4
Definition at line 43 of file Round.java.
String org.jgap.gp.function.Round.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 33 of file Round.java.
Member Data Documentation
final String org.jgap.gp.function.Round.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file Round.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Round.java