org.jgap.impl.fitness.TruthTableFitnessFunction Class Reference
Public Member Functions
TruthTableFitnessFunction ()
TruthTableFitnessFunction (Configuration a_conf)
TruthTableFitnessFunction (Configuration a_conf, final Map a_truthTable)
void setTruthTable (final Map a_truthTable)
Map getTruthTable ()
double calcFitness (final Map a_actualInputOutput)
Configuration getConfiguration ()
Static Public Attributes
static final int MAX_FITNESS = 9999999
static final int WORST = MAX_FITNESS / RELATION_FITNESS
Protected Member Functions
abstract double evaluate (IChromosome a_chromosome)
Private Attributes
Map m_truthTable
Configuration m_conf
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.6 $`
static final int RELATION_FITNESS = 100
Detailed Description
Fitness Function relying on a truth table. To use this class, just implement a subclass of it, register the current truth table and implement the evaluate method in a way that you can call calcFitness with the required (parameter (given values: encoded with the chromosome). If the truth table is dynamic just register it in evaluate, otherwise do it after construction of this fitness function.
Author
Klaus Meffert
Since
2.4
Definition at line 27 of file TruthTableFitnessFunction.java.
Constructor & Destructor Documentation
org.jgap.impl.fitness.TruthTableFitnessFunction.TruthTableFitnessFunction () [inline]
Only use for dynamic instantiation as configuration retrieved from static setting.
Author
Klaus Meffert
Since
2.4
Definition at line 51 of file TruthTableFitnessFunction.java.
org.jgap.impl.fitness.TruthTableFitnessFunction.TruthTableFitnessFunction (Configuration a_conf) [inline]
Constructor without registering a truth table. Use this constructor if the truth table is not fix over generations and needs to be set in method evaluate.
Parameters
a_conf the configuration to use
Author
Klaus Meffert
Since
3.01
Definition at line 65 of file TruthTableFitnessFunction.java.
References org.jgap.impl.fitness.TruthTableFitnessFunction.m_conf.
org.jgap.impl.fitness.TruthTableFitnessFunction.TruthTableFitnessFunction (Configuration a_conf, final Map a_truthTable) [inline]
Constructor for registering a truth table. Use this constructor if the truth table is fix over generations.
Parameters
a_conf the configuration to use
a_truthTable table of input/output pairs for feeding the formula and determining the fitness value thru delta computation
Author
Klaus Meffert
Since
3.1
Definition at line 81 of file TruthTableFitnessFunction.java.
References org.jgap.impl.fitness.TruthTableFitnessFunction.setTruthTable().
Member Function Documentation
double org.jgap.impl.fitness.TruthTableFitnessFunction.calcFitness (final Map a_actualInputOutput) [inline]
Fitness value calculation for a given table of input/output tupels and a truth-table (also given as list of input/output tupels)
Parameters
a_actualInputOutput table of actual input/output pairs
Returns
delta between current values and given truth table
Author
Klaus Meffert
Since
2.4
Todo
Todo consider length of formula (i.e. number of terms, e.g.) for fitness calculation
Definition at line 115 of file TruthTableFitnessFunction.java.
References org.jgap.impl.fitness.TruthTableFitnessFunction.getTruthTable().
abstract double org.jgap.impl.fitness.TruthTableFitnessFunction.evaluate (IChromosome a_chromosome) [protected], [pure virtual]
Implementation of the evaluate method from class FitnessFunction. Calculates the fitness of a given Chromosome in a determined way.
Parameters
a_chromosome the Chromosome to be evaluated
Returns
positive integer value representing the fitness of the Chromosome
Author
Klaus Meffert
Since
2.4
Implements org.jgap.FitnessFunction.
Implemented in org.jgap.impl.fitness.TruthTableFitnessFunctionTest.TruthTableFitnessFunctionImpl.
Configuration org.jgap.impl.fitness.TruthTableFitnessFunction.getConfiguration () [inline]
Returns
the Configuration object set
Author
Klaus Meffert
Since
3.1
Definition at line 155 of file TruthTableFitnessFunction.java.
References org.jgap.impl.fitness.TruthTableFitnessFunction.m_conf.
Map org.jgap.impl.fitness.TruthTableFitnessFunction.getTruthTable () [inline]
Definition at line 90 of file TruthTableFitnessFunction.java.
References org.jgap.impl.fitness.TruthTableFitnessFunction.m_truthTable.
Referenced by org.jgap.impl.fitness.TruthTableFitnessFunction.calcFitness().
void org.jgap.impl.fitness.TruthTableFitnessFunction.setTruthTable (final Map a_truthTable) [inline]
Definition at line 86 of file TruthTableFitnessFunction.java.
References org.jgap.impl.fitness.TruthTableFitnessFunction.m_truthTable.
Referenced by org.jgap.impl.fitness.TruthTableFitnessFunction.TruthTableFitnessFunction().
Member Data Documentation
final String org.jgap.impl.fitness.TruthTableFitnessFunction.CVS_REVISION = `$Revision: 1.6 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 30 of file TruthTableFitnessFunction.java.
Configuration org.jgap.impl.fitness.TruthTableFitnessFunction.m_conf [private]
Definition at line 42 of file TruthTableFitnessFunction.java.
Referenced by org.jgap.impl.fitness.TruthTableFitnessFunction.getConfiguration(), and org.jgap.impl.fitness.TruthTableFitnessFunction.TruthTableFitnessFunction().
Map org.jgap.impl.fitness.TruthTableFitnessFunction.m_truthTable [private]
Definition at line 32 of file TruthTableFitnessFunction.java.
Referenced by org.jgap.impl.fitness.TruthTableFitnessFunction.getTruthTable(), and org.jgap.impl.fitness.TruthTableFitnessFunction.setTruthTable().
final int org.jgap.impl.fitness.TruthTableFitnessFunction.MAX_FITNESS = 9999999 [static]
Definition at line 36 of file TruthTableFitnessFunction.java.
final int org.jgap.impl.fitness.TruthTableFitnessFunction.RELATION_FITNESS = 100 [static], [private]
Definition at line 38 of file TruthTableFitnessFunction.java.
final int org.jgap.impl.fitness.TruthTableFitnessFunction.WORST = MAX_FITNESS / RELATION_FITNESS [static]
Definition at line 40 of file TruthTableFitnessFunction.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/fitness/TruthTableFitnessFunction.java