org.jgap.impl.BestChromosomesSelector Class Reference
Classes
class BestChromosomesSelectorConfig
Public Member Functions
BestChromosomesSelector () throws InvalidConfigurationException
BestChromosomesSelector (final Configuration a_config) throws InvalidConfigurationException
BestChromosomesSelector (final Configuration a_config, final double a_originalRate) throws InvalidConfigurationException
void selectChromosomes (final int a_howManyToSelect, Population a_to_pop)
void empty ()
boolean returnsUniqueChromosomes ()
void setOriginalRate (final double a_originalRate)
double getOriginalRate ()
boolean equals (Object a_o)
Object clone ()
Protected Member Functions
void add (final IChromosome a_chromosomeToAdd)
Private Attributes
Population m_chromosomes
boolean m_needsSorting
Comparator m_fitnessValueComparator
BestChromosomesSelectorConfig m_config
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.54 $`
Additional Inherited Members
Detailed Description
Implementation of a NaturalSelector that takes the top n chromosomes into the next generation. n can be specified. Which chromosomes are the best is decided by evaluating their fitness value.
Author
Klaus Meffert
Since
1.1
Definition at line 24 of file BestChromosomesSelector.java.
Constructor & Destructor Documentation
org.jgap.impl.BestChromosomesSelector.BestChromosomesSelector () throws InvalidConfigurationException [inline]
Default constructor. Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
1.1
Definition at line 57 of file BestChromosomesSelector.java.
Referenced by org.jgap.impl.BestChromosomesSelector.clone(), and org.jgap.impl.BestChromosomesSelector.equals().
org.jgap.impl.BestChromosomesSelector.BestChromosomesSelector (final Configuration a_config) throws InvalidConfigurationException [inline]
Using original rate of 1.0
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 71 of file BestChromosomesSelector.java.
org.jgap.impl.BestChromosomesSelector.BestChromosomesSelector (final Configuration a_config, final double a_originalRate) throws InvalidConfigurationException [inline]
Definition at line 76 of file BestChromosomesSelector.java.
References org.jgap.impl.BestChromosomesSelector.m_chromosomes, org.jgap.impl.BestChromosomesSelector.m_fitnessValueComparator, org.jgap.impl.BestChromosomesSelector.m_needsSorting, org.jgap.NaturalSelectorExt.setDoubletteChromosomesAllowed(), and org.jgap.impl.BestChromosomesSelector.setOriginalRate().
Member Function Documentation
void org.jgap.impl.BestChromosomesSelector.add (final IChromosome a_chromosomeToAdd) [inline], [protected], [virtual]
Add a Chromosome instance to this selector's working pool of Chromosomes.
Parameters
a_chromosomeToAdd the specimen to add to the pool
Author
Klaus Meffert
Since
1.1
Implements org.jgap.NaturalSelectorExt.
Definition at line 94 of file BestChromosomesSelector.java.
References org.jgap.impl.BestChromosomesSelector.clone(), org.jgap.Population.getChromosomes(), org.jgap.NaturalSelector.getConfiguration(), org.jgap.NaturalSelectorExt.getDoubletteChromosomesAllowed(), org.jgap.impl.BestChromosomesSelector.m_chromosomes, org.jgap.impl.BestChromosomesSelector.m_needsSorting, and org.jgap.IHandler.perform().
Object org.jgap.impl.BestChromosomesSelector.clone () [inline]
Returns
clone of the current object instance
Implements org.jgap.util.ICloneable.
Definition at line 298 of file BestChromosomesSelector.java.
References org.jgap.impl.BestChromosomesSelector.BestChromosomesSelector(), org.jgap.NaturalSelector.getConfiguration(), org.jgap.NaturalSelectorExt.getDoubletteChromosomesAllowed(), org.jgap.impl.BestChromosomesSelector.m_config, and org.jgap.impl.BestChromosomesSelector.m_needsSorting.
Referenced by org.jgap.impl.BestChromosomesSelector.add().
void org.jgap.impl.BestChromosomesSelector.empty () [inline]
Empties out the working pool of Chromosomes.
Author
Klaus Meffert
Since
1.1
Implements org.jgap.INaturalSelector.
Definition at line 216 of file BestChromosomesSelector.java.
References org.jgap.impl.BestChromosomesSelector.m_needsSorting.
boolean org.jgap.impl.BestChromosomesSelector.equals (Object a_o) [inline]
Definition at line 275 of file BestChromosomesSelector.java.
References org.jgap.impl.BestChromosomesSelector.BestChromosomesSelector(), org.jgap.Population.equals(), org.jgap.NaturalSelectorExt.getDoubletteChromosomesAllowed(), org.jgap.impl.BestChromosomesSelector.m_chromosomes, org.jgap.impl.BestChromosomesSelector.m_config, and org.jgap.impl.BestChromosomesSelector.m_fitnessValueComparator.
double org.jgap.impl.BestChromosomesSelector.getOriginalRate () [inline]
Returns
see setOriginalRate
Author
Klaus Meffert
Since
2.0
Definition at line 262 of file BestChromosomesSelector.java.
Referenced by org.jgap.impl.BestChromosomesSelectorTest.testSetOriginalRate_1().
boolean org.jgap.impl.BestChromosomesSelector.returnsUniqueChromosomes () [inline]
Returns
always true as no Chromosome can be returnd multiple times
Author
Klaus Meffert
Since
2.0
Implements org.jgap.INaturalSelector.
Definition at line 229 of file BestChromosomesSelector.java.
Referenced by org.jgap.impl.BestChromosomesSelectorTest.testConstruct_0(), and org.jgap.impl.BestChromosomesSelectorTest.testReturnsUnique_0().
void org.jgap.impl.BestChromosomesSelector.selectChromosomes (final int a_howManyToSelect, Population a_to_pop) [inline]
Selects a given number of chromosomes from the pool that will move on to the next generation population. This selection will be guided by the fitness values. The chromosomes with the best fitness value win.
Parameters
a_to_pop the population the chromosomes will be added to
a_howManyToSelect the number of chromosomes to select
Author
Klaus Meffert
Since
1.1
Definition at line 141 of file BestChromosomesSelector.java.
References org.jgap.NaturalSelector.getConfiguration(), org.jgap.NaturalSelectorExt.getDoubletteChromosomesAllowed(), org.jgap.impl.BestChromosomesSelector.m_fitnessValueComparator, org.jgap.NaturalSelector.m_monitorActive, and org.jgap.impl.BestChromosomesSelector.m_needsSorting.
void org.jgap.impl.BestChromosomesSelector.setOriginalRate (final double a_originalRate) [inline]
Setting this parameter controls how many chromosomes of the original population will be considered for selection to the next population. If the value is 1 then the whole original population is considered, if it is 0.5 only half of the chromosomes are considered. If doublettes are allowed, then a number of chromosomes missing (number of to be selected minus number selected) will be added.
Parameters
a_originalRate the rate of how many of the original chromosomes will be selected according to BestChromosomeSelector's strategy. The rest (non-original) of the chromosomes is added as duplicates
Author
Klaus Meffert
Since
2.0
Definition at line 247 of file BestChromosomesSelector.java.
Referenced by org.jgap.impl.BestChromosomesSelector.BestChromosomesSelector().
Member Data Documentation
final String org.jgap.impl.BestChromosomesSelector.CVS_REVISION = `$Revision: 1.54 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file BestChromosomesSelector.java.
Population org.jgap.impl.BestChromosomesSelector.m_chromosomes [private]
Stores the chromosomes to be taken into account for selection
Definition at line 32 of file BestChromosomesSelector.java.
Referenced by org.jgap.impl.BestChromosomesSelector.add(), org.jgap.impl.BestChromosomesSelector.BestChromosomesSelector(), and org.jgap.impl.BestChromosomesSelector.equals().
BestChromosomesSelectorConfig org.jgap.impl.BestChromosomesSelector.m_config [private]
Initial value:
= new
      BestChromosomesSelectorConfig()
Definition at line 44 of file BestChromosomesSelector.java.
Referenced by org.jgap.impl.BestChromosomesSelector.clone(), and org.jgap.impl.BestChromosomesSelector.equals().
Comparator org.jgap.impl.BestChromosomesSelector.m_fitnessValueComparator [private]
Comparator that is concerned about both age and fitness values
Definition at line 42 of file BestChromosomesSelector.java.
Referenced by org.jgap.impl.BestChromosomesSelector.BestChromosomesSelector(), org.jgap.impl.BestChromosomesSelector.equals(), and org.jgap.impl.BestChromosomesSelector.selectChromosomes().
boolean org.jgap.impl.BestChromosomesSelector.m_needsSorting [private]
Indicated whether the list of added chromosomes needs sorting
Definition at line 37 of file BestChromosomesSelector.java.
Referenced by org.jgap.impl.BestChromosomesSelector.add(), org.jgap.impl.BestChromosomesSelector.BestChromosomesSelector(), org.jgap.impl.BestChromosomesSelector.clone(), org.jgap.impl.BestChromosomesSelector.empty(), and org.jgap.impl.BestChromosomesSelector.selectChromosomes().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/BestChromosomesSelector.java