org.jgap.impl.CompositeGeneTest Class Reference
Classes
class GeneConstraintChecker
Public Member Functions
void testCompareTo_4 () throws Exception
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testAddGene_0 () throws Exception
void testAddGene_1 () throws Exception
void testAddGene_2 () throws Exception
void testAddGene_3 () throws Exception
void testAddGene_4 () throws Exception
void testAddGene_5 () throws Exception
void testAddGene_6 () throws Exception
void testAddGene_7 () throws Exception
void testToString_0 () throws Exception
void testToString_1 () throws Exception
void testGetAllele_0 () throws Exception
void testGetAllele_1 () throws Exception
void testGetAllele_2 () throws Exception
void testEquals_0 () throws Exception
void testEquals_1 () throws Exception
void testEquals_2 () throws Exception
void testEquals_3 () throws Exception
void testEquals_4_2 () throws Exception
void testEquals_5 () throws Exception
void testEquals_5_2 () throws Exception
void testEquals_6 () throws Exception
void testEquals_7 () throws Exception
void testEquals_8 () throws Exception
void testSetAllele_0 () throws Exception
void testSetAllele_1 () throws Exception
void testSetAllele_2 () throws Exception
void testSetAllele_3 () throws Exception
void testSetAllele_4 () throws Exception
void testSetAllele_5 () throws Exception
void testNewGene_0 () throws Exception
void testPersistentPresentation_0 () throws Exception
void testPersistentPresentation_0_2 () throws Exception
void testPersistentPresentation_1 () throws Exception
void testPersistentPresentation_2 () throws Exception
void testPersistentPresentation_3 () throws Exception
void testPersistentPresentation_4 () throws Exception
void testPersistentPresentation_5 () throws Exception
void testPersistentPresentation_6 () throws Exception
void testPersistentPresentation_7 () throws Exception
void testRemoveGeneByIdentity_0 () throws Exception
void testRemoveGeneByIdentity_1 () throws Exception
void testCleanup_0 () throws Exception
void testCleanup_1 () throws Exception
void testSetConstraintChecker_0 () throws Exception
void testSetToRandomValue_0 () throws Exception
void testSetToRandomValue_1 () throws Exception
void testSetToRandomValue_2 () throws Exception
void testSetEnergy_0 () throws Exception
void testSetEnergy_1 () throws Exception
void testCompareTo_0 () throws Exception
void testCompareTo_1 () throws Exception
void testCompareTo_2 () throws Exception
void testCompareTo_3 () throws Exception
void testCompareTo_3_2 () throws Exception
void testCompareTo_5 () throws Exception
void testCompareTo_6 () throws Exception
void testApplyMutation_0 () throws Exception
void testGetAllele_3 () throws Exception
void testHashCode_0 () throws Exception
void testGetGenes_1 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.52 $`
static int cleanedUp = 0
Additional Inherited Members
Detailed Description
Tests the CompositeGene class.
Author
Klaus Meffert
Since
1.1
Definition at line 22 of file CompositeGeneTest.java.
Member Function Documentation
static Test org.jgap.impl.CompositeGeneTest.suite () [inline], [static]
Definition at line 29 of file CompositeGeneTest.java.
void org.jgap.impl.CompositeGeneTest.testAddGene_0 () throws Exception [inline]
Ensures that a CompositeGene may be added to a CompositeGene
Author
Audrius Meskauskas
Klaus Meffert
Since
2.0
Exceptions
Exception
Definition at line 91 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.size().
void org.jgap.impl.CompositeGeneTest.testAddGene_1 () throws Exception [inline]
Definition at line 98 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.size().
void org.jgap.impl.CompositeGeneTest.testAddGene_2 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 125 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.CompositeGene.getGeneTypeAllowed(), and org.jgap.impl.CompositeGene.size().
void org.jgap.impl.CompositeGeneTest.testAddGene_3 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 139 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testAddGene_4 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 157 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.size().
void org.jgap.impl.CompositeGeneTest.testAddGene_5 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 170 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testAddGene_6 () throws Exception [inline]
Adding two different initial genes with strict parameter set is not allowed.
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 191 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testAddGene_7 () throws Exception [inline]
Adding an initial CompositeGene twice should be possible, if they are two newly created instances.
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 212 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testApplyMutation_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1089 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testCleanup_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 803 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.CompositeGeneTest.cleanedUp, org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.size().
void org.jgap.impl.CompositeGeneTest.testCleanup_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 830 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.size().
void org.jgap.impl.CompositeGeneTest.testCompareTo_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 947 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.CompositeGene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testCompareTo_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 967 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.CompositeGene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testCompareTo_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 985 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.CompositeGene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testCompareTo_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 1004 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testCompareTo_3_2 () throws Exception [inline]
Definition at line 1015 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.CompositeGene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testCompareTo_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 39 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.CompositeGene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testCompareTo_5 () throws Exception [inline]
Using application data.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 1037 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.CompositeGene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testCompareTo_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1071 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.CompositeGene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testConstruct_0 () throws Exception [inline]
Author
Klaus Meffert
Exceptions
Exception
Definition at line 63 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.getGeneTypeAllowed().
void org.jgap.impl.CompositeGeneTest.testConstruct_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 76 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testEquals_0 () throws Exception [inline]
Definition at line 287 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testEquals_1 () throws Exception [inline]
Definition at line 295 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testEquals_2 () throws Exception [inline]
Definition at line 301 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testEquals_3 () throws Exception [inline]
Definition at line 307 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testEquals_4_2 () throws Exception [inline]
Tests that no NullPointerException arises.
Author
Klaus Meffert
Since
2.6
Exceptions
Exception
Definition at line 320 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testEquals_5 () throws Exception [inline]
Definition at line 332 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.equals().
void org.jgap.impl.CompositeGeneTest.testEquals_5_2 () throws Exception [inline]
Author
Klaus Meffert
Since
2.4
Exceptions
Exception
Definition at line 349 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.equals().
void org.jgap.impl.CompositeGeneTest.testEquals_6 () throws Exception [inline]
Definition at line 362 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testEquals_7 () throws Exception [inline]
Definition at line 374 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testEquals_8 () throws Exception [inline]
Author
Klaus Meffert
Since
2.4
Exceptions
Exception
Definition at line 392 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testGetAllele_0 () throws Exception [inline]
Definition at line 250 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testGetAllele_1 () throws Exception [inline]
Definition at line 257 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.getAllele().
void org.jgap.impl.CompositeGeneTest.testGetAllele_2 () throws Exception [inline]
Definition at line 270 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.getAllele().
void org.jgap.impl.CompositeGeneTest.testGetAllele_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1108 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.getInternalValue().
void org.jgap.impl.CompositeGeneTest.testGetGenes_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2.2
Definition at line 1151 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.CompositeGene.geneAt(), org.jgap.impl.CompositeGene.getGenes(), and org.jgap.impl.CompositeGene.size().
void org.jgap.impl.CompositeGeneTest.testHashCode_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1120 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.hashCode().
void org.jgap.impl.CompositeGeneTest.testNewGene_0 () throws Exception [inline]
Definition at line 501 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseGene.equals(), and org.jgap.BaseGene.newGene().
void org.jgap.impl.CompositeGeneTest.testPersistentPresentation_0 () throws Exception [inline]
Definition at line 525 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testPersistentPresentation_0_2 () throws Exception [inline]
Use special characters in alphabet.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 558 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testPersistentPresentation_1 () throws Exception [inline]
Test a nested persistent representation, including strings.
Exceptions
Exception
Author
Audrius Meskauskas
Since
2.0
Definition at line 586 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.CompositeGene.geneAt(), and org.jgap.BaseGene.getAllele().
void org.jgap.impl.CompositeGeneTest.testPersistentPresentation_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 647 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.size().
void org.jgap.impl.CompositeGeneTest.testPersistentPresentation_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 661 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testPersistentPresentation_4 () throws Exception [inline]
Invalid Gene class.
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 683 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testPersistentPresentation_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 704 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testPersistentPresentation_6 () throws Exception [inline]
No closing tag.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 724 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testPersistentPresentation_7 () throws Exception [inline]
Empty representation.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 746 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.size().
void org.jgap.impl.CompositeGeneTest.testRemoveGeneByIdentity_0 () throws Exception [inline]
Tests if removal from empty list returns false no matter what to remove.
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 771 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.removeGeneByIdentity().
void org.jgap.impl.CompositeGeneTest.testRemoveGeneByIdentity_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 785 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.CompositeGene.removeGeneByIdentity(), and org.jgap.impl.CompositeGene.size().
void org.jgap.impl.CompositeGeneTest.testSetAllele_0 () throws Exception [inline]
Definition at line 406 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testSetAllele_1 () throws Exception [inline]
Definition at line 418 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testSetAllele_2 () throws Exception [inline]
Set Allele to empty Vector, no exception should occur.
Exceptions
Exception
Definition at line 435 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testSetAllele_3 () throws Exception [inline]
Definition at line 441 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testSetAllele_4 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 459 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.CompositeGeneTest.testSetAllele_5 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 483 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.CompositeGeneTest.testSetConstraintChecker_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 844 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getConstraintChecker().
void org.jgap.impl.CompositeGeneTest.testSetEnergy_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 915 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getEnergy().
void org.jgap.impl.CompositeGeneTest.testSetEnergy_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 928 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getEnergy().
void org.jgap.impl.CompositeGeneTest.testSetToRandomValue_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 864 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.CompositeGeneTest.testSetToRandomValue_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 883 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.impl.DoubleGene.doubleValue().
void org.jgap.impl.CompositeGeneTest.testSetToRandomValue_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 899 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.impl.DoubleGene.doubleValue().
void org.jgap.impl.CompositeGeneTest.testToString_0 () throws Exception [inline]
Author
Klaus Meffert
Exceptions
Exception
Definition at line 224 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.toString().
void org.jgap.impl.CompositeGeneTest.testToString_1 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 244 of file CompositeGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.CompositeGene.toString().
Member Data Documentation
int org.jgap.impl.CompositeGeneTest.cleanedUp = 0 [static], [private]
Definition at line 27 of file CompositeGeneTest.java.
Referenced by org.jgap.impl.CompositeGeneTest.testCleanup_0().
final String org.jgap.impl.CompositeGeneTest.CVS_REVISION = `$Revision: 1.52 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file CompositeGeneTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/CompositeGeneTest.java