org.jgap.impl.NumberGeneTest.NumberGeneImpl Class Reference
Public Member Functions
NumberGeneImpl (final Configuration a_conf, int a_lowerBounds, int a_upperBounds) throws InvalidConfigurationException
String getPersistentRepresentation ()
void setValueFromPersistentRepresentation (String a_representation)
void setToRandomValue (RandomGenerator a_numberGenerator)
void applyMutation (int a_index, double a_percentage)
boolean equals (Object a_other)
Protected Member Functions
Gene newGeneInternal ()
void calculateBoundsUnitsToIntegerUnitsRatio ()
void mapValueToWithinBounds ()
int compareToNative (Object a_o1, Object a_o2)
Static Protected Attributes
static final long INTEGER_RANGE
Private Attributes
int m_upperBounds
int m_lowerBounds
long m_boundsUnitsToIntegerUnits
Additional Inherited Members
Detailed Description
Test implementation of NumberGene, based on IntegerGene.
Author
Klaus Meffert
Since
1.1
Definition at line 469 of file NumberGeneTest.java.
Constructor & Destructor Documentation
org.jgap.impl.NumberGeneTest.NumberGeneImpl.NumberGeneImpl (final Configuration a_conf, int a_lowerBounds, int a_upperBounds) throws InvalidConfigurationException [inline]
Definition at line 480 of file NumberGeneTest.java.
References org.jgap.impl.NumberGeneTest.NumberGeneImpl.calculateBoundsUnitsToIntegerUnitsRatio(), org.jgap.impl.NumberGeneTest.NumberGeneImpl.m_lowerBounds, and org.jgap.impl.NumberGeneTest.NumberGeneImpl.m_upperBounds.
Referenced by org.jgap.impl.NumberGeneTest.NumberGeneImpl.newGeneInternal().
Member Function Documentation
void org.jgap.impl.NumberGeneTest.NumberGeneImpl.applyMutation (int index, double a_percentage) [inline]
Applies a mutation of a given intensity (percentage) onto the atomic element at given index (NumberGenes only have one atomic element)
Parameters
index index of atomic element, between 0 and size()-1
a_percentage percentage of mutation (greater than -1 and smaller than 1).
Since
1.1
Implements org.jgap.Gene.
Definition at line 514 of file NumberGeneTest.java.
void org.jgap.impl.NumberGeneTest.NumberGeneImpl.calculateBoundsUnitsToIntegerUnitsRatio () [inline], [protected]
Definition at line 519 of file NumberGeneTest.java.
References org.jgap.impl.NumberGeneTest.NumberGeneImpl.INTEGER_RANGE, org.jgap.impl.NumberGeneTest.NumberGeneImpl.m_boundsUnitsToIntegerUnits, org.jgap.impl.NumberGeneTest.NumberGeneImpl.m_lowerBounds, and org.jgap.impl.NumberGeneTest.NumberGeneImpl.m_upperBounds.
Referenced by org.jgap.impl.NumberGeneTest.NumberGeneImpl.NumberGeneImpl().
int org.jgap.impl.NumberGeneTest.NumberGeneImpl.compareToNative (Object a_o1, Object a_o2) [inline], [protected], [virtual]
Compares to objects by first casting them into their expected type (e.g. Integer for IntegerGene) and then calling the compareTo-method of the casted type.
Parameters
a_o1 first object to be compared, always is not null
a_o2 second object to be compared, always is not null
Returns
a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than the object provided for comparison
Author
Klaus Meffert
Since
1.1
Implements org.jgap.impl.NumberGene.
Definition at line 549 of file NumberGeneTest.java.
boolean org.jgap.impl.NumberGeneTest.NumberGeneImpl.equals (Object a_other) [inline]
Definition at line 553 of file NumberGeneTest.java.
References org.jgap.impl.NumberGene.compareTo().
String org.jgap.impl.NumberGeneTest.NumberGeneImpl.getPersistentRepresentation () [inline]
Retrieves a string representation of the value of this Gene instance that includes any information required to reconstruct it at a later time, such as its value and internal state. This string will be used to represent this Gene instance in XML persistence. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Returns
string representation of this Gene's current state
Exceptions
UnsupportedOperationException to indicate that no implementation is provided for this method
Since
1.0
Implements org.jgap.Gene.
Definition at line 499 of file NumberGeneTest.java.
References org.jgap.impl.NumberGeneTest.NumberGeneImpl.m_lowerBounds, org.jgap.impl.NumberGeneTest.NumberGeneImpl.m_upperBounds, org.jgap.Gene.PERSISTENT_FIELD_DELIMITER, and org.jgap.BaseGene.toString().
void org.jgap.impl.NumberGeneTest.NumberGeneImpl.mapValueToWithinBounds () [inline], [protected], [virtual]
Maps the value of this NumberGene to within the bounds specified by the m_upperBounds and m_lowerBounds instance variables. The value's relative position within the integer range will be preserved within the bounds range (in other words, if the value is about halfway between the integer max and min, then the resulting value will be about halfway between the upper bounds and lower bounds). If the value is null or is already within the bounds, it will be left unchanged.
Author
Klaus Meffert
Since
1.1
Implements org.jgap.impl.NumberGene.
Definition at line 529 of file NumberGeneTest.java.
References org.jgap.BaseGene.getAllele(), org.jgap.impl.NumberGeneTest.NumberGeneImpl.m_boundsUnitsToIntegerUnits, org.jgap.impl.NumberGeneTest.NumberGeneImpl.m_lowerBounds, org.jgap.impl.NumberGeneTest.NumberGeneImpl.m_upperBounds, and org.jgap.impl.NumberGene.setAllele().
Gene org.jgap.impl.NumberGeneTest.NumberGeneImpl.newGeneInternal () [inline], [protected], [virtual]
Implements org.jgap.BaseGene.
Definition at line 489 of file NumberGeneTest.java.
References org.jgap.BaseGene.getConfiguration(), org.jgap.impl.NumberGeneTest.NumberGeneImpl.m_lowerBounds, org.jgap.impl.NumberGeneTest.NumberGeneImpl.m_upperBounds, and org.jgap.impl.NumberGeneTest.NumberGeneImpl.NumberGeneImpl().
void org.jgap.impl.NumberGeneTest.NumberGeneImpl.setToRandomValue (RandomGenerator a_numberGenerator) [inline]
Sets the value of this Gene to a random legal value for the implementation. This method exists for the benefit of mutation and other operations that simply desire to randomize the value of a gene.
Parameters
a_numberGenerator The random number generator that should be used to create any random values. It's important to use this generator to maintain the user's flexibility to configure the genetic engine to use the random number generator of their choice
Since
1.0
Implements org.jgap.Gene.
Definition at line 509 of file NumberGeneTest.java.
void org.jgap.impl.NumberGeneTest.NumberGeneImpl.setValueFromPersistentRepresentation (String a_representation) [inline]
Sets the value and internal state of this Gene from the string representation returned by a previous invocation of the getPersistentRepresentation() method. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Parameters
a_representation the string representation retrieved from a prior call to the getPersistentRepresentation() method
Exceptions
UnsupportedOperationException to indicate that no implementation is provided for this method
UnsupportedRepresentationException if this Gene implementation does not support the given string representation
Since
1.0
Implements org.jgap.Gene.
Definition at line 504 of file NumberGeneTest.java.
Member Data Documentation
final long org.jgap.impl.NumberGeneTest.NumberGeneImpl.INTEGER_RANGE [static], [protected]
Initial value:
= (long) Integer.MAX_VALUE
        - (long) Integer.MIN_VALUE
Definition at line 471 of file NumberGeneTest.java.
Referenced by org.jgap.impl.NumberGeneTest.NumberGeneImpl.calculateBoundsUnitsToIntegerUnitsRatio().
long org.jgap.impl.NumberGeneTest.NumberGeneImpl.m_boundsUnitsToIntegerUnits [private]
Definition at line 478 of file NumberGeneTest.java.
Referenced by org.jgap.impl.NumberGeneTest.NumberGeneImpl.calculateBoundsUnitsToIntegerUnitsRatio(), and org.jgap.impl.NumberGeneTest.NumberGeneImpl.mapValueToWithinBounds().
int org.jgap.impl.NumberGeneTest.NumberGeneImpl.m_lowerBounds [private]
Definition at line 476 of file NumberGeneTest.java.
Referenced by org.jgap.impl.NumberGeneTest.NumberGeneImpl.calculateBoundsUnitsToIntegerUnitsRatio(), org.jgap.impl.NumberGeneTest.NumberGeneImpl.getPersistentRepresentation(), org.jgap.impl.NumberGeneTest.NumberGeneImpl.mapValueToWithinBounds(), org.jgap.impl.NumberGeneTest.NumberGeneImpl.newGeneInternal(), and org.jgap.impl.NumberGeneTest.NumberGeneImpl.NumberGeneImpl().
int org.jgap.impl.NumberGeneTest.NumberGeneImpl.m_upperBounds [private]
Definition at line 474 of file NumberGeneTest.java.
Referenced by org.jgap.impl.NumberGeneTest.NumberGeneImpl.calculateBoundsUnitsToIntegerUnitsRatio(), org.jgap.impl.NumberGeneTest.NumberGeneImpl.getPersistentRepresentation(), org.jgap.impl.NumberGeneTest.NumberGeneImpl.mapValueToWithinBounds(), org.jgap.impl.NumberGeneTest.NumberGeneImpl.newGeneInternal(), and org.jgap.impl.NumberGeneTest.NumberGeneImpl.NumberGeneImpl().
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/NumberGeneTest.java