org.jgap.gp.function.Switch Class Reference
Public Member Functions
Switch (final GPConfiguration a_conf, Class a_type) throws InvalidConfigurationException
String toString ()
String getName ()
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
boolean execute_boolean (ProgramChromosome c, int n, Object[] args)
int execute_int (ProgramChromosome c, int n, Object[] args)
long execute_long (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
Class getChildType (IGPProgram a_ind, int a_chromNum)
Object clone ()
boolean equals (Object a_other)
Private Attributes
Class m_type
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.1 $`
Additional Inherited Members
Detailed Description
The switch construct: if <condition> then return <result of command 1> else return <result of command 2>
Author
Klaus Meffert, Johannes Goebel
Since
3.6
Definition at line 27 of file Switch.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Switch.Switch (final GPConfiguration a_conf, Class a_type) throws InvalidConfigurationException [inline]
Definition at line 34 of file Switch.java.
References org.jgap.gp.CommandGene.FloatClass, and org.jgap.gp.function.Switch.m_type.
Referenced by org.jgap.gp.function.Switch.clone(), and org.jgap.gp.function.Switch.equals().
Member Function Documentation
Object org.jgap.gp.function.Switch.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 148 of file Switch.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.function.Switch.m_type, and org.jgap.gp.function.Switch.Switch().
boolean org.jgap.gp.function.Switch.equals (Object a_other) [inline]
The equals method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Frank Pape
Since
3.4.3
Definition at line 166 of file Switch.java.
References org.jgap.gp.function.Switch.Switch().
boolean org.jgap.gp.function.Switch.execute_boolean (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 77 of file Switch.java.
double org.jgap.gp.function.Switch.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 65 of file Switch.java.
float org.jgap.gp.function.Switch.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 54 of file Switch.java.
int org.jgap.gp.function.Switch.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 89 of file Switch.java.
long org.jgap.gp.function.Switch.execute_long (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 100 of file Switch.java.
Object org.jgap.gp.function.Switch.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 111 of file Switch.java.
Class org.jgap.gp.function.Switch.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Determines which type a specific child of this command has.
Parameters
a_ind ignored here
a_chromNum index of child
Returns
type of the a_chromNum'th child
Author
Klaus Meffert
Since
3.2
Definition at line 133 of file Switch.java.
References org.jgap.gp.CommandGene.BooleanClass, and org.jgap.gp.function.Switch.m_type.
String org.jgap.gp.function.Switch.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 50 of file Switch.java.
String org.jgap.gp.function.Switch.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 40 of file Switch.java.
Member Data Documentation
final String org.jgap.gp.function.Switch.CVS_REVISION = `$Revision: 1.1 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 30 of file Switch.java.
Class org.jgap.gp.function.Switch.m_type [private]
Definition at line 32 of file Switch.java.
Referenced by org.jgap.gp.function.Switch.clone(), org.jgap.gp.function.Switch.getChildType(), and org.jgap.gp.function.Switch.Switch().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Switch.java