org.jgap.gp.terminal.True Class Reference
Public Member Functions
True (final GPConfiguration a_conf) throws InvalidConfigurationException
True (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException
CommandGene applyMutation (int index, double a_percentage) throws InvalidConfigurationException
Object clone ()
String toString ()
String getName ()
boolean execute_boolean (ProgramChromosome c, int n, Object[] args)
Class getChildType (IGPProgram a_ind, int a_index)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.8 $`
Additional Inherited Members
Detailed Description
The boolean value true.
Author
Klaus Meffert
Since
3.0
Definition at line 23 of file True.java.
Constructor & Destructor Documentation
org.jgap.gp.terminal.True.True (final GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Definition at line 28 of file True.java.
References org.jgap.gp.CommandGene.BooleanClass.
Referenced by org.jgap.gp.terminal.True.clone().
org.jgap.gp.terminal.True.True (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 33 of file True.java.
Member Function Documentation
CommandGene org.jgap.gp.terminal.True.applyMutation (int a_index, double a_percentage) throws InvalidConfigurationException [inline]
Mutates a CommandGene.
Parameters
a_index references the part of a multipart object, normally not relevant
a_percentage the mutation rate (0.0 to 1.0)
Returns
the mutant
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IMutateable.
Definition at line 38 of file True.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.CommandGene.getReturnType().
Object org.jgap.gp.terminal.True.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 52 of file True.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.terminal.True.True().
boolean org.jgap.gp.terminal.True.execute_boolean (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 75 of file True.java.
Class org.jgap.gp.terminal.True.getChildType (IGPProgram a_ind, int a_index) [inline]
Definition at line 79 of file True.java.
String org.jgap.gp.terminal.True.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 71 of file True.java.
String org.jgap.gp.terminal.True.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 61 of file True.java.
Member Data Documentation
final String org.jgap.gp.terminal.True.CVS_REVISION = `$Revision: 1.8 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file True.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/terminal/True.java