org.jgap.gp.function.Modulo Class Reference
Classes
interface Compatible
Public Member Functions
Modulo (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException
String toString ()
String getName ()
int execute_int (ProgramChromosome c, int n, Object[] args)
long execute_long (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.10 $`
Additional Inherited Members
Detailed Description
The modulo operation.
Author
Konrad Odell
Klaus Meffert
Since
3.0
Definition at line 24 of file Modulo.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Modulo.Modulo (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 29 of file Modulo.java.
Referenced by org.jgap.gp.function.Modulo.clone().
Member Function Documentation
Object org.jgap.gp.function.Modulo.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 104 of file Modulo.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.function.Modulo.Modulo().
double org.jgap.gp.function.Modulo.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 75 of file Modulo.java.
References org.jgap.gp.CommandGene.DELTA.
float org.jgap.gp.function.Modulo.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 66 of file Modulo.java.
References org.jgap.gp.CommandGene.DELTA.
int org.jgap.gp.function.Modulo.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 48 of file Modulo.java.
long org.jgap.gp.function.Modulo.execute_long (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 57 of file Modulo.java.
Object org.jgap.gp.function.Modulo.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 84 of file Modulo.java.
String org.jgap.gp.function.Modulo.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 44 of file Modulo.java.
String org.jgap.gp.function.Modulo.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 34 of file Modulo.java.
Member Data Documentation
final String org.jgap.gp.function.Modulo.CVS_REVISION = `$Revision: 1.10 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file Modulo.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Modulo.java