org.jgap.distr.grid.JGAPServer Class Reference
Public Member Functions
JGAPServer (String[] args) throws Exception
void addFile (String a_filename) throws Exception
Static Public Member Functions
static void copyFile (String source, String dest) throws Exception
static void main (String[] args) throws Exception
Private Attributes
GridServer m_gs
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.7 $`
static final String className = JGAPServer.class.getName()
static Logger log = Logger.getLogger(className)
Detailed Description
A grid server is able to:
a) receive work requests from JGAPClients b) send work units to JGAPWorkers c) receive solutions from JGAPWorkers, and d) send back these solutions to the requesting JGAPClient.
Author
Klaus Meffert
Since
3.01
Definition at line 29 of file JGAPServer.java.
Constructor & Destructor Documentation
org.jgap.distr.grid.JGAPServer.JGAPServer (String[] args) throws Exception [inline]
Definition at line 39 of file JGAPServer.java.
References org.jgap.distr.grid.JGAPServer.m_gs.
Referenced by org.jgap.distr.grid.JGAPServer.main().
Member Function Documentation
void org.jgap.distr.grid.JGAPServer.addFile (String a_filename) throws Exception [inline]
Definition at line 52 of file JGAPServer.java.
References org.jgap.distr.grid.JGAPServer.copyFile().
static void org.jgap.distr.grid.JGAPServer.copyFile (String source, String dest) throws Exception [inline], [static]
Definition at line 64 of file JGAPServer.java.
Referenced by org.jgap.distr.grid.JGAPServer.addFile().
static void org.jgap.distr.grid.JGAPServer.main (String[] args) throws Exception [inline], [static]
Definition at line 88 of file JGAPServer.java.
References org.jgap.distr.grid.JGAPServer.JGAPServer().
Member Data Documentation
final String org.jgap.distr.grid.JGAPServer.className = JGAPServer.class.getName() [static], [private]
Definition at line 33 of file JGAPServer.java.
final String org.jgap.distr.grid.JGAPServer.CVS_REVISION = `$Revision: 1.7 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 31 of file JGAPServer.java.
Logger org.jgap.distr.grid.JGAPServer.log = Logger.getLogger(className) [static], [private]
Definition at line 35 of file JGAPServer.java.
GridServer org.jgap.distr.grid.JGAPServer.m_gs [private]
Definition at line 37 of file JGAPServer.java.
Referenced by org.jgap.distr.grid.JGAPServer.JGAPServer().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/distr/grid/JGAPServer.java