org.jgap.impl.GaussianMutationOperatorTest Class Reference
Public Member Functions
void setUp ()
void testOperate_0 () throws Exception
void testOperate_1 () throws Exception
void testOperate_2 () throws Exception
void testOperate_4 () throws Exception
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testConstruct_2 () throws Exception
void testConstruct_3 () throws Exception
void testCompareTo_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.15 $`
Additional Inherited Members
Detailed Description
Tests the GaussianMutationOperator class.
Author
Klaus Meffert
Since
2.0
Definition at line 22 of file GaussianMutationOperatorTest.java.
Member Function Documentation
void org.jgap.impl.GaussianMutationOperatorTest.setUp () [inline]
Definition at line 32 of file GaussianMutationOperatorTest.java.
static Test org.jgap.impl.GaussianMutationOperatorTest.suite () [inline], [static]
Definition at line 27 of file GaussianMutationOperatorTest.java.
void org.jgap.impl.GaussianMutationOperatorTest.testCompareTo_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 299 of file GaussianMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.GaussianMutationOperator.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.GaussianMutationOperatorTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 250 of file GaussianMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.impl.GaussianMutationOperator.getDeviation().
void org.jgap.impl.GaussianMutationOperatorTest.testConstruct_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 262 of file GaussianMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.impl.GaussianMutationOperator.getDeviation().
void org.jgap.impl.GaussianMutationOperatorTest.testConstruct_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 274 of file GaussianMutationOperatorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.GaussianMutationOperatorTest.testConstruct_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 287 of file GaussianMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.impl.GaussianMutationOperator.getDeviation().
void org.jgap.impl.GaussianMutationOperatorTest.testOperate_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 43 of file GaussianMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.GaussianMutationOperatorTest.testOperate_1 () throws Exception [inline]
Tests if mutation produces same results for two operate-runs
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 94 of file GaussianMutationOperatorTest.java.
References org.jgap.Chromosome.clone(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.isChromosomesEqual().
void org.jgap.impl.GaussianMutationOperatorTest.testOperate_2 () throws Exception [inline]
Tests if mutation works for CompositeGene.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 143 of file GaussianMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.GaussianMutationOperatorTest.testOperate_4 () throws Exception [inline]
Tests if population size grows expectedly after two consecutive calls.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 199 of file GaussianMutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
Member Data Documentation
final String org.jgap.impl.GaussianMutationOperatorTest.CVS_REVISION = `$Revision: 1.15 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file GaussianMutationOperatorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/GaussianMutationOperatorTest.java