examples.math.cmd.MinusOperator Class Reference
Public Member Functions
MinusOperator ()
MinusOperator (Operand theLeft, Operand theRight)
double calcuate ()
void accept (MathVisitor theVisitor)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.1 $`
Additional Inherited Members
Detailed Description
The minus operator.
Author
Michael Grove
Since
3.4.2
Definition at line 20 of file MinusOperator.java.
Constructor & Destructor Documentation
examples.math.cmd.MinusOperator.MinusOperator () [inline]
Definition at line 25 of file MinusOperator.java.
Referenced by examples.math.cmd.MinusOperator.clone().
examples.math.cmd.MinusOperator.MinusOperator (Operand theLeft, Operand theRight) [inline]
Definition at line 29 of file MinusOperator.java.
Member Function Documentation
void examples.math.cmd.MinusOperator.accept (MathVisitor theVisitor) [inline]
Implements examples.math.cmd.Operand.
Definition at line 37 of file MinusOperator.java.
double examples.math.cmd.MinusOperator.calcuate () [inline]
Implements examples.math.cmd.Operator.
Definition at line 33 of file MinusOperator.java.
References examples.math.cmd.MathOperator.getLeftOperand(), and examples.math.cmd.MathOperator.getRightOperand().
Object examples.math.cmd.MinusOperator.clone () [inline], [virtual]
Implements examples.math.cmd.MathOperator.
Definition at line 41 of file MinusOperator.java.
References examples.math.cmd.MinusOperator.MinusOperator().
Member Data Documentation
final String examples.math.cmd.MinusOperator.CVS_REVISION = `$Revision: 1.1 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 23 of file MinusOperator.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/math/cmd/MinusOperator.java