org.jgap.impl.DefaultCompareToHandlerTest Class Reference
Classes
class MyAppDataForTesting
Public Member Functions
void testIsHandlerFor_0 () throws Exception
void testIsHandlerFor_1 () throws Exception
void testIsHandlerFor_3 () throws Exception
void testPerform_1 () throws Exception
void testPerform_2 () throws Exception
void testIsHandlerFor_2 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
Tests the DefaultCompareToHandler class.
Author
Klaus Meffert
Since
3.1
Definition at line 22 of file DefaultCompareToHandlerTest.java.
Member Function Documentation
static Test org.jgap.impl.DefaultCompareToHandlerTest.suite () [inline], [static]
Definition at line 27 of file DefaultCompareToHandlerTest.java.
void org.jgap.impl.DefaultCompareToHandlerTest.testIsHandlerFor_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 38 of file DefaultCompareToHandlerTest.java.
References org.jgap.IHandler.isHandlerFor().
void org.jgap.impl.DefaultCompareToHandlerTest.testIsHandlerFor_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 50 of file DefaultCompareToHandlerTest.java.
References org.jgap.IHandler.isHandlerFor().
void org.jgap.impl.DefaultCompareToHandlerTest.testIsHandlerFor_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 104 of file DefaultCompareToHandlerTest.java.
References org.jgap.IHandler.isHandlerFor().
void org.jgap.impl.DefaultCompareToHandlerTest.testIsHandlerFor_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 62 of file DefaultCompareToHandlerTest.java.
References org.jgap.IHandler.isHandlerFor().
void org.jgap.impl.DefaultCompareToHandlerTest.testPerform_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 75 of file DefaultCompareToHandlerTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.IHandler.perform().
void org.jgap.impl.DefaultCompareToHandlerTest.testPerform_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 89 of file DefaultCompareToHandlerTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.IHandler.perform().
Member Data Documentation
final String org.jgap.impl.DefaultCompareToHandlerTest.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file DefaultCompareToHandlerTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/DefaultCompareToHandlerTest.java