org.jgap.gp.function.TransferMemory Class Reference
Public Member Functions
TransferMemory (final GPConfiguration a_conf, String a_sourceStorageName, String a_targetStorageName) throws InvalidConfigurationException
String toString ()
String getName ()
void execute_void (ProgramChromosome c, int n, Object[] args)
boolean isAffectGlobalState ()
boolean isValid (ProgramChromosome a_program)
Class getChildType (IGPProgram a_ind, int a_chromNum)
int compareTo (Object a_other)
boolean equals (Object a_other)
Object clone ()
Private Attributes
String m_sourceStorageName
String m_targetStorageName
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.12 $`
Additional Inherited Members
Detailed Description
Transfers a memory value to another memory cell.
Author
Klaus Meffert
Since
3.0
Definition at line 24 of file TransferMemory.java.
Constructor & Destructor Documentation
org.jgap.gp.function.TransferMemory.TransferMemory (final GPConfiguration a_conf, String a_sourceStorageName, String a_targetStorageName) throws InvalidConfigurationException [inline]
Definition at line 37 of file TransferMemory.java.
References org.jgap.gp.function.TransferMemory.m_sourceStorageName, org.jgap.gp.function.TransferMemory.m_targetStorageName, and org.jgap.gp.CommandGene.VoidClass.
Referenced by org.jgap.gp.function.TransferMemory.clone(), org.jgap.gp.function.TransferMemory.compareTo(), and org.jgap.gp.function.TransferMemory.equals().
Member Function Documentation
Object org.jgap.gp.function.TransferMemory.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 154 of file TransferMemory.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.function.TransferMemory.m_sourceStorageName, org.jgap.gp.function.TransferMemory.m_targetStorageName, and org.jgap.gp.function.TransferMemory.TransferMemory().
int org.jgap.gp.function.TransferMemory.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.0
Definition at line 113 of file TransferMemory.java.
References org.jgap.gp.function.TransferMemory.m_sourceStorageName, org.jgap.gp.function.TransferMemory.m_targetStorageName, and org.jgap.gp.function.TransferMemory.TransferMemory().
boolean org.jgap.gp.function.TransferMemory.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Klaus Meffert
Since
3.0
Definition at line 134 of file TransferMemory.java.
References org.jgap.gp.function.TransferMemory.m_sourceStorageName, org.jgap.gp.function.TransferMemory.m_targetStorageName, and org.jgap.gp.function.TransferMemory.TransferMemory().
void org.jgap.gp.function.TransferMemory.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 76 of file TransferMemory.java.
References org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.function.TransferMemory.m_sourceStorageName, and org.jgap.gp.function.TransferMemory.m_targetStorageName.
Class org.jgap.gp.function.TransferMemory.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Definition at line 100 of file TransferMemory.java.
String org.jgap.gp.function.TransferMemory.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 72 of file TransferMemory.java.
boolean org.jgap.gp.function.TransferMemory.isAffectGlobalState () [inline]
Todo
Todo subclass from new abstract class MemoryCommand?
Definition at line 91 of file TransferMemory.java.
boolean org.jgap.gp.function.TransferMemory.isValid (ProgramChromosome a_program) [inline]
Definition at line 96 of file TransferMemory.java.
String org.jgap.gp.function.TransferMemory.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 58 of file TransferMemory.java.
References org.jgap.gp.function.TransferMemory.m_sourceStorageName, and org.jgap.gp.function.TransferMemory.m_targetStorageName.
Member Data Documentation
final String org.jgap.gp.function.TransferMemory.CVS_REVISION = `$Revision: 1.12 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file TransferMemory.java.
String org.jgap.gp.function.TransferMemory.m_sourceStorageName [private]
Symbolic name of the storage. Must correspond with a chosen name for ReadTerminalCommand.
Definition at line 33 of file TransferMemory.java.
Referenced by org.jgap.gp.function.TransferMemory.clone(), org.jgap.gp.function.TransferMemory.compareTo(), org.jgap.gp.function.TransferMemory.equals(), org.jgap.gp.function.TransferMemory.execute_void(), org.jgap.gp.function.TransferMemory.toString(), and org.jgap.gp.function.TransferMemory.TransferMemory().
String org.jgap.gp.function.TransferMemory.m_targetStorageName [private]
Definition at line 35 of file TransferMemory.java.
Referenced by org.jgap.gp.function.TransferMemory.clone(), org.jgap.gp.function.TransferMemory.compareTo(), org.jgap.gp.function.TransferMemory.equals(), org.jgap.gp.function.TransferMemory.execute_void(), org.jgap.gp.function.TransferMemory.toString(), and org.jgap.gp.function.TransferMemory.TransferMemory().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/TransferMemory.java