org.jgap.Chromosome Class Reference
Public Member Functions
Chromosome () throws InvalidConfigurationException
Chromosome (final Configuration a_configuration) throws InvalidConfigurationException
Chromosome (final Configuration a_configuration, String a_persistentRepresentatuion) throws InvalidConfigurationException, UnsupportedRepresentationException
Chromosome (final Configuration a_configuration, final int a_desiredSize) throws InvalidConfigurationException
Chromosome (final Configuration a_configuration, final Gene a_sampleGene, final int a_desiredSize) throws InvalidConfigurationException
Chromosome (final Configuration a_configuration, Gene a_sampleGene, int a_desiredSize, IGeneConstraintChecker a_constraintChecker) throws InvalidConfigurationException
Chromosome (final Configuration a_configuration, Gene[] a_initialGenes) throws InvalidConfigurationException
Chromosome (final Configuration a_configuration, Gene[] a_initialGenes, IGeneConstraintChecker a_constraintChecker) throws InvalidConfigurationException
synchronized Object clone ()
double getFitnessValue ()
double getFitnessValueDirectly ()
void setFitnessValue (double a_newFitnessValue)
void setFitnessValueDirectly (double a_newFitnessValue)
String toString ()
boolean equals (Object other)
int hashCode ()
int compareTo (Object other)
void setIsSelectedForNextGeneration (boolean a_isSelected)
boolean isSelectedForNextGeneration ()
void cleanup ()
void setApplicationData (Object a_newData)
Object getApplicationData ()
void setGenes (Gene[] a_genes) throws InvalidConfigurationException
void setCompareApplicationData (boolean a_doCompare)
boolean isCompareApplicationData ()
void setConstraintChecker (IGeneConstraintChecker a_constraintChecker) throws InvalidConfigurationException
IGeneConstraintChecker getConstraintChecker ()
boolean isHandlerFor (Object a_obj, Class a_class)
Object perform (Object a_obj, Class a_class, Object a_params) throws Exception
void setMultiObjectives (List a_values)
List getMultiObjectives ()
Static Public Member Functions
static Object cloneObject (Configuration a_config, Object a_object, Object a_master) throws Exception
static IChromosome randomInitialChromosome (Configuration a_configuration) throws InvalidConfigurationException
Protected Member Functions
void initFromGene (Gene a_sampleGene)
void checkGenes (Gene[] a_initialGenes)
Object cloneObject (Object a_object) throws Exception
double calcFitnessValue ()
void verify (IGeneConstraintChecker a_constraintChecker) throws InvalidConfigurationException
Protected Attributes
double m_fitnessValue = FitnessFunction.NO_FITNESS_VALUE
Private Attributes
Object m_applicationData
List m_multiObjective
boolean m_isSelectedForNextGeneration
boolean m_compareAppData
IGeneConstraintChecker m_geneAlleleChecker
boolean m_alwaysCalculate
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.105 $`
Additional Inherited Members
Detailed Description
Chromosomes represent potential solutions and consist of a fixed-length collection of genes. Each gene represents a discrete part of the solution. Each gene in the Chromosome may be backed by a different concrete implementation of the Gene interface, but all genes in a respective position (locus) must share the same concrete implementation across Chromosomes within a single population (genotype). In other words, gene 1 in a chromosome must share the same concrete implementation as gene 1 in all other chromosomes in the population.
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 65 of file Chromosome.java.
Constructor & Destructor Documentation
org.jgap.Chromosome.Chromosome () throws InvalidConfigurationException [inline]
Default constructor, only provided for dynamic instantiation.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.4
Definition at line 141 of file Chromosome.java.
Referenced by org.jgap.Chromosome.clone(), and org.jgap.Chromosome.randomInitialChromosome().
org.jgap.Chromosome.Chromosome (final Configuration a_configuration) throws InvalidConfigurationException [inline]
Constructor, provided for dynamic or minimal instantiation.
Parameters
a_configuration the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 155 of file Chromosome.java.
References org.jgap.Chromosome.m_alwaysCalculate.
org.jgap.Chromosome.Chromosome (final Configuration a_configuration, String a_persistentRepresentatuion) throws InvalidConfigurationException, UnsupportedRepresentationException [inline]
Constructor, provided for instantiation via persistent representation.
Parameters
a_configuration the configuration to use
a_persistentRepresentatuion valid persistent representation that was most likely obtained via getPersistentRepresentation()
Exceptions
InvalidConfigurationException
UnsupportedRepresentationException
Author
Klaus Meffert
Since
3.2
Definition at line 173 of file Chromosome.java.
References org.jgap.BaseChromosome.setValueFromPersistentRepresentation().
org.jgap.Chromosome.Chromosome (final Configuration a_configuration, final int a_desiredSize) throws InvalidConfigurationException [inline]
Constructor for specifying the number of genes.
Parameters
a_configuration the configuration to use
a_desiredSize number of genes the chromosome contains of
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.2
Definition at line 190 of file Chromosome.java.
References org.jgap.Chromosome.setGenes().
org.jgap.Chromosome.Chromosome (final Configuration a_configuration, final Gene a_sampleGene, final int a_desiredSize) throws InvalidConfigurationException [inline]
Constructs a Chromosome of the given size separate from any specific Configuration. This constructor will use the given sample Gene to construct a new Chromosome instance containing genes all of the same type as the sample Gene. This can be useful for constructing sample chromosomes that use the same Gene type for all of their genes and that are to be used to setup a Configuration object.
Parameters
a_configuration the configuration to use
a_sampleGene a concrete sampleGene instance that will be used as a template for all of the genes in this Chromosome
a_desiredSize the desired size (number of genes) of this Chromosome
Exceptions
InvalidConfigurationException
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 219 of file Chromosome.java.
References org.jgap.Chromosome.initFromGene().
org.jgap.Chromosome.Chromosome (final Configuration a_configuration, Gene a_sampleGene, int a_desiredSize, IGeneConstraintChecker a_constraintChecker) throws InvalidConfigurationException [inline]
Definition at line 226 of file Chromosome.java.
References org.jgap.Chromosome.initFromGene(), and org.jgap.Chromosome.setConstraintChecker().
org.jgap.Chromosome.Chromosome (final Configuration a_configuration, Gene[] a_initialGenes) throws InvalidConfigurationException [inline]
Constructs a Chromosome separate from any specific Configuration. This can be useful for constructing sample chromosomes that are to be used to setup a Configuration object.
Parameters
a_configuration the configuration to use
a_initialGenes the initial genes of this Chromosome
Exceptions
InvalidConfigurationException
Author
Neil Rotstan
Since
1.0
Definition at line 264 of file Chromosome.java.
References org.jgap.Chromosome.checkGenes(), and org.jgap.Chromosome.setGenes().
org.jgap.Chromosome.Chromosome (final Configuration a_configuration, Gene[] a_initialGenes, IGeneConstraintChecker a_constraintChecker) throws InvalidConfigurationException [inline]
Constructs a Chromosome separate from any specific Configuration. This can be useful for constructing sample chromosomes that are to be used to setup a Configuration object. Additionally, a constraint checker can be specified. It is used right here to verify the validity of the gene types supplied.
Parameters
a_configuration the configuration to use
a_initialGenes the initial genes of this Chromosome
a_constraintChecker constraint checker to use
Exceptions
InvalidConfigurationException in case the constraint checker reports a configuration error
Author
Klaus Meffert
Since
2.5
Definition at line 287 of file Chromosome.java.
References org.jgap.Chromosome.checkGenes(), org.jgap.Chromosome.setConstraintChecker(), and org.jgap.Chromosome.setGenes().
Member Function Documentation
double org.jgap.Chromosome.calcFitnessValue () [inline], [protected]
Returns
fitness value of this chromosome determined via the registered fitness function
Author
Klaus Meffert
Since
2.4
Definition at line 560 of file Chromosome.java.
References org.jgap.BaseChromosome.getConfiguration(), and org.jgap.Chromosome.m_fitnessValue.
Referenced by org.jgap.Chromosome.getFitnessValue().
void org.jgap.Chromosome.checkGenes (Gene[] a_initialGenes) [inline], [protected]
Helper: called by constructors only to verify the initial genes.
Parameters
a_initialGenes the initial genes of this Chromosome to verify
Author
Klaus Meffert
Since
2.5
Definition at line 304 of file Chromosome.java.
Referenced by org.jgap.Chromosome.Chromosome().
void org.jgap.Chromosome.cleanup () [inline]
Invoked when this Chromosome is no longer needed and should perform any necessary cleanup. Note that this method will attempt to release this Chromosome instance to the active ChromosomePool, if any.
Author
Neil Rotstan
Since
1.0
Implements org.jgap.IChromosome.
Definition at line 928 of file Chromosome.java.
References org.jgap.BaseChromosome.getConfiguration(), org.jgap.BaseChromosome.getGene(), org.jgap.Chromosome.m_fitnessValue, org.jgap.Chromosome.m_isSelectedForNextGeneration, and org.jgap.BaseChromosome.size().
synchronized Object org.jgap.Chromosome.clone () [inline], [virtual]
Returns a copy of this Chromosome. The returned instance can evolve independently of this instance. Note that, if possible, this method will first attempt to acquire a Chromosome instance from the active ChromosomePool (if any) and set its value appropriately before returning it. If that is not possible, then a new Chromosome instance will be constructed and its value set appropriately before returning.
Returns
copy of this Chromosome
Exceptions
IllegalStateException instead of CloneNotSupportedException
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Todo
Todo once output a warning: allele should be cloneable!
Implements org.jgap.BaseChromosome.
Reimplemented in org.jgap.ChromosomeForTesting.
Definition at line 334 of file Chromosome.java.
References org.jgap.Chromosome.Chromosome(), org.jgap.Chromosome.cloneObject(), org.jgap.Chromosome.getApplicationData(), org.jgap.BaseChromosome.getConfiguration(), org.jgap.Chromosome.getConstraintChecker(), org.jgap.BaseChromosome.getGene(), org.jgap.Chromosome.m_fitnessValue, org.jgap.Chromosome.m_multiObjective, and org.jgap.BaseChromosome.size().
Referenced by org.jgap.impl.GABreeder.bulkFunctionEvaluation(), org.jgap.ChromosomeTest.testClone_1(), org.jgap.ChromosomeTest.testClone_2(), org.jgap.ChromosomeTest.testClone_4(), org.jgap.ChromosomeTest.testClone_5(), org.jgap.ChromosomeTest.testClone_6(), org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_1(), org.jgap.impl.GaussianMutationOperatorTest.testOperate_1(), org.jgap.impl.InversionOperatorTest.testOperate_1(), and org.jgap.impl.CrossoverOperatorTest.testOperate_1().
Object org.jgap.Chromosome.cloneObject (Object a_object) throws Exception [inline], [protected]
Clones an object by using clone handlers. If no deep cloning possible, then return the reference.
Parameters
a_object the object to clone
Returns
the cloned object, or the object itself if no coning supported
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 478 of file Chromosome.java.
References org.jgap.BaseChromosome.getConfiguration().
Referenced by org.jgap.Chromosome.clone(), and org.jgap.Chromosome.randomInitialChromosome().
static Object org.jgap.Chromosome.cloneObject (Configuration a_config, Object a_object, Object a_master) throws Exception [inline], [static]
Static convenience method. Clones an object by using clone handlers. If no deep cloning possible, then return the reference.
Parameters
a_config a valid configuration to obtain the JGAPFactory from
a_object the object to clone
a_master the super object of a_object, e.g. a chromosome in case of application to be cloned
Returns
the cloned object, or the object itself if no coning supported
Exceptions
Exception
Author
Klaus Meffert
Since
3.5
Definition at line 498 of file Chromosome.java.
int org.jgap.Chromosome.compareTo (Object other) [inline]
Compares the given Chromosome to this Chromosome. This chromosome is considered to be `less than` the given chromosome if it has a fewer number of genes or if any of its gene values (alleles) are less than their corresponding gene values in the other chromosome.
Parameters
other the Chromosome against which to compare this chromosome
Returns
a negative number if this chromosome is `less than` the given chromosome, zero if they are equal to each other, and a positive number if this chromosome is `greater than` the given chromosome
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Todo
Todo improve
Definition at line 816 of file Chromosome.java.
References org.jgap.IChromosome.getApplicationData(), org.jgap.Chromosome.getApplicationData(), org.jgap.BaseChromosome.getConfiguration(), org.jgap.IChromosome.getFitnessValueDirectly(), org.jgap.BaseChromosome.getGene(), org.jgap.FitnessEvaluator.isFitter(), org.jgap.Chromosome.m_compareAppData, org.jgap.Chromosome.m_fitnessValue, org.jgap.IChromosome.size(), and org.jgap.BaseChromosome.size().
Referenced by org.jgap.Chromosome.equals(), org.jgap.ChromosomeTest.testCompareTo_1(), org.jgap.ChromosomeTest.testCompareTo_2(), org.jgap.ChromosomeTest.testCompareTo_3(), and org.jgap.ChromosomeTest.testCompareTo_4().
boolean org.jgap.Chromosome.equals (Object other) [inline]
Compares this Chromosome against the specified object. The result is true if and the argument is an instance of the Chromosome class and has a set of genes equal to this one.
Parameters
other the object to compare against
Returns
true: if the objects are the same, false otherwise
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 751 of file Chromosome.java.
References org.jgap.Chromosome.compareTo().
Referenced by org.jgap.ChromosomeTest.testEquals_0(), org.jgap.ChromosomeTest.testEquals_1(), org.jgap.ChromosomeTest.testEquals_2(), org.jgap.ChromosomeTest.testEquals_3(), org.jgap.xml.XMLManagerTest.testGetChromosomeFromDocument_1(), and org.jgap.PopulationTest.testSetChromosome_1().
Object org.jgap.Chromosome.getApplicationData () [inline]
Retrieves the application-specific data that is attached to this Chromosome. Attaching application-specific data may be useful for some applications when it comes time to evaluate this Chromosome in the fitness function. JGAP ignores this data functionally.
Returns
the application-specific data previously attached to this Chromosome, or null if there is no data attached
Author
Neil Rotstan
Since
1.1
Implements org.jgap.IChromosome.
Definition at line 993 of file Chromosome.java.
References org.jgap.Chromosome.m_applicationData.
Referenced by org.jgap.Chromosome.clone(), org.jgap.Chromosome.compareTo(), and org.jgap.Chromosome.toString().
IGeneConstraintChecker org.jgap.Chromosome.getConstraintChecker () [inline]
Returns
IGeneConstraintChecker the constraint checker to be used whenever method setGenes(Gene[]) is called.
Author
Klaus Meffert
Since
2.5
Definition at line 1059 of file Chromosome.java.
References org.jgap.Chromosome.m_geneAlleleChecker.
Referenced by org.jgap.Chromosome.clone(), org.jgap.Chromosome.setGenes(), org.jgap.ChromosomeTest.testSetConstraintChecker_0(), org.jgap.ChromosomeTest.testSetConstraintChecker_1(), and org.jgap.ChromosomeTest.testSetConstraintChecker_2().
double org.jgap.Chromosome.getFitnessValue () [inline]
Retrieves the fitness value of this Chromosome, as determined by the active fitness function. If a bulk fitness function is in use and has not yet assigned a fitness value to this Chromosome, then -1 is returned.
Attention: should not be called from toString() as the fitness value would be computed if it was initial!
Returns
a positive double value representing the fitness of this Chromosome, or -1 if a bulk fitness function is in use and has not yet assigned a fitness value to this Chromosome
Author
Neil Rotstan
Klaus Meffert
Since
2.0
Implements org.jgap.IChromosome.
Definition at line 534 of file Chromosome.java.
References org.jgap.Chromosome.calcFitnessValue(), org.jgap.Chromosome.m_alwaysCalculate, and org.jgap.Chromosome.m_fitnessValue.
Referenced by org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_3(), and org.jgap.impl.BulkFitnessOffsetRemoverTest.testGetAbsoluteFitness_0().
double org.jgap.Chromosome.getFitnessValueDirectly () [inline]
Returns
the lastly computed fitness value, or FitnessFunction.NO_FITNESS_VALUE in case no value has been computed yet.
Author
Klaus Meffert
Implements org.jgap.IChromosome.
Definition at line 549 of file Chromosome.java.
References org.jgap.Chromosome.m_fitnessValue.
List org.jgap.Chromosome.getMultiObjectives () [inline]
Definition at line 1121 of file Chromosome.java.
References org.jgap.Chromosome.m_multiObjective.
Referenced by org.jgap.ChromosomeTest.testSetMultiObjectives_0().
int org.jgap.Chromosome.hashCode () [inline]
Retrieve a hash code for this Chromosome. Does not considers the order of the Genes for all cases (especially when gene is empty).
Returns
the hash code of this Chromosome
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 780 of file Chromosome.java.
References org.jgap.BaseChromosome.getGene(), org.jgap.BaseChromosome.getGenes(), and org.jgap.BaseChromosome.size().
void org.jgap.Chromosome.initFromGene (Gene a_sampleGene) [inline], [protected]
Definition at line 235 of file Chromosome.java.
References org.jgap.Gene.newGene(), org.jgap.BaseChromosome.setGene(), and org.jgap.BaseChromosome.size().
Referenced by org.jgap.Chromosome.Chromosome().
boolean org.jgap.Chromosome.isCompareApplicationData () [inline]
Definition at line 1032 of file Chromosome.java.
References org.jgap.Chromosome.m_compareAppData.
Referenced by org.jgap.ChromosomeTest.testSetCompareApplicationData_0().
boolean org.jgap.Chromosome.isHandlerFor (Object a_obj, Class a_class) [inline]
Determines whether the handler is suitable for the given object instance or class.
Parameters
a_obj the object instance to check
a_class the class to check, alternatively if no object instance is available (some handlers could need to get an object and would always return false if only a class is provided)
Returns
true: handler suitable for given object or class
Author
Klaus Meffert
Since
2.6
Implements org.jgap.IHandler.
Definition at line 1095 of file Chromosome.java.
Referenced by org.jgap.ChromosomeTest.testIsHandlerFor_0().
boolean org.jgap.Chromosome.isSelectedForNextGeneration () [inline]
Retrieves whether this Chromosome has been selected by the natural selector to continue to the next generation.
Returns
true if this Chromosome has been selected, false otherwise
Author
Neil Rotstan
Since
1.0
Implements org.jgap.IChromosome.
Definition at line 916 of file Chromosome.java.
References org.jgap.Chromosome.m_isSelectedForNextGeneration.
Object org.jgap.Chromosome.perform (Object a_obj, Class a_class, Object a_params) throws Exception [inline]
Performs a task for the given object or class. For some handlers, additional parameters are necessary, which could be provided.
Parameters
a_obj the object instance to perform the handler task for
a_class the class to perform the handler task for, in case no object instance is available (some handlers could need to get an object and would always throw an exception if only a class is provided)
a_params optional parameters needed for the handler to perform its task
Exceptions
Exception in case of any error
Returns
Object
Author
Klaus Meffert
Since
2.6
Implements org.jgap.IHandler.
Definition at line 1105 of file Chromosome.java.
References org.jgap.BaseChromosome.getConfiguration(), and org.jgap.Chromosome.randomInitialChromosome().
Referenced by org.jgap.ChromosomeTest.testIsHandlerFor_0().
static IChromosome org.jgap.Chromosome.randomInitialChromosome (Configuration a_configuration) throws InvalidConfigurationException [inline], [static]
Convenience method that returns a new Chromosome instance with its genes values (alleles) randomized. Note that, if possible, this method will acquire a Chromosome instance from the active ChromosomePool (if any) and then randomize its gene values before returning it. If a Chromosome cannot be acquired from the pool, then a new instance will be constructed and its gene values randomized before returning it.
Parameters
a_configuration the configuration to use
Returns
randomly initialized Chromosome
Exceptions
InvalidConfigurationException if the given Configuration instance is invalid
IllegalArgumentException if the given Configuration instance is null
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Todo
Todo what about Gene's energy?
Todo
Todo what about Gene's energy?
Definition at line 668 of file Chromosome.java.
References org.jgap.Chromosome.Chromosome(), org.jgap.Chromosome.cloneObject(), and org.jgap.FitnessFunction.NO_FITNESS_VALUE.
Referenced by org.jgap.Chromosome.perform(), and org.jgap.ChromosomeTest.testSetCompareApplicationData_0().
void org.jgap.Chromosome.setApplicationData (Object a_newData) [inline]
This sets the application-specific data that is attached to this Chromosome. Attaching application-specific data may be useful for some applications when it comes time to evaluate this Chromosome in the fitness function. JGAP ignores this data, except for cloning and comparison (latter only if opted in via setCompareApplicationData(..))
Parameters
a_newData the new application-specific data to attach to this Chromosome. Should be an instance of IApplicationData
Author
Neil Rotstan
Since
1.1
Implements org.jgap.IChromosome.
Definition at line 977 of file Chromosome.java.
References org.jgap.Chromosome.m_applicationData.
void org.jgap.Chromosome.setCompareApplicationData (boolean a_doCompare) [inline]
Should we also consider the application data when comparing? Default is `false` as `true` means a Chromosome is losing its identity when application data is set differently!
Parameters
a_doCompare true: consider application data in method compareTo
Author
Klaus Meffert
Since
2.2
Definition at line 1022 of file Chromosome.java.
References org.jgap.Chromosome.m_compareAppData.
void org.jgap.Chromosome.setConstraintChecker (IGeneConstraintChecker a_constraintChecker) throws InvalidConfigurationException [inline]
Sets the constraint checker to be used for this gene whenever method setAllele(Object) is called.
Parameters
a_constraintChecker the constraint checker to be set
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.5
Implements org.jgap.IChromosome.
Definition at line 1046 of file Chromosome.java.
References org.jgap.Chromosome.m_geneAlleleChecker, and org.jgap.Chromosome.verify().
Referenced by org.jgap.Chromosome.Chromosome().
void org.jgap.Chromosome.setFitnessValue (double a_newFitnessValue) [inline]
Sets the fitness value of this Chromosome. This method is for use by bulk fitness functions and should not be invoked from anything else (except test cases).
Parameters
a_newFitnessValue a positive integer representing the fitness of this Chromosome
Author
Neil Rotstan
Since
1.0
Implements org.jgap.IChromosome.
Definition at line 585 of file Chromosome.java.
References org.jgap.Chromosome.m_fitnessValue.
void org.jgap.Chromosome.setFitnessValueDirectly (double a_newFitnessValue) [inline]
Sets the fitness value of this Chromosome directly without any constraint checks, conversions or checks. Only use if you know what you do.
Parameters
a_newFitnessValue a positive integer representing the fitness of this Chromosome
Author
Klaus Meffert
Implements org.jgap.IChromosome.
Definition at line 602 of file Chromosome.java.
References org.jgap.Chromosome.m_fitnessValue.
void org.jgap.Chromosome.setGenes (Gene[] a_genes) throws InvalidConfigurationException [inline]
Sets the genes for the chromosome.
Parameters
a_genes the genes to set for the chromosome
Exceptions
InvalidConfigurationException in case constraint checker is provided
Author
Klaus Meffert
Implements org.jgap.IChromosome.
Definition at line 1006 of file Chromosome.java.
References org.jgap.Chromosome.getConstraintChecker(), and org.jgap.Chromosome.verify().
Referenced by org.jgap.Chromosome.Chromosome().
void org.jgap.Chromosome.setIsSelectedForNextGeneration (boolean a_isSelected) [inline]
Sets whether this Chromosome has been selected by the natural selector to continue to the next generation or manually (e.g. via an add-method).
Parameters
a_isSelected true if this Chromosome has been selected, false otherwise
Author
Neil Rotstan
Since
1.0
Implements org.jgap.IChromosome.
Definition at line 903 of file Chromosome.java.
References org.jgap.Chromosome.m_isSelectedForNextGeneration.
void org.jgap.Chromosome.setMultiObjectives (List a_values) [inline]
Definition at line 1113 of file Chromosome.java.
References org.jgap.Chromosome.m_multiObjective.
String org.jgap.Chromosome.toString () [inline]
Returns
a string representation of this Chromosome, useful for display purposes
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 614 of file Chromosome.java.
References org.jgap.Chromosome.getApplicationData(), org.jgap.BaseChromosome.getGene(), org.jgap.Chromosome.m_fitnessValue, org.jgap.IChromosome.S_ALLELES, org.jgap.IChromosome.S_APPLICATION_DATA, org.jgap.IChromosome.S_FITNESS_VALUE, org.jgap.IChromosome.S_SIZE, and org.jgap.BaseChromosome.size().
void org.jgap.Chromosome.verify (IGeneConstraintChecker a_constraintChecker) throws InvalidConfigurationException [inline], [protected]
Verifies the state of the chromosome. Especially takes care of the given constraint checker.
Parameters
a_constraintChecker the constraint checker to verify
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.5
Definition at line 1073 of file Chromosome.java.
References org.jgap.BaseChromosome.getGene(), and org.jgap.BaseChromosome.getGenes().
Referenced by org.jgap.Chromosome.setConstraintChecker(), and org.jgap.Chromosome.setGenes().
Member Data Documentation
final String org.jgap.Chromosome.CVS_REVISION = `$Revision: 1.105 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 68 of file Chromosome.java.
boolean org.jgap.Chromosome.m_alwaysCalculate [private]
If set to true the method getFitnessValue() will always (re-)calculate the fitness value. This may be necessary in case of environments where the state changes without the chromosome to notice
Since
3.2.2
Definition at line 129 of file Chromosome.java.
Referenced by org.jgap.Chromosome.Chromosome(), and org.jgap.Chromosome.getFitnessValue().
Object org.jgap.Chromosome.m_applicationData [private]
Application-specific data that is attached to this Chromosome. This data may assist the application in evaluating this Chromosome in the fitness function. JGAP does not operate on the data, aside from allowing it to be set and retrieved, and considering it with comparations (if user opted in to do so).
Definition at line 77 of file Chromosome.java.
Referenced by org.jgap.Chromosome.getApplicationData(), and org.jgap.Chromosome.setApplicationData().
boolean org.jgap.Chromosome.m_compareAppData [private]
Method compareTo(): Should we also consider the application data when comparing? Default is `false`, as `true` means a Chromosome's losing its identity when application data is set differently!
Since
2.2
Definition at line 111 of file Chromosome.java.
Referenced by org.jgap.Chromosome.compareTo(), org.jgap.Chromosome.isCompareApplicationData(), and org.jgap.Chromosome.setCompareApplicationData().
double org.jgap.Chromosome.m_fitnessValue = FitnessFunction.NO_FITNESS_VALUE [protected]
Stores the fitness value of this Chromosome as determined by the active fitness function. A value of -1 indicates that this field has not yet been set with this Chromosome's fitness values (valid fitness values are always positive).
Since
2.0 (until 1.1: type int)
Definition at line 102 of file Chromosome.java.
Referenced by org.jgap.Chromosome.calcFitnessValue(), org.jgap.Chromosome.cleanup(), org.jgap.Chromosome.clone(), org.jgap.Chromosome.compareTo(), org.jgap.ChromosomeForTesting.getFitnessValue(), org.jgap.Chromosome.getFitnessValue(), org.jgap.Chromosome.getFitnessValueDirectly(), org.jgap.Chromosome.setFitnessValue(), org.jgap.Chromosome.setFitnessValueDirectly(), and org.jgap.Chromosome.toString().
IGeneConstraintChecker org.jgap.Chromosome.m_geneAlleleChecker [private]
Optional helper class for checking if a given allele value to be set for a given gene is valid. If not, the allele value may not be set for the gene or the gene type (e.g. IntegerGene) is not allowed in general!
Since
2.5
Definition at line 120 of file Chromosome.java.
Referenced by org.jgap.Chromosome.getConstraintChecker(), and org.jgap.Chromosome.setConstraintChecker().
boolean org.jgap.Chromosome.m_isSelectedForNextGeneration [private]
Keeps track of whether or not this Chromosome has been selected by the natural selector to move on to the next generation.
Definition at line 92 of file Chromosome.java.
Referenced by org.jgap.Chromosome.cleanup(), org.jgap.Chromosome.isSelectedForNextGeneration(), and org.jgap.Chromosome.setIsSelectedForNextGeneration().
List org.jgap.Chromosome.m_multiObjective [private]
Holds multiobjective values.
Since
2.6
Todo
Todo move to new subclass of Chromosome (and introduce new interface IMultiObjective with that)
Definition at line 86 of file Chromosome.java.
Referenced by org.jgap.Chromosome.clone(), org.jgap.Chromosome.getMultiObjectives(), and org.jgap.Chromosome.setMultiObjectives().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/Chromosome.java