org.jgap.impl.CompositeGene Class Reference
Public Member Functions
CompositeGene () throws InvalidConfigurationException
CompositeGene (Configuration a_config) throws InvalidConfigurationException
CompositeGene (final Configuration a_config, final Gene a_geneTypeAllowed) throws InvalidConfigurationException
void addGene (final Gene a_gene)
Gene getGeneTypeAllowed ()
void addGene (final Gene a_gene, final boolean a_strict)
boolean removeGeneByIdentity (final Gene a_gene)
boolean removeGene (final Gene a_gene)
void cleanup ()
void setToRandomValue (final RandomGenerator a_numberGenerator)
void setValueFromPersistentRepresentation (String a_representation) throws UnsupportedRepresentationException
String getPersistentRepresentation () throws UnsupportedOperationException
Object getAllele ()
void setAllele (Object a_newValue)
int compareTo (Object a_other)
String toString ()
boolean isEmpty ()
Gene geneAt (int a_index)
List< Gene > getGenes ()
int size ()
boolean containsGeneByIdentity (Gene gene)
void applyMutation (int a_index, double a_percentage)
int hashCode ()
String getBusinessKey ()
Static Public Attributes
static final String GENE_DELIMITER = `#`
static final String GENE_DELIMITER_HEADING = `<`
static final String GENE_DELIMITER_CLOSING = `>`
Protected Member Functions
Gene createGene (String a_geneClassName, String a_persistentRepresentation) throws Exception
Gene newGeneInternal ()
Object getInternalValue ()
Static Protected Member Functions
static final List split (String a_string) throws UnsupportedRepresentationException
Private Attributes
Gene m_geneTypeAllowed
List< Gene > m_genes
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.60 $`
Detailed Description
Ordered container for multiple genes Has the same interface as a single gene and could be used accordingly. Use the addGene(Gene) method to add single genes (possibly CompositeGenes) after construction, an empty CompositeGene without genes makes no sense. Beware that there are two equalities defined for a CompositeGene in respect to its contained genes: a) Two genes are (only) equal if they are identical b) Two genes are (seen as) equal if their equals method returns true
This influences several methods such as addGene. Notice that it is safer to use addGene(a_gene, false) than addGene(a_gene, true) because the second variant only allows to add genes not seen as equal to already added genes in respect to their equals function. But: the equals function returns true for two different DoubleGenes (e.g.) just after their creation. If no specific (and hopefully different) allele is set for these DoubleGenes they are seen as equal!
Author
Klaus Meffert
Audrius Meskauskas
Since
1.1
Definition at line 38 of file CompositeGene.java.
Constructor & Destructor Documentation
org.jgap.impl.CompositeGene.CompositeGene () throws InvalidConfigurationException [inline]
Default constructor.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
1.1
Definition at line 82 of file CompositeGene.java.
Referenced by org.jgap.impl.CompositeGene.compareTo(), and org.jgap.impl.CompositeGene.newGeneInternal().
org.jgap.impl.CompositeGene.CompositeGene (Configuration a_config) throws InvalidConfigurationException [inline]
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 94 of file CompositeGene.java.
org.jgap.impl.CompositeGene.CompositeGene (final Configuration a_config, final Gene a_geneTypeAllowed) throws InvalidConfigurationException [inline]
Allows to specify which Gene implementation is allowed to be added to the CompositeGene.
Parameters
a_config the configuration to use
a_geneTypeAllowed the class of Genes to be allowed to be added to the CompositeGene
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.0
Definition at line 112 of file CompositeGene.java.
References org.jgap.impl.CompositeGene.m_genes, and org.jgap.impl.CompositeGene.m_geneTypeAllowed.
Member Function Documentation
void org.jgap.impl.CompositeGene.addGene (final Gene a_gene) [inline]
Adds a gene to the CompositeGene.
Parameters
a_gene the gene to add
Definition at line 127 of file CompositeGene.java.
Referenced by org.jgap.impl.CompositeGene.setValueFromPersistentRepresentation().
void org.jgap.impl.CompositeGene.addGene (final Gene a_gene, final boolean a_strict) [inline]
Adds a gene to the CompositeGene's container. See comments in class header for additional details about equality (concerning `strict` param.)
Parameters
a_gene the gene to be added
a_strict false: add the given gene except the gene itself already is contained within the CompositeGene's container. true: add the gene if there is no other gene being equal to the given gene in request to the Gene's equals method
Author
Klaus Meffert
Since
1.1
Definition at line 154 of file CompositeGene.java.
References org.jgap.impl.CompositeGene.containsGeneByIdentity(), org.jgap.BaseGene.equals(), and org.jgap.impl.CompositeGene.m_geneTypeAllowed.
void org.jgap.impl.CompositeGene.applyMutation (int a_index, double a_percentage) [inline]
Don't use this method, is makes no sense here. It is just there to satisfy the Gene interface. Instead, loop over all contained genes and call their applyMutation method.
Parameters
a_index does not matter here
a_percentage does not matter here
Author
Klaus Meffert
Since
1.1
Implements org.jgap.Gene.
Definition at line 622 of file CompositeGene.java.
void org.jgap.impl.CompositeGene.cleanup () [inline]
Executed by the genetic engine when this Gene instance is no longer needed and should perform any necessary resource cleanup.
Author
Klaus Meffert
Since
1.1
Implements org.jgap.Gene.
Definition at line 231 of file CompositeGene.java.
References org.jgap.impl.CompositeGene.m_genes, and org.jgap.impl.CompositeGene.size().
int org.jgap.impl.CompositeGene.compareTo (Object a_other) [inline]
Compares this CompositeGene with the specified object for order. A false value is considered to be less than a true value. A null value is considered to be less than any non-null value.
Parameters
a_other the CompositeGene to be compared
Returns
a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than the specified object
Exceptions
ClassCastException if the specified object's type prevents it from being compared to this CompositeGene
Author
Klaus Meffert
Since
1.1
Definition at line 450 of file CompositeGene.java.
References org.jgap.BaseGene.compareApplicationData(), org.jgap.impl.CompositeGene.CompositeGene(), org.jgap.impl.CompositeGene.geneAt(), org.jgap.BaseGene.getApplicationData(), org.jgap.BaseGene.isCompareApplicationData(), org.jgap.impl.CompositeGene.isEmpty(), and org.jgap.impl.CompositeGene.size().
Referenced by org.jgap.impl.CompositeGeneTest.testCompareTo_0(), org.jgap.impl.CompositeGeneTest.testCompareTo_1(), org.jgap.impl.CompositeGeneTest.testCompareTo_2(), org.jgap.impl.CompositeGeneTest.testCompareTo_3_2(), org.jgap.impl.CompositeGeneTest.testCompareTo_4(), org.jgap.impl.CompositeGeneTest.testCompareTo_5(), and org.jgap.impl.CompositeGeneTest.testCompareTo_6().
boolean org.jgap.impl.CompositeGene.containsGeneByIdentity (Gene gene) [inline]
Checks whether a specific gene is already contained. The determination will be done by checking for identity and not using the equal method!
Parameters
gene the gene under test
Returns
true: the given gene object is contained
Author
Klaus Meffert
Since
1.1
Definition at line 592 of file CompositeGene.java.
References org.jgap.impl.CompositeGene.geneAt(), and org.jgap.impl.CompositeGene.size().
Referenced by org.jgap.impl.CompositeGene.addGene().
Gene org.jgap.impl.CompositeGene.createGene (String a_geneClassName, String a_persistentRepresentation) throws Exception [inline], [protected]
Creates a new instance of gene.
Parameters
a_geneClassName name of the gene class
a_persistentRepresentation persistent representation of the gene to create (could be obtained via getPersistentRepresentation)
Returns
newly created gene
Exceptions
Exception
Author
Klaus Meffert
Definition at line 319 of file CompositeGene.java.
References org.jgap.BaseGene.getConfiguration().
Referenced by org.jgap.impl.CompositeGene.setValueFromPersistentRepresentation().
Gene org.jgap.impl.CompositeGene.geneAt (int a_index) [inline]
Parameters
a_index index to return the gene at
Returns
the gene at the given index
Author
Klaus Meffert
Since
1.1
Implements org.jgap.ICompositeGene.
Definition at line 557 of file CompositeGene.java.
Referenced by org.jgap.impl.CompositeGene.compareTo(), org.jgap.impl.CompositeGene.containsGeneByIdentity(), org.jgap.impl.CompositeGene.hashCode(), org.jgap.impl.GaussianMutationOperator.operate(), org.jgap.impl.CompositeGene.removeGeneByIdentity(), org.jgap.impl.CompositeGeneTest.testGetGenes_1(), and org.jgap.impl.CompositeGeneTest.testPersistentPresentation_1().
Object org.jgap.impl.CompositeGene.getAllele () [inline]
Retrieves the value represented by this Gene. All values returned by this class will be Vector instances. Each element of the Vector represents the allele of the corresponding gene in the CompositeGene's container
Returns
the value of this Gene
Author
Klaus Meffert
Since
1.1
Implements org.jgap.Gene.
Definition at line 367 of file CompositeGene.java.
References org.jgap.impl.CompositeGene.m_genes, and org.jgap.impl.CompositeGene.size().
Referenced by org.jgap.impl.CompositeGeneTest.testGetAllele_1(), org.jgap.impl.CompositeGeneTest.testGetAllele_2(), org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_2(), org.jgap.impl.InversionOperatorTest.testOperate_2(), org.jgap.impl.CrossoverOperatorTest.testOperate_2(), and org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_4().
String org.jgap.impl.CompositeGene.getBusinessKey () [inline]
Returns
business key
Author
Klaus Meffert
Since
3.2
Implements org.jgap.IBusinessKey.
Definition at line 697 of file CompositeGene.java.
References org.jgap.impl.CompositeGene.GENE_DELIMITER_CLOSING, and org.jgap.impl.CompositeGene.GENE_DELIMITER_HEADING.
List<Gene> org.jgap.impl.CompositeGene.getGenes () [inline]
Returns
list of genes contained in the CompositeGene
Author
Klaus Meffert
Since
3.2.2
Definition at line 568 of file CompositeGene.java.
References org.jgap.impl.CompositeGene.m_genes.
Referenced by org.jgap.impl.CompositeGeneTest.testGetGenes_1().
Gene org.jgap.impl.CompositeGene.getGeneTypeAllowed () [inline]
Returns
the gene type allowed, or null if any type allowed
Author
Klaus Meffert
Since
2.4
Definition at line 137 of file CompositeGene.java.
References org.jgap.impl.CompositeGene.m_geneTypeAllowed.
Referenced by org.jgap.impl.CompositeGeneTest.testAddGene_2(), and org.jgap.impl.CompositeGeneTest.testConstruct_0().
Object org.jgap.impl.CompositeGene.getInternalValue () [inline], [protected], [virtual]
This method is not called internally because BaseGene.getAllele() is overridden here!
Returns
always null
Implements org.jgap.BaseGene.
Definition at line 692 of file CompositeGene.java.
Referenced by org.jgap.impl.CompositeGeneTest.testGetAllele_3().
String org.jgap.impl.CompositeGene.getPersistentRepresentation () throws UnsupportedOperationException [inline]
See interface Gene for description.
Returns
string representation of this Gene's current state
Exceptions
UnsupportedOperationException
Author
Klaus Meffert
Audrius Meskauskas
Since
1.1
Implements org.jgap.IPersistentRepresentation.
Definition at line 339 of file CompositeGene.java.
References org.jgap.BaseGene.encode(), org.jgap.impl.CompositeGene.GENE_DELIMITER, org.jgap.impl.CompositeGene.GENE_DELIMITER_CLOSING, and org.jgap.impl.CompositeGene.GENE_DELIMITER_HEADING.
int org.jgap.impl.CompositeGene.hashCode () [inline]
Retrieves the hash code value for this Gene.
Returns
this Gene's hash code
Author
Klaus Meffert
Since
2.2
Definition at line 677 of file CompositeGene.java.
References org.jgap.impl.CompositeGene.geneAt(), and org.jgap.impl.CompositeGene.size().
Referenced by org.jgap.impl.CompositeGeneTest.testHashCode_0().
boolean org.jgap.impl.CompositeGene.isEmpty () [inline]
Returns
true: no genes contained, false otherwise
Author
Klaus Meffert
Since
1.1
Definition at line 546 of file CompositeGene.java.
Referenced by org.jgap.impl.CompositeGene.compareTo().
Gene org.jgap.impl.CompositeGene.newGeneInternal () [inline], [protected], [virtual]
Provides an implementation-independent means for creating new Gene instances.
Returns
a new Gene instance of the same type and with the same setup as this concrete Gene
Author
Klaus Meffert
Since
1.1
Implements org.jgap.BaseGene.
Definition at line 418 of file CompositeGene.java.
References org.jgap.impl.CompositeGene.CompositeGene(), org.jgap.BaseGene.getConfiguration(), org.jgap.BaseGene.getConstraintChecker(), and org.jgap.impl.CompositeGene.m_genes.
boolean org.jgap.impl.CompositeGene.removeGene (final Gene a_gene) [inline]
Removes the given gene from the collection of genes. The gene is removed if another gene exists that is equal to the given gene in respect to the equals method of the gene.
Parameters
a_gene the gene to be removed
Returns
true: given gene found and removed
Author
Klaus Meffert
Since
1.1
Definition at line 220 of file CompositeGene.java.
boolean org.jgap.impl.CompositeGene.removeGeneByIdentity (final Gene a_gene) [inline]
Removes the given gene from the collection of genes. The gene is only removed if an object of the same identity is contained. The equals method is not used here intentionally.
Parameters
a_gene the gene to be removed
Returns
true: given gene found and removed
Author
Klaus Meffert
Since
1.1
Definition at line 193 of file CompositeGene.java.
References org.jgap.impl.CompositeGene.geneAt(), and org.jgap.impl.CompositeGene.size().
Referenced by org.jgap.impl.CompositeGeneTest.testRemoveGeneByIdentity_0(), and org.jgap.impl.CompositeGeneTest.testRemoveGeneByIdentity_1().
void org.jgap.impl.CompositeGene.setAllele (Object a_newValue) [inline]
Sets the value of the contained Genes to the new given value. This class expects the value to be of a Vector type. Each element of the Vector must conform with the type of the gene in the CompositeGene's container at the corresponding position.
Parameters
a_newValue the new value of this Gene instance
Author
Klaus Meffert
Since
1.1
Implements org.jgap.Gene.
Definition at line 389 of file CompositeGene.java.
References org.jgap.BaseGene.getConstraintChecker(), and org.jgap.impl.CompositeGene.m_genes.
void org.jgap.impl.CompositeGene.setToRandomValue (final RandomGenerator a_numberGenerator) [inline]
See interface Gene for description.
Parameters
a_numberGenerator the random number generator that should be used to create any random values. It's important to use this generator to maintain the user's flexibility to configure the genetic engine to use the random number generator of their choice
Author
Klaus Meffert
Since
1.1
Definition at line 251 of file CompositeGene.java.
References org.jgap.impl.CompositeGene.m_genes, and org.jgap.impl.CompositeGene.size().
void org.jgap.impl.CompositeGene.setValueFromPersistentRepresentation (String a_representation) throws UnsupportedRepresentationException [inline]
See interface Gene for description.
Parameters
a_representation the string representation retrieved from a prior call to the getPersistentRepresentation() method
Exceptions
UnsupportedRepresentationException
Author
Klaus Meffert
Audrius Meskauskas
Since
1.1
Implements org.jgap.IPersistentRepresentation.
Definition at line 275 of file CompositeGene.java.
References org.jgap.impl.CompositeGene.addGene(), org.jgap.impl.CompositeGene.createGene(), org.jgap.BaseGene.decode(), org.jgap.impl.CompositeGene.GENE_DELIMITER, and org.jgap.impl.CompositeGene.split().
int org.jgap.impl.CompositeGene.size () [inline]
Returns
the number of genes contained
Author
Klaus Meffert
Since
1.1
Implements org.jgap.Gene.
Definition at line 578 of file CompositeGene.java.
Referenced by org.jgap.impl.CompositeGene.cleanup(), org.jgap.impl.CompositeGene.compareTo(), org.jgap.impl.CompositeGene.containsGeneByIdentity(), org.jgap.impl.CompositeGene.getAllele(), org.jgap.impl.CompositeGene.hashCode(), org.jgap.impl.CompositeGene.removeGeneByIdentity(), org.jgap.impl.CompositeGene.setToRandomValue(), org.jgap.impl.CompositeGeneTest.testAddGene_0(), org.jgap.impl.CompositeGeneTest.testAddGene_1(), org.jgap.impl.CompositeGeneTest.testAddGene_2(), org.jgap.impl.CompositeGeneTest.testAddGene_4(), org.jgap.impl.CompositeGeneTest.testCleanup_0(), org.jgap.impl.CompositeGeneTest.testCleanup_1(), org.jgap.impl.CompositeGeneTest.testGetGenes_1(), org.jgap.impl.CompositeGeneTest.testPersistentPresentation_2(), org.jgap.impl.CompositeGeneTest.testPersistentPresentation_7(), and org.jgap.impl.CompositeGeneTest.testRemoveGeneByIdentity_1().
static final List org.jgap.impl.CompositeGene.split (String a_string) throws UnsupportedRepresentationException [inline], [static], [protected]
Splits a_string into individual gene representations.
Parameters
a_string the string to split
Returns
the elements of the returned array are the persistent representation strings of the gene's components
Exceptions
UnsupportedRepresentationException
Author
Audrius Meskauskas
Since
2.0
Definition at line 644 of file CompositeGene.java.
References org.jgap.impl.CompositeGene.GENE_DELIMITER_CLOSING, and org.jgap.impl.CompositeGene.GENE_DELIMITER_HEADING.
Referenced by org.jgap.impl.CompositeGene.setValueFromPersistentRepresentation().
String org.jgap.impl.CompositeGene.toString () [inline]
Retrieves a string representation of this CompositeGene's value that may be useful for display purposes.
Returns
string representation of this CompositeGene's value. Every contained gene's string representation is delimited by the given delimiter
Author
Neil Rotstan
Klaus Meffert
Audrius Meskauskas
Since
1.1
Implements org.jgap.Gene.
Definition at line 522 of file CompositeGene.java.
References org.jgap.impl.CompositeGene.GENE_DELIMITER, and org.jgap.impl.CompositeGene.m_genes.
Referenced by org.jgap.impl.CompositeGeneTest.testToString_0(), and org.jgap.impl.CompositeGeneTest.testToString_1().
Member Data Documentation
final String org.jgap.impl.CompositeGene.CVS_REVISION = `$Revision: 1.60 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 42 of file CompositeGene.java.
final String org.jgap.impl.CompositeGene.GENE_DELIMITER = `#` [static]
This field separates gene class name from the gene persistent representation string. '*' does not work properly with URLEncoder!
Definition at line 48 of file CompositeGene.java.
Referenced by org.jgap.impl.CompositeGenePersistentReprTest.createSampleNestedGene(), org.jgap.impl.CompositeGene.getPersistentRepresentation(), org.jgap.impl.CompositeGene.setValueFromPersistentRepresentation(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_5(), and org.jgap.impl.CompositeGene.toString().
final String org.jgap.impl.CompositeGene.GENE_DELIMITER_CLOSING = `>` [static]
Represents the closing delimiter that is used to separate genes in the persistent representation of CompositeGene instances.
Definition at line 60 of file CompositeGene.java.
Referenced by org.jgap.impl.CompositeGene.getBusinessKey(), org.jgap.impl.CompositeGene.getPersistentRepresentation(), and org.jgap.impl.CompositeGene.split().
final String org.jgap.impl.CompositeGene.GENE_DELIMITER_HEADING = `<` [static]
Represents the heading delimiter that is used to separate genes in the persistent representation of CompositeGene instances.
Definition at line 54 of file CompositeGene.java.
Referenced by org.jgap.impl.CompositeGene.getBusinessKey(), org.jgap.impl.CompositeGene.getPersistentRepresentation(), and org.jgap.impl.CompositeGene.split().
List<Gene> org.jgap.impl.CompositeGene.m_genes [private]
The genes contained in this CompositeGene
Author
Klaus Meffert
Since
1.1
Definition at line 70 of file CompositeGene.java.
Referenced by org.jgap.impl.CompositeGene.cleanup(), org.jgap.impl.CompositeGene.CompositeGene(), org.jgap.impl.CompositeGene.getAllele(), org.jgap.impl.CompositeGene.getGenes(), org.jgap.impl.CompositeGene.newGeneInternal(), org.jgap.impl.CompositeGene.setAllele(), org.jgap.impl.CompositeGene.setToRandomValue(), and org.jgap.impl.CompositeGene.toString().
Gene org.jgap.impl.CompositeGene.m_geneTypeAllowed [private]
Definition at line 62 of file CompositeGene.java.
Referenced by org.jgap.impl.CompositeGene.addGene(), org.jgap.impl.CompositeGene.CompositeGene(), and org.jgap.impl.CompositeGene.getGeneTypeAllowed().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/CompositeGene.java