org.jgap.impl.WeightedRouletteSelectorTest Class Reference
Public Member Functions
void setUp ()
void testConstruct_0 () throws Exception
void testAdd_0 () throws Exception
void testSelect_0 () throws Exception
void testSelect_1 () throws Exception
void testSelect_2 () throws Exception
void testSelect_3 () throws Exception
void testSelect_4 () throws Exception
void testEmpty_0 () throws Exception
void testEmpty_1 () throws Exception
void testEmpty_2 () throws Exception
void testReturnsUniqueChromosomes_0 () throws Exception
void testIsSerializable_0 () throws Exception
void testDoSerialize_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.34 $`
Additional Inherited Members
Detailed Description
Tests the WeightedRouletteSelector class.
Author
Klaus Meffert
Since
1.1
Definition at line 24 of file WeightedRouletteSelectorTest.java.
Member Function Documentation
void org.jgap.impl.WeightedRouletteSelectorTest.setUp () [inline]
Definition at line 34 of file WeightedRouletteSelectorTest.java.
static Test org.jgap.impl.WeightedRouletteSelectorTest.suite () [inline], [static]
Definition at line 29 of file WeightedRouletteSelectorTest.java.
void org.jgap.impl.WeightedRouletteSelectorTest.testAdd_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 57 of file WeightedRouletteSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.WeightedRouletteSelectorTest.testConstruct_0 () throws Exception [inline]
Test if construction possible without failure.
Exceptions
Exception
Definition at line 44 of file WeightedRouletteSelectorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.WeightedRouletteSelectorTest.testDoSerialize_0 () throws Exception [inline]
Ensures that WRS implements Serializable correctly.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 403 of file WeightedRouletteSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.doSerialize().
void org.jgap.impl.WeightedRouletteSelectorTest.testEmpty_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 304 of file WeightedRouletteSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.WeightedRouletteSelectorTest.testEmpty_1 () throws Exception [inline]
Test if clear()-method does not affect original Population.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 326 of file WeightedRouletteSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.WeightedRouletteSelectorTest.testEmpty_2 () throws Exception [inline]
Test if clear()-method does not affect return value.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 348 of file WeightedRouletteSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.WeightedRouletteSelectorTest.testIsSerializable_0 () throws Exception [inline]
Ensures WRS is implementing Serializable.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 386 of file WeightedRouletteSelectorTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.isSerializable().
void org.jgap.impl.WeightedRouletteSelectorTest.testReturnsUniqueChromosomes_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 371 of file WeightedRouletteSelectorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.WeightedRouletteSelectorTest.testSelect_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 84 of file WeightedRouletteSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.WeightedRouletteSelectorTest.testSelect_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 105 of file WeightedRouletteSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.WeightedRouletteSelectorTest.testSelect_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 155 of file WeightedRouletteSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.WeightedRouletteSelectorTest.testSelect_3 () throws Exception [inline]
Ensure the scaling of fitness value works without error (like division by zero).
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 208 of file WeightedRouletteSelectorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.WeightedRouletteSelectorTest.testSelect_4 () throws Exception [inline]
Use DeltaFitnessEvaluator.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 253 of file WeightedRouletteSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
Member Data Documentation
final String org.jgap.impl.WeightedRouletteSelectorTest.CVS_REVISION = `$Revision: 1.34 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file WeightedRouletteSelectorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/WeightedRouletteSelectorTest.java