org.jgap.distr.CultureTest Class Reference
Public Member Functions
void testConstruct_0 ()
void testConstruct_1 ()
void testConstruct_2 ()
void testGet_0 ()
void testGet_1 ()
void testGet_2 ()
void testGet_3 ()
void testGet_4 ()
void testGet_5 ()
void testToString_0 ()
void testToString_1 ()
void testSerialize_0 () throws Exception
void testClear_0 ()
void testContains_0 ()
void testContains_1 ()
void testContains_2 ()
void testContains_3 ()
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.15 $`
Additional Inherited Members
Detailed Description
Tests the Culture class.
Author
Klaus Meffert
Since
2.3
Definition at line 21 of file CultureTest.java.
Member Function Documentation
static Test org.jgap.distr.CultureTest.suite () [inline], [static]
Definition at line 26 of file CultureTest.java.
void org.jgap.distr.CultureTest.testClear_0 () [inline]
Author
Klaus Meffert
Since
3.0
Definition at line 219 of file CultureTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.distr.Culture.get(), and org.jgap.distr.Culture.getMemoryNames().
void org.jgap.distr.CultureTest.testConstruct_0 () [inline]
Author
Klaus Meffert
Since
2.3
Definition at line 35 of file CultureTest.java.
void org.jgap.distr.CultureTest.testConstruct_1 () [inline]
Author
Klaus Meffert
Since
2.3
Definition at line 49 of file CultureTest.java.
void org.jgap.distr.CultureTest.testConstruct_2 () [inline]
Author
Klaus Meffert
Since
2.3
Definition at line 63 of file CultureTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.distr.Culture.size().
void org.jgap.distr.CultureTest.testContains_0 () [inline]
Author
Klaus Meffert
Since
3.2
Definition at line 236 of file CultureTest.java.
References org.jgap.distr.Culture.contains().
void org.jgap.distr.CultureTest.testContains_1 () [inline]
Author
Klaus Meffert
Since
3.2
Definition at line 251 of file CultureTest.java.
References org.jgap.distr.Culture.contains().
void org.jgap.distr.CultureTest.testContains_2 () [inline]
Author
Klaus Meffert
Since
3.2
Definition at line 262 of file CultureTest.java.
References org.jgap.distr.Culture.contains().
void org.jgap.distr.CultureTest.testContains_3 () [inline]
Author
Klaus Meffert
Since
3.2
Definition at line 276 of file CultureTest.java.
References org.jgap.distr.Culture.contains().
void org.jgap.distr.CultureTest.testGet_0 () [inline]
Illegal index.
Author
Klaus Meffert
Since
2.3
Definition at line 74 of file CultureTest.java.
void org.jgap.distr.CultureTest.testGet_1 () [inline]
Illegal index (too high).
Author
Klaus Meffert
Since
2.3
Definition at line 91 of file CultureTest.java.
void org.jgap.distr.CultureTest.testGet_2 () [inline]
Author
Klaus Meffert
Since
2.3
Definition at line 106 of file CultureTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.DELTA.
void org.jgap.distr.CultureTest.testGet_3 () [inline]
Author
Klaus Meffert
Since
2.3
Definition at line 120 of file CultureTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.DELTA.
void org.jgap.distr.CultureTest.testGet_4 () [inline]
Author
Klaus Meffert
Since
2.3
Definition at line 134 of file CultureTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.DELTA.
void org.jgap.distr.CultureTest.testGet_5 () [inline]
Author
Klaus Meffert
Since
2.3
Definition at line 148 of file CultureTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.distr.CultureTest.testSerialize_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.3
Definition at line 207 of file CultureTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.doSerialize().
void org.jgap.distr.CultureTest.testToString_0 () [inline]
Author
Klaus Meffert
Since
2.3
Definition at line 158 of file CultureTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.distr.Culture.get(), and org.jgap.distr.Culture.toString().
void org.jgap.distr.CultureTest.testToString_1 () [inline]
Author
Klaus Meffert
Since
2.3
Definition at line 180 of file CultureTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.distr.Culture.get(), and org.jgap.distr.Culture.toString().
Member Data Documentation
final String org.jgap.distr.CultureTest.CVS_REVISION = `$Revision: 1.15 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file CultureTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/distr/CultureTest.java