org.jgap.gp.impl.GPConfiguration Class Reference
Public Member Functions
GPConfiguration () throws InvalidConfigurationException
GPConfiguration (String a_id, String a_name) throws InvalidConfigurationException
GPConfiguration (final String a_name) throws InvalidConfigurationException
void setGPFitnessEvaluator (IGPFitnessEvaluator a_evaluator)
GPConfiguration (INaturalGPSelector a_selectionMethod) throws InvalidConfigurationException
void setSelectionMethod (INaturalGPSelector a_method)
void setCrossoverMethod (CrossMethod a_method)
synchronized void verifyStateIsValid () throws InvalidConfigurationException
synchronized void addGeneticOperator (GeneticOperator a_operatorToAdd) throws InvalidConfigurationException
double getCrossoverProb ()
void setCrossoverProb (float a_crossoverProb)
double getReproductionProb ()
void setReproductionProb (float a_reproductionProb)
double getMutationProb ()
void setMutationProb (float a_mutationProb)
double getDynamizeArityProb ()
void setDynamizeArityProb (float a_dynArityProb)
void setFunctionProb (double a_functionProb)
double getFunctionProb ()
void setNewChromsPercent (double a_newChromsPercent)
double getNewChromsPercent ()
int getMaxCrossoverDepth ()
void setMaxCrossoverDepth (int a_maxCrossoverDepth)
INaturalGPSelector getSelectionMethod ()
CrossMethod getCrossMethod ()
int getMaxInitDepth ()
void setMaxInitDepth (int a_maxDepth)
int getMinInitDepth ()
void setMinInitDepth (int a_minDepth)
void pushToStack (Object a_value)
Object popFromStack ()
Object peekStack ()
int stackSize ()
void clearStack ()
void storeInMemory (String a_name, Object a_value)
void createMatrix (String a_name, int a_cols, int a_rows)
void setMatrix (String a_name, int a_col, int a_row, char a_value)
void setMatrix (String a_name, int a_col, int a_row, int a_value)
void resetMatrix (String a_name, char a_filler)
char readMatrix (String a_name, int a_col, int a_row)
char[][] getMatrix (String a_name)
CultureMemoryCell storeMatrixMemory (int a_x, int a_y, Object a_value)
Object readMatrixMemory (int a_x, int a_y)
Object readFromMemory (String a_name)
Object readFromMemoryIfExists (String a_name)
CultureMemoryCell storeIndexedMemory (int a_index, Object a_value)
Object readIndexedMemory (int a_index)
void clearMemory ()
GPFitnessFunction getGPFitnessFunction ()
void setFitnessEvaluator (IGPFitnessEvaluator a_fitnessEvaluator)
synchronized void setFitnessFunction (GPFitnessFunction a_functionToSet) throws InvalidConfigurationException
boolean isStrictProgramCreation ()
void setStrictProgramCreation (boolean a_strict)
int getProgramCreationMaxtries ()
void setProgramCreationMaxTries (int a_maxtries)
IGPFitnessEvaluator getGPFitnessEvaluator ()
boolean validateNode (ProgramChromosome a_chrom, CommandGene a_node, CommandGene a_rootNode, int a_tries, int a_num, int a_recurseLevel, Class a_type, CommandGene[] a_functionSet, int a_depth, boolean a_grow, int a_childIndex, boolean a_fullProgram)
void setNodeValidator (INodeValidator a_nodeValidator)
INodeValidator getNodeValidator ()
void setSingleNodeValidator (ISingleNodeValidator a_singleNodeValidator)
ISingleNodeValidator getSingleNodeValidator ()
boolean equals (Object a_other)
int compareTo (Object a_other)
boolean isMaxNodeWarningPrinted ()
void flagMaxNodeWarningPrinted ()
void setPrototypeProgram (IGPProgram a_program)
IGPProgram getPrototypeProgram ()
int getMemorySize ()
GPProgramInfo readProgramCache (GPProgram a_prog)
GPProgramInfo putToProgramCache (GPProgram a_prog)
boolean isUseProgramCache ()
void setUseProgramCache (boolean a_useCache)
void putVariable (Variable a_var)
Variable getVariable (String a_varName)
Object clone ()
GPConfiguration newInstanceGP (String a_id, String a_name)
IJGAPFactory getJGAPFactory ()
void setInitStrategy (IGPInitStrategy a_strategy)
IGPInitStrategy getInitStrategy ()
void setVerifyPrograms (boolean a_verify)
boolean isVerifyPrograms ()
void setNoCommandGeneCloning (boolean a_noCommandGeneCloning)
boolean isNoCommandGeneCloning ()
Protected Member Functions
void init (boolean a_fullInit) throws InvalidConfigurationException
Private Member Functions
void readObject (ObjectInputStream a_inputStream) throws IOException, ClassNotFoundException
Private Attributes
GPFitnessFunction m_objectiveFunction
Stack m_stack = new Stack()
transient Culture m_memory = new Culture(50)
transient Hashtable< String,
*
char[][]> m_matrices
double m_crossoverProb = 0.9d
double m_reproductionProb = 0.1d
double m_mutationProb = 0.1d
double m_dynArityProb = 0.08d
double m_newChromsPercent = 0.3d
double m_functionProb = 0.9d
int m_maxCrossoverDepth = 17
int m_maxInitDepth = 7
int m_minInitDepth = 2
INaturalGPSelector m_selectionMethod
CrossMethod m_crossMethod
boolean m_strictProgramCreation
int m_programCreationMaxTries = 5
IGPFitnessEvaluator m_fitnessEvaluator
INodeValidator m_nodeValidator
ISingleNodeValidator m_singleNodeValidator
transient boolean m_warningPrinted
IGPProgram m_prototypeProgram
boolean m_useProgramCache = false
Map m_variables
transient Map m_programCache
transient IJGAPFactory m_factory
IGPInitStrategy m_initStrategy
boolean m_verify
boolean m_noCommandGeneCloning
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.52 $`
Additional Inherited Members
Detailed Description
Configuration for a GP.
Author
Klaus Meffert
Since
3.0
Definition at line 30 of file GPConfiguration.java.
Constructor & Destructor Documentation
org.jgap.gp.impl.GPConfiguration.GPConfiguration () throws InvalidConfigurationException [inline]
Constructor utilizing the FitnessProportionateSelection.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 197 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.compareTo(), and org.jgap.gp.impl.GPConfiguration.newInstanceGP().
org.jgap.gp.impl.GPConfiguration.GPConfiguration (String a_id, String a_name) throws InvalidConfigurationException [inline]
Definition at line 202 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.init(), and org.jgap.gp.impl.GPConfiguration.m_selectionMethod.
org.jgap.gp.impl.GPConfiguration.GPConfiguration (final String a_name) throws InvalidConfigurationException [inline]
Constructs a configuration with an informative name but without a unique ID. This practically prevents more than one configurations to be instantiated within the same thread.
Parameters
a_name informative name of the configuration, may be null
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Definition at line 219 of file GPConfiguration.java.
References org.jgap.Configuration.setName().
org.jgap.gp.impl.GPConfiguration.GPConfiguration (INaturalGPSelector a_selectionMethod) throws InvalidConfigurationException [inline]
Constructor utilizing the FitnessProportionateSelection.
Parameters
a_selectionMethod the selection method to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.1
Definition at line 290 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.init(), and org.jgap.gp.impl.GPConfiguration.m_selectionMethod.
Member Function Documentation
synchronized void org.jgap.gp.impl.GPConfiguration.addGeneticOperator (GeneticOperator a_operatorToAdd) throws InvalidConfigurationException [inline]
Definition at line 331 of file GPConfiguration.java.
void org.jgap.gp.impl.GPConfiguration.clearMemory () [inline]
Clears the memory.
Author
Klaus Meffert
Since
3.0
Definition at line 720 of file GPConfiguration.java.
void org.jgap.gp.impl.GPConfiguration.clearStack () [inline]
Definition at line 482 of file GPConfiguration.java.
Object org.jgap.gp.impl.GPConfiguration.clone () [inline]
Returns
deep clone of this instance
Author
Klaus Meffert
Since
3.2
Implements org.jgap.util.ICloneable.
Definition at line 1039 of file GPConfiguration.java.
References org.jgap.Configuration.getId(), org.jgap.Configuration.getName(), and org.jgap.gp.impl.GPConfiguration.newInstanceGP().
Referenced by org.jgap.gp.impl.GPConfiguration.newInstanceGP(), org.jgap.gp.impl.GPConfigurationTest.testClone_0(), and org.jgap.gp.impl.GPConfigurationTest.testClone_1().
int org.jgap.gp.impl.GPConfiguration.compareTo (Object a_other) [inline]
Definition at line 918 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.GPConfiguration(), org.jgap.gp.impl.GPConfiguration.m_crossMethod, org.jgap.gp.impl.GPConfiguration.m_crossoverProb, org.jgap.gp.impl.GPConfiguration.m_fitnessEvaluator, org.jgap.gp.impl.GPConfiguration.m_maxCrossoverDepth, org.jgap.gp.impl.GPConfiguration.m_maxInitDepth, org.jgap.gp.impl.GPConfiguration.m_newChromsPercent, org.jgap.gp.impl.GPConfiguration.m_objectiveFunction, org.jgap.gp.impl.GPConfiguration.m_programCreationMaxTries, org.jgap.gp.impl.GPConfiguration.m_reproductionProb, org.jgap.gp.impl.GPConfiguration.m_selectionMethod, and org.jgap.gp.impl.GPConfiguration.m_strictProgramCreation.
Referenced by org.jgap.gp.impl.GPConfiguration.equals().
void org.jgap.gp.impl.GPConfiguration.createMatrix (String a_name, int a_cols, int a_rows) [inline]
Creates an instance of a matrix with a unique name.
Parameters
a_name the name of the matrix
a_cols number of columns the matrix should have
a_rows number of rows the matrix should have
Author
Klaus Meffert
Since
3.4.3
Definition at line 509 of file GPConfiguration.java.
boolean org.jgap.gp.impl.GPConfiguration.equals (Object a_other) [inline]
Compares this entity against the specified object.
Parameters
a_other the object to compare against
Returns
true: if the objects are the same, false otherwise
Author
Klaus Meffert
Since
3.1
Definition at line 910 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.compareTo().
void org.jgap.gp.impl.GPConfiguration.flagMaxNodeWarningPrinted () [inline]
See ProgramChromosome.growOrFull(...) and GPGenotype.evolve().
Author
Klaus Meffert
Since
3.2
Definition at line 956 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_warningPrinted.
CrossMethod org.jgap.gp.impl.GPConfiguration.getCrossMethod () [inline]
Definition at line 446 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_crossMethod.
double org.jgap.gp.impl.GPConfiguration.getCrossoverProb () [inline]
Todo
Todo implement something like that
Definition at line 341 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_crossoverProb.
double org.jgap.gp.impl.GPConfiguration.getDynamizeArityProb () [inline]
Returns
probability for dynamizing the arity of a node during growing a program
Author
Klaus Meffert
Since
3.4
Definition at line 385 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_dynArityProb.
Referenced by org.jgap.gp.impl.ProgramChromosome.growOrFullNode().
double org.jgap.gp.impl.GPConfiguration.getFunctionProb () [inline]
Returns
probability that a function instead of a terminal is chosen in crossing over
Author
Klaus Meffert
Since
3.2
Definition at line 418 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_functionProb.
IGPFitnessEvaluator org.jgap.gp.impl.GPConfiguration.getGPFitnessEvaluator () [inline]
Returns
the fitness evaluator set
Author
Klaus Meffert
Since
3.0
Definition at line 811 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_fitnessEvaluator.
GPFitnessFunction org.jgap.gp.impl.GPConfiguration.getGPFitnessFunction () [inline]
Definition at line 724 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_objectiveFunction.
IGPInitStrategy org.jgap.gp.impl.GPConfiguration.getInitStrategy () [inline]
Returns
IGPInitStrategy
Author
Klaus Meffert
Since
3.2.2
Definition at line 1160 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_initStrategy.
IJGAPFactory org.jgap.gp.impl.GPConfiguration.getJGAPFactory () [inline]
Returns
the JGAP factory registered
Author
Klaus Meffert
Since
3.2
Definition at line 1115 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_factory.
Referenced by org.jgap.distr.grid.gp.JGAPWorkerGP.doWork().
char [][] org.jgap.gp.impl.GPConfiguration.getMatrix (String a_name) [inline]
Retrieves a named matrix.
Parameters
a_name the name of the matrix
Returns
the matrix itself
Author
Klaus Meffert
Since
3.4.3
Definition at line 612 of file GPConfiguration.java.
int org.jgap.gp.impl.GPConfiguration.getMaxCrossoverDepth () [inline]
Definition at line 434 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_maxCrossoverDepth.
int org.jgap.gp.impl.GPConfiguration.getMaxInitDepth () [inline]
Definition at line 450 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_maxInitDepth.
int org.jgap.gp.impl.GPConfiguration.getMemorySize () [inline]
Returns
capacity of the memory in cells
Author
Klaus Meffert
Since
3.2
Definition at line 987 of file GPConfiguration.java.
int org.jgap.gp.impl.GPConfiguration.getMinInitDepth () [inline]
Definition at line 458 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_minInitDepth.
double org.jgap.gp.impl.GPConfiguration.getMutationProb () [inline]
Returns
probability for mutation of a node during growing a program
Author
Klaus Meffert
Since
3.3.1
Definition at line 363 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_mutationProb.
double org.jgap.gp.impl.GPConfiguration.getNewChromsPercent () [inline]
Definition at line 430 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_newChromsPercent.
INodeValidator org.jgap.gp.impl.GPConfiguration.getNodeValidator () [inline]
Returns
the node validator set
Author
Klaus Meffert
Since
3.0
Definition at line 875 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_nodeValidator.
Referenced by org.jgap.gp.impl.GPConfiguration.validateNode().
int org.jgap.gp.impl.GPConfiguration.getProgramCreationMaxtries () [inline]
Definition at line 797 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_programCreationMaxTries.
IGPProgram org.jgap.gp.impl.GPConfiguration.getPrototypeProgram () [inline]
Returns
prototype program set (maybe null if not setted previously)
Author
Klaus Meffert
Since
3.2
Definition at line 977 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_prototypeProgram.
double org.jgap.gp.impl.GPConfiguration.getReproductionProb () [inline]
Definition at line 349 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_reproductionProb.
INaturalGPSelector org.jgap.gp.impl.GPConfiguration.getSelectionMethod () [inline]
Definition at line 442 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_selectionMethod.
Referenced by org.jgap.gp.impl.GPConfigurationTest.testConstructor_1().
ISingleNodeValidator org.jgap.gp.impl.GPConfiguration.getSingleNodeValidator () [inline]
Returns
the validator set for single node checking
Author
Klaus Meffert
Since
3.6
Definition at line 897 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_singleNodeValidator.
Variable org.jgap.gp.impl.GPConfiguration.getVariable (String a_varName) [inline]
Parameters
a_varName name of variable to retrieve
Returns
Variable instance or null, if not found
Author
Klaus Meffert
Since
3.2
Definition at line 1029 of file GPConfiguration.java.
void org.jgap.gp.impl.GPConfiguration.init (boolean a_fullInit) throws InvalidConfigurationException [inline], [protected]
Helper for construction.
Parameters
a_fullInit true set event manager, random generator and fitness evaluator to defauklt
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.1
Todo
Todo make reusable in class Configuration and reuse here from Configuration
Definition at line 248 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_crossMethod, org.jgap.gp.impl.GPConfiguration.m_factory, org.jgap.gp.impl.GPConfiguration.m_matrices, org.jgap.gp.impl.GPConfiguration.m_programCache, org.jgap.gp.impl.GPConfiguration.m_variables, org.jgap.Configuration.PROPERTY_JGAPFACTORY_CLASS, org.jgap.Configuration.setEventManager(), org.jgap.gp.impl.GPConfiguration.setGPFitnessEvaluator(), and org.jgap.Configuration.setRandomGenerator().
Referenced by org.jgap.gp.impl.GPConfiguration.GPConfiguration(), and org.jgap.gp.impl.GPConfiguration.readObject().
boolean org.jgap.gp.impl.GPConfiguration.isMaxNodeWarningPrinted () [inline]
Returns
see ProgramChromosome.growOrFull(...) and GPGenotype.evolve()
Author
Klaus Meffert
Since
3.2
Definition at line 946 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_warningPrinted.
boolean org.jgap.gp.impl.GPConfiguration.isNoCommandGeneCloning () [inline]
Returns
true: do not clone command genes when creating a new GP program in ProgramChromosome
Author
Klaus Meffert
Since
3.4.3
Definition at line 1206 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_noCommandGeneCloning.
Referenced by org.jgap.gp.impl.ProgramChromosome.growOrFullNode().
boolean org.jgap.gp.impl.GPConfiguration.isStrictProgramCreation () [inline]
Returns
true: throw an error during evolution in case a situation is detected where no function or terminal of a required type is declared in the GPConfiguration; false: don't throw an error but try a completely different combination of functions and terminals
Author
Klaus Meffert
Definition at line 781 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_strictProgramCreation.
boolean org.jgap.gp.impl.GPConfiguration.isUseProgramCache () [inline]
Definition at line 1002 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_useProgramCache.
boolean org.jgap.gp.impl.GPConfiguration.isVerifyPrograms () [inline]
Returns
true: verify GP programs for correctness (i.e. is fitness computation possible without exception?)
Author
Klaus Meffert
Since
3.3.4
Definition at line 1182 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_verify.
GPConfiguration org.jgap.gp.impl.GPConfiguration.newInstanceGP (String a_id, String a_name) [inline]
Creates a new GPConfiguration instance by cloning. Allows to preset the ID and the name.
Parameters
a_id new ID for clone
a_name new name for clone
Returns
deep clone of this instance
Author
Klaus Meffert
Since
3.2
Definition at line 1054 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.clone(), org.jgap.Configuration.doClone(), org.jgap.Configuration.getName(), org.jgap.Configuration.getPopulationSize(), org.jgap.gp.impl.GPConfiguration.GPConfiguration(), org.jgap.gp.impl.GPConfiguration.m_crossMethod, org.jgap.gp.impl.GPConfiguration.m_crossoverProb, org.jgap.gp.impl.GPConfiguration.m_factory, org.jgap.gp.impl.GPConfiguration.m_fitnessEvaluator, org.jgap.gp.impl.GPConfiguration.m_functionProb, org.jgap.gp.impl.GPConfiguration.m_maxCrossoverDepth, org.jgap.gp.impl.GPConfiguration.m_maxInitDepth, org.jgap.gp.impl.GPConfiguration.m_minInitDepth, org.jgap.gp.impl.GPConfiguration.m_newChromsPercent, org.jgap.gp.impl.GPConfiguration.m_nodeValidator, org.jgap.gp.impl.GPConfiguration.m_objectiveFunction, org.jgap.gp.impl.GPConfiguration.m_programCreationMaxTries, org.jgap.gp.impl.GPConfiguration.m_reproductionProb, org.jgap.gp.impl.GPConfiguration.m_selectionMethod, org.jgap.gp.impl.GPConfiguration.m_strictProgramCreation, org.jgap.gp.impl.GPConfiguration.m_useProgramCache, org.jgap.gp.impl.GPConfiguration.m_variables, and org.jgap.gp.impl.GPConfiguration.m_verify.
Referenced by org.jgap.gp.impl.GPConfiguration.clone(), and examples.gp.island.IslandGPThread.createConfiguration().
Object org.jgap.gp.impl.GPConfiguration.peekStack () [inline]
Definition at line 474 of file GPConfiguration.java.
Object org.jgap.gp.impl.GPConfiguration.popFromStack () [inline]
Definition at line 470 of file GPConfiguration.java.
void org.jgap.gp.impl.GPConfiguration.pushToStack (Object a_value) [inline]
Definition at line 466 of file GPConfiguration.java.
GPProgramInfo org.jgap.gp.impl.GPConfiguration.putToProgramCache (GPProgram a_prog) [inline]
Definition at line 997 of file GPConfiguration.java.
void org.jgap.gp.impl.GPConfiguration.putVariable (Variable a_var) [inline]
Stores a Variable.
Parameters
a_var the Variable to store
Author
Klaus Meffert
Since
3.2
Definition at line 1018 of file GPConfiguration.java.
Object org.jgap.gp.impl.GPConfiguration.readFromMemory (String a_name) [inline]
Reads a value from the internal memory.
Parameters
a_name named index of the memory cell to read out
Returns
read value
Author
Klaus Meffert
Since
3.0
Definition at line 655 of file GPConfiguration.java.
Object org.jgap.gp.impl.GPConfiguration.readFromMemoryIfExists (String a_name) [inline]
Parameters
a_name the name of the cell to evaluate
Returns
the value of a memory cell, if it exsists. Otherwise returns null.
Author
Klaus Meffert
Since
3.2
Definition at line 666 of file GPConfiguration.java.
Object org.jgap.gp.impl.GPConfiguration.readIndexedMemory (int a_index) [inline]
Reads a value from the internal indexed memory.
Parameters
a_index index of the cell
Returns
read value (maybe null)
Author
Klaus Meffert
Since
3.2
Definition at line 704 of file GPConfiguration.java.
char org.jgap.gp.impl.GPConfiguration.readMatrix (String a_name, int a_col, int a_row) [inline]
Reads a matrix cell and returns the value.
Parameters
a_name the name of the matrix
a_col the column to read
a_row the row to read
Returns
the value in the matrix
Author
Klaus Meffert
Since
3.4.3
Definition at line 594 of file GPConfiguration.java.
Object org.jgap.gp.impl.GPConfiguration.readMatrixMemory (int a_x, int a_y) [inline]
Reads a value from the internal matrix memory.
Parameters
a_x the first coordinate of the matrix (width)
a_y the second coordinate of the matrix (height)
Returns
read value
Author
Klaus Meffert
Since
3.2
Definition at line 642 of file GPConfiguration.java.
void org.jgap.gp.impl.GPConfiguration.readObject (ObjectInputStream a_inputStream) throws IOException, ClassNotFoundException [inline], [private]
When deserializing, do specific initializations.
Parameters
a_inputStream the ObjectInputStream provided for deserialzation
Exceptions
IOException
ClassNotFoundException
Author
Klaus Meffert
Since
3.2
Definition at line 1130 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.init().
GPProgramInfo org.jgap.gp.impl.GPConfiguration.readProgramCache (GPProgram a_prog) [inline]
Definition at line 991 of file GPConfiguration.java.
void org.jgap.gp.impl.GPConfiguration.resetMatrix (String a_name, char a_filler) [inline]
Resets the matrix by filling it with a given character.
Parameters
a_name the name of the matrix
a_filler the character to fill the whole matrix with
Author
Klaus Meffert
Since
3.4.3
Definition at line 570 of file GPConfiguration.java.
void org.jgap.gp.impl.GPConfiguration.setCrossoverMethod (CrossMethod a_method) [inline]
Sets the crossover method to use.
Parameters
a_method the crossover method to use
Author
Klaus Meffert
Since
3.1
Definition at line 318 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_crossMethod.
void org.jgap.gp.impl.GPConfiguration.setCrossoverProb (float a_crossoverProb) [inline]
Definition at line 345 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_crossoverProb.
Referenced by examples.gp.monalisa.core.DrawingGPConfiguration.DrawingGPConfiguration().
void org.jgap.gp.impl.GPConfiguration.setDynamizeArityProb (float a_dynArityProb) [inline]
Parameters
a_dynArityProb probability for dynamizing the arity of a node during growing a program
Author
Klaus Meffert
Since
3.4
Definition at line 396 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_dynArityProb.
void org.jgap.gp.impl.GPConfiguration.setFitnessEvaluator (IGPFitnessEvaluator a_fitnessEvaluator) [inline]
Set the fitness evaluator (deciding if a given fitness value is better when it's higher or better when it's lower).
Parameters
a_fitnessEvaluator the FitnessEvaluator to be used
Author
Klaus Meffert
Since
3.3.3
Definition at line 736 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.setGPFitnessEvaluator().
synchronized void org.jgap.gp.impl.GPConfiguration.setFitnessFunction (GPFitnessFunction a_functionToSet) throws InvalidConfigurationException [inline]
Sets the fitness function to be used for this genetic algorithm. The fitness function is responsible for evaluating a given Chromosome and returning a positive integer that represents its worth as a candidate solution. These values are used as a guide by the natural to determine which Chromosome instances will be allowed to move on to the next round of evolution, and which will instead be eliminated.
Parameters
a_functionToSet fitness function to be used
Exceptions
InvalidConfigurationException if the fitness function is null, or if this Configuration object is locked.
Author
Klaus Meffert
Since
1.1
Definition at line 756 of file GPConfiguration.java.
References org.jgap.Configuration.checkProperty(), org.jgap.gp.impl.GPConfiguration.m_objectiveFunction, org.jgap.Configuration.PROPERTY_FITFUNC_INST, and org.jgap.Configuration.verifyChangesAllowed().
Referenced by examples.gp.monalisa.core.DrawingGPConfiguration.DrawingGPConfiguration().
void org.jgap.gp.impl.GPConfiguration.setFunctionProb (double a_functionProb) [inline]
Parameters
a_functionProb probability that a function instead of a terminal is chosen in crossing over (between 0 and 1)
Author
Klaus Meffert
Since
3.2
Definition at line 407 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_functionProb.
void org.jgap.gp.impl.GPConfiguration.setGPFitnessEvaluator (IGPFitnessEvaluator a_evaluator) [inline]
Sets a GP fitness evaluator, such as org.jgap.gp.impl.DefaultGPFitnessEvaluator.
Parameters
a_evaluator the fitness evaluator to set
Author
Klaus Meffert
Since
3.1
Definition at line 234 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_fitnessEvaluator.
Referenced by examples.gp.monalisa.core.DrawingGPConfiguration.DrawingGPConfiguration(), org.jgap.gp.impl.GPConfiguration.init(), and org.jgap.gp.impl.GPConfiguration.setFitnessEvaluator().
void org.jgap.gp.impl.GPConfiguration.setInitStrategy (IGPInitStrategy a_strategy) [inline]
Parameters
a_strategy IGPInitStrategy
Author
Klaus Meffert
Since
3.2.2
Definition at line 1149 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_initStrategy.
Referenced by examples.gp.monalisa.core.DrawingGPConfiguration.DrawingGPConfiguration().
void org.jgap.gp.impl.GPConfiguration.setMatrix (String a_name, int a_col, int a_row, char a_value) [inline]
Sets a matrix field with a value.
Parameters
a_name the name of the matrix
a_col column in the matrix
a_row row in the matrix
a_value the value to set in the matrix at given column and row
Author
Klaus Meffert
Since
3.4.3
Definition at line 532 of file GPConfiguration.java.
void org.jgap.gp.impl.GPConfiguration.setMatrix (String a_name, int a_col, int a_row, int a_value) [inline]
Sets a matrix field with a value.
Parameters
a_name the name of the matrix
a_col column in the matrix
a_row row in the matrix
a_value the value to set in the matrix at given column and row
Author
Klaus Meffert
Since
3.6
Definition at line 552 of file GPConfiguration.java.
void org.jgap.gp.impl.GPConfiguration.setMaxCrossoverDepth (int a_maxCrossoverDepth) [inline]
Definition at line 438 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_maxCrossoverDepth.
Referenced by examples.gp.monalisa.core.DrawingGPConfiguration.DrawingGPConfiguration().
void org.jgap.gp.impl.GPConfiguration.setMaxInitDepth (int a_maxDepth) [inline]
Definition at line 454 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_maxInitDepth.
Referenced by examples.gp.monalisa.core.DrawingGPConfiguration.DrawingGPConfiguration().
void org.jgap.gp.impl.GPConfiguration.setMinInitDepth (int a_minDepth) [inline]
Definition at line 462 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_minInitDepth.
Referenced by examples.gp.monalisa.core.DrawingGPConfiguration.DrawingGPConfiguration().
void org.jgap.gp.impl.GPConfiguration.setMutationProb (float a_mutationProb) [inline]
Parameters
a_mutationProb probability for mutation of a node during growing a program
Author
Klaus Meffert
Since
3.3.1
Definition at line 374 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_mutationProb.
Referenced by examples.gp.monalisa.core.DrawingGPConfiguration.DrawingGPConfiguration().
void org.jgap.gp.impl.GPConfiguration.setNewChromsPercent (double a_newChromsPercent) [inline]
Definition at line 422 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_newChromsPercent.
Referenced by examples.gp.monalisa.core.DrawingGPConfiguration.DrawingGPConfiguration().
void org.jgap.gp.impl.GPConfiguration.setNoCommandGeneCloning (boolean a_noCommandGeneCloning) [inline]
Decide whether to clone command genes when creating a new GP program in ProgramChromosome.
Parameters
a_noCommandGeneCloning boolean
Author
Klaus Meffert
Since
3.4.3
Definition at line 1195 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_noCommandGeneCloning.
void org.jgap.gp.impl.GPConfiguration.setNodeValidator (INodeValidator a_nodeValidator) [inline]
Sets the node validator. Also see method validateNode.
Parameters
a_nodeValidator sic
Author
Klaus Meffert
Since
3.0
Definition at line 865 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_nodeValidator.
Referenced by examples.gp.monalisa.core.DrawingGPConfiguration.DrawingGPConfiguration().
void org.jgap.gp.impl.GPConfiguration.setProgramCreationMaxTries (int a_maxtries) [inline]
Definition at line 801 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_programCreationMaxTries.
Referenced by examples.gp.monalisa.core.DrawingGPConfiguration.DrawingGPConfiguration().
void org.jgap.gp.impl.GPConfiguration.setPrototypeProgram (IGPProgram a_program) [inline]
Parameters
a_program IGPProgram
Author
Klaus Meffert
Since
3.2
Definition at line 967 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_prototypeProgram.
void org.jgap.gp.impl.GPConfiguration.setReproductionProb (float a_reproductionProb) [inline]
Definition at line 353 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_reproductionProb.
Referenced by examples.gp.monalisa.core.DrawingGPConfiguration.DrawingGPConfiguration().
void org.jgap.gp.impl.GPConfiguration.setSelectionMethod (INaturalGPSelector a_method) [inline]
Sets the selection method to use.
Parameters
a_method the selection method to use
Author
Klaus Meffert
Since
3.1
Definition at line 304 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_selectionMethod.
Referenced by examples.gp.monalisa.core.DrawingGPConfiguration.DrawingGPConfiguration().
void org.jgap.gp.impl.GPConfiguration.setSingleNodeValidator (ISingleNodeValidator a_singleNodeValidator) [inline]
Sets the validator for checking single nodes.
Parameters
a_singleNodeValidator sic
Author
Klaus Meffert
Since
3.6
Definition at line 887 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_singleNodeValidator.
void org.jgap.gp.impl.GPConfiguration.setStrictProgramCreation (boolean a_strict) [inline]
Parameters
a_strict true: throw an error during evolution in case a situation is detected where no function or terminal of a required type is declared in the GPConfiguration; false: don't throw an error but try a completely different combination of functions and terminals
Author
Klaus Meffert
Definition at line 793 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_strictProgramCreation.
Referenced by examples.gp.monalisa.core.DrawingGPConfiguration.DrawingGPConfiguration().
void org.jgap.gp.impl.GPConfiguration.setUseProgramCache (boolean a_useCache) [inline]
Definition at line 1006 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_useProgramCache.
void org.jgap.gp.impl.GPConfiguration.setVerifyPrograms (boolean a_verify) [inline]
Parameters
a_verify true: verify GP programs for correctness (i.e. is fitness computation possible without exception?)
Author
Klaus Meffert
Since
3.3.4
Definition at line 1171 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.m_verify.
int org.jgap.gp.impl.GPConfiguration.stackSize () [inline]
Definition at line 478 of file GPConfiguration.java.
CultureMemoryCell org.jgap.gp.impl.GPConfiguration.storeIndexedMemory (int a_index, Object a_value) [inline]
Stores a value in the internal indexed memory.
Parameters
a_index index of the cell
a_value the value to store
Returns
created or used memory cell
Author
Klaus Meffert
Since
3.2
Definition at line 691 of file GPConfiguration.java.
void org.jgap.gp.impl.GPConfiguration.storeInMemory (String a_name, Object a_value) [inline]
Stores a value in the internal memory.
Parameters
a_name named index of the memory cell
a_value the value to store
Author
Klaus Meffert
Since
3.0
Definition at line 495 of file GPConfiguration.java.
CultureMemoryCell org.jgap.gp.impl.GPConfiguration.storeMatrixMemory (int a_x, int a_y, Object a_value) [inline]
Stores a value in the internal matrix memory.
Parameters
a_x the first coordinate of the matrix (width)
a_y the second coordinate of the matrix (height)
a_value the value to store
Returns
created or used memory cell
Author
Klaus Meffert
Since
3.2
Definition at line 628 of file GPConfiguration.java.
boolean org.jgap.gp.impl.GPConfiguration.validateNode (ProgramChromosome a_chrom, CommandGene a_node, CommandGene a_rootNode, int a_tries, int a_num, int a_recurseLevel, Class a_type, CommandGene[] a_functionSet, int a_depth, boolean a_grow, int a_childIndex, boolean a_fullProgram) [inline]
Validates a_node in the context of a_chrom. Considers the recursion level (a_recursLevel), the type needed (a_type) for the node, the functions available (a_functionSet) and the depth of the whole chromosome needed (a_depth), and whether grow mode is used (a_grow is true) or not.
Parameters
a_chrom the chromosome that will contain the node, if valid
a_node the node selected and to be validated
a_rootNode root node of the node to be validated (may be null)
a_tries number of times the validator has been called, useful for stopping by returning true if the number exceeds a limit
a_num the chromosome's index in the individual of this chromosome
a_recurseLevel level of recursion
a_type the return type of the node needed
a_functionSet the array of available functions
a_depth the needed depth of the program chromosome
a_grow true: use grow mode, false: use full mode
a_childIndex index of the child in the parent node to which it belongs (-1 if node is root node)
a_fullProgram true: whole program is available in a_chrom
Returns
true: node is valid; false: node is invalid
Author
Klaus Meffert
Since
3.0
Definition at line 841 of file GPConfiguration.java.
References org.jgap.gp.impl.GPConfiguration.getNodeValidator().
Referenced by org.jgap.gp.impl.ProgramChromosome.growOrFullNode().
synchronized void org.jgap.gp.impl.GPConfiguration.verifyStateIsValid () throws InvalidConfigurationException [inline]
Definition at line 325 of file GPConfiguration.java.
Member Data Documentation
final String org.jgap.gp.impl.GPConfiguration.CVS_REVISION = `$Revision: 1.52 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 33 of file GPConfiguration.java.
CrossMethod org.jgap.gp.impl.GPConfiguration.m_crossMethod [private]
The method of crossing over two individuals during evolution.
Definition at line 113 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.compareTo(), org.jgap.gp.impl.GPConfiguration.getCrossMethod(), org.jgap.gp.impl.GPConfiguration.init(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), and org.jgap.gp.impl.GPConfiguration.setCrossoverMethod().
double org.jgap.gp.impl.GPConfiguration.m_crossoverProb = 0.9d [private]
The probability that a crossover operation is chosen during evolution. Must be between 0.0d and 1.0d, inclusive.
Definition at line 58 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.compareTo(), org.jgap.gp.impl.GPConfiguration.getCrossoverProb(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), and org.jgap.gp.impl.GPConfiguration.setCrossoverProb().
double org.jgap.gp.impl.GPConfiguration.m_dynArityProb = 0.08d [private]
The probability that the arity of a node is changed during growing a program.
Definition at line 76 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.getDynamizeArityProb(), and org.jgap.gp.impl.GPConfiguration.setDynamizeArityProb().
transient IJGAPFactory org.jgap.gp.impl.GPConfiguration.m_factory [private]
Holds the central configurable factory for creating default objects.
Author
Klaus Meffert
Since
2.6
Definition at line 164 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.getJGAPFactory(), org.jgap.gp.impl.GPConfiguration.init(), and org.jgap.gp.impl.GPConfiguration.newInstanceGP().
IGPFitnessEvaluator org.jgap.gp.impl.GPConfiguration.m_fitnessEvaluator [private]
The fitness evaluator. See interface IGPFitnessEvaluator for details.
Definition at line 131 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.compareTo(), org.jgap.gp.impl.GPConfiguration.getGPFitnessEvaluator(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), and org.jgap.gp.impl.GPConfiguration.setGPFitnessEvaluator().
double org.jgap.gp.impl.GPConfiguration.m_functionProb = 0.9d [private]
In crossover: If random number (0..1) < this value, then choose a function otherwise a terminal.
Definition at line 88 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.getFunctionProb(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), and org.jgap.gp.impl.GPConfiguration.setFunctionProb().
IGPInitStrategy org.jgap.gp.impl.GPConfiguration.m_initStrategy [private]
For initializing GP programs before random creation.
Author
Klaus Meffert
Since
2.6
Definition at line 172 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.getInitStrategy(), and org.jgap.gp.impl.GPConfiguration.setInitStrategy().
transient Hashtable<String, char[][]> org.jgap.gp.impl.GPConfiguration.m_matrices [private]
Definition at line 52 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.init().
int org.jgap.gp.impl.GPConfiguration.m_maxCrossoverDepth = 17 [private]
The maximum depth of an individual resulting from crossover.
Definition at line 93 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.compareTo(), org.jgap.gp.impl.GPConfiguration.getMaxCrossoverDepth(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), and org.jgap.gp.impl.GPConfiguration.setMaxCrossoverDepth().
int org.jgap.gp.impl.GPConfiguration.m_maxInitDepth = 7 [private]
The maximum depth of an individual when the world is created.
Definition at line 98 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.compareTo(), org.jgap.gp.impl.GPConfiguration.getMaxInitDepth(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), and org.jgap.gp.impl.GPConfiguration.setMaxInitDepth().
transient Culture org.jgap.gp.impl.GPConfiguration.m_memory = new Culture(50) [private]
Internal memory, see StoreTerminalCommand for example.
Definition at line 50 of file GPConfiguration.java.
int org.jgap.gp.impl.GPConfiguration.m_minInitDepth = 2 [private]
The minimum depth of an individual when the world is created.
Definition at line 103 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.getMinInitDepth(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), and org.jgap.gp.impl.GPConfiguration.setMinInitDepth().
double org.jgap.gp.impl.GPConfiguration.m_mutationProb = 0.1d [private]
The probability that a node is mutated during growing a program.
Definition at line 70 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.getMutationProb(), and org.jgap.gp.impl.GPConfiguration.setMutationProb().
double org.jgap.gp.impl.GPConfiguration.m_newChromsPercent = 0.3d [private]
Percentage of the population that will be filled with new individuals during evolution. Must be between 0.0d and 1.0d.
Definition at line 82 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.compareTo(), org.jgap.gp.impl.GPConfiguration.getNewChromsPercent(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), and org.jgap.gp.impl.GPConfiguration.setNewChromsPercent().
boolean org.jgap.gp.impl.GPConfiguration.m_noCommandGeneCloning [private]
TRUE: Do not clone command genes when creating a new GP program in ProgramChromosome.
Author
Klaus Meffert
Since
3.4.3
Definition at line 187 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.isNoCommandGeneCloning(), and org.jgap.gp.impl.GPConfiguration.setNoCommandGeneCloning().
INodeValidator org.jgap.gp.impl.GPConfiguration.m_nodeValidator [private]
Definition at line 133 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.getNodeValidator(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), and org.jgap.gp.impl.GPConfiguration.setNodeValidator().
GPFitnessFunction org.jgap.gp.impl.GPConfiguration.m_objectiveFunction [private]
Todo
Todo introduce lock for configuration
References the current fitness function that will be used to evaluate chromosomes during the natural selection process.
Definition at line 40 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.compareTo(), org.jgap.gp.impl.GPConfiguration.getGPFitnessFunction(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), and org.jgap.gp.impl.GPConfiguration.setFitnessFunction().
transient Map org.jgap.gp.impl.GPConfiguration.m_programCache [private]
Definition at line 156 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.init().
int org.jgap.gp.impl.GPConfiguration.m_programCreationMaxTries = 5 [private]
If m_strictProgramCreation is false: Maximum number of tries to construct a valid program.
Definition at line 126 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.compareTo(), org.jgap.gp.impl.GPConfiguration.getProgramCreationMaxtries(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), and org.jgap.gp.impl.GPConfiguration.setProgramCreationMaxTries().
IGPProgram org.jgap.gp.impl.GPConfiguration.m_prototypeProgram [private]
Prototype of a valid program. May be cloned if needed (do not reference it!).
Since
3.2
Definition at line 150 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.getPrototypeProgram(), and org.jgap.gp.impl.GPConfiguration.setPrototypeProgram().
double org.jgap.gp.impl.GPConfiguration.m_reproductionProb = 0.1d [private]
The probability that a reproduction operation is chosen during evolution. Must be between 0.0d and 1.0d. crossoverProb + reproductionProb must equal 1.0d.
Definition at line 65 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.compareTo(), org.jgap.gp.impl.GPConfiguration.getReproductionProb(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), and org.jgap.gp.impl.GPConfiguration.setReproductionProb().
INaturalGPSelector org.jgap.gp.impl.GPConfiguration.m_selectionMethod [private]
The method of choosing an individual to perform an evolution operation on.
Definition at line 108 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.compareTo(), org.jgap.gp.impl.GPConfiguration.getSelectionMethod(), org.jgap.gp.impl.GPConfiguration.GPConfiguration(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), and org.jgap.gp.impl.GPConfiguration.setSelectionMethod().
ISingleNodeValidator org.jgap.gp.impl.GPConfiguration.m_singleNodeValidator [private]
Definition at line 134 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.getSingleNodeValidator(), and org.jgap.gp.impl.GPConfiguration.setSingleNodeValidator().
Stack org.jgap.gp.impl.GPConfiguration.m_stack = new Stack() [private]
Internal stack, see PushCommand for example.
Definition at line 45 of file GPConfiguration.java.
boolean org.jgap.gp.impl.GPConfiguration.m_strictProgramCreation [private]
True: Set of available functions must contain any `type of function` that may be needed during construction of a new program. A `type of function` is, for instance, a terminal with return type CommandGene.IntegerClass.
Definition at line 120 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.compareTo(), org.jgap.gp.impl.GPConfiguration.isStrictProgramCreation(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), and org.jgap.gp.impl.GPConfiguration.setStrictProgramCreation().
boolean org.jgap.gp.impl.GPConfiguration.m_useProgramCache = false [private]
Definition at line 152 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.isUseProgramCache(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), and org.jgap.gp.impl.GPConfiguration.setUseProgramCache().
Map org.jgap.gp.impl.GPConfiguration.m_variables [private]
Definition at line 154 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.init(), and org.jgap.gp.impl.GPConfiguration.newInstanceGP().
boolean org.jgap.gp.impl.GPConfiguration.m_verify [private]
TRUE: Activate methods checkErroneousPop and checkErroneousProg in class GPGenotype.
Definition at line 178 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.isVerifyPrograms(), org.jgap.gp.impl.GPConfiguration.newInstanceGP(), and org.jgap.gp.impl.GPConfiguration.setVerifyPrograms().
transient boolean org.jgap.gp.impl.GPConfiguration.m_warningPrinted [private]
Internal flag to display a warning only once, in case a program could not be evolved with the allowed maximum number of nodes.
Since
3.2
Definition at line 142 of file GPConfiguration.java.
Referenced by org.jgap.gp.impl.GPConfiguration.flagMaxNodeWarningPrinted(), and org.jgap.gp.impl.GPConfiguration.isMaxNodeWarningPrinted().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/impl/GPConfiguration.java