org.jgap.data.config.RootConfigurationHandlerTest Class Reference
Public Member Functions
void testConstruct_0 () throws Exception
void testGetNameSpace_0 () throws Exception
void testGetPrivateField_0 () throws Exception
void testGetPrivateField_1 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
static final int NUM_CHROMS = 5
static final int NUM_GENES = 2
Additional Inherited Members
Detailed Description
Tests the RootConfigurationHandler class.
Author
Klaus Meffert
Since
3.0
Definition at line 21 of file RootConfigurationHandlerTest.java.
Member Function Documentation
static Test org.jgap.data.config.RootConfigurationHandlerTest.suite () [inline], [static]
Definition at line 32 of file RootConfigurationHandlerTest.java.
void org.jgap.data.config.RootConfigurationHandlerTest.testConstruct_0 () throws Exception [inline]
Definition at line 37 of file RootConfigurationHandlerTest.java.
References org.jgap.data.config.RootConfigurationHandler.getConfigProperties().
void org.jgap.data.config.RootConfigurationHandlerTest.testGetNameSpace_0 () throws Exception [inline]
Definition at line 42 of file RootConfigurationHandlerTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.data.config.RootConfigurationHandler.getNS().
void org.jgap.data.config.RootConfigurationHandlerTest.testGetPrivateField_0 () throws Exception [inline]
Definition at line 47 of file RootConfigurationHandlerTest.java.
References org.jgap.data.config.RootConfigurationHandler.getPrivateField().
void org.jgap.data.config.RootConfigurationHandlerTest.testGetPrivateField_1 () throws Exception [inline]
Definition at line 52 of file RootConfigurationHandlerTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.data.config.RootConfigurationHandler.getPrivateField().
Member Data Documentation
final String org.jgap.data.config.RootConfigurationHandlerTest.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file RootConfigurationHandlerTest.java.
final int org.jgap.data.config.RootConfigurationHandlerTest.NUM_CHROMS = 5 [static], [private]
Definition at line 27 of file RootConfigurationHandlerTest.java.
final int org.jgap.data.config.RootConfigurationHandlerTest.NUM_GENES = 2 [static], [private]
Definition at line 30 of file RootConfigurationHandlerTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/data/config/RootConfigurationHandlerTest.java