org.jgap.ChromosomeTest Class Reference
Classes
class MyAppObject
class MyAppObject2
class MyChromosome
class MyConstraintChecker
Public Member Functions
void setUp ()
void testConstruct_0 () throws Exception
void testConstruct_0_2 () throws Exception
void testConstruct_1 () throws Exception
void testConstruct_1_2 () throws Exception
void testConstruct_1_3 () throws Exception
void testConstruct_2 () throws Exception
void testConstruct_2_2 () throws Exception
void testConstruct_2_3 () throws Exception
void testConstruct_3 () throws Exception
void testConstruct_5_2 () throws Exception
void testConstruct_5_3 () throws Exception
void testConstruct_6 () throws Exception
void testConstruct_7_1 () throws Exception
void testConstruct_7_2 () throws Exception
void testConstruct_7_3 () throws Exception
void testConstruct_8 () throws Exception
void testConstruct_9 () throws Exception
void testConstruct_10 () throws Exception
void testConstruct_11 () throws Exception
void testConstruct_12 () throws Exception
void testConstruct_14 () throws Exception
void testClone_5 () throws Exception
void testClone_6 () throws Exception
void testClone_1 () throws InvalidConfigurationException
void testClone_2 () throws InvalidConfigurationException
void testClone_3 () throws InvalidConfigurationException
void testClone_4 () throws InvalidConfigurationException
void testClone_7 () throws Exception
void testClone_8 () throws Exception
void testHashCode_0 () throws InvalidConfigurationException
void testEquals_0 () throws Exception
void testEquals_1 () throws Exception
void testEquals_2 () throws Exception
void testEquals_3 () throws Exception
void testGetFitnessValue_0 () throws Exception
void testGetFitnessValue_1 () throws Exception
void testSize_0 () throws Exception
void testSize_1 () throws Exception
void testSize_2 () throws Exception
void testCompareTo_0 () throws Exception
void testCompareTo_0_2 () throws Exception
void testCompareTo_0_3 () throws Exception
void testCompareTo_0_4 () throws Exception
void testCompareTo_1 () throws Exception
void testCompareTo_2 () throws Exception
void testCompareTo_3 () throws Exception
void testCompareTo_4 () throws Exception
void testCompareTo_5 () throws Exception
void testCompareTo_6 () throws Exception
void testRandomInitialChromosome_0 () throws Exception
void testRandomInitialChromosome_1 () throws Exception
void testRandomInitialChromosome_2 () throws Exception
void testRandomInitialChromosome_3 () throws Exception
void testRandomInitialChromosome_4 () throws Exception
void testCleanup_0 () throws Exception
void testCleanup_2 () throws Exception
void testSetCompareApplicationData_0 () throws Exception
void testToString_0 () throws Exception
void testToString_1 () throws Exception
void testToString_2 () throws Exception
void testSetConstraintChecker_0 () throws Exception
void testSetConstraintChecker_1 () throws Exception
void testSetConstraintChecker_2 () throws Exception
void testSetConstraintChecker_3 () throws Exception
void testSetConstraintChecker_4 () throws Exception
void testIsSerializable_0 () throws Exception
void testDoSerialize_0 () throws Exception
void testIsHandlerFor_0 () throws Exception
void testSetMultiObjectives_0 () throws Exception
void testPersistentRepresentation_0 () throws Exception
void testPersistentRepresentation_1 () throws Exception
void testPersistentRepresentation_2 () throws Exception
void testPersistentRepresentation_3 () throws Exception
void testPersistentRepresentation_4 () throws Exception
void testPersistentRepresentation_6 () throws Exception
void testPersistentRepresentation_7 () throws Exception
void testPersistentRepresentation_5 () throws Exception
void testAlwaysCalculate_0 () throws Exception
void testAlwaysCalculate_1 () throws Exception
void testAlwaysCalculate_2 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.69 $`
static final int MAX_CHROMOSOME_TO_TEST = 1000
static final int MAX_GENES_TO_TEST = 25
static final int MAX_GENES_TYPES = 6
Additional Inherited Members
Detailed Description
Tests the Chromosome class.
Author
Klaus Meffert
Since
1.1
Definition at line 23 of file ChromosomeTest.java.
Member Function Documentation
void org.jgap.ChromosomeTest.setUp () [inline]
Definition at line 32 of file ChromosomeTest.java.
static Test org.jgap.ChromosomeTest.suite () [inline], [static]
Definition at line 28 of file ChromosomeTest.java.
void org.jgap.ChromosomeTest.testAlwaysCalculate_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2.2
Definition at line 1783 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.ChromosomeTest.testAlwaysCalculate_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2.2
Definition at line 1803 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.ChromosomeTest.testAlwaysCalculate_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2.2
Definition at line 1820 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.ChromosomeTest.testCleanup_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1255 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testCleanup_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 1268 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testClone_1 () throws InvalidConfigurationException [inline]
Test clone with configuration set.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Definition at line 476 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.Chromosome.clone(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseChromosome.getGenes().
void org.jgap.ChromosomeTest.testClone_2 () throws InvalidConfigurationException [inline]
Test clone with set application data implementing interface Cloneable, but restricting access because MyAppData is a package protected class (and the Chromosome class resides in different package) and also not implementing IApplicationData. But by using setAccessible in framework code, now it works. Some months ago it didn't uuumm.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Definition at line 514 of file ChromosomeTest.java.
References org.jgap.Chromosome.clone(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testClone_3 () throws InvalidConfigurationException [inline]
Test clone with set application data, where cloning supported. Access is not granted via Cloneable (because of inner class) but via explicit and specially considered interface IApplicationData (see MyAppObject2)!
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Definition at line 540 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testClone_4 () throws InvalidConfigurationException [inline]
Test clone with Gene's energy set (value should be considered, too).
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.6
Definition at line 567 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.Chromosome.clone(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.DELTA.
void org.jgap.ChromosomeTest.testClone_5 () throws Exception [inline]
Tests cloning and cleanup of a chromosome.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 431 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.Chromosome.clone(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testClone_6 () throws Exception [inline]
Tests cloning of a chromosome with genes using the chromosome pool.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 453 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.Chromosome.clone(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseChromosome.size().
void org.jgap.ChromosomeTest.testClone_7 () throws Exception [inline]
Tests cloning of sub class of org.jgap.Chromosome. This test uses a chromosome with own clone method. Thanx to Peter Molettiere for pointing out the problem with Chromosome.clone().
Exceptions
Exception
Author
Klaus Meffert
Since
3.5
Definition at line 597 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.util.ICloneable.clone(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testClone_8 () throws Exception [inline]
Tests cloning of sub class of org.jgap.Chromosome. This test uses a chromosome without own clone method.
Exceptions
Exception
Author
Klaus Meffert
Since
3.5
Definition at line 619 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.util.ICloneable.clone(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testCompareTo_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 915 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testCompareTo_0_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 936 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testCompareTo_0_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 959 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testCompareTo_0_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 984 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testCompareTo_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1009 of file ChromosomeTest.java.
References org.jgap.Chromosome.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testCompareTo_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1038 of file ChromosomeTest.java.
References org.jgap.Chromosome.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testCompareTo_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1063 of file ChromosomeTest.java.
References org.jgap.Chromosome.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testCompareTo_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1077 of file ChromosomeTest.java.
References org.jgap.Chromosome.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testCompareTo_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1106 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testCompareTo_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1127 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testConstruct_0 () throws Exception [inline]
Illegal constructions regarding second parameter.
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 45 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testConstruct_0_2 () throws Exception [inline]
Illegal constructions regarding second parameter.
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 63 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testConstruct_1 () throws Exception [inline]
Illegal constructions regarding third parameter.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 80 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testConstruct_10 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 355 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseChromosome.getGene(), and org.jgap.BaseChromosome.size().
void org.jgap.ChromosomeTest.testConstruct_11 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 372 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testConstruct_12 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 393 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testConstruct_14 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 410 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testConstruct_1_2 () throws Exception [inline]
Illegal constructions regarding third parameter.
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 98 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testConstruct_1_3 () throws Exception [inline]
Illegal constructions regarding second parameter.
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 116 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testConstruct_2 () throws Exception [inline]
Illegal constructions regarding second and third parameter.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 133 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testConstruct_2_2 () throws Exception [inline]
Illegal constructions regarding second and third parameter.
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 151 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testConstruct_2_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 167 of file ChromosomeTest.java.
void org.jgap.ChromosomeTest.testConstruct_3 () throws Exception [inline]
Legal construction.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 184 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseChromosome.size().
void org.jgap.ChromosomeTest.testConstruct_5_2 () throws Exception [inline]
Illegal constructions regarding an element of the second parameter.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 204 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testConstruct_5_3 () throws Exception [inline]
Illegal constructions regarding a gene type forbidden by the constraint checker used.
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 225 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testConstruct_6 () throws Exception [inline]
Illegal constructions regarding second parameter.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 248 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testConstruct_7_1 () throws Exception [inline]
Illegal constructions regarding second parameter.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 266 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testConstruct_7_2 () throws Exception [inline]
Illegal constructions regarding second parameter.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 284 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testConstruct_7_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 300 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseChromosome.getGene(), and org.jgap.BaseChromosome.getGenes().
void org.jgap.ChromosomeTest.testConstruct_8 () throws Exception [inline]
Illegal constructions regarding first parameter.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 316 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testConstruct_9 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 336 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseChromosome.getPersistentRepresentation().
void org.jgap.ChromosomeTest.testDoSerialize_0 () throws Exception [inline]
Ensures that Chromosome and all objects contained implement Serializable correctly.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1556 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.doSerialize().
void org.jgap.ChromosomeTest.testEquals_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 731 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.Chromosome.equals().
void org.jgap.ChromosomeTest.testEquals_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 748 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.Chromosome.equals().
void org.jgap.ChromosomeTest.testEquals_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 768 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.Chromosome.equals().
void org.jgap.ChromosomeTest.testEquals_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 802 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.Chromosome.equals().
void org.jgap.ChromosomeTest.testGetFitnessValue_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 820 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.DELTA.
void org.jgap.ChromosomeTest.testGetFitnessValue_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 843 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.DELTA.
void org.jgap.ChromosomeTest.testHashCode_0 () throws InvalidConfigurationException [inline]
Test hashcode for intensity of diversity.
Warning: when a new Gene type is added the constant MAX_GENES_TYPES must be adjusted as well as adding the new type in the switch case below.
Exceptions
InvalidConfigurationException
Author
John Serri
Since
2.1
Definition at line 648 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf, org.jgap.ChromosomeTest.MAX_CHROMOSOME_TO_TEST, org.jgap.ChromosomeTest.MAX_GENES_TO_TEST, and org.jgap.ChromosomeTest.MAX_GENES_TYPES.
void org.jgap.ChromosomeTest.testIsHandlerFor_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1574 of file ChromosomeTest.java.
References org.jgap.Chromosome.isHandlerFor(), and org.jgap.Chromosome.perform().
void org.jgap.ChromosomeTest.testIsSerializable_0 () throws Exception [inline]
Ensures Chromosome is implementing Serializable.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1539 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.isSerializable().
void org.jgap.ChromosomeTest.testPersistentRepresentation_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 1613 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseChromosome.getPersistentRepresentation().
void org.jgap.ChromosomeTest.testPersistentRepresentation_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 1635 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseChromosome.getPersistentRepresentation().
void org.jgap.ChromosomeTest.testPersistentRepresentation_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 1656 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseChromosome.size().
void org.jgap.ChromosomeTest.testPersistentRepresentation_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 1669 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testPersistentRepresentation_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 1688 of file ChromosomeTest.java.
References org.jgap.BaseChromosome.CHROM_DELIMITER, and org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testPersistentRepresentation_5 () throws Exception [inline]
Empty representation.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 1757 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseChromosome.GENE_DELIMITER, and org.jgap.BaseChromosome.size().
void org.jgap.ChromosomeTest.testPersistentRepresentation_6 () throws Exception [inline]
Invalid closing tag.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 1710 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.BaseChromosome.GENE_DELIMITER.
void org.jgap.ChromosomeTest.testPersistentRepresentation_7 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 1734 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseChromosome.getPersistentRepresentation().
void org.jgap.ChromosomeTest.testRandomInitialChromosome_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1154 of file ChromosomeTest.java.
void org.jgap.ChromosomeTest.testRandomInitialChromosome_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 1170 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testRandomInitialChromosome_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 1190 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testRandomInitialChromosome_3 () throws Exception [inline]
Use Chromosome Pool.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1208 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.FitnessFunction.NO_FITNESS_VALUE.
void org.jgap.ChromosomeTest.testRandomInitialChromosome_4 () throws Exception [inline]
Setting random generator not allowed after configuration has been locked.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 1229 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testSetCompareApplicationData_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1284 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf, org.jgap.Chromosome.isCompareApplicationData(), and org.jgap.Chromosome.randomInitialChromosome().
void org.jgap.ChromosomeTest.testSetConstraintChecker_0 () throws Exception [inline]
Test setter/getter of constraint checker.
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 1370 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.Chromosome.getConstraintChecker().
void org.jgap.ChromosomeTest.testSetConstraintChecker_1 () throws Exception [inline]
Test setter/getter of constraint checker.
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 1389 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.Chromosome.getConstraintChecker().
void org.jgap.ChromosomeTest.testSetConstraintChecker_2 () throws Exception [inline]
Test setter/getter of constraint checker.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1412 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.Chromosome.getConstraintChecker().
void org.jgap.ChromosomeTest.testSetConstraintChecker_3 () throws Exception [inline]
Test setter/getter of constraint checker which forbids the used gene type.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1432 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testSetConstraintChecker_4 () throws Exception [inline]
Test setter/getter of constraint checker which allows ther used gene type.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1453 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testSetMultiObjectives_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 1590 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.Chromosome.getMultiObjectives().
void org.jgap.ChromosomeTest.testSize_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 869 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseChromosome.size().
void org.jgap.ChromosomeTest.testSize_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 884 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseChromosome.size().
void org.jgap.ChromosomeTest.testSize_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 898 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.ChromosomeTest.testToString_0 () throws Exception [inline]
No genes.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 1301 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.IChromosome.S_SIZE, and org.jgap.BaseChromosome.size().
void org.jgap.ChromosomeTest.testToString_1 () throws Exception [inline]
Two genes.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 1321 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.IChromosome.S_SIZE.
void org.jgap.ChromosomeTest.testToString_2 () throws Exception [inline]
Considering application data.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1349 of file ChromosomeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.IChromosome.S_SIZE, and org.jgap.BaseChromosome.size().
Member Data Documentation
final String org.jgap.ChromosomeTest.CVS_REVISION = `$Revision: 1.69 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file ChromosomeTest.java.
final int org.jgap.ChromosomeTest.MAX_CHROMOSOME_TO_TEST = 1000 [static], [private]
Definition at line 632 of file ChromosomeTest.java.
Referenced by org.jgap.ChromosomeTest.testHashCode_0().
final int org.jgap.ChromosomeTest.MAX_GENES_TO_TEST = 25 [static], [private]
Definition at line 634 of file ChromosomeTest.java.
Referenced by org.jgap.ChromosomeTest.testHashCode_0().
final int org.jgap.ChromosomeTest.MAX_GENES_TYPES = 6 [static], [private]
Definition at line 636 of file ChromosomeTest.java.
Referenced by org.jgap.ChromosomeTest.testHashCode_0().
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/ChromosomeTest.java