org.jgap.gp.impl.GPGenotypeTest Class Reference
Classes
class TerminalsFirstComparator
class TerminalsOnly
Public Member Functions
void setUp ()
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testRandomInitialize_0 () throws Exception
void testSerialize_0 () throws Exception
void testReferenceProblem_0 () throws Exception
void testConfigurationInstance_0 () throws Exception
void testOutputSolution_0 () throws Exception
Static Public Member Functions
static Test suite ()
Private Member Functions
double computeFitness (IGPProgram a_program, Variable vx)
int fib_iter (int a_index)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.13 $`
Additional Inherited Members
Detailed Description
Tests the GPGenotype class.
Author
Klaus Meffert
Since
3.0
Definition at line 25 of file GPGenotypeTest.java.
Member Function Documentation
double org.jgap.gp.impl.GPGenotypeTest.computeFitness (IGPProgram a_program, Variable vx) [inline], [private]
Definition at line 150 of file GPGenotypeTest.java.
References org.jgap.gp.impl.GPGenotypeTest.fib_iter(), and org.jgap.gp.IGPProgram.size().
Referenced by org.jgap.gp.impl.GPGenotypeTest.testRandomInitialize_0().
int org.jgap.gp.impl.GPGenotypeTest.fib_iter (int a_index) [inline], [private]
Definition at line 187 of file GPGenotypeTest.java.
Referenced by org.jgap.gp.impl.GPGenotypeTest.computeFitness().
void org.jgap.gp.impl.GPGenotypeTest.setUp () [inline]
Definition at line 35 of file GPGenotypeTest.java.
static Test org.jgap.gp.impl.GPGenotypeTest.suite () [inline], [static]
Definition at line 30 of file GPGenotypeTest.java.
void org.jgap.gp.impl.GPGenotypeTest.testConfigurationInstance_0 () throws Exception [inline]
Verifies that for different genotypes different configurations are possible.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 272 of file GPGenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.GPGenotypeTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 45 of file GPGenotypeTest.java.
References org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.GPGenotypeTest.testConstruct_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 62 of file GPGenotypeTest.java.
References org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.GPGenotypeTest.testOutputSolution_0 () throws Exception [inline]
Output null solution should not produce an Exception.
Exceptions
Exception
Author
Klaus Meffert
Since
3.3
Definition at line 309 of file GPGenotypeTest.java.
References org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.GPGenotypeTest.testRandomInitialize_0 () throws Exception [inline]
Definition at line 76 of file GPGenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.GPTestCase.CMD_FOR, org.jgap.gp.impl.GPGenotypeTest.computeFitness(), org.jgap.JGAPTestCase.DELTA, org.jgap.gp.IGPProgram.getChromosome(), org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.GPTestCase.m_gpconf, and org.jgap.gp.CommandGene.VoidClass.
void org.jgap.gp.impl.GPGenotypeTest.testReferenceProblem_0 () throws Exception [inline]
Verifies that terminals are passed as clones during evolution and not as references. Thanx a lot Javier for pointing this out nicely!
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 236 of file GPGenotypeTest.java.
References org.jgap.gp.impl.ProgramChromosome.getGene(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.GPGenotypeTest.testSerialize_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 211 of file GPGenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.doSerialize(), and org.jgap.gp.GPTestCase.m_gpconf.
Member Data Documentation
final String org.jgap.gp.impl.GPGenotypeTest.CVS_REVISION = `$Revision: 1.13 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file GPGenotypeTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/gp/impl/GPGenotypeTest.java