org.jgap.impl.FixedBinaryGene Class Reference
Public Member Functions
FixedBinaryGene (final Configuration a_config, final int a_length) throws InvalidConfigurationException
FixedBinaryGene (final Configuration a_config, final FixedBinaryGene a_toCopy) throws InvalidConfigurationException
int getLength ()
Object clone ()
void setAllele (final Object a_newValue)
Object getAllele ()
int[] getIntValues ()
boolean getBit (final int a_index)
void setBit (final int a_index, final boolean a_value)
void setBit (final int a_index, final int a_value)
void setBit (final int a_from, final int a_to, final boolean a_value)
void setBit (final int a_from, final int a_to, final FixedBinaryGene a_values)
FixedBinaryGene substring (final int a_from, final int a_to)
void flip (final int a_index)
void setUnchecked (final int a_index, final boolean a_value)
String getPersistentRepresentation ()
void setValueFromPersistentRepresentation (String a_representation) throws UnsupportedRepresentationException
void setToRandomValue (final RandomGenerator a_numberGenerator)
String toString ()
String getBusinessKey ()
int size ()
void applyMutation (final int a_index, final double a_percentage)
int compareTo (final Object a_other)
int hashCode ()
Protected Member Functions
Gene newGeneInternal ()
int[] getValue ()
int checkSubLength (final int a_from, final int a_to)
void checkIndex (final int a_index)
boolean getUnchecked (final int a_index)
Object getInternalValue ()
Private Member Functions
boolean isValidRepresentation (final String a_representation)
Private Attributes
int m_length
int[] m_value
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.40 $`
static final int WORD_LEN_BITS = 32
Additional Inherited Members
Detailed Description
A Gene implementation that supports two possible values (alleles, 1 and 0) with a fixed length of alleles.
NOTE: Since this Gene implementation only supports two different values (1 and 0), there's only a 50% chance that invocation of the setToRandomValue() method will actually change the value of this Gene (if it has a value). As a result, it may be desirable to use a higher overall mutation rate when this Gene implementation is in use.
Partly adapted stuff from the JAGA (Java API for Genetic Algorithms) package (see jaga).
Author
Klaus Meffert
Since
2.0
Definition at line 32 of file FixedBinaryGene.java.
Constructor & Destructor Documentation
org.jgap.impl.FixedBinaryGene.FixedBinaryGene (final Configuration a_config, final int a_length) throws InvalidConfigurationException [inline]
Parameters
a_config the configuration to use
a_length the fixed length of the gene
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.0
Definition at line 52 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.m_length, org.jgap.impl.FixedBinaryGene.m_value, and org.jgap.impl.FixedBinaryGene.WORD_LEN_BITS.
Referenced by org.jgap.impl.FixedBinaryGene.clone(), org.jgap.impl.FixedBinaryGene.compareTo(), org.jgap.impl.FixedBinaryGene.newGeneInternal(), and org.jgap.impl.FixedBinaryGene.substring().
org.jgap.impl.FixedBinaryGene.FixedBinaryGene (final Configuration a_config, final FixedBinaryGene a_toCopy) throws InvalidConfigurationException [inline]
Definition at line 79 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.m_length, org.jgap.impl.FixedBinaryGene.m_value, and org.jgap.impl.FixedBinaryGene.WORD_LEN_BITS.
Member Function Documentation
void org.jgap.impl.FixedBinaryGene.applyMutation (final int a_index, final double a_percentage) [inline]
Applies a mutation of a given intensity (percentage) onto the atomic element at given index
Parameters
a_index index of atomic element, between 0 and size()-1
a_percentage percentage of mutation (greater than -1 and smaller than 1)
Author
Klaus Meffert
Since
2.0
Definition at line 384 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.getBit(), org.jgap.impl.FixedBinaryGene.getLength(), and org.jgap.impl.FixedBinaryGene.setBit().
void org.jgap.impl.FixedBinaryGene.checkIndex (final int a_index) [inline], [protected]
Definition at line 231 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.getLength().
Referenced by org.jgap.impl.FixedBinaryGene.checkSubLength(), org.jgap.impl.FixedBinaryGene.flip(), org.jgap.impl.FixedBinaryGene.getBit(), and org.jgap.impl.FixedBinaryGene.setBit().
int org.jgap.impl.FixedBinaryGene.checkSubLength (final int a_from, final int a_to) [inline], [protected]
Definition at line 220 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.checkIndex().
Referenced by org.jgap.impl.FixedBinaryGene.setBit(), and org.jgap.impl.FixedBinaryGene.substring().
Object org.jgap.impl.FixedBinaryGene.clone () [inline]
Definition at line 100 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.FixedBinaryGene(), and org.jgap.BaseGene.getConfiguration().
Referenced by org.jgap.impl.FixedBinaryGeneTest.testClone_0(), and org.jgap.impl.FixedBinaryGeneTest.testClone_1().
int org.jgap.impl.FixedBinaryGene.compareTo (final Object a_other) [inline]
Compares this Gene with the specified object for order. A 0 value is considered to be less than a 1 value. A null value is considered to be less than any non-null value. A Gene is greater than another one of the same length if it has more 1's than the other one. If there is the same number of 1's the Gene with the highest value (binary to int) is greater.
Parameters
a_other the FixedBinaryGene to be compared
Returns
a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than the specified object.
Exceptions
ClassCastException if the specified object's type prevents it from being compared to this Gene
Author
Klaus Meffert
Since
2.0
Definition at line 423 of file FixedBinaryGene.java.
References org.jgap.BaseGene.compareApplicationData(), org.jgap.impl.FixedBinaryGene.FixedBinaryGene(), org.jgap.BaseGene.getApplicationData(), org.jgap.impl.FixedBinaryGene.getBit(), org.jgap.impl.FixedBinaryGene.getLength(), and org.jgap.BaseGene.isCompareApplicationData().
Referenced by org.jgap.impl.FixedBinaryGeneTest.testCompareTo_0(), org.jgap.impl.FixedBinaryGeneTest.testCompareTo_1(), org.jgap.impl.FixedBinaryGeneTest.testCompareTo_2(), and org.jgap.impl.FixedBinaryGeneTest.testCompareTo_4().
void org.jgap.impl.FixedBinaryGene.flip (final int a_index) [inline]
Definition at line 212 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.checkIndex(), org.jgap.impl.FixedBinaryGene.m_value, and org.jgap.impl.FixedBinaryGene.WORD_LEN_BITS.
Object org.jgap.impl.FixedBinaryGene.getAllele () [inline]
Retrieves the value represented by this Gene. The actual type of the value is implementation-dependent.
Returns
the value of this Gene.
Since
1.0
Implements org.jgap.Gene.
Definition at line 130 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.getBit(), and org.jgap.impl.FixedBinaryGene.getLength().
boolean org.jgap.impl.FixedBinaryGene.getBit (final int a_index) [inline]
Definition at line 151 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.checkIndex(), and org.jgap.impl.FixedBinaryGene.getUnchecked().
Referenced by org.jgap.impl.FixedBinaryGene.applyMutation(), org.jgap.impl.FixedBinaryGene.compareTo(), org.jgap.impl.FixedBinaryGene.getAllele(), org.jgap.impl.FixedBinaryGeneTest.testConstruct_3(), org.jgap.impl.FixedBinaryGeneTest.testFlip_0(), org.jgap.impl.FixedBinaryGeneTest.testGetIntValues_3(), org.jgap.impl.FixedBinaryGeneTest.testSetAllele_6(), org.jgap.impl.FixedBinaryGeneTest.testSetAllele_7(), org.jgap.impl.FixedBinaryGeneTest.testSetBit_0(), org.jgap.impl.FixedBinaryGeneTest.testSetBit_0_2(), org.jgap.impl.FixedBinaryGeneTest.testSetBit_1(), org.jgap.impl.FixedBinaryGeneTest.testSetToRandomValue_2(), org.jgap.impl.FixedBinaryGeneTest.testSetToRandomValue_3(), org.jgap.impl.FixedBinaryGeneTest.testSetValueFromPersistentRepresentation_2(), org.jgap.impl.FixedBinaryGeneTest.testSetValueFromPersistentRepresentation_3(), org.jgap.impl.FixedBinaryGeneTest.testSetValueFromPersistentRepresentation_4(), and org.jgap.impl.FixedBinaryGene.toString().
String org.jgap.impl.FixedBinaryGene.getBusinessKey () [inline]
Returns
business key
Author
Klaus Meffert
Since
3.2
Implements org.jgap.IBusinessKey.
Definition at line 360 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.toString().
Object org.jgap.impl.FixedBinaryGene.getInternalValue () [inline], [protected], [virtual]
Not called as getAllele() is overridden.
Returns
same as getAllele()
Implements org.jgap.BaseGene.
Definition at line 471 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.m_value.
int [] org.jgap.impl.FixedBinaryGene.getIntValues () [inline]
Returns
internal representation of the gene's state. Use getBit for reading bits!
Definition at line 147 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.m_value.
Referenced by org.jgap.impl.FixedBinaryGeneTest.testGetIntValues_0(), and org.jgap.impl.FixedBinaryGeneTest.testGetIntValues_1().
int org.jgap.impl.FixedBinaryGene.getLength () [inline]
Definition at line 96 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.m_length.
Referenced by org.jgap.impl.FixedBinaryGene.applyMutation(), org.jgap.impl.FixedBinaryGene.checkIndex(), org.jgap.impl.FixedBinaryGene.compareTo(), org.jgap.impl.FixedBinaryGene.getAllele(), org.jgap.impl.FixedBinaryGene.setAllele(), org.jgap.impl.FixedBinaryGene.setBit(), org.jgap.impl.FixedBinaryGene.setToRandomValue(), org.jgap.impl.FixedBinaryGene.setValueFromPersistentRepresentation(), org.jgap.impl.FixedBinaryGeneTest.testGetIntValues_3(), and org.jgap.impl.FixedBinaryGene.toString().
String org.jgap.impl.FixedBinaryGene.getPersistentRepresentation () [inline]
Returns a persistent representation of an entity (such as a chromosome or a gene).
Returns
string representation of current state
Exceptions
UnsupportedOperationException
Author
Klaus Meffert
Since
3.2
Implements org.jgap.IPersistentRepresentation.
Definition at line 258 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.toString().
boolean org.jgap.impl.FixedBinaryGene.getUnchecked (final int a_index) [inline], [protected]
Definition at line 239 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.m_value, and org.jgap.impl.FixedBinaryGene.WORD_LEN_BITS.
Referenced by org.jgap.impl.FixedBinaryGene.getBit(), org.jgap.impl.FixedBinaryGene.setBit(), and org.jgap.impl.FixedBinaryGene.substring().
int [] org.jgap.impl.FixedBinaryGene.getValue () [inline], [protected]
Definition at line 92 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.m_value.
Referenced by org.jgap.impl.FixedBinaryGeneTest.testConstruct_4().
int org.jgap.impl.FixedBinaryGene.hashCode () [inline]
Modified hashCode() function to return different hashcodes for differently ordered genes in a chromosome --> does not work as internal value always initialized!
Returns
this Gene's hash code
Author
Klaus Meffert
Since
2.2
Definition at line 485 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.m_value.
boolean org.jgap.impl.FixedBinaryGene.isValidRepresentation (final String a_representation) [inline], [private]
Verifies if the String is a valid representation of this Gene type in general (bit values will not be checked)
Parameters
a_representation the representation to check
Returns
true: representation is valid in general
Author
Klaus Meffert
Since
2.0
Definition at line 315 of file FixedBinaryGene.java.
Referenced by org.jgap.impl.FixedBinaryGene.setValueFromPersistentRepresentation().
Gene org.jgap.impl.FixedBinaryGene.newGeneInternal () [inline], [protected], [virtual]
Implements org.jgap.BaseGene.
Definition at line 69 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.FixedBinaryGene(), org.jgap.BaseGene.getConfiguration(), and org.jgap.impl.FixedBinaryGene.m_length.
void org.jgap.impl.FixedBinaryGene.setAllele (final Object a_newValue) [inline]
Definition at line 109 of file FixedBinaryGene.java.
References org.jgap.BaseGene.getConstraintChecker(), org.jgap.impl.FixedBinaryGene.getLength(), and org.jgap.impl.FixedBinaryGene.setBit().
void org.jgap.impl.FixedBinaryGene.setBit (final int a_index, final boolean a_value) [inline]
Definition at line 156 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.checkIndex(), and org.jgap.impl.FixedBinaryGene.setUnchecked().
Referenced by org.jgap.impl.FixedBinaryGene.applyMutation(), org.jgap.impl.FixedBinaryGene.setAllele(), org.jgap.impl.FixedBinaryGene.setBit(), org.jgap.impl.FixedBinaryGene.setToRandomValue(), and org.jgap.impl.FixedBinaryGene.setValueFromPersistentRepresentation().
void org.jgap.impl.FixedBinaryGene.setBit (final int a_index, final int a_value) [inline]
Definition at line 161 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.setBit().
void org.jgap.impl.FixedBinaryGene.setBit (final int a_from, final int a_to, final boolean a_value) [inline]
Definition at line 176 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.checkSubLength(), and org.jgap.impl.FixedBinaryGene.setUnchecked().
void org.jgap.impl.FixedBinaryGene.setBit (final int a_from, final int a_to, final FixedBinaryGene a_values) [inline]
Definition at line 183 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.checkSubLength(), org.jgap.impl.FixedBinaryGene.getLength(), org.jgap.impl.FixedBinaryGene.getUnchecked(), and org.jgap.impl.FixedBinaryGene.setUnchecked().
void org.jgap.impl.FixedBinaryGene.setToRandomValue (final RandomGenerator a_numberGenerator) [inline]
Definition at line 322 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.getLength(), org.jgap.RandomGenerator.nextBoolean(), and org.jgap.impl.FixedBinaryGene.setBit().
void org.jgap.impl.FixedBinaryGene.setUnchecked (final int a_index, final boolean a_value) [inline]
Definition at line 246 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.m_value, and org.jgap.impl.FixedBinaryGene.WORD_LEN_BITS.
Referenced by org.jgap.impl.FixedBinaryGene.setBit().
void org.jgap.impl.FixedBinaryGene.setValueFromPersistentRepresentation (String a_representation) throws UnsupportedRepresentationException [inline]
Sets the value and internal state of this Gene from the string representation returned by a previous invocation of the getPersistentRepresentation() method. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Parameters
a_representation the string representation retrieved from a prior call to the getPersistentRepresentation() method
Exceptions
UnsupportedRepresentationException if this Gene implementation does not support the given string representation
Author
Klaus Meffert
Since
2.0
Implements org.jgap.IPersistentRepresentation.
Definition at line 279 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.getLength(), org.jgap.impl.FixedBinaryGene.isValidRepresentation(), and org.jgap.impl.FixedBinaryGene.setBit().
int org.jgap.impl.FixedBinaryGene.size () [inline]
Returns
the size of the gene, i.e the number of atomic elements
Author
Klaus Meffert
Since
2.0
Implements org.jgap.Gene.
Definition at line 370 of file FixedBinaryGene.java.
Referenced by org.jgap.impl.FixedBinaryGeneTest.testConstruct_4(), and org.jgap.impl.FixedBinaryGeneTest.testConstruct_5().
FixedBinaryGene org.jgap.impl.FixedBinaryGene.substring (final int a_from, final int a_to) [inline]
Definition at line 198 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.checkSubLength(), org.jgap.impl.FixedBinaryGene.FixedBinaryGene(), org.jgap.BaseGene.getConfiguration(), and org.jgap.impl.FixedBinaryGene.getUnchecked().
String org.jgap.impl.FixedBinaryGene.toString () [inline]
Returns
String representation
Author
Klaus Meffert
Since
2.0
Implements org.jgap.Gene.
Definition at line 338 of file FixedBinaryGene.java.
References org.jgap.impl.FixedBinaryGene.getBit(), and org.jgap.impl.FixedBinaryGene.getLength().
Referenced by org.jgap.impl.FixedBinaryGene.getBusinessKey(), org.jgap.impl.FixedBinaryGene.getPersistentRepresentation(), org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_0(), org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_1(), org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_3(), org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_4(), org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_5(), org.jgap.impl.FixedBinaryGeneTest.testConstruct_3(), and org.jgap.impl.FixedBinaryGeneTest.testConstruct_4().
Member Data Documentation
final String org.jgap.impl.FixedBinaryGene.CVS_REVISION = `$Revision: 1.40 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 35 of file FixedBinaryGene.java.
int org.jgap.impl.FixedBinaryGene.m_length [private]
Definition at line 37 of file FixedBinaryGene.java.
Referenced by org.jgap.impl.FixedBinaryGene.FixedBinaryGene(), org.jgap.impl.FixedBinaryGene.getLength(), and org.jgap.impl.FixedBinaryGene.newGeneInternal().
int [] org.jgap.impl.FixedBinaryGene.m_value [private]
Definition at line 39 of file FixedBinaryGene.java.
Referenced by org.jgap.impl.FixedBinaryGene.FixedBinaryGene(), org.jgap.impl.FixedBinaryGene.flip(), org.jgap.impl.FixedBinaryGene.getInternalValue(), org.jgap.impl.FixedBinaryGene.getIntValues(), org.jgap.impl.FixedBinaryGene.getUnchecked(), org.jgap.impl.FixedBinaryGene.getValue(), org.jgap.impl.FixedBinaryGene.hashCode(), and org.jgap.impl.FixedBinaryGene.setUnchecked().
final int org.jgap.impl.FixedBinaryGene.WORD_LEN_BITS = 32 [static], [private]
Definition at line 41 of file FixedBinaryGene.java.
Referenced by org.jgap.impl.FixedBinaryGene.FixedBinaryGene(), org.jgap.impl.FixedBinaryGene.flip(), org.jgap.impl.FixedBinaryGene.getUnchecked(), and org.jgap.impl.FixedBinaryGene.setUnchecked().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/FixedBinaryGene.java