examples.dynamicMutation.DynamicMutationFitnessFunction Class Reference
Public Member Functions
DynamicMutationFitnessFunction (int a_targetAmount)
double evaluate (IChromosome a_subject)
Static Public Member Functions
static int amountOfChange (IChromosome a_potentialSolution)
static int getNumberOfCoinsAtGene (IChromosome a_potentialSolution, int a_position)
static int getTotalNumberOfCoins (IChromosome a_potentialsolution)
Static Public Attributes
static final int MAX_BOUND = 4000
Protected Member Functions
double changeDifferenceBonus (double a_maxFitness, int a_changeDifference)
double computeCoinNumberPenalty (double a_maxFitness, int a_coins)
Private Attributes
final int m_targetAmount
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Detailed Description
Sample fitness function for the DynamicMutation example.
Author
Klaus Meffert
Since
2.6
Definition at line 20 of file DynamicMutationFitnessFunction.java.
Constructor & Destructor Documentation
examples.dynamicMutation.DynamicMutationFitnessFunction.DynamicMutationFitnessFunction (int a_targetAmount) [inline]
Definition at line 29 of file DynamicMutationFitnessFunction.java.
References examples.dynamicMutation.DynamicMutationFitnessFunction.m_targetAmount, and examples.dynamicMutation.DynamicMutationFitnessFunction.MAX_BOUND.
Member Function Documentation
static int examples.dynamicMutation.DynamicMutationFitnessFunction.amountOfChange (IChromosome a_potentialSolution) [inline], [static]
Calculates the total amount of change (in cents) represented by the given potential solution and returns that amount.
Parameters
a_potentialSolution the potential solution to evaluate
Returns
The total amount of change (in cents) represented by the given solution
Author
Neil Rotstan
Since
1.0
Definition at line 171 of file DynamicMutationFitnessFunction.java.
References examples.dynamicMutation.DynamicMutationFitnessFunction.getNumberOfCoinsAtGene().
Referenced by examples.dynamicMutation.DynamicMutationFitnessFunction.evaluate().
double examples.dynamicMutation.DynamicMutationFitnessFunction.changeDifferenceBonus (double a_maxFitness, int a_changeDifference) [inline], [protected]
Bonus calculation of fitness value.
Parameters
a_maxFitness maximum fitness value appliable
a_changeDifference change difference in coins for the coins problem
Returns
bonus for given change difference
Author
Klaus Meffert
Since
2.3
Definition at line 119 of file DynamicMutationFitnessFunction.java.
Referenced by examples.dynamicMutation.DynamicMutationFitnessFunction.evaluate().
double examples.dynamicMutation.DynamicMutationFitnessFunction.computeCoinNumberPenalty (double a_maxFitness, int a_coins) [inline], [protected]
Calculates the penalty to apply to the fitness value based on the ammount of coins in the solution
Parameters
a_maxFitness maximum fitness value allowed
a_coins number of coins in the solution
Returns
penalty for the fitness value base on the number of coins
Author
John Serri
Since
2.2
Definition at line 147 of file DynamicMutationFitnessFunction.java.
Referenced by examples.dynamicMutation.DynamicMutationFitnessFunction.evaluate().
double examples.dynamicMutation.DynamicMutationFitnessFunction.evaluate (IChromosome a_subject) [inline]
Determine the fitness of the given Chromosome instance. The higher the return value, the more fit the instance. This method should always return the same fitness value for two equivalent Chromosome instances.
Parameters
a_subject the Chromosome instance to evaluate
Returns
positive double reflecting the fitness rating of the given Chromosome
Since
2.0 (until 1.1: return type int)
Author
Neil Rotstan, Klaus Meffert, John Serri
Definition at line 49 of file DynamicMutationFitnessFunction.java.
References examples.dynamicMutation.DynamicMutationFitnessFunction.amountOfChange(), examples.dynamicMutation.DynamicMutationFitnessFunction.changeDifferenceBonus(), examples.dynamicMutation.DynamicMutationFitnessFunction.computeCoinNumberPenalty(), examples.dynamicMutation.DynamicMutationFitnessFunction.getTotalNumberOfCoins(), examples.dynamicMutation.DynamicMutationFitnessFunction.m_targetAmount, and examples.dynamicMutation.DynamicMutationFitnessFunction.MAX_BOUND.
static int examples.dynamicMutation.DynamicMutationFitnessFunction.getNumberOfCoinsAtGene (IChromosome a_potentialSolution, int a_position) [inline], [static]
Retrieves the number of coins represented by the given potential solution at the given gene position.
Parameters
a_potentialSolution the potential solution to evaluate
a_position the gene position to evaluate
Returns
the number of coins represented by the potential solution at the given gene position
Author
Neil Rotstan
Since
1.0
Definition at line 192 of file DynamicMutationFitnessFunction.java.
Referenced by examples.dynamicMutation.DynamicMutationFitnessFunction.amountOfChange(), and examples.dynamicMutation.DynamicMutationFitnessFunction.getTotalNumberOfCoins().
static int examples.dynamicMutation.DynamicMutationFitnessFunction.getTotalNumberOfCoins (IChromosome a_potentialsolution) [inline], [static]
Returns the total number of coins represented by all of the genes in the given potential solution.
Parameters
a_potentialsolution the potential solution to evaluate
Returns
total number of coins represented by the given Chromosome
Author
Neil Rotstan
Since
1.0
Definition at line 209 of file DynamicMutationFitnessFunction.java.
References examples.dynamicMutation.DynamicMutationFitnessFunction.getNumberOfCoinsAtGene().
Referenced by examples.dynamicMutation.DynamicMutationFitnessFunction.evaluate().
Member Data Documentation
final String examples.dynamicMutation.DynamicMutationFitnessFunction.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 23 of file DynamicMutationFitnessFunction.java.
final int examples.dynamicMutation.DynamicMutationFitnessFunction.m_targetAmount [private]
Definition at line 25 of file DynamicMutationFitnessFunction.java.
Referenced by examples.dynamicMutation.DynamicMutationFitnessFunction.DynamicMutationFitnessFunction(), and examples.dynamicMutation.DynamicMutationFitnessFunction.evaluate().
final int examples.dynamicMutation.DynamicMutationFitnessFunction.MAX_BOUND = 4000 [static]
Definition at line 27 of file DynamicMutationFitnessFunction.java.
Referenced by examples.dynamicMutation.DynamicMutationFitnessFunction.DynamicMutationFitnessFunction(), examples.dynamicMutation.DynamicMutationFitnessFunction.evaluate(), and examples.dynamicMutation.DynamicMutationExample.main().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/dynamicMutation/DynamicMutationFitnessFunction.java