org.jgap.distr.grid.common.BasicContext Class Reference
Public Member Functions
BasicContext ()
BasicContext (String a_appId, Object a_contextId)
Object getContextId ()
String getContextIdAsString ()
void setContextId (Object a_contextId)
String getAppId ()
void setAppId (String a_appId)
Private Attributes
String m_appId
Object m_contextId
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Detailed Description
Holds information to identify the context in which a solution should be evolved.
Author
Klaus Meffert
Since
3.3.3
Definition at line 21 of file BasicContext.java.
Constructor & Destructor Documentation
org.jgap.distr.grid.common.BasicContext.BasicContext () [inline]
Definition at line 29 of file BasicContext.java.
org.jgap.distr.grid.common.BasicContext.BasicContext (String a_appId, Object a_contextId) [inline]
Definition at line 32 of file BasicContext.java.
References org.jgap.distr.grid.common.BasicContext.setAppId(), and org.jgap.distr.grid.common.BasicContext.setContextId().
Member Function Documentation
String org.jgap.distr.grid.common.BasicContext.getAppId () [inline]
Definition at line 59 of file BasicContext.java.
References org.jgap.distr.grid.common.BasicContext.m_appId.
Object org.jgap.distr.grid.common.BasicContext.getContextId () [inline]
Definition at line 37 of file BasicContext.java.
References org.jgap.distr.grid.common.BasicContext.m_contextId.
String org.jgap.distr.grid.common.BasicContext.getContextIdAsString () [inline]
Returns
context ID as a string, as it should be a string most times (but not always!)
Definition at line 45 of file BasicContext.java.
References org.jgap.distr.grid.common.BasicContext.m_contextId.
void org.jgap.distr.grid.common.BasicContext.setAppId (String a_appId) [inline]
Definition at line 63 of file BasicContext.java.
References org.jgap.distr.grid.common.BasicContext.m_appId.
Referenced by org.jgap.distr.grid.common.BasicContext.BasicContext().
void org.jgap.distr.grid.common.BasicContext.setContextId (Object a_contextId) [inline]
Sets the context id. It is an object, not a string, as a request or a response could be available as a header-object and not by its ID.
Parameters
a_contextId the context id to set
Definition at line 55 of file BasicContext.java.
References org.jgap.distr.grid.common.BasicContext.m_contextId.
Referenced by org.jgap.distr.grid.common.BasicContext.BasicContext().
Member Data Documentation
final String org.jgap.distr.grid.common.BasicContext.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 23 of file BasicContext.java.
String org.jgap.distr.grid.common.BasicContext.m_appId [private]
Definition at line 25 of file BasicContext.java.
Referenced by org.jgap.distr.grid.common.BasicContext.getAppId(), and org.jgap.distr.grid.common.BasicContext.setAppId().
Object org.jgap.distr.grid.common.BasicContext.m_contextId [private]
Definition at line 27 of file BasicContext.java.
Referenced by org.jgap.distr.grid.common.BasicContext.getContextId(), org.jgap.distr.grid.common.BasicContext.getContextIdAsString(), and org.jgap.distr.grid.common.BasicContext.setContextId().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/distr/grid/common/BasicContext.java