org.jgap.event.EventManagerTest Class Reference
Classes
class EventListener
Public Member Functions
void testAddEventListener_0 () throws Exception
void testAddEventListener_1 () throws Exception
void testRemoveEventListener_0 () throws Exception
void testFireGeneticeEvent_0 () throws Exception
void testFireGeneticeEvent_1 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.10 $`
Additional Inherited Members
Detailed Description
Tests for EventManager class
Author
Klaus Meffert
Since
1.1
Definition at line 22 of file EventManagerTest.java.
Member Function Documentation
static Test org.jgap.event.EventManagerTest.suite () [inline], [static]
Definition at line 27 of file EventManagerTest.java.
void org.jgap.event.EventManagerTest.testAddEventListener_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 38 of file EventManagerTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.event.EventManagerTest.testAddEventListener_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 55 of file EventManagerTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.event.EventManagerTest.testFireGeneticeEvent_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 93 of file EventManagerTest.java.
void org.jgap.event.EventManagerTest.testFireGeneticeEvent_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 108 of file EventManagerTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.event.EventManagerTest.EventListener.m_event, and org.jgap.event.EventManagerTest.EventListener.m_fired.
void org.jgap.event.EventManagerTest.testRemoveEventListener_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 72 of file EventManagerTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.privateAccessor.
Member Data Documentation
final String org.jgap.event.EventManagerTest.CVS_REVISION = `$Revision: 1.10 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file EventManagerTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/event/EventManagerTest.java