org.jgap.JGAPTestCase Class Reference
Inherits TestCase.
Inherited by org.jgap.audit.EvaluatorTest, org.jgap.audit.KeyedValues2DTest, org.jgap.audit.KeyedValuesTest, org.jgap.audit.KeyedValueTest, org.jgap.audit.PermutingConfigurationTest, org.jgap.BaseGeneTest, org.jgap.BaseRateCalculatorTest, org.jgap.ChromosomeTest, org.jgap.ConfigurationTest, org.jgap.data.config.ConfigPropertyTest, org.jgap.data.config.MetaConfigTest, org.jgap.data.config.RootConfigurationHandlerTest, org.jgap.data.DataElementsDocumentTest, org.jgap.data.DataElementTest, org.jgap.data.DataTreeBuilderTest, org.jgap.DefaultFitnessEvaluatorTest, org.jgap.DeltaFitnessEvaluatorTest, org.jgap.distr.CultureMemoryCellTest, org.jgap.distr.CultureTest, org.jgap.distr.grid.DefaultGenotypeInitializerTest, org.jgap.distr.ProblemTest, org.jgap.eval.PopulationHistoryTest, org.jgap.event.EventManagerTest, org.jgap.event.GeneticEventTest, org.jgap.FitnessFunctionTest, org.jgap.GenotypeTest, org.jgap.gp.GPTestCase, org.jgap.gui.ConfigWriterTest, org.jgap.impl.AveragingCrossoverOperatorTest, org.jgap.impl.BestChromosomesSelectorTest, org.jgap.impl.BooleanGeneTest, org.jgap.impl.BulkFitnessOffsetRemoverTest, org.jgap.impl.CauchyRandomGeneratorTest, org.jgap.impl.ChainOfSelectorsTest, org.jgap.impl.ChromosomePoolTest, org.jgap.impl.CompositeGenePersistentReprTest, org.jgap.impl.CompositeGeneTest, org.jgap.impl.CrossoverOperatorTest, org.jgap.impl.DefaultCloneHandlerTest, org.jgap.impl.DefaultCompareToHandlerTest, org.jgap.impl.DefaultConfigurationTest, org.jgap.impl.DefaultCrossoverRateCalculatorTest, org.jgap.impl.DefaultInitializerTest, org.jgap.impl.DefaultMutationRateCalculatorTest, org.jgap.impl.DoubleGeneTest, org.jgap.impl.fitness.TruthTableFitnessFunctionTest, org.jgap.impl.FittestPopulationMergerTest, org.jgap.impl.FixedBinaryGeneTest, org.jgap.impl.GaussianMutationOperatorTest, org.jgap.impl.GaussianRandomGeneratorTest, org.jgap.impl.GreedyCrossoverTest, org.jgap.impl.IntegerGeneTest, org.jgap.impl.InversionOperatorTest, org.jgap.impl.JGAPFactoryTest, org.jgap.impl.job.EvolveDataTest, org.jgap.impl.MapGeneTest, org.jgap.impl.MutationOperatorTest, org.jgap.impl.NumberGeneTest, org.jgap.impl.PoolTest, org.jgap.impl.salesman.TravellingSalesmanTest, org.jgap.impl.SeededRandomGeneratorTest, org.jgap.impl.SetGeneTest, org.jgap.impl.StockRandomGeneratorTest, org.jgap.impl.StringGeneTest, org.jgap.impl.SwappingMutationOperatorTest, org.jgap.impl.ThresholdSelectorTest, org.jgap.impl.TournamentSelectorTest, org.jgap.impl.TwoWayMutationOperatorTest, org.jgap.impl.WeightedRouletteSelectorTest, org.jgap.PopulationTest, org.jgap.supergenes.SupergeneInternalParserTest, org.jgap.supergenes.SupergenePersistentRepresentationTest, org.jgap.util.FileKitTest, org.jgap.util.NumberKitTest, org.jgap.util.PluginDiscovererTest, org.jgap.xml.XMLDocumentBuilderTest, and org.jgap.xml.XMLManagerTest.
Classes
class TestFitnessFunction
Public Member Functions
JGAPTestCase (String a_name)
JGAPTestCase ()
void setUp ()
boolean isSerializable (Object a_obj)
Object doSerialize (Object a_obj) throws Exception
Object getNestedField (Object a_instance, String a_parentFieldName, String a_childFieldName) throws NoSuchFieldException
void setNestedField (Object a_instance, String a_parentFieldName, String a_childFieldName, Object a_value) throws NoSuchFieldException
boolean uniqueChromosomes (Population a_pop)
void assertEquals (double a_one, double a_two)
Static Public Member Functions
static boolean isChromosomesEqual (IChromosome[] a_list1, IChromosome[] a_list2)
static void assertEqualsMap (Map a_map1, Map a_map2)
static void assertInList (final Map a_list, Object a_object)
static void assertInList (final List a_list, Object a_object)
Public Attributes
Configuration conf
Static Public Attributes
static final PrivateAccessor privateAccessor = null
Static Protected Attributes
static final double DELTA = 0.0000001
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.21 $`
Detailed Description
Abstract test case for all JGAP test cases providing a common infrastructure.
Author
Klaus Meffert
Since
2.4
Definition at line 24 of file JGAPTestCase.java.
Constructor & Destructor Documentation
org.jgap.JGAPTestCase.JGAPTestCase (String a_name) [inline]
Definition at line 35 of file JGAPTestCase.java.
org.jgap.JGAPTestCase.JGAPTestCase () [inline]
Definition at line 39 of file JGAPTestCase.java.
Member Function Documentation
void org.jgap.JGAPTestCase.assertEquals (double a_one, double a_two) [inline]
Helper for assertion comparing two doubles with a JGAP-wide delta.
Parameters
a_one first double to compare
a_two second double to compare
Author
Klaus Meffert
Since
3.3.2
Definition at line 241 of file JGAPTestCase.java.
References org.jgap.JGAPTestCase.DELTA.
Referenced by org.jgap.impl.PoolTest.testAcquirePooledObject_0(), org.jgap.impl.WeightedRouletteSelectorTest.testAdd_0(), org.jgap.impl.BestChromosomesSelectorTest.testAdd_0(), org.jgap.impl.ThresholdSelectorTest.testAdd_0(), org.jgap.impl.TournamentSelectorTest.testAdd_0(), org.jgap.PopulationTest.testAddChromosome_0(), org.jgap.PopulationTest.testAddChromosome_1(), org.jgap.PopulationTest.testAddChromosomes_0(), org.jgap.PopulationTest.testAddChromosomes_1(), org.jgap.event.EventManagerTest.testAddEventListener_0(), org.jgap.event.EventManagerTest.testAddEventListener_1(), org.jgap.util.FileKitTest.testAddFilename_0(), org.jgap.util.FileKitTest.testAddFilename_1(), org.jgap.util.FileKitTest.testAddFilename_10(), org.jgap.util.FileKitTest.testAddFilename_11(), org.jgap.util.FileKitTest.testAddFilename_2(), org.jgap.util.FileKitTest.testAddFilename_3(), org.jgap.util.FileKitTest.testAddFilename_4(), org.jgap.util.FileKitTest.testAddFilename_5(), org.jgap.util.FileKitTest.testAddFilename_6(), org.jgap.util.FileKitTest.testAddFilename_7(), org.jgap.util.FileKitTest.testAddFilename_8(), org.jgap.util.FileKitTest.testAddFilename_9(), org.jgap.impl.CompositeGeneTest.testAddGene_0(), org.jgap.impl.CompositeGeneTest.testAddGene_1(), org.jgap.impl.CompositeGeneTest.testAddGene_2(), org.jgap.impl.CompositeGeneTest.testAddGene_4(), org.jgap.ConfigurationTest.testAddGeneticOperator_2(), org.jgap.ConfigurationTest.testAddNaturalSelector_0(), org.jgap.ConfigurationTest.testAddNaturalSelector_1(), org.jgap.ConfigurationTest.testAddNaturalSelector_2(), org.jgap.ConfigurationTest.testAddNaturalSelector_3(), org.jgap.ConfigurationTest.testAddNaturalSelector_4(), org.jgap.eval.PopulationHistoryTest.testAddPopulation_0(), org.jgap.eval.PopulationHistoryTest.testAddPopulation_1(), org.jgap.data.config.ConfigPropertyTest.testAddValue_0(), org.jgap.data.DataElementTest.testAppendChild_0(), org.jgap.data.DataElementsDocumentTest.testAppendChild_0(), org.jgap.impl.SetGeneTest.testApplyMutation_0(), org.jgap.impl.BooleanGeneTest.testApplyMutation_0(), org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_0(), org.jgap.impl.IntegerGeneTest.testApplyMutation_0(), org.jgap.impl.DoubleGeneTest.testApplyMutation_0(), org.jgap.impl.SetGeneTest.testApplyMutation_1(), org.jgap.impl.BooleanGeneTest.testApplyMutation_1(), org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_1(), org.jgap.impl.IntegerGeneTest.testApplyMutation_1(), org.jgap.impl.DoubleGeneTest.testApplyMutation_1(), org.jgap.impl.SetGeneTest.testApplyMutation_10(), org.jgap.impl.BooleanGeneTest.testApplyMutation_10(), org.jgap.impl.SetGeneTest.testApplyMutation_2(), org.jgap.impl.BooleanGeneTest.testApplyMutation_2(), org.jgap.impl.IntegerGeneTest.testApplyMutation_2(), org.jgap.impl.DoubleGeneTest.testApplyMutation_2(), org.jgap.impl.SetGeneTest.testApplyMutation_3(), org.jgap.impl.BooleanGeneTest.testApplyMutation_3(), org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_3(), org.jgap.impl.IntegerGeneTest.testApplyMutation_3(), org.jgap.impl.DoubleGeneTest.testApplyMutation_3(), org.jgap.impl.SetGeneTest.testApplyMutation_4(), org.jgap.impl.BooleanGeneTest.testApplyMutation_4(), org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_4(), org.jgap.impl.IntegerGeneTest.testApplyMutation_4(), org.jgap.impl.DoubleGeneTest.testApplyMutation_4(), org.jgap.impl.SetGeneTest.testApplyMutation_5(), org.jgap.impl.BooleanGeneTest.testApplyMutation_5(), org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_5(), org.jgap.impl.IntegerGeneTest.testApplyMutation_5(), org.jgap.impl.DoubleGeneTest.testApplyMutation_5(), org.jgap.impl.StringGeneTest.testApplyMutation_5(), org.jgap.impl.SetGeneTest.testApplyMutation_6(), org.jgap.impl.BooleanGeneTest.testApplyMutation_6(), org.jgap.impl.IntegerGeneTest.testApplyMutation_6(), org.jgap.impl.DoubleGeneTest.testApplyMutation_6(), org.jgap.impl.SetGeneTest.testApplyMutation_7(), org.jgap.impl.BooleanGeneTest.testApplyMutation_7(), org.jgap.impl.IntegerGeneTest.testApplyMutation_7(), org.jgap.impl.SetGeneTest.testApplyMutation_8(), org.jgap.impl.BooleanGeneTest.testApplyMutation_8(), org.jgap.impl.IntegerGeneTest.testApplyMutation_8(), org.jgap.impl.SetGeneTest.testApplyMutation_9(), org.jgap.impl.BooleanGeneTest.testApplyMutation_9(), org.jgap.impl.IntegerGeneTest.testApplyMutationSupportsFullIntegerRange(), org.jgap.impl.ChromosomePoolTest.testAquireChromosome_0(), org.jgap.data.DataElementTest.testAttributes_0(), org.jgap.impl.BooleanGeneTest.testBooleanValue_0(), org.jgap.impl.BooleanGeneTest.testBooleanValue_1(), org.jgap.impl.BooleanGeneTest.testBooleanValue_2(), org.jgap.impl.DoubleGeneTest.testBounds_0(), org.jgap.impl.DoubleGeneTest.testBounds_1(), org.jgap.xml.XMLDocumentBuilderTest.testBuildDocument_0(), org.jgap.xml.XMLDocumentBuilderTest.testBuildDocument_1(), org.jgap.audit.EvaluatorTest.testCalcAvgFitness_0(), org.jgap.audit.EvaluatorTest.testCalcAvgFitness_1(), org.jgap.impl.fitness.TruthTableFitnessFunctionTest.testCalcFitness_0(), org.jgap.impl.fitness.TruthTableFitnessFunctionTest.testCalcFitness_1(), org.jgap.audit.EvaluatorTest.testCalcPerformance_0(), org.jgap.audit.EvaluatorTest.testCalcPerformance_1(), org.jgap.audit.EvaluatorTest.testCalcPerformance_2(), org.jgap.impl.DefaultCrossoverRateCalculatorTest.testCalculateCurrentRate_0(), org.jgap.impl.DefaultMutationRateCalculatorTest.testCalculateCurrentRate_0(), org.jgap.impl.DefaultCrossoverRateCalculatorTest.testCalculateCurrentRate_01(), org.jgap.impl.DefaultMutationRateCalculatorTest.testCalculateCurrentRate_1(), org.jgap.impl.DefaultCrossoverRateCalculatorTest.testCalculateCurrentRate_1(), org.jgap.impl.DefaultMutationRateCalculatorTest.testCalculateCurrentRate_2(), org.jgap.xml.XMLManagerTest.testChromosome_0(), org.jgap.impl.MapGeneTest.testCleanup(), org.jgap.impl.IntegerGeneTest.testCleanup(), org.jgap.impl.DoubleGeneTest.testCleanup_0(), org.jgap.impl.CompositeGeneTest.testCleanup_0(), org.jgap.impl.CompositeGeneTest.testCleanup_1(), org.jgap.impl.PoolTest.testClear_0(), org.jgap.distr.CultureTest.testClear_0(), org.jgap.impl.ChainOfSelectorsTest.testClear_1(), org.jgap.impl.ChainOfSelectorsTest.testClear_2(), org.jgap.gp.function.ForLoopTest.testClone_0(), org.jgap.audit.KeyedValueTest.testClone_0(), org.jgap.impl.DefaultConfigurationTest.testClone_0(), org.jgap.audit.KeyedValues2DTest.testClone_0(), org.jgap.audit.KeyedValuesTest.testClone_0(), org.jgap.gp.impl.GPConfigurationTest.testClone_0(), org.jgap.impl.FixedBinaryGeneTest.testClone_0(), org.jgap.ConfigurationTest.testClone_0(), org.jgap.gp.function.ForLoopTest.testClone_1(), org.jgap.gp.impl.GPConfigurationTest.testClone_1(), org.jgap.ChromosomeTest.testClone_1(), org.jgap.impl.FixedBinaryGeneTest.testClone_1(), org.jgap.ConfigurationTest.testClone_1(), org.jgap.gp.function.ForLoopTest.testClone_2(), org.jgap.ConfigurationTest.testClone_2(), org.jgap.ChromosomeTest.testClone_3(), org.jgap.ChromosomeTest.testClone_4(), org.jgap.ChromosomeTest.testClone_5(), org.jgap.ChromosomeTest.testClone_6(), org.jgap.ChromosomeTest.testClone_7(), org.jgap.ChromosomeTest.testClone_8(), org.jgap.distr.grid.DefaultGenotypeInitializerTest.testCompareTo_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testCompareTo_0(), org.jgap.impl.SetGeneTest.testCompareTo_0(), org.jgap.impl.BooleanGeneTest.testCompareTo_0(), org.jgap.impl.InversionOperatorTest.testCompareTo_0(), org.jgap.impl.GaussianMutationOperatorTest.testCompareTo_0(), org.jgap.impl.NumberGeneTest.testCompareTo_0(), org.jgap.impl.StringGeneTest.testCompareTo_0(), org.jgap.impl.AveragingCrossoverOperatorTest.testCompareTo_0(), org.jgap.impl.MapGeneTest.testCompareTo_0(), org.jgap.impl.GreedyCrossoverTest.testCompareTo_0(), org.jgap.impl.FixedBinaryGeneTest.testCompareTo_0(), org.jgap.impl.CrossoverOperatorTest.testCompareTo_0(), org.jgap.impl.MutationOperatorTest.testCompareTo_0(), org.jgap.impl.TwoWayMutationOperatorTest.testCompareTo_0(), org.jgap.PopulationTest.testCompareTo_0(), org.jgap.impl.CompositeGeneTest.testCompareTo_0(), org.jgap.impl.SetGeneTest.testCompareTo_1(), org.jgap.impl.BooleanGeneTest.testCompareTo_1(), org.jgap.impl.NumberGeneTest.testCompareTo_1(), org.jgap.impl.AveragingCrossoverOperatorTest.testCompareTo_1(), org.jgap.impl.MapGeneTest.testCompareTo_1(), org.jgap.impl.FixedBinaryGeneTest.testCompareTo_1(), org.jgap.impl.IntegerGeneTest.testCompareTo_1(), org.jgap.impl.CompositeGeneTest.testCompareTo_1(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testCompareTo_2(), org.jgap.impl.SetGeneTest.testCompareTo_2(), org.jgap.impl.BooleanGeneTest.testCompareTo_2(), org.jgap.impl.NumberGeneTest.testCompareTo_2(), org.jgap.impl.StringGeneTest.testCompareTo_2(), org.jgap.impl.MapGeneTest.testCompareTo_2(), org.jgap.impl.FixedBinaryGeneTest.testCompareTo_2(), org.jgap.impl.IntegerGeneTest.testCompareTo_2(), org.jgap.impl.CompositeGeneTest.testCompareTo_2(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testCompareTo_3(), org.jgap.impl.SetGeneTest.testCompareTo_3(), org.jgap.impl.BooleanGeneTest.testCompareTo_3(), org.jgap.impl.NumberGeneTest.testCompareTo_3(), org.jgap.impl.MapGeneTest.testCompareTo_3(), org.jgap.impl.IntegerGeneTest.testCompareTo_3(), org.jgap.impl.CompositeGeneTest.testCompareTo_3_2(), org.jgap.impl.CompositeGeneTest.testCompareTo_4(), org.jgap.impl.BooleanGeneTest.testCompareTo_4(), org.jgap.impl.FixedBinaryGeneTest.testCompareTo_4(), org.jgap.impl.IntegerGeneTest.testCompareTo_4(), org.jgap.impl.BooleanGeneTest.testCompareTo_5(), org.jgap.impl.CompositeGeneTest.testCompareTo_5(), org.jgap.impl.BooleanGeneTest.testCompareTo_6(), org.jgap.impl.CompositeGeneTest.testCompareTo_6(), org.jgap.impl.BooleanGeneTest.testCompareTo_6_2(), org.jgap.impl.BooleanGeneTest.testCompareTo_6_3(), org.jgap.impl.BooleanGeneTest.testCompareTo_7(), org.jgap.impl.IntegerGeneTest.testCompareToNative_0(), org.jgap.impl.DoubleGeneTest.testCompareToNative_0(), org.jgap.impl.IntegerGeneTest.testCompareToNative_1(), org.jgap.impl.DoubleGeneTest.testCompareToNative_1(), org.jgap.impl.IntegerGeneTest.testCompareToNative_2(), org.jgap.impl.DoubleGeneTest.testCompareToNative_2(), org.jgap.impl.IntegerGeneTest.testCompareToNative_3(), org.jgap.impl.DoubleGeneTest.testCompareToNative_3(), org.jgap.impl.IntegerGeneTest.testCompareToNative_4(), org.jgap.impl.DoubleGeneTest.testCompareToNative_4(), org.jgap.gui.ConfigWriterTest.testConfigData_0(), org.jgap.gui.ConfigWriterTest.testConfigReader_0(), org.jgap.gp.impl.GPGenotypeTest.testConfigurationInstance_0(), org.jgap.impl.DefaultConfigurationTest.testConstruct_0(), org.jgap.data.config.ConfigPropertyTest.testConstruct_0(), org.jgap.data.DataElementsDocumentTest.testConstruct_0(), org.jgap.impl.BestChromosomesSelectorTest.testConstruct_0(), org.jgap.impl.StringGeneTest.testConstruct_0(), org.jgap.audit.KeyedValuesTest.testConstruct_0(), org.jgap.impl.MutationOperatorTest.testConstruct_0(), org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_0(), org.jgap.gp.impl.GPPopulationTest.testConstruct_0(), org.jgap.impl.SwappingMutationOperatorTest.testConstruct_0(), org.jgap.audit.KeyedValues2DTest.testConstruct_0(), org.jgap.impl.CompositeGeneTest.testConstruct_0(), org.jgap.impl.GaussianMutationOperatorTest.testConstruct_0(), org.jgap.ConfigurationTest.testConstruct_0(), org.jgap.impl.MapGeneTest.testConstruct_1(), org.jgap.impl.SetGeneTest.testConstruct_1(), org.jgap.impl.BooleanGeneTest.testConstruct_1(), org.jgap.audit.PermutingConfigurationTest.testConstruct_1(), org.jgap.impl.MutationOperatorTest.testConstruct_1(), org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_1(), org.jgap.impl.SwappingMutationOperatorTest.testConstruct_1(), org.jgap.impl.GaussianMutationOperatorTest.testConstruct_1(), org.jgap.audit.EvaluatorTest.testConstruct_1(), org.jgap.ChromosomeTest.testConstruct_10(), org.jgap.ChromosomeTest.testConstruct_11(), org.jgap.ChromosomeTest.testConstruct_14(), org.jgap.impl.ThresholdSelectorTest.testConstruct_2(), org.jgap.impl.BooleanGeneTest.testConstruct_2(), org.jgap.event.GeneticEventTest.testConstruct_2(), org.jgap.distr.CultureTest.testConstruct_2(), org.jgap.impl.MutationOperatorTest.testConstruct_2(), org.jgap.impl.SwappingMutationOperatorTest.testConstruct_2(), org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_2(), org.jgap.impl.DefaultConfigurationTest.testConstruct_2(), org.jgap.ConfigurationTest.testConstruct_2(), org.jgap.PopulationTest.testConstruct_3(), org.jgap.event.GeneticEventTest.testConstruct_3(), org.jgap.impl.MutationOperatorTest.testConstruct_3(), org.jgap.distr.ProblemTest.testConstruct_3(), org.jgap.impl.FixedBinaryGeneTest.testConstruct_3(), org.jgap.impl.SwappingMutationOperatorTest.testConstruct_3(), org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_3(), org.jgap.impl.DefaultConfigurationTest.testConstruct_3(), org.jgap.ChromosomeTest.testConstruct_3(), org.jgap.impl.GaussianMutationOperatorTest.testConstruct_3(), org.jgap.ConfigurationTest.testConstruct_3(), org.jgap.impl.CrossoverOperatorTest.testConstruct_4(), org.jgap.impl.FixedBinaryGeneTest.testConstruct_4(), org.jgap.impl.CrossoverOperatorTest.testConstruct_5(), org.jgap.impl.FixedBinaryGeneTest.testConstruct_5(), org.jgap.impl.CrossoverOperatorTest.testConstruct_6(), org.jgap.impl.CrossoverOperatorTest.testConstruct_7(), org.jgap.ChromosomeTest.testConstruct_7_3(), org.jgap.impl.CrossoverOperatorTest.testConstruct_8(), org.jgap.impl.CrossoverOperatorTest.testConstruct_9(), org.jgap.ChromosomeTest.testConstruct_9(), org.jgap.gp.impl.GPConfigurationTest.testConstructor_0(), org.jgap.impl.JGAPFactoryTest.testCreateRandomGenerator_0(), org.jgap.PopulationTest.testDetermineFittestChromosome_0(), org.jgap.PopulationTest.testDetermineFittestChromosome_1(), org.jgap.PopulationTest.testDetermineFittestChromosome_2(), org.jgap.PopulationTest.testDetermineFittestChromosome_2_0(), org.jgap.PopulationTest.testDetermineFittestChromosome_3(), org.jgap.PopulationTest.testDetermineFittestChromosome_4(), org.jgap.PopulationTest.testDetermineFittestChromosome_5(), org.jgap.PopulationTest.testDetermineFittestChromosomes_1(), org.jgap.PopulationTest.testDetermineFittestChromosomes_2(), org.jgap.PopulationTest.testDetermineFittestChromosomes_3(), org.jgap.impl.JGAPFactoryTest.testDoSerialize_0(), org.jgap.impl.SwappingMutationOperatorTest.testDoSerialize_0(), org.jgap.impl.AveragingCrossoverOperatorTest.testDoSerialize_0(), org.jgap.impl.WeightedRouletteSelectorTest.testDoSerialize_0(), org.jgap.impl.GreedyCrossoverTest.testDoSerialize_0(), org.jgap.impl.BestChromosomesSelectorTest.testDoSerialize_0(), org.jgap.impl.CrossoverOperatorTest.testDoSerialize_0(), org.jgap.impl.MutationOperatorTest.testDoSerialize_0(), org.jgap.impl.TwoWayMutationOperatorTest.testDoSerialize_0(), org.jgap.PopulationTest.testDoSerialize_0(), org.jgap.GenotypeTest.testdoSerialize_0(), org.jgap.ChromosomeTest.testDoSerialize_0(), org.jgap.impl.CrossoverOperatorTest.testDoSerialize_1(), org.jgap.impl.DoubleGeneTest.testDoubleValue_0(), org.jgap.impl.DoubleGeneTest.testDoubleValue_1(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testDummyFitnessFunction_0(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testDummyFitnessFunction_1(), org.jgap.impl.TournamentSelectorTest.testEmpty_0(), org.jgap.impl.WeightedRouletteSelectorTest.testEmpty_0(), org.jgap.impl.ThresholdSelectorTest.testEmpty_0(), org.jgap.impl.BestChromosomesSelectorTest.testEmpty_0(), org.jgap.impl.TournamentSelectorTest.testEmpty_1(), org.jgap.impl.WeightedRouletteSelectorTest.testEmpty_1(), org.jgap.impl.ThresholdSelectorTest.testEmpty_1(), org.jgap.impl.BestChromosomesSelectorTest.testEmpty_1(), org.jgap.impl.TournamentSelectorTest.testEmpty_2(), org.jgap.impl.WeightedRouletteSelectorTest.testEmpty_2(), org.jgap.impl.ThresholdSelectorTest.testEmpty_2(), org.jgap.impl.BestChromosomesSelectorTest.testEmpty_2(), org.jgap.impl.NumberGeneTest.testEquals_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testEquals_0(), org.jgap.GenotypeTest.testEquals_0(), org.jgap.impl.NumberGeneTest.testEquals_4(), org.jgap.impl.CompositeGeneTest.testEquals_6(), org.jgap.impl.CompositeGeneTest.testEquals_7(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_0(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_1(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_2(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_3(), org.jgap.GenotypeTest.testEvolve_2_1(), org.jgap.GenotypeTest.testEvolve_2_2(), org.jgap.GenotypeTest.testEvolve_2_3(), org.jgap.GenotypeTest.testEvolve_3_1(), org.jgap.GenotypeTest.testEvolve_3_25(), org.jgap.GenotypeTest.testEvolve_3_26(), org.jgap.GenotypeTest.testEvolve_5_3(), org.jgap.GenotypeTest.testEvolve_7(), org.jgap.gp.impl.GPProgramTest.testExecute_0(), org.jgap.gp.CommandDynamicArityTest.testExecution_0(), org.jgap.event.EventManagerTest.testFireGeneticeEvent_1(), org.jgap.ConfigurationTest.testGenerationNr_0(), org.jgap.xml.XMLManagerTest.testGenotype_0(), org.jgap.distr.CultureTest.testGet_2(), org.jgap.distr.CultureTest.testGet_3(), org.jgap.distr.CultureTest.testGet_4(), org.jgap.distr.CultureTest.testGet_5(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testGetAbsoluteFitness_0(), org.jgap.impl.IntegerGeneTest.testGetAllele_0(), org.jgap.impl.NumberGeneTest.testGetAllele_0(), org.jgap.impl.SetGeneTest.testGetAllele_0(), org.jgap.BaseGeneTest.testGetAllele_0(), org.jgap.impl.BooleanGeneTest.testGetAllele_0(), org.jgap.impl.DoubleGeneTest.testGetAllele_0(), org.jgap.impl.MapGeneTest.testGetAllele_0(), org.jgap.impl.FixedBinaryGeneTest.testGetAllele_0(), org.jgap.impl.StringGeneTest.testGetAllele_0(), org.jgap.impl.IntegerGeneTest.testGetAllele_1(), org.jgap.impl.NumberGeneTest.testGetAllele_1(), org.jgap.impl.BooleanGeneTest.testGetAllele_1(), org.jgap.impl.DoubleGeneTest.testGetAllele_1(), org.jgap.impl.CompositeGeneTest.testGetAllele_1(), org.jgap.impl.IntegerGeneTest.testGetAllele_2(), org.jgap.impl.NumberGeneTest.testGetAllele_2(), org.jgap.impl.DoubleGeneTest.testGetAllele_2(), org.jgap.impl.FixedBinaryGeneTest.testGetAllele_2(), org.jgap.impl.CompositeGeneTest.testGetAllele_2(), org.jgap.impl.IntegerGeneTest.testGetBounds_0(), org.jgap.impl.CauchyRandomGeneratorTest.testGetCauchyStdDeviation_0(), org.jgap.PopulationTest.testGetChromosome_0(), org.jgap.xml.XMLManagerTest.testGetChromosomeFromElement_1(), org.jgap.PopulationTest.testGetChromosomes_0(), org.jgap.GenotypeTest.testGetChromosomes_0(), org.jgap.ConfigurationTest.testGetChromosomeSize_0(), org.jgap.data.config.MetaConfigTest.testGetConfigProperty_0(), org.jgap.gp.impl.ProgramChromosomeTest.testGetDepth_0(), org.jgap.gp.impl.ProgramChromosomeTest.testGetDepth_1(), org.jgap.gp.impl.ProgramChromosomeTest.testGetDepth_2(), org.jgap.data.DataElementTest.testGetElementsByTagName_0(), org.jgap.event.GeneticEventTest.testGetEventName_0(), org.jgap.FitnessFunctionTest.testGetFitnessValue_0(), org.jgap.ChromosomeTest.testGetFitnessValue_0(), org.jgap.ChromosomeTest.testGetFitnessValue_1(), org.jgap.GenotypeTest.testGetFittestChromosome_0(), org.jgap.GenotypeTest.testGetFittestChromosome_1(), org.jgap.GenotypeTest.testGetFittestChromosomes_0(), org.jgap.impl.GaussianRandomGeneratorTest.testGetGaussianStdDeviation_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testGetGenes_0(), org.jgap.impl.CompositeGeneTest.testGetGenes_1(), org.jgap.xml.XMLManagerTest.testGetGenesFromElement_0(), org.jgap.xml.XMLManagerTest.testGetGenesFromElement_2(), org.jgap.PopulationTest.testGetGenome_0(), org.jgap.PopulationTest.testGetGenome_1(), org.jgap.PopulationTest.testGetGenome_2(), org.jgap.xml.XMLManagerTest.testGetGenotypeFromDocument_1(), org.jgap.xml.XMLManagerTest.testGetGenotypeFromElement_0(), org.jgap.audit.KeyedValuesTest.testGetIndex_0(), org.jgap.audit.KeyedValuesTest.testGetIndex_1(), org.jgap.audit.KeyedValuesTest.testGetIndex_2(), org.jgap.impl.FixedBinaryGeneTest.testGetIntValues_0(), org.jgap.impl.FixedBinaryGeneTest.testGetIntValues_2(), org.jgap.impl.FixedBinaryGeneTest.testGetIntValues_3(), org.jgap.audit.KeyedValuesTest.testGetKeys_0(), org.jgap.data.config.ConfigPropertyTest.testGetLabel_0(), org.jgap.data.config.ConfigPropertyTest.testGetName_0(), org.jgap.ConfigurationTest.testGetName_0(), org.jgap.ConfigurationTest.testGetName_1(), org.jgap.ConfigurationTest.testGetName_2(), org.jgap.data.config.RootConfigurationHandlerTest.testGetNameSpace_0(), org.jgap.ConfigurationTest.testGetNaturalSelector_0(), org.jgap.ConfigurationTest.testGetNaturalSelector_1(), org.jgap.ConfigurationTest.testGetNaturalSelector_4(), org.jgap.data.DataElementTest.testGetNodeType_0(), org.jgap.audit.EvaluatorTest.testGetNumberOfRuns_0(), org.jgap.impl.SetGeneTest.testGetPersistentRepresentation_0(), org.jgap.impl.BooleanGeneTest.testGetPersistentRepresentation_0(), org.jgap.impl.FixedBinaryGeneTest.testGetPersistentRepresentation_0(), org.jgap.impl.SetGeneTest.testGetPersistentRepresentation_1(), org.jgap.impl.BooleanGeneTest.testGetPersistentRepresentation_1(), org.jgap.impl.SetGeneTest.testGetPersistentRepresentation_2(), org.jgap.impl.BooleanGeneTest.testGetPersistentRepresentation_2(), org.jgap.impl.FixedBinaryGeneTest.testGetPersistentRepresentation_2(), org.jgap.eval.PopulationHistoryTest.testGetPopulation_0(), org.jgap.eval.PopulationHistoryTest.testGetPopulation_1(), org.jgap.eval.PopulationHistoryTest.testGetPopulations_0(), org.jgap.ConfigurationTest.testGetPopulationSize_0(), org.jgap.data.config.RootConfigurationHandlerTest.testGetPrivateField_1(), org.jgap.ConfigurationTest.testGetter_0(), org.jgap.audit.KeyedValues2DTest.testGetValue_0(), org.jgap.data.config.ConfigPropertyTest.testGetWidget_0(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_0(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_1(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_2(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_3(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_4(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_4_2(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_4_3(), org.jgap.gp.impl.ProgramChromosomeTest.testGrowNode_5(), org.jgap.impl.NumberGeneTest.testHashCode_0(), org.jgap.audit.KeyedValueTest.testHashcode_0(), org.jgap.impl.ChainOfSelectorsTest.testHashCode_0(), org.jgap.gp.CommandGeneTest.testHashCode_0(), org.jgap.BaseGeneTest.testHashCode_0(), org.jgap.audit.KeyedValuesTest.testHashcode_0(), org.jgap.impl.SetGeneTest.testHashCode_0(), org.jgap.impl.BooleanGeneTest.testHashCode_0(), org.jgap.impl.DoubleGeneTest.testHashCode_0(), org.jgap.impl.CompositeGeneTest.testHashCode_0(), org.jgap.impl.NumberGeneTest.testHashCode_1(), org.jgap.BaseGeneTest.testHashCode_1(), org.jgap.impl.DoubleGeneTest.testHashCode_1(), org.jgap.impl.FixedBinaryGeneTest.testHashCode_1(), org.jgap.impl.FixedBinaryGeneTest.testHashCode_2(), org.jgap.audit.EvaluatorTest.testHasNext_0(), org.jgap.impl.IntegerGeneTest.testIntegerGeneSupportsFullIntegerRange(), org.jgap.impl.IntegerGeneTest.testIntValue_0(), org.jgap.impl.IntegerGeneTest.testIntValue_1(), org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_0(), org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_0(), org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_1(), org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_1(), org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_2(), org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_2(), org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_3(), org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_3(), org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_4(), org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_4(), org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_5(), org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_5(), org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_6(), org.jgap.ConfigurationTest.testIsLocked_0(), org.jgap.PopulationTest.testIterator_0(), org.jgap.ConfigurationTest.testKeepPopSizeConstant_0(), org.jgap.FitnessFunctionTest.testLastComputedValue_0(), org.jgap.ConfigurationTest.testLock_1(), org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange(), org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange2(), org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange3(), org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange4(), org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange5(), org.jgap.impl.IntegerGeneTest.testMapValueToWithinBoundsSupportsFullIntegerRange(), org.jgap.gp.impl.GPConfigurationTest.testMemory_0(), org.jgap.gp.impl.GPConfigurationTest.testMemory_2(), org.jgap.impl.FittestPopulationMergerTest.testMergePopulations_0(), org.jgap.data.DataElementsDocumentTest.testNewDocument_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testNewGene_0(), org.jgap.impl.MapGeneTest.testNewGene_0(), org.jgap.impl.NumberGeneTest.testNewGene_0(), org.jgap.impl.IntegerGeneTest.testNewGene_0(), org.jgap.impl.DoubleGeneTest.testNewGene_0(), org.jgap.impl.CompositeGeneTest.testNewGene_0(), org.jgap.impl.StringGeneTest.testNewGene_0(), org.jgap.impl.FixedBinaryGeneTest.testNewGene_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testNewGene_1(), org.jgap.impl.MapGeneTest.testNewGene_1(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testNewGene_2(), org.jgap.impl.CauchyRandomGeneratorTest.testNextInt_0(), org.jgap.util.NumberKitTest.testNiceDecimalNumber_0(), org.jgap.util.NumberKitTest.testNiceDecimalNumber_1(), org.jgap.util.NumberKitTest.testNiceDecimalNumber_2(), org.jgap.util.NumberKitTest.testNiceDecimalNumber_3(), org.jgap.impl.GaussianMutationOperatorTest.testOperate_0(), org.jgap.impl.GreedyCrossoverTest.testOperate_0(), org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_0(), org.jgap.gp.impl.BranchTypingCrossTest.testOperate_0(), org.jgap.impl.InversionOperatorTest.testOperate_0(), org.jgap.impl.MutationOperatorTest.testOperate_0(), org.jgap.impl.TwoWayMutationOperatorTest.testOperate_0(), org.jgap.impl.SwappingMutationOperatorTest.testOperate_0(), org.jgap.impl.CrossoverOperatorTest.testOperate_0(), org.jgap.impl.MutationOperatorTest.testOperate_0_2(), org.jgap.impl.TwoWayMutationOperatorTest.testOperate_0_2(), org.jgap.impl.CrossoverOperatorTest.testOperate_0_2(), org.jgap.gp.impl.BranchTypingCrossTest.testOperate_1(), org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_2(), org.jgap.impl.GaussianMutationOperatorTest.testOperate_2(), org.jgap.impl.InversionOperatorTest.testOperate_2(), org.jgap.gp.impl.BranchTypingCrossTest.testOperate_2(), org.jgap.impl.CrossoverOperatorTest.testOperate_2(), org.jgap.impl.SwappingMutationOperatorTest.testOperate_3(), org.jgap.impl.MutationOperatorTest.testOperate_3(), org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_3(), org.jgap.impl.TwoWayMutationOperatorTest.testOperate_3(), org.jgap.impl.CrossoverOperatorTest.testOperate_3(), org.jgap.impl.MutationOperatorTest.testOperate_3_1(), org.jgap.impl.TwoWayMutationOperatorTest.testOperate_3_1(), org.jgap.impl.GaussianMutationOperatorTest.testOperate_4(), org.jgap.impl.GreedyCrossoverTest.testOperate_4(), org.jgap.impl.SwappingMutationOperatorTest.testOperate_4(), org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_4(), org.jgap.impl.MutationOperatorTest.testOperate_4(), org.jgap.impl.TwoWayMutationOperatorTest.testOperate_4(), org.jgap.impl.SwappingMutationOperatorTest.testOperate_5(), org.jgap.impl.GreedyCrossoverTest.testOperate_5(), org.jgap.impl.MutationOperatorTest.testOperate_5(), org.jgap.impl.TwoWayMutationOperatorTest.testOperate_5(), org.jgap.impl.MutationOperatorTest.testOperate_5_2(), org.jgap.impl.TwoWayMutationOperatorTest.testOperate_5_2(), org.jgap.impl.GreedyCrossoverTest.testOperate_6(), org.jgap.impl.MutationOperatorTest.testOperate_8(), org.jgap.impl.TwoWayMutationOperatorTest.testOperate_8(), org.jgap.impl.DefaultInitializerTest.testPerform_1(), org.jgap.impl.DefaultCompareToHandlerTest.testPerform_1(), org.jgap.impl.DefaultCloneHandlerTest.testPerform_1(), org.jgap.impl.DefaultCompareToHandlerTest.testPerform_2(), org.jgap.impl.DefaultCloneHandlerTest.testPerform_2(), org.jgap.impl.DefaultCloneHandlerTest.testPerform_3(), org.jgap.impl.DefaultCloneHandlerTest.testPerform_4(), org.jgap.impl.DefaultCloneHandlerTest.testPerform_5(), org.jgap.impl.CompositeGeneTest.testPersistentPresentation_0(), org.jgap.impl.CompositeGeneTest.testPersistentPresentation_0_2(), org.jgap.impl.CompositeGeneTest.testPersistentPresentation_1(), org.jgap.impl.CompositeGeneTest.testPersistentPresentation_2(), org.jgap.impl.CompositeGeneTest.testPersistentPresentation_7(), org.jgap.impl.MapGeneTest.testPersistentRepresentation_0(), org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_0(), org.jgap.impl.DoubleGeneTest.testPersistentRepresentation_0(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_0(), org.jgap.PopulationTest.testPersistentRepresentation_0(), org.jgap.ChromosomeTest.testPersistentRepresentation_0(), org.jgap.PopulationTest.testPersistentRepresentation_1(), org.jgap.ChromosomeTest.testPersistentRepresentation_1(), org.jgap.impl.MapGeneTest.testPersistentRepresentation_2(), org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_2(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_2(), org.jgap.PopulationTest.testPersistentRepresentation_2(), org.jgap.ChromosomeTest.testPersistentRepresentation_2(), org.jgap.impl.MapGeneTest.testPersistentRepresentation_3(), org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_3(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_3(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_4(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_5(), org.jgap.PopulationTest.testPersistentRepresentation_5(), org.jgap.ChromosomeTest.testPersistentRepresentation_5(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_5_2(), org.jgap.impl.MapGeneTest.testPersistentRepresentation_6(), org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_6(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_6(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_7(), org.jgap.ChromosomeTest.testPersistentRepresentation_7(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_9(), org.jgap.ChromosomeTest.testRandomInitialChromosome_1(), org.jgap.ChromosomeTest.testRandomInitialChromosome_3(), org.jgap.GenotypeTest.testRandomInitialGenotype_1(), org.jgap.GenotypeTest.testRandomInitialGenotype_2(), org.jgap.gp.impl.GPGenotypeTest.testRandomInitialize_0(), org.jgap.xml.XMLManagerTest.testReadFile_1(), org.jgap.impl.JGAPFactoryTest.testRegisterCloneHandler_0(), org.jgap.impl.JGAPFactoryTest.testRegisterCompareToHandler_0(), org.jgap.impl.JGAPFactoryTest.testRegisterInitializer_0(), org.jgap.impl.PoolTest.testReleaseAllObjects_0(), org.jgap.impl.PoolTest.testReleaseAllObjects_1(), org.jgap.impl.MapGeneTest.testRemoveAlleles_0(), org.jgap.impl.MapGeneTest.testRemoveAlleles_1(), org.jgap.eval.PopulationHistoryTest.testRemoveAllPopulations_0(), org.jgap.PopulationTest.testRemoveChromosome_0(), org.jgap.PopulationTest.testRemoveChromosome_3(), org.jgap.event.EventManagerTest.testRemoveEventListener_0(), org.jgap.impl.CompositeGeneTest.testRemoveGeneByIdentity_1(), org.jgap.ConfigurationTest.testRemoveNaturalSelector_0(), org.jgap.ConfigurationTest.testRemoveNaturalSelector_1(), org.jgap.ConfigurationTest.testRemoveNaturalSelector_2(), org.jgap.ConfigurationTest.testRemoveNaturalSelector_3(), org.jgap.impl.CompositeGenePersistentReprTest.testRepresentation(), org.jgap.data.DataTreeBuilderTest.testRepresentChromosomeAsDocument_0(), org.jgap.xml.XMLManagerTest.testRepresentChromosomeAsDocument_0(), org.jgap.xml.XMLManagerTest.testRepresentChromosomeAsElement_0(), org.jgap.xml.XMLManagerTest.testRepresentGenesAsElement_0(), org.jgap.data.DataTreeBuilderTest.testRepresentGenotypeAsDocument_0(), org.jgap.xml.XMLManagerTest.testRepresentGenotypeAsDocument_0(), org.jgap.xml.XMLManagerTest.testRepresentGenotypeAsElement_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testReset_0(), org.jgap.impl.WeightedRouletteSelectorTest.testSelect_0(), org.jgap.impl.WeightedRouletteSelectorTest.testSelect_1(), org.jgap.impl.ThresholdSelectorTest.testSelect_1(), org.jgap.impl.BestChromosomesSelectorTest.testSelect_1(), org.jgap.impl.TournamentSelectorTest.testSelect_1(), org.jgap.impl.WeightedRouletteSelectorTest.testSelect_2(), org.jgap.impl.ThresholdSelectorTest.testSelect_2(), org.jgap.impl.BestChromosomesSelectorTest.testSelect_2(), org.jgap.impl.TournamentSelectorTest.testSelect_2(), org.jgap.impl.WeightedRouletteSelectorTest.testSelect_4(), org.jgap.impl.BestChromosomesSelectorTest.testSelect_4(), org.jgap.impl.ThresholdSelectorTest.testSelect_5(), org.jgap.impl.TournamentSelectorTest.testSelect_5(), org.jgap.impl.TournamentSelectorTest.testSelect_6(), org.jgap.eval.PopulationHistoryTest.testSerializable_0(), org.jgap.gp.impl.GPConfigurationTest.testSerialize_0(), org.jgap.gp.impl.DefaultGPFitnessEvaluatorTest.testSerialize_0(), org.jgap.gp.impl.DeltaGPFitnessEvaluatorTest.testSerialize_0(), org.jgap.gp.impl.GPProgramTest.testSerialize_0(), org.jgap.distr.CultureMemoryCellTest.testSerialize_0(), org.jgap.gp.impl.GPPopulationTest.testSerialize_0(), org.jgap.distr.CultureTest.testSerialize_0(), org.jgap.gp.impl.GPGenotypeTest.testSerialize_0(), org.jgap.gp.impl.BranchTypingCrossTest.testSerialize_0(), org.jgap.gp.impl.ProgramChromosomeTest.testSerialize_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testSetAllele_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testSetAllele_2(), org.jgap.impl.IntegerGeneTest.testSetAllele_2(), org.jgap.impl.IntegerGeneTest.testSetAllele_3(), org.jgap.impl.DoubleGeneTest.testSetAllele_4(), org.jgap.impl.CompositeGeneTest.testSetAllele_4(), org.jgap.impl.DoubleGeneTest.testSetAllele_5(), org.jgap.impl.CompositeGeneTest.testSetAllele_5(), org.jgap.impl.StringGeneTest.testSetAllele_5(), org.jgap.impl.DoubleGeneTest.testSetAllele_6(), org.jgap.impl.StringGeneTest.testSetAllele_6(), org.jgap.impl.StringGeneTest.testSetAlphabet_1(), org.jgap.PopulationTest.testSetChromosome_0(), org.jgap.PopulationTest.testSetChromosome_1(), org.jgap.PopulationTest.testSetChromosomes_0(), org.jgap.ChromosomeTest.testSetConstraintChecker_0(), org.jgap.distr.CultureMemoryCellTest.testSetDouble_0(), org.jgap.gp.CommandGeneTest.testSetEnergy_0(), org.jgap.BaseGeneTest.testSetEnergy_0(), org.jgap.impl.NumberGeneTest.testSetEnergy_0(), org.jgap.impl.SetGeneTest.testSetEnergy_0(), org.jgap.impl.BooleanGeneTest.testSetEnergy_0(), org.jgap.impl.DoubleGeneTest.testSetEnergy_0(), org.jgap.impl.IntegerGeneTest.testSetEnergy_0(), org.jgap.impl.CompositeGeneTest.testSetEnergy_0(), org.jgap.impl.StringGeneTest.testSetEnergy_0(), org.jgap.impl.FixedBinaryGeneTest.testSetEnergy_0(), org.jgap.gp.CommandGeneTest.testSetEnergy_1(), org.jgap.BaseGeneTest.testSetEnergy_1(), org.jgap.impl.NumberGeneTest.testSetEnergy_1(), org.jgap.impl.SetGeneTest.testSetEnergy_1(), org.jgap.impl.BooleanGeneTest.testSetEnergy_1(), org.jgap.impl.DoubleGeneTest.testSetEnergy_1(), org.jgap.impl.IntegerGeneTest.testSetEnergy_1(), org.jgap.impl.CompositeGeneTest.testSetEnergy_1(), org.jgap.impl.StringGeneTest.testSetEnergy_1(), org.jgap.impl.FixedBinaryGeneTest.testSetEnergy_1(), org.jgap.impl.StringGeneTest.testSetMinMaxLength_0(), org.jgap.ChromosomeTest.testSetMultiObjectives_0(), org.jgap.ConfigurationTest.testSetNaturalSelector_0(), org.jgap.impl.BestChromosomesSelectorTest.testSetOriginalRate_1(), org.jgap.impl.JGAPFactoryTest.testSetParameters_0(), org.jgap.eval.PopulationHistoryTest.testSetPopulations_0(), org.jgap.eval.PopulationHistoryTest.testSetPopulations_1(), org.jgap.impl.TournamentSelectorTest.testSetProbability_0(), org.jgap.impl.salesman.TravellingSalesmanTest.testSetStartOffset_0(), org.jgap.impl.DoubleGeneTest.testSetToRandomValue_0(), org.jgap.impl.MapGeneTest.testSetToRandomValue_0(), org.jgap.impl.IntegerGeneTest.testSetToRandomValue_0(), org.jgap.impl.StringGeneTest.testSetToRandomValue_0(), org.jgap.impl.DoubleGeneTest.testSetToRandomValue_1(), org.jgap.impl.MapGeneTest.testSetToRandomValue_1(), org.jgap.impl.IntegerGeneTest.testSetToRandomValue_1(), org.jgap.impl.CompositeGeneTest.testSetToRandomValue_1(), org.jgap.impl.StringGeneTest.testSetToRandomValue_1(), org.jgap.impl.DoubleGeneTest.testSetToRandomValue_2(), org.jgap.impl.IntegerGeneTest.testSetToRandomValue_2(), org.jgap.impl.CompositeGeneTest.testSetToRandomValue_2(), org.jgap.impl.StringGeneTest.testSetToRandomValue_2(), org.jgap.impl.StringGeneTest.testSetToRandomValue_3(), org.jgap.impl.StringGeneTest.testSetToRandomValue_4(), org.jgap.impl.IntegerGeneTest.testSetToRandomValue_5(), org.jgap.impl.TournamentSelectorTest.testSetTournametSize_0(), org.jgap.distr.CultureMemoryCellTest.testSetValue_0(), org.jgap.audit.EvaluatorTest.testSetValue_0(), org.jgap.audit.KeyedValues2DTest.testSetValue_1(), org.jgap.audit.EvaluatorTest.testSetValue_1(), org.jgap.audit.KeyedValues2DTest.testSetValue_2(), org.jgap.audit.EvaluatorTest.testSetValue_2(), org.jgap.audit.KeyedValues2DTest.testSetValue_3(), org.jgap.audit.EvaluatorTest.testSetValue_3(), org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_1(), org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_1(), org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_2(), org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_2(), org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_3(), org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_3(), org.jgap.gp.CommandGeneTest.testSize_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testSize_0(), org.jgap.impl.PoolTest.testSize_0(), org.jgap.BaseGeneTest.testSize_0(), org.jgap.eval.PopulationHistoryTest.testSize_0(), org.jgap.PopulationTest.testSize_0(), org.jgap.ChromosomeTest.testSize_0(), org.jgap.ChromosomeTest.testSize_1(), org.jgap.gp.impl.GPConfigurationTest.testStack_0(), org.jgap.gp.impl.GPConfigurationTest.testStack_1(), org.jgap.gp.impl.GPConfigurationTest.testStack_4(), org.jgap.impl.SwappingMutationOperatorTest.testStartoffset_0(), org.jgap.impl.GreedyCrossoverTest.testStartoffset_0(), org.jgap.audit.EvaluatorTest.testStoreGenotype_0(), org.jgap.impl.FixedBinaryGeneTest.testSubbString_0(), org.jgap.supergenes.SupergeneInternalParserTest.testSupergeneInternalParser(), org.jgap.PopulationTest.testToChromosomes_0(), org.jgap.distr.CultureMemoryCellTest.testToString_0(), org.jgap.BaseGeneTest.testToString_0(), org.jgap.gp.CommandGeneTest.testToString_0(), org.jgap.impl.IntegerGeneTest.testToString_0(), org.jgap.impl.NumberGeneTest.testToString_0(), org.jgap.impl.SetGeneTest.testToString_0(), org.jgap.impl.MapGeneTest.testToString_0(), org.jgap.impl.DoubleGeneTest.testToString_0(), org.jgap.impl.BooleanGeneTest.testToString_0(), org.jgap.impl.FixedBinaryGeneTest.testToString_0(), org.jgap.impl.StringGeneTest.testToString_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testToString_0(), org.jgap.distr.CultureTest.testToString_0(), org.jgap.impl.CompositeGeneTest.testToString_0(), org.jgap.gp.impl.ProgramChromosomeTest.testToString_0(), org.jgap.GenotypeTest.testToString_0(), org.jgap.ConfigurationTest.testToString_0(), org.jgap.ChromosomeTest.testToString_0(), org.jgap.distr.CultureMemoryCellTest.testToString_1(), org.jgap.impl.IntegerGeneTest.testToString_1(), org.jgap.BaseGeneTest.testToString_1(), org.jgap.impl.SetGeneTest.testToString_1(), org.jgap.impl.MapGeneTest.testToString_1(), org.jgap.impl.DoubleGeneTest.testToString_1(), org.jgap.impl.BooleanGeneTest.testToString_1(), org.jgap.impl.FixedBinaryGeneTest.testToString_1(), org.jgap.impl.StringGeneTest.testToString_1(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testToString_1(), org.jgap.distr.CultureTest.testToString_1(), org.jgap.impl.CompositeGeneTest.testToString_1(), org.jgap.gp.impl.ProgramChromosomeTest.testToString_1(), org.jgap.GenotypeTest.testToString_1(), org.jgap.ConfigurationTest.testToString_1(), org.jgap.ChromosomeTest.testToString_1(), org.jgap.distr.CultureMemoryCellTest.testToString_2(), org.jgap.BaseGeneTest.testToString_2(), org.jgap.impl.MapGeneTest.testToString_2(), org.jgap.impl.DoubleGeneTest.testToString_2(), org.jgap.impl.BooleanGeneTest.testToString_2(), org.jgap.impl.FixedBinaryGeneTest.testToString_2(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testToString_2(), org.jgap.impl.StringGeneTest.testToString_2(), org.jgap.ChromosomeTest.testToString_2(), org.jgap.impl.MapGeneTest.testToString_3(), org.jgap.impl.MapGeneTest.testToString_4(), org.jgap.impl.MapGeneTest.testToString_5(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_0(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_1(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_2(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_3(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_4(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_5(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_6(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_7(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_8(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_9(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_A(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_B(), org.jgap.gp.impl.ProgramChromosomeTest.testToStringNorm_C(), org.jgap.ConfigurationTest.testVerifyStateIsValid_0(), org.jgap.ConfigurationTest.testVerifyStateIsValid_1(), org.jgap.ConfigurationTest.testVerifyStateIsValid_2(), org.jgap.ConfigurationTest.testVerifyStateIsValid_3(), org.jgap.ConfigurationTest.testVerifyStateIsValid_4(), org.jgap.ConfigurationTest.testVerifyStateIsValid_5(), org.jgap.ConfigurationTest.testVerifyStateIsValid_6(), and org.jgap.ConfigurationTest.testVerifyStateIsValid_7().
static void org.jgap.JGAPTestCase.assertEqualsMap (Map a_map1, Map a_map2) [inline], [static]
Todo
Todo implement
Definition at line 85 of file JGAPTestCase.java.
static void org.jgap.JGAPTestCase.assertInList (final Map a_list, Object a_object) [inline], [static]
Definition at line 101 of file JGAPTestCase.java.
static void org.jgap.JGAPTestCase.assertInList (final List a_list, Object a_object) [inline], [static]
Definition at line 117 of file JGAPTestCase.java.
Object org.jgap.JGAPTestCase.doSerialize (Object a_obj) throws Exception [inline]
Parameters
a_obj object to serialize, then deserialize
Returns
deserialized object that has previously been serialized
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 153 of file JGAPTestCase.java.
Referenced by org.jgap.impl.JGAPFactoryTest.testDoSerialize_0(), org.jgap.impl.SwappingMutationOperatorTest.testDoSerialize_0(), org.jgap.impl.AveragingCrossoverOperatorTest.testDoSerialize_0(), org.jgap.impl.WeightedRouletteSelectorTest.testDoSerialize_0(), org.jgap.impl.GreedyCrossoverTest.testDoSerialize_0(), org.jgap.impl.BestChromosomesSelectorTest.testDoSerialize_0(), org.jgap.impl.CrossoverOperatorTest.testDoSerialize_0(), org.jgap.impl.MutationOperatorTest.testDoSerialize_0(), org.jgap.impl.TwoWayMutationOperatorTest.testDoSerialize_0(), org.jgap.PopulationTest.testDoSerialize_0(), org.jgap.ChromosomeTest.testDoSerialize_0(), org.jgap.impl.CrossoverOperatorTest.testDoSerialize_1(), org.jgap.eval.PopulationHistoryTest.testSerializable_0(), org.jgap.gp.impl.GPConfigurationTest.testSerialize_0(), org.jgap.impl.CauchyRandomGeneratorTest.testSerialize_0(), org.jgap.gp.impl.DeltaGPFitnessEvaluatorTest.testSerialize_0(), org.jgap.gp.impl.DefaultGPFitnessEvaluatorTest.testSerialize_0(), org.jgap.gp.impl.GPProgramTest.testSerialize_0(), org.jgap.distr.CultureMemoryCellTest.testSerialize_0(), org.jgap.gp.impl.GPPopulationTest.testSerialize_0(), org.jgap.distr.CultureTest.testSerialize_0(), org.jgap.gp.impl.GPGenotypeTest.testSerialize_0(), org.jgap.impl.StockRandomGeneratorTest.testSerialize_0(), org.jgap.impl.SeededRandomGeneratorTest.testSerialize_0(), org.jgap.impl.GaussianRandomGeneratorTest.testSerialize_0(), org.jgap.gp.impl.BranchTypingCrossTest.testSerialize_0(), org.jgap.gp.impl.ProgramChromosomeTest.testSerialize_0(), and org.jgap.impl.GaussianRandomGeneratorTest.testSerialize_1().
Object org.jgap.JGAPTestCase.getNestedField (Object a_instance, String a_parentFieldName, String a_childFieldName) throws NoSuchFieldException [inline]
Retrieves a nested (private) field, that is field2 from `field1.field2`.
Parameters
a_instance the instance the parent field is located in
a_parentFieldName the name of the parent field (case sensitive!)
a_childFieldName the name of the child field (case sensitive!)
Exceptions
NoSuchFieldException
Returns
the value of the child field
Author
Klaus Meffert
Since
2.6
Definition at line 182 of file JGAPTestCase.java.
Referenced by org.jgap.impl.ThresholdSelectorTest.testConstruct_2().
static boolean org.jgap.JGAPTestCase.isChromosomesEqual (IChromosome[] a_list1, IChromosome[] a_list2) [inline], [static]
Parameters
a_list1 first list of chromosomes
a_list2 second list of chromosomes
Returns
true lists of chromosomes are equal
Author
Klaus Meffert
Definition at line 60 of file JGAPTestCase.java.
Referenced by org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_1(), org.jgap.impl.GaussianMutationOperatorTest.testOperate_1(), org.jgap.impl.InversionOperatorTest.testOperate_1(), and org.jgap.impl.CrossoverOperatorTest.testOperate_1().
boolean org.jgap.JGAPTestCase.isSerializable (Object a_obj) [inline]
Parameters
a_obj object to verify
Returns
true: object implements serializable
Author
Klaus Meffert
Since
2.6
Definition at line 140 of file JGAPTestCase.java.
Referenced by org.jgap.impl.JGAPFactoryTest.testIsSerializable_0(), org.jgap.impl.SwappingMutationOperatorTest.testIsSerializable_0(), org.jgap.impl.AveragingCrossoverOperatorTest.testIsSerializable_0(), org.jgap.impl.WeightedRouletteSelectorTest.testIsSerializable_0(), org.jgap.impl.GreedyCrossoverTest.testIsSerializable_0(), org.jgap.impl.BestChromosomesSelectorTest.testIsSerializable_0(), org.jgap.impl.CrossoverOperatorTest.testIsSerializable_0(), org.jgap.impl.TwoWayMutationOperatorTest.testIsSerializable_0(), org.jgap.impl.MutationOperatorTest.testIsSerializable_0(), org.jgap.PopulationTest.testIsSerializable_0(), org.jgap.GenotypeTest.testIsSerializable_0(), and org.jgap.ChromosomeTest.testIsSerializable_0().
void org.jgap.JGAPTestCase.setNestedField (Object a_instance, String a_parentFieldName, String a_childFieldName, Object a_value) throws NoSuchFieldException [inline]
Sets a nested (private) field, that is field2 from `field1.field2`.
Parameters
a_instance the instance the parent field is located in
a_parentFieldName the name of the parent field (case sensitive!)
a_childFieldName the name of the child field (case sensitive!)
a_value the value to set the child field to
Exceptions
NoSuchFieldException
Author
Klaus Meffert
Since
2.6
Definition at line 202 of file JGAPTestCase.java.
Referenced by org.jgap.impl.TournamentSelectorTest.testSelect_5().
void org.jgap.JGAPTestCase.setUp () [inline]
Definition at line 43 of file JGAPTestCase.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.PROPERTY_JGAPFACTORY_CLASS.
boolean org.jgap.JGAPTestCase.uniqueChromosomes (Population a_pop) [inline]
Are all chromosomes in the given population unique?
Parameters
a_pop the population to verify
Returns
true if all chromosomes in the population are unique
Author
Klaus Meffert
Since
3.3.1
Definition at line 218 of file JGAPTestCase.java.
Referenced by org.jgap.GenotypeTest.testEvolve_0(), org.jgap.GenotypeTest.testEvolve_1(), org.jgap.GenotypeTest.testEvolve_10(), org.jgap.GenotypeTest.testEvolve_2_1(), org.jgap.GenotypeTest.testEvolve_2_2(), org.jgap.GenotypeTest.testEvolve_2_3(), org.jgap.GenotypeTest.testEvolve_3_1(), org.jgap.GenotypeTest.testEvolve_3_2(), org.jgap.GenotypeTest.testEvolve_3_25(), org.jgap.GenotypeTest.testEvolve_3_26(), org.jgap.GenotypeTest.testEvolve_7(), org.jgap.GenotypeTest.testEvolve_8(), and org.jgap.GenotypeTest.testEvolve_9().
Member Data Documentation
Configuration org.jgap.JGAPTestCase.conf
Definition at line 33 of file JGAPTestCase.java.
Referenced by org.jgap.impl.GreedyCrossoverTest.chromosome(), org.jgap.impl.CompositeGenePersistentReprTest.createSampleNestedGene(), org.jgap.JGAPTestCase.setUp(), org.jgap.xml.XMLManagerTest.setUp(), org.jgap.impl.WeightedRouletteSelectorTest.testAdd_0(), org.jgap.impl.BestChromosomesSelectorTest.testAdd_0(), org.jgap.impl.ThresholdSelectorTest.testAdd_0(), org.jgap.impl.TournamentSelectorTest.testAdd_0(), org.jgap.PopulationTest.testAddChromosome_0(), org.jgap.PopulationTest.testAddChromosome_1(), org.jgap.PopulationTest.testAddChromosomes_0(), org.jgap.PopulationTest.testAddChromosomes_1(), org.jgap.impl.CompositeGeneTest.testAddGene_0(), org.jgap.impl.CompositeGeneTest.testAddGene_1(), org.jgap.impl.CompositeGeneTest.testAddGene_2(), org.jgap.impl.CompositeGeneTest.testAddGene_3(), org.jgap.impl.CompositeGeneTest.testAddGene_4(), org.jgap.impl.CompositeGeneTest.testAddGene_5(), org.jgap.impl.CompositeGeneTest.testAddGene_6(), org.jgap.impl.CompositeGeneTest.testAddGene_7(), org.jgap.ConfigurationTest.testAddGeneticOperator_0(), org.jgap.ConfigurationTest.testAddGeneticOperator_1(), org.jgap.ConfigurationTest.testAddGeneticOperator_2(), org.jgap.impl.ChainOfSelectorsTest.testAddNaturalSelector_0(), org.jgap.ConfigurationTest.testAddNaturalSelector_0(), org.jgap.ConfigurationTest.testAddNaturalSelector_1(), org.jgap.ConfigurationTest.testAddNaturalSelector_2(), org.jgap.ConfigurationTest.testAddNaturalSelector_3(), org.jgap.ConfigurationTest.testAddNaturalSelector_4(), org.jgap.eval.PopulationHistoryTest.testAddPopulation_0(), org.jgap.eval.PopulationHistoryTest.testAddPopulation_1(), org.jgap.ChromosomeTest.testAlwaysCalculate_0(), org.jgap.ChromosomeTest.testAlwaysCalculate_1(), org.jgap.ChromosomeTest.testAlwaysCalculate_2(), org.jgap.impl.SetGeneTest.testApplyMutation_0(), org.jgap.impl.BooleanGeneTest.testApplyMutation_0(), org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_0(), org.jgap.impl.IntegerGeneTest.testApplyMutation_0(), org.jgap.impl.DoubleGeneTest.testApplyMutation_0(), org.jgap.impl.StringGeneTest.testApplyMutation_0(), org.jgap.impl.CompositeGeneTest.testApplyMutation_0(), org.jgap.impl.SetGeneTest.testApplyMutation_1(), org.jgap.impl.BooleanGeneTest.testApplyMutation_1(), org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_1(), org.jgap.impl.IntegerGeneTest.testApplyMutation_1(), org.jgap.impl.DoubleGeneTest.testApplyMutation_1(), org.jgap.impl.StringGeneTest.testApplyMutation_1(), org.jgap.impl.SetGeneTest.testApplyMutation_10(), org.jgap.impl.BooleanGeneTest.testApplyMutation_10(), org.jgap.impl.SetGeneTest.testApplyMutation_2(), org.jgap.impl.BooleanGeneTest.testApplyMutation_2(), org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_2(), org.jgap.impl.IntegerGeneTest.testApplyMutation_2(), org.jgap.impl.DoubleGeneTest.testApplyMutation_2(), org.jgap.impl.StringGeneTest.testApplyMutation_2(), org.jgap.impl.SetGeneTest.testApplyMutation_3(), org.jgap.impl.BooleanGeneTest.testApplyMutation_3(), org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_3(), org.jgap.impl.IntegerGeneTest.testApplyMutation_3(), org.jgap.impl.DoubleGeneTest.testApplyMutation_3(), org.jgap.impl.StringGeneTest.testApplyMutation_3(), org.jgap.impl.SetGeneTest.testApplyMutation_4(), org.jgap.impl.BooleanGeneTest.testApplyMutation_4(), org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_4(), org.jgap.impl.IntegerGeneTest.testApplyMutation_4(), org.jgap.impl.DoubleGeneTest.testApplyMutation_4(), org.jgap.impl.StringGeneTest.testApplyMutation_4(), org.jgap.impl.SetGeneTest.testApplyMutation_5(), org.jgap.impl.BooleanGeneTest.testApplyMutation_5(), org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_5(), org.jgap.impl.IntegerGeneTest.testApplyMutation_5(), org.jgap.impl.DoubleGeneTest.testApplyMutation_5(), org.jgap.impl.StringGeneTest.testApplyMutation_5(), org.jgap.impl.SetGeneTest.testApplyMutation_6(), org.jgap.impl.BooleanGeneTest.testApplyMutation_6(), org.jgap.impl.IntegerGeneTest.testApplyMutation_6(), org.jgap.impl.DoubleGeneTest.testApplyMutation_6(), org.jgap.impl.StringGeneTest.testApplyMutation_6(), org.jgap.impl.SetGeneTest.testApplyMutation_7(), org.jgap.impl.BooleanGeneTest.testApplyMutation_7(), org.jgap.impl.IntegerGeneTest.testApplyMutation_7(), org.jgap.impl.DoubleGeneTest.testApplyMutation_7(), org.jgap.impl.StringGeneTest.testApplyMutation_7(), org.jgap.impl.SetGeneTest.testApplyMutation_8(), org.jgap.impl.BooleanGeneTest.testApplyMutation_8(), org.jgap.impl.IntegerGeneTest.testApplyMutation_8(), org.jgap.impl.SetGeneTest.testApplyMutation_9(), org.jgap.impl.BooleanGeneTest.testApplyMutation_9(), org.jgap.impl.IntegerGeneTest.testApplyMutationSupportsFullIntegerRange(), org.jgap.impl.BooleanGeneTest.testBooleanValue_0(), org.jgap.impl.BooleanGeneTest.testBooleanValue_1(), org.jgap.impl.BooleanGeneTest.testBooleanValue_2(), org.jgap.impl.DoubleGeneTest.testBounds_0(), org.jgap.impl.DoubleGeneTest.testBounds_1(), org.jgap.GenotypeTest.testBreeder_0(), org.jgap.xml.XMLDocumentBuilderTest.testBuildDocument_0(), org.jgap.xml.XMLDocumentBuilderTest.testBuildDocument_1(), org.jgap.audit.EvaluatorTest.testCalcAvgFitness_0(), org.jgap.audit.EvaluatorTest.testCalcAvgFitness_1(), org.jgap.impl.fitness.TruthTableFitnessFunctionTest.testCalcFitness_0(), org.jgap.impl.fitness.TruthTableFitnessFunctionTest.testCalcFitness_1(), org.jgap.impl.fitness.TruthTableFitnessFunctionTest.testCalcFitness_2(), org.jgap.audit.EvaluatorTest.testCalcPerformance_0(), org.jgap.audit.EvaluatorTest.testCalcPerformance_1(), org.jgap.audit.EvaluatorTest.testCalcPerformance_2(), org.jgap.impl.DefaultCrossoverRateCalculatorTest.testCalculateCurrentRate_0(), org.jgap.impl.DefaultMutationRateCalculatorTest.testCalculateCurrentRate_0(), org.jgap.impl.DefaultCrossoverRateCalculatorTest.testCalculateCurrentRate_01(), org.jgap.impl.DefaultMutationRateCalculatorTest.testCalculateCurrentRate_1(), org.jgap.impl.DefaultCrossoverRateCalculatorTest.testCalculateCurrentRate_1(), org.jgap.impl.DefaultMutationRateCalculatorTest.testCalculateCurrentRate_2(), org.jgap.xml.XMLManagerTest.testChromosome_0(), org.jgap.impl.MapGeneTest.testCleanup(), org.jgap.impl.IntegerGeneTest.testCleanup(), org.jgap.BaseGeneTest.testCleanup_0(), org.jgap.impl.DoubleGeneTest.testCleanup_0(), org.jgap.impl.CompositeGeneTest.testCleanup_0(), org.jgap.ChromosomeTest.testCleanup_0(), org.jgap.impl.CompositeGeneTest.testCleanup_1(), org.jgap.ChromosomeTest.testCleanup_2(), org.jgap.impl.ChainOfSelectorsTest.testClear_0(), org.jgap.impl.ChainOfSelectorsTest.testClear_1(), org.jgap.impl.ChainOfSelectorsTest.testClear_2(), org.jgap.impl.DefaultConfigurationTest.testClone_0(), org.jgap.gp.impl.GPConfigurationTest.testClone_0(), org.jgap.impl.FixedBinaryGeneTest.testClone_0(), org.jgap.ConfigurationTest.testClone_0(), org.jgap.gp.impl.GPConfigurationTest.testClone_1(), org.jgap.ChromosomeTest.testClone_1(), org.jgap.impl.FixedBinaryGeneTest.testClone_1(), org.jgap.ConfigurationTest.testClone_1(), org.jgap.ChromosomeTest.testClone_2(), org.jgap.ConfigurationTest.testClone_2(), org.jgap.ChromosomeTest.testClone_3(), org.jgap.ChromosomeTest.testClone_4(), org.jgap.ChromosomeTest.testClone_5(), org.jgap.ChromosomeTest.testClone_6(), org.jgap.ChromosomeTest.testClone_7(), org.jgap.ChromosomeTest.testClone_8(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testCompareTo_0(), org.jgap.impl.SetGeneTest.testCompareTo_0(), org.jgap.impl.BooleanGeneTest.testCompareTo_0(), org.jgap.impl.GaussianMutationOperatorTest.testCompareTo_0(), org.jgap.impl.InversionOperatorTest.testCompareTo_0(), org.jgap.impl.NumberGeneTest.testCompareTo_0(), org.jgap.impl.StringGeneTest.testCompareTo_0(), org.jgap.impl.AveragingCrossoverOperatorTest.testCompareTo_0(), org.jgap.impl.MapGeneTest.testCompareTo_0(), org.jgap.impl.GreedyCrossoverTest.testCompareTo_0(), org.jgap.impl.FixedBinaryGeneTest.testCompareTo_0(), org.jgap.impl.CrossoverOperatorTest.testCompareTo_0(), org.jgap.impl.IntegerGeneTest.testCompareTo_0(), org.jgap.PopulationTest.testCompareTo_0(), org.jgap.ChromosomeTest.testCompareTo_0(), org.jgap.impl.CompositeGeneTest.testCompareTo_0(), org.jgap.ChromosomeTest.testCompareTo_0_2(), org.jgap.ChromosomeTest.testCompareTo_0_3(), org.jgap.ChromosomeTest.testCompareTo_0_4(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testCompareTo_1(), org.jgap.impl.SetGeneTest.testCompareTo_1(), org.jgap.impl.BooleanGeneTest.testCompareTo_1(), org.jgap.impl.NumberGeneTest.testCompareTo_1(), org.jgap.impl.StringGeneTest.testCompareTo_1(), org.jgap.impl.AveragingCrossoverOperatorTest.testCompareTo_1(), org.jgap.impl.MapGeneTest.testCompareTo_1(), org.jgap.impl.FixedBinaryGeneTest.testCompareTo_1(), org.jgap.impl.IntegerGeneTest.testCompareTo_1(), org.jgap.impl.CompositeGeneTest.testCompareTo_1(), org.jgap.ChromosomeTest.testCompareTo_1(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testCompareTo_2(), org.jgap.impl.SetGeneTest.testCompareTo_2(), org.jgap.impl.BooleanGeneTest.testCompareTo_2(), org.jgap.impl.NumberGeneTest.testCompareTo_2(), org.jgap.impl.StringGeneTest.testCompareTo_2(), org.jgap.impl.MapGeneTest.testCompareTo_2(), org.jgap.impl.FixedBinaryGeneTest.testCompareTo_2(), org.jgap.impl.IntegerGeneTest.testCompareTo_2(), org.jgap.impl.CompositeGeneTest.testCompareTo_2(), org.jgap.ChromosomeTest.testCompareTo_2(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testCompareTo_3(), org.jgap.impl.SetGeneTest.testCompareTo_3(), org.jgap.impl.BooleanGeneTest.testCompareTo_3(), org.jgap.impl.NumberGeneTest.testCompareTo_3(), org.jgap.impl.MapGeneTest.testCompareTo_3(), org.jgap.impl.IntegerGeneTest.testCompareTo_3(), org.jgap.impl.CompositeGeneTest.testCompareTo_3(), org.jgap.ChromosomeTest.testCompareTo_3(), org.jgap.impl.FixedBinaryGeneTest.testCompareTo_3_1(), org.jgap.impl.FixedBinaryGeneTest.testCompareTo_3_2(), org.jgap.impl.CompositeGeneTest.testCompareTo_3_2(), org.jgap.impl.CompositeGeneTest.testCompareTo_4(), org.jgap.impl.BooleanGeneTest.testCompareTo_4(), org.jgap.impl.FixedBinaryGeneTest.testCompareTo_4(), org.jgap.impl.IntegerGeneTest.testCompareTo_4(), org.jgap.ChromosomeTest.testCompareTo_4(), org.jgap.impl.BooleanGeneTest.testCompareTo_5(), org.jgap.impl.CompositeGeneTest.testCompareTo_5(), org.jgap.ChromosomeTest.testCompareTo_5(), org.jgap.impl.BooleanGeneTest.testCompareTo_6(), org.jgap.impl.CompositeGeneTest.testCompareTo_6(), org.jgap.ChromosomeTest.testCompareTo_6(), org.jgap.impl.BooleanGeneTest.testCompareTo_6_2(), org.jgap.impl.BooleanGeneTest.testCompareTo_6_3(), org.jgap.impl.BooleanGeneTest.testCompareTo_7(), org.jgap.impl.IntegerGeneTest.testCompareToNative_0(), org.jgap.impl.DoubleGeneTest.testCompareToNative_0(), org.jgap.impl.IntegerGeneTest.testCompareToNative_1(), org.jgap.impl.DoubleGeneTest.testCompareToNative_1(), org.jgap.impl.IntegerGeneTest.testCompareToNative_2(), org.jgap.impl.DoubleGeneTest.testCompareToNative_2(), org.jgap.impl.IntegerGeneTest.testCompareToNative_3(), org.jgap.impl.DoubleGeneTest.testCompareToNative_3(), org.jgap.impl.IntegerGeneTest.testCompareToNative_4(), org.jgap.impl.DoubleGeneTest.testCompareToNative_4(), org.jgap.gui.ConfigWriterTest.testConfigReader_0(), org.jgap.impl.BooleanGeneTest.testConstruct_0(), org.jgap.impl.IntegerGeneTest.testConstruct_0(), org.jgap.impl.SetGeneTest.testConstruct_0(), org.jgap.impl.MapGeneTest.testConstruct_0(), org.jgap.impl.ChainOfSelectorsTest.testConstruct_0(), org.jgap.BaseRateCalculatorTest.testConstruct_0(), org.jgap.impl.DefaultConfigurationTest.testConstruct_0(), org.jgap.impl.FixedBinaryGeneTest.testConstruct_0(), org.jgap.BaseGeneTest.testConstruct_0(), org.jgap.impl.BestChromosomesSelectorTest.testConstruct_0(), org.jgap.impl.StringGeneTest.testConstruct_0(), org.jgap.impl.NumberGeneTest.testConstruct_0(), org.jgap.impl.DoubleGeneTest.testConstruct_0(), org.jgap.impl.TournamentSelectorTest.testConstruct_0(), org.jgap.impl.InversionOperatorTest.testConstruct_0(), org.jgap.impl.CrossoverOperatorTest.testConstruct_0(), org.jgap.impl.MutationOperatorTest.testConstruct_0(), org.jgap.impl.WeightedRouletteSelectorTest.testConstruct_0(), org.jgap.ChromosomeTest.testConstruct_0(), org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_0(), org.jgap.impl.SwappingMutationOperatorTest.testConstruct_0(), org.jgap.GenotypeTest.testConstruct_0(), org.jgap.impl.CompositeGeneTest.testConstruct_0(), org.jgap.impl.fitness.TruthTableFitnessFunctionTest.testConstruct_0(), org.jgap.impl.GaussianMutationOperatorTest.testConstruct_0(), org.jgap.impl.AveragingCrossoverOperatorTest.testConstruct_0(), org.jgap.ConfigurationTest.testConstruct_0(), org.jgap.GenotypeTest.testConstruct_02(), org.jgap.ChromosomeTest.testConstruct_0_2(), org.jgap.impl.MapGeneTest.testConstruct_1(), org.jgap.impl.SetGeneTest.testConstruct_1(), org.jgap.impl.IntegerGeneTest.testConstruct_1(), org.jgap.PopulationTest.testConstruct_1(), org.jgap.impl.BooleanGeneTest.testConstruct_1(), org.jgap.audit.PermutingConfigurationTest.testConstruct_1(), org.jgap.impl.FixedBinaryGeneTest.testConstruct_1(), org.jgap.impl.InversionOperatorTest.testConstruct_1(), org.jgap.impl.StringGeneTest.testConstruct_1(), org.jgap.impl.DoubleGeneTest.testConstruct_1(), org.jgap.impl.MutationOperatorTest.testConstruct_1(), org.jgap.impl.CrossoverOperatorTest.testConstruct_1(), org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_1(), org.jgap.impl.SwappingMutationOperatorTest.testConstruct_1(), org.jgap.impl.DefaultConfigurationTest.testConstruct_1(), org.jgap.impl.CompositeGeneTest.testConstruct_1(), org.jgap.ChromosomeTest.testConstruct_1(), org.jgap.impl.GaussianMutationOperatorTest.testConstruct_1(), org.jgap.audit.EvaluatorTest.testConstruct_1(), org.jgap.impl.AveragingCrossoverOperatorTest.testConstruct_1(), org.jgap.ChromosomeTest.testConstruct_10(), org.jgap.ChromosomeTest.testConstruct_11(), org.jgap.ChromosomeTest.testConstruct_12(), org.jgap.ChromosomeTest.testConstruct_14(), org.jgap.ChromosomeTest.testConstruct_1_2(), org.jgap.ChromosomeTest.testConstruct_1_3(), org.jgap.impl.MapGeneTest.testConstruct_2(), org.jgap.impl.ThresholdSelectorTest.testConstruct_2(), org.jgap.impl.BooleanGeneTest.testConstruct_2(), org.jgap.impl.DoubleGeneTest.testConstruct_2(), org.jgap.impl.FixedBinaryGeneTest.testConstruct_2(), org.jgap.impl.MutationOperatorTest.testConstruct_2(), org.jgap.impl.StringGeneTest.testConstruct_2(), org.jgap.impl.SwappingMutationOperatorTest.testConstruct_2(), org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_2(), org.jgap.impl.DefaultConfigurationTest.testConstruct_2(), org.jgap.ChromosomeTest.testConstruct_2(), org.jgap.impl.GaussianMutationOperatorTest.testConstruct_2(), org.jgap.impl.AveragingCrossoverOperatorTest.testConstruct_2(), org.jgap.ConfigurationTest.testConstruct_2(), org.jgap.ChromosomeTest.testConstruct_2_2(), org.jgap.impl.BestChromosomesSelectorTest.testConstruct_3(), org.jgap.PopulationTest.testConstruct_3(), org.jgap.impl.MapGeneTest.testConstruct_3(), org.jgap.impl.BooleanGeneTest.testConstruct_3(), org.jgap.impl.ThresholdSelectorTest.testConstruct_3(), org.jgap.impl.DoubleGeneTest.testConstruct_3(), org.jgap.impl.MutationOperatorTest.testConstruct_3(), org.jgap.distr.ProblemTest.testConstruct_3(), org.jgap.impl.FixedBinaryGeneTest.testConstruct_3(), org.jgap.impl.StringGeneTest.testConstruct_3(), org.jgap.impl.SwappingMutationOperatorTest.testConstruct_3(), org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_3(), org.jgap.impl.DefaultConfigurationTest.testConstruct_3(), org.jgap.GenotypeTest.testConstruct_3(), org.jgap.ChromosomeTest.testConstruct_3(), org.jgap.impl.GaussianMutationOperatorTest.testConstruct_3(), org.jgap.impl.CrossoverOperatorTest.testConstruct_4(), org.jgap.impl.BooleanGeneTest.testConstruct_4(), org.jgap.impl.StringGeneTest.testConstruct_4(), org.jgap.impl.SwappingMutationOperatorTest.testConstruct_4(), org.jgap.impl.FixedBinaryGeneTest.testConstruct_4(), org.jgap.GenotypeTest.testConstruct_4(), org.jgap.impl.CrossoverOperatorTest.testConstruct_5(), org.jgap.impl.FixedBinaryGeneTest.testConstruct_5(), org.jgap.impl.StringGeneTest.testConstruct_5(), org.jgap.GenotypeTest.testConstruct_5(), org.jgap.ChromosomeTest.testConstruct_5_2(), org.jgap.ChromosomeTest.testConstruct_5_3(), org.jgap.impl.CrossoverOperatorTest.testConstruct_6(), org.jgap.impl.FixedBinaryGeneTest.testConstruct_6(), org.jgap.GenotypeTest.testConstruct_6(), org.jgap.ChromosomeTest.testConstruct_6(), org.jgap.impl.CrossoverOperatorTest.testConstruct_7(), org.jgap.GenotypeTest.testConstruct_7(), org.jgap.ChromosomeTest.testConstruct_7_1(), org.jgap.ChromosomeTest.testConstruct_7_2(), org.jgap.ChromosomeTest.testConstruct_7_3(), org.jgap.impl.CrossoverOperatorTest.testConstruct_8(), org.jgap.GenotypeTest.testConstruct_8(), org.jgap.ChromosomeTest.testConstruct_8(), org.jgap.impl.CrossoverOperatorTest.testConstruct_9(), org.jgap.GenotypeTest.testConstruct_9(), org.jgap.ChromosomeTest.testConstruct_9(), org.jgap.gp.impl.GPConfigurationTest.testConstructor_0(), org.jgap.gp.impl.GPConfigurationTest.testConstructor_1(), org.jgap.PopulationTest.testContains_0(), org.jgap.PopulationTest.testDetermineFittestChromosome_0(), org.jgap.PopulationTest.testDetermineFittestChromosome_1(), org.jgap.PopulationTest.testDetermineFittestChromosome_2(), org.jgap.PopulationTest.testDetermineFittestChromosome_2_0(), org.jgap.PopulationTest.testDetermineFittestChromosome_3(), org.jgap.PopulationTest.testDetermineFittestChromosome_4(), org.jgap.PopulationTest.testDetermineFittestChromosome_5(), org.jgap.PopulationTest.testDetermineFittestChromosomes_1(), org.jgap.PopulationTest.testDetermineFittestChromosomes_2(), org.jgap.PopulationTest.testDetermineFittestChromosomes_3(), org.jgap.impl.AveragingCrossoverOperatorTest.testDoSerialize_0(), org.jgap.impl.WeightedRouletteSelectorTest.testDoSerialize_0(), org.jgap.impl.GreedyCrossoverTest.testDoSerialize_0(), org.jgap.impl.BestChromosomesSelectorTest.testDoSerialize_0(), org.jgap.impl.CrossoverOperatorTest.testDoSerialize_0(), org.jgap.PopulationTest.testDoSerialize_0(), org.jgap.GenotypeTest.testdoSerialize_0(), org.jgap.impl.CrossoverOperatorTest.testDoSerialize_1(), org.jgap.impl.BestChromosomesSelectorTest.testDoubletteChromosomesAllowed_0(), org.jgap.impl.DoubleGeneTest.testDoubleValue_0(), org.jgap.impl.DoubleGeneTest.testDoubleValue_1(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testDummyFitnessFunction_0(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testDummyFitnessFunction_1(), org.jgap.impl.TournamentSelectorTest.testEmpty_0(), org.jgap.impl.WeightedRouletteSelectorTest.testEmpty_0(), org.jgap.impl.ThresholdSelectorTest.testEmpty_0(), org.jgap.impl.BestChromosomesSelectorTest.testEmpty_0(), org.jgap.impl.TournamentSelectorTest.testEmpty_1(), org.jgap.impl.WeightedRouletteSelectorTest.testEmpty_1(), org.jgap.impl.ThresholdSelectorTest.testEmpty_1(), org.jgap.impl.BestChromosomesSelectorTest.testEmpty_1(), org.jgap.impl.TournamentSelectorTest.testEmpty_2(), org.jgap.impl.WeightedRouletteSelectorTest.testEmpty_2(), org.jgap.impl.ThresholdSelectorTest.testEmpty_2(), org.jgap.impl.BestChromosomesSelectorTest.testEmpty_2(), org.jgap.impl.IntegerGeneTest.testEquals_0(), org.jgap.impl.SetGeneTest.testEquals_0(), org.jgap.BaseGeneTest.testEquals_0(), org.jgap.impl.ChainOfSelectorsTest.testEquals_0(), org.jgap.impl.BooleanGeneTest.testEquals_0(), org.jgap.impl.MapGeneTest.testEquals_0(), org.jgap.impl.DoubleGeneTest.testEquals_0(), org.jgap.impl.NumberGeneTest.testEquals_0(), org.jgap.impl.StringGeneTest.testEquals_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testEquals_0(), org.jgap.impl.FixedBinaryGeneTest.testEquals_0(), org.jgap.impl.InversionOperatorTest.testEquals_0(), org.jgap.impl.CompositeGeneTest.testEquals_0(), org.jgap.impl.AveragingCrossoverOperatorTest.testEquals_0(), org.jgap.impl.GreedyCrossoverTest.testEquals_0(), org.jgap.impl.CrossoverOperatorTest.testEquals_0(), org.jgap.ChromosomeTest.testEquals_0(), org.jgap.GenotypeTest.testEquals_0(), org.jgap.impl.IntegerGeneTest.testEquals_1(), org.jgap.impl.SetGeneTest.testEquals_1(), org.jgap.BaseGeneTest.testEquals_1(), org.jgap.impl.ChainOfSelectorsTest.testEquals_1(), org.jgap.impl.BooleanGeneTest.testEquals_1(), org.jgap.impl.MapGeneTest.testEquals_1(), org.jgap.impl.DoubleGeneTest.testEquals_1(), org.jgap.impl.NumberGeneTest.testEquals_1(), org.jgap.impl.StringGeneTest.testEquals_1(), org.jgap.impl.FixedBinaryGeneTest.testEquals_1(), org.jgap.impl.CompositeGeneTest.testEquals_1(), org.jgap.ChromosomeTest.testEquals_1(), org.jgap.GenotypeTest.testEquals_1(), org.jgap.impl.IntegerGeneTest.testEquals_10(), org.jgap.impl.IntegerGeneTest.testEquals_2(), org.jgap.impl.SetGeneTest.testEquals_2(), org.jgap.BaseGeneTest.testEquals_2(), org.jgap.impl.BooleanGeneTest.testEquals_2(), org.jgap.impl.MapGeneTest.testEquals_2(), org.jgap.impl.DoubleGeneTest.testEquals_2(), org.jgap.impl.NumberGeneTest.testEquals_2(), org.jgap.impl.StringGeneTest.testEquals_2(), org.jgap.impl.FixedBinaryGeneTest.testEquals_2(), org.jgap.impl.CompositeGeneTest.testEquals_2(), org.jgap.ChromosomeTest.testEquals_2(), org.jgap.GenotypeTest.testEquals_2(), org.jgap.impl.IntegerGeneTest.testEquals_3(), org.jgap.impl.SetGeneTest.testEquals_3(), org.jgap.BaseGeneTest.testEquals_3(), org.jgap.impl.BooleanGeneTest.testEquals_3(), org.jgap.impl.MapGeneTest.testEquals_3(), org.jgap.impl.DoubleGeneTest.testEquals_3(), org.jgap.impl.NumberGeneTest.testEquals_3(), org.jgap.impl.StringGeneTest.testEquals_3(), org.jgap.impl.FixedBinaryGeneTest.testEquals_3(), org.jgap.impl.CompositeGeneTest.testEquals_3(), org.jgap.ChromosomeTest.testEquals_3(), org.jgap.impl.IntegerGeneTest.testEquals_4(), org.jgap.impl.SetGeneTest.testEquals_4(), org.jgap.impl.BooleanGeneTest.testEquals_4(), org.jgap.impl.MapGeneTest.testEquals_4(), org.jgap.impl.DoubleGeneTest.testEquals_4(), org.jgap.impl.NumberGeneTest.testEquals_4(), org.jgap.impl.StringGeneTest.testEquals_4(), org.jgap.impl.FixedBinaryGeneTest.testEquals_4(), org.jgap.impl.MapGeneTest.testEquals_4_2(), org.jgap.impl.CompositeGeneTest.testEquals_4_2(), org.jgap.impl.IntegerGeneTest.testEquals_5(), org.jgap.impl.SetGeneTest.testEquals_5(), org.jgap.impl.BooleanGeneTest.testEquals_5(), org.jgap.impl.MapGeneTest.testEquals_5(), org.jgap.impl.DoubleGeneTest.testEquals_5(), org.jgap.impl.NumberGeneTest.testEquals_5(), org.jgap.impl.StringGeneTest.testEquals_5(), org.jgap.impl.FixedBinaryGeneTest.testEquals_5(), org.jgap.impl.CompositeGeneTest.testEquals_5(), org.jgap.impl.CompositeGeneTest.testEquals_5_2(), org.jgap.impl.IntegerGeneTest.testEquals_6(), org.jgap.impl.DoubleGeneTest.testEquals_6(), org.jgap.impl.StringGeneTest.testEquals_6(), org.jgap.impl.FixedBinaryGeneTest.testEquals_6(), org.jgap.impl.CompositeGeneTest.testEquals_6(), org.jgap.impl.IntegerGeneTest.testEquals_7(), org.jgap.impl.DoubleGeneTest.testEquals_7(), org.jgap.impl.StringGeneTest.testEquals_7(), org.jgap.impl.FixedBinaryGeneTest.testEquals_7(), org.jgap.impl.CompositeGeneTest.testEquals_7(), org.jgap.impl.IntegerGeneTest.testEquals_8(), org.jgap.impl.DoubleGeneTest.testEquals_8(), org.jgap.impl.StringGeneTest.testEquals_8(), org.jgap.impl.FixedBinaryGeneTest.testEquals_8(), org.jgap.impl.CompositeGeneTest.testEquals_8(), org.jgap.impl.IntegerGeneTest.testEquals_9(), org.jgap.impl.StringGeneTest.testEquals_9(), org.jgap.impl.IntegerGeneTest.testEquals_9_2(), org.jgap.impl.IntegerGeneTest.testEquals_9_3(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_0(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_1(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_2(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testEvaluate_3(), org.jgap.GenotypeTest.testEvolve_10(), org.jgap.GenotypeTest.testEvolve_5_1(), org.jgap.GenotypeTest.testEvolve_5_2(), org.jgap.GenotypeTest.testEvolve_5_3(), org.jgap.impl.FixedBinaryGeneTest.testFlip_0(), org.jgap.impl.FixedBinaryGeneTest.testFlip_1(), org.jgap.ConfigurationTest.testGenerationNr_0(), org.jgap.xml.XMLManagerTest.testGenotype_0(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testGetAbsoluteFitness_0(), org.jgap.impl.IntegerGeneTest.testGetAllele_0(), org.jgap.impl.NumberGeneTest.testGetAllele_0(), org.jgap.impl.SetGeneTest.testGetAllele_0(), org.jgap.BaseGeneTest.testGetAllele_0(), org.jgap.impl.BooleanGeneTest.testGetAllele_0(), org.jgap.impl.DoubleGeneTest.testGetAllele_0(), org.jgap.impl.MapGeneTest.testGetAllele_0(), org.jgap.impl.FixedBinaryGeneTest.testGetAllele_0(), org.jgap.impl.StringGeneTest.testGetAllele_0(), org.jgap.impl.CompositeGeneTest.testGetAllele_0(), org.jgap.impl.IntegerGeneTest.testGetAllele_1(), org.jgap.impl.NumberGeneTest.testGetAllele_1(), org.jgap.impl.BooleanGeneTest.testGetAllele_1(), org.jgap.impl.DoubleGeneTest.testGetAllele_1(), org.jgap.impl.FixedBinaryGeneTest.testGetAllele_1(), org.jgap.impl.CompositeGeneTest.testGetAllele_1(), org.jgap.impl.IntegerGeneTest.testGetAllele_2(), org.jgap.impl.NumberGeneTest.testGetAllele_2(), org.jgap.impl.BooleanGeneTest.testGetAllele_2(), org.jgap.impl.DoubleGeneTest.testGetAllele_2(), org.jgap.impl.FixedBinaryGeneTest.testGetAllele_2(), org.jgap.impl.CompositeGeneTest.testGetAllele_2(), org.jgap.impl.CompositeGeneTest.testGetAllele_3(), org.jgap.impl.IntegerGeneTest.testGetBounds_0(), org.jgap.PopulationTest.testGetChromosome_0(), org.jgap.PopulationTest.testGetChromosomes_0(), org.jgap.GenotypeTest.testGetChromosomes_0(), org.jgap.ConfigurationTest.testGetChromosomeSize_0(), org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_6(), org.jgap.impl.JGAPFactoryTest.testGetCloneHandlerFor_7(), org.jgap.impl.job.EvolveDataTest.testGetConfiguration_0(), org.jgap.BaseRateCalculatorTest.testGetConfiguration_0(), org.jgap.impl.fitness.TruthTableFitnessFunctionTest.testgetConfiguration_0(), org.jgap.ChromosomeTest.testGetFitnessValue_0(), org.jgap.ChromosomeTest.testGetFitnessValue_1(), org.jgap.GenotypeTest.testGetFittestChromosome_0(), org.jgap.GenotypeTest.testGetFittestChromosome_1(), org.jgap.GenotypeTest.testGetFittestChromosomes_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testGetGenes_0(), org.jgap.impl.CompositeGeneTest.testGetGenes_1(), org.jgap.PopulationTest.testGetGenome_0(), org.jgap.PopulationTest.testGetGenome_1(), org.jgap.PopulationTest.testGetGenome_2(), org.jgap.impl.FixedBinaryGeneTest.testGetIntValues_0(), org.jgap.impl.FixedBinaryGeneTest.testGetIntValues_1(), org.jgap.impl.FixedBinaryGeneTest.testGetIntValues_2(), org.jgap.impl.FixedBinaryGeneTest.testGetIntValues_3(), org.jgap.ConfigurationTest.testGetName_0(), org.jgap.ConfigurationTest.testGetName_1(), org.jgap.ConfigurationTest.testGetName_2(), org.jgap.ConfigurationTest.testGetNaturalSelector_0(), org.jgap.ConfigurationTest.testGetNaturalSelector_1(), org.jgap.ConfigurationTest.testGetNaturalSelector_2(), org.jgap.ConfigurationTest.testGetNaturalSelector_3(), org.jgap.ConfigurationTest.testGetNaturalSelector_4(), org.jgap.audit.EvaluatorTest.testGetNumberOfRuns_0(), org.jgap.impl.SetGeneTest.testGetPersistentRepresentation_0(), org.jgap.impl.BooleanGeneTest.testGetPersistentRepresentation_0(), org.jgap.impl.FixedBinaryGeneTest.testGetPersistentRepresentation_0(), org.jgap.impl.SetGeneTest.testGetPersistentRepresentation_1(), org.jgap.impl.BooleanGeneTest.testGetPersistentRepresentation_1(), org.jgap.impl.FixedBinaryGeneTest.testGetPersistentRepresentation_1(), org.jgap.impl.SetGeneTest.testGetPersistentRepresentation_2(), org.jgap.impl.BooleanGeneTest.testGetPersistentRepresentation_2(), org.jgap.impl.FixedBinaryGeneTest.testGetPersistentRepresentation_2(), org.jgap.eval.PopulationHistoryTest.testGetPopulation_1(), org.jgap.eval.PopulationHistoryTest.testGetPopulations_0(), org.jgap.ConfigurationTest.testGetPopulationSize_0(), org.jgap.ConfigurationTest.testGetter_0(), org.jgap.impl.NumberGeneTest.testHashCode_0(), org.jgap.impl.ChainOfSelectorsTest.testHashCode_0(), org.jgap.BaseGeneTest.testHashCode_0(), org.jgap.impl.SetGeneTest.testHashCode_0(), org.jgap.ChromosomeTest.testHashCode_0(), org.jgap.impl.BooleanGeneTest.testHashCode_0(), org.jgap.impl.DoubleGeneTest.testHashCode_0(), org.jgap.impl.CompositeGeneTest.testHashCode_0(), org.jgap.GenotypeTest.testHashcode_0(), org.jgap.impl.FixedBinaryGeneTest.testHashCode_0(), org.jgap.impl.NumberGeneTest.testHashCode_1(), org.jgap.BaseGeneTest.testHashCode_1(), org.jgap.impl.DoubleGeneTest.testHashCode_1(), org.jgap.GenotypeTest.testHashcode_1(), org.jgap.impl.FixedBinaryGeneTest.testHashCode_1(), org.jgap.impl.NumberGeneTest.testHashCode_2(), org.jgap.impl.FixedBinaryGeneTest.testHashCode_2(), org.jgap.impl.FixedBinaryGeneTest.testHashCode_3(), org.jgap.audit.EvaluatorTest.testHasNext_0(), org.jgap.impl.IntegerGeneTest.testIntegerGeneSupportsFullIntegerRange(), org.jgap.impl.IntegerGeneTest.testIntValue_0(), org.jgap.impl.IntegerGeneTest.testIntValue_1(), org.jgap.BaseGeneTest.testIsCompareApplicationData_0(), org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_6(), org.jgap.ConfigurationTest.testIsLocked_0(), org.jgap.impl.AveragingCrossoverOperatorTest.testIsSerializable_0(), org.jgap.impl.WeightedRouletteSelectorTest.testIsSerializable_0(), org.jgap.impl.GreedyCrossoverTest.testIsSerializable_0(), org.jgap.impl.BestChromosomesSelectorTest.testIsSerializable_0(), org.jgap.impl.CrossoverOperatorTest.testIsSerializable_0(), org.jgap.PopulationTest.testIsSerializable_0(), org.jgap.GenotypeTest.testIsSerializable_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testIsValid_0(), org.jgap.impl.StringGeneTest.testIsValidAlphabet_0(), org.jgap.impl.ChainOfSelectorsTest.testIterator_0(), org.jgap.PopulationTest.testIterator_0(), org.jgap.ConfigurationTest.testKeepPopSizeConstant_0(), org.jgap.ConfigurationTest.testLock_0(), org.jgap.ConfigurationTest.testLock_1(), org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange(), org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange2(), org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange3(), org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange4(), org.jgap.impl.DoubleGeneTest.testMapValueToWithinBoundsSupportsFullDoubleRange5(), org.jgap.impl.IntegerGeneTest.testMapValueToWithinBoundsSupportsFullIntegerRange(), org.jgap.gp.impl.GPConfigurationTest.testMemory_0(), org.jgap.gp.impl.GPConfigurationTest.testMemory_1(), org.jgap.gp.impl.GPConfigurationTest.testMemory_2(), org.jgap.gp.impl.GPConfigurationTest.testMemory_3(), org.jgap.impl.FittestPopulationMergerTest.testMergePopulations_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testNewGene_0(), org.jgap.impl.MapGeneTest.testNewGene_0(), org.jgap.impl.NumberGeneTest.testNewGene_0(), org.jgap.impl.IntegerGeneTest.testNewGene_0(), org.jgap.impl.DoubleGeneTest.testNewGene_0(), org.jgap.impl.CompositeGeneTest.testNewGene_0(), org.jgap.impl.StringGeneTest.testNewGene_0(), org.jgap.impl.FixedBinaryGeneTest.testNewGene_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testNewGene_1(), org.jgap.impl.MapGeneTest.testNewGene_1(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testNewGene_2(), org.jgap.impl.MapGeneTest.testNewGene_2(), org.jgap.impl.MapGeneTest.testNewGene_3(), org.jgap.audit.EvaluatorTest.testNext_0(), org.jgap.audit.PermutingConfigurationTest.testNotSupported_1(), org.jgap.impl.GaussianMutationOperatorTest.testOperate_0(), org.jgap.impl.GreedyCrossoverTest.testOperate_0(), org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_0(), org.jgap.impl.InversionOperatorTest.testOperate_0(), org.jgap.impl.MutationOperatorTest.testOperate_0(), org.jgap.impl.TwoWayMutationOperatorTest.testOperate_0(), org.jgap.impl.SwappingMutationOperatorTest.testOperate_0(), org.jgap.impl.CrossoverOperatorTest.testOperate_0(), org.jgap.impl.MutationOperatorTest.testOperate_0_2(), org.jgap.impl.TwoWayMutationOperatorTest.testOperate_0_2(), org.jgap.impl.CrossoverOperatorTest.testOperate_0_2(), org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_1(), org.jgap.impl.GaussianMutationOperatorTest.testOperate_1(), org.jgap.impl.GreedyCrossoverTest.testOperate_1(), org.jgap.impl.InversionOperatorTest.testOperate_1(), org.jgap.impl.MutationOperatorTest.testOperate_1(), org.jgap.impl.SwappingMutationOperatorTest.testOperate_1(), org.jgap.impl.TwoWayMutationOperatorTest.testOperate_1(), org.jgap.impl.CrossoverOperatorTest.testOperate_1(), org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_2(), org.jgap.impl.GaussianMutationOperatorTest.testOperate_2(), org.jgap.impl.GreedyCrossoverTest.testOperate_2(), org.jgap.impl.InversionOperatorTest.testOperate_2(), org.jgap.impl.CrossoverOperatorTest.testOperate_2(), org.jgap.impl.GreedyCrossoverTest.testOperate_3(), org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_3(), org.jgap.impl.InversionOperatorTest.testOperate_3(), org.jgap.impl.CrossoverOperatorTest.testOperate_3(), org.jgap.impl.GaussianMutationOperatorTest.testOperate_4(), org.jgap.impl.GreedyCrossoverTest.testOperate_4(), org.jgap.impl.AveragingCrossoverOperatorTest.testOperate_4(), org.jgap.impl.GreedyCrossoverTest.testOperate_5(), org.jgap.impl.GreedyCrossoverTest.testOperate_6(), org.jgap.impl.DefaultInitializerTest.testPerform_0(), org.jgap.impl.DefaultInitializerTest.testPerform_1(), org.jgap.impl.DefaultCompareToHandlerTest.testPerform_1(), org.jgap.impl.DefaultCloneHandlerTest.testPerform_1(), org.jgap.impl.DefaultCompareToHandlerTest.testPerform_2(), org.jgap.impl.DefaultCloneHandlerTest.testPerform_2(), org.jgap.impl.DefaultCloneHandlerTest.testPerform_3(), org.jgap.impl.DefaultCloneHandlerTest.testPerform_4(), org.jgap.impl.DefaultCloneHandlerTest.testPerform_5(), org.jgap.impl.DefaultCloneHandlerTest.testPerform_6(), org.jgap.audit.PermutingConfigurationTest.testPermute_0(), org.jgap.audit.PermutingConfigurationTest.testPermute_1(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testPers_0(), org.jgap.impl.CompositeGeneTest.testPersistentPresentation_0(), org.jgap.impl.CompositeGeneTest.testPersistentPresentation_0_2(), org.jgap.impl.CompositeGeneTest.testPersistentPresentation_1(), org.jgap.impl.CompositeGeneTest.testPersistentPresentation_2(), org.jgap.impl.CompositeGeneTest.testPersistentPresentation_3(), org.jgap.impl.CompositeGeneTest.testPersistentPresentation_4(), org.jgap.impl.CompositeGeneTest.testPersistentPresentation_5(), org.jgap.impl.CompositeGeneTest.testPersistentPresentation_6(), org.jgap.impl.CompositeGeneTest.testPersistentPresentation_7(), org.jgap.impl.MapGeneTest.testPersistentRepresentation_0(), org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_0(), org.jgap.impl.DoubleGeneTest.testPersistentRepresentation_0(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_0(), org.jgap.PopulationTest.testPersistentRepresentation_0(), org.jgap.ChromosomeTest.testPersistentRepresentation_0(), org.jgap.impl.MapGeneTest.testPersistentRepresentation_1(), org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_1(), org.jgap.impl.DoubleGeneTest.testPersistentRepresentation_1(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_1(), org.jgap.PopulationTest.testPersistentRepresentation_1(), org.jgap.ChromosomeTest.testPersistentRepresentation_1(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_10(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_11(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_12(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_14(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_15(), org.jgap.impl.MapGeneTest.testPersistentRepresentation_2(), org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_2(), org.jgap.impl.DoubleGeneTest.testPersistentRepresentation_2(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_2(), org.jgap.PopulationTest.testPersistentRepresentation_2(), org.jgap.ChromosomeTest.testPersistentRepresentation_2(), org.jgap.impl.MapGeneTest.testPersistentRepresentation_3(), org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_3(), org.jgap.impl.DoubleGeneTest.testPersistentRepresentation_3(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_3(), org.jgap.PopulationTest.testPersistentRepresentation_3(), org.jgap.ChromosomeTest.testPersistentRepresentation_3(), org.jgap.impl.MapGeneTest.testPersistentRepresentation_4(), org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_4(), org.jgap.impl.DoubleGeneTest.testPersistentRepresentation_4(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_4(), org.jgap.PopulationTest.testPersistentRepresentation_4(), org.jgap.ChromosomeTest.testPersistentRepresentation_4(), org.jgap.impl.MapGeneTest.testPersistentRepresentation_5(), org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_5(), org.jgap.impl.DoubleGeneTest.testPersistentRepresentation_5(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_5(), org.jgap.PopulationTest.testPersistentRepresentation_5(), org.jgap.ChromosomeTest.testPersistentRepresentation_5(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_5_2(), org.jgap.impl.MapGeneTest.testPersistentRepresentation_6(), org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_6(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_6(), org.jgap.PopulationTest.testPersistentRepresentation_6(), org.jgap.ChromosomeTest.testPersistentRepresentation_6(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_7(), org.jgap.ChromosomeTest.testPersistentRepresentation_7(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_8(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_9(), org.jgap.ChromosomeTest.testRandomInitialChromosome_1(), org.jgap.ChromosomeTest.testRandomInitialChromosome_2(), org.jgap.ChromosomeTest.testRandomInitialChromosome_3(), org.jgap.ChromosomeTest.testRandomInitialChromosome_4(), org.jgap.GenotypeTest.testRandomInitialGenotype_1(), org.jgap.GenotypeTest.testRandomInitialGenotype_2(), org.jgap.GenotypeTest.testRandomInitialGenotype_3(), org.jgap.impl.ChromosomePoolTest.testReleaseChromosome_1(), org.jgap.impl.MapGeneTest.testRemoveAlleles_0(), org.jgap.impl.MapGeneTest.testRemoveAlleles_1(), org.jgap.eval.PopulationHistoryTest.testRemoveAllPopulations_0(), org.jgap.PopulationTest.testRemoveChromosome_0(), org.jgap.PopulationTest.testRemoveChromosome_1(), org.jgap.PopulationTest.testRemoveChromosome_2(), org.jgap.PopulationTest.testRemoveChromosome_3(), org.jgap.impl.CompositeGeneTest.testRemoveGeneByIdentity_0(), org.jgap.impl.CompositeGeneTest.testRemoveGeneByIdentity_1(), org.jgap.ConfigurationTest.testRemoveNaturalSelector_0(), org.jgap.ConfigurationTest.testRemoveNaturalSelector_1(), org.jgap.ConfigurationTest.testRemoveNaturalSelector_2(), org.jgap.ConfigurationTest.testRemoveNaturalSelector_3(), org.jgap.impl.CompositeGenePersistentReprTest.testRepresentation(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testRepresentation(), org.jgap.data.DataTreeBuilderTest.testRepresentChromosomeAsDocument_0(), org.jgap.data.DataTreeBuilderTest.testRepresentGenotypeAsDocument_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testReset_0(), org.jgap.impl.BestChromosomesSelectorTest.testReturnsUnique_0(), org.jgap.impl.WeightedRouletteSelectorTest.testReturnsUniqueChromosomes_0(), org.jgap.impl.TournamentSelectorTest.testReturnsUniqueChromosomes_0(), org.jgap.impl.WeightedRouletteSelectorTest.testSelect_0(), org.jgap.impl.ThresholdSelectorTest.testSelect_0(), org.jgap.impl.BestChromosomesSelectorTest.testSelect_0(), org.jgap.impl.TournamentSelectorTest.testSelect_0(), org.jgap.impl.WeightedRouletteSelectorTest.testSelect_1(), org.jgap.impl.ThresholdSelectorTest.testSelect_1(), org.jgap.impl.BestChromosomesSelectorTest.testSelect_1(), org.jgap.impl.TournamentSelectorTest.testSelect_1(), org.jgap.impl.WeightedRouletteSelectorTest.testSelect_2(), org.jgap.impl.ThresholdSelectorTest.testSelect_2(), org.jgap.impl.BestChromosomesSelectorTest.testSelect_2(), org.jgap.impl.TournamentSelectorTest.testSelect_2(), org.jgap.impl.WeightedRouletteSelectorTest.testSelect_3(), org.jgap.impl.ThresholdSelectorTest.testSelect_3(), org.jgap.impl.BestChromosomesSelectorTest.testSelect_3(), org.jgap.impl.TournamentSelectorTest.testSelect_3(), org.jgap.impl.WeightedRouletteSelectorTest.testSelect_4(), org.jgap.impl.ThresholdSelectorTest.testSelect_4(), org.jgap.impl.BestChromosomesSelectorTest.testSelect_4(), org.jgap.impl.TournamentSelectorTest.testSelect_4(), org.jgap.impl.ThresholdSelectorTest.testSelect_5(), org.jgap.impl.TournamentSelectorTest.testSelect_5(), org.jgap.impl.TournamentSelectorTest.testSelect_6(), org.jgap.gp.impl.GPConfigurationTest.testSerialize_0(), org.jgap.impl.SetGeneTest.testSetAllele_0(), org.jgap.impl.MapGeneTest.testSetAllele_0(), org.jgap.impl.BooleanGeneTest.testSetAllele_0(), org.jgap.impl.NumberGeneTest.testSetAllele_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testSetAllele_0(), org.jgap.impl.IntegerGeneTest.testSetAllele_0(), org.jgap.impl.DoubleGeneTest.testSetAllele_0(), org.jgap.impl.FixedBinaryGeneTest.testSetAllele_0(), org.jgap.impl.CompositeGeneTest.testSetAllele_0(), org.jgap.impl.StringGeneTest.testSetAllele_0(), org.jgap.impl.SetGeneTest.testSetAllele_1(), org.jgap.impl.MapGeneTest.testSetAllele_1(), org.jgap.impl.BooleanGeneTest.testSetAllele_1(), org.jgap.impl.NumberGeneTest.testSetAllele_1(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testSetAllele_1(), org.jgap.impl.IntegerGeneTest.testSetAllele_1(), org.jgap.impl.DoubleGeneTest.testSetAllele_1(), org.jgap.impl.FixedBinaryGeneTest.testSetAllele_1(), org.jgap.impl.CompositeGeneTest.testSetAllele_1(), org.jgap.impl.StringGeneTest.testSetAllele_1(), org.jgap.impl.SetGeneTest.testSetAllele_2(), org.jgap.impl.MapGeneTest.testSetAllele_2(), org.jgap.impl.BooleanGeneTest.testSetAllele_2(), org.jgap.impl.NumberGeneTest.testSetAllele_2(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testSetAllele_2(), org.jgap.impl.IntegerGeneTest.testSetAllele_2(), org.jgap.impl.DoubleGeneTest.testSetAllele_2(), org.jgap.impl.FixedBinaryGeneTest.testSetAllele_2(), org.jgap.impl.CompositeGeneTest.testSetAllele_2(), org.jgap.impl.StringGeneTest.testSetAllele_2(), org.jgap.impl.BooleanGeneTest.testSetAllele_3(), org.jgap.impl.NumberGeneTest.testSetAllele_3(), org.jgap.impl.IntegerGeneTest.testSetAllele_3(), org.jgap.impl.DoubleGeneTest.testSetAllele_3(), org.jgap.impl.FixedBinaryGeneTest.testSetAllele_3(), org.jgap.impl.CompositeGeneTest.testSetAllele_3(), org.jgap.impl.StringGeneTest.testSetAllele_3(), org.jgap.impl.DoubleGeneTest.testSetAllele_4(), org.jgap.impl.FixedBinaryGeneTest.testSetAllele_4(), org.jgap.impl.CompositeGeneTest.testSetAllele_4(), org.jgap.impl.StringGeneTest.testSetAllele_4(), org.jgap.impl.DoubleGeneTest.testSetAllele_5(), org.jgap.impl.FixedBinaryGeneTest.testSetAllele_5(), org.jgap.impl.CompositeGeneTest.testSetAllele_5(), org.jgap.impl.StringGeneTest.testSetAllele_5(), org.jgap.impl.DoubleGeneTest.testSetAllele_6(), org.jgap.impl.FixedBinaryGeneTest.testSetAllele_6(), org.jgap.impl.StringGeneTest.testSetAllele_6(), org.jgap.impl.FixedBinaryGeneTest.testSetAllele_7(), org.jgap.impl.StringGeneTest.testSetAlphabet_1(), org.jgap.ConfigurationTest.testSetAlwaysCalculateFitness_0(), org.jgap.BaseGeneTest.testSetApplicationData_0(), org.jgap.BaseGeneTest.testSetApplicationData_1(), org.jgap.BaseGeneTest.testSetApplicationData_2(), org.jgap.impl.FixedBinaryGeneTest.testSetBit_0(), org.jgap.impl.FixedBinaryGeneTest.testSetBit_0_2(), org.jgap.impl.FixedBinaryGeneTest.testSetBit_1(), org.jgap.impl.FixedBinaryGeneTest.testSetBit_2(), org.jgap.impl.FixedBinaryGeneTest.testSetBit_3(), org.jgap.impl.FixedBinaryGeneTest.testSetBit_4(), org.jgap.impl.FixedBinaryGeneTest.testSetBit_5(), org.jgap.impl.FixedBinaryGeneTest.testSetBit_6(), org.jgap.ConfigurationTest.testSetBulkFitnessFunction_0(), org.jgap.ConfigurationTest.testSetBulkFitnessFunction_1(), org.jgap.ConfigurationTest.testSetBulkFitnessFunction_2(), org.jgap.ConfigurationTest.testSetBulkFitnessFunction_3(), org.jgap.ConfigurationTest.testSetBulkFitnessFunction_4(), org.jgap.ConfigurationTest.testSetBulkFitnessFunction_5(), org.jgap.PopulationTest.testSetChromosome_0(), org.jgap.PopulationTest.testSetChromosome_1(), org.jgap.PopulationTest.testSetChromosomes_0(), org.jgap.ChromosomeTest.testSetCompareApplicationData_0(), org.jgap.impl.NumberGeneTest.testSetConstraintChecker_0(), org.jgap.impl.FixedBinaryGeneTest.testSetConstraintChecker_0(), org.jgap.impl.DoubleGeneTest.testSetConstraintChecker_0(), org.jgap.impl.CompositeGeneTest.testSetConstraintChecker_0(), org.jgap.impl.StringGeneTest.testSetConstraintChecker_0(), org.jgap.ChromosomeTest.testSetConstraintChecker_1(), org.jgap.ChromosomeTest.testSetConstraintChecker_2(), org.jgap.ChromosomeTest.testSetConstraintChecker_3(), org.jgap.ChromosomeTest.testSetConstraintChecker_4(), org.jgap.gp.impl.GPConfigurationTest.testSetCrossoverMethod_0(), org.jgap.gp.impl.GPConfigurationTest.testSetCrossoverMethod_1(), org.jgap.BaseGeneTest.testSetEnergy_0(), org.jgap.impl.NumberGeneTest.testSetEnergy_0(), org.jgap.impl.SetGeneTest.testSetEnergy_0(), org.jgap.impl.BooleanGeneTest.testSetEnergy_0(), org.jgap.impl.DoubleGeneTest.testSetEnergy_0(), org.jgap.impl.IntegerGeneTest.testSetEnergy_0(), org.jgap.impl.CompositeGeneTest.testSetEnergy_0(), org.jgap.impl.StringGeneTest.testSetEnergy_0(), org.jgap.impl.FixedBinaryGeneTest.testSetEnergy_0(), org.jgap.BaseGeneTest.testSetEnergy_1(), org.jgap.impl.NumberGeneTest.testSetEnergy_1(), org.jgap.impl.SetGeneTest.testSetEnergy_1(), org.jgap.impl.BooleanGeneTest.testSetEnergy_1(), org.jgap.impl.DoubleGeneTest.testSetEnergy_1(), org.jgap.impl.IntegerGeneTest.testSetEnergy_1(), org.jgap.impl.CompositeGeneTest.testSetEnergy_1(), org.jgap.impl.StringGeneTest.testSetEnergy_1(), org.jgap.impl.FixedBinaryGeneTest.testSetEnergy_1(), org.jgap.ConfigurationTest.testSetEventManager_0(), org.jgap.ConfigurationTest.testSetEventManager_1(), org.jgap.ConfigurationTest.testSetEventManager_2(), org.jgap.ConfigurationTest.testSetFitnessEvaluator_0(), org.jgap.ConfigurationTest.testSetFitnessFunction_0(), org.jgap.ConfigurationTest.testSetFitnessFunction_1(), org.jgap.ConfigurationTest.testSetFitnessFunction_2(), org.jgap.ConfigurationTest.testSetFitnessFunction_3(), org.jgap.impl.StringGeneTest.testSetMinMaxLength_0(), org.jgap.ConfigurationTest.testSetNaturalSelector_0(), org.jgap.impl.BestChromosomesSelectorTest.testSetOriginalRate_0(), org.jgap.impl.BestChromosomesSelectorTest.testSetOriginalRate_0_1(), org.jgap.impl.BestChromosomesSelectorTest.testSetOriginalRate_1(), org.jgap.eval.PopulationHistoryTest.testSetPopulations_0(), org.jgap.eval.PopulationHistoryTest.testSetPopulations_1(), org.jgap.ConfigurationTest.testSetPopulationSize_1(), org.jgap.ConfigurationTest.testSetPreserveFittestIndividual_0(), org.jgap.impl.TournamentSelectorTest.testSetProbability_0(), org.jgap.ConfigurationTest.testSetRandomGenerator_0(), org.jgap.ConfigurationTest.testSetSampleChromosome_0(), org.jgap.gp.impl.GPConfigurationTest.testSetSelectionMethod_0(), org.jgap.gp.impl.GPConfigurationTest.testSetSelectionMethod_1(), org.jgap.impl.DoubleGeneTest.testSetToRandomValue_0(), org.jgap.impl.MapGeneTest.testSetToRandomValue_0(), org.jgap.impl.IntegerGeneTest.testSetToRandomValue_0(), org.jgap.impl.CompositeGeneTest.testSetToRandomValue_0(), org.jgap.impl.StringGeneTest.testSetToRandomValue_0(), org.jgap.impl.FixedBinaryGeneTest.testSetToRandomValue_0(), org.jgap.impl.DoubleGeneTest.testSetToRandomValue_1(), org.jgap.impl.MapGeneTest.testSetToRandomValue_1(), org.jgap.impl.IntegerGeneTest.testSetToRandomValue_1(), org.jgap.impl.CompositeGeneTest.testSetToRandomValue_1(), org.jgap.impl.StringGeneTest.testSetToRandomValue_1(), org.jgap.impl.FixedBinaryGeneTest.testSetToRandomValue_1(), org.jgap.impl.DoubleGeneTest.testSetToRandomValue_2(), org.jgap.impl.IntegerGeneTest.testSetToRandomValue_2(), org.jgap.impl.CompositeGeneTest.testSetToRandomValue_2(), org.jgap.impl.StringGeneTest.testSetToRandomValue_2(), org.jgap.impl.FixedBinaryGeneTest.testSetToRandomValue_2(), org.jgap.impl.DoubleGeneTest.testSetToRandomValue_3(), org.jgap.impl.IntegerGeneTest.testSetToRandomValue_3(), org.jgap.impl.StringGeneTest.testSetToRandomValue_3(), org.jgap.impl.FixedBinaryGeneTest.testSetToRandomValue_3(), org.jgap.impl.DoubleGeneTest.testSetToRandomValue_4(), org.jgap.impl.IntegerGeneTest.testSetToRandomValue_4(), org.jgap.impl.StringGeneTest.testSetToRandomValue_4(), org.jgap.impl.IntegerGeneTest.testSetToRandomValue_5(), org.jgap.impl.StringGeneTest.testSetToRandomValue_5(), org.jgap.impl.StringGeneTest.testSetToRandomValue_6(), org.jgap.impl.StringGeneTest.testSetToRandomValue_7(), org.jgap.impl.StringGeneTest.testSetToRandomValue_8(), org.jgap.impl.TournamentSelectorTest.testSetTournametSize_0(), org.jgap.audit.EvaluatorTest.testSetValue_0(), org.jgap.audit.EvaluatorTest.testSetValue_1(), org.jgap.audit.EvaluatorTest.testSetValue_2(), org.jgap.audit.EvaluatorTest.testSetValue_3(), org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_0(), org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_0(), org.jgap.impl.FixedBinaryGeneTest.testSetValueFromPersistentRepresentation_0(), org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_1(), org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_1(), org.jgap.impl.FixedBinaryGeneTest.testSetValueFromPersistentRepresentation_1(), org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_2(), org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_2(), org.jgap.impl.FixedBinaryGeneTest.testSetValueFromPersistentRepresentation_2(), org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_3(), org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_3(), org.jgap.impl.FixedBinaryGeneTest.testSetValueFromPersistentRepresentation_3(), org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_4(), org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_4(), org.jgap.impl.FixedBinaryGeneTest.testSetValueFromPersistentRepresentation_4(), org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_5(), org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_5(), org.jgap.impl.FixedBinaryGeneTest.testSetValueFromPersistentRepresentation_5(), org.jgap.impl.SetGeneTest.testSetValueFromPersistentRepresentation_6(), org.jgap.impl.BooleanGeneTest.testSetValueFromPersistentRepresentation_6(), org.jgap.impl.FixedBinaryGeneTest.testSetValueFromPersistentRepresentation_6(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testSize_0(), org.jgap.BaseGeneTest.testSize_0(), org.jgap.eval.PopulationHistoryTest.testSize_0(), org.jgap.PopulationTest.testSize_0(), org.jgap.ChromosomeTest.testSize_0(), org.jgap.ChromosomeTest.testSize_1(), org.jgap.ChromosomeTest.testSize_2(), org.jgap.PopulationTest.testSortByFitness_0(), org.jgap.PopulationTest.testSortByFitness_1(), org.jgap.gp.impl.GPConfigurationTest.testStack_0(), org.jgap.gp.impl.GPConfigurationTest.testStack_1(), org.jgap.gp.impl.GPConfigurationTest.testStack_2(), org.jgap.gp.impl.GPConfigurationTest.testStack_3(), org.jgap.gp.impl.GPConfigurationTest.testStack_4(), org.jgap.impl.GreedyCrossoverTest.testStartoffset_0(), org.jgap.audit.EvaluatorTest.testStoreGenotype_0(), org.jgap.impl.FixedBinaryGeneTest.testSubbString_0(), org.jgap.impl.FixedBinaryGeneTest.testSubString_1(), org.jgap.supergenes.SupergeneInternalParserTest.testSupergeneInternalParser(), org.jgap.impl.DefaultCrossoverRateCalculatorTest.testToBePermutated_0(), org.jgap.PopulationTest.testToChromosomes_0(), org.jgap.BaseGeneTest.testToString_0(), org.jgap.impl.IntegerGeneTest.testToString_0(), org.jgap.impl.NumberGeneTest.testToString_0(), org.jgap.impl.SetGeneTest.testToString_0(), org.jgap.impl.MapGeneTest.testToString_0(), org.jgap.impl.DoubleGeneTest.testToString_0(), org.jgap.impl.BooleanGeneTest.testToString_0(), org.jgap.impl.FixedBinaryGeneTest.testToString_0(), org.jgap.impl.StringGeneTest.testToString_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testToString_0(), org.jgap.impl.CompositeGeneTest.testToString_0(), org.jgap.GenotypeTest.testToString_0(), org.jgap.ConfigurationTest.testToString_0(), org.jgap.ChromosomeTest.testToString_0(), org.jgap.impl.IntegerGeneTest.testToString_1(), org.jgap.BaseGeneTest.testToString_1(), org.jgap.impl.NumberGeneTest.testToString_1(), org.jgap.impl.SetGeneTest.testToString_1(), org.jgap.impl.MapGeneTest.testToString_1(), org.jgap.impl.DoubleGeneTest.testToString_1(), org.jgap.impl.BooleanGeneTest.testToString_1(), org.jgap.impl.FixedBinaryGeneTest.testToString_1(), org.jgap.impl.StringGeneTest.testToString_1(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testToString_1(), org.jgap.impl.CompositeGeneTest.testToString_1(), org.jgap.GenotypeTest.testToString_1(), org.jgap.ConfigurationTest.testToString_1(), org.jgap.ChromosomeTest.testToString_1(), org.jgap.BaseGeneTest.testToString_2(), org.jgap.impl.MapGeneTest.testToString_2(), org.jgap.impl.DoubleGeneTest.testToString_2(), org.jgap.impl.BooleanGeneTest.testToString_2(), org.jgap.impl.FixedBinaryGeneTest.testToString_2(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testToString_2(), org.jgap.impl.StringGeneTest.testToString_2(), org.jgap.ChromosomeTest.testToString_2(), org.jgap.impl.MapGeneTest.testToString_3(), org.jgap.impl.MapGeneTest.testToString_4(), org.jgap.impl.MapGeneTest.testToString_5(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testValidatorPers_0(), org.jgap.ConfigurationTest.testVerifyStateIsValid_0(), org.jgap.ConfigurationTest.testVerifyStateIsValid_1(), org.jgap.ConfigurationTest.testVerifyStateIsValid_2(), org.jgap.ConfigurationTest.testVerifyStateIsValid_3(), org.jgap.ConfigurationTest.testVerifyStateIsValid_4(), org.jgap.ConfigurationTest.testVerifyStateIsValid_5(), org.jgap.ConfigurationTest.testVerifyStateIsValid_6(), org.jgap.ConfigurationTest.testVerifyStateIsValid_7(), org.jgap.ConfigurationTest.testVerifyStateIsValid_8(), and org.jgap.ConfigurationTest.testVerifyStateIsValid_9().
final String org.jgap.JGAPTestCase.CVS_REVISION = `$Revision: 1.21 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file JGAPTestCase.java.
final double org.jgap.JGAPTestCase.DELTA = 0.0000001 [static], [protected]
Definition at line 30 of file JGAPTestCase.java.
Referenced by org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.DoubleGeneTest.testApplyMutation_0(), org.jgap.impl.DoubleGeneTest.testApplyMutation_1(), org.jgap.impl.DoubleGeneTest.testApplyMutation_2(), org.jgap.impl.DoubleGeneTest.testApplyMutation_3(), org.jgap.impl.DoubleGeneTest.testApplyMutation_4(), org.jgap.impl.DoubleGeneTest.testApplyMutation_5(), org.jgap.impl.DoubleGeneTest.testApplyMutation_6(), org.jgap.impl.DoubleGeneTest.testBounds_0(), org.jgap.impl.DoubleGeneTest.testBounds_1(), org.jgap.audit.EvaluatorTest.testCalcAvgFitness_0(), org.jgap.audit.EvaluatorTest.testCalcAvgFitness_1(), org.jgap.impl.fitness.TruthTableFitnessFunctionTest.testCalcFitness_0(), org.jgap.impl.fitness.TruthTableFitnessFunctionTest.testCalcFitness_1(), org.jgap.audit.EvaluatorTest.testCalcPerformance_0(), org.jgap.audit.EvaluatorTest.testCalcPerformance_1(), org.jgap.audit.EvaluatorTest.testCalcPerformance_2(), org.jgap.ChromosomeTest.testClone_1(), org.jgap.ChromosomeTest.testClone_4(), org.jgap.impl.SeededRandomGeneratorTest.testConstruct_0(), org.jgap.impl.StockRandomGeneratorTest.testConstruct_0(), org.jgap.impl.GaussianMutationOperatorTest.testConstruct_0(), org.jgap.impl.GaussianRandomGeneratorTest.testConstruct_1(), org.jgap.impl.GaussianMutationOperatorTest.testConstruct_1(), org.jgap.impl.ThresholdSelectorTest.testConstruct_2(), org.jgap.impl.GaussianMutationOperatorTest.testConstruct_3(), org.jgap.impl.CrossoverOperatorTest.testConstruct_7(), org.jgap.impl.CrossoverOperatorTest.testConstruct_8(), org.jgap.impl.CrossoverOperatorTest.testConstruct_9(), org.jgap.PopulationTest.testDetermineFittestChromosomes_3(), org.jgap.impl.DoubleGeneTest.testDoubleValue_0(), org.jgap.impl.DoubleGeneTest.testDoubleValue_1(), org.jgap.GenotypeTest.testEvolve_2_3(), org.jgap.distr.CultureTest.testGet_2(), org.jgap.distr.CultureTest.testGet_3(), org.jgap.distr.CultureTest.testGet_4(), org.jgap.impl.BulkFitnessOffsetRemoverTest.testGetAbsoluteFitness_0(), org.jgap.impl.CauchyRandomGeneratorTest.testGetCauchyStdDeviation_0(), org.jgap.ChromosomeTest.testGetFitnessValue_0(), org.jgap.ChromosomeTest.testGetFitnessValue_1(), org.jgap.impl.GaussianRandomGeneratorTest.testGetGaussianStdDeviation_0(), org.jgap.FitnessFunctionTest.testLastComputedValue_0(), org.jgap.impl.FittestPopulationMergerTest.testMergePopulations_0(), org.jgap.impl.SeededRandomGeneratorTest.testNextDouble_0(), org.jgap.impl.StockRandomGeneratorTest.testNextDouble_0(), org.jgap.impl.GaussianRandomGeneratorTest.testNextDouble_0(), org.jgap.impl.SeededRandomGeneratorTest.testNextFloat_0(), org.jgap.impl.StockRandomGeneratorTest.testNextFloat_0(), org.jgap.impl.GaussianRandomGeneratorTest.testNextFloat_0(), org.jgap.ChromosomeTest.testRandomInitialChromosome_3(), org.jgap.GenotypeTest.testRandomInitialGenotype_2(), org.jgap.gp.impl.GPGenotypeTest.testRandomInitialize_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testSetAllele_2(), org.jgap.impl.DoubleGeneTest.testSetAllele_4(), org.jgap.impl.CompositeGeneTest.testSetAllele_4(), org.jgap.impl.DoubleGeneTest.testSetAllele_5(), org.jgap.impl.CompositeGeneTest.testSetAllele_5(), org.jgap.impl.DoubleGeneTest.testSetAllele_6(), org.jgap.distr.CultureMemoryCellTest.testSetDouble_0(), org.jgap.gp.CommandGeneTest.testSetEnergy_0(), org.jgap.BaseGeneTest.testSetEnergy_0(), org.jgap.impl.NumberGeneTest.testSetEnergy_0(), org.jgap.impl.SetGeneTest.testSetEnergy_0(), org.jgap.impl.BooleanGeneTest.testSetEnergy_0(), org.jgap.impl.DoubleGeneTest.testSetEnergy_0(), org.jgap.impl.IntegerGeneTest.testSetEnergy_0(), org.jgap.impl.CompositeGeneTest.testSetEnergy_0(), org.jgap.impl.StringGeneTest.testSetEnergy_0(), org.jgap.impl.FixedBinaryGeneTest.testSetEnergy_0(), org.jgap.gp.CommandGeneTest.testSetEnergy_1(), org.jgap.BaseGeneTest.testSetEnergy_1(), org.jgap.impl.NumberGeneTest.testSetEnergy_1(), org.jgap.impl.SetGeneTest.testSetEnergy_1(), org.jgap.impl.BooleanGeneTest.testSetEnergy_1(), org.jgap.impl.DoubleGeneTest.testSetEnergy_1(), org.jgap.impl.IntegerGeneTest.testSetEnergy_1(), org.jgap.impl.CompositeGeneTest.testSetEnergy_1(), org.jgap.impl.StringGeneTest.testSetEnergy_1(), org.jgap.impl.FixedBinaryGeneTest.testSetEnergy_1(), org.jgap.impl.BestChromosomesSelectorTest.testSetOriginalRate_1(), org.jgap.impl.TournamentSelectorTest.testSetProbability_0(), org.jgap.impl.CompositeGeneTest.testSetToRandomValue_1(), org.jgap.impl.CompositeGeneTest.testSetToRandomValue_2(), org.jgap.audit.EvaluatorTest.testSetValue_0(), org.jgap.audit.EvaluatorTest.testSetValue_1(), org.jgap.audit.EvaluatorTest.testSetValue_2(), org.jgap.audit.EvaluatorTest.testSetValue_3(), and org.jgap.audit.EvaluatorTest.testStoreGenotype_0().
final PrivateAccessor org.jgap.JGAPTestCase.privateAccessor = null [static]
Definition at line 32 of file JGAPTestCase.java.
Referenced by org.jgap.xml.XMLManagerTest.setUp(), org.jgap.impl.WeightedRouletteSelectorTest.testAdd_0(), org.jgap.impl.BestChromosomesSelectorTest.testAdd_0(), org.jgap.impl.TournamentSelectorTest.testAdd_0(), org.jgap.event.EventManagerTest.testAddEventListener_0(), org.jgap.event.EventManagerTest.testAddEventListener_1(), org.jgap.ChromosomeTest.testAlwaysCalculate_0(), org.jgap.ChromosomeTest.testAlwaysCalculate_1(), org.jgap.ChromosomeTest.testAlwaysCalculate_2(), org.jgap.impl.MapGeneTest.testConstruct_0(), org.jgap.impl.BestChromosomesSelectorTest.testConstruct_0(), org.jgap.impl.TournamentSelectorTest.testConstruct_0(), org.jgap.impl.ChromosomePoolTest.testConstruct_0(), org.jgap.impl.MapGeneTest.testConstruct_1(), org.jgap.impl.TournamentSelectorTest.testEmpty_0(), org.jgap.impl.WeightedRouletteSelectorTest.testEmpty_0(), org.jgap.impl.BestChromosomesSelectorTest.testEmpty_0(), org.jgap.impl.MapGeneTest.testNewGene_0(), org.jgap.impl.NumberGeneTest.testNewGene_0(), org.jgap.impl.DoubleGeneTest.testNewGene_0(), org.jgap.impl.MapGeneTest.testPersistentRepresentation_2(), org.jgap.impl.MapGeneTest.testPersistentRepresentation_3(), org.jgap.event.EventManagerTest.testRemoveEventListener_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testReset_0(), org.jgap.impl.BestChromosomesSelectorTest.testSelect_3(), org.jgap.impl.TournamentSelectorTest.testSelect_4(), org.jgap.impl.CauchyRandomGeneratorTest.testSerialize_0(), org.jgap.impl.SeededRandomGeneratorTest.testSerialize_0(), org.jgap.impl.StockRandomGeneratorTest.testSerialize_0(), org.jgap.impl.GaussianRandomGeneratorTest.testSerialize_0(), org.jgap.impl.GaussianRandomGeneratorTest.testSerialize_1(), and org.jgap.impl.StringGeneTest.testSetAlphabet_1().
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/JGAPTestCase.java