org.jgap.ChromosomeForTesting Class Reference
Classes
class TestResultHolder
Public Member Functions
ChromosomeForTesting () throws InvalidConfigurationException
ChromosomeForTesting (Configuration a_config) throws InvalidConfigurationException
ChromosomeForTesting (Configuration a_config, final Gene[] a_initialGenes) throws InvalidConfigurationException
int getComputedTimes ()
void resetComputedTimes ()
double getFitnessValue ()
void resetIsCloned ()
IChromosome randomInitialChromosome2 () throws InvalidConfigurationException
synchronized Object clone ()
boolean isHandlerFor (Object a_obj, Class a_class)
Object perform (Object a_obj, Class a_class, Object a_params) throws Exception
Private Attributes
boolean m_isCloned
Additional Inherited Members
Detailed Description
Derived Chromosome class for testing purposes only.
Author
Klaus Meffert
Since
2.5
Definition at line 18 of file ChromosomeForTesting.java.
Constructor & Destructor Documentation
org.jgap.ChromosomeForTesting.ChromosomeForTesting () throws InvalidConfigurationException [inline]
Definition at line 23 of file ChromosomeForTesting.java.
References org.jgap.Genotype.getStaticConfiguration().
Referenced by org.jgap.ChromosomeForTesting.clone(), and org.jgap.ChromosomeForTesting.randomInitialChromosome2().
org.jgap.ChromosomeForTesting.ChromosomeForTesting (Configuration a_config) throws InvalidConfigurationException [inline]
Definition at line 28 of file ChromosomeForTesting.java.
org.jgap.ChromosomeForTesting.ChromosomeForTesting (Configuration a_config, final Gene[] a_initialGenes) throws InvalidConfigurationException [inline]
Definition at line 33 of file ChromosomeForTesting.java.
Member Function Documentation
synchronized Object org.jgap.ChromosomeForTesting.clone () [inline], [virtual]
Returns a copy of this Chromosome. The returned instance can evolve independently of this instance. Note that, if possible, this method will first attempt to acquire a Chromosome instance from the active ChromosomePool (if any) and set its value appropriately before returning it. If that is not possible, then a new Chromosome instance will be constructed and its value set appropriately before returning.
Returns
copy of this Chromosome
Exceptions
IllegalStateException instead of CloneNotSupportedException
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Todo
Todo once output a warning: allele should be cloneable!
Reimplemented from org.jgap.Chromosome.
Definition at line 114 of file ChromosomeForTesting.java.
References org.jgap.ChromosomeForTesting.ChromosomeForTesting(), and org.jgap.BaseChromosome.getConfiguration().
int org.jgap.ChromosomeForTesting.getComputedTimes () [inline]
Definition at line 38 of file ChromosomeForTesting.java.
double org.jgap.ChromosomeForTesting.getFitnessValue () [inline]
Retrieves the fitness value of this Chromosome, as determined by the active fitness function. If a bulk fitness function is in use and has not yet assigned a fitness value to this Chromosome, then -1 is returned.
Attention: should not be called from toString() as the fitness value would be computed if it was initial!
Returns
a positive double value representing the fitness of this Chromosome, or -1 if a bulk fitness function is in use and has not yet assigned a fitness value to this Chromosome
Author
Neil Rotstan
Klaus Meffert
Since
2.6
Implements org.jgap.IChromosome.
Definition at line 46 of file ChromosomeForTesting.java.
References org.jgap.Chromosome.m_fitnessValue, and org.jgap.ChromosomeForTesting.m_isCloned.
boolean org.jgap.ChromosomeForTesting.isHandlerFor (Object a_obj, Class a_class) [inline]
Determines whether the handler is suitable for the given object instance or class.
Parameters
a_obj the object instance to check
a_class the class to check, alternatively if no object instance is available (some handlers could need to get an object and would always return false if only a class is provided)
Returns
true: handler suitable for given object or class
Author
Klaus Meffert
Since
2.6
Implements org.jgap.IHandler.
Definition at line 129 of file ChromosomeForTesting.java.
Object org.jgap.ChromosomeForTesting.perform (Object a_obj, Class a_class, Object a_params) throws Exception [inline]
Performs a task for the given object or class. For some handlers, additional parameters are necessary, which could be provided.
Parameters
a_obj the object instance to perform the handler task for
a_class the class to perform the handler task for, in case no object instance is available (some handlers could need to get an object and would always throw an exception if only a class is provided)
a_params optional parameters needed for the handler to perform its task
Exceptions
Exception in case of any error
Returns
Object
Author
Klaus Meffert
Since
2.6
Implements org.jgap.IHandler.
Definition at line 138 of file ChromosomeForTesting.java.
References org.jgap.ChromosomeForTesting.randomInitialChromosome2().
IChromosome org.jgap.ChromosomeForTesting.randomInitialChromosome2 () throws InvalidConfigurationException [inline]
Definition at line 58 of file ChromosomeForTesting.java.
References org.jgap.ChromosomeForTesting.ChromosomeForTesting(), org.jgap.BaseChromosome.getConfiguration(), and org.jgap.FitnessFunction.NO_FITNESS_VALUE.
Referenced by org.jgap.ChromosomeForTesting.perform(), and org.jgap.GenotypeTest.ChromosomeForTest2.perform().
void org.jgap.ChromosomeForTesting.resetComputedTimes () [inline]
Definition at line 42 of file ChromosomeForTesting.java.
void org.jgap.ChromosomeForTesting.resetIsCloned () [inline]
Definition at line 54 of file ChromosomeForTesting.java.
References org.jgap.ChromosomeForTesting.m_isCloned.
Member Data Documentation
boolean org.jgap.ChromosomeForTesting.m_isCloned [private]
Definition at line 20 of file ChromosomeForTesting.java.
Referenced by org.jgap.ChromosomeForTesting.getFitnessValue(), and org.jgap.ChromosomeForTesting.resetIsCloned().
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/ChromosomeForTesting.java