org.jgap.gp.function.statistics.Skewness Class Reference
Public Member Functions
Skewness (final GPConfiguration a_conf, Class a_returnType, int a_arityInitial, int a_arityMin, int a_arityMax) throws InvalidConfigurationException
double execute_double (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
String toString ()
Object clone ()
String getName ()
Additional Inherited Members
Detailed Description
Computes the skewness of the available values.
We use the following (unbiased) formula to define skewness:
skewness = [n / (n -1) (n - 2)] sum[(x_i - mean)^3] / std^3
where n is the number of values, and std is the Standard Deviation
Author
Luis Garcia
Since
3.5
Definition at line 30 of file Skewness.java.
Constructor & Destructor Documentation
org.jgap.gp.function.statistics.Skewness.Skewness (final GPConfiguration a_conf, Class a_returnType, int a_arityInitial, int a_arityMin, int a_arityMax) throws InvalidConfigurationException [inline]
Definition at line 32 of file Skewness.java.
Referenced by org.jgap.gp.function.statistics.Skewness.clone().
Member Function Documentation
Object org.jgap.gp.function.statistics.Skewness.clone () [inline]
Returns
clone of the current object instance
Implements org.jgap.util.ICloneable.
Definition at line 73 of file Skewness.java.
References org.jgap.gp.CommandGene.getArity(), org.jgap.gp.CommandGene.getArityMax(), org.jgap.gp.CommandGene.getArityMin(), org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.function.statistics.Skewness.Skewness().
double org.jgap.gp.function.statistics.Skewness.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 40 of file Skewness.java.
References org.jgap.gp.CommandGene.size().
float org.jgap.gp.function.statistics.Skewness.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 50 of file Skewness.java.
References org.jgap.gp.CommandGene.size().
String org.jgap.gp.function.statistics.Skewness.getName () [inline]
Definition at line 84 of file Skewness.java.
String org.jgap.gp.function.statistics.Skewness.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 60 of file Skewness.java.
References org.jgap.gp.CommandGene.size().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/statistics/Skewness.java