org.jgap.NaturalSelectorExt Class Reference
Public Member Functions
NaturalSelectorExt () throws InvalidConfigurationException
NaturalSelectorExt (Configuration a_config) throws InvalidConfigurationException
void setDoubletteChromosomesAllowed (final boolean a_doublettesAllowed)
boolean getDoubletteChromosomesAllowed ()
boolean equals (Object a_o)
final synchronized void select (final int a_howManyToSelect, final Population a_from_pop, Population a_to_pop)
Protected Member Functions
void init (Configuration a_config) throws InvalidConfigurationException
abstract void add (final IChromosome a_chromosomeToAdd)
abstract void selectChromosomes (final int a_howManyToSelect, final Population a_from_pop)
final void selectChromosome (IChromosome a_chrom, final boolean a_clone)
Private Attributes
Population m_to_pop
boolean m_doublettesAllowed
Additional Inherited Members
Detailed Description
An extended implementation of NaturalSelector that acts as a base class for the built-in JGAP selectors BestChromosomesSelector and WeightedRouletteSelector.
Author
Klaus Meffert
Since
3.3.3
Definition at line 20 of file NaturalSelectorExt.java.
Constructor & Destructor Documentation
org.jgap.NaturalSelectorExt.NaturalSelectorExt () throws InvalidConfigurationException [inline]
Default constructor, only needed for dynamic instantiation!
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.3.3
Definition at line 37 of file NaturalSelectorExt.java.
References org.jgap.Genotype.getStaticConfiguration(), and org.jgap.NaturalSelectorExt.init().
Referenced by org.jgap.NaturalSelectorExt.equals().
org.jgap.NaturalSelectorExt.NaturalSelectorExt (Configuration a_config) throws InvalidConfigurationException [inline]
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.3.3
Definition at line 52 of file NaturalSelectorExt.java.
References org.jgap.NaturalSelectorExt.init().
Member Function Documentation
abstract void org.jgap.NaturalSelectorExt.add (final IChromosome a_chromosomeToAdd) [protected], [pure virtual]
Implemented in org.jgap.impl.TournamentSelector, org.jgap.impl.ThresholdSelector, org.jgap.impl.WeightedRouletteSelector, and org.jgap.impl.BestChromosomesSelector.
Referenced by org.jgap.NaturalSelectorExt.select().
boolean org.jgap.NaturalSelectorExt.equals (Object a_o) [inline]
Parameters
a_o the object to compare
Returns
true: compared object is seen as equal to current instance
Author
Klaus Meffert
Since
3.3.3
Definition at line 94 of file NaturalSelectorExt.java.
References org.jgap.NaturalSelectorExt.m_doublettesAllowed, and org.jgap.NaturalSelectorExt.NaturalSelectorExt().
boolean org.jgap.NaturalSelectorExt.getDoubletteChromosomesAllowed () [inline]
Returns
true: doublette chromosomes allowed to be added to the selector false: this is sort of risky and might lead to unexpected population sizes during evolution!
Author
Klaus Meffert
Since
3.3.3
Definition at line 83 of file NaturalSelectorExt.java.
References org.jgap.NaturalSelectorExt.m_doublettesAllowed.
Referenced by org.jgap.impl.BestChromosomesSelector.add(), org.jgap.impl.BestChromosomesSelector.clone(), org.jgap.impl.BestChromosomesSelector.equals(), org.jgap.impl.BestChromosomesSelector.selectChromosomes(), org.jgap.impl.BestChromosomesSelectorTest.testConstruct_0(), and org.jgap.impl.BestChromosomesSelectorTest.testDoubletteChromosomesAllowed_0().
void org.jgap.NaturalSelectorExt.init (Configuration a_config) throws InvalidConfigurationException [inline], [protected]
Definition at line 58 of file NaturalSelectorExt.java.
Referenced by org.jgap.NaturalSelectorExt.NaturalSelectorExt().
final synchronized void org.jgap.NaturalSelectorExt.select (final int a_howManyToSelect, final Population a_from_pop, Population a_to_pop) [inline]
Selects a given number of Chromosomes that will move on to the next generation population.
Parameters
a_from_pop the population the Chromosomes will be selected from
a_to_pop the population the Chromosomes will be added to
a_howManyToSelect the number of Chromosomes to select
Author
Klaus Meffert
Since
3.3.3
Definition at line 127 of file NaturalSelectorExt.java.
References org.jgap.NaturalSelectorExt.add(), org.jgap.Population.getChromosome(), and org.jgap.NaturalSelectorExt.selectChromosomes().
final void org.jgap.NaturalSelectorExt.selectChromosome (IChromosome a_chrom, final boolean a_clone) [inline], [protected]
Definition at line 156 of file NaturalSelectorExt.java.
References org.jgap.Population.contains(), org.jgap.NaturalSelector.getConfiguration(), org.jgap.NaturalSelector.m_monitorActive, org.jgap.NaturalSelectorExt.m_to_pop, and org.jgap.IHandler.perform().
abstract void org.jgap.NaturalSelectorExt.selectChromosomes (final int a_howManyToSelect, final Population a_from_pop) [protected], [pure virtual]
Selects a given number of chromosomes that will move on to the next generation population. For selecting a chromosome for the next generation, the method selectChromosome(IChromosome, boolean) has to be used!
Parameters
a_from_pop the population the Chromosomes will be selected from
a_howManyToSelect the number of Chromosomes to select
Author
Klaus Meffert
Since
3.3.3
Referenced by org.jgap.NaturalSelectorExt.select().
void org.jgap.NaturalSelectorExt.setDoubletteChromosomesAllowed (final boolean a_doublettesAllowed) [inline]
Determines whether doublette chromosomes may be added to the selector or will be ignored.
Parameters
a_doublettesAllowed true: doublette chromosomes allowed to be added to the selector. false: doublettes will be ignored and not added
Author
Klaus Meffert
Since
3.3.3
Definition at line 71 of file NaturalSelectorExt.java.
References org.jgap.NaturalSelectorExt.m_doublettesAllowed.
Referenced by org.jgap.impl.BestChromosomesSelector.BestChromosomesSelector().
Member Data Documentation
boolean org.jgap.NaturalSelectorExt.m_doublettesAllowed [private]
Allows or disallows doublette chromosomes to be added to the selector
Definition at line 27 of file NaturalSelectorExt.java.
Referenced by org.jgap.NaturalSelectorExt.equals(), org.jgap.NaturalSelectorExt.getDoubletteChromosomesAllowed(), and org.jgap.NaturalSelectorExt.setDoubletteChromosomesAllowed().
Population org.jgap.NaturalSelectorExt.m_to_pop [private]
Definition at line 22 of file NaturalSelectorExt.java.
Referenced by org.jgap.NaturalSelectorExt.selectChromosome().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/NaturalSelectorExt.java