org.jgap.data.DataElementsDocument Class Reference
Public Member Functions
void setTree (final IDataElementList a_tree)
IDataElementList getTree ()
DataElementsDocument () throws Exception
IDataCreators newDocument () throws Exception
void appendChild (final IDataElement a_newChild) throws Exception
Private Attributes
IDataElementList m_tree
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.6 $`
Additional Inherited Members
Detailed Description
The IDataCreators interface represents an entity comparable to org.w3c.dom.Document
Author
Klaus Meffert
Since
2.0
Definition at line 19 of file DataElementsDocument.java.
Constructor & Destructor Documentation
org.jgap.data.DataElementsDocument.DataElementsDocument () throws Exception [inline]
Definition at line 41 of file DataElementsDocument.java.
References org.jgap.data.DataElementsDocument.m_tree.
Referenced by org.jgap.data.DataElementsDocument.newDocument().
Member Function Documentation
void org.jgap.data.DataElementsDocument.appendChild (final IDataElement a_newChild) throws Exception [inline]
Appends a child element to the tree
Parameters
a_newChild the child to be added to the tree
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 59 of file DataElementsDocument.java.
IDataElementList org.jgap.data.DataElementsDocument.getTree () [inline]
Returns
the tree (of elements) held by this class
Author
Klaus Meffert
Since
2.0
Implements org.jgap.data.IDataCreators.
Definition at line 37 of file DataElementsDocument.java.
References org.jgap.data.DataElementsDocument.m_tree.
Referenced by org.jgap.data.DataElementsDocumentTest.testAppendChild_0(), and org.jgap.data.DataElementsDocumentTest.testConstruct_0().
IDataCreators org.jgap.data.DataElementsDocument.newDocument () throws Exception [inline]
Constructs a new instance of the entity implementing IDataCreators
Exceptions
Exception
Returns
new instance of the entity itself
Author
Klaus Meffert
Since
2.0
Implements org.jgap.data.IDataCreators.
Definition at line 46 of file DataElementsDocument.java.
References org.jgap.data.DataElementsDocument.DataElementsDocument().
Referenced by org.jgap.data.DataElementsDocumentTest.testNewDocument_0().
void org.jgap.data.DataElementsDocument.setTree (final IDataElementList a_tree) [inline]
Definition at line 27 of file DataElementsDocument.java.
References org.jgap.data.DataElementsDocument.m_tree.
Member Data Documentation
final String org.jgap.data.DataElementsDocument.CVS_REVISION = `$Revision: 1.6 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 22 of file DataElementsDocument.java.
IDataElementList org.jgap.data.DataElementsDocument.m_tree [private]
Definition at line 24 of file DataElementsDocument.java.
Referenced by org.jgap.data.DataElementsDocument.DataElementsDocument(), org.jgap.data.DataElementsDocument.getTree(), and org.jgap.data.DataElementsDocument.setTree().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/data/DataElementsDocument.java