examples.gp.anttrail.AntTrailProblem Class Reference
Classes
class AntFitnessFunction
Public Member Functions
AntTrailProblem (GPConfiguration config, String a_filename) throws InvalidConfigurationException, Exception
GPGenotype create () throws InvalidConfigurationException
Static Public Member Functions
static void main (String[] args)
Static Public Attributes
static int m_maxMoves = 400
Protected Member Functions
void displaySolution (int[][] a_antmap)
Protected Attributes
int[][] m_map
Static Protected Attributes
static int totalFood
Private Member Functions
int[][] readTrail (String a_filename) throws Exception
GPFitnessFunction createFitFunc ()
Static Private Member Functions
static int countFood (AntMap a_map)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.20 $`
static int foodAvail
static int m_maxx
static int m_maxy
Detailed Description
The ant trail problem. It demonstrates Genetic Programming (GP) capabilities of JGAP.
The ant trail problem searches for a solution to let an ant pick up as many food as possible on a given parcours with as few steps as possible. The ant can move, take food and see food in adjacent fields.
Whenever a new best solution has been found, the ant trail is printed to the console. Additionally, the tree represented by the GP program is output in graphical representation.
Author
Klaus Meffert
Since
3.01
Definition at line 38 of file AntTrailProblem.java.
Constructor & Destructor Documentation
examples.gp.anttrail.AntTrailProblem.AntTrailProblem (GPConfiguration config, String a_filename) throws InvalidConfigurationException, Exception [inline]
Definition at line 58 of file AntTrailProblem.java.
References examples.gp.anttrail.AntTrailProblem.countFood(), examples.gp.anttrail.AntTrailProblem.create(), examples.gp.anttrail.AntTrailProblem.createFitFunc(), examples.gp.anttrail.AntTrailProblem.m_map, examples.gp.anttrail.AntTrailProblem.m_maxMoves, examples.gp.anttrail.AntTrailProblem.readTrail(), and examples.gp.anttrail.AntTrailProblem.totalFood.
Referenced by examples.gp.anttrail.AntTrailProblem.main().
Member Function Documentation
static int examples.gp.anttrail.AntTrailProblem.countFood (AntMap a_map) [inline], [static], [private]
Definition at line 349 of file AntTrailProblem.java.
References examples.gp.anttrail.AntMap.FOOD, examples.gp.anttrail.AntMap.getFromMap(), examples.gp.anttrail.AntTrailProblem.m_maxx, and examples.gp.anttrail.AntTrailProblem.m_maxy.
Referenced by examples.gp.anttrail.AntTrailProblem.AntTrailProblem().
GPGenotype examples.gp.anttrail.AntTrailProblem.create () throws InvalidConfigurationException [inline], [virtual]
Sets up the functions to use and other parameters. Then creates the initial genotype.
Returns
the genotype created
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.GPProblem.
Definition at line 126 of file AntTrailProblem.java.
References org.jgap.gp.GPProblem.getGPConfiguration(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.CommandGene.VoidClass.
Referenced by examples.gp.anttrail.AntTrailProblem.AntTrailProblem().
GPFitnessFunction examples.gp.anttrail.AntTrailProblem.createFitFunc () [inline], [private]
Definition at line 289 of file AntTrailProblem.java.
Referenced by examples.gp.anttrail.AntTrailProblem.AntTrailProblem().
void examples.gp.anttrail.AntTrailProblem.displaySolution (int a_antmap[][]) [inline], [protected]
Display ant trail as found by GP.
Parameters
a_antmap the map containing the trail
Definition at line 263 of file AntTrailProblem.java.
References examples.gp.anttrail.AntTrailProblem.m_maxx, and examples.gp.anttrail.AntTrailProblem.m_maxy.
static void examples.gp.anttrail.AntTrailProblem.main (String[] args) [inline], [static]
Starts the example.
Parameters
args ignored
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 229 of file AntTrailProblem.java.
References examples.gp.anttrail.AntTrailProblem.AntTrailProblem().
int [][] examples.gp.anttrail.AntTrailProblem.readTrail (String a_filename) throws Exception [inline], [private]
Definition at line 157 of file AntTrailProblem.java.
References examples.gp.anttrail.AntMap.EMPTY, examples.gp.anttrail.AntMap.FOOD, examples.gp.anttrail.AntTrailProblem.foodAvail, examples.gp.anttrail.AntTrailProblem.m_maxx, examples.gp.anttrail.AntTrailProblem.m_maxy, and examples.gp.anttrail.AntMap.TRAIL.
Referenced by examples.gp.anttrail.AntTrailProblem.AntTrailProblem().
Member Data Documentation
final String examples.gp.anttrail.AntTrailProblem.CVS_REVISION = `$Revision: 1.20 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 41 of file AntTrailProblem.java.
int examples.gp.anttrail.AntTrailProblem.foodAvail [static], [private]
Definition at line 45 of file AntTrailProblem.java.
Referenced by examples.gp.anttrail.AntTrailProblem.readTrail().
int [][] examples.gp.anttrail.AntTrailProblem.m_map [protected]
Definition at line 43 of file AntTrailProblem.java.
Referenced by examples.gp.anttrail.AntTrailProblem.AntTrailProblem().
int examples.gp.anttrail.AntTrailProblem.m_maxMoves = 400 [static]
Maximum number of moves allowed.
Definition at line 56 of file AntTrailProblem.java.
Referenced by examples.gp.anttrail.AntTrailProblem.AntTrailProblem().
int examples.gp.anttrail.AntTrailProblem.m_maxx [static], [private]
Definition at line 47 of file AntTrailProblem.java.
Referenced by examples.gp.anttrail.AntTrailProblem.countFood(), examples.gp.anttrail.AntTrailProblem.displaySolution(), and examples.gp.anttrail.AntTrailProblem.readTrail().
int examples.gp.anttrail.AntTrailProblem.m_maxy [static], [private]
Definition at line 49 of file AntTrailProblem.java.
Referenced by examples.gp.anttrail.AntTrailProblem.countFood(), examples.gp.anttrail.AntTrailProblem.displaySolution(), and examples.gp.anttrail.AntTrailProblem.readTrail().
int examples.gp.anttrail.AntTrailProblem.totalFood [static], [protected]
Definition at line 51 of file AntTrailProblem.java.
Referenced by examples.gp.anttrail.AntTrailProblem.AntTrailProblem().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/anttrail/AntTrailProblem.java