examples.supergene.SupergeneSample Class Reference
Public Member Functions
int makeChangeForAmount (int a_targetChangeAmount) throws Exception
Static Public Member Functions
static void main (String[] args)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
To test the Supergene, we created the `make change` version with additional condition: the number of nickels and pennies must be both even or both odd. The supergene encloses two genes (nickels and pennies) and is valid if the condition above is satisfied.
Author
Neil Rotstan
Klaus Meffert
Audrius Meskauskas
Since
2.0
Definition at line 27 of file SupergeneSample.java.
Member Function Documentation
static void examples.supergene.SupergeneSample.main (String[] args) [inline], [static]
Definition at line 80 of file SupergeneSample.java.
References examples.supergene.AbstractSupergeneTest.test().
int examples.supergene.SupergeneSample.makeChangeForAmount (int a_targetChangeAmount) throws Exception [inline], [virtual]
Executes the genetic algorithm to determine the minimum number of coins necessary to make up the given target amount of change. The solution will then be written to System.out.
Parameters
a_targetChangeAmount the target amount of change for which this method is attempting to produce the minimum number of coins
Returns
absolute difference between the required and computed change amount
Exceptions
Exception
Implements examples.supergene.AbstractSupergeneTest.
Definition at line 44 of file SupergeneSample.java.
References examples.supergene.AbstractSupergeneTest.DIMES, examples.supergene.AbstractSupergeneTest.getDimesGene(), examples.supergene.AbstractSupergeneTest.getNickelsGene(), examples.supergene.AbstractSupergeneTest.getPenniesGene(), examples.supergene.AbstractSupergeneTest.getQuartersGene(), examples.supergene.AbstractSupergeneTest.QUARTERS, and examples.supergene.AbstractSupergeneTest.solve().
Member Data Documentation
final String examples.supergene.SupergeneSample.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 30 of file SupergeneSample.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/supergene/SupergeneSample.java