org.jgap.event.EventManager Class Reference
Public Member Functions
synchronized void addEventListener (final String a_eventName, final GeneticEventListener a_eventListenerToAdd)
synchronized void removeEventListener (final String a_eventName, final GeneticEventListener a_eventListenerToRemove)
synchronized void fireGeneticEvent (final GeneticEvent a_eventToFire)
int hashCode ()
Object clone ()
Private Attributes
HashMap m_listeners = new HashMap()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.9 $`
Additional Inherited Members
Detailed Description
Manages event notification in the system. Observers that desire to be notified of genetic events should subscribe to this class via the addEventListener() method. To unsubscribe, use the removeEventListener() method. To generate a genetic event, use the fireGeneticEvent() method, which will take care of notifying the appropriate subscribers.
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 26 of file EventManager.java.
Member Function Documentation
synchronized void org.jgap.event.EventManager.addEventListener (final String a_eventName, final GeneticEventListener a_eventListenerToAdd) [inline]
Adds a new listener that will be notified when the event represented by the given name is fired.
Parameters
a_eventName the name of the event to which the given listener should be subscribed. Standard events are represented by constants in the GeneticEvent class
a_eventListenerToAdd the genetic listener to subscribe to notifications of the given event
Author
Neil Rotstan
Since
1.0
Definition at line 50 of file EventManager.java.
References org.jgap.event.EventManager.m_listeners.
Object org.jgap.event.EventManager.clone () [inline]
Returns
cloned instance
Author
Klaus Meffert
Since
3.2
Implements org.jgap.util.ICloneable.
Definition at line 121 of file EventManager.java.
References org.jgap.event.EventManager.m_listeners.
synchronized void org.jgap.event.EventManager.fireGeneticEvent (final GeneticEvent a_eventToFire) [inline]
Fires a genetic event. All subscribers of that particular event type (as determined by the name of the event) will be notified.
Parameters
a_eventToFire the representation of the genetic event to fire
Author
Neil Rotstan
Since
1.0
Definition at line 90 of file EventManager.java.
References org.jgap.event.GeneticEvent.getEventName(), and org.jgap.event.EventManager.m_listeners.
int org.jgap.event.EventManager.hashCode () [inline]
Returns
hashcode
Author
Klaus Meffert
Since
3.0
Definition at line 110 of file EventManager.java.
synchronized void org.jgap.event.EventManager.removeEventListener (final String a_eventName, final GeneticEventListener a_eventListenerToRemove) [inline]
Removes the given listener from subscription of the indicated event. The listener will no longer be notified when the given event occurs.
Parameters
a_eventName the name of the event to which the given listener should be removed. Standard events are represented by constants in the GeneticEvent class
a_eventListenerToRemove the genetic listener to unsubscribe from notifications of the given event
Author
Neil Rotstan
Since
1.0
Definition at line 73 of file EventManager.java.
References org.jgap.event.EventManager.m_listeners.
Member Data Documentation
final String org.jgap.event.EventManager.CVS_REVISION = `$Revision: 1.9 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 29 of file EventManager.java.
HashMap org.jgap.event.EventManager.m_listeners = new HashMap() [private]
References a Map of subscribed event listeners. Each key is an event name, and each value is a List of listeners subscribed to that event.
Definition at line 35 of file EventManager.java.
Referenced by org.jgap.event.EventManager.addEventListener(), org.jgap.event.EventManager.clone(), org.jgap.event.EventManager.fireGeneticEvent(), and org.jgap.event.EventManager.removeEventListener().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/event/EventManager.java