org.jgap.gp.function.ForLoopTest Class Reference
Public Member Functions
void testConstruct_0 () throws Exception
void testClone_0 () throws Exception
void testClone_1 () throws Exception
void testClone_2 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.1 $`
Additional Inherited Members
Detailed Description
Tests the ForLoop class.
Author
Klaus Meffert
Since
3.4
Definition at line 22 of file ForLoopTest.java.
Member Function Documentation
static Test org.jgap.gp.function.ForLoopTest.suite () [inline], [static]
Definition at line 27 of file ForLoopTest.java.
void org.jgap.gp.function.ForLoopTest.testClone_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.4
Definition at line 55 of file ForLoopTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.function.ForLoopTest.testClone_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.4
Definition at line 74 of file ForLoopTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.getArity(), and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.function.ForLoopTest.testClone_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.4
Definition at line 93 of file ForLoopTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.getArity(), and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.function.ForLoopTest.testConstruct_0 () throws Exception [inline]
Following should be possible without exception.
Exceptions
Exception
Author
Klaus Meffert
Since
3.4
Definition at line 40 of file ForLoopTest.java.
References org.jgap.gp.GPTestCase.m_gpconf.
Member Data Documentation
final String org.jgap.gp.function.ForLoopTest.CVS_REVISION = `$Revision: 1.1 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file ForLoopTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/gp/function/ForLoopTest.java