org.jgap.impl.FixedBinaryGeneTest Class Reference
Classes
class GeneConstraintChecker
Public Member Functions
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testConstruct_2 () throws Exception
void testConstruct_3 () throws Exception
void testConstruct_4 () throws Exception
void testConstruct_5 () throws Exception
void testConstruct_6 () throws Exception
void testToString_0 () throws Exception
void testToString_1 () throws Exception
void testToString_2 () throws Exception
void testGetAllele_0 () throws Exception
void testGetAllele_1 () throws Exception
void testGetAllele_2 () throws Exception
void testEquals_0 () throws Exception
void testEquals_1 () throws Exception
void testEquals_2 () throws Exception
void testEquals_3 () throws Exception
void testEquals_4 () throws Exception
void testEquals_5 () throws Exception
void testEquals_6 () throws Exception
void testEquals_7 () throws Exception
void testEquals_8 () throws Exception
void testGetIntValues_0 () throws Exception
void testGetIntValues_1 () throws Exception
void testGetIntValues_2 () throws Exception
void testGetIntValues_3 () throws Exception
void testSetAllele_0 () throws Exception
void testSetAllele_1 () throws Exception
void testSetAllele_2 () throws Exception
void testSetAllele_3 () throws Exception
void testSetAllele_4 () throws Exception
void testSetAllele_5 () throws Exception
void testSetAllele_6 () throws Exception
void testSetAllele_7 () throws Exception
void testSetConstraintChecker_0 () throws Exception
void testCompareTo_0 () throws Exception
void testCompareTo_1 () throws Exception
void testCompareTo_2 () throws Exception
void testCompareTo_3_1 () throws Exception
void testCompareTo_3_2 () throws Exception
void testCompareTo_4 () throws Exception
void testApplyMutation_0 () throws Exception
void testApplyMutation_1 () throws Exception
void testApplyMutation_2 () throws Exception
void testApplyMutation_3 () throws Exception
void testApplyMutation_4 () throws Exception
void testApplyMutation_5 () throws Exception
void testSetValueFromPersistentRepresentation_0 () throws Exception
void testSetValueFromPersistentRepresentation_1 () throws Exception
void testSetValueFromPersistentRepresentation_2 () throws Exception
void testSetValueFromPersistentRepresentation_3 () throws Exception
void testSetValueFromPersistentRepresentation_4 () throws Exception
void testSetValueFromPersistentRepresentation_5 () throws Exception
void testSetValueFromPersistentRepresentation_6 () throws Exception
void testGetPersistentRepresentation_0 () throws Exception
void testGetPersistentRepresentation_1 () throws Exception
void testGetPersistentRepresentation_2 () throws Exception
void testClone_0 () throws Exception
void testClone_1 () throws Exception
void testSetBit_0 () throws Exception
void testSetBit_0_2 () throws Exception
void testSetBit_1 () throws Exception
void testSetBit_2 () throws Exception
void testSetBit_3 () throws Exception
void testSetBit_4 () throws Exception
void testSetBit_5 () throws Exception
void testSetBit_6 () throws Exception
void testSubbString_0 () throws Exception
void testSubString_1 () throws Exception
void testFlip_0 () throws Exception
void testFlip_1 () throws Exception
void testSetToRandomValue_0 () throws Exception
void testSetToRandomValue_1 () throws Exception
void testSetToRandomValue_2 () throws Exception
void testSetToRandomValue_3 () throws Exception
void testNewGene_0 () throws Exception
void testHashCode_0 () throws Exception
void testHashCode_1 () throws Exception
void testHashCode_2 () throws Exception
void testHashCode_3 () throws Exception
void testSetEnergy_0 () throws Exception
void testSetEnergy_1 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.34 $`
Additional Inherited Members
Detailed Description
Tests the FixedBinaryGene class.
Author
Klaus Meffert
vamsi
Since
2.0
Definition at line 22 of file FixedBinaryGeneTest.java.
Member Function Documentation
static Test org.jgap.impl.FixedBinaryGeneTest.suite () [inline], [static]
Definition at line 27 of file FixedBinaryGeneTest.java.
void org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_0 () throws Exception [inline]
Apply Mutation (index,percentage). if >0 make 1(0) if <0 make 0(1)
Author
vamsi
Exceptions
Exception
Definition at line 646 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.toString().
void org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_1 () throws Exception [inline]
Author
vamsi
Exceptions
Exception
Definition at line 659 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.toString().
void org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_2 () throws Exception [inline]
Author
vamsi
Exceptions
Exception
Definition at line 672 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_3 () throws Exception [inline]
Author
vamsi
Exceptions
Exception
Definition at line 691 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.toString().
void org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_4 () throws Exception [inline]
Author
vamsi
Exceptions
Exception
Definition at line 704 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.toString().
void org.jgap.impl.FixedBinaryGeneTest.testApplyMutation_5 () throws Exception [inline]
Author
vamsi
Exceptions
Exception
Definition at line 719 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.toString().
void org.jgap.impl.FixedBinaryGeneTest.testClone_0 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 899 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.FixedBinaryGene.clone(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testClone_1 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 912 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.FixedBinaryGene.clone(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testCompareTo_0 () throws Exception [inline]
Comparison should return 0 if same, -1 if less 1 if more.
Author
vamsi
Exceptions
Exception
Definition at line 548 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.FixedBinaryGene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testCompareTo_1 () throws Exception [inline]
Author
vamsi
Exceptions
Exception
Definition at line 564 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.FixedBinaryGene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testCompareTo_2 () throws Exception [inline]
Author
vamsi
Exceptions
Exception
Definition at line 577 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.FixedBinaryGene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testCompareTo_3_1 () throws Exception [inline]
Author
vamsi
Exceptions
Exception
Definition at line 596 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testCompareTo_3_2 () throws Exception [inline]
Author
vamsi
Exceptions
Exception
Definition at line 614 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testCompareTo_4 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 632 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.FixedBinaryGene.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 38 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testConstruct_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 52 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testConstruct_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 68 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testConstruct_3 () throws Exception [inline]
Exceptions
Exception
Author
vamsi
Definition at line 84 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.FixedBinaryGene.getBit(), and org.jgap.impl.FixedBinaryGene.toString().
void org.jgap.impl.FixedBinaryGeneTest.testConstruct_4 () throws Exception [inline]
Exceptions
Exception
Author
vamsi
Definition at line 100 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.FixedBinaryGene.getValue(), org.jgap.impl.FixedBinaryGene.size(), and org.jgap.impl.FixedBinaryGene.toString().
void org.jgap.impl.FixedBinaryGeneTest.testConstruct_5 () throws Exception [inline]
Buffer allocation test case.
Exceptions
Exception
Author
vamsi
Definition at line 115 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.size().
void org.jgap.impl.FixedBinaryGeneTest.testConstruct_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 130 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testEquals_0 () throws Exception [inline]
Exceptions
Exception
Author
vamsi
Definition at line 229 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testEquals_1 () throws Exception [inline]
Exceptions
Exception
Author
vamsi
Definition at line 241 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testEquals_2 () throws Exception [inline]
Exceptions
Exception
Author
vamsi
Definition at line 252 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testEquals_3 () throws Exception [inline]
Exceptions
Exception
Author
vamsi
Definition at line 267 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testEquals_4 () throws Exception [inline]
Definition at line 273 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testEquals_5 () throws Exception [inline]
Definition at line 281 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testEquals_6 () throws Exception [inline]
Definition at line 289 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testEquals_7 () throws Exception [inline]
Definition at line 297 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testEquals_8 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 311 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testFlip_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 1120 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.getBit().
void org.jgap.impl.FixedBinaryGeneTest.testFlip_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 1138 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testGetAllele_0 () throws Exception [inline]
Exceptions
Exception
Author
vamsi
Definition at line 177 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.FixedBinaryGeneTest.testGetAllele_1 () throws Exception [inline]
Exceptions
Exception
Author
vamsi
Definition at line 194 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testGetAllele_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 212 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.FixedBinaryGeneTest.testGetIntValues_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.3.3
Definition at line 327 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.getIntValues().
void org.jgap.impl.FixedBinaryGeneTest.testGetIntValues_1 () throws Exception [inline]
Exceptions
Exception
Author
vamsi
Definition at line 339 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.getIntValues().
void org.jgap.impl.FixedBinaryGeneTest.testGetIntValues_2 () throws Exception [inline]
Exceptions
Exception
Author
vamsi
Definition at line 350 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testGetIntValues_3 () throws Exception [inline]
Exceptions
Exception
Author
vamsi
Definition at line 365 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.FixedBinaryGene.getBit(), and org.jgap.impl.FixedBinaryGene.getLength().
void org.jgap.impl.FixedBinaryGeneTest.testGetPersistentRepresentation_0 () throws Exception [inline]
Author
vamsi
Exceptions
Exception
Definition at line 854 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testGetPersistentRepresentation_1 () throws Exception [inline]
Exceptions
Exception
Author
vamsi
Since
2.0
Definition at line 868 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testGetPersistentRepresentation_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 886 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testHashCode_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Todo
Todo implement checks for uniqueness
Definition at line 1233 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testHashCode_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 1250 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.FixedBinaryGeneTest.testHashCode_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 1267 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testHashCode_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 1282 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testNewGene_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1216 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseGene.equals(), and org.jgap.BaseGene.newGene().
void org.jgap.impl.FixedBinaryGeneTest.testSetAllele_0 () throws Exception [inline]
Allele is null.
Exceptions
Exception
Author
vamsi
Definition at line 382 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSetAllele_1 () throws Exception [inline]
Allele is of wrong type.
Exceptions
Exception
Author
vamsi
Definition at line 401 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSetAllele_2 () throws Exception [inline]
Set Allele to int values, no exception should occur.
Exceptions
Exception
Author
vamsi
Definition at line 420 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSetAllele_3 () throws Exception [inline]
The implementation should throw an exception if the alle size is more than the size of the created gene.
Author
vamsi
Exceptions
Exception
Definition at line 433 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSetAllele_4 () throws Exception [inline]
Allele contains illegal characters.
Author
vamsi
Exceptions
Exception
Definition at line 451 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSetAllele_5 () throws Exception [inline]
Allele is of wrong length.
Author
vamsi
Exceptions
Exception
Definition at line 469 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSetAllele_6 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 487 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.getBit().
void org.jgap.impl.FixedBinaryGeneTest.testSetAllele_7 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 508 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.getBit().
void org.jgap.impl.FixedBinaryGeneTest.testSetBit_0 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 925 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.getBit().
void org.jgap.impl.FixedBinaryGeneTest.testSetBit_0_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.3.3
Definition at line 944 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.getBit().
void org.jgap.impl.FixedBinaryGeneTest.testSetBit_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 963 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.getBit().
void org.jgap.impl.FixedBinaryGeneTest.testSetBit_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 980 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSetBit_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 999 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSetBit_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 1018 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSetBit_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1037 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSetBit_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1060 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSetConstraintChecker_0 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 529 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getConstraintChecker().
void org.jgap.impl.FixedBinaryGeneTest.testSetEnergy_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 1299 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getEnergy().
void org.jgap.impl.FixedBinaryGeneTest.testSetEnergy_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 1311 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getEnergy().
void org.jgap.impl.FixedBinaryGeneTest.testSetToRandomValue_0 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 1157 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSetToRandomValue_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 1175 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSetToRandomValue_2 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 1187 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.getBit().
void org.jgap.impl.FixedBinaryGeneTest.testSetToRandomValue_3 () throws Exception [inline]
Author
Klaus Meffert
Since
2.2
Exceptions
Exception
Definition at line 1202 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.getBit().
void org.jgap.impl.FixedBinaryGeneTest.testSetValueFromPersistentRepresentation_0 () throws Exception [inline]
Author
vamsi
Since
2.0
Exceptions
Exception
Definition at line 736 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSetValueFromPersistentRepresentation_1 () throws Exception [inline]
Since
2.0
Exceptions
Exception
Definition at line 752 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSetValueFromPersistentRepresentation_2 () throws Exception [inline]
Exceptions
Exception
Author
vamsi
Since
2.0
Definition at line 770 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.getBit().
void org.jgap.impl.FixedBinaryGeneTest.testSetValueFromPersistentRepresentation_3 () throws Exception [inline]
Exceptions
Exception
Author
vamsi
Since
2.0
Definition at line 786 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.getBit().
void org.jgap.impl.FixedBinaryGeneTest.testSetValueFromPersistentRepresentation_4 () throws Exception [inline]
Exceptions
Exception
Author
vamsi
Since
2.0
Definition at line 802 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.FixedBinaryGene.getBit().
void org.jgap.impl.FixedBinaryGeneTest.testSetValueFromPersistentRepresentation_5 () throws Exception [inline]
Exceptions
Exception
Since
2.0
Author
Klaus Meffert
Definition at line 819 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSetValueFromPersistentRepresentation_6 () throws Exception [inline]
Author
vamsi
Since
2.0
Exceptions
Exception
Definition at line 837 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSubbString_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 1081 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testSubString_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 1101 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.FixedBinaryGeneTest.testToString_0 () throws Exception [inline]
Exceptions
Exception
Author
vamsi
Definition at line 141 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.toString().
void org.jgap.impl.FixedBinaryGeneTest.testToString_1 () throws Exception [inline]
Exceptions
Exception
Author
vamsi
Definition at line 153 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.toString().
void org.jgap.impl.FixedBinaryGeneTest.testToString_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 166 of file FixedBinaryGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.toString().
Member Data Documentation
final String org.jgap.impl.FixedBinaryGeneTest.CVS_REVISION = `$Revision: 1.34 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file FixedBinaryGeneTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/FixedBinaryGeneTest.java