org.jgap.impl.job.MaxFunction Class Reference
Public Member Functions
double evaluate (IChromosome a_subject)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Additional Inherited Members
Detailed Description
Fitness function for SimpleJobConsumer.
Author
Klaus Meffert
Since
3.2
Definition at line 21 of file MaxFunction.java.
Member Function Documentation
double org.jgap.impl.job.MaxFunction.evaluate (IChromosome a_subject) [inline], [virtual]
Determine the fitness of the given Chromosome instance. The higher the return value, the more fit the instance. This method should always return the same fitness value for two equivalent Chromosome instances.
Parameters
a_subject the Chromosome instance to evaluate
Returns
positive double reflecting the fitness rating of the given Chromosome. Note that if a non-positive double is returned, a RuntimeException should be generated
Author
Neil Rotstan
Klaus Meffert
Since
2.0 (until 1.1: return type int)
Implements org.jgap.FitnessFunction.
Definition at line 33 of file MaxFunction.java.
References org.jgap.impl.BooleanGene.booleanValue(), org.jgap.IChromosome.getGene(), and org.jgap.IChromosome.size().
Member Data Documentation
final String org.jgap.impl.job.MaxFunction.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file MaxFunction.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/job/MaxFunction.java