examples.monalisa.core.PointMutationOperator Class Reference
Public Member Functions
PointMutationOperator (final Configuration a_config, final int a_desiredMutationRate) throws InvalidConfigurationException
void operate (final Population a_population, final List a_candidateChromosomes)
Private Member Functions
void mutateGene (final Gene a_gene, final RandomGenerator a_generator)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Detailed Description
Moves a point of a chromosome randomly.
Author
Yann N. Dauphin
Since
3.4
Definition at line 22 of file PointMutationOperator.java.
Constructor & Destructor Documentation
examples.monalisa.core.PointMutationOperator.PointMutationOperator (final Configuration a_config, final int a_desiredMutationRate) throws InvalidConfigurationException [inline]
Definition at line 27 of file PointMutationOperator.java.
Member Function Documentation
void examples.monalisa.core.PointMutationOperator.mutateGene (final Gene a_gene, final RandomGenerator a_generator) [inline], [private]
Definition at line 155 of file PointMutationOperator.java.
Referenced by examples.monalisa.core.PointMutationOperator.operate().
void examples.monalisa.core.PointMutationOperator.operate (final Population a_population, final List a_candidateChromosomes) [inline]
Todo
Todo move to base class, refactor
Definition at line 34 of file PointMutationOperator.java.
References examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfGenesPerPoint(), examples.monalisa.core.PointMutationOperator.mutateGene(), and examples.monalisa.core.GAInitialChromosomeFactory.POINTS.
Member Data Documentation
final String examples.monalisa.core.PointMutationOperator.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file PointMutationOperator.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/monalisa/core/PointMutationOperator.java