org.jgap.impl.fitness.RosenbrocksBulkNegativeFunction Class Reference
Public Member Functions
double evaluate (IChromosome ic)
double getFunctionValue (double X, double Y)
void evaluate (Population a_subject)
Additional Inherited Members
Detailed Description
Rosenbrock's fitness function.
Rosenbrock's function is a good test function in optimization. It has a unique minimum value at the point (1,1). Finding the minimum is a challenge for some algorithms since it has a shallow minimum inside a deeply curved valley.
Author
Vasilis
Since
3.6.2
Definition at line 17 of file RosenbrocksBulkNegativeFunction.java.
Member Function Documentation
double org.jgap.impl.fitness.RosenbrocksBulkNegativeFunction.evaluate (IChromosome ic) [inline]
Definition at line 34 of file RosenbrocksBulkNegativeFunction.java.
References org.jgap.impl.fitness.RosenbrocksBulkNegativeFunction.getFunctionValue(), and org.jgap.IChromosome.getGene().
Referenced by org.jgap.impl.fitness.RosenbrocksBulkNegativeFunction.evaluate().
void org.jgap.impl.fitness.RosenbrocksBulkNegativeFunction.evaluate (Population a_chromosomes) [inline], [virtual]
Calculates and sets the fitness values on each of the given Chromosomes via their setFitnessValue() method.
Parameters
a_chromosomes list of Chromosomes for which the fitness values must be computed and set
Author
Neil Rotstan
Klaus Meffert
Since
2.2 (prior versions used other input type)
Implements org.jgap.BulkFitnessFunction.
Definition at line 46 of file RosenbrocksBulkNegativeFunction.java.
References org.jgap.impl.fitness.RosenbrocksBulkNegativeFunction.evaluate().
double org.jgap.impl.fitness.RosenbrocksBulkNegativeFunction.getFunctionValue (double X, double Y) [inline]
Definition at line 41 of file RosenbrocksBulkNegativeFunction.java.
Referenced by org.jgap.impl.fitness.RosenbrocksBulkNegativeFunction.evaluate().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/fitness/RosenbrocksBulkNegativeFunction.java