org.jgap.gp.function.CharacterProvider Class Reference
Public Member Functions
CharacterProvider (final GPConfiguration a_conf, Class a_returnType, String a_alphabet) throws InvalidConfigurationException
CharacterProvider (final GPConfiguration a_conf, Class a_returnType, String a_alphabet, int a_subReturnType) throws InvalidConfigurationException
String toString ()
String getName ()
Object execute_object (ProgramChromosome c, int n, Object[] args)
int compareTo (Object a_other)
boolean equals (Object a_other)
Object clone ()
Private Attributes
String m_alphabet
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Additional Inherited Members
Detailed Description
Returns a single character out of a set of given characters. The decision which character to return is controlled by a child of this command which in turn returns an integer index.
Author
Klaus Meffert
Since
3.4.3
Definition at line 26 of file CharacterProvider.java.
Constructor & Destructor Documentation
org.jgap.gp.function.CharacterProvider.CharacterProvider (final GPConfiguration a_conf, Class a_returnType, String a_alphabet) throws InvalidConfigurationException [inline]
Definition at line 36 of file CharacterProvider.java.
Referenced by org.jgap.gp.function.CharacterProvider.clone(), org.jgap.gp.function.CharacterProvider.compareTo(), and org.jgap.gp.function.CharacterProvider.equals().
org.jgap.gp.function.CharacterProvider.CharacterProvider (final GPConfiguration a_conf, Class a_returnType, String a_alphabet, int a_subReturnType) throws InvalidConfigurationException [inline]
Definition at line 42 of file CharacterProvider.java.
References org.jgap.gp.function.CharacterProvider.m_alphabet.
Member Function Documentation
Object org.jgap.gp.function.CharacterProvider.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4.3
Implements org.jgap.util.ICloneable.
Definition at line 124 of file CharacterProvider.java.
References org.jgap.gp.function.CharacterProvider.CharacterProvider(), org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), org.jgap.gp.CommandGene.getSubReturnType(), and org.jgap.gp.function.CharacterProvider.m_alphabet.
int org.jgap.gp.function.CharacterProvider.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.4.3
Definition at line 85 of file CharacterProvider.java.
References org.jgap.gp.function.CharacterProvider.CharacterProvider(), and org.jgap.gp.function.CharacterProvider.m_alphabet.
boolean org.jgap.gp.function.CharacterProvider.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Klaus Meffert
Since
3.4.3
Definition at line 105 of file CharacterProvider.java.
References org.jgap.gp.function.CharacterProvider.CharacterProvider(), and org.jgap.gp.function.CharacterProvider.m_alphabet.
Object org.jgap.gp.function.CharacterProvider.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 66 of file CharacterProvider.java.
String org.jgap.gp.function.CharacterProvider.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 62 of file CharacterProvider.java.
String org.jgap.gp.function.CharacterProvider.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 52 of file CharacterProvider.java.
References org.jgap.gp.function.CharacterProvider.m_alphabet.
Member Data Documentation
final String org.jgap.gp.function.CharacterProvider.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 29 of file CharacterProvider.java.
String org.jgap.gp.function.CharacterProvider.m_alphabet [private]
Alphabet of valid characters.
Definition at line 34 of file CharacterProvider.java.
Referenced by org.jgap.gp.function.CharacterProvider.CharacterProvider(), org.jgap.gp.function.CharacterProvider.clone(), org.jgap.gp.function.CharacterProvider.compareTo(), org.jgap.gp.function.CharacterProvider.equals(), and org.jgap.gp.function.CharacterProvider.toString().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/CharacterProvider.java