examples.math.cmd.AddOperator Class Reference
Public Member Functions
AddOperator ()
AddOperator (Operand theLeft, Operand theRight)
double calcuate ()
void accept (MathVisitor theVisitor)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.1 $`
Additional Inherited Members
Detailed Description
The add operation.
Author
Michael Grove
Since
3.4.2
Definition at line 21 of file AddOperator.java.
Constructor & Destructor Documentation
examples.math.cmd.AddOperator.AddOperator () [inline]
Definition at line 26 of file AddOperator.java.
Referenced by examples.math.cmd.AddOperator.clone().
examples.math.cmd.AddOperator.AddOperator (Operand theLeft, Operand theRight) [inline]
Definition at line 30 of file AddOperator.java.
Member Function Documentation
void examples.math.cmd.AddOperator.accept (MathVisitor theVisitor) [inline]
Implements examples.math.cmd.Operand.
Definition at line 38 of file AddOperator.java.
double examples.math.cmd.AddOperator.calcuate () [inline]
Implements examples.math.cmd.Operator.
Definition at line 34 of file AddOperator.java.
References examples.math.cmd.MathOperator.getLeftOperand(), and examples.math.cmd.MathOperator.getRightOperand().
Object examples.math.cmd.AddOperator.clone () [inline], [virtual]
Implements examples.math.cmd.MathOperator.
Definition at line 42 of file AddOperator.java.
References examples.math.cmd.AddOperator.AddOperator().
Member Data Documentation
final String examples.math.cmd.AddOperator.CVS_REVISION = `$Revision: 1.1 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file AddOperator.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/math/cmd/AddOperator.java