org.jgap.util.SystemKit Class Reference
Static Public Member Functions
static double getTotalMemoryMB ()
static double getTotalMemoryKB ()
static double getFreeMemoryMB ()
static double getFreeMemoryKB ()
static String niceMemory (double a_mem)
static void printHelp (CommandLine cmd, Options options)
static String getGUID ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.9 $`
Detailed Description
System-related utility functions.
Author
Klaus Meffert
Since
3.2
Definition at line 24 of file SystemKit.java.
Member Function Documentation
static double org.jgap.util.SystemKit.getFreeMemoryKB () [inline], [static]
Returns
free memory available in the VM in kilobytes.
Author
Klaus Meffert
Since
3.2.1
Definition at line 64 of file SystemKit.java.
Referenced by org.jgap.util.SystemKit.getFreeMemoryMB().
static double org.jgap.util.SystemKit.getFreeMemoryMB () [inline], [static]
Returns
free memory available in the VM in megabytes.
Author
Klaus Meffert
Since
3.2 (since 3.0 in GPGenotype)
Definition at line 54 of file SystemKit.java.
References org.jgap.util.SystemKit.getFreeMemoryKB().
static String org.jgap.util.SystemKit.getGUID () [inline], [static]
Returns
a GUID
Author
Klaus Meffert
Since
3.5
Definition at line 153 of file SystemKit.java.
static double org.jgap.util.SystemKit.getTotalMemoryKB () [inline], [static]
Returns
total memory available by the VM in kilobytes.
Author
Klaus Meffert
Since
3.2.1
Definition at line 44 of file SystemKit.java.
Referenced by org.jgap.util.SystemKit.getTotalMemoryMB().
static double org.jgap.util.SystemKit.getTotalMemoryMB () [inline], [static]
Returns
total memory available by the VM in megabytes.
Author
Klaus Meffert
Since
3.2 (since 3.0 in GPGenotype)
Definition at line 34 of file SystemKit.java.
References org.jgap.util.SystemKit.getTotalMemoryKB().
static String org.jgap.util.SystemKit.niceMemory (double a_mem) [inline], [static]
Nicifies a decimal string by cutting of all but two decimal places.
Parameters
a_mem the number to make nice
Returns
nicified number as a string
Since
3.3.1
Definition at line 76 of file SystemKit.java.
static void org.jgap.util.SystemKit.printHelp (CommandLine cmd, Options options) [inline], [static]
Prints all available comamnd line options.
Parameters
cmd the CommandLine object
options the Options list
Author
Klaus Meffert
Since
3.3.4
Definition at line 132 of file SystemKit.java.
Member Data Documentation
final String org.jgap.util.SystemKit.CVS_REVISION = `$Revision: 1.9 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file SystemKit.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/util/SystemKit.java