examples.gp.anttrail.TurnToFood Class Reference
Public Member Functions
TurnToFood (final GPConfiguration a_conf) throws InvalidConfigurationException
CommandGene applyMutation (int index, double a_percentage) throws InvalidConfigurationException
void execute_void (ProgramChromosome a_chrom, int a_n, Object[] a_args)
String toString ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
Look ahead, right and left (in this order) and turns to food in case such was detected. Does nothing in the other case.
This command is not part of the classic ant problem.
Author
Klaus Meffert
Since
3.01
Definition at line 24 of file TurnToFood.java.
Constructor & Destructor Documentation
examples.gp.anttrail.TurnToFood.TurnToFood (final GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Constructor.
Parameters
a_conf the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.01
Definition at line 39 of file TurnToFood.java.
References org.jgap.gp.CommandGene.VoidClass.
Member Function Documentation
CommandGene examples.gp.anttrail.TurnToFood.applyMutation (int index, double a_percentage) throws InvalidConfigurationException [inline]
Definition at line 44 of file TurnToFood.java.
References org.jgap.gp.CommandGene.getGPConfiguration().
void examples.gp.anttrail.TurnToFood.execute_void (ProgramChromosome a_chrom, int a_n, Object[] a_args) [inline]
Definition at line 59 of file TurnToFood.java.
References examples.gp.anttrail.AntMap.FOOD, examples.gp.anttrail.AntMap.getFromMap(), examples.gp.anttrail.AntMap.getHeight(), examples.gp.anttrail.AntCommand.getMap(), examples.gp.anttrail.AntMap.getWidth(), examples.gp.anttrail.AntMap.O_DOWN, examples.gp.anttrail.AntMap.O_LEFT, examples.gp.anttrail.AntMap.O_RIGHT, and examples.gp.anttrail.AntMap.O_UP.
String examples.gp.anttrail.TurnToFood.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 190 of file TurnToFood.java.
Member Data Documentation
final String examples.gp.anttrail.TurnToFood.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file TurnToFood.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/anttrail/TurnToFood.java