examples.gp.anttrail.IfFoodAheadRight Class Reference
Public Member Functions
IfFoodAheadRight (final GPConfiguration a_conf) throws InvalidConfigurationException
IfFoodAheadRight (final GPConfiguration a_conf, int a_lookAheadFields) throws InvalidConfigurationException
CommandGene applyMutation (int index, double a_percentage) throws InvalidConfigurationException
void execute_void (ProgramChromosome a_chrom, int a_n, Object[] a_args)
String toString ()
Private Attributes
int m_lookAheadFields
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
If food-ahead to the right then execute <child 0> else execute <child 1>.
Author
Klaus Meffert
Since
3.01
Definition at line 22 of file IfFoodAheadRight.java.
Constructor & Destructor Documentation
examples.gp.anttrail.IfFoodAheadRight.IfFoodAheadRight (final GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Looks ahead 1 field to the right.
Parameters
a_conf the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.01
Definition at line 38 of file IfFoodAheadRight.java.
examples.gp.anttrail.IfFoodAheadRight.IfFoodAheadRight (final GPConfiguration a_conf, int a_lookAheadFields) throws InvalidConfigurationException [inline]
Allows to specify how many fields to look ahead to the right.
Parameters
a_conf the configuration to use
a_lookAheadFields look ahead n fields
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.01
Definition at line 54 of file IfFoodAheadRight.java.
References examples.gp.anttrail.IfFoodAheadRight.m_lookAheadFields, and org.jgap.gp.CommandGene.VoidClass.
Member Function Documentation
CommandGene examples.gp.anttrail.IfFoodAheadRight.applyMutation (int index, double a_percentage) throws InvalidConfigurationException [inline]
Definition at line 60 of file IfFoodAheadRight.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), and examples.gp.anttrail.IfFoodAheadRight.m_lookAheadFields.
void examples.gp.anttrail.IfFoodAheadRight.execute_void (ProgramChromosome a_chrom, int a_n, Object[] a_args) [inline]
Definition at line 67 of file IfFoodAheadRight.java.
References examples.gp.anttrail.AntMap.EMPTY, examples.gp.anttrail.AntMap.ERROR, examples.gp.anttrail.AntMap.FOOD, examples.gp.anttrail.AntMap.getHeight(), examples.gp.anttrail.AntCommand.getMap(), examples.gp.anttrail.AntMap.getWidth(), and examples.gp.anttrail.IfFoodAheadRight.m_lookAheadFields.
String examples.gp.anttrail.IfFoodAheadRight.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 119 of file IfFoodAheadRight.java.
References examples.gp.anttrail.IfFoodAheadRight.m_lookAheadFields.
Member Data Documentation
final String examples.gp.anttrail.IfFoodAheadRight.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file IfFoodAheadRight.java.
int examples.gp.anttrail.IfFoodAheadRight.m_lookAheadFields [private]
Definition at line 27 of file IfFoodAheadRight.java.
Referenced by examples.gp.anttrail.IfFoodAheadRight.applyMutation(), examples.gp.anttrail.IfFoodAheadRight.execute_void(), examples.gp.anttrail.IfFoodAheadRight.IfFoodAheadRight(), and examples.gp.anttrail.IfFoodAheadRight.toString().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/anttrail/IfFoodAheadRight.java