org.jgap.gp.impl.GPProgram Class Reference
Public Member Functions
GPProgram () throws Exception
GPProgram (GPConfiguration a_conf, Class[] a_types, Class[][] a_argTypes, CommandGene[][] a_nodeSets, int[] a_minDepths, int[] a_maxDepths, int a_maxNodes) throws InvalidConfigurationException
GPProgram (IGPProgram a_prog) throws InvalidConfigurationException
GPProgram (GPConfiguration a_conf, int a_numChromosomes) throws InvalidConfigurationException
ProgramChromosome getChromosome (int a_index)
void setChromosome (int a_index, ProgramChromosome a_chrom)
void growOrFull (int a_depth, boolean a_grow, int a_maxNodes, boolean[] a_fullModeAllowed, int a_tries)
void growOrFull (Class[][] a_argTypes, CommandGene[][] a_nodeSets)
int size ()
String toString (int a_startNode)
String toStringNorm (int a_startNode)
String toStringDebug ()
int execute_int (int a_chromosomeNum, Object[] a_args)
float execute_float (int a_chromosomeNum, Object[] a_args)
double execute_double (int a_chromosomeNum, Object[] a_args)
boolean execute_boolean (int a_chromosomeNum, Object[] a_args)
Object execute_object (int a_chromosomeNum, Object[] a_args)
void execute_void (int a_chromosomeNum, Object[] a_args)
int getCommandOfClass (int a_chromosomeNum, Class a_class)
int compareTo (Object a_other)
Object clone ()
String getPersistentRepresentation ()
String getBusinessKey ()
Protected Member Functions
GPProgramInfo putToCache (GPProgram a_program)
String encode (String a_string)
String decode (String a_string)
Private Attributes
ProgramChromosome[] m_chromosomes
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.24 $`
Additional Inherited Members
Detailed Description
A GP program contains 1..n ProgramChromosome's.
Author
Klaus Meffert
Since
3.0
Definition at line 26 of file GPProgram.java.
Constructor & Destructor Documentation
org.jgap.gp.impl.GPProgram.GPProgram () throws Exception [inline]
Default constructor, only for dynamic instantiation.
Exceptions
Exception
Author
Klaus Meffert
Since
3.3.4
Definition at line 51 of file GPProgram.java.
Referenced by org.jgap.gp.impl.GPProgram.clone(), and org.jgap.gp.impl.GPProgram.compareTo().
org.jgap.gp.impl.GPProgram.GPProgram (GPConfiguration a_conf, Class[] a_types, Class a_argTypes[][], CommandGene a_nodeSets[][], int[] a_minDepths, int[] a_maxDepths, int a_maxNodes) throws InvalidConfigurationException [inline]
Master constructor.
Parameters
a_conf the configuration to use
a_types the type of each chromosome, the length is the number of chromosomes
a_argTypes the types of the arguments to each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of arguments to the chromosome
a_nodeSets the nodes which are allowed to be used by each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of nodes
a_minDepths contains the minimum depth allowed for each chromosome
a_maxDepths contains the maximum depth allowed for each chromosome
a_maxNodes reserve space for a_maxNodes number of nodes
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 76 of file GPProgram.java.
References org.jgap.gp.impl.GPProgram.m_chromosomes, org.jgap.gp.GPProgramBase.setArgTypes(), org.jgap.gp.GPProgramBase.setMaxDepths(), org.jgap.gp.GPProgramBase.setMaxNodes(), org.jgap.gp.GPProgramBase.setMinDepths(), org.jgap.gp.GPProgramBase.setNodeSets(), and org.jgap.gp.GPProgramBase.setTypes().
org.jgap.gp.impl.GPProgram.GPProgram (IGPProgram a_prog) throws InvalidConfigurationException [inline]
Constructor to initialize a GPProgram with values of another GPProgram.
Parameters
a_prog the GPProgram to read the initialization values from
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 99 of file GPProgram.java.
References org.jgap.gp.GPProgramBase.getTypes(), and org.jgap.gp.impl.GPProgram.m_chromosomes.
org.jgap.gp.impl.GPProgram.GPProgram (GPConfiguration a_conf, int a_numChromosomes) throws InvalidConfigurationException [inline]
Sort of minimalistic constructor. Use only if you are aware of what you do.
Parameters
a_conf the configuration to use
a_numChromosomes the number of chromosomes to use with this program.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 115 of file GPProgram.java.
References org.jgap.gp.impl.GPProgram.m_chromosomes.
Member Function Documentation
Object org.jgap.gp.impl.GPProgram.clone () [inline], [virtual]
Returns
deep clone of the object instance
Author
Klaus Meffert
Since
3.2
Implements org.jgap.gp.GPProgramBase.
Definition at line 538 of file GPProgram.java.
References org.jgap.gp.GPProgramBase.getApplicationData(), org.jgap.gp.GPProgramBase.getArgTypes(), org.jgap.gp.GPProgramBase.getFitnessValueDirectly(), org.jgap.gp.GPProgramBase.getGPConfiguration(), org.jgap.gp.GPProgramBase.getMaxDepths(), org.jgap.gp.GPProgramBase.getMaxNodes(), org.jgap.gp.GPProgramBase.getMinDepths(), org.jgap.gp.GPProgramBase.getNodeSets(), org.jgap.gp.GPProgramBase.getTypes(), org.jgap.gp.impl.GPProgram.GPProgram(), and org.jgap.gp.impl.GPProgram.m_chromosomes.
int org.jgap.gp.impl.GPProgram.compareTo (Object a_other) [inline]
Compares the given program to this program.
Parameters
a_other the program against which to compare this program
Returns
a negative number if this program is `less than` the given program, zero if they are equal to each other, and a positive number if this program is `greater than` the given program
Author
Klaus Meffert
Since
3.0
Definition at line 499 of file GPProgram.java.
References org.jgap.gp.impl.GPProgram.GPProgram(), org.jgap.gp.impl.GPProgram.m_chromosomes, and org.jgap.gp.impl.GPProgram.size().
String org.jgap.gp.impl.GPProgram.decode (String a_string) [inline], [protected]
Definition at line 613 of file GPProgram.java.
String org.jgap.gp.impl.GPProgram.encode (String a_string) [inline], [protected]
Definition at line 609 of file GPProgram.java.
Referenced by org.jgap.gp.impl.GPProgram.getPersistentRepresentation().
boolean org.jgap.gp.impl.GPProgram.execute_boolean (int a_chromosomeNum, Object[] a_args) [inline]
Executes the given chromosome as a boolean function.
Parameters
a_chromosomeNum the index of the chromosome to execute
a_args the arguments to use
Returns
the boolean return value
Author
Klaus Meffert
Since
3.2
Implements org.jgap.gp.IGPProgram.
Definition at line 434 of file GPProgram.java.
References org.jgap.gp.impl.GPProgram.m_chromosomes.
double org.jgap.gp.impl.GPProgram.execute_double (int a_chromosomeNum, Object[] a_args) [inline]
Executes the given chromosome as a double function.
Parameters
a_chromosomeNum the index of the chromosome to execute
a_args the arguments to use
Returns
the double return value
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IGPProgram.
Definition at line 419 of file GPProgram.java.
References org.jgap.gp.impl.GPProgram.m_chromosomes.
float org.jgap.gp.impl.GPProgram.execute_float (int a_chromosomeNum, Object[] a_args) [inline]
Executes the given chromosome as a float function.
Parameters
a_chromosomeNum the index of the chromosome to execute
a_args the arguments to use
Returns
the floar return value
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IGPProgram.
Definition at line 404 of file GPProgram.java.
References org.jgap.gp.impl.GPProgram.m_chromosomes.
int org.jgap.gp.impl.GPProgram.execute_int (int a_chromosomeNum, Object[] a_args) [inline]
Executes the given chromosome as an integer function.
Parameters
a_chromosomeNum the index of the chromosome to execute
a_args the arguments to use
Returns
the integer return value
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IGPProgram.
Definition at line 389 of file GPProgram.java.
References org.jgap.gp.impl.GPProgram.m_chromosomes.
Object org.jgap.gp.impl.GPProgram.execute_object (int a_chromosomeNum, Object[] a_args) [inline]
Executes the given chromosome as an object function.
Parameters
a_chromosomeNum the index of the chromosome to execute
a_args the arguments to use
Returns
the object return value
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IGPProgram.
Definition at line 449 of file GPProgram.java.
References org.jgap.gp.impl.GPProgram.m_chromosomes.
void org.jgap.gp.impl.GPProgram.execute_void (int a_chromosomeNum, Object[] a_args) [inline]
Executes the given chromosome as an object function.
Parameters
a_chromosomeNum the index of the chromosome to execute
a_args the arguments to use
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IGPProgram.
Definition at line 463 of file GPProgram.java.
References org.jgap.gp.impl.GPProgram.m_chromosomes.
String org.jgap.gp.impl.GPProgram.getBusinessKey () [inline]
Returns
hopefully unique key representing the state of the GPProgram
Author
Klaus Meffert
Since
3.4
Implements org.jgap.IBusinessKey.
Definition at line 623 of file GPProgram.java.
References org.jgap.gp.impl.GPProgram.toStringNorm().
ProgramChromosome org.jgap.gp.impl.GPProgram.getChromosome (int a_index) [inline]
Parameters
a_index the chromosome to get
Returns
the ProgramChromosome with the given index
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IGPProgram.
Definition at line 128 of file GPProgram.java.
References org.jgap.gp.impl.GPProgram.m_chromosomes.
int org.jgap.gp.impl.GPProgram.getCommandOfClass (int a_chromosomeNum, Class a_class) [inline]
Searches for a chromosome that has the given class and returns its index.
Parameters
a_chromosomeNum the index of the chromosome to start the search with
a_class the class to find
Returns
the index of the first chromosome found that is of a_class, or -1
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IGPProgram.
Definition at line 478 of file GPProgram.java.
References org.jgap.gp.impl.GPProgram.m_chromosomes.
String org.jgap.gp.impl.GPProgram.getPersistentRepresentation () [inline]
Returns
the persistent representation of the GP program, including all chromosomes
Author
Klaus Meffert
Since
3.3
Implements org.jgap.gp.IGPProgram.
Definition at line 596 of file GPProgram.java.
References org.jgap.gp.impl.GPProgram.encode(), and org.jgap.gp.impl.GPProgram.m_chromosomes.
void org.jgap.gp.impl.GPProgram.growOrFull (int a_depth, boolean a_grow, int a_maxNodes, boolean[] a_fullModeAllowed, int a_tries) [inline]
Initialize the chromosomes within this GP program using the grow or the full method.
Parameters
a_depth the maximum depth of the chromosome to create
a_grow true: use grow method; false: use full method
a_maxNodes maximum number of nodes allowed
a_fullModeAllowed for each chromosome: true means full mode allowed, otherwise use grow mode
a_tries maximum number of tries to create a valid program
Author
Klaus Meffert
Since
3.0
Definition at line 163 of file GPProgram.java.
References org.jgap.gp.GPProgramBase.getArgType(), org.jgap.gp.GPProgramBase.getArgTypes(), org.jgap.gp.impl.GPProgramInfo.getFitnessValue(), org.jgap.gp.GPProgramBase.getGPConfiguration(), org.jgap.gp.GPProgramBase.getMaxDepths(), org.jgap.gp.GPProgramBase.getMinDepths(), org.jgap.gp.GPProgramBase.getNodeSet(), org.jgap.gp.GPProgramBase.getNodeSets(), org.jgap.gp.GPProgramBase.getType(), org.jgap.gp.GPProgramBase.getTypes(), org.jgap.gp.impl.GPProgram.m_chromosomes, org.jgap.gp.impl.GPProgram.putToCache(), org.jgap.gp.GPProgramBase.setFitnessValue(), and org.jgap.gp.impl.GPProgram.size().
void org.jgap.gp.impl.GPProgram.growOrFull (Class a_argTypes[][], CommandGene a_nodeSets[][]) [inline]
Initialize this program by using given chromosomes.
Parameters
a_argTypes the types of the arguments to each chromosome, must be an array of arrays, the first dimension of which is the number of chromosomes and the second dimension of which is the number of arguments to the chromosome
a_nodeSets the nodes which are allowed to be used by each chromosome,
Author
Klaus Meffert
Since
3.2.2
Definition at line 255 of file GPProgram.java.
References org.jgap.gp.impl.GPProgramInfo.getFitnessValue(), org.jgap.gp.GPProgramBase.getGPConfiguration(), org.jgap.gp.GPProgramBase.getNodeSets(), org.jgap.gp.GPProgramBase.getTypes(), org.jgap.gp.impl.GPProgram.m_chromosomes, org.jgap.gp.impl.GPProgram.putToCache(), org.jgap.gp.GPProgramBase.setFitnessValue(), and org.jgap.gp.impl.GPProgram.size().
GPProgramInfo org.jgap.gp.impl.GPProgram.putToCache (GPProgram a_program) [inline], [protected]
Put program to cache.
Parameters
a_program the program to put into the cache
Returns
GPProgramInfo info about the program
Author
Klaus Meffert
Since
3.4
Definition at line 239 of file GPProgram.java.
References org.jgap.gp.GPProgramBase.getGPConfiguration().
Referenced by org.jgap.gp.impl.GPProgram.growOrFull().
void org.jgap.gp.impl.GPProgram.setChromosome (int a_index, ProgramChromosome a_chrom) [inline]
Sets the given chromosome at the given index.
Parameters
a_index sic
a_chrom sic
Author
Klaus Meffert
Since
3.0
Definition at line 145 of file GPProgram.java.
References org.jgap.gp.impl.GPProgram.m_chromosomes.
int org.jgap.gp.impl.GPProgram.size () [inline]
Returns
the number of chromosomes in the program
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IGPProgram.
Definition at line 307 of file GPProgram.java.
Referenced by org.jgap.gp.impl.GPProgram.compareTo(), and org.jgap.gp.impl.GPProgram.growOrFull().
String org.jgap.gp.impl.GPProgram.toString (int a_startNode) [inline]
Builds a string that represents the output of the GPProgram in left-hand-notion.
Parameters
a_startNode the node to start with
Returns
output in left-hand notion
Author
Klaus Meffert
Since
3.0
Definition at line 321 of file GPProgram.java.
References org.jgap.gp.impl.GPProgram.m_chromosomes.
String org.jgap.gp.impl.GPProgram.toStringDebug () [inline]
Builds a string that represents the debug output of the GPProgram.
Returns
class names of all program chromosomes
Author
Klaus Meffert
Since
3.0
Definition at line 367 of file GPProgram.java.
References org.jgap.gp.impl.GPProgram.m_chromosomes.
String org.jgap.gp.impl.GPProgram.toStringNorm (int a_startNode) [inline]
Builds a string that represents the normalized output of the GPProgram.
Parameters
a_startNode the node to start with
Returns
output in normalized notion
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IGPProgram.
Definition at line 344 of file GPProgram.java.
References org.jgap.gp.impl.GPProgram.m_chromosomes.
Referenced by org.jgap.gp.impl.GPProgram.getBusinessKey().
Member Data Documentation
final String org.jgap.gp.impl.GPProgram.CVS_REVISION = `$Revision: 1.24 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 30 of file GPProgram.java.
ProgramChromosome [] org.jgap.gp.impl.GPProgram.m_chromosomes [private]
Holds the chromosomes contained in this program.
Definition at line 41 of file GPProgram.java.
Referenced by org.jgap.gp.impl.GPProgram.clone(), org.jgap.gp.impl.GPProgram.compareTo(), org.jgap.gp.impl.GPProgram.execute_boolean(), org.jgap.gp.impl.GPProgram.execute_double(), org.jgap.gp.impl.GPProgram.execute_float(), org.jgap.gp.impl.GPProgram.execute_int(), org.jgap.gp.impl.GPProgram.execute_object(), org.jgap.gp.impl.GPProgram.execute_void(), org.jgap.gp.impl.GPProgram.getChromosome(), org.jgap.gp.impl.GPProgram.getCommandOfClass(), org.jgap.gp.impl.GPProgram.getPersistentRepresentation(), org.jgap.gp.impl.GPProgram.GPProgram(), org.jgap.gp.impl.GPProgram.growOrFull(), org.jgap.gp.impl.GPProgram.setChromosome(), org.jgap.gp.impl.GPProgram.toString(), org.jgap.gp.impl.GPProgram.toStringDebug(), and org.jgap.gp.impl.GPProgram.toStringNorm().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/impl/GPProgram.java