org.jgap.impl.InversionOperatorTest Class Reference
Classes
class TestConstraintChecker
Public Member Functions
void setUp ()
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testOperate_0 () throws Exception
void testOperate_1 () throws Exception
void testOperate_2 () throws Exception
void testEquals_0 () throws Exception
void testOperate_3 () throws Exception
void testCompareTo_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.12 $`
Additional Inherited Members
Detailed Description
Tests the InversionOperator class.
Author
Klaus Meffert
Since
2.3
Definition at line 23 of file InversionOperatorTest.java.
Member Function Documentation
void org.jgap.impl.InversionOperatorTest.setUp () [inline]
Definition at line 33 of file InversionOperatorTest.java.
static Test org.jgap.impl.InversionOperatorTest.suite () [inline], [static]
Definition at line 28 of file InversionOperatorTest.java.
void org.jgap.impl.InversionOperatorTest.testCompareTo_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 299 of file InversionOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.impl.InversionOperator.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.InversionOperatorTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 43 of file InversionOperatorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.InversionOperatorTest.testConstruct_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 54 of file InversionOperatorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.InversionOperatorTest.testEquals_0 () throws Exception [inline]
Test equals with classcast object.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 231 of file InversionOperatorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.InversionOperatorTest.testOperate_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 67 of file InversionOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.InversionOperatorTest.testOperate_1 () throws Exception [inline]
Tests if operator produces same results for two operate-runs.
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 124 of file InversionOperatorTest.java.
References org.jgap.Chromosome.clone(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.isChromosomesEqual().
void org.jgap.impl.InversionOperatorTest.testOperate_2 () throws Exception [inline]
Test with CompositeGene.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 173 of file InversionOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseGene.getAllele(), and org.jgap.impl.CompositeGene.getAllele().
void org.jgap.impl.InversionOperatorTest.testOperate_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 243 of file InversionOperatorTest.java.
References org.jgap.JGAPTestCase.conf.
Member Data Documentation
final String org.jgap.impl.InversionOperatorTest.CVS_REVISION = `$Revision: 1.12 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file InversionOperatorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/InversionOperatorTest.java