org.jgap.impl.DefaultConfiguration Class Reference
Public Member Functions
DefaultConfiguration ()
DefaultConfiguration (String a_id, String a_name)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.26 $`
Additional Inherited Members
Detailed Description
The DefaultConfiguration class simplifies the JGAP configuration process by providing default configuration values for many of the configuration settings. The following values must still be provided: the sample Chromosome, population size, and desired fitness function. All other settings may also be changed in the normal fashion for those who wish to specify other custom values.
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 28 of file DefaultConfiguration.java.
Constructor & Destructor Documentation
org.jgap.impl.DefaultConfiguration.DefaultConfiguration () [inline]
Definition at line 33 of file DefaultConfiguration.java.
org.jgap.impl.DefaultConfiguration.DefaultConfiguration (String a_id, String a_name) [inline]
Constructs a new DefaultConfiguration instance with a number of configuration settings set to default values. It is still necessary to set the sample Chromosome, population size, and desired fitness function. Other settings may optionally be altered as desired.
Parameters
a_id unique id for the configuration within the current thread
a_name informative name of the configuration, may be null
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 50 of file DefaultConfiguration.java.
References org.jgap.Configuration.addGeneticOperator(), org.jgap.Configuration.addNaturalSelector(), org.jgap.Configuration.setBreeder(), org.jgap.Configuration.setChromosomePool(), org.jgap.Configuration.setEventManager(), org.jgap.Configuration.setFitnessEvaluator(), org.jgap.Configuration.setKeepPopulationSizeConstant(), org.jgap.Configuration.setMinimumPopSizePercent(), org.jgap.Configuration.setRandomGenerator(), and org.jgap.Configuration.setSelectFromPrevGen().
Member Function Documentation
Object org.jgap.impl.DefaultConfiguration.clone () [inline]
Returns
deep clone of this instance
Author
Klaus Meffert
Since
3.2
Implements org.jgap.util.ICloneable.
Definition at line 83 of file DefaultConfiguration.java.
Member Data Documentation
final String org.jgap.impl.DefaultConfiguration.CVS_REVISION = `$Revision: 1.26 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 31 of file DefaultConfiguration.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/DefaultConfiguration.java