org.jgap.gp.BaseGPChromosome Class Reference
Public Member Functions
BaseGPChromosome (GPConfiguration a_configuration) throws InvalidConfigurationException
BaseGPChromosome (GPConfiguration a_configuration, IGPProgram a_ind) throws InvalidConfigurationException
IGPProgram getIndividual ()
void setIndividual (IGPProgram a_ind)
int getTerminal (int a_index)
int getFunction (int a_index)
int getTerminal (int a_index, Class a_type, int a_subType)
int getFunction (int a_index, Class a_type, int a_subType)
int numTerminals ()
int numFunctions ()
int numTerminals (Class a_type, int a_subType)
int numFunctions (Class a_type, int a_subType)
CommandGene getNode (int a_index)
int getCommandOfClass (int a_n, Class a_class)
int getAssignableFromClass (int a_n, Class a_class)
int getVariableWithReturnType (int a_n, Class a_returnType)
GPConfiguration getGPConfiguration ()
Private Attributes
GPConfiguration m_configuration
IGPProgram m_ind
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.8 $`
Additional Inherited Members
Detailed Description
Abstract base class for all implementations of IGPChromosome.
Author
Klaus Meffert
Since
3.01
Definition at line 22 of file BaseGPChromosome.java.
Constructor & Destructor Documentation
org.jgap.gp.BaseGPChromosome.BaseGPChromosome (GPConfiguration a_configuration) throws InvalidConfigurationException [inline]
Definition at line 37 of file BaseGPChromosome.java.
References org.jgap.gp.BaseGPChromosome.m_configuration.
org.jgap.gp.BaseGPChromosome.BaseGPChromosome (GPConfiguration a_configuration, IGPProgram a_ind) throws InvalidConfigurationException [inline]
Definition at line 47 of file BaseGPChromosome.java.
References org.jgap.gp.BaseGPChromosome.m_ind.
Member Function Documentation
int org.jgap.gp.BaseGPChromosome.getAssignableFromClass (int a_n, Class a_class) [inline]
Helper: Find GP command being assignable from given class.
Parameters
a_n return the n'th found command (starting at zero)
a_class the class to find a command for
Returns
index of first found matching GP command, or -1 if none found
Author
Klaus Meffert
Since
3.3
Definition at line 318 of file BaseGPChromosome.java.
References org.jgap.gp.IGPChromosome.getFunctions().
int org.jgap.gp.BaseGPChromosome.getCommandOfClass (int a_n, Class a_class) [inline]
Helper: Find GP command with given class and return index of it.
Parameters
a_n return the n'th found command (starting at zero)
a_class the class to find a command for
Returns
index of first found matching GP command, or -1 if none found
Author
Klaus Meffert
Since
3.01
Definition at line 295 of file BaseGPChromosome.java.
References org.jgap.gp.IGPChromosome.getFunctions().
Referenced by org.jgap.gp.impl.ProgramChromosome.growOrFullNode().
int org.jgap.gp.BaseGPChromosome.getFunction (int a_index) [inline]
Gets the a_index'th function in this chromosome. The nodes are counted in a depth-first manner, with node zero being the first function in this chromosome.
Parameters
a_index the a_index'th function to get
Returns
the function
Author
Klaus Meffert
Since
3.01 (since 3.0 in ProgramChromosome)
Implements org.jgap.gp.IGPChromosome.
Definition at line 113 of file BaseGPChromosome.java.
References org.jgap.gp.IGPChromosome.getFunctions(), and org.jgap.gp.BaseGPChromosome.m_ind.
int org.jgap.gp.BaseGPChromosome.getFunction (int a_index, Class a_type, int a_subType) [inline]
Gets the i'th function of the given return type in this chromosome. The nodes are counted in a depth-first manner, with node zero being the first function of the given type in this chromosome.
Parameters
a_index the i'th function to get
a_type the type of function to get
a_subType the subtype to consider
Returns
the index of the function found, or -1 if no appropriate function was found
Author
Klaus Meffert
Since
3.01 (since 3.0 in ProgramChromosome)
Implements org.jgap.gp.IGPChromosome.
Definition at line 169 of file BaseGPChromosome.java.
References org.jgap.gp.IGPChromosome.getFunctions(), and org.jgap.gp.BaseGPChromosome.m_ind.
GPConfiguration org.jgap.gp.BaseGPChromosome.getGPConfiguration () [inline]
Implements org.jgap.gp.IGPChromosome.
Definition at line 357 of file BaseGPChromosome.java.
References org.jgap.gp.BaseGPChromosome.m_configuration.
Referenced by org.jgap.gp.impl.ProgramChromosome.clone(), org.jgap.gp.impl.ProgramChromosome.createGene(), org.jgap.gp.impl.ProgramChromosome.growOrFull(), org.jgap.gp.impl.ProgramChromosome.growOrFullNode(), org.jgap.gp.impl.ProgramChromosome.init(), and org.jgap.gp.impl.ProgramChromosome.selectNode().
IGPProgram org.jgap.gp.BaseGPChromosome.getIndividual () [inline]
Returns
the individual containing this chromosome
Author
Klaus Meffert
Since
3.01 (since 3.0 in ProgramChromosome)
Implements org.jgap.gp.IGPChromosome.
Definition at line 59 of file BaseGPChromosome.java.
References org.jgap.gp.BaseGPChromosome.m_ind.
Referenced by org.jgap.gp.impl.ProgramChromosome.clone(), org.jgap.gp.impl.ProgramChromosome.growOrFullNode(), org.jgap.gp.impl.ProgramChromosome.isPossible(), org.jgap.gp.impl.ProgramChromosome.redepth(), org.jgap.gp.impl.ProgramChromosome.selectNode(), org.jgap.gp.impl.ProgramChromosome.toString(), org.jgap.gp.impl.ProgramChromosome.toStringDebug(), and org.jgap.gp.impl.ProgramChromosome.toStringNorm().
CommandGene org.jgap.gp.BaseGPChromosome.getNode (int a_index) [inline]
Gets the a_index'th node in this chromosome. The nodes are counted in a depth-first manner, with node zero being the root of this chromosome.
Parameters
a_index the node number to get
Returns
the node
Author
Klaus Meffert
Since
3.01
Implements org.jgap.gp.IGPChromosome.
Definition at line 278 of file BaseGPChromosome.java.
References org.jgap.gp.IGPChromosome.getFunctions().
int org.jgap.gp.BaseGPChromosome.getTerminal (int a_index) [inline]
Gets the i'th terminal in this chromosome. The nodes are counted in a depth-first manner, with node zero being the first terminal in this chromosome.
Parameters
a_index the i'th terminal to get
Returns
the terminal
Author
Klaus Meffert
Since
3.01 (since 3.0 in ProgramChromosome)
Implements org.jgap.gp.IGPChromosome.
Definition at line 89 of file BaseGPChromosome.java.
References org.jgap.gp.IGPChromosome.getFunctions(), and org.jgap.gp.BaseGPChromosome.m_ind.
int org.jgap.gp.BaseGPChromosome.getTerminal (int a_index, Class a_type, int a_subType) [inline]
Gets the a_index'th terminal of the given type in this chromosome. The nodes are counted in a depth-first manner, with node zero being the first terminal of the given type in this chromosome.
Parameters
a_index the a_index'th terminal to get
a_type the type of terminal to get
a_subType the subtype to consider
Returns
the index of the terminal found, or -1 if no appropriate terminal was found
Author
Klaus Meffert
Since
3.01 (since 3.0 in ProgramChromosome)
Implements org.jgap.gp.IGPChromosome.
Definition at line 140 of file BaseGPChromosome.java.
References org.jgap.gp.IGPChromosome.getFunctions(), and org.jgap.gp.BaseGPChromosome.m_ind.
int org.jgap.gp.BaseGPChromosome.getVariableWithReturnType (int a_n, Class a_returnType) [inline]
Helper: Find GP Variable with given return type and return index of it.
Parameters
a_n return the n'th found command (starting at zero)
a_returnType the return type to find a Variable for
Returns
index of first found matching GP command, or -1 if none found
Author
Klaus Meffert
Since
3.01 (since 3.0 in ProgramChromosome)
Definition at line 341 of file BaseGPChromosome.java.
References org.jgap.gp.IGPChromosome.getFunctions().
int org.jgap.gp.BaseGPChromosome.numFunctions () [inline]
Returns
the number of functions in this chromosome
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IGPChromosome.
Definition at line 208 of file BaseGPChromosome.java.
References org.jgap.gp.IGPChromosome.getFunctions(), and org.jgap.gp.BaseGPChromosome.m_ind.
int org.jgap.gp.BaseGPChromosome.numFunctions (Class a_type, int a_subType) [inline]
Counts the number of functions of the given type in this chromosome.
Parameters
a_type the type of function to count
a_subType the subtype to consider
Returns
the number of functions in this chromosome.
Author
Klaus Meffert
Since
3.01 (since 3.0 in ProgramChromosome)
Implements org.jgap.gp.IGPChromosome.
Definition at line 254 of file BaseGPChromosome.java.
References org.jgap.gp.IGPChromosome.getFunctions(), and org.jgap.gp.BaseGPChromosome.m_ind.
int org.jgap.gp.BaseGPChromosome.numTerminals () [inline]
Returns
the number of terminals in this chromosome
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IGPChromosome.
Definition at line 190 of file BaseGPChromosome.java.
References org.jgap.gp.IGPChromosome.getFunctions(), and org.jgap.gp.BaseGPChromosome.m_ind.
int org.jgap.gp.BaseGPChromosome.numTerminals (Class a_type, int a_subType) [inline]
Counts the number of terminals of the given type in this chromosome.
Parameters
a_type the type of terminal to count
a_subType the subtype to consider
Returns
the number of terminals in this chromosome
Author
Klaus Meffert
Since
3.01 (since 3.0 in ProgramChromosome)
Implements org.jgap.gp.IGPChromosome.
Definition at line 230 of file BaseGPChromosome.java.
References org.jgap.gp.IGPChromosome.getFunctions(), and org.jgap.gp.BaseGPChromosome.m_ind.
void org.jgap.gp.BaseGPChromosome.setIndividual (IGPProgram a_ind) [inline]
Sets the individual the chromosome belongs to.
Parameters
a_ind the individual containing this chromosome
Author
Klaus Meffert
Since
3.01 (since 3.0 in ProgramChromosome)
Implements org.jgap.gp.IGPChromosome.
Definition at line 71 of file BaseGPChromosome.java.
References org.jgap.gp.BaseGPChromosome.m_ind.
Member Data Documentation
final String org.jgap.gp.BaseGPChromosome.CVS_REVISION = `$Revision: 1.8 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file BaseGPChromosome.java.
GPConfiguration org.jgap.gp.BaseGPChromosome.m_configuration [private]
The configuration object to use.
Definition at line 30 of file BaseGPChromosome.java.
Referenced by org.jgap.gp.BaseGPChromosome.BaseGPChromosome(), and org.jgap.gp.BaseGPChromosome.getGPConfiguration().
IGPProgram org.jgap.gp.BaseGPChromosome.m_ind [private]
The individual the chromosome belongs to.
Definition at line 35 of file BaseGPChromosome.java.
Referenced by org.jgap.gp.BaseGPChromosome.BaseGPChromosome(), org.jgap.gp.BaseGPChromosome.getFunction(), org.jgap.gp.BaseGPChromosome.getIndividual(), org.jgap.gp.BaseGPChromosome.getTerminal(), org.jgap.gp.BaseGPChromosome.numFunctions(), org.jgap.gp.BaseGPChromosome.numTerminals(), and org.jgap.gp.BaseGPChromosome.setIndividual().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/BaseGPChromosome.java