org.jgap.gp.function.ForXLoop Class Reference
Public Member Functions
ForXLoop (final GPConfiguration a_conf, Class a_type) throws InvalidConfigurationException
String toString ()
String getName ()
void execute_void (ProgramChromosome c, int n, Object[] args)
boolean isValid (ProgramChromosome a_program)
Class getChildType (IGPProgram a_ind, int a_chromNum)
Class getReturnType ()
int compareTo (Object a_other)
boolean equals (Object a_other)
Object clone ()
Private Attributes
Class m_type
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.12 $`
Additional Inherited Members
Detailed Description
The for-loop loop from 0 to X-1.
Author
Klaus Meffert
Since
3.0
Definition at line 25 of file ForXLoop.java.
Constructor & Destructor Documentation
org.jgap.gp.function.ForXLoop.ForXLoop (final GPConfiguration a_conf, Class a_type) throws InvalidConfigurationException [inline]
Definition at line 32 of file ForXLoop.java.
References org.jgap.gp.function.ForXLoop.m_type, and org.jgap.gp.CommandGene.VoidClass.
Referenced by org.jgap.gp.function.ForXLoop.clone(), org.jgap.gp.function.ForXLoop.compareTo(), and org.jgap.gp.function.ForXLoop.equals().
Member Function Documentation
Object org.jgap.gp.function.ForXLoop.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 145 of file ForXLoop.java.
References org.jgap.gp.function.ForXLoop.ForXLoop(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.function.ForXLoop.m_type.
int org.jgap.gp.function.ForXLoop.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.0
Definition at line 106 of file ForXLoop.java.
References org.jgap.gp.function.ForXLoop.ForXLoop(), and org.jgap.gp.function.ForXLoop.m_type.
boolean org.jgap.gp.function.ForXLoop.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Klaus Meffert
Since
3.0
Definition at line 125 of file ForXLoop.java.
References org.jgap.gp.function.ForXLoop.ForXLoop(), org.jgap.gp.function.ForXLoop.m_type, and org.jgap.gp.CommandGene.size().
void org.jgap.gp.function.ForXLoop.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Todo
Todo only consider variables appearing before FORX in the program tree
Definition at line 52 of file ForXLoop.java.
References org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.DoubleClass, org.jgap.gp.CommandGene.FloatClass, org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.CommandGene.LongClass, and org.jgap.gp.function.ForXLoop.m_type.
Class org.jgap.gp.function.ForXLoop.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Definition at line 90 of file ForXLoop.java.
References org.jgap.gp.CommandGene.VoidClass.
String org.jgap.gp.function.ForXLoop.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 48 of file ForXLoop.java.
Class org.jgap.gp.function.ForXLoop.getReturnType () [inline]
Definition at line 94 of file ForXLoop.java.
boolean org.jgap.gp.function.ForXLoop.isValid (ProgramChromosome a_program) [inline]
Definition at line 86 of file ForXLoop.java.
References org.jgap.gp.function.ForXLoop.m_type.
String org.jgap.gp.function.ForXLoop.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 38 of file ForXLoop.java.
Member Data Documentation
final String org.jgap.gp.function.ForXLoop.CVS_REVISION = `$Revision: 1.12 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file ForXLoop.java.
Class org.jgap.gp.function.ForXLoop.m_type [private]
Definition at line 30 of file ForXLoop.java.
Referenced by org.jgap.gp.function.ForXLoop.clone(), org.jgap.gp.function.ForXLoop.compareTo(), org.jgap.gp.function.ForXLoop.equals(), org.jgap.gp.function.ForXLoop.execute_void(), org.jgap.gp.function.ForXLoop.ForXLoop(), and org.jgap.gp.function.ForXLoop.isValid().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/ForXLoop.java