org.jgap.GenotypeTest Class Reference
Classes
class ChromosomeForTest2
class MyChromosome
class Test2Function
class TestConfiguration
Public Member Functions
void setUp ()
void testConstruct_0 () throws Exception
void testConstruct_02 () throws Exception
void testConstruct_1 () throws Exception
void testConstruct_2 () throws Exception
void testConstruct_3 () throws Exception
void testConstruct_4 () throws Exception
void testConstruct_5 () throws Exception
void testConstruct_6 () throws Exception
void testConstruct_7 () throws Exception
void testConstruct_8 () throws Exception
void testConstruct_9 () throws Exception
void testGetChromosomes_0 () throws Exception
void testGetFittestChromosome_0 () throws Exception
void testGetFittestChromosome_1 () throws Exception
void testGetFittestChromosomes_0 () throws Exception
void testEvolve_0 () throws Exception
void testEvolve_1 () throws Exception
void testEvolve_2_1 () throws Exception
void testEvolve_2_3 () throws Exception
void testEvolve_2_2 () throws Exception
void testEvolve_3_1 () throws Exception
void testEvolve_3_2 () throws Exception
void testEvolve_3_25 () throws Exception
void testEvolve_3_26 () throws Exception
void testEvolve_3_3 () throws Exception
void testEvolve_5_1 () throws Exception
void testEvolve_5_2 () throws Exception
void testEvolve_5_3 () throws Exception
void testEvolve_6 () throws Exception
void testEvolve_7 () throws Exception
void testEvolve_8 () throws Exception
void testEvolve_9 () throws Exception
void testEvolve_10 () throws Exception
void testToString_0 () throws Exception
void testToString_1 () throws Exception
void testRandomInitialGenotype_0 () throws Exception
void testRandomInitialGenotype_1 () throws Exception
void testRandomInitialGenotype_2 () throws Exception
void testRandomInitialGenotype_3 () throws Exception
void testRandomInitialGenotype_4 () throws Exception
void testEquals_0 () throws Exception
void testEquals_1 () throws Exception
void testEquals_2 () throws Exception
void testHashcode_0 () throws Exception
void testHashcode_1 () throws Exception
void testIsSerializable_0 () throws Exception
void testdoSerialize_0 () throws Exception
void testBreeder_0 () throws Exception
Static Public Member Functions
static Test suite ()
Private Member Functions
int doTestEvolve_5 (Configuration config) throws Exception
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.75 $`
static final int MAX_CHROMOSOME_TO_TEST = 1000
static final int MAX_GENES_TO_TEST = 25
static final int MAX_GENES_TYPES = 6
Additional Inherited Members
Detailed Description
Tests the Genotype class.
Author
Klaus Meffert
Since
1.1
Definition at line 27 of file GenotypeTest.java.
Member Function Documentation
int org.jgap.GenotypeTest.doTestEvolve_5 (Configuration config) throws Exception [inline], [private]
Helper: used in tests for evolve method
Parameters
config Configuration
Exceptions
Exception
Returns
number of times the fitness value has been computed for the first chromosome
Author
Klaus Meffert
Since
2.5
Definition at line 730 of file GenotypeTest.java.
References org.jgap.Genotype.getPopulation().
Referenced by org.jgap.GenotypeTest.testEvolve_5_1(), org.jgap.GenotypeTest.testEvolve_5_2(), and org.jgap.GenotypeTest.testEvolve_5_3().
void org.jgap.GenotypeTest.setUp () [inline]
Definition at line 37 of file GenotypeTest.java.
static Test org.jgap.GenotypeTest.suite () [inline], [static]
Definition at line 32 of file GenotypeTest.java.
void org.jgap.GenotypeTest.testBreeder_0 () throws Exception [inline]
With specific configurations there was a bug in GABreeder: Some chromosomes where not updates properly.
Exceptions
Exception
Since
3.6
Definition at line 1472 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.IChromosome.getGene().
void org.jgap.GenotypeTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 48 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testConstruct_02 () throws Exception [inline]
Unproper Configuration (e.g. fitness function not set)
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 65 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testConstruct_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 82 of file GenotypeTest.java.
void org.jgap.GenotypeTest.testConstruct_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 99 of file GenotypeTest.java.
void org.jgap.GenotypeTest.testConstruct_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 121 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testConstruct_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 141 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testConstruct_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 162 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testConstruct_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 184 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testConstruct_7 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 205 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testConstruct_8 () throws Exception [inline]
Tests that construction is possible without exception. Here, the sample chromosome is of a different type than the chromosome(s) making up the population. This is possible because the sample chromosome comes into play just with Genotype.randomInitialGenotype.
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 230 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testConstruct_9 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 247 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testdoSerialize_0 () throws Exception [inline]
Ensures that Genotype and all objects contained implement Serializable.
Exceptions
Exception
Author
Klaus Meffert
Since
2.3
Definition at line 1320 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testEquals_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 1059 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testEquals_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1082 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testEquals_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1105 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testEvolve_0 () throws Exception [inline]
Assert population size shrinks when using special configuration and by overwriting default setting for keeping population size constant.
Exceptions
Exception
Author
Klaus Meffert
Since
2.3
Definition at line 356 of file GenotypeTest.java.
References org.jgap.Configuration.getSampleChromosome(), and org.jgap.JGAPTestCase.uniqueChromosomes().
void org.jgap.GenotypeTest.testEvolve_1 () throws Exception [inline]
Test evolve with BulkFitnessFunction.
Exceptions
Exception
Author
Klaus Meffert
Since
2.3
Definition at line 383 of file GenotypeTest.java.
References org.jgap.Genotype.getPopulation(), and org.jgap.JGAPTestCase.uniqueChromosomes().
void org.jgap.GenotypeTest.testEvolve_10 () throws Exception [inline]
Asserts that evolutions works without error (see bug 1748528).
Exceptions
Exception
Author
Klaus Meffert
Since
3.2.1
Definition at line 858 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf, org.jgap.Configuration.PROPERTY_FITEVAL_INST, and org.jgap.JGAPTestCase.uniqueChromosomes().
void org.jgap.GenotypeTest.testEvolve_2_1 () throws Exception [inline]
Test that population size remains constant when the configuration contains a BCS as postselector.
Exceptions
Exception
Author
Klaus Meffert
Since
2.3
Definition at line 412 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.uniqueChromosomes().
void org.jgap.GenotypeTest.testEvolve_2_2 () throws Exception [inline]
Test that multiple NaturalSelector's work without error
Exceptions
Exception
Author
Klaus Meffert
Since
2.3
Definition at line 493 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.uniqueChromosomes().
void org.jgap.GenotypeTest.testEvolve_2_3 () throws Exception [inline]
Test that size of selected sub-population size is the fraction configured when using a BCS as preselector.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 442 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.DELTA, org.jgap.Configuration.getSelectFromPrevGen(), and org.jgap.JGAPTestCase.uniqueChromosomes().
void org.jgap.GenotypeTest.testEvolve_3_1 () throws Exception [inline]
Test that population size remains constant with default settings.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 520 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.uniqueChromosomes().
void org.jgap.GenotypeTest.testEvolve_3_2 () throws Exception [inline]
Test that population size grows with default settings overwritten.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 541 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.uniqueChromosomes().
void org.jgap.GenotypeTest.testEvolve_3_25 () throws Exception [inline]
Test that population size grows with default settings overwritten.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2.2
Definition at line 565 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.uniqueChromosomes().
void org.jgap.GenotypeTest.testEvolve_3_26 () throws Exception [inline]
Test that population size grows with default settings overwritten.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2.2
Definition at line 592 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.uniqueChromosomes().
void org.jgap.GenotypeTest.testEvolve_3_3 () throws Exception [inline]
Expect exception when no natural selectors are provided.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2.2
Definition at line 625 of file GenotypeTest.java.
void org.jgap.GenotypeTest.testEvolve_5_1 () throws Exception [inline]
Test that for new chromosomes (e.g. mutated ones) their fitness value will be recomputed. Reveals bug 1368072.
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 648 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf, org.jgap.GenotypeTest.doTestEvolve_5(), and org.jgap.Configuration.PROPERTY_SAMPLE_CHROM_INST.
void org.jgap.GenotypeTest.testEvolve_5_2 () throws Exception [inline]
Test that for new chromosomes (e.g. mutated ones) their fitness value will be recomputed. Reveals bug 1368072.
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 676 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf, org.jgap.GenotypeTest.doTestEvolve_5(), and org.jgap.Configuration.PROPERTY_SAMPLE_CHROM_INST.
void org.jgap.GenotypeTest.testEvolve_5_3 () throws Exception [inline]
Test that for new chromosomes (e.g. mutated ones) their fitness value will only be recomputed if necessary. Special case in which bug 1368072 does not apply.
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 703 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.GenotypeTest.doTestEvolve_5(), and org.jgap.Configuration.PROPERTY_SAMPLE_CHROM_INST.
void org.jgap.GenotypeTest.testEvolve_6 () throws Exception [inline]
Population is null.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 763 of file GenotypeTest.java.
void org.jgap.GenotypeTest.testEvolve_7 () throws Exception [inline]
minimumPopSizePercent > 0.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 784 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.uniqueChromosomes().
void org.jgap.GenotypeTest.testEvolve_8 () throws Exception [inline]
Preserve fittest Chromosome.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 808 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.uniqueChromosomes().
void org.jgap.GenotypeTest.testEvolve_9 () throws Exception [inline]
Preserve fittest Chromosome.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 835 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.uniqueChromosomes().
void org.jgap.GenotypeTest.testGetChromosomes_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 268 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testGetFittestChromosome_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 289 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testGetFittestChromosome_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 310 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testGetFittestChromosomes_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 331 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testHashcode_0 () throws Exception [inline]
Test if hashcode working in general.
Exceptions
Exception
Author
Klaus Meffert
John Serri
Since
2.1
Definition at line 1127 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testHashcode_1 () throws Exception [inline]
Definition at line 1146 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf, org.jgap.GenotypeTest.MAX_CHROMOSOME_TO_TEST, org.jgap.GenotypeTest.MAX_GENES_TO_TEST, and org.jgap.GenotypeTest.MAX_GENES_TYPES.
void org.jgap.GenotypeTest.testIsSerializable_0 () throws Exception [inline]
This test fails and shows the need for revamping configuration object handling.
Exceptions
Exception
Author
Klaus Meffert
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Todo
Todo following will be obsolete
Ensures Genotype is implementing Serializable.
Exceptions
Exception
Author
Klaus Meffert
Since
2.3
Definition at line 1304 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.isSerializable().
void org.jgap.GenotypeTest.testRandomInitialGenotype_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 954 of file GenotypeTest.java.
void org.jgap.GenotypeTest.testRandomInitialGenotype_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 970 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testRandomInitialGenotype_2 () throws Exception [inline]
Test for a Chromosome class not equal to org.jgap.Chromosome.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 990 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.Gene.getEnergy().
void org.jgap.GenotypeTest.testRandomInitialGenotype_3 () throws Exception [inline]
Use a chromosome implementation for which the DefaultInitializer is not suited.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 1015 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.GenotypeTest.testRandomInitialGenotype_4 () throws Exception [inline]
GeneticOperators missing.
Exceptions
Exception
Author
Klaus Meffert
Since
2.3
Definition at line 1038 of file GenotypeTest.java.
void org.jgap.GenotypeTest.testToString_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 890 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.FitnessFunction.NO_FITNESS_VALUE, org.jgap.IChromosome.S_ALLELES, org.jgap.IChromosome.S_APPLICATION_DATA, org.jgap.IChromosome.S_FITNESS_VALUE, and org.jgap.IChromosome.S_SIZE.
void org.jgap.GenotypeTest.testToString_1 () throws Exception [inline]
Same as testToString_0 except that fitness value is computed
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 921 of file GenotypeTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.IChromosome.S_ALLELES, org.jgap.IChromosome.S_APPLICATION_DATA, org.jgap.IChromosome.S_FITNESS_VALUE, and org.jgap.IChromosome.S_SIZE.
Member Data Documentation
final String org.jgap.GenotypeTest.CVS_REVISION = `$Revision: 1.75 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 30 of file GenotypeTest.java.
final int org.jgap.GenotypeTest.MAX_CHROMOSOME_TO_TEST = 1000 [static], [private]
Definition at line 1140 of file GenotypeTest.java.
Referenced by org.jgap.GenotypeTest.testHashcode_1().
final int org.jgap.GenotypeTest.MAX_GENES_TO_TEST = 25 [static], [private]
Definition at line 1142 of file GenotypeTest.java.
Referenced by org.jgap.GenotypeTest.testHashcode_1().
final int org.jgap.GenotypeTest.MAX_GENES_TYPES = 6 [static], [private]
Definition at line 1144 of file GenotypeTest.java.
Referenced by org.jgap.GenotypeTest.testHashcode_1().
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/GenotypeTest.java