org.jgap.impl.StringGeneTest Class Reference
Classes
class GeneConstraintChecker
Public Member Functions
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testConstruct_2 () throws Exception
void testConstruct_3 () throws Exception
void testConstruct_4 () throws Exception
void testConstruct_5 () throws Exception
void testSetAlphabet_1 () throws Exception
void testToString_0 () throws Exception
void testToString_1 () throws Exception
void testToString_2 () throws Exception
void testGetAllele_0 () throws Exception
void testEquals_0 () throws Exception
void testEquals_1 () throws Exception
void testEquals_2 () throws Exception
void testEquals_3 () throws Exception
void testEquals_4 () throws Exception
void testEquals_5 () throws Exception
void testEquals_6 () throws Exception
void testEquals_7 () throws Exception
void testEquals_8 () throws Exception
void testEquals_9 () throws Exception
void testCompareTo_0 () throws Exception
void testCompareTo_1 () throws Exception
void testCompareTo_2 () throws Exception
void testSetAllele_0 () throws Exception
void testSetAllele_1 () throws Exception
void testSetAllele_2 () throws Exception
void testSetAllele_3 () throws Exception
void testSetAllele_4 () throws Exception
void testSetAllele_5 () throws Exception
void testSetAllele_6 () throws Exception
void testNewGene_0 () throws Exception
void testPersistentRepresentation_0 () throws Exception
void testPersistentRepresentation_1 () throws Exception
void testPersistentRepresentation_2 () throws Exception
void testPersistentRepresentation_3 () throws Exception
void testPersistentRepresentation_4 () throws Exception
void testPersistentRepresentation_5 () throws Exception
void testPersistentRepresentation_5_2 () throws Exception
void testPersistentRepresentation_6 () throws Exception
void testPersistentRepresentation_7 () throws Exception
void testPersistentRepresentation_8 () throws Exception
void testPersistentRepresentation_9 () throws Exception
void testPersistentRepresentation_10 () throws Exception
void testPersistentRepresentation_11 () throws Exception
void testPersistentRepresentation_12 () throws Exception
void testPersistentRepresentation_14 () throws Exception
void testPersistentRepresentation_15 () throws Exception
void testApplyMutation_0 () throws Exception
void testApplyMutation_1 () throws Exception
void testApplyMutation_2 () throws Exception
void testApplyMutation_3 () throws Exception
void testApplyMutation_4 () throws Exception
void testApplyMutation_5 () throws Exception
void testApplyMutation_6 () throws Exception
void testApplyMutation_7 () throws Exception
void testSetMinMaxLength_0 () throws Exception
void testSetToRandomValue_0 () throws Exception
void testSetToRandomValue_1 () throws Exception
void testSetToRandomValue_2 () throws Exception
void testSetToRandomValue_3 () throws Exception
void testSetToRandomValue_4 () throws Exception
void testSetToRandomValue_5 () throws Exception
void testSetToRandomValue_6 () throws Exception
void testSetToRandomValue_7 () throws Exception
void testSetToRandomValue_8 () throws Exception
void testSetConstraintChecker_0 () throws Exception
void testIsValidAlphabet_0 () throws Exception
void testSetEnergy_0 () throws Exception
void testSetEnergy_1 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.39 $`
Additional Inherited Members
Detailed Description
Tests the StringGene class.
Author
Klaus Meffert
Since
1.1
Definition at line 24 of file StringGeneTest.java.
Member Function Documentation
static Test org.jgap.impl.StringGeneTest.suite () [inline], [static]
Definition at line 29 of file StringGeneTest.java.
void org.jgap.impl.StringGeneTest.testApplyMutation_0 () throws Exception [inline]
Following should be possible without exception.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 840 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testApplyMutation_1 () throws Exception [inline]
Following should be possible without exception.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 856 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testApplyMutation_2 () throws Exception [inline]
Invalid index specified.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 871 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testApplyMutation_3 () throws Exception [inline]
No allele set.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 891 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testApplyMutation_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 902 of file StringGeneTest.java.
References org.jgap.impl.StringGene.ALPHABET_CHARACTERS_LOWER, org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.StringGeneTest.testApplyMutation_5 () throws Exception [inline]
Mutation 0.0 should not change anything.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 921 of file StringGeneTest.java.
References org.jgap.impl.StringGene.ALPHABET_CHARACTERS_LOWER, org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.StringGeneTest.testApplyMutation_6 () throws Exception [inline]
applyMutation with empty alphabet.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 938 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testApplyMutation_7 () throws Exception [inline]
null random generator should lead to NullPointerException.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 958 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testCompareTo_0 () throws Exception [inline]
Comparation using application data.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 344 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testCompareTo_1 () throws Exception [inline]
class cast exception.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 376 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testCompareTo_2 () throws Exception [inline]
Comparation using application data and null allele.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 395 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 39 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.StringGene.getAlphabet(), org.jgap.impl.StringGene.getMaxLength(), and org.jgap.impl.StringGene.getMinLength().
void org.jgap.impl.StringGeneTest.testConstruct_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 54 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testConstruct_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 69 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testConstruct_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 84 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testConstruct_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 99 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testConstruct_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 115 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testEquals_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 191 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testEquals_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 204 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testEquals_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 215 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testEquals_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 226 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testEquals_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 237 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testEquals_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 250 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testEquals_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 265 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testEquals_7 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 278 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testEquals_8 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 292 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testEquals_9 () throws Exception [inline]
Using application data.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 316 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testGetAllele_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 179 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.StringGeneTest.testIsValidAlphabet_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1149 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testNewGene_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 539 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.newGene().
void org.jgap.impl.StringGeneTest.testPersistentRepresentation_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 561 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testPersistentRepresentation_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 577 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testPersistentRepresentation_10 () throws Exception [inline]
Invalid number in second argument.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 747 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testPersistentRepresentation_11 () throws Exception [inline]
Invalid number in third argument.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 766 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testPersistentRepresentation_12 () throws Exception [inline]
Minlen to great
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 784 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testPersistentRepresentation_14 () throws Exception [inline]
Maxlen to small
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 802 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testPersistentRepresentation_15 () throws Exception [inline]
Illegal character.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 821 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testPersistentRepresentation_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 594 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testPersistentRepresentation_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 611 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testPersistentRepresentation_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 628 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testPersistentRepresentation_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 645 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.CompositeGene.GENE_DELIMITER, and org.jgap.impl.StringGene.getAlphabet().
void org.jgap.impl.StringGeneTest.testPersistentRepresentation_5_2 () throws Exception [inline]
Use special characters in alphabet
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 667 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.StringGene.getAlphabet(), and org.jgap.Gene.PERSISTENT_FIELD_DELIMITER.
void org.jgap.impl.StringGeneTest.testPersistentRepresentation_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 689 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.StringGeneTest.testPersistentRepresentation_7 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 703 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.StringGene.getPersistentRepresentation().
void org.jgap.impl.StringGeneTest.testPersistentRepresentation_8 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 716 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testPersistentRepresentation_9 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 734 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.StringGene.getPersistentRepresentation().
void org.jgap.impl.StringGeneTest.testSetAllele_0 () throws Exception [inline]
Set Allele to null, no exception should occur.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 421 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testSetAllele_1 () throws Exception [inline]
Allele too short.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 433 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testSetAllele_2 () throws Exception [inline]
Allele consists of illegal characters.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 450 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testSetAllele_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 466 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testSetAllele_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 484 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testSetAllele_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 497 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.StringGene.stringValue().
void org.jgap.impl.StringGeneTest.testSetAllele_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 518 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.StringGene.stringValue().
void org.jgap.impl.StringGeneTest.testSetAlphabet_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 127 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.StringGene.getAlphabet(), and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.StringGeneTest.testSetConstraintChecker_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1131 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getConstraintChecker().
void org.jgap.impl.StringGeneTest.testSetEnergy_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 1166 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getEnergy().
void org.jgap.impl.StringGeneTest.testSetEnergy_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 1178 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getEnergy().
void org.jgap.impl.StringGeneTest.testSetMinMaxLength_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 977 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.StringGene.getMaxLength(), and org.jgap.impl.StringGene.getMinLength().
void org.jgap.impl.StringGeneTest.testSetToRandomValue_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 991 of file StringGeneTest.java.
References org.jgap.impl.StringGene.ALPHABET_CHARACTERS_UPPER, org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.StringGeneTest.testSetToRandomValue_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1008 of file StringGeneTest.java.
References org.jgap.impl.StringGene.ALPHABET_CHARACTERS_UPPER, org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.StringGeneTest.testSetToRandomValue_2 () throws Exception [inline]
Definition at line 1016 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.StringGeneTest.testSetToRandomValue_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1029 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.StringGeneTest.testSetToRandomValue_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1042 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.StringGeneTest.testSetToRandomValue_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1063 of file StringGeneTest.java.
References org.jgap.impl.StringGene.ALPHABET_CHARACTERS_LOWER, and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testSetToRandomValue_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1081 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testSetToRandomValue_7 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 1097 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testSetToRandomValue_8 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 1114 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.StringGeneTest.testToString_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 142 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.toString().
void org.jgap.impl.StringGeneTest.testToString_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 155 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.StringGene.toString().
void org.jgap.impl.StringGeneTest.testToString_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 167 of file StringGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.StringGene.toString().
Member Data Documentation
final String org.jgap.impl.StringGeneTest.CVS_REVISION = `$Revision: 1.39 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file StringGeneTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/StringGeneTest.java