examples.gp.monalisa.core.commands.ColorConstructor Class Reference
Public Member Functions
ColorConstructor (GPConfiguration a_conf) throws InvalidConfigurationException
Object execute_object (ProgramChromosome a_chrom, int a_n, Object[] a_args)
Class getChildType (IGPProgram a_ind, int a_chromNum)
String toString ()
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
Specifies a color, represented by R, G, B and Alpha.
Author
Yann N. Dauphin
Since
3.4
Definition at line 25 of file ColorConstructor.java.
Constructor & Destructor Documentation
examples.gp.monalisa.core.commands.ColorConstructor.ColorConstructor (GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Definition at line 30 of file ColorConstructor.java.
Referenced by examples.gp.monalisa.core.commands.ColorConstructor.clone().
Member Function Documentation
Object examples.gp.monalisa.core.commands.ColorConstructor.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4.1
Definition at line 63 of file ColorConstructor.java.
References examples.gp.monalisa.core.commands.ColorConstructor.ColorConstructor(), and org.jgap.gp.CommandGene.getGPConfiguration().
Object examples.gp.monalisa.core.commands.ColorConstructor.execute_object (ProgramChromosome a_chrom, int a_n, Object[] a_args) [inline]
Definition at line 36 of file ColorConstructor.java.
Class examples.gp.monalisa.core.commands.ColorConstructor.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Definition at line 46 of file ColorConstructor.java.
References org.jgap.gp.CommandGene.FloatClass.
String examples.gp.monalisa.core.commands.ColorConstructor.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 51 of file ColorConstructor.java.
Member Data Documentation
final String examples.gp.monalisa.core.commands.ColorConstructor.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file ColorConstructor.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/monalisa/core/commands/ColorConstructor.java