org.jgap.impl.ChainOfSelectors Class Reference
Public Member Functions
ChainOfSelectors ()
ChainOfSelectors (Configuration a_conf)
void addNaturalSelector (NaturalSelector a_selector) throws InvalidConfigurationException
void addAll (Collection a_c) throws InvalidConfigurationException
int size ()
boolean isEmpty ()
int hashCode ()
boolean equals (final Object a_obj)
NaturalSelector get (final int a_index)
void clear ()
Iterator iterator ()
Object clone ()
int compareTo (Object a_other)
Private Attributes
List m_selectors
Configuration m_conf
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.19 $`
Additional Inherited Members
Detailed Description
Ordered chain of NaturalSelectors. With this container you can plugin NaturalSelector implementations which will be performed either before (pre-) or after (post-selectors) registered genetic operations have been applied.
See Also
Configuration
Genotype
Author
Klaus Meffert
Since
1.1
Definition at line 28 of file ChainOfSelectors.java.
Constructor & Destructor Documentation
org.jgap.impl.ChainOfSelectors.ChainOfSelectors () [inline]
Only for dynamic instantiation.
Author
Klaus Meffert
Since
3.2
Definition at line 47 of file ChainOfSelectors.java.
Referenced by org.jgap.impl.ChainOfSelectors.clone(), org.jgap.impl.ChainOfSelectors.compareTo(), and org.jgap.impl.ChainOfSelectors.equals().
org.jgap.impl.ChainOfSelectors.ChainOfSelectors (Configuration a_conf) [inline]
Definition at line 51 of file ChainOfSelectors.java.
References org.jgap.impl.ChainOfSelectors.m_conf, and org.jgap.impl.ChainOfSelectors.m_selectors.
Member Function Documentation
void org.jgap.impl.ChainOfSelectors.addAll (Collection a_c) throws InvalidConfigurationException [inline]
Parameters
a_c Collection to add all elements from
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
1.1
Definition at line 83 of file ChainOfSelectors.java.
References org.jgap.impl.ChainOfSelectors.addNaturalSelector().
void org.jgap.impl.ChainOfSelectors.addNaturalSelector (NaturalSelector a_selector) throws InvalidConfigurationException [inline]
Adds a natural selector to the chain.
Parameters
a_selector the selector to be added
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
1.1 (previously part of class Configuration)
Definition at line 65 of file ChainOfSelectors.java.
Referenced by org.jgap.impl.ChainOfSelectors.addAll().
void org.jgap.impl.ChainOfSelectors.clear () [inline]
Clears all registered selectors.
Author
Klaus Meffert
Since
1.1
Definition at line 156 of file ChainOfSelectors.java.
Object org.jgap.impl.ChainOfSelectors.clone () [inline]
Returns
deep clone of this instance
Author
Klaus Meffert
Since
3.2
Implements org.jgap.util.ICloneable.
Definition at line 176 of file ChainOfSelectors.java.
References org.jgap.impl.ChainOfSelectors.ChainOfSelectors(), org.jgap.impl.ChainOfSelectors.m_conf, and org.jgap.impl.ChainOfSelectors.m_selectors.
int org.jgap.impl.ChainOfSelectors.compareTo (Object a_other) [inline]
The compareTo-method. Here we simply compare the class names of the contained selectors as INaturalSelector does not contain interface Comparable.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.2
Definition at line 212 of file ChainOfSelectors.java.
References org.jgap.impl.ChainOfSelectors.ChainOfSelectors(), org.jgap.impl.ChainOfSelectors.m_selectors, and org.jgap.impl.ChainOfSelectors.size().
boolean org.jgap.impl.ChainOfSelectors.equals (final Object a_obj) [inline]
Parameters
a_obj Object
Returns
boolean
Author
Klaus Meffert
Since
1.1
Definition at line 124 of file ChainOfSelectors.java.
References org.jgap.impl.ChainOfSelectors.ChainOfSelectors().
Referenced by org.jgap.impl.ChainOfSelectorsTest.testEquals_0(), and org.jgap.impl.ChainOfSelectorsTest.testEquals_1().
NaturalSelector org.jgap.impl.ChainOfSelectors.get (final int a_index) [inline]
Returns a Selector with specific index in the list.
Parameters
a_index the index of the Selector to read from the list
Returns
NaturalSelector
Author
Klaus Meffert
Since
1.1
Definition at line 145 of file ChainOfSelectors.java.
int org.jgap.impl.ChainOfSelectors.hashCode () [inline]
Definition at line 112 of file ChainOfSelectors.java.
Referenced by org.jgap.impl.ChainOfSelectorsTest.testHashCode_0().
boolean org.jgap.impl.ChainOfSelectors.isEmpty () [inline]
Returns
true if number of selectors is zero
Author
Klaus Meffert
Since
1.1
Definition at line 108 of file ChainOfSelectors.java.
References org.jgap.impl.ChainOfSelectors.size().
Referenced by org.jgap.impl.ChainOfSelectorsTest.testClear_0(), org.jgap.impl.ChainOfSelectorsTest.testClear_1(), and org.jgap.impl.ChainOfSelectorsTest.testClear_2().
Iterator org.jgap.impl.ChainOfSelectors.iterator () [inline]
Returns
Iterator for iterating over list of selectors
Author
Klaus Meffert
Since
1.1
Definition at line 166 of file ChainOfSelectors.java.
int org.jgap.impl.ChainOfSelectors.size () [inline]
Returns
number of selectors in list
Author
Klaus Meffert
Since
1.1 (previously part of class Configuration)
Definition at line 98 of file ChainOfSelectors.java.
Referenced by org.jgap.impl.ChainOfSelectors.compareTo(), org.jgap.impl.ChainOfSelectors.isEmpty(), org.jgap.impl.ChainOfSelectorsTest.testClear_1(), and org.jgap.impl.ChainOfSelectorsTest.testClear_2().
Member Data Documentation
final String org.jgap.impl.ChainOfSelectors.CVS_REVISION = `$Revision: 1.19 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 31 of file ChainOfSelectors.java.
Configuration org.jgap.impl.ChainOfSelectors.m_conf [private]
Definition at line 39 of file ChainOfSelectors.java.
Referenced by org.jgap.impl.ChainOfSelectors.ChainOfSelectors(), and org.jgap.impl.ChainOfSelectors.clone().
List org.jgap.impl.ChainOfSelectors.m_selectors [private]
Ordered list holding the NaturalSelector's. Intentionally used as a decorator and not via inheritance!
Definition at line 37 of file ChainOfSelectors.java.
Referenced by org.jgap.impl.ChainOfSelectors.ChainOfSelectors(), org.jgap.impl.ChainOfSelectors.clone(), and org.jgap.impl.ChainOfSelectors.compareTo().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/ChainOfSelectors.java