org.jgap.util.PluginDiscoverer Class Reference
Classes
class ClassFilter
class DirectoryFilter
Public Member Functions
PluginDiscoverer ()
PluginDiscoverer (String a_jarFile)
List findImplementingClasses (final String a_fullInterfaceName) throws ClassNotFoundException
List findImplementingClasses (final Class a_intrface)
List findImplementingClasses (final Class a_intrface, final String a_base, final String a_path)
Static Public Member Functions
static void main (String[] args) throws Exception
Private Member Functions
void init ()
String checkIfClassMatches (String a_jarFilename, final Class a_interfaceClass, String a_testClass)
void findImplementingClasses0 (final Class a_intrface, final List a_result, final String a_base, final String a_path)
Private Attributes
List m_classpathFolders
List m_classpathJars
String m_jarFile
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.9 $`
static final boolean DEBUG = false
Detailed Description
This class will (slightly inefficiently) look for all classes that implement a particular interface. It is useful for plugins. This is done by looking through the contents of all jar files in the classpath, as well as performing a recursive search for *.class files in the classpath directories
This particular class may not work in restrictive ClassLoader environments such as Applets or WebStart. (It may...but unlikely and untested.)
Author
Klaus Meffert
Since
2.3
Definition at line 28 of file PluginDiscoverer.java.
Constructor & Destructor Documentation
org.jgap.util.PluginDiscoverer.PluginDiscoverer () [inline]
Reads the list of jars and classpath folders into instance variables for later (cached) access.
Author
Klaus Meffert
Since
2.3
Definition at line 49 of file PluginDiscoverer.java.
References org.jgap.util.PluginDiscoverer.init().
Referenced by org.jgap.util.PluginDiscoverer.main().
org.jgap.util.PluginDiscoverer.PluginDiscoverer (String a_jarFile) [inline]
Prepares the discoverer for a single jar file
Parameters
a_jarFile String
Author
Klaus Meffert
Since
3.2
Definition at line 72 of file PluginDiscoverer.java.
References org.jgap.util.PluginDiscoverer.init(), and org.jgap.util.PluginDiscoverer.m_jarFile.
Member Function Documentation
String org.jgap.util.PluginDiscoverer.checkIfClassMatches (String a_jarFilename, final Class a_interfaceClass, String a_testClass) [inline], [private]
Checks if a given class matches a given interface
Parameters
interfaceClass The interface we are looking for
testClass class under test against the interface
Returns
corrected name of matched class, or null if not matching
Author
Klaus Meffert
Since
2.3
Definition at line 92 of file PluginDiscoverer.java.
References org.jgap.util.PluginDiscoverer.DEBUG.
Referenced by org.jgap.util.PluginDiscoverer.findImplementingClasses().
List org.jgap.util.PluginDiscoverer.findImplementingClasses (final String a_fullInterfaceName) throws ClassNotFoundException [inline]
Finds all classes implementing the given interface
Parameters
a_fullInterfaceName name of the interface (inclusive package name) to find implementing classes (not abstract) for
Returns
list of class names that implement the given interface
Exceptions
ClassNotFoundException
Author
Klaus Meffert
Since
2.4
Definition at line 161 of file PluginDiscoverer.java.
Referenced by org.jgap.util.PluginDiscoverer.findImplementingClasses0().
List org.jgap.util.PluginDiscoverer.findImplementingClasses (final Class a_intrface) [inline]
Finds all classes implementing the given interface
Parameters
a_intrface the interface to check against
Returns
list of class names that implement the given interface
Author
Klaus Meffert
Since
2.3
Definition at line 175 of file PluginDiscoverer.java.
References org.jgap.util.PluginDiscoverer.checkIfClassMatches(), and org.jgap.util.PluginDiscoverer.findImplementingClasses0().
List org.jgap.util.PluginDiscoverer.findImplementingClasses (final Class a_intrface, final String a_base, final String a_path) [inline]
Finds all classes implementing the given interface within a given directory.
Parameters
a_intrface Class
a_base String
a_path String
Returns
List
Definition at line 267 of file PluginDiscoverer.java.
References org.jgap.util.PluginDiscoverer.checkIfClassMatches().
void org.jgap.util.PluginDiscoverer.findImplementingClasses0 (final Class a_intrface, final List a_result, final String a_base, final String a_path) [inline], [private]
Recursive helper method, searching a path recursively for class files conforming to a given interface
Parameters
intrface the interface we are looking for
result container for storing the results
base base directory
path current location in the traversal
Author
Klaus Meffert
Since
2.3
Definition at line 234 of file PluginDiscoverer.java.
References org.jgap.util.PluginDiscoverer.findImplementingClasses().
Referenced by org.jgap.util.PluginDiscoverer.findImplementingClasses().
void org.jgap.util.PluginDiscoverer.init () [inline], [private]
Definition at line 78 of file PluginDiscoverer.java.
References org.jgap.util.PluginDiscoverer.m_classpathFolders, and org.jgap.util.PluginDiscoverer.m_classpathJars.
Referenced by org.jgap.util.PluginDiscoverer.PluginDiscoverer().
static void org.jgap.util.PluginDiscoverer.main (String[] args) throws Exception [inline], [static]
For testing purpose
Parameters
args not used
Exceptions
Exception in case of any problem
Author
Klaus Meffert
Since
2.3
Definition at line 314 of file PluginDiscoverer.java.
References org.jgap.util.PluginDiscoverer.PluginDiscoverer().
Member Data Documentation
final String org.jgap.util.PluginDiscoverer.CVS_REVISION = `$Revision: 1.9 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 30 of file PluginDiscoverer.java.
final boolean org.jgap.util.PluginDiscoverer.DEBUG = false [static], [private]
Definition at line 32 of file PluginDiscoverer.java.
Referenced by org.jgap.util.PluginDiscoverer.checkIfClassMatches().
List org.jgap.util.PluginDiscoverer.m_classpathFolders [private]
Definition at line 35 of file PluginDiscoverer.java.
Referenced by org.jgap.util.PluginDiscoverer.init().
List org.jgap.util.PluginDiscoverer.m_classpathJars [private]
Definition at line 38 of file PluginDiscoverer.java.
Referenced by org.jgap.util.PluginDiscoverer.init().
String org.jgap.util.PluginDiscoverer.m_jarFile [private]
Definition at line 40 of file PluginDiscoverer.java.
Referenced by org.jgap.util.PluginDiscoverer.PluginDiscoverer().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/util/PluginDiscoverer.java