org.jgap.impl.salesman.TravellingSalesmanTest Class Reference
Classes
class TravellingSalesmanForTesting
Public Member Functions
void setUp ()
void tearDown () throws Exception
void testSampleTravellingSalesmanApp () throws Exception
void testSetStartOffset_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.17 $`
Additional Inherited Members
Detailed Description
Test JGAP's travelling salesman implementation.
Author
Audrius Meskauskas
Klaus Meffert
Since
2.0
Definition at line 24 of file TravellingSalesmanTest.java.
Member Function Documentation
void org.jgap.impl.salesman.TravellingSalesmanTest.setUp () [inline]
Definition at line 34 of file TravellingSalesmanTest.java.
static Test org.jgap.impl.salesman.TravellingSalesmanTest.suite () [inline], [static]
Definition at line 29 of file TravellingSalesmanTest.java.
void org.jgap.impl.salesman.TravellingSalesmanTest.tearDown () throws Exception [inline]
Definition at line 39 of file TravellingSalesmanTest.java.
void org.jgap.impl.salesman.TravellingSalesmanTest.testSampleTravellingSalesmanApp () throws Exception [inline]
Exceptions
Exception
Author
Audrius Meskauskas
Since
2.0
Definition at line 50 of file TravellingSalesmanTest.java.
References org.jgap.IChromosome.getFitnessValue().
void org.jgap.impl.salesman.TravellingSalesmanTest.testSetStartOffset_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 73 of file TravellingSalesmanTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.impl.salesman.Salesman.getStartOffset().
Member Data Documentation
final String org.jgap.impl.salesman.TravellingSalesmanTest.CVS_REVISION = `$Revision: 1.17 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file TravellingSalesmanTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/salesman/TravellingSalesmanTest.java