org.jgap.gp.function.Floor Class Reference
Classes
interface Compatible
Public Member Functions
Floor (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException
String toString ()
String getName ()
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
Returns the largest (closest to positive infinity) double/float value that is not greater than the argument and is equal to a mathematical integer.
Author
Klaus Meffert
Since
3.3.4
Definition at line 24 of file Floor.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Floor.Floor (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 29 of file Floor.java.
Referenced by org.jgap.gp.function.Floor.clone().
Member Function Documentation
Object org.jgap.gp.function.Floor.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 73 of file Floor.java.
References org.jgap.gp.function.Floor.Floor(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.CommandGene.getReturnType().
double org.jgap.gp.function.Floor.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 53 of file Floor.java.
float org.jgap.gp.function.Floor.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 48 of file Floor.java.
Object org.jgap.gp.function.Floor.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 58 of file Floor.java.
String org.jgap.gp.function.Floor.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.3.4
Definition at line 44 of file Floor.java.
String org.jgap.gp.function.Floor.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 34 of file Floor.java.
Member Data Documentation
final String org.jgap.gp.function.Floor.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file Floor.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Floor.java