org.jgap.distr.grid.wan.WANUtils Class Reference
Public Member Functions
WANUtils ()
Static Public Member Functions
static String outputRequestInformation (ReceivedPacket a_packet)
static String outputRequestInformation (RequestInformation a_info)
static String outputResultInformation (ReceivedPacket a_packet)
static String outputResultInformation (ResultInformation a_info)
static String getFitnessString (JGAPResultGP res)
static String outputInformation (MasterInfo worker, String postFix)
static IGPProgram getFittest (JGAPResultGP a_res)
static double getFitnessValue (IGPProgram a_prog)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Detailed Description
WAN Utilities.
Author
Klaus Meffert
Since
3.3.4
Definition at line 25 of file WANUtils.java.
Constructor & Destructor Documentation
org.jgap.distr.grid.wan.WANUtils.WANUtils () [inline]
Definition at line 29 of file WANUtils.java.
Member Function Documentation
static String org.jgap.distr.grid.wan.WANUtils.getFitnessString (JGAPResultGP res) [inline], [static]
Definition at line 131 of file WANUtils.java.
References org.jgap.distr.grid.wan.WANUtils.getFitnessValue().
Referenced by org.jgap.distr.grid.wan.WANUtils.outputResultInformation().
static double org.jgap.distr.grid.wan.WANUtils.getFitnessValue (IGPProgram a_prog) [inline], [static]
Definition at line 171 of file WANUtils.java.
References org.jgap.gp.GPFitnessFunction.NO_FITNESS_VALUE.
Referenced by org.jgap.distr.grid.wan.WANUtils.getFitnessString().
static IGPProgram org.jgap.distr.grid.wan.WANUtils.getFittest (JGAPResultGP a_res) [inline], [static]
Definition at line 158 of file WANUtils.java.
static String org.jgap.distr.grid.wan.WANUtils.outputInformation (MasterInfo worker, String postFix) [inline], [static]
Definition at line 153 of file WANUtils.java.
Referenced by org.jgap.distr.grid.wan.WANUtils.outputRequestInformation(), and org.jgap.distr.grid.wan.WANUtils.outputResultInformation().
static String org.jgap.distr.grid.wan.WANUtils.outputRequestInformation (ReceivedPacket a_packet) [inline], [static]
Definition at line 32 of file WANUtils.java.
References org.jgap.distr.grid.wan.ReceivedPacket.getData(), and org.jgap.distr.grid.wan.WANUtils.outputInformation().
static String org.jgap.distr.grid.wan.WANUtils.outputRequestInformation (RequestInformation a_info) [inline], [static]
Definition at line 47 of file WANUtils.java.
References org.jgap.distr.grid.wan.RequestInformation.getRequestDate().
static String org.jgap.distr.grid.wan.WANUtils.outputResultInformation (ReceivedPacket a_packet) [inline], [static]
Definition at line 73 of file WANUtils.java.
References org.jgap.distr.grid.wan.ReceivedPacket.getData(), org.jgap.distr.grid.wan.WANUtils.getFitnessString(), and org.jgap.distr.grid.wan.WANUtils.outputInformation().
static String org.jgap.distr.grid.wan.WANUtils.outputResultInformation (ResultInformation a_info) [inline], [static]
Definition at line 93 of file WANUtils.java.
References org.jgap.distr.grid.wan.ResultInformation.getResponseDate().
Member Data Documentation
final String org.jgap.distr.grid.wan.WANUtils.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file WANUtils.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/distr/grid/wan/WANUtils.java