org.jgap.impl.DefaultCloneHandlerTest Class Reference
Classes
class MyAppDataForTesting
class MyClassForTesting
class MyCloneHandlerForTesting
Public Member Functions
void testIsHandlerFor_0 () throws Exception
void testIsHandlerFor_1 () throws Exception
void testIsHandlerFor_2 () throws Exception
void testIsHandlerFor_3 () throws Exception
void testPerform_1 () throws Exception
void testPerform_2 () throws Exception
void testPerform_3 () throws Exception
void testPerform_4 () throws Exception
void testPerform_5 () throws Exception
void testPerform_6 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.8 $`
Additional Inherited Members
Detailed Description
Tests the DefaultCloneHandler class.
Author
Klaus Meffert
Since
2.6
Definition at line 23 of file DefaultCloneHandlerTest.java.
Member Function Documentation
static Test org.jgap.impl.DefaultCloneHandlerTest.suite () [inline], [static]
Definition at line 28 of file DefaultCloneHandlerTest.java.
void org.jgap.impl.DefaultCloneHandlerTest.testIsHandlerFor_0 () throws Exception [inline]
Handler implementing Cloneable without clone() method.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 40 of file DefaultCloneHandlerTest.java.
References org.jgap.IHandler.isHandlerFor().
void org.jgap.impl.DefaultCloneHandlerTest.testIsHandlerFor_1 () throws Exception [inline]
Handler not implementing Cloneable.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 53 of file DefaultCloneHandlerTest.java.
References org.jgap.IHandler.isHandlerFor().
void org.jgap.impl.DefaultCloneHandlerTest.testIsHandlerFor_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 65 of file DefaultCloneHandlerTest.java.
References org.jgap.IHandler.isHandlerFor().
void org.jgap.impl.DefaultCloneHandlerTest.testIsHandlerFor_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 78 of file DefaultCloneHandlerTest.java.
References org.jgap.IHandler.isHandlerFor().
void org.jgap.impl.DefaultCloneHandlerTest.testPerform_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 90 of file DefaultCloneHandlerTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.IHandler.perform().
void org.jgap.impl.DefaultCloneHandlerTest.testPerform_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 105 of file DefaultCloneHandlerTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.IHandler.perform().
void org.jgap.impl.DefaultCloneHandlerTest.testPerform_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 120 of file DefaultCloneHandlerTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.IHandler.perform().
void org.jgap.impl.DefaultCloneHandlerTest.testPerform_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 134 of file DefaultCloneHandlerTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.IHandler.perform().
void org.jgap.impl.DefaultCloneHandlerTest.testPerform_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 148 of file DefaultCloneHandlerTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.IHandler.perform().
void org.jgap.impl.DefaultCloneHandlerTest.testPerform_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 162 of file DefaultCloneHandlerTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.IHandler.perform().
Member Data Documentation
final String org.jgap.impl.DefaultCloneHandlerTest.CVS_REVISION = `$Revision: 1.8 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file DefaultCloneHandlerTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/DefaultCloneHandlerTest.java