examples.energy.CoinsEnergyFitnessFunction Class Reference
Public Member Functions
CoinsEnergyFitnessFunction (int a_targetAmount, double a_maxWeight)
double evaluate (IChromosome a_subject)
Static Public Member Functions
static int amountOfChange (IChromosome a_potentialSolution)
static int getNumberOfCoinsAtGene (IChromosome a_potentialSolution, int a_position)
static int getTotalNumberOfCoins (IChromosome a_potentialsolution)
static double getTotalWeight (IChromosome a_potentialSolution)
Static Public Attributes
static final int MAX_BOUND = 10000
static final double MAX_WEIGHT = 500
Protected Member Functions
double changeDifferenceBonus (double a_maxFitness, int a_changeDifference)
double computeCoinNumberPenalty (double a_maxFitness, int a_coins)
double computeWeightPenalty (double a_maxFitness, double a_weight)
Private Attributes
final int m_targetAmount
final double m_maxWeight
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.5 $`
static final double ZERO_DIFFERENCE_FITNESS = Math.sqrt(MAX_BOUND)
Detailed Description
Sample fitness function for the CoinsEnergy example. Adapted from examples.MinimizingMakeChangeFitnessFunction
Author
Klaus Meffert
Since
2.4
Definition at line 21 of file CoinsEnergyFitnessFunction.java.
Constructor & Destructor Documentation
examples.energy.CoinsEnergyFitnessFunction.CoinsEnergyFitnessFunction (int a_targetAmount, double a_maxWeight) [inline]
Definition at line 35 of file CoinsEnergyFitnessFunction.java.
References examples.energy.CoinsEnergyFitnessFunction.m_maxWeight, examples.energy.CoinsEnergyFitnessFunction.m_targetAmount, examples.energy.CoinsEnergyFitnessFunction.MAX_BOUND, and examples.energy.CoinsEnergyFitnessFunction.MAX_WEIGHT.
Member Function Documentation
static int examples.energy.CoinsEnergyFitnessFunction.amountOfChange (IChromosome a_potentialSolution) [inline], [static]
Calculates the total amount of change (in cents) represented by the given potential solution and returns that amount.
Parameters
a_potentialSolution the potential solution to evaluate
Returns
the total amount of change (in cents) represented by the given solution
Author
Neil Rotstan
Since
1.0
Definition at line 195 of file CoinsEnergyFitnessFunction.java.
References examples.energy.CoinsEnergyFitnessFunction.getNumberOfCoinsAtGene().
Referenced by examples.energy.CoinsEnergyFitnessFunction.evaluate().
double examples.energy.CoinsEnergyFitnessFunction.changeDifferenceBonus (double a_maxFitness, int a_changeDifference) [inline], [protected]
Bonus calculation of fitness value.
Parameters
a_maxFitness maximum fitness value appliable
a_changeDifference change difference in coins for the coins problem
Returns
bonus for given change difference
Author
Klaus Meffert
Since
2.3
Definition at line 145 of file CoinsEnergyFitnessFunction.java.
Referenced by examples.energy.CoinsEnergyFitnessFunction.evaluate().
double examples.energy.CoinsEnergyFitnessFunction.computeCoinNumberPenalty (double a_maxFitness, int a_coins) [inline], [protected]
Calculates the penalty to apply to the fitness value based on the ammount of coins in the solution
Parameters
a_maxFitness maximum fitness value allowed
a_coins number of coins in the solution
Returns
penalty for the fitness value base on the number of coins
Author
John Serri
Since
2.4
Definition at line 168 of file CoinsEnergyFitnessFunction.java.
Referenced by examples.energy.CoinsEnergyFitnessFunction.evaluate().
double examples.energy.CoinsEnergyFitnessFunction.computeWeightPenalty (double a_maxFitness, double a_weight) [inline], [protected]
Parameters
a_maxFitness the maximum fitness value allowed
a_weight the coins weight of the current solution
Returns
the penalty computed
Author
Klaus Meffert
Since
2.4
Definition at line 269 of file CoinsEnergyFitnessFunction.java.
Referenced by examples.energy.CoinsEnergyFitnessFunction.evaluate().
double examples.energy.CoinsEnergyFitnessFunction.evaluate (IChromosome a_subject) [inline]
Determine the fitness of the given Chromosome instance. The higher the return value, the more fit the instance. This method should always return the same fitness value for two equivalent Chromosome instances.
Parameters
a_subject the Chromosome instance to evaluate
Returns
positive double reflecting the fitness rating of the given Chromosome
Since
2.0 (until 1.1: return type int)
Author
Neil Rotstan, Klaus Meffert, John Serri
Definition at line 62 of file CoinsEnergyFitnessFunction.java.
References examples.energy.CoinsEnergyFitnessFunction.amountOfChange(), examples.energy.CoinsEnergyFitnessFunction.changeDifferenceBonus(), examples.energy.CoinsEnergyFitnessFunction.computeCoinNumberPenalty(), examples.energy.CoinsEnergyFitnessFunction.computeWeightPenalty(), examples.energy.CoinsEnergyFitnessFunction.getTotalNumberOfCoins(), examples.energy.CoinsEnergyFitnessFunction.getTotalWeight(), examples.energy.CoinsEnergyFitnessFunction.m_maxWeight, examples.energy.CoinsEnergyFitnessFunction.m_targetAmount, and examples.energy.CoinsEnergyFitnessFunction.MAX_BOUND.
static int examples.energy.CoinsEnergyFitnessFunction.getNumberOfCoinsAtGene (IChromosome a_potentialSolution, int a_position) [inline], [static]
Retrieves the number of coins represented by the given potential solution at the given gene position.
Parameters
a_potentialSolution the potential solution to evaluate
a_position the gene position to evaluate
Returns
the number of coins represented by the potential solution at the given gene position
Author
Neil Rotstan
Since
1.0
Definition at line 216 of file CoinsEnergyFitnessFunction.java.
Referenced by examples.energy.CoinsEnergyFitnessFunction.amountOfChange(), examples.energy.CoinsEnergyFitnessFunction.getTotalNumberOfCoins(), and examples.energy.CoinsEnergyFitnessFunction.getTotalWeight().
static int examples.energy.CoinsEnergyFitnessFunction.getTotalNumberOfCoins (IChromosome a_potentialsolution) [inline], [static]
Returns the total number of coins represented by all of the genes in the given potential solution.
Parameters
a_potentialsolution the potential solution to evaluate
Returns
total number of coins represented by the given Chromosome
Author
Neil Rotstan
Since
2.4
Definition at line 233 of file CoinsEnergyFitnessFunction.java.
References examples.energy.CoinsEnergyFitnessFunction.getNumberOfCoinsAtGene().
Referenced by examples.energy.CoinsEnergyFitnessFunction.evaluate(), and examples.energy.CoinsEnergy.makeChangeForAmount().
static double examples.energy.CoinsEnergyFitnessFunction.getTotalWeight (IChromosome a_potentialSolution) [inline], [static]
Returns the total weight of all coins.
Parameters
a_potentialSolution the potential solution to evaluate
Returns
total weight of all coins
Author
Klaus Meffert
Since
2.4
Definition at line 251 of file CoinsEnergyFitnessFunction.java.
References examples.energy.CoinsEnergyFitnessFunction.getNumberOfCoinsAtGene().
Referenced by examples.energy.CoinsEnergyFitnessFunction.evaluate().
Member Data Documentation
final String examples.energy.CoinsEnergyFitnessFunction.CVS_REVISION = `$Revision: 1.5 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file CoinsEnergyFitnessFunction.java.
final double examples.energy.CoinsEnergyFitnessFunction.m_maxWeight [private]
Definition at line 28 of file CoinsEnergyFitnessFunction.java.
Referenced by examples.energy.CoinsEnergyFitnessFunction.CoinsEnergyFitnessFunction(), and examples.energy.CoinsEnergyFitnessFunction.evaluate().
final int examples.energy.CoinsEnergyFitnessFunction.m_targetAmount [private]
Definition at line 26 of file CoinsEnergyFitnessFunction.java.
Referenced by examples.energy.CoinsEnergyFitnessFunction.CoinsEnergyFitnessFunction(), and examples.energy.CoinsEnergyFitnessFunction.evaluate().
final int examples.energy.CoinsEnergyFitnessFunction.MAX_BOUND = 10000 [static]
Definition at line 30 of file CoinsEnergyFitnessFunction.java.
Referenced by examples.energy.CoinsEnergyFitnessFunction.CoinsEnergyFitnessFunction(), and examples.energy.CoinsEnergyFitnessFunction.evaluate().
final double examples.energy.CoinsEnergyFitnessFunction.MAX_WEIGHT = 500 [static]
Definition at line 31 of file CoinsEnergyFitnessFunction.java.
Referenced by examples.energy.CoinsEnergyFitnessFunction.CoinsEnergyFitnessFunction().
final double examples.energy.CoinsEnergyFitnessFunction.ZERO_DIFFERENCE_FITNESS = Math.sqrt(MAX_BOUND) [static], [private]
Definition at line 33 of file CoinsEnergyFitnessFunction.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/energy/CoinsEnergyFitnessFunction.java