org.jgap.gp.impl.DeltaGPFitnessEvaluator Class Reference
Public Member Functions
boolean isFitter (final double a_fitness_value1, final double a_fitness_value2)
boolean isFitter (IGPProgram a_prog1, IGPProgram a_prog2)
boolean equals (Object a_object)
int compareTo (Object a_object)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
Fitness evaluator taking input as delta values. Thus a lower value is seen as fitter than a higher number.
Author
Klaus Meffert
Since
3.1
Definition at line 21 of file DeltaGPFitnessEvaluator.java.
Member Function Documentation
Object org.jgap.gp.impl.DeltaGPFitnessEvaluator.clone () [inline]
Returns
deep clone of this instance
Author
Klaus Meffert
Since
3.3.3
Definition at line 81 of file DeltaGPFitnessEvaluator.java.
int org.jgap.gp.impl.DeltaGPFitnessEvaluator.compareTo (Object a_object) [inline]
Definition at line 70 of file DeltaGPFitnessEvaluator.java.
boolean org.jgap.gp.impl.DeltaGPFitnessEvaluator.equals (Object a_object) [inline]
Definition at line 61 of file DeltaGPFitnessEvaluator.java.
boolean org.jgap.gp.impl.DeltaGPFitnessEvaluator.isFitter (final double a_fitness_value1, final double a_fitness_value2) [inline]
Compares the first given fitness value with the second and returns true if the first one is smaller than the second one. Otherwise returns false.
Parameters
a_fitness_value1 first fitness value
a_fitness_value2 second fitness value
Returns
true: first fitness value greater than second
Author
Klaus Meffert
Since
3.1
Definition at line 37 of file DeltaGPFitnessEvaluator.java.
Referenced by org.jgap.gp.impl.DeltaGPFitnessEvaluator.isFitter().
boolean org.jgap.gp.impl.DeltaGPFitnessEvaluator.isFitter (IGPProgram a_prog1, IGPProgram a_prog2) [inline]
Implements org.jgap.gp.IGPFitnessEvaluator.
Definition at line 53 of file DeltaGPFitnessEvaluator.java.
References org.jgap.gp.IGPProgram.getFitnessValue(), and org.jgap.gp.impl.DeltaGPFitnessEvaluator.isFitter().
Member Data Documentation
final String org.jgap.gp.impl.DeltaGPFitnessEvaluator.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file DeltaGPFitnessEvaluator.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/impl/DeltaGPFitnessEvaluator.java