org.jgap.NaturalSelector Class Reference
Classes
class AgeFitnessValueComparator
class FitnessAgeValueComparator
class FitnessValueComparator
Public Member Functions
NaturalSelector ()
NaturalSelector (Configuration a_config)
Configuration getConfiguration ()
Protected Member Functions
abstract void add (IChromosome a_chromosomeToAdd)
Protected Attributes
Configuration m_config
IEvolutionMonitor m_monitor
boolean m_monitorActive
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.32 $`
Additional Inherited Members
Detailed Description
Abstract base implementation of interface INaturalSelector.
Author
Neil Rotstan
Klaus Meffert
Since
2.0
Definition at line 24 of file NaturalSelector.java.
Constructor & Destructor Documentation
org.jgap.NaturalSelector.NaturalSelector () [inline]
Default constructor
Author
Klaus Meffert
Since
3.3.2
Definition at line 41 of file NaturalSelector.java.
org.jgap.NaturalSelector.NaturalSelector (Configuration a_config) [inline]
Parameters
a_config the configuration to use
Author
Klaus Meffert
Since
3.0
Definition at line 51 of file NaturalSelector.java.
References org.jgap.NaturalSelector.getConfiguration(), org.jgap.NaturalSelector.m_config, org.jgap.NaturalSelector.m_monitor, and org.jgap.NaturalSelector.m_monitorActive.
Member Function Documentation
abstract void org.jgap.NaturalSelector.add (IChromosome a_chromosomeToAdd) [protected], [pure virtual]
Add a Chromosome instance to this selector's working pool of Chromosomes.
Parameters
a_chromosomeToAdd the specimen to add to the pool
Author
Neil Rotstan
Since
1.0
Configuration org.jgap.NaturalSelector.getConfiguration () [inline]
Returns
the (immutable) configuration to use
Author
Klaus Meffert
Since
3.0
Definition at line 68 of file NaturalSelector.java.
References org.jgap.NaturalSelector.m_config.
Referenced by org.jgap.impl.BestChromosomesSelector.add(), org.jgap.impl.StandardPostSelector.clone(), org.jgap.impl.BestChromosomesSelector.clone(), org.jgap.impl.WeightedRouletteSelector.clone(), org.jgap.NaturalSelector.FitnessValueComparator.compare(), org.jgap.NaturalSelector.AgeFitnessValueComparator.compare(), org.jgap.NaturalSelector.FitnessAgeValueComparator.compare(), org.jgap.impl.ThresholdSelector.FitnessValueComparator.compare(), org.jgap.impl.TournamentSelector.FitnessValueComparator.compare(), org.jgap.NaturalSelector.NaturalSelector(), org.jgap.NaturalSelectorExt.selectChromosome(), org.jgap.impl.ThresholdSelector.selectChromosomes(), org.jgap.impl.TournamentSelector.selectChromosomes(), org.jgap.impl.BestChromosomesSelector.selectChromosomes(), org.jgap.impl.WeightedRouletteSelector.selectChromosomes(), and org.jgap.impl.WeightedRouletteSelector.spinWheel().
Member Data Documentation
final String org.jgap.NaturalSelector.CVS_REVISION = `$Revision: 1.32 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file NaturalSelector.java.
Configuration org.jgap.NaturalSelector.m_config [protected]
Definition at line 29 of file NaturalSelector.java.
Referenced by org.jgap.NaturalSelector.getConfiguration(), and org.jgap.NaturalSelector.NaturalSelector().
IEvolutionMonitor org.jgap.NaturalSelector.m_monitor [protected]
Definition at line 31 of file NaturalSelector.java.
Referenced by org.jgap.NaturalSelector.NaturalSelector().
boolean org.jgap.NaturalSelector.m_monitorActive [protected]
Definition at line 33 of file NaturalSelector.java.
Referenced by org.jgap.NaturalSelector.NaturalSelector(), org.jgap.NaturalSelectorExt.selectChromosome(), org.jgap.impl.BestChromosomesSelector.selectChromosomes(), and org.jgap.impl.WeightedRouletteSelector.selectChromosomes().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/NaturalSelector.java