org.jgap.audit.EvolutionEvaluator Class Reference
Public Member Functions
EvolutionEvaluator (PopulationHistoryIndexed a_monitorData)
void evaluate ()
Private Member Functions
Map< IChromosome, Map< Integer,
*
List< IChromosome > > > trackChromosomes (Map< Integer, Map > a_data)
Map< IChromosome, Map< Integer,
*
List< IChromosome > > > trackChromosomes (Map< Integer, Map > a_data, Population a_pop)
Map< String, Map< IChromosome,
*
List< Integer > > > gatherChromosomesIDs (Map< Integer, Map > a_data)
Private Attributes
PopulationHistoryIndexed m_monitorData
List< Integer > evolutionIndexes
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Detailed Description
Evaluates evolution progress thas has previously been tracked by EvolutionMonitor (or a similar instance). This class regards a complete evolution, not just a single round. This is an optional way, another would be to just gather data per round and then display or evaluate the round-specific data. This class considers global (complete evolution) data because computations are executed on this data, like tracking chromosomes, evaluating the progress of selectors or genetic operators, etc.
Author
Klaus Meffert
Since
3.5
Definition at line 32 of file EvolutionEvaluator.java.
Constructor & Destructor Documentation
org.jgap.audit.EvolutionEvaluator.EvolutionEvaluator (PopulationHistoryIndexed a_monitorData) [inline]
Definition at line 40 of file EvolutionEvaluator.java.
References org.jgap.audit.EvolutionEvaluator.evolutionIndexes, and org.jgap.audit.EvolutionEvaluator.m_monitorData.
Member Function Documentation
void org.jgap.audit.EvolutionEvaluator.evaluate () [inline]
Todo
Todo use chromIDs and chromTrack
Todo
Todo
Definition at line 48 of file EvolutionEvaluator.java.
References org.jgap.audit.EvolutionEvaluator.gatherChromosomesIDs(), and org.jgap.audit.EvolutionEvaluator.trackChromosomes().
Map<String, Map<IChromosome, List<Integer> > > org.jgap.audit.EvolutionEvaluator.gatherChromosomesIDs (Map< Integer, Map > a_data) [inline], [private]
For all chromosomes: Gather their IDs and the list of indexes of the evolution rounds they appeared in. Normally, a chromosome with a specific unique ID just appears within one single generation. The reason is, that, normally, in selection and genetic operator, the chromosomes' IDs change, because the chromosomes are cloned.
Parameters
a_data monitoring data
Returns
result of investigation
Definition at line 197 of file EvolutionEvaluator.java.
Referenced by org.jgap.audit.EvolutionEvaluator.evaluate().
Map<IChromosome, Map<Integer, List<IChromosome> > > org.jgap.audit.EvolutionEvaluator.trackChromosomes (Map< Integer, Map > a_data) [inline], [private]
Tracks the originator chain of each chromosome in the final population. The originator chain potentially begins with the first generation. A chromosome could virtually have as many originators as there are evolutions (minus one), or it could have zero originators. The latter case means the chromosome was just created in the final population.
Parameters
a_data population (evolution) data
Returns
the result of the investigation
Author
Klaus Meffert
Since
3.5
Definition at line 116 of file EvolutionEvaluator.java.
References org.jgap.audit.EvolutionMonitor.CONTEXT_END_OF_CYCLE.
Referenced by org.jgap.audit.EvolutionEvaluator.evaluate().
Map<IChromosome, Map<Integer, List<IChromosome> > > org.jgap.audit.EvolutionEvaluator.trackChromosomes (Map< Integer, Map > a_data, Population a_pop) [inline], [private]
Parameters
a_data Map
a_pop Population
Returns
the result of the investigation
Author
Klaus Meffert
Since
3.5
Definition at line 135 of file EvolutionEvaluator.java.
References org.jgap.audit.EvolutionMonitor.CONTEXT_END_OF_CYCLE.
Member Data Documentation
final String org.jgap.audit.EvolutionEvaluator.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 34 of file EvolutionEvaluator.java.
List<Integer> org.jgap.audit.EvolutionEvaluator.evolutionIndexes [private]
Definition at line 38 of file EvolutionEvaluator.java.
Referenced by org.jgap.audit.EvolutionEvaluator.EvolutionEvaluator().
PopulationHistoryIndexed org.jgap.audit.EvolutionEvaluator.m_monitorData [private]
Definition at line 36 of file EvolutionEvaluator.java.
Referenced by org.jgap.audit.EvolutionEvaluator.EvolutionEvaluator().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/audit/EvolutionEvaluator.java