org.jgap.event.GeneticEventTest Class Reference
Public Member Functions
void testConstruct_0 ()
void testConstruct_1 ()
void testConstruct_2 ()
void testConstruct_3 ()
void testGetEventName_0 ()
void testGENOTYPE_EVOLVED_EVENT_0 ()
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.8 $`
Additional Inherited Members
Detailed Description
Tests the GeneticEvent class.
Author
Klaus Meffert
Since
1.1
Definition at line 23 of file GeneticEventTest.java.
Member Function Documentation
static Test org.jgap.event.GeneticEventTest.suite () [inline], [static]
Definition at line 28 of file GeneticEventTest.java.
void org.jgap.event.GeneticEventTest.testConstruct_0 () [inline]
Author
Klaus Meffert
Since
1.1
Definition at line 37 of file GeneticEventTest.java.
void org.jgap.event.GeneticEventTest.testConstruct_1 () [inline]
Author
Klaus Meffert
Since
1.1
Definition at line 51 of file GeneticEventTest.java.
void org.jgap.event.GeneticEventTest.testConstruct_2 () [inline]
Author
Klaus Meffert
Since
3.0
Definition at line 60 of file GeneticEventTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.event.GeneticEventTest.testConstruct_3 () [inline]
Author
Klaus Meffert
Since
3.0
Definition at line 69 of file GeneticEventTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.event.GeneticEventTest.testGENOTYPE_EVOLVED_EVENT_0 () [inline]
Author
Klaus Meffert
Since
1.1
Definition at line 88 of file GeneticEventTest.java.
References org.jgap.event.GeneticEvent.GENOTYPE_EVOLVED_EVENT.
void org.jgap.event.GeneticEventTest.testGetEventName_0 () [inline]
Author
Klaus Meffert
Since
1.1
Definition at line 79 of file GeneticEventTest.java.
References org.jgap.JGAPTestCase.assertEquals().
Member Data Documentation
final String org.jgap.event.GeneticEventTest.CVS_REVISION = `$Revision: 1.8 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file GeneticEventTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/event/GeneticEventTest.java