org.jgap.distr.ProblemTest Class Reference
Public Member Functions
void testConstruct_0 ()
void testConstruct_1 ()
void testConstruct_2 ()
void testConstruct_3 () throws Exception
void testGetID_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Additional Inherited Members
Detailed Description
Tests the Problem class.
Author
Klaus Meffert
Since
3.0
Definition at line 23 of file ProblemTest.java.
Member Function Documentation
static Test org.jgap.distr.ProblemTest.suite () [inline], [static]
Definition at line 28 of file ProblemTest.java.
void org.jgap.distr.ProblemTest.testConstruct_0 () [inline]
Author
Klaus Meffert
Since
3.0
Definition at line 37 of file ProblemTest.java.
void org.jgap.distr.ProblemTest.testConstruct_1 () [inline]
Author
Klaus Meffert
Since
3.0
Definition at line 51 of file ProblemTest.java.
void org.jgap.distr.ProblemTest.testConstruct_2 () [inline]
Author
Klaus Meffert
Since
3.0
Definition at line 65 of file ProblemTest.java.
void org.jgap.distr.ProblemTest.testConstruct_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 81 of file ProblemTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.distr.Problem.getChromosomes(), org.jgap.distr.Problem.getFitnessFunction(), and org.jgap.distr.Problem.getPopulationSize().
void org.jgap.distr.ProblemTest.testGetID_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 97 of file ProblemTest.java.
References org.jgap.distr.Problem.getID().
Member Data Documentation
final String org.jgap.distr.ProblemTest.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file ProblemTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/distr/ProblemTest.java