org.jgap.util.ClassKit Class Reference
Classes
class ExtensionsFilter
Static Public Member Functions
static void main (String[] args) throws Exception
static List find (final String a_tosubclassname)
static List find (final String a_pckname, final String a_tosubclassname) throws ClassNotFoundException
static List find (final String a_pckgname, final Class a_tosubclass)
static List find (final URL a_url, final String a_pckgname, final Class a_tosubclass)
static void findInJar (final List a_result, final URL a_url, Class a_tosubclass)
static boolean implementsInterface (final Class a_o, final Class a_clazz)
static boolean extendsClass (final Class a_o, final Class a_clazz)
static void getPlugins (final String a_directory)
static void addClasses (final Vector a_v, final File a_path, final String a_name)
static void addClassesJar (final Vector a_v, final File a_path)
static void addClassesFile (Vector a_v, final File a_path, final String a_name)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.10 $`
static transient Logger LOGGER = Logger.getLogger(ClassKit.class)
Detailed Description
Definition at line 19 of file ClassKit.java.
Member Function Documentation
static void org.jgap.util.ClassKit.addClasses (final Vector a_v, final File a_path, final String a_name) [inline], [static]
Definition at line 272 of file ClassKit.java.
References org.jgap.util.ClassKit.addClassesFile(), and org.jgap.util.ClassKit.addClassesJar().
Referenced by org.jgap.util.ClassKit.getPlugins().
static void org.jgap.util.ClassKit.addClassesFile (Vector a_v, final File a_path, final String a_name) [inline], [static]
Definition at line 299 of file ClassKit.java.
Referenced by org.jgap.util.ClassKit.addClasses().
static void org.jgap.util.ClassKit.addClassesJar (final Vector a_v, final File a_path) [inline], [static]
Definition at line 278 of file ClassKit.java.
Referenced by org.jgap.util.ClassKit.addClasses().
static boolean org.jgap.util.ClassKit.extendsClass (final Class a_o, final Class a_clazz) [inline], [static]
Definition at line 217 of file ClassKit.java.
Referenced by org.jgap.util.ClassKit.find(), and org.jgap.util.ClassKit.findInJar().
static List org.jgap.util.ClassKit.find (final String a_tosubclassname) [inline], [static]
Retrieves all the classes inheriting or implementing a given class in the currently loaded packages.
Parameters
a_tosubclassname the name of the class to inherit from
Returns
classes inheriting or implementing a given class in the currently loaded packages
See Also
http//www.javaworld.com/javaworld/javatips/jw-javatip113.html
Todo
Todo take care of abstract classes --> introduce parameter for that
Definition at line 51 of file ClassKit.java.
Referenced by org.jgap.util.ClassKit.find(), and org.jgap.util.ClassKit.main().
static List org.jgap.util.ClassKit.find (final String a_pckname, final String a_tosubclassname) throws ClassNotFoundException [inline], [static]
Display all the classes inheriting or implementing a given class in a given package.
Parameters
a_pckname the fully qualified name of the package
a_tosubclassname the name of the class to inherit from
Returns
classes inheriting or implementing a given class in a given package
Exceptions
ClassNotFoundException
See Also
http//www.javaworld.com/javaworld/javatips/jw-javatip113.html
Definition at line 82 of file ClassKit.java.
References org.jgap.util.ClassKit.find().
static List org.jgap.util.ClassKit.find (final String a_pckgname, final Class a_tosubclass) [inline], [static]
Display all the classes inheriting or implementing a given class in a given package.
Parameters
a_pckgname the fully qualified name of the package
a_tosubclass the Class object to inherit from See http//www.javaworld.com/javaworld/javatips/jw-javatip113.html
Definition at line 95 of file ClassKit.java.
References org.jgap.util.ClassKit.find().
static List org.jgap.util.ClassKit.find (final URL a_url, final String a_pckgname, final Class a_tosubclass) [inline], [static]
Definition at line 125 of file ClassKit.java.
References org.jgap.util.ClassKit.extendsClass(), org.jgap.util.ClassKit.findInJar(), and org.jgap.util.ClassKit.implementsInterface().
static void org.jgap.util.ClassKit.findInJar (final List a_result, final URL a_url, Class a_tosubclass) [inline], [static]
Definition at line 164 of file ClassKit.java.
References org.jgap.util.ClassKit.extendsClass(), and org.jgap.util.ClassKit.implementsInterface().
Referenced by org.jgap.util.ClassKit.find(), and org.jgap.util.ClassKit.main().
static void org.jgap.util.ClassKit.getPlugins (final String a_directory) [inline], [static]
Todo
Todo add input param: type (or list of types) to look for
Todo
Todo check if class assignable from given type
Definition at line 230 of file ClassKit.java.
References org.jgap.util.ClassKit.addClasses().
Referenced by org.jgap.util.ClassKit.main().
static boolean org.jgap.util.ClassKit.implementsInterface (final Class a_o, final Class a_clazz) [inline], [static]
Definition at line 205 of file ClassKit.java.
Referenced by org.jgap.util.ClassKit.find(), and org.jgap.util.ClassKit.findInJar().
static void org.jgap.util.ClassKit.main (String[] args) throws Exception [inline], [static]
Definition at line 25 of file ClassKit.java.
References org.jgap.util.ClassKit.find(), org.jgap.util.ClassKit.findInJar(), and org.jgap.util.ClassKit.getPlugins().
Member Data Documentation
final String org.jgap.util.ClassKit.CVS_REVISION = `$Revision: 1.10 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 21 of file ClassKit.java.
transient Logger org.jgap.util.ClassKit.LOGGER = Logger.getLogger(ClassKit.class) [static], [private]
Definition at line 23 of file ClassKit.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/util/ClassKit.java