org.jgap.gp.function.RandomGenerator Class Reference
Public Member Functions
RandomGenerator (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException
String toString ()
String getName ()
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
Returns a double/float value with a positive sign, greater than or equal to 0.0 and less than 1.0.
Author
Klaus Meffert
Since
3.3.4
Definition at line 24 of file RandomGenerator.java.
Constructor & Destructor Documentation
org.jgap.gp.function.RandomGenerator.RandomGenerator (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 29 of file RandomGenerator.java.
Referenced by org.jgap.gp.function.RandomGenerator.clone().
Member Function Documentation
Object org.jgap.gp.function.RandomGenerator.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 64 of file RandomGenerator.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.function.RandomGenerator.RandomGenerator().
double org.jgap.gp.function.RandomGenerator.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 52 of file RandomGenerator.java.
float org.jgap.gp.function.RandomGenerator.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 48 of file RandomGenerator.java.
String org.jgap.gp.function.RandomGenerator.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.3.4
Definition at line 44 of file RandomGenerator.java.
String org.jgap.gp.function.RandomGenerator.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 34 of file RandomGenerator.java.
Member Data Documentation
final String org.jgap.gp.function.RandomGenerator.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file RandomGenerator.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/RandomGenerator.java