examples.math.cmd.MathOperator Class Reference
Public Member Functions
MathOperator ()
MathOperator (Operand theLeft, Operand theRight)
void setLeftOperand (Operand theOp)
void setRightOperand (Operand theOp)
Operand getLeftOperand ()
Operand getRightOperand ()
double value ()
abstract Object clone ()
Private Attributes
Operand mLeftOperand
Operand mRightOperand
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.1 $`
Additional Inherited Members
Detailed Description
Base class for mathematical operators.
Author
Michael Grove
Since
3.4.2
Definition at line 18 of file MathOperator.java.
Constructor & Destructor Documentation
examples.math.cmd.MathOperator.MathOperator () [inline]
Definition at line 27 of file MathOperator.java.
examples.math.cmd.MathOperator.MathOperator (Operand theLeft, Operand theRight) [inline]
Definition at line 30 of file MathOperator.java.
References examples.math.cmd.MathOperator.mLeftOperand, and examples.math.cmd.MathOperator.mRightOperand.
Member Function Documentation
abstract Object examples.math.cmd.MathOperator.clone () [pure virtual]
Implemented in examples.math.cmd.AddOperator, examples.math.cmd.DivideOperator, examples.math.cmd.MinusOperator, and examples.math.cmd.MultiplyOperator.
Operand examples.math.cmd.MathOperator.getLeftOperand () [inline]
Implements examples.math.cmd.Operator.
Definition at line 43 of file MathOperator.java.
References examples.math.cmd.MathOperator.mLeftOperand.
Referenced by examples.math.cmd.DivideOperator.calcuate(), examples.math.cmd.MultiplyOperator.calcuate(), examples.math.cmd.MinusOperator.calcuate(), and examples.math.cmd.AddOperator.calcuate().
Operand examples.math.cmd.MathOperator.getRightOperand () [inline]
Implements examples.math.cmd.Operator.
Definition at line 47 of file MathOperator.java.
References examples.math.cmd.MathOperator.mRightOperand.
Referenced by examples.math.cmd.DivideOperator.calcuate(), examples.math.cmd.MultiplyOperator.calcuate(), examples.math.cmd.MinusOperator.calcuate(), and examples.math.cmd.AddOperator.calcuate().
void examples.math.cmd.MathOperator.setLeftOperand (Operand theOp) [inline]
Definition at line 35 of file MathOperator.java.
References examples.math.cmd.MathOperator.mLeftOperand.
void examples.math.cmd.MathOperator.setRightOperand (Operand theOp) [inline]
Definition at line 39 of file MathOperator.java.
References examples.math.cmd.MathOperator.mRightOperand.
double examples.math.cmd.MathOperator.value () [inline]
Implements examples.math.cmd.Operand.
Definition at line 51 of file MathOperator.java.
References examples.math.cmd.Operator.calcuate().
Member Data Documentation
final String examples.math.cmd.MathOperator.CVS_REVISION = `$Revision: 1.1 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 21 of file MathOperator.java.
Operand examples.math.cmd.MathOperator.mLeftOperand [private]
Definition at line 23 of file MathOperator.java.
Referenced by examples.math.cmd.MathOperator.getLeftOperand(), examples.math.cmd.MathOperator.MathOperator(), and examples.math.cmd.MathOperator.setLeftOperand().
Operand examples.math.cmd.MathOperator.mRightOperand [private]
Definition at line 25 of file MathOperator.java.
Referenced by examples.math.cmd.MathOperator.getRightOperand(), examples.math.cmd.MathOperator.MathOperator(), and examples.math.cmd.MathOperator.setRightOperand().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/math/cmd/MathOperator.java