org.jgap.audit.KeyedValuesTest Class Reference
Public Member Functions
void setUp ()
void testConstruct_0 () throws Exception
void testSetValue_0 () throws Exception
void testSetValue_1 () throws Exception
void testGetKeys_0 () throws Exception
void testGetValue_0 () throws Exception
void testGetKey_0 () throws Exception
void testGetKey_1 () throws Exception
void testGetKey_2 () throws Exception
void testGetValue_1 () throws Exception
void testGetValue_2 () throws Exception
void testGetValue_3 () throws Exception
void testClone_0 () throws Exception
void testEquals_0 () throws Exception
void testEquals_1 () throws Exception
void testHashcode_0 () throws Exception
void testGetIndex_0 () throws Exception
void testGetIndex_1 () throws Exception
void testGetIndex_2 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
Tests for KeyedValues class
Author
Klaus Meffert
Since
3.0
Definition at line 22 of file KeyedValuesTest.java.
Member Function Documentation
void org.jgap.audit.KeyedValuesTest.setUp () [inline]
Definition at line 27 of file KeyedValuesTest.java.
static Test org.jgap.audit.KeyedValuesTest.suite () [inline], [static]
Definition at line 31 of file KeyedValuesTest.java.
void org.jgap.audit.KeyedValuesTest.testClone_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 225 of file KeyedValuesTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.audit.KeyedValues.clone().
void org.jgap.audit.KeyedValuesTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 42 of file KeyedValuesTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.audit.KeyedValues.hashCode(), and org.jgap.audit.KeyedValues.size().
void org.jgap.audit.KeyedValuesTest.testEquals_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 248 of file KeyedValuesTest.java.
References org.jgap.audit.KeyedValues.equals().
void org.jgap.audit.KeyedValuesTest.testEquals_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 265 of file KeyedValuesTest.java.
References org.jgap.audit.KeyedValues.equals().
void org.jgap.audit.KeyedValuesTest.testGetIndex_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 298 of file KeyedValuesTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.audit.KeyedValues.getIndex().
void org.jgap.audit.KeyedValuesTest.testGetIndex_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 313 of file KeyedValuesTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.audit.KeyedValues.getIndex().
void org.jgap.audit.KeyedValuesTest.testGetIndex_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 328 of file KeyedValuesTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.audit.KeyedValues.getIndex().
void org.jgap.audit.KeyedValuesTest.testGetKey_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 137 of file KeyedValuesTest.java.
void org.jgap.audit.KeyedValuesTest.testGetKey_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 154 of file KeyedValuesTest.java.
References org.jgap.audit.KeyedValues.getKey().
void org.jgap.audit.KeyedValuesTest.testGetKey_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 168 of file KeyedValuesTest.java.
References org.jgap.audit.KeyedValues.getKey().
void org.jgap.audit.KeyedValuesTest.testGetKeys_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 93 of file KeyedValuesTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.audit.KeyedValuesTest.testGetValue_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 116 of file KeyedValuesTest.java.
References org.jgap.audit.KeyedValues.getValue().
void org.jgap.audit.KeyedValuesTest.testGetValue_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 181 of file KeyedValuesTest.java.
void org.jgap.audit.KeyedValuesTest.testGetValue_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 198 of file KeyedValuesTest.java.
References org.jgap.audit.KeyedValues.getValue().
void org.jgap.audit.KeyedValuesTest.testGetValue_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 212 of file KeyedValuesTest.java.
References org.jgap.audit.KeyedValues.getValue().
void org.jgap.audit.KeyedValuesTest.testHashcode_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 282 of file KeyedValuesTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.audit.KeyedValuesTest.testSetValue_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 55 of file KeyedValuesTest.java.
References org.jgap.audit.KeyedValues.getKey(), and org.jgap.audit.KeyedValues.getValue().
void org.jgap.audit.KeyedValuesTest.testSetValue_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 76 of file KeyedValuesTest.java.
References org.jgap.audit.KeyedValues.getValue().
Member Data Documentation
final String org.jgap.audit.KeyedValuesTest.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file KeyedValuesTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/audit/KeyedValuesTest.java