examples.gp.tictactoe.TransferBoardToMemory Class Reference
Public Member Functions
TransferBoardToMemory (final GPConfiguration a_conf, Board a_board, int a_startMemoryIndex) throws InvalidConfigurationException
TransferBoardToMemory (final GPConfiguration a_conf, Board a_board, int a_startMemoryIndex, int a_subReturnType) throws InvalidConfigurationException
String toString ()
String getName ()
void execute_void (ProgramChromosome c, int n, Object[] args)
Object clone ()
Private Attributes
Board m_board
int m_startMemoryIndex
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
Definition at line 17 of file TransferBoardToMemory.java.
Constructor & Destructor Documentation
examples.gp.tictactoe.TransferBoardToMemory.TransferBoardToMemory (final GPConfiguration a_conf, Board a_board, int a_startMemoryIndex) throws InvalidConfigurationException [inline]
Definition at line 26 of file TransferBoardToMemory.java.
Referenced by examples.gp.tictactoe.TransferBoardToMemory.clone().
examples.gp.tictactoe.TransferBoardToMemory.TransferBoardToMemory (final GPConfiguration a_conf, Board a_board, int a_startMemoryIndex, int a_subReturnType) throws InvalidConfigurationException [inline]
Definition at line 32 of file TransferBoardToMemory.java.
References examples.gp.tictactoe.TransferBoardToMemory.m_board, examples.gp.tictactoe.TransferBoardToMemory.m_startMemoryIndex, and org.jgap.gp.CommandGene.VoidClass.
Member Function Documentation
Object examples.gp.tictactoe.TransferBoardToMemory.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 83 of file TransferBoardToMemory.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getSubReturnType(), examples.gp.tictactoe.TransferBoardToMemory.m_board, examples.gp.tictactoe.TransferBoardToMemory.m_startMemoryIndex, and examples.gp.tictactoe.TransferBoardToMemory.TransferBoardToMemory().
void examples.gp.tictactoe.TransferBoardToMemory.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Executes the command.
Parameters
c ProgramChromosome
n ignored here
args ignored here
Author
Klaus Meffert
Since
3.2
Definition at line 64 of file TransferBoardToMemory.java.
References org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.getGPConfiguration(), examples.gp.tictactoe.Board.HEIGHT, examples.gp.tictactoe.TransferBoardToMemory.m_startMemoryIndex, and examples.gp.tictactoe.Board.WIDTH.
String examples.gp.tictactoe.TransferBoardToMemory.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 50 of file TransferBoardToMemory.java.
References examples.gp.tictactoe.TransferBoardToMemory.m_startMemoryIndex.
String examples.gp.tictactoe.TransferBoardToMemory.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 40 of file TransferBoardToMemory.java.
References examples.gp.tictactoe.TransferBoardToMemory.m_startMemoryIndex.
Member Data Documentation
final String examples.gp.tictactoe.TransferBoardToMemory.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 20 of file TransferBoardToMemory.java.
Board examples.gp.tictactoe.TransferBoardToMemory.m_board [private]
Definition at line 22 of file TransferBoardToMemory.java.
Referenced by examples.gp.tictactoe.TransferBoardToMemory.clone(), and examples.gp.tictactoe.TransferBoardToMemory.TransferBoardToMemory().
int examples.gp.tictactoe.TransferBoardToMemory.m_startMemoryIndex [private]
Definition at line 24 of file TransferBoardToMemory.java.
Referenced by examples.gp.tictactoe.TransferBoardToMemory.clone(), examples.gp.tictactoe.TransferBoardToMemory.execute_void(), examples.gp.tictactoe.TransferBoardToMemory.getName(), examples.gp.tictactoe.TransferBoardToMemory.toString(), and examples.gp.tictactoe.TransferBoardToMemory.TransferBoardToMemory().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/tictactoe/TransferBoardToMemory.java