org.jgap.data.config.ConfigWriter Class Reference
Public Member Functions
void write (final IConfigInfo a_cInfo)
Static Public Member Functions
static ConfigWriter getInstance ()
Private Member Functions
ConfigWriter ()
Private Attributes
Properties m_config
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.8 $`
static ConfigWriter m_cWriter
Detailed Description
This class is a Singleton that generates a properties file from classes implementing IConfigInfo.
Author
Siddhartha Azad
Since
2.3
Definition at line 23 of file ConfigWriter.java.
Constructor & Destructor Documentation
org.jgap.data.config.ConfigWriter.ConfigWriter () [inline], [private]
Constructor for the ConfigWriter Singleton
Author
Siddhartha Azad
Since
2.3
Definition at line 55 of file ConfigWriter.java.
References org.jgap.data.config.ConfigWriter.m_config.
Referenced by org.jgap.data.config.ConfigWriter.getInstance().
Member Function Documentation
static ConfigWriter org.jgap.data.config.ConfigWriter.getInstance () [inline], [static]
Method to create and access the Singleton ConfigWriter instance.
Returns
a ConfigWriter Singleton instance.
Author
Siddhartha Azad
Since
2.3
Definition at line 42 of file ConfigWriter.java.
References org.jgap.data.config.ConfigWriter.ConfigWriter(), and org.jgap.data.config.ConfigWriter.m_cWriter.
void org.jgap.data.config.ConfigWriter.write (final IConfigInfo a_cInfo) [inline]
Persist the configuration information as selected by the user.
Parameters
a_cInfo configuration Information to persist
Author
Siddhartha Azad
Since
2.3
Definition at line 66 of file ConfigWriter.java.
References org.jgap.data.config.IConfigInfo.getFileName().
Member Data Documentation
final String org.jgap.data.config.ConfigWriter.CVS_REVISION = `$Revision: 1.8 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file ConfigWriter.java.
Properties org.jgap.data.config.ConfigWriter.m_config [private]
Definition at line 33 of file ConfigWriter.java.
Referenced by org.jgap.data.config.ConfigWriter.ConfigWriter().
ConfigWriter org.jgap.data.config.ConfigWriter.m_cWriter [static], [private]
Singleton instance of ConfigWriter
Definition at line 30 of file ConfigWriter.java.
Referenced by org.jgap.data.config.ConfigWriter.getInstance().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/data/config/ConfigWriter.java