org.jgap.impl.DefaultInitializerTest Class Reference
Classes
class MyInitializerForTesting
Public Member Functions
void testIsHandlerFor_0 () throws Exception
void testPerform_0 () throws Exception
void testPerform_1 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
Tests the DefaultInitializer class.
Author
Klaus Meffert
Since
2.6
Definition at line 21 of file DefaultInitializerTest.java.
Member Function Documentation
static Test org.jgap.impl.DefaultInitializerTest.suite () [inline], [static]
Definition at line 26 of file DefaultInitializerTest.java.
void org.jgap.impl.DefaultInitializerTest.testIsHandlerFor_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 37 of file DefaultInitializerTest.java.
References org.jgap.IHandler.isHandlerFor().
void org.jgap.impl.DefaultInitializerTest.testPerform_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus meffert
Since
2.6
Definition at line 55 of file DefaultInitializerTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DefaultInitializerTest.testPerform_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus meffert
Since
2.6
Definition at line 74 of file DefaultInitializerTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.IHandler.perform().
Member Data Documentation
final String org.jgap.impl.DefaultInitializerTest.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file DefaultInitializerTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/DefaultInitializerTest.java