org.jgap.util.FileKitTest Class Reference
Public Member Functions
void testAddFilename_0 () throws Exception
void testAddFilename_1 () throws Exception
void testAddFilename_2 () throws Exception
void testAddFilename_3 () throws Exception
void testAddFilename_4 () throws Exception
void testAddFilename_5 () throws Exception
void testAddFilename_6 () throws Exception
void testAddFilename_7 () throws Exception
void testAddFilename_8 () throws Exception
void testAddFilename_9 () throws Exception
void testAddFilename_10 () throws Exception
void testAddFilename_11 () throws Exception
Static Public Member Functions
static Test suite ()
Private Member Functions
String replaceSeparator (String a_s, String a_orig)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.1 $`
Additional Inherited Members
Detailed Description
Tests the FileKit class.
Author
Klaus Meffert
Since
3.3.4
Definition at line 22 of file FileKitTest.java.
Member Function Documentation
String org.jgap.util.FileKitTest.replaceSeparator (String a_s, String a_orig) [inline], [private]
Definition at line 115 of file FileKitTest.java.
References org.jgap.util.FileKit.fileseparator.
Referenced by org.jgap.util.FileKitTest.testAddFilename_0(), org.jgap.util.FileKitTest.testAddFilename_1(), org.jgap.util.FileKitTest.testAddFilename_10(), org.jgap.util.FileKitTest.testAddFilename_11(), org.jgap.util.FileKitTest.testAddFilename_2(), org.jgap.util.FileKitTest.testAddFilename_3(), org.jgap.util.FileKitTest.testAddFilename_4(), org.jgap.util.FileKitTest.testAddFilename_5(), org.jgap.util.FileKitTest.testAddFilename_6(), org.jgap.util.FileKitTest.testAddFilename_7(), org.jgap.util.FileKitTest.testAddFilename_8(), and org.jgap.util.FileKitTest.testAddFilename_9().
static Test org.jgap.util.FileKitTest.suite () [inline], [static]
Definition at line 27 of file FileKitTest.java.
void org.jgap.util.FileKitTest.testAddFilename_0 () throws Exception [inline]
Definition at line 31 of file FileKitTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.util.FileKitTest.replaceSeparator().
void org.jgap.util.FileKitTest.testAddFilename_1 () throws Exception [inline]
Definition at line 38 of file FileKitTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.util.FileKitTest.replaceSeparator().
void org.jgap.util.FileKitTest.testAddFilename_10 () throws Exception [inline]
Definition at line 101 of file FileKitTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.util.FileKitTest.replaceSeparator().
void org.jgap.util.FileKitTest.testAddFilename_11 () throws Exception [inline]
Definition at line 108 of file FileKitTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.util.FileKitTest.replaceSeparator().
void org.jgap.util.FileKitTest.testAddFilename_2 () throws Exception [inline]
Definition at line 45 of file FileKitTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.util.FileKitTest.replaceSeparator().
void org.jgap.util.FileKitTest.testAddFilename_3 () throws Exception [inline]
Definition at line 52 of file FileKitTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.util.FileKitTest.replaceSeparator().
void org.jgap.util.FileKitTest.testAddFilename_4 () throws Exception [inline]
Definition at line 59 of file FileKitTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.util.FileKitTest.replaceSeparator().
void org.jgap.util.FileKitTest.testAddFilename_5 () throws Exception [inline]
Definition at line 66 of file FileKitTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.util.FileKitTest.replaceSeparator().
void org.jgap.util.FileKitTest.testAddFilename_6 () throws Exception [inline]
Definition at line 73 of file FileKitTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.util.FileKitTest.replaceSeparator().
void org.jgap.util.FileKitTest.testAddFilename_7 () throws Exception [inline]
Definition at line 80 of file FileKitTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.util.FileKitTest.replaceSeparator().
void org.jgap.util.FileKitTest.testAddFilename_8 () throws Exception [inline]
Definition at line 87 of file FileKitTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.util.FileKitTest.replaceSeparator().
void org.jgap.util.FileKitTest.testAddFilename_9 () throws Exception [inline]
Definition at line 94 of file FileKitTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.util.FileKitTest.replaceSeparator().
Member Data Documentation
final String org.jgap.util.FileKitTest.CVS_REVISION = `$Revision: 1.1 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file FileKitTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/util/FileKitTest.java