examples.island.IslandExample Class Reference
Public Member Functions
IslandExample ()
void start () throws Exception
Static Public Member Functions
static void main (String[] args) throws Exception
Private Member Functions
Thread getIsland () throws Exception
Private Attributes
int nextNumber
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Detailed Description
Simple example on how to build and run an island model with JGAP.
Author
Klaus Meffert
Since
3.5
Definition at line 18 of file IslandExample.java.
Constructor & Destructor Documentation
examples.island.IslandExample.IslandExample () [inline]
Definition at line 24 of file IslandExample.java.
Referenced by examples.island.IslandExample.main().
Member Function Documentation
Thread examples.island.IslandExample.getIsland () throws Exception [inline], [private]
Definition at line 56 of file IslandExample.java.
References examples.island.IslandExample.nextNumber.
Referenced by examples.island.IslandExample.start().
static void examples.island.IslandExample.main (String[] args) throws Exception [inline], [static]
Definition at line 61 of file IslandExample.java.
References examples.island.IslandExample.IslandExample().
void examples.island.IslandExample.start () throws Exception [inline]
Todo
Todo
Definition at line 27 of file IslandExample.java.
References examples.island.IslandExample.getIsland(), and examples.island.IslandThread.isFinished().
Member Data Documentation
final String examples.island.IslandExample.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 20 of file IslandExample.java.
int examples.island.IslandExample.nextNumber [private]
Definition at line 22 of file IslandExample.java.
Referenced by examples.island.IslandExample.getIsland().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/island/IslandExample.java