examples.gp.island.IslandGPExample Class Reference
Public Member Functions
IslandGPExample ()
void start () throws Exception
Static Public Member Functions
static void main (String[] args) throws Exception
Private Member Functions
void mergePopulation (GPPopulation original, GPPopulation toMerge, int offset, int count)
void stopAllIslands (Thread[] islandThreads)
Runnable getIsland (int a_index, int a_popSize) throws Exception
Private Attributes
int nextNumber
IslandGPThread m_firstIsland = null
int runs = 0
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.6 $`
Detailed Description
Simple example on how to build and run an GP island model with JGAP.
Author
Klaus Meffert
Since
3.6
Definition at line 21 of file IslandGPExample.java.
Constructor & Destructor Documentation
examples.gp.island.IslandGPExample.IslandGPExample () [inline]
Todo
Todo Island config. einbauen, so dass Island model automatisch ausgeführt wird
Todo
Todo impl. MergeEvent, e.g.: merge islands when one island stucks
Todo
Todo jeweils beste lösung geht öfters verloren! Beeinflusst ein Island das andere oder ist die Lösung in einem Island nicht beständig?
Definition at line 38 of file IslandGPExample.java.
Referenced by examples.gp.island.IslandGPExample.main().
Member Function Documentation
Runnable examples.gp.island.IslandGPExample.getIsland (int a_index, int a_popSize) throws Exception [inline], [private]
Parameters
a_index index of island to create
a_popSize the population size the island should have
Returns
new island instance
Exceptions
Exception
Author
Klaus Meffert
Since
3.6
Definition at line 212 of file IslandGPExample.java.
References examples.gp.island.IslandGPExample.m_firstIsland.
Referenced by examples.gp.island.IslandGPExample.start().
static void examples.gp.island.IslandGPExample.main (String[] args) throws Exception [inline], [static]
Definition at line 220 of file IslandGPExample.java.
References examples.gp.island.IslandGPExample.IslandGPExample().
void examples.gp.island.IslandGPExample.mergePopulation (GPPopulation original, GPPopulation toMerge, int offset, int count) [inline], [private]
Merge two populations.
Parameters
original GPPopulation
toMerge GPPopulation
offset offset in `original` for programs to be merged in to
count number of programs to merge from `toMerge` to `original`
Author
Klaus Meffert
Since
3.6
Definition at line 187 of file IslandGPExample.java.
Referenced by examples.gp.island.IslandGPExample.start().
void examples.gp.island.IslandGPExample.start () throws Exception [inline]
Definition at line 41 of file IslandGPExample.java.
References org.jgap.gp.IGPProgram.getFitnessValue(), examples.gp.island.IslandGPExample.getIsland(), examples.gp.island.IslandGPThread.isFinished(), examples.gp.island.IslandGPThread.isLocked(), examples.gp.island.IslandGPExample.m_firstIsland, examples.gp.island.IslandGPExample.mergePopulation(), examples.gp.island.IslandGPExample.nextNumber, examples.gp.island.IslandGPExample.runs, examples.gp.island.IslandGPExample.stopAllIslands(), and org.jgap.gp.IGPProgram.toStringNorm().
void examples.gp.island.IslandGPExample.stopAllIslands (Thread[] islandThreads) [inline], [private]
Definition at line 195 of file IslandGPExample.java.
Referenced by examples.gp.island.IslandGPExample.start().
Member Data Documentation
final String examples.gp.island.IslandGPExample.CVS_REVISION = `$Revision: 1.6 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 23 of file IslandGPExample.java.
IslandGPThread examples.gp.island.IslandGPExample.m_firstIsland = null [private]
Definition at line 27 of file IslandGPExample.java.
Referenced by examples.gp.island.IslandGPExample.getIsland(), and examples.gp.island.IslandGPExample.start().
int examples.gp.island.IslandGPExample.nextNumber [private]
Definition at line 25 of file IslandGPExample.java.
Referenced by examples.gp.island.IslandGPExample.start().
int examples.gp.island.IslandGPExample.runs = 0 [private]
Definition at line 29 of file IslandGPExample.java.
Referenced by examples.gp.island.IslandGPExample.start().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/island/IslandGPExample.java