org.jgap.DefaultFitnessEvaluatorTest Class Reference
Public Member Functions
void testIsFitter_0 ()
void testIsFitter_1 ()
void testIsFitter_2 ()
void testIsFitter_3 ()
void testIsFitter_4 ()
void testIsFitter_5 ()
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.7 $`
Additional Inherited Members
Detailed Description
Test cases for clasfs DefaultFitnessEvaluator
Author
Klaus Meffert
Since
1.1
Definition at line 20 of file DefaultFitnessEvaluatorTest.java.
Member Function Documentation
static Test org.jgap.DefaultFitnessEvaluatorTest.suite () [inline], [static]
Definition at line 26 of file DefaultFitnessEvaluatorTest.java.
void org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_0 () [inline]
Definition at line 31 of file DefaultFitnessEvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.FitnessEvaluator.isFitter().
void org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_1 () [inline]
Definition at line 37 of file DefaultFitnessEvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.FitnessEvaluator.isFitter().
void org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_2 () [inline]
Definition at line 43 of file DefaultFitnessEvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.FitnessEvaluator.isFitter().
void org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_3 () [inline]
Definition at line 49 of file DefaultFitnessEvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.FitnessEvaluator.isFitter().
void org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_4 () [inline]
Definition at line 54 of file DefaultFitnessEvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.FitnessEvaluator.isFitter().
void org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_5 () [inline]
Definition at line 59 of file DefaultFitnessEvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.FitnessEvaluator.isFitter().
Member Data Documentation
final String org.jgap.DefaultFitnessEvaluatorTest.CVS_REVISION = `$Revision: 1.7 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file DefaultFitnessEvaluatorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/DefaultFitnessEvaluatorTest.java