org.jgap.util.NetworkKit Class Reference
Static Public Member Functions
static String getLocalIPAddress () throws UnknownHostException
static String getLocalHostName () throws UnknownHostException
static String getMACAddress ()
static void main (String[] args)
Private Member Functions
NetworkKit ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.5 $`
Detailed Description
Houses network related functionality.
Author
Klaus Meffert
Since
2.4
Definition at line 21 of file NetworkKit.java.
Constructor & Destructor Documentation
org.jgap.util.NetworkKit.NetworkKit () [inline], [private]
Private constructor because it's a utility class.
Definition at line 28 of file NetworkKit.java.
Member Function Documentation
static String org.jgap.util.NetworkKit.getLocalHostName () throws UnknownHostException [inline], [static]
Returns
name of the computer calling this function locally
Exceptions
UnknownHostException
Author
Klaus Meffert
Since
2.4
Definition at line 50 of file NetworkKit.java.
static String org.jgap.util.NetworkKit.getLocalIPAddress () throws UnknownHostException [inline], [static]
Returns
IP address string in textual presentation
Exceptions
UnknownHostException
Author
Klaus Meffert
Since
2.4
Definition at line 38 of file NetworkKit.java.
static String org.jgap.util.NetworkKit.getMACAddress () [inline], [static]
Taken and adapted from UUID.
Returns
MAC address of the current computer.
Since
3.3.3
Definition at line 62 of file NetworkKit.java.
References org.jgap.util.NumberKit.parseShort().
Referenced by org.jgap.util.NetworkKit.main().
static void org.jgap.util.NetworkKit.main (String[] args) [inline], [static]
Definition at line 120 of file NetworkKit.java.
References org.jgap.util.NetworkKit.getMACAddress().
Member Data Documentation
final String org.jgap.util.NetworkKit.CVS_REVISION = `$Revision: 1.5 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 23 of file NetworkKit.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/util/NetworkKit.java