org.jgap.impl.SetGene Class Reference
Public Member Functions
SetGene () throws InvalidConfigurationException
SetGene (final Configuration a_conf) throws InvalidConfigurationException
void addAllele (final Object a_value)
void addAlleles (final Collection a_alleles)
void removeAlleles (final Object a_key)
void setToRandomValue (final RandomGenerator a_numberGenerator)
void applyMutation (final int a_index, final double a_percentage)
void setValueFromPersistentRepresentation (String a_representation) throws UnsupportedRepresentationException
String getPersistentRepresentation () throws UnsupportedOperationException
void setAllele (Object a_newValue)
int compareTo (Object other)
int hashCode ()
Protected Member Functions
Gene newGeneInternal ()
Object getInternalValue ()
Private Attributes
THashSet m_geneSet = new THashSet()
Object m_value
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.18 $`
Additional Inherited Members
Detailed Description
ATTENTION: This class is preliminary and subject of future adaptations! Use with care or wait for a more mature version we are working on.
Creates a gene instance in which individual alleles have both a label (key) and a value with a distinct meaning. For example, IntegerGene only allows for values having a continuous range, and does not have a function where it is possible to specify setValue...
Author
Johnathan Kool (RSMAS, University of Miami)
Since
2.4
Definition at line 28 of file SetGene.java.
Constructor & Destructor Documentation
org.jgap.impl.SetGene.SetGene () throws InvalidConfigurationException [inline]
Default constructor.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Definition at line 44 of file SetGene.java.
Referenced by org.jgap.impl.SetGene.compareTo(), and org.jgap.impl.SetGene.newGeneInternal().
org.jgap.impl.SetGene.SetGene (final Configuration a_conf) throws InvalidConfigurationException [inline]
Parameters
a_conf the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 57 of file SetGene.java.
Member Function Documentation
void org.jgap.impl.SetGene.addAllele (final Object a_value) [inline]
Adds a potential allele value to the collection.
Parameters
a_value the Integer value to be added
Definition at line 76 of file SetGene.java.
void org.jgap.impl.SetGene.addAlleles (final Collection a_alleles) [inline]
Add a set of potential allele values to the collection
Parameters
a_alleles the set of alleles to be added
Definition at line 85 of file SetGene.java.
void org.jgap.impl.SetGene.applyMutation (final int a_index, final double a_percentage) [inline]
See interface Gene for description of applyMutation.
For this kind of gene, providing an index and a magnitude have no significance because the individual allele forms are independent of one another. In mutating, they can only cange from one form to another. It may be possible to weight the likelihood of mutation to different forms, but that will not be implemented here.
Parameters
a_index ignored here
a_percentage ignored here
Author
Klaus Meffert
Johnathan Kool
Since
2.4
Definition at line 127 of file SetGene.java.
References org.jgap.BaseGene.getConfiguration(), and org.jgap.impl.SetGene.setToRandomValue().
int org.jgap.impl.SetGene.compareTo (Object other) [inline]
Compares this NumberGene with the specified object (which must also be a NumberGene) for order, which is determined by the number value of this Gene compared to the one provided for comparison.
Parameters
other the NumberGene to be compared to this NumberGene
Returns
a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than the object provided for comparison
Exceptions
ClassCastException if the specified object's type prevents it from being compared to this NumberGene
Author
Klaus Meffert
Johnathan Kool
Since
2.4
Definition at line 272 of file SetGene.java.
References org.jgap.BaseGene.getConfiguration(), org.jgap.impl.SetGene.m_value, and org.jgap.impl.SetGene.SetGene().
Referenced by org.jgap.impl.SetGeneTest.testCompareTo_2(), and org.jgap.impl.SetGeneTest.testCompareTo_3().
Object org.jgap.impl.SetGene.getInternalValue () [inline], [protected], [virtual]
Returns
the internal value of the gene
Since
2.4
Implements org.jgap.BaseGene.
Definition at line 309 of file SetGene.java.
References org.jgap.impl.SetGene.m_value.
Referenced by org.jgap.impl.SetGene.hashCode(), and org.jgap.impl.SetGeneTest.testConstruct_1().
String org.jgap.impl.SetGene.getPersistentRepresentation () throws UnsupportedOperationException [inline]
Retrieves a string representation of this Gene that includes any information required to reconstruct it at a later time, such as its value and internal state. This string will be used to represent this Gene in XML persistence. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Returns
a string representation of this Gene's current state
Exceptions
UnsupportedOperationException to indicate that no implementation is provided for this method
Author
Neil Rostan
Since
1.0
Implements org.jgap.IPersistentRepresentation.
Definition at line 222 of file SetGene.java.
References org.jgap.Gene.PERSISTENT_FIELD_DELIMITER, and org.jgap.BaseGene.toString().
int org.jgap.impl.SetGene.hashCode () [inline]
Modified hashCode() function to return different hashcodes for differently ordered genes in a chromosome
Returns
-67 if no allele set, otherwise value return by BaseGene.hashCode()
Author
Klaus Meffert
Since
2.4
Definition at line 321 of file SetGene.java.
References org.jgap.impl.SetGene.getInternalValue().
Gene org.jgap.impl.SetGene.newGeneInternal () [inline], [protected], [virtual]
Implements org.jgap.BaseGene.
Definition at line 62 of file SetGene.java.
References org.jgap.BaseGene.getConfiguration(), and org.jgap.impl.SetGene.SetGene().
void org.jgap.impl.SetGene.removeAlleles (final Object a_key) [inline]
Removes a potential allele or set of alleles from the collection.
Parameters
a_key the unique value(s) of the object(s) to be removed
Definition at line 94 of file SetGene.java.
void org.jgap.impl.SetGene.setAllele (Object a_newValue) [inline]
Sets the value (allele) of this Gene to the new given value. This class expects the value to be an instance of current type (e.g. Integer).
Parameters
a_newValue the new value of this Gene instance.
Author
Johnathan Kool
Implements org.jgap.Gene.
Definition at line 245 of file SetGene.java.
References org.jgap.impl.SetGene.m_geneSet, and org.jgap.impl.SetGene.m_value.
void org.jgap.impl.SetGene.setToRandomValue (final RandomGenerator a_numberGenerator) [inline]
Sets the allele value to be a random value using a defined random number generator.
Author
Johnathan Kool
Parameters
a_numberGenerator RandomGenerator
Definition at line 106 of file SetGene.java.
References org.jgap.impl.SetGene.m_geneSet, org.jgap.impl.SetGene.m_value, and org.jgap.RandomGenerator.nextInt().
Referenced by org.jgap.impl.SetGene.applyMutation().
void org.jgap.impl.SetGene.setValueFromPersistentRepresentation (String a_representation) throws UnsupportedRepresentationException [inline]
Sets the value and internal state of this Gene from the string representation returned by a previous invocation of the getPersistentRepresentation() method. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Parameters
a_representation the string representation retrieved from a prior call to the getPersistentRepresentation() method
Exceptions
UnsupportedRepresentationException if this Gene implementation does not support the given string representation
Author
Neil Rostan
Since
1.0
Implements org.jgap.IPersistentRepresentation.
Definition at line 154 of file SetGene.java.
References org.jgap.impl.SetGene.m_value, and org.jgap.Gene.PERSISTENT_FIELD_DELIMITER.
Member Data Documentation
final String org.jgap.impl.SetGene.CVS_REVISION = `$Revision: 1.18 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 31 of file SetGene.java.
THashSet org.jgap.impl.SetGene.m_geneSet = new THashSet() [private]
Definition at line 33 of file SetGene.java.
Referenced by org.jgap.impl.SetGene.setAllele(), and org.jgap.impl.SetGene.setToRandomValue().
Object org.jgap.impl.SetGene.m_value [private]
Definition at line 35 of file SetGene.java.
Referenced by org.jgap.impl.SetGene.compareTo(), org.jgap.impl.SetGene.getInternalValue(), org.jgap.impl.SetGene.setAllele(), org.jgap.impl.SetGene.setToRandomValue(), and org.jgap.impl.SetGene.setValueFromPersistentRepresentation().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/SetGene.java