org.jgap.impl.MutationOperator Class Reference
Classes
class MutationOperatorConfigurable
Public Member Functions
MutationOperator () throws InvalidConfigurationException
MutationOperator (final Configuration a_conf) throws InvalidConfigurationException
MutationOperator (final Configuration a_config, final IUniversalRateCalculator a_mutationRateCalculator) throws InvalidConfigurationException
MutationOperator (final Configuration a_config, final int a_desiredMutationRate) throws InvalidConfigurationException
void operate (final Population a_population, final List a_candidateChromosomes)
IUniversalRateCalculator getMutationRateCalc ()
void setMutationRateCalc (final IUniversalRateCalculator a_mutationRateCalc)
void setMutationRate (int a_mutationRate)
boolean equals (final Object a_other)
int compareTo (Object a_other)
int getMutationRate ()
Private Member Functions
void mutateGene (final Gene a_gene, final RandomGenerator a_generator)
Private Attributes
IUniversalRateCalculator m_mutationRateCalc
MutationOperatorConfigurable m_config
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.49 $`
Additional Inherited Members
Detailed Description
The mutation operator runs through the genes in each of the Chromosomes in the population and mutates them in statistical accordance to the given mutation rate. Mutated Chromosomes are then added to the list of candidate Chromosomes destined for the natural selection process.
This MutationOperator supports both fixed and dynamic mutation rates. A fixed rate is one specified at construction time by the user. A dynamic rate is determined by this class if no fixed rate is provided, and is calculated based on the size of the Chromosomes in the population. Details are specified in the DefaultMutationRateCalculator class.
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 33 of file MutationOperator.java.
Constructor & Destructor Documentation
org.jgap.impl.MutationOperator.MutationOperator () throws InvalidConfigurationException [inline]
Constructs a new instance of this MutationOperator without a specified mutation rate, which results in dynamic mutation being turned on. This means that the mutation rate will be automatically determined by this operator based upon the number of genes present in the chromosomes.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 63 of file MutationOperator.java.
Referenced by org.jgap.impl.MutationOperator.compareTo().
org.jgap.impl.MutationOperator.MutationOperator (final Configuration a_conf) throws InvalidConfigurationException [inline]
Parameters
a_conf the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 75 of file MutationOperator.java.
References org.jgap.impl.MutationOperator.setMutationRateCalc().
org.jgap.impl.MutationOperator.MutationOperator (final Configuration a_config, final IUniversalRateCalculator a_mutationRateCalculator) throws InvalidConfigurationException [inline]
Constructs a new instance of this MutationOperator with a specified mutation rate calculator, which results in dynamic mutation being turned on.
Parameters
a_config the configuration to use
a_mutationRateCalculator calculator for dynamic mutation rate computation
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
1.1
Definition at line 93 of file MutationOperator.java.
References org.jgap.impl.MutationOperator.setMutationRateCalc().
org.jgap.impl.MutationOperator.MutationOperator (final Configuration a_config, final int a_desiredMutationRate) throws InvalidConfigurationException [inline]
Constructs a new instance of this MutationOperator with the given mutation rate.
Parameters
a_config the configuration to use
a_desiredMutationRate desired rate of mutation, expressed as the denominator of the 1 / X fraction. For example, 1000 would result in 1/1000 genes being mutated on average. A mutation rate of zero disables mutation entirely
Exceptions
InvalidConfigurationException
Author
Neil Rotstan
Since
1.1
Definition at line 115 of file MutationOperator.java.
References org.jgap.impl.MutationOperator.setMutationRateCalc().
Member Function Documentation
int org.jgap.impl.MutationOperator.compareTo (Object a_other) [inline]
Compares the given GeneticOperator to this GeneticOperator.
Parameters
a_other the instance against which to compare this instance
Returns
a negative number if this instance is `less than` the given instance, zero if they are equal to each other, and a positive number if this is `greater than` the given instance
Author
Klaus Meffert
Since
2.6
Definition at line 342 of file MutationOperator.java.
References org.jgap.impl.MutationOperator.m_config, org.jgap.impl.MutationOperator.m_mutationRateCalc, and org.jgap.impl.MutationOperator.MutationOperator().
Referenced by org.jgap.impl.MutationOperator.equals(), and org.jgap.impl.MutationOperatorTest.testCompareTo_0().
boolean org.jgap.impl.MutationOperator.equals (final Object a_other) [inline]
Compares this GeneticOperator against the specified object. The result is true if and the argument is an instance of this class and is equal wrt the data.
Parameters
a_other the object to compare against
Returns
true: if the objects are the same, false otherwise
Author
Klaus Meffert
Since
2.6
Definition at line 323 of file MutationOperator.java.
References org.jgap.impl.MutationOperator.compareTo().
int org.jgap.impl.MutationOperator.getMutationRate () [inline]
Definition at line 372 of file MutationOperator.java.
Referenced by org.jgap.impl.SwappingMutationOperator.operate(), org.jgap.impl.RangedSwappingMutationOperator.operate(), org.jgap.impl.MutationOperatorTest.testConstruct_0(), org.jgap.impl.SwappingMutationOperatorTest.testConstruct_0(), org.jgap.impl.MutationOperatorTest.testConstruct_1(), org.jgap.impl.SwappingMutationOperatorTest.testConstruct_1(), org.jgap.impl.MutationOperatorTest.testConstruct_2(), org.jgap.impl.SwappingMutationOperatorTest.testConstruct_2(), org.jgap.impl.MutationOperatorTest.testConstruct_3(), and org.jgap.impl.SwappingMutationOperatorTest.testConstruct_3().
IUniversalRateCalculator org.jgap.impl.MutationOperator.getMutationRateCalc () [inline]
Returns
the MutationRateCalculator used
Author
Klaus Meffert
Since
1.1
Definition at line 276 of file MutationOperator.java.
References org.jgap.impl.MutationOperator.m_mutationRateCalc.
Referenced by org.jgap.impl.SwappingMutationOperator.operate(), org.jgap.impl.RangedSwappingMutationOperator.operate(), org.jgap.impl.MutationOperatorTest.testConstruct_0(), org.jgap.impl.SwappingMutationOperatorTest.testConstruct_0(), org.jgap.impl.MutationOperatorTest.testConstruct_1(), org.jgap.impl.SwappingMutationOperatorTest.testConstruct_1(), org.jgap.impl.MutationOperatorTest.testConstruct_2(), org.jgap.impl.SwappingMutationOperatorTest.testConstruct_2(), org.jgap.impl.MutationOperatorTest.testConstruct_3(), and org.jgap.impl.SwappingMutationOperatorTest.testConstruct_3().
void org.jgap.impl.MutationOperator.mutateGene (final Gene a_gene, final RandomGenerator a_generator) [inline], [private]
Helper: mutate all atomic elements of a gene.
Parameters
a_gene the gene to be mutated
a_generator the generator delivering the amount of mutation
Author
Klaus Meffert
Since
1.1
Definition at line 258 of file MutationOperator.java.
Referenced by org.jgap.impl.MutationOperator.operate().
void org.jgap.impl.MutationOperator.operate (final Population a_population, final List a_candidateChromosomes) [inline]
Parameters
a_population the population of chromosomes from the current evolution prior to exposure to any genetic operators. Chromosomes in this array should not be modified. Please notice, that the call in Genotype.evolve() to the implementations of GeneticOperator overgoes this due to performance issues
a_candidateChromosomes the pool of chromosomes that have been mutated
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Todo
Todo move to base class, refactor
Implements org.jgap.GeneticOperator.
Definition at line 136 of file MutationOperator.java.
References org.jgap.util.ICloneable.clone(), org.jgap.ICompositeGene.geneAt(), org.jgap.BaseGeneticOperator.getConfiguration(), org.jgap.impl.MutationOperator.m_config, org.jgap.BaseGeneticOperator.m_monitorActive, org.jgap.impl.MutationOperator.m_mutationRateCalc, org.jgap.impl.MutationOperator.mutateGene(), and org.jgap.Population.size().
void org.jgap.impl.MutationOperator.setMutationRate (int a_mutationRate) [inline]
Parameters
a_mutationRate new rate of mutation, expressed as the denominator of the 1 / X fraction. For example, 1000 would result in 1/1000 genes being mutated on average. A mutation rate of zero disables mutation entirely
Author
Klaus Meffert
Since
3.2.2
Definition at line 307 of file MutationOperator.java.
References org.jgap.impl.MutationOperator.setMutationRateCalc().
void org.jgap.impl.MutationOperator.setMutationRateCalc (final IUniversalRateCalculator a_mutationRateCalc) [inline]
Sets the MutationRateCalculator to be used for determining the strength of mutation.
Parameters
a_mutationRateCalc MutationRateCalculator
Author
Klaus Meffert
Since
1.1
Definition at line 289 of file MutationOperator.java.
References org.jgap.impl.MutationOperator.m_mutationRateCalc.
Referenced by org.jgap.impl.MutationOperator.MutationOperator(), and org.jgap.impl.MutationOperator.setMutationRate().
Member Data Documentation
final String org.jgap.impl.MutationOperator.CVS_REVISION = `$Revision: 1.49 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 36 of file MutationOperator.java.
MutationOperatorConfigurable org.jgap.impl.MutationOperator.m_config [private]
Initial value:
= new
      MutationOperatorConfigurable()
Definition at line 45 of file MutationOperator.java.
Referenced by org.jgap.impl.MutationOperator.compareTo(), and org.jgap.impl.MutationOperator.operate().
IUniversalRateCalculator org.jgap.impl.MutationOperator.m_mutationRateCalc [private]
Calculator for dynamically determining the mutation rate. If set to null the value of m_mutationRate will be used. Replaces the previously used boolean m_dynamicMutationRate.
Definition at line 43 of file MutationOperator.java.
Referenced by org.jgap.impl.MutationOperator.compareTo(), org.jgap.impl.MutationOperator.getMutationRateCalc(), org.jgap.impl.SwappingMutationOperator.operate(), org.jgap.impl.RangedSwappingMutationOperator.operate(), org.jgap.impl.MutationOperator.operate(), and org.jgap.impl.MutationOperator.setMutationRateCalc().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/MutationOperator.java