examples.monalisa.core.GAPhenotypeExpresser Class Reference
Public Member Functions
GAPhenotypeExpresser (GAConfiguration a_conf)
BufferedImage express (IChromosome a_chromosome)
Color expressColor (IChromosome a_chromosome, int a_n)
Polygon expressPolygon (IChromosome a_chromosome, int a_n)
Private Attributes
GAConfiguration m_conf
BufferedImage m_generated
Graphics m_graphics
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Detailed Description
Author
Yann N. Dauphin
Since
3.4
Definition at line 22 of file GAPhenotypeExpresser.java.
Constructor & Destructor Documentation
examples.monalisa.core.GAPhenotypeExpresser.GAPhenotypeExpresser (GAConfiguration a_conf) [inline]
Definition at line 32 of file GAPhenotypeExpresser.java.
References examples.monalisa.core.GAPhenotypeExpresser.m_conf, examples.monalisa.core.GAPhenotypeExpresser.m_generated, and examples.monalisa.core.GAPhenotypeExpresser.m_graphics.
Member Function Documentation
BufferedImage examples.monalisa.core.GAPhenotypeExpresser.express (IChromosome a_chromosome) [inline]
Definition at line 40 of file GAPhenotypeExpresser.java.
References examples.monalisa.core.GAPhenotypeExpresser.expressColor(), examples.monalisa.core.GAPhenotypeExpresser.expressPolygon(), and examples.monalisa.core.GAPhenotypeExpresser.m_generated.
Color examples.monalisa.core.GAPhenotypeExpresser.expressColor (IChromosome a_chromosome, int a_n) [inline]
Parameters
a_chromosome the chromosome that holds the color information
a_n the index of the polygon
Returns
an object representing the nth color encoded in the chromosome
Definition at line 56 of file GAPhenotypeExpresser.java.
Referenced by examples.monalisa.core.GAPhenotypeExpresser.express().
Polygon examples.monalisa.core.GAPhenotypeExpresser.expressPolygon (IChromosome a_chromosome, int a_n) [inline]
Parameters
a_chromosome the chromosome that holds the polygon information
a_n the index of the polygon
Returns
an object representing the nth polygon encoded in the chromosome
Definition at line 73 of file GAPhenotypeExpresser.java.
References examples.monalisa.core.GAInitialChromosomeFactory.getNumberOfColorGenesPerPolygon(), and examples.monalisa.core.GAInitialChromosomeFactory.POINTS.
Referenced by examples.monalisa.core.GAPhenotypeExpresser.express().
Member Data Documentation
final String examples.monalisa.core.GAPhenotypeExpresser.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file GAPhenotypeExpresser.java.
GAConfiguration examples.monalisa.core.GAPhenotypeExpresser.m_conf [private]
Definition at line 26 of file GAPhenotypeExpresser.java.
Referenced by examples.monalisa.core.GAPhenotypeExpresser.GAPhenotypeExpresser().
BufferedImage examples.monalisa.core.GAPhenotypeExpresser.m_generated [private]
Definition at line 28 of file GAPhenotypeExpresser.java.
Referenced by examples.monalisa.core.GAPhenotypeExpresser.express(), and examples.monalisa.core.GAPhenotypeExpresser.GAPhenotypeExpresser().
Graphics examples.monalisa.core.GAPhenotypeExpresser.m_graphics [private]
Definition at line 30 of file GAPhenotypeExpresser.java.
Referenced by examples.monalisa.core.GAPhenotypeExpresser.GAPhenotypeExpresser().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/monalisa/core/GAPhenotypeExpresser.java