org.jgap.impl.BestChromosomesSelectorTest Class Reference
Public Member Functions
void testConstruct_0 () throws Exception
void testConstruct_3 () throws Exception
void testDoubletteChromosomesAllowed_0 () throws Exception
void testAdd_0 () throws Exception
void testSelect_0 () throws Exception
void testSelect_1 () throws Exception
void testSelect_2 () throws Exception
void testSelect_3 () throws Exception
void testSelect_4 () throws Exception
void testEmpty_0 () throws Exception
void testEmpty_1 () throws Exception
void testEmpty_2 () throws Exception
void testSetOriginalRate_0 () throws Exception
void testSetOriginalRate_0_1 () throws Exception
void testSetOriginalRate_1 () throws Exception
void testReturnsUnique_0 () throws Exception
void testIsSerializable_0 () throws Exception
void testDoSerialize_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.35 $`
Additional Inherited Members
Detailed Description
Tests the BestChromosomesSelector class.
Author
Klaus Meffert
Since
1.1
Definition at line 22 of file BestChromosomesSelectorTest.java.
Member Function Documentation
static Test org.jgap.impl.BestChromosomesSelectorTest.suite () [inline], [static]
Definition at line 27 of file BestChromosomesSelectorTest.java.
void org.jgap.impl.BestChromosomesSelectorTest.testAdd_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 89 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.BestChromosomesSelectorTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 38 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.NaturalSelectorExt.getDoubletteChromosomesAllowed(), org.jgap.JGAPTestCase.privateAccessor, and org.jgap.impl.BestChromosomesSelector.returnsUniqueChromosomes().
void org.jgap.impl.BestChromosomesSelectorTest.testConstruct_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 57 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BestChromosomesSelectorTest.testDoSerialize_0 () throws Exception [inline]
Ensures that BCS implements Serializable correctly.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 488 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.doSerialize().
void org.jgap.impl.BestChromosomesSelectorTest.testDoubletteChromosomesAllowed_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 70 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.NaturalSelectorExt.getDoubletteChromosomesAllowed().
void org.jgap.impl.BestChromosomesSelectorTest.testEmpty_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 348 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.BestChromosomesSelectorTest.testEmpty_1 () throws Exception [inline]
Test if clear()-method does not affect original Population.
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 370 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BestChromosomesSelectorTest.testEmpty_2 () throws Exception [inline]
Test if clear()-method does not affect return value.
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 391 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BestChromosomesSelectorTest.testIsSerializable_0 () throws Exception [inline]
Ensures BCS is implementing Serializable.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 474 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.isSerializable().
void org.jgap.impl.BestChromosomesSelectorTest.testReturnsUnique_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 460 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.BestChromosomesSelector.returnsUniqueChromosomes().
void org.jgap.impl.BestChromosomesSelectorTest.testSelect_0 () throws Exception [inline]
Test if below functionality available without error.
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 121 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BestChromosomesSelectorTest.testSelect_1 () throws Exception [inline]
Test selection algorithm.
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 145 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BestChromosomesSelectorTest.testSelect_2 () throws Exception [inline]
Test selection algorithm.
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 196 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BestChromosomesSelectorTest.testSelect_3 () throws Exception [inline]
Ensure that selected Chromosomes are not equal to added Chromosomes.
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 242 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.BestChromosomesSelectorTest.testSelect_4 () throws Exception [inline]
Test selection algorithm with allowed doublettes.
Exceptions
Exception
Author
Klaus Meffert
Since
1.1
Definition at line 280 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BestChromosomesSelectorTest.testSetOriginalRate_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 411 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BestChromosomesSelectorTest.testSetOriginalRate_0_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 429 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.BestChromosomesSelectorTest.testSetOriginalRate_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 447 of file BestChromosomesSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.impl.BestChromosomesSelector.getOriginalRate().
Member Data Documentation
final String org.jgap.impl.BestChromosomesSelectorTest.CVS_REVISION = `$Revision: 1.35 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file BestChromosomesSelectorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/BestChromosomesSelectorTest.java