org.jgap.distr.grid.util.GridKit Class Reference
Static Public Member Functions
static String ensureDirectory (String a_currentDir, String a_subDir, String a_descr) throws IOException
static URLConnection getConnection (String a_url) throws Exception
static VersionInfo isUpdateAvailable (String BASE_URL, String a_moduleName, String currentVersion) throws Exception
static String addURLParameter (String a_requestURL, String a_key, long a_value)
static String addURLParameter (String a_requestURL, String a_key, String a_value)
static String retrieveModule (String BASE_URL, VersionInfo a_versionInfo, String a_destDir) throws Exception
static void updateModule (String a_filename, String a_workDir, String a_libDir) throws Exception
static boolean getFile (String BASE_URL, String a_sourceFilename, String a_targetDir) throws Exception
static void updateModuleLibrary (String BASE_URL, String a_moduleName, String a_libDir, String a_workDir) throws Exception
static void updateJGAPLibrary (String BASE_URL, String a_libDir, String a_workDir) throws Exception
static void main (String[] args) throws Exception
static void writeTextFile (Vector zeilen, String dateiname) throws Exception
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.5 $`
Detailed Description
Utility functions related to distributed/grid computing.
Author
Klaus Meffert
Since
3.2
Definition at line 27 of file GridKit.java.
Member Function Documentation
static String org.jgap.distr.grid.util.GridKit.addURLParameter (String a_requestURL, String a_key, long a_value) [inline], [static]
Definition at line 79 of file GridKit.java.
Referenced by org.jgap.distr.grid.util.GridKit.isUpdateAvailable().
static String org.jgap.distr.grid.util.GridKit.addURLParameter (String a_requestURL, String a_key, String a_value) [inline], [static]
Definition at line 85 of file GridKit.java.
static String org.jgap.distr.grid.util.GridKit.ensureDirectory (String a_currentDir, String a_subDir, String a_descr) throws IOException [inline], [static]
Definition at line 31 of file GridKit.java.
static URLConnection org.jgap.distr.grid.util.GridKit.getConnection (String a_url) throws Exception [inline], [static]
Definition at line 55 of file GridKit.java.
static boolean org.jgap.distr.grid.util.GridKit.getFile (String BASE_URL, String a_sourceFilename, String a_targetDir) throws Exception [inline], [static]
Definition at line 117 of file GridKit.java.
Referenced by org.jgap.distr.grid.util.GridKit.retrieveModule().
static VersionInfo org.jgap.distr.grid.util.GridKit.isUpdateAvailable (String BASE_URL, String a_moduleName, String currentVersion) throws Exception [inline], [static]
Todo
Todo download a versions.txt file and obtain version per project
Definition at line 66 of file GridKit.java.
References org.jgap.distr.grid.util.GridKit.addURLParameter().
static void org.jgap.distr.grid.util.GridKit.main (String[] args) throws Exception [inline], [static]
Definition at line 269 of file GridKit.java.
References org.jgap.distr.grid.util.GridKit.writeTextFile().
static String org.jgap.distr.grid.util.GridKit.retrieveModule (String BASE_URL, VersionInfo a_versionInfo, String a_destDir) throws Exception [inline], [static]
Definition at line 91 of file GridKit.java.
References org.jgap.distr.grid.util.GridKit.getFile().
static void org.jgap.distr.grid.util.GridKit.updateJGAPLibrary (String BASE_URL, String a_libDir, String a_workDir) throws Exception [inline], [static]
Definition at line 263 of file GridKit.java.
References org.jgap.distr.grid.util.GridKit.updateModuleLibrary().
static void org.jgap.distr.grid.util.GridKit.updateModule (String a_filename, String a_workDir, String a_libDir) throws Exception [inline], [static]
Todo
Todo write log: delete manually
Definition at line 102 of file GridKit.java.
static void org.jgap.distr.grid.util.GridKit.updateModuleLibrary (String BASE_URL, String a_moduleName, String a_libDir, String a_workDir) throws Exception [inline], [static]
Todo
Todo zuordnung irgendwo abspeichern
Todo
Todo zuordnung irgendwo abspeichern
Todo
Todo zuordnung irgendwo abspeichern
Definition at line 194 of file GridKit.java.
Referenced by org.jgap.distr.grid.util.GridKit.updateJGAPLibrary().
static void org.jgap.distr.grid.util.GridKit.writeTextFile (Vector zeilen, String dateiname) throws Exception [inline], [static]
Definition at line 284 of file GridKit.java.
Referenced by org.jgap.distr.grid.util.GridKit.main().
Member Data Documentation
final String org.jgap.distr.grid.util.GridKit.CVS_REVISION = `$Revision: 1.5 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 29 of file GridKit.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/distr/grid/util/GridKit.java