examples.MinimizingMakeChangeCached Class Reference
Static Public Member Functions
static void makeChangeForAmount (int a_targetChangeAmount) throws Exception
static void main (String[] args) throws Exception
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
static final int MAX_ALLOWED_EVOLUTIONS = 200
Detailed Description
See class MinimizingMakeChanged. Here a cached fitness function is used instead of an ordinary fitness function.
Author
Klaus Meffert
Since
3.2
Definition at line 25 of file MinimizingMakeChangeCached.java.
Member Function Documentation
static void examples.MinimizingMakeChangeCached.main (String[] args) throws Exception [inline], [static]
Main method. A single command-line argument is expected, which is the amount of change to create (in other words, 75 would be equal to 75 cents).
Parameters
args amount of change in cents to create
Exceptions
Exception
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 145 of file MinimizingMakeChangeCached.java.
References examples.MinimizingMakeChangeCached.makeChangeForAmount(), and examples.MinimizingFitnessFunctionCached.MAX_BOUND.
static void examples.MinimizingMakeChangeCached.makeChangeForAmount (int a_targetChangeAmount) throws Exception [inline], [static]
Executes the genetic algorithm to determine the minimum number of coins necessary to make up the given target amount of change. The solution will then be written to System.out.
Parameters
a_targetChangeAmount the target amount of change for which this method is attempting to produce the minimum number of coins
Exceptions
Exception
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 47 of file MinimizingMakeChangeCached.java.
References examples.MinimizingFitnessFunctionCached.getTotalNumberOfCoins(), and examples.MinimizingMakeChangeCached.MAX_ALLOWED_EVOLUTIONS.
Referenced by examples.MinimizingMakeChangeCached.main().
Member Data Documentation
final String examples.MinimizingMakeChangeCached.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file MinimizingMakeChangeCached.java.
final int examples.MinimizingMakeChangeCached.MAX_ALLOWED_EVOLUTIONS = 200 [static], [private]
The total number of times we'll let the population evolve.
Definition at line 32 of file MinimizingMakeChangeCached.java.
Referenced by examples.MinimizingMakeChangeCached.makeChangeForAmount().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/MinimizingMakeChangeCached.java