org.jgap.gp.impl.BranchTypingCrossTest Class Reference
Public Member Functions
void setUp ()
void testOperate_0 () throws Exception
void testOperate_1 () throws Exception
void testOperate_2 () throws Exception
void testSerialize_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.7 $`
Additional Inherited Members
Detailed Description
Tests the BranchTypingCross class.
Author
Klaus Meffert
Since
3.0
Definition at line 23 of file BranchTypingCrossTest.java.
Member Function Documentation
void org.jgap.gp.impl.BranchTypingCrossTest.setUp () [inline]
Definition at line 33 of file BranchTypingCrossTest.java.
static Test org.jgap.gp.impl.BranchTypingCrossTest.suite () [inline], [static]
Definition at line 28 of file BranchTypingCrossTest.java.
void org.jgap.gp.impl.BranchTypingCrossTest.testOperate_0 () throws Exception [inline]
See if crossover chooses a correct function for a function selected priorly. Simple case: De facto replace subtrees (from `FOR` on, see above code). Cross over at functions in this test case.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 47 of file BranchTypingCrossTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.GPTestCase.CMD_ADD, org.jgap.gp.GPTestCase.CMD_CONST0, org.jgap.gp.GPTestCase.CMD_FOR, org.jgap.gp.GPTestCase.CMD_NOP, org.jgap.gp.impl.ProgramChromosome.getGene(), and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.BranchTypingCrossTest.testOperate_1 () throws Exception [inline]
Cross over a function with a terminal.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 119 of file BranchTypingCrossTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.GPTestCase.CMD_ADD, org.jgap.gp.GPTestCase.CMD_CONST0, org.jgap.gp.GPTestCase.CMD_FOR, org.jgap.gp.GPTestCase.CMD_NOP, org.jgap.gp.impl.ProgramChromosome.getGene(), and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.BranchTypingCrossTest.testOperate_2 () throws Exception [inline]
Cross over a terminal with a terminal.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 191 of file BranchTypingCrossTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.GPTestCase.CMD_ADD, org.jgap.gp.GPTestCase.CMD_CONST0, org.jgap.gp.GPTestCase.CMD_FOR, org.jgap.gp.GPTestCase.CMD_NOP, org.jgap.gp.impl.ProgramChromosome.getGene(), and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.BranchTypingCrossTest.testSerialize_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 255 of file BranchTypingCrossTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.doSerialize(), and org.jgap.gp.GPTestCase.m_gpconf.
Member Data Documentation
final String org.jgap.gp.impl.BranchTypingCrossTest.CVS_REVISION = `$Revision: 1.7 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file BranchTypingCrossTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/gp/impl/BranchTypingCrossTest.java