examples.math.ga.MathGene Class Reference
Classes
class GetValueOperandVisitor
Public Member Functions
MathGene (Configuration theConfiguration) throws InvalidConfigurationException
void setAllele (Object o)
String getPersistentRepresentation () throws UnsupportedOperationException
void setValueFromPersistentRepresentation (String s) throws UnsupportedOperationException, UnsupportedRepresentationException
void setToRandomValue (RandomGenerator theRandomGenerator)
void applyMutation (int i, double v)
int hashCode ()
String toString ()
boolean equals (Object theObj)
int compareTo (Object o)
Protected Member Functions
Object getInternalValue ()
Gene newGeneInternal ()
Private Member Functions
Operand generateRandomOperand (RandomGenerator theRand)
ValueOperand generateRandomValueOperand (RandomGenerator theRand)
MathOperator generateRandomMathOperator (RandomGenerator theRand)
Operand mutateOperand (Operand theOp, double theRate)
Private Attributes
Operand mOperand
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.1 $`
Detailed Description
A gene for mathematical expressions.
Author
Michael Grove
Since
3.4.2
Definition at line 23 of file MathGene.java.
Constructor & Destructor Documentation
examples.math.ga.MathGene.MathGene (Configuration theConfiguration) throws InvalidConfigurationException [inline]
Definition at line 30 of file MathGene.java.
References examples.math.ga.MathGene.mOperand.
Referenced by examples.math.ga.MathGene.compareTo(), examples.math.ga.MathGene.equals(), and examples.math.ga.MathGene.newGeneInternal().
Member Function Documentation
void examples.math.ga.MathGene.applyMutation (int i, double v) [inline]
Definition at line 104 of file MathGene.java.
References examples.math.ga.MathGene.mOperand, examples.math.ga.MathGene.mutateOperand(), and examples.math.ga.MathGene.setAllele().
int examples.math.ga.MathGene.compareTo (Object o) [inline]
Definition at line 187 of file MathGene.java.
References examples.math.ga.MathGene.MathGene(), and examples.math.ga.MathGene.mOperand.
boolean examples.math.ga.MathGene.equals (Object theObj) [inline]
Definition at line 177 of file MathGene.java.
References examples.math.ga.MathGene.MathGene(), and examples.math.ga.MathGene.toString().
MathOperator examples.math.ga.MathGene.generateRandomMathOperator (RandomGenerator theRand) [inline], [private]
Definition at line 84 of file MathGene.java.
References examples.math.ga.MathGene.generateRandomValueOperand().
Referenced by examples.math.ga.MathGene.generateRandomOperand(), and examples.math.ga.MathGene.mutateOperand().
Operand examples.math.ga.MathGene.generateRandomOperand (RandomGenerator theRand) [inline], [private]
Definition at line 68 of file MathGene.java.
References examples.math.ga.MathGene.generateRandomMathOperator(), and examples.math.ga.MathGene.generateRandomValueOperand().
Referenced by examples.math.ga.MathGene.mutateOperand(), and examples.math.ga.MathGene.setToRandomValue().
ValueOperand examples.math.ga.MathGene.generateRandomValueOperand (RandomGenerator theRand) [inline], [private]
Definition at line 77 of file MathGene.java.
Referenced by examples.math.ga.MathGene.generateRandomMathOperator(), examples.math.ga.MathGene.generateRandomOperand(), and examples.math.ga.MathGene.mutateOperand().
Object examples.math.ga.MathGene.getInternalValue () [inline], [protected]
Definition at line 36 of file MathGene.java.
References examples.math.ga.MathGene.mOperand.
String examples.math.ga.MathGene.getPersistentRepresentation () throws UnsupportedOperationException [inline]
Definition at line 54 of file MathGene.java.
int examples.math.ga.MathGene.hashCode () [inline]
Definition at line 167 of file MathGene.java.
References examples.math.ga.MathGene.toString().
Operand examples.math.ga.MathGene.mutateOperand (Operand theOp, double theRate) [inline], [private]
Definition at line 109 of file MathGene.java.
References examples.math.ga.MathGene.generateRandomMathOperator(), examples.math.ga.MathGene.generateRandomOperand(), and examples.math.ga.MathGene.generateRandomValueOperand().
Referenced by examples.math.ga.MathGene.applyMutation().
Gene examples.math.ga.MathGene.newGeneInternal () [inline], [protected]
Definition at line 40 of file MathGene.java.
References examples.math.ga.MathGene.MathGene().
void examples.math.ga.MathGene.setAllele (Object o) [inline]
Definition at line 48 of file MathGene.java.
References examples.math.ga.MathGene.mOperand.
Referenced by examples.math.ga.MathGene.applyMutation(), and examples.math.ga.MathGene.setToRandomValue().
void examples.math.ga.MathGene.setToRandomValue (RandomGenerator theRandomGenerator) [inline]
Definition at line 64 of file MathGene.java.
References examples.math.ga.MathGene.generateRandomOperand(), and examples.math.ga.MathGene.setAllele().
void examples.math.ga.MathGene.setValueFromPersistentRepresentation (String s) throws UnsupportedOperationException, UnsupportedRepresentationException [inline]
Definition at line 59 of file MathGene.java.
String examples.math.ga.MathGene.toString () [inline]
Definition at line 172 of file MathGene.java.
References examples.math.ga.MathGene.mOperand.
Referenced by examples.math.ga.MathGene.equals(), and examples.math.ga.MathGene.hashCode().
Member Data Documentation
final String examples.math.ga.MathGene.CVS_REVISION = `$Revision: 1.1 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file MathGene.java.
Operand examples.math.ga.MathGene.mOperand [private]
Definition at line 28 of file MathGene.java.
Referenced by examples.math.ga.MathGene.applyMutation(), examples.math.ga.MathGene.compareTo(), examples.math.ga.MathGene.getInternalValue(), examples.math.ga.MathGene.MathGene(), examples.math.ga.MathGene.setAllele(), and examples.math.ga.MathGene.toString().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/math/ga/MathGene.java