examples.constraint.ConstraintExample Class Reference
Static Public Member Functions
static void makeChangeForAmount (int a_targetChangeAmount, boolean a_doMonitor) throws Exception
static void main (String[] args) throws Exception
static boolean uniqueChromosomes (Population a_pop)
Static Public Attributes
static EvolutionMonitor m_monitor
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.1 $`
static final int MAX_ALLOWED_EVOLUTIONS = 200
Detailed Description
This class provides an implementation of the classic `Make change` problem using a genetic algorithm. The goal of the problem is to provide a specified amount of change (from a cash purchase) in the fewest coins possible. This example implementation uses American currency (quarters, dimes, nickels, and pennies).
This example may be seen as somewhat significant because it demonstrates the use of a genetic algorithm in a less-than-optimal problem space. The genetic algorithm does best when there is a smooth slope of fitness over the problem space towards the optimum solution. This problem exhibits a more choppy space with more local optima. However, as can be seen from running this example, the genetic algorithm still will get the correct (or a very close) answer virtually everytime.
Author
Klaus Meffert
Since
3.6.2
Definition at line 34 of file ConstraintExample.java.
Member Function Documentation
static void examples.constraint.ConstraintExample.main (String[] args) throws Exception [inline], [static]
Main method. A single command-line argument is expected, which is the amount of change to create (in other words, 75 would be equal to 75 cents).
Parameters
args amount of change in cents to create
Exceptions
Exception
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 181 of file ConstraintExample.java.
References examples.constraint.ConstraintExample.makeChangeForAmount().
static void examples.constraint.ConstraintExample.makeChangeForAmount (int a_targetChangeAmount, boolean a_doMonitor) throws Exception [inline], [static]
Executes the genetic algorithm to determine the minimum number of coins necessary to make up the given target amount of change. The solution will then be written to System.out.
Parameters
a_targetChangeAmount the target amount of change for which this method is attempting to produce the minimum number of coins
a_doMonitor true: turn on monitoring for later evaluation of evolution progress
Exceptions
Exception
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 61 of file ConstraintExample.java.
References examples.constraint.ConstraintExample.m_monitor, examples.constraint.ConstraintExample.MAX_ALLOWED_EVOLUTIONS, and examples.constraint.ConstraintExample.uniqueChromosomes().
Referenced by examples.constraint.ConstraintExample.main().
static boolean examples.constraint.ConstraintExample.uniqueChromosomes (Population a_pop) [inline], [static]
Parameters
a_pop the population to verify
Returns
true if all chromosomes in the populationa are unique
Author
Klaus Meffert
Since
3.3.1
Definition at line 214 of file ConstraintExample.java.
Referenced by examples.constraint.ConstraintExample.makeChangeForAmount().
Member Data Documentation
final String examples.constraint.ConstraintExample.CVS_REVISION = `$Revision: 1.1 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 36 of file ConstraintExample.java.
EvolutionMonitor examples.constraint.ConstraintExample.m_monitor [static]
Definition at line 43 of file ConstraintExample.java.
Referenced by examples.constraint.ConstraintExample.makeChangeForAmount().
final int examples.constraint.ConstraintExample.MAX_ALLOWED_EVOLUTIONS = 200 [static], [private]
The total number of times we'll let the population evolve.
Definition at line 41 of file ConstraintExample.java.
Referenced by examples.constraint.ConstraintExample.makeChangeForAmount().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/constraint/ConstraintExample.java