examples.gp.anttrail.AntCommand Class Reference
Public Member Functions
AntCommand (final GPConfiguration a_conf) throws InvalidConfigurationException
AntCommand (final GPConfiguration a_conf, int a_arity, Class a_type) throws InvalidConfigurationException
AntMap getMap (ProgramChromosome a_chrom)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
Abstract base class for GP-commands related to the ant trail problem.
Author
Klaus Meffert
Since
3.01
Definition at line 22 of file AntCommand.java.
Constructor & Destructor Documentation
examples.gp.anttrail.AntCommand.AntCommand (final GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Definition at line 27 of file AntCommand.java.
References org.jgap.gp.CommandGene.VoidClass.
examples.gp.anttrail.AntCommand.AntCommand (final GPConfiguration a_conf, int a_arity, Class a_type) throws InvalidConfigurationException [inline]
Definition at line 32 of file AntCommand.java.
Member Function Documentation
AntMap examples.gp.anttrail.AntCommand.getMap (ProgramChromosome a_chrom) [inline]
Definition at line 37 of file AntCommand.java.
References org.jgap.gp.CommandGene.getApplicationData().
Referenced by examples.gp.anttrail.Left.execute_void(), examples.gp.anttrail.Right.execute_void(), examples.gp.anttrail.TurnToFood.execute_void(), examples.gp.anttrail.Move.execute_void(), examples.gp.anttrail.IfFoodAheadElse.execute_void(), examples.gp.anttrail.IfFoodAheadRight.execute_void(), and examples.gp.anttrail.IfFoodAheadLeft.execute_void().
Member Data Documentation
final String examples.gp.anttrail.AntCommand.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file AntCommand.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/anttrail/AntCommand.java