org.jgap.PopulationTest Class Reference
Classes
class MyFitnessEvaluator
Public Member Functions
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testConstruct_2 () throws Exception
void testConstruct_3 () throws Exception
void testAddChromosome_0 () throws Exception
void testAddChromosome_1 () throws Exception
void testAddChromosomes_0 () throws Exception
void testAddChromosomes_1 () throws Exception
void testSetChromosome_0 () throws Exception
void testSetChromosome_1 () throws Exception
void testSetChromosomes_0 () throws Exception
void testGetChromosomes_0 () throws Exception
void testGetChromosome_0 () throws Exception
void testToChromosomes_0 () throws Exception
void testDetermineFittestChromosome_0 () throws Exception
void testDetermineFittestChromosome_1 () throws Exception
void testDetermineFittestChromosome_2 () throws Exception
void testDetermineFittestChromosome_3 () throws Exception
void testDetermineFittestChromosome_4 () throws Exception
void testDetermineFittestChromosome_5 () throws Exception
void testDetermineFittestChromosome_2_0 () throws Exception
void testDetermineFittestChromosomes_1 () throws Exception
void testDetermineFittestChromosomes_2 () throws Exception
void testDetermineFittestChromosomes_3 () throws Exception
void testSize_0 () throws Exception
void testIterator_0 () throws Exception
void testContains_0 () throws Exception
void testGetGenome_0 () throws Exception
void testGetGenome_1 () throws Exception
void testGetGenome_2 () throws Exception
void testIsSerializable_0 () throws Exception
void testDoSerialize_0 () throws Exception
void testRemoveChromosome_0 () throws Exception
void testRemoveChromosome_1 () throws Exception
void testRemoveChromosome_2 () throws Exception
void testRemoveChromosome_3 () throws Exception
void testSortByFitness_0 () throws Exception
void testSortByFitness_1 () throws Exception
void testCompareTo_0 () throws Exception
void testPersistentRepresentation_0 () throws Exception
void testPersistentRepresentation_1 () throws Exception
void testPersistentRepresentation_2 () throws Exception
void testPersistentRepresentation_3 () throws Exception
void testPersistentRepresentation_4 () throws Exception
void testPersistentRepresentation_5 () throws Exception
void testPersistentRepresentation_6 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Member Functions
static Population getNewPopulation (Configuration a_conf) throws InvalidConfigurationException
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.40 $`
Additional Inherited Members
Detailed Description
Tests the Population class.
Author
Klaus Meffert
Chris Knowles
Since
2.0
Definition at line 25 of file PopulationTest.java.
Member Function Documentation
static Population org.jgap.PopulationTest.getNewPopulation (Configuration a_conf) throws InvalidConfigurationException [inline], [static], [private]
Definition at line 495 of file PopulationTest.java.
Referenced by org.jgap.PopulationTest.testDetermineFittestChromosomes_1(), org.jgap.PopulationTest.testDetermineFittestChromosomes_2(), and org.jgap.PopulationTest.testDetermineFittestChromosomes_3().
static Test org.jgap.PopulationTest.suite () [inline], [static]
Definition at line 30 of file PopulationTest.java.
void org.jgap.PopulationTest.testAddChromosome_0 () throws Exception [inline]
Definition at line 74 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.PopulationTest.testAddChromosome_1 () throws Exception [inline]
Definition at line 84 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.size().
void org.jgap.PopulationTest.testAddChromosomes_0 () throws Exception [inline]
Definition at line 91 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.PopulationTest.testAddChromosomes_1 () throws Exception [inline]
Definition at line 103 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.size().
void org.jgap.PopulationTest.testCompareTo_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 841 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.Population.compareTo(), and org.jgap.JGAPTestCase.conf.
void org.jgap.PopulationTest.testConstruct_0 () throws Exception [inline]
Definition at line 35 of file PopulationTest.java.
void org.jgap.PopulationTest.testConstruct_1 () throws Exception [inline]
Definition at line 45 of file PopulationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.PopulationTest.testConstruct_2 () throws Exception [inline]
Definition at line 54 of file PopulationTest.java.
void org.jgap.PopulationTest.testConstruct_3 () throws Exception [inline]
Definition at line 64 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.size().
void org.jgap.PopulationTest.testContains_0 () throws Exception [inline]
Definition at line 540 of file PopulationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.PopulationTest.testDetermineFittestChromosome_0 () throws Exception [inline]
Empty population
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 232 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.determineFittestChromosome().
void org.jgap.PopulationTest.testDetermineFittestChromosome_1 () throws Exception [inline]
Unordered list of fitness values of chroms in population.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 246 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.determineFittestChromosome().
void org.jgap.PopulationTest.testDetermineFittestChromosome_2 () throws Exception [inline]
Ordered list of fitness values of chroms in population.
Exceptions
Exception
Definition at line 279 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.determineFittestChromosome().
void org.jgap.PopulationTest.testDetermineFittestChromosome_2_0 () throws Exception [inline]
Test that the last chromosome in the population is preserved if it is the fittest one.
Exceptions
Exception
Author
Klaus Meffert
Since
3.3.2
Definition at line 387 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.Population.determineFittestChromosome(), and org.jgap.Population.size().
void org.jgap.PopulationTest.testDetermineFittestChromosome_3 () throws Exception [inline]
Ordered list of fitness values of chroms in population. Use fitness evaluator different from standard one.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 307 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.Population.determineFittestChromosome(), and org.jgap.Configuration.PROPERTY_FITEVAL_INST.
void org.jgap.PopulationTest.testDetermineFittestChromosome_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 334 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.determineFittestChromosomes().
void org.jgap.PopulationTest.testDetermineFittestChromosome_5 () throws Exception [inline]
Special case exposing a previous bug in method under test.
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 353 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.determineFittestChromosome().
void org.jgap.PopulationTest.testDetermineFittestChromosomes_1 () throws Exception [inline]
Exceptions
Exception
Author
Dan Clark
Klaus Meffert
Since
2.6
Definition at line 423 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.Population.determineFittestChromosomes(), and org.jgap.PopulationTest.getNewPopulation().
void org.jgap.PopulationTest.testDetermineFittestChromosomes_2 () throws Exception [inline]
Exposes bug 1422962.
Exceptions
Exception
Author
Dan Clark
Klaus Meffert
Since
2.6
Definition at line 445 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.Population.determineFittestChromosome(), and org.jgap.PopulationTest.getNewPopulation().
void org.jgap.PopulationTest.testDetermineFittestChromosomes_3 () throws Exception [inline]
Exposes bug 1422962.
Exceptions
Exception
Author
Dan Clark
Klaus Meffert
Since
2.6
Definition at line 467 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, org.jgap.Population.determineFittestChromosome(), org.jgap.PopulationTest.getNewPopulation(), and org.jgap.Population.isChanged().
void org.jgap.PopulationTest.testDoSerialize_0 () throws Exception [inline]
Ensures that Population and all objects contained implement Serializable.
Exceptions
Exception
Author
Klaus Meffert
Since
2.3
Definition at line 676 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.doSerialize().
void org.jgap.PopulationTest.testGetChromosome_0 () throws Exception [inline]
Definition at line 171 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.getChromosome().
void org.jgap.PopulationTest.testGetChromosomes_0 () throws Exception [inline]
Definition at line 155 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.getChromosomes().
void org.jgap.PopulationTest.testGetGenome_0 () throws Exception [inline]
Single chromosome.
Exceptions
Exception
Author
Klaus Meffert
Since
2.3
Definition at line 561 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.PopulationTest.testGetGenome_1 () throws Exception [inline]
Two chromosomes.
Exceptions
Exception
Author
Klaus Meffert
Since
2.3
Definition at line 587 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.isChanged().
void org.jgap.PopulationTest.testGetGenome_2 () throws Exception [inline]
Using CompositeGene.
Exceptions
Exception
Author
Klaus Meffert
Since
2.3
Definition at line 623 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.isChanged().
void org.jgap.PopulationTest.testIsSerializable_0 () throws Exception [inline]
Ensures that the Population class is implementing the Serializable interface.
Exceptions
Exception
Author
Klaus Meffert
Since
2.3
Definition at line 664 of file PopulationTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.isSerializable().
void org.jgap.PopulationTest.testIterator_0 () throws Exception [inline]
Definition at line 527 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.size().
void org.jgap.PopulationTest.testPersistentRepresentation_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 858 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.PopulationTest.testPersistentRepresentation_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 879 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.getPersistentRepresentation().
void org.jgap.PopulationTest.testPersistentRepresentation_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 900 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.size().
void org.jgap.PopulationTest.testPersistentRepresentation_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 913 of file PopulationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.PopulationTest.testPersistentRepresentation_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 932 of file PopulationTest.java.
References org.jgap.Population.CHROM_DELIMITER, and org.jgap.JGAPTestCase.conf.
void org.jgap.PopulationTest.testPersistentRepresentation_5 () throws Exception [inline]
Invalid closing tag.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 954 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.BaseChromosome.CHROM_DELIMITER, org.jgap.Population.CHROM_DELIMITER, org.jgap.Population.CHROM_DELIMITER_CLOSING, org.jgap.JGAPTestCase.conf, and org.jgap.Population.size().
void org.jgap.PopulationTest.testPersistentRepresentation_6 () throws Exception [inline]
Invalid closing tag.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 981 of file PopulationTest.java.
References org.jgap.BaseChromosome.CHROM_DELIMITER, org.jgap.Population.CHROM_DELIMITER, and org.jgap.JGAPTestCase.conf.
void org.jgap.PopulationTest.testRemoveChromosome_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 694 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.PopulationTest.testRemoveChromosome_1 () throws Exception [inline]
With illegal index.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 717 of file PopulationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.PopulationTest.testRemoveChromosome_2 () throws Exception [inline]
With illegal index.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 738 of file PopulationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.PopulationTest.testRemoveChromosome_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 758 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.PopulationTest.testSetChromosome_0 () throws Exception [inline]
Definition at line 110 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.size().
void org.jgap.PopulationTest.testSetChromosome_1 () throws Exception [inline]
Definition at line 126 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.Chromosome.equals(), org.jgap.Population.getChromosome(), and org.jgap.Population.size().
void org.jgap.PopulationTest.testSetChromosomes_0 () throws Exception [inline]
Definition at line 139 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.size().
void org.jgap.PopulationTest.testSize_0 () throws Exception [inline]
Definition at line 513 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Population.size().
void org.jgap.PopulationTest.testSortByFitness_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 775 of file PopulationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.PopulationTest.testSortByFitness_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 807 of file PopulationTest.java.
References org.jgap.JGAPTestCase.conf, org.jgap.Population.isChanged(), and org.jgap.Population.isSorted().
void org.jgap.PopulationTest.testToChromosomes_0 () throws Exception [inline]
Definition at line 191 of file PopulationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
Member Data Documentation
final String org.jgap.PopulationTest.CVS_REVISION = `$Revision: 1.40 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file PopulationTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/PopulationTest.java