org.jgap.gp.CommandGeneTest Class Reference
Classes
class AppDataForTesting
class CommandGeneImpl
Public Member Functions
void testConstruct_0 () throws Exception
void testToString_0 () throws Exception
void testSetAllele_0 () throws Exception
void testSize_0 () throws Exception
void testEquals_0 () throws Exception
void testEquals_1 () throws Exception
void testEquals_2 () throws Exception
void testEquals_3 () throws Exception
void testCleanup_0 () throws Exception
void testHashCode_0 () throws Exception
void testHashCode_1 () throws Exception
void testSetEnergy_0 () throws Exception
void testSetEnergy_1 () throws Exception
void testSetApplicationData_0 () throws Exception
void testIsCompareApplicationData_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.11 $`
Additional Inherited Members
Detailed Description
Tests the CommandGene class.
Author
Klaus Meffert
Since
3.0
Definition at line 22 of file CommandGeneTest.java.
Member Function Documentation
static Test org.jgap.gp.CommandGeneTest.suite () [inline], [static]
Definition at line 27 of file CommandGeneTest.java.
void org.jgap.gp.CommandGeneTest.testCleanup_0 () throws Exception [inline]
Simple cleanup should be possible without exception.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 158 of file CommandGeneTest.java.
References org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.CommandGeneTest.testConstruct_0 () throws Exception [inline]
Following should be possible without exception.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 40 of file CommandGeneTest.java.
References org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.CommandGeneTest.testEquals_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 93 of file CommandGeneTest.java.
References org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.CommandGeneTest.testEquals_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 107 of file CommandGeneTest.java.
References org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.CommandGeneTest.testEquals_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 121 of file CommandGeneTest.java.
References org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.CommandGeneTest.testEquals_3 () throws Exception [inline]
Compare application data.
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Todo
Todo use other than JGAPFactory to be able to receive a null CompareToHandler for the application data object
Definition at line 137 of file CommandGeneTest.java.
References org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.CommandGeneTest.testHashCode_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 170 of file CommandGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.CommandGeneTest.testHashCode_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 182 of file CommandGeneTest.java.
References org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.CommandGeneTest.testIsCompareApplicationData_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 246 of file CommandGeneTest.java.
References org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.CommandGeneTest.testSetAllele_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 63 of file CommandGeneTest.java.
References org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.CommandGeneTest.testSetApplicationData_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 228 of file CommandGeneTest.java.
References org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.CommandGeneTest.testSetEnergy_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 196 of file CommandGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.DELTA, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.CommandGeneTest.testSetEnergy_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 210 of file CommandGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.DELTA, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.CommandGeneTest.testSize_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 80 of file CommandGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.CommandGene.getArity(), org.jgap.gp.GPTestCase.m_gpconf, and org.jgap.gp.CommandGene.size().
void org.jgap.gp.CommandGeneTest.testToString_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 51 of file CommandGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.GPTestCase.m_gpconf, and org.jgap.gp.CommandGene.toString().
Member Data Documentation
final String org.jgap.gp.CommandGeneTest.CVS_REVISION = `$Revision: 1.11 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file CommandGeneTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/gp/CommandGeneTest.java