org.jgap.gp.function.SubProgram Class Reference
Public Member Functions
SubProgram (final GPConfiguration a_conf, Class[] a_types) throws InvalidConfigurationException
SubProgram (final GPConfiguration a_conf, int a_arity, Class a_types) throws InvalidConfigurationException
SubProgram (final GPConfiguration a_conf, int a_arity, Class a_types, boolean a_mutateable) throws InvalidConfigurationException
SubProgram (final GPConfiguration a_conf, int a_arity, Class a_types, int a_minArity, int a_maxArity, boolean a_mutateable) throws InvalidConfigurationException
SubProgram (final GPConfiguration a_conf, Class[] a_types, boolean a_mutateable) throws InvalidConfigurationException
SubProgram (final GPConfiguration a_conf, Class[] a_types, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException
SubProgram (final GPConfiguration a_conf, Class[] a_types, int a_subReturnType, int[] a_subChildTypes, boolean a_mutateable) throws InvalidConfigurationException
String toString ()
String getName ()
int execute_int (ProgramChromosome c, int n, Object[] args)
void execute_void (ProgramChromosome c, int n, Object[] args)
long execute_long (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
boolean isValid (ProgramChromosome a_program)
Class getChildType (IGPProgram a_ind, int a_chromNum)
int compareTo (Object a_other)
boolean equals (Object a_other)
Object clone ()
CommandGene applyMutation (int index, double a_percentage) throws InvalidConfigurationException
CommandGene applyMutation () throws InvalidConfigurationException
Private Attributes
int m_subtrees
int m_minArity
int m_maxArity
Class[] m_types
boolean m_mutateable
int m_mode
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.18 $`
Additional Inherited Members
Detailed Description
A connector for independent subprograms (subtrees). Each subtree except the last one must have a memory- or stack-modifying command (such as push or store), otherwise there is no connection between the subtrees (which would be useless bloating).
Author
Klaus Meffert
Since
3.0
Definition at line 27 of file SubProgram.java.
Constructor & Destructor Documentation
org.jgap.gp.function.SubProgram.SubProgram (final GPConfiguration a_conf, Class[] a_types) throws InvalidConfigurationException [inline]
Definition at line 56 of file SubProgram.java.
Referenced by org.jgap.gp.function.SubProgram.applyMutation(), org.jgap.gp.function.SubProgram.clone(), org.jgap.gp.function.SubProgram.compareTo(), and org.jgap.gp.function.SubProgram.equals().
org.jgap.gp.function.SubProgram.SubProgram (final GPConfiguration a_conf, int a_arity, Class a_types) throws InvalidConfigurationException [inline]
Collage constructor: Create a sub program that has a_arity elements of the same type a_types.
Parameters
a_conf the configuration to use
a_arity number of children in the collage
a_types uniform type of all children
Exceptions
org.jgap.InvalidConfigurationException
Author
Klaus Meffert
Since
3.4
Definition at line 73 of file SubProgram.java.
org.jgap.gp.function.SubProgram.SubProgram (final GPConfiguration a_conf, int a_arity, Class a_types, boolean a_mutateable) throws InvalidConfigurationException [inline]
Collage constructor: Create a sub program that has a_arity elements of the same type a_types.
Parameters
a_conf the configuration to use
a_arity number of children in the collage
a_types uniform type of all children
a_mutateable true: allow mutation of the sub program, i.e., the number of children (=arity) may be varied automatically during evolution
Exceptions
org.jgap.InvalidConfigurationException
Author
Klaus Meffert
Since
3.4
Definition at line 92 of file SubProgram.java.
org.jgap.gp.function.SubProgram.SubProgram (final GPConfiguration a_conf, int a_arity, Class a_types, int a_minArity, int a_maxArity, boolean a_mutateable) throws InvalidConfigurationException [inline]
Definition at line 98 of file SubProgram.java.
References org.jgap.gp.function.SubProgram.m_maxArity, org.jgap.gp.function.SubProgram.m_minArity, org.jgap.gp.function.SubProgram.m_mode, org.jgap.gp.function.SubProgram.m_mutateable, org.jgap.gp.function.SubProgram.m_subtrees, and org.jgap.gp.function.SubProgram.m_types.
org.jgap.gp.function.SubProgram.SubProgram (final GPConfiguration a_conf, Class[] a_types, boolean a_mutateable) throws InvalidConfigurationException [inline]
Definition at line 124 of file SubProgram.java.
org.jgap.gp.function.SubProgram.SubProgram (final GPConfiguration a_conf, Class[] a_types, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException [inline]
Definition at line 130 of file SubProgram.java.
org.jgap.gp.function.SubProgram.SubProgram (final GPConfiguration a_conf, Class[] a_types, int a_subReturnType, int[] a_subChildTypes, boolean a_mutateable) throws InvalidConfigurationException [inline]
Definition at line 136 of file SubProgram.java.
References org.jgap.gp.function.SubProgram.m_maxArity, org.jgap.gp.function.SubProgram.m_minArity, org.jgap.gp.function.SubProgram.m_mode, org.jgap.gp.function.SubProgram.m_mutateable, org.jgap.gp.function.SubProgram.m_subtrees, and org.jgap.gp.function.SubProgram.m_types.
Member Function Documentation
CommandGene org.jgap.gp.function.SubProgram.applyMutation (int a_index, double a_percentage) throws InvalidConfigurationException [inline]
Mutates a CommandGene.
Parameters
a_index references the part of a multipart object, normally not relevant
a_percentage the mutation rate (0.0 to 1.0)
Returns
the mutant
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IMutateable.
Definition at line 329 of file SubProgram.java.
References org.jgap.gp.function.SubProgram.applyMutation(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.function.SubProgram.m_mutateable.
CommandGene org.jgap.gp.function.SubProgram.applyMutation () throws InvalidConfigurationException [inline]
Todo
Todo use dynamizeArity instead!
Returns
mutated command gene
Exceptions
InvalidConfigurationException
Definition at line 349 of file SubProgram.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getSubChildTypes(), org.jgap.gp.CommandGene.getSubReturnType(), org.jgap.gp.function.SubProgram.m_maxArity, org.jgap.gp.function.SubProgram.m_minArity, org.jgap.gp.function.SubProgram.m_mode, org.jgap.gp.function.SubProgram.m_mutateable, org.jgap.gp.function.SubProgram.m_types, org.jgap.gp.CommandGene.size(), and org.jgap.gp.function.SubProgram.SubProgram().
Referenced by org.jgap.gp.function.SubProgram.applyMutation().
Object org.jgap.gp.function.SubProgram.clone () [inline]
Returns
deep clone of this instance
Author
Klaus Meffert
Since
3.2
Implements org.jgap.util.ICloneable.
Definition at line 291 of file SubProgram.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getSubChildTypes(), org.jgap.gp.CommandGene.getSubReturnType(), org.jgap.gp.function.SubProgram.m_maxArity, org.jgap.gp.function.SubProgram.m_minArity, org.jgap.gp.function.SubProgram.m_mode, org.jgap.gp.function.SubProgram.m_mutateable, org.jgap.gp.function.SubProgram.m_subtrees, org.jgap.gp.function.SubProgram.m_types, and org.jgap.gp.function.SubProgram.SubProgram().
int org.jgap.gp.function.SubProgram.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.0
Definition at line 254 of file SubProgram.java.
References org.jgap.gp.function.SubProgram.m_types, and org.jgap.gp.function.SubProgram.SubProgram().
boolean org.jgap.gp.function.SubProgram.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Klaus Meffert
Since
3.0
Definition at line 274 of file SubProgram.java.
References org.jgap.gp.function.SubProgram.m_types, and org.jgap.gp.function.SubProgram.SubProgram().
double org.jgap.gp.function.SubProgram.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 215 of file SubProgram.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.function.SubProgram.m_subtrees.
float org.jgap.gp.function.SubProgram.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 206 of file SubProgram.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.function.SubProgram.m_subtrees.
int org.jgap.gp.function.SubProgram.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Todo
Todo evaluate m_types
Definition at line 172 of file SubProgram.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.function.SubProgram.m_subtrees.
long org.jgap.gp.function.SubProgram.execute_long (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 197 of file SubProgram.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.function.SubProgram.m_subtrees.
Object org.jgap.gp.function.SubProgram.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 224 of file SubProgram.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.function.SubProgram.m_subtrees.
void org.jgap.gp.function.SubProgram.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Todo
Todo evaluate m_types
Definition at line 190 of file SubProgram.java.
References org.jgap.gp.CommandGene.check(), and org.jgap.gp.function.SubProgram.m_subtrees.
Class org.jgap.gp.function.SubProgram.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Definition at line 237 of file SubProgram.java.
References org.jgap.gp.function.SubProgram.m_types.
String org.jgap.gp.function.SubProgram.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 168 of file SubProgram.java.
boolean org.jgap.gp.function.SubProgram.isValid (ProgramChromosome a_program) [inline]
Definition at line 233 of file SubProgram.java.
String org.jgap.gp.function.SubProgram.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 153 of file SubProgram.java.
References org.jgap.gp.function.SubProgram.m_subtrees.
Member Data Documentation
final String org.jgap.gp.function.SubProgram.CVS_REVISION = `$Revision: 1.18 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 30 of file SubProgram.java.
int org.jgap.gp.function.SubProgram.m_maxArity [private]
Maximum arity allowed during mutation of arity.
Definition at line 45 of file SubProgram.java.
Referenced by org.jgap.gp.function.SubProgram.applyMutation(), org.jgap.gp.function.SubProgram.clone(), and org.jgap.gp.function.SubProgram.SubProgram().
int org.jgap.gp.function.SubProgram.m_minArity [private]
Minimum arity allowed during mutation of arity.
Definition at line 40 of file SubProgram.java.
Referenced by org.jgap.gp.function.SubProgram.applyMutation(), org.jgap.gp.function.SubProgram.clone(), and org.jgap.gp.function.SubProgram.SubProgram().
int org.jgap.gp.function.SubProgram.m_mode [private]
Definition at line 54 of file SubProgram.java.
Referenced by org.jgap.gp.function.SubProgram.applyMutation(), org.jgap.gp.function.SubProgram.clone(), and org.jgap.gp.function.SubProgram.SubProgram().
boolean org.jgap.gp.function.SubProgram.m_mutateable [private]
Definition at line 52 of file SubProgram.java.
Referenced by org.jgap.gp.function.SubProgram.applyMutation(), org.jgap.gp.function.SubProgram.clone(), and org.jgap.gp.function.SubProgram.SubProgram().
int org.jgap.gp.function.SubProgram.m_subtrees [private]
Number of subprograms. Redundant, because equal to m_types.length.
Definition at line 35 of file SubProgram.java.
Referenced by org.jgap.gp.function.SubProgram.clone(), org.jgap.gp.function.SubProgram.execute_double(), org.jgap.gp.function.SubProgram.execute_float(), org.jgap.gp.function.SubProgram.execute_int(), org.jgap.gp.function.SubProgram.execute_long(), org.jgap.gp.function.SubProgram.execute_object(), org.jgap.gp.function.SubProgram.execute_void(), org.jgap.gp.function.SubProgram.SubProgram(), and org.jgap.gp.function.SubProgram.toString().
Class [] org.jgap.gp.function.SubProgram.m_types [private]
Return types of the subprograms to excecute.
Definition at line 50 of file SubProgram.java.
Referenced by org.jgap.gp.function.SubProgram.applyMutation(), org.jgap.gp.function.SubProgram.clone(), org.jgap.gp.function.SubProgram.compareTo(), org.jgap.gp.function.SubProgram.equals(), org.jgap.gp.function.SubProgram.getChildType(), and org.jgap.gp.function.SubProgram.SubProgram().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/SubProgram.java