examples.gp.paintedDesert.AntMap Class Reference
Public Member Functions
AntMap (final int[][] a_map, Ant[] a_ants)
void placeSand (int sandColor, int x, int y)
int atLocation (int x, int y)
int[][] getMap ()
int[][] getInitialMap ()
boolean sandAtLocation (int x, int y)
boolean sandBelongsHere (int sandColor, int x)
boolean mayDropSand (int x, int y)
int removeSand (int x, int y)
Ant getAnt ()
void finalize ()
int fitness ()
Ant nextAnt ()
int getMoveCount ()
int getWidth ()
int getHeight ()
Ant[] getAnts ()
void init ()
void resetMap ()
Static Public Attributes
static final int EMPTY = -1
static final int BLACK = 0
static final int GRAY = 1
static final int STRIPED = 2
static final int ANT_AT_POSITION = 9
Private Member Functions
int fitnessValue (int[][] antmap, int sandColor, int x, int y)
void placeNear (int sandType, int x, int y)
Private Attributes
int m_currentAnt
int[][] m_initialPosition
int m_sizex
int m_sizey
int m_popSize = 1
int[][] m_currentMap
Ant[] m_ants
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Detailed Description
Holds the map of the painted desert sand locations
Author
Scott Mueller
Since
3.2
Definition at line 18 of file AntMap.java.
Constructor & Destructor Documentation
examples.gp.paintedDesert.AntMap.AntMap (final int a_map[][], Ant[] a_ants) [inline]
Maximum number of moves allowed. Creates the map.
Parameters
a_map the map itself
a_ants the list of ants
Definition at line 98 of file AntMap.java.
References examples.gp.paintedDesert.AntMap.ANT_AT_POSITION, examples.gp.paintedDesert.AntMap.m_ants, examples.gp.paintedDesert.AntMap.m_currentAnt, examples.gp.paintedDesert.AntMap.m_currentMap, examples.gp.paintedDesert.AntMap.m_initialPosition, examples.gp.paintedDesert.AntMap.m_popSize, examples.gp.paintedDesert.AntMap.m_sizex, and examples.gp.paintedDesert.AntMap.m_sizey.
Member Function Documentation
int examples.gp.paintedDesert.AntMap.atLocation (int x, int y) [inline]
Returns the color of sand at the provided location
Parameters
x
y
Returns
Definition at line 136 of file AntMap.java.
References examples.gp.paintedDesert.AntMap.m_currentMap.
Referenced by examples.gp.paintedDesert.Ant.drop(), and examples.gp.paintedDesert.Ant.pickup().
void examples.gp.paintedDesert.AntMap.finalize () [inline]
Determine the final position of grains of sand. If an ant is carrying sand and there is no sand at the current position, drop the sand at this position. If there is sand, rubberband the sand back to where the ant picked up the sand. If both locations are full, then pick the nearest open spot
See Also
java.lang.Object::finalize()
Definition at line 217 of file AntMap.java.
References examples.gp.paintedDesert.AntMap.EMPTY, examples.gp.paintedDesert.AntMap.getAnts(), examples.gp.paintedDesert.AntMap.getMap(), examples.gp.paintedDesert.AntMap.m_popSize, and examples.gp.paintedDesert.AntMap.placeNear().
int examples.gp.paintedDesert.AntMap.fitness () [inline]
Calculates how well the sand is moved to the proper columns.
Returns
Definition at line 251 of file AntMap.java.
References examples.gp.paintedDesert.AntMap.EMPTY, examples.gp.paintedDesert.AntMap.fitnessValue(), and examples.gp.paintedDesert.AntMap.getMap().
int examples.gp.paintedDesert.AntMap.fitnessValue (int antmap[][], int sandColor, int x, int y) [inline], [private]
Calculates the fitness value for a single grain of sand
Parameters
antmap
sandColor
x
y
Returns
Definition at line 285 of file AntMap.java.
Referenced by examples.gp.paintedDesert.AntMap.fitness().
Ant examples.gp.paintedDesert.AntMap.getAnt () [inline]
Returns the current Ant. The current ant is incremented by the NextAnt method.
Returns
Definition at line 203 of file AntMap.java.
References examples.gp.paintedDesert.AntMap.getAnts(), and examples.gp.paintedDesert.AntMap.m_currentAnt.
Referenced by examples.gp.paintedDesert.IfDrop.execute_void().
Ant [] examples.gp.paintedDesert.AntMap.getAnts () [inline]
Returns this list of ants
Returns
Definition at line 394 of file AntMap.java.
References examples.gp.paintedDesert.AntMap.m_ants.
Referenced by examples.gp.paintedDesert.AntMap.finalize(), examples.gp.paintedDesert.AntMap.getAnt(), examples.gp.paintedDesert.AntMap.getMoveCount(), and examples.gp.paintedDesert.AntMap.nextAnt().
int examples.gp.paintedDesert.AntMap.getHeight () [inline]
Returns the height of the map
Returns
Definition at line 386 of file AntMap.java.
References examples.gp.paintedDesert.AntMap.m_sizey.
Referenced by examples.gp.paintedDesert.Ant.goN(), and examples.gp.paintedDesert.Ant.moveRandom().
int [][] examples.gp.paintedDesert.AntMap.getInitialMap () [inline]
Returns a representation of the initial map
Returns
Definition at line 152 of file AntMap.java.
int [][] examples.gp.paintedDesert.AntMap.getMap () [inline]
Returns a representation of the current map
Returns
Definition at line 144 of file AntMap.java.
Referenced by examples.gp.paintedDesert.AntMap.finalize(), examples.gp.paintedDesert.AntMap.fitness(), examples.gp.paintedDesert.Ant.moveRandom(), and examples.gp.paintedDesert.AntMap.placeNear().
int examples.gp.paintedDesert.AntMap.getMoveCount () [inline]
Asks each ant for the number of moves and sums up the result.
Returns
Definition at line 364 of file AntMap.java.
References examples.gp.paintedDesert.AntMap.getAnts(), and examples.gp.paintedDesert.AntMap.m_popSize.
int examples.gp.paintedDesert.AntMap.getWidth () [inline]
Returns the width of the map
Returns
Definition at line 378 of file AntMap.java.
References examples.gp.paintedDesert.AntMap.m_sizex.
Referenced by examples.gp.paintedDesert.Ant.goE().
void examples.gp.paintedDesert.AntMap.init () [inline]
Definition at line 398 of file AntMap.java.
References examples.gp.paintedDesert.AntMap.resetMap().
boolean examples.gp.paintedDesert.AntMap.mayDropSand (int x, int y) [inline]
Identifies that sand may be placed here
Parameters
x
y
Returns
Definition at line 182 of file AntMap.java.
References examples.gp.paintedDesert.AntMap.EMPTY.
Ant examples.gp.paintedDesert.AntMap.nextAnt () [inline]
Increments the index to the next ant.
Returns
Definition at line 348 of file AntMap.java.
References examples.gp.paintedDesert.AntMap.getAnts(), examples.gp.paintedDesert.AntMap.m_currentAnt, and examples.gp.paintedDesert.AntMap.m_popSize.
void examples.gp.paintedDesert.AntMap.placeNear (int sandType, int x, int y) [inline], [private]
Places the grain of sand near where the current location is at.
Parameters
sandType
x
y
Definition at line 304 of file AntMap.java.
References examples.gp.paintedDesert.AntMap.EMPTY, examples.gp.paintedDesert.AntMap.getMap(), examples.gp.paintedDesert.AntMap.m_sizex, and examples.gp.paintedDesert.AntMap.m_sizey.
Referenced by examples.gp.paintedDesert.AntMap.finalize().
void examples.gp.paintedDesert.AntMap.placeSand (int sandColor, int x, int y) [inline]
Places sand or identifies an empty spot at the current position
Parameters
sandColor
x
y
Definition at line 126 of file AntMap.java.
References examples.gp.paintedDesert.AntMap.m_currentMap.
int examples.gp.paintedDesert.AntMap.removeSand (int x, int y) [inline]
Removes the sand from the current position
Parameters
x
y
Returns
Definition at line 192 of file AntMap.java.
References examples.gp.paintedDesert.AntMap.EMPTY.
void examples.gp.paintedDesert.AntMap.resetMap () [inline]
Resets the sand and ant back to their positions before the program was applied
Definition at line 406 of file AntMap.java.
References examples.gp.paintedDesert.AntMap.m_ants, examples.gp.paintedDesert.AntMap.m_currentAnt, examples.gp.paintedDesert.AntMap.m_currentMap, examples.gp.paintedDesert.AntMap.m_initialPosition, examples.gp.paintedDesert.AntMap.m_sizex, and examples.gp.paintedDesert.AntMap.m_sizey.
Referenced by examples.gp.paintedDesert.AntMap.init().
boolean examples.gp.paintedDesert.AntMap.sandAtLocation (int x, int y) [inline]
Identifies whether there is sand at the provided location
Parameters
x
y
Returns
Definition at line 162 of file AntMap.java.
References examples.gp.paintedDesert.AntMap.EMPTY.
boolean examples.gp.paintedDesert.AntMap.sandBelongsHere (int sandColor, int x) [inline]
Identifies that sand is at that location
Parameters
sandColor
x
Returns
Definition at line 172 of file AntMap.java.
Member Data Documentation
final int examples.gp.paintedDesert.AntMap.ANT_AT_POSITION = 9 [static]
Ant at this location
Definition at line 52 of file AntMap.java.
Referenced by examples.gp.paintedDesert.AntMap.AntMap(), and examples.gp.paintedDesert.Ant.moveRandom().
final int examples.gp.paintedDesert.AntMap.BLACK = 0 [static]
Black sand at this location or carried by the ant
Definition at line 37 of file AntMap.java.
Referenced by examples.gp.paintedDesert.PaintedDesertProblem.readMap().
final String examples.gp.paintedDesert.AntMap.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 20 of file AntMap.java.
final int examples.gp.paintedDesert.AntMap.EMPTY = -1 [static]
No Sand at this location or carried by the ant
Definition at line 32 of file AntMap.java.
Referenced by examples.gp.paintedDesert.Ant.drop(), examples.gp.paintedDesert.AntMap.finalize(), examples.gp.paintedDesert.AntMap.fitness(), examples.gp.paintedDesert.Ant.isCarrying(), examples.gp.paintedDesert.AntMap.mayDropSand(), examples.gp.paintedDesert.Ant.pickup(), examples.gp.paintedDesert.AntMap.placeNear(), examples.gp.paintedDesert.PaintedDesertProblem.readMap(), examples.gp.paintedDesert.AntMap.removeSand(), examples.gp.paintedDesert.Ant.reset(), and examples.gp.paintedDesert.AntMap.sandAtLocation().
final int examples.gp.paintedDesert.AntMap.GRAY = 1 [static]
Gray sand at this location or carried by the ant
Definition at line 42 of file AntMap.java.
Referenced by examples.gp.paintedDesert.PaintedDesertProblem.readMap().
Ant [] examples.gp.paintedDesert.AntMap.m_ants [private]
Holds the list of ants
Definition at line 84 of file AntMap.java.
Referenced by examples.gp.paintedDesert.AntMap.AntMap(), examples.gp.paintedDesert.AntMap.getAnts(), and examples.gp.paintedDesert.AntMap.resetMap().
int examples.gp.paintedDesert.AntMap.m_currentAnt [private]
Holds the instance of the ant being processed. Assumption that some external single threaded process will loop through all the ants using nextAnt to sequence through the ants. It is expected that the clients of the AntMap can use getAnt() to return the Ant instance at the currentAnt index.
Definition at line 26 of file AntMap.java.
Referenced by examples.gp.paintedDesert.AntMap.AntMap(), examples.gp.paintedDesert.AntMap.getAnt(), examples.gp.paintedDesert.AntMap.nextAnt(), and examples.gp.paintedDesert.AntMap.resetMap().
int [][] examples.gp.paintedDesert.AntMap.m_currentMap [private]
Holder of the current map.
Sand is indicated by AntMap.EMPTY|GRAY|STRIPED|BLACK
Definition at line 79 of file AntMap.java.
Referenced by examples.gp.paintedDesert.AntMap.AntMap(), examples.gp.paintedDesert.AntMap.atLocation(), examples.gp.paintedDesert.AntMap.placeSand(), and examples.gp.paintedDesert.AntMap.resetMap().
int [][] examples.gp.paintedDesert.AntMap.m_initialPosition [private]
Initial sand position as [x][y]
Definition at line 57 of file AntMap.java.
Referenced by examples.gp.paintedDesert.AntMap.AntMap(), and examples.gp.paintedDesert.AntMap.resetMap().
int examples.gp.paintedDesert.AntMap.m_popSize = 1 [private]
Population size.
Definition at line 72 of file AntMap.java.
Referenced by examples.gp.paintedDesert.AntMap.AntMap(), examples.gp.paintedDesert.AntMap.finalize(), examples.gp.paintedDesert.AntMap.getMoveCount(), and examples.gp.paintedDesert.AntMap.nextAnt().
int examples.gp.paintedDesert.AntMap.m_sizex [private]
Width of map.
Definition at line 62 of file AntMap.java.
Referenced by examples.gp.paintedDesert.AntMap.AntMap(), examples.gp.paintedDesert.AntMap.getWidth(), examples.gp.paintedDesert.AntMap.placeNear(), and examples.gp.paintedDesert.AntMap.resetMap().
int examples.gp.paintedDesert.AntMap.m_sizey [private]
Height of map.
Definition at line 67 of file AntMap.java.
Referenced by examples.gp.paintedDesert.AntMap.AntMap(), examples.gp.paintedDesert.AntMap.getHeight(), examples.gp.paintedDesert.AntMap.placeNear(), and examples.gp.paintedDesert.AntMap.resetMap().
final int examples.gp.paintedDesert.AntMap.STRIPED = 2 [static]
Striped sand at this location or carried by the ant
Definition at line 47 of file AntMap.java.
Referenced by examples.gp.paintedDesert.PaintedDesertProblem.readMap().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/paintedDesert/AntMap.java