org.jgap.gp.function.IfDyn Class Reference
Public Member Functions
IfDyn (final GPConfiguration a_conf, Class a_returnType, int a_arityInitial, int a_arityMin, int a_arityMax) throws InvalidConfigurationException
String toString ()
boolean execute_boolean (ProgramChromosome c, int n, Object[] args)
void execute_void (ProgramChromosome c, int n, Object[] args)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Additional Inherited Members
Detailed Description
The if-then construct with a dynamic number of children.
Author
Klaus Meffert
Since
3.4
Definition at line 23 of file IfDyn.java.
Constructor & Destructor Documentation
org.jgap.gp.function.IfDyn.IfDyn (final GPConfiguration a_conf, Class a_returnType, int a_arityInitial, int a_arityMin, int a_arityMax) throws InvalidConfigurationException [inline]
Definition at line 28 of file IfDyn.java.
Referenced by org.jgap.gp.function.IfDyn.clone().
Member Function Documentation
Object org.jgap.gp.function.IfDyn.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 82 of file IfDyn.java.
References org.jgap.gp.CommandGene.getArity(), org.jgap.gp.CommandGene.getArityMax(), org.jgap.gp.CommandGene.getArityMin(), org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.function.IfDyn.IfDyn().
boolean org.jgap.gp.function.IfDyn.execute_boolean (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 47 of file IfDyn.java.
References org.jgap.gp.CommandGene.size().
void org.jgap.gp.function.IfDyn.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Todo
Todo add option for type of first child to constructor
Definition at line 62 of file IfDyn.java.
References org.jgap.gp.CommandGene.size().
String org.jgap.gp.function.IfDyn.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 35 of file IfDyn.java.
References org.jgap.gp.CommandGene.size().
Member Data Documentation
final String org.jgap.gp.function.IfDyn.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file IfDyn.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/IfDyn.java