org.jgap.impl.RandomGeneratorForTesting Class Reference
Public Member Functions
RandomGeneratorForTesting ()
RandomGeneratorForTesting (int a_nextInt)
RandomGeneratorForTesting (double a_nextDouble)
RandomGeneratorForTesting (float a_nextFloat)
RandomGeneratorForTesting (long a_nextLong)
RandomGeneratorForTesting (boolean a_nextBoolean)
int nextInt ()
int nextInt (int a_ceiling)
long nextLong ()
double nextDouble ()
double nextGaussian ()
float nextFloat ()
boolean nextBoolean ()
void setNextBoolean (boolean a_nextBoolean)
void setNextDouble (double a_nextDouble)
void setNextGaussian (double a_nextDouble)
void setNextFloat (float a_nextFloat)
void setNextInt (int a_nextInt)
void setNextLong (long a_nextLong)
void setNextFloatSequence (float[] a_sequence)
void setNextIntSequence (int[] a_sequence)
Private Attributes
long m_nextLong
double m_nextDouble
boolean m_nextBoolean
int[] m_nextIntSequence
float[] m_nextFloatSequence
double m_nextGaussian
int m_intIndex
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Additional Inherited Members
Detailed Description
A random generator only determined for testing purposes. With this, you can specify the next value which will be returned. It is also possible to specify a sequence to be produced.
Author
Klaus Meffert
Since
1.1
Definition at line 22 of file RandomGeneratorForTesting.java.
Constructor & Destructor Documentation
org.jgap.impl.RandomGeneratorForTesting.RandomGeneratorForTesting () [inline]
Definition at line 36 of file RandomGeneratorForTesting.java.
org.jgap.impl.RandomGeneratorForTesting.RandomGeneratorForTesting (int a_nextInt) [inline]
Definition at line 39 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.setNextInt().
org.jgap.impl.RandomGeneratorForTesting.RandomGeneratorForTesting (double a_nextDouble) [inline]
Definition at line 44 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.setNextDouble().
org.jgap.impl.RandomGeneratorForTesting.RandomGeneratorForTesting (float a_nextFloat) [inline]
Definition at line 49 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.setNextFloat().
org.jgap.impl.RandomGeneratorForTesting.RandomGeneratorForTesting (long a_nextLong) [inline]
Definition at line 54 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.setNextLong().
org.jgap.impl.RandomGeneratorForTesting.RandomGeneratorForTesting (boolean a_nextBoolean) [inline]
Definition at line 59 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.setNextBoolean(), and org.jgap.impl.RandomGeneratorForTesting.setNextInt().
Member Function Documentation
boolean org.jgap.impl.RandomGeneratorForTesting.nextBoolean () [inline]
Returns the next pseudorandom, uniformly distributed boolean value from this random number generator's sequence. The general contract of nextBoolean is that one boolean value is pseudorandomly generated and returned. The values true and false are produced with (approximately) equal probability.
Returns
a pseudorandom boolean value
Author
Neil Rotstan
Since
1.0
Implements org.jgap.RandomGenerator.
Definition at line 97 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.m_nextBoolean.
double org.jgap.impl.RandomGeneratorForTesting.nextDouble () [inline]
Returns the next pseudorandom, uniformly distributed double value between 0.0 and 1.0 from this random number generator's sequence.
Returns
a psuedorandom double value GREATER/EQUAL 0 AND LESS THAN 1
Author
Neil Rotstan
Since
1.0
Implements org.jgap.RandomGenerator.
Definition at line 81 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.m_nextDouble.
float org.jgap.impl.RandomGeneratorForTesting.nextFloat () [inline]
Returns the next pseudorandom, uniformly distributed float value between 0.0 and 1.0 from this random number generator's sequence.
Returns
a psuedorandom float value
Author
Neil Rotstan
Since
1.0
Implements org.jgap.RandomGenerator.
Definition at line 89 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.m_nextFloatSequence.
double org.jgap.impl.RandomGeneratorForTesting.nextGaussian () [inline]
Definition at line 85 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.m_nextGaussian.
int org.jgap.impl.RandomGeneratorForTesting.nextInt () [inline]
Returns the next pseudorandom, uniformly distributed int value from this random number generator's sequence. The general contract of nextInt is that one int value is pseudorandomly generated and returned. All 2^32 possible int values are produced with (approximately) equal probability.
Returns
a pseudorandom integer value
Author
Neil Rotstan
Since
1.0
Implements org.jgap.RandomGenerator.
Definition at line 65 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.m_intIndex, and org.jgap.impl.RandomGeneratorForTesting.m_nextIntSequence.
Referenced by org.jgap.impl.RandomGeneratorForTesting.nextInt().
int org.jgap.impl.RandomGeneratorForTesting.nextInt (int a_ceiling) [inline]
Returns a pseudorandom, uniformly distributed int value between 0 (inclusive) and the specified value (exclusive), drawn from this random number generator's sequence. The general contract of nextInt is that one int value in the specified range is pseudorandomly generated and returned. All n possible int values are produced with (approximately) equal probability.
Parameters
a_ceiling the upper boundary excluded
Returns
a pseudorandom integer value between 0 and the given ceiling - 1, inclusive
Author
Neil Rotstan
Since
1.0
Implements org.jgap.RandomGenerator.
Definition at line 73 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.nextInt().
long org.jgap.impl.RandomGeneratorForTesting.nextLong () [inline]
Returns the next pseudorandom, uniformly distributed long value from this random number generator's sequence. The general contract of nextLong() is that one long value is pseudorandomly generated and returned. All 2^64 possible long values are produced with (approximately) equal probability.
Returns
a psuedorandom long value
Author
Neil Rotstan
Since
1.0
Implements org.jgap.RandomGenerator.
Definition at line 77 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.m_nextLong.
void org.jgap.impl.RandomGeneratorForTesting.setNextBoolean (boolean a_nextBoolean) [inline]
Definition at line 101 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.m_nextBoolean.
Referenced by org.jgap.impl.RandomGeneratorForTesting.RandomGeneratorForTesting().
void org.jgap.impl.RandomGeneratorForTesting.setNextDouble (double a_nextDouble) [inline]
Definition at line 105 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.m_nextDouble.
Referenced by org.jgap.impl.RandomGeneratorForTesting.RandomGeneratorForTesting().
void org.jgap.impl.RandomGeneratorForTesting.setNextFloat (float a_nextFloat) [inline]
Definition at line 113 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.setNextFloatSequence().
Referenced by org.jgap.impl.RandomGeneratorForTesting.RandomGeneratorForTesting().
void org.jgap.impl.RandomGeneratorForTesting.setNextFloatSequence (float[] a_sequence) [inline]
Definition at line 125 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.m_nextFloatSequence.
Referenced by org.jgap.impl.RandomGeneratorForTesting.setNextFloat().
void org.jgap.impl.RandomGeneratorForTesting.setNextGaussian (double a_nextDouble) [inline]
Definition at line 109 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.m_nextGaussian.
void org.jgap.impl.RandomGeneratorForTesting.setNextInt (int a_nextInt) [inline]
Definition at line 117 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.setNextIntSequence().
Referenced by org.jgap.impl.RandomGeneratorForTesting.RandomGeneratorForTesting().
void org.jgap.impl.RandomGeneratorForTesting.setNextIntSequence (int[] a_sequence) [inline]
Definition at line 130 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.m_intIndex, and org.jgap.impl.RandomGeneratorForTesting.m_nextIntSequence.
Referenced by org.jgap.impl.RandomGeneratorForTesting.setNextInt().
void org.jgap.impl.RandomGeneratorForTesting.setNextLong (long a_nextLong) [inline]
Definition at line 121 of file RandomGeneratorForTesting.java.
References org.jgap.impl.RandomGeneratorForTesting.m_nextLong.
Referenced by org.jgap.impl.RandomGeneratorForTesting.RandomGeneratorForTesting().
Member Data Documentation
final String org.jgap.impl.RandomGeneratorForTesting.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file RandomGeneratorForTesting.java.
int org.jgap.impl.RandomGeneratorForTesting.m_intIndex [private]
Definition at line 34 of file RandomGeneratorForTesting.java.
Referenced by org.jgap.impl.RandomGeneratorForTesting.nextInt(), and org.jgap.impl.RandomGeneratorForTesting.setNextIntSequence().
boolean org.jgap.impl.RandomGeneratorForTesting.m_nextBoolean [private]
Definition at line 30 of file RandomGeneratorForTesting.java.
Referenced by org.jgap.impl.RandomGeneratorForTesting.nextBoolean(), and org.jgap.impl.RandomGeneratorForTesting.setNextBoolean().
double org.jgap.impl.RandomGeneratorForTesting.m_nextDouble [private]
Definition at line 29 of file RandomGeneratorForTesting.java.
Referenced by org.jgap.impl.RandomGeneratorForTesting.nextDouble(), and org.jgap.impl.RandomGeneratorForTesting.setNextDouble().
float [] org.jgap.impl.RandomGeneratorForTesting.m_nextFloatSequence [private]
Definition at line 32 of file RandomGeneratorForTesting.java.
Referenced by org.jgap.impl.RandomGeneratorForTesting.nextFloat(), and org.jgap.impl.RandomGeneratorForTesting.setNextFloatSequence().
double org.jgap.impl.RandomGeneratorForTesting.m_nextGaussian [private]
Definition at line 33 of file RandomGeneratorForTesting.java.
Referenced by org.jgap.impl.RandomGeneratorForTesting.nextGaussian(), and org.jgap.impl.RandomGeneratorForTesting.setNextGaussian().
int [] org.jgap.impl.RandomGeneratorForTesting.m_nextIntSequence [private]
Definition at line 31 of file RandomGeneratorForTesting.java.
Referenced by org.jgap.impl.RandomGeneratorForTesting.nextInt(), and org.jgap.impl.RandomGeneratorForTesting.setNextIntSequence().
long org.jgap.impl.RandomGeneratorForTesting.m_nextLong [private]
Definition at line 28 of file RandomGeneratorForTesting.java.
Referenced by org.jgap.impl.RandomGeneratorForTesting.nextLong(), and org.jgap.impl.RandomGeneratorForTesting.setNextLong().
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/RandomGeneratorForTesting.java