org.jgap.impl.MutipleIntegerGene Class Reference
Public Member Functions
MutipleIntegerGene () throws InvalidConfigurationException
MutipleIntegerGene (final Configuration a_config) throws InvalidConfigurationException
MutipleIntegerGene (final Configuration a_config, final int a_lowerBound, final int a_upperBound, final int a_significance) throws InvalidConfigurationException
String getPersistentRepresentation ()
void setValueFromPersistentRepresentation (final String a_representation) throws UnsupportedRepresentationException
void setToRandomValue (final RandomGenerator a_numberGenerator)
void applyMutation (final int a_index, final double a_percentage)
int hashCode ()
String toString ()
int getLowerBounds ()
int getUpperBounds ()
int getSignificance ()
Protected Member Functions
Gene newGeneInternal ()
int compareToNative (final Object a_o1, final Object a_o2)
void mapValueToWithinBounds ()
Static Protected Attributes
static final long INTEGER_RANGE
Private Member Functions
Integer getRandomValue (RandomGenerator a_numberGenerator)
int round (double value, Integer factor)
Private Attributes
int m_upperBounds
int m_lowerBounds
int m_significance
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Additional Inherited Members
Detailed Description
Extension of IntegerGene. The only difference is that this gene allele has to be a multiple of a specific significance, ie
Gene gene = new MutipleIntegerGene(configuration, -100,100,3);
The genes allele must be between -100 and 100 and be a multiple of 3.
Author
Chris Jones
Since
3.5
Definition at line 27 of file MutipleIntegerGene.java.
Constructor & Destructor Documentation
org.jgap.impl.MutipleIntegerGene.MutipleIntegerGene () throws InvalidConfigurationException [inline]
Definition at line 56 of file MutipleIntegerGene.java.
Referenced by org.jgap.impl.MutipleIntegerGene.newGeneInternal().
org.jgap.impl.MutipleIntegerGene.MutipleIntegerGene (final Configuration a_config) throws InvalidConfigurationException [inline]
Constructs a new IntegerGene with default settings. No bounds will be put into effect for values (alleles) of this Gene instance, other than the standard range of Integer values.
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.5
Definition at line 72 of file MutipleIntegerGene.java.
org.jgap.impl.MutipleIntegerGene.MutipleIntegerGene (final Configuration a_config, final int a_lowerBound, final int a_upperBound, final int a_significance) throws InvalidConfigurationException [inline]
Constructs a new IntegerGene with the specified lower and upper bounds for values (alleles) of this Gene instance.
Parameters
a_config the configuration to use
a_lowerBound the lowest value that this Gene may possess, inclusively
a_upperBound the highest value that this Gene may possess, inclusively
Exceptions
InvalidConfigurationException
Author
Chris Johnes
Since
3.5
Definition at line 91 of file MutipleIntegerGene.java.
References org.jgap.impl.MutipleIntegerGene.m_lowerBounds, org.jgap.impl.MutipleIntegerGene.m_significance, org.jgap.impl.MutipleIntegerGene.m_upperBounds, and org.jgap.impl.MutipleIntegerGene.round().
Member Function Documentation
void org.jgap.impl.MutipleIntegerGene.applyMutation (final int a_index, final double a_percentage) [inline]
See interface Gene for description.
Parameters
a_index ignored (because there is only 1 atomic element)
a_percentage percentage of mutation (greater than -1 and smaller than 1)
Author
Chris Jones
Since
3.5
Definition at line 352 of file MutipleIntegerGene.java.
References org.jgap.BaseGene.getAllele(), org.jgap.impl.MutipleIntegerGene.m_lowerBounds, org.jgap.impl.MutipleIntegerGene.m_significance, org.jgap.impl.MutipleIntegerGene.m_upperBounds, org.jgap.impl.MutipleIntegerGene.round(), and org.jgap.impl.NumberGene.setAllele().
int org.jgap.impl.MutipleIntegerGene.compareToNative (final Object a_o1, final Object a_o2) [inline], [protected]
Compares to objects by first casting them into their expected type (e.g. Integer for IntegerGene) and then calling the compareTo-method of the casted type.
Parameters
a_o1 first object to be compared, always is not null
a_o2 second object to be compared, always is not null
Returns
a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than the object provided for comparison
Author
Neil Rostan
Since
3.5
Definition at line 298 of file MutipleIntegerGene.java.
int org.jgap.impl.MutipleIntegerGene.getLowerBounds () [inline]
Returns
the lower bounds of the integer gene
Author
Klaus Meffert
Since
3.5
Definition at line 408 of file MutipleIntegerGene.java.
References org.jgap.impl.MutipleIntegerGene.m_lowerBounds.
String org.jgap.impl.MutipleIntegerGene.getPersistentRepresentation () [inline]
Retrieves a string representation of this Gene that includes any information required to reconstruct it at a later time, such as its value and internal state. This string will be used to represent this Gene in XML persistence. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Returns
string representation of this Gene's current state
Author
Chris Jones
Since
3.5
Implements org.jgap.IPersistentRepresentation.
Definition at line 143 of file MutipleIntegerGene.java.
References org.jgap.impl.NumberGene.getInternalValue(), org.jgap.impl.MutipleIntegerGene.m_lowerBounds, org.jgap.impl.MutipleIntegerGene.m_significance, org.jgap.impl.MutipleIntegerGene.m_upperBounds, and org.jgap.Gene.PERSISTENT_FIELD_DELIMITER.
Integer org.jgap.impl.MutipleIntegerGene.getRandomValue (RandomGenerator a_numberGenerator) [inline], [private]
Definition at line 263 of file MutipleIntegerGene.java.
References org.jgap.impl.MutipleIntegerGene.m_lowerBounds, org.jgap.impl.MutipleIntegerGene.m_significance, org.jgap.impl.MutipleIntegerGene.m_upperBounds, org.jgap.RandomGenerator.nextDouble(), and org.jgap.impl.MutipleIntegerGene.round().
Referenced by org.jgap.impl.MutipleIntegerGene.setToRandomValue().
int org.jgap.impl.MutipleIntegerGene.getSignificance () [inline]
Returns
the upper bounds of the integer gene
Author
Klaus Meffert
Since
3.5
Definition at line 428 of file MutipleIntegerGene.java.
References org.jgap.impl.MutipleIntegerGene.m_significance.
int org.jgap.impl.MutipleIntegerGene.getUpperBounds () [inline]
Returns
the upper bounds of the integer gene
Author
Klaus Meffert
Since
3.5
Definition at line 418 of file MutipleIntegerGene.java.
References org.jgap.impl.MutipleIntegerGene.m_upperBounds.
int org.jgap.impl.MutipleIntegerGene.hashCode () [inline]
Modified hashCode() function to return different hashcodes for differently ordered genes in a chromosome.
Returns
-1 if no allele set, otherwise value return by BaseGene.hashCode()
Author
Klaus Meffert
Since
3.5
Definition at line 374 of file MutipleIntegerGene.java.
References org.jgap.impl.NumberGene.getInternalValue().
void org.jgap.impl.MutipleIntegerGene.mapValueToWithinBounds () [inline], [protected], [virtual]
Maps the value of this IntegerGene to within the bounds specified by the m_upperBounds and m_lowerBounds instance variables. The value's relative position within the integer range will be preserved within the bounds range (in other words, if the value is about halfway between the integer max and min, then the resulting value will be about halfway between the upper bounds and lower bounds). If the value is null or is already within the bounds, it will be left unchanged.
Author
Neil Rostan
Klaus Meffert
Since
1.0
Implements org.jgap.impl.NumberGene.
Definition at line 315 of file MutipleIntegerGene.java.
References org.jgap.BaseGene.getAllele(), org.jgap.BaseGene.getConfiguration(), org.jgap.impl.MutipleIntegerGene.m_lowerBounds, org.jgap.impl.MutipleIntegerGene.m_upperBounds, org.jgap.impl.NumberGene.setAllele(), and org.jgap.impl.MutipleIntegerGene.setToRandomValue().
Gene org.jgap.impl.MutipleIntegerGene.newGeneInternal () [inline], [protected], [virtual]
Provides implementation-independent means for creating new Gene instances.
Returns
a new Gene instance of the same type and with the same setup as this concrete Gene
Author
Chris Jones
Since
3.5
Implements org.jgap.BaseGene.
Definition at line 118 of file MutipleIntegerGene.java.
References org.jgap.BaseGene.getConfiguration(), org.jgap.impl.MutipleIntegerGene.m_lowerBounds, org.jgap.impl.MutipleIntegerGene.m_significance, org.jgap.impl.MutipleIntegerGene.m_upperBounds, and org.jgap.impl.MutipleIntegerGene.MutipleIntegerGene().
int org.jgap.impl.MutipleIntegerGene.round (double value, Integer factor) [inline], [private]
Definition at line 269 of file MutipleIntegerGene.java.
References org.jgap.impl.MutipleIntegerGene.m_lowerBounds, and org.jgap.impl.MutipleIntegerGene.m_upperBounds.
Referenced by org.jgap.impl.MutipleIntegerGene.applyMutation(), org.jgap.impl.MutipleIntegerGene.getRandomValue(), and org.jgap.impl.MutipleIntegerGene.MutipleIntegerGene().
void org.jgap.impl.MutipleIntegerGene.setToRandomValue (final RandomGenerator a_numberGenerator) [inline]
Sets the value (allele) of this Gene to a random Integer value between the lower and upper bounds (if any) of this Gene.
Parameters
a_numberGenerator the random number generator that should be used to create any random values. It's important to use this generator to maintain the user's flexibility to configure the genetic engine to use the random number generator of their choice
Author
Chris Jones
Since
3.5
Definition at line 259 of file MutipleIntegerGene.java.
References org.jgap.impl.MutipleIntegerGene.getRandomValue(), and org.jgap.impl.NumberGene.setAllele().
Referenced by org.jgap.impl.MutipleIntegerGene.mapValueToWithinBounds().
void org.jgap.impl.MutipleIntegerGene.setValueFromPersistentRepresentation (final String a_representation) throws UnsupportedRepresentationException [inline]
Sets the value and internal state of this Gene from the string representation returned by a previous invocation of the getPersistentRepresentation() method. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Parameters
a_representation the string representation retrieved from a prior call to the getPersistentRepresentation() method
Exceptions
UnsupportedOperationException to indicate that no implementation is provided for this method
UnsupportedRepresentationException if this Gene implementation does not support the given string representation
Author
Chris Jones
Since
3.5
Definition at line 178 of file MutipleIntegerGene.java.
References org.jgap.impl.MutipleIntegerGene.m_lowerBounds, org.jgap.impl.MutipleIntegerGene.m_significance, org.jgap.impl.MutipleIntegerGene.m_upperBounds, org.jgap.Gene.PERSISTENT_FIELD_DELIMITER, and org.jgap.impl.NumberGene.setAllele().
String org.jgap.impl.MutipleIntegerGene.toString () [inline]
Returns
string representation of this Gene's value that may be useful for display purposes
Author
Chris Jones
Since
3.5
Implements org.jgap.Gene.
Definition at line 390 of file MutipleIntegerGene.java.
References org.jgap.impl.NumberGene.getInternalValue(), org.jgap.impl.MutipleIntegerGene.m_lowerBounds, org.jgap.impl.MutipleIntegerGene.m_significance, and org.jgap.impl.MutipleIntegerGene.m_upperBounds.
Member Data Documentation
final String org.jgap.impl.MutipleIntegerGene.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 30 of file MutipleIntegerGene.java.
final long org.jgap.impl.MutipleIntegerGene.INTEGER_RANGE [static], [protected]
Initial value:
= (long) Integer.MAX_VALUE -
      (long) Integer.MIN_VALUE
Represents the constant range of values supported by integers.
Definition at line 53 of file MutipleIntegerGene.java.
int org.jgap.impl.MutipleIntegerGene.m_lowerBounds [private]
The lower bounds of values represented by this Gene. If not explicitly provided by the user, this should be set to Integer.MIN_VALUE
Definition at line 42 of file MutipleIntegerGene.java.
Referenced by org.jgap.impl.MutipleIntegerGene.applyMutation(), org.jgap.impl.MutipleIntegerGene.getLowerBounds(), org.jgap.impl.MutipleIntegerGene.getPersistentRepresentation(), org.jgap.impl.MutipleIntegerGene.getRandomValue(), org.jgap.impl.MutipleIntegerGene.mapValueToWithinBounds(), org.jgap.impl.MutipleIntegerGene.MutipleIntegerGene(), org.jgap.impl.MutipleIntegerGene.newGeneInternal(), org.jgap.impl.MutipleIntegerGene.round(), org.jgap.impl.MutipleIntegerGene.setValueFromPersistentRepresentation(), and org.jgap.impl.MutipleIntegerGene.toString().
int org.jgap.impl.MutipleIntegerGene.m_significance [private]
The lower bounds of values represented by this Gene. If not explicitly provided by the user, this should be set to Integer.MIN_VALUE
Definition at line 48 of file MutipleIntegerGene.java.
Referenced by org.jgap.impl.MutipleIntegerGene.applyMutation(), org.jgap.impl.MutipleIntegerGene.getPersistentRepresentation(), org.jgap.impl.MutipleIntegerGene.getRandomValue(), org.jgap.impl.MutipleIntegerGene.getSignificance(), org.jgap.impl.MutipleIntegerGene.MutipleIntegerGene(), org.jgap.impl.MutipleIntegerGene.newGeneInternal(), org.jgap.impl.MutipleIntegerGene.setValueFromPersistentRepresentation(), and org.jgap.impl.MutipleIntegerGene.toString().
int org.jgap.impl.MutipleIntegerGene.m_upperBounds [private]
The upper bounds of values represented by this Gene. If not explicitly provided by the user, this should be set to Integer.MAX_VALUE.
Definition at line 36 of file MutipleIntegerGene.java.
Referenced by org.jgap.impl.MutipleIntegerGene.applyMutation(), org.jgap.impl.MutipleIntegerGene.getPersistentRepresentation(), org.jgap.impl.MutipleIntegerGene.getRandomValue(), org.jgap.impl.MutipleIntegerGene.getUpperBounds(), org.jgap.impl.MutipleIntegerGene.mapValueToWithinBounds(), org.jgap.impl.MutipleIntegerGene.MutipleIntegerGene(), org.jgap.impl.MutipleIntegerGene.newGeneInternal(), org.jgap.impl.MutipleIntegerGene.round(), org.jgap.impl.MutipleIntegerGene.setValueFromPersistentRepresentation(), and org.jgap.impl.MutipleIntegerGene.toString().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/MutipleIntegerGene.java