org.jgap.impl.AveragingCrossoverOperator Class Reference
Public Member Functions
AveragingCrossoverOperator () throws InvalidConfigurationException
AveragingCrossoverOperator (final Configuration a_configuration) throws InvalidConfigurationException
AveragingCrossoverOperator (final Configuration a_configuration, final RandomGenerator a_generatorForAveraging) throws InvalidConfigurationException
AveragingCrossoverOperator (final Configuration a_configuration, final IUniversalRateCalculator a_crossoverRateCalculator) throws InvalidConfigurationException
void operate (final Population a_population, final List a_candidateChromosomes)
boolean equals (final Object a_other)
int compareTo (final Object a_other)
void setCrossoverRate (int a_rate)
Protected Member Functions
int getLocus (final RandomGenerator a_generator, final int a_index, final int a_max)
Private Member Functions
void init ()
void setCrossoverRateCalc (final IUniversalRateCalculator a_crossoverRateCalculator)
Private Attributes
RandomGenerator m_crossoverGenerator
int m_crossoverRate
Map m_loci
IUniversalRateCalculator m_crossoverRateCalc
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.29 $`
Additional Inherited Members
Detailed Description
The averaging crossover operator randomly selects two Chromosomes from the population and `mates` them by randomly picking a gene and then swapping that gene and all subsequent genes between the two Chromosomes. The two modified Chromosomes are then added to the list of candidate Chromosomes. This operation is performed half as many times as there are Chromosomes in the population. Additionally, the loci of crossing over are cached for each index, i.e., after randomizing the loci for each index once, they don't change again.
If you work with CompositeGene's, this operator expects them to contain genes of the same type (e.g. IntegerGene). If you have mixed types, please provide your own crossover operator.
Author
Klaus Meffert
Since
2.0
Definition at line 32 of file AveragingCrossoverOperator.java.
Constructor & Destructor Documentation
org.jgap.impl.AveragingCrossoverOperator.AveragingCrossoverOperator () throws InvalidConfigurationException [inline]
Using the same random generator for randomizing the loci for crossing over as for selecting the genes to be crossed over.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.0
Definition at line 74 of file AveragingCrossoverOperator.java.
Referenced by org.jgap.impl.AveragingCrossoverOperator.compareTo().
org.jgap.impl.AveragingCrossoverOperator.AveragingCrossoverOperator (final Configuration a_configuration) throws InvalidConfigurationException [inline]
Using the same random generator for randomizing the loci for crossing over as for selecting the genes to be crossed over.
Parameters
a_configuration the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 90 of file AveragingCrossoverOperator.java.
org.jgap.impl.AveragingCrossoverOperator.AveragingCrossoverOperator (final Configuration a_configuration, final RandomGenerator a_generatorForAveraging) throws InvalidConfigurationException [inline]
Using a different random generator for randomizing the loci for crossing over than for selecting the genes to be crossed over
Parameters
a_configuration the configuration to use
a_generatorForAveraging RandomGenerator to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0 (since 2.0 without a_configuration)
Definition at line 106 of file AveragingCrossoverOperator.java.
References org.jgap.impl.AveragingCrossoverOperator.init(), and org.jgap.impl.AveragingCrossoverOperator.m_crossoverGenerator.
org.jgap.impl.AveragingCrossoverOperator.AveragingCrossoverOperator (final Configuration a_configuration, final IUniversalRateCalculator a_crossoverRateCalculator) throws InvalidConfigurationException [inline]
Constructs a new instance of this CrossoverOperator with a specified crossover rate calculator, which results in dynamic crossover being turned on.
Parameters
a_configuration the configuration to use
a_crossoverRateCalculator calculator for dynamic crossover rate computation
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0 (since 2.0 without a_configuration)
Definition at line 128 of file AveragingCrossoverOperator.java.
References org.jgap.impl.AveragingCrossoverOperator.init(), and org.jgap.impl.AveragingCrossoverOperator.setCrossoverRateCalc().
Member Function Documentation
int org.jgap.impl.AveragingCrossoverOperator.compareTo (final Object a_other) [inline]
Compares the given object to this one.
Parameters
a_other the instance against which to compare this instance
Returns
a negative number if this instance is `less than` the given instance, zero if they are equal to each other, and a positive number if this is `greater than` the given instance
Author
Klaus Meffert
Since
2.6
Definition at line 297 of file AveragingCrossoverOperator.java.
References org.jgap.impl.AveragingCrossoverOperator.AveragingCrossoverOperator(), org.jgap.impl.AveragingCrossoverOperator.m_crossoverRate, and org.jgap.impl.AveragingCrossoverOperator.m_crossoverRateCalc.
Referenced by org.jgap.impl.AveragingCrossoverOperator.equals(), org.jgap.impl.AveragingCrossoverOperatorTest.testCompareTo_0(), and org.jgap.impl.AveragingCrossoverOperatorTest.testCompareTo_1().
boolean org.jgap.impl.AveragingCrossoverOperator.equals (final Object a_other) [inline]
Compares this GeneticOperator against the specified object. The result is true if and the argument is an instance of this class and is equal wrt the data.
Parameters
a_other the object to compare against
Returns
true: if the objects are the same, false otherwise
Author
Klaus Meffert
Since
2.6
Definition at line 277 of file AveragingCrossoverOperator.java.
References org.jgap.impl.AveragingCrossoverOperator.compareTo().
int org.jgap.impl.AveragingCrossoverOperator.getLocus (final RandomGenerator a_generator, final int a_index, final int a_max) [inline], [protected]
Returns the crossover location for a given index. For each index the crossover locatio is the same, therefor it is cached!
Parameters
a_generator to generate random values the first time
a_index the index of the crossover operation
a_max upper boundary for random generator
Returns
crossover location for a given index
Author
Klaus Meffert
Since
2.0
Definition at line 256 of file AveragingCrossoverOperator.java.
References org.jgap.impl.AveragingCrossoverOperator.m_loci, and org.jgap.RandomGenerator.nextInt().
Referenced by org.jgap.impl.AveragingCrossoverOperator.operate().
void org.jgap.impl.AveragingCrossoverOperator.init () [inline], [private]
Definition at line 58 of file AveragingCrossoverOperator.java.
References org.jgap.impl.AveragingCrossoverOperator.m_crossoverRate, and org.jgap.impl.AveragingCrossoverOperator.m_loci.
Referenced by org.jgap.impl.AveragingCrossoverOperator.AveragingCrossoverOperator().
void org.jgap.impl.AveragingCrossoverOperator.operate (final Population a_population, final List a_candidateChromosomes) [inline]
Crossover that acts as a perturbed mean of two individuals. x_i = p*x1_i + (1-p)*x2_i p - uniform random value over [0,1]. Averaging over line means p is same for every i, averaging over space if different p is chosen for each i. See CrossoverOperator for general description, also see feature request 708774
Parameters
a_population Chromosome[]
a_candidateChromosomes List
Author
Klaus Meffert
Since
2.0
Implements org.jgap.GeneticOperator.
Definition at line 164 of file AveragingCrossoverOperator.java.
References org.jgap.util.ICloneable.clone(), org.jgap.BaseGeneticOperator.getConfiguration(), org.jgap.impl.AveragingCrossoverOperator.getLocus(), org.jgap.impl.AveragingCrossoverOperator.m_crossoverGenerator, org.jgap.impl.AveragingCrossoverOperator.m_crossoverRate, org.jgap.impl.AveragingCrossoverOperator.m_crossoverRateCalc, org.jgap.BaseGeneticOperator.m_monitorActive, and org.jgap.Population.size().
void org.jgap.impl.AveragingCrossoverOperator.setCrossoverRate (int a_rate) [inline]
Parameters
a_rate crossover rate to use by this crossover operator
Author
Klaus Meffert
Since
2.6
Definition at line 330 of file AveragingCrossoverOperator.java.
References org.jgap.impl.AveragingCrossoverOperator.m_crossoverRate.
void org.jgap.impl.AveragingCrossoverOperator.setCrossoverRateCalc (final IUniversalRateCalculator a_crossoverRateCalculator) [inline], [private]
Sets the crossover rate calculator
Parameters
a_crossoverRateCalculator the new calculator
Author
Klaus Meffert
Since
2.0
Definition at line 144 of file AveragingCrossoverOperator.java.
References org.jgap.impl.AveragingCrossoverOperator.m_crossoverRateCalc.
Referenced by org.jgap.impl.AveragingCrossoverOperator.AveragingCrossoverOperator().
Member Data Documentation
final String org.jgap.impl.AveragingCrossoverOperator.CVS_REVISION = `$Revision: 1.29 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 35 of file AveragingCrossoverOperator.java.
RandomGenerator org.jgap.impl.AveragingCrossoverOperator.m_crossoverGenerator [private]
Random generator for randomizing the loci for crossing over
Definition at line 40 of file AveragingCrossoverOperator.java.
Referenced by org.jgap.impl.AveragingCrossoverOperator.AveragingCrossoverOperator(), and org.jgap.impl.AveragingCrossoverOperator.operate().
int org.jgap.impl.AveragingCrossoverOperator.m_crossoverRate [private]
The current crossover rate used by this crossover operator.
Definition at line 45 of file AveragingCrossoverOperator.java.
Referenced by org.jgap.impl.AveragingCrossoverOperator.compareTo(), org.jgap.impl.AveragingCrossoverOperator.init(), org.jgap.impl.AveragingCrossoverOperator.operate(), and org.jgap.impl.AveragingCrossoverOperator.setCrossoverRate().
IUniversalRateCalculator org.jgap.impl.AveragingCrossoverOperator.m_crossoverRateCalc [private]
Calculator for dynamically determining the crossover rate. If set to null the value of m_crossoverRate will be used instead.
Definition at line 56 of file AveragingCrossoverOperator.java.
Referenced by org.jgap.impl.AveragingCrossoverOperator.compareTo(), org.jgap.impl.AveragingCrossoverOperator.operate(), and org.jgap.impl.AveragingCrossoverOperator.setCrossoverRateCalc().
Map org.jgap.impl.AveragingCrossoverOperator.m_loci [private]
Cache for alreadycrandomized loci for crossing over
Definition at line 50 of file AveragingCrossoverOperator.java.
Referenced by org.jgap.impl.AveragingCrossoverOperator.getLocus(), and org.jgap.impl.AveragingCrossoverOperator.init().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/AveragingCrossoverOperator.java