org.jgap.data.DocumentBuilderBase Class Reference
Public Member Functions
Object buildDocument (final IDataCreators a_dataholder, final Object a_document) throws Exception
Protected Member Functions
abstract Object documentAppendChild (Object a_document, Object a_element)
abstract Object elementAppendChild (Object a_rootElement, Object a_childElement)
abstract Object createElement (Object a_document, Object a_element, String a_tagName)
abstract void setAttribute (Object a_element, String a_key, String a_value)
Private Member Functions
void doTraverse (final IDataElement a_elem, final Object a_document, final Object a_Element) throws Exception
Object createElementGeneric (final Object a_document, final Object a_element, final String a_tagName)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.8 $`
Detailed Description
Definition at line 22 of file DocumentBuilderBase.java.
Member Function Documentation
Object org.jgap.data.DocumentBuilderBase.buildDocument (final IDataCreators a_dataholder, final Object a_document) throws Exception [inline]
Builds a document from the given input (input data + existing document).
Parameters
a_dataholder the input structure holding the data to be represented as a generic document
a_document the document to put the elements in
Exceptions
Exception
Returns
the document built up by adding elements
Author
Klaus Meffert
Since
2.0
Definition at line 40 of file DocumentBuilderBase.java.
References org.jgap.data.DocumentBuilderBase.doTraverse().
abstract Object org.jgap.data.DocumentBuilderBase.createElement (Object a_document, Object a_element, String a_tagName) [protected], [pure virtual]
Creates an element with help for a given document.
Parameters
a_document could be used as factory to create the element with
a_element null or existing element as template
a_tagName name of tag to create for the element
Returns
created element
Author
Klaus Meffert
Since
2.0
Referenced by org.jgap.data.DocumentBuilderBase.createElementGeneric().
Object org.jgap.data.DocumentBuilderBase.createElementGeneric (final Object a_document, final Object a_element, final String a_tagName) [inline], [private]
Generically creates an element (Template Method).
Parameters
a_document could be used as factory to create the element with
a_element null or existing element as template
a_tagName name of tag to create for the element
Returns
created element
Author
Klaus Meffert
Since
2.0
Definition at line 99 of file DocumentBuilderBase.java.
References org.jgap.data.DocumentBuilderBase.createElement(), org.jgap.data.DocumentBuilderBase.documentAppendChild(), and org.jgap.data.DocumentBuilderBase.elementAppendChild().
Referenced by org.jgap.data.DocumentBuilderBase.doTraverse().
abstract Object org.jgap.data.DocumentBuilderBase.documentAppendChild (Object a_document, Object a_element) [protected], [pure virtual]
Append a child to a given document.
Parameters
a_document to append element on (e.g. org.w3c.dom.Document)
a_element to append to document (e.g. org.w3c.com.Element)
Returns
a_document with appended element (e.g. org.w3c.dom.Document)
Author
Klaus Meffert
Since
2.0
Referenced by org.jgap.data.DocumentBuilderBase.createElementGeneric().
void org.jgap.data.DocumentBuilderBase.doTraverse (final IDataElement a_elem, final Object a_document, final Object a_Element) throws Exception [inline], [private]
Recursive traversing over data tree containing elements to be transformed into tags.
Parameters
a_elem IDataElement
a_document Document
a_Element Element
Exceptions
Exception
Author
Klaus Meffert
Since
2.0
Definition at line 66 of file DocumentBuilderBase.java.
References org.jgap.data.DocumentBuilderBase.createElementGeneric(), and org.jgap.data.DocumentBuilderBase.setAttribute().
Referenced by org.jgap.data.DocumentBuilderBase.buildDocument().
abstract Object org.jgap.data.DocumentBuilderBase.elementAppendChild (Object a_rootElement, Object a_childElement) [protected], [pure virtual]
Append a child to a given element.
Parameters
a_rootElement to append childElement on (e.g. org.w3c.com.Element)
a_childElement to append to rootElement (e.g. org.w3c.com.Element)
Returns
rootElement with appended childElement (e.g. org.w3c.com.Element)
Author
Klaus Meffert
Since
2.0
Referenced by org.jgap.data.DocumentBuilderBase.createElementGeneric().
abstract void org.jgap.data.DocumentBuilderBase.setAttribute (Object a_element, String a_key, String a_value) [protected], [pure virtual]
Sets an attribute for a given Element.
Parameters
a_element the Element to set an attribute for (e.g. org.w3c.com.Element)
a_key the key of the attribute
a_value the value of the attribute
Author
Klaus Meffert
Since
2.0
Referenced by org.jgap.data.DocumentBuilderBase.doTraverse().
Member Data Documentation
final String org.jgap.data.DocumentBuilderBase.CVS_REVISION = `$Revision: 1.8 $` [static], [private]
Todo
Todo add new class DocumentCreatorBase that reads in data written by DocumentBuilderBase
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file DocumentBuilderBase.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/data/DocumentBuilderBase.java