examples.gp.monalisa.core.commands.PolygonConstructor Class Reference
Public Member Functions
PolygonConstructor (GPConfiguration a_conf, int a_points) throws InvalidConfigurationException
PolygonConstructor (GPConfiguration a_conf, int a_points, int a_minPoints, int a_maxPoints) throws InvalidConfigurationException
PolygonConstructor (GPConfiguration a_conf, int a_points, boolean a_mutateable) throws InvalidConfigurationException
Object execute_object (ProgramChromosome a_chrom, int a_n, Object[] a_args)
Class getChildType (IGPProgram a_ind, int a_chromNum)
String toString ()
CommandGene applyMutation (int index, double a_percentage) throws InvalidConfigurationException
CommandGene applyMutation () throws InvalidConfigurationException
Object clone ()
Private Attributes
boolean m_mutateable
int m_points = 5
int m_minPoints
int m_maxPoints
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
A polygon consists of a series of points.
Author
Yann N. Dauphin
Definition at line 23 of file PolygonConstructor.java.
Constructor & Destructor Documentation
examples.gp.monalisa.core.commands.PolygonConstructor.PolygonConstructor (GPConfiguration a_conf, int a_points) throws InvalidConfigurationException [inline]
Definition at line 36 of file PolygonConstructor.java.
Referenced by examples.gp.monalisa.core.commands.PolygonConstructor.applyMutation(), and examples.gp.monalisa.core.commands.PolygonConstructor.clone().
examples.gp.monalisa.core.commands.PolygonConstructor.PolygonConstructor (GPConfiguration a_conf, int a_points, int a_minPoints, int a_maxPoints) throws InvalidConfigurationException [inline]
Definition at line 41 of file PolygonConstructor.java.
References examples.gp.monalisa.core.commands.PolygonConstructor.m_maxPoints, and examples.gp.monalisa.core.commands.PolygonConstructor.m_minPoints.
examples.gp.monalisa.core.commands.PolygonConstructor.PolygonConstructor (GPConfiguration a_conf, int a_points, boolean a_mutateable) throws InvalidConfigurationException [inline]
Definition at line 50 of file PolygonConstructor.java.
References examples.gp.monalisa.core.commands.PolygonConstructor.m_mutateable, and examples.gp.monalisa.core.commands.PolygonConstructor.m_points.
Member Function Documentation
CommandGene examples.gp.monalisa.core.commands.PolygonConstructor.applyMutation (int index, double a_percentage) throws InvalidConfigurationException [inline]
Definition at line 87 of file PolygonConstructor.java.
References examples.gp.monalisa.core.commands.PolygonConstructor.applyMutation(), org.jgap.gp.CommandGene.getGPConfiguration(), and examples.gp.monalisa.core.commands.PolygonConstructor.m_mutateable.
CommandGene examples.gp.monalisa.core.commands.PolygonConstructor.applyMutation () throws InvalidConfigurationException [inline]
Definition at line 100 of file PolygonConstructor.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), examples.gp.monalisa.core.commands.PolygonConstructor.m_maxPoints, examples.gp.monalisa.core.commands.PolygonConstructor.m_minPoints, examples.gp.monalisa.core.commands.PolygonConstructor.m_mutateable, and examples.gp.monalisa.core.commands.PolygonConstructor.PolygonConstructor().
Referenced by examples.gp.monalisa.core.commands.PolygonConstructor.applyMutation().
Object examples.gp.monalisa.core.commands.PolygonConstructor.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4.1
Definition at line 124 of file PolygonConstructor.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), examples.gp.monalisa.core.commands.PolygonConstructor.m_mutateable, examples.gp.monalisa.core.commands.PolygonConstructor.m_points, and examples.gp.monalisa.core.commands.PolygonConstructor.PolygonConstructor().
Object examples.gp.monalisa.core.commands.PolygonConstructor.execute_object (ProgramChromosome a_chrom, int a_n, Object[] a_args) [inline]
Definition at line 59 of file PolygonConstructor.java.
References examples.gp.monalisa.core.commands.PolygonConstructor.m_points.
Class examples.gp.monalisa.core.commands.PolygonConstructor.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Definition at line 70 of file PolygonConstructor.java.
String examples.gp.monalisa.core.commands.PolygonConstructor.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 75 of file PolygonConstructor.java.
References examples.gp.monalisa.core.commands.PolygonConstructor.m_points.
Member Data Documentation
final String examples.gp.monalisa.core.commands.PolygonConstructor.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file PolygonConstructor.java.
int examples.gp.monalisa.core.commands.PolygonConstructor.m_maxPoints [private]
Definition at line 34 of file PolygonConstructor.java.
Referenced by examples.gp.monalisa.core.commands.PolygonConstructor.applyMutation(), and examples.gp.monalisa.core.commands.PolygonConstructor.PolygonConstructor().
int examples.gp.monalisa.core.commands.PolygonConstructor.m_minPoints [private]
Definition at line 32 of file PolygonConstructor.java.
Referenced by examples.gp.monalisa.core.commands.PolygonConstructor.applyMutation(), and examples.gp.monalisa.core.commands.PolygonConstructor.PolygonConstructor().
boolean examples.gp.monalisa.core.commands.PolygonConstructor.m_mutateable [private]
Definition at line 28 of file PolygonConstructor.java.
Referenced by examples.gp.monalisa.core.commands.PolygonConstructor.applyMutation(), examples.gp.monalisa.core.commands.PolygonConstructor.clone(), and examples.gp.monalisa.core.commands.PolygonConstructor.PolygonConstructor().
int examples.gp.monalisa.core.commands.PolygonConstructor.m_points = 5 [private]
Definition at line 30 of file PolygonConstructor.java.
Referenced by examples.gp.monalisa.core.commands.PolygonConstructor.clone(), examples.gp.monalisa.core.commands.PolygonConstructor.execute_object(), examples.gp.monalisa.core.commands.PolygonConstructor.PolygonConstructor(), and examples.gp.monalisa.core.commands.PolygonConstructor.toString().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/monalisa/core/commands/PolygonConstructor.java