org.jgap.gp.terminal.Terminal Class Reference
Public Member Functions
Terminal () throws InvalidConfigurationException
Terminal (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException
Terminal (final GPConfiguration a_conf, Class a_returnType, double a_minValue, double a_maxValue) throws InvalidConfigurationException
Terminal (final GPConfiguration a_conf, Class a_returnType, double a_minValue, double a_maxValue, boolean a_wholeNumbers) throws InvalidConfigurationException
Terminal (final GPConfiguration a_conf, Class a_returnType, double a_minValue, double a_maxValue, boolean a_wholeNumbers, int a_subReturnType) throws InvalidConfigurationException
Terminal (final GPConfiguration a_conf, Class a_returnType, double a_minValue, double a_maxValue, boolean a_wholeNumbers, int a_subReturnType, boolean a_randomize) throws InvalidConfigurationException
void setValue (double a_value)
void setValue (float a_value)
void setValue (int a_value)
void setValue (long a_value)
CommandGene applyMutation (int index, double a_percentage) throws InvalidConfigurationException
String toString ()
int execute_int (ProgramChromosome c, int n, Object[] args)
long execute_long (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
Class getChildType (IGPProgram a_ind, int a_chromNum)
Object clone ()
Protected Member Functions
void setRandomValue (int a_value)
void setRandomValue (long a_value)
void setRandomValue (double a_value)
void setRandomValue (float a_value)
void setRandomValue ()
Private Attributes
float m_value_float
double m_value_double
int m_value_int
long m_value_long
double m_lowerBounds
double m_upperBounds
boolean m_wholeNumbers
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.18 $`
Additional Inherited Members
Detailed Description
A terminal is a static number that can be mutated.
Author
Klaus Meffert
Since
3.0
Definition at line 23 of file Terminal.java.
Constructor & Destructor Documentation
org.jgap.gp.terminal.Terminal.Terminal () throws InvalidConfigurationException [inline]
Definition at line 42 of file Terminal.java.
References org.jgap.gp.CommandGene.IntegerClass.
Referenced by org.jgap.gp.terminal.Terminal.clone().
org.jgap.gp.terminal.Terminal.Terminal (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 47 of file Terminal.java.
org.jgap.gp.terminal.Terminal.Terminal (final GPConfiguration a_conf, Class a_returnType, double a_minValue, double a_maxValue) throws InvalidConfigurationException [inline]
Constructor.
Parameters
a_conf GPConfiguration
a_returnType Class
a_minValue double
a_maxValue double
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 64 of file Terminal.java.
org.jgap.gp.terminal.Terminal.Terminal (final GPConfiguration a_conf, Class a_returnType, double a_minValue, double a_maxValue, boolean a_wholeNumbers) throws InvalidConfigurationException [inline]
Constructor.
Parameters
a_conf GPConfiguration
a_returnType Class
a_minValue double
a_maxValue double
a_wholeNumbers true: only return whole numbers (only relevant when using type double or float)
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.2
Definition at line 84 of file Terminal.java.
org.jgap.gp.terminal.Terminal.Terminal (final GPConfiguration a_conf, Class a_returnType, double a_minValue, double a_maxValue, boolean a_wholeNumbers, int a_subReturnType) throws InvalidConfigurationException [inline]
Definition at line 90 of file Terminal.java.
org.jgap.gp.terminal.Terminal.Terminal (final GPConfiguration a_conf, Class a_returnType, double a_minValue, double a_maxValue, boolean a_wholeNumbers, int a_subReturnType, boolean a_randomize) throws InvalidConfigurationException [inline]
Parameters
a_conf GPConfiguration
a_returnType Class
a_minValue double
a_maxValue double
a_wholeNumbers boolean
a_subReturnType int
a_randomize true: randomize initial value
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.4.1
Definition at line 112 of file Terminal.java.
References org.jgap.gp.terminal.Terminal.m_lowerBounds, org.jgap.gp.terminal.Terminal.m_upperBounds, org.jgap.gp.terminal.Terminal.m_wholeNumbers, and org.jgap.gp.terminal.Terminal.setRandomValue().
Member Function Documentation
CommandGene org.jgap.gp.terminal.Terminal.applyMutation (int a_index, double a_percentage) throws InvalidConfigurationException [inline]
Mutates a CommandGene.
Parameters
a_index references the part of a multipart object, normally not relevant
a_percentage the mutation rate (0.0 to 1.0)
Returns
the mutant
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IMutateable.
Definition at line 203 of file Terminal.java.
References org.jgap.gp.CommandGene.DELTA, org.jgap.gp.CommandGene.DoubleClass, org.jgap.gp.CommandGene.FloatClass, org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.CommandGene.LongClass, org.jgap.gp.terminal.Terminal.m_lowerBounds, org.jgap.gp.terminal.Terminal.m_upperBounds, org.jgap.gp.terminal.Terminal.m_value_double, org.jgap.gp.terminal.Terminal.m_value_float, org.jgap.gp.terminal.Terminal.m_value_int, org.jgap.gp.terminal.Terminal.m_value_long, org.jgap.gp.terminal.Terminal.setRandomValue(), and org.jgap.gp.terminal.Terminal.setValue().
Object org.jgap.gp.terminal.Terminal.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.2
Implements org.jgap.util.ICloneable.
Definition at line 381 of file Terminal.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), org.jgap.gp.CommandGene.getSubReturnType(), org.jgap.gp.terminal.Terminal.m_lowerBounds, org.jgap.gp.terminal.Terminal.m_upperBounds, org.jgap.gp.terminal.Terminal.m_value_double, org.jgap.gp.terminal.Terminal.m_value_float, org.jgap.gp.terminal.Terminal.m_value_int, org.jgap.gp.terminal.Terminal.m_value_long, org.jgap.gp.terminal.Terminal.m_wholeNumbers, and org.jgap.gp.terminal.Terminal.Terminal().
double org.jgap.gp.terminal.Terminal.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 335 of file Terminal.java.
References org.jgap.gp.terminal.Terminal.m_value_double.
float org.jgap.gp.terminal.Terminal.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 331 of file Terminal.java.
References org.jgap.gp.terminal.Terminal.m_value_float.
int org.jgap.gp.terminal.Terminal.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 323 of file Terminal.java.
References org.jgap.gp.terminal.Terminal.m_value_int.
long org.jgap.gp.terminal.Terminal.execute_long (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 327 of file Terminal.java.
References org.jgap.gp.terminal.Terminal.m_value_long.
Object org.jgap.gp.terminal.Terminal.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Returns a string representation of the terminal.
Parameters
c ignored here
n ignored here
args ignored here
Returns
StringBuffer with textual representation of terminal's value
Author
Klaus Meffert
Since
3.2
Definition at line 350 of file Terminal.java.
References org.jgap.gp.CommandGene.DoubleClass, org.jgap.gp.CommandGene.FloatClass, org.jgap.gp.CommandGene.getReturnType(), org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.CommandGene.LongClass, org.jgap.gp.terminal.Terminal.m_value_double, org.jgap.gp.terminal.Terminal.m_value_float, org.jgap.gp.terminal.Terminal.m_value_int, and org.jgap.gp.terminal.Terminal.m_value_long.
Class org.jgap.gp.terminal.Terminal.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Definition at line 369 of file Terminal.java.
void org.jgap.gp.terminal.Terminal.setRandomValue (int a_value) [inline], [protected]
Definition at line 125 of file Terminal.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.terminal.Terminal.m_lowerBounds, org.jgap.gp.terminal.Terminal.m_upperBounds, org.jgap.gp.terminal.Terminal.m_value_int, and org.jgap.RandomGenerator.nextDouble().
void org.jgap.gp.terminal.Terminal.setRandomValue (long a_value) [inline], [protected]
Definition at line 132 of file Terminal.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.terminal.Terminal.m_lowerBounds, org.jgap.gp.terminal.Terminal.m_upperBounds, and org.jgap.gp.terminal.Terminal.m_value_long.
void org.jgap.gp.terminal.Terminal.setRandomValue (double a_value) [inline], [protected]
Definition at line 139 of file Terminal.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.terminal.Terminal.m_lowerBounds, org.jgap.gp.terminal.Terminal.m_upperBounds, org.jgap.gp.terminal.Terminal.m_value_double, and org.jgap.gp.terminal.Terminal.m_wholeNumbers.
void org.jgap.gp.terminal.Terminal.setRandomValue (float a_value) [inline], [protected]
Definition at line 148 of file Terminal.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.terminal.Terminal.m_lowerBounds, org.jgap.gp.terminal.Terminal.m_upperBounds, org.jgap.gp.terminal.Terminal.m_value_float, org.jgap.gp.terminal.Terminal.m_wholeNumbers, and org.jgap.RandomGenerator.nextFloat().
void org.jgap.gp.terminal.Terminal.setRandomValue () [inline], [protected]
Definition at line 158 of file Terminal.java.
References org.jgap.gp.CommandGene.DoubleClass, org.jgap.gp.CommandGene.FloatClass, org.jgap.gp.CommandGene.getReturnType(), org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.CommandGene.LongClass, org.jgap.gp.terminal.Terminal.m_value_double, org.jgap.gp.terminal.Terminal.m_value_float, org.jgap.gp.terminal.Terminal.m_value_int, and org.jgap.gp.terminal.Terminal.m_value_long.
Referenced by org.jgap.gp.terminal.Terminal.applyMutation(), and org.jgap.gp.terminal.Terminal.Terminal().
void org.jgap.gp.terminal.Terminal.setValue (double a_value) [inline]
Definition at line 177 of file Terminal.java.
References org.jgap.gp.terminal.Terminal.m_value_double, and org.jgap.gp.terminal.Terminal.m_wholeNumbers.
Referenced by org.jgap.gp.terminal.Terminal.applyMutation().
void org.jgap.gp.terminal.Terminal.setValue (float a_value) [inline]
Definition at line 186 of file Terminal.java.
References org.jgap.gp.terminal.Terminal.m_value_float, and org.jgap.gp.terminal.Terminal.m_wholeNumbers.
void org.jgap.gp.terminal.Terminal.setValue (int a_value) [inline]
Definition at line 195 of file Terminal.java.
References org.jgap.gp.terminal.Terminal.m_value_int.
void org.jgap.gp.terminal.Terminal.setValue (long a_value) [inline]
Definition at line 199 of file Terminal.java.
References org.jgap.gp.terminal.Terminal.m_value_long.
String org.jgap.gp.terminal.Terminal.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 304 of file Terminal.java.
References org.jgap.gp.CommandGene.DoubleClass, org.jgap.gp.CommandGene.FloatClass, org.jgap.gp.CommandGene.getReturnType(), org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.CommandGene.LongClass, org.jgap.gp.terminal.Terminal.m_value_double, org.jgap.gp.terminal.Terminal.m_value_float, org.jgap.gp.terminal.Terminal.m_value_int, and org.jgap.gp.terminal.Terminal.m_value_long.
Member Data Documentation
final String org.jgap.gp.terminal.Terminal.CVS_REVISION = `$Revision: 1.18 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file Terminal.java.
double org.jgap.gp.terminal.Terminal.m_lowerBounds [private]
Definition at line 36 of file Terminal.java.
Referenced by org.jgap.gp.terminal.Terminal.applyMutation(), org.jgap.gp.terminal.Terminal.clone(), org.jgap.gp.terminal.Terminal.setRandomValue(), and org.jgap.gp.terminal.Terminal.Terminal().
double org.jgap.gp.terminal.Terminal.m_upperBounds [private]
Definition at line 38 of file Terminal.java.
Referenced by org.jgap.gp.terminal.Terminal.applyMutation(), org.jgap.gp.terminal.Terminal.clone(), org.jgap.gp.terminal.Terminal.setRandomValue(), and org.jgap.gp.terminal.Terminal.Terminal().
double org.jgap.gp.terminal.Terminal.m_value_double [private]
Definition at line 30 of file Terminal.java.
Referenced by org.jgap.gp.terminal.Terminal.applyMutation(), org.jgap.gp.terminal.Terminal.clone(), org.jgap.gp.terminal.Terminal.execute_double(), org.jgap.gp.terminal.Terminal.execute_object(), org.jgap.gp.terminal.Terminal.setRandomValue(), org.jgap.gp.terminal.Terminal.setValue(), and org.jgap.gp.terminal.Terminal.toString().
float org.jgap.gp.terminal.Terminal.m_value_float [private]
Definition at line 28 of file Terminal.java.
Referenced by org.jgap.gp.terminal.Terminal.applyMutation(), org.jgap.gp.terminal.Terminal.clone(), org.jgap.gp.terminal.Terminal.execute_float(), org.jgap.gp.terminal.Terminal.execute_object(), org.jgap.gp.terminal.Terminal.setRandomValue(), org.jgap.gp.terminal.Terminal.setValue(), and org.jgap.gp.terminal.Terminal.toString().
int org.jgap.gp.terminal.Terminal.m_value_int [private]
Definition at line 32 of file Terminal.java.
Referenced by org.jgap.gp.terminal.Terminal.applyMutation(), org.jgap.gp.terminal.Terminal.clone(), org.jgap.gp.terminal.Terminal.execute_int(), org.jgap.gp.terminal.Terminal.execute_object(), org.jgap.gp.terminal.Terminal.setRandomValue(), org.jgap.gp.terminal.Terminal.setValue(), and org.jgap.gp.terminal.Terminal.toString().
long org.jgap.gp.terminal.Terminal.m_value_long [private]
Definition at line 34 of file Terminal.java.
Referenced by org.jgap.gp.terminal.Terminal.applyMutation(), org.jgap.gp.terminal.Terminal.clone(), org.jgap.gp.terminal.Terminal.execute_long(), org.jgap.gp.terminal.Terminal.execute_object(), org.jgap.gp.terminal.Terminal.setRandomValue(), org.jgap.gp.terminal.Terminal.setValue(), and org.jgap.gp.terminal.Terminal.toString().
boolean org.jgap.gp.terminal.Terminal.m_wholeNumbers [private]
Definition at line 40 of file Terminal.java.
Referenced by org.jgap.gp.terminal.Terminal.clone(), org.jgap.gp.terminal.Terminal.setRandomValue(), org.jgap.gp.terminal.Terminal.setValue(), and org.jgap.gp.terminal.Terminal.Terminal().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/terminal/Terminal.java