examples.gp.Fibonacci.FormulaFitnessFunction Class Reference
Public Member Functions
double computeRawFitness (final IGPProgram a_program)
Protected Member Functions
double evaluate (final IGPProgram a_subject)
Additional Inherited Members
Detailed Description
Definition at line 302 of file Fibonacci.java.
Member Function Documentation
double examples.gp.Fibonacci.FormulaFitnessFunction.computeRawFitness (final IGPProgram a_program) [inline]
Todo
Todo check if program valid, i.e. worth evaluating
Todo
Todo add penalty for longer solutions
Definition at line 308 of file Fibonacci.java.
References org.jgap.gp.IGPProgram.getGPConfiguration(), org.jgap.gp.GPFitnessFunction.MAX_FITNESS_VALUE, examples.gp.Fibonacci.NUMFIB, and org.jgap.gp.IGPProgram.size().
Referenced by examples.gp.Fibonacci.FormulaFitnessFunction.evaluate().
double examples.gp.Fibonacci.FormulaFitnessFunction.evaluate (final IGPProgram a_subject) [inline], [protected]
Definition at line 304 of file Fibonacci.java.
References examples.gp.Fibonacci.FormulaFitnessFunction.computeRawFitness().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/Fibonacci.java