org.jgap.gp.impl.GPConfigurationTest Class Reference
Public Member Functions
void setUp ()
void testSerialize_0 () throws Exception
void testMemory_0 () throws Exception
void testMemory_1 () throws Exception
void testMemory_2 () throws Exception
void testMemory_3 () throws Exception
void testStack_0 () throws Exception
void testStack_1 () throws Exception
void testStack_2 () throws Exception
void testStack_3 () throws Exception
void testStack_4 () throws Exception
void testSetSelectionMethod_0 () throws Exception
void testSetSelectionMethod_1 () throws Exception
void testSetCrossoverMethod_0 () throws Exception
void testSetCrossoverMethod_1 () throws Exception
void testConstructor_0 () throws Exception
void testConstructor_1 () throws Exception
void testClone_0 () throws Exception
void testClone_1 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.9 $`
Additional Inherited Members
Detailed Description
Tests the GPConfiguration class.
Author
Klaus Meffert
Since
3.0
Definition at line 26 of file GPConfigurationTest.java.
Member Function Documentation
void org.jgap.gp.impl.GPConfigurationTest.setUp () [inline]
Definition at line 36 of file GPConfigurationTest.java.
static Test org.jgap.gp.impl.GPConfigurationTest.suite () [inline], [static]
Definition at line 31 of file GPConfigurationTest.java.
void org.jgap.gp.impl.GPConfigurationTest.testClone_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 320 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.impl.GPConfiguration.clone(), org.jgap.JGAPTestCase.conf, org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.GPConfigurationTest.testClone_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.6
Definition at line 346 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.impl.GPConfiguration.clone(), org.jgap.JGAPTestCase.conf, org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.GPConfigurationTest.testConstructor_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 289 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.gp.impl.GPConfigurationTest.testConstructor_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 306 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.gp.impl.GPConfiguration.getSelectionMethod().
void org.jgap.gp.impl.GPConfigurationTest.testMemory_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 60 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.gp.impl.GPConfigurationTest.testMemory_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 74 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.gp.impl.GPConfigurationTest.testMemory_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 92 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.gp.impl.GPConfigurationTest.testMemory_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 115 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.gp.impl.GPConfigurationTest.testSerialize_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 46 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.doSerialize().
void org.jgap.gp.impl.GPConfigurationTest.testSetCrossoverMethod_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 256 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.gp.impl.GPConfigurationTest.testSetCrossoverMethod_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 274 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.gp.impl.GPConfigurationTest.testSetSelectionMethod_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 223 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.gp.impl.GPConfigurationTest.testSetSelectionMethod_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 241 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.gp.impl.GPConfigurationTest.testStack_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 135 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.gp.impl.GPConfigurationTest.testStack_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 154 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.gp.impl.GPConfigurationTest.testStack_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 174 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.gp.impl.GPConfigurationTest.testStack_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 190 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.gp.impl.GPConfigurationTest.testStack_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 208 of file GPConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
Member Data Documentation
final String org.jgap.gp.impl.GPConfigurationTest.CVS_REVISION = `$Revision: 1.9 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 29 of file GPConfigurationTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/gp/impl/GPConfigurationTest.java