examples.math.cmd.MultiplyOperator Class Reference
Public Member Functions
MultiplyOperator ()
MultiplyOperator (Operand theLeft, Operand theRight)
double calcuate ()
void accept (MathVisitor theVisitor)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.1 $`
Additional Inherited Members
Detailed Description
The multiply operator.
Author
Michael Grove
Since
3.4.2
Definition at line 20 of file MultiplyOperator.java.
Constructor & Destructor Documentation
examples.math.cmd.MultiplyOperator.MultiplyOperator () [inline]
Definition at line 25 of file MultiplyOperator.java.
Referenced by examples.math.cmd.MultiplyOperator.clone().
examples.math.cmd.MultiplyOperator.MultiplyOperator (Operand theLeft, Operand theRight) [inline]
Definition at line 29 of file MultiplyOperator.java.
Member Function Documentation
void examples.math.cmd.MultiplyOperator.accept (MathVisitor theVisitor) [inline]
Implements examples.math.cmd.Operand.
Definition at line 37 of file MultiplyOperator.java.
double examples.math.cmd.MultiplyOperator.calcuate () [inline]
Implements examples.math.cmd.Operator.
Definition at line 33 of file MultiplyOperator.java.
References examples.math.cmd.MathOperator.getLeftOperand(), and examples.math.cmd.MathOperator.getRightOperand().
Object examples.math.cmd.MultiplyOperator.clone () [inline], [virtual]
Implements examples.math.cmd.MathOperator.
Definition at line 41 of file MultiplyOperator.java.
References examples.math.cmd.MultiplyOperator.MultiplyOperator().
Member Data Documentation
final String examples.math.cmd.MultiplyOperator.CVS_REVISION = `$Revision: 1.1 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 23 of file MultiplyOperator.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/math/cmd/MultiplyOperator.java