org.jgap.gp.function.AddAndStore Class Reference
Public Member Functions
AddAndStore (final GPConfiguration a_conf, Class a_type, String a_storageName) throws InvalidConfigurationException
String toString ()
String getName ()
void execute_void (ProgramChromosome c, int n, Object[] args)
Class getChildType (IGPProgram a_ind, int a_chromNum)
int compareTo (Object a_other)
boolean equals (Object a_other)
Object clone ()
Private Attributes
String m_storageName
Class m_type
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.13 $`
Additional Inherited Members
Detailed Description
The add operation that stores the result in internal memory afterwards.
Author
Klaus Meffert
Since
3.0
Definition at line 24 of file AddAndStore.java.
Constructor & Destructor Documentation
org.jgap.gp.function.AddAndStore.AddAndStore (final GPConfiguration a_conf, Class a_type, String a_storageName) throws InvalidConfigurationException [inline]
Definition at line 37 of file AddAndStore.java.
References org.jgap.gp.function.AddAndStore.m_storageName, org.jgap.gp.function.AddAndStore.m_type, and org.jgap.gp.CommandGene.VoidClass.
Referenced by org.jgap.gp.function.AddAndStore.clone(), org.jgap.gp.function.AddAndStore.compareTo(), and org.jgap.gp.function.AddAndStore.equals().
Member Function Documentation
Object org.jgap.gp.function.AddAndStore.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 135 of file AddAndStore.java.
References org.jgap.gp.function.AddAndStore.AddAndStore(), org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.function.AddAndStore.m_storageName, and org.jgap.gp.function.AddAndStore.m_type.
int org.jgap.gp.function.AddAndStore.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
-1, 0, 1
Author
Klaus Meffert
Since
3.0
Definition at line 95 of file AddAndStore.java.
References org.jgap.gp.function.AddAndStore.AddAndStore(), org.jgap.gp.function.AddAndStore.m_storageName, and org.jgap.gp.function.AddAndStore.m_type.
boolean org.jgap.gp.function.AddAndStore.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Klaus Meffert
Since
3.0
Definition at line 115 of file AddAndStore.java.
References org.jgap.gp.function.AddAndStore.AddAndStore(), org.jgap.gp.function.AddAndStore.m_storageName, and org.jgap.gp.function.AddAndStore.m_type.
void org.jgap.gp.function.AddAndStore.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 59 of file AddAndStore.java.
References org.jgap.gp.CommandGene.DoubleClass, org.jgap.gp.CommandGene.FloatClass, org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.CommandGene.LongClass, org.jgap.gp.function.AddAndStore.m_storageName, and org.jgap.gp.function.AddAndStore.m_type.
Class org.jgap.gp.function.AddAndStore.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Definition at line 82 of file AddAndStore.java.
References org.jgap.gp.function.AddAndStore.m_type.
String org.jgap.gp.function.AddAndStore.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 55 of file AddAndStore.java.
String org.jgap.gp.function.AddAndStore.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 45 of file AddAndStore.java.
References org.jgap.gp.function.AddAndStore.m_storageName.
Member Data Documentation
final String org.jgap.gp.function.AddAndStore.CVS_REVISION = `$Revision: 1.13 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file AddAndStore.java.
String org.jgap.gp.function.AddAndStore.m_storageName [private]
Symbolic name of the storage. Must correspond with a chosen name for ReadTerminalCommand.
Definition at line 33 of file AddAndStore.java.
Referenced by org.jgap.gp.function.AddAndStore.AddAndStore(), org.jgap.gp.function.AddAndStore.clone(), org.jgap.gp.function.AddAndStore.compareTo(), org.jgap.gp.function.AddAndStore.equals(), org.jgap.gp.function.AddAndStore.execute_void(), and org.jgap.gp.function.AddAndStore.toString().
Class org.jgap.gp.function.AddAndStore.m_type [private]
Definition at line 35 of file AddAndStore.java.
Referenced by org.jgap.gp.function.AddAndStore.AddAndStore(), org.jgap.gp.function.AddAndStore.clone(), org.jgap.gp.function.AddAndStore.compareTo(), org.jgap.gp.function.AddAndStore.equals(), org.jgap.gp.function.AddAndStore.execute_void(), and org.jgap.gp.function.AddAndStore.getChildType().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/AddAndStore.java