org.jgap.distr.grid.gp.JGAPWorkersGP Class Reference
Public Member Functions
JGAPWorkersGP (String[] args) throws Exception
void getNeededFiles (GridNodeWorkerConfig a_config)
JGAPWorkersGP (GridNodeWorkerConfig a_config) throws Exception
Static Public Member Functions
static void main (String[] args) throws Exception
Protected Member Functions
void startWork (GridNodeWorkerConfig a_config) throws Exception
Private Attributes
Class m_workerClass
Class m_workerFeedbackClaas
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
static final String className = JGAPWorkersGP.class.getName()
static Logger log = Logger.getLogger(className)
Detailed Description
A GP worker receives work units from a JGAPServer and sends back computed solutions to a JGAPServer.
Author
Klaus Meffert
Since
3.2
Definition at line 25 of file JGAPWorkersGP.java.
Constructor & Destructor Documentation
org.jgap.distr.grid.gp.JGAPWorkersGP.JGAPWorkersGP (String[] args) throws Exception [inline]
Definition at line 37 of file JGAPWorkersGP.java.
References org.jgap.distr.grid.gp.JGAPWorkersGP.getNeededFiles(), and org.jgap.distr.grid.gp.JGAPWorkersGP.startWork().
Referenced by org.jgap.distr.grid.gp.JGAPWorkersGP.main().
org.jgap.distr.grid.gp.JGAPWorkersGP.JGAPWorkersGP (GridNodeWorkerConfig a_config) throws Exception [inline]
Definition at line 66 of file JGAPWorkersGP.java.
References org.jgap.distr.grid.gp.JGAPWorkersGP.startWork().
Member Function Documentation
void org.jgap.distr.grid.gp.JGAPWorkersGP.getNeededFiles (GridNodeWorkerConfig a_config) [inline]
Get jar and other files needed for computation from server .
Parameters
a_config GridNodeWorkerConfig
Todo
Todo implement
Definition at line 55 of file JGAPWorkersGP.java.
Referenced by org.jgap.distr.grid.gp.JGAPWorkersGP.JGAPWorkersGP().
static void org.jgap.distr.grid.gp.JGAPWorkersGP.main (String[] args) throws Exception [inline], [static]
Convenience method to start a workers or multiple instances of it. For possible parameters see method parseCommonOptions in class org.homedns.dade.jcgrid.cmd.MainCmd. The most important parameters are: -n <session name=`` without=`` spaces>=``> -s <server ip=`` address>=``> -d <working directory>=``> -c <number of=`` workers=`` to=`` run>=``>
Parameters
args see above
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 119 of file JGAPWorkersGP.java.
References org.jgap.distr.grid.gp.JGAPWorkersGP.JGAPWorkersGP().
void org.jgap.distr.grid.gp.JGAPWorkersGP.startWork (GridNodeWorkerConfig a_config) throws Exception [inline], [protected]
Definition at line 71 of file JGAPWorkersGP.java.
Referenced by org.jgap.distr.grid.gp.JGAPWorkersGP.JGAPWorkersGP().
Member Data Documentation
final String org.jgap.distr.grid.gp.JGAPWorkersGP.className = JGAPWorkersGP.class.getName() [static], [private]
Definition at line 33 of file JGAPWorkersGP.java.
final String org.jgap.distr.grid.gp.JGAPWorkersGP.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file JGAPWorkersGP.java.
Logger org.jgap.distr.grid.gp.JGAPWorkersGP.log = Logger.getLogger(className) [static], [private]
Definition at line 35 of file JGAPWorkersGP.java.
Class org.jgap.distr.grid.gp.JGAPWorkersGP.m_workerClass [private]
Definition at line 29 of file JGAPWorkersGP.java.
Class org.jgap.distr.grid.gp.JGAPWorkersGP.m_workerFeedbackClaas [private]
Definition at line 31 of file JGAPWorkersGP.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/distr/grid/gp/JGAPWorkersGP.java