examples.gp.tictactoe.CountStones Class Reference
Public Member Functions
CountStones (final GPConfiguration a_conf, Board a_board, int a_color, String a_memoryNameBase) throws InvalidConfigurationException
CountStones (final GPConfiguration a_conf, Board a_board, int a_color, String a_memoryNameBase, int a_subReturnType) throws InvalidConfigurationException
String toString ()
String getName ()
void execute_void (ProgramChromosome c, int n, Object[] args)
Object clone ()
Private Member Functions
void readRow (int i, String a_baseName)
void readCol (int i, String a_baseName)
void readDia (int index, String a_baseName)
void store (String memoryName, int a_count)
Private Attributes
Board m_board
String m_memoryNameBase
int m_color
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
Definition at line 18 of file CountStones.java.
Constructor & Destructor Documentation
examples.gp.tictactoe.CountStones.CountStones (final GPConfiguration a_conf, Board a_board, int a_color, String a_memoryNameBase) throws InvalidConfigurationException [inline]
Definition at line 29 of file CountStones.java.
Referenced by examples.gp.tictactoe.CountStones.clone().
examples.gp.tictactoe.CountStones.CountStones (final GPConfiguration a_conf, Board a_board, int a_color, String a_memoryNameBase, int a_subReturnType) throws InvalidConfigurationException [inline]
Definition at line 35 of file CountStones.java.
References examples.gp.tictactoe.CountStones.m_board, examples.gp.tictactoe.CountStones.m_color, examples.gp.tictactoe.CountStones.m_memoryNameBase, and org.jgap.gp.CommandGene.VoidClass.
Member Function Documentation
Object examples.gp.tictactoe.CountStones.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.6
Implements org.jgap.util.ICloneable.
Definition at line 133 of file CountStones.java.
References examples.gp.tictactoe.CountStones.CountStones(), org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getSubReturnType(), examples.gp.tictactoe.CountStones.m_board, examples.gp.tictactoe.CountStones.m_color, and examples.gp.tictactoe.CountStones.m_memoryNameBase.
void examples.gp.tictactoe.CountStones.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 58 of file CountStones.java.
References org.jgap.gp.CommandGene.check(), examples.gp.tictactoe.Board.HEIGHT, examples.gp.tictactoe.CountStones.m_memoryNameBase, examples.gp.tictactoe.CountStones.readCol(), examples.gp.tictactoe.CountStones.readDia(), examples.gp.tictactoe.CountStones.readRow(), and examples.gp.tictactoe.Board.WIDTH.
String examples.gp.tictactoe.CountStones.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 54 of file CountStones.java.
void examples.gp.tictactoe.CountStones.readCol (int i, String a_baseName) [inline], [private]
Definition at line 84 of file CountStones.java.
References examples.gp.tictactoe.Board.HEIGHT, examples.gp.tictactoe.CountStones.m_board, examples.gp.tictactoe.CountStones.m_color, examples.gp.tictactoe.Board.readField(), and examples.gp.tictactoe.CountStones.store().
Referenced by examples.gp.tictactoe.CountStones.execute_void().
void examples.gp.tictactoe.CountStones.readDia (int index, String a_baseName) [inline], [private]
Definition at line 95 of file CountStones.java.
References examples.gp.tictactoe.Board.HEIGHT, examples.gp.tictactoe.CountStones.m_board, examples.gp.tictactoe.CountStones.m_color, examples.gp.tictactoe.Board.readField(), examples.gp.tictactoe.CountStones.store(), and examples.gp.tictactoe.Board.WIDTH.
Referenced by examples.gp.tictactoe.CountStones.execute_void().
void examples.gp.tictactoe.CountStones.readRow (int i, String a_baseName) [inline], [private]
Definition at line 73 of file CountStones.java.
References examples.gp.tictactoe.CountStones.m_board, examples.gp.tictactoe.CountStones.m_color, examples.gp.tictactoe.Board.readField(), examples.gp.tictactoe.CountStones.store(), and examples.gp.tictactoe.Board.WIDTH.
Referenced by examples.gp.tictactoe.CountStones.execute_void().
void examples.gp.tictactoe.CountStones.store (String memoryName, int a_count) [inline], [private]
Definition at line 121 of file CountStones.java.
References org.jgap.gp.CommandGene.getGPConfiguration().
Referenced by examples.gp.tictactoe.CountStones.readCol(), examples.gp.tictactoe.CountStones.readDia(), and examples.gp.tictactoe.CountStones.readRow().
String examples.gp.tictactoe.CountStones.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 44 of file CountStones.java.
References examples.gp.tictactoe.CountStones.m_color, and examples.gp.tictactoe.CountStones.m_memoryNameBase.
Member Data Documentation
final String examples.gp.tictactoe.CountStones.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 21 of file CountStones.java.
Board examples.gp.tictactoe.CountStones.m_board [private]
Definition at line 23 of file CountStones.java.
Referenced by examples.gp.tictactoe.CountStones.clone(), examples.gp.tictactoe.CountStones.CountStones(), examples.gp.tictactoe.CountStones.readCol(), examples.gp.tictactoe.CountStones.readDia(), and examples.gp.tictactoe.CountStones.readRow().
int examples.gp.tictactoe.CountStones.m_color [private]
Definition at line 27 of file CountStones.java.
Referenced by examples.gp.tictactoe.CountStones.clone(), examples.gp.tictactoe.CountStones.CountStones(), examples.gp.tictactoe.CountStones.readCol(), examples.gp.tictactoe.CountStones.readDia(), examples.gp.tictactoe.CountStones.readRow(), and examples.gp.tictactoe.CountStones.toString().
String examples.gp.tictactoe.CountStones.m_memoryNameBase [private]
Definition at line 25 of file CountStones.java.
Referenced by examples.gp.tictactoe.CountStones.clone(), examples.gp.tictactoe.CountStones.CountStones(), examples.gp.tictactoe.CountStones.execute_void(), and examples.gp.tictactoe.CountStones.toString().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/tictactoe/CountStones.java