org.jgap.supergenes.AbstractSupergene Class Reference
Public Member Functions
Gene[] getGenes ()
final Gene geneAt (final int a_index)
AbstractSupergene () throws InvalidConfigurationException
AbstractSupergene (final Configuration a_config) throws InvalidConfigurationException
AbstractSupergene (final Configuration a_conf, final Gene[] a_genes) throws InvalidConfigurationException
boolean isValid ()
boolean isValid (final Gene[] a_case, final Supergene a_forSupergene)
void applyMutation (final int a_index, final double a_percentage)
void setToRandomValue (final RandomGenerator a_numberGenerator)
void setAllele (final Object a_superAllele)
Object getAllele ()
String getPersistentRepresentation () throws UnsupportedOperationException
void setValueFromPersistentRepresentation (String a_representation) throws UnsupportedRepresentationException
void cleanup ()
String toString ()
int size ()
int compareTo (Object o)
boolean equals (Object a_gene)
int hashCode ()
void addGene (Gene a_gene)
void setValidator (SupergeneValidator a_validator)
SupergeneValidator getValidator ()
String getPersistent ()
void setFromPersistent (String a_from)
Object getInternalValue ()
Static Public Member Functions
static void reset ()
Static Public Attributes
static final String GENE_DELIMITER = `#`
static final String GENE_DELIMITER_HEADING = `<`
static final String GENE_DELIMITER_CLOSING = `>`
static final int MAX_RETRIES = 1
static final int MAX_IMMUTABLE_GENES = 100000
Protected Member Functions
Gene newGeneInternal ()
SupergeneValidator createValidator (String a_rep)
Gene createGene (String a_geneClassName, String a_persistentRepresentation) throws Exception
Static Protected Member Functions
static final List split (String a_string) throws UnsupportedRepresentationException
Protected Attributes
SupergeneValidator m_validator = this
Private Member Functions
void markImmutable (final int a_index)
Private Attributes
Gene[] m_genes
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.24 $`
static Set[] m_immutable = new Set[1]
Detailed Description
Combined implementation of both Supergene and SupergeneValidator. A working supergene can be easily created from this class just by adding genes and overriding [] a_case, Supergene a_forSupergene) isValid (Gene [], Supergene) method. For more complex cases, you may need to set your own Validator.
Author
Audrius Meskauskas
Since
2.0
Definition at line 29 of file AbstractSupergene.java.
Constructor & Destructor Documentation
org.jgap.supergenes.AbstractSupergene.AbstractSupergene () throws InvalidConfigurationException [inline]
Default constructor for dynamic instantiation.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 104 of file AbstractSupergene.java.
Referenced by org.jgap.supergenes.AbstractSupergene.compareTo(), org.jgap.supergenes.AbstractSupergene.equals(), and org.jgap.supergenes.AbstractSupergene.newGeneInternal().
org.jgap.supergenes.AbstractSupergene.AbstractSupergene (final Configuration a_config) throws InvalidConfigurationException [inline]
Constructor for dynamic instantiation.
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 118 of file AbstractSupergene.java.
org.jgap.supergenes.AbstractSupergene.AbstractSupergene (final Configuration a_conf, final Gene[] a_genes) throws InvalidConfigurationException [inline]
Constructs abstract supergene with the given gene list.
Parameters
a_conf the configuration to use
a_genes array of genes for this Supergene
Exceptions
InvalidConfigurationException
Definition at line 130 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.m_genes.
Member Function Documentation
void org.jgap.supergenes.AbstractSupergene.addGene (Gene a_gene) [inline]
Append a new gene to the gene array.
Implements org.jgap.ICompositeGene.
Definition at line 611 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.m_genes.
void org.jgap.supergenes.AbstractSupergene.applyMutation (final int a_index, final double a_percentage) [inline]
Applies a mutation of a given intensity (percentage) onto the gene at the given index. Retries while isValid() returns true for the supergene. The method is delegated to the first element of the gene, indexed by a_index. See org.jgap.supergenes.AbstractSupergene.isValid()
Definition at line 222 of file AbstractSupergene.java.
References org.jgap.BaseGene.getConfiguration(), org.jgap.supergenes.AbstractSupergene.isValid(), org.jgap.supergenes.AbstractSupergene.m_genes, org.jgap.supergenes.AbstractSupergene.m_immutable, org.jgap.supergenes.AbstractSupergene.markImmutable(), org.jgap.supergenes.AbstractSupergene.MAX_RETRIES, and org.jgap.supergenes.AbstractSupergene.size().
void org.jgap.supergenes.AbstractSupergene.cleanup () [inline]
Calls cleanup() for each subgene.
Implements org.jgap.Gene.
Definition at line 499 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.m_genes.
int org.jgap.supergenes.AbstractSupergene.compareTo (Object o) [inline]
Calls compareTo() for all subgenes. The passed parameter must be an instance of AbstractSupergene.
Definition at line 534 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.AbstractSupergene(), and org.jgap.supergenes.AbstractSupergene.m_genes.
Referenced by org.jgap.supergenes.SupergenePersistentRepresentationTest.testCompareTo_0(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testCompareTo_2(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testCompareTo_3(), and org.jgap.supergenes.SupergenePersistentRepresentationTest.testEquals_0().
Gene org.jgap.supergenes.AbstractSupergene.createGene (String a_geneClassName, String a_persistentRepresentation) throws Exception [inline], [protected]
Creates a new instance of gene.
Definition at line 488 of file AbstractSupergene.java.
References org.jgap.BaseGene.getConfiguration().
Referenced by org.jgap.supergenes.AbstractSupergene.setValueFromPersistentRepresentation().
SupergeneValidator org.jgap.supergenes.AbstractSupergene.createValidator (String a_rep) [inline], [protected]
Create validator from the string representation.
Definition at line 453 of file AbstractSupergene.java.
References org.jgap.BaseGene.decode(), org.jgap.supergenes.AbstractSupergene.GENE_DELIMITER, and org.jgap.BaseGene.getConfiguration().
Referenced by org.jgap.supergenes.AbstractSupergene.setValueFromPersistentRepresentation().
boolean org.jgap.supergenes.AbstractSupergene.equals (Object a_gene) [inline]
Calls equals() for each pair of genes. If the supplied object is an instance of the different class, returns false. Also, the genes are assumed to be different if they have different validator classes (or only one of the validators is set to null).
Definition at line 558 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.AbstractSupergene(), org.jgap.supergenes.AbstractSupergene.m_genes, org.jgap.supergenes.AbstractSupergene.m_immutable, and org.jgap.supergenes.AbstractSupergene.m_validator.
Referenced by org.jgap.supergenes.SupergenePersistentRepresentationTest.testEquals_0(), and org.jgap.supergenes.SupergenePersistentRepresentationTest.testRepresentation().
final Gene org.jgap.supergenes.AbstractSupergene.geneAt (final int a_index) [inline]
Returns the Gene at the given index (locus) within the Chromosome. The first gene is at index zero and the last gene is at the index equal to the size of this Chromosome - 1.
This seems to be one of the bottlenecks, so it is declared final. I cannot imagine the reason for overriding this trivial single line method.
Parameters
a_index the index of the gene value to be returned
Returns
the Gene at the given index
Definition at line 92 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.m_genes.
Referenced by org.jgap.supergenes.SupergenePersistentRepresentationTest.testGetGenes_0(), and org.jgap.supergenes.SupergenePersistentRepresentationTest.testSetAllele_2().
Object org.jgap.supergenes.AbstractSupergene.getAllele () [inline]
Retrieves the allele value represented by this Supergene.
Returns
array of objects, each matching the subgene in this Supergene
Implements org.jgap.Gene.
Definition at line 349 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.m_genes.
Gene [] org.jgap.supergenes.AbstractSupergene.getGenes () [inline]
Returns
the array of genes - components of this supergene. The supergene components may be supergenes itself
Implements org.jgap.supergenes.Supergene.
Definition at line 76 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.m_genes.
Referenced by org.jgap.supergenes.SupergenePersistentRepresentationTest.testGetGenes_0().
Object org.jgap.supergenes.AbstractSupergene.getInternalValue () [inline], [virtual]
Returns
not needed for abstract supergene
Implements org.jgap.BaseGene.
Definition at line 654 of file AbstractSupergene.java.
String org.jgap.supergenes.AbstractSupergene.getPersistent () [inline]
Returns
persistent string representation (if needed) of this validator. The method name is different allowing the same class to implement both Supergene and supergeneValidator.
 The default implementation returns an empty string.
Implements org.jgap.supergenes.SupergeneValidator.
Definition at line 642 of file AbstractSupergene.java.
String org.jgap.supergenes.AbstractSupergene.getPersistentRepresentation () throws UnsupportedOperationException [inline]
Returns
a string representation of the value of this Supergene instance, using calls to the Supergene components. Supports other (nested) supergenes in this supergene
Exceptions
UnsupportedOperationException
Implements org.jgap.IPersistentRepresentation.
Definition at line 363 of file AbstractSupergene.java.
References org.jgap.BaseGene.encode(), org.jgap.supergenes.AbstractSupergene.GENE_DELIMITER, org.jgap.supergenes.AbstractSupergene.GENE_DELIMITER_CLOSING, org.jgap.supergenes.AbstractSupergene.GENE_DELIMITER_HEADING, org.jgap.supergenes.AbstractSupergene.getValidator(), and org.jgap.supergenes.AbstractSupergene.m_genes.
SupergeneValidator org.jgap.supergenes.AbstractSupergene.getValidator () [inline]
Gets an object, responsible for deciding if the Supergene allele combination is valid. If no external validator was set and the class uses its own internal validation method, it returns this
Implements org.jgap.supergenes.Supergene.
Definition at line 633 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.m_validator.
Referenced by org.jgap.supergenes.AbstractSupergene.getPersistentRepresentation().
int org.jgap.supergenes.AbstractSupergene.hashCode () [inline]
Returns sum of hashCode() of the genes-components.
Definition at line 571 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.m_genes.
boolean org.jgap.supergenes.AbstractSupergene.isValid () [inline]
Test the allele combination of this supergene for validity. This method calls isValid for the current gene list.
Returns
true only if the supergene allele combination is valid or the setValidator (null) has been previously called
Implements org.jgap.supergenes.Supergene.
Definition at line 145 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.m_genes, and org.jgap.supergenes.AbstractSupergene.m_validator.
Referenced by org.jgap.supergenes.AbstractSupergene.applyMutation(), and org.jgap.supergenes.AbstractSupergene.setToRandomValue().
boolean org.jgap.supergenes.AbstractSupergene.isValid (final Gene[] a_case, final Supergene a_forSupergene) [inline]
Test the given gene list for validity. The genes must exactly the same as inside this supergene. At least about 5 % of the randomly generated Supergene suparallele values should be valid. If the valid combinations represents too small part of all possible combinations, it can take too long to find the suitable mutation that does not brake a supergene. If you face this problem, try to split the supergene into several sub-supergenes.
This method is only called if you have not set any alternative validator (including null).
Parameters
a_case ignored here
a_forSupergene ignored here
Returns
true only if the supergene allele combination is valid
Exceptions
Error by default. If you do not set external validator, you should always override this method
Definition at line 174 of file AbstractSupergene.java.
void org.jgap.supergenes.AbstractSupergene.markImmutable (final int a_index) [inline], [private]
Todo
Todo : Implement protection against overgrowing of this data block.
Definition at line 267 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.m_immutable, org.jgap.supergenes.AbstractSupergene.MAX_IMMUTABLE_GENES, and org.jgap.supergenes.AbstractSupergene.size().
Referenced by org.jgap.supergenes.AbstractSupergene.applyMutation().
Gene org.jgap.supergenes.AbstractSupergene.newGeneInternal () [inline], [protected], [virtual]
Creates a new instance of this Supergene class with the same number of genes, calling newGene() for each subgene. The class, derived from this abstract supergene will be instantiated (not the instance of abstractSupergene itself). If the external validator is set, the same validator will be set for the new gene.
Returns
the new Gene
Exceptions
Error if the instance of this cannot be instantiated (for example, if it is not public or the parameterless constructor is not provided).
Implements org.jgap.BaseGene.
Definition at line 192 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.AbstractSupergene(), org.jgap.BaseGene.getConfiguration(), org.jgap.supergenes.AbstractSupergene.m_genes, and org.jgap.supergenes.AbstractSupergene.m_validator.
static void org.jgap.supergenes.AbstractSupergene.reset () [inline], [static]
Discards all internal caches, ensuring correct repetetive tests of performance. Differently from cleanup(), discards also static references, that are assumed to be useful for the multiple instances of the Supergene. Clears the set of the alleles that are known to be immutable.
Definition at line 293 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.m_immutable.
void org.jgap.supergenes.AbstractSupergene.setAllele (final Object a_superAllele) [inline]
Sets the allele.
Parameters
a_superAllele must be an array of objects, size matching the number of genes
Definition at line 329 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.m_genes.
void org.jgap.supergenes.AbstractSupergene.setFromPersistent (String a_from) [inline]
Set a persistend string representation (if needed) for this validator. The method name is different allowing the same class to implement both Supergene and supergeneValidator. The default implementation does nothing.
Implements org.jgap.supergenes.SupergeneValidator.
Definition at line 648 of file AbstractSupergene.java.
void org.jgap.supergenes.AbstractSupergene.setToRandomValue (final RandomGenerator a_numberGenerator) [inline]
Sets the value of this Gene to a random legal value for the implementation. It calls setToRandomValue for all subgenes and then validates. With a large number of subgenes and low percent of valid combinations this may take too long to complete. We think, at lease several % of the all possible combintations must be valid.
Definition at line 304 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.isValid(), org.jgap.supergenes.AbstractSupergene.m_genes, and org.jgap.supergenes.AbstractSupergene.MAX_RETRIES.
void org.jgap.supergenes.AbstractSupergene.setValidator (SupergeneValidator a_validator) [inline]
Sets an object, responsible for deciding if the Supergene allele combination is valid. If it is set to null, no validation is performed (all combinations are assumed to be valid). If no validator is set, the method isValid (Gene []) is called.
Implements org.jgap.supergenes.Supergene.
Definition at line 624 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.m_validator.
Referenced by org.jgap.supergenes.AbstractSupergene.setValueFromPersistentRepresentation().
void org.jgap.supergenes.AbstractSupergene.setValueFromPersistentRepresentation (String a_representation) throws UnsupportedRepresentationException [inline]
Sets the value and internal state of this Gene from the string representation returned by a previous invocation of the getPersistentRepresentation() method.
If the validator is not THIS and not null, a new validator is created using Class.forName(..).newInstance.
Parameters
a_representation the string representation retrieved from a prior call to the getPersistentRepresentation() method
Exceptions
UnsupportedRepresentationException
Author
Audrius Meskauskas
Since
2.0
Remove the old content.
Implements org.jgap.IPersistentRepresentation.
Definition at line 411 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.createGene(), org.jgap.supergenes.AbstractSupergene.createValidator(), org.jgap.BaseGene.decode(), org.jgap.supergenes.AbstractSupergene.GENE_DELIMITER, org.jgap.supergenes.AbstractSupergene.m_genes, org.jgap.supergenes.AbstractSupergene.setValidator(), and org.jgap.supergenes.AbstractSupergene.split().
int org.jgap.supergenes.AbstractSupergene.size () [inline]
Returns the number of the genes-components of this supergene.
Implements org.jgap.Gene.
Definition at line 528 of file AbstractSupergene.java.
Referenced by org.jgap.supergenes.AbstractSupergene.applyMutation(), org.jgap.supergenes.AbstractSupergene.markImmutable(), org.jgap.supergenes.SupergenePersistentRepresentationTest.testSetAllele_0(), and org.jgap.supergenes.SupergenePersistentRepresentationTest.testSize_0().
static final List org.jgap.supergenes.AbstractSupergene.split (String a_string) throws UnsupportedRepresentationException [inline], [static], [protected]
Splits the string a_x into individual gene representations
Parameters
a_string the string to split
Returns
the elements of the returned array are the persistent representation strings of the genes - components
Author
Audrius Meskauskas
Definition at line 587 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.GENE_DELIMITER_CLOSING, and org.jgap.supergenes.AbstractSupergene.GENE_DELIMITER_HEADING.
Referenced by org.jgap.supergenes.AbstractSupergene.setValueFromPersistentRepresentation().
String org.jgap.supergenes.AbstractSupergene.toString () [inline]
Returns
a string representation of the supergene, providing class name and calling toString() for all subgenes.
Implements org.jgap.Gene.
Definition at line 509 of file AbstractSupergene.java.
References org.jgap.supergenes.AbstractSupergene.m_genes, and org.jgap.supergenes.AbstractSupergene.m_validator.
Member Data Documentation
final String org.jgap.supergenes.AbstractSupergene.CVS_REVISION = `$Revision: 1.24 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 33 of file AbstractSupergene.java.
final String org.jgap.supergenes.AbstractSupergene.GENE_DELIMITER = `#` [static]
This field separates gene class name from the gene persistent representation string.
Definition at line 39 of file AbstractSupergene.java.
Referenced by org.jgap.supergenes.AbstractSupergene.createValidator(), org.jgap.supergenes.AbstractSupergene.getPersistentRepresentation(), and org.jgap.supergenes.AbstractSupergene.setValueFromPersistentRepresentation().
final String org.jgap.supergenes.AbstractSupergene.GENE_DELIMITER_CLOSING = `>` [static]
Represents the closing delimiter that is used to separate genes in the persistent representation of CompositeGene instances.
Definition at line 51 of file AbstractSupergene.java.
Referenced by org.jgap.supergenes.AbstractSupergene.getPersistentRepresentation(), and org.jgap.supergenes.AbstractSupergene.split().
final String org.jgap.supergenes.AbstractSupergene.GENE_DELIMITER_HEADING = `<` [static]
Represents the heading delimiter that is used to separate genes in the persistent representation of CompositeGene instances.
Definition at line 45 of file AbstractSupergene.java.
Referenced by org.jgap.supergenes.AbstractSupergene.getPersistentRepresentation(), and org.jgap.supergenes.AbstractSupergene.split().
Gene [] org.jgap.supergenes.AbstractSupergene.m_genes [private]
Holds the genes of this supergene.
Definition at line 67 of file AbstractSupergene.java.
Referenced by org.jgap.supergenes.AbstractSupergene.AbstractSupergene(), org.jgap.supergenes.AbstractSupergene.addGene(), org.jgap.supergenes.AbstractSupergene.applyMutation(), org.jgap.supergenes.AbstractSupergene.cleanup(), org.jgap.supergenes.AbstractSupergene.compareTo(), org.jgap.supergenes.AbstractSupergene.equals(), org.jgap.supergenes.AbstractSupergene.geneAt(), org.jgap.supergenes.AbstractSupergene.getAllele(), org.jgap.supergenes.AbstractSupergene.getGenes(), org.jgap.supergenes.AbstractSupergene.getPersistentRepresentation(), org.jgap.supergenes.AbstractSupergene.hashCode(), org.jgap.supergenes.AbstractSupergene.isValid(), org.jgap.supergenes.AbstractSupergene.newGeneInternal(), org.jgap.supergenes.AbstractSupergene.setAllele(), org.jgap.supergenes.AbstractSupergene.setToRandomValue(), org.jgap.supergenes.AbstractSupergene.setValueFromPersistentRepresentation(), and org.jgap.supergenes.AbstractSupergene.toString().
Set [] org.jgap.supergenes.AbstractSupergene.m_immutable = new Set[1] [static], [private]
Set of supergene allele values that cannot mutate.
Definition at line 70 of file AbstractSupergene.java.
Referenced by org.jgap.supergenes.AbstractSupergene.applyMutation(), org.jgap.supergenes.AbstractSupergene.equals(), org.jgap.supergenes.AbstractSupergene.markImmutable(), and org.jgap.supergenes.AbstractSupergene.reset().
SupergeneValidator org.jgap.supergenes.AbstractSupergene.m_validator = this [protected]
A validator (initially set to this
Definition at line 638 of file AbstractSupergene.java.
Referenced by org.jgap.supergenes.AbstractSupergene.equals(), org.jgap.supergenes.AbstractSupergene.getValidator(), org.jgap.supergenes.AbstractSupergene.isValid(), org.jgap.supergenes.AbstractSupergene.newGeneInternal(), org.jgap.supergenes.AbstractSupergene.setValidator(), and org.jgap.supergenes.AbstractSupergene.toString().
final int org.jgap.supergenes.AbstractSupergene.MAX_IMMUTABLE_GENES = 100000 [static]
Maximal number of notes about immutable genes per single gene position
Definition at line 64 of file AbstractSupergene.java.
Referenced by org.jgap.supergenes.AbstractSupergene.markImmutable().
final int org.jgap.supergenes.AbstractSupergene.MAX_RETRIES = 1 [static]
Maximal number of retries for applyMutation and setToRandomValue. If the valid supergen cannot be created after this number of iterations, the error message is printed and the unchanged instance is returned.
Definition at line 58 of file AbstractSupergene.java.
Referenced by org.jgap.supergenes.AbstractSupergene.applyMutation(), and org.jgap.supergenes.AbstractSupergene.setToRandomValue().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/supergenes/AbstractSupergene.java