org.jgap.util.JarResources Class Reference
Public Member Functions
JarResources (String jarFileName)
byte[] getResource (String name)
Static Public Member Functions
static void main (String[] args) throws IOException
Public Attributes
boolean debugOn = false
Private Member Functions
void init ()
String dumpZipEntry (ZipEntry a_ze)
Private Attributes
Hashtable htSizes = new Hashtable()
Hashtable htJarContents = new Hashtable()
String jarFileName
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Detailed Description
JarResources maps all resources included in a zip or jar file. Additionaly, it provides a method to extract one as a blob.
Author
unknown
Klaus Meffert (integrated into JGAP)
Since
3.2
Definition at line 24 of file JarResources.java.
Constructor & Destructor Documentation
org.jgap.util.JarResources.JarResources (String jarFileName) [inline]
creates a JarResources. It extracts all resources from a Jar into an internal hashtable, keyed by resource names.
Parameters
jarFileName a jar or zip file
Definition at line 44 of file JarResources.java.
References org.jgap.util.JarResources.init(), and org.jgap.util.JarResources.jarFileName.
Referenced by org.jgap.util.JarResources.main().
Member Function Documentation
String org.jgap.util.JarResources.dumpZipEntry (ZipEntry a_ze) [inline], [private]
Dumps a zip entry into a string.
Parameters
a_ze a ZipEntry
Returns
info about the zip entry
Definition at line 129 of file JarResources.java.
Referenced by org.jgap.util.JarResources.init().
byte [] org.jgap.util.JarResources.getResource (String name) [inline]
Extracts a jar resource as a blob.
Parameters
name a resource name
Returns
extracted blob
Definition at line 55 of file JarResources.java.
Referenced by org.jgap.util.JarClassLoader.loadClassBytes().
void org.jgap.util.JarResources.init () [inline], [private]
initializes internal hash tables with Jar file resources.
Definition at line 62 of file JarResources.java.
References org.jgap.util.JarResources.debugOn, org.jgap.util.JarResources.dumpZipEntry(), org.jgap.util.JarResources.htSizes, and org.jgap.util.JarResources.jarFileName.
Referenced by org.jgap.util.JarResources.JarResources().
static void org.jgap.util.JarResources.main (String[] args) throws IOException [inline], [static]
Is a test driver. Given a jar file and a resource name, it trys to extract the resource and then tells us whether it could or not.
Example Let's say you have a JAR file which jarred up a bunch of gif image files. Now, by using JarResources, you could extract, create, and display those images on-the-fly.
    ...
    JarResources JR=new JarResources("GifBundle.jar");
    Image image=Toolkit.createImage(JR.getResource("logo.gif");
    Image logo=Toolkit.getDefaultToolkit().createImage(
                  JR.getResources("logo.gif")
);
    ...
Parameters
args arguments
Exceptions
IOException
Definition at line 173 of file JarResources.java.
References org.jgap.util.JarResources.JarResources().
Member Data Documentation
final String org.jgap.util.JarResources.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file JarResources.java.
boolean org.jgap.util.JarResources.debugOn = false
Definition at line 29 of file JarResources.java.
Referenced by org.jgap.util.JarResources.init().
Hashtable org.jgap.util.JarResources.htJarContents = new Hashtable() [private]
Definition at line 34 of file JarResources.java.
Hashtable org.jgap.util.JarResources.htSizes = new Hashtable() [private]
Definition at line 32 of file JarResources.java.
Referenced by org.jgap.util.JarResources.init().
String org.jgap.util.JarResources.jarFileName [private]
Definition at line 37 of file JarResources.java.
Referenced by org.jgap.util.JarResources.init(), and org.jgap.util.JarResources.JarResources().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/util/JarResources.java