org.jgap.impl.DefaultConfigurationTest Class Reference
Classes
class DefaultConfigForTesting
Public Member Functions
void testConstruct_0 ()
void testConstruct_1 ()
void testConstruct_2 () throws Exception
void testConstruct_3 () throws Exception
void testClone_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.20 $`
Additional Inherited Members
Detailed Description
Tests the DefaultConfiguration class.
Author
Klaus Meffert
Since
1.1
Definition at line 23 of file DefaultConfigurationTest.java.
Member Function Documentation
static Test org.jgap.impl.DefaultConfigurationTest.suite () [inline], [static]
Definition at line 28 of file DefaultConfigurationTest.java.
void org.jgap.impl.DefaultConfigurationTest.testClone_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 115 of file DefaultConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.Configuration.clone(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DefaultConfigurationTest.testConstruct_0 () [inline]
Author
Klaus Meffert
Since
1.1
Definition at line 37 of file DefaultConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.Configuration.getChromosomePool(), org.jgap.Configuration.getEventManager(), org.jgap.Configuration.getFitnessEvaluator(), org.jgap.Configuration.getGeneticOperators(), org.jgap.Configuration.getNaturalSelectors(), and org.jgap.Configuration.getRandomGenerator().
void org.jgap.impl.DefaultConfigurationTest.testConstruct_1 () [inline]
Provoke error during initialization.
Author
Klaus Meffert
Since
2.6
Definition at line 71 of file DefaultConfigurationTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DefaultConfigurationTest.testConstruct_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 87 of file DefaultConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.DefaultConfigurationTest.testConstruct_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 101 of file DefaultConfigurationTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
Member Data Documentation
final String org.jgap.impl.DefaultConfigurationTest.CVS_REVISION = `$Revision: 1.20 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file DefaultConfigurationTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/DefaultConfigurationTest.java