org.jgap.gp.function.If Class Reference
Public Member Functions
If (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException
If (final GPConfiguration a_conf, Class a_childType, Class a_returnType) throws InvalidConfigurationException
Class getChildType (IGPProgram prog, int index)
String toString ()
boolean execute_boolean (ProgramChromosome c, int n, Object[] args)
int execute_int (ProgramChromosome c, int n, Object[] args)
long execute_long (ProgramChromosome c, int n, Object[] args)
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
void execute_void (ProgramChromosome c, int n, Object[] args)
Object clone ()
Private Attributes
Class m_childType
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.9 $`
Additional Inherited Members
Detailed Description
The if-then construct.
Author
Klaus Meffert
Since
3.0
Definition at line 23 of file If.java.
Constructor & Destructor Documentation
org.jgap.gp.function.If.If (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 30 of file If.java.
References org.jgap.gp.function.If.m_childType.
Referenced by org.jgap.gp.function.If.clone().
org.jgap.gp.function.If.If (final GPConfiguration a_conf, Class a_childType, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 36 of file If.java.
References org.jgap.gp.function.If.m_childType.
Member Function Documentation
Object org.jgap.gp.function.If.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 134 of file If.java.
References org.jgap.gp.function.If.getChildType(), org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.function.If.If().
boolean org.jgap.gp.function.If.execute_boolean (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 55 of file If.java.
double org.jgap.gp.function.If.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 109 of file If.java.
float org.jgap.gp.function.If.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 100 of file If.java.
int org.jgap.gp.function.If.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 64 of file If.java.
References org.jgap.gp.CommandGene.BooleanClass, org.jgap.gp.CommandGene.DoubleClass, org.jgap.gp.CommandGene.FloatClass, org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.CommandGene.LongClass, and org.jgap.gp.function.If.m_childType.
long org.jgap.gp.function.If.execute_long (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 91 of file If.java.
void org.jgap.gp.function.If.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Todo
Todo add option for type of first child to constructor
Definition at line 118 of file If.java.
Class org.jgap.gp.function.If.getChildType (IGPProgram prog, int index) [inline]
Definition at line 42 of file If.java.
References org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.function.If.m_childType.
Referenced by org.jgap.gp.function.If.clone().
String org.jgap.gp.function.If.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 51 of file If.java.
Member Data Documentation
final String org.jgap.gp.function.If.CVS_REVISION = `$Revision: 1.9 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file If.java.
Class org.jgap.gp.function.If.m_childType [private]
Definition at line 28 of file If.java.
Referenced by org.jgap.gp.function.If.execute_int(), org.jgap.gp.function.If.getChildType(), and org.jgap.gp.function.If.If().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/If.java