org.jgap.impl.DefaultMutationRateCalculator Class Reference
Public Member Functions
DefaultMutationRateCalculator (Configuration a_config) throws InvalidConfigurationException
int calculateCurrentRate ()
boolean toBePermutated (IChromosome a_chrom, int a_geneIndex)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.17 $`
Additional Inherited Members
Detailed Description
Default implementation of a mutation rate calculcator.
Author
Klaus Meffert
Since
1.1
Definition at line 20 of file DefaultMutationRateCalculator.java.
Constructor & Destructor Documentation
org.jgap.impl.DefaultMutationRateCalculator.DefaultMutationRateCalculator (Configuration a_config) throws InvalidConfigurationException [inline]
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 32 of file DefaultMutationRateCalculator.java.
Member Function Documentation
int org.jgap.impl.DefaultMutationRateCalculator.calculateCurrentRate () [inline]
Calculates the mutation rate.
Returns
calculated divisor of mutation rate probability (dividend is 1)
Author
Klaus Meffert
Since
1.1 (same functionality as earlier, but not encapsulated)
Implements org.jgap.IUniversalRateCalculator.
Definition at line 45 of file DefaultMutationRateCalculator.java.
References org.jgap.BaseRateCalculator.getConfiguration().
Referenced by org.jgap.impl.DefaultMutationRateCalculator.toBePermutated().
boolean org.jgap.impl.DefaultMutationRateCalculator.toBePermutated (IChromosome a_chrom, int a_geneIndex) [inline]
Determines whether mutation is to be carried out. In this case the rate is the size of the chromosome. There is therefore a probability of 1/totalgenes that a particular gene mutates.
Parameters
a_chrom ignored
a_geneIndex ignored
Returns
true if gene should be mutated
Author
Chris Knowles
Since
2.0
Implements org.jgap.IUniversalRateCalculator.
Definition at line 65 of file DefaultMutationRateCalculator.java.
References org.jgap.impl.DefaultMutationRateCalculator.calculateCurrentRate(), org.jgap.BaseRateCalculator.getConfiguration(), and org.jgap.RandomGenerator.nextInt().
Member Data Documentation
final String org.jgap.impl.DefaultMutationRateCalculator.CVS_REVISION = `$Revision: 1.17 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 23 of file DefaultMutationRateCalculator.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/DefaultMutationRateCalculator.java