org.jgap.util.MultiClassLoader Class Reference
Public Member Functions
MultiClassLoader ()
Class loadClass (String className) throws ClassNotFoundException
synchronized Class loadClass (String className, boolean resolveIt) throws ClassNotFoundException
void setClassNameReplacementChar (char replacement)
Protected Member Functions
abstract byte[] loadClassBytes (String className)
String formatClassName (String className)
void monitor (String text)
Static Protected Member Functions
static void print (String text)
Protected Attributes
boolean monitorOn = false
boolean sourceMonitorOn = true
Private Attributes
Hashtable classes = new Hashtable()
char classNameReplacementChar
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Detailed Description
A simple test class loader capable of loading from multiple sources, such as local files or a URL.
This class is derived from an article by Chuck McManis http://www.javaworld.com/javaworld/jw-10-1996/indepth.src.html with large modifications.
Note that this has been updated to use the non-deprecated version of defineClass() -- JDM.
Author
Jack Harich - 8/18/97
John D. Mitchell - 99.03.04
Klaus Meffert (integrated into JGAP)
Since
3.2
Definition at line 31 of file MultiClassLoader.java.
Constructor & Destructor Documentation
org.jgap.util.MultiClassLoader.MultiClassLoader () [inline]
Definition at line 45 of file MultiClassLoader.java.
Member Function Documentation
String org.jgap.util.MultiClassLoader.formatClassName (String className) [inline], [protected]
Definition at line 112 of file MultiClassLoader.java.
References org.jgap.util.MultiClassLoader.classNameReplacementChar.
Referenced by org.jgap.util.JarClassLoader.loadClassBytes().
Class org.jgap.util.MultiClassLoader.loadClass (String className) throws ClassNotFoundException [inline]
This is a simple version for external clients since they will always want the class resolved before it is returned to them.
Definition at line 53 of file MultiClassLoader.java.
synchronized Class org.jgap.util.MultiClassLoader.loadClass (String className, boolean resolveIt) throws ClassNotFoundException [inline]
Definition at line 58 of file MultiClassLoader.java.
References org.jgap.util.MultiClassLoader.classes, org.jgap.util.MultiClassLoader.loadClassBytes(), and org.jgap.util.MultiClassLoader.monitor().
abstract byte [] org.jgap.util.MultiClassLoader.loadClassBytes (String className) [protected], [pure virtual]
Referenced by org.jgap.util.MultiClassLoader.loadClass().
void org.jgap.util.MultiClassLoader.monitor (String text) [inline], [protected]
Definition at line 124 of file MultiClassLoader.java.
References org.jgap.util.MultiClassLoader.monitorOn, and org.jgap.util.MultiClassLoader.print().
Referenced by org.jgap.util.MultiClassLoader.loadClass().
static void org.jgap.util.MultiClassLoader.print (String text) [inline], [static], [protected]
Definition at line 129 of file MultiClassLoader.java.
Referenced by org.jgap.util.MultiClassLoader.monitor().
void org.jgap.util.MultiClassLoader.setClassNameReplacementChar (char replacement) [inline]
This optional call allows a class name such as `COM.test.Hello` to be changed to `COM_test_Hello`, which is useful for storing classes from different packages in the same retrival directory. In the above example the char would be '_'.
Definition at line 106 of file MultiClassLoader.java.
References org.jgap.util.MultiClassLoader.classNameReplacementChar.
Member Data Documentation
Hashtable org.jgap.util.MultiClassLoader.classes = new Hashtable() [private]
Definition at line 37 of file MultiClassLoader.java.
Referenced by org.jgap.util.MultiClassLoader.loadClass().
char org.jgap.util.MultiClassLoader.classNameReplacementChar [private]
Definition at line 39 of file MultiClassLoader.java.
Referenced by org.jgap.util.MultiClassLoader.formatClassName(), and org.jgap.util.MultiClassLoader.setClassNameReplacementChar().
final String org.jgap.util.MultiClassLoader.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 34 of file MultiClassLoader.java.
boolean org.jgap.util.MultiClassLoader.monitorOn = false [protected]
Definition at line 41 of file MultiClassLoader.java.
Referenced by org.jgap.util.MultiClassLoader.monitor().
boolean org.jgap.util.MultiClassLoader.sourceMonitorOn = true [protected]
Definition at line 43 of file MultiClassLoader.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/util/MultiClassLoader.java