examples.gp.paintedDesert.AntCommand Class Reference
Public Member Functions
AntCommand (final GPConfiguration a_conf, int a_arity, Class a_type) throws InvalidConfigurationException
AntCommand (final GPConfiguration a_conf, final int a_arity, final Class a_returnType, final int a_subReturnType, final int[] a_childSubTypes) throws InvalidConfigurationException
AntMap getMap (ProgramChromosome a_chrom)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Additional Inherited Members
Detailed Description
Abstract base class for GP-commands related to the ant painted desert problem. Derived from class AntCommand from the ant trail example.
Author
Scott Mueller
Since
3.2
Definition at line 23 of file AntCommand.java.
Constructor & Destructor Documentation
examples.gp.paintedDesert.AntCommand.AntCommand (final GPConfiguration a_conf, int a_arity, Class a_type) throws InvalidConfigurationException [inline]
Definition at line 28 of file AntCommand.java.
examples.gp.paintedDesert.AntCommand.AntCommand (final GPConfiguration a_conf, final int a_arity, final Class a_returnType, final int a_subReturnType, final int[] a_childSubTypes) throws InvalidConfigurationException [inline]
Definition at line 33 of file AntCommand.java.
Member Function Documentation
AntMap examples.gp.paintedDesert.AntCommand.getMap (ProgramChromosome a_chrom) [inline]
Definition at line 40 of file AntCommand.java.
References org.jgap.gp.CommandGene.getApplicationData().
Referenced by examples.gp.paintedDesert.MayDropSand.execute_boolean(), examples.gp.paintedDesert.MayPickUp.execute_boolean(), examples.gp.paintedDesert.SandBelongsHere.execute_boolean(), examples.gp.paintedDesert.SandAtLocation.execute_boolean(), examples.gp.paintedDesert.Pickup.execute_int(), examples.gp.paintedDesert.Carrying.execute_int(), examples.gp.paintedDesert.Drop.execute_int(), examples.gp.paintedDesert.SandColor.execute_int(), examples.gp.paintedDesert.Y.execute_int(), examples.gp.paintedDesert.X.execute_int(), examples.gp.paintedDesert.MoveRandom.execute_void(), examples.gp.paintedDesert.GO_W.execute_void(), examples.gp.paintedDesert.GO_N.execute_void(), examples.gp.paintedDesert.GO_S.execute_void(), examples.gp.paintedDesert.GO_E.execute_void(), and examples.gp.paintedDesert.IfDrop.execute_void().
Member Data Documentation
final String examples.gp.paintedDesert.AntCommand.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file AntCommand.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/paintedDesert/AntCommand.java