examples.gp.monalisa.core.DrawingGPConfiguration Class Reference
Public Member Functions
DrawingGPConfiguration (BufferedImage a_target) throws InvalidConfigurationException
BufferedImage getTarget ()
Protected Attributes
BufferedImage m_target = null
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
Encapsulates the settings of the genetic algorithm.
Author
Yann N. Dauphin
Klaus Meffert
Since
3.4
Definition at line 23 of file DrawingGPConfiguration.java.
Constructor & Destructor Documentation
examples.gp.monalisa.core.DrawingGPConfiguration.DrawingGPConfiguration (BufferedImage a_target) throws InvalidConfigurationException [inline]
Definition at line 30 of file DrawingGPConfiguration.java.
References examples.gp.monalisa.core.DrawingGPConfiguration.m_target, org.jgap.gp.impl.GPConfiguration.setCrossoverProb(), org.jgap.gp.impl.GPConfiguration.setFitnessFunction(), org.jgap.gp.impl.GPConfiguration.setGPFitnessEvaluator(), org.jgap.gp.impl.GPConfiguration.setInitStrategy(), org.jgap.gp.impl.GPConfiguration.setMaxCrossoverDepth(), org.jgap.gp.impl.GPConfiguration.setMaxInitDepth(), org.jgap.gp.impl.GPConfiguration.setMinInitDepth(), org.jgap.gp.impl.GPConfiguration.setMutationProb(), org.jgap.gp.impl.GPConfiguration.setNewChromsPercent(), org.jgap.gp.impl.GPConfiguration.setNodeValidator(), org.jgap.Configuration.setPopulationSize(), org.jgap.gp.impl.GPConfiguration.setProgramCreationMaxTries(), org.jgap.gp.impl.GPConfiguration.setReproductionProb(), org.jgap.gp.impl.GPConfiguration.setSelectionMethod(), and org.jgap.gp.impl.GPConfiguration.setStrictProgramCreation().
Member Function Documentation
BufferedImage examples.gp.monalisa.core.DrawingGPConfiguration.getTarget () [inline]
Get the target image of the drawing problem.
Returns
the value of target
Definition at line 55 of file DrawingGPConfiguration.java.
References examples.gp.monalisa.core.DrawingGPConfiguration.m_target.
Referenced by examples.gp.monalisa.core.DrawingProblem.create().
Member Data Documentation
final String examples.gp.monalisa.core.DrawingGPConfiguration.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file DrawingGPConfiguration.java.
BufferedImage examples.gp.monalisa.core.DrawingGPConfiguration.m_target = null [protected]
Definition at line 28 of file DrawingGPConfiguration.java.
Referenced by examples.gp.monalisa.core.DrawingGPConfiguration.DrawingGPConfiguration(), and examples.gp.monalisa.core.DrawingGPConfiguration.getTarget().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/monalisa/core/DrawingGPConfiguration.java