org.jgap.BaseChromosome Class Reference
Public Member Functions
BaseChromosome (Configuration a_configuration) throws InvalidConfigurationException
String getUniqueID ()
void setUniqueIDTemplate (String a_templateID, int a_index)
String getUniqueIDTemplate (int a_index)
Configuration getConfiguration ()
abstract Object clone ()
void increaseAge ()
void resetAge ()
int getAge ()
void setAge (int a_age)
void increaseOperatedOn ()
void resetOperatedOn ()
int operatedOn ()
synchronized Gene[] getGenes ()
void setGenes (Gene[] a_genes) throws InvalidConfigurationException
synchronized Gene getGene (int a_desiredLocus)
void setGene (int a_index, Gene a_gene)
int size ()
String getPersistentRepresentation ()
StringBuffer getGenesPersistentRepresentation ()
String getBusinessKey ()
void getGenesPersistentRepresentation (StringBuffer a_buffer)
void setValueFromPersistentRepresentation (String a_representation) throws UnsupportedRepresentationException
Static Public Attributes
static final String GENE_DELIMITER = `#`
static final String GENE_DELIMITER_HEADING = `<`
static final String GENE_DELIMITER_CLOSING = `>`
static final String CHROM_DELIMITER = `#`
Protected Member Functions
String encode (String a_string)
String decode (String a_string) throws UnsupportedEncodingException
Gene createGene (String a_geneClassName, String a_persistentRepresentation) throws Exception
Static Protected Member Functions
static final List split (String a_string) throws UnsupportedRepresentationException
Private Attributes
Configuration m_configuration
Gene[] m_genes
int m_age
int m_operatedOn
String m_uniqueID
Map< Integer, String > m_uniqueIDTemplates
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.15 $`
Detailed Description
Base class for any implementation of interface IChromosome.
Author
Klaus Meffert
Since
3.0
Definition at line 25 of file BaseChromosome.java.
Constructor & Destructor Documentation
org.jgap.BaseChromosome.BaseChromosome (Configuration a_configuration) throws InvalidConfigurationException [inline]
The only constructor in this class. Sets the immutable configuration.
Parameters
a_configuration the configuration to set
Exceptions
InvalidConfigurationException if configuration is null
Author
Klaus Meffert
Since
3.0
Definition at line 88 of file BaseChromosome.java.
References org.jgap.Configuration.getJGAPFactory(), org.jgap.Configuration.isUniqueKeysActive(), org.jgap.BaseChromosome.m_configuration, org.jgap.BaseChromosome.m_uniqueID, and org.jgap.BaseChromosome.m_uniqueIDTemplates.
Member Function Documentation
abstract Object org.jgap.BaseChromosome.clone () [pure virtual]
Creates and returns a copy of this object.
Returns
a clone of this instance
Exceptions
IllegalStateException instead of CloneNotSupportedException
Author
Klaus Meffert
Since
3.0
Implements org.jgap.util.ICloneable.
Implemented in org.jgap.Chromosome, and org.jgap.ChromosomeForTesting.
Gene org.jgap.BaseChromosome.createGene (String a_geneClassName, String a_persistentRepresentation) throws Exception [inline], [protected]
Creates a new Gene instance.
Taken from CompositeGene.
Parameters
a_geneClassName name of the gene class
a_persistentRepresentation persistent representation of the gene to create (could be obtained via getPersistentRepresentation)
Returns
newly created gene
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 457 of file BaseChromosome.java.
References org.jgap.BaseChromosome.getConfiguration().
Referenced by org.jgap.BaseChromosome.setValueFromPersistentRepresentation().
String org.jgap.BaseChromosome.decode (String a_string) throws UnsupportedEncodingException [inline], [protected]
Definition at line 385 of file BaseChromosome.java.
Referenced by org.jgap.BaseChromosome.setValueFromPersistentRepresentation().
String org.jgap.BaseChromosome.encode (String a_string) [inline], [protected]
Definition at line 381 of file BaseChromosome.java.
Referenced by org.jgap.BaseChromosome.getGenesPersistentRepresentation().
int org.jgap.BaseChromosome.getAge () [inline]
Returns
0: Chromosome newly created in this generation. This means it does not need being crossed over with another newly created one
Author
Klaus Meffert
Since
3.2
Implements org.jgap.IChromosome.
Definition at line 193 of file BaseChromosome.java.
References org.jgap.BaseChromosome.m_age.
String org.jgap.BaseChromosome.getBusinessKey () [inline]
Returns
business key of the chromosome
Author
Klaus Meffert
Since
3.2
Implements org.jgap.IBusinessKey.
Definition at line 356 of file BaseChromosome.java.
References org.jgap.BaseChromosome.getGenesPersistentRepresentation().
Configuration org.jgap.BaseChromosome.getConfiguration () [inline]
Returns
the configuration used
Author
Klaus Meffert
Since
3.0
Implements org.jgap.IChromosome.
Definition at line 150 of file BaseChromosome.java.
References org.jgap.BaseChromosome.m_configuration.
Referenced by org.jgap.Chromosome.calcFitnessValue(), org.jgap.Chromosome.cleanup(), org.jgap.ChromosomeForTesting.clone(), org.jgap.Chromosome.clone(), org.jgap.Chromosome.cloneObject(), org.jgap.Chromosome.compareTo(), org.jgap.BaseChromosome.createGene(), org.jgap.Chromosome.perform(), and org.jgap.ChromosomeForTesting.randomInitialChromosome2().
synchronized Gene org.jgap.BaseChromosome.getGene (int a_desiredLocus) [inline]
Returns the Gene at the given index (locus) within the Chromosome. The first gene is at index zero and the last gene is at the index equal to the size of this Chromosome - 1.
Parameters
a_desiredLocus index of the gene value to be returned
Returns
Gene at the given index
Author
Neil Rotstan
Since
1.0
Implements org.jgap.IChromosome.
Definition at line 283 of file BaseChromosome.java.
References org.jgap.BaseChromosome.m_genes.
Referenced by org.jgap.Chromosome.cleanup(), org.jgap.Chromosome.clone(), org.jgap.Chromosome.compareTo(), org.jgap.BaseChromosome.getGenesPersistentRepresentation(), org.jgap.Chromosome.hashCode(), org.jgap.ChromosomeTest.testConstruct_10(), org.jgap.ChromosomeTest.testConstruct_7_3(), org.jgap.impl.MutationOperatorTest.testOperate_3_1(), org.jgap.impl.TwoWayMutationOperatorTest.testOperate_3_1(), org.jgap.Chromosome.toString(), and org.jgap.Chromosome.verify().
synchronized Gene [] org.jgap.BaseChromosome.getGenes () [inline]
Retrieves the set of genes that make up this Chromosome. This method exists primarily for the benefit of GeneticOperators that require the ability to manipulate Chromosomes at a low level.
Returns
an array of the Genes contained within this Chromosome
Author
Neil Rotstan
Since
1.0
Implements org.jgap.IChromosome.
Definition at line 252 of file BaseChromosome.java.
References org.jgap.BaseChromosome.m_genes.
Referenced by org.jgap.Chromosome.hashCode(), org.jgap.ChromosomeTest.testClone_1(), org.jgap.ChromosomeTest.testConstruct_7_3(), and org.jgap.Chromosome.verify().
StringBuffer org.jgap.BaseChromosome.getGenesPersistentRepresentation () [inline]
Returns
the persistent representation of the chromosome by considering its genes.
Author
Klaus Meffert
Definition at line 344 of file BaseChromosome.java.
Referenced by org.jgap.BaseChromosome.getBusinessKey(), and org.jgap.BaseChromosome.getPersistentRepresentation().
void org.jgap.BaseChromosome.getGenesPersistentRepresentation (StringBuffer a_buffer) [inline]
Retrieves the persistent representation of the chromosome by considering its genes.
Parameters
a_buffer the variable to store the persistent representation in
Author
Klaus Meffert
Definition at line 368 of file BaseChromosome.java.
References org.jgap.BaseChromosome.encode(), org.jgap.BaseChromosome.GENE_DELIMITER, org.jgap.BaseChromosome.GENE_DELIMITER_CLOSING, org.jgap.BaseChromosome.GENE_DELIMITER_HEADING, org.jgap.BaseChromosome.getGene(), org.jgap.Gene.getPersistentRepresentation(), and org.jgap.BaseChromosome.size().
String org.jgap.BaseChromosome.getPersistentRepresentation () [inline]
Returns a persistent representation of this chromosome, see interface Gene for description. Similar to CompositeGene's routine. But does not include all information of the chromosome (yet).
Returns
string representation of this Chromosome's relevant parts of its current state
Exceptions
UnsupportedOperationException
Author
Klaus Meffert
Since
3.2
Implements org.jgap.IPersistentRepresentation.
Definition at line 324 of file BaseChromosome.java.
References org.jgap.BaseChromosome.CHROM_DELIMITER, org.jgap.IChromosome.getFitnessValueDirectly(), org.jgap.BaseChromosome.getGenesPersistentRepresentation(), and org.jgap.BaseChromosome.size().
Referenced by org.jgap.ChromosomeTest.testConstruct_9(), org.jgap.ChromosomeTest.testPersistentRepresentation_0(), org.jgap.ChromosomeTest.testPersistentRepresentation_1(), and org.jgap.ChromosomeTest.testPersistentRepresentation_7().
String org.jgap.BaseChromosome.getUniqueID () [inline]
Returns
unique ID of the chromosome, which allows to distinct this instance from others, in the best case worldwide
Author
Klaus Meffert
Since
3.5
Implements org.jgap.IUniqueKey.
Definition at line 112 of file BaseChromosome.java.
References org.jgap.BaseChromosome.m_uniqueID.
String org.jgap.BaseChromosome.getUniqueIDTemplate (int a_index) [inline]
Parameters
a_index the index of the template to retrieve the key for
Returns
String
Author
Klaus Meffert
Since
3.5
Implements org.jgap.IUniqueKey.
Definition at line 140 of file BaseChromosome.java.
void org.jgap.BaseChromosome.increaseAge () [inline]
Increases the number of evolutionary rounds of chromosome in which it has not been changed by one.
Author
Klaus Meffert
Since
3.2
Implements org.jgap.IChromosome.
Definition at line 172 of file BaseChromosome.java.
References org.jgap.BaseChromosome.m_age.
void org.jgap.BaseChromosome.increaseOperatedOn () [inline]
Increase information of number of genetic operations performed on chromosome in current evolution round.
Author
Klaus Meffert
Since
3.2
Implements org.jgap.IChromosome.
Definition at line 215 of file BaseChromosome.java.
References org.jgap.BaseChromosome.m_operatedOn.
int org.jgap.BaseChromosome.operatedOn () [inline]
Returns
number of genetic operations performed on chromosome in current evolution round
Author
Klaus Meffert
Since
3.2
Implements org.jgap.IChromosome.
Definition at line 238 of file BaseChromosome.java.
References org.jgap.BaseChromosome.m_operatedOn.
void org.jgap.BaseChromosome.resetAge () [inline]
Reset age of chromosome because it has been changed.
Author
Klaus Meffert
Since
3.2
Implements org.jgap.IChromosome.
Definition at line 182 of file BaseChromosome.java.
References org.jgap.BaseChromosome.m_age.
void org.jgap.BaseChromosome.resetOperatedOn () [inline]
Resets the information of how many genetic operators have been performed on the chromosome in the current round of evolution.
Author
Klaus Meffert
Since
3.2
Implements org.jgap.IChromosome.
Definition at line 227 of file BaseChromosome.java.
References org.jgap.BaseChromosome.m_operatedOn.
void org.jgap.BaseChromosome.setAge (int a_age) [inline]
Parameters
a_age set the age of the chromosome, see BestChromosomesSelector for a use-case
Author
Klaus Meffert
Since
3.3.3
Implements org.jgap.IChromosome.
Definition at line 204 of file BaseChromosome.java.
References org.jgap.BaseChromosome.m_age.
void org.jgap.BaseChromosome.setGene (int a_index, Gene a_gene) [inline]
Definition at line 287 of file BaseChromosome.java.
References org.jgap.BaseChromosome.m_genes.
Referenced by org.jgap.Chromosome.initFromGene(), and org.jgap.BaseChromosome.setValueFromPersistentRepresentation().
void org.jgap.BaseChromosome.setGenes (Gene[] a_genes) throws InvalidConfigurationException [inline]
Sets the genes for the chromosome.
Parameters
a_genes the genes to set for the chromosome
Exceptions
InvalidConfigurationException in case constraint checker is provided
Author
Klaus Meffert
Since
3.2 (previously in class Chromosome)
Implements org.jgap.IChromosome.
Definition at line 267 of file BaseChromosome.java.
References org.jgap.BaseChromosome.m_genes.
Referenced by org.jgap.BaseChromosome.setValueFromPersistentRepresentation().
void org.jgap.BaseChromosome.setUniqueIDTemplate (String a_templateID, int a_index) [inline]
A template is a chromosome that is the logical predecessor of the current chromosome. A template can occur in mutation or crossing over. In the latter case can be at least two template chromosomes. This is why in this setter method the parameter a_index exists.
Parameters
a_templateID the unique ID of the template
a_index the index of the template, e.g. in crossing over for the second candidate chromosome this is 2
Author
Klaus Meffert
Since
3.5
Implements org.jgap.IUniqueKey.
Definition at line 129 of file BaseChromosome.java.
void org.jgap.BaseChromosome.setValueFromPersistentRepresentation (String a_representation) throws UnsupportedRepresentationException [inline]
Counterpart of getPersistentRepresentation.
Parameters
a_representation the string representation retrieved from a prior call to the getPersistentRepresentation() method
Exceptions
UnsupportedRepresentationException
Author
Klaus Meffert
Since
3.2
Todo
Todo we can do this faster!
Todo
Todo we can do this faster!
Implements org.jgap.IPersistentRepresentation.
Definition at line 400 of file BaseChromosome.java.
References org.jgap.BaseChromosome.createGene(), org.jgap.BaseChromosome.decode(), org.jgap.BaseChromosome.GENE_DELIMITER, org.jgap.IChromosome.setFitnessValue(), org.jgap.BaseChromosome.setGene(), org.jgap.BaseChromosome.setGenes(), and org.jgap.BaseChromosome.split().
Referenced by org.jgap.Chromosome.Chromosome().
int org.jgap.BaseChromosome.size () [inline]
Returns the size of this Chromosome (the number of genes it contains). A Chromosome's size is constant and will not change, until setGenes(...) is used.
Returns
number of genes contained within this Chromosome instance
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Implements org.jgap.IChromosome.
Definition at line 302 of file BaseChromosome.java.
References org.jgap.BaseChromosome.m_genes.
Referenced by org.jgap.Chromosome.cleanup(), org.jgap.Chromosome.clone(), org.jgap.Chromosome.compareTo(), org.jgap.BaseChromosome.getGenesPersistentRepresentation(), org.jgap.BaseChromosome.getPersistentRepresentation(), org.jgap.Chromosome.hashCode(), org.jgap.Chromosome.initFromGene(), org.jgap.ChromosomeTest.testClone_6(), org.jgap.ChromosomeTest.testConstruct_10(), org.jgap.ChromosomeTest.testConstruct_3(), org.jgap.ChromosomeTest.testPersistentRepresentation_2(), org.jgap.ChromosomeTest.testPersistentRepresentation_5(), org.jgap.ChromosomeTest.testSize_0(), org.jgap.ChromosomeTest.testSize_1(), org.jgap.ChromosomeTest.testToString_0(), org.jgap.ChromosomeTest.testToString_2(), and org.jgap.Chromosome.toString().
static final List org.jgap.BaseChromosome.split (String a_string) throws UnsupportedRepresentationException [inline], [static], [protected]
Splits the input a_string into individual gene representations.
Taken and adapted from CompositeGene.
Parameters
a_string the string to split
Returns
the elements of the returned array are the persistent representation strings of the chromosome's components
Exceptions
UnsupportedRepresentationException
Author
Klaus Meffert
Since
3.2
Definition at line 479 of file BaseChromosome.java.
References org.jgap.BaseChromosome.CHROM_DELIMITER, org.jgap.BaseChromosome.GENE_DELIMITER_CLOSING, and org.jgap.BaseChromosome.GENE_DELIMITER_HEADING.
Referenced by org.jgap.BaseChromosome.setValueFromPersistentRepresentation().
Member Data Documentation
final String org.jgap.BaseChromosome.CHROM_DELIMITER = `#` [static]
Separates chromosome-related information.
Definition at line 51 of file BaseChromosome.java.
Referenced by org.jgap.BaseChromosome.getPersistentRepresentation(), org.jgap.BaseChromosome.split(), org.jgap.ChromosomeTest.testPersistentRepresentation_4(), org.jgap.PopulationTest.testPersistentRepresentation_5(), and org.jgap.PopulationTest.testPersistentRepresentation_6().
final String org.jgap.BaseChromosome.CVS_REVISION = `$Revision: 1.15 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file BaseChromosome.java.
final String org.jgap.BaseChromosome.GENE_DELIMITER = `#` [static]
This field separates gene class name from the gene persistent representation string. '*' does not work properly with URLEncoder!
Definition at line 34 of file BaseChromosome.java.
Referenced by org.jgap.BaseChromosome.getGenesPersistentRepresentation(), org.jgap.BaseChromosome.setValueFromPersistentRepresentation(), org.jgap.ChromosomeTest.testPersistentRepresentation_5(), and org.jgap.ChromosomeTest.testPersistentRepresentation_6().
final String org.jgap.BaseChromosome.GENE_DELIMITER_CLOSING = `>` [static]
Represents the closing delimiter that is used to separate genes in the persistent representation of Chromosome instances.
Definition at line 46 of file BaseChromosome.java.
Referenced by org.jgap.BaseChromosome.getGenesPersistentRepresentation(), and org.jgap.BaseChromosome.split().
final String org.jgap.BaseChromosome.GENE_DELIMITER_HEADING = `<` [static]
Represents the heading delimiter that is used to separate genes in the persistent representation of Chromosome instances.
Definition at line 40 of file BaseChromosome.java.
Referenced by org.jgap.BaseChromosome.getGenesPersistentRepresentation(), and org.jgap.BaseChromosome.split().
int org.jgap.BaseChromosome.m_age [private]
Definition at line 63 of file BaseChromosome.java.
Referenced by org.jgap.BaseChromosome.getAge(), org.jgap.BaseChromosome.increaseAge(), org.jgap.BaseChromosome.resetAge(), and org.jgap.BaseChromosome.setAge().
Configuration org.jgap.BaseChromosome.m_configuration [private]
The configuration object to use
Definition at line 56 of file BaseChromosome.java.
Referenced by org.jgap.BaseChromosome.BaseChromosome(), and org.jgap.BaseChromosome.getConfiguration().
Gene [] org.jgap.BaseChromosome.m_genes [private]
The array of Genes contained in this Chromosome.
Definition at line 61 of file BaseChromosome.java.
Referenced by org.jgap.BaseChromosome.getGene(), org.jgap.BaseChromosome.getGenes(), org.jgap.BaseChromosome.setGene(), org.jgap.BaseChromosome.setGenes(), and org.jgap.BaseChromosome.size().
int org.jgap.BaseChromosome.m_operatedOn [private]
Definition at line 65 of file BaseChromosome.java.
Referenced by org.jgap.BaseChromosome.increaseOperatedOn(), org.jgap.BaseChromosome.operatedOn(), and org.jgap.BaseChromosome.resetOperatedOn().
String org.jgap.BaseChromosome.m_uniqueID [private]
Unique ID of the chromosome that allows to distinct it from other chromosomes. In the best case, this ID is unique worldwide.
Definition at line 71 of file BaseChromosome.java.
Referenced by org.jgap.BaseChromosome.BaseChromosome(), and org.jgap.BaseChromosome.getUniqueID().
Map<Integer,String> org.jgap.BaseChromosome.m_uniqueIDTemplates [private]
In case mutation, crossing over etc. happened, this sequence gives evidence about the parent(s) of the current chromosome.
Definition at line 77 of file BaseChromosome.java.
Referenced by org.jgap.BaseChromosome.BaseChromosome().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/BaseChromosome.java