examples.gp.anttrail.Move Class Reference
Public Member Functions
Move (final GPConfiguration a_conf) throws InvalidConfigurationException
Move (final GPConfiguration a_conf, int a_moves) throws InvalidConfigurationException
void execute_void (ProgramChromosome a_chrom, int a_n, Object[] a_args)
String toString ()
Private Attributes
int m_moves
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
Move the ant. Allows to specify how many times in a row a move will be executed. The classic ant problem uses 1 as parameter value.
Author
Klaus Meffert
Since
3.01
Definition at line 22 of file Move.java.
Constructor & Destructor Documentation
examples.gp.anttrail.Move.Move (final GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Standard constructor for classic ant problem.
Parameters
a_conf the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.01
Definition at line 38 of file Move.java.
examples.gp.anttrail.Move.Move (final GPConfiguration a_conf, int a_moves) throws InvalidConfigurationException [inline]
Allows to move more than one time in a row.
Parameters
a_conf the configuration to use
a_moves number of moves to execute in a row
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.01
Definition at line 54 of file Move.java.
References examples.gp.anttrail.Move.m_moves.
Member Function Documentation
void examples.gp.anttrail.Move.execute_void (ProgramChromosome a_chrom, int a_n, Object[] a_args) [inline]
Definition at line 60 of file Move.java.
References examples.gp.anttrail.AntMap.getHeight(), examples.gp.anttrail.AntCommand.getMap(), examples.gp.anttrail.AntMap.getWidth(), and examples.gp.anttrail.Move.m_moves.
String examples.gp.anttrail.Move.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 102 of file Move.java.
References examples.gp.anttrail.Move.m_moves.
Member Data Documentation
final String examples.gp.anttrail.Move.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file Move.java.
int examples.gp.anttrail.Move.m_moves [private]
Definition at line 27 of file Move.java.
Referenced by examples.gp.anttrail.Move.execute_void(), examples.gp.anttrail.Move.Move(), and examples.gp.anttrail.Move.toString().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/anttrail/Move.java