org.jgap.DefaultFitnessEvaluator Class Reference
Public Member Functions
boolean isFitter (final double a_fitness_value1, final double a_fitness_value2)
boolean isFitter (IChromosome a_chrom1, IChromosome a_chrom2)
Object clone ()
int compareTo (Object a_other)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.13 $`
Additional Inherited Members
Detailed Description
A default implementation of a fitness evaluator. This implementation is straight forward: a higher fitness value is seen as fitter.
Author
Klaus Meffert
Since
1.1
Definition at line 21 of file DefaultFitnessEvaluator.java.
Member Function Documentation
Object org.jgap.DefaultFitnessEvaluator.clone () [inline]
Returns
deep clone of this instance
Author
Klaus Meffert
Since
3.2
Implements org.jgap.util.ICloneable.
Definition at line 51 of file DefaultFitnessEvaluator.java.
int org.jgap.DefaultFitnessEvaluator.compareTo (Object a_other) [inline]
Parameters
a_other sic
Returns
as always
Author
Klaus Meffert
Since
3.2
Definition at line 62 of file DefaultFitnessEvaluator.java.
boolean org.jgap.DefaultFitnessEvaluator.isFitter (final double a_fitness_value1, final double a_fitness_value2) [inline]
Compares the first given fitness value with the second and returns true if the first one is greater than the second one. Otherwise returns false
Parameters
a_fitness_value1 first fitness value
a_fitness_value2 second fitness value
Returns
true: first fitness value greater than second
Author
Klaus Meffert
Since
2.0 (until 1.1: input types int)
Definition at line 36 of file DefaultFitnessEvaluator.java.
Referenced by org.jgap.DefaultFitnessEvaluator.isFitter().
boolean org.jgap.DefaultFitnessEvaluator.isFitter (IChromosome a_chrom1, IChromosome a_chrom2) [inline]
Implements org.jgap.FitnessEvaluator.
Definition at line 41 of file DefaultFitnessEvaluator.java.
References org.jgap.IChromosome.getFitnessValue(), and org.jgap.DefaultFitnessEvaluator.isFitter().
Member Data Documentation
final String org.jgap.DefaultFitnessEvaluator.CVS_REVISION = `$Revision: 1.13 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file DefaultFitnessEvaluator.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/DefaultFitnessEvaluator.java