org.jgap.gp.function.And Class Reference
Public Member Functions
And (final GPConfiguration a_conf) throws InvalidConfigurationException
And (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException
CommandGene applyMutation (int index, double a_percentage) throws InvalidConfigurationException
Object clone ()
String toString ()
String getName ()
boolean execute_boolean (ProgramChromosome c, int n, Object[] args)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.8 $`
Additional Inherited Members
Detailed Description
The boolean and operation.
Author
Klaus Meffert
Since
3.0
Definition at line 23 of file And.java.
Constructor & Destructor Documentation
org.jgap.gp.function.And.And (final GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Definition at line 28 of file And.java.
References org.jgap.gp.CommandGene.BooleanClass.
Referenced by org.jgap.gp.function.And.clone().
org.jgap.gp.function.And.And (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 33 of file And.java.
Member Function Documentation
CommandGene org.jgap.gp.function.And.applyMutation (int a_index, double a_percentage) throws InvalidConfigurationException [inline]
Mutates a CommandGene.
Parameters
a_index references the part of a multipart object, normally not relevant
a_percentage the mutation rate (0.0 to 1.0)
Returns
the mutant
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.IMutateable.
Definition at line 38 of file And.java.
References org.jgap.gp.CommandGene.getGPConfiguration().
Object org.jgap.gp.function.And.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 58 of file And.java.
References org.jgap.gp.function.And.And(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.CommandGene.getReturnType().
boolean org.jgap.gp.function.And.execute_boolean (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 81 of file And.java.
String org.jgap.gp.function.And.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 77 of file And.java.
String org.jgap.gp.function.And.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 67 of file And.java.
Member Data Documentation
final String org.jgap.gp.function.And.CVS_REVISION = `$Revision: 1.8 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file And.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/And.java