org.jgap.impl.IntegerGeneTest Class Reference
Classes
class GeneConstraintChecker
class IntegerGene2
Public Member Functions
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testToString_0 () throws Exception
void testToString_1 () throws Exception
void testGetAllele_0 () throws Exception
void testGetAllele_1 () throws Exception
void testGetAllele_2 () throws Exception
void testEquals_0 () throws Exception
void testEquals_1 () throws Exception
void testEquals_2 () throws Exception
void testEquals_3 () throws Exception
void testEquals_4 () throws Exception
void testEquals_5 () throws Exception
void testEquals_6 () throws Exception
void testEquals_7 () throws Exception
void testEquals_8 () throws Exception
void testEquals_9 () throws Exception
void testEquals_9_2 () throws Exception
void testEquals_10 () throws Exception
void testEquals_9_3 () throws Exception
void testIntValue_0 () throws Exception
void testIntValue_1 () throws Exception
void testSetAllele_0 () throws Exception
void testSetAllele_1 () throws Exception
void testSetAllele_2 () throws Exception
void testSetAllele_3 () throws Exception
void testNewGene_0 () throws Exception
void testCleanup () throws Exception
void testPersistentRepresentation_0 () throws Exception
void testPersistentRepresentation_1 () throws Exception
void testPersistentRepresentation_2 () throws Exception
void testPersistentRepresentation_3 () throws Exception
void testPersistentRepresentation_4 () throws Exception
void testPersistentRepresentation_5 () throws Exception
void testPersistentRepresentation_6 () throws Exception
void testCompareToNative_0 () throws Exception
void testCompareToNative_1 () throws Exception
void testCompareToNative_2 () throws Exception
void testCompareToNative_3 () throws Exception
void testCompareToNative_4 () throws Exception
void testCompareTo_0 () throws Exception
void testCompareTo_1 () throws Exception
void testCompareTo_2 () throws Exception
void testCompareTo_3 () throws Exception
void testCompareTo_4 () throws Exception
void testApplyMutation_0 () throws Exception
void testApplyMutation_1 () throws Exception
void testApplyMutation_2 () throws Exception
void testApplyMutation_3 () throws Exception
void testApplyMutation_4 () throws Exception
void testApplyMutation_5 () throws Exception
void testApplyMutation_6 () throws Exception
void testApplyMutation_7 () throws Exception
void testApplyMutation_8 () throws Exception
void testSetToRandomValue_0 () throws Exception
void testSetToRandomValue_1 () throws Exception
void testSetToRandomValue_2 () throws Exception
void testSetToRandomValue_3 () throws Exception
void testSetToRandomValue_4 () throws Exception
void testSetToRandomValue_5 () throws Exception
void testSetEnergy_0 () throws Exception
void testSetEnergy_1 () throws Exception
void testGetBounds_0 () throws Exception
void testIntegerGeneSupportsFullIntegerRange () throws Exception
void testMapValueToWithinBoundsSupportsFullIntegerRange () throws Exception
void testApplyMutationSupportsFullIntegerRange () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.47 $`
Additional Inherited Members
Detailed Description
Tests the IntegerGene class.
Author
Klaus Meffert
Since
1.1
Definition at line 22 of file IntegerGeneTest.java.
Member Function Documentation
static Test org.jgap.impl.IntegerGeneTest.suite () [inline], [static]
Definition at line 27 of file IntegerGeneTest.java.
void org.jgap.impl.IntegerGeneTest.testApplyMutation_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 663 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.IntegerGene.intValue().
void org.jgap.impl.IntegerGeneTest.testApplyMutation_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 677 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testApplyMutation_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 692 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testApplyMutation_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 707 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testApplyMutation_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 724 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testApplyMutation_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 741 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testApplyMutation_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 758 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testApplyMutation_7 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 772 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testApplyMutation_8 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 786 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testApplyMutationSupportsFullIntegerRange () throws Exception [inline]
Exceptions
Exception
Author
David Kemp
Since
3.4.4
Definition at line 1004 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.IntegerGene.intValue().
void org.jgap.impl.IntegerGeneTest.testCleanup () throws Exception [inline]
Definition at line 352 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testCompareTo_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 582 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testCompareTo_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 603 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testCompareTo_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 618 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testCompareTo_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 633 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testCompareTo_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 649 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testCompareToNative_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 500 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.IntegerGeneTest.testCompareToNative_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 516 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.IntegerGeneTest.testCompareToNative_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 532 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.IntegerGeneTest.testCompareToNative_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 548 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.IntegerGeneTest.testCompareToNative_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 565 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.IntegerGeneTest.testConstruct_0 () throws Exception [inline]
Definition at line 32 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testConstruct_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.1
Definition at line 45 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testEquals_0 () throws Exception [inline]
Definition at line 87 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testEquals_1 () throws Exception [inline]
Definition at line 95 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testEquals_10 () throws Exception [inline]
Definition at line 232 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testEquals_2 () throws Exception [inline]
Definition at line 101 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testEquals_3 () throws Exception [inline]
Definition at line 107 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testEquals_4 () throws Exception [inline]
Definition at line 113 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testEquals_5 () throws Exception [inline]
Definition at line 121 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testEquals_6 () throws Exception [inline]
Uses subclass of IntegerGene.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 136 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testEquals_7 () throws Exception [inline]
Uses subclass of IntegerGene.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 153 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testEquals_8 () throws Exception [inline]
Compare with application data set and option for comparation activated.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 170 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.equals().
void org.jgap.impl.IntegerGeneTest.testEquals_9 () throws Exception [inline]
Compare with application data set and option for comparation activated.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 191 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.equals().
void org.jgap.impl.IntegerGeneTest.testEquals_9_2 () throws Exception [inline]
Compare with application data set and option for comparation activated.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 212 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.equals().
void org.jgap.impl.IntegerGeneTest.testEquals_9_3 () throws Exception [inline]
Compare with application data set but option for comparation deactivated.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 251 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.equals().
void org.jgap.impl.IntegerGeneTest.testGetAllele_0 () throws Exception [inline]
Definition at line 66 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.IntegerGeneTest.testGetAllele_1 () throws Exception [inline]
Definition at line 73 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.IntegerGeneTest.testGetAllele_2 () throws Exception [inline]
Definition at line 80 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.IntegerGeneTest.testGetBounds_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 955 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.IntegerGene.getLowerBounds(), and org.jgap.impl.IntegerGene.getUpperBounds().
void org.jgap.impl.IntegerGeneTest.testIntegerGeneSupportsFullIntegerRange () throws Exception [inline]
Exceptions
Exception
Author
David Kemp
Since
3.4.4
Definition at line 968 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.IntegerGeneTest.testIntValue_0 () throws Exception [inline]
Definition at line 265 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.IntegerGene.intValue().
void org.jgap.impl.IntegerGeneTest.testIntValue_1 () throws Exception [inline]
Definition at line 272 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.IntegerGene.intValue().
void org.jgap.impl.IntegerGeneTest.testMapValueToWithinBoundsSupportsFullIntegerRange () throws Exception [inline]
Exceptions
Exception
Author
David Kemp
Since
3.4.4
Definition at line 985 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.getAllele().
void org.jgap.impl.IntegerGeneTest.testNewGene_0 () throws Exception [inline]
Definition at line 336 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.BaseGene.newGene().
void org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_0 () throws Exception [inline]
Definition at line 361 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_1 () throws Exception [inline]
Should be possible without exception.
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 379 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 392 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseGene.getAllele(), org.jgap.impl.IntegerGene.getLowerBounds(), and org.jgap.impl.IntegerGene.getUpperBounds().
void org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 414 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.BaseGene.getAllele(), org.jgap.impl.IntegerGene.getLowerBounds(), and org.jgap.impl.IntegerGene.getUpperBounds().
void org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 436 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_5 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 460 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_6 () throws Exception [inline]
Constructed IntegerGene without user initialization.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 485 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.IntegerGene.getPersistentRepresentation(), and org.jgap.Gene.PERSISTENT_FIELD_DELIMITER.
void org.jgap.impl.IntegerGeneTest.testSetAllele_0 () throws Exception [inline]
Set Allele to null, no exception should occur.
Exceptions
Exception
Definition at line 289 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testSetAllele_1 () throws Exception [inline]
Definition at line 295 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.IntegerGeneTest.testSetAllele_2 () throws Exception [inline]
Set Allele to value out of bounds with bounds' dimension of 1.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 314 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.IntegerGene.intValue().
void org.jgap.impl.IntegerGeneTest.testSetAllele_3 () throws Exception [inline]
Set Allele to value out of bounds with bounds' dimension of 1.
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 329 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.IntegerGene.intValue().
void org.jgap.impl.IntegerGeneTest.testSetEnergy_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 898 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getEnergy().
void org.jgap.impl.IntegerGeneTest.testSetEnergy_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 910 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.BaseGene.getEnergy().
void org.jgap.impl.IntegerGeneTest.testSetToRandomValue_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 803 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.IntegerGeneTest.testSetToRandomValue_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 817 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.IntegerGeneTest.testSetToRandomValue_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 831 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.IntegerGeneTest.testSetToRandomValue_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 846 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.IntegerGene.intValue().
void org.jgap.impl.IntegerGeneTest.testSetToRandomValue_4 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 863 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.IntegerGene.intValue().
void org.jgap.impl.IntegerGeneTest.testSetToRandomValue_5 () throws Exception [inline]
Exposing bug #1357474.
Exceptions
Exception
Author
Klaus Meffert
Since
2.5
Definition at line 881 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.getAllele().
void org.jgap.impl.IntegerGeneTest.testToString_0 () throws Exception [inline]
Definition at line 52 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.toString().
void org.jgap.impl.IntegerGeneTest.testToString_1 () throws Exception [inline]
Definition at line 59 of file IntegerGeneTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Gene.toString().
Member Data Documentation
final String org.jgap.impl.IntegerGeneTest.CVS_REVISION = `$Revision: 1.47 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file IntegerGeneTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/IntegerGeneTest.java