examples.gp.tictactoe.IfIsFree Class Reference
Public Member Functions
IfIsFree (final GPConfiguration a_conf, Board a_board, Class a_type) throws InvalidConfigurationException
IfIsFree (final GPConfiguration a_conf, Board a_board, Class a_type, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException
String toString ()
String getName ()
void execute_void (ProgramChromosome c, int n, Object[] args)
Class getChildType (IGPProgram a_ind, int a_chromNum)
Object clone ()
Private Attributes
Class m_type
Board m_board
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
The if-then construct. If-Condition is: if specific color, then execute X else do nothing.
Author
Klaus Meffert
Since
3.2
Definition at line 24 of file IfIsFree.java.
Constructor & Destructor Documentation
examples.gp.tictactoe.IfIsFree.IfIsFree (final GPConfiguration a_conf, Board a_board, Class a_type) throws InvalidConfigurationException [inline]
Definition at line 33 of file IfIsFree.java.
Referenced by examples.gp.tictactoe.IfIsFree.clone().
examples.gp.tictactoe.IfIsFree.IfIsFree (final GPConfiguration a_conf, Board a_board, Class a_type, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException [inline]
Definition at line 38 of file IfIsFree.java.
References examples.gp.tictactoe.IfIsFree.m_board, examples.gp.tictactoe.IfIsFree.m_type, and org.jgap.gp.CommandGene.VoidClass.
Member Function Documentation
Object examples.gp.tictactoe.IfIsFree.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 107 of file IfIsFree.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getSubChildTypes(), org.jgap.gp.CommandGene.getSubReturnType(), examples.gp.tictactoe.IfIsFree.IfIsFree(), examples.gp.tictactoe.IfIsFree.m_board, and examples.gp.tictactoe.IfIsFree.m_type.
void examples.gp.tictactoe.IfIsFree.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 60 of file IfIsFree.java.
References org.jgap.gp.CommandGene.check(), examples.gp.tictactoe.Board.HEIGHT, org.jgap.gp.CommandGene.IntegerClass, examples.gp.tictactoe.IfIsFree.m_type, and examples.gp.tictactoe.Board.WIDTH.
Class examples.gp.tictactoe.IfIsFree.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Determines which type a specific child of this command has.
Parameters
a_ind ignored here
a_chromNum index of child
Returns
type of the a_chromNum'th child
Author
Klaus Meffert
Since
3.2
Definition at line 92 of file IfIsFree.java.
References examples.gp.tictactoe.IfIsFree.m_type, and org.jgap.gp.CommandGene.VoidClass.
String examples.gp.tictactoe.IfIsFree.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 56 of file IfIsFree.java.
String examples.gp.tictactoe.IfIsFree.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 46 of file IfIsFree.java.
Member Data Documentation
final String examples.gp.tictactoe.IfIsFree.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file IfIsFree.java.
Board examples.gp.tictactoe.IfIsFree.m_board [private]
Definition at line 31 of file IfIsFree.java.
Referenced by examples.gp.tictactoe.IfIsFree.clone(), and examples.gp.tictactoe.IfIsFree.IfIsFree().
Class examples.gp.tictactoe.IfIsFree.m_type [private]
Definition at line 29 of file IfIsFree.java.
Referenced by examples.gp.tictactoe.IfIsFree.clone(), examples.gp.tictactoe.IfIsFree.execute_void(), examples.gp.tictactoe.IfIsFree.getChildType(), and examples.gp.tictactoe.IfIsFree.IfIsFree().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/tictactoe/IfIsFree.java