examples.gp.tictactoe.IfColor Class Reference
Public Member Functions
IfColor (final GPConfiguration a_conf, Class a_type, int a_color) throws InvalidConfigurationException
IfColor (final GPConfiguration a_conf, Class a_type, int a_color, int a_subChildType1, int a_subChildType2) throws InvalidConfigurationException
IfColor (final GPConfiguration a_conf, Class a_type, int a_color, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException
String toString ()
String getName ()
void execute_void (ProgramChromosome c, int n, Object[] args)
int execute_int (ProgramChromosome c, int n, Object[] args)
Class getChildType (IGPProgram a_ind, int a_chromNum)
Object clone ()
Private Attributes
Class m_type
int m_color
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
The if-then construct. If-Condition is: if specific color, then execute X else do nothing.
Author
Klaus Meffert
Since
3.2
Definition at line 24 of file IfColor.java.
Constructor & Destructor Documentation
examples.gp.tictactoe.IfColor.IfColor (final GPConfiguration a_conf, Class a_type, int a_color) throws InvalidConfigurationException [inline]
Definition at line 33 of file IfColor.java.
Referenced by examples.gp.tictactoe.IfColor.clone().
examples.gp.tictactoe.IfColor.IfColor (final GPConfiguration a_conf, Class a_type, int a_color, int a_subChildType1, int a_subChildType2) throws InvalidConfigurationException [inline]
Allows setting the sub child type.
Parameters
a_conf GPConfiguration
a_type Class
a_color int
a_subChildType1 int
a_subChildType2 int
Exceptions
InvalidConfigurationException
Since
3.6
Definition at line 51 of file IfColor.java.
examples.gp.tictactoe.IfColor.IfColor (final GPConfiguration a_conf, Class a_type, int a_color, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException [inline]
Definition at line 57 of file IfColor.java.
References examples.gp.tictactoe.IfColor.m_color, examples.gp.tictactoe.IfColor.m_type, and org.jgap.gp.CommandGene.VoidClass.
Member Function Documentation
Object examples.gp.tictactoe.IfColor.clone () [inline]
Returns
clone of the current object instance
Implements org.jgap.util.ICloneable.
Definition at line 122 of file IfColor.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getSubChildTypes(), org.jgap.gp.CommandGene.getSubReturnType(), examples.gp.tictactoe.IfColor.IfColor(), examples.gp.tictactoe.IfColor.m_color, and examples.gp.tictactoe.IfColor.m_type.
int examples.gp.tictactoe.IfColor.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 96 of file IfColor.java.
References org.jgap.gp.CommandGene.check(), and examples.gp.tictactoe.IfColor.m_color.
void examples.gp.tictactoe.IfColor.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 79 of file IfColor.java.
References org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.CommandGene.LongClass, examples.gp.tictactoe.IfColor.m_color, and examples.gp.tictactoe.IfColor.m_type.
Class examples.gp.tictactoe.IfColor.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Determines which type a specific child of this command has.
Parameters
a_ind ignored here
a_chromNum index of child
Returns
type of the a_chromNum'th child
Author
Klaus Meffert
Since
3.2
Definition at line 115 of file IfColor.java.
References examples.gp.tictactoe.IfColor.m_type, and org.jgap.gp.CommandGene.VoidClass.
String examples.gp.tictactoe.IfColor.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 75 of file IfColor.java.
String examples.gp.tictactoe.IfColor.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 65 of file IfColor.java.
References examples.gp.tictactoe.IfColor.m_color.
Member Data Documentation
final String examples.gp.tictactoe.IfColor.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file IfColor.java.
int examples.gp.tictactoe.IfColor.m_color [private]
Definition at line 31 of file IfColor.java.
Referenced by examples.gp.tictactoe.IfColor.clone(), examples.gp.tictactoe.IfColor.execute_int(), examples.gp.tictactoe.IfColor.execute_void(), examples.gp.tictactoe.IfColor.IfColor(), and examples.gp.tictactoe.IfColor.toString().
Class examples.gp.tictactoe.IfColor.m_type [private]
Definition at line 29 of file IfColor.java.
Referenced by examples.gp.tictactoe.IfColor.clone(), examples.gp.tictactoe.IfColor.execute_void(), examples.gp.tictactoe.IfColor.getChildType(), and examples.gp.tictactoe.IfColor.IfColor().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/tictactoe/IfColor.java