org.jgap.DeltaFitnessEvaluatorTest Class Reference
Public Member Functions
void testIsFitter_0 ()
void testIsFitter_1 ()
void testIsFitter_2 ()
void testIsFitter_3 ()
void testIsFitter_4 ()
void testIsFitter_5 ()
void testIsFitter_6 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.10 $`
Additional Inherited Members
Detailed Description
Test cases for class DeltaFitnessEvaluator.
Author
Klaus Meffert
Since
2.2
Definition at line 20 of file DeltaFitnessEvaluatorTest.java.
Member Function Documentation
static Test org.jgap.DeltaFitnessEvaluatorTest.suite () [inline], [static]
Definition at line 25 of file DeltaFitnessEvaluatorTest.java.
void org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_0 () [inline]
Definition at line 30 of file DeltaFitnessEvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.FitnessEvaluator.isFitter().
void org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_1 () [inline]
Definition at line 36 of file DeltaFitnessEvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.FitnessEvaluator.isFitter().
void org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_2 () [inline]
Definition at line 42 of file DeltaFitnessEvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.FitnessEvaluator.isFitter().
void org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_3 () [inline]
Definition at line 48 of file DeltaFitnessEvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.FitnessEvaluator.isFitter().
void org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_4 () [inline]
Definition at line 53 of file DeltaFitnessEvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.FitnessEvaluator.isFitter().
void org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_5 () [inline]
Definition at line 58 of file DeltaFitnessEvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.FitnessEvaluator.isFitter().
void org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_6 () throws Exception [inline]
Definition at line 64 of file DeltaFitnessEvaluatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.FitnessEvaluator.isFitter().
Member Data Documentation
final String org.jgap.DeltaFitnessEvaluatorTest.CVS_REVISION = `$Revision: 1.10 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 23 of file DeltaFitnessEvaluatorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/DeltaFitnessEvaluatorTest.java