examples.math.ga.MathGene.GetValueOperandVisitor Class Reference
Public Member Functions
ValueOperand find (MathOperator theOp)
void visit (ValueOperand theOp)
void visit (AddOperator theOp)
void visit (MinusOperator theOp)
void visit (DivideOperator theOp)
void visit (MultiplyOperator theOp)
Private Member Functions
void mathOpVisit (MathOperator theOp)
Private Attributes
ValueOperand mOp
Additional Inherited Members
Detailed Description
Definition at line 198 of file MathGene.java.
Member Function Documentation
ValueOperand examples.math.ga.MathGene.GetValueOperandVisitor.find (MathOperator theOp) [inline]
Definition at line 202 of file MathGene.java.
References examples.math.ga.MathGene.GetValueOperandVisitor.mOp.
void examples.math.ga.MathGene.GetValueOperandVisitor.mathOpVisit (MathOperator theOp) [inline], [private]
Definition at line 213 of file MathGene.java.
References examples.math.ga.MathGene.GetValueOperandVisitor.mOp.
Referenced by examples.math.ga.MathGene.GetValueOperandVisitor.visit().
void examples.math.ga.MathGene.GetValueOperandVisitor.visit (ValueOperand theOp) [inline]
Implements examples.math.MathVisitor.
Definition at line 207 of file MathGene.java.
References examples.math.ga.MathGene.GetValueOperandVisitor.mOp.
void examples.math.ga.MathGene.GetValueOperandVisitor.visit (AddOperator theOp) [inline]
Implements examples.math.MathVisitor.
Definition at line 222 of file MathGene.java.
References examples.math.ga.MathGene.GetValueOperandVisitor.mathOpVisit().
void examples.math.ga.MathGene.GetValueOperandVisitor.visit (MinusOperator theOp) [inline]
Implements examples.math.MathVisitor.
Definition at line 226 of file MathGene.java.
References examples.math.ga.MathGene.GetValueOperandVisitor.mathOpVisit().
void examples.math.ga.MathGene.GetValueOperandVisitor.visit (DivideOperator theOp) [inline]
Implements examples.math.MathVisitor.
Definition at line 230 of file MathGene.java.
References examples.math.ga.MathGene.GetValueOperandVisitor.mathOpVisit().
void examples.math.ga.MathGene.GetValueOperandVisitor.visit (MultiplyOperator theOp) [inline]
Implements examples.math.MathVisitor.
Definition at line 234 of file MathGene.java.
References examples.math.ga.MathGene.GetValueOperandVisitor.mathOpVisit().
Member Data Documentation
ValueOperand examples.math.ga.MathGene.GetValueOperandVisitor.mOp [private]
Definition at line 200 of file MathGene.java.
Referenced by examples.math.ga.MathGene.GetValueOperandVisitor.find(), examples.math.ga.MathGene.GetValueOperandVisitor.mathOpVisit(), and examples.math.ga.MathGene.GetValueOperandVisitor.visit().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/math/ga/MathGene.java