org.jgap.impl.TournamentSelectorTest Class Reference
Public Member Functions
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testConstruct_2 () throws Exception
void testConstruct_3 () throws Exception
void testConstruct_4 () throws Exception
void testAdd_0 () throws Exception
void testEmpty_0 () throws Exception
void testEmpty_1 () throws Exception
void testEmpty_2 () throws Exception
void testSelect_0 () throws Exception
void testSelect_1 () throws Exception
void testSelect_2 () throws Exception
void testSelect_3 () throws Exception
void testSelect_4 () throws Exception
void testSelect_5 () throws Exception
void testSelect_6 () throws Exception
void testReturnsUniqueChromosomes_0 () throws Exception
void testSetTournametSize_0 () throws Exception
void testSetProbability_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.16 $`
Additional Inherited Members
Detailed Description
Tests the TournamentSelector class.
Author
Klaus Meffert
Since
2.0
Definition at line 24 of file TournamentSelectorTest.java.
Member Function Documentation
static Test org.jgap.impl.TournamentSelectorTest.suite () [inline], [static]
Definition at line 29 of file TournamentSelectorTest.java.
void org.jgap.impl.TournamentSelectorTest.testAdd_0 () throws Exception [inline]
Definition at line 125 of file TournamentSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.TournamentSelectorTest.testConstruct_0 () throws Exception [inline]
Valid construction
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 41 of file TournamentSelectorTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.TournamentSelectorTest.testConstruct_1 () throws Exception [inline]
Invalid construction.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 60 of file TournamentSelectorTest.java.
void org.jgap.impl.TournamentSelectorTest.testConstruct_2 () throws Exception [inline]
Invalid construction,
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 78 of file TournamentSelectorTest.java.
void org.jgap.impl.TournamentSelectorTest.testConstruct_3 () throws Exception [inline]
Invalid construction.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 96 of file TournamentSelectorTest.java.
void org.jgap.impl.TournamentSelectorTest.testConstruct_4 () throws Exception [inline]
Invalid construction.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 114 of file TournamentSelectorTest.java.
void org.jgap.impl.TournamentSelectorTest.testEmpty_0 () throws Exception [inline]
Definition at line 142 of file TournamentSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.TournamentSelectorTest.testEmpty_1 () throws Exception [inline]
Test if clear()-method does not affect original Population.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 161 of file TournamentSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.TournamentSelectorTest.testEmpty_2 () throws Exception [inline]
Test if clear()-method does not affect return value.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 183 of file TournamentSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.TournamentSelectorTest.testReturnsUniqueChromosomes_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 492 of file TournamentSelectorTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.impl.TournamentSelector.returnsUniqueChromosomes().
void org.jgap.impl.TournamentSelectorTest.testSelect_0 () throws Exception [inline]
Test if below functionality working without error.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 206 of file TournamentSelectorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.TournamentSelectorTest.testSelect_1 () throws Exception [inline]
Always select best chromosome for granted if prob is 1.0 and index for selected chromosomes in tournament is equal to index of best chromosome.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 230 of file TournamentSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.TournamentSelectorTest.testSelect_2 () throws Exception [inline]
Always select best chromosome for granted if prob is 1.0 and index for selected chromosomes in tournament is equal to index of best chromosome.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 283 of file TournamentSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.TournamentSelectorTest.testSelect_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 327 of file TournamentSelectorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.TournamentSelectorTest.testSelect_4 () throws Exception [inline]
Ensure that selected Chromosome's are not equal to added Chromosome's.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 365 of file TournamentSelectorTest.java.
References org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.privateAccessor.
void org.jgap.impl.TournamentSelectorTest.testSelect_5 () throws Exception [inline]
Never select best chromosome if prob is 0.0d. it is not allowed to select probability to 0.0d therefor we set it via reflection.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 400 of file TournamentSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.JGAPTestCase.setNestedField().
void org.jgap.impl.TournamentSelectorTest.testSelect_6 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 436 of file TournamentSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.TournamentSelectorTest.testSetProbability_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 527 of file TournamentSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, and org.jgap.impl.TournamentSelector.getProbability().
void org.jgap.impl.TournamentSelectorTest.testSetTournametSize_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 505 of file TournamentSelectorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.impl.TournamentSelector.getTournamentSize().
Member Data Documentation
final String org.jgap.impl.TournamentSelectorTest.CVS_REVISION = `$Revision: 1.16 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file TournamentSelectorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/TournamentSelectorTest.java