org.jgap.impl.TwoWayMutationOperator Class Reference
Public Member Functions
TwoWayMutationOperator () throws InvalidConfigurationException
TwoWayMutationOperator (final Configuration a_config) throws InvalidConfigurationException
TwoWayMutationOperator (final Configuration a_config, final IUniversalRateCalculator a_mutationRateCalculator) throws InvalidConfigurationException
TwoWayMutationOperator (final Configuration a_config, final int a_desiredMutationRate) throws InvalidConfigurationException
void operate (final Population a_population, final List a_candidateChromosomes)
IUniversalRateCalculator getMutationRateCalc ()
void setMutationRateCalc (final IUniversalRateCalculator a_mutationRateCalc)
boolean equals (final Object a_other)
int compareTo (Object a_other)
int getMutationRate ()
Private Member Functions
void mutateGene (final Gene a_gene, final RandomGenerator a_generator)
Private Attributes
int m_mutationRate
IUniversalRateCalculator m_mutationRateCalc
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.9 $`
Additional Inherited Members
Detailed Description
Considers two levels of mutation. At first, this mutation operator assumes all genes within a chromosome to having a different impact on the result when mutated. For that, a gene with fewer impact is selected for mutation more likely than one with bigger impact. After a gene has been selected for mutation, it is indeed mutated in a traditional way.
See class examples.dynamicMutation.DynamicMutationExample for usage, currently this class only works with that example!
Author
Klaus Meffert
Since
2.6
Definition at line 28 of file TwoWayMutationOperator.java.
Constructor & Destructor Documentation
org.jgap.impl.TwoWayMutationOperator.TwoWayMutationOperator () throws InvalidConfigurationException [inline]
Constructs a new instance of this MutationOperator without a specified mutation rate, which results in dynamic mutation being turned on. This means that the mutation rate will be automatically determined by this operator based upon the number of genes present in the chromosomes.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.6
Definition at line 61 of file TwoWayMutationOperator.java.
References org.jgap.Genotype.getStaticConfiguration().
Referenced by org.jgap.impl.TwoWayMutationOperator.compareTo().
org.jgap.impl.TwoWayMutationOperator.TwoWayMutationOperator (final Configuration a_config) throws InvalidConfigurationException [inline]
Constructs a new instance of this MutationOperator without a specified mutation rate, which results in dynamic mutation being turned on. This means that the mutation rate will be automatically determined by this operator based upon the number of genes present in the chromosomes.
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.1
Definition at line 79 of file TwoWayMutationOperator.java.
org.jgap.impl.TwoWayMutationOperator.TwoWayMutationOperator (final Configuration a_config, final IUniversalRateCalculator a_mutationRateCalculator) throws InvalidConfigurationException [inline]
Constructs a new instance of this MutationOperator with a specified mutation rate calculator, which results in dynamic mutation being turned on.
Parameters
a_config the configuration to use
a_mutationRateCalculator calculator for dynamic mutation rate computation
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.6
Definition at line 97 of file TwoWayMutationOperator.java.
References org.jgap.impl.TwoWayMutationOperator.setMutationRateCalc().
org.jgap.impl.TwoWayMutationOperator.TwoWayMutationOperator (final Configuration a_config, final int a_desiredMutationRate) throws InvalidConfigurationException [inline]
Constructs a new instance of this MutationOperator with the given mutation rate.
Parameters
a_config the configuration to use
a_desiredMutationRate desired rate of mutation, expressed as the denominator of the 1 / X fraction. For example, 1000 would result in 1/1000 genes being mutated on average. A mutation rate of zero disables mutation entirely
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.6
Definition at line 119 of file TwoWayMutationOperator.java.
References org.jgap.impl.TwoWayMutationOperator.m_mutationRate, and org.jgap.impl.TwoWayMutationOperator.setMutationRateCalc().
Member Function Documentation
int org.jgap.impl.TwoWayMutationOperator.compareTo (Object a_other) [inline]
Compares the given GeneticOperator to this GeneticOperator.
Parameters
a_other the instance against which to compare this instance
Returns
a negative number if this instance is `less than` the given instance, zero if they are equal to each other, and a positive number if this is `greater than` the given instance
Author
Klaus Meffert
Since
2.6
Definition at line 352 of file TwoWayMutationOperator.java.
References org.jgap.impl.TwoWayMutationOperator.m_mutationRate, org.jgap.impl.TwoWayMutationOperator.m_mutationRateCalc, and org.jgap.impl.TwoWayMutationOperator.TwoWayMutationOperator().
Referenced by org.jgap.impl.TwoWayMutationOperator.equals(), and org.jgap.impl.TwoWayMutationOperatorTest.testCompareTo_0().
boolean org.jgap.impl.TwoWayMutationOperator.equals (final Object a_other) [inline]
Compares this GeneticOperator against the specified object. The result is true if and the argument is an instance of this class and is equal wrt the data.
Parameters
a_other the object to compare against
Returns
true: if the objects are the same, false otherwise
Author
Klaus Meffert
Since
2.6
Definition at line 332 of file TwoWayMutationOperator.java.
References org.jgap.impl.TwoWayMutationOperator.compareTo().
int org.jgap.impl.TwoWayMutationOperator.getMutationRate () [inline]
Definition at line 382 of file TwoWayMutationOperator.java.
References org.jgap.impl.TwoWayMutationOperator.m_mutationRate.
Referenced by org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_0(), org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_2(), and org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_3().
IUniversalRateCalculator org.jgap.impl.TwoWayMutationOperator.getMutationRateCalc () [inline]
Returns
the MutationRateCalculator used
Author
Klaus Meffert
Since
1.1
Definition at line 301 of file TwoWayMutationOperator.java.
References org.jgap.impl.TwoWayMutationOperator.m_mutationRateCalc.
Referenced by org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_0(), org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_2(), and org.jgap.impl.TwoWayMutationOperatorTest.testConstruct_3().
void org.jgap.impl.TwoWayMutationOperator.mutateGene (final Gene a_gene, final RandomGenerator a_generator) [inline], [private]
Helper: mutate all atomic elements of a gene
Parameters
a_gene the gene to be mutated
a_generator the generator delivering amount of mutation
Author
Klaus Meffert
Since
2.6
Definition at line 279 of file TwoWayMutationOperator.java.
Referenced by org.jgap.impl.TwoWayMutationOperator.operate().
void org.jgap.impl.TwoWayMutationOperator.operate (final Population a_population, final List a_candidateChromosomes) [inline]
Parameters
a_population see interface
a_candidateChromosomes see interface
Author
Klaus Meffert
Since
2.6
Todo
Todo make this configurable, it is a first test, see example DynamicMutationExample
Todo
Todo move to base class, refactor
Implements org.jgap.GeneticOperator.
Definition at line 134 of file TwoWayMutationOperator.java.
References org.jgap.util.ICloneable.clone(), org.jgap.ICompositeGene.geneAt(), org.jgap.BaseGeneticOperator.getConfiguration(), org.jgap.BaseGeneticOperator.m_monitorActive, org.jgap.impl.TwoWayMutationOperator.m_mutationRate, org.jgap.impl.TwoWayMutationOperator.m_mutationRateCalc, org.jgap.impl.TwoWayMutationOperator.mutateGene(), and org.jgap.Population.size().
void org.jgap.impl.TwoWayMutationOperator.setMutationRateCalc (final IUniversalRateCalculator a_mutationRateCalc) [inline]
Sets the MutationRateCalculator to be used for determining the strength of mutation.
Parameters
a_mutationRateCalc MutationRateCalculator
Author
Klaus Meffert
Since
1.1
Definition at line 313 of file TwoWayMutationOperator.java.
References org.jgap.impl.TwoWayMutationOperator.m_mutationRate, and org.jgap.impl.TwoWayMutationOperator.m_mutationRateCalc.
Referenced by org.jgap.impl.TwoWayMutationOperator.TwoWayMutationOperator().
Member Data Documentation
final String org.jgap.impl.TwoWayMutationOperator.CVS_REVISION = `$Revision: 1.9 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 31 of file TwoWayMutationOperator.java.
int org.jgap.impl.TwoWayMutationOperator.m_mutationRate [private]
The current mutation rate used by this MutationOperator, expressed as the denominator in the 1 / X ratio. For example, X = 1000 would mean that, on average, 1 / 1000 genes would be mutated. A value of zero disables mutation entirely.
Definition at line 39 of file TwoWayMutationOperator.java.
Referenced by org.jgap.impl.TwoWayMutationOperator.compareTo(), org.jgap.impl.TwoWayMutationOperator.getMutationRate(), org.jgap.impl.TwoWayMutationOperator.operate(), org.jgap.impl.TwoWayMutationOperator.setMutationRateCalc(), and org.jgap.impl.TwoWayMutationOperator.TwoWayMutationOperator().
IUniversalRateCalculator org.jgap.impl.TwoWayMutationOperator.m_mutationRateCalc [private]
Calculator for dynamically determining the mutation rate. If set to null the value of m_mutationRate will be used. Replaces the previously used boolean m_dynamicMutationRate.
Definition at line 46 of file TwoWayMutationOperator.java.
Referenced by org.jgap.impl.TwoWayMutationOperator.compareTo(), org.jgap.impl.TwoWayMutationOperator.getMutationRateCalc(), org.jgap.impl.TwoWayMutationOperator.operate(), and org.jgap.impl.TwoWayMutationOperator.setMutationRateCalc().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/TwoWayMutationOperator.java