org.jgap.impl.CrossoverOperator Class Reference
Public Member Functions
CrossoverOperator () throws InvalidConfigurationException
CrossoverOperator (final Configuration a_configuration) throws InvalidConfigurationException
CrossoverOperator (final Configuration a_configuration, final IUniversalRateCalculator a_crossoverRateCalculator) throws InvalidConfigurationException
CrossoverOperator (final Configuration a_configuration, final IUniversalRateCalculator a_crossoverRateCalculator, boolean a_allowFullCrossOver) throws InvalidConfigurationException
CrossoverOperator (final Configuration a_configuration, final int a_desiredCrossoverRate) throws InvalidConfigurationException
CrossoverOperator (final Configuration a_configuration, final int a_desiredCrossoverRate, boolean a_allowFullCrossOver) throws InvalidConfigurationException
CrossoverOperator (final Configuration a_configuration, final int a_desiredCrossoverRate, final boolean a_allowFullCrossOver, final boolean a_xoverNewAge) throws InvalidConfigurationException
CrossoverOperator (final Configuration a_configuration, final double a_crossoverRatePercentage) throws InvalidConfigurationException
CrossoverOperator (final Configuration a_configuration, final double a_crossoverRatePercentage, boolean a_allowFullCrossOver) throws InvalidConfigurationException
CrossoverOperator (final Configuration a_configuration, final double a_crossoverRatePercentage, final boolean a_allowFullCrossOver, final boolean a_xoverNewAge) throws InvalidConfigurationException
void operate (final Population a_population, final List a_candidateChromosomes)
int compareTo (final Object a_other)
void setAllowFullCrossOver (boolean a_allowFullXOver)
boolean isAllowFullCrossOver ()
int getCrossOverRate ()
double getCrossOverRatePercent ()
void setXoverNewAge (boolean a_xoverNewAge)
boolean isXoverNewAge ()
Protected Member Functions
void init ()
void doCrossover (IChromosome firstMate, IChromosome secondMate, List a_candidateChromosomes, RandomGenerator generator)
Private Member Functions
void setCrossoverRateCalc (final IUniversalRateCalculator a_crossoverRateCalculator)
Private Attributes
int m_crossoverRate
double m_crossoverRatePercent
IUniversalRateCalculator m_crossoverRateCalc
boolean m_allowFullCrossOver
boolean m_xoverNewAge
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.48 $`
Additional Inherited Members
Detailed Description
The crossover operator randomly selects two Chromosomes from the population and `mates` them by randomly picking a gene and then swapping that gene and all subsequent genes between the two Chromosomes. The two modified Chromosomes are then added to the list of candidate Chromosomes.
If you work with CompositeGenes, this operator expects them to contain genes of the same type (e.g. IntegerGene). If you have mixed types, please provide your own crossover operator.
This CrossoverOperator supports both fixed and dynamic crossover rates. A fixed rate is one specified at construction time by the user. This operation is performed 1/m_crossoverRate as many times as there are Chromosomes in the population. Another possibility is giving the crossover rate as a percentage. A dynamic rate is determined by this class on the fly if no fixed rate is provided.
Author
Neil Rotstan
Klaus Meffert
Chris Knowles
Since
1.0
Definition at line 39 of file CrossoverOperator.java.
Constructor & Destructor Documentation
org.jgap.impl.CrossoverOperator.CrossoverOperator () throws InvalidConfigurationException [inline]
Constructs a new instance of this CrossoverOperator without a specified crossover rate, this results in dynamic crossover rate being turned off. This means that the crossover rate will be fixed at populationsize/2.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Chris Knowles
Since
2.0
Definition at line 85 of file CrossoverOperator.java.
References org.jgap.Genotype.getStaticConfiguration(), and org.jgap.impl.CrossoverOperator.init().
Referenced by org.jgap.impl.CrossoverOperator.compareTo().
org.jgap.impl.CrossoverOperator.CrossoverOperator (final Configuration a_configuration) throws InvalidConfigurationException [inline]
Constructs a new instance of this CrossoverOperator without a specified crossover rate, this results in dynamic crossover rate being turned off. This means that the crossover rate will be fixed at populationsize/2.
Parameters
a_configuration the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 102 of file CrossoverOperator.java.
References org.jgap.impl.CrossoverOperator.init().
org.jgap.impl.CrossoverOperator.CrossoverOperator (final Configuration a_configuration, final IUniversalRateCalculator a_crossoverRateCalculator) throws InvalidConfigurationException [inline]
Constructs a new instance of this CrossoverOperator with a specified crossover rate calculator, which results in dynamic crossover being turned on.
Parameters
a_configuration the configuration to use
a_crossoverRateCalculator calculator for dynamic crossover rate computation
Exceptions
InvalidConfigurationException
Author
Chris Knowles
Klaus Meffert
Since
3.0 (since 2.0 without a_configuration)
Definition at line 138 of file CrossoverOperator.java.
org.jgap.impl.CrossoverOperator.CrossoverOperator (final Configuration a_configuration, final IUniversalRateCalculator a_crossoverRateCalculator, boolean a_allowFullCrossOver) throws InvalidConfigurationException [inline]
Constructs a new instance of this CrossoverOperator with a specified crossover rate calculator, which results in dynamic crossover being turned on.
Parameters
a_configuration the configuration to use
a_crossoverRateCalculator calculator for dynamic crossover rate computation
a_allowFullCrossOver true: x-over before AND after x-over point, false: only x-over after x-over point
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.3.2
Definition at line 160 of file CrossoverOperator.java.
References org.jgap.impl.CrossoverOperator.setAllowFullCrossOver(), and org.jgap.impl.CrossoverOperator.setCrossoverRateCalc().
org.jgap.impl.CrossoverOperator.CrossoverOperator (final Configuration a_configuration, final int a_desiredCrossoverRate) throws InvalidConfigurationException [inline]
Constructs a new instance of this CrossoverOperator with the given crossover rate.
Parameters
a_configuration the configuration to use
a_desiredCrossoverRate the desired rate of crossover
Exceptions
InvalidConfigurationException
Author
Chris Knowles
Klaus Meffert
Since
3.0 (since 2.0 without a_configuration)
Definition at line 182 of file CrossoverOperator.java.
org.jgap.impl.CrossoverOperator.CrossoverOperator (final Configuration a_configuration, final int a_desiredCrossoverRate, boolean a_allowFullCrossOver) throws InvalidConfigurationException [inline]
Constructs a new instance of this CrossoverOperator with the given crossover rate. No new chromosomes are x-overed.
Parameters
a_configuration the configuration to use
a_desiredCrossoverRate the desired rate of crossover
a_allowFullCrossOver true: x-over before AND after x-over point, false: only x-over after x-over point
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.3.2
Definition at line 201 of file CrossoverOperator.java.
org.jgap.impl.CrossoverOperator.CrossoverOperator (final Configuration a_configuration, final int a_desiredCrossoverRate, final boolean a_allowFullCrossOver, final boolean a_xoverNewAge) throws InvalidConfigurationException [inline]
Constructs a new instance of this CrossoverOperator with the given crossover rate.
Parameters
a_configuration the configuration to use
a_desiredCrossoverRate the desired rate of crossover
a_allowFullCrossOver true: x-over before AND after x-over point, false: only x-over after x-over point
Exceptions
InvalidConfigurationException
Parameters
a_xoverNewAge true: also x-over chromosomes with age of zero (newly created chromosomes)
Author
Klaus Meffert
Since
3.3.2
Definition at line 223 of file CrossoverOperator.java.
References org.jgap.impl.CrossoverOperator.m_crossoverRate, org.jgap.impl.CrossoverOperator.m_crossoverRatePercent, org.jgap.impl.CrossoverOperator.setAllowFullCrossOver(), org.jgap.impl.CrossoverOperator.setCrossoverRateCalc(), and org.jgap.impl.CrossoverOperator.setXoverNewAge().
org.jgap.impl.CrossoverOperator.CrossoverOperator (final Configuration a_configuration, final double a_crossoverRatePercentage) throws InvalidConfigurationException [inline]
Constructs a new instance of this CrossoverOperator with the given crossover rate. No new chromosomes are x-overed.
Parameters
a_configuration the configuration to use
a_crossoverRatePercentage the desired rate of crossover in percentage of the population
Exceptions
InvalidConfigurationException
Author
Chris Knowles
Klaus Meffert
Since
3.0 (since 2.0 without a_configuration)
Definition at line 252 of file CrossoverOperator.java.
org.jgap.impl.CrossoverOperator.CrossoverOperator (final Configuration a_configuration, final double a_crossoverRatePercentage, boolean a_allowFullCrossOver) throws InvalidConfigurationException [inline]
Constructs a new instance of this CrossoverOperator with the given crossover rate. No new chromosomes are x-overed.
Parameters
a_configuration the configuration to use
a_crossoverRatePercentage the desired rate of crossover in percentage of the population
a_allowFullCrossOver true: x-over before AND after x-over point, false: only x-over after x-over point
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.3.2.
Definition at line 272 of file CrossoverOperator.java.
org.jgap.impl.CrossoverOperator.CrossoverOperator (final Configuration a_configuration, final double a_crossoverRatePercentage, final boolean a_allowFullCrossOver, final boolean a_xoverNewAge) throws InvalidConfigurationException [inline]
Constructs a new instance of this CrossoverOperator with the given crossover rate.
Parameters
a_configuration the configuration to use
a_crossoverRatePercentage the desired rate of crossover in percentage of the population
a_allowFullCrossOver true: x-over before AND after x-over point, false: only x-over after x-over point
a_xoverNewAge true: also x-over chromosomes with age of zero (newly created chromosomes)
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.3.2.
Definition at line 295 of file CrossoverOperator.java.
References org.jgap.impl.CrossoverOperator.m_crossoverRate, org.jgap.impl.CrossoverOperator.m_crossoverRatePercent, org.jgap.impl.CrossoverOperator.setAllowFullCrossOver(), org.jgap.impl.CrossoverOperator.setCrossoverRateCalc(), and org.jgap.impl.CrossoverOperator.setXoverNewAge().
Member Function Documentation
int org.jgap.impl.CrossoverOperator.compareTo (final Object a_other) [inline]
Compares the given object to this one.
Parameters
a_other the instance against which to compare this instance
Returns
a negative number if this instance is `less than` the given instance, zero if they are equal to each other, and a positive number if this is `greater than` the given instance
Author
Klaus Meffert
Since
2.6
Todo
Todo consider Configuration
Definition at line 466 of file CrossoverOperator.java.
References org.jgap.impl.CrossoverOperator.CrossoverOperator(), org.jgap.impl.CrossoverOperator.m_allowFullCrossOver, org.jgap.impl.CrossoverOperator.m_crossoverRate, org.jgap.impl.CrossoverOperator.m_crossoverRateCalc, and org.jgap.impl.CrossoverOperator.m_xoverNewAge.
Referenced by org.jgap.impl.CrossoverOperatorTest.testCompareTo_0().
void org.jgap.impl.CrossoverOperator.doCrossover (IChromosome firstMate, IChromosome secondMate, List a_candidateChromosomes, RandomGenerator generator) [inline], [protected]
Definition at line 390 of file CrossoverOperator.java.
References org.jgap.BaseGeneticOperator.m_monitorActive.
Referenced by org.jgap.impl.CrossoverOperator.operate().
int org.jgap.impl.CrossoverOperator.getCrossOverRate () [inline]
Returns
the crossover rate set
Author
Klaus Meffert
Since
3.3.2
Definition at line 537 of file CrossoverOperator.java.
References org.jgap.impl.CrossoverOperator.m_crossoverRate.
Referenced by org.jgap.impl.CrossoverOperatorTest.testConstruct_4(), org.jgap.impl.CrossoverOperatorTest.testConstruct_5(), and org.jgap.impl.CrossoverOperatorTest.testConstruct_6().
double org.jgap.impl.CrossoverOperator.getCrossOverRatePercent () [inline]
Returns
the crossover rate set
Author
Klaus Meffert
Since
3.3.2
Definition at line 547 of file CrossoverOperator.java.
References org.jgap.impl.CrossoverOperator.m_crossoverRatePercent.
Referenced by org.jgap.impl.CrossoverOperatorTest.testConstruct_7(), org.jgap.impl.CrossoverOperatorTest.testConstruct_8(), and org.jgap.impl.CrossoverOperatorTest.testConstruct_9().
void org.jgap.impl.CrossoverOperator.init () [inline], [protected]
Initializes certain parameters.
Author
Klaus Meffert
Since
3.3.2
Definition at line 114 of file CrossoverOperator.java.
References org.jgap.impl.CrossoverOperator.m_crossoverRate, org.jgap.impl.CrossoverOperator.m_crossoverRatePercent, org.jgap.impl.CrossoverOperator.setAllowFullCrossOver(), org.jgap.impl.CrossoverOperator.setCrossoverRateCalc(), and org.jgap.impl.CrossoverOperator.setXoverNewAge().
Referenced by org.jgap.impl.CrossoverOperator.CrossoverOperator().
boolean org.jgap.impl.CrossoverOperator.isAllowFullCrossOver () [inline]
Returns
x-over before and after a randomly chosen x-over point
Author
Klaus Meffert
Since
3.3.2
Definition at line 527 of file CrossoverOperator.java.
References org.jgap.impl.CrossoverOperator.m_allowFullCrossOver.
Referenced by org.jgap.impl.CrossoverOperatorTest.testConstruct_4(), org.jgap.impl.CrossoverOperatorTest.testConstruct_5(), org.jgap.impl.CrossoverOperatorTest.testConstruct_6(), org.jgap.impl.CrossoverOperatorTest.testConstruct_7(), org.jgap.impl.CrossoverOperatorTest.testConstruct_8(), and org.jgap.impl.CrossoverOperatorTest.testConstruct_9().
boolean org.jgap.impl.CrossoverOperator.isXoverNewAge () [inline]
Returns
a_xoverNewAge true: also x-over chromosomes with age of zero (newly created chromosomes)
Author
Klaus Meffert
Since
3.3.2
Definition at line 569 of file CrossoverOperator.java.
References org.jgap.impl.CrossoverOperator.m_xoverNewAge.
Referenced by org.jgap.impl.CrossoverOperator.operate().
void org.jgap.impl.CrossoverOperator.operate (final Population a_population, final List a_candidateChromosomes) [inline]
Does the crossing over.
Parameters
a_population the population of chromosomes from the current evolution prior to exposure to crossing over
a_candidateChromosomes the pool of chromosomes that have been selected for the next evolved population
Author
Neil Rotstan
Klaus Meffert
Since
2.0
Implements org.jgap.GeneticOperator.
Definition at line 323 of file CrossoverOperator.java.
References org.jgap.util.ICloneable.clone(), org.jgap.impl.CrossoverOperator.doCrossover(), org.jgap.BaseGeneticOperator.getConfiguration(), org.jgap.impl.CrossoverOperator.isXoverNewAge(), org.jgap.impl.CrossoverOperator.m_crossoverRate, org.jgap.impl.CrossoverOperator.m_crossoverRateCalc, org.jgap.impl.CrossoverOperator.m_crossoverRatePercent, org.jgap.BaseGeneticOperator.m_monitorActive, and org.jgap.Population.size().
void org.jgap.impl.CrossoverOperator.setAllowFullCrossOver (boolean a_allowFullXOver) [inline]
Parameters
a_allowFullXOver x-over before and after a randomly chosen point
Author
Klaus Meffert
Since
3.3.2
Definition at line 517 of file CrossoverOperator.java.
References org.jgap.impl.CrossoverOperator.m_allowFullCrossOver.
Referenced by org.jgap.impl.CrossoverOperator.CrossoverOperator(), and org.jgap.impl.CrossoverOperator.init().
void org.jgap.impl.CrossoverOperator.setCrossoverRateCalc (final IUniversalRateCalculator a_crossoverRateCalculator) [inline], [private]
Sets the crossover rate calculator.
Parameters
a_crossoverRateCalculator the new calculator
Author
Chris Knowles
Since
2.0
Definition at line 446 of file CrossoverOperator.java.
References org.jgap.impl.CrossoverOperator.m_crossoverRate, org.jgap.impl.CrossoverOperator.m_crossoverRateCalc, and org.jgap.impl.CrossoverOperator.m_crossoverRatePercent.
Referenced by org.jgap.impl.CrossoverOperator.CrossoverOperator(), and org.jgap.impl.CrossoverOperator.init().
void org.jgap.impl.CrossoverOperator.setXoverNewAge (boolean a_xoverNewAge) [inline]
Parameters
a_xoverNewAge true: also x-over chromosomes with age of zero (newly created chromosomes)
Author
Klaus Meffert
Since
3.3.2
Definition at line 558 of file CrossoverOperator.java.
References org.jgap.impl.CrossoverOperator.m_xoverNewAge.
Referenced by org.jgap.impl.CrossoverOperator.CrossoverOperator(), and org.jgap.impl.CrossoverOperator.init().
Member Data Documentation
final String org.jgap.impl.CrossoverOperator.CVS_REVISION = `$Revision: 1.48 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 42 of file CrossoverOperator.java.
boolean org.jgap.impl.CrossoverOperator.m_allowFullCrossOver [private]
true: x-over before and after a randomly chosen x-over point false: only x-over after the chosen point.
Definition at line 66 of file CrossoverOperator.java.
Referenced by org.jgap.impl.CrossoverOperator.compareTo(), org.jgap.impl.CrossoverOperator.isAllowFullCrossOver(), and org.jgap.impl.CrossoverOperator.setAllowFullCrossOver().
int org.jgap.impl.CrossoverOperator.m_crossoverRate [private]
The current crossover rate used by this crossover operator (mutual exclusive to m_crossoverRatePercent and m_crossoverRateCalc).
Definition at line 48 of file CrossoverOperator.java.
Referenced by org.jgap.impl.CrossoverOperator.compareTo(), org.jgap.impl.CrossoverOperator.CrossoverOperator(), org.jgap.impl.CrossoverOperator.getCrossOverRate(), org.jgap.impl.CrossoverOperator.init(), org.jgap.impl.CrossoverOperator.operate(), and org.jgap.impl.CrossoverOperator.setCrossoverRateCalc().
IUniversalRateCalculator org.jgap.impl.CrossoverOperator.m_crossoverRateCalc [private]
Calculator for dynamically determining the crossover rate (mutual exclusive to m_crossoverRate and m_crossoverRatePercent)
Definition at line 60 of file CrossoverOperator.java.
Referenced by org.jgap.impl.CrossoverOperator.compareTo(), org.jgap.impl.CrossoverOperator.operate(), and org.jgap.impl.CrossoverOperator.setCrossoverRateCalc().
double org.jgap.impl.CrossoverOperator.m_crossoverRatePercent [private]
Crossover rate in percentage of population size (mutual exclusive to m_crossoverRate and m_crossoverRateCalc).
Definition at line 54 of file CrossoverOperator.java.
Referenced by org.jgap.impl.CrossoverOperator.CrossoverOperator(), org.jgap.impl.CrossoverOperator.getCrossOverRatePercent(), org.jgap.impl.CrossoverOperator.init(), org.jgap.impl.CrossoverOperator.operate(), and org.jgap.impl.CrossoverOperator.setCrossoverRateCalc().
boolean org.jgap.impl.CrossoverOperator.m_xoverNewAge [private]
true: also x-over chromosomes with age of zero (newly created chromosomes)
Definition at line 71 of file CrossoverOperator.java.
Referenced by org.jgap.impl.CrossoverOperator.compareTo(), org.jgap.impl.CrossoverOperator.isXoverNewAge(), and org.jgap.impl.CrossoverOperator.setXoverNewAge().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/CrossoverOperator.java