org.jgap.gp.impl.GPProgramTest Class Reference
Public Member Functions
void setUp ()
void testExecute_0 () throws Exception
void testSerialize_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.5 $`
Additional Inherited Members
Detailed Description
Tests the GPProgram class.
Author
Klaus Meffert
Since
3.0
Definition at line 26 of file GPProgramTest.java.
Member Function Documentation
void org.jgap.gp.impl.GPProgramTest.setUp () [inline]
Definition at line 36 of file GPProgramTest.java.
static Test org.jgap.gp.impl.GPProgramTest.suite () [inline], [static]
Definition at line 31 of file GPProgramTest.java.
void org.jgap.gp.impl.GPProgramTest.testExecute_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 46 of file GPProgramTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.gp.GPTestCase.CMD_FOR, org.jgap.gp.GPTestCase.CMD_NOP, org.jgap.gp.impl.ProgramChromosome.getDepth(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
void org.jgap.gp.impl.GPProgramTest.testSerialize_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 120 of file GPProgramTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.doSerialize(), org.jgap.gp.CommandGene.IntegerClass, and org.jgap.gp.GPTestCase.m_gpconf.
Member Data Documentation
final String org.jgap.gp.impl.GPProgramTest.CVS_REVISION = `$Revision: 1.5 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 29 of file GPProgramTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/gp/impl/GPProgramTest.java