org.jgap.gp.function.Equals Class Reference
Public Member Functions
Equals (final GPConfiguration a_conf, Class a_type) throws InvalidConfigurationException
Equals (final GPConfiguration a_conf, Class a_type, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException
String toString ()
String getName ()
boolean execute_boolean (ProgramChromosome c, int n, Object[] args)
Class getChildType (IGPProgram a_ind, int a_index)
Object clone ()
boolean equals (Object a_other)
Private Attributes
Class m_type
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.9 $`
Additional Inherited Members
Detailed Description
The equals operation.
Author
Klaus Meffert
Since
3.0
Definition at line 24 of file Equals.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Equals.Equals (final GPConfiguration a_conf, Class a_type) throws InvalidConfigurationException [inline]
Definition at line 31 of file Equals.java.
Referenced by org.jgap.gp.function.Equals.clone(), and org.jgap.gp.function.Equals.equals().
org.jgap.gp.function.Equals.Equals (final GPConfiguration a_conf, Class a_type, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException [inline]
Definition at line 36 of file Equals.java.
References org.jgap.gp.CommandGene.BooleanClass, and org.jgap.gp.function.Equals.m_type.
Member Function Documentation
Object org.jgap.gp.function.Equals.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 94 of file Equals.java.
References org.jgap.gp.function.Equals.Equals(), org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getSubChildTypes(), org.jgap.gp.CommandGene.getSubReturnType(), and org.jgap.gp.function.Equals.m_type.
boolean org.jgap.gp.function.Equals.equals (Object a_other) [inline]
The equals method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Frank Pape
Since
3.4.3
Definition at line 113 of file Equals.java.
References org.jgap.gp.function.Equals.Equals(), and org.jgap.gp.function.Equals.m_type.
Referenced by org.jgap.gp.function.Equals.execute_boolean().
boolean org.jgap.gp.function.Equals.execute_boolean (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 57 of file Equals.java.
References org.jgap.gp.CommandGene.BooleanClass, org.jgap.gp.CommandGene.DELTA, org.jgap.gp.CommandGene.DoubleClass, org.jgap.gp.function.Equals.equals(), org.jgap.gp.CommandGene.FloatClass, org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.CommandGene.LongClass, org.jgap.gp.function.Equals.m_type, and org.jgap.gp.CommandGene.VoidClass.
Class org.jgap.gp.function.Equals.getChildType (IGPProgram a_ind, int a_index) [inline]
Definition at line 82 of file Equals.java.
References org.jgap.gp.function.Equals.m_type.
String org.jgap.gp.function.Equals.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 53 of file Equals.java.
String org.jgap.gp.function.Equals.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 43 of file Equals.java.
Member Data Documentation
final String org.jgap.gp.function.Equals.CVS_REVISION = `$Revision: 1.9 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file Equals.java.
Class org.jgap.gp.function.Equals.m_type [private]
Definition at line 29 of file Equals.java.
Referenced by org.jgap.gp.function.Equals.clone(), org.jgap.gp.function.Equals.Equals(), org.jgap.gp.function.Equals.equals(), org.jgap.gp.function.Equals.execute_boolean(), and org.jgap.gp.function.Equals.getChildType().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Equals.java