examples.grid.mathProblemDistributed.ClientEvolveStrategy Class Reference
Public Member Functions
ClientEvolveStrategy (GridConfiguration a_gridConfig)
void initialize (IGridClientMediator a_gc, GPConfiguration a_config, IClientFeedbackGP a_clientFeedback) throws Exception
void afterWorkRequestsSent () throws Exception
boolean isEvolutionFinished (int a_evolutionsDone)
void onFinished ()
void evolve () throws Exception
JGAPRequestGP[] generateWorkRequests (JGAPRequestGP m_workReq, IRequestSplitStrategyGP m_splitStrategy, Object data) throws Exception
void resultReceived (JGAPResultGP a_result) throws Exception
Variable createVariable (GPConfiguration a_conf) throws InvalidConfigurationException
CommandGene[][] getNodeSets (GPConfiguration conf) throws InvalidConfigurationException
GPGenotype create () throws InvalidConfigurationException
Static Public Attributes
static final String CVS_REVISION = `$Revision: 1.14 $`
Private Attributes
IClientFeedbackGP m_clientFeedback
final int m_maxEvolutions = 3
GPPopulation m_pop
GridConfiguration m_gridConfig
Static Private Attributes
static Logger log = Logger.getLogger(ClientEvolveStrategy.class)
static Float[] x = new Float[20]
static float[] y = new float[20]
Detailed Description
Sample implementation of a strategy for evolving a generation on the client.
Author
Klaus Meffert
Since
3.2
Definition at line 27 of file ClientEvolveStrategy.java.
Constructor & Destructor Documentation
examples.grid.mathProblemDistributed.ClientEvolveStrategy.ClientEvolveStrategy (GridConfiguration a_gridConfig) [inline]
Default constructor is necessary here as it will be called dynamically! Don't declare any other constructor as it will not be called!
Parameters
a_gridConfig the grid configuration to use
Definition at line 54 of file ClientEvolveStrategy.java.
References examples.grid.mathProblemDistributed.ClientEvolveStrategy.m_gridConfig.
Member Function Documentation
void examples.grid.mathProblemDistributed.ClientEvolveStrategy.afterWorkRequestsSent () throws Exception [inline]
Definition at line 83 of file ClientEvolveStrategy.java.
References examples.grid.mathProblemDistributed.ClientEvolveStrategy.m_pop.
GPGenotype examples.grid.mathProblemDistributed.ClientEvolveStrategy.create () throws InvalidConfigurationException [inline]
Definition at line 204 of file ClientEvolveStrategy.java.
References examples.grid.mathProblemDistributed.ClientEvolveStrategy.getNodeSets(), and examples.grid.mathProblemDistributed.ClientEvolveStrategy.m_gridConfig.
Referenced by examples.grid.mathProblemDistributed.ClientEvolveStrategy.initialize().
Variable examples.grid.mathProblemDistributed.ClientEvolveStrategy.createVariable (GPConfiguration a_conf) throws InvalidConfigurationException [inline]
Definition at line 177 of file ClientEvolveStrategy.java.
References org.jgap.gp.CommandGene.FloatClass.
Referenced by examples.grid.mathProblemDistributed.ClientEvolveStrategy.getNodeSets().
void examples.grid.mathProblemDistributed.ClientEvolveStrategy.evolve () throws Exception [inline]
Definition at line 125 of file ClientEvolveStrategy.java.
JGAPRequestGP [] examples.grid.mathProblemDistributed.ClientEvolveStrategy.generateWorkRequests (JGAPRequestGP m_workReq, IRequestSplitStrategyGP m_splitStrategy, Object data) throws Exception [inline]
Definition at line 132 of file ClientEvolveStrategy.java.
References examples.grid.mathProblemDistributed.ClientEvolveStrategy.m_pop.
CommandGene [][] examples.grid.mathProblemDistributed.ClientEvolveStrategy.getNodeSets (GPConfiguration conf) throws InvalidConfigurationException [inline]
Definition at line 182 of file ClientEvolveStrategy.java.
References examples.grid.mathProblemDistributed.ClientEvolveStrategy.createVariable(), org.jgap.gp.CommandGene.FloatClass, examples.grid.mathProblemDistributed.GridConfiguration.getVariable(), and examples.grid.mathProblemDistributed.ClientEvolveStrategy.m_gridConfig.
Referenced by examples.grid.mathProblemDistributed.ClientEvolveStrategy.create().
void examples.grid.mathProblemDistributed.ClientEvolveStrategy.initialize (IGridClientMediator a_gc, GPConfiguration a_config, IClientFeedbackGP a_clientFeedback) throws Exception [inline]
Called at the very beginning and only once before distributed evolution starts.
Parameters
a_gc GridClient mediator
a_config Configuration
a_clientFeedback IClientFeedback
Exceptions
Exception
Author
Klaus Meffert
Since
3.2
Definition at line 71 of file ClientEvolveStrategy.java.
References examples.grid.mathProblemDistributed.ClientEvolveStrategy.create(), examples.grid.mathProblemDistributed.ClientEvolveStrategy.m_clientFeedback, and examples.grid.mathProblemDistributed.ClientEvolveStrategy.m_pop.
boolean examples.grid.mathProblemDistributed.ClientEvolveStrategy.isEvolutionFinished (int a_evolutionsDone) [inline]
Definition at line 97 of file ClientEvolveStrategy.java.
References examples.grid.mathProblemDistributed.ClientEvolveStrategy.m_maxEvolutions, and examples.grid.mathProblemDistributed.ClientEvolveStrategy.m_pop.
void examples.grid.mathProblemDistributed.ClientEvolveStrategy.onFinished () [inline]
Called after evolution has finished.
Definition at line 119 of file ClientEvolveStrategy.java.
void examples.grid.mathProblemDistributed.ClientEvolveStrategy.resultReceived (JGAPResultGP a_result) throws Exception [inline]
Merge the received results as a basis for the next evolution.
Parameters
a_result JGAPResult
Exceptions
Exception
Since
3.2
Definition at line 155 of file ClientEvolveStrategy.java.
References examples.grid.mathProblemDistributed.ClientEvolveStrategy.m_pop.
Member Data Documentation
final String examples.grid.mathProblemDistributed.ClientEvolveStrategy.CVS_REVISION = `$Revision: 1.14 $` [static]
String containing the CVS revision. Read out via reflection!
Definition at line 30 of file ClientEvolveStrategy.java.
Logger examples.grid.mathProblemDistributed.ClientEvolveStrategy.log = Logger.getLogger(ClientEvolveStrategy.class) [static], [private]
Definition at line 32 of file ClientEvolveStrategy.java.
IClientFeedbackGP examples.grid.mathProblemDistributed.ClientEvolveStrategy.m_clientFeedback [private]
Definition at line 36 of file ClientEvolveStrategy.java.
Referenced by examples.grid.mathProblemDistributed.ClientEvolveStrategy.initialize().
GridConfiguration examples.grid.mathProblemDistributed.ClientEvolveStrategy.m_gridConfig [private]
Definition at line 42 of file ClientEvolveStrategy.java.
Referenced by examples.grid.mathProblemDistributed.ClientEvolveStrategy.ClientEvolveStrategy(), examples.grid.mathProblemDistributed.ClientEvolveStrategy.create(), and examples.grid.mathProblemDistributed.ClientEvolveStrategy.getNodeSets().
final int examples.grid.mathProblemDistributed.ClientEvolveStrategy.m_maxEvolutions = 3 [private]
Definition at line 38 of file ClientEvolveStrategy.java.
Referenced by examples.grid.mathProblemDistributed.ClientEvolveStrategy.isEvolutionFinished().
GPPopulation examples.grid.mathProblemDistributed.ClientEvolveStrategy.m_pop [private]
Definition at line 40 of file ClientEvolveStrategy.java.
Referenced by examples.grid.mathProblemDistributed.ClientEvolveStrategy.afterWorkRequestsSent(), examples.grid.mathProblemDistributed.ClientEvolveStrategy.generateWorkRequests(), examples.grid.mathProblemDistributed.ClientEvolveStrategy.initialize(), examples.grid.mathProblemDistributed.ClientEvolveStrategy.isEvolutionFinished(), and examples.grid.mathProblemDistributed.ClientEvolveStrategy.resultReceived().
Float [] examples.grid.mathProblemDistributed.ClientEvolveStrategy.x = new Float[20] [static], [private]
Definition at line 44 of file ClientEvolveStrategy.java.
float [] examples.grid.mathProblemDistributed.ClientEvolveStrategy.y = new float[20] [static], [private]
Definition at line 46 of file ClientEvolveStrategy.java.
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/grid/mathProblemDistributed/ClientEvolveStrategy.java