examples.gp.tictactoe.IfIsOccupied Class Reference
Public Member Functions
IfIsOccupied (final GPConfiguration a_conf, Board a_board, Class a_type) throws InvalidConfigurationException
IfIsOccupied (final GPConfiguration a_conf, Board a_board, Class a_type, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException
String toString ()
String getName ()
void execute_void (ProgramChromosome c, int n, Object[] args)
Class getChildType (IGPProgram a_ind, int a_chromNum)
Object clone ()
Private Attributes
Class m_type
Board m_board
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
The if-then construct. If-Condition is: if board free at position (X,Y), then execute Z else do nothing.
Author
Klaus Meffert
Since
3.2
Definition at line 24 of file IfIsOccupied.java.
Constructor & Destructor Documentation
examples.gp.tictactoe.IfIsOccupied.IfIsOccupied (final GPConfiguration a_conf, Board a_board, Class a_type) throws InvalidConfigurationException [inline]
Definition at line 33 of file IfIsOccupied.java.
Referenced by examples.gp.tictactoe.IfIsOccupied.clone().
examples.gp.tictactoe.IfIsOccupied.IfIsOccupied (final GPConfiguration a_conf, Board a_board, Class a_type, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException [inline]
Definition at line 38 of file IfIsOccupied.java.
References examples.gp.tictactoe.IfIsOccupied.m_board, examples.gp.tictactoe.IfIsOccupied.m_type, and org.jgap.gp.CommandGene.VoidClass.
Member Function Documentation
Object examples.gp.tictactoe.IfIsOccupied.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 108 of file IfIsOccupied.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getSubChildTypes(), org.jgap.gp.CommandGene.getSubReturnType(), examples.gp.tictactoe.IfIsOccupied.IfIsOccupied(), examples.gp.tictactoe.IfIsOccupied.m_board, and examples.gp.tictactoe.IfIsOccupied.m_type.
void examples.gp.tictactoe.IfIsOccupied.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 60 of file IfIsOccupied.java.
References org.jgap.gp.CommandGene.check(), examples.gp.tictactoe.Board.HEIGHT, org.jgap.gp.CommandGene.IntegerClass, examples.gp.tictactoe.IfIsOccupied.m_type, and examples.gp.tictactoe.Board.WIDTH.
Class examples.gp.tictactoe.IfIsOccupied.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Determines which type a specific child of this command has.
Parameters
a_ind ignored here
a_chromNum index of child
Returns
type of the a_chromNum'th child
Author
Klaus Meffert
Since
3.2
Definition at line 93 of file IfIsOccupied.java.
References examples.gp.tictactoe.IfIsOccupied.m_type, and org.jgap.gp.CommandGene.VoidClass.
String examples.gp.tictactoe.IfIsOccupied.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 56 of file IfIsOccupied.java.
String examples.gp.tictactoe.IfIsOccupied.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 46 of file IfIsOccupied.java.
Member Data Documentation
final String examples.gp.tictactoe.IfIsOccupied.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file IfIsOccupied.java.
Board examples.gp.tictactoe.IfIsOccupied.m_board [private]
Definition at line 31 of file IfIsOccupied.java.
Referenced by examples.gp.tictactoe.IfIsOccupied.clone(), and examples.gp.tictactoe.IfIsOccupied.IfIsOccupied().
Class examples.gp.tictactoe.IfIsOccupied.m_type [private]
Definition at line 29 of file IfIsOccupied.java.
Referenced by examples.gp.tictactoe.IfIsOccupied.clone(), examples.gp.tictactoe.IfIsOccupied.execute_void(), examples.gp.tictactoe.IfIsOccupied.getChildType(), and examples.gp.tictactoe.IfIsOccupied.IfIsOccupied().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/tictactoe/IfIsOccupied.java