org.jgap.impl.CauchyRandomGenerator Class Reference
Public Member Functions
CauchyRandomGenerator ()
CauchyRandomGenerator (final double a_location, final double a_scale)
int nextInt ()
int nextInt (final int a_ceiling)
long nextLong ()
double nextDouble ()
float nextFloat ()
boolean nextBoolean ()
double nextCauchy ()
double getCauchyStandardDeviation ()
Private Member Functions
void readObject (ObjectInputStream a_inputStream) throws IOException, ClassNotFoundException
Private Attributes
double m_scale
double m_location
Random m_rn
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.15 $`
Additional Inherited Members
Detailed Description
Cauchy probability density function (cumulative distribution function).
Author
Klaus Meffert
Since
1.1
Definition at line 23 of file CauchyRandomGenerator.java.
Constructor & Destructor Documentation
org.jgap.impl.CauchyRandomGenerator.CauchyRandomGenerator () [inline]
Defaults to location = 0.0 and scale = 1.0.
Author
Klaus Meffert
Since
1.1
Definition at line 40 of file CauchyRandomGenerator.java.
org.jgap.impl.CauchyRandomGenerator.CauchyRandomGenerator (final double a_location, final double a_scale) [inline]
Parameters
a_location cauchy parameter, 0 is standard
a_scale cauchy parameter, 1 is standard
Author
Klaus Meffert
Since
1.1
Definition at line 51 of file CauchyRandomGenerator.java.
References org.jgap.impl.CauchyRandomGenerator.m_location, org.jgap.impl.CauchyRandomGenerator.m_rn, and org.jgap.impl.CauchyRandomGenerator.m_scale.
Member Function Documentation
double org.jgap.impl.CauchyRandomGenerator.getCauchyStandardDeviation () [inline]
Returns
the cauchy standard deviation
Author
Klaus Meffert
Since
1.1
Definition at line 104 of file CauchyRandomGenerator.java.
References org.jgap.impl.CauchyRandomGenerator.m_scale.
Referenced by org.jgap.impl.CauchyRandomGeneratorTest.testGetCauchyStdDeviation_0().
boolean org.jgap.impl.CauchyRandomGenerator.nextBoolean () [inline]
Returns the next pseudorandom, uniformly distributed boolean value from this random number generator's sequence. The general contract of nextBoolean is that one boolean value is pseudorandomly generated and returned. The values true and false are produced with (approximately) equal probability.
Returns
a pseudorandom boolean value
Author
Neil Rotstan
Since
1.0
Implements org.jgap.RandomGenerator.
Definition at line 81 of file CauchyRandomGenerator.java.
References org.jgap.impl.CauchyRandomGenerator.nextCauchy().
double org.jgap.impl.CauchyRandomGenerator.nextCauchy () [inline]
Calculate Cumulative Cauchy distribution function.
Returns
the probability that a stochastic variable x is less than X
Author
Klaus Meffert
Since
1.1
Definition at line 93 of file CauchyRandomGenerator.java.
References org.jgap.impl.CauchyRandomGenerator.m_location, and org.jgap.impl.CauchyRandomGenerator.m_scale.
Referenced by org.jgap.impl.CauchyRandomGenerator.nextBoolean(), org.jgap.impl.CauchyRandomGenerator.nextDouble(), org.jgap.impl.CauchyRandomGenerator.nextFloat(), org.jgap.impl.CauchyRandomGenerator.nextInt(), and org.jgap.impl.CauchyRandomGenerator.nextLong().
double org.jgap.impl.CauchyRandomGenerator.nextDouble () [inline]
Returns the next pseudorandom, uniformly distributed double value between 0.0 and 1.0 from this random number generator's sequence.
Returns
a psuedorandom double value GREATER/EQUAL 0 AND LESS THAN 1
Author
Neil Rotstan
Since
1.0
Implements org.jgap.RandomGenerator.
Definition at line 72 of file CauchyRandomGenerator.java.
References org.jgap.impl.CauchyRandomGenerator.nextCauchy().
float org.jgap.impl.CauchyRandomGenerator.nextFloat () [inline]
Returns the next pseudorandom, uniformly distributed float value between 0.0 and 1.0 from this random number generator's sequence.
Returns
a psuedorandom float value
Author
Neil Rotstan
Since
1.0
Implements org.jgap.RandomGenerator.
Definition at line 76 of file CauchyRandomGenerator.java.
References org.jgap.impl.CauchyRandomGenerator.nextCauchy().
int org.jgap.impl.CauchyRandomGenerator.nextInt () [inline]
Returns the next pseudorandom, uniformly distributed int value from this random number generator's sequence. The general contract of nextInt is that one int value is pseudorandomly generated and returned. All 2^32 possible int values are produced with (approximately) equal probability.
Returns
a pseudorandom integer value
Author
Neil Rotstan
Since
1.0
Implements org.jgap.RandomGenerator.
Definition at line 57 of file CauchyRandomGenerator.java.
References org.jgap.impl.CauchyRandomGenerator.nextCauchy().
int org.jgap.impl.CauchyRandomGenerator.nextInt (final int a_ceiling) [inline]
Definition at line 62 of file CauchyRandomGenerator.java.
References org.jgap.impl.CauchyRandomGenerator.nextCauchy().
long org.jgap.impl.CauchyRandomGenerator.nextLong () [inline]
Returns the next pseudorandom, uniformly distributed long value from this random number generator's sequence. The general contract of nextLong() is that one long value is pseudorandomly generated and returned. All 2^64 possible long values are produced with (approximately) equal probability.
Returns
a psuedorandom long value
Author
Neil Rotstan
Since
1.0
Implements org.jgap.RandomGenerator.
Definition at line 67 of file CauchyRandomGenerator.java.
References org.jgap.impl.CauchyRandomGenerator.nextCauchy().
void org.jgap.impl.CauchyRandomGenerator.readObject (ObjectInputStream a_inputStream) throws IOException, ClassNotFoundException [inline], [private]
When deserializing, initialize the seed because otherwise we could get duplicate evolution results when doing distributed computing!
Parameters
a_inputStream the ObjectInputStream provided for deserialzation
Exceptions
IOException
ClassNotFoundException
Author
Klaus Meffert
Since
3.01
Definition at line 120 of file CauchyRandomGenerator.java.
Member Data Documentation
final String org.jgap.impl.CauchyRandomGenerator.CVS_REVISION = `$Revision: 1.15 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file CauchyRandomGenerator.java.
double org.jgap.impl.CauchyRandomGenerator.m_location [private]
Definition at line 30 of file CauchyRandomGenerator.java.
Referenced by org.jgap.impl.CauchyRandomGenerator.CauchyRandomGenerator(), and org.jgap.impl.CauchyRandomGenerator.nextCauchy().
Random org.jgap.impl.CauchyRandomGenerator.m_rn [private]
Definition at line 32 of file CauchyRandomGenerator.java.
Referenced by org.jgap.impl.CauchyRandomGenerator.CauchyRandomGenerator().
double org.jgap.impl.CauchyRandomGenerator.m_scale [private]
Definition at line 28 of file CauchyRandomGenerator.java.
Referenced by org.jgap.impl.CauchyRandomGenerator.CauchyRandomGenerator(), org.jgap.impl.CauchyRandomGenerator.getCauchyStandardDeviation(), and org.jgap.impl.CauchyRandomGenerator.nextCauchy().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/CauchyRandomGenerator.java