org.jgap.impl.GaussianMutationOperator Class Reference
Public Member Functions
GaussianMutationOperator () throws InvalidConfigurationException
GaussianMutationOperator (Configuration a_config) throws InvalidConfigurationException
GaussianMutationOperator (final Configuration a_configuration, final double a_deviation) throws InvalidConfigurationException
void operate (final Population a_population, final List a_candidateChromosomes)
int compareTo (final Object a_other)
double getDeviation ()
Private Member Functions
void mutateGene (final Gene a_gene, final double a_percentage)
Private Attributes
double m_deviation
RandomGenerator m_rg
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.25 $`
Additional Inherited Members
Detailed Description
This genetic operator performs Gaussian mutation across all genes in a Chromosome.
Author
Klaus Meffert (modified JOONEGAP source)
Since
2.0
Definition at line 22 of file GaussianMutationOperator.java.
Constructor & Destructor Documentation
org.jgap.impl.GaussianMutationOperator.GaussianMutationOperator () throws InvalidConfigurationException [inline]
Constructs a GaussianMutationOperator with a default deviation of 0.05. Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.0
Definition at line 41 of file GaussianMutationOperator.java.
Referenced by org.jgap.impl.GaussianMutationOperator.compareTo().
org.jgap.impl.GaussianMutationOperator.GaussianMutationOperator (Configuration a_config) throws InvalidConfigurationException [inline]
Constructs a GaussianMutationOperator with a default deviation of 0.05.
Parameters
a_config the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Definition at line 56 of file GaussianMutationOperator.java.
org.jgap.impl.GaussianMutationOperator.GaussianMutationOperator (final Configuration a_configuration, final double a_deviation) throws InvalidConfigurationException [inline]
Constructs a GaussianMutationOperator with the given deviation.
Parameters
a_configuration the configuration to use
a_deviation sic
Exceptions
InvalidConfigurationException
Since
3.0 (since 2.0 without a_configuration)
Definition at line 71 of file GaussianMutationOperator.java.
References org.jgap.impl.GaussianMutationOperator.m_deviation.
Member Function Documentation
int org.jgap.impl.GaussianMutationOperator.compareTo (final Object a_other) [inline]
Compares the given GeneticOperator to this GeneticOperator.
Parameters
a_other the instance against which to compare this instance
Returns
a negative number if this instance is `less than` the given instance, zero if they are equal to each other, and a positive number if this is `greater than` the given instance
Author
Klaus Meffert
Since
2.6
Definition at line 178 of file GaussianMutationOperator.java.
References org.jgap.impl.GaussianMutationOperator.GaussianMutationOperator(), and org.jgap.impl.GaussianMutationOperator.m_deviation.
Referenced by org.jgap.impl.GaussianMutationOperatorTest.testCompareTo_0().
double org.jgap.impl.GaussianMutationOperator.getDeviation () [inline]
Returns
the deviation set
Author
Klaus Meffert
Since
3.1
Definition at line 202 of file GaussianMutationOperator.java.
References org.jgap.impl.GaussianMutationOperator.m_deviation.
Referenced by org.jgap.impl.GaussianMutationOperatorTest.testConstruct_0(), org.jgap.impl.GaussianMutationOperatorTest.testConstruct_1(), and org.jgap.impl.GaussianMutationOperatorTest.testConstruct_3().
void org.jgap.impl.GaussianMutationOperator.mutateGene (final Gene a_gene, final double a_percentage) [inline], [private]
Helper: mutate all atomic elements of a gene.
Parameters
a_gene the gene to be mutated
a_percentage the percentage the gene is to be mutated with
Author
Klaus Meffert
Since
2.0
Definition at line 158 of file GaussianMutationOperator.java.
Referenced by org.jgap.impl.GaussianMutationOperator.operate().
void org.jgap.impl.GaussianMutationOperator.operate (final Population a_population, final List a_candidateChromosomes) [inline]
Executes the operation.
Parameters
a_population containing chromosomes to be mutated
a_candidateChromosomes resulting chromosomes
Author
Klaus Meffert
Since
2.0
Implements org.jgap.GeneticOperator.
Definition at line 87 of file GaussianMutationOperator.java.
References org.jgap.util.ICloneable.clone(), org.jgap.impl.CompositeGene.geneAt(), org.jgap.BaseGeneticOperator.getConfiguration(), org.jgap.impl.GaussianMutationOperator.m_deviation, org.jgap.BaseGeneticOperator.m_monitorActive, org.jgap.impl.GaussianMutationOperator.m_rg, org.jgap.impl.GaussianMutationOperator.mutateGene(), and org.jgap.Population.size().
Member Data Documentation
final String org.jgap.impl.GaussianMutationOperator.CVS_REVISION = `$Revision: 1.25 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file GaussianMutationOperator.java.
double org.jgap.impl.GaussianMutationOperator.m_deviation [private]
Definition at line 27 of file GaussianMutationOperator.java.
Referenced by org.jgap.impl.GaussianMutationOperator.compareTo(), org.jgap.impl.GaussianMutationOperator.GaussianMutationOperator(), org.jgap.impl.GaussianMutationOperator.getDeviation(), and org.jgap.impl.GaussianMutationOperator.operate().
RandomGenerator org.jgap.impl.GaussianMutationOperator.m_rg [private]
Definition at line 29 of file GaussianMutationOperator.java.
Referenced by org.jgap.impl.GaussianMutationOperator.operate().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/GaussianMutationOperator.java