org.jgap.impl.MutationOperatorTest Class Reference
Classes
class GeneticOperatorConstraintForTesting
Public Member Functions
void setUp ()
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testConstruct_2 () throws Exception
void testConstruct_3 () throws Exception
void testOperate_0 () throws Exception
void testOperate_0_2 () throws Exception
void testOperate_1 () throws Exception
void testOperate_2 () throws Exception
void testOperate_3 () throws Exception
void testOperate_3_1 () throws Exception
void testOperate_4 () throws Exception
void testOperate_5 () throws Exception
void testOperate_5_2 () throws Exception
void testOperate_6 () throws Exception
void testOperate_6_2 () throws Exception
void testOperate_8 () throws Exception
void testIsSerializable_0 () throws Exception
void testDoSerialize_0 () throws Exception
void testEquals_0 () throws Exception
void testCompareTo_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.39 $`
Additional Inherited Members
Detailed Description
Tests the MutationOperator class.
Author
Klaus Meffert
Since
1.1
Definition at line 24 of file MutationOperatorTest.java.
Member Function Documentation
void org.jgap.impl.MutationOperatorTest.setUp () [inline]
Definition at line 34 of file MutationOperatorTest.java.
static Test org.jgap.impl.MutationOperatorTest.suite () [inline], [static]
Definition at line 29 of file MutationOperatorTest.java.
void org.jgap.impl.MutationOperatorTest.testCompareTo_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 564 of file MutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.impl.MutationOperator.compareTo().
void org.jgap.impl.MutationOperatorTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 44 of file MutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.MutationOperator.getMutationRate(), and org.jgap.impl.MutationOperator.getMutationRateCalc().
void org.jgap.impl.MutationOperatorTest.testConstruct_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 56 of file MutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.MutationOperator.getMutationRate(), and org.jgap.impl.MutationOperator.getMutationRateCalc().
void org.jgap.impl.MutationOperatorTest.testConstruct_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 68 of file MutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.MutationOperator.getMutationRate(), and org.jgap.impl.MutationOperator.getMutationRateCalc().
void org.jgap.impl.MutationOperatorTest.testConstruct_3 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 80 of file MutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.impl.MutationOperator.getMutationRate(), and org.jgap.impl.MutationOperator.getMutationRateCalc().
void org.jgap.impl.MutationOperatorTest.testDoSerialize_0 () throws Exception [inline]
Ensures that operator and all objects contained implement Serializable.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 527 of file MutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.doSerialize().
void org.jgap.impl.MutationOperatorTest.testEquals_0 () throws Exception [inline]
Test equals with classcast object.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 552 of file MutationOperatorTest.java.
void org.jgap.impl.MutationOperatorTest.testIsSerializable_0 () throws Exception [inline]
Ensures operator is implementing Serializable
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 514 of file MutationOperatorTest.java.
References org.jgap.JGAPTestCase.isSerializable().
void org.jgap.impl.MutationOperatorTest.testOperate_0 () throws Exception [inline]
Ensure that size of mutated set of chromosomes equals the size of original chromosomes.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 95 of file MutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MutationOperatorTest.testOperate_0_2 () throws Exception [inline]
Ensure that size of mutated set of chromosomes equals the size of original chromosomes.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 114 of file MutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MutationOperatorTest.testOperate_1 () throws Exception [inline]
Mutating with different types of genes contained in the population should be possible without exception.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 151 of file MutationOperatorTest.java.
References org.jgap.JGAPTestCase.conf.
void org.jgap.impl.MutationOperatorTest.testOperate_2 () throws Exception [inline]
NullpointerException because of null Configuration.
Exceptions
Exception
Author
Klaus Meffert
Definition at line 173 of file MutationOperatorTest.java.
void org.jgap.impl.MutationOperatorTest.testOperate_3 () throws Exception [inline]
Tests if population size grows expectedly after two consecutive calls.
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 196 of file MutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.impl.MutationOperatorTest.testOperate_3_1 () throws Exception [inline]
Exceptions
Exception
Author
Dan Clark
Since
2.6
Definition at line 250 of file MutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.BaseChromosome.getGene().
void org.jgap.impl.MutationOperatorTest.testOperate_4 () throws Exception [inline]
Ensure that nothing is done.
Exceptions
Exception
Author
Klaus Meffert
Since
2.4
Definition at line 307 of file MutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.impl.MutationOperatorTest.testOperate_5 () throws Exception [inline]
Mutation, especially tested for an IntegerGene.
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 335 of file MutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.impl.MutationOperatorTest.testOperate_5_2 () throws Exception [inline]
Mutation, especially tested for an IntegerGene. Uses a CompositeGene.
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 382 of file MutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.impl.MutationOperatorTest.testOperate_6 () throws Exception [inline]
Following should be possible without exception.
Exceptions
Exception
Author
Klaus Meffert
Since
2.2
Definition at line 437 of file MutationOperatorTest.java.
void org.jgap.impl.MutationOperatorTest.testOperate_6_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 451 of file MutationOperatorTest.java.
void org.jgap.impl.MutationOperatorTest.testOperate_8 () throws Exception [inline]
Considers IGeneticOperatorConstraint. Here, the mutation of a BooleanGene is forbidden by that constraint.
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 468 of file MutationOperatorTest.java.
References org.jgap.JGAPTestCase.assertEquals().
Member Data Documentation
final String org.jgap.impl.MutationOperatorTest.CVS_REVISION = `$Revision: 1.39 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file MutationOperatorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/MutationOperatorTest.java