org.jgap.gp.function.IfElse Class Reference
Public Member Functions
IfElse (final GPConfiguration a_conf, Class a_type) throws InvalidConfigurationException
IfElse (final GPConfiguration a_conf, Class a_type, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException
String toString ()
String getName ()
boolean execute_boolean (ProgramChromosome c, int n, Object[] args)
int execute_int (ProgramChromosome c, int n, Object[] args)
void execute_void (ProgramChromosome c, int n, Object[] args)
Class getChildType (IGPProgram a_ind, int a_chromNum)
Object clone ()
boolean equals (Object a_other)
Private Attributes
Class m_type
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.14 $`
Additional Inherited Members
Detailed Description
The if-then-else construct.
Author
Klaus Meffert
Since
3.0
Definition at line 24 of file IfElse.java.
Constructor & Destructor Documentation
org.jgap.gp.function.IfElse.IfElse (final GPConfiguration a_conf, Class a_type) throws InvalidConfigurationException [inline]
Definition at line 31 of file IfElse.java.
Referenced by org.jgap.gp.function.IfElse.clone(), and org.jgap.gp.function.IfElse.equals().
org.jgap.gp.function.IfElse.IfElse (final GPConfiguration a_conf, Class a_type, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException [inline]
Definition at line 36 of file IfElse.java.
References org.jgap.gp.function.IfElse.m_type, and org.jgap.gp.CommandGene.VoidClass.
Member Function Documentation
Object org.jgap.gp.function.IfElse.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 169 of file IfElse.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getSubChildTypes(), org.jgap.gp.CommandGene.getSubReturnType(), org.jgap.gp.function.IfElse.IfElse(), and org.jgap.gp.function.IfElse.m_type.
boolean org.jgap.gp.function.IfElse.equals (Object a_other) [inline]
The equals method.
Parameters
a_other the other object to compare
Returns
true if the objects are seen as equal
Author
Frank Pape
Since
3.4.3
Definition at line 188 of file IfElse.java.
References org.jgap.gp.function.IfElse.IfElse(), and org.jgap.gp.function.IfElse.m_type.
boolean org.jgap.gp.function.IfElse.execute_boolean (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 57 of file IfElse.java.
References org.jgap.gp.CommandGene.BooleanClass, org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.DoubleClass, org.jgap.gp.CommandGene.FloatClass, org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.CommandGene.LongClass, and org.jgap.gp.function.IfElse.m_type.
int org.jgap.gp.function.IfElse.execute_int (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 86 of file IfElse.java.
References org.jgap.gp.CommandGene.BooleanClass, org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.DoubleClass, org.jgap.gp.CommandGene.FloatClass, org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.CommandGene.LongClass, and org.jgap.gp.function.IfElse.m_type.
void org.jgap.gp.function.IfElse.execute_void (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 115 of file IfElse.java.
References org.jgap.gp.CommandGene.BooleanClass, org.jgap.gp.CommandGene.check(), org.jgap.gp.CommandGene.DoubleClass, org.jgap.gp.CommandGene.FloatClass, org.jgap.gp.CommandGene.IntegerClass, org.jgap.gp.CommandGene.LongClass, and org.jgap.gp.function.IfElse.m_type.
Class org.jgap.gp.function.IfElse.getChildType (IGPProgram a_ind, int a_chromNum) [inline]
Determines which type a specific child of this command has.
Parameters
a_ind ignored here
a_chromNum index of child
Returns
type of the a_chromNum'th child
Author
Klaus Meffert
Since
3.2
Definition at line 154 of file IfElse.java.
References org.jgap.gp.function.IfElse.m_type, and org.jgap.gp.CommandGene.VoidClass.
String org.jgap.gp.function.IfElse.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 53 of file IfElse.java.
String org.jgap.gp.function.IfElse.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 43 of file IfElse.java.
Member Data Documentation
final String org.jgap.gp.function.IfElse.CVS_REVISION = `$Revision: 1.14 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 27 of file IfElse.java.
Class org.jgap.gp.function.IfElse.m_type [private]
Definition at line 29 of file IfElse.java.
Referenced by org.jgap.gp.function.IfElse.clone(), org.jgap.gp.function.IfElse.equals(), org.jgap.gp.function.IfElse.execute_boolean(), org.jgap.gp.function.IfElse.execute_int(), org.jgap.gp.function.IfElse.execute_void(), org.jgap.gp.function.IfElse.getChildType(), and org.jgap.gp.function.IfElse.IfElse().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/IfElse.java