org.jgap.audit.KeyedValueTest Class Reference
Public Member Functions
void setUp ()
void testConstruct_0 () throws Exception
void testConstruct_1 () throws Exception
void testConstruct_2 () throws Exception
void testClone_0 () throws Exception
void testEquals_0 () throws Exception
void testEquals_1 () throws Exception
void testEquals_2 () throws Exception
void testHashcode_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Additional Inherited Members
Detailed Description
Tests for KeyedValue class
Author
Klaus Meffert
Since
2.2
Definition at line 22 of file KeyedValueTest.java.
Member Function Documentation
void org.jgap.audit.KeyedValueTest.setUp () [inline]
Definition at line 27 of file KeyedValueTest.java.
static Test org.jgap.audit.KeyedValueTest.suite () [inline], [static]
Definition at line 31 of file KeyedValueTest.java.
void org.jgap.audit.KeyedValueTest.testClone_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 88 of file KeyedValueTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.audit.KeyedValue.clone(), org.jgap.audit.KeyedValue.getKey(), and org.jgap.audit.KeyedValue.getValue().
void org.jgap.audit.KeyedValueTest.testConstruct_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.6
Definition at line 42 of file KeyedValueTest.java.
References org.jgap.audit.KeyedValue.getKey(), and org.jgap.audit.KeyedValue.getValue().
void org.jgap.audit.KeyedValueTest.testConstruct_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 60 of file KeyedValueTest.java.
References org.jgap.audit.KeyedValue.getKey(), and org.jgap.audit.KeyedValue.getValue().
void org.jgap.audit.KeyedValueTest.testConstruct_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 74 of file KeyedValueTest.java.
References org.jgap.audit.KeyedValue.getKey(), org.jgap.audit.KeyedValue.getValue(), and org.jgap.audit.KeyedValue.hashCode().
void org.jgap.audit.KeyedValueTest.testEquals_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 105 of file KeyedValueTest.java.
References org.jgap.audit.KeyedValue.equals().
void org.jgap.audit.KeyedValueTest.testEquals_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 121 of file KeyedValueTest.java.
References org.jgap.audit.KeyedValue.equals().
void org.jgap.audit.KeyedValueTest.testEquals_2 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 139 of file KeyedValueTest.java.
References org.jgap.audit.KeyedValue.equals().
void org.jgap.audit.KeyedValueTest.testHashcode_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 154 of file KeyedValueTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.audit.KeyedValue.hashCode().
Member Data Documentation
final String org.jgap.audit.KeyedValueTest.CVS_REVISION = `$Revision: 1.3 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file KeyedValueTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/audit/KeyedValueTest.java