org.jgap.impl.NumberGene Class Reference
Public Member Functions
NumberGene (Configuration a_config) throws InvalidConfigurationException
int compareTo (final Object a_other)
void setAllele (final Object a_newValue)
Protected Member Functions
abstract int compareToNative (Object a_o1, Object a_o2)
abstract void mapValueToWithinBounds ()
Object getInternalValue ()
Private Attributes
Object m_value
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.23 $`
Additional Inherited Members
Detailed Description
Base class for all Genes based on numbers.
Author
Klaus Meffert
Since
1.1 (most code moved and adapted from IntegerGene)
Definition at line 20 of file NumberGene.java.
Constructor & Destructor Documentation
org.jgap.impl.NumberGene.NumberGene (Configuration a_config) throws InvalidConfigurationException [inline]
Definition at line 31 of file NumberGene.java.
Referenced by org.jgap.impl.NumberGene.compareTo().
Member Function Documentation
int org.jgap.impl.NumberGene.compareTo (final Object a_other) [inline]
Compares this NumberGene with the specified object (which must also be a NumberGene) for order, which is determined by the number value of this Gene compared to the one provided for comparison.
Parameters
a_other the NumberGene to be compared to this NumberGene
Returns
a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than the object provided for comparison
Exceptions
ClassCastException if the specified object's type prevents it from being compared to this NumberGene
Author
Klaus Meffert
Since
1.1
Definition at line 50 of file NumberGene.java.
References org.jgap.BaseGene.compareApplicationData(), org.jgap.impl.NumberGene.compareToNative(), org.jgap.BaseGene.getApplicationData(), org.jgap.BaseGene.isCompareApplicationData(), org.jgap.impl.NumberGene.m_value, and org.jgap.impl.NumberGene.NumberGene().
Referenced by org.jgap.impl.NumberGeneTest.NumberGeneImpl.equals().
abstract int org.jgap.impl.NumberGene.compareToNative (Object a_o1, Object a_o2) [protected], [pure virtual]
Compares to objects by first casting them into their expected type (e.g. Integer for IntegerGene) and then calling the compareTo-method of the casted type.
Parameters
a_o1 first object to be compared, always is not null
a_o2 second object to be compared, always is not null
Returns
a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than the object provided for comparison
Author
Klaus Meffert
Since
1.1
Implemented in org.jgap.impl.NumberGeneTest.NumberGeneImpl, and org.jgap.impl.DoubleGene.
Referenced by org.jgap.impl.NumberGene.compareTo().
Object org.jgap.impl.NumberGene.getInternalValue () [inline], [protected], [virtual]
Each Gene implementation holds its own m_value object keeping the allele value. In your Gene implementation, just return it with this method (see org.jgap.impl.BooleanGene for example)
Returns
the m_value object
Author
Klaus Meffert
Since
2.2
Implements org.jgap.BaseGene.
Definition at line 165 of file NumberGene.java.
References org.jgap.impl.NumberGene.m_value.
Referenced by org.jgap.impl.DoubleGene.getPersistentRepresentation(), org.jgap.impl.IntegerGene.getPersistentRepresentation(), org.jgap.impl.MutipleIntegerGene.getPersistentRepresentation(), org.jgap.impl.DoubleGene.hashCode(), org.jgap.impl.IntegerGene.hashCode(), org.jgap.impl.MutipleIntegerGene.hashCode(), org.jgap.impl.DoubleGene.toString(), org.jgap.impl.IntegerGene.toString(), and org.jgap.impl.MutipleIntegerGene.toString().
abstract void org.jgap.impl.NumberGene.mapValueToWithinBounds () [protected], [pure virtual]
Maps the value of this NumberGene to within the bounds specified by the m_upperBounds and m_lowerBounds instance variables. The value's relative position within the integer range will be preserved within the bounds range (in other words, if the value is about halfway between the integer max and min, then the resulting value will be about halfway between the upper bounds and lower bounds). If the value is null or is already within the bounds, it will be left unchanged.
Author
Klaus Meffert
Since
1.1
Implemented in org.jgap.impl.NumberGeneTest.NumberGeneImpl, org.jgap.impl.MutipleIntegerGene, org.jgap.impl.IntegerGene, and org.jgap.impl.DoubleGene.
Referenced by org.jgap.impl.NumberGene.setAllele().
void org.jgap.impl.NumberGene.setAllele (final Object a_newValue) [inline]
Sets the value (allele) of this Gene to the new given value. This class expects the value to be an instance of current type (e.g. Integer). If the value is above or below the upper or lower bounds, it will be mappped to within the allowable range.
Parameters
a_newValue the new value of this Gene instance
Author
Klaus Meffert
Since
1.1
Definition at line 138 of file NumberGene.java.
References org.jgap.BaseGene.getConstraintChecker(), org.jgap.impl.NumberGene.m_value, and org.jgap.impl.NumberGene.mapValueToWithinBounds().
Referenced by org.jgap.impl.DoubleGene.applyMutation(), org.jgap.impl.IntegerGene.applyMutation(), org.jgap.impl.MutipleIntegerGene.applyMutation(), org.jgap.impl.DoubleGene.mapValueToWithinBounds(), org.jgap.impl.IntegerGene.mapValueToWithinBounds(), org.jgap.impl.MutipleIntegerGene.mapValueToWithinBounds(), org.jgap.impl.NumberGeneTest.NumberGeneImpl.mapValueToWithinBounds(), org.jgap.impl.DoubleGene.setToRandomValue(), org.jgap.impl.IntegerGene.setToRandomValue(), org.jgap.impl.MutipleIntegerGene.setToRandomValue(), org.jgap.impl.DoubleGene.setValueFromPersistentRepresentation(), org.jgap.impl.IntegerGene.setValueFromPersistentRepresentation(), and org.jgap.impl.MutipleIntegerGene.setValueFromPersistentRepresentation().
Member Data Documentation
final String org.jgap.impl.NumberGene.CVS_REVISION = `$Revision: 1.23 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 23 of file NumberGene.java.
Object org.jgap.impl.NumberGene.m_value [private]
References the internal value (allele) of this Gene E.g., for DoubleGene this is of type Double
Definition at line 29 of file NumberGene.java.
Referenced by org.jgap.impl.NumberGene.compareTo(), org.jgap.impl.NumberGene.getInternalValue(), and org.jgap.impl.NumberGene.setAllele().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/NumberGene.java