org.jgap.gp.CommandDynamicArity Class Reference
Public Member Functions
CommandDynamicArity () throws Exception
CommandDynamicArity (final GPConfiguration a_conf, int a_arityInitial, int a_arityMin, int a_arityMax, Class a_returnType) throws InvalidConfigurationException
CommandDynamicArity (final GPConfiguration a_conf, int a_arityInitial, int a_arityMin, int a_arityMax, Class a_returnType, int a_subReturnType) throws InvalidConfigurationException
CommandDynamicArity (final GPConfiguration a_conf, int a_arityInitial, int a_arityMin, int a_arityMax, Class a_returnType, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException
void dynamizeArity ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.2 $`
Additional Inherited Members
Detailed Description
Abstract base class for GP-commands with a dynamic number of children.
Author
Klaus Meffert
Since
3.4
Definition at line 21 of file CommandDynamicArity.java.
Constructor & Destructor Documentation
org.jgap.gp.CommandDynamicArity.CommandDynamicArity () throws Exception [inline]
Default constructor, only for dynamic instantiation.
Exceptions
Exception
Author
Klaus Meffert
Since
3.4
Definition at line 34 of file CommandDynamicArity.java.
org.jgap.gp.CommandDynamicArity.CommandDynamicArity (final GPConfiguration a_conf, int a_arityInitial, int a_arityMin, int a_arityMax, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 39 of file CommandDynamicArity.java.
org.jgap.gp.CommandDynamicArity.CommandDynamicArity (final GPConfiguration a_conf, int a_arityInitial, int a_arityMin, int a_arityMax, Class a_returnType, int a_subReturnType) throws InvalidConfigurationException [inline]
Definition at line 45 of file CommandDynamicArity.java.
org.jgap.gp.CommandDynamicArity.CommandDynamicArity (final GPConfiguration a_conf, int a_arityInitial, int a_arityMin, int a_arityMax, Class a_returnType, int a_subReturnType, int[] a_subChildTypes) throws InvalidConfigurationException [inline]
Allows specifying a sub return type and sub child types.
Parameters
a_conf the configuration to use
a_arityInitial the number of children of the node
a_arityMin the minimum arity allowed/required
a_arityMax the maximum arity allowed/required
a_returnType type of the return value of the node
a_subReturnType sub type of the return type, optional usage
a_subChildTypes sub type of a child, optional usage
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.4
Definition at line 68 of file CommandDynamicArity.java.
References org.jgap.gp.CommandGene.setArityMax(), and org.jgap.gp.CommandGene.setArityMin().
Member Function Documentation
void org.jgap.gp.CommandDynamicArity.dynamizeArity () [inline]
Adaptation of the arity so that it represents a value within the interval [m_arityMin, m_arityMax].
Author
Klaus Meffert
Since
3.4
Definition at line 96 of file CommandDynamicArity.java.
References org.jgap.gp.CommandGene.getArityMax(), org.jgap.gp.CommandGene.getArityMin(), org.jgap.gp.CommandGene.getGPConfiguration(), and org.jgap.gp.CommandGene.setArity().
Member Data Documentation
final String org.jgap.gp.CommandDynamicArity.CVS_REVISION = `$Revision: 1.2 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file CommandDynamicArity.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/CommandDynamicArity.java