org.jgap.DeltaFitnessEvaluator Class Reference
Public Member Functions
boolean isFitter (final double a_fitness_value1, final double a_fitness_value2)
boolean isFitter (IChromosome a_chrom1, IChromosome a_chrom2)
Object clone ()
int compareTo (Object a_other)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.11 $`
Additional Inherited Members
Detailed Description
An implementation of a fitness evaluator interpreting the fitness as delta value.
Author
Klaus Meffert
Since
2.0
Definition at line 21 of file DeltaFitnessEvaluator.java.
Member Function Documentation
Object org.jgap.DeltaFitnessEvaluator.clone () [inline]
Returns
deep clone of this instance
Author
Klaus Meffert
Since
3.2
Implements org.jgap.util.ICloneable.
Definition at line 63 of file DeltaFitnessEvaluator.java.
int org.jgap.DeltaFitnessEvaluator.compareTo (Object a_other) [inline]
Parameters
a_other sic
Returns
as always
Author
Klaus Meffert
Since
3.2
Definition at line 74 of file DeltaFitnessEvaluator.java.
boolean org.jgap.DeltaFitnessEvaluator.isFitter (final double a_fitness_value1, final double a_fitness_value2) [inline]
Compares the first given fitness value with the second and returns true if the first one is smaller than the second one. Otherwise returns false
Parameters
a_fitness_value1 first fitness value
a_fitness_value2 second fitness value
Returns
true: first fitness value smaller than second
Since
2.0 (until 1.1: input types int)
Definition at line 35 of file DeltaFitnessEvaluator.java.
Referenced by org.jgap.DeltaFitnessEvaluator.isFitter().
boolean org.jgap.DeltaFitnessEvaluator.isFitter (IChromosome a_chrom1, IChromosome a_chrom2) [inline]
Implements org.jgap.FitnessEvaluator.
Definition at line 53 of file DeltaFitnessEvaluator.java.
References org.jgap.IChromosome.getFitnessValue(), and org.jgap.DeltaFitnessEvaluator.isFitter().
Member Data Documentation
final String org.jgap.DeltaFitnessEvaluator.CVS_REVISION = `$Revision: 1.11 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file DeltaFitnessEvaluator.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/DeltaFitnessEvaluator.java