examples.constraint.SampleFitnessFunction Class Reference
Public Member Functions
SampleFitnessFunction (int a_targetAmount)
double evaluate (IChromosome a_subject)
Static Public Member Functions
static double amountOfChange (IChromosome a_potentialSolution)
static int getNumberOfCoinsAtGene (IChromosome a_potentialSolution, int a_position)
static int getTotalNumberOfCoins (IChromosome a_potentialsolution)
Static Public Attributes
static final int MAX_BOUND = 4000
Protected Member Functions
double changeDifferenceBonus (double a_maxFitness, int a_changeDifference)
double computeCoinNumberPenalty (double a_maxFitness, int a_coins)
Private Attributes
final int m_targetAmount
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.1 $`
Detailed Description
Sample fitness function for the MakeChange example.
Author
Klaus Meffert
Since
3.6.2
Definition at line 21 of file SampleFitnessFunction.java.
Constructor & Destructor Documentation
examples.constraint.SampleFitnessFunction.SampleFitnessFunction (int a_targetAmount) [inline]
Definition at line 30 of file SampleFitnessFunction.java.
References examples.constraint.SampleFitnessFunction.m_targetAmount, and examples.constraint.SampleFitnessFunction.MAX_BOUND.
Member Function Documentation
static double examples.constraint.SampleFitnessFunction.amountOfChange (IChromosome a_potentialSolution) [inline], [static]
Calculates the total amount of change (in cents) represented by the given potential solution and returns that amount.
Parameters
a_potentialSolution the potential solution to evaluate
Returns
The total amount of change (in cents) represented by the given solution
Author
Klaus Meffert
Since
3.6.2
Definition at line 161 of file SampleFitnessFunction.java.
References examples.constraint.SampleFitnessFunction.getNumberOfCoinsAtGene().
Referenced by examples.constraint.SampleFitnessFunction.evaluate().
double examples.constraint.SampleFitnessFunction.changeDifferenceBonus (double a_maxFitness, int a_changeDifference) [inline], [protected]
Bonus calculation of fitness value.
Parameters
a_maxFitness maximum fitness value appliable
a_changeDifference change difference in coins for the coins problem
Returns
bonus for given change difference
Author
Klaus Meffert
Since
2.3
Definition at line 109 of file SampleFitnessFunction.java.
Referenced by examples.constraint.SampleFitnessFunction.evaluate().
double examples.constraint.SampleFitnessFunction.computeCoinNumberPenalty (double a_maxFitness, int a_coins) [inline], [protected]
Calculates the penalty to apply to the fitness value based on the ammount of coins in the solution
Parameters
a_maxFitness maximum fitness value allowed
a_coins number of coins in the solution
Returns
penalty for the fitness value base on the number of coins
Author
John Serri
Since
2.2
Definition at line 137 of file SampleFitnessFunction.java.
Referenced by examples.constraint.SampleFitnessFunction.evaluate().
double examples.constraint.SampleFitnessFunction.evaluate (IChromosome a_subject) [inline]
Determine the fitness of the given Chromosome instance. The higher the return value, the more fit the instance. This method should always return the same fitness value for two equivalent Chromosome instances.
Parameters
a_subject the Chromosome instance to evaluate
Returns
positive double reflecting the fitness rating of the given Chromosome
Since
2.0 (until 1.1: return type int)
Author
Neil Rotstan, Klaus Meffert, John Serri
Definition at line 50 of file SampleFitnessFunction.java.
References examples.constraint.SampleFitnessFunction.amountOfChange(), examples.constraint.SampleFitnessFunction.changeDifferenceBonus(), examples.constraint.SampleFitnessFunction.computeCoinNumberPenalty(), examples.constraint.SampleFitnessFunction.getTotalNumberOfCoins(), examples.constraint.SampleFitnessFunction.m_targetAmount, and examples.constraint.SampleFitnessFunction.MAX_BOUND.
static int examples.constraint.SampleFitnessFunction.getNumberOfCoinsAtGene (IChromosome a_potentialSolution, int a_position) [inline], [static]
Retrieves the number of coins represented by the given potential solution at the given gene position.
Parameters
a_potentialSolution the potential solution to evaluate
a_position the gene position to evaluate
Returns
the number of coins represented by the potential solution at the given gene position
Author
Klaus Meffert
Since
3.6.2
Definition at line 182 of file SampleFitnessFunction.java.
Referenced by examples.constraint.SampleFitnessFunction.amountOfChange(), and examples.constraint.SampleFitnessFunction.getTotalNumberOfCoins().
static int examples.constraint.SampleFitnessFunction.getTotalNumberOfCoins (IChromosome a_potentialsolution) [inline], [static]
Returns the total number of coins represented by all of the genes in the given potential solution.
Parameters
a_potentialsolution the potential solution to evaluate
Returns
total number of coins represented by the given Chromosome
Author
Klaus Meffert
Since
3.6.2
Definition at line 199 of file SampleFitnessFunction.java.
References examples.constraint.SampleFitnessFunction.getNumberOfCoinsAtGene().
Referenced by examples.constraint.SampleFitnessFunction.evaluate().
Member Data Documentation
final String examples.constraint.SampleFitnessFunction.CVS_REVISION = `$Revision: 1.1 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file SampleFitnessFunction.java.
final int examples.constraint.SampleFitnessFunction.m_targetAmount [private]
Definition at line 26 of file SampleFitnessFunction.java.
Referenced by examples.constraint.SampleFitnessFunction.evaluate(), and examples.constraint.SampleFitnessFunction.SampleFitnessFunction().
final int examples.constraint.SampleFitnessFunction.MAX_BOUND = 4000 [static]
Definition at line 28 of file SampleFitnessFunction.java.
Referenced by examples.constraint.SampleFitnessFunction.evaluate(), and examples.constraint.SampleFitnessFunction.SampleFitnessFunction().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/constraint/SampleFitnessFunction.java