org.jgap.impl.CauchyRandomGeneratorTest Class Reference
Public Member Functions
void testGeneral ()
void testNextCauchy_0 () throws Exception
void testGetCauchyStdDeviation_0 ()
void testNextInt_0 ()
void testSerialize_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.11 $`
Additional Inherited Members
Detailed Description
Tests the CauchyRandomGenerator class.
Author
Klaus Meffert
Since
1.1
Definition at line 23 of file CauchyRandomGeneratorTest.java.
Member Function Documentation
static Test org.jgap.impl.CauchyRandomGeneratorTest.suite () [inline], [static]
Definition at line 28 of file CauchyRandomGeneratorTest.java.
void org.jgap.impl.CauchyRandomGeneratorTest.testGeneral () [inline]
Check if construction and calculation possible in general.
Author
Klaus Meffert
Definition at line 38 of file CauchyRandomGeneratorTest.java.
void org.jgap.impl.CauchyRandomGeneratorTest.testGetCauchyStdDeviation_0 () [inline]
Author
Klaus Meffert
Since
2.2
Definition at line 64 of file CauchyRandomGeneratorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.DELTA, and org.jgap.impl.CauchyRandomGenerator.getCauchyStandardDeviation().
void org.jgap.impl.CauchyRandomGeneratorTest.testNextCauchy_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 53 of file CauchyRandomGeneratorTest.java.
void org.jgap.impl.CauchyRandomGeneratorTest.testNextInt_0 () [inline]
Author
Klaus Meffert
Since
2.6
Definition at line 74 of file CauchyRandomGeneratorTest.java.
References org.jgap.JGAPTestCase.assertEquals().
void org.jgap.impl.CauchyRandomGeneratorTest.testSerialize_0 () throws Exception [inline]
Tests serializability capabilities.
Exceptions
Exception
Author
Klaus Meffert
Since
3.01
Todo
Todo fix test as Java 5 uses java.util.concurrent.AtomicLong instead of sun.misc.AtomicLong
Definition at line 91 of file CauchyRandomGeneratorTest.java.
References org.jgap.JGAPTestCase.doSerialize(), and org.jgap.JGAPTestCase.privateAccessor.
Member Data Documentation
final String org.jgap.impl.CauchyRandomGeneratorTest.CVS_REVISION = `$Revision: 1.11 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file CauchyRandomGeneratorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/CauchyRandomGeneratorTest.java