org.jgap.gp.impl.BranchTypingCross Class Reference
Public Member Functions
BranchTypingCross (GPConfiguration a_config)
BranchTypingCross (GPConfiguration a_config, boolean a_simpleChromosomeSelection)
IGPProgram[] operate (final IGPProgram a_i1, final IGPProgram a_i2)
int compareTo (Object a_other)
boolean equals (Object a_other)
Object clone ()
Protected Member Functions
ProgramChromosome[] doCross (ProgramChromosome a_c0, ProgramChromosome a_c1) throws InvalidConfigurationException
Private Attributes
boolean m_simpleChromosomeSelection
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.19 $`
Detailed Description
Crossing over for GP ProgramChromosomes.
Author
Klaus Meffert
Since
3.0
Definition at line 22 of file BranchTypingCross.java.
Constructor & Destructor Documentation
org.jgap.gp.impl.BranchTypingCross.BranchTypingCross (GPConfiguration a_config) [inline]
Standard constructor.
Parameters
a_config the configuration to use
Definition at line 34 of file BranchTypingCross.java.
Referenced by org.jgap.gp.impl.BranchTypingCross.clone(), org.jgap.gp.impl.BranchTypingCross.compareTo(), and org.jgap.gp.impl.BranchTypingCross.equals().
org.jgap.gp.impl.BranchTypingCross.BranchTypingCross (GPConfiguration a_config, boolean a_simpleChromosomeSelection) [inline]
Parameters
a_config the configuration to use
a_simpleChromosomeSelection true: plainly select chromosomes, false: select chromosomes proportionally to their size (=number of nodes within a chromosome)
Author
Klaus Meffert
Since
3.4
Definition at line 48 of file BranchTypingCross.java.
References org.jgap.gp.impl.BranchTypingCross.m_simpleChromosomeSelection.
Member Function Documentation
Object org.jgap.gp.impl.BranchTypingCross.clone () [inline]
Returns
deep clone of this instance
Author
Klaus Meffert
Since
3.2
Definition at line 347 of file BranchTypingCross.java.
References org.jgap.gp.impl.BranchTypingCross.BranchTypingCross(), and org.jgap.gp.CrossMethod.getConfiguration().
int org.jgap.gp.impl.BranchTypingCross.compareTo (Object a_other) [inline]
The compareTo-method.
Parameters
a_other the other object to compare
Returns
0 or 1 in this case, as BranchTypingCross objects keep no state
Author
Klaus Meffert
Since
3.0
Definition at line 309 of file BranchTypingCross.java.
References org.jgap.gp.impl.BranchTypingCross.BranchTypingCross().
ProgramChromosome [] org.jgap.gp.impl.BranchTypingCross.doCross (ProgramChromosome a_c0, ProgramChromosome a_c1) throws InvalidConfigurationException [inline], [protected]
Crosses two chromsomes using branch-typing. A random point in the first chromosome is chosen, with a certain probability it will be a function and with a rest probability it will be a terminal. A random point in the second chromosome is chosen using the same probability distribution, but the node chosen must be of the same type as the chosen node in the first chromosome. If a suitable point in the second chromosome couldn't be found then the chromosomes are not crossed. If a resulting chromosome's depth is larger than the maximum crossover depth then that chromosome is simply copied from the original rather than crossed.
Parameters
a_c0 the first chromosome to cross
a_c1 the second chromosome to cross
Returns
an array of the two resulting chromosomes
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Todo
Todo solve in general
Definition at line 158 of file BranchTypingCross.java.
References org.jgap.gp.CrossMethod.getConfiguration(), org.jgap.RandomGenerator.nextDouble(), and org.jgap.RandomGenerator.nextFloat().
Referenced by org.jgap.gp.impl.BranchTypingCross.operate().
boolean org.jgap.gp.impl.BranchTypingCross.equals (Object a_other) [inline]
The equals-method.
Parameters
a_other the other object to compare
Returns
always true for non-null BranchTypingCross objects because they keep no state
Author
Klaus Meffert
Since
3.0
Definition at line 327 of file BranchTypingCross.java.
References org.jgap.gp.impl.BranchTypingCross.BranchTypingCross().
IGPProgram [] org.jgap.gp.impl.BranchTypingCross.operate (final IGPProgram a_i1, final IGPProgram a_i2) [inline], [virtual]
Crosses two individuals. A random chromosome is chosen for crossing based on the proportion of nodes in each chromosome in the first individual.
Parameters
a_i1 the first individual to cross
a_i2 the second individual to cross
Returns
an array of the two resulting individuals
Author
Klaus Meffert
Since
3.0
Todo
Todo try to ensure uniqueness for unique commands: after selecting first node, check if there is a unique node in the sub tree. If so, check if it appears in the sub tree of the second node.
Implements org.jgap.gp.CrossMethod.
Definition at line 65 of file BranchTypingCross.java.
References org.jgap.gp.impl.BranchTypingCross.doCross(), org.jgap.gp.IGPProgram.getChromosome(), org.jgap.gp.CrossMethod.getConfiguration(), org.jgap.gp.impl.BranchTypingCross.m_simpleChromosomeSelection, and org.jgap.gp.IGPProgram.size().
Member Data Documentation
final String org.jgap.gp.impl.BranchTypingCross.CVS_REVISION = `$Revision: 1.19 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file BranchTypingCross.java.
boolean org.jgap.gp.impl.BranchTypingCross.m_simpleChromosomeSelection [private]
Definition at line 27 of file BranchTypingCross.java.
Referenced by org.jgap.gp.impl.BranchTypingCross.BranchTypingCross(), and org.jgap.gp.impl.BranchTypingCross.operate().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/impl/BranchTypingCross.java