org.jgap.impl.FittestPopulationMergerTest Class Reference
Public Member Functions
void testConstruct_0 ()
void testMergePopulations_0 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.10 $`
Additional Inherited Members
Detailed Description
Tests the FittestPopulationMerger class.
Author
Klaus Meffert
Since
2.0
Definition at line 22 of file FittestPopulationMergerTest.java.
Member Function Documentation
static Test org.jgap.impl.FittestPopulationMergerTest.suite () [inline], [static]
Definition at line 27 of file FittestPopulationMergerTest.java.
void org.jgap.impl.FittestPopulationMergerTest.testConstruct_0 () [inline]
Test if construction possible
Author
Klaus Meffert
Since
2.1
Definition at line 38 of file FittestPopulationMergerTest.java.
void org.jgap.impl.FittestPopulationMergerTest.testMergePopulations_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
2.1
Definition at line 48 of file FittestPopulationMergerTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, org.jgap.JGAPTestCase.DELTA, org.jgap.Population.getChromosome(), and org.jgap.Population.size().
Member Data Documentation
final String org.jgap.impl.FittestPopulationMergerTest.CVS_REVISION = `$Revision: 1.10 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file FittestPopulationMergerTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/FittestPopulationMergerTest.java