org.jgap.audit.KeyedValues Class Reference
Public Member Functions
KeyedValues ()
int size ()
Number getValue (final int a_index)
Comparable getKey (final int a_index)
int getIndex (final Comparable a_key)
List getKeys ()
Number getValue (final Comparable a_key)
void setValue (final Comparable a_key, final Number a_value)
boolean equals (final Object a_obj)
int hashCode ()
Object clone ()
Private Attributes
List m_data
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.7 $`
Additional Inherited Members
Detailed Description
A collection of (key, value) tupels
Author
Klaus Meffert
Since
2.3
Definition at line 22 of file KeyedValues.java.
Constructor & Destructor Documentation
org.jgap.audit.KeyedValues.KeyedValues () [inline]
Creates a new collection (initially empty).
Author
Klaus Meffert
Since
2.3
Definition at line 36 of file KeyedValues.java.
References org.jgap.audit.KeyedValues.m_data.
Referenced by org.jgap.audit.KeyedValues.clone(), and org.jgap.audit.KeyedValues.equals().
Member Function Documentation
Object org.jgap.audit.KeyedValues.clone () [inline]
Returns
clone of the current instance
Author
Klaus Meffert
Since
2.3
Implements org.jgap.util.ICloneable.
Definition at line 247 of file KeyedValues.java.
References org.jgap.audit.KeyedValues.KeyedValues().
Referenced by org.jgap.audit.KeyedValuesTest.testClone_0().
boolean org.jgap.audit.KeyedValues.equals (final Object a_obj) [inline]
Tests if this object is equal to another
Parameters
a_obj the other object
Returns
true: this object is equal to the other one
Author
Klaus Meffert
Since
2.3
Definition at line 189 of file KeyedValues.java.
References org.jgap.audit.KeyedValues.getKey(), org.jgap.audit.KeyedValues.getValue(), org.jgap.audit.KeyedValues.KeyedValues(), and org.jgap.audit.KeyedValues.size().
Referenced by org.jgap.audit.KeyedValuesTest.testEquals_0(), and org.jgap.audit.KeyedValuesTest.testEquals_1().
int org.jgap.audit.KeyedValues.getIndex (final Comparable a_key) [inline]
Parameters
a_key the key to search for
Returns
index for a given key or -1 if the key is not found
Author
Klaus Meffert
Since
2.3
Definition at line 97 of file KeyedValues.java.
References org.jgap.audit.KeyedValue.getKey().
Referenced by org.jgap.audit.KeyedValues.getValue(), org.jgap.audit.KeyedValues.setValue(), org.jgap.audit.KeyedValuesTest.testGetIndex_0(), org.jgap.audit.KeyedValuesTest.testGetIndex_1(), and org.jgap.audit.KeyedValuesTest.testGetIndex_2().
Comparable org.jgap.audit.KeyedValues.getKey (final int a_index) [inline]
Parameters
a_index the item index to retrieve the key for, starting at 0
Returns
the row key for item at given index
Author
Klaus Meffert
Since
2.3
Definition at line 77 of file KeyedValues.java.
References org.jgap.audit.KeyedValues.m_data.
Referenced by org.jgap.audit.KeyedValues.equals(), org.jgap.audit.KeyedValuesTest.testGetKey_1(), org.jgap.audit.KeyedValuesTest.testGetKey_2(), and org.jgap.audit.KeyedValuesTest.testSetValue_0().
List org.jgap.audit.KeyedValues.getKeys () [inline]
Returns the keys for the values in the collection
Returns
The keys (never null)
Author
Klaus Meffert
Since
2.3
Definition at line 126 of file KeyedValues.java.
Number org.jgap.audit.KeyedValues.getValue (final int a_index) [inline]
Parameters
a_index the index of the item to return the value for
Returns
the value at given index
Author
Klaus Meffert
Since
2.3
Definition at line 57 of file KeyedValues.java.
References org.jgap.audit.KeyedValues.m_data.
Referenced by org.jgap.audit.KeyedValues.equals(), org.jgap.audit.KeyedValues.getValue(), org.jgap.audit.KeyedValuesTest.testGetValue_0(), org.jgap.audit.KeyedValuesTest.testGetValue_2(), org.jgap.audit.KeyedValuesTest.testGetValue_3(), org.jgap.audit.KeyedValuesTest.testSetValue_0(), and org.jgap.audit.KeyedValuesTest.testSetValue_1().
Number org.jgap.audit.KeyedValues.getValue (final Comparable a_key) [inline]
Returns the value for a given key. For unknown keys, null is returned
Parameters
a_key the key
Returns
the value for the key
Author
Klaus Meffert
Since
2.3
Definition at line 146 of file KeyedValues.java.
References org.jgap.audit.KeyedValues.getIndex(), and org.jgap.audit.KeyedValues.getValue().
int org.jgap.audit.KeyedValues.hashCode () [inline]
Returns
hash code of the instance
Author
Klaus Meffert
Since
2.3
Definition at line 232 of file KeyedValues.java.
References org.jgap.audit.KeyedValues.m_data.
Referenced by org.jgap.audit.KeyedValuesTest.testConstruct_0().
void org.jgap.audit.KeyedValues.setValue (final Comparable a_key, final Number a_value) [inline]
Updates an existing value, or adds a new value to the collection
Parameters
a_key the key
a_value the value
Author
Klaus Meffert
Since
2.3
Definition at line 167 of file KeyedValues.java.
References org.jgap.audit.KeyedValues.getIndex(), and org.jgap.audit.KeyedValues.m_data.
int org.jgap.audit.KeyedValues.size () [inline]
Returns
number of items in the collection
Author
Klaus Meffert
Since
2.3
Definition at line 46 of file KeyedValues.java.
Referenced by org.jgap.audit.KeyedValues.equals(), and org.jgap.audit.KeyedValuesTest.testConstruct_0().
Member Data Documentation
final String org.jgap.audit.KeyedValues.CVS_REVISION = `$Revision: 1.7 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 25 of file KeyedValues.java.
List org.jgap.audit.KeyedValues.m_data [private]
Data storage
Definition at line 28 of file KeyedValues.java.
Referenced by org.jgap.audit.KeyedValues.getKey(), org.jgap.audit.KeyedValues.getValue(), org.jgap.audit.KeyedValues.hashCode(), org.jgap.audit.KeyedValues.KeyedValues(), and org.jgap.audit.KeyedValues.setValue().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/audit/KeyedValues.java