org.jgap.gp.function.Max Class Reference
Public Member Functions
Max (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException
String toString ()
String getName ()
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Additional Inherited Members
Detailed Description
Returns the bigger of two values.
Author
Klaus Meffert
Since
3.3.4
Definition at line 23 of file Max.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Max.Max (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 28 of file Max.java.
Referenced by org.jgap.gp.function.Max.clone().
Member Function Documentation
Object org.jgap.gp.function.Max.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 67 of file Max.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.function.Max.Max().
double org.jgap.gp.function.Max.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 53 of file Max.java.
float org.jgap.gp.function.Max.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 47 of file Max.java.
String org.jgap.gp.function.Max.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.3.4
Definition at line 43 of file Max.java.
String org.jgap.gp.function.Max.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 33 of file Max.java.
Member Data Documentation
final String org.jgap.gp.function.Max.CVS_REVISION = `$Revision: 1.4 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file Max.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Max.java