examples.gp.island.IslandGPThread Class Reference
Classes
class SimpleFitnessFunction
Public Member Functions
GPConfiguration createConfiguration (String a_threadKey, int a_popSize) throws Exception
GPGenotype create () throws InvalidConfigurationException
void run ()
void outputBestSolution ()
boolean isFinished ()
boolean isLocked ()
void setLocked ()
void releaseLocked ()
IGPProgram getBestSolution ()
GPPopulation getPopulation ()
Static Public Member Functions
static IslandGPThread newInstance (int nextNumber, int popSize) throws Exception
Static Public Attributes
static boolean locked = false
Static Protected Attributes
static Variable vx
Private Member Functions
IslandGPThread (int nextNumber) throws Exception
Private Attributes
GPGenotype gen
int m_nextNumber
IGPProgram m_best
boolean m_finished
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.5 $`
static GPConfiguration config
Additional Inherited Members
Detailed Description
Simple GP example of an island thread. It utilizes the former example class SimpleExample in the gp package for reasons of simplicity.
Author
Klaus Meffert
Since
3.6
Definition at line 25 of file IslandGPThread.java.
Constructor & Destructor Documentation
examples.gp.island.IslandGPThread.IslandGPThread (int nextNumber) throws Exception [inline], [private]
Definition at line 67 of file IslandGPThread.java.
Referenced by examples.gp.island.IslandGPThread.newInstance().
Member Function Documentation
GPGenotype examples.gp.island.IslandGPThread.create () throws InvalidConfigurationException [inline], [virtual]
Returns
newly created GPGenotype
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0
Implements org.jgap.gp.GPProblem.
Definition at line 83 of file IslandGPThread.java.
References org.jgap.gp.CommandGene.BooleanClass, org.jgap.gp.GPProblem.getGPConfiguration(), org.jgap.gp.CommandGene.IntegerClass, and examples.gp.island.IslandGPThread.vx.
GPConfiguration examples.gp.island.IslandGPThread.createConfiguration (String a_threadKey, int a_popSize) throws Exception [inline]
Definition at line 42 of file IslandGPThread.java.
References examples.gp.island.IslandGPThread.config, and org.jgap.gp.impl.GPConfiguration.newInstanceGP().
IGPProgram examples.gp.island.IslandGPThread.getBestSolution () [inline]
Definition at line 205 of file IslandGPThread.java.
References examples.gp.island.IslandGPThread.m_best, and examples.gp.island.IslandGPThread.m_finished.
GPPopulation examples.gp.island.IslandGPThread.getPopulation () [inline]
Definition at line 212 of file IslandGPThread.java.
boolean examples.gp.island.IslandGPThread.isFinished () [inline]
Definition at line 189 of file IslandGPThread.java.
References examples.gp.island.IslandGPThread.m_finished.
Referenced by examples.gp.island.IslandGPExample.start().
boolean examples.gp.island.IslandGPThread.isLocked () [inline]
Definition at line 193 of file IslandGPThread.java.
References examples.gp.island.IslandGPThread.locked.
Referenced by examples.gp.island.IslandGPExample.start().
static IslandGPThread examples.gp.island.IslandGPThread.newInstance (int nextNumber, int popSize) throws Exception [inline], [static]
Definition at line 71 of file IslandGPThread.java.
References examples.gp.island.IslandGPThread.config, and examples.gp.island.IslandGPThread.IslandGPThread().
void examples.gp.island.IslandGPThread.outputBestSolution () [inline]
Output the currently best solution for the current thread.
Definition at line 177 of file IslandGPThread.java.
References examples.gp.island.IslandGPThread.m_best, examples.gp.island.IslandGPThread.m_nextNumber, and org.jgap.gp.IGPProgram.toStringNorm().
Referenced by examples.gp.island.IslandGPThread.run().
void examples.gp.island.IslandGPThread.releaseLocked () [inline]
Definition at line 201 of file IslandGPThread.java.
References examples.gp.island.IslandGPThread.locked.
void examples.gp.island.IslandGPThread.run () [inline]
Definition at line 128 of file IslandGPThread.java.
References org.jgap.util.ICloneable.clone(), org.jgap.gp.IGPProgram.getFitnessValue(), examples.gp.island.IslandGPThread.locked, examples.gp.island.IslandGPThread.m_best, examples.gp.island.IslandGPThread.m_finished, examples.gp.island.IslandGPThread.m_nextNumber, and examples.gp.island.IslandGPThread.outputBestSolution().
void examples.gp.island.IslandGPThread.setLocked () [inline]
Definition at line 197 of file IslandGPThread.java.
References examples.gp.island.IslandGPThread.locked.
Member Data Documentation
GPConfiguration examples.gp.island.IslandGPThread.config [static], [private]
Definition at line 38 of file IslandGPThread.java.
Referenced by examples.gp.island.IslandGPThread.createConfiguration(), and examples.gp.island.IslandGPThread.newInstance().
final String examples.gp.island.IslandGPThread.CVS_REVISION = `$Revision: 1.5 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file IslandGPThread.java.
GPGenotype examples.gp.island.IslandGPThread.gen [private]
Definition at line 30 of file IslandGPThread.java.
boolean examples.gp.island.IslandGPThread.locked = false [static]
Definition at line 126 of file IslandGPThread.java.
Referenced by examples.gp.island.IslandGPThread.isLocked(), examples.gp.island.IslandGPThread.releaseLocked(), examples.gp.island.IslandGPThread.run(), and examples.gp.island.IslandGPThread.setLocked().
IGPProgram examples.gp.island.IslandGPThread.m_best [private]
Definition at line 34 of file IslandGPThread.java.
Referenced by examples.gp.island.IslandGPThread.getBestSolution(), examples.gp.island.IslandGPThread.outputBestSolution(), and examples.gp.island.IslandGPThread.run().
boolean examples.gp.island.IslandGPThread.m_finished [private]
Definition at line 36 of file IslandGPThread.java.
Referenced by examples.gp.island.IslandGPThread.getBestSolution(), examples.gp.island.IslandGPThread.isFinished(), and examples.gp.island.IslandGPThread.run().
int examples.gp.island.IslandGPThread.m_nextNumber [private]
Definition at line 32 of file IslandGPThread.java.
Referenced by examples.gp.island.IslandGPThread.outputBestSolution(), and examples.gp.island.IslandGPThread.run().
Variable examples.gp.island.IslandGPThread.vx [static], [protected]
Definition at line 40 of file IslandGPThread.java.
Referenced by examples.gp.island.IslandGPThread.create().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/gp/island/IslandGPThread.java