org.jgap.impl.GreedyCrossover Class Reference
Public Member Functions
GreedyCrossover () throws InvalidConfigurationException
GreedyCrossover (Configuration a_configuration) throws InvalidConfigurationException
double distance (final Object a_from, final Object a_to)
void operate (final Population a_population, final List a_candidateChromosomes)
void operate (final IChromosome a_firstMate, final IChromosome a_secondMate)
void setStartOffset (int a_offset)
int getStartOffset ()
int compareTo (final Object a_other)
Protected Member Functions
Gene[] operate (final Gene[] a_g1, final Gene[] a_g2)
Gene findNext (final Gene[] a_g, final Gene a_x)
Private Attributes
int m_startOffset = 1
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.30 $`
Additional Inherited Members
Detailed Description
The Greedy Crossover is a specific type of crossover. It can only be is applied if
All genes in the chromosome are different and
The set of genes for both chromosomes is identical and only their order in the chromosome can vary.
After the GreedyCrossover, these two conditions always remain true, so it can be applied again and again.
The algorithm throws an assertion error if the two initial chromosomes does not satisfy these conditions.
Greedy crossover can be best explained in the terms of the Traveling Salesman Problem:
The algorithm selects the first city of one parent, compares the cities leaving that city in both parents, and chooses the closer one to extend the tour. If one city has already appeared in the tour, we choose the other city. If both cities have already appeared, we randomly select a non-selected city.
See J. Grefenstette, R. Gopal, R. Rosmaita, and D. Gucht. Genetic algorithms for the traveling salesman problem. In Proceedings of the Second International Conference on Genetic Algorithms. Lawrence Eribaum Associates, Mahwah, NJ, 1985. and also Sushil J. Louis & Gong Li}
Author
Audrius Meskauskas
<font size=`-1`>Neil Rotstan, Klaus Meffert (reused code from CrossoverOperator)</font>
Since
2.0
Definition at line 55 of file GreedyCrossover.java.
Constructor & Destructor Documentation
org.jgap.impl.GreedyCrossover.GreedyCrossover () throws InvalidConfigurationException [inline]
Default constructor for dynamic instantiation.
Attention: The configuration used is the one set with the static method Genotype.setConfiguration.
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.6
3.0 (since 2.0 without a_configuration)
Definition at line 76 of file GreedyCrossover.java.
References org.jgap.Genotype.getStaticConfiguration().
Referenced by org.jgap.impl.GreedyCrossover.compareTo().
org.jgap.impl.GreedyCrossover.GreedyCrossover (Configuration a_configuration) throws InvalidConfigurationException [inline]
Using the given configuration.
Parameters
a_configuration the configuration to use
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
3.0 (since 2.6 without a_configuration)
Definition at line 90 of file GreedyCrossover.java.
Member Function Documentation
int org.jgap.impl.GreedyCrossover.compareTo (final Object a_other) [inline]
Compares the given GeneticOperator to this GeneticOperator.
Parameters
a_other the instance against which to compare this instance
Returns
a negative number if this instance is `less than` the given instance, zero if they are equal to each other, and a positive number if this is `greater than` the given instance
Author
Klaus Meffert
Since
2.6
Definition at line 306 of file GreedyCrossover.java.
References org.jgap.impl.GreedyCrossover.getStartOffset(), and org.jgap.impl.GreedyCrossover.GreedyCrossover().
Referenced by org.jgap.impl.GreedyCrossoverTest.testCompareTo_0().
double org.jgap.impl.GreedyCrossover.distance (final Object a_from, final Object a_to) [inline]
Compute the distance between `cities`, indicated by these two given genes. The default method expects the genes to be IntegerGene's and returns their absolute difference, that makes sense only for tests.
Parameters
a_from Object
a_to Object
Returns
distance between the two given cities
Definition at line 105 of file GreedyCrossover.java.
References org.jgap.impl.IntegerGene.intValue().
Referenced by org.jgap.impl.GreedyCrossover.operate().
Gene org.jgap.impl.GreedyCrossover.findNext (final Gene[] a_g, final Gene a_x) [inline], [protected]
Definition at line 262 of file GreedyCrossover.java.
References org.jgap.BaseGeneticOperator.equals(), and org.jgap.impl.GreedyCrossover.m_startOffset.
Referenced by org.jgap.impl.GreedyCrossover.operate().
int org.jgap.impl.GreedyCrossover.getStartOffset () [inline]
Gets a number of genes at the start of chromosome, that are excluded from the swapping. In the Salesman task, the first city in the list should (where the salesman leaves from) probably should not change as it is part of the list. The default value is 1.
Returns
the start offset used
Definition at line 291 of file GreedyCrossover.java.
References org.jgap.impl.GreedyCrossover.m_startOffset.
Referenced by org.jgap.impl.GreedyCrossover.compareTo(), and org.jgap.impl.GreedyCrossoverTest.testStartoffset_0().
void org.jgap.impl.GreedyCrossover.operate (final Population a_population, final List a_candidateChromosomes) [inline]
The operate method will be invoked on each of the genetic operators referenced by the current Configuration object during the evolution phase. Operators are given an opportunity to run in the order that they are added to the Configuration. Implementations of this method may reference the population of Chromosomes as it was at the beginning of the evolutionary phase and/or they may instead reference the candidate Chromosomes, which are the results of prior genetic operators. In either case, only Chromosomes added to the list of candidate chromosomes will be considered for natural selection.
The parameters a_population and a_candidateChromosomes may refer to the same list of chromosomes for performance issues. Thus would mean an in-place modification. In ealier JGAP versions it was suggested never modifying the input population. Please refer to implementations delivered with JGAP to get a picture of the way non-susceptible in-place modifications are possible. If wrongly done, ConcurrentModificationException could be risen when accessing the population by an iterator in a GeneticOperator. Or, if population.getChromosomes().size() was used inside a loop where chromosomes were added to the input population this could lead to an infinite loop in worst case.
Parameters
a_population the population of chromosomes from the current evolution prior to exposure to any genetic operators. Chromosomes in this array should not be modified. Please, notice, that the call in Genotype.evolve() to the implementations of GeneticOperator overgoes this due to performance issues
a_candidateChromosomes the pool of chromosomes that have been selected for the next evolved population
Author
Neil Rotstan
Klaus Meffert
Since
2.0 (earlier versions referenced the Configuration object)
Implements org.jgap.GeneticOperator.
Definition at line 111 of file GreedyCrossover.java.
References org.jgap.util.ICloneable.clone(), org.jgap.BaseGeneticOperator.getConfiguration(), org.jgap.BaseGeneticOperator.m_monitorActive, and org.jgap.Population.size().
Referenced by org.jgap.impl.GreedyCrossover.operate().
void org.jgap.impl.GreedyCrossover.operate (final IChromosome a_firstMate, final IChromosome a_secondMate) [inline]
Performs a greedy crossover for the two given chromosoms.
Parameters
a_firstMate the first chromosome to crossover on
a_secondMate the second chromosome to crossover on
Exceptions
Error if the gene set in the chromosomes is not identical
Author
Audrius Meskauskas
Since
2.1
Definition at line 155 of file GreedyCrossover.java.
References org.jgap.impl.GreedyCrossover.m_startOffset, and org.jgap.impl.GreedyCrossover.operate().
Gene [] org.jgap.impl.GreedyCrossover.operate (final Gene[] a_g1, final Gene[] a_g2) [inline], [protected]
Definition at line 176 of file GreedyCrossover.java.
References org.jgap.impl.GreedyCrossover.distance(), org.jgap.BaseGeneticOperator.equals(), org.jgap.impl.GreedyCrossover.findNext(), and org.jgap.impl.GreedyCrossover.m_startOffset.
void org.jgap.impl.GreedyCrossover.setStartOffset (int a_offset) [inline]
Sets a number of genes at the start of chromosome, that are excluded from the swapping. In the Salesman task, the first city in the list should (where the salesman leaves from) probably should not change as it is part of the list. The default value is 1.
Parameters
a_offset the start offset to use
Definition at line 279 of file GreedyCrossover.java.
References org.jgap.impl.GreedyCrossover.m_startOffset.
Member Data Documentation
final String org.jgap.impl.GreedyCrossover.CVS_REVISION = `$Revision: 1.30 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 58 of file GreedyCrossover.java.
int org.jgap.impl.GreedyCrossover.m_startOffset = 1 [private]
Definition at line 63 of file GreedyCrossover.java.
Referenced by org.jgap.impl.GreedyCrossover.findNext(), org.jgap.impl.GreedyCrossover.getStartOffset(), org.jgap.impl.GreedyCrossover.operate(), and org.jgap.impl.GreedyCrossover.setStartOffset().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/impl/GreedyCrossover.java