org.jgap.distr.grid.gp.JGAPRequestGP Class Reference
Public Member Functions
JGAPRequestGP (String a_name, String a_id, int a_chunk, IGridConfigurationGP a_config, IWorkerEvolveStrategyGP a_strategy)
JGAPRequestGP (String name, String a_id, int a_chunk, IGridConfigurationGP a_config)
JGAPRequestGP (String a_name, String a_id, int a_chunk, IGridConfigurationGP a_config, GPPopulation a_pop, IWorkerEvolveStrategyGP a_strategy)
JGAPRequestGP (String a_name, String a_id, int a_chunk, IGridConfigurationGP a_config, GPPopulation a_pop)
void setEvolveStrategy (IWorkerEvolveStrategyGP a_evolveStrategy)
IWorkerEvolveStrategyGP getWorkerEvolveStrategy ()
void setWorkerReturnStrategy (IWorkerReturnStrategyGP a_strategy)
IWorkerReturnStrategyGP getWorkerReturnStrategy ()
GridWorkerFeedback getWorkerFeedback ()
void setWorkerFeedback (GridWorkerFeedback a_feedback)
void setGenotypeInitializer (IGenotypeInitializerGP a_initializer)
IGenotypeInitializerGP getGenotypeInitializer ()
void setPopulation (GPPopulation a_pop)
GPConfiguration getConfiguration ()
IGridConfigurationGP getGridConfiguration ()
void setConfiguration (GPConfiguration a_conf)
GPPopulation getPopulation ()
Object clone ()
JGAPRequestGP newInstance (String a_name, String a_id, int a_chunk)
int getChunk ()
MasterInfo getRequesterInfo ()
void setRequesterInfo (MasterInfo a_requesterInfo)
String getID ()
void setRequestDate (Date a_date)
Date getRequestDate ()
void setDescription (String a_descr)
String getDescription ()
double getMinFitness ()
void setMinFitness (double a_minFitness)
void setTitle (String a_title)
String getTitle ()
Private Attributes
IGridConfigurationGP m_config
GPPopulation m_pop
IWorkerEvolveStrategyGP m_evolveStrategy
IWorkerReturnStrategyGP m_returnStrategy
IGenotypeInitializerGP m_genotypeInitializer
GridWorkerFeedback m_workerFeedback
int m_chunk
MasterInfo m_requesterInfo
String m_id
Date m_requestDate
String m_description
double m_minFitness
String m_title
Object m_genericData
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.8 $`
Additional Inherited Members
Detailed Description
An instance that defines a request from which work packages are generated that are sent to workers in the grid.
Author
Klaus Meffert
Since
3.2
Definition at line 27 of file JGAPRequestGP.java.
Constructor & Destructor Documentation
org.jgap.distr.grid.gp.JGAPRequestGP.JGAPRequestGP (String a_name, String a_id, int a_chunk, IGridConfigurationGP a_config, IWorkerEvolveStrategyGP a_strategy) [inline]
Constructor.
Parameters
a_name textual description of request
a_id unique identification of request
a_chunk running index of request chunk, should be unique within an identification
a_config Configuration
a_strategy the strategy to choose for evolution
Author
Klaus Meffert
Since
3.2
Definition at line 73 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_chunk, org.jgap.distr.grid.gp.JGAPRequestGP.m_config, org.jgap.distr.grid.gp.JGAPRequestGP.m_evolveStrategy, and org.jgap.distr.grid.gp.JGAPRequestGP.m_id.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.newInstance().
org.jgap.distr.grid.gp.JGAPRequestGP.JGAPRequestGP (String name, String a_id, int a_chunk, IGridConfigurationGP a_config) [inline]
Constructor.
Parameters
name String
a_id unique identification of request
a_chunk running index of request chunk, should be unique within an identification
a_config Configuration
Author
Klaus Meffert
Since
3.2
Definition at line 95 of file JGAPRequestGP.java.
org.jgap.distr.grid.gp.JGAPRequestGP.JGAPRequestGP (String a_name, String a_id, int a_chunk, IGridConfigurationGP a_config, GPPopulation a_pop, IWorkerEvolveStrategyGP a_strategy) [inline]
Constructor. Allows to specify a preset population with which the genotype will be initialized.
Parameters
a_name textual description of request
a_id unique identification of request
a_chunk running index of request chunk, should be unique within an identification
a_config Configuration
a_pop Population
a_strategy the strategy to choose for evolution
Author
Klaus Meffert
Since
3.2
Definition at line 115 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_pop.
org.jgap.distr.grid.gp.JGAPRequestGP.JGAPRequestGP (String a_name, String a_id, int a_chunk, IGridConfigurationGP a_config, GPPopulation a_pop) [inline]
Constructor. Allows to specify a preset population with which the genotype will be initialized.
Parameters
a_name textual description of request
a_id unique identification of request
a_chunk running index of request chunk, should be unique within an identification
a_config Configuration
a_pop Population
Author
Klaus Meffert
Since
3.2
Definition at line 136 of file JGAPRequestGP.java.
Member Function Documentation
Object org.jgap.distr.grid.gp.JGAPRequestGP.clone () [inline]
Returns
deep clone of current instance
Author
Klaus Meffert
Since
3.2
Implements org.jgap.util.ICloneable.
Definition at line 270 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.getChunk(), org.jgap.distr.grid.gp.JGAPRequestGP.getID(), and org.jgap.distr.grid.gp.JGAPRequestGP.newInstance().
int org.jgap.distr.grid.gp.JGAPRequestGP.getChunk () [inline]
Definition at line 302 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_chunk.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.clone().
GPConfiguration org.jgap.distr.grid.gp.JGAPRequestGP.getConfiguration () [inline]
Returns
the JGAP configuration set
Author
Klaus Meffert
Since
3.2
Definition at line 226 of file JGAPRequestGP.java.
String org.jgap.distr.grid.gp.JGAPRequestGP.getDescription () [inline]
Returns
arbitrary description of the request
Author
Klaus Meffert
Since
3.3.3
Definition at line 367 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_description.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.newInstance().
IGenotypeInitializerGP org.jgap.distr.grid.gp.JGAPRequestGP.getGenotypeInitializer () [inline]
Returns
the IGenotypeInitializer set
Author
Klaus Meffert
Since
3.2
Definition at line 203 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_genotypeInitializer.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.newInstance().
IGridConfigurationGP org.jgap.distr.grid.gp.JGAPRequestGP.getGridConfiguration () [inline]
Returns
the grid configuration set
Author
Klaus Meffert
Since
3.2
Definition at line 236 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_config.
String org.jgap.distr.grid.gp.JGAPRequestGP.getID () [inline]
Definition at line 327 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_id.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.clone().
double org.jgap.distr.grid.gp.JGAPRequestGP.getMinFitness () [inline]
Returns
the minimum fitness wanted for results to be returned as response to this request
Author
Klaus Meffert
Since
3.3.3
Definition at line 378 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_minFitness.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.newInstance().
GPPopulation org.jgap.distr.grid.gp.JGAPRequestGP.getPopulation () [inline]
Returns
the population used to initialize new requests. May be null or empty
Author
Klaus Meffert
Since
3.2
Definition at line 260 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_pop.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.newInstance().
Date org.jgap.distr.grid.gp.JGAPRequestGP.getRequestDate () [inline]
Returns
the date the request was initialized
Author
Klaus Meffert
Since
3.3.3
Definition at line 347 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_requestDate.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.newInstance().
MasterInfo org.jgap.distr.grid.gp.JGAPRequestGP.getRequesterInfo () [inline]
Returns
information about the requester
Author
Klaus Meffert
Since
3.3.3
Definition at line 312 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_requesterInfo.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.newInstance().
String org.jgap.distr.grid.gp.JGAPRequestGP.getTitle () [inline]
Returns
the title set
Author
Klaus Meffert
Since
3.3.4
Definition at line 409 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_title.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.newInstance().
IWorkerEvolveStrategyGP org.jgap.distr.grid.gp.JGAPRequestGP.getWorkerEvolveStrategy () [inline]
Returns
the evolve strategy set
Author
Klaus Meffert
Since
3.2
Definition at line 161 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_evolveStrategy.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.newInstance().
GridWorkerFeedback org.jgap.distr.grid.gp.JGAPRequestGP.getWorkerFeedback () [inline]
Definition at line 179 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_workerFeedback.
IWorkerReturnStrategyGP org.jgap.distr.grid.gp.JGAPRequestGP.getWorkerReturnStrategy () [inline]
Returns
the strategy which part of a result is returned by a worker
Author
Klaus Meffert
Since
3.2
Definition at line 175 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_returnStrategy.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.newInstance().
JGAPRequestGP org.jgap.distr.grid.gp.JGAPRequestGP.newInstance (String a_name, String a_id, int a_chunk) [inline]
Creates a new instance using the given name and ID. Reason for this method: ID cannot be set other than with construction!
Parameters
a_name textual description of request
a_id unique identification of request
a_chunk running index of request chunk, should be unique within an identification
Returns
newly created JGAPRequest object
Author
Klaus Meffert
Since
3.2
Definition at line 288 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.getDescription(), org.jgap.distr.grid.gp.JGAPRequestGP.getGenotypeInitializer(), org.jgap.distr.grid.gp.JGAPRequestGP.getMinFitness(), org.jgap.distr.grid.gp.JGAPRequestGP.getPopulation(), org.jgap.distr.grid.gp.JGAPRequestGP.getRequestDate(), org.jgap.distr.grid.gp.JGAPRequestGP.getRequesterInfo(), org.jgap.distr.grid.gp.JGAPRequestGP.getTitle(), org.jgap.distr.grid.gp.JGAPRequestGP.getWorkerEvolveStrategy(), org.jgap.distr.grid.gp.JGAPRequestGP.getWorkerReturnStrategy(), org.jgap.distr.grid.gp.JGAPRequestGP.JGAPRequestGP(), and org.jgap.distr.grid.gp.JGAPRequestGP.m_config.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.clone().
void org.jgap.distr.grid.gp.JGAPRequestGP.setConfiguration (GPConfiguration a_conf) [inline]
Set a modified JGAP configuration. Should only be used to re-set a configuration because some parts have not been serialized.
Parameters
a_conf the JGAP Configuration to set
Author
Klaus Meffert
Since
3.2
Definition at line 249 of file JGAPRequestGP.java.
void org.jgap.distr.grid.gp.JGAPRequestGP.setDescription (String a_descr) [inline]
Parameters
a_descr arbitrary description of the request
Author
Klaus Meffert
Since
3.3.3
Definition at line 357 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_description.
void org.jgap.distr.grid.gp.JGAPRequestGP.setEvolveStrategy (IWorkerEvolveStrategyGP a_evolveStrategy) [inline]
Sets the strategy to use for executing the evolution with a worker for a single request.
Parameters
a_evolveStrategy the evolve strategy to use
Author
Klaus Meffert
Since
3.2
Definition at line 151 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_evolveStrategy.
void org.jgap.distr.grid.gp.JGAPRequestGP.setGenotypeInitializer (IGenotypeInitializerGP a_initializer) [inline]
Parameters
a_initializer the IGenotypeInitializer to use
Author
Klaus Meffert
Since
3.2
Definition at line 193 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_genotypeInitializer.
void org.jgap.distr.grid.gp.JGAPRequestGP.setMinFitness (double a_minFitness) [inline]
Parameters
a_minFitness the minimum fitness wanted for results to be returned as response to this request
Author
Klaus Meffert
Since
3.3.3
Definition at line 389 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_minFitness.
void org.jgap.distr.grid.gp.JGAPRequestGP.setPopulation (GPPopulation a_pop) [inline]
Sets the Population to store in this request so that it can be passed to workers.
Parameters
a_pop the Population to store
Author
Klaus Meffert
Since
3.2
Definition at line 216 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_pop.
void org.jgap.distr.grid.gp.JGAPRequestGP.setRequestDate (Date a_date) [inline]
Parameters
a_date date the request was initialized
Author
Klaus Meffert
Since
3.3.3
Definition at line 337 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_requestDate.
void org.jgap.distr.grid.gp.JGAPRequestGP.setRequesterInfo (MasterInfo a_requesterInfo) [inline]
Parameters
a_requesterInfo set information about the requester
Author
Klaus Meffert
Since
3.3.3
Definition at line 323 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_requesterInfo.
void org.jgap.distr.grid.gp.JGAPRequestGP.setTitle (String a_title) [inline]
Parameters
a_title the title to set
Author
Klaus Meffert
Since
3.3.4
Definition at line 399 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_title.
void org.jgap.distr.grid.gp.JGAPRequestGP.setWorkerFeedback (GridWorkerFeedback a_feedback) [inline]
Definition at line 183 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_workerFeedback.
void org.jgap.distr.grid.gp.JGAPRequestGP.setWorkerReturnStrategy (IWorkerReturnStrategyGP a_strategy) [inline]
Definition at line 165 of file JGAPRequestGP.java.
References org.jgap.distr.grid.gp.JGAPRequestGP.m_returnStrategy.
Member Data Documentation
final String org.jgap.distr.grid.gp.JGAPRequestGP.CVS_REVISION = `$Revision: 1.8 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 30 of file JGAPRequestGP.java.
int org.jgap.distr.grid.gp.JGAPRequestGP.m_chunk [private]
Definition at line 44 of file JGAPRequestGP.java.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.getChunk(), and org.jgap.distr.grid.gp.JGAPRequestGP.JGAPRequestGP().
IGridConfigurationGP org.jgap.distr.grid.gp.JGAPRequestGP.m_config [private]
Definition at line 32 of file JGAPRequestGP.java.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.getGridConfiguration(), org.jgap.distr.grid.gp.JGAPRequestGP.JGAPRequestGP(), and org.jgap.distr.grid.gp.JGAPRequestGP.newInstance().
String org.jgap.distr.grid.gp.JGAPRequestGP.m_description [private]
Definition at line 52 of file JGAPRequestGP.java.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.getDescription(), and org.jgap.distr.grid.gp.JGAPRequestGP.setDescription().
IWorkerEvolveStrategyGP org.jgap.distr.grid.gp.JGAPRequestGP.m_evolveStrategy [private]
Definition at line 36 of file JGAPRequestGP.java.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.getWorkerEvolveStrategy(), org.jgap.distr.grid.gp.JGAPRequestGP.JGAPRequestGP(), and org.jgap.distr.grid.gp.JGAPRequestGP.setEvolveStrategy().
Object org.jgap.distr.grid.gp.JGAPRequestGP.m_genericData [private]
Definition at line 58 of file JGAPRequestGP.java.
IGenotypeInitializerGP org.jgap.distr.grid.gp.JGAPRequestGP.m_genotypeInitializer [private]
Definition at line 40 of file JGAPRequestGP.java.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.getGenotypeInitializer(), and org.jgap.distr.grid.gp.JGAPRequestGP.setGenotypeInitializer().
String org.jgap.distr.grid.gp.JGAPRequestGP.m_id [private]
Definition at line 48 of file JGAPRequestGP.java.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.getID(), and org.jgap.distr.grid.gp.JGAPRequestGP.JGAPRequestGP().
double org.jgap.distr.grid.gp.JGAPRequestGP.m_minFitness [private]
Definition at line 54 of file JGAPRequestGP.java.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.getMinFitness(), and org.jgap.distr.grid.gp.JGAPRequestGP.setMinFitness().
GPPopulation org.jgap.distr.grid.gp.JGAPRequestGP.m_pop [private]
Definition at line 34 of file JGAPRequestGP.java.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.getPopulation(), org.jgap.distr.grid.gp.JGAPRequestGP.JGAPRequestGP(), and org.jgap.distr.grid.gp.JGAPRequestGP.setPopulation().
Date org.jgap.distr.grid.gp.JGAPRequestGP.m_requestDate [private]
Definition at line 50 of file JGAPRequestGP.java.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.getRequestDate(), and org.jgap.distr.grid.gp.JGAPRequestGP.setRequestDate().
MasterInfo org.jgap.distr.grid.gp.JGAPRequestGP.m_requesterInfo [private]
Definition at line 46 of file JGAPRequestGP.java.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.getRequesterInfo(), and org.jgap.distr.grid.gp.JGAPRequestGP.setRequesterInfo().
IWorkerReturnStrategyGP org.jgap.distr.grid.gp.JGAPRequestGP.m_returnStrategy [private]
Definition at line 38 of file JGAPRequestGP.java.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.getWorkerReturnStrategy(), and org.jgap.distr.grid.gp.JGAPRequestGP.setWorkerReturnStrategy().
String org.jgap.distr.grid.gp.JGAPRequestGP.m_title [private]
Definition at line 56 of file JGAPRequestGP.java.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.getTitle(), and org.jgap.distr.grid.gp.JGAPRequestGP.setTitle().
GridWorkerFeedback org.jgap.distr.grid.gp.JGAPRequestGP.m_workerFeedback [private]
Definition at line 42 of file JGAPRequestGP.java.
Referenced by org.jgap.distr.grid.gp.JGAPRequestGP.getWorkerFeedback(), and org.jgap.distr.grid.gp.JGAPRequestGP.setWorkerFeedback().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/distr/grid/gp/JGAPRequestGP.java