org.jgap.util.PersistableObject Class Reference
Public Member Functions
PersistableObject (File a_file)
PersistableObject (String a_filename)
void setObject (Object a_object)
void save () throws Exception
void save (boolean a_omitConfig) throws Exception
void save (boolean a_omitConfig, Object[][] a_omitFields) throws Exception
Object load () throws Exception
Object load (File a_file)
Object getObject ()
Protected Member Functions
void init (XStream a_xstream)
Private Attributes
transient Logger log = Logger.getLogger(getClass())
Object m_object
File m_file
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.7 $`
Detailed Description
A wrapper that allows an object to be written to and read from a file.
Author
Klaus Meffert
Since
3.3.3
Definition at line 26 of file PersistableObject.java.
Constructor & Destructor Documentation
org.jgap.util.PersistableObject.PersistableObject (File a_file) [inline]
Definition at line 36 of file PersistableObject.java.
References org.jgap.util.PersistableObject.m_file.
org.jgap.util.PersistableObject.PersistableObject (String a_filename) [inline]
Definition at line 40 of file PersistableObject.java.
Member Function Documentation
Object org.jgap.util.PersistableObject.getObject () [inline]
Definition at line 103 of file PersistableObject.java.
References org.jgap.util.PersistableObject.m_object.
void org.jgap.util.PersistableObject.init (XStream a_xstream) [inline], [protected]
Definition at line 107 of file PersistableObject.java.
Referenced by org.jgap.util.PersistableObject.load(), and org.jgap.util.PersistableObject.save().
Object org.jgap.util.PersistableObject.load () throws Exception [inline]
Definition at line 84 of file PersistableObject.java.
References org.jgap.util.PersistableObject.m_file.
Object org.jgap.util.PersistableObject.load (File a_file) [inline]
Definition at line 89 of file PersistableObject.java.
References org.jgap.util.PersistableObject.init(), and org.jgap.util.PersistableObject.m_object.
void org.jgap.util.PersistableObject.save () throws Exception [inline]
Definition at line 48 of file PersistableObject.java.
Referenced by org.jgap.util.PersistableObject.save().
void org.jgap.util.PersistableObject.save (boolean a_omitConfig) throws Exception [inline]
Definition at line 53 of file PersistableObject.java.
References org.jgap.util.PersistableObject.save().
void org.jgap.util.PersistableObject.save (boolean a_omitConfig, Object a_omitFields[][]) throws Exception [inline]
Definition at line 57 of file PersistableObject.java.
References org.jgap.util.PersistableObject.init(), org.jgap.util.PersistableObject.m_file, and org.jgap.util.PersistableObject.m_object.
void org.jgap.util.PersistableObject.setObject (Object a_object) [inline]
Definition at line 44 of file PersistableObject.java.
References org.jgap.util.PersistableObject.m_object.
Member Data Documentation
final String org.jgap.util.PersistableObject.CVS_REVISION = `$Revision: 1.7 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 28 of file PersistableObject.java.
transient Logger org.jgap.util.PersistableObject.log = Logger.getLogger(getClass()) [private]
Definition at line 30 of file PersistableObject.java.
File org.jgap.util.PersistableObject.m_file [private]
Definition at line 34 of file PersistableObject.java.
Referenced by org.jgap.util.PersistableObject.load(), org.jgap.util.PersistableObject.PersistableObject(), and org.jgap.util.PersistableObject.save().
Object org.jgap.util.PersistableObject.m_object [private]
Definition at line 32 of file PersistableObject.java.
Referenced by org.jgap.util.PersistableObject.getObject(), org.jgap.util.PersistableObject.load(), org.jgap.util.PersistableObject.save(), and org.jgap.util.PersistableObject.setObject().
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/util/PersistableObject.java