org.jgap.impl.DefaultMutationRateCalculatorTest Class Reference
Public Member Functions
void setUp ()
void testCalculateCurrentRate_0 () throws Exception
void testCalculateCurrentRate_1 () throws Exception
void testCalculateCurrentRate_2 () throws Exception
Static Public Member Functions
static Test suite ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.13 $`
Additional Inherited Members
Detailed Description
Tests the DefaultMutationRateCalculator class.
Author
Klaus Meffert
Since
1.1
Definition at line 22 of file DefaultMutationRateCalculatorTest.java.
Member Function Documentation
void org.jgap.impl.DefaultMutationRateCalculatorTest.setUp () [inline]
Definition at line 33 of file DefaultMutationRateCalculatorTest.java.
static Test org.jgap.impl.DefaultMutationRateCalculatorTest.suite () [inline], [static]
Definition at line 28 of file DefaultMutationRateCalculatorTest.java.
void org.jgap.impl.DefaultMutationRateCalculatorTest.testCalculateCurrentRate_0 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Definition at line 44 of file DefaultMutationRateCalculatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.getChromosomeSize().
void org.jgap.impl.DefaultMutationRateCalculatorTest.testCalculateCurrentRate_1 () throws Exception [inline]
Exceptions
Exception
Author
Klaus Meffert
Since
3.0
Definition at line 59 of file DefaultMutationRateCalculatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), org.jgap.JGAPTestCase.conf, and org.jgap.Configuration.getChromosomeSize().
void org.jgap.impl.DefaultMutationRateCalculatorTest.testCalculateCurrentRate_2 () throws Exception [inline]
If there are zero chromosomes in the config., the mutation rate nevertheless should be 1, because Random needs positive integers as input (see MutationOperator.operate for calling Random class)
Exceptions
Exception
Author
Klaus Meffert
Definition at line 76 of file DefaultMutationRateCalculatorTest.java.
References org.jgap.JGAPTestCase.assertEquals(), and org.jgap.JGAPTestCase.conf.
Member Data Documentation
final String org.jgap.impl.DefaultMutationRateCalculatorTest.CVS_REVISION = `$Revision: 1.13 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file DefaultMutationRateCalculatorTest.java.
The documentation for this class was generated from the following file:
LDH_Git/tests/org/jgap/impl/DefaultMutationRateCalculatorTest.java