examples.MapGeneExample Class Reference
Static Public Member Functions
static void makeChangeForAmount (int a_targetChangeAmount) throws Exception
static void main (String[] args) throws Exception
static boolean uniqueChromosomes (Population a_pop)
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.1 $`
static final int MAX_ALLOWED_EVOLUTIONS = 200
Detailed Description
This class provides an implementation of the classic `Make change` problem using a genetic algorithm. It is equivalent to the example in class MinimizingMakeChange in the same package, except that it uses a MapGene.
A MapGene allows to specify discrete values for possible solutions. Instead, an IntegerGene (used in the original example) uses a range of values.
Author
Klaus Meffert
Since
3.6
Definition at line 28 of file MapGeneExample.java.
Member Function Documentation
static void examples.MapGeneExample.main (String[] args) throws Exception [inline], [static]
Main method. A single command-line argument is expected, which is the amount of change to create (in other words, 75 would be equal to 75 cents).
Parameters
args amount of change in cents to create
Exceptions
Exception
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 174 of file MapGeneExample.java.
References examples.MapGeneExample.makeChangeForAmount(), and examples.MinimizingMakeChangeFitnessFunction.MAX_BOUND.
static void examples.MapGeneExample.makeChangeForAmount (int a_targetChangeAmount) throws Exception [inline], [static]
Executes the genetic algorithm to determine the minimum number of coins necessary to make up the given target amount of change. The solution will then be written to System.out.
Parameters
a_targetChangeAmount the target amount of change for which this method is attempting to produce the minimum number of coins
Exceptions
Exception
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 51 of file MapGeneExample.java.
References examples.MapGeneExample.MAX_ALLOWED_EVOLUTIONS, and examples.MapGeneExample.uniqueChromosomes().
Referenced by examples.MapGeneExample.main().
static boolean examples.MapGeneExample.uniqueChromosomes (Population a_pop) [inline], [static]
Parameters
a_pop the population to verify
Returns
true if all chromosomes in the populationa are unique
Author
Klaus Meffert
Since
3.3.1
Definition at line 209 of file MapGeneExample.java.
Referenced by examples.MapGeneExample.makeChangeForAmount().
Member Data Documentation
final String examples.MapGeneExample.CVS_REVISION = `$Revision: 1.1 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 30 of file MapGeneExample.java.
final int examples.MapGeneExample.MAX_ALLOWED_EVOLUTIONS = 200 [static], [private]
The total number of times we'll let the population evolve.
Definition at line 35 of file MapGeneExample.java.
Referenced by examples.MapGeneExample.makeChangeForAmount().
The documentation for this class was generated from the following file:
LDH_Git/examples/src/examples/MapGeneExample.java