org.jgap.gp.function.Sine Class Reference
Classes
interface Compatible
Public Member Functions
Sine (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException
String toString ()
String getName ()
float execute_float (ProgramChromosome c, int n, Object[] args)
double execute_double (ProgramChromosome c, int n, Object[] args)
Object execute_object (ProgramChromosome c, int n, Object[] args)
Object clone ()
Static Private Attributes
static final String CVS_REVISION = `$Revision: 1.8 $`
Additional Inherited Members
Detailed Description
The sine operation.
Author
Klaus Meffert
Since
3.0
Definition at line 23 of file Sine.java.
Constructor & Destructor Documentation
org.jgap.gp.function.Sine.Sine (final GPConfiguration a_conf, Class a_returnType) throws InvalidConfigurationException [inline]
Definition at line 28 of file Sine.java.
Referenced by org.jgap.gp.function.Sine.clone().
Member Function Documentation
Object org.jgap.gp.function.Sine.clone () [inline]
Clones the object. Simple and straight forward implementation here.
Returns
cloned instance of this object
Author
Klaus Meffert
Since
3.4
Implements org.jgap.util.ICloneable.
Definition at line 74 of file Sine.java.
References org.jgap.gp.CommandGene.getGPConfiguration(), org.jgap.gp.CommandGene.getReturnType(), and org.jgap.gp.function.Sine.Sine().
double org.jgap.gp.function.Sine.execute_double (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 53 of file Sine.java.
float org.jgap.gp.function.Sine.execute_float (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 47 of file Sine.java.
Object org.jgap.gp.function.Sine.execute_object (ProgramChromosome c, int n, Object[] args) [inline]
Definition at line 59 of file Sine.java.
String org.jgap.gp.function.Sine.getName () [inline]
Returns
textual name of this command
Author
Klaus Meffert
Since
3.2
Definition at line 43 of file Sine.java.
String org.jgap.gp.function.Sine.toString () [inline], [virtual]
Returns
the string representation of the command. Especially usefull to output a resulting formula in human-readable form.
Implements org.jgap.gp.CommandGene.
Definition at line 33 of file Sine.java.
Member Data Documentation
final String org.jgap.gp.function.Sine.CVS_REVISION = `$Revision: 1.8 $` [static], [private]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file Sine.java.
The documentation for this class was generated from the following file:
LDH_Git/src/org/jgap/gp/function/Sine.java