org.jgap.IHandler Interface Reference
Public Member Functions
boolean isHandlerFor (Object a_obj, Class a_class)
Object perform (Object a_obj, Class a_class, Object a_params) throws Exception
Static Public Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Detailed Description
Interface for handlers capable of doing somethign specific.
Such a handler acknowledges via isHandlerFor(Class) that the method perform(Object, Object) could be executed for the given class.
Author
Klaus Meffert
Since
2.6
Definition at line 20 of file IHandler.java.
Member Function Documentation
boolean org.jgap.IHandler.isHandlerFor (Object a_obj, Class a_class)
Determines whether the handler is suitable for the given object instance or class.
Parameters
a_obj the object instance to check
a_class the class to check, alternatively if no object instance is available (some handlers could need to get an object and would always return false if only a class is provided)
Returns
true: handler suitable for given object or class
Author
Klaus Meffert
Since
2.6
Implemented in org.jgap.Chromosome, and org.jgap.ChromosomeForTesting.
Referenced by org.jgap.impl.JGAPFactory.findHandlerFor(), org.jgap.impl.DefaultInitializerTest.testIsHandlerFor_0(), org.jgap.impl.DefaultCompareToHandlerTest.testIsHandlerFor_0(), org.jgap.impl.DefaultCloneHandlerTest.testIsHandlerFor_0(), org.jgap.impl.DefaultCompareToHandlerTest.testIsHandlerFor_1(), org.jgap.impl.DefaultCloneHandlerTest.testIsHandlerFor_1(), org.jgap.impl.DefaultCloneHandlerTest.testIsHandlerFor_2(), org.jgap.impl.DefaultCompareToHandlerTest.testIsHandlerFor_2(), org.jgap.impl.DefaultCompareToHandlerTest.testIsHandlerFor_3(), and org.jgap.impl.DefaultCloneHandlerTest.testIsHandlerFor_3().
Object org.jgap.IHandler.perform (Object a_obj, Class a_class, Object a_params) throws Exception
Performs a task for the given object or class. For some handlers, additional parameters are necessary, which could be provided.
Parameters
a_obj the object instance to perform the handler task for
a_class the class to perform the handler task for, in case no object instance is available (some handlers could need to get an object and would always throw an exception if only a class is provided)
a_params optional parameters needed for the handler to perform its task
Exceptions
Exception in case of any error
Returns
Object
Author
Klaus Meffert
Since
2.6
Implemented in org.jgap.GenotypeTest.ChromosomeForTest2, org.jgap.Chromosome, and org.jgap.ChromosomeForTesting.
Referenced by org.jgap.impl.BestChromosomesSelector.add(), org.jgap.gp.impl.GPGenotype.calcFitness(), org.jgap.gp.impl.GPGenotype.cloneProgram(), org.jgap.gp.impl.GPPopulation.create(), org.jgap.gp.impl.GPPopulation.determineFittestProgram(), org.jgap.NaturalSelectorExt.selectChromosome(), org.jgap.impl.WeightedRouletteSelector.selectChromosomes(), org.jgap.impl.DefaultInitializerTest.testPerform_1(), org.jgap.impl.DefaultCompareToHandlerTest.testPerform_1(), org.jgap.impl.DefaultCloneHandlerTest.testPerform_1(), org.jgap.impl.DefaultCompareToHandlerTest.testPerform_2(), org.jgap.impl.DefaultCloneHandlerTest.testPerform_2(), org.jgap.impl.DefaultCloneHandlerTest.testPerform_3(), org.jgap.impl.DefaultCloneHandlerTest.testPerform_4(), org.jgap.impl.DefaultCloneHandlerTest.testPerform_5(), and org.jgap.impl.DefaultCloneHandlerTest.testPerform_6().
Member Data Documentation
final String org.jgap.IHandler.CVS_REVISION = `$Revision: 1.3 $` [static]
String containing the CVS revision. Read out via reflection!
Definition at line 22 of file IHandler.java.
The documentation for this interface was generated from the following file:
LDH_Git/src/org/jgap/IHandler.java