org.jgap.IChromosome Interface Reference
Public Member Functions
Gene getGene (int a_desiredLocus)
Gene[] getGenes ()
void setGenes (Gene[] a_genes) throws InvalidConfigurationException
int size ()
void setFitnessValue (double a_newFitnessValue)
void setFitnessValueDirectly (double a_newFitnessValue)
double getFitnessValue ()
double getFitnessValueDirectly ()
void setIsSelectedForNextGeneration (boolean a_isSelected)
boolean isSelectedForNextGeneration ()
void setConstraintChecker (IGeneConstraintChecker a_constraintChecker) throws InvalidConfigurationException
void setApplicationData (Object a_newData)
Object getApplicationData ()
void cleanup ()
Configuration getConfiguration ()
void increaseAge ()
void resetAge ()
void setAge (int a_age)
int getAge ()
void increaseOperatedOn ()
void resetOperatedOn ()
int operatedOn ()
Static Public Attributes
static final String CVS_REVISION = `$Revision: 1.17 $`
static final String S_FITNESS_VALUE = `Fitness value`
static final String S_ALLELES = `Alleles`
static final String S_APPLICATION_DATA = `Application data`
static final String S_SIZE = `Size`
Detailed Description
Interface for chromosomes. Normally, you would start using BaseChromosome which implements this interface to build your own chromosome classes.
Author
Klaus Meffert
Since
2.6
Definition at line 23 of file IChromosome.java.
Member Function Documentation
void org.jgap.IChromosome.cleanup ()
Invoked when this Chromosome is no longer needed and should perform any necessary cleanup. Note that this method will attempt to release this Chromosome instance to the active ChromosomePool, if any.
Author
Neil Rotstan
Klaus Meffert
Since
2.6
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.Chromosome.
int org.jgap.IChromosome.getAge ()
Returns
0: Chromosome newly created in this generation. This means it does not need being crossed over with another newly created one
Author
Klaus Meffert
Since
3.2
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.BaseChromosome.
Referenced by org.jgap.NaturalSelector.AgeFitnessValueComparator.compare(), and org.jgap.NaturalSelector.FitnessAgeValueComparator.compare().
Object org.jgap.IChromosome.getApplicationData ()
Retrieves the application-specific data that is attached to this Chromosome. Attaching application-specific data may be useful for some applications when it comes time to evaluate this Chromosome in the fitness function. JGAP ignores this data functionally.
Returns
the application-specific data previously attached to this Chromosome, or null if there is no data attached
Author
Neil Rotstan
Klaus Meffert
Since
2.6
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.Chromosome.
Referenced by org.jgap.Chromosome.compareTo().
Configuration org.jgap.IChromosome.getConfiguration ()
Returns
the configuration set
Author
Klaus Meffert
Since
3.0
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.BaseChromosome.
double org.jgap.IChromosome.getFitnessValue ()
Retrieves the fitness value of this Chromosome, as determined by the active fitness function. If a bulk fitness function is in use and has not yet assigned a fitness value to this Chromosome, then -1 is returned.
Attention: should not be called from toString() as the fitness value would be computed if it was initial!
Returns
a positive double value representing the fitness of this Chromosome, or -1 if a bulk fitness function is in use and has not yet assigned a fitness value to this Chromosome
Author
Neil Rotstan
Klaus Meffert
Since
2.6
Implemented in org.jgap.GenotypeTest.MyChromosome, org.jgap.Chromosome, and org.jgap.ChromosomeForTesting.
Referenced by org.jgap.impl.FittestPopulationMerger.FitnessChromosomeComparator.compare(), org.jgap.impl.ThresholdSelector.FitnessValueComparator.compare(), org.jgap.impl.TournamentSelector.FitnessValueComparator.compare(), org.jgap.DefaultFitnessEvaluator.isFitter(), org.jgap.DeltaFitnessEvaluator.isFitter(), org.jgap.audit.FitnessImprovementMonitor.nextCycle(), and org.jgap.impl.salesman.TravellingSalesmanTest.testSampleTravellingSalesmanApp().
double org.jgap.IChromosome.getFitnessValueDirectly ()
Returns
the lastly computed fitness value, or FitnessFunction.NO_FITNESS_VALUE in case no value has been computed yet.
Author
Klaus Meffert
Since
2.6
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.Chromosome.
Referenced by org.jgap.Chromosome.compareTo(), org.jgap.BaseChromosome.getPersistentRepresentation(), org.jgap.impl.GABreeder.removeChromosomesWithoutFitnessValue(), org.jgap.impl.GABreeder.removeEvaluatedChromosomes(), and org.jgap.impl.StandardPostSelector.select().
Gene org.jgap.IChromosome.getGene (int a_desiredLocus)
Returns the Gene at the given index (locus) within the Chromosome. The first gene is at index zero and the last gene is at the index equal to the size of this Chromosome - 1.
Parameters
a_desiredLocus index of the gene value to be returned
Returns
Gene at the given index
Author
Neil Rotstan
Klaus Meffert
Since
2.6
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.BaseChromosome.
Referenced by org.jgap.impl.job.MaxFunction.evaluate(), org.jgap.impl.fitness.RosenbrocksBulkNegativeFunction.evaluate(), org.jgap.perf.TestOverallPerformanceFitnessFunc.getNumberOfCoinsAtGene(), org.jgap.GenotypeTest.Test2Function.getX(), org.jgap.GenotypeTest.Test2Function.getY(), and org.jgap.GenotypeTest.testBreeder_0().
Gene [] org.jgap.IChromosome.getGenes ()
Retrieves the set of genes that make up this Chromosome. This method exists primarily for the benefit of GeneticOperators that require the ability to manipulate Chromosomes at a low level.
Returns
an array of the Genes contained within this Chromosome
Author
Neil Rotstan
Klaus Meffert
Since
2.6
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.BaseChromosome.
Referenced by org.jgap.xml.XMLManager.representChromosomeAsElement().
void org.jgap.IChromosome.increaseAge ()
Increases the number of evolutionary rounds of chromosome in which it has not been changed by one.
Author
Klaus Meffert
Since
3.2
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.BaseChromosome.
void org.jgap.IChromosome.increaseOperatedOn ()
Increase information of number of genetic operations performed on chromosome in current evolution round.
Author
Klaus Meffert
Since
3.2
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.BaseChromosome.
boolean org.jgap.IChromosome.isSelectedForNextGeneration ()
Retrieves whether this Chromosome has been selected by the natural selector to continue to the next generation.
Returns
true if this Chromosome has been selected, false otherwise
Author
Neil Rotstan
Klaus Meffert
Since
2.6
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.Chromosome.
int org.jgap.IChromosome.operatedOn ()
Returns
number of genetic operations performed on chromosome in current evolution round
Author
Klaus Meffert
Since
3.2
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.BaseChromosome.
void org.jgap.IChromosome.resetAge ()
Reset age of chromosome because it has been changed.
Author
Klaus Meffert
Since
3.2
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.BaseChromosome.
void org.jgap.IChromosome.resetOperatedOn ()
Resets the information of how many genetic operators have been performed on the chromosome in the current round of evolution.
Author
Klaus Meffert
Since
3.2
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.BaseChromosome.
void org.jgap.IChromosome.setAge (int a_age)
Parameters
a_age set the age of the chromosome, see BestChromosomesSelector for a use-case
Author
Klaus Meffert
Since
3.3.3
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.BaseChromosome.
void org.jgap.IChromosome.setApplicationData (Object a_newData)
This sets the application-specific data that is attached to this Chromosome. Attaching application-specific data may be useful for some applications when it comes time to evaluate this Chromosome in the fitness function.
Parameters
a_newData the new application-specific data to attach to this Chromosome. Should be an instance of IApplicationData
Author
Neil Rotstan
Klaus Meffert
Since
2.6
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.Chromosome.
void org.jgap.IChromosome.setConstraintChecker (IGeneConstraintChecker a_constraintChecker) throws InvalidConfigurationException
Sets the constraint checker to be used for this gene whenever method setAllele(Object) is called.
Parameters
a_constraintChecker the constraint checker to be set
Exceptions
InvalidConfigurationException
Author
Klaus Meffert
Since
2.6
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.Chromosome.
void org.jgap.IChromosome.setFitnessValue (double a_newFitnessValue)
Sets the fitness value of this Chromosome. This method is for use by bulk fitness functions and should not be invokved from anything else (except test cases).
Parameters
a_newFitnessValue a positive integer representing the fitness of this Chromosome
Author
Neil Rotstan
Since
2.6
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.Chromosome.
Referenced by org.jgap.BaseChromosome.setValueFromPersistentRepresentation().
void org.jgap.IChromosome.setFitnessValueDirectly (double a_newFitnessValue)
Sets the fitness value of this Chromosome directly without any constraint checks, conversions or checks. Only use if you know what you do.
Parameters
a_newFitnessValue a positive integer representing the fitness of this Chromosome
Author
Klaus Meffert
Since
2.6
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.Chromosome.
void org.jgap.IChromosome.setGenes (Gene[] a_genes) throws InvalidConfigurationException
Sets the genes for the chromosome.
Parameters
a_genes the genes to set for the chromosome
Exceptions
InvalidConfigurationException in case constraint checker is provided
Author
Klaus Meffert
Since
2.6
Implemented in org.jgap.GenotypeTest.MyChromosome, org.jgap.Chromosome, and org.jgap.BaseChromosome.
void org.jgap.IChromosome.setIsSelectedForNextGeneration (boolean a_isSelected)
Sets whether this Chromosome has been selected by the natural selector to continue to the next generation or manually (e.g. via an add-method).
Parameters
a_isSelected true if this Chromosome has been selected, false otherwise
Author
Neil Rotstan
Klaus Meffert
Since
2.6
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.Chromosome.
int org.jgap.IChromosome.size ()
Returns the size of this Chromosome (the number of genes it contains). A Chromosome's size is constant and will not change, until setGenes(...) is used.
Returns
number of genes contained within this Chromosome instance
Author
Klaus Meffert
Neil Rotstan
Since
2.6
Implemented in org.jgap.GenotypeTest.MyChromosome, and org.jgap.BaseChromosome.
Referenced by org.jgap.Chromosome.compareTo(), and org.jgap.impl.job.MaxFunction.evaluate().
Member Data Documentation
final String org.jgap.IChromosome.CVS_REVISION = `$Revision: 1.17 $` [static]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file IChromosome.java.
final String org.jgap.IChromosome.S_ALLELES = `Alleles` [static]
Definition at line 33 of file IChromosome.java.
Referenced by org.jgap.GenotypeTest.testToString_0(), org.jgap.GenotypeTest.testToString_1(), and org.jgap.Chromosome.toString().
final String org.jgap.IChromosome.S_APPLICATION_DATA = `Application data` [static]
Definition at line 35 of file IChromosome.java.
Referenced by org.jgap.GenotypeTest.testToString_0(), org.jgap.GenotypeTest.testToString_1(), and org.jgap.Chromosome.toString().
final String org.jgap.IChromosome.S_FITNESS_VALUE = `Fitness value` [static]
Constants for toString()
Definition at line 31 of file IChromosome.java.
Referenced by org.jgap.GenotypeTest.testToString_0(), org.jgap.GenotypeTest.testToString_1(), and org.jgap.Chromosome.toString().
final String org.jgap.IChromosome.S_SIZE = `Size` [static]
Definition at line 37 of file IChromosome.java.
Referenced by org.jgap.GenotypeTest.testToString_0(), org.jgap.ChromosomeTest.testToString_0(), org.jgap.GenotypeTest.testToString_1(), org.jgap.ChromosomeTest.testToString_1(), org.jgap.ChromosomeTest.testToString_2(), and org.jgap.Chromosome.toString().
The documentation for this interface was generated from the following file:
LDH_Git/src/org/jgap/IChromosome.java