org.jgap.gp.IGPChromosome Interface Reference
Public Member Functions
IGPProgram getIndividual ()
void setIndividual (IGPProgram a_ind)
void cleanup ()
String toStringNorm (final int a_startNode)
void redepth ()
int numTerminals ()
int numFunctions ()
int numTerminals (Class a_type, int a_subType)
int numFunctions (Class a_type, int a_subType)
CommandGene getNode (int a_index)
int getChild (int a_index, int a_child)
int getTerminal (int a_index)
int getFunction (int a_index)
int getTerminal (int a_index, Class a_type, int a_subType)
int getFunction (int a_index, Class a_type, int a_subType)
CommandGene[] getFunctions ()
CommandGene[] getFunctionSet ()
GPConfiguration getGPConfiguration ()
String getPersistentRepresentation ()
Static Public Attributes
static final String CVS_REVISION = `$Revision: 1.7 $`
Detailed Description
Interface for GP chromosomes. See ProgramChromosome for an implementation.
Author
Klaus Meffert
Since
3.01
Definition at line 21 of file IGPChromosome.java.
Member Function Documentation
void org.jgap.gp.IGPChromosome.cleanup ()
Clean up the chromosome.
Author
Klaus Meffert
Since
3.01
Implemented in org.jgap.gp.impl.ProgramChromosome.
int org.jgap.gp.IGPChromosome.getChild (int a_index, int a_child)
Gets the a_child'th child of the a_index'th node in this chromosome. This is the same as the a_child'th node whose depth is one more than the depth of the a_index'th node.
Parameters
a_index the node number of the parent
a_child the child number (starting from 0) of the parent
Returns
the node number of the child, or -1 if not found
Author
Klaus Meffert
Since
3.01
Implemented in org.jgap.gp.impl.ProgramChromosome.
int org.jgap.gp.IGPChromosome.getFunction (int a_index)
Gets the a_index'th function in this chromosome. The nodes are counted in a depth-first manner, with node 0 being the first function in this chromosome.
Parameters
a_index the a_index'th function to get
Returns
the function
Author
Klaus Meffert
Since
3.01
Implemented in org.jgap.gp.BaseGPChromosome.
int org.jgap.gp.IGPChromosome.getFunction (int a_index, Class a_type, int a_subType)
Gets the i'th function of the given type in this chromosome. The nodes are counted in a depth-first manner, with node 0 being the first function of the given type in this chromosome.
Parameters
a_index the i'th function to get
a_type the type of function to get
a_subType the subtype to consider
Returns
the index of the function found, or -1 if no appropriate function was found
Author
Klaus Meffert
Since
3.01
Implemented in org.jgap.gp.BaseGPChromosome.
CommandGene [] org.jgap.gp.IGPChromosome.getFunctions ()
Implemented in org.jgap.gp.impl.ProgramChromosome.
Referenced by org.jgap.gp.BaseGPChromosome.getAssignableFromClass(), org.jgap.gp.BaseGPChromosome.getCommandOfClass(), org.jgap.gp.BaseGPChromosome.getFunction(), org.jgap.gp.BaseGPChromosome.getNode(), org.jgap.gp.BaseGPChromosome.getTerminal(), org.jgap.gp.BaseGPChromosome.getVariableWithReturnType(), org.jgap.gp.BaseGPChromosome.numFunctions(), and org.jgap.gp.BaseGPChromosome.numTerminals().
CommandGene [] org.jgap.gp.IGPChromosome.getFunctionSet ()
Returns
set of CommandGene instances allowed
Author
Klaus Meffert
Since
3.2.1
Implemented in org.jgap.gp.impl.ProgramChromosome.
GPConfiguration org.jgap.gp.IGPChromosome.getGPConfiguration ()
Implemented in org.jgap.gp.BaseGPChromosome.
IGPProgram org.jgap.gp.IGPChromosome.getIndividual ()
Returns
the individual containing this chromosome
Author
Klaus Meffert
Since
3.01
Implemented in org.jgap.gp.BaseGPChromosome.
CommandGene org.jgap.gp.IGPChromosome.getNode (int a_index)
Gets the a_index'th node in this chromosome. The nodes are counted in a depth-first manner, with node 0 being the root of this chromosome.
Parameters
a_index the node number to get
Returns
the node
Author
Klaus Meffert
Since
3.01
Implemented in org.jgap.gp.BaseGPChromosome.
String org.jgap.gp.IGPChromosome.getPersistentRepresentation ()
Returns
the persistent representation of the population, including all GP programs
Author
Klaus Meffert
Since
3.3
Implemented in org.jgap.gp.impl.ProgramChromosome.
int org.jgap.gp.IGPChromosome.getTerminal (int a_index)
Gets the i'th terminal in this chromosome. The nodes are counted in a depth-first manner, with node 0 being the first terminal in this chromosome.
Parameters
a_index the i'th terminal to get
Returns
the terminal
Author
Klaus Meffert
Since
3.01
Implemented in org.jgap.gp.BaseGPChromosome.
int org.jgap.gp.IGPChromosome.getTerminal (int a_index, Class a_type, int a_subType)
Gets the a_index'th terminal of the given type in this chromosome. The nodes are counted in a depth-first manner, with node 0 being the first terminal of the given type in this chromosome.
Parameters
a_index the a_index'th terminal to get
a_type the type of terminal to get
a_subType the subtype to consider
Returns
the index of the terminal found, or -1 if no appropriate terminal was found
Author
Klaus Meffert
Since
3.01
Implemented in org.jgap.gp.BaseGPChromosome.
int org.jgap.gp.IGPChromosome.numFunctions ()
Returns
the number of functions in this chromosome
Author
Klaus Meffert
Since
3.01
Implemented in org.jgap.gp.BaseGPChromosome.
int org.jgap.gp.IGPChromosome.numFunctions (Class a_type, int a_subType)
Counts the number of functions of the given type in this chromosome.
Parameters
a_type the type of function to count
a_subType the subtype to consider
Returns
the number of functions in this chromosome.
Author
Klaus Meffert
Since
3.01
Implemented in org.jgap.gp.BaseGPChromosome.
int org.jgap.gp.IGPChromosome.numTerminals ()
Returns
the number of terminals in this chromosome
Author
Klaus Meffert
Since
3.01
Implemented in org.jgap.gp.BaseGPChromosome.
int org.jgap.gp.IGPChromosome.numTerminals (Class a_type, int a_subType)
Counts the number of terminals of the given type in this chromosome.
Parameters
a_type the type of terminal to count
a_subType the subtype to consider
Returns
the number of terminals in this chromosome
Author
Klaus Meffert
Since
3.01
Implemented in org.jgap.gp.BaseGPChromosome.
void org.jgap.gp.IGPChromosome.redepth ()
Recalculate the depths of each node.
Author
Klaus Meffert
Since
3.01
Implemented in org.jgap.gp.impl.ProgramChromosome.
void org.jgap.gp.IGPChromosome.setIndividual (IGPProgram a_ind)
Sets the individual the chromosome belongs to.
Parameters
a_ind the individual containing this chromosome
Author
Klaus Meffert
Since
3.01
Implemented in org.jgap.gp.BaseGPChromosome.
String org.jgap.gp.IGPChromosome.toStringNorm (final int a_startNode)
Output program in `natural` notion (e.g.: `X + Y` for `X + Y`)
Parameters
a_startNode the node to start with
Returns
output in normalized notion
Author
Klaus Meffert
Since
3.01
Implemented in org.jgap.gp.impl.ProgramChromosome.
Member Data Documentation
final String org.jgap.gp.IGPChromosome.CVS_REVISION = `$Revision: 1.7 $` [static]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file IGPChromosome.java.
The documentation for this interface was generated from the following file:
LDH_Git/src/org/jgap/gp/IGPChromosome.java