org.jgap.data.IDataElementList Interface Reference
Public Member Functions
IDataElement item (int a_index)
int getLength ()
void add (IDataElement a_element)
Static Public Attributes
static final String CVS_REVISION = `$Revision: 1.4 $`
Detailed Description
IDataElementList is an interface describing a list of IDataElement elements
Author
Klaus Meffert
Since
2.0
Definition at line 18 of file IDataElementList.java.
Member Function Documentation
void org.jgap.data.IDataElementList.add (IDataElement a_element)
int org.jgap.data.IDataElementList.getLength ()
Implemented in org.jgap.data.DataElementList.
Referenced by org.jgap.data.DataTreeBuilderTest.testRepresentChromosomeAsDocument_0(), and org.jgap.data.DataTreeBuilderTest.testRepresentGenotypeAsDocument_0().
IDataElement org.jgap.data.IDataElementList.item (int a_index)
Referenced by org.jgap.data.DataElement.getElementsByTagName().
Member Data Documentation
final String org.jgap.data.IDataElementList.CVS_REVISION = `$Revision: 1.4 $` [static]
String containing the CVS revision. Read out via reflection!
Definition at line 20 of file IDataElementList.java.
The documentation for this interface was generated from the following file:
LDH_Git/src/org/jgap/data/IDataElementList.java