org.jgap.gp.IGPProgram Interface Reference
Public Member Functions
int execute_int (int a_chromosomeNum, Object[] a_args)
float execute_float (int a_chromosomeNum, Object[] a_args)
double execute_double (int a_chromosomeNum, Object[] a_args)
boolean execute_boolean (int a_chromosomeNum, Object[] a_args)
Object execute_object (int a_chromosomeNum, Object[] a_args)
void execute_void (int a_chromosomeNum, Object[] a_args)
int size ()
ProgramChromosome getChromosome (int a_index)
double getFitnessValue ()
String toStringNorm (int a_startNode)
void setChromosome (int a_index, ProgramChromosome a_chrom)
int getCommandOfClass (int a_chromosomeNum, Class a_class)
void setFitnessValue (double a_fitness)
void setTypes (Class[] a_types)
Class[] getTypes ()
void setArgTypes (Class[][] a_argTypes)
Class[][] getArgTypes ()
void setNodeSets (CommandGene[][] a_nodeSets)
CommandGene[][] getNodeSets ()
void setMaxDepths (int[] a_maxDepths)
int[] getMaxDepths ()
void setMinDepths (int[] a_minDepths)
int[] getMinDepths ()
void setMaxNodes (int a_maxNodes)
int getMaxNodes ()
GPConfiguration getGPConfiguration ()
void setApplicationData (Object a_data)
Object getApplicationData ()
String getPersistentRepresentation ()
Static Public Attributes
static final String CVS_REVISION = `$Revision: 1.14 $`
Detailed Description
Interface for GP programs.
Author
Klaus Meffert
Since
3.0
Definition at line 22 of file IGPProgram.java.
Member Function Documentation
boolean org.jgap.gp.IGPProgram.execute_boolean (int a_chromosomeNum, Object[] a_args)
Executes the given chromosome as a boolean function.
Parameters
a_chromosomeNum the index of the chromosome to execute
a_args the arguments to use
Returns
the boolean return value
Author
Klaus Meffert
Since
3.2
Implemented in org.jgap.gp.impl.GPProgram.
double org.jgap.gp.IGPProgram.execute_double (int a_chromosomeNum, Object[] a_args)
Executes the given chromosome as a double function.
Parameters
a_chromosomeNum the index of the chromosome to execute
a_args the arguments to use
Returns
the double return value
Author
Klaus Meffert
Since
3.0
Implemented in org.jgap.gp.impl.GPProgram.
float org.jgap.gp.IGPProgram.execute_float (int a_chromosomeNum, Object[] a_args)
Executes the given chromosome as a float function.
Parameters
a_chromosomeNum the index of the chromosome to execute
a_args the arguments to use
Returns
the floar return value
Author
Klaus Meffert
Since
3.0
Implemented in org.jgap.gp.impl.GPProgram.
int org.jgap.gp.IGPProgram.execute_int (int a_chromosomeNum, Object[] a_args)
Executes the given chromosome as an integer function.
Parameters
a_chromosomeNum the index of the chromosome to execute
a_args the arguments to use
Returns
the integer return value
Author
Klaus Meffert
Since
3.0
Implemented in org.jgap.gp.impl.GPProgram.
Object org.jgap.gp.IGPProgram.execute_object (int a_chromosomeNum, Object[] a_args)
Executes the given chromosome as an object function.
Parameters
a_chromosomeNum the index of the chromosome to execute
a_args the arguments to use
Returns
the object return value
Author
Klaus Meffert
Since
3.0
Implemented in org.jgap.gp.impl.GPProgram.
void org.jgap.gp.IGPProgram.execute_void (int a_chromosomeNum, Object[] a_args)
Executes the given chromosome as an object function.
Parameters
a_chromosomeNum the index of the chromosome to execute
a_args the arguments to use
Author
Klaus Meffert
Since
3.0
Implemented in org.jgap.gp.impl.GPProgram.
Object org.jgap.gp.IGPProgram.getApplicationData ()
Returns
the application data object set
Author
Klaus Meffert
Since
3.01
Implemented in org.jgap.gp.GPProgramBase.
Referenced by examples.gp.paintedDesert.PaintedDesertProblem.main(), and examples.gp.monalisa.gui.EvolutionRunnable.run().
Class [][] org.jgap.gp.IGPProgram.getArgTypes ()
Implemented in org.jgap.gp.GPProgramBase.
ProgramChromosome org.jgap.gp.IGPProgram.getChromosome (int a_index)
Parameters
a_index the chromosome to get
Returns
the ProgramChromosome with the given index
Author
Klaus Meffert
Since
3.0
Implemented in org.jgap.gp.impl.GPProgram.
Referenced by org.jgap.gp.impl.BranchTypingCross.operate(), and org.jgap.gp.impl.GPGenotypeTest.testRandomInitialize_0().
int org.jgap.gp.IGPProgram.getCommandOfClass (int a_chromosomeNum, Class a_class)
Searches for a chromosome that has the given class and returns its index.
Parameters
a_chromosomeNum the index of the chromosome to start the search with
a_class the class to find
Returns
the index of the first chromosome found that is of a_class, or -1
Author
Klaus Meffert
Since
3.0
Implemented in org.jgap.gp.impl.GPProgram.
double org.jgap.gp.IGPProgram.getFitnessValue ()
Returns
fitness value of this program
Author
Klaus Meffert
Since
3.0
Implemented in org.jgap.gp.GPProgramBase.
Referenced by org.jgap.gp.impl.GPGenotype.getFittestProgram(), org.jgap.gp.impl.DeltaGPFitnessEvaluator.isFitter(), examples.gp.monalisa.gui.EvolutionRunnable.run(), examples.gp.island.IslandGPThread.run(), and examples.gp.island.IslandGPExample.start().
GPConfiguration org.jgap.gp.IGPProgram.getGPConfiguration ()
Implemented in org.jgap.gp.GPProgramBase.
Referenced by org.jgap.gp.impl.GPGenotype.checkErroneousProg(), and examples.gp.Fibonacci.FormulaFitnessFunction.computeRawFitness().
int [] org.jgap.gp.IGPProgram.getMaxDepths ()
Implemented in org.jgap.gp.GPProgramBase.
int org.jgap.gp.IGPProgram.getMaxNodes ()
Implemented in org.jgap.gp.GPProgramBase.
int [] org.jgap.gp.IGPProgram.getMinDepths ()
Implemented in org.jgap.gp.GPProgramBase.
CommandGene [][] org.jgap.gp.IGPProgram.getNodeSets ()
Implemented in org.jgap.gp.GPProgramBase.
String org.jgap.gp.IGPProgram.getPersistentRepresentation ()
Returns
the persistent representation of the population, including all GP programs
Author
Klaus Meffert
Since
3.3
Implemented in org.jgap.gp.impl.GPProgram.
Class [] org.jgap.gp.IGPProgram.getTypes ()
Implemented in org.jgap.gp.GPProgramBase.
void org.jgap.gp.IGPProgram.setApplicationData (Object a_data)
Sets the application data object.
Parameters
a_data the object to set
Author
Klaus Meffert
Since
3.01
Implemented in org.jgap.gp.GPProgramBase.
void org.jgap.gp.IGPProgram.setArgTypes (Class a_argTypes[][])
Implemented in org.jgap.gp.GPProgramBase.
void org.jgap.gp.IGPProgram.setChromosome (int a_index, ProgramChromosome a_chrom)
Sets the given chromosome at the given index.
Parameters
a_index the index to the the chromosome at
a_chrom the chromosome to set
Author
Klaus Meffert
Since
3.0
void org.jgap.gp.IGPProgram.setFitnessValue (double a_fitness)
Implemented in org.jgap.gp.GPProgramBase.
void org.jgap.gp.IGPProgram.setMaxDepths (int[] a_maxDepths)
Implemented in org.jgap.gp.GPProgramBase.
void org.jgap.gp.IGPProgram.setMaxNodes (int a_maxNodes)
Implemented in org.jgap.gp.GPProgramBase.
void org.jgap.gp.IGPProgram.setMinDepths (int[] a_minDepths)
Implemented in org.jgap.gp.GPProgramBase.
void org.jgap.gp.IGPProgram.setNodeSets (CommandGene a_nodeSets[][])
Implemented in org.jgap.gp.GPProgramBase.
void org.jgap.gp.IGPProgram.setTypes (Class[] a_types)
Implemented in org.jgap.gp.GPProgramBase.
int org.jgap.gp.IGPProgram.size ()
Returns
the number of chromosomes in the program
Author
Klaus Meffert
Since
3.0
Implemented in org.jgap.gp.impl.GPProgram.
Referenced by org.jgap.gp.impl.GPGenotypeTest.computeFitness(), examples.gp.Fibonacci.FormulaFitnessFunction.computeRawFitness(), examples.gp.tictactoe.TicTacToeMain.GameFitnessFunction.computeRawFitness(), org.jgap.gp.function.ADF.getArity(), and org.jgap.gp.impl.BranchTypingCross.operate().
String org.jgap.gp.IGPProgram.toStringNorm (int a_startNode)
Builds a string that represents the normalized output of the GP program.
Parameters
a_startNode the node to start with
Returns
textual output in normalized notion
Author
Klaus Meffert
Since
3.0
Implemented in org.jgap.gp.impl.GPProgram.
Referenced by org.jgap.gp.impl.GPGenotype.calcFitness(), examples.gp.island.IslandGPThread.outputBestSolution(), and examples.gp.island.IslandGPExample.start().
Member Data Documentation
final String org.jgap.gp.IGPProgram.CVS_REVISION = `$Revision: 1.14 $` [static]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file IGPProgram.java.
The documentation for this interface was generated from the following file:
LDH_Git/src/org/jgap/gp/IGPProgram.java