org.jgap.gp.IGPFitnessEvaluator Interface Reference
Public Member Functions
boolean isFitter (double a_fitness_value1, double a_fitness_value2)
boolean isFitter (IGPProgram a_prog1, IGPProgram a_prog2)
Static Public Attributes
static final String CVS_REVISION = `$Revision: 1.6 $`
Detailed Description
Interface for a fitness evaluator used in a Genotype to determine how to interpret the fitness value. The fitness value can either be interpreted straight forward as a fitness indicator (the higher the better). Or it could be seen as a defect rate (the lower the better).
Author
Klaus Meffert
Since
3.0
Definition at line 21 of file IGPFitnessEvaluator.java.
Member Function Documentation
boolean org.jgap.gp.IGPFitnessEvaluator.isFitter (double a_fitness_value1, double a_fitness_value2)
Compares the first given fitness value with the second and returns true if the first one is fitter than the second one. Otherwise returns false.
Parameters
a_fitness_value1 first fitness value
a_fitness_value2 second fitness value
Returns
true: first fitness value fitter than second
Author
Klaus Meffert
Since
2.0 (until 1.1: input types int)
Referenced by org.jgap.gp.impl.GPGenotype.calcFitness(), org.jgap.gp.impl.GPProgramFitnessComparator.compare(), org.jgap.gp.impl.GPPopulation.determineFittestProgram(), org.jgap.gp.impl.GPPopulation.determineFittestProgramComputed(), and org.jgap.gp.impl.TournamentSelector.select().
boolean org.jgap.gp.IGPFitnessEvaluator.isFitter (IGPProgram a_prog1, IGPProgram a_prog2)
Implemented in org.jgap.gp.impl.DeltaGPFitnessEvaluator, and org.jgap.gp.impl.DefaultGPFitnessEvaluator.
Member Data Documentation
final String org.jgap.gp.IGPFitnessEvaluator.CVS_REVISION = `$Revision: 1.6 $` [static]
String containing the CVS revision. Read out via reflection!
Definition at line 24 of file IGPFitnessEvaluator.java.
The documentation for this interface was generated from the following file:
LDH_Git/src/org/jgap/gp/IGPFitnessEvaluator.java