org.jgap.Gene Interface Reference
Public Member Functions
Gene newGene ()
void setAllele (Object a_newValue)
Object getAllele ()
String getPersistentRepresentation () throws UnsupportedOperationException
void setValueFromPersistentRepresentation (String a_representation) throws UnsupportedOperationException, UnsupportedRepresentationException
void setToRandomValue (RandomGenerator a_numberGenerator)
void cleanup ()
String toString ()
int size ()
void applyMutation (int index, double a_percentage)
void setApplicationData (Object a_newData)
Object getApplicationData ()
void setCompareApplicationData (boolean a_doCompare)
boolean isCompareApplicationData ()
double getEnergy ()
void setEnergy (double a_energy)
void setConstraintChecker (final IGeneConstraintChecker a_constraintChecker)
Configuration getConfiguration ()
Static Public Attributes
static final String CVS_REVISION = `$Revision: 1.26 $`
static final String PERSISTENT_FIELD_DELIMITER = `:`
Detailed Description
Genes represent the discrete components of a potential solution (the Chromosome). This interface exists so that custom gene implementations can be easily plugged-in, which can add a great deal of flexibility and convenience for many applications. Note that it's very important that implementations of this interface also implement the equals() method. Without a proper implementation of equals(), some genetic operations will fail to work properly.
When implementing a new Gene type, extend it from org.jgap.BaseGene!
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 29 of file Gene.java.
Member Function Documentation
void org.jgap.Gene.applyMutation (int index, double a_percentage)
Applies a mutation of a given intensity (percentage) onto the atomic element at given index (NumberGenes only have one atomic element)
Parameters
index index of atomic element, between 0 and size()-1
a_percentage percentage of mutation (greater than -1 and smaller than 1).
Since
1.1
Implemented in org.jgap.impl.CompositeGene, org.jgap.impl.StringGene, org.jgap.impl.NumberGeneTest.NumberGeneImpl, org.jgap.impl.BooleanGene, and org.jgap.impl.DoubleGene.
void org.jgap.Gene.cleanup ()
Executed by the genetic engine when this Gene instance is no longer needed and should perform any necessary resource cleanup.
Implemented in org.jgap.supergenes.AbstractSupergene, org.jgap.impl.CompositeGene, and org.jgap.BaseGene.
Object org.jgap.Gene.getAllele ()
Retrieves the value represented by this Gene. The actual type of the value is implementation-dependent.
Returns
the value of this Gene.
Since
1.0
Implemented in org.jgap.impl.CompositeGene, org.jgap.supergenes.AbstractSupergene, org.jgap.impl.FixedBinaryGene, and org.jgap.BaseGene.
Referenced by org.jgap.impl.StringGeneTest.testApplyMutation_4(), org.jgap.impl.StringGeneTest.testApplyMutation_5(), org.jgap.impl.IntegerGeneTest.testCompareToNative_0(), org.jgap.impl.DoubleGeneTest.testCompareToNative_0(), org.jgap.impl.IntegerGeneTest.testCompareToNative_1(), org.jgap.impl.DoubleGeneTest.testCompareToNative_1(), org.jgap.impl.IntegerGeneTest.testCompareToNative_2(), org.jgap.impl.DoubleGeneTest.testCompareToNative_2(), org.jgap.impl.IntegerGeneTest.testCompareToNative_3(), org.jgap.impl.DoubleGeneTest.testCompareToNative_3(), org.jgap.impl.IntegerGeneTest.testCompareToNative_4(), org.jgap.impl.DoubleGeneTest.testCompareToNative_4(), org.jgap.impl.IntegerGeneTest.testGetAllele_0(), org.jgap.impl.NumberGeneTest.testGetAllele_0(), org.jgap.BaseGeneTest.testGetAllele_0(), org.jgap.impl.DoubleGeneTest.testGetAllele_0(), org.jgap.impl.FixedBinaryGeneTest.testGetAllele_0(), org.jgap.impl.StringGeneTest.testGetAllele_0(), org.jgap.impl.IntegerGeneTest.testGetAllele_1(), org.jgap.impl.NumberGeneTest.testGetAllele_1(), org.jgap.impl.DoubleGeneTest.testGetAllele_1(), org.jgap.impl.IntegerGeneTest.testGetAllele_2(), org.jgap.impl.NumberGeneTest.testGetAllele_2(), org.jgap.impl.DoubleGeneTest.testGetAllele_2(), org.jgap.impl.FixedBinaryGeneTest.testGetAllele_2(), org.jgap.impl.FixedBinaryGeneTest.testHashCode_1(), org.jgap.impl.IntegerGeneTest.testIntegerGeneSupportsFullIntegerRange(), org.jgap.impl.GaussianMutationOperatorTest.testOperate_2(), org.jgap.impl.MapGeneTest.testPersistentRepresentation_3(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_6(), org.jgap.impl.DoubleGeneTest.testSetToRandomValue_0(), org.jgap.impl.MapGeneTest.testSetToRandomValue_0(), org.jgap.impl.IntegerGeneTest.testSetToRandomValue_0(), org.jgap.impl.DoubleGeneTest.testSetToRandomValue_1(), org.jgap.impl.IntegerGeneTest.testSetToRandomValue_1(), org.jgap.impl.StringGeneTest.testSetToRandomValue_1(), org.jgap.impl.DoubleGeneTest.testSetToRandomValue_2(), org.jgap.impl.IntegerGeneTest.testSetToRandomValue_2(), org.jgap.impl.StringGeneTest.testSetToRandomValue_2(), and org.jgap.impl.IntegerGeneTest.testSetToRandomValue_5().
Object org.jgap.Gene.getApplicationData ()
Retrieves the application-specific data that is attached to this Gene. Attaching application-specific data may be useful for some applications when it comes time to distinguish a Gene from another. JGAP ignores this data functionally.
Returns
the application-specific data previously attached to this Gene, or null if there is no data attached
Author
Klaus Meffert
Since
2.4
Implemented in org.jgap.BaseGene.
Referenced by org.jgap.BaseGene.equals().
Configuration org.jgap.Gene.getConfiguration ()
Returns
the configuration used
Author
Klaus Meffert
Since
3.0
Implemented in org.jgap.BaseGene.
double org.jgap.Gene.getEnergy ()
Returns
energy of the gene
Author
Klaus Meffert
Since
2.3
Implemented in org.jgap.BaseGene.
Referenced by org.jgap.GenotypeTest.testRandomInitialGenotype_2().
String org.jgap.Gene.getPersistentRepresentation () throws UnsupportedOperationException
Retrieves a string representation of the value of this Gene instance that includes any information required to reconstruct it at a later time, such as its value and internal state. This string will be used to represent this Gene instance in XML persistence. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Returns
string representation of this Gene's current state
Exceptions
UnsupportedOperationException to indicate that no implementation is provided for this method
Since
1.0
Implemented in org.jgap.impl.NumberGeneTest.NumberGeneImpl, org.jgap.supergenes.AbstractSupergene, org.jgap.impl.MapGene, org.jgap.impl.CompositeGene, org.jgap.impl.StringGene, org.jgap.impl.FixedBinaryGene, org.jgap.impl.SetGene, org.jgap.impl.BooleanGene, org.jgap.impl.MutipleIntegerGene, org.jgap.impl.IntegerGene, and org.jgap.impl.DoubleGene.
Referenced by org.jgap.BaseChromosome.getGenesPersistentRepresentation().
boolean org.jgap.Gene.isCompareApplicationData ()
Implemented in org.jgap.BaseGene.
Gene org.jgap.Gene.newGene ()
Provides an implementation-independent means for creating new Gene instances. The new instance that is created and returned should be setup with any implementation-dependent configuration that this Gene instance is setup with (aside from the actual value, of course). For example, if this Gene were setup with bounds on its value, then the Gene instance returned from this method should also be setup with those same bounds. This is important, as the JGAP core will invoke this method on each Gene in the sample Chromosome in order to create each new Gene in the same respective gene position for a new Chromosome.
It should be noted that nothing is guaranteed about the actual value of the returned Gene and it should therefore be considered to be undefined.
Returns
a new Gene instance of the same type and with the same setup as this concrete Gene
Since
1.0
Implemented in org.jgap.BaseGene.
Referenced by org.jgap.Chromosome.initFromGene().
void org.jgap.Gene.setAllele (Object a_newValue)
Sets the value of this Gene to the new given value. The actual type of the value is implementation-dependent.
Parameters
a_newValue the new value of this Gene instance
Since
1.0
Implemented in org.jgap.impl.CompositeGene, org.jgap.impl.MapGene, and org.jgap.impl.SetGene.
void org.jgap.Gene.setApplicationData (Object a_newData)
This sets the application-specific data that is attached to this Gene. Attaching application-specific data may be useful for some applications when it comes time to distinguish a Gene from another. JGAP ignores this data functionally.
Parameters
a_newData the new application-specific data to attach to this Gene
Author
Klaus Meffert
Since
2.4
void org.jgap.Gene.setCompareApplicationData (boolean a_doCompare)
Should we also consider the application data when comparing? Default is `false` as `true` means a Gene is losing its identity when application data is set differently!
Parameters
a_doCompare true: consider application data in method compareTo
Author
Klaus Meffert
Since
2.4
void org.jgap.Gene.setConstraintChecker (final IGeneConstraintChecker a_constraintChecker)
Sets the constraint checker to be used for this gene whenever method setAllele(Object) is called.
Parameters
a_constraintChecker the constraint checker to be set
Author
Klaus Meffert
Since
2.6 (moved from CompositeGene, where it was since 2.0)
Implemented in org.jgap.BaseGene.
void org.jgap.Gene.setEnergy (double a_energy)
Sets the energy of the gene
Parameters
a_energy the energy to set
Author
Klaus Meffert
Since
2.3
void org.jgap.Gene.setToRandomValue (RandomGenerator a_numberGenerator)
Sets the value of this Gene to a random legal value for the implementation. This method exists for the benefit of mutation and other operations that simply desire to randomize the value of a gene.
Parameters
a_numberGenerator The random number generator that should be used to create any random values. It's important to use this generator to maintain the user's flexibility to configure the genetic engine to use the random number generator of their choice
Since
1.0
Implemented in org.jgap.impl.NumberGeneTest.NumberGeneImpl, org.jgap.impl.DoubleGene, and org.jgap.impl.BooleanGene.
void org.jgap.Gene.setValueFromPersistentRepresentation (String a_representation) throws UnsupportedOperationException, UnsupportedRepresentationException
Sets the value and internal state of this Gene from the string representation returned by a previous invocation of the getPersistentRepresentation() method. This is an optional method but, if not implemented, XML persistence and possibly other features will not be available. An UnsupportedOperationException should be thrown if no implementation is provided.
Parameters
a_representation the string representation retrieved from a prior call to the getPersistentRepresentation() method
Exceptions
UnsupportedOperationException to indicate that no implementation is provided for this method
UnsupportedRepresentationException if this Gene implementation does not support the given string representation
Since
1.0
Implemented in org.jgap.impl.NumberGeneTest.NumberGeneImpl, org.jgap.supergenes.AbstractSupergene, org.jgap.impl.FixedBinaryGene, org.jgap.impl.CompositeGene, org.jgap.impl.BooleanGene, org.jgap.impl.DoubleGene, and org.jgap.impl.SetGene.
int org.jgap.Gene.size ()
Returns
the size of the gene, i.e the number of atomic elements. Always 1 for numbers
Since
1.1
Implemented in org.jgap.impl.CompositeGene, org.jgap.supergenes.AbstractSupergene, org.jgap.impl.StringGene, org.jgap.impl.FixedBinaryGene, and org.jgap.BaseGene.
Referenced by org.jgap.BaseGeneTest.testSize_0().
String org.jgap.Gene.toString ()
Returns
a string representation of the gene
Since
1.1 (in the interface)
Implemented in org.jgap.impl.MapGene, org.jgap.impl.CompositeGene, org.jgap.supergenes.AbstractSupergene, org.jgap.impl.StringGene, org.jgap.impl.BooleanGene, org.jgap.impl.MutipleIntegerGene, org.jgap.impl.IntegerGene, org.jgap.impl.DoubleGene, org.jgap.impl.FixedBinaryGene, and org.jgap.BaseGene.
Referenced by org.jgap.BaseGeneTest.testToString_0(), org.jgap.impl.IntegerGeneTest.testToString_0(), org.jgap.impl.NumberGeneTest.testToString_0(), org.jgap.impl.DoubleGeneTest.testToString_0(), org.jgap.impl.BooleanGeneTest.testToString_0(), org.jgap.impl.FixedBinaryGeneTest.testToString_0(), org.jgap.impl.StringGeneTest.testToString_0(), org.jgap.impl.IntegerGeneTest.testToString_1(), org.jgap.BaseGeneTest.testToString_1(), org.jgap.impl.DoubleGeneTest.testToString_1(), org.jgap.impl.BooleanGeneTest.testToString_1(), org.jgap.impl.FixedBinaryGeneTest.testToString_1(), org.jgap.BaseGeneTest.testToString_2(), org.jgap.impl.DoubleGeneTest.testToString_2(), org.jgap.impl.BooleanGeneTest.testToString_2(), org.jgap.impl.FixedBinaryGeneTest.testToString_2(), and org.jgap.supergenes.SupergenePersistentRepresentationTest.testToString_2().
Member Data Documentation
final String org.jgap.Gene.CVS_REVISION = `$Revision: 1.26 $` [static]
String containing the CVS revision. Read out via reflection!
Definition at line 32 of file Gene.java.
final String org.jgap.Gene.PERSISTENT_FIELD_DELIMITER = `:` [static]
Represents the delimiter that is used to separate fields in the persistent representation.
Definition at line 38 of file Gene.java.
Referenced by org.jgap.impl.StringGene.getBusinessKey(), org.jgap.BaseGene.getBusinessKey(), org.jgap.impl.DoubleGene.getPersistentRepresentation(), org.jgap.impl.IntegerGene.getPersistentRepresentation(), org.jgap.impl.MutipleIntegerGene.getPersistentRepresentation(), org.jgap.impl.SetGene.getPersistentRepresentation(), org.jgap.impl.StringGene.getPersistentRepresentation(), org.jgap.impl.MapGene.getPersistentRepresentation(), org.jgap.impl.NumberGeneTest.NumberGeneImpl.getPersistentRepresentation(), org.jgap.impl.SetGene.setValueFromPersistentRepresentation(), org.jgap.impl.DoubleGene.setValueFromPersistentRepresentation(), org.jgap.impl.IntegerGene.setValueFromPersistentRepresentation(), org.jgap.impl.MutipleIntegerGene.setValueFromPersistentRepresentation(), org.jgap.impl.StringGene.setValueFromPersistentRepresentation(), org.jgap.impl.MapGene.setValueFromPersistentRepresentation(), org.jgap.impl.StringGeneTest.testPersistentRepresentation_5_2(), and org.jgap.impl.IntegerGeneTest.testPersistentRepresentation_6().
The documentation for this interface was generated from the following file:
LDH_Git/src/org/jgap/Gene.java