org.jgap.FitnessEvaluator Interface Reference
Public Member Functions
boolean isFitter (double a_fitness_value1, double a_fitness_value2)
boolean isFitter (IChromosome a_chrom1, IChromosome a_chrom2)
Static Public Attributes
static final String CVS_REVISION = `$Revision: 1.9 $`
Detailed Description
Interface for a fitness evaluator used in a Genotype to determine how to interpret the fitness value. The fitness value can either be interpreted straight forward as a fitness indicator (the higher the better). Or it could be seen as a defect rate (the lower the better).
Author
Klaus Meffert
Since
1.1
Definition at line 23 of file FitnessEvaluator.java.
Member Function Documentation
boolean org.jgap.FitnessEvaluator.isFitter (double a_fitness_value1, double a_fitness_value2)
Compares the first given fitness value with the second and returns true if the first one is greater than the second one. Otherwise returns false
Parameters
a_fitness_value1 first fitness value
a_fitness_value2 second fitness value
Returns
true: first fitness value greater than second
Author
Klaus Meffert
Since
2.0 (until 1.1: input types int)
Referenced by org.jgap.util.ChromosomeFitnessComparator.compare(), org.jgap.impl.FittestPopulationMerger.FitnessChromosomeComparator.compare(), org.jgap.Chromosome.compareTo(), org.jgap.Population.determineFittestChromosome(), org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_0(), org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_0(), org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_1(), org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_1(), org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_2(), org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_2(), org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_3(), org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_3(), org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_4(), org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_4(), org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_5(), org.jgap.DefaultFitnessEvaluatorTest.testIsFitter_5(), and org.jgap.DeltaFitnessEvaluatorTest.testIsFitter_6().
boolean org.jgap.FitnessEvaluator.isFitter (IChromosome a_chrom1, IChromosome a_chrom2)
Implemented in org.jgap.DeltaFitnessEvaluator, and org.jgap.DefaultFitnessEvaluator.
Member Data Documentation
final String org.jgap.FitnessEvaluator.CVS_REVISION = `$Revision: 1.9 $` [static]
String containing the CVS revision. Read out via reflection!
Definition at line 26 of file FitnessEvaluator.java.
The documentation for this interface was generated from the following file:
LDH_Git/src/org/jgap/FitnessEvaluator.java