org.jgap.util.ICloneable Interface Reference
Inherits Cloneable.
Inherited by examples.gp.tictactoe.CountStones, examples.gp.tictactoe.EvaluateBoard, examples.gp.tictactoe.IfColor, examples.gp.tictactoe.IfIsFree, examples.gp.tictactoe.IfIsOccupied, examples.gp.tictactoe.IsOwnColor, examples.gp.tictactoe.PutStone, examples.gp.tictactoe.PutStone1, examples.gp.tictactoe.ReadBoard, examples.gp.tictactoe.TransferBoardToMemory, org.jgap.audit.KeyedValue, org.jgap.audit.KeyedValues, org.jgap.audit.KeyedValues2D, org.jgap.BulkFitnessFunction, org.jgap.Configuration, org.jgap.DefaultFitnessEvaluator, org.jgap.DeltaFitnessEvaluator, org.jgap.distr.grid.DefaultEvolveStrategy, org.jgap.distr.grid.gp.DefaultEvolveStrategyGP, org.jgap.distr.grid.gp.JGAPRequestGP, org.jgap.distr.grid.JGAPRequest, org.jgap.event.EventManager, org.jgap.FitnessFunction, org.jgap.GenotypeTest.TestConfiguration, org.jgap.gp.function.Abs, org.jgap.gp.function.Add, org.jgap.gp.function.Add3, org.jgap.gp.function.Add4, org.jgap.gp.function.AddAndStore, org.jgap.gp.function.AddAndStoreTerminal, org.jgap.gp.function.And, org.jgap.gp.function.ArcCosine, org.jgap.gp.function.ArcSine, org.jgap.gp.function.ArcTangent, org.jgap.gp.function.Ceil, org.jgap.gp.function.CharacterProvider, org.jgap.gp.function.Cosine, org.jgap.gp.function.CountMatrix, org.jgap.gp.function.Divide, org.jgap.gp.function.Equals, org.jgap.gp.function.ExchangeMemory, org.jgap.gp.function.Exp, org.jgap.gp.function.Floor, org.jgap.gp.function.ForLoop, org.jgap.gp.function.ForXLoop, org.jgap.gp.function.GreaterThan, org.jgap.gp.function.If, org.jgap.gp.function.IfDyn, org.jgap.gp.function.IfElse, org.jgap.gp.function.Increment, org.jgap.gp.function.IncrementMemory, org.jgap.gp.function.LesserThan, org.jgap.gp.function.Log, org.jgap.gp.function.Loop, org.jgap.gp.function.Max, org.jgap.gp.function.Mean, org.jgap.gp.function.Min, org.jgap.gp.function.Modulo, org.jgap.gp.function.Multiply, org.jgap.gp.function.Multiply3, org.jgap.gp.function.Not, org.jgap.gp.function.Or, org.jgap.gp.function.Pop, org.jgap.gp.function.Pow, org.jgap.gp.function.Push, org.jgap.gp.function.RandomGenerator, org.jgap.gp.function.ReadFromMatrix, org.jgap.gp.function.ReadTerminal, org.jgap.gp.function.ReadTerminalIndexed, org.jgap.gp.function.ReplaceInMatrix, org.jgap.gp.function.ResetMatrix, org.jgap.gp.function.Round, org.jgap.gp.function.Sine, org.jgap.gp.function.statistics.Kurtosis, org.jgap.gp.function.statistics.Mean, org.jgap.gp.function.statistics.Skewness, org.jgap.gp.function.statistics.StandardDeviation, org.jgap.gp.function.statistics.Variance, org.jgap.gp.function.StoreTerminal, org.jgap.gp.function.StoreTerminalIndexed, org.jgap.gp.function.SubProgram, org.jgap.gp.function.Subtract, org.jgap.gp.function.Switch, org.jgap.gp.function.Tangent, org.jgap.gp.function.TransferMemory, org.jgap.gp.function.Tupel, org.jgap.gp.function.WriteToMatrix, org.jgap.gp.function.Xor, org.jgap.gp.IGPProgram, org.jgap.gp.impl.GPProgram, org.jgap.gp.terminal.Constant, org.jgap.gp.terminal.False, org.jgap.gp.terminal.Terminal, org.jgap.gp.terminal.True, org.jgap.IBreeder, org.jgap.IChromosome, org.jgap.impl.BestChromosomesSelector, org.jgap.impl.ChainOfSelectors, org.jgap.impl.DefaultCloneHandler, org.jgap.impl.DefaultCompareToHandler, org.jgap.impl.DefaultConfiguration, org.jgap.impl.DefaultInitializer, org.jgap.impl.JGAPFactory, org.jgap.impl.SeededRandomGenerator, org.jgap.impl.StandardPostSelector, org.jgap.impl.StockRandomGenerator, org.jgap.impl.WeightedRouletteSelector, and org.jgap.Population.
Public Member Functions
Object clone ()
Static Public Attributes
static final String CVS_REVISION = `$Revision: 1.3 $`
Detailed Description
Interface introducing the clone method that should already be there with java.lang.Cloneable!
Author
Klaus Meffert
Since
3.1
Definition at line 10 of file ICloneable.java.
Member Function Documentation
Object org.jgap.util.ICloneable.clone ()
Returns
clone of the current object instance
Implemented in org.jgap.Configuration, org.jgap.GenotypeTest.MyChromosome, org.jgap.gp.impl.GPConfiguration, org.jgap.Population, org.jgap.gp.impl.GPProgram, org.jgap.impl.BulkFitnessOffsetRemover, org.jgap.impl.WeightedRouletteSelector, org.jgap.gp.terminal.Terminal, org.jgap.impl.JGAPFactory, org.jgap.Chromosome, org.jgap.gp.function.ForLoop, org.jgap.impl.BestChromosomesSelector, org.jgap.audit.KeyedValues2D, org.jgap.gp.function.SubProgram, org.jgap.impl.GABreeder, org.jgap.distr.grid.gp.JGAPRequestGP, org.jgap.gp.GPProgramBase, org.jgap.gp.function.CountMatrix, org.jgap.audit.KeyedValues, org.jgap.gp.function.ReplaceInMatrix, org.jgap.distr.grid.JGAPRequest, org.jgap.gp.function.StoreTerminal, org.jgap.impl.StandardPostSelector, org.jgap.gp.function.AddAndStoreTerminal, org.jgap.gp.function.StoreTerminalIndexed, org.jgap.gp.function.WriteToMatrix, org.jgap.gp.function.ReadTerminalIndexed, org.jgap.gp.function.ReadTerminal, org.jgap.impl.ChainOfSelectors, org.jgap.gp.function.Push, org.jgap.BreederBase, org.jgap.gp.function.IfElse, org.jgap.gp.function.IncrementMemory, org.jgap.gp.function.ExchangeMemory, org.jgap.BaseChromosome, org.jgap.gp.function.Increment, org.jgap.gp.function.TransferMemory, org.jgap.impl.DefaultCloneHandler, org.jgap.gp.function.ReadFromMatrix, org.jgap.gp.function.Switch, org.jgap.gp.function.ForXLoop, org.jgap.gp.function.Loop, org.jgap.audit.KeyedValue, org.jgap.gp.function.AddAndStore, examples.gp.tictactoe.EvaluateBoard, org.jgap.gp.function.If, examples.gp.tictactoe.CountStones, org.jgap.gp.function.ResetMatrix, org.jgap.gp.function.CharacterProvider, examples.gp.tictactoe.IfColor, org.jgap.event.EventManager, org.jgap.gp.function.Tupel, org.jgap.ChromosomeForTesting, org.jgap.FitnessFunction, examples.gp.tictactoe.IfIsOccupied, org.jgap.gp.function.Pop, examples.gp.tictactoe.IfIsFree, org.jgap.gp.function.Modulo, examples.gp.tictactoe.PutStone, examples.gp.tictactoe.PutStone1, org.jgap.gp.function.Equals, org.jgap.gp.function.LesserThan, org.jgap.gp.function.GreaterThan, org.jgap.impl.DefaultCompareToHandler, org.jgap.gp.function.Pow, org.jgap.gp.function.Add4, org.jgap.gp.function.Multiply3, org.jgap.gp.function.Add3, org.jgap.gp.terminal.Constant, examples.gp.tictactoe.TransferBoardToMemory, org.jgap.impl.DefaultConfiguration, org.jgap.gp.function.IfDyn, org.jgap.gp.function.Exp, org.jgap.gp.function.statistics.Kurtosis, org.jgap.impl.SeededRandomGenerator, org.jgap.gp.function.Or, org.jgap.gp.function.Cosine, org.jgap.gp.function.Sine, org.jgap.gp.function.Ceil, org.jgap.gp.function.Floor, org.jgap.gp.function.statistics.Skewness, org.jgap.gp.function.Abs, org.jgap.gp.function.ArcCosine, org.jgap.gp.function.ArcSine, org.jgap.gp.function.ArcTangent, org.jgap.gp.function.Log, org.jgap.gp.function.Tangent, org.jgap.gp.function.Xor, org.jgap.gp.function.statistics.Variance, examples.gp.tictactoe.ReadBoard, org.jgap.gp.function.Max, org.jgap.gp.function.Min, org.jgap.gp.function.statistics.StandardDeviation, org.jgap.gp.function.Round, org.jgap.gp.function.RandomGenerator, org.jgap.DeltaFitnessEvaluator, org.jgap.impl.DefaultInitializer, examples.gp.tictactoe.IsOwnColor, org.jgap.gp.function.Mean, org.jgap.gp.function.Not, org.jgap.gp.function.And, org.jgap.gp.function.statistics.Mean, org.jgap.impl.StockRandomGenerator, org.jgap.BulkFitnessFunction, org.jgap.gp.terminal.False, org.jgap.gp.terminal.True, org.jgap.DefaultFitnessEvaluator, org.jgap.gp.function.Add, org.jgap.gp.function.Divide, org.jgap.gp.function.Multiply, org.jgap.gp.function.Subtract, org.jgap.distr.grid.gp.DefaultEvolveStrategyGP, and org.jgap.distr.grid.DefaultEvolveStrategy.
Referenced by org.jgap.Population.clone(), org.jgap.gp.impl.GPPopulation.GPPopulation(), org.jgap.Configuration.newInstance(), org.jgap.impl.InversionOperator.operate(), org.jgap.impl.GaussianMutationOperator.operate(), org.jgap.impl.GreedyCrossover.operate(), org.jgap.impl.TwoWayMutationOperator.operate(), org.jgap.impl.MutationOperator.operate(), org.jgap.impl.AveragingCrossoverOperator.operate(), org.jgap.impl.SwappingMutationOperator.operate(), org.jgap.impl.RangedSwappingMutationOperator.operate(), org.jgap.impl.CrossoverOperator.operate(), examples.gp.island.IslandGPThread.run(), org.jgap.ChromosomeTest.testClone_7(), and org.jgap.ChromosomeTest.testClone_8().
Member Data Documentation
final String org.jgap.util.ICloneable.CVS_REVISION = `$Revision: 1.3 $` [static]
String containing the CVS revision. Read out via reflection!
Definition at line 13 of file ICloneable.java.
The documentation for this interface was generated from the following file:
LDH_Git/src/org/jgap/util/ICloneable.java