org.jgap.RandomGenerator Interface Reference
Public Member Functions
int nextInt ()
int nextInt (int a_ceiling)
long nextLong ()
double nextDouble ()
float nextFloat ()
boolean nextBoolean ()
Static Public Attributes
static final String CVS_REVISION = `$Revision: 1.8 $`
Detailed Description
The RandomGenerator interface provides an abstraction for the random number implementation so that more rigorous or alternative implementations can be provided as desired.
ATTENTION: nextDouble should only return values betwen 0 (inclusive) and 1 (exclusive!). The same holds for nextFloat.
Author
Neil Rotstan
Klaus Meffert
Since
1.0
Definition at line 26 of file RandomGenerator.java.
Member Function Documentation
boolean org.jgap.RandomGenerator.nextBoolean ()
Returns the next pseudorandom, uniformly distributed boolean value from this random number generator's sequence. The general contract of nextBoolean is that one boolean value is pseudorandomly generated and returned. The values true and false are produced with (approximately) equal probability.
Returns
a pseudorandom boolean value
Author
Neil Rotstan
Since
1.0
Implemented in org.jgap.impl.GaussianRandomGenerator, org.jgap.impl.RandomGeneratorForTesting, org.jgap.impl.CauchyRandomGenerator, and org.jgap.impl.HotBitsRandomGenerator.
Referenced by org.jgap.impl.BooleanGene.setToRandomValue(), and org.jgap.impl.FixedBinaryGene.setToRandomValue().
double org.jgap.RandomGenerator.nextDouble ()
Returns the next pseudorandom, uniformly distributed double value between 0.0 and 1.0 from this random number generator's sequence.
Returns
a psuedorandom double value GREATER/EQUAL 0 AND LESS THAN 1
Author
Neil Rotstan
Since
1.0
Implemented in org.jgap.impl.GaussianRandomGenerator, org.jgap.impl.RandomGeneratorForTesting, org.jgap.impl.CauchyRandomGenerator, and org.jgap.impl.HotBitsRandomGenerator.
Referenced by org.jgap.gp.impl.BranchTypingCross.doCross(), org.jgap.impl.MutipleIntegerGene.getRandomValue(), org.jgap.gp.impl.ProgramChromosome.growOrFullNode(), org.jgap.impl.DoubleGene.mapValueToWithinBounds(), org.jgap.distr.grid.gp.JGAPClientGP.presetPopulation(), org.jgap.gp.impl.TournamentSelector.select(), org.jgap.gp.terminal.Terminal.setRandomValue(), org.jgap.impl.DoubleGene.setToRandomValue(), and org.jgap.impl.IntegerGene.setToRandomValue().
float org.jgap.RandomGenerator.nextFloat ()
Returns the next pseudorandom, uniformly distributed float value between 0.0 and 1.0 from this random number generator's sequence.
Returns
a psuedorandom float value
Author
Neil Rotstan
Since
1.0
Implemented in org.jgap.impl.GaussianRandomGenerator, org.jgap.impl.RandomGeneratorForTesting, org.jgap.impl.CauchyRandomGenerator, and org.jgap.impl.HotBitsRandomGenerator.
Referenced by org.jgap.gp.impl.BranchTypingCross.doCross(), and org.jgap.gp.terminal.Terminal.setRandomValue().
int org.jgap.RandomGenerator.nextInt ()
Returns the next pseudorandom, uniformly distributed int value from this random number generator's sequence. The general contract of nextInt is that one int value is pseudorandomly generated and returned. All 2^32 possible int values are produced with (approximately) equal probability.
Returns
a pseudorandom integer value
Author
Neil Rotstan
Since
1.0
Implemented in org.jgap.impl.GaussianRandomGenerator, org.jgap.impl.RandomGeneratorForTesting, org.jgap.impl.CauchyRandomGenerator, and org.jgap.impl.HotBitsRandomGenerator.
Referenced by org.jgap.gp.impl.GPGenotype.evolve(), org.jgap.impl.AveragingCrossoverOperator.getLocus(), org.jgap.impl.SwappingMutationOperator.operate(), org.jgap.impl.RangedSwappingMutationOperator.operate(), org.jgap.impl.SetGene.setToRandomValue(), org.jgap.impl.MapGene.setToRandomValue(), and org.jgap.impl.DefaultMutationRateCalculator.toBePermutated().
int org.jgap.RandomGenerator.nextInt (int a_ceiling)
Returns a pseudorandom, uniformly distributed int value between 0 (inclusive) and the specified value (exclusive), drawn from this random number generator's sequence. The general contract of nextInt is that one int value in the specified range is pseudorandomly generated and returned. All n possible int values are produced with (approximately) equal probability.
Parameters
a_ceiling the upper boundary excluded
Returns
a pseudorandom integer value between 0 and the given ceiling - 1, inclusive
Author
Neil Rotstan
Since
1.0
Implemented in org.jgap.impl.RandomGeneratorForTesting, and org.jgap.impl.HotBitsRandomGenerator.
long org.jgap.RandomGenerator.nextLong ()
Returns the next pseudorandom, uniformly distributed long value from this random number generator's sequence. The general contract of nextLong() is that one long value is pseudorandomly generated and returned. All 2^64 possible long values are produced with (approximately) equal probability.
Returns
a psuedorandom long value
Author
Neil Rotstan
Since
1.0
Implemented in org.jgap.impl.GaussianRandomGenerator, org.jgap.impl.RandomGeneratorForTesting, org.jgap.impl.CauchyRandomGenerator, and org.jgap.impl.HotBitsRandomGenerator.
Member Data Documentation
final String org.jgap.RandomGenerator.CVS_REVISION = `$Revision: 1.8 $` [static]
String containing the CVS revision. Read out via reflection!
Definition at line 29 of file RandomGenerator.java.
The documentation for this interface was generated from the following file:
LDH_Git/src/org/jgap/RandomGenerator.java