.TH "LDH_Git/tests/org/jgap/xml Directory Reference" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LDH_Git/tests/org/jgap/xml Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAllXMLTests\&.java\fP"
.br
.ti -1c
.RI "file \fBXMLDocumentBuilderTest\&.java\fP"
.br
.ti -1c
.RI "file \fBXMLManagerTest\&.java\fP"
.br
.in -1c
