.TH "LDH_Git/src/org/jgap/gui Directory Reference" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LDH_Git/src/org/jgap/gui Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBConfigFrame\&.java\fP"
.br
.ti -1c
.RI "file \fBGUIManager\&.java\fP"
.br
.in -1c
