.TH "LDH_Git/src/org/jgap/distr/grid Directory Reference" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LDH_Git/src/org/jgap/distr/grid Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcommon\fP"
.br
.ti -1c
.RI "directory \fBgp\fP"
.br
.ti -1c
.RI "directory \fBrequest\fP"
.br
.ti -1c
.RI "directory \fButil\fP"
.br
.ti -1c
.RI "directory \fBwan\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDefaultClientFeedback\&.java\fP"
.br
.ti -1c
.RI "file \fBDefaultEvolveStrategy\&.java\fP"
.br
.ti -1c
.RI "file \fBDefaultGenotypeInitializer\&.java\fP"
.br
.ti -1c
.RI "file \fBDefaultWorkerReturnStrategy\&.java\fP"
.br
.ti -1c
.RI "file \fBDummyGridClientMediator\&.java\fP"
.br
.ti -1c
.RI "file \fBGridConfigurationBase\&.java\fP"
.br
.ti -1c
.RI "file \fBIClientEvolveStrategy\&.java\fP"
.br
.ti -1c
.RI "file \fBIClientFeedback\&.java\fP"
.br
.ti -1c
.RI "file \fBIEvolveStrategy\&.java\fP"
.br
.ti -1c
.RI "file \fBIGenotypeInitializer\&.java\fP"
.br
.ti -1c
.RI "file \fBIGridClientMediator\&.java\fP"
.br
.ti -1c
.RI "file \fBIGridConfiguration\&.java\fP"
.br
.ti -1c
.RI "file \fBIGridMasterConnectionListener\&.java\fP"
.br
.ti -1c
.RI "file \fBIRequestSplitStrategy\&.java\fP"
.br
.ti -1c
.RI "file \fBIResultMergeStrategy\&.java\fP"
.br
.ti -1c
.RI "file \fBIWorkerEvolveStrategy\&.java\fP"
.br
.ti -1c
.RI "file \fBIWorkerReturnStrategy\&.java\fP"
.br
.ti -1c
.RI "file \fBJGAPAdmin\&.java\fP"
.br
.ti -1c
.RI "file \fBJGAPClient\&.java\fP"
.br
.ti -1c
.RI "file \fBJGAPClientHandlerThread\&.java\fP"
.br
.ti -1c
.RI "file \fBJGAPRequest\&.java\fP"
.br
.ti -1c
.RI "file \fBJGAPResult\&.java\fP"
.br
.ti -1c
.RI "file \fBJGAPServer\&.java\fP"
.br
.ti -1c
.RI "file \fBJGAPWorker\&.java\fP"
.br
.ti -1c
.RI "file \fBJGAPWorkers\&.java\fP"
.br
.ti -1c
.RI "file \fBMessageContext\&.java\fP"
.br
.ti -1c
.RI "file \fBRequestSplitStrategy\&.java\fP"
.br
.ti -1c
.RI "file \fBSampleSplitStrategy\&.java\fP"
.br
.in -1c
