.TH "LDH_Git/tests/org/jgap/supergenes Directory Reference" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LDH_Git/tests/org/jgap/supergenes Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAllSupergenesTests\&.java\fP"
.br
.ti -1c
.RI "file \fBInstantiableSupergeneForTesting\&.java\fP"
.br
.ti -1c
.RI "file \fBSupergeneInternalParserTest\&.java\fP"
.br
.ti -1c
.RI "file \fBSupergenePersistentRepresentationTest\&.java\fP"
.br
.in -1c
