.TH "examples.grid.fitnessDistributed.MyRequest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.grid.fitnessDistributed.MyRequest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JGAPRequest\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyRequest\fP (String name, int id, Configuration a_config)"
.br
.ti -1c
.RI "\fBMyRequest\fP (String name, int id, Configuration a_config, Population a_pop)"
.br
.ti -1c
.RI "Object \fBclone\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.3 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
An instance splitting a single request into multiple requests that will be sent to multiple workers for computation\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.01 
.RE
.PP

.PP
Definition at line 22 of file MyRequest\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.grid\&.fitnessDistributed\&.MyRequest\&.MyRequest (Stringname, intid, Configurationa_config)\fC [inline]\fP"

.PP
Definition at line 27 of file MyRequest\&.java\&.
.SS "examples\&.grid\&.fitnessDistributed\&.MyRequest\&.MyRequest (Stringname, intid, Configurationa_config, Populationa_pop)\fC [inline]\fP"

.PP
Definition at line 31 of file MyRequest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Object examples\&.grid\&.fitnessDistributed\&.MyRequest\&.clone ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
deep clone of current instance
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 41 of file MyRequest\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.grid\&.fitnessDistributed\&.MyRequest\&.CVS_REVISION = '$Revision: 1\&.3 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file MyRequest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
