.TH "examples.energy.CoinsEnergyFitnessFunction" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.energy.CoinsEnergyFitnessFunction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits FitnessFunction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCoinsEnergyFitnessFunction\fP (int a_targetAmount, double a_maxWeight)"
.br
.ti -1c
.RI "double \fBevaluate\fP (IChromosome a_subject)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBamountOfChange\fP (IChromosome a_potentialSolution)"
.br
.ti -1c
.RI "static int \fBgetNumberOfCoinsAtGene\fP (IChromosome a_potentialSolution, int a_position)"
.br
.ti -1c
.RI "static int \fBgetTotalNumberOfCoins\fP (IChromosome a_potentialsolution)"
.br
.ti -1c
.RI "static double \fBgetTotalWeight\fP (IChromosome a_potentialSolution)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final int \fBMAX_BOUND\fP = 10000"
.br
.ti -1c
.RI "static final double \fBMAX_WEIGHT\fP = 500"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "double \fBchangeDifferenceBonus\fP (double a_maxFitness, int a_changeDifference)"
.br
.ti -1c
.RI "double \fBcomputeCoinNumberPenalty\fP (double a_maxFitness, int a_coins)"
.br
.ti -1c
.RI "double \fBcomputeWeightPenalty\fP (double a_maxFitness, double a_weight)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "final int \fBm_targetAmount\fP"
.br
.ti -1c
.RI "final double \fBm_maxWeight\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.5 $'"
.br
.ti -1c
.RI "static final double \fBZERO_DIFFERENCE_FITNESS\fP = Math\&.sqrt(\fBMAX_BOUND\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Sample fitness function for the \fBCoinsEnergy\fP example\&. Adapted from \fBexamples\&.MinimizingMakeChangeFitnessFunction\fP
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 21 of file CoinsEnergyFitnessFunction\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.energy\&.CoinsEnergyFitnessFunction\&.CoinsEnergyFitnessFunction (inta_targetAmount, doublea_maxWeight)\fC [inline]\fP"

.PP
Definition at line 35 of file CoinsEnergyFitnessFunction\&.java\&.
.PP
References examples\&.energy\&.CoinsEnergyFitnessFunction\&.m_maxWeight, examples\&.energy\&.CoinsEnergyFitnessFunction\&.m_targetAmount, examples\&.energy\&.CoinsEnergyFitnessFunction\&.MAX_BOUND, and examples\&.energy\&.CoinsEnergyFitnessFunction\&.MAX_WEIGHT\&.
.SH "Member Function Documentation"
.PP 
.SS "static int examples\&.energy\&.CoinsEnergyFitnessFunction\&.amountOfChange (IChromosomea_potentialSolution)\fC [inline]\fP, \fC [static]\fP"
Calculates the total amount of change (in cents) represented by the given potential solution and returns that amount\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_potentialSolution\fP the potential solution to evaluate 
.RE
.PP
\fBReturns:\fP
.RS 4
the total amount of change (in cents) represented by the given solution
.RE
.PP
\fBAuthor:\fP
.RS 4
Neil Rotstan 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 195 of file CoinsEnergyFitnessFunction\&.java\&.
.PP
References examples\&.energy\&.CoinsEnergyFitnessFunction\&.getNumberOfCoinsAtGene()\&.
.PP
Referenced by examples\&.energy\&.CoinsEnergyFitnessFunction\&.evaluate()\&.
.SS "double examples\&.energy\&.CoinsEnergyFitnessFunction\&.changeDifferenceBonus (doublea_maxFitness, inta_changeDifference)\fC [inline]\fP, \fC [protected]\fP"
Bonus calculation of fitness value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa_maxFitness\fP maximum fitness value appliable 
.br
\fIa_changeDifference\fP change difference in coins for the coins problem 
.RE
.PP
\fBReturns:\fP
.RS 4
bonus for given change difference 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 145 of file CoinsEnergyFitnessFunction\&.java\&.
.PP
Referenced by examples\&.energy\&.CoinsEnergyFitnessFunction\&.evaluate()\&.
.SS "double examples\&.energy\&.CoinsEnergyFitnessFunction\&.computeCoinNumberPenalty (doublea_maxFitness, inta_coins)\fC [inline]\fP, \fC [protected]\fP"
Calculates the penalty to apply to the fitness value based on the ammount of coins in the solution
.PP
\fBParameters:\fP
.RS 4
\fIa_maxFitness\fP maximum fitness value allowed 
.br
\fIa_coins\fP number of coins in the solution 
.RE
.PP
\fBReturns:\fP
.RS 4
penalty for the fitness value base on the number of coins
.RE
.PP
\fBAuthor:\fP
.RS 4
John Serri 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 168 of file CoinsEnergyFitnessFunction\&.java\&.
.PP
Referenced by examples\&.energy\&.CoinsEnergyFitnessFunction\&.evaluate()\&.
.SS "double examples\&.energy\&.CoinsEnergyFitnessFunction\&.computeWeightPenalty (doublea_maxFitness, doublea_weight)\fC [inline]\fP, \fC [protected]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIa_maxFitness\fP the maximum fitness value allowed 
.br
\fIa_weight\fP the coins weight of the current solution 
.RE
.PP
\fBReturns:\fP
.RS 4
the penalty computed 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 269 of file CoinsEnergyFitnessFunction\&.java\&.
.PP
Referenced by examples\&.energy\&.CoinsEnergyFitnessFunction\&.evaluate()\&.
.SS "double examples\&.energy\&.CoinsEnergyFitnessFunction\&.evaluate (IChromosomea_subject)\fC [inline]\fP"
Determine the fitness of the given Chromosome instance\&. The higher the return value, the more fit the instance\&. This method should always return the same fitness value for two equivalent Chromosome instances\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_subject\fP the Chromosome instance to evaluate
.RE
.PP
\fBReturns:\fP
.RS 4
positive double reflecting the fitness rating of the given Chromosome 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 (until 1\&.1: return type int) 
.RE
.PP
\fBAuthor:\fP
.RS 4
Neil Rotstan, Klaus Meffert, John Serri 
.RE
.PP

.PP
Definition at line 62 of file CoinsEnergyFitnessFunction\&.java\&.
.PP
References examples\&.energy\&.CoinsEnergyFitnessFunction\&.amountOfChange(), examples\&.energy\&.CoinsEnergyFitnessFunction\&.changeDifferenceBonus(), examples\&.energy\&.CoinsEnergyFitnessFunction\&.computeCoinNumberPenalty(), examples\&.energy\&.CoinsEnergyFitnessFunction\&.computeWeightPenalty(), examples\&.energy\&.CoinsEnergyFitnessFunction\&.getTotalNumberOfCoins(), examples\&.energy\&.CoinsEnergyFitnessFunction\&.getTotalWeight(), examples\&.energy\&.CoinsEnergyFitnessFunction\&.m_maxWeight, examples\&.energy\&.CoinsEnergyFitnessFunction\&.m_targetAmount, and examples\&.energy\&.CoinsEnergyFitnessFunction\&.MAX_BOUND\&.
.SS "static int examples\&.energy\&.CoinsEnergyFitnessFunction\&.getNumberOfCoinsAtGene (IChromosomea_potentialSolution, inta_position)\fC [inline]\fP, \fC [static]\fP"
Retrieves the number of coins represented by the given potential solution at the given gene position\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_potentialSolution\fP the potential solution to evaluate 
.br
\fIa_position\fP the gene position to evaluate 
.RE
.PP
\fBReturns:\fP
.RS 4
the number of coins represented by the potential solution at the given gene position
.RE
.PP
\fBAuthor:\fP
.RS 4
Neil Rotstan 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 216 of file CoinsEnergyFitnessFunction\&.java\&.
.PP
Referenced by examples\&.energy\&.CoinsEnergyFitnessFunction\&.amountOfChange(), examples\&.energy\&.CoinsEnergyFitnessFunction\&.getTotalNumberOfCoins(), and examples\&.energy\&.CoinsEnergyFitnessFunction\&.getTotalWeight()\&.
.SS "static int examples\&.energy\&.CoinsEnergyFitnessFunction\&.getTotalNumberOfCoins (IChromosomea_potentialsolution)\fC [inline]\fP, \fC [static]\fP"
Returns the total number of coins represented by all of the genes in the given potential solution\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_potentialsolution\fP the potential solution to evaluate 
.RE
.PP
\fBReturns:\fP
.RS 4
total number of coins represented by the given Chromosome
.RE
.PP
\fBAuthor:\fP
.RS 4
Neil Rotstan 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 233 of file CoinsEnergyFitnessFunction\&.java\&.
.PP
References examples\&.energy\&.CoinsEnergyFitnessFunction\&.getNumberOfCoinsAtGene()\&.
.PP
Referenced by examples\&.energy\&.CoinsEnergyFitnessFunction\&.evaluate(), and examples\&.energy\&.CoinsEnergy\&.makeChangeForAmount()\&.
.SS "static double examples\&.energy\&.CoinsEnergyFitnessFunction\&.getTotalWeight (IChromosomea_potentialSolution)\fC [inline]\fP, \fC [static]\fP"
Returns the total weight of all coins\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_potentialSolution\fP the potential solution to evaluate 
.RE
.PP
\fBReturns:\fP
.RS 4
total weight of all coins
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 251 of file CoinsEnergyFitnessFunction\&.java\&.
.PP
References examples\&.energy\&.CoinsEnergyFitnessFunction\&.getNumberOfCoinsAtGene()\&.
.PP
Referenced by examples\&.energy\&.CoinsEnergyFitnessFunction\&.evaluate()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.energy\&.CoinsEnergyFitnessFunction\&.CVS_REVISION = '$Revision: 1\&.5 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 24 of file CoinsEnergyFitnessFunction\&.java\&.
.SS "final double examples\&.energy\&.CoinsEnergyFitnessFunction\&.m_maxWeight\fC [private]\fP"

.PP
Definition at line 28 of file CoinsEnergyFitnessFunction\&.java\&.
.PP
Referenced by examples\&.energy\&.CoinsEnergyFitnessFunction\&.CoinsEnergyFitnessFunction(), and examples\&.energy\&.CoinsEnergyFitnessFunction\&.evaluate()\&.
.SS "final int examples\&.energy\&.CoinsEnergyFitnessFunction\&.m_targetAmount\fC [private]\fP"

.PP
Definition at line 26 of file CoinsEnergyFitnessFunction\&.java\&.
.PP
Referenced by examples\&.energy\&.CoinsEnergyFitnessFunction\&.CoinsEnergyFitnessFunction(), and examples\&.energy\&.CoinsEnergyFitnessFunction\&.evaluate()\&.
.SS "final int examples\&.energy\&.CoinsEnergyFitnessFunction\&.MAX_BOUND = 10000\fC [static]\fP"

.PP
Definition at line 30 of file CoinsEnergyFitnessFunction\&.java\&.
.PP
Referenced by examples\&.energy\&.CoinsEnergyFitnessFunction\&.CoinsEnergyFitnessFunction(), and examples\&.energy\&.CoinsEnergyFitnessFunction\&.evaluate()\&.
.SS "final double examples\&.energy\&.CoinsEnergyFitnessFunction\&.MAX_WEIGHT = 500\fC [static]\fP"

.PP
Definition at line 31 of file CoinsEnergyFitnessFunction\&.java\&.
.PP
Referenced by examples\&.energy\&.CoinsEnergyFitnessFunction\&.CoinsEnergyFitnessFunction()\&.
.SS "final double examples\&.energy\&.CoinsEnergyFitnessFunction\&.ZERO_DIFFERENCE_FITNESS = Math\&.sqrt(\fBMAX_BOUND\fP)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 33 of file CoinsEnergyFitnessFunction\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
