.TH "examples.island.IslandThread" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.island.IslandThread \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Thread\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIslandThread\fP (int nextNumber)  throws Exception "
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "boolean \fBisFinished\fP ()"
.br
.ti -1c
.RI "IChromosome \fBgetBestSolution\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Genotype \fBgen\fP"
.br
.ti -1c
.RI "int \fBm_nextNumber\fP"
.br
.ti -1c
.RI "IChromosome \fBm_best\fP"
.br
.ti -1c
.RI "boolean \fBm_finished\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.3 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Simple example of an island thread\&. It utilizes the former example class \fBMinimizingMakeChangeFitnessFunction\fP for reasons of simplicity\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.5 
.RE
.PP

.PP
Definition at line 23 of file IslandThread\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.island\&.IslandThread\&.IslandThread (intnextNumber) throws Exception\fC [inline]\fP"

.PP
Definition at line 36 of file IslandThread\&.java\&.
.PP
References examples\&.island\&.IslandThread\&.gen, and examples\&.island\&.IslandThread\&.m_nextNumber\&.
.SH "Member Function Documentation"
.PP 
.SS "IChromosome examples\&.island\&.IslandThread\&.getBestSolution ()\fC [inline]\fP"

.PP
Definition at line 122 of file IslandThread\&.java\&.
.PP
References examples\&.island\&.IslandThread\&.m_best, and examples\&.island\&.IslandThread\&.m_finished\&.
.SS "boolean examples\&.island\&.IslandThread\&.isFinished ()\fC [inline]\fP"

.PP
Definition at line 118 of file IslandThread\&.java\&.
.PP
References examples\&.island\&.IslandThread\&.m_finished\&.
.PP
Referenced by examples\&.island\&.IslandExample\&.start()\&.
.SS "void examples\&.island\&.IslandThread\&.run ()\fC [inline]\fP"

.PP
Definition at line 75 of file IslandThread\&.java\&.
.PP
References examples\&.island\&.IslandThread\&.m_best, examples\&.island\&.IslandThread\&.m_finished, and examples\&.island\&.IslandThread\&.m_nextNumber\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.island\&.IslandThread\&.CVS_REVISION = '$Revision: 1\&.3 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file IslandThread\&.java\&.
.SS "Genotype examples\&.island\&.IslandThread\&.gen\fC [private]\fP"

.PP
Definition at line 28 of file IslandThread\&.java\&.
.PP
Referenced by examples\&.island\&.IslandThread\&.IslandThread()\&.
.SS "IChromosome examples\&.island\&.IslandThread\&.m_best\fC [private]\fP"

.PP
Definition at line 32 of file IslandThread\&.java\&.
.PP
Referenced by examples\&.island\&.IslandThread\&.getBestSolution(), and examples\&.island\&.IslandThread\&.run()\&.
.SS "boolean examples\&.island\&.IslandThread\&.m_finished\fC [private]\fP"

.PP
Definition at line 34 of file IslandThread\&.java\&.
.PP
Referenced by examples\&.island\&.IslandThread\&.getBestSolution(), examples\&.island\&.IslandThread\&.isFinished(), and examples\&.island\&.IslandThread\&.run()\&.
.SS "int examples\&.island\&.IslandThread\&.m_nextNumber\fC [private]\fP"

.PP
Definition at line 30 of file IslandThread\&.java\&.
.PP
Referenced by examples\&.island\&.IslandThread\&.IslandThread(), and examples\&.island\&.IslandThread\&.run()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
