.TH "examples.monalisa.gui.GeneticDrawingAboutBox" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.monalisa.gui.GeneticDrawingAboutBox \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeneticDrawingAboutBox\fP (java\&.awt\&.Frame parent)"
.br
.ti -1c
.RI "void \fBcloseAboutBox\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitComponents\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "javax\&.swing\&.JButton \fBcloseButton\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.3 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Shows a dialog that informs about the application\&.
.PP
\fBAuthor:\fP
.RS 4
Yann N\&. Dauphin 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4 
.RE
.PP

.PP
Definition at line 20 of file GeneticDrawingAboutBox\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.monalisa\&.gui\&.GeneticDrawingAboutBox\&.GeneticDrawingAboutBox (java\&.awt\&.Frameparent)\fC [inline]\fP"

.PP
Definition at line 25 of file GeneticDrawingAboutBox\&.java\&.
.PP
References examples\&.monalisa\&.gui\&.GeneticDrawingAboutBox\&.closeButton, and examples\&.monalisa\&.gui\&.GeneticDrawingAboutBox\&.initComponents()\&.
.SH "Member Function Documentation"
.PP 
.SS "void examples\&.monalisa\&.gui\&.GeneticDrawingAboutBox\&.closeAboutBox ()\fC [inline]\fP"

.PP
Definition at line 31 of file GeneticDrawingAboutBox\&.java\&.
.SS "void examples\&.monalisa\&.gui\&.GeneticDrawingAboutBox\&.initComponents ()\fC [inline]\fP, \fC [private]\fP"
This method is called from within the constructor to initialize the form\&. WARNING: Do NOT modify this code\&. The content of this method is always regenerated by the Form Editor\&. 
.PP
Definition at line 41 of file GeneticDrawingAboutBox\&.java\&.
.PP
References examples\&.monalisa\&.gui\&.GeneticDrawingAboutBox\&.closeButton\&.
.PP
Referenced by examples\&.monalisa\&.gui\&.GeneticDrawingAboutBox\&.GeneticDrawingAboutBox()\&.
.SH "Member Data Documentation"
.PP 
.SS "javax\&.swing\&.JButton examples\&.monalisa\&.gui\&.GeneticDrawingAboutBox\&.closeButton\fC [private]\fP"

.PP
Definition at line 156 of file GeneticDrawingAboutBox\&.java\&.
.PP
Referenced by examples\&.monalisa\&.gui\&.GeneticDrawingAboutBox\&.GeneticDrawingAboutBox(), and examples\&.monalisa\&.gui\&.GeneticDrawingAboutBox\&.initComponents()\&.
.SS "final String examples\&.monalisa\&.gui\&.GeneticDrawingAboutBox\&.CVS_REVISION = '$Revision: 1\&.3 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 23 of file GeneticDrawingAboutBox\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
