.TH "examples.island.IslandExample" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.island.IslandExample \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIslandExample\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)  throws Exception "
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "Thread \fBgetIsland\fP ()  throws Exception "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBnextNumber\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Simple example on how to build and run an island model with JGAP\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.5 
.RE
.PP

.PP
Definition at line 18 of file IslandExample\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.island\&.IslandExample\&.IslandExample ()\fC [inline]\fP"

.PP
Definition at line 24 of file IslandExample\&.java\&.
.PP
Referenced by examples\&.island\&.IslandExample\&.main()\&.
.SH "Member Function Documentation"
.PP 
.SS "Thread examples\&.island\&.IslandExample\&.getIsland () throws Exception\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line 56 of file IslandExample\&.java\&.
.PP
References examples\&.island\&.IslandExample\&.nextNumber\&.
.PP
Referenced by examples\&.island\&.IslandExample\&.start()\&.
.SS "static void examples\&.island\&.IslandExample\&.main (String[]args) throws Exception\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 61 of file IslandExample\&.java\&.
.PP
References examples\&.island\&.IslandExample\&.IslandExample()\&.
.SS "void examples\&.island\&.IslandExample\&.start () throws Exception\fC [inline]\fP"

.PP
\fBTodo\fP
.RS 4

.RE
.PP

.PP
Definition at line 27 of file IslandExample\&.java\&.
.PP
References examples\&.island\&.IslandExample\&.getIsland(), and examples\&.island\&.IslandThread\&.isFinished()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.island\&.IslandExample\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 20 of file IslandExample\&.java\&.
.SS "int examples\&.island\&.IslandExample\&.nextNumber\fC [private]\fP"

.PP
Definition at line 22 of file IslandExample\&.java\&.
.PP
Referenced by examples\&.island\&.IslandExample\&.getIsland()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
