.TH "examples.gp.paintedDesert.LoopUntil" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.gp.paintedDesert.LoopUntil \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.gp\&.CommandGene\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoopUntil\fP (final \fBGPConfiguration\fP a_conf)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBLoopUntil\fP (final \fBGPConfiguration\fP a_conf, Class a_typeVar, int a_count)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "boolean \fBexecute_boolean\fP (ProgramChromosome c, int n, Object[] args)"
.br
.ti -1c
.RI "boolean \fBisValid\fP (ProgramChromosome a_program)"
.br
.ti -1c
.RI "Class \fBgetChildType\fP (\fBIGPProgram\fP a_ind, int a_chromNum)"
.br
.ti -1c
.RI "int \fBcompareTo\fP (Object a_other)"
.br
.ti -1c
.RI "boolean \fBequals\fP (Object a_other)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Class \fBm_typeVar\fP"
.br
.ti -1c
.RI "int \fBm_count\fP = 50"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A loop until the condition of the first argument is true\&.
.PP
\fBAuthor:\fP
.RS 4
Scott Mueller 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 22 of file LoopUntil\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.gp\&.paintedDesert\&.LoopUntil\&.LoopUntil (final \fBGPConfiguration\fPa_conf) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"
Constructor for the function 
.PP
\fBParameters:\fP
.RS 4
\fIa_conf\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIInvalidConfigurationException\fP 
.RE
.PP

.PP
Definition at line 42 of file LoopUntil\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.BooleanClass\&.
.SS "examples\&.gp\&.paintedDesert\&.LoopUntil\&.LoopUntil (final \fBGPConfiguration\fPa_conf, Classa_typeVar, inta_count) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 47 of file LoopUntil\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.BooleanClass, and examples\&.gp\&.paintedDesert\&.LoopUntil\&.m_count\&.
.SH "Member Function Documentation"
.PP 
.SS "int examples\&.gp\&.paintedDesert\&.LoopUntil\&.compareTo (Objecta_other)\fC [inline]\fP"
The compareTo-method\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_other\fP the other object to compare 
.RE
.PP
\fBReturns:\fP
.RS 4
-1, 0, 1
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.01 
.RE
.PP

.PP
Definition at line 105 of file LoopUntil\&.java\&.
.SS "boolean examples\&.gp\&.paintedDesert\&.LoopUntil\&.equals (Objecta_other)\fC [inline]\fP"
The equals-method\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_other\fP the other object to compare 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the objects are seen as equal
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.01 
.RE
.PP

.PP
Definition at line 128 of file LoopUntil\&.java\&.
.SS "boolean examples\&.gp\&.paintedDesert\&.LoopUntil\&.execute_boolean (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"
Executes the \fBLoopUntil\fP function for a void argument\&. Essentially loops m_count times\&. 
.PP
\fBParameters:\fP
.RS 4
\fIc\fP 
.br
\fItest\fP 
.br
\fIargs\fP 
.RE
.PP

.PP
Definition at line 75 of file LoopUntil\&.java\&.
.SS "Class examples\&.gp\&.paintedDesert\&.LoopUntil\&.getChildType (\fBIGPProgram\fPa_ind, inta_chromNum)\fC [inline]\fP"

.PP
Definition at line 92 of file LoopUntil\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.VoidClass\&.
.SS "String examples\&.gp\&.paintedDesert\&.LoopUntil\&.getName ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
textual name of this command 
.RE
.PP

.PP
Definition at line 64 of file LoopUntil\&.java\&.
.SS "boolean examples\&.gp\&.paintedDesert\&.LoopUntil\&.isValid (ProgramChromosomea_program)\fC [inline]\fP"

.PP
Definition at line 88 of file LoopUntil\&.java\&.
.SS "String examples\&.gp\&.paintedDesert\&.LoopUntil\&.toString ()\fC [inline]\fP, \fC [virtual]\fP"
Program listing name of function 
.PP
Implements \fBorg\&.jgap\&.gp\&.CommandGene\fP\&.
.PP
Definition at line 56 of file LoopUntil\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.gp\&.paintedDesert\&.LoopUntil\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file LoopUntil\&.java\&.
.SS "int examples\&.gp\&.paintedDesert\&.LoopUntil\&.m_count = 50\fC [private]\fP"
Maximum number of times the function is allowed to loop 
.PP
Definition at line 35 of file LoopUntil\&.java\&.
.PP
Referenced by examples\&.gp\&.paintedDesert\&.LoopUntil\&.LoopUntil()\&.
.SS "Class examples\&.gp\&.paintedDesert\&.LoopUntil\&.m_typeVar\fC [private]\fP"
Type of the fist argument 
.PP
Definition at line 30 of file LoopUntil\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
