.TH "examples.gp.paintedDesert.IfLessThanZero" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.gp.paintedDesert.IfLessThanZero \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.gp\&.CommandGene\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIfLessThanZero\fP (final \fBGPConfiguration\fP a_conf, Class a_type)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBexecute_void\fP (ProgramChromosome c, int n, Object[] args)"
.br
.ti -1c
.RI "Class \fBgetChildType\fP (\fBIGPProgram\fP a_ind, int a_chromNum)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Class \fBm_type\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A three argument version of if-less-than-zero (IFLTZ) construct\&. If the first argument is less than zero, then return the second argument, else the return the third argument\&. Mimics the Lisp function from Koza\&.
.PP
\fBAuthor:\fP
.RS 4
Scott Mueller 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 24 of file IfLessThanZero\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.gp\&.paintedDesert\&.IfLessThanZero\&.IfLessThanZero (final \fBGPConfiguration\fPa_conf, Classa_type) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"
Constructor for the less than zero function 
.PP
\fBParameters:\fP
.RS 4
\fIa_conf\fP 
.br
\fIa_type\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIInvalidConfigurationException\fP 
.RE
.PP

.PP
Definition at line 40 of file IfLessThanZero\&.java\&.
.PP
References examples\&.gp\&.paintedDesert\&.IfLessThanZero\&.m_type, and org\&.jgap\&.gp\&.CommandGene\&.VoidClass\&.
.SH "Member Function Documentation"
.PP 
.SS "void examples\&.gp\&.paintedDesert\&.IfLessThanZero\&.execute_void (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"
Executes the If less than zero function for void arguments 
.PP
Definition at line 64 of file IfLessThanZero\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.BooleanClass, org\&.jgap\&.gp\&.CommandGene\&.check(), org\&.jgap\&.gp\&.CommandGene\&.DoubleClass, org\&.jgap\&.gp\&.CommandGene\&.FloatClass, org\&.jgap\&.gp\&.CommandGene\&.IntegerClass, org\&.jgap\&.gp\&.CommandGene\&.LongClass, and examples\&.gp\&.paintedDesert\&.IfLessThanZero\&.m_type\&.
.SS "Class examples\&.gp\&.paintedDesert\&.IfLessThanZero\&.getChildType (\fBIGPProgram\fPa_ind, inta_chromNum)\fC [inline]\fP"
Determines which type a specific child of this command has\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_ind\fP ignored here 
.br
\fIa_chromNum\fP index of child 
.RE
.PP
\fBReturns:\fP
.RS 4
type of the a_chromNum'th child 
.RE
.PP

.PP
Definition at line 102 of file IfLessThanZero\&.java\&.
.PP
References examples\&.gp\&.paintedDesert\&.IfLessThanZero\&.m_type, and org\&.jgap\&.gp\&.CommandGene\&.VoidClass\&.
.SS "String examples\&.gp\&.paintedDesert\&.IfLessThanZero\&.getName ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
textual name of this command 
.RE
.PP

.PP
Definition at line 57 of file IfLessThanZero\&.java\&.
.SS "String examples\&.gp\&.paintedDesert\&.IfLessThanZero\&.toString ()\fC [inline]\fP, \fC [virtual]\fP"
Program listing for the function 
.PP
Implements \fBorg\&.jgap\&.gp\&.CommandGene\fP\&.
.PP
Definition at line 49 of file IfLessThanZero\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.gp\&.paintedDesert\&.IfLessThanZero\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 27 of file IfLessThanZero\&.java\&.
.SS "Class examples\&.gp\&.paintedDesert\&.IfLessThanZero\&.m_type\fC [private]\fP"
Returns the type of the arguments 
.PP
Definition at line 32 of file IfLessThanZero\&.java\&.
.PP
Referenced by examples\&.gp\&.paintedDesert\&.IfLessThanZero\&.execute_void(), examples\&.gp\&.paintedDesert\&.IfLessThanZero\&.getChildType(), and examples\&.gp\&.paintedDesert\&.IfLessThanZero\&.IfLessThanZero()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
