.TH "examples.grid.mathProblemDistributed.SampleFitnessFunction" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.grid.mathProblemDistributed.SampleFitnessFunction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits GPFitnessFunction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSampleFitnessFunction\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "double \fBcomputeRawFitness\fP (final IGPProgram ind)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "double \fBevaluate\fP (final IGPProgram a_subject)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.8 $'"
.br
.ti -1c
.RI "static Logger \fBlog\fP = Logger\&.getLogger(SampleFitnessFunction\&.class)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Fitness function for our example\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 23 of file SampleFitnessFunction\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.grid\&.mathProblemDistributed\&.SampleFitnessFunction\&.SampleFitnessFunction ()\fC [inline]\fP"

.PP
Definition at line 36 of file SampleFitnessFunction\&.java\&.
.PP
References examples\&.grid\&.mathProblemDistributed\&.SampleFitnessFunction\&.init()\&.
.SH "Member Function Documentation"
.PP 
.SS "double examples\&.grid\&.mathProblemDistributed\&.SampleFitnessFunction\&.computeRawFitness (final IGPProgramind)\fC [inline]\fP"

.PP
Definition at line 56 of file SampleFitnessFunction\&.java\&.
.PP
References examples\&.grid\&.mathProblemDistributed\&.SampleFitnessFunction\&.init()\&.
.PP
Referenced by examples\&.grid\&.mathProblemDistributed\&.SampleFitnessFunction\&.evaluate()\&.
.SS "double examples\&.grid\&.mathProblemDistributed\&.SampleFitnessFunction\&.evaluate (final IGPPrograma_subject)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 52 of file SampleFitnessFunction\&.java\&.
.PP
References examples\&.grid\&.mathProblemDistributed\&.SampleFitnessFunction\&.computeRawFitness()\&.
.SS "void examples\&.grid\&.mathProblemDistributed\&.SampleFitnessFunction\&.init ()\fC [inline]\fP"

.PP
Definition at line 40 of file SampleFitnessFunction\&.java\&.
.PP
Referenced by examples\&.grid\&.mathProblemDistributed\&.SampleFitnessFunction\&.computeRawFitness(), and examples\&.grid\&.mathProblemDistributed\&.SampleFitnessFunction\&.SampleFitnessFunction()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.grid\&.mathProblemDistributed\&.SampleFitnessFunction\&.CVS_REVISION = '$Revision: 1\&.8 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file SampleFitnessFunction\&.java\&.
.SS "Logger examples\&.grid\&.mathProblemDistributed\&.SampleFitnessFunction\&.log = Logger\&.getLogger(SampleFitnessFunction\&.class)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 28 of file SampleFitnessFunction\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
