.TH "examples.gp.symbolicRegression.AndD" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.gp.symbolicRegression.AndD \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MathCommand, IMutateable, and ICloneable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAndD\fP (final \fBGPConfiguration\fP a_conf)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBAndD\fP (final \fBGPConfiguration\fP a_conf, Class a_returnType)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBCommandGene\fP \fBapplyMutation\fP (int index, double a_percentage)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "Object \fBclone\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "double \fBexecute_double\fP (ProgramChromosome c, int n, Object[] args)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.1 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
The boolean and operation\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert, Hakan Kjellerstrand 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.5 
.RE
.PP

.PP
Definition at line 23 of file AndD\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.gp\&.symbolicRegression\&.AndD\&.AndD (final \fBGPConfiguration\fPa_conf) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 28 of file AndD\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.DoubleClass\&.
.PP
Referenced by examples\&.gp\&.symbolicRegression\&.AndD\&.clone()\&.
.SS "examples\&.gp\&.symbolicRegression\&.AndD\&.AndD (final \fBGPConfiguration\fPa_conf, Classa_returnType) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 33 of file AndD\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCommandGene\fP examples\&.gp\&.symbolicRegression\&.AndD\&.applyMutation (intindex, doublea_percentage) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 38 of file AndD\&.java\&.
.SS "Object examples\&.gp\&.symbolicRegression\&.AndD\&.clone ()\fC [inline]\fP"
Clones the object\&. Simple and straight forward implementation here\&.
.PP
\fBReturns:\fP
.RS 4
cloned instance of this object
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4 
.RE
.PP

.PP
Definition at line 58 of file AndD\&.java\&.
.PP
References examples\&.gp\&.symbolicRegression\&.AndD\&.AndD()\&.
.SS "double examples\&.gp\&.symbolicRegression\&.AndD\&.execute_double (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 81 of file AndD\&.java\&.
.SS "String examples\&.gp\&.symbolicRegression\&.AndD\&.getName ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
textual name of this command
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 77 of file AndD\&.java\&.
.SS "String examples\&.gp\&.symbolicRegression\&.AndD\&.toString ()\fC [inline]\fP"

.PP
Definition at line 67 of file AndD\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.gp\&.symbolicRegression\&.AndD\&.CVS_REVISION = '$Revision: 1\&.1 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file AndD\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
