.TH "examples.grid.fitnessDistributed" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.grid.fitnessDistributed \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClientEvolveStrategy\fP"
.br
.ti -1c
.RI "class \fBFitnessSplitStrategy\fP"
.br
.ti -1c
.RI "class \fBGridConfiguration\fP"
.br
.ti -1c
.RI "class \fBMyClientFeedback\fP"
.br
.ti -1c
.RI "class \fBMyGAWorker\fP"
.br
.ti -1c
.RI "class \fBMyRequest\fP"
.br
.ti -1c
.RI "class \fBMyRequestSplitStrategy\fP"
.br
.ti -1c
.RI "class \fBMyResult\fP"
.br
.ti -1c
.RI "class \fBMyWorkerFeedback\fP"
.br
.ti -1c
.RI "class \fBMyWorkerReturnStrategy\fP"
.br
.ti -1c
.RI "class \fBSampleFitnessFunction\fP"
.br
.ti -1c
.RI "class \fBServerAndWorker\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
