.TH "examples.gp.symbolicRegression.Logistic.Compatible" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.gp.symbolicRegression.Logistic.Compatible \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Object \fBexecute_logistic\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 68 of file Logistic\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Object examples\&.gp\&.symbolicRegression\&.Logistic\&.Compatible\&.execute_logistic ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
