.TH "examples.gp.monalisa.gui.EvolutionRunnable" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.gp.monalisa.gui.EvolutionRunnable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Runnable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEvolutionRunnable\fP (\fBGeneticDrawingView\fP a_view)"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "final \fBGeneticDrawingView\fP \fBm_view\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static boolean \fBinitView\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.4 $'"
.br
.ti -1c
.RI "static transient Logger \fBLOGGER\fP = Logger\&.getLogger(EvolutionRunnable\&.class)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class in charge of actually running the evolution process\&.
.PP
\fBAuthor:\fP
.RS 4
Yann N\&. Dauphin 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4 
.RE
.PP

.PP
Definition at line 30 of file EvolutionRunnable\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.gp\&.monalisa\&.gui\&.EvolutionRunnable\&.EvolutionRunnable (\fBGeneticDrawingView\fPa_view)\fC [inline]\fP"

.PP
Definition at line 41 of file EvolutionRunnable\&.java\&.
.PP
References examples\&.gp\&.monalisa\&.gui\&.EvolutionRunnable\&.m_view\&.
.SH "Member Function Documentation"
.PP 
.SS "void examples\&.gp\&.monalisa\&.gui\&.EvolutionRunnable\&.run ()\fC [inline]\fP"
Updates the chart in the main view\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_firedEvent\fP the event
.RE
.PP
Display best solution in fittestChromosomeView's mainPanel\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_firedEvent\fP the event
.RE
.PP

.PP
Definition at line 46 of file EvolutionRunnable\&.java\&.
.PP
References org\&.jgap\&.gp\&.IGPProgram\&.getApplicationData(), org\&.jgap\&.gp\&.IGPProgram\&.getFitnessValue(), org\&.jgap\&.gp\&.impl\&.GPGenotype\&.getGPConfiguration(), examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.getTargetImage(), examples\&.gp\&.monalisa\&.gui\&.EvolutionRunnable\&.initView, examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.isEvolutionActivated, examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.isSaveToFile(), and examples\&.gp\&.monalisa\&.gui\&.EvolutionRunnable\&.m_view\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.gp\&.monalisa\&.gui\&.EvolutionRunnable\&.CVS_REVISION = '$Revision: 1\&.4 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 33 of file EvolutionRunnable\&.java\&.
.SS "boolean examples\&.gp\&.monalisa\&.gui\&.EvolutionRunnable\&.initView\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 39 of file EvolutionRunnable\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.EvolutionRunnable\&.run()\&.
.SS "transient Logger examples\&.gp\&.monalisa\&.gui\&.EvolutionRunnable\&.LOGGER = Logger\&.getLogger(EvolutionRunnable\&.class)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 35 of file EvolutionRunnable\&.java\&.
.SS "final \fBGeneticDrawingView\fP examples\&.gp\&.monalisa\&.gui\&.EvolutionRunnable\&.m_view\fC [protected]\fP"

.PP
Definition at line 37 of file EvolutionRunnable\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.EvolutionRunnable\&.EvolutionRunnable(), and examples\&.gp\&.monalisa\&.gui\&.EvolutionRunnable\&.run()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
