.TH "examples.supergene.Force" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.supergene.Force \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static boolean \fBsolve\fP (int a_sum)"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static boolean \fBREPORT_ENABLED\fP = true"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBForce\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Solve the change problem using force method\&. This class was used to verify if the solution exists in general\&.
.PP
\fBAuthor:\fP
.RS 4
Audrius Meskauskas 
.RE
.PP

.PP
Definition at line 18 of file Force\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.supergene\&.Force\&.Force ()\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line 24 of file Force\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void examples\&.supergene\&.Force\&.main (String[]args)\fC [inline]\fP, \fC [static]\fP"
Test the \fBForce\fP method itself\&.
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP ignored 
.RE
.PP

.PP
Definition at line 67 of file Force\&.java\&.
.PP
References examples\&.supergene\&.Force\&.solve()\&.
.SS "static boolean examples\&.supergene\&.Force\&.solve (inta_sum)\fC [inline]\fP, \fC [static]\fP"
Check the existence of a soulution\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_sum\fP the sum needed 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the change can be expressed in coins, satisfying pennies mod 2 = nickels mod 2
.RE
.PP
\fBAuthor:\fP
.RS 4
Audrius Meskauskas 
.RE
.PP

.PP
Definition at line 37 of file Force\&.java\&.
.PP
References examples\&.supergene\&.AbstractSupergeneTest\&.amountOfChange(), and examples\&.supergene\&.Force\&.REPORT_ENABLED\&.
.PP
Referenced by examples\&.supergene\&.Force\&.main(), and examples\&.supergene\&.AbstractSupergeneTest\&.test()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.supergene\&.Force\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 20 of file Force\&.java\&.
.SS "boolean examples\&.supergene\&.Force\&.REPORT_ENABLED = true\fC [static]\fP"

.PP
Definition at line 22 of file Force\&.java\&.
.PP
Referenced by examples\&.supergene\&.Force\&.solve()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
