.TH "examples.gp.symbolicRegression.Sign" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.gp.symbolicRegression.Sign \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MathCommand, and ICloneable\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBCompatible\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSign\fP (final \fBGPConfiguration\fP a_conf, Class a_returnType)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "float \fBexecute_float\fP (ProgramChromosome c, int n, Object[] args)"
.br
.ti -1c
.RI "double \fBexecute_double\fP (ProgramChromosome c, int n, Object[] args)"
.br
.ti -1c
.RI "Object \fBexecute_object\fP (ProgramChromosome c, int n, Object[] args)"
.br
.ti -1c
.RI "Object \fBclone\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.1 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Returns the natural logarithm (base e) of a double value\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.5 
.RE
.PP

.PP
Definition at line 31 of file Sign\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.gp\&.symbolicRegression\&.Sign\&.Sign (final \fBGPConfiguration\fPa_conf, Classa_returnType) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 36 of file Sign\&.java\&.
.PP
Referenced by examples\&.gp\&.symbolicRegression\&.Sign\&.clone()\&.
.SH "Member Function Documentation"
.PP 
.SS "Object examples\&.gp\&.symbolicRegression\&.Sign\&.clone ()\fC [inline]\fP"
Clones the object\&. Simple and straight forward implementation here\&.
.PP
\fBReturns:\fP
.RS 4
cloned instance of this object
.RE
.PP
\fBAuthor:\fP
.RS 4
Hakan Kjellerstrand (based on Klaus Meffert's Log file) 
.RE
.PP

.PP
Definition at line 94 of file Sign\&.java\&.
.PP
References examples\&.gp\&.symbolicRegression\&.Sign\&.Sign()\&.
.SS "double examples\&.gp\&.symbolicRegression\&.Sign\&.execute_double (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 67 of file Sign\&.java\&.
.SS "float examples\&.gp\&.symbolicRegression\&.Sign\&.execute_float (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 54 of file Sign\&.java\&.
.SS "Object examples\&.gp\&.symbolicRegression\&.Sign\&.execute_object (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 80 of file Sign\&.java\&.
.SS "String examples\&.gp\&.symbolicRegression\&.Sign\&.getName ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
textual name of this command
.RE
.PP
\fBAuthor:\fP
.RS 4
Hakan Kjellerstrand (based on Klaus Meffert's Log file) 
.RE
.PP

.PP
Definition at line 50 of file Sign\&.java\&.
.SS "String examples\&.gp\&.symbolicRegression\&.Sign\&.toString ()\fC [inline]\fP"

.PP
Definition at line 41 of file Sign\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.gp\&.symbolicRegression\&.Sign\&.CVS_REVISION = '$Revision: 1\&.1 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 34 of file Sign\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
