.TH "examples.math.ReplVisitor" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.math.ReplVisitor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBexamples\&.math\&.MathVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "String \fBrender\fP (Operand theOp)"
.br
.ti -1c
.RI "void \fBvisit\fP (ValueOperand theOp)"
.br
.ti -1c
.RI "void \fBvisit\fP (AddOperator theOp)"
.br
.ti -1c
.RI "void \fBvisit\fP (MinusOperator theOp)"
.br
.ti -1c
.RI "void \fBvisit\fP (DivideOperator theOp)"
.br
.ti -1c
.RI "void \fBvisit\fP (MultiplyOperator theOp)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "StringBuffer \fBmBuffer\fP = new StringBuffer()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.1 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Only used in MathGene\&.toString()\&.
.PP
\fBAuthor:\fP
.RS 4
Michael Grove 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.2 
.RE
.PP

.PP
Definition at line 21 of file ReplVisitor\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void examples\&.math\&.ReplVisitor\&.main (String[]args)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 75 of file ReplVisitor\&.java\&.
.SS "String examples\&.math\&.ReplVisitor\&.render (OperandtheOp)\fC [inline]\fP"

.PP
Definition at line 32 of file ReplVisitor\&.java\&.
.SS "void examples\&.math\&.ReplVisitor\&.reset ()\fC [inline]\fP"

.PP
Definition at line 28 of file ReplVisitor\&.java\&.
.PP
References examples\&.math\&.ReplVisitor\&.mBuffer\&.
.SS "void examples\&.math\&.ReplVisitor\&.visit (ValueOperandtheOp)\fC [inline]\fP"

.PP
Implements \fBexamples\&.math\&.MathVisitor\fP\&.
.PP
Definition at line 39 of file ReplVisitor\&.java\&.
.SS "void examples\&.math\&.ReplVisitor\&.visit (AddOperatortheOp)\fC [inline]\fP"

.PP
Implements \fBexamples\&.math\&.MathVisitor\fP\&.
.PP
Definition at line 43 of file ReplVisitor\&.java\&.
.SS "void examples\&.math\&.ReplVisitor\&.visit (MinusOperatortheOp)\fC [inline]\fP"

.PP
Implements \fBexamples\&.math\&.MathVisitor\fP\&.
.PP
Definition at line 51 of file ReplVisitor\&.java\&.
.SS "void examples\&.math\&.ReplVisitor\&.visit (DivideOperatortheOp)\fC [inline]\fP"

.PP
Implements \fBexamples\&.math\&.MathVisitor\fP\&.
.PP
Definition at line 59 of file ReplVisitor\&.java\&.
.SS "void examples\&.math\&.ReplVisitor\&.visit (MultiplyOperatortheOp)\fC [inline]\fP"

.PP
Implements \fBexamples\&.math\&.MathVisitor\fP\&.
.PP
Definition at line 67 of file ReplVisitor\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.math\&.ReplVisitor\&.CVS_REVISION = '$Revision: 1\&.1 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 24 of file ReplVisitor\&.java\&.
.SS "StringBuffer examples\&.math\&.ReplVisitor\&.mBuffer = new StringBuffer()\fC [private]\fP"

.PP
Definition at line 26 of file ReplVisitor\&.java\&.
.PP
Referenced by examples\&.math\&.ReplVisitor\&.reset()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
