.TH "examples.grid.mathProblemDistributed.MyGenotypeInitializer" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.grid.mathProblemDistributed.MyGenotypeInitializer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits IGenotypeInitializerGP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGPGenotype\fP \fBsetupGenotype\fP (JGAPRequestGP a_req, GPPopulation a_initialPop)  throws Exception "
.br
.ti -1c
.RI "void \fBinitPop\fP (\fBGPConfiguration\fP conf, \fBGridConfiguration\fP gridConfig)  throws Exception "
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.7 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Initializes the genotype on behalf of the workers in a grid\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 22 of file MyGenotypeInitializer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void examples\&.grid\&.mathProblemDistributed\&.MyGenotypeInitializer\&.initPop (\fBGPConfiguration\fPconf, \fBGridConfiguration\fPgridConfig) throws Exception\fC [inline]\fP"
Initializes a partly or fully incomplete population on behalf of the worker\&.
.PP
\fBParameters:\fP
.RS 4
\fIconf\fP the GP configuration 
.br
\fIgridConfig\fP the grid configuration 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.6 
.RE
.PP

.PP
Definition at line 76 of file MyGenotypeInitializer\&.java\&.
.PP
Referenced by examples\&.grid\&.mathProblemDistributed\&.MyGenotypeInitializer\&.setupGenotype()\&.
.SS "\fBGPGenotype\fP examples\&.grid\&.mathProblemDistributed\&.MyGenotypeInitializer\&.setupGenotype (JGAPRequestGPa_req, GPPopulationa_initialPop) throws Exception\fC [inline]\fP"

.PP
Definition at line 27 of file MyGenotypeInitializer\&.java\&.
.PP
References org\&.jgap\&.Configuration\&.getPopulationSize(), and examples\&.grid\&.mathProblemDistributed\&.MyGenotypeInitializer\&.initPop()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.grid\&.mathProblemDistributed\&.MyGenotypeInitializer\&.CVS_REVISION = '$Revision: 1\&.7 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file MyGenotypeInitializer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
