.TH "examples.gp.paintedDesert.Y" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.gp.paintedDesert.Y \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBexamples\&.gp\&.paintedDesert\&.AntCommand\fP, and IMutateable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBY\fP (final \fBGPConfiguration\fP a_conf)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBY\fP (final \fBGPConfiguration\fP a_conf, final int a_subReturnType, final int[] a_childSubTypes)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBCommandGene\fP \fBapplyMutation\fP (int index, double a_percentage)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "int \fBexecute_int\fP (ProgramChromosome a_chrom, int a_n, Object[] a_args)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.1 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Look ahead, right and left (in this order) and turns to food in case such was detected\&. Does nothing in the other case\&.
.PP
This command is not part of the classic ant problem\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.01 
.RE
.PP

.PP
Definition at line 24 of file Y\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.gp\&.paintedDesert\&.Y\&.Y (final \fBGPConfiguration\fPa_conf) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_conf\fP the configuration to use
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIInvalidConfigurationException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.01 
.RE
.PP

.PP
Definition at line 39 of file Y\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.IntegerClass\&.
.SS "examples\&.gp\&.paintedDesert\&.Y\&.Y (final \fBGPConfiguration\fPa_conf, final inta_subReturnType, final int[]a_childSubTypes) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 44 of file Y\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.IntegerClass\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCommandGene\fP examples\&.gp\&.paintedDesert\&.Y\&.applyMutation (intindex, doublea_percentage) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 50 of file Y\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.getGPConfiguration()\&.
.SS "int examples\&.gp\&.paintedDesert\&.Y\&.execute_int (ProgramChromosomea_chrom, inta_n, Object[]a_args)\fC [inline]\fP"

.PP
Definition at line 57 of file Y\&.java\&.
.PP
References examples\&.gp\&.paintedDesert\&.AntCommand\&.getMap()\&.
.SS "String examples\&.gp\&.paintedDesert\&.Y\&.toString ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
the string representation of the command\&. Especially usefull to output a resulting formula in human-readable form\&. 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.gp\&.CommandGene\fP\&.
.PP
Definition at line 62 of file Y\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.gp\&.paintedDesert\&.Y\&.CVS_REVISION = '$Revision: 1\&.1 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 27 of file Y\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
