.TH "examples.supergene.SupergeneSampleApplicationTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.supergene.SupergeneSampleApplicationTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JGAPTestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestSupergeneTotal\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Test Supergene sample application, verifying the 'make change' supergene and non-supergene versions\&. Both must return a zero error\&. Performance is not verified\&.
.PP
\fBAuthor:\fP
.RS 4
Meskauskas Audrius 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 24 of file SupergeneSampleApplicationTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test examples\&.supergene\&.SupergeneSampleApplicationTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 48 of file SupergeneSampleApplicationTest\&.java\&.
.SS "void examples\&.supergene\&.SupergeneSampleApplicationTest\&.testSupergeneTotal ()\fC [inline]\fP"

.PP
Definition at line 29 of file SupergeneSampleApplicationTest\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.supergene\&.SupergeneSampleApplicationTest\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 27 of file SupergeneSampleApplicationTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
