.TH "examples.monalisa.core.LMSFitnessFunction" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.monalisa.core.LMSFitnessFunction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits FitnessFunction\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "double \fBevaluate\fP (IChromosome a_chromosome)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "final \fBGAConfiguration\fP \fBm_conf\fP"
.br
.ti -1c
.RI "final int[] \fBtargetPixels\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Computes the fitness of a program as the Least-Mean-Sqare distance between the image it generates and the target image\&.
.PP
\fBAuthor:\fP
.RS 4
Yann N\&. Dauphin 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4 
.RE
.PP

.PP
Definition at line 25 of file LMSFitnessFunction\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "double examples\&.monalisa\&.core\&.LMSFitnessFunction\&.evaluate (IChromosomea_chromosome)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 51 of file LMSFitnessFunction\&.java\&.
.PP
References examples\&.monalisa\&.core\&.LMSFitnessFunction\&.targetPixels\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.monalisa\&.core\&.LMSFitnessFunction\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 28 of file LMSFitnessFunction\&.java\&.
.SS "final \fBGAConfiguration\fP examples\&.monalisa\&.core\&.LMSFitnessFunction\&.m_conf\fC [private]\fP"

.PP
Definition at line 30 of file LMSFitnessFunction\&.java\&.
.SS "final int [] examples\&.monalisa\&.core\&.LMSFitnessFunction\&.targetPixels\fC [private]\fP"

.PP
Definition at line 32 of file LMSFitnessFunction\&.java\&.
.PP
Referenced by examples\&.monalisa\&.core\&.LMSFitnessFunction\&.evaluate()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
