.TH "examples.grid.fitnessDistributed.MyWorkerFeedback" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.grid.fitnessDistributed.MyWorkerFeedback \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits GridWorkerFeedback\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBbeginWorkingFor\fP (String a_sessionName, WorkRequest req)"
.br
.ti -1c
.RI "void \fBendWorkingFor\fP (WorkResult res)"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "String \fBm_sessionName\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.4 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Listener called on worker events\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.01 
.RE
.PP

.PP
Definition at line 22 of file MyWorkerFeedback\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void examples\&.grid\&.fitnessDistributed\&.MyWorkerFeedback\&.beginWorkingFor (Stringa_sessionName, WorkRequestreq)\fC [inline]\fP"

.PP
Definition at line 35 of file MyWorkerFeedback\&.java\&.
.PP
References examples\&.grid\&.fitnessDistributed\&.MyWorkerFeedback\&.m_sessionName\&.
.SS "void examples\&.grid\&.fitnessDistributed\&.MyWorkerFeedback\&.endWorkingFor (WorkResultres)\fC [inline]\fP"

.PP
Definition at line 41 of file MyWorkerFeedback\&.java\&.
.PP
References examples\&.grid\&.fitnessDistributed\&.MyWorkerFeedback\&.m_sessionName\&.
.SS "void examples\&.grid\&.fitnessDistributed\&.MyWorkerFeedback\&.start ()\fC [inline]\fP"
Called when listener is started\&. 
.PP
Definition at line 32 of file MyWorkerFeedback\&.java\&.
.SS "void examples\&.grid\&.fitnessDistributed\&.MyWorkerFeedback\&.stop ()\fC [inline]\fP"
Called when listener is stopped\&. 
.PP
Definition at line 50 of file MyWorkerFeedback\&.java\&.
.PP
References examples\&.grid\&.fitnessDistributed\&.MyWorkerFeedback\&.m_sessionName\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.grid\&.fitnessDistributed\&.MyWorkerFeedback\&.CVS_REVISION = '$Revision: 1\&.4 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file MyWorkerFeedback\&.java\&.
.SS "String examples\&.grid\&.fitnessDistributed\&.MyWorkerFeedback\&.m_sessionName\fC [private]\fP"

.PP
Definition at line 27 of file MyWorkerFeedback\&.java\&.
.PP
Referenced by examples\&.grid\&.fitnessDistributed\&.MyWorkerFeedback\&.beginWorkingFor(), examples\&.grid\&.fitnessDistributed\&.MyWorkerFeedback\&.endWorkingFor(), and examples\&.grid\&.fitnessDistributed\&.MyWorkerFeedback\&.stop()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
