.TH "examples.gp.KarubProblem" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.gp.KarubProblem \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.gp\&.GPProblem\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFormulaFitnessFunction\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKarubProblem\fP (\fBGPConfiguration\fP a_conf)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBGPGenotype\fP \fBcreate\fP ()  throws InvalidConfigurationException "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)  throws Exception "
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBVariable\fP \fBvx\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Sort of minimal GP problem definition\&. Does not stop when best solution found\&. Discovers a very simple formula (see comments in code!)\&.
.PP
Only there to show the general setup\&.
.PP
Inspired by user Karub (who wrote most of the code in this class), therefor 'KarubProblem'
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.5 
.RE
.PP

.PP
Definition at line 39 of file KarubProblem\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.gp\&.KarubProblem\&.KarubProblem (\fBGPConfiguration\fPa_conf) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 43 of file KarubProblem\&.java\&.
.PP
Referenced by examples\&.gp\&.KarubProblem\&.main()\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBGPGenotype\fP examples\&.gp\&.KarubProblem\&.create () throws \fBInvalidConfigurationException\fP\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
newly created GPGenotype 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIInvalidConfigurationException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.gp\&.GPProblem\fP\&.
.PP
Definition at line 48 of file KarubProblem\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.BooleanClass, org\&.jgap\&.gp\&.GPProblem\&.getGPConfiguration(), org\&.jgap\&.gp\&.CommandGene\&.IntegerClass, and examples\&.gp\&.KarubProblem\&.vx\&.
.SS "static void examples\&.gp\&.KarubProblem\&.main (String[]args) throws Exception\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 67 of file KarubProblem\&.java\&.
.PP
References examples\&.gp\&.KarubProblem\&.KarubProblem()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBVariable\fP examples\&.gp\&.KarubProblem\&.vx\fC [static]\fP"

.PP
Definition at line 41 of file KarubProblem\&.java\&.
.PP
Referenced by examples\&.gp\&.KarubProblem\&.create()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
