.TH "examples.gp.tictactoe.IsOwnColor" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.gp.tictactoe.IsOwnColor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.gp\&.CommandGene\fP, and \fBorg\&.jgap\&.util\&.ICloneable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIsOwnColor\fP (final \fBGPConfiguration\fP a_conf, int a_color)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBIsOwnColor\fP (final \fBGPConfiguration\fP a_conf, int a_color, int a_subReturnType, int a_subChildType)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "boolean \fBexecute_boolean\fP (\fBProgramChromosome\fP c, int n, Object[] args)"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "Object \fBclone\fP ()"
.br
.ti -1c
.RI "Class \fBgetChildType\fP (\fBIGPProgram\fP a_ind, int a_chromNum)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_color\fP"
.br
.ti -1c
.RI "int \fBm_subChildType\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.4 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file IsOwnColor\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.gp\&.tictactoe\&.IsOwnColor\&.IsOwnColor (final \fBGPConfiguration\fPa_conf, inta_color) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 26 of file IsOwnColor\&.java\&.
.PP
Referenced by examples\&.gp\&.tictactoe\&.IsOwnColor\&.clone()\&.
.SS "examples\&.gp\&.tictactoe\&.IsOwnColor\&.IsOwnColor (final \fBGPConfiguration\fPa_conf, inta_color, inta_subReturnType, inta_subChildType) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 31 of file IsOwnColor\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.BooleanClass, examples\&.gp\&.tictactoe\&.IsOwnColor\&.m_color, and examples\&.gp\&.tictactoe\&.IsOwnColor\&.m_subChildType\&.
.SH "Member Function Documentation"
.PP 
.SS "Object examples\&.gp\&.tictactoe\&.IsOwnColor\&.clone ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
clone of the current object instance 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.util\&.ICloneable\fP\&.
.PP
Definition at line 59 of file IsOwnColor\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.getGPConfiguration(), org\&.jgap\&.gp\&.CommandGene\&.getSubReturnType(), examples\&.gp\&.tictactoe\&.IsOwnColor\&.IsOwnColor(), examples\&.gp\&.tictactoe\&.IsOwnColor\&.m_color, and examples\&.gp\&.tictactoe\&.IsOwnColor\&.m_subChildType\&.
.SS "boolean examples\&.gp\&.tictactoe\&.IsOwnColor\&.execute_boolean (\fBProgramChromosome\fPc, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 43 of file IsOwnColor\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.check(), and examples\&.gp\&.tictactoe\&.IsOwnColor\&.m_color\&.
.SS "Class examples\&.gp\&.tictactoe\&.IsOwnColor\&.getChildType (\fBIGPProgram\fPa_ind, inta_chromNum)\fC [inline]\fP"

.PP
Definition at line 69 of file IsOwnColor\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.IntegerClass\&.
.SS "String examples\&.gp\&.tictactoe\&.IsOwnColor\&.getName ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
textual name of this command
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 55 of file IsOwnColor\&.java\&.
.SS "String examples\&.gp\&.tictactoe\&.IsOwnColor\&.toString ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
the string representation of the command\&. Especially usefull to output a resulting formula in human-readable form\&. 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.gp\&.CommandGene\fP\&.
.PP
Definition at line 39 of file IsOwnColor\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.gp\&.tictactoe\&.IsOwnColor\&.CVS_REVISION = '$Revision: 1\&.4 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 20 of file IsOwnColor\&.java\&.
.SS "int examples\&.gp\&.tictactoe\&.IsOwnColor\&.m_color\fC [private]\fP"

.PP
Definition at line 22 of file IsOwnColor\&.java\&.
.PP
Referenced by examples\&.gp\&.tictactoe\&.IsOwnColor\&.clone(), examples\&.gp\&.tictactoe\&.IsOwnColor\&.execute_boolean(), and examples\&.gp\&.tictactoe\&.IsOwnColor\&.IsOwnColor()\&.
.SS "int examples\&.gp\&.tictactoe\&.IsOwnColor\&.m_subChildType\fC [private]\fP"

.PP
Definition at line 24 of file IsOwnColor\&.java\&.
.PP
Referenced by examples\&.gp\&.tictactoe\&.IsOwnColor\&.clone(), and examples\&.gp\&.tictactoe\&.IsOwnColor\&.IsOwnColor()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
