.TH "examples.gp.monalisa.gui.GeneticDrawingView" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.gp.monalisa.gui.GeneticDrawingView \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits FrameView\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeneticDrawingView\fP (SingleFrameApplication app)"
.br
.ti -1c
.RI "void \fBshowAboutBox\fP ()"
.br
.ti -1c
.RI "void \fBchooseImage\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBstartEvolution\fP ()"
.br
.ti -1c
.RI "ImageIcon \fBscaleToImageLabel\fP (Image image)"
.br
.ti -1c
.RI "BufferedImage \fBgetTargetImage\fP ()"
.br
.ti -1c
.RI "boolean \fBisEvolutionActivated\fP ()"
.br
.ti -1c
.RI "boolean \fBisSaveToFile\fP ()"
.br
.ti -1c
.RI "\fBFittestDrawingView\fP \fBgetFittestDrawingView\fP ()"
.br
.ti -1c
.RI "JFreeChart \fBgetChart\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitComponents\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "javax\&.swing\&.JPanel \fBchartPanel\fP"
.br
.ti -1c
.RI "javax\&.swing\&.JButton \fBchooseImage\fP"
.br
.ti -1c
.RI "javax\&.swing\&.JPanel \fBmainPanel\fP"
.br
.ti -1c
.RI "javax\&.swing\&.JMenuBar \fBmenuBar\fP"
.br
.ti -1c
.RI "javax\&.swing\&.JToggleButton \fBstartEvolution\fP"
.br
.ti -1c
.RI "javax\&.swing\&.JLabel \fBtargetImageLabel\fP"
.br
.ti -1c
.RI "JDialog \fBaboutBox\fP"
.br
.ti -1c
.RI "javax\&.swing\&.JCheckBox \fBsaveCheckBox\fP"
.br
.ti -1c
.RI "javax\&.swing\&.JLabel \fBtargetSaveDirLabel\fP"
.br
.ti -1c
.RI "javax\&.swing\&.JLabel \fBtargetSaveDirEdit\fP"
.br
.ti -1c
.RI "BufferedImage \fBtargetImage\fP = null"
.br
.ti -1c
.RI "boolean \fBisEvolutionActivated\fP = false"
.br
.ti -1c
.RI "\fBFittestDrawingView\fP \fBfittestDrawingView\fP = null"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
The application's main frame\&.
.PP
\fBAuthor:\fP
.RS 4
Yann N\&. Dauphin 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4 
.RE
.PP

.PP
Definition at line 29 of file GeneticDrawingView\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.GeneticDrawingView (SingleFrameApplicationapp)\fC [inline]\fP"

.PP
Definition at line 34 of file GeneticDrawingView\&.java\&.
.PP
References examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.fittestDrawingView, examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.initComponents(), and examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.targetImage\&.
.SH "Member Function Documentation"
.PP 
.SS "void examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.chooseImage () throws IOException\fC [inline]\fP"

.PP
Definition at line 59 of file GeneticDrawingView\&.java\&.
.PP
References examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.mainPanel, examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.scaleToImageLabel(), and examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.targetImage\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.initComponents()\&.
.SS "JFreeChart examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.getChart ()\fC [inline]\fP"

.PP
Definition at line 121 of file GeneticDrawingView\&.java\&.
.PP
References examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.chartPanel\&.
.SS "\fBFittestDrawingView\fP examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.getFittestDrawingView ()\fC [inline]\fP"

.PP
Definition at line 117 of file GeneticDrawingView\&.java\&.
.PP
References examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.fittestDrawingView\&.
.SS "BufferedImage examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.getTargetImage ()\fC [inline]\fP"

.PP
Definition at line 105 of file GeneticDrawingView\&.java\&.
.PP
References examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.targetImage\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.EvolutionRunnable\&.run()\&.
.SS "void examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.initComponents ()\fC [inline]\fP, \fC [private]\fP"
This method is called from within the constructor to initialize the form\&. WARNING: Do NOT modify this code\&. The content of this method is always regenerated by the Form Editor\&. 
.PP
Definition at line 133 of file GeneticDrawingView\&.java\&.
.PP
References examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.chartPanel, examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.chooseImage(), examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.mainPanel, examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.menuBar, examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.saveCheckBox, examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.startEvolution(), examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.targetImageLabel, examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.targetSaveDirEdit, and examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.targetSaveDirLabel\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.GeneticDrawingView()\&.
.SS "boolean examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.isEvolutionActivated ()\fC [inline]\fP"

.PP
Definition at line 109 of file GeneticDrawingView\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.startEvolution()\&.
.SS "boolean examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.isSaveToFile ()\fC [inline]\fP"

.PP
Definition at line 113 of file GeneticDrawingView\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.EvolutionRunnable\&.run()\&.
.SS "ImageIcon examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.scaleToImageLabel (Imageimage)\fC [inline]\fP"
Scale an image to fit the size of the targetImageLabel\&. 
.PP
Definition at line 92 of file GeneticDrawingView\&.java\&.
.PP
References examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.targetImageLabel\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.chooseImage()\&.
.SS "void examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.showAboutBox ()\fC [inline]\fP"

.PP
Definition at line 49 of file GeneticDrawingView\&.java\&.
.PP
References examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.aboutBox\&.
.SS "void examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.startEvolution ()\fC [inline]\fP"

.PP
Definition at line 71 of file GeneticDrawingView\&.java\&.
.PP
References examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.isEvolutionActivated(), and examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.targetImage\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.initComponents()\&.
.SH "Member Data Documentation"
.PP 
.SS "JDialog examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.aboutBox\fC [private]\fP"

.PP
Definition at line 290 of file GeneticDrawingView\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.showAboutBox()\&.
.SS "javax\&.swing\&.JPanel examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.chartPanel\fC [private]\fP"

.PP
Definition at line 277 of file GeneticDrawingView\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.getChart(), and examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.initComponents()\&.
.SS "javax\&.swing\&.JButton examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.chooseImage\fC [private]\fP"

.PP
Definition at line 279 of file GeneticDrawingView\&.java\&.
.SS "final String examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 32 of file GeneticDrawingView\&.java\&.
.SS "\fBFittestDrawingView\fP examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.fittestDrawingView = null\fC [private]\fP"

.PP
Definition at line 302 of file GeneticDrawingView\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.GeneticDrawingView(), and examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.getFittestDrawingView()\&.
.SS "boolean examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.isEvolutionActivated = false\fC [private]\fP"

.PP
Definition at line 300 of file GeneticDrawingView\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.EvolutionRunnable\&.run()\&.
.SS "javax\&.swing\&.JPanel examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.mainPanel\fC [private]\fP"

.PP
Definition at line 281 of file GeneticDrawingView\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.chooseImage(), and examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.initComponents()\&.
.SS "javax\&.swing\&.JMenuBar examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.menuBar\fC [private]\fP"

.PP
Definition at line 283 of file GeneticDrawingView\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.initComponents()\&.
.SS "javax\&.swing\&.JCheckBox examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.saveCheckBox\fC [private]\fP"

.PP
Definition at line 292 of file GeneticDrawingView\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.initComponents()\&.
.SS "javax\&.swing\&.JToggleButton examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.startEvolution\fC [private]\fP"

.PP
Definition at line 285 of file GeneticDrawingView\&.java\&.
.SS "BufferedImage examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.targetImage = null\fC [private]\fP"

.PP
Definition at line 298 of file GeneticDrawingView\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.chooseImage(), examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.GeneticDrawingView(), examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.getTargetImage(), and examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.startEvolution()\&.
.SS "javax\&.swing\&.JLabel examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.targetImageLabel\fC [private]\fP"

.PP
Definition at line 287 of file GeneticDrawingView\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.initComponents(), and examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.scaleToImageLabel()\&.
.SS "javax\&.swing\&.JLabel examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.targetSaveDirEdit\fC [private]\fP"

.PP
Definition at line 296 of file GeneticDrawingView\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.initComponents()\&.
.SS "javax\&.swing\&.JLabel examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.targetSaveDirLabel\fC [private]\fP"

.PP
Definition at line 294 of file GeneticDrawingView\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingView\&.initComponents()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
