.TH "examples.gp.monalisa.core.DrawingProblem.TerminalType" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.gp.monalisa.core.DrawingProblem.TerminalType \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBintValue\fP ()"
.br
.ti -1c
.RI "\fBTerminalType\fP (int a_value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBWIDTH\fP =(1)"
.br
.ti -1c
.RI "\fBHEIGHT\fP =(2)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTerminalType\fP helps differentiate the terminals that have different ranges\&. 
.PP
Definition at line 88 of file DrawingProblem\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.gp\&.monalisa\&.core\&.DrawingProblem\&.TerminalType\&.TerminalType (inta_value)\fC [inline]\fP"

.PP
Definition at line 98 of file DrawingProblem\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int examples\&.gp\&.monalisa\&.core\&.DrawingProblem\&.TerminalType\&.intValue ()\fC [inline]\fP"

.PP
Definition at line 94 of file DrawingProblem\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "examples\&.gp\&.monalisa\&.core\&.DrawingProblem\&.TerminalType\&.HEIGHT =(2)"

.PP
Definition at line 90 of file DrawingProblem\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.core\&.DrawingProblem\&.create()\&.
.SS "int examples\&.gp\&.monalisa\&.core\&.DrawingProblem\&.TerminalType\&.m_value\fC [private]\fP"

.PP
Definition at line 92 of file DrawingProblem\&.java\&.
.SS "examples\&.gp\&.monalisa\&.core\&.DrawingProblem\&.TerminalType\&.WIDTH =(1)"

.PP
Definition at line 89 of file DrawingProblem\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.core\&.DrawingProblem\&.create()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
