.TH "examples.math.PhenotypeExpresser< T >" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.math.PhenotypeExpresser< T > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "T \fBexpress\fP (IChromosome theChromosome)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.1 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Michael Grove 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.2 
.RE
.PP

.PP
Definition at line 20 of file PhenotypeExpresser\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "T examples\&.math\&.PhenotypeExpresser< T >\&.express (IChromosometheChromosome)"

.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.math\&.PhenotypeExpresser< T >\&.CVS_REVISION = '$Revision: 1\&.1 $'\fC [static]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 22 of file PhenotypeExpresser\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
