.TH "examples.math.cmd.Operand" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.math.cmd.Operand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ICloneable\&.
.PP
Inherited by \fBexamples\&.math\&.cmd\&.Operator\fP, and \fBexamples\&.math\&.cmd\&.ValueOperand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBvalue\fP ()"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBMathVisitor\fP theVisitor)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.1 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for mathematical operands\&.
.PP
\fBAuthor:\fP
.RS 4
Michael Grove 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.2 
.RE
.PP

.PP
Definition at line 22 of file Operand\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void examples\&.math\&.cmd\&.Operand\&.accept (\fBMathVisitor\fPtheVisitor)"

.PP
Implemented in \fBexamples\&.math\&.cmd\&.ValueOperand\fP, \fBexamples\&.math\&.cmd\&.AddOperator\fP, \fBexamples\&.math\&.cmd\&.DivideOperator\fP, \fBexamples\&.math\&.cmd\&.MinusOperator\fP, and \fBexamples\&.math\&.cmd\&.MultiplyOperator\fP\&.
.SS "double examples\&.math\&.cmd\&.Operand\&.value ()"

.PP
Implemented in \fBexamples\&.math\&.cmd\&.MathOperator\fP, and \fBexamples\&.math\&.cmd\&.ValueOperand\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.math\&.cmd\&.Operand\&.CVS_REVISION = '$Revision: 1\&.1 $'\fC [static]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file Operand\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
