.TH "examples.monalisa.core.AlphaMutationOperator" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.monalisa.core.AlphaMutationOperator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MutationOperator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlphaMutationOperator\fP (final Configuration a_config, final int a_desiredMutationRate)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "void \fBoperate\fP (final Population a_population, final List a_candidateChromosomes)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBmutateGene\fP (final Gene a_gene, final RandomGenerator a_generator)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.3 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Makes a polygon of each chromosome transparent\&.
.PP
\fBAuthor:\fP
.RS 4
Yann N\&. Dauphin 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4 
.RE
.PP

.PP
Definition at line 23 of file AlphaMutationOperator\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.monalisa\&.core\&.AlphaMutationOperator\&.AlphaMutationOperator (final Configurationa_config, final inta_desiredMutationRate) throws InvalidConfigurationException\fC [inline]\fP"

.PP
Definition at line 28 of file AlphaMutationOperator\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void examples\&.monalisa\&.core\&.AlphaMutationOperator\&.mutateGene (final Genea_gene, final RandomGeneratora_generator)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line 151 of file AlphaMutationOperator\&.java\&.
.PP
Referenced by examples\&.monalisa\&.core\&.AlphaMutationOperator\&.operate()\&.
.SS "void examples\&.monalisa\&.core\&.AlphaMutationOperator\&.operate (final Populationa_population, final Lista_candidateChromosomes)\fC [inline]\fP"

.PP
\fBTodo\fP
.RS 4
move to base class, refactor 
.RE
.PP

.PP
Definition at line 35 of file AlphaMutationOperator\&.java\&.
.PP
References examples\&.monalisa\&.core\&.AlphaMutationOperator\&.mutateGene()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.monalisa\&.core\&.AlphaMutationOperator\&.CVS_REVISION = '$Revision: 1\&.3 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file AlphaMutationOperator\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
