.TH "examples.config.MaximizingFunction" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.config.MaximizingFunction \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaximizingFunction\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String args[])  throws Exception"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.9 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is to test the working of JGAP with a config file provided for configuring JGAP\&. The problem statement is to maximize the value of the function f(a,b,c) = (a - b + c)\&. This is trivial but works fine for the purpose of demonstration of the working of JGAP with a config file\&. Reasonable bounds have been set up for the values of a, b and c\&.
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 27 of file MaximizingFunction\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.config\&.MaximizingFunction\&.MaximizingFunction ()\fC [inline]\fP"
Default Constructor 
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 36 of file MaximizingFunction\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void examples\&.config\&.MaximizingFunction\&.main (Stringargs[]) throws Exception\fC [inline]\fP, \fC [static]\fP"
Starting the example 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP not used 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 47 of file MaximizingFunction\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.config\&.MaximizingFunction\&.CVS_REVISION = '$Revision: 1\&.9 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 29 of file MaximizingFunction\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
