.TH "examples.math.ga.MathRunnerConfiguration" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.math.ga.MathRunnerConfiguration \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Configuration\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMathRunnerConfiguration\fP ()  throws InvalidConfigurationException "
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.1 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Genetic configuration for the example\&.
.PP
\fBAuthor:\fP
.RS 4
Michael Grove 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.2 
.RE
.PP

.PP
Definition at line 24 of file MathRunnerConfiguration\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.math\&.ga\&.MathRunnerConfiguration\&.MathRunnerConfiguration () throws InvalidConfigurationException\fC [inline]\fP"

.PP
Definition at line 29 of file MathRunnerConfiguration\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.math\&.ga\&.MathRunnerConfiguration\&.CVS_REVISION = '$Revision: 1\&.1 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 27 of file MathRunnerConfiguration\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
