.TH "examples.chromInit.MaxFunction" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.chromInit.MaxFunction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits FitnessFunction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBevaluate\fP (IChromosome a_subject)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.4 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Fitness function for our example\&. See evolve() method for details\&.
.PP
\fBAuthor:\fP
.RS 4
Neil Rotstan 
.PP
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 22 of file MaxFunction\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "double examples\&.chromInit\&.MaxFunction\&.evaluate (IChromosomea_subject)\fC [inline]\fP"
See \fBexamples\&.simpleBoolean\&.MaxFunction\fP for description\&. Please notice that in this example here, we have chromosomes with one and Chromosomes with two Genes, so that the description from the original \fBMaxFunction\fP does not apply directly here\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa_subject\fP the Chromosome to be evaluated 
.RE
.PP
\fBReturns:\fP
.RS 4
defect rate of our problem
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 38 of file MaxFunction\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.chromInit\&.MaxFunction\&.CVS_REVISION = '$Revision: 1\&.4 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file MaxFunction\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
