.TH "examples.math.cmd.MultiplyOperator" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.math.cmd.MultiplyOperator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBexamples\&.math\&.cmd\&.MathOperator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultiplyOperator\fP ()"
.br
.ti -1c
.RI "\fBMultiplyOperator\fP (\fBOperand\fP theLeft, \fBOperand\fP theRight)"
.br
.ti -1c
.RI "double \fBcalcuate\fP ()"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBMathVisitor\fP theVisitor)"
.br
.ti -1c
.RI "Object \fBclone\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.1 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The multiply operator\&.
.PP
\fBAuthor:\fP
.RS 4
Michael Grove 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.2 
.RE
.PP

.PP
Definition at line 20 of file MultiplyOperator\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.math\&.cmd\&.MultiplyOperator\&.MultiplyOperator ()\fC [inline]\fP"

.PP
Definition at line 25 of file MultiplyOperator\&.java\&.
.PP
Referenced by examples\&.math\&.cmd\&.MultiplyOperator\&.clone()\&.
.SS "examples\&.math\&.cmd\&.MultiplyOperator\&.MultiplyOperator (\fBOperand\fPtheLeft, \fBOperand\fPtheRight)\fC [inline]\fP"

.PP
Definition at line 29 of file MultiplyOperator\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void examples\&.math\&.cmd\&.MultiplyOperator\&.accept (\fBMathVisitor\fPtheVisitor)\fC [inline]\fP"

.PP
Implements \fBexamples\&.math\&.cmd\&.Operand\fP\&.
.PP
Definition at line 37 of file MultiplyOperator\&.java\&.
.SS "double examples\&.math\&.cmd\&.MultiplyOperator\&.calcuate ()\fC [inline]\fP"

.PP
Implements \fBexamples\&.math\&.cmd\&.Operator\fP\&.
.PP
Definition at line 33 of file MultiplyOperator\&.java\&.
.PP
References examples\&.math\&.cmd\&.MathOperator\&.getLeftOperand(), and examples\&.math\&.cmd\&.MathOperator\&.getRightOperand()\&.
.SS "Object examples\&.math\&.cmd\&.MultiplyOperator\&.clone ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBexamples\&.math\&.cmd\&.MathOperator\fP\&.
.PP
Definition at line 41 of file MultiplyOperator\&.java\&.
.PP
References examples\&.math\&.cmd\&.MultiplyOperator\&.MultiplyOperator()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.math\&.cmd\&.MultiplyOperator\&.CVS_REVISION = '$Revision: 1\&.1 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 23 of file MultiplyOperator\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
