.TH "examples.gp.monalisa.core.LMSFitnessFunction" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.gp.monalisa.core.LMSFitnessFunction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.gp\&.GPFitnessFunction\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "double \fBevaluate\fP (final \fBIGPProgram\fP a_subject)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "final \fBDrawingGPConfiguration\fP \fBm_conf\fP"
.br
.ti -1c
.RI "final \fBDrawingGPProgramRunner\fP \fBprogramRunner\fP"
.br
.ti -1c
.RI "final int[] \fBtargetPixels\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.4 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Computes the fitness of a program as the Least-Mean-Sqare distance between the image it generates and the target image\&.
.PP
\fBAuthor:\fP
.RS 4
Yann N\&. Dauphin 
.PP
Klaus Meffert (enhancement) 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4 
.RE
.PP

.PP
Definition at line 25 of file LMSFitnessFunction\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "double examples\&.gp\&.monalisa\&.core\&.LMSFitnessFunction\&.evaluate (final \fBIGPProgram\fPa_subject)\fC [inline]\fP, \fC [protected]\fP"
5 Bytes per Polygon
.IP "\(bu" 2
Delimiter: 1 Byte (-1 for first Polygon)
.IP "\(bu" 2
Color (R, G, B, Alpha): 4 Bytes (simplified) 2 Bytes per Point:
.IP "\(bu" 2
X: 1 Byte
.IP "\(bu" 2
Y: 1 Byte
.PP

.PP
Definition at line 54 of file LMSFitnessFunction\&.java\&.
.PP
References examples\&.gp\&.monalisa\&.core\&.LMSFitnessFunction\&.targetPixels\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.gp\&.monalisa\&.core\&.LMSFitnessFunction\&.CVS_REVISION = '$Revision: 1\&.4 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 28 of file LMSFitnessFunction\&.java\&.
.SS "final \fBDrawingGPConfiguration\fP examples\&.gp\&.monalisa\&.core\&.LMSFitnessFunction\&.m_conf\fC [private]\fP"

.PP
Definition at line 30 of file LMSFitnessFunction\&.java\&.
.SS "final \fBDrawingGPProgramRunner\fP examples\&.gp\&.monalisa\&.core\&.LMSFitnessFunction\&.programRunner\fC [private]\fP"

.PP
Definition at line 32 of file LMSFitnessFunction\&.java\&.
.SS "final int [] examples\&.gp\&.monalisa\&.core\&.LMSFitnessFunction\&.targetPixels\fC [private]\fP"

.PP
Definition at line 34 of file LMSFitnessFunction\&.java\&.
.PP
Referenced by examples\&.gp\&.monalisa\&.core\&.LMSFitnessFunction\&.evaluate()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
