.TH "examples.monalisa.gui.FittestDrawingView" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.monalisa.gui.FittestDrawingView \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JFrame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFittestDrawingView\fP ()"
.br
.ti -1c
.RI "javax\&.swing\&.JPanel \fBgetMainPanel\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitComponents\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "javax\&.swing\&.JPanel \fBmainPanel\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Yann N\&. Dauphin 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4 
.RE
.PP

.PP
Definition at line 17 of file FittestDrawingView\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.monalisa\&.gui\&.FittestDrawingView\&.FittestDrawingView ()\fC [inline]\fP"

.PP
Definition at line 22 of file FittestDrawingView\&.java\&.
.PP
References examples\&.monalisa\&.gui\&.FittestDrawingView\&.initComponents()\&.
.SH "Member Function Documentation"
.PP 
.SS "javax\&.swing\&.JPanel examples\&.monalisa\&.gui\&.FittestDrawingView\&.getMainPanel ()\fC [inline]\fP"

.PP
Definition at line 26 of file FittestDrawingView\&.java\&.
.PP
References examples\&.monalisa\&.gui\&.FittestDrawingView\&.mainPanel\&.
.SS "void examples\&.monalisa\&.gui\&.FittestDrawingView\&.initComponents ()\fC [inline]\fP, \fC [private]\fP"
This method is called from within the constructor to initialize the form\&. WARNING: Do NOT modify this code\&. The content of this method is always regenerated by the Form Editor\&. 
.PP
Definition at line 37 of file FittestDrawingView\&.java\&.
.PP
References examples\&.monalisa\&.gui\&.FittestDrawingView\&.mainPanel\&.
.PP
Referenced by examples\&.monalisa\&.gui\&.FittestDrawingView\&.FittestDrawingView()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.monalisa\&.gui\&.FittestDrawingView\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 20 of file FittestDrawingView\&.java\&.
.SS "javax\&.swing\&.JPanel examples\&.monalisa\&.gui\&.FittestDrawingView\&.mainPanel\fC [private]\fP"

.PP
Definition at line 79 of file FittestDrawingView\&.java\&.
.PP
Referenced by examples\&.monalisa\&.gui\&.FittestDrawingView\&.getMainPanel(), and examples\&.monalisa\&.gui\&.FittestDrawingView\&.initComponents()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
