.TH "examples.gp.tictactoe.PutStone1" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.gp.tictactoe.PutStone1 \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.gp\&.CommandGene\fP, and \fBorg\&.jgap\&.util\&.ICloneable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPutStone1\fP (final \fBGPConfiguration\fP a_conf, \fBBoard\fP a_board, int a_color)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBPutStone1\fP (final \fBGPConfiguration\fP a_conf, \fBBoard\fP a_board, int a_color, int a_subReturnType, int a_subChildType)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "void \fBexecute_void\fP (\fBProgramChromosome\fP c, int n, Object[] args)"
.br
.ti -1c
.RI "Class \fBgetChildType\fP (\fBIGPProgram\fP a_ind, int a_chromNum)"
.br
.ti -1c
.RI "Object \fBclone\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBcheck\fP (\fBProgramChromosome\fP a_program)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBBoard\fP \fBm_board\fP"
.br
.ti -1c
.RI "int \fBm_color\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.4 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Puts a stone on a board\&. Accepts one parameters, representing X and Y coordinates on the board at the same time\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2? 
.RE
.PP

.PP
Definition at line 24 of file PutStone1\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.gp\&.tictactoe\&.PutStone1\&.PutStone1 (final \fBGPConfiguration\fPa_conf, \fBBoard\fPa_board, inta_color) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 33 of file PutStone1\&.java\&.
.PP
Referenced by examples\&.gp\&.tictactoe\&.PutStone1\&.clone()\&.
.SS "examples\&.gp\&.tictactoe\&.PutStone1\&.PutStone1 (final \fBGPConfiguration\fPa_conf, \fBBoard\fPa_board, inta_color, inta_subReturnType, inta_subChildType) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 38 of file PutStone1\&.java\&.
.PP
References examples\&.gp\&.tictactoe\&.PutStone1\&.m_board, examples\&.gp\&.tictactoe\&.PutStone1\&.m_color, and org\&.jgap\&.gp\&.CommandGene\&.VoidClass\&.
.SH "Member Function Documentation"
.PP 
.SS "void examples\&.gp\&.tictactoe\&.PutStone1\&.check (\fBProgramChromosome\fPa_program)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 69 of file PutStone1\&.java\&.
.PP
References examples\&.gp\&.tictactoe\&.Board\&.getLastColor(), examples\&.gp\&.tictactoe\&.PutStone1\&.m_board, and examples\&.gp\&.tictactoe\&.PutStone1\&.m_color\&.
.PP
Referenced by examples\&.gp\&.tictactoe\&.PutStone1\&.execute_void()\&.
.SS "Object examples\&.gp\&.tictactoe\&.PutStone1\&.clone ()\fC [inline]\fP"
Clones the object\&. Simple and straight forward implementation here\&.
.PP
\fBReturns:\fP
.RS 4
cloned instance of this object
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.util\&.ICloneable\fP\&.
.PP
Definition at line 97 of file PutStone1\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.getGPConfiguration(), org\&.jgap\&.gp\&.CommandGene\&.getSubChildType(), org\&.jgap\&.gp\&.CommandGene\&.getSubReturnType(), examples\&.gp\&.tictactoe\&.PutStone1\&.m_board, examples\&.gp\&.tictactoe\&.PutStone1\&.m_color, and examples\&.gp\&.tictactoe\&.PutStone1\&.PutStone1()\&.
.SS "void examples\&.gp\&.tictactoe\&.PutStone1\&.execute_void (\fBProgramChromosome\fPc, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 50 of file PutStone1\&.java\&.
.PP
References examples\&.gp\&.tictactoe\&.PutStone1\&.check(), org\&.jgap\&.gp\&.impl\&.ProgramChromosome\&.getGene(), org\&.jgap\&.gp\&.CommandGene\&.getName(), examples\&.gp\&.tictactoe\&.Board\&.HEIGHT, examples\&.gp\&.tictactoe\&.PutStone1\&.m_color, and examples\&.gp\&.tictactoe\&.Board\&.WIDTH\&.
.SS "Class examples\&.gp\&.tictactoe\&.PutStone1\&.getChildType (\fBIGPProgram\fPa_ind, inta_chromNum)\fC [inline]\fP"
Determines which type a specific child of this command has\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_ind\fP ignored here 
.br
\fIa_chromNum\fP index of child 
.RE
.PP
\fBReturns:\fP
.RS 4
type of the a_chromNum'th child
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 85 of file PutStone1\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.IntegerClass\&.
.SS "String examples\&.gp\&.tictactoe\&.PutStone1\&.toString ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
the string representation of the command\&. Especially usefull to output a resulting formula in human-readable form\&. 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.gp\&.CommandGene\fP\&.
.PP
Definition at line 46 of file PutStone1\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.gp\&.tictactoe\&.PutStone1\&.CVS_REVISION = '$Revision: 1\&.4 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 27 of file PutStone1\&.java\&.
.SS "\fBBoard\fP examples\&.gp\&.tictactoe\&.PutStone1\&.m_board\fC [private]\fP"

.PP
Definition at line 29 of file PutStone1\&.java\&.
.PP
Referenced by examples\&.gp\&.tictactoe\&.PutStone1\&.check(), examples\&.gp\&.tictactoe\&.PutStone1\&.clone(), and examples\&.gp\&.tictactoe\&.PutStone1\&.PutStone1()\&.
.SS "int examples\&.gp\&.tictactoe\&.PutStone1\&.m_color\fC [private]\fP"

.PP
Definition at line 31 of file PutStone1\&.java\&.
.PP
Referenced by examples\&.gp\&.tictactoe\&.PutStone1\&.check(), examples\&.gp\&.tictactoe\&.PutStone1\&.clone(), examples\&.gp\&.tictactoe\&.PutStone1\&.execute_void(), and examples\&.gp\&.tictactoe\&.PutStone1\&.PutStone1()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
