.TH "examples.distinctGenes.MyChromosome" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.distinctGenes.MyChromosome \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Chromosome\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyChromosome\fP ()  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBMyChromosome\fP (final Configuration a_configuration)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBMyChromosome\fP (final Configuration a_configuration, final int a_desiredSize)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBMyChromosome\fP (final Configuration a_configuration, final Gene a_sampleGene, final int a_desiredSize)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBMyChromosome\fP (final Configuration a_configuration, final Gene[] a_initialGenes)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBMyChromosome\fP (final Configuration a_configuration, Gene a_sampleGene, int a_desiredSize, IGeneConstraintChecker a_constraintChecker)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "boolean \fBisHandlerFor\fP (Object a_obj, Class a_class)"
.br
.ti -1c
.RI "Object \fBperform\fP (Object a_obj, Class a_class, Object a_params)  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static IChromosome \fBrandomInitialMyChromosome\fP (Configuration a_configuration)  throws InvalidConfigurationException "
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.4 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Sample class: Descendent of Chromosome that creates Chromosomes with n CompositeGenes\&. All but one CompositeGene's have 4 sub-genes, the last one has only 3 sub-genes\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 23 of file MyChromosome\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.distinctGenes\&.MyChromosome\&.MyChromosome () throws InvalidConfigurationException\fC [inline]\fP"

.PP
Definition at line 28 of file MyChromosome\&.java\&.
.PP
Referenced by examples\&.distinctGenes\&.MyChromosome\&.randomInitialMyChromosome()\&.
.SS "examples\&.distinctGenes\&.MyChromosome\&.MyChromosome (final Configurationa_configuration) throws InvalidConfigurationException\fC [inline]\fP"

.PP
Definition at line 33 of file MyChromosome\&.java\&.
.SS "examples\&.distinctGenes\&.MyChromosome\&.MyChromosome (final Configurationa_configuration, final inta_desiredSize) throws InvalidConfigurationException\fC [inline]\fP"

.PP
Definition at line 38 of file MyChromosome\&.java\&.
.SS "examples\&.distinctGenes\&.MyChromosome\&.MyChromosome (final Configurationa_configuration, final Genea_sampleGene, final inta_desiredSize) throws InvalidConfigurationException\fC [inline]\fP"

.PP
Definition at line 44 of file MyChromosome\&.java\&.
.SS "examples\&.distinctGenes\&.MyChromosome\&.MyChromosome (final Configurationa_configuration, final Gene[]a_initialGenes) throws InvalidConfigurationException\fC [inline]\fP"

.PP
Definition at line 50 of file MyChromosome\&.java\&.
.SS "examples\&.distinctGenes\&.MyChromosome\&.MyChromosome (final Configurationa_configuration, Genea_sampleGene, inta_desiredSize, IGeneConstraintCheckera_constraintChecker) throws InvalidConfigurationException\fC [inline]\fP"

.PP
Definition at line 56 of file MyChromosome\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean examples\&.distinctGenes\&.MyChromosome\&.isHandlerFor (Objecta_obj, Classa_class)\fC [inline]\fP"

.PP
Definition at line 63 of file MyChromosome\&.java\&.
.SS "Object examples\&.distinctGenes\&.MyChromosome\&.perform (Objecta_obj, Classa_class, Objecta_params) throws Exception\fC [inline]\fP"

.PP
Definition at line 73 of file MyChromosome\&.java\&.
.PP
References examples\&.distinctGenes\&.MyChromosome\&.randomInitialMyChromosome()\&.
.SS "static IChromosome examples\&.distinctGenes\&.MyChromosome\&.randomInitialMyChromosome (Configurationa_configuration) throws InvalidConfigurationException\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 78 of file MyChromosome\&.java\&.
.PP
References examples\&.distinctGenes\&.MyChromosome\&.MyChromosome()\&.
.PP
Referenced by examples\&.distinctGenes\&.MyChromosome\&.perform()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.distinctGenes\&.MyChromosome\&.CVS_REVISION = '$Revision: 1\&.4 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file MyChromosome\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
