.TH "examples.supergene.SupergeneChangeFitnessFunction" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.supergene.SupergeneChangeFitnessFunction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBexamples\&.supergene\&.AbstractChangeFitnessFunction\fP\&.
.PP
Inherited by examples\&.supergene\&.WithoutSupergeneChangeFitFForTesting\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSupergeneChangeFitnessFunction\fP (int a_targetAmount)"
.br
.ti -1c
.RI "Gene \fBgetResponsibleGene\fP (IChromosome a_chromosome, int a_code)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Fitness function for a version where Supergene is used\&.
.PP
\fBAuthor:\fP
.RS 4
Neil Rotstan 
.PP
Klaus Meffert 
.PP
Audrius Meskauskas 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 24 of file SupergeneChangeFitnessFunction\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.supergene\&.SupergeneChangeFitnessFunction\&.SupergeneChangeFitnessFunction (inta_targetAmount)\fC [inline]\fP"

.PP
Definition at line 29 of file SupergeneChangeFitnessFunction\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Gene examples\&.supergene\&.SupergeneChangeFitnessFunction\&.getResponsibleGene (IChromosomea_chromosome, inta_code)\fC [inline]\fP, \fC [virtual]\fP"
Dimes and nickels are taken from the chromosome, and quarters and pennies are taken from the supergene (gene number 2)\&. 
.PP
Implements \fBexamples\&.supergene\&.AbstractChangeFitnessFunction\fP\&.
.PP
Definition at line 37 of file SupergeneChangeFitnessFunction\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.supergene\&.SupergeneChangeFitnessFunction\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 27 of file SupergeneChangeFitnessFunction\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
