.TH "examples.grid.mathProblemDistributed.MyClientFeedback" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.grid.mathProblemDistributed.MyClientFeedback \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits IClientFeedbackGP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyClientFeedback\fP ()"
.br
.ti -1c
.RI "void \fBerror\fP (String msg, Exception ex)"
.br
.ti -1c
.RI "void \fBsendingFragmentRequest\fP (JGAPRequestGP req)"
.br
.ti -1c
.RI "void \fBreceivedFragmentResult\fP (JGAPRequestGP req, JGAPResultGP res, int idx)"
.br
.ti -1c
.RI "void \fBbeginWork\fP ()"
.br
.ti -1c
.RI "void \fBendWork\fP ()"
.br
.ti -1c
.RI "void \fBinfo\fP (String a_msg)"
.br
.ti -1c
.RI "void \fBsetProgressMaximum\fP (int max)"
.br
.ti -1c
.RI "void \fBsetProgressMinimum\fP (int min)"
.br
.ti -1c
.RI "void \fBsetProgressValue\fP (int val)"
.br
.ti -1c
.RI "void \fBsetRenderingTime\fP (JGAPRequest req, long dt)"
.br
.ti -1c
.RI "void \fBcompleteFrame\fP (int idx)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.7 $'"
.br
.ti -1c
.RI "static Logger \fBlog\fP = Logger\&.getLogger(MyClientFeedback\&.class)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Listener for feedback sent to the GP client\&. This is a simple sample implementation\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 26 of file MyClientFeedback\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.grid\&.mathProblemDistributed\&.MyClientFeedback\&.MyClientFeedback ()\fC [inline]\fP"

.PP
Definition at line 33 of file MyClientFeedback\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void examples\&.grid\&.mathProblemDistributed\&.MyClientFeedback\&.beginWork ()\fC [inline]\fP"

.PP
Definition at line 66 of file MyClientFeedback\&.java\&.
.SS "void examples\&.grid\&.mathProblemDistributed\&.MyClientFeedback\&.completeFrame (intidx)\fC [inline]\fP"

.PP
Definition at line 90 of file MyClientFeedback\&.java\&.
.SS "void examples\&.grid\&.mathProblemDistributed\&.MyClientFeedback\&.endWork ()\fC [inline]\fP"

.PP
Definition at line 70 of file MyClientFeedback\&.java\&.
.SS "void examples\&.grid\&.mathProblemDistributed\&.MyClientFeedback\&.error (Stringmsg, Exceptionex)\fC [inline]\fP"

.PP
Definition at line 36 of file MyClientFeedback\&.java\&.
.SS "void examples\&.grid\&.mathProblemDistributed\&.MyClientFeedback\&.info (Stringa_msg)\fC [inline]\fP"

.PP
Definition at line 74 of file MyClientFeedback\&.java\&.
.SS "void examples\&.grid\&.mathProblemDistributed\&.MyClientFeedback\&.receivedFragmentResult (JGAPRequestGPreq, JGAPResultGPres, intidx)\fC [inline]\fP"

.PP
Definition at line 44 of file MyClientFeedback\&.java\&.
.SS "void examples\&.grid\&.mathProblemDistributed\&.MyClientFeedback\&.sendingFragmentRequest (JGAPRequestGPreq)\fC [inline]\fP"

.PP
Definition at line 40 of file MyClientFeedback\&.java\&.
.SS "void examples\&.grid\&.mathProblemDistributed\&.MyClientFeedback\&.setProgressMaximum (intmax)\fC [inline]\fP"

.PP
Definition at line 78 of file MyClientFeedback\&.java\&.
.SS "void examples\&.grid\&.mathProblemDistributed\&.MyClientFeedback\&.setProgressMinimum (intmin)\fC [inline]\fP"

.PP
Definition at line 81 of file MyClientFeedback\&.java\&.
.SS "void examples\&.grid\&.mathProblemDistributed\&.MyClientFeedback\&.setProgressValue (intval)\fC [inline]\fP"

.PP
Definition at line 84 of file MyClientFeedback\&.java\&.
.SS "void examples\&.grid\&.mathProblemDistributed\&.MyClientFeedback\&.setRenderingTime (JGAPRequestreq, longdt)\fC [inline]\fP"

.PP
Definition at line 87 of file MyClientFeedback\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.grid\&.mathProblemDistributed\&.MyClientFeedback\&.CVS_REVISION = '$Revision: 1\&.7 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 29 of file MyClientFeedback\&.java\&.
.SS "Logger examples\&.grid\&.mathProblemDistributed\&.MyClientFeedback\&.log = Logger\&.getLogger(MyClientFeedback\&.class)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 31 of file MyClientFeedback\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
