.TH "examples.gp.anttrail.Right" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.gp.anttrail.Right \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBexamples\&.gp\&.anttrail\&.AntCommand\fP, and IMutateable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRight\fP (final \fBGPConfiguration\fP a_conf)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBCommandGene\fP \fBapplyMutation\fP (int index, double a_percentage)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "void \fBexecute_void\fP (ProgramChromosome a_chrom, int a_n, Object[] a_args)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.4 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Turn the ant right\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.01 
.RE
.PP

.PP
Definition at line 22 of file Right\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.gp\&.anttrail\&.Right\&.Right (final \fBGPConfiguration\fPa_conf) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 27 of file Right\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCommandGene\fP examples\&.gp\&.anttrail\&.Right\&.applyMutation (intindex, doublea_percentage) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 32 of file Right\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.getGPConfiguration()\&.
.SS "void examples\&.gp\&.anttrail\&.Right\&.execute_void (ProgramChromosomea_chrom, inta_n, Object[]a_args)\fC [inline]\fP"

.PP
Definition at line 38 of file Right\&.java\&.
.PP
References examples\&.gp\&.anttrail\&.AntCommand\&.getMap(), examples\&.gp\&.anttrail\&.AntMap\&.O_DOWN, examples\&.gp\&.anttrail\&.AntMap\&.O_LEFT, examples\&.gp\&.anttrail\&.AntMap\&.O_RIGHT, and examples\&.gp\&.anttrail\&.AntMap\&.O_UP\&.
.SS "String examples\&.gp\&.anttrail\&.Right\&.toString ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
the string representation of the command\&. Especially usefull to output a resulting formula in human-readable form\&. 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.gp\&.CommandGene\fP\&.
.PP
Definition at line 59 of file Right\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.gp\&.anttrail\&.Right\&.CVS_REVISION = '$Revision: 1\&.4 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file Right\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
