.TH "examples.gp.paintedDesert.SandColor" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.gp.paintedDesert.SandColor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBexamples\&.gp\&.paintedDesert\&.AntCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSandColor\fP (final \fBGPConfiguration\fP a_conf)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "int \fBexecute_int\fP (ProgramChromosome a_chrom, int a_n, Object[] a_args)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.1 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Returns the color of the sand at the current position\&.
.PP
\fBAuthor:\fP
.RS 4
Scott Mueller 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 22 of file SandColor\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.gp\&.paintedDesert\&.SandColor\&.SandColor (final \fBGPConfiguration\fPa_conf) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"
Allows to specify how many fields to look ahead to the right\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_conf\fP the configuration to use 
.br
\fIa_lookAheadFields\fP look ahead n fields
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIInvalidConfigurationException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.01 
.RE
.PP

.PP
Definition at line 38 of file SandColor\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.IntegerClass\&.
.SH "Member Function Documentation"
.PP 
.SS "int examples\&.gp\&.paintedDesert\&.SandColor\&.execute_int (ProgramChromosomea_chrom, inta_n, Object[]a_args)\fC [inline]\fP"

.PP
Definition at line 43 of file SandColor\&.java\&.
.PP
References examples\&.gp\&.paintedDesert\&.AntCommand\&.getMap()\&.
.SS "String examples\&.gp\&.paintedDesert\&.SandColor\&.toString ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
the string representation of the command\&. Especially usefull to output a resulting formula in human-readable form\&. 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.gp\&.CommandGene\fP\&.
.PP
Definition at line 48 of file SandColor\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.gp\&.paintedDesert\&.SandColor\&.CVS_REVISION = '$Revision: 1\&.1 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file SandColor\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
