.TH "examples.math.cmd.ValueOperand" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.math.cmd.ValueOperand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBexamples\&.math\&.cmd\&.Operand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValueOperand\fP (double theValue)"
.br
.ti -1c
.RI "double \fBvalue\fP ()"
.br
.ti -1c
.RI "void \fBsetValue\fP (double theVal)"
.br
.ti -1c
.RI "void \fBaccept\fP (\fBMathVisitor\fP theVisitor)"
.br
.ti -1c
.RI "Object \fBclone\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBmValue\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.1 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A mathematical operand\&.
.PP
\fBAuthor:\fP
.RS 4
Michael Grove 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.2 
.RE
.PP

.PP
Definition at line 20 of file ValueOperand\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.math\&.cmd\&.ValueOperand\&.ValueOperand (doubletheValue)\fC [inline]\fP"

.PP
Definition at line 27 of file ValueOperand\&.java\&.
.PP
References examples\&.math\&.cmd\&.ValueOperand\&.mValue\&.
.PP
Referenced by examples\&.math\&.cmd\&.ValueOperand\&.clone()\&.
.SH "Member Function Documentation"
.PP 
.SS "void examples\&.math\&.cmd\&.ValueOperand\&.accept (\fBMathVisitor\fPtheVisitor)\fC [inline]\fP"

.PP
Implements \fBexamples\&.math\&.cmd\&.Operand\fP\&.
.PP
Definition at line 39 of file ValueOperand\&.java\&.
.SS "Object examples\&.math\&.cmd\&.ValueOperand\&.clone ()\fC [inline]\fP"

.PP
Definition at line 43 of file ValueOperand\&.java\&.
.PP
References examples\&.math\&.cmd\&.ValueOperand\&.mValue, and examples\&.math\&.cmd\&.ValueOperand\&.ValueOperand()\&.
.SS "void examples\&.math\&.cmd\&.ValueOperand\&.setValue (doubletheVal)\fC [inline]\fP"

.PP
Definition at line 35 of file ValueOperand\&.java\&.
.PP
References examples\&.math\&.cmd\&.ValueOperand\&.mValue\&.
.SS "double examples\&.math\&.cmd\&.ValueOperand\&.value ()\fC [inline]\fP"

.PP
Implements \fBexamples\&.math\&.cmd\&.Operand\fP\&.
.PP
Definition at line 31 of file ValueOperand\&.java\&.
.PP
References examples\&.math\&.cmd\&.ValueOperand\&.mValue\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.math\&.cmd\&.ValueOperand\&.CVS_REVISION = '$Revision: 1\&.1 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 23 of file ValueOperand\&.java\&.
.SS "double examples\&.math\&.cmd\&.ValueOperand\&.mValue\fC [private]\fP"

.PP
Definition at line 25 of file ValueOperand\&.java\&.
.PP
Referenced by examples\&.math\&.cmd\&.ValueOperand\&.clone(), examples\&.math\&.cmd\&.ValueOperand\&.setValue(), examples\&.math\&.cmd\&.ValueOperand\&.value(), and examples\&.math\&.cmd\&.ValueOperand\&.ValueOperand()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
