.TH "examples.gp.monalisa.gui.GeneticDrawingApp" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.gp.monalisa.gui.GeneticDrawingApp \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits SingleFrameApplication\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGeneticDrawingApp\fP \fBgetApplication\fP ()"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBstartup\fP ()"
.br
.ti -1c
.RI "void \fBconfigureWindow\fP (java\&.awt\&.Window root)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.3 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the main class of the Mona Lisa Painting Problem\&. It starts the application\&. Please notice that this is the Genetic Programming version\&. Another implementation of the problem is done with Genetic Algorithms\&. Please see package \fBexamples\&.monalisa\fP\&.
.PP
The Mona Lisa Painting Problem is to find a number of polygons that form a picture which corresponds as good as possible to a given input picture\&. Originally, the Mona Lisa from Leonardo da Vinci was chosen as input\&.
.PP
See http://rogeralsing.com/2008/12/07/genetic-programming-evolution-of-mona-lisa/ for the initiator's blog of the problem, Roger Alsing\&.
.PP
\fBAuthor:\fP
.RS 4
Yann N\&. Dauphin 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4 
.RE
.PP

.PP
Definition at line 29 of file GeneticDrawingApp\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingApp\&.configureWindow (java\&.awt\&.Windowroot)\fC [inline]\fP, \fC [protected]\fP"
This method is to initialize the specified window by injecting resources\&. Windows shown in our application come fully initialized from the GUI builder, so this additional configuration is not needed\&. 
.PP
Definition at line 48 of file GeneticDrawingApp\&.java\&.
.SS "static \fBGeneticDrawingApp\fP examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingApp\&.getApplication ()\fC [inline]\fP, \fC [static]\fP"
A convenient static getter for the application instance\&. 
.PP
\fBReturns:\fP
.RS 4
the instance of \fBGeneticDrawingApp\fP 
.RE
.PP

.PP
Definition at line 55 of file GeneticDrawingApp\&.java\&.
.SS "static void examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingApp\&.main (String[]args)\fC [inline]\fP, \fC [static]\fP"
Main method launching the application\&. 
.PP
Definition at line 62 of file GeneticDrawingApp\&.java\&.
.SS "void examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingApp\&.startup ()\fC [inline]\fP, \fC [protected]\fP"
At startup create and show the main frame of the application\&. 
.PP
Definition at line 38 of file GeneticDrawingApp\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.gp\&.monalisa\&.gui\&.GeneticDrawingApp\&.CVS_REVISION = '$Revision: 1\&.3 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 33 of file GeneticDrawingApp\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
