.TH "examples.simpleBoolean.SimpleExample" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.simpleBoolean.SimpleExample \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.9 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Simple class that demonstrates the basic usage of JGAP\&.
.PP
\fBAuthor:\fP
.RS 4
Neil Rotstan 
.PP
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 22 of file SimpleExample\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void examples\&.simpleBoolean\&.SimpleExample\&.main (String[]args)\fC [inline]\fP, \fC [static]\fP"
Starts the example\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP if optional first argument provided, it represents the number of bits to use, but no more than 32
.RE
.PP
\fBAuthor:\fP
.RS 4
Neil Rotstan 
.PP
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 35 of file SimpleExample\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.simpleBoolean\&.SimpleExample\&.CVS_REVISION = '$Revision: 1\&.9 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 24 of file SimpleExample\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
