.TH "examples.grid.evolutionDistributed.MyGenotypeInitializer" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.grid.evolutionDistributed.MyGenotypeInitializer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits IGenotypeInitializer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Genotype \fBsetupGenotype\fP (JGAPRequest a_req, Population a_initialPop)  throws Exception "
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.3 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Initializes the genotype on behalf of the workers in a grid\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 21 of file MyGenotypeInitializer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Genotype examples\&.grid\&.evolutionDistributed\&.MyGenotypeInitializer\&.setupGenotype (JGAPRequesta_req, Populationa_initialPop) throws Exception\fC [inline]\fP"

.PP
Definition at line 26 of file MyGenotypeInitializer\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.grid\&.evolutionDistributed\&.MyGenotypeInitializer\&.CVS_REVISION = '$Revision: 1\&.3 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 24 of file MyGenotypeInitializer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
