.TH "examples.grid.evolutionDistributed.GridConfiguration" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples.grid.evolutionDistributed.GridConfiguration \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits GridConfigurationBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGridConfiguration\fP ()"
.br
.ti -1c
.RI "void \fBinitialize\fP (GridNodeClientConfig a_gridconfig)  throws Exception "
.br
.ti -1c
.RI "void \fBvalidate\fP ()  throws Exception "
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.3 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main configuration for defining the problem and the way it is solved in the grid\&. Thus, the most important class in a JGAP Grid!
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 25 of file GridConfiguration\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "examples\&.grid\&.evolutionDistributed\&.GridConfiguration\&.GridConfiguration ()\fC [inline]\fP"

.PP
Definition at line 30 of file GridConfiguration\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void examples\&.grid\&.evolutionDistributed\&.GridConfiguration\&.initialize (GridNodeClientConfiga_gridconfig) throws Exception\fC [inline]\fP"

.PP
Definition at line 34 of file GridConfiguration\&.java\&.
.SS "void examples\&.grid\&.evolutionDistributed\&.GridConfiguration\&.validate () throws Exception\fC [inline]\fP"

.PP
Definition at line 71 of file GridConfiguration\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String examples\&.grid\&.evolutionDistributed\&.GridConfiguration\&.CVS_REVISION = '$Revision: 1\&.3 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 28 of file GridConfiguration\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
