.TH "org.jgap.util.NetworkKit" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.util.NetworkKit \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static String \fBgetLocalIPAddress\fP ()  throws UnknownHostException "
.br
.ti -1c
.RI "static String \fBgetLocalHostName\fP ()  throws UnknownHostException "
.br
.ti -1c
.RI "static String \fBgetMACAddress\fP ()"
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBNetworkKit\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.5 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Houses network related functionality\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 21 of file NetworkKit\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.util\&.NetworkKit\&.NetworkKit ()\fC [inline]\fP, \fC [private]\fP"
Private constructor because it's a utility class\&. 
.PP
Definition at line 28 of file NetworkKit\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static String org\&.jgap\&.util\&.NetworkKit\&.getLocalHostName () throws UnknownHostException\fC [inline]\fP, \fC [static]\fP"

.PP
\fBReturns:\fP
.RS 4
name of the computer calling this function locally 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIUnknownHostException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 50 of file NetworkKit\&.java\&.
.SS "static String org\&.jgap\&.util\&.NetworkKit\&.getLocalIPAddress () throws UnknownHostException\fC [inline]\fP, \fC [static]\fP"

.PP
\fBReturns:\fP
.RS 4
IP address string in textual presentation 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIUnknownHostException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 38 of file NetworkKit\&.java\&.
.SS "static String org\&.jgap\&.util\&.NetworkKit\&.getMACAddress ()\fC [inline]\fP, \fC [static]\fP"
Taken and adapted from UUID\&.
.PP
\fBReturns:\fP
.RS 4
MAC address of the current computer\&.
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.3 
.RE
.PP

.PP
Definition at line 62 of file NetworkKit\&.java\&.
.PP
References org\&.jgap\&.util\&.NumberKit\&.parseShort()\&.
.PP
Referenced by org\&.jgap\&.util\&.NetworkKit\&.main()\&.
.SS "static void org\&.jgap\&.util\&.NetworkKit\&.main (String[]args)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 120 of file NetworkKit\&.java\&.
.PP
References org\&.jgap\&.util\&.NetworkKit\&.getMACAddress()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.util\&.NetworkKit\&.CVS_REVISION = '$Revision: 1\&.5 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 23 of file NetworkKit\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
