.TH "org.jgap.impl.ChainOfSelectorsTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.ChainOfSelectorsTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestConstruct_0\fP ()"
.br
.ti -1c
.RI "void \fBtestClear_0\fP ()"
.br
.ti -1c
.RI "void \fBtestClear_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestClear_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestIterator_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestAddNaturalSelector_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestHashCode_0\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.13 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBChainOfSelectors\fP class\&.
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 22 of file ChainOfSelectorsTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.impl\&.ChainOfSelectorsTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 27 of file ChainOfSelectorsTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.ChainOfSelectorsTest\&.testAddNaturalSelector_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 114 of file ChainOfSelectorsTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.ChainOfSelectorsTest\&.testClear_0 ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 44 of file ChainOfSelectorsTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.ChainOfSelectors\&.isEmpty()\&.
.SS "void org\&.jgap\&.impl\&.ChainOfSelectorsTest\&.testClear_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 57 of file ChainOfSelectorsTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.impl\&.ChainOfSelectors\&.isEmpty(), and org\&.jgap\&.impl\&.ChainOfSelectors\&.size()\&.
.SS "void org\&.jgap\&.impl\&.ChainOfSelectorsTest\&.testClear_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 74 of file ChainOfSelectorsTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.impl\&.ChainOfSelectors\&.isEmpty(), and org\&.jgap\&.impl\&.ChainOfSelectors\&.size()\&.
.SS "void org\&.jgap\&.impl\&.ChainOfSelectorsTest\&.testConstruct_0 ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 36 of file ChainOfSelectorsTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.ChainOfSelectorsTest\&.testEquals_0 () throws Exception\fC [inline]\fP"

.PP
\fBTodo\fP
.RS 4
improve: 2 unsame selectors of same class with same params should make the chain equal! 
.RE
.PP

.PP
Definition at line 126 of file ChainOfSelectorsTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.ChainOfSelectors\&.equals()\&.
.SS "void org\&.jgap\&.impl\&.ChainOfSelectorsTest\&.testEquals_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 151 of file ChainOfSelectorsTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.ChainOfSelectors\&.equals()\&.
.SS "void org\&.jgap\&.impl\&.ChainOfSelectorsTest\&.testHashCode_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 163 of file ChainOfSelectorsTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.ChainOfSelectors\&.hashCode()\&.
.SS "void org\&.jgap\&.impl\&.ChainOfSelectorsTest\&.testIterator_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 93 of file ChainOfSelectorsTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.ChainOfSelectorsTest\&.CVS_REVISION = '$Revision: 1\&.13 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file ChainOfSelectorsTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
