.TH "org.jgap.distr.grid.gp.NullClientFeedbackGP" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.grid.gp.NullClientFeedbackGP \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.distr\&.grid\&.gp\&.IClientFeedbackGP\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetProgressMinimum\fP (int a_min)"
.br
.ti -1c
.RI "void \fBsetProgressMaximum\fP (int a_max)"
.br
.ti -1c
.RI "void \fBsetProgressValue\fP (int a_val)"
.br
.ti -1c
.RI "void \fBbeginWork\fP ()"
.br
.ti -1c
.RI "void \fBsendingFragmentRequest\fP (\fBJGAPRequestGP\fP a_req)"
.br
.ti -1c
.RI "void \fBreceivedFragmentResult\fP (\fBJGAPRequestGP\fP a_req, \fBJGAPResultGP\fP a_res, int a_idx)"
.br
.ti -1c
.RI "void \fBendWork\fP ()"
.br
.ti -1c
.RI "void \fBcompleteFrame\fP (int a_idx)"
.br
.ti -1c
.RI "void \fBerror\fP (String a_msg, Exception a_ex)"
.br
.ti -1c
.RI "void \fBinfo\fP (String a_msg)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.3 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Null implementation of client feedback for GP\&. Does exactly nothing\&. Will be used in case no client feedback is registered with the grid configuration\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 20 of file NullClientFeedbackGP\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.distr\&.grid\&.gp\&.NullClientFeedbackGP\&.beginWork ()\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.gp\&.IClientFeedbackGP\fP\&.
.PP
Definition at line 37 of file NullClientFeedbackGP\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.gp\&.NullClientFeedbackGP\&.completeFrame (inta_idx)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.gp\&.IClientFeedbackGP\fP\&.
.PP
Definition at line 54 of file NullClientFeedbackGP\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.gp\&.NullClientFeedbackGP\&.endWork ()\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.gp\&.IClientFeedbackGP\fP\&.
.PP
Definition at line 50 of file NullClientFeedbackGP\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.gp\&.NullClientFeedbackGP\&.error (Stringa_msg, Exceptiona_ex)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.gp\&.IClientFeedbackGP\fP\&.
.PP
Definition at line 58 of file NullClientFeedbackGP\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.gp\&.NullClientFeedbackGP\&.info (Stringa_msg)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.gp\&.IClientFeedbackGP\fP\&.
.PP
Definition at line 62 of file NullClientFeedbackGP\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.gp\&.NullClientFeedbackGP\&.receivedFragmentResult (\fBJGAPRequestGP\fPa_req, \fBJGAPResultGP\fPa_res, inta_idx)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.gp\&.IClientFeedbackGP\fP\&.
.PP
Definition at line 45 of file NullClientFeedbackGP\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.gp\&.NullClientFeedbackGP\&.sendingFragmentRequest (\fBJGAPRequestGP\fPa_req)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.gp\&.IClientFeedbackGP\fP\&.
.PP
Definition at line 41 of file NullClientFeedbackGP\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.gp\&.NullClientFeedbackGP\&.setProgressMaximum (inta_max)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.gp\&.IClientFeedbackGP\fP\&.
.PP
Definition at line 29 of file NullClientFeedbackGP\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.gp\&.NullClientFeedbackGP\&.setProgressMinimum (inta_min)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.gp\&.IClientFeedbackGP\fP\&.
.PP
Definition at line 25 of file NullClientFeedbackGP\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.gp\&.NullClientFeedbackGP\&.setProgressValue (inta_val)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.gp\&.IClientFeedbackGP\fP\&.
.PP
Definition at line 33 of file NullClientFeedbackGP\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.grid\&.gp\&.NullClientFeedbackGP\&.CVS_REVISION = '$Revision: 1\&.3 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 23 of file NullClientFeedbackGP\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
