.TH "org.jgap.gp.function.CountMatrix.CountMode" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.function.CountMatrix.CountMode \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBintValue\fP ()"
.br
.ti -1c
.RI "\fBCountMode\fP (int a_value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEMPTY\fP =(1)"
.br
.ti -1c
.RI "\fBNONEMPTY\fP =(2)"
.br
.ti -1c
.RI "\fBSPECIFIC\fP =(3)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 297 of file CountMatrix\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.gp\&.function\&.CountMatrix\&.CountMode\&.CountMode (inta_value)\fC [inline]\fP"

.PP
Definition at line 308 of file CountMatrix\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int org\&.jgap\&.gp\&.function\&.CountMatrix\&.CountMode\&.intValue ()\fC [inline]\fP"

.PP
Definition at line 304 of file CountMatrix\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "org\&.jgap\&.gp\&.function\&.CountMatrix\&.CountMode\&.EMPTY =(1)"

.PP
Definition at line 299 of file CountMatrix\&.java\&.
.SS "int org\&.jgap\&.gp\&.function\&.CountMatrix\&.CountMode\&.m_value\fC [private]\fP"

.PP
Definition at line 302 of file CountMatrix\&.java\&.
.SS "org\&.jgap\&.gp\&.function\&.CountMatrix\&.CountMode\&.NONEMPTY =(2)"

.PP
Definition at line 300 of file CountMatrix\&.java\&.
.SS "org\&.jgap\&.gp\&.function\&.CountMatrix\&.CountMode\&.SPECIFIC =(3)"

.PP
Definition at line 301 of file CountMatrix\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
