.TH "org.jgap.gp.function.Sine.Compatible" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.function.Sine.Compatible \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Object \fBexecute_sine\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 63 of file Sine\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Object org\&.jgap\&.gp\&.function\&.Sine\&.Compatible\&.execute_sine ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
