.TH "org.jgap.ICompositeGene" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.ICompositeGene \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.Gene\fP\&.
.PP
Inherited by \fBorg\&.jgap\&.impl\&.CompositeGene\fP, and \fBorg\&.jgap\&.supergenes\&.Supergene\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddGene\fP (\fBGene\fP a_gene)"
.br
.ti -1c
.RI "\fBGene\fP \fBgeneAt\fP (int a_index)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.4 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for Genes being composed by other genes\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 18 of file ICompositeGene\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.ICompositeGene\&.addGene (\fBGene\fPa_gene)"
Adds a gene to the composed \fBGene\fP 
.PP
\fBParameters:\fP
.RS 4
\fIa_gene\fP the gene to add
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 (since earlier in CompositeGene) 
.RE
.PP

.PP
Implemented in \fBorg\&.jgap\&.supergenes\&.AbstractSupergene\fP\&.
.SS "\fBGene\fP org\&.jgap\&.ICompositeGene\&.geneAt (inta_index)"

.PP
\fBParameters:\fP
.RS 4
\fIa_index\fP index to return the gene at 
.RE
.PP
\fBReturns:\fP
.RS 4
the gene at the given index
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 (since 1\&.1 in CompositeGene) 
.RE
.PP

.PP
Implemented in \fBorg\&.jgap\&.impl\&.CompositeGene\fP, and \fBorg\&.jgap\&.supergenes\&.Supergene\fP\&.
.PP
Referenced by org\&.jgap\&.impl\&.TwoWayMutationOperator\&.operate(), and org\&.jgap\&.impl\&.MutationOperator\&.operate()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.ICompositeGene\&.CVS_REVISION = '$Revision: 1\&.4 $'\fC [static]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 20 of file ICompositeGene\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
