.TH "org.jgap.gui.ConfigFrame.ListGroup" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gui.ConfigFrame.ListGroup \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "ConfigProperty \fBgetProp\fP ()"
.br
.ti -1c
.RI "void \fBsetProp\fP (final ConfigProperty a_prop)"
.br
.ti -1c
.RI "JList \fBgetList\fP ()"
.br
.ti -1c
.RI "DefaultListModel \fBgetListModel\fP ()"
.br
.ti -1c
.RI "JScrollPane \fBgetListScroller\fP ()"
.br
.ti -1c
.RI "JList \fBgetOutList\fP ()"
.br
.ti -1c
.RI "DefaultListModel \fBgetOutListModel\fP ()"
.br
.ti -1c
.RI "JScrollPane \fBgetOutListScroller\fP ()"
.br
.ti -1c
.RI "JButton \fBgetLButton\fP ()"
.br
.ti -1c
.RI "JButton \fBgetRButton\fP ()"
.br
.ti -1c
.RI "void \fBleftButtonPressed\fP ()"
.br
.ti -1c
.RI "void \fBrightButtonPressed\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "JList \fBm_list\fP"
.br
.ti -1c
.RI "DefaultListModel \fBm_listModel\fP"
.br
.ti -1c
.RI "JScrollPane \fBm_listScroller\fP"
.br
.ti -1c
.RI "JList \fBm_outList\fP"
.br
.ti -1c
.RI "DefaultListModel \fBm_outListModel\fP"
.br
.ti -1c
.RI "JScrollPane \fBm_outListScroller\fP"
.br
.ti -1c
.RI "\fBConfigListSelectionListener\fP \fBm_outListListener\fP"
.br
.ti -1c
.RI "JButton \fBm_lButton\fP"
.br
.ti -1c
.RI "JButton \fBm_rButton\fP"
.br
.ti -1c
.RI "ConfigProperty \fBm_prop\fP"
.br
.ti -1c
.RI "\fBListButtonListener\fP \fBm_listBL\fP"
.br
.ti -1c
.RI "\fBConfigFrame\fP \fBm_frame\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class groups the property data structure along with the JLists associated with it\&.
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 480 of file ConfigFrame\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "JButton org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getLButton ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
the button to move items from outlist to list
.RE
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 637 of file ConfigFrame\&.java\&.
.PP
References org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_lButton\&.
.SS "JList org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getList ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
the JList containing the items to select from
.RE
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 576 of file ConfigFrame\&.java\&.
.PP
References org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_list\&.
.SS "DefaultListModel org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getListModel ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
DefaultListModel for the list
.RE
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 586 of file ConfigFrame\&.java\&.
.PP
References org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_listModel\&.
.SS "JScrollPane org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getListScroller ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
scroller for the list
.RE
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 596 of file ConfigFrame\&.java\&.
.PP
References org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_listScroller\&.
.SS "JList org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getOutList ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
Output JList
.RE
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 606 of file ConfigFrame\&.java\&.
.PP
References org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_outList\&.
.SS "DefaultListModel org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getOutListModel ()\fC [inline]\fP"
Getter for the output list's associated model\&. 
.PP
\fBReturns:\fP
.RS 4
DefaultListModel for the output list
.RE
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 617 of file ConfigFrame\&.java\&.
.PP
References org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_outListModel\&.
.SS "JScrollPane org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getOutListScroller ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
scroller for the output list
.RE
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 627 of file ConfigFrame\&.java\&.
.PP
References org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_outListScroller\&.
.SS "ConfigProperty org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getProp ()\fC [inline]\fP"
Getter for the ConfigProperty object associated with this \fBListGroup\fP\&. 
.PP
\fBReturns:\fP
.RS 4
the ConfigProperty object associated with this \fBListGroup\fP
.RE
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 553 of file ConfigFrame\&.java\&.
.PP
References org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_prop\&.
.SS "JButton org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getRButton ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
the button to move items from list to outlist
.RE
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 647 of file ConfigFrame\&.java\&.
.PP
References org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_rButton\&.
.SS "void org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.leftButtonPressed ()\fC [inline]\fP"
Move selected items from the output list back to the list\&.
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 657 of file ConfigFrame\&.java\&.
.PP
References org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_outListModel\&.
.SS "void org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.rightButtonPressed ()\fC [inline]\fP"
Move selected items from list to the output list\&.
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 671 of file ConfigFrame\&.java\&.
.PP
References org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_listModel\&.
.SS "void org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.setProp (final ConfigPropertya_prop)\fC [inline]\fP"
Setter for the ConfigProperty object associated with this \fBListGroup\fP\&. This object is used to retrieve the values that the list is initialized with\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa_prop\fP the ConfigProperty object associated with this \fBListGroup\fP
.RE
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 566 of file ConfigFrame\&.java\&.
.PP
References org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_prop\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBConfigFrame\fP org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_frame\fC [private]\fP"

.PP
Definition at line 509 of file ConfigFrame\&.java\&.
.SS "JButton org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_lButton\fC [private]\fP"

.PP
Definition at line 500 of file ConfigFrame\&.java\&.
.PP
Referenced by org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getLButton()\&.
.SS "JList org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_list\fC [private]\fP"

.PP
Definition at line 482 of file ConfigFrame\&.java\&.
.PP
Referenced by org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getList()\&.
.SS "\fBListButtonListener\fP org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_listBL\fC [private]\fP"

.PP
Definition at line 507 of file ConfigFrame\&.java\&.
.SS "DefaultListModel org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_listModel\fC [private]\fP"

.PP
Definition at line 485 of file ConfigFrame\&.java\&.
.PP
Referenced by org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getListModel(), and org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.rightButtonPressed()\&.
.SS "JScrollPane org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_listScroller\fC [private]\fP"

.PP
Definition at line 487 of file ConfigFrame\&.java\&.
.PP
Referenced by org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getListScroller()\&.
.SS "JList org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_outList\fC [private]\fP"

.PP
Definition at line 490 of file ConfigFrame\&.java\&.
.PP
Referenced by org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getOutList()\&.
.SS "\fBConfigListSelectionListener\fP org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_outListListener\fC [private]\fP"

.PP
Definition at line 497 of file ConfigFrame\&.java\&.
.SS "DefaultListModel org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_outListModel\fC [private]\fP"

.PP
Definition at line 493 of file ConfigFrame\&.java\&.
.PP
Referenced by org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getOutListModel(), and org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.leftButtonPressed()\&.
.SS "JScrollPane org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_outListScroller\fC [private]\fP"

.PP
Definition at line 495 of file ConfigFrame\&.java\&.
.PP
Referenced by org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getOutListScroller()\&.
.SS "ConfigProperty org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_prop\fC [private]\fP"

.PP
Definition at line 505 of file ConfigFrame\&.java\&.
.PP
Referenced by org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getProp(), and org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.setProp()\&.
.SS "JButton org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.m_rButton\fC [private]\fP"

.PP
Definition at line 502 of file ConfigFrame\&.java\&.
.PP
Referenced by org\&.jgap\&.gui\&.ConfigFrame\&.ListGroup\&.getRButton()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
