.TH "org.jgap.gp.impl.JGAPTreeBranchRenderer" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.impl.JGAPTreeBranchRenderer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TreeBranchRenderer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Color \fBgetBranchColor\fP (Object a_node, int a_level)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Renders the branches' colors of a tree to display\&. Created by Brian Risk of Geneffects on March 18, 2004\&. Last Modified on March 19, 2004\&. www\&.geneffects\&.com Modified by Klaus Meffert
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 27 of file JGAPTreeBranchRenderer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Color org\&.jgap\&.gp\&.impl\&.JGAPTreeBranchRenderer\&.getBranchColor (Objecta_node, inta_level)\fC [inline]\fP"

.PP
Definition at line 32 of file JGAPTreeBranchRenderer\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.gp\&.impl\&.JGAPTreeBranchRenderer\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 30 of file JGAPTreeBranchRenderer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
