.TH "org.jgap.gp.impl.NodeValidatorForTesting" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.impl.NodeValidatorForTesting \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.gp\&.INodeValidator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBvalidate\fP (\fBProgramChromosome\fP a_chrom, \fBCommandGene\fP a_node, \fBCommandGene\fP a_rootNode, int a_tries, int a_num, int a_recurseLevel, Class a_type, \fBCommandGene\fP[] a_functionSet, int a_depth, boolean a_grow, int a_childIndex, boolean a_fullProgram)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
For testing purposes only\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 12 of file NodeValidatorForTesting\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean org\&.jgap\&.gp\&.impl\&.NodeValidatorForTesting\&.validate (\fBProgramChromosome\fPa_chrom, \fBCommandGene\fPa_node, \fBCommandGene\fPa_rootNode, inta_tries, inta_num, inta_recurseLevel, Classa_type, \fBCommandGene\fP[]a_functionSet, inta_depth, booleana_grow, inta_childIndex, booleana_fullProgram)\fC [inline]\fP"

.PP
Definition at line 14 of file NodeValidatorForTesting\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
