.TH "org.jgap.gp.function.ReplaceInMatrix.ReplacementMode" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.function.ReplaceInMatrix.ReplacementMode \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBintValue\fP ()"
.br
.ti -1c
.RI "\fBReplacementMode\fP (int a_value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCOLUMN\fP =(1)"
.br
.ti -1c
.RI "\fBROW\fP =(2)"
.br
.ti -1c
.RI "\fBDIAGONAL\fP =(3)"
.br
.ti -1c
.RI "\fBMATRIX\fP =(4)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 261 of file ReplaceInMatrix\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.gp\&.function\&.ReplaceInMatrix\&.ReplacementMode\&.ReplacementMode (inta_value)\fC [inline]\fP"

.PP
Definition at line 273 of file ReplaceInMatrix\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int org\&.jgap\&.gp\&.function\&.ReplaceInMatrix\&.ReplacementMode\&.intValue ()\fC [inline]\fP"

.PP
Definition at line 269 of file ReplaceInMatrix\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "org\&.jgap\&.gp\&.function\&.ReplaceInMatrix\&.ReplacementMode\&.COLUMN =(1)"

.PP
Definition at line 263 of file ReplaceInMatrix\&.java\&.
.SS "org\&.jgap\&.gp\&.function\&.ReplaceInMatrix\&.ReplacementMode\&.DIAGONAL =(3)"

.PP
Definition at line 265 of file ReplaceInMatrix\&.java\&.
.SS "int org\&.jgap\&.gp\&.function\&.ReplaceInMatrix\&.ReplacementMode\&.m_value\fC [private]\fP"

.PP
Definition at line 267 of file ReplaceInMatrix\&.java\&.
.SS "org\&.jgap\&.gp\&.function\&.ReplaceInMatrix\&.ReplacementMode\&.MATRIX =(4)"

.PP
Definition at line 266 of file ReplaceInMatrix\&.java\&.
.PP
Referenced by org\&.jgap\&.gp\&.function\&.ReplaceInMatrix\&.execute_int()\&.
.SS "org\&.jgap\&.gp\&.function\&.ReplaceInMatrix\&.ReplacementMode\&.ROW =(2)"

.PP
Definition at line 264 of file ReplaceInMatrix\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
