.TH "org.jgap.event.GeneticEventTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.event.GeneticEventTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestConstruct_0\fP ()"
.br
.ti -1c
.RI "void \fBtestConstruct_1\fP ()"
.br
.ti -1c
.RI "void \fBtestConstruct_2\fP ()"
.br
.ti -1c
.RI "void \fBtestConstruct_3\fP ()"
.br
.ti -1c
.RI "void \fBtestGetEventName_0\fP ()"
.br
.ti -1c
.RI "void \fBtestGENOTYPE_EVOLVED_EVENT_0\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.8 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBGeneticEvent\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 23 of file GeneticEventTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.event\&.GeneticEventTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 28 of file GeneticEventTest\&.java\&.
.SS "void org\&.jgap\&.event\&.GeneticEventTest\&.testConstruct_0 ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 37 of file GeneticEventTest\&.java\&.
.SS "void org\&.jgap\&.event\&.GeneticEventTest\&.testConstruct_1 ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 51 of file GeneticEventTest\&.java\&.
.SS "void org\&.jgap\&.event\&.GeneticEventTest\&.testConstruct_2 ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 60 of file GeneticEventTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals()\&.
.SS "void org\&.jgap\&.event\&.GeneticEventTest\&.testConstruct_3 ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 69 of file GeneticEventTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals()\&.
.SS "void org\&.jgap\&.event\&.GeneticEventTest\&.testGENOTYPE_EVOLVED_EVENT_0 ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 88 of file GeneticEventTest\&.java\&.
.PP
References org\&.jgap\&.event\&.GeneticEvent\&.GENOTYPE_EVOLVED_EVENT\&.
.SS "void org\&.jgap\&.event\&.GeneticEventTest\&.testGetEventName_0 ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 79 of file GeneticEventTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.event\&.GeneticEventTest\&.CVS_REVISION = '$Revision: 1\&.8 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file GeneticEventTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
