.TH "org.jgap.impl.TwoWayMutationOperatorTest.GeneticOperatorConstraintForTesting" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.TwoWayMutationOperatorTest.GeneticOperatorConstraintForTesting \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.IGeneticOperatorConstraint\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBisValid\fP (\fBPopulation\fP a_pop, List a_chromosomes, \fBGeneticOperator\fP a_caller)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 536 of file TwoWayMutationOperatorTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean org\&.jgap\&.impl\&.TwoWayMutationOperatorTest\&.GeneticOperatorConstraintForTesting\&.isValid (\fBPopulation\fPa_pop, Lista_chromosomes, \fBGeneticOperator\fPa_caller)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.IGeneticOperatorConstraint\fP\&.
.PP
Definition at line 538 of file TwoWayMutationOperatorTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
