.TH "org.jgap.event.GeneticEventListener" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.event.GeneticEventListener \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg\&.jgap\&.event\&.EventManagerTest\&.EventListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBgeneticEventFired\fP (\fBGeneticEvent\fP a_firedEvent)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.6 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents objects that process genetic events\&. Once subscribed to an event type with the \fBEventManager\fP, an object implementing this interface will be notified each time a genetic event of that type is fired (until it is unsubscribed)\&.
.PP
\fBAuthor:\fP
.RS 4
Neil Rotstan 
.PP
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 22 of file GeneticEventListener\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.event\&.GeneticEventListener\&.geneticEventFired (\fBGeneticEvent\fPa_firedEvent)"
Notify this \fBGeneticEventListener\fP that an event has been fired of a type to which this listener is subscribed\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_firedEvent\fP the event object that was fired\&. The type of the event can be determined by the \fBGeneticEvent\fP's name
.RE
.PP
\fBAuthor:\fP
.RS 4
Neil Rotstan 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Implemented in \fBorg\&.jgap\&.event\&.EventManagerTest\&.EventListener\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.event\&.GeneticEventListener\&.CVS_REVISION = '$Revision: 1\&.6 $'\fC [static]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file GeneticEventListener\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
