.TH "org.jgap.JGAPTestCase.TestFitnessFunction" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.JGAPTestCase.TestFitnessFunction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.FitnessFunction\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "double \fBevaluate\fP (\fBIChromosome\fP a_subject)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 89 of file JGAPTestCase\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "double org\&.jgap\&.JGAPTestCase\&.TestFitnessFunction\&.evaluate (\fBIChromosome\fPa_subject)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIa_subject\fP \fBChromosome\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
double 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.FitnessFunction\fP\&.
.PP
Definition at line 96 of file JGAPTestCase\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
