.TH "org.jgap.distr.grid.gp.JGAPGPXStream" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.grid.gp.JGAPGPXStream \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits XStream\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJGAPGPXStream\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (XStream a_xstream)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Specialized version of XStream for JGAP\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 28 of file JGAPGPXStream\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.distr\&.grid\&.gp\&.JGAPGPXStream\&.JGAPGPXStream ()\fC [inline]\fP"

.PP
Definition at line 32 of file JGAPGPXStream\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.gp\&.JGAPGPXStream\&.init()\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.distr\&.grid\&.gp\&.JGAPGPXStream\&.init (XStreama_xstream)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 37 of file JGAPGPXStream\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.gp\&.JGAPGPXStream\&.JGAPGPXStream()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.grid\&.gp\&.JGAPGPXStream\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 31 of file JGAPGPXStream\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
