.TH "org.jgap.impl.DefaultMutationRateCalculatorTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.DefaultMutationRateCalculatorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtestCalculateCurrentRate_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCalculateCurrentRate_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCalculateCurrentRate_2\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.13 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBDefaultMutationRateCalculator\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 22 of file DefaultMutationRateCalculatorTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.impl\&.DefaultMutationRateCalculatorTest\&.setUp ()\fC [inline]\fP"

.PP
Definition at line 33 of file DefaultMutationRateCalculatorTest\&.java\&.
.SS "static Test org\&.jgap\&.impl\&.DefaultMutationRateCalculatorTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 28 of file DefaultMutationRateCalculatorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.DefaultMutationRateCalculatorTest\&.testCalculateCurrentRate_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 44 of file DefaultMutationRateCalculatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Configuration\&.getChromosomeSize()\&.
.SS "void org\&.jgap\&.impl\&.DefaultMutationRateCalculatorTest\&.testCalculateCurrentRate_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 59 of file DefaultMutationRateCalculatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Configuration\&.getChromosomeSize()\&.
.SS "void org\&.jgap\&.impl\&.DefaultMutationRateCalculatorTest\&.testCalculateCurrentRate_2 () throws Exception\fC [inline]\fP"
If there are zero chromosomes in the config\&., the mutation rate nevertheless should be 1, because Random needs positive integers as input (see \fBMutationOperator\&.operate\fP for calling Random class) 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 76 of file DefaultMutationRateCalculatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.DefaultMutationRateCalculatorTest\&.CVS_REVISION = '$Revision: 1\&.13 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file DefaultMutationRateCalculatorTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
