.TH "org.jgap.impl.DoubleGeneTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.DoubleGeneTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGeneConstraintChecker\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtestConstruct_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestToString_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestToString_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestToString_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetAllele_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetAllele_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetAllele_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_7\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_8\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestDoubleValue_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestDoubleValue_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestNewGene_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCleanup_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareToNative_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareToNative_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareToNative_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareToNative_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareToNative_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_7\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetConstraintChecker_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestHashCode_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestHashCode_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetEnergy_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetEnergy_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestBounds_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestBounds_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestMapValueToWithinBoundsSupportsFullDoubleRange\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestMapValueToWithinBoundsSupportsFullDoubleRange2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestMapValueToWithinBoundsSupportsFullDoubleRange3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestMapValueToWithinBoundsSupportsFullDoubleRange4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestMapValueToWithinBoundsSupportsFullDoubleRange5\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.42 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBDoubleGene\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 22 of file DoubleGeneTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.setUp ()\fC [inline]\fP"

.PP
Definition at line 27 of file DoubleGeneTest\&.java\&.
.SS "static Test org\&.jgap\&.impl\&.DoubleGeneTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 31 of file DoubleGeneTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testApplyMutation_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 713 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.impl\&.DoubleGene\&.doubleValue()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testApplyMutation_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 726 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.DELTA\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testApplyMutation_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 740 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.DELTA\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testApplyMutation_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 754 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.DELTA\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testApplyMutation_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 768 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.DELTA\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testApplyMutation_5 () throws Exception\fC [inline]\fP"
Exceed bounds for applyMutation to force randomized setting of allele\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 783 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.DELTA\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testApplyMutation_6 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 797 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.impl\&.DoubleGene\&.doubleValue()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testApplyMutation_7 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 810 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testBounds_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 909 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, org\&.jgap\&.impl\&.DoubleGene\&.getLowerBound(), and org\&.jgap\&.impl\&.DoubleGene\&.getUpperBound()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testBounds_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 922 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, org\&.jgap\&.impl\&.DoubleGene\&.getLowerBound(), and org\&.jgap\&.impl\&.DoubleGene\&.getUpperBound()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testCleanup_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 549 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testCompareToNative_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 638 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testCompareToNative_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 653 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testCompareToNative_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 668 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testCompareToNative_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 683 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testCompareToNative_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 698 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testConstruct_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 41 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testConstruct_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 54 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testConstruct_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 65 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testConstruct_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.1 
.RE
.PP

.PP
Definition at line 77 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testDoubleValue_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 276 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.impl\&.DoubleGene\&.doubleValue()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testDoubleValue_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 288 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.impl\&.DoubleGene\&.doubleValue()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testEquals_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 161 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testEquals_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 174 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testEquals_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 185 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testEquals_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 196 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testEquals_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 207 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testEquals_5 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 220 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testEquals_6 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 233 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testEquals_7 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 246 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testEquals_8 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 260 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testGetAllele_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 125 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testGetAllele_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 137 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testGetAllele_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 149 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testHashCode_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 847 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.DoubleGene\&.hashCode()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testHashCode_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 859 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.DoubleGene\&.hashCode()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testMapValueToWithinBoundsSupportsFullDoubleRange () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.4 
.RE
.PP

.PP
Definition at line 943 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testMapValueToWithinBoundsSupportsFullDoubleRange2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.4 
.RE
.PP

.PP
Definition at line 960 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testMapValueToWithinBoundsSupportsFullDoubleRange3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.4 
.RE
.PP

.PP
Definition at line 978 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testMapValueToWithinBoundsSupportsFullDoubleRange4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.4 
.RE
.PP

.PP
Definition at line 995 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testMapValueToWithinBoundsSupportsFullDoubleRange5 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.4 
.RE
.PP

.PP
Definition at line 1012 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testNewGene_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 411 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.BaseGene\&.getConstraintChecker(), org\&.jgap\&.BaseGene\&.newGene(), and org\&.jgap\&.JGAPTestCase\&.privateAccessor\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testPersistentRepresentation_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 436 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testPersistentRepresentation_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 452 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testPersistentRepresentation_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 463 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testPersistentRepresentation_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 480 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testPersistentRepresentation_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 503 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testPersistentRepresentation_5 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 526 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testSetAllele_0 () throws Exception\fC [inline]\fP"
Set allele to null, no exception should occur\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 307 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testSetAllele_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 318 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testSetAllele_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 335 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testSetAllele_3 () throws Exception\fC [inline]\fP"
Call setAllele with need of mapping to bounds\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 355 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testSetAllele_4 () throws Exception\fC [inline]\fP"
Call setAllele with need of mapping to bounds\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 369 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.impl\&.DoubleGene\&.doubleValue()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testSetAllele_5 () throws Exception\fC [inline]\fP"
Call setAllele with need of mapping to bounds\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 384 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.impl\&.DoubleGene\&.doubleValue()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testSetAllele_6 () throws Exception\fC [inline]\fP"
Call setAllele with need of mapping to bounds\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 399 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.impl\&.DoubleGene\&.doubleValue()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testSetConstraintChecker_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 828 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getConstraintChecker()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testSetEnergy_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 878 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.BaseGene\&.getEnergy()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testSetEnergy_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 890 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.BaseGene\&.getEnergy()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testSetToRandomValue_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 563 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testSetToRandomValue_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 576 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testSetToRandomValue_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
test needed any longer? 
.RE
.PP

.PP
Definition at line 590 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testSetToRandomValue_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 606 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.DoubleGene\&.doubleValue()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testSetToRandomValue_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 622 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.DoubleGene\&.doubleValue()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testToString_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 89 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.toString()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testToString_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 101 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.toString()\&.
.SS "void org\&.jgap\&.impl\&.DoubleGeneTest\&.testToString_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 114 of file DoubleGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.toString()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.DoubleGeneTest\&.CVS_REVISION = '$Revision: 1\&.42 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file DoubleGeneTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
