.TH "org.jgap.audit.Evaluator.GenotypeDataAvg" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.audit.Evaluator.GenotypeDataAvg \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpermutation\fP"
.br
.ti -1c
.RI "int \fBgeneration\fP"
.br
.ti -1c
.RI "double \fBsizeAvg\fP"
.br
.ti -1c
.RI "double \fBbestFitnessValue\fP"
.br
.ti -1c
.RI "double \fBavgFitnessValue\fP"
.br
.ti -1c
.RI "int \fBbestFitnessValueGeneration\fP"
.br
.ti -1c
.RI "double \fBavgDiversityFitnessValue\fP"
.br
.ti -1c
.RI "double \fBavgBestDeltaFitnessValue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Averaged genotype data (computed over all runs of a permutation)
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 432 of file Evaluator\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "double org\&.jgap\&.audit\&.Evaluator\&.GenotypeDataAvg\&.avgBestDeltaFitnessValue"

.PP
Definition at line 447 of file Evaluator\&.java\&.
.SS "double org\&.jgap\&.audit\&.Evaluator\&.GenotypeDataAvg\&.avgDiversityFitnessValue"

.PP
Definition at line 445 of file Evaluator\&.java\&.
.SS "double org\&.jgap\&.audit\&.Evaluator\&.GenotypeDataAvg\&.avgFitnessValue"

.PP
Definition at line 441 of file Evaluator\&.java\&.
.SS "double org\&.jgap\&.audit\&.Evaluator\&.GenotypeDataAvg\&.bestFitnessValue"

.PP
Definition at line 439 of file Evaluator\&.java\&.
.SS "int org\&.jgap\&.audit\&.Evaluator\&.GenotypeDataAvg\&.bestFitnessValueGeneration"

.PP
Definition at line 443 of file Evaluator\&.java\&.
.SS "int org\&.jgap\&.audit\&.Evaluator\&.GenotypeDataAvg\&.generation"

.PP
Definition at line 435 of file Evaluator\&.java\&.
.SS "int org\&.jgap\&.audit\&.Evaluator\&.GenotypeDataAvg\&.permutation"

.PP
Definition at line 433 of file Evaluator\&.java\&.
.SS "double org\&.jgap\&.audit\&.Evaluator\&.GenotypeDataAvg\&.sizeAvg"

.PP
Definition at line 437 of file Evaluator\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
