.TH "org.jgap.distr.grid.wan.ResultInformation" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.grid.wan.ResultInformation \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResultInformation\fP ()"
.br
.ti -1c
.RI "String \fBgetID\fP ()"
.br
.ti -1c
.RI "void \fBsetID\fP (String a_id)"
.br
.ti -1c
.RI "void \fBsetResponseDate\fP (Date a_date)"
.br
.ti -1c
.RI "Date \fBgetResponseDate\fP ()"
.br
.ti -1c
.RI "void \fBsetDescription\fP (String a_descr)"
.br
.ti -1c
.RI "String \fBgetDescription\fP ()"
.br
.ti -1c
.RI "long \fBgetDurationComputation\fP ()"
.br
.ti -1c
.RI "void \fBsetDurationComputation\fP (long a_durationComputation)"
.br
.ti -1c
.RI "void \fBsetTitle\fP (String a_title)"
.br
.ti -1c
.RI "String \fBgetTitle\fP ()"
.br
.ti -1c
.RI "int \fBgetPopSize\fP ()"
.br
.ti -1c
.RI "void \fBsetPopSize\fP (int popSize)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMasterInfo\fP \fBworkerInfo\fP"
.br
.ti -1c
.RI "double \fBm_fittest\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "String \fBm_id\fP"
.br
.ti -1c
.RI "String \fBm_title\fP"
.br
.ti -1c
.RI "Date \fBm_responseDate\fP"
.br
.ti -1c
.RI "String \fBm_description\fP"
.br
.ti -1c
.RI "int \fBm_popSize\fP"
.br
.ti -1c
.RI "long \fBm_durationComputation\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.1 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Meta-Information about a result\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 22 of file ResultInformation\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.ResultInformation ()\fC [inline]\fP"

.PP
Definition at line 45 of file ResultInformation\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.getDescription ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
arbitrary description of the request
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 92 of file ResultInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_description\&.
.SS "long org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.getDurationComputation ()\fC [inline]\fP"

.PP
Definition at line 96 of file ResultInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_durationComputation\&.
.SS "String org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.getID ()\fC [inline]\fP"

.PP
Definition at line 48 of file ResultInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_id\&.
.SS "int org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.getPopSize ()\fC [inline]\fP"

.PP
Definition at line 124 of file ResultInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_popSize\&.
.SS "Date org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.getResponseDate ()\fC [inline]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIthe\fP result was computed
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 72 of file ResultInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_responseDate\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.wan\&.WANUtils\&.outputResultInformation()\&.
.SS "String org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.getTitle ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
the title set
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 120 of file ResultInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_title\&.
.SS "void org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.setDescription (Stringa_descr)\fC [inline]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIa_descr\fP arbitrary description of the request
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 82 of file ResultInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_description\&.
.SS "void org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.setDurationComputation (longa_durationComputation)\fC [inline]\fP"

.PP
Definition at line 100 of file ResultInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_durationComputation\&.
.SS "void org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.setID (Stringa_id)\fC [inline]\fP"

.PP
Definition at line 52 of file ResultInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_id\&.
.SS "void org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.setPopSize (intpopSize)\fC [inline]\fP"

.PP
Definition at line 128 of file ResultInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_popSize\&.
.SS "void org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.setResponseDate (Datea_date)\fC [inline]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIa_date\fP date the result was computed
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 62 of file ResultInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_responseDate\&.
.SS "void org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.setTitle (Stringa_title)\fC [inline]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIa_title\fP the title to set
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 110 of file ResultInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_title\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.CVS_REVISION = '$Revision: 1\&.1 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 24 of file ResultInformation\&.java\&.
.SS "String org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_description\fC [private]\fP"

.PP
Definition at line 34 of file ResultInformation\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.getDescription(), and org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.setDescription()\&.
.SS "long org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_durationComputation\fC [private]\fP"
Duration of computation 
.PP
Definition at line 43 of file ResultInformation\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.getDurationComputation(), and org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.setDurationComputation()\&.
.SS "double org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_fittest"

.PP
Definition at line 36 of file ResultInformation\&.java\&.
.SS "String org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_id\fC [private]\fP"

.PP
Definition at line 28 of file ResultInformation\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.getID(), and org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.setID()\&.
.SS "int org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_popSize\fC [private]\fP"

.PP
Definition at line 38 of file ResultInformation\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.getPopSize(), and org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.setPopSize()\&.
.SS "Date org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_responseDate\fC [private]\fP"

.PP
Definition at line 32 of file ResultInformation\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.getResponseDate(), and org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.setResponseDate()\&.
.SS "String org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.m_title\fC [private]\fP"

.PP
Definition at line 30 of file ResultInformation\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.getTitle(), and org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.setTitle()\&.
.SS "\fBMasterInfo\fP org\&.jgap\&.distr\&.grid\&.wan\&.ResultInformation\&.workerInfo"

.PP
Definition at line 26 of file ResultInformation\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
