.TH "org.jgap.GenotypeTest.ChromosomeForTest2" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.GenotypeTest.ChromosomeForTest2 \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.ChromosomeForTesting\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChromosomeForTest2\fP (\fBConfiguration\fP a_config, final \fBGene\fP[] a_initialGenes)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "boolean \fBisHandlerFor\fP (Class a_class)"
.br
.ti -1c
.RI "Object \fBperform\fP (Object a_obj, Class a_class, Object a_params)  throws Exception "
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1333 of file GenotypeTest\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.GenotypeTest\&.ChromosomeForTest2\&.ChromosomeForTest2 (\fBConfiguration\fPa_config, final \fBGene\fP[]a_initialGenes) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 1335 of file GenotypeTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean org\&.jgap\&.GenotypeTest\&.ChromosomeForTest2\&.isHandlerFor (Classa_class)\fC [inline]\fP"

.PP
Definition at line 1341 of file GenotypeTest\&.java\&.
.SS "Object org\&.jgap\&.GenotypeTest\&.ChromosomeForTest2\&.perform (Objecta_obj, Classa_class, Objecta_params) throws Exception\fC [inline]\fP"
Performs a task for the given object or class\&. For some handlers, additional parameters are necessary, which could be provided\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_obj\fP the object instance to perform the handler task for 
.br
\fIa_class\fP the class to perform the handler task for, in case no object instance is available (some handlers could need to get an object and would always throw an exception if only a class is provided) 
.br
\fIa_params\fP optional parameters needed for the handler to perform its task 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP in case of any error 
.RE
.PP
\fBReturns:\fP
.RS 4
Object
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.IHandler\fP\&.
.PP
Definition at line 1350 of file GenotypeTest\&.java\&.
.PP
References org\&.jgap\&.ChromosomeForTesting\&.randomInitialChromosome2()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
