.TH "org.jgap.util.JarClassLoader" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.util.JarClassLoader \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.util\&.MultiClassLoader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJarClassLoader\fP (final String a_jarName)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "byte[] \fBloadClassBytes\fP (final String a_className)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBJarResources\fP \fBm_jarResources\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.6 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A class loader for loading jar files, both local and remote\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert (adapted from http://java.sun.com/docs/books/tutorial/deployment/jar/apiindex.html) 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 19 of file JarClassLoader\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.util\&.JarClassLoader\&.JarClassLoader (final Stringa_jarName)\fC [inline]\fP"

.PP
Definition at line 26 of file JarClassLoader\&.java\&.
.PP
References org\&.jgap\&.util\&.JarClassLoader\&.m_jarResources\&.
.SH "Member Function Documentation"
.PP 
.SS "byte [] org\&.jgap\&.util\&.JarClassLoader\&.loadClassBytes (final Stringa_className)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 31 of file JarClassLoader\&.java\&.
.PP
References org\&.jgap\&.util\&.MultiClassLoader\&.formatClassName(), org\&.jgap\&.util\&.JarResources\&.getResource(), and org\&.jgap\&.util\&.JarClassLoader\&.m_jarResources\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.util\&.JarClassLoader\&.CVS_REVISION = '$Revision: 1\&.6 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 22 of file JarClassLoader\&.java\&.
.SS "\fBJarResources\fP org\&.jgap\&.util\&.JarClassLoader\&.m_jarResources\fC [private]\fP"

.PP
Definition at line 24 of file JarClassLoader\&.java\&.
.PP
Referenced by org\&.jgap\&.util\&.JarClassLoader\&.JarClassLoader(), and org\&.jgap\&.util\&.JarClassLoader\&.loadClassBytes()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
