.TH "org.jgap.impl.ThresholdSelectorTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.ThresholdSelectorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestConstruct_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestAdd_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEmpty_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEmpty_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEmpty_2\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.19 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBThresholdSelector\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 25 of file ThresholdSelectorTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.impl\&.ThresholdSelectorTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 30 of file ThresholdSelectorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.ThresholdSelectorTest\&.testAdd_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 90 of file ThresholdSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.ThresholdSelectorTest\&.testConstruct_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 35 of file ThresholdSelectorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.ThresholdSelectorTest\&.testConstruct_1 () throws Exception\fC [inline]\fP"

.PP
Definition at line 46 of file ThresholdSelectorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.ThresholdSelectorTest\&.testConstruct_2 () throws Exception\fC [inline]\fP"

.PP
Definition at line 57 of file ThresholdSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, org\&.jgap\&.JGAPTestCase\&.getNestedField(), and org\&.jgap\&.impl\&.ThresholdSelector\&.returnsUniqueChromosomes()\&.
.SS "void org\&.jgap\&.impl\&.ThresholdSelectorTest\&.testConstruct_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.1 
.RE
.PP

.PP
Definition at line 77 of file ThresholdSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.ThresholdSelectorTest\&.testEmpty_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 338 of file ThresholdSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.ThresholdSelectorTest\&.testEmpty_1 () throws Exception\fC [inline]\fP"
Test if method clear() does not affect original \fBPopulation\fP\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 360 of file ThresholdSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.ThresholdSelectorTest\&.testEmpty_2 () throws Exception\fC [inline]\fP"
Test if method clear() does not affect return value\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 382 of file ThresholdSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.ThresholdSelectorTest\&.testSelect_0 () throws Exception\fC [inline]\fP"
Test if below functionality available without error\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 114 of file ThresholdSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.ThresholdSelectorTest\&.testSelect_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 136 of file ThresholdSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.ThresholdSelectorTest\&.testSelect_2 () throws Exception\fC [inline]\fP"
Always select best chromosome if threshold is 1\&.0d\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 185 of file ThresholdSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.ThresholdSelectorTest\&.testSelect_3 () throws Exception\fC [inline]\fP"
Never select best chromosome for granted if threshold is 0\&.0d\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 227 of file ThresholdSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.ThresholdSelectorTest\&.testSelect_4 () throws Exception\fC [inline]\fP"
Ensure that selected \fBChromosome\fP's are not equal to added \fBChromosome\fP's\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 263 of file ThresholdSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.ThresholdSelectorTest\&.testSelect_5 () throws Exception\fC [inline]\fP"
Always select best chromosome if threshold is 1\&.0d\&. Target population not empty\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 298 of file ThresholdSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.ThresholdSelectorTest\&.CVS_REVISION = '$Revision: 1\&.19 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 28 of file ThresholdSelectorTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
