.TH "org.jgap.impl.job.MaxFunction" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.job.MaxFunction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.FitnessFunction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBevaluate\fP (\fBIChromosome\fP a_subject)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Fitness function for \fBSimpleJobConsumer\fP\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 21 of file MaxFunction\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "double org\&.jgap\&.impl\&.job\&.MaxFunction\&.evaluate (\fBIChromosome\fPa_subject)\fC [inline]\fP, \fC [virtual]\fP"
Determine the fitness of the given \fBChromosome\fP instance\&. The higher the return value, the more fit the instance\&. This method should always return the same fitness value for two equivalent \fBChromosome\fP instances\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_subject\fP the \fBChromosome\fP instance to evaluate
.RE
.PP
\fBReturns:\fP
.RS 4
positive double reflecting the fitness rating of the given \fBChromosome\fP\&. Note that if a non-positive double is returned, a RuntimeException should be generated
.RE
.PP
\fBAuthor:\fP
.RS 4
Neil Rotstan 
.PP
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 (until 1\&.1: return type int) 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.FitnessFunction\fP\&.
.PP
Definition at line 33 of file MaxFunction\&.java\&.
.PP
References org\&.jgap\&.impl\&.BooleanGene\&.booleanValue(), org\&.jgap\&.IChromosome\&.getGene(), and org\&.jgap\&.IChromosome\&.size()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.job\&.MaxFunction\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 24 of file MaxFunction\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
