.TH "org.jgap.gp.impl.ProgramChromosome.NodeInfo" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.impl.ProgramChromosome.NodeInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeInfo\fP (Class a_returnType, int a_subReturnType)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Class \fBreturnType\fP"
.br
.ti -1c
.RI "int \fBsubReturnType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 467 of file ProgramChromosome\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.gp\&.impl\&.ProgramChromosome\&.NodeInfo\&.NodeInfo (Classa_returnType, inta_subReturnType)\fC [inline]\fP"

.PP
Definition at line 470 of file ProgramChromosome\&.java\&.
.PP
References org\&.jgap\&.gp\&.impl\&.ProgramChromosome\&.NodeInfo\&.returnType, and org\&.jgap\&.gp\&.impl\&.ProgramChromosome\&.NodeInfo\&.subReturnType\&.
.SH "Member Data Documentation"
.PP 
.SS "Class org\&.jgap\&.gp\&.impl\&.ProgramChromosome\&.NodeInfo\&.returnType"

.PP
Definition at line 468 of file ProgramChromosome\&.java\&.
.PP
Referenced by org\&.jgap\&.gp\&.impl\&.ProgramChromosome\&.NodeInfo\&.NodeInfo()\&.
.SS "int org\&.jgap\&.gp\&.impl\&.ProgramChromosome\&.NodeInfo\&.subReturnType"

.PP
Definition at line 469 of file ProgramChromosome\&.java\&.
.PP
Referenced by org\&.jgap\&.gp\&.impl\&.ProgramChromosome\&.NodeInfo\&.NodeInfo()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
