.TH "org.jgap.distr.IPopulationMerger" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.IPopulationMerger \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPopulation\fP \fBmergePopulations\fP (\fBPopulation\fP a_population1, \fBPopulation\fP a_population2, int a_new_population_size)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.6 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for implementations allowing to merge two independent populations together into one combined population\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 21 of file IPopulationMerger\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPopulation\fP org\&.jgap\&.distr\&.IPopulationMerger\&.mergePopulations (\fBPopulation\fPa_population1, \fBPopulation\fPa_population2, inta_new_population_size)"
Merges two populations into one that has the given size\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_population1\fP first population 
.br
\fIa_population2\fP second population 
.br
\fIa_new_population_size\fP size of merged population 
.RE
.PP
\fBReturns:\fP
.RS 4
the resulting population
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.IPopulationMerger\&.CVS_REVISION = '$Revision: 1\&.6 $'\fC [static]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 23 of file IPopulationMerger\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
