.TH "org.jgap.IGeneticOperatorConstraint" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.IGeneticOperatorConstraint \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg\&.jgap\&.impl\&.CrossoverOperatorTest\&.GeneticOperatorConstraintForTesting\fP, \fBorg\&.jgap\&.impl\&.MutationOperatorTest\&.GeneticOperatorConstraintForTesting\fP, and \fBorg\&.jgap\&.impl\&.TwoWayMutationOperatorTest\&.GeneticOperatorConstraintForTesting\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBisValid\fP (\fBPopulation\fP a_pop, List a_chromosomes, \fBGeneticOperator\fP a_caller)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for a constraint checker that determines whether a genetic operation should be executed for a given list of chromosomes\&. it is possible considering the caller\&. With that one could state that the two chromosome with classes ChromosomeClass1 and ChromosomeClass2 should not be considered for CrossoverOperator but for MutationOperator\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 24 of file IGeneticOperatorConstraint\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean org\&.jgap\&.IGeneticOperatorConstraint\&.isValid (\fBPopulation\fPa_pop, Lista_chromosomes, \fBGeneticOperator\fPa_caller)"

.PP
Implemented in \fBorg\&.jgap\&.impl\&.MutationOperatorTest\&.GeneticOperatorConstraintForTesting\fP, \fBorg\&.jgap\&.impl\&.TwoWayMutationOperatorTest\&.GeneticOperatorConstraintForTesting\fP, and \fBorg\&.jgap\&.impl\&.CrossoverOperatorTest\&.GeneticOperatorConstraintForTesting\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.IGeneticOperatorConstraint\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file IGeneticOperatorConstraint\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
