.TH "org.jgap.impl.StringGeneTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.StringGeneTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGeneConstraintChecker\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestConstruct_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAlphabet_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestToString_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestToString_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestToString_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetAllele_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_7\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_8\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_9\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestNewGene_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_5_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_7\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_8\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_9\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_10\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_11\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_12\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_14\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentRepresentation_15\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_7\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetMinMaxLength_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_7\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_8\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetConstraintChecker_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestIsValidAlphabet_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetEnergy_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetEnergy_1\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.39 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBStringGene\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 24 of file StringGeneTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.impl\&.StringGeneTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 29 of file StringGeneTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testApplyMutation_0 () throws Exception\fC [inline]\fP"
Following should be possible without exception\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 840 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testApplyMutation_1 () throws Exception\fC [inline]\fP"
Following should be possible without exception\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 856 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testApplyMutation_2 () throws Exception\fC [inline]\fP"
Invalid index specified\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 871 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testApplyMutation_3 () throws Exception\fC [inline]\fP"
No allele set\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 891 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testApplyMutation_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 902 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.impl\&.StringGene\&.ALPHABET_CHARACTERS_LOWER, org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testApplyMutation_5 () throws Exception\fC [inline]\fP"
Mutation 0\&.0 should not change anything\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 921 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.impl\&.StringGene\&.ALPHABET_CHARACTERS_LOWER, org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testApplyMutation_6 () throws Exception\fC [inline]\fP"
applyMutation with empty alphabet\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 938 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testApplyMutation_7 () throws Exception\fC [inline]\fP"
null random generator should lead to NullPointerException\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 958 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testCompareTo_0 () throws Exception\fC [inline]\fP"
Comparation using application data\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 344 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testCompareTo_1 () throws Exception\fC [inline]\fP"
class cast exception\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 376 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testCompareTo_2 () throws Exception\fC [inline]\fP"
Comparation using application data and null allele\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 395 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testConstruct_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 39 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.impl\&.StringGene\&.getAlphabet(), org\&.jgap\&.impl\&.StringGene\&.getMaxLength(), and org\&.jgap\&.impl\&.StringGene\&.getMinLength()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testConstruct_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 54 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testConstruct_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 69 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testConstruct_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 84 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testConstruct_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 99 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testConstruct_5 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.1 
.RE
.PP

.PP
Definition at line 115 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testEquals_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 191 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testEquals_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 204 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testEquals_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 215 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testEquals_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 226 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testEquals_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 237 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testEquals_5 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 250 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testEquals_6 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 265 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testEquals_7 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 278 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testEquals_8 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 292 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testEquals_9 () throws Exception\fC [inline]\fP"
Using application data\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 316 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testGetAllele_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 179 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testIsValidAlphabet_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 1149 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testNewGene_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 539 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.newGene()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testPersistentRepresentation_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 561 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testPersistentRepresentation_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 577 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testPersistentRepresentation_10 () throws Exception\fC [inline]\fP"
Invalid number in second argument\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 747 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testPersistentRepresentation_11 () throws Exception\fC [inline]\fP"
Invalid number in third argument\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 766 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testPersistentRepresentation_12 () throws Exception\fC [inline]\fP"
Minlen to great 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 784 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testPersistentRepresentation_14 () throws Exception\fC [inline]\fP"
Maxlen to small 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 802 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testPersistentRepresentation_15 () throws Exception\fC [inline]\fP"
Illegal character\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 821 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testPersistentRepresentation_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 594 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testPersistentRepresentation_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 611 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testPersistentRepresentation_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 628 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testPersistentRepresentation_5 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 645 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.impl\&.CompositeGene\&.GENE_DELIMITER, and org\&.jgap\&.impl\&.StringGene\&.getAlphabet()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testPersistentRepresentation_5_2 () throws Exception\fC [inline]\fP"
Use special characters in alphabet
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 667 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.impl\&.StringGene\&.getAlphabet(), and org\&.jgap\&.Gene\&.PERSISTENT_FIELD_DELIMITER\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testPersistentRepresentation_6 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 689 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testPersistentRepresentation_7 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 703 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.StringGene\&.getPersistentRepresentation()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testPersistentRepresentation_8 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 716 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testPersistentRepresentation_9 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 734 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.StringGene\&.getPersistentRepresentation()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetAllele_0 () throws Exception\fC [inline]\fP"
Set Allele to null, no exception should occur\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 421 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetAllele_1 () throws Exception\fC [inline]\fP"
Allele too short\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 433 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetAllele_2 () throws Exception\fC [inline]\fP"
Allele consists of illegal characters\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 450 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetAllele_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 466 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetAllele_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 484 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetAllele_5 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 497 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.StringGene\&.stringValue()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetAllele_6 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 518 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.StringGene\&.stringValue()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetAlphabet_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 127 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.impl\&.StringGene\&.getAlphabet(), and org\&.jgap\&.JGAPTestCase\&.privateAccessor\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetConstraintChecker_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 1131 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getConstraintChecker()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetEnergy_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 1166 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.BaseGene\&.getEnergy()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetEnergy_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 1178 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.BaseGene\&.getEnergy()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetMinMaxLength_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 977 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.impl\&.StringGene\&.getMaxLength(), and org\&.jgap\&.impl\&.StringGene\&.getMinLength()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetToRandomValue_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 991 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.impl\&.StringGene\&.ALPHABET_CHARACTERS_UPPER, org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetToRandomValue_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 1008 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.impl\&.StringGene\&.ALPHABET_CHARACTERS_UPPER, org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetToRandomValue_2 () throws Exception\fC [inline]\fP"

.PP
Definition at line 1016 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetToRandomValue_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 1029 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetToRandomValue_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 1042 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetToRandomValue_5 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 1063 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.impl\&.StringGene\&.ALPHABET_CHARACTERS_LOWER, and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetToRandomValue_6 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 1081 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetToRandomValue_7 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 1097 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testSetToRandomValue_8 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 1114 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testToString_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 142 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.toString()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testToString_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 155 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.StringGene\&.toString()\&.
.SS "void org\&.jgap\&.impl\&.StringGeneTest\&.testToString_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 167 of file StringGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.StringGene\&.toString()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.StringGeneTest\&.CVS_REVISION = '$Revision: 1\&.39 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 27 of file StringGeneTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
