.TH "org.jgap.distr.grid.JGAPWorker" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.grid.JGAPWorker \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.distr\&.Worker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "WorkResult \fBdoWork\fP (WorkRequest work, String workDir)  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)  throws Exception "
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.8 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A worker receives work units from a \fBJGAPServer\fP and sends back computed solutions to the same \fBJGAPServer\fP\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 (since 3\&.01 this class contained something different that is now in class \fBorg\&.jgap\&.distr\&.grid\&.JGAPWorkers\fP) 
.RE
.PP

.PP
Definition at line 25 of file JGAPWorker\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "WorkResult org\&.jgap\&.distr\&.grid\&.JGAPWorker\&.doWork (WorkRequestwork, StringworkDir) throws Exception\fC [inline]\fP"
Executes the evolution and returns the result\&.
.PP
\fBParameters:\fP
.RS 4
\fIwork\fP WorkRequest 
.br
\fIworkDir\fP String 
.RE
.PP
\fBReturns:\fP
.RS 4
WorkResult 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.01 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
set gridworkerfeedback in class GridWorker 
.RE
.PP

.PP
Definition at line 41 of file JGAPWorker\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.JGAPRequest\&.getGenotypeInitializer(), and org\&.jgap\&.distr\&.grid\&.JGAPRequest\&.getWorkerEvolveStrategy()\&.
.SS "static void org\&.jgap\&.distr\&.grid\&.JGAPWorker\&.main (String[]args) throws Exception\fC [inline]\fP, \fC [static]\fP"
Convenience method to start the worker\&.
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP command-line arguments, such as server address 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.01 
.RE
.PP

.PP
Definition at line 82 of file JGAPWorker\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.grid\&.JGAPWorker\&.CVS_REVISION = '$Revision: 1\&.8 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 28 of file JGAPWorker\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
