.TH "org.jgap.gp.CrossMethod" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.CrossMethod \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Serializable\&.
.PP
Inherited by \fBorg\&.jgap\&.gp\&.impl\&.BranchTypingCross\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCrossMethod\fP (GPConfiguration a_configuration)"
.br
.ti -1c
.RI "GPConfiguration \fBgetConfiguration\fP ()"
.br
.ti -1c
.RI "abstract \fBIGPProgram\fP[] \fBoperate\fP (final \fBIGPProgram\fP a_i1, final \fBIGPProgram\fP a_i2)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "GPConfiguration \fBm_configuration\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.8 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract base class for GP-crossing over implementations\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 21 of file CrossMethod\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.gp\&.CrossMethod\&.CrossMethod (GPConfigurationa_configuration)\fC [inline]\fP"

.PP
Definition at line 28 of file CrossMethod\&.java\&.
.PP
References org\&.jgap\&.gp\&.CrossMethod\&.m_configuration\&.
.SH "Member Function Documentation"
.PP 
.SS "GPConfiguration org\&.jgap\&.gp\&.CrossMethod\&.getConfiguration ()\fC [inline]\fP"

.PP
Definition at line 32 of file CrossMethod\&.java\&.
.PP
References org\&.jgap\&.gp\&.CrossMethod\&.m_configuration\&.
.PP
Referenced by org\&.jgap\&.gp\&.impl\&.BranchTypingCross\&.clone(), org\&.jgap\&.gp\&.impl\&.BranchTypingCross\&.doCross(), and org\&.jgap\&.gp\&.impl\&.BranchTypingCross\&.operate()\&.
.SS "abstract \fBIGPProgram\fP [] org\&.jgap\&.gp\&.CrossMethod\&.operate (final \fBIGPProgram\fPa_i1, final \fBIGPProgram\fPa_i2)\fC [pure virtual]\fP"
Crosses two individuals\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_i1\fP the first individual to cross 
.br
\fIa_i2\fP the second individual to cross 
.RE
.PP
\fBReturns:\fP
.RS 4
an array of the two resulting individuals
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Implemented in \fBorg\&.jgap\&.gp\&.impl\&.BranchTypingCross\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.gp\&.CrossMethod\&.CVS_REVISION = '$Revision: 1\&.8 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 24 of file CrossMethod\&.java\&.
.SS "GPConfiguration org\&.jgap\&.gp\&.CrossMethod\&.m_configuration\fC [private]\fP"

.PP
Definition at line 26 of file CrossMethod\&.java\&.
.PP
Referenced by org\&.jgap\&.gp\&.CrossMethod\&.CrossMethod(), and org\&.jgap\&.gp\&.CrossMethod\&.getConfiguration()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
