.TH "org.jgap.data.DataElementsDocument" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.data.DataElementsDocument \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.data\&.IDataCreators\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetTree\fP (final \fBIDataElementList\fP a_tree)"
.br
.ti -1c
.RI "\fBIDataElementList\fP \fBgetTree\fP ()"
.br
.ti -1c
.RI "\fBDataElementsDocument\fP ()  throws Exception "
.br
.ti -1c
.RI "\fBIDataCreators\fP \fBnewDocument\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBappendChild\fP (final \fBIDataElement\fP a_newChild)  throws Exception "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBIDataElementList\fP \fBm_tree\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.6 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBIDataCreators\fP interface represents an entity comparable to org\&.w3c\&.dom\&.Document
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 19 of file DataElementsDocument\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.data\&.DataElementsDocument\&.DataElementsDocument () throws Exception\fC [inline]\fP"

.PP
Definition at line 41 of file DataElementsDocument\&.java\&.
.PP
References org\&.jgap\&.data\&.DataElementsDocument\&.m_tree\&.
.PP
Referenced by org\&.jgap\&.data\&.DataElementsDocument\&.newDocument()\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.data\&.DataElementsDocument\&.appendChild (final \fBIDataElement\fPa_newChild) throws Exception\fC [inline]\fP"
Appends a child element to the tree 
.PP
\fBParameters:\fP
.RS 4
\fIa_newChild\fP the child to be added to the tree 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 59 of file DataElementsDocument\&.java\&.
.SS "\fBIDataElementList\fP org\&.jgap\&.data\&.DataElementsDocument\&.getTree ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
the tree (of elements) held by this class
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.data\&.IDataCreators\fP\&.
.PP
Definition at line 37 of file DataElementsDocument\&.java\&.
.PP
References org\&.jgap\&.data\&.DataElementsDocument\&.m_tree\&.
.PP
Referenced by org\&.jgap\&.data\&.DataElementsDocumentTest\&.testAppendChild_0(), and org\&.jgap\&.data\&.DataElementsDocumentTest\&.testConstruct_0()\&.
.SS "\fBIDataCreators\fP org\&.jgap\&.data\&.DataElementsDocument\&.newDocument () throws Exception\fC [inline]\fP"
Constructs a new instance of the entity implementing \fBIDataCreators\fP 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
new instance of the entity itself
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.data\&.IDataCreators\fP\&.
.PP
Definition at line 46 of file DataElementsDocument\&.java\&.
.PP
References org\&.jgap\&.data\&.DataElementsDocument\&.DataElementsDocument()\&.
.PP
Referenced by org\&.jgap\&.data\&.DataElementsDocumentTest\&.testNewDocument_0()\&.
.SS "void org\&.jgap\&.data\&.DataElementsDocument\&.setTree (final \fBIDataElementList\fPa_tree)\fC [inline]\fP"

.PP
Definition at line 27 of file DataElementsDocument\&.java\&.
.PP
References org\&.jgap\&.data\&.DataElementsDocument\&.m_tree\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.data\&.DataElementsDocument\&.CVS_REVISION = '$Revision: 1\&.6 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 22 of file DataElementsDocument\&.java\&.
.SS "\fBIDataElementList\fP org\&.jgap\&.data\&.DataElementsDocument\&.m_tree\fC [private]\fP"

.PP
Definition at line 24 of file DataElementsDocument\&.java\&.
.PP
Referenced by org\&.jgap\&.data\&.DataElementsDocument\&.DataElementsDocument(), org\&.jgap\&.data\&.DataElementsDocument\&.getTree(), and org\&.jgap\&.data\&.DataElementsDocument\&.setTree()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
