.TH "org.jgap.impl.WeightedRouletteSelectorTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.WeightedRouletteSelectorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtestConstruct_0\fP ()  throws Exception"
.br
.ti -1c
.RI "void \fBtestAdd_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEmpty_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEmpty_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEmpty_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestReturnsUniqueChromosomes_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestIsSerializable_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestDoSerialize_0\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.34 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBWeightedRouletteSelector\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 24 of file WeightedRouletteSelectorTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.impl\&.WeightedRouletteSelectorTest\&.setUp ()\fC [inline]\fP"

.PP
Definition at line 34 of file WeightedRouletteSelectorTest\&.java\&.
.SS "static Test org\&.jgap\&.impl\&.WeightedRouletteSelectorTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 29 of file WeightedRouletteSelectorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.WeightedRouletteSelectorTest\&.testAdd_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 57 of file WeightedRouletteSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.privateAccessor\&.
.SS "void org\&.jgap\&.impl\&.WeightedRouletteSelectorTest\&.testConstruct_0 () throws Exception\fC [inline]\fP"
Test if construction possible without failure\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 44 of file WeightedRouletteSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.WeightedRouletteSelectorTest\&.testDoSerialize_0 () throws Exception\fC [inline]\fP"
Ensures that WRS implements Serializable correctly\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 403 of file WeightedRouletteSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.doSerialize()\&.
.SS "void org\&.jgap\&.impl\&.WeightedRouletteSelectorTest\&.testEmpty_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 304 of file WeightedRouletteSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.privateAccessor\&.
.SS "void org\&.jgap\&.impl\&.WeightedRouletteSelectorTest\&.testEmpty_1 () throws Exception\fC [inline]\fP"
Test if clear()-method does not affect original \fBPopulation\fP\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 326 of file WeightedRouletteSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.WeightedRouletteSelectorTest\&.testEmpty_2 () throws Exception\fC [inline]\fP"
Test if clear()-method does not affect return value\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 348 of file WeightedRouletteSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.WeightedRouletteSelectorTest\&.testIsSerializable_0 () throws Exception\fC [inline]\fP"
Ensures WRS is implementing Serializable\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 386 of file WeightedRouletteSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.isSerializable()\&.
.SS "void org\&.jgap\&.impl\&.WeightedRouletteSelectorTest\&.testReturnsUniqueChromosomes_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 371 of file WeightedRouletteSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.WeightedRouletteSelectorTest\&.testSelect_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 84 of file WeightedRouletteSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.WeightedRouletteSelectorTest\&.testSelect_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 105 of file WeightedRouletteSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.WeightedRouletteSelectorTest\&.testSelect_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 155 of file WeightedRouletteSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.WeightedRouletteSelectorTest\&.testSelect_3 () throws Exception\fC [inline]\fP"
Ensure the scaling of fitness value works without error (like division by zero)\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 208 of file WeightedRouletteSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.WeightedRouletteSelectorTest\&.testSelect_4 () throws Exception\fC [inline]\fP"
Use \fBDeltaFitnessEvaluator\fP\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 253 of file WeightedRouletteSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.WeightedRouletteSelectorTest\&.CVS_REVISION = '$Revision: 1\&.34 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 27 of file WeightedRouletteSelectorTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
