.TH "org.jgap.data.config.AllConfigTests" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.data.config.AllConfigTests \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestSuite\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.3 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Test suite for all tests of package \fBorg\&.jgap\&.data\&.config\fP
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 20 of file AllConfigTests\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.data\&.config\&.AllConfigTests\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 26 of file AllConfigTests\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.data\&.config\&.AllConfigTests\&.CVS_REVISION = '$Revision: 1\&.3 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 24 of file AllConfigTests\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
