.TH "org.jgap.gp.IPopulationCreator" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.IPopulationCreator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg\&.jgap\&.gp\&.impl\&.DefaultPopulationCreator\fP, and \fBorg\&.jgap\&.gp\&.impl\&.StaticPopulationCreator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP (GPPopulation a_pop, Class[] a_types, Class[][] a_argTypes, \fBCommandGene\fP[][] a_nodeSets, int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, boolean[] a_fullModeAllowed)  throws InvalidConfigurationException"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for initializing the complete population within GPGenotype\&.randomInitializeGenotype\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2\&.2 
.RE
.PP

.PP
Definition at line 23 of file IPopulationCreator\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.gp\&.IPopulationCreator\&.initialize (GPPopulationa_pop, Class[]a_types, Classa_argTypes[][], \fBCommandGene\fPa_nodeSets[][], int[]a_minDepths, int[]a_maxDepths, inta_maxNodes, boolean[]a_fullModeAllowed) throws \fBInvalidConfigurationException\fP"
Initializes the given population\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_pop\fP GPPopulation 
.br
\fIa_types\fP Class[] 
.br
\fIa_argTypes\fP Class[][] 
.br
\fIa_nodeSets\fP \fBCommandGene\fP[][] 
.br
\fIa_minDepths\fP int[] 
.br
\fIa_maxDepths\fP int[] 
.br
\fIa_maxNodes\fP int 
.br
\fIa_fullModeAllowed\fP boolean[] 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBInvalidConfigurationException\fP\fP in case of any error
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2\&.2 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.gp\&.IPopulationCreator\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file IPopulationCreator\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
