.TH "org.jgap.FitnessFunctionTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.FitnessFunctionTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFitnessFunctionImpl\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestGetFitnessValue_0\fP ()"
.br
.ti -1c
.RI "void \fBtestGetFitnessValue_1\fP ()"
.br
.ti -1c
.RI "void \fBtestGetFitnessValue_2\fP ()"
.br
.ti -1c
.RI "void \fBtestLastComputedValue_0\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.16 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBFitnessFunction\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 20 of file FitnessFunctionTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.FitnessFunctionTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 25 of file FitnessFunctionTest\&.java\&.
.SS "void org\&.jgap\&.FitnessFunctionTest\&.testGetFitnessValue_0 ()\fC [inline]\fP"

.PP
Definition at line 30 of file FitnessFunctionTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.FitnessFunction\&.getFitnessValue()\&.
.SS "void org\&.jgap\&.FitnessFunctionTest\&.testGetFitnessValue_1 ()\fC [inline]\fP"

.PP
Definition at line 35 of file FitnessFunctionTest\&.java\&.
.SS "void org\&.jgap\&.FitnessFunctionTest\&.testGetFitnessValue_2 ()\fC [inline]\fP"

.PP
Definition at line 46 of file FitnessFunctionTest\&.java\&.
.SS "void org\&.jgap\&.FitnessFunctionTest\&.testLastComputedValue_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 62 of file FitnessFunctionTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.DELTA, org\&.jgap\&.FitnessFunction\&.getLastComputedFitnessValue(), and org\&.jgap\&.FitnessFunction\&.NO_FITNESS_VALUE\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.FitnessFunctionTest\&.CVS_REVISION = '$Revision: 1\&.16 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 23 of file FitnessFunctionTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
