.TH "org.jgap.impl.job.JobResult" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.job.JobResult \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Serializable\&.
.PP
Inherited by \fBorg\&.jgap\&.impl\&.job\&.EvolveResult\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJobResult\fP ()"
.br
.ti -1c
.RI "\fBConfiguration\fP \fBgetConfiguration\fP ()"
.br
.ti -1c
.RI "void \fBsetConfiguration\fP (\fBConfiguration\fP a_config)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBConfiguration\fP \fBm_config\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file JobResult\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.impl\&.job\&.JobResult\&.JobResult ()\fC [inline]\fP"

.PP
Definition at line 17 of file JobResult\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBConfiguration\fP org\&.jgap\&.impl\&.job\&.JobResult\&.getConfiguration ()\fC [inline]\fP"

.PP
Definition at line 21 of file JobResult\&.java\&.
.PP
References org\&.jgap\&.impl\&.job\&.JobResult\&.m_config\&.
.SS "void org\&.jgap\&.impl\&.job\&.JobResult\&.setConfiguration (\fBConfiguration\fPa_config)\fC [inline]\fP"

.PP
Definition at line 25 of file JobResult\&.java\&.
.PP
References org\&.jgap\&.impl\&.job\&.JobResult\&.m_config\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBConfiguration\fP org\&.jgap\&.impl\&.job\&.JobResult\&.m_config\fC [private]\fP"

.PP
Definition at line 15 of file JobResult\&.java\&.
.PP
Referenced by org\&.jgap\&.impl\&.job\&.JobResult\&.getConfiguration(), and org\&.jgap\&.impl\&.job\&.JobResult\&.setConfiguration()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
