.TH "org.jgap.impl.SetGeneTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.SetGeneTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestConstruct_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestToString_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestToString_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetAllele_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_7\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_8\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_9\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_10\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValueFromPersistentRepresentation_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValueFromPersistentRepresentation_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValueFromPersistentRepresentation_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValueFromPersistentRepresentation_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValueFromPersistentRepresentation_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValueFromPersistentRepresentation_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValueFromPersistentRepresentation_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetPersistentRepresentation_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetPersistentRepresentation_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetPersistentRepresentation_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestHashCode_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetEnergy_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetEnergy_1\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.7 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBSetGene\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 22 of file SetGeneTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.impl\&.SetGeneTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 27 of file SetGeneTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testApplyMutation_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 246 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testApplyMutation_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 263 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testApplyMutation_10 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 390 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.BooleanGene\&.booleanValue(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testApplyMutation_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 280 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testApplyMutation_3 () throws Exception\fC [inline]\fP"

.PP
\fBTodo\fP
.RS 4
from here on: adapt tests to \fBSetGene\fP 
.RE
.PP
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 298 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.BooleanGene\&.booleanValue(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testApplyMutation_4 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 311 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.BooleanGene\&.booleanValue(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testApplyMutation_5 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 324 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.BooleanGene\&.booleanValue(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testApplyMutation_6 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 337 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.BooleanGene\&.booleanValue(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testApplyMutation_7 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 350 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.BooleanGene\&.booleanValue(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testApplyMutation_8 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 363 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.BooleanGene\&.booleanValue(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testApplyMutation_9 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 376 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.BooleanGene\&.booleanValue(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testCompareTo_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 196 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testCompareTo_1 () throws Exception\fC [inline]\fP"

.PP
Definition at line 202 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testCompareTo_2 () throws Exception\fC [inline]\fP"

.PP
Definition at line 210 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.SetGene\&.compareTo(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testCompareTo_3 () throws Exception\fC [inline]\fP"

.PP
Definition at line 228 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.SetGene\&.compareTo(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testConstruct_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 32 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getConfiguration()\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testConstruct_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 44 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.SetGene\&.getInternalValue()\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testEquals_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 96 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testEquals_1 () throws Exception\fC [inline]\fP"

.PP
Definition at line 103 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testEquals_2 () throws Exception\fC [inline]\fP"

.PP
Definition at line 109 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.equals()\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testEquals_3 () throws Exception\fC [inline]\fP"

.PP
Definition at line 121 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testEquals_4 () throws Exception\fC [inline]\fP"

.PP
Definition at line 127 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testEquals_5 () throws Exception\fC [inline]\fP"

.PP
Definition at line 135 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testGetAllele_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 87 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testGetPersistentRepresentation_0 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 507 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testGetPersistentRepresentation_1 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 520 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testGetPersistentRepresentation_2 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 533 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testHashCode_0 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 546 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.BooleanGene\&.hashCode()\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testSetAllele_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 149 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testSetAllele_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 167 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testSetAllele_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 187 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testSetEnergy_0 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 558 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.BaseGene\&.getEnergy()\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testSetEnergy_1 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 570 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.BaseGene\&.getEnergy()\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testSetValueFromPersistentRepresentation_0 () throws Exception\fC [inline]\fP"
Should be possible without exception\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 404 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testSetValueFromPersistentRepresentation_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 416 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testSetValueFromPersistentRepresentation_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 429 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testSetValueFromPersistentRepresentation_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 441 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testSetValueFromPersistentRepresentation_4 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 454 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testSetValueFromPersistentRepresentation_5 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 472 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testSetValueFromPersistentRepresentation_6 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 490 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testToString_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 56 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.toString()\&.
.SS "void org\&.jgap\&.impl\&.SetGeneTest\&.testToString_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 71 of file SetGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.toString()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.SetGeneTest\&.CVS_REVISION = '$Revision: 1\&.7 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file SetGeneTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
