.TH "org.jgap.impl.BulkFitnessOffsetRemoverTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.BulkFitnessOffsetRemoverTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDummyFitnessFunction\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestDummyFitnessFunction_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestDummyFitnessFunction_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstructor_0\fP ()"
.br
.ti -1c
.RI "void \fBtestConstructor_1\fP ()"
.br
.ti -1c
.RI "void \fBtestEvaluate_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEvaluate_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEvaluate_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEvaluate_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetAbsoluteFitness_0\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "final transient \fBFitnessFunction\fP \fBm_fitnessFunction\fP"
.br
.ti -1c
.RI "final transient \fBBulkFitnessFunction\fP \fBm_bulkFitnessFunction\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.12 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests for the \fBBulkFitnessOffsetRemover\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Achim Westermann 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 21 of file BulkFitnessOffsetRemoverTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 36 of file BulkFitnessOffsetRemoverTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testConstructor_0 ()\fC [inline]\fP"

.PP
Definition at line 99 of file BulkFitnessOffsetRemoverTest\&.java\&.
.PP
References org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.m_fitnessFunction\&.
.SS "void org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testConstructor_1 ()\fC [inline]\fP"

.PP
Definition at line 104 of file BulkFitnessOffsetRemoverTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testDummyFitnessFunction_0 () throws Exception\fC [inline]\fP"
Test the inner class \fBDummyFitnessFunction\fP that is needed for this test with IntegerGenes in a \fBChromosome\fP\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 47 of file BulkFitnessOffsetRemoverTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.m_fitnessFunction\&.
.SS "void org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testDummyFitnessFunction_1 () throws Exception\fC [inline]\fP"
Test the inner class \fBDummyFitnessFunction\fP that is needed for this test with a mix of IntegerGenes and DoubleGenes in a \fBChromosome\fP\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 76 of file BulkFitnessOffsetRemoverTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.m_fitnessFunction\&.
.SS "void org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testEvaluate_0 () throws Exception\fC [inline]\fP"
Tests the method \fBBulkFitnessOffsetRemover\&.evaluate\fP(java\&.util\&.List) with a list of two Chromosomes with each one \fBIntegerGene\fP with the allele 100\&.
.PP
\fBAuthor:\fP
.RS 4
Achim Westermann 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 123 of file BulkFitnessOffsetRemoverTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.m_bulkFitnessFunction, and org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.m_fitnessFunction\&.
.SS "void org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testEvaluate_1 () throws Exception\fC [inline]\fP"
Tests the method BulkFitnessOffsetRemover\&.evaluate(List) with a list of two Chromosomes with one \fBIntegerGene\fP with the allele 100\&. The \fBIntegerGene\fP is the same instance in both Chromosomes\&.
.PP
\fBAuthor:\fP
.RS 4
Achim Westermann 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 157 of file BulkFitnessOffsetRemoverTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.m_bulkFitnessFunction, and org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.m_fitnessFunction\&.
.SS "void org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testEvaluate_2 () throws Exception\fC [inline]\fP"
Tests the method BulkFitnessOffsetRemover\&.evaluate(List) with a list of two Chromosomes with each one \fBIntegerGene\fP with the allele 200\&. The Chromosomes ar the same instance in the List that is evaluated\&.
.PP
\fBAuthor:\fP
.RS 4
Achim Westermann 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 189 of file BulkFitnessOffsetRemoverTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.m_bulkFitnessFunction, and org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.m_fitnessFunction\&.
.SS "void org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testEvaluate_3 () throws Exception\fC [inline]\fP"
Tests the method BulkFitnessOffsetRemover\&.evaluate(List) with a list of two Chromosomes with each two NumberGenes\&. 
.PP
.nf

                 chromosomeA
                /           \\
            \fBIntegerGene\fP   \fBDoubleGene\fP   => Fitness 4100\&.15
               |             |
             100            4000\&.15
                 chromosomeB
                /           \\
            \fBIntegerGene\fP   \fBDoubleGene\fP   =>; Fitness 1234 + 14e-5
               |             |
             1234           14e-5
 
.fi
.PP
.PP
\fBAuthor:\fP
.RS 4
Achim Westermann 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 229 of file BulkFitnessOffsetRemoverTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.Chromosome\&.getFitnessValue(), org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.m_bulkFitnessFunction, and org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.m_fitnessFunction\&.
.SS "void org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testGetAbsoluteFitness_0 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 284 of file BulkFitnessOffsetRemoverTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.Chromosome\&.getFitnessValue()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.CVS_REVISION = '$Revision: 1\&.12 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 24 of file BulkFitnessOffsetRemoverTest\&.java\&.
.SS "final transient \fBBulkFitnessFunction\fP org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.m_bulkFitnessFunction\fC [private]\fP"
\fBInitial value:\fP
.PP
.nf
=
      new BulkFitnessOffsetRemover(m_fitnessFunction)
.fi
.PP
Definition at line 33 of file BulkFitnessOffsetRemoverTest\&.java\&.
.PP
Referenced by org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testEvaluate_0(), org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testEvaluate_1(), org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testEvaluate_2(), and org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testEvaluate_3()\&.
.SS "final transient \fBFitnessFunction\fP org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.m_fitnessFunction\fC [private]\fP"
\fBInitial value:\fP
.PP
.nf
=
      new DummyFitnessFunction()
.fi
.PP
Definition at line 28 of file BulkFitnessOffsetRemoverTest\&.java\&.
.PP
Referenced by org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testConstructor_0(), org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testDummyFitnessFunction_0(), org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testDummyFitnessFunction_1(), org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testEvaluate_0(), org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testEvaluate_1(), org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testEvaluate_2(), and org\&.jgap\&.impl\&.BulkFitnessOffsetRemoverTest\&.testEvaluate_3()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
