.TH "org.jgap.util.randomHotBits" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.util.randomHotBits \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.util\&.randomX\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrandomHotBits\fP ()"
.br
.ti -1c
.RI "byte \fBnextByte\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBfillBuffer\fP ()  throws java\&.io\&.IOException     "
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of a \fB\fBrandomX\fP\fP-compliant class which obtains genuine random data from \fCJohn Walker\fP's \fCHotBits\fP radioactive decay random sequence generator\&.
.PP
Designed and implemented in July 1996 by \fCJohn Walker\fP, \fCkelvin@fourmilab\&.ch\fP\&. 
.PP
Definition at line 17 of file randomHotBits\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.util\&.randomHotBits\&.randomHotBits ()\fC [inline]\fP"
Creates a new pseudorandom sequence generator\&. 
.PP
Definition at line 27 of file randomHotBits\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.util\&.randomHotBits\&.fillBuffer () throws java\&.io\&.IOException\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line 33 of file randomHotBits\&.java\&.
.PP
Referenced by org\&.jgap\&.util\&.randomHotBits\&.nextByte()\&.
.SS "byte org\&.jgap\&.util\&.randomHotBits\&.nextByte ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
.nf
    Get next byte from generator.

.fi
.PP
.PP
\fBReturns:\fP
.RS 4
the next byte from the generator\&. 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.util\&.randomX\fP\&.
.PP
Definition at line 53 of file randomHotBits\&.java\&.
.PP
References org\&.jgap\&.util\&.randomHotBits\&.fillBuffer()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
