.TH "org.jgap.util.FileKit" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.util.FileKit \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyFileNameFilter\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBcopyFile\fP (String source, String dest)  throws FileNotFoundException, IOException "
.br
.ti -1c
.RI "static void \fBcopyFile\fP (String source, String dest, int a_offset)  throws FileNotFoundException, IOException "
.br
.ti -1c
.RI "static String \fBgetFilename\fP (String name_and_path)"
.br
.ti -1c
.RI "static String \fBgetFilename\fP (String name_and_path, String \fBfileseparator\fP)"
.br
.ti -1c
.RI "static String \fBgetCurrentDir\fP ()  throws IOException "
.br
.ti -1c
.RI "static String \fBaddSubDir\fP (String dir, String subDir, boolean makeNice)"
.br
.ti -1c
.RI "static String \fBaddFilename\fP (String dir, String a_filename)"
.br
.ti -1c
.RI "static String \fBgetConformPath\fP (String path, boolean makeNice)"
.br
.ti -1c
.RI "static String \fBgetConformPath\fP (String path)"
.br
.ti -1c
.RI "static String \fBgetConformPath\fP (String path, String a_fileseparator)"
.br
.ti -1c
.RI "static String \fBgetNiceURL\fP (String url, String separator)"
.br
.ti -1c
.RI "static String \fBremoveDoubleSeparators\fP (String dir)"
.br
.ti -1c
.RI "static boolean \fBdirectoryExists\fP (String a_dir)"
.br
.ti -1c
.RI "static boolean \fBexistsFile\fP (String a_filename)"
.br
.ti -1c
.RI "static boolean \fBdeleteFile\fP (String a_filename)"
.br
.ti -1c
.RI "static boolean \fBdeleteFile\fP (File a_file)"
.br
.ti -1c
.RI "static boolean \fBdeleteDirectory\fP (File a_dir)"
.br
.ti -1c
.RI "static ClassLoader \fBloadJar\fP (String a_filename)  throws Exception "
.br
.ti -1c
.RI "static Manifest \fBgetManifestOfJar\fP (String a_filename)  throws Exception "
.br
.ti -1c
.RI "static String \fBgetJGAPVersion\fP (Manifest a_JGAPManifest)"
.br
.ti -1c
.RI "static String \fBgetModuleVersion\fP (Manifest a_JGAPManifest)"
.br
.ti -1c
.RI "static String \fBgetVersionOfModule\fP (String a_filename)  throws Exception "
.br
.ti -1c
.RI "static String \fBgetVersionOfJGAP\fP (String a_filename)  throws Exception "
.br
.ti -1c
.RI "static String \fBtoJarFileName\fP (String a_filename)"
.br
.ti -1c
.RI "static void \fBcreateDirectory\fP (String a_dirname)  throws IOException "
.br
.ti -1c
.RI "static Vector \fBreadFile\fP (String a_filename)  throws IOException "
.br
.ti -1c
.RI "static String \fBgetTempDir\fP ()"
.br
.ti -1c
.RI "static String[] \fBlistFilesInDir\fP (String a_dir, String a_mask)  throws Exception "
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static String \fBfileseparator\fP = System\&.getProperty('file\&.separator')"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.12 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains helper functions related to the file system\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 23 of file FileKit\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static String org\&.jgap\&.util\&.FileKit\&.addFilename (Stringdir, Stringa_filename)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 155 of file FileKit\&.java\&.
.PP
References org\&.jgap\&.util\&.FileKit\&.getConformPath()\&.
.SS "static String org\&.jgap\&.util\&.FileKit\&.addSubDir (Stringdir, StringsubDir, booleanmakeNice)\fC [inline]\fP, \fC [static]\fP"
Adds a subdir to a given dir and returns the resulting dir\&.
.PP
\fBParameters:\fP
.RS 4
\fIdir\fP the original dir 
.br
\fIsubDir\fP the subdir to add 
.br
\fImakeNice\fP true: call getNiceDir afterwards 
.RE
.PP
\fBReturns:\fP
.RS 4
dir with subdir added
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 149 of file FileKit\&.java\&.
.PP
References org\&.jgap\&.util\&.FileKit\&.getConformPath()\&.
.SS "static void org\&.jgap\&.util\&.FileKit\&.copyFile (Stringsource, Stringdest) throws FileNotFoundException, IOException\fC [inline]\fP, \fC [static]\fP"
Copies a complete file\&.
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP source file name 
.br
\fIdest\fP destination file name or destination path (filename then taken from source) 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIFileNotFoundException\fP 
.br
\fIIOException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 41 of file FileKit\&.java\&.
.SS "static void org\&.jgap\&.util\&.FileKit\&.copyFile (Stringsource, Stringdest, inta_offset) throws FileNotFoundException, IOException\fC [inline]\fP, \fC [static]\fP"
Copies a file\&.
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP source file name 
.br
\fIdest\fP destination file name or destination path (filename then taken from source) 
.br
\fIa_offset\fP start offset of file to copy (0 is begin of file) 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIFileNotFoundException\fP 
.br
\fIIOException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 59 of file FileKit\&.java\&.
.PP
References org\&.jgap\&.util\&.FileKit\&.getFilename()\&.
.SS "static void org\&.jgap\&.util\&.FileKit\&.createDirectory (Stringa_dirname) throws IOException\fC [inline]\fP, \fC [static]\fP"
Creates a directory, and if necessary, any of its parent directories\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_dirname\fP name of the dir to create 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 442 of file FileKit\&.java\&.
.SS "static boolean org\&.jgap\&.util\&.FileKit\&.deleteDirectory (Filea_dir)\fC [inline]\fP, \fC [static]\fP"
Deletes a directory from disk, also if it is non-empty\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_dir\fP name of file to delete
.RE
.PP
\fBReturns:\fP
.RS 4
true if deletion successful
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.3 
.RE
.PP

.PP
Definition at line 294 of file FileKit\&.java\&.
.SS "static boolean org\&.jgap\&.util\&.FileKit\&.deleteFile (Stringa_filename)\fC [inline]\fP, \fC [static]\fP"
Deletes a file from disk\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_filename\fP name of file to delete
.RE
.PP
\fBReturns:\fP
.RS 4
true if deletion successful 
.RE
.PP

.PP
Definition at line 260 of file FileKit\&.java\&.
.PP
References org\&.jgap\&.util\&.FileKit\&.getConformPath()\&.
.SS "static boolean org\&.jgap\&.util\&.FileKit\&.deleteFile (Filea_file)\fC [inline]\fP, \fC [static]\fP"
Deletes a file from disk\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_file\fP name of file to delete
.RE
.PP
\fBReturns:\fP
.RS 4
true if deletion successful
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.3 
.RE
.PP

.PP
Definition at line 275 of file FileKit\&.java\&.
.SS "static boolean org\&.jgap\&.util\&.FileKit\&.directoryExists (Stringa_dir)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 243 of file FileKit\&.java\&.
.SS "static boolean org\&.jgap\&.util\&.FileKit\&.existsFile (Stringa_filename)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 248 of file FileKit\&.java\&.
.PP
References org\&.jgap\&.util\&.FileKit\&.getConformPath()\&.
.SS "static String org\&.jgap\&.util\&.FileKit\&.getConformPath (Stringpath, booleanmakeNice)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 160 of file FileKit\&.java\&.
.PP
References org\&.jgap\&.util\&.FileKit\&.fileseparator, and org\&.jgap\&.util\&.FileKit\&.getNiceURL()\&.
.PP
Referenced by org\&.jgap\&.util\&.FileKit\&.addFilename(), org\&.jgap\&.util\&.FileKit\&.addSubDir(), org\&.jgap\&.util\&.FileKit\&.deleteFile(), org\&.jgap\&.util\&.FileKit\&.existsFile(), and org\&.jgap\&.util\&.FileKit\&.getConformPath()\&.
.SS "static String org\&.jgap\&.util\&.FileKit\&.getConformPath (Stringpath)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 169 of file FileKit\&.java\&.
.PP
References org\&.jgap\&.util\&.FileKit\&.fileseparator, and org\&.jgap\&.util\&.FileKit\&.getConformPath()\&.
.SS "static String org\&.jgap\&.util\&.FileKit\&.getConformPath (Stringpath, Stringa_fileseparator)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 173 of file FileKit\&.java\&.
.PP
References org\&.jgap\&.util\&.FileKit\&.removeDoubleSeparators()\&.
.SS "static String org\&.jgap\&.util\&.FileKit\&.getCurrentDir () throws IOException\fC [inline]\fP, \fC [static]\fP"

.PP
\fBReturns:\fP
.RS 4
current directory of the application 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 132 of file FileKit\&.java\&.
.SS "static String org\&.jgap\&.util\&.FileKit\&.getFilename (Stringname_and_path)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 82 of file FileKit\&.java\&.
.PP
References org\&.jgap\&.util\&.FileKit\&.fileseparator\&.
.PP
Referenced by org\&.jgap\&.util\&.FileKit\&.copyFile()\&.
.SS "static String org\&.jgap\&.util\&.FileKit\&.getFilename (Stringname_and_path, Stringfileseparator)\fC [inline]\fP, \fC [static]\fP"
Extract file name from a given path+filename\&.
.PP
\fBParameters:\fP
.RS 4
\fIname_and_path\fP input 
.br
\fIfileseparator\fP Slash or Backslash 
.RE
.PP
\fBReturns:\fP
.RS 4
extracted file nmame
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
possibly use File\&.getName() instead? 
.RE
.PP

.PP
Definition at line 96 of file FileKit\&.java\&.
.PP
References org\&.jgap\&.util\&.FileKit\&.fileseparator\&.
.SS "static String org\&.jgap\&.util\&.FileKit\&.getJGAPVersion (Manifesta_JGAPManifest)\fC [inline]\fP, \fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIa_JGAPManifest\fP manifest with JGAP-specific information 
.RE
.PP
\fBReturns:\fP
.RS 4
version the jar file is working with (or version of the JGAP library in case the file \fIis\fP the JGAP library)
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 357 of file FileKit\&.java\&.
.PP
Referenced by org\&.jgap\&.util\&.FileKit\&.getVersionOfJGAP()\&.
.SS "static Manifest org\&.jgap\&.util\&.FileKit\&.getManifestOfJar (Stringa_filename) throws Exception\fC [inline]\fP, \fC [static]\fP"
Retrieve the manifest included in the given jar\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_filename\fP jar file name 
.RE
.PP
\fBReturns:\fP
.RS 4
Manifest included in the given jar
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 338 of file FileKit\&.java\&.
.PP
Referenced by org\&.jgap\&.util\&.FileKit\&.getVersionOfJGAP(), and org\&.jgap\&.util\&.FileKit\&.getVersionOfModule()\&.
.SS "static String org\&.jgap\&.util\&.FileKit\&.getModuleVersion (Manifesta_JGAPManifest)\fC [inline]\fP, \fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIa_JGAPManifest\fP Manifest with JGAP-specific information 
.RE
.PP
\fBReturns:\fP
.RS 4
version of the module represented by the jar
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 369 of file FileKit\&.java\&.
.PP
Referenced by org\&.jgap\&.util\&.FileKit\&.getVersionOfModule()\&.
.SS "static String org\&.jgap\&.util\&.FileKit\&.getNiceURL (Stringurl, Stringseparator)\fC [inline]\fP, \fC [static]\fP"
Makes an URL nice by bringing it into a normalized (i\&.e\&. convenient) form\&.
.PP
\fBParameters:\fP
.RS 4
\fIurl\fP any URL 
.br
\fIseparator\fP the separator to remove duplicates of 
.RE
.PP
\fBReturns:\fP
.RS 4
prettified URL
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 197 of file FileKit\&.java\&.
.PP
References org\&.jgap\&.util\&.FileKit\&.removeDoubleSeparators()\&.
.PP
Referenced by org\&.jgap\&.util\&.FileKit\&.getConformPath()\&.
.SS "static String org\&.jgap\&.util\&.FileKit\&.getTempDir ()\fC [inline]\fP, \fC [static]\fP"

.PP
\fBReturns:\fP
.RS 4
temporary directory
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.3 
.RE
.PP

.PP
Definition at line 483 of file FileKit\&.java\&.
.SS "static String org\&.jgap\&.util\&.FileKit\&.getVersionOfJGAP (Stringa_filename) throws Exception\fC [inline]\fP, \fC [static]\fP"
See getJGAPVersion\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_filename\fP name of a JGAP jar 
.RE
.PP
\fBReturns:\fP
.RS 4
version the jar file is working wit (or version of the JGAP library in case the file \fIis\fP the JGAP library) 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 405 of file FileKit\&.java\&.
.PP
References org\&.jgap\&.util\&.FileKit\&.getJGAPVersion(), and org\&.jgap\&.util\&.FileKit\&.getManifestOfJar()\&.
.SS "static String org\&.jgap\&.util\&.FileKit\&.getVersionOfModule (Stringa_filename) throws Exception\fC [inline]\fP, \fC [static]\fP"
See getModuleVersion\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_filename\fP name of a JGAP jar 
.RE
.PP
\fBReturns:\fP
.RS 4
version of the module represented by the jar 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 384 of file FileKit\&.java\&.
.PP
References org\&.jgap\&.util\&.FileKit\&.getManifestOfJar(), and org\&.jgap\&.util\&.FileKit\&.getModuleVersion()\&.
.SS "static String [] org\&.jgap\&.util\&.FileKit\&.listFilesInDir (Stringa_dir, Stringa_mask) throws Exception\fC [inline]\fP, \fC [static]\fP"
Returns the files within a directory that match a given pattern\&. No directories are returned\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_dir\fP String 
.br
\fIa_mask\fP String 
.RE
.PP
\fBReturns:\fP
.RS 4
String[] 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 499 of file FileKit\&.java\&.
.SS "static ClassLoader org\&.jgap\&.util\&.FileKit\&.loadJar (Stringa_filename) throws Exception\fC [inline]\fP, \fC [static]\fP"
Loads a jar file and returns a class loader to access the jar's classes\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_filename\fP the full jar file name, e\&.g\&.: C:/jgap/lib/ext/ashcroft\&.jar 
.RE
.PP
\fBReturns:\fP
.RS 4
ClassLoader the class loader with which to access the loaded classes, e\&.g\&. by <classloader>\&.loadClass(<classname including package>), e\&.g\&.: cl\&.loadClass('com\&.thoughtworks\&.ashcroft\&.runtime\&.JohnAshcroft');
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 320 of file FileKit\&.java\&.
.SS "static Vector org\&.jgap\&.util\&.FileKit\&.readFile (Stringa_filename) throws IOException\fC [inline]\fP, \fC [static]\fP"
Reads a text file\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_filename\fP name of text file 
.RE
.PP
\fBReturns:\fP
.RS 4
list of read text lines 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 464 of file FileKit\&.java\&.
.SS "static String org\&.jgap\&.util\&.FileKit\&.removeDoubleSeparators (Stringdir)\fC [inline]\fP, \fC [static]\fP"
Removes duplicate separators from an URL\&.
.PP
\fBParameters:\fP
.RS 4
\fIdir\fP name of directory including file name 
.RE
.PP
\fBReturns:\fP
.RS 4
prettified URL
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 222 of file FileKit\&.java\&.
.PP
References org\&.jgap\&.util\&.FileKit\&.fileseparator\&.
.PP
Referenced by org\&.jgap\&.util\&.FileKit\&.getConformPath(), and org\&.jgap\&.util\&.FileKit\&.getNiceURL()\&.
.SS "static String org\&.jgap\&.util\&.FileKit\&.toJarFileName (Stringa_filename)\fC [inline]\fP, \fC [static]\fP"
Converts an ordinary file name into a jar filename that can be used with \fBJarClassLoader\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_filename\fP the name to convert 
.RE
.PP
\fBReturns:\fP
.RS 4
converted name
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 425 of file FileKit\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.util\&.FileKit\&.CVS_REVISION = '$Revision: 1\&.12 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file FileKit\&.java\&.
.SS "String org\&.jgap\&.util\&.FileKit\&.fileseparator = System\&.getProperty('file\&.separator')\fC [static]\fP"

.PP
Definition at line 27 of file FileKit\&.java\&.
.PP
Referenced by org\&.jgap\&.util\&.FileKit\&.getConformPath(), org\&.jgap\&.util\&.FileKit\&.getFilename(), org\&.jgap\&.util\&.FileKit\&.removeDoubleSeparators(), and org\&.jgap\&.util\&.FileKitTest\&.replaceSeparator()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
