.TH "org.jgap.impl.ChromosomePoolTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.ChromosomePoolTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtestConstruct_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestAquireChromosome_0\fP ()"
.br
.ti -1c
.RI "void \fBtestReleaseChromosome_0\fP ()"
.br
.ti -1c
.RI "void \fBtestReleaseChromosome_1\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.10 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBChromosomePool\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 21 of file ChromosomePoolTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.impl\&.ChromosomePoolTest\&.setUp ()\fC [inline]\fP"

.PP
Definition at line 31 of file ChromosomePoolTest\&.java\&.
.SS "static Test org\&.jgap\&.impl\&.ChromosomePoolTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 26 of file ChromosomePoolTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.ChromosomePoolTest\&.testAquireChromosome_0 ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 53 of file ChromosomePoolTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals()\&.
.SS "void org\&.jgap\&.impl\&.ChromosomePoolTest\&.testConstruct_0 () throws Exception\fC [inline]\fP"
Test if construction possible without failure\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 43 of file ChromosomePoolTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.privateAccessor\&.
.SS "void org\&.jgap\&.impl\&.ChromosomePoolTest\&.testReleaseChromosome_0 ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 61 of file ChromosomePoolTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.ChromosomePoolTest\&.testReleaseChromosome_1 () throws Exception\fC [inline]\fP"
Should be possible without exception\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 78 of file ChromosomePoolTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.ChromosomePoolTest\&.CVS_REVISION = '$Revision: 1\&.10 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 24 of file ChromosomePoolTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
