.TH "org.jgap.gp.terminal.Argument" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.terminal.Argument \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.gp\&.CommandGene\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArgument\fP (final GPConfiguration a_conf, int a_index, Class type)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "boolean \fBexecute_boolean\fP (ProgramChromosome c, int n, Object[] args)"
.br
.ti -1c
.RI "int \fBexecute_int\fP (ProgramChromosome c, int n, Object[] args)"
.br
.ti -1c
.RI "long \fBexecute_long\fP (ProgramChromosome c, int n, Object[] args)"
.br
.ti -1c
.RI "float \fBexecute_float\fP (ProgramChromosome c, int n, Object[] args)"
.br
.ti -1c
.RI "double \fBexecute_double\fP (ProgramChromosome c, int n, Object[] args)"
.br
.ti -1c
.RI "Object \fBexecute_object\fP (ProgramChromosome c, int n, Object[] args)"
.br
.ti -1c
.RI "Class \fBgetChildType\fP (\fBIGPProgram\fP a_ind, int a_chromNum)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_index\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.9 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An argument that will be used internally only by ADF's\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 22 of file Argument\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.gp\&.terminal\&.Argument\&.Argument (final GPConfigurationa_conf, inta_index, Classtype) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 29 of file Argument\&.java\&.
.PP
References org\&.jgap\&.gp\&.terminal\&.Argument\&.m_index\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean org\&.jgap\&.gp\&.terminal\&.Argument\&.execute_boolean (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 49 of file Argument\&.java\&.
.PP
References org\&.jgap\&.gp\&.terminal\&.Argument\&.m_index\&.
.SS "double org\&.jgap\&.gp\&.terminal\&.Argument\&.execute_double (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 65 of file Argument\&.java\&.
.PP
References org\&.jgap\&.gp\&.terminal\&.Argument\&.m_index\&.
.SS "float org\&.jgap\&.gp\&.terminal\&.Argument\&.execute_float (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 61 of file Argument\&.java\&.
.PP
References org\&.jgap\&.gp\&.terminal\&.Argument\&.m_index\&.
.SS "int org\&.jgap\&.gp\&.terminal\&.Argument\&.execute_int (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 53 of file Argument\&.java\&.
.PP
References org\&.jgap\&.gp\&.terminal\&.Argument\&.m_index\&.
.SS "long org\&.jgap\&.gp\&.terminal\&.Argument\&.execute_long (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 57 of file Argument\&.java\&.
.PP
References org\&.jgap\&.gp\&.terminal\&.Argument\&.m_index\&.
.SS "Object org\&.jgap\&.gp\&.terminal\&.Argument\&.execute_object (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 69 of file Argument\&.java\&.
.PP
References org\&.jgap\&.gp\&.terminal\&.Argument\&.m_index\&.
.SS "Class org\&.jgap\&.gp\&.terminal\&.Argument\&.getChildType (\fBIGPProgram\fPa_ind, inta_chromNum)\fC [inline]\fP"

.PP
Definition at line 73 of file Argument\&.java\&.
.SS "String org\&.jgap\&.gp\&.terminal\&.Argument\&.getName ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
textual name of this command
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 45 of file Argument\&.java\&.
.SS "String org\&.jgap\&.gp\&.terminal\&.Argument\&.toString ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
the string representation of the command\&. Especially usefull to output a resulting formula in human-readable form\&. 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.gp\&.CommandGene\fP\&.
.PP
Definition at line 35 of file Argument\&.java\&.
.PP
References org\&.jgap\&.gp\&.terminal\&.Argument\&.m_index\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.gp\&.terminal\&.Argument\&.CVS_REVISION = '$Revision: 1\&.9 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file Argument\&.java\&.
.SS "int org\&.jgap\&.gp\&.terminal\&.Argument\&.m_index\fC [private]\fP"

.PP
Definition at line 27 of file Argument\&.java\&.
.PP
Referenced by org\&.jgap\&.gp\&.terminal\&.Argument\&.Argument(), org\&.jgap\&.gp\&.terminal\&.Argument\&.execute_boolean(), org\&.jgap\&.gp\&.terminal\&.Argument\&.execute_double(), org\&.jgap\&.gp\&.terminal\&.Argument\&.execute_float(), org\&.jgap\&.gp\&.terminal\&.Argument\&.execute_int(), org\&.jgap\&.gp\&.terminal\&.Argument\&.execute_long(), org\&.jgap\&.gp\&.terminal\&.Argument\&.execute_object(), and org\&.jgap\&.gp\&.terminal\&.Argument\&.toString()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
