.TH "org.jgap.distr.grid.DefaultClientFeedback" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.grid.DefaultClientFeedback \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.distr\&.grid\&.IClientFeedback\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDefaultClientFeedback\fP ()"
.br
.ti -1c
.RI "void \fBerror\fP (String msg, Exception ex)"
.br
.ti -1c
.RI "void \fBsendingFragmentRequest\fP (\fBJGAPRequest\fP req)"
.br
.ti -1c
.RI "void \fBreceivedFragmentResult\fP (\fBJGAPRequest\fP req, \fBJGAPResult\fP res, int idx)"
.br
.ti -1c
.RI "void \fBbeginWork\fP ()"
.br
.ti -1c
.RI "void \fBendWork\fP ()"
.br
.ti -1c
.RI "void \fBinfo\fP (String a_msg)"
.br
.ti -1c
.RI "void \fBsetProgressMaximum\fP (int max)"
.br
.ti -1c
.RI "void \fBsetProgressMinimum\fP (int min)"
.br
.ti -1c
.RI "void \fBsetProgressValue\fP (int val)"
.br
.ti -1c
.RI "void \fBsetRenderingTime\fP (\fBJGAPRequest\fP req, long dt)"
.br
.ti -1c
.RI "void \fBcompleteFrame\fP (int idx)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.1 $'"
.br
.ti -1c
.RI "static final String \fBclassName\fP = DefaultClientFeedback\&.class\&.getName()"
.br
.ti -1c
.RI "static Logger \fBlog\fP = Logger\&.getLogger(\fBclassName\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Empty implementation\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 22 of file DefaultClientFeedback\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.distr\&.grid\&.DefaultClientFeedback\&.DefaultClientFeedback ()\fC [inline]\fP"

.PP
Definition at line 31 of file DefaultClientFeedback\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.distr\&.grid\&.DefaultClientFeedback\&.beginWork ()\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.IClientFeedback\fP\&.
.PP
Definition at line 44 of file DefaultClientFeedback\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.DefaultClientFeedback\&.completeFrame (intidx)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.IClientFeedback\fP\&.
.PP
Definition at line 65 of file DefaultClientFeedback\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.DefaultClientFeedback\&.endWork ()\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.IClientFeedback\fP\&.
.PP
Definition at line 47 of file DefaultClientFeedback\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.DefaultClientFeedback\&.error (Stringmsg, Exceptionex)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.IClientFeedback\fP\&.
.PP
Definition at line 34 of file DefaultClientFeedback\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.DefaultClientFeedback\&.info (Stringa_msg)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.IClientFeedback\fP\&.
.PP
Definition at line 50 of file DefaultClientFeedback\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.DefaultClientFeedback\&.receivedFragmentResult (\fBJGAPRequest\fPreq, \fBJGAPResult\fPres, intidx)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.IClientFeedback\fP\&.
.PP
Definition at line 40 of file DefaultClientFeedback\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.DefaultClientFeedback\&.sendingFragmentRequest (\fBJGAPRequest\fPreq)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.IClientFeedback\fP\&.
.PP
Definition at line 37 of file DefaultClientFeedback\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.DefaultClientFeedback\&.setProgressMaximum (intmax)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.IClientFeedback\fP\&.
.PP
Definition at line 53 of file DefaultClientFeedback\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.DefaultClientFeedback\&.setProgressMinimum (intmin)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.IClientFeedback\fP\&.
.PP
Definition at line 56 of file DefaultClientFeedback\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.DefaultClientFeedback\&.setProgressValue (intval)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.IClientFeedback\fP\&.
.PP
Definition at line 59 of file DefaultClientFeedback\&.java\&.
.SS "void org\&.jgap\&.distr\&.grid\&.DefaultClientFeedback\&.setRenderingTime (\fBJGAPRequest\fPreq, longdt)\fC [inline]\fP"

.PP
Definition at line 62 of file DefaultClientFeedback\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.grid\&.DefaultClientFeedback\&.className = DefaultClientFeedback\&.class\&.getName()\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 27 of file DefaultClientFeedback\&.java\&.
.SS "final String org\&.jgap\&.distr\&.grid\&.DefaultClientFeedback\&.CVS_REVISION = '$Revision: 1\&.1 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file DefaultClientFeedback\&.java\&.
.SS "Logger org\&.jgap\&.distr\&.grid\&.DefaultClientFeedback\&.log = Logger\&.getLogger(\fBclassName\fP)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 29 of file DefaultClientFeedback\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
