.TH "org.jgap.DefaultFitnessEvaluator" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.DefaultFitnessEvaluator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.FitnessEvaluator\fP, \fBorg\&.jgap\&.util\&.ICloneable\fP, and Comparable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBisFitter\fP (final double a_fitness_value1, final double a_fitness_value2)"
.br
.ti -1c
.RI "boolean \fBisFitter\fP (\fBIChromosome\fP a_chrom1, \fBIChromosome\fP a_chrom2)"
.br
.ti -1c
.RI "Object \fBclone\fP ()"
.br
.ti -1c
.RI "int \fBcompareTo\fP (Object a_other)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.13 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A default implementation of a fitness evaluator\&. This implementation is straight forward: a higher fitness value is seen as fitter\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 21 of file DefaultFitnessEvaluator\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Object org\&.jgap\&.DefaultFitnessEvaluator\&.clone ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
deep clone of this instance
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.util\&.ICloneable\fP\&.
.PP
Definition at line 51 of file DefaultFitnessEvaluator\&.java\&.
.SS "int org\&.jgap\&.DefaultFitnessEvaluator\&.compareTo (Objecta_other)\fC [inline]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIa_other\fP sic 
.RE
.PP
\fBReturns:\fP
.RS 4
as always
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 62 of file DefaultFitnessEvaluator\&.java\&.
.SS "boolean org\&.jgap\&.DefaultFitnessEvaluator\&.isFitter (final doublea_fitness_value1, final doublea_fitness_value2)\fC [inline]\fP"
Compares the first given fitness value with the second and returns true if the first one is greater than the second one\&. Otherwise returns false 
.PP
\fBParameters:\fP
.RS 4
\fIa_fitness_value1\fP first fitness value 
.br
\fIa_fitness_value2\fP second fitness value 
.RE
.PP
\fBReturns:\fP
.RS 4
true: first fitness value greater than second
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 (until 1\&.1: input types int) 
.RE
.PP

.PP
Definition at line 36 of file DefaultFitnessEvaluator\&.java\&.
.PP
Referenced by org\&.jgap\&.DefaultFitnessEvaluator\&.isFitter()\&.
.SS "boolean org\&.jgap\&.DefaultFitnessEvaluator\&.isFitter (\fBIChromosome\fPa_chrom1, \fBIChromosome\fPa_chrom2)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.FitnessEvaluator\fP\&.
.PP
Definition at line 41 of file DefaultFitnessEvaluator\&.java\&.
.PP
References org\&.jgap\&.IChromosome\&.getFitnessValue(), and org\&.jgap\&.DefaultFitnessEvaluator\&.isFitter()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.DefaultFitnessEvaluator\&.CVS_REVISION = '$Revision: 1\&.13 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 24 of file DefaultFitnessEvaluator\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
