.TH "org.jgap.impl.CauchyRandomGeneratorTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.CauchyRandomGeneratorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestGeneral\fP ()"
.br
.ti -1c
.RI "void \fBtestNextCauchy_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetCauchyStdDeviation_0\fP ()"
.br
.ti -1c
.RI "void \fBtestNextInt_0\fP ()"
.br
.ti -1c
.RI "void \fBtestSerialize_0\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.11 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBCauchyRandomGenerator\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 23 of file CauchyRandomGeneratorTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.impl\&.CauchyRandomGeneratorTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 28 of file CauchyRandomGeneratorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.CauchyRandomGeneratorTest\&.testGeneral ()\fC [inline]\fP"
Check if construction and calculation possible in general\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 38 of file CauchyRandomGeneratorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.CauchyRandomGeneratorTest\&.testGetCauchyStdDeviation_0 ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 64 of file CauchyRandomGeneratorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.impl\&.CauchyRandomGenerator\&.getCauchyStandardDeviation()\&.
.SS "void org\&.jgap\&.impl\&.CauchyRandomGeneratorTest\&.testNextCauchy_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 53 of file CauchyRandomGeneratorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.CauchyRandomGeneratorTest\&.testNextInt_0 ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 74 of file CauchyRandomGeneratorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals()\&.
.SS "void org\&.jgap\&.impl\&.CauchyRandomGeneratorTest\&.testSerialize_0 () throws Exception\fC [inline]\fP"
Tests serializability capabilities\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.01 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
fix test as Java 5 uses java\&.util\&.concurrent\&.AtomicLong instead of sun\&.misc\&.AtomicLong 
.RE
.PP

.PP
Definition at line 91 of file CauchyRandomGeneratorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.doSerialize(), and org\&.jgap\&.JGAPTestCase\&.privateAccessor\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.CauchyRandomGeneratorTest\&.CVS_REVISION = '$Revision: 1\&.11 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file CauchyRandomGeneratorTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
