.TH "org.jgap.NaturalSelector.AgeFitnessValueComparator" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.NaturalSelector.AgeFitnessValueComparator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Comparator, and Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBcompare\fP (Object first, Object second)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Comparator regarding first the age (older is better), then the fitness value\&. Better results will be on top of the resulting sorted list\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.3 
.RE
.PP

.PP
Definition at line 114 of file NaturalSelector\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int org\&.jgap\&.NaturalSelector\&.AgeFitnessValueComparator\&.compare (Objectfirst, Objectsecond)\fC [inline]\fP"

.PP
Definition at line 116 of file NaturalSelector\&.java\&.
.PP
References org\&.jgap\&.IChromosome\&.getAge(), and org\&.jgap\&.NaturalSelector\&.getConfiguration()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
