.TH "org.jgap.gp.impl.DefaultProgramCreator" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.impl.DefaultProgramCreator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.gp\&.IProgramCreator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIGPProgram\fP \fBcreate\fP (\fBGPConfiguration\fP a_conf, int a_programIndex, Class[] a_types, Class[][] a_argTypes, \fBCommandGene\fP[][] a_nodeSets, int[] a_minDepths, int[] a_maxDepths, int a_maxNodes, int a_depth, boolean a_grow, int a_tries, boolean[] a_fullModeAllowed)  throws InvalidConfigurationException "
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.4 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Used by \fBDefaultPopulationCreator\fP to create GP programs\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2\&.1 
.RE
.PP

.PP
Definition at line 21 of file DefaultProgramCreator\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIGPProgram\fP org\&.jgap\&.gp\&.impl\&.DefaultProgramCreator\&.create (\fBGPConfiguration\fPa_conf, inta_programIndex, Class[]a_types, Classa_argTypes[][], \fBCommandGene\fPa_nodeSets[][], int[]a_minDepths, int[]a_maxDepths, inta_maxNodes, inta_depth, booleana_grow, inta_tries, boolean[]a_fullModeAllowed) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 26 of file DefaultProgramCreator\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.gp\&.impl\&.DefaultProgramCreator\&.CVS_REVISION = '$Revision: 1\&.4 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 24 of file DefaultProgramCreator\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
