.TH "org.jgap.xml.XMLDocumentBuilder" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.xml.XMLDocumentBuilder \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits DocumentBuilderBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Object \fBbuildDocument\fP (final IDataCreators a_document)  throws Exception "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetAttribute\fP (final Object a_xmlElement, final String a_key, final String a_value)"
.br
.ti -1c
.RI "Object \fBdocumentAppendChild\fP (final Object a_xmlDocument, final Object a_element)"
.br
.ti -1c
.RI "Object \fBelementAppendChild\fP (final Object a_xmlElement, final Object a_element)"
.br
.ti -1c
.RI "Object \fBcreateElement\fP (final Object a_doc, final Object a_xmlElement, final String a_tagName)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.10 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class building an XML file\&. Can be used to persist objects like \fBGenotype\fP, \fBChromosome\fP or \fBGene\fP (or a list of them) to an XML file\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 23 of file XMLDocumentBuilder\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Object org\&.jgap\&.xml\&.XMLDocumentBuilder\&.buildDocument (final IDataCreatorsa_document) throws Exception\fC [inline]\fP"
Convenience method to build an XML document from a generic input structure (of type IDataCreators)
.PP
\fBParameters:\fP
.RS 4
\fIa_document\fP the input structure holding the data to be represented as XML document 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Object the XML document
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 60 of file XMLDocumentBuilder\&.java\&.
.PP
Referenced by org\&.jgap\&.xml\&.XMLDocumentBuilderTest\&.testBuildDocument_0(), and org\&.jgap\&.xml\&.XMLDocumentBuilderTest\&.testBuildDocument_1()\&.
.SS "Object org\&.jgap\&.xml\&.XMLDocumentBuilder\&.createElement (final Objecta_doc, final Objecta_xmlElement, final Stringa_tagName)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 43 of file XMLDocumentBuilder\&.java\&.
.SS "Object org\&.jgap\&.xml\&.XMLDocumentBuilder\&.documentAppendChild (final Objecta_xmlDocument, final Objecta_element)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 33 of file XMLDocumentBuilder\&.java\&.
.SS "Object org\&.jgap\&.xml\&.XMLDocumentBuilder\&.elementAppendChild (final Objecta_xmlElement, final Objecta_element)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 38 of file XMLDocumentBuilder\&.java\&.
.SS "void org\&.jgap\&.xml\&.XMLDocumentBuilder\&.setAttribute (final Objecta_xmlElement, final Stringa_key, final Stringa_value)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 28 of file XMLDocumentBuilder\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.xml\&.XMLDocumentBuilder\&.CVS_REVISION = '$Revision: 1\&.10 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file XMLDocumentBuilder\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
