.TH "org.jgap.impl.DefaultInitializerTest.MyInitializerForTesting" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.DefaultInitializerTest.MyInitializerForTesting \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.IInitializer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBisHandlerFor\fP (final Object a_obj, final Class a_class)"
.br
.ti -1c
.RI "Object \fBperform\fP (final Object a_obj, final Class a_class, final Object a_params)  throws Exception "
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 83 of file DefaultInitializerTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean org\&.jgap\&.impl\&.DefaultInitializerTest\&.MyInitializerForTesting\&.isHandlerFor (final Objecta_obj, final Classa_class)\fC [inline]\fP"

.PP
Definition at line 85 of file DefaultInitializerTest\&.java\&.
.SS "Object org\&.jgap\&.impl\&.DefaultInitializerTest\&.MyInitializerForTesting\&.perform (final Objecta_obj, final Classa_class, final Objecta_params) throws Exception\fC [inline]\fP"

.PP
Definition at line 89 of file DefaultInitializerTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
