.TH "org.jgap.distr.grid.gp.IGenotypeInitializerGP" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.grid.gp.IGenotypeInitializerGP \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGPGenotype\fP \fBsetupGenotype\fP (\fBJGAPRequestGP\fP a_req, GPPopulation a_initialPop)  throws Exception"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface specifying how to initialize a GPGenotype on behalf of the worker\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 22 of file IGenotypeInitializerGP\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBGPGenotype\fP org\&.jgap\&.distr\&.grid\&.gp\&.IGenotypeInitializerGP\&.setupGenotype (\fBJGAPRequestGP\fPa_req, GPPopulationa_initialPop) throws Exception"

.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.grid\&.gp\&.IGenotypeInitializerGP\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file IGenotypeInitializerGP\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
