.TH "org.jgap.ConfigurationForTesting" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.ConfigurationForTesting \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.Configuration\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyAppData\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigurationForTesting\fP ()  throws InvalidConfigurationException "
.br
.ti -1c
.RI "synchronized void \fBsetRandomGenerator\fP (\fBRandomGenerator\fP a_generatorToSet)  throws InvalidConfigurationException "
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final double \fBSTATIC_FITNESS_VALUE\fP = 2\&.3d"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Ready-to-go Implementation of \fBorg\&.jgap\&.Configuration\fP with all important parameters already set\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 22 of file ConfigurationForTesting\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.ConfigurationForTesting\&.ConfigurationForTesting () throws \fBInvalidConfigurationException\fP\fC [inline]\fP"
Default constructor\&.
.PP
\fBExceptions:\fP
.RS 4
\fI\fBInvalidConfigurationException\fP\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 37 of file ConfigurationForTesting\&.java\&.
.PP
References org\&.jgap\&.Configuration\&.addGeneticOperator(), org\&.jgap\&.Configuration\&.addNaturalSelector(), org\&.jgap\&.Configuration\&.reset(), org\&.jgap\&.Configuration\&.setEventManager(), org\&.jgap\&.Configuration\&.setFitnessEvaluator(), org\&.jgap\&.Configuration\&.setFitnessFunction(), org\&.jgap\&.Configuration\&.setPopulationSize(), org\&.jgap\&.ConfigurationForTesting\&.setRandomGenerator(), org\&.jgap\&.Configuration\&.setSampleChromosome(), and org\&.jgap\&.ConfigurationForTesting\&.STATIC_FITNESS_VALUE\&.
.SH "Member Function Documentation"
.PP 
.SS "synchronized void org\&.jgap\&.ConfigurationForTesting\&.setRandomGenerator (\fBRandomGenerator\fPa_generatorToSet) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"
Allows to set the random generator freely, also to null (normally forbidden)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa_generatorToSet\fP the random generator to set 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBInvalidConfigurationException\fP\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 70 of file ConfigurationForTesting\&.java\&.
.PP
Referenced by org\&.jgap\&.ConfigurationForTesting\&.ConfigurationForTesting()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.ConfigurationForTesting\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file ConfigurationForTesting\&.java\&.
.SS "final double org\&.jgap\&.ConfigurationForTesting\&.STATIC_FITNESS_VALUE = 2\&.3d\fC [static]\fP"

.PP
Definition at line 27 of file ConfigurationForTesting\&.java\&.
.PP
Referenced by org\&.jgap\&.ConfigurationForTesting\&.ConfigurationForTesting()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
