.TH "org.jgap.distr.RequestDispatcher" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.RequestDispatcher \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBdispatch\fP (\fBIWorker\fP a_worker, \fBWorkerCommand\fP a_command)  throws IOException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file RequestDispatcher\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract void org\&.jgap\&.distr\&.RequestDispatcher\&.dispatch (\fBIWorker\fPa_worker, \fBWorkerCommand\fPa_command) throws IOException\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
