.TH "org.jgap.xml.XMLDocumentBuilderTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.xml.XMLDocumentBuilderTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestBuildDocument_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestBuildDocument_1\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.6 $'"
.br
.ti -1c
.RI "static final String \fBFILENAME_WRITE\fP = 'GAtestWrite\&.xml'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBXMLDocumentBuilder\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 24 of file XMLDocumentBuilderTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.xml\&.XMLDocumentBuilderTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 31 of file XMLDocumentBuilderTest\&.java\&.
.SS "void org\&.jgap\&.xml\&.XMLDocumentBuilderTest\&.testBuildDocument_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 41 of file XMLDocumentBuilderTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.xml\&.XMLDocumentBuilder\&.buildDocument(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.xml\&.XMLDocumentBuilderTest\&.testBuildDocument_1 () throws Exception\fC [inline]\fP"
Artifically create a null node 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 67 of file XMLDocumentBuilderTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.xml\&.XMLDocumentBuilder\&.buildDocument(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.xml\&.XMLDocumentBuilderTest\&.CVS_REVISION = '$Revision: 1\&.6 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 27 of file XMLDocumentBuilderTest\&.java\&.
.SS "final String org\&.jgap\&.xml\&.XMLDocumentBuilderTest\&.FILENAME_WRITE = 'GAtestWrite\&.xml'\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 29 of file XMLDocumentBuilderTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
