.TH "org.jgap.gp.impl.DefaultGPFitnessEvaluator" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.impl.DefaultGPFitnessEvaluator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.gp\&.IGPFitnessEvaluator\fP, and Cloneable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBisFitter\fP (final double a_fitness_value1, final double a_fitness_value2)"
.br
.ti -1c
.RI "boolean \fBisFitter\fP (\fBIGPProgram\fP a_prog1, \fBIGPProgram\fP a_prog2)"
.br
.ti -1c
.RI "boolean \fBequals\fP (Object a_object)"
.br
.ti -1c
.RI "int \fBcompareTo\fP (Object a_object)"
.br
.ti -1c
.RI "Object \fBclone\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.8 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A default implementation of a fitness evaluator\&. This implementation is straight forward: a higher fitness value is seen as fitter\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 21 of file DefaultGPFitnessEvaluator\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Object org\&.jgap\&.gp\&.impl\&.DefaultGPFitnessEvaluator\&.clone ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
deep clone of this instance
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 108 of file DefaultGPFitnessEvaluator\&.java\&.
.SS "int org\&.jgap\&.gp\&.impl\&.DefaultGPFitnessEvaluator\&.compareTo (Objecta_object)\fC [inline]\fP"

.PP
Definition at line 97 of file DefaultGPFitnessEvaluator\&.java\&.
.SS "boolean org\&.jgap\&.gp\&.impl\&.DefaultGPFitnessEvaluator\&.equals (Objecta_object)\fC [inline]\fP"

.PP
Definition at line 88 of file DefaultGPFitnessEvaluator\&.java\&.
.SS "boolean org\&.jgap\&.gp\&.impl\&.DefaultGPFitnessEvaluator\&.isFitter (final doublea_fitness_value1, final doublea_fitness_value2)\fC [inline]\fP"
Compares the first given fitness value with the second and returns true if the first one is greater than the second one\&. Otherwise returns false 
.PP
\fBParameters:\fP
.RS 4
\fIa_fitness_value1\fP first fitness value 
.br
\fIa_fitness_value2\fP second fitness value 
.RE
.PP
\fBReturns:\fP
.RS 4
true: first fitness value greater than second
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 (until 1\&.1: input types int) 
.RE
.PP

.PP
Definition at line 36 of file DefaultGPFitnessEvaluator\&.java\&.
.PP
Referenced by org\&.jgap\&.gp\&.impl\&.DefaultGPFitnessEvaluator\&.isFitter()\&.
.SS "boolean org\&.jgap\&.gp\&.impl\&.DefaultGPFitnessEvaluator\&.isFitter (\fBIGPProgram\fPa_prog1, \fBIGPProgram\fPa_prog2)\fC [inline]\fP"

.PP
Implements \fBorg\&.jgap\&.gp\&.IGPFitnessEvaluator\fP\&.
.PP
Definition at line 52 of file DefaultGPFitnessEvaluator\&.java\&.
.PP
References org\&.jgap\&.gp\&.impl\&.DefaultGPFitnessEvaluator\&.isFitter()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.gp\&.impl\&.DefaultGPFitnessEvaluator\&.CVS_REVISION = '$Revision: 1\&.8 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 24 of file DefaultGPFitnessEvaluator\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
