.TH "org.jgap.GenotypeTest.Test2Function" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.GenotypeTest.Test2Function \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.FitnessFunction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBevaluate\fP (\fBIChromosome\fP ic)"
.br
.ti -1c
.RI "Double \fBgetX\fP (\fBIChromosome\fP a_potentialSolution)"
.br
.ti -1c
.RI "Double \fBgetY\fP (\fBIChromosome\fP a_potentialSolution)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1556 of file GenotypeTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "double org\&.jgap\&.GenotypeTest\&.Test2Function\&.evaluate (\fBIChromosome\fPa_subject)\fC [inline]\fP, \fC [virtual]\fP"
Determine the fitness of the given \fBChromosome\fP instance\&. The higher the return value, the more fit the instance\&. This method should always return the same fitness value for two equivalent \fBChromosome\fP instances\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_subject\fP the \fBChromosome\fP instance to evaluate
.RE
.PP
\fBReturns:\fP
.RS 4
positive double reflecting the fitness rating of the given \fBChromosome\fP\&. Note that if a non-positive double is returned, a RuntimeException should be generated
.RE
.PP
\fBAuthor:\fP
.RS 4
Neil Rotstan 
.PP
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 (until 1\&.1: return type int) 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.FitnessFunction\fP\&.
.PP
Definition at line 1566 of file GenotypeTest\&.java\&.
.PP
References org\&.jgap\&.GenotypeTest\&.Test2Function\&.getX(), and org\&.jgap\&.GenotypeTest\&.Test2Function\&.getY()\&.
.SS "Double org\&.jgap\&.GenotypeTest\&.Test2Function\&.getX (\fBIChromosome\fPa_potentialSolution)\fC [inline]\fP"

.PP
Definition at line 1581 of file GenotypeTest\&.java\&.
.PP
References org\&.jgap\&.IChromosome\&.getGene()\&.
.PP
Referenced by org\&.jgap\&.GenotypeTest\&.Test2Function\&.evaluate()\&.
.SS "Double org\&.jgap\&.GenotypeTest\&.Test2Function\&.getY (\fBIChromosome\fPa_potentialSolution)\fC [inline]\fP"

.PP
Definition at line 1587 of file GenotypeTest\&.java\&.
.PP
References org\&.jgap\&.IChromosome\&.getGene()\&.
.PP
Referenced by org\&.jgap\&.GenotypeTest\&.Test2Function\&.evaluate()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
