.TH "org.jgap.data.IDataElement" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.data.IDataElement \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg\&.jgap\&.data\&.DataElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetAttribute\fP (String a_name, String a_value)  throws Exception"
.br
.ti -1c
.RI "void \fBappendChild\fP (\fBIDataElement\fP a_newChild)  throws Exception"
.br
.ti -1c
.RI "String \fBgetTagName\fP ()"
.br
.ti -1c
.RI "\fBIDataElementList\fP \fBgetElementsByTagName\fP (String a_name)"
.br
.ti -1c
.RI "\fBIDataElementList\fP \fBgetChildNodes\fP ()"
.br
.ti -1c
.RI "String \fBgetAttribute\fP (String a_name)"
.br
.ti -1c
.RI "Map \fBgetAttributes\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.4 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBIDataElement\fP interface represents an entity comparable to org\&.w3c\&.dom\&.Element
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 21 of file IDataElement\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.data\&.IDataElement\&.appendChild (\fBIDataElement\fPa_newChild) throws Exception"

.SS "String org\&.jgap\&.data\&.IDataElement\&.getAttribute (Stringa_name)"

.SS "Map org\&.jgap\&.data\&.IDataElement\&.getAttributes ()"

.PP
Implemented in \fBorg\&.jgap\&.data\&.DataElement\fP\&.
.SS "\fBIDataElementList\fP org\&.jgap\&.data\&.IDataElement\&.getChildNodes ()"

.PP
Implemented in \fBorg\&.jgap\&.data\&.DataElement\fP\&.
.SS "\fBIDataElementList\fP org\&.jgap\&.data\&.IDataElement\&.getElementsByTagName (Stringa_name)"

.SS "String org\&.jgap\&.data\&.IDataElement\&.getTagName ()"

.PP
Implemented in \fBorg\&.jgap\&.data\&.DataElement\fP\&.
.PP
Referenced by org\&.jgap\&.data\&.DataTreeBuilderTest\&.testRepresentChromosomeAsDocument_0(), and org\&.jgap\&.data\&.DataTreeBuilderTest\&.testRepresentGenotypeAsDocument_0()\&.
.SS "void org\&.jgap\&.data\&.IDataElement\&.setAttribute (Stringa_name, Stringa_value) throws Exception"

.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.data\&.IDataElement\&.CVS_REVISION = '$Revision: 1\&.4 $'\fC [static]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 23 of file IDataElement\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
