.TH "org.jgap.distr.grid.MessageContext" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.grid.MessageContext \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BasicContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessageContext\fP ()"
.br
.ti -1c
.RI "\fBMessageContext\fP (String a_module, String a_context, Object a_contextid)"
.br
.ti -1c
.RI "String \fBgetContext\fP ()"
.br
.ti -1c
.RI "String \fBgetModule\fP ()"
.br
.ti -1c
.RI "void \fBsetModule\fP (String a_module)"
.br
.ti -1c
.RI "void \fBsetContext\fP (String a_context)"
.br
.ti -1c
.RI "String \fBgetUserID\fP ()"
.br
.ti -1c
.RI "String \fBgetUserGrp\fP ()"
.br
.ti -1c
.RI "void \fBsetUserGrp\fP (String a_userGrp)"
.br
.ti -1c
.RI "void \fBsetUserID\fP (String a_userID)"
.br
.ti -1c
.RI "String \fBgetVersion\fP ()"
.br
.ti -1c
.RI "void \fBsetVersion\fP (String a_version)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "String \fBm_module\fP"
.br
.ti -1c
.RI "String \fBm_context\fP"
.br
.ti -1c
.RI "String \fBm_userGrp\fP"
.br
.ti -1c
.RI "String \fBm_userID\fP"
.br
.ti -1c
.RI "String \fBm_version\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.4 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Context of a message\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.3 
.RE
.PP

.PP
Definition at line 20 of file MessageContext\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.distr\&.grid\&.MessageContext\&.MessageContext ()\fC [inline]\fP"

.PP
Definition at line 35 of file MessageContext\&.java\&.
.SS "org\&.jgap\&.distr\&.grid\&.MessageContext\&.MessageContext (Stringa_module, Stringa_context, Objecta_contextid)\fC [inline]\fP"

.PP
Definition at line 38 of file MessageContext\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.MessageContext\&.m_context, and org\&.jgap\&.distr\&.grid\&.MessageContext\&.m_module\&.
.SH "Member Function Documentation"
.PP 
.SS "String org\&.jgap\&.distr\&.grid\&.MessageContext\&.getContext ()\fC [inline]\fP"

.PP
Definition at line 44 of file MessageContext\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.MessageContext\&.m_context\&.
.SS "String org\&.jgap\&.distr\&.grid\&.MessageContext\&.getModule ()\fC [inline]\fP"

.PP
Definition at line 48 of file MessageContext\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.MessageContext\&.m_module\&.
.SS "String org\&.jgap\&.distr\&.grid\&.MessageContext\&.getUserGrp ()\fC [inline]\fP"

.PP
Definition at line 64 of file MessageContext\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.MessageContext\&.m_userGrp\&.
.SS "String org\&.jgap\&.distr\&.grid\&.MessageContext\&.getUserID ()\fC [inline]\fP"

.PP
Definition at line 60 of file MessageContext\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.MessageContext\&.m_userID\&.
.SS "String org\&.jgap\&.distr\&.grid\&.MessageContext\&.getVersion ()\fC [inline]\fP"

.PP
Definition at line 76 of file MessageContext\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.MessageContext\&.m_version\&.
.SS "void org\&.jgap\&.distr\&.grid\&.MessageContext\&.setContext (Stringa_context)\fC [inline]\fP"

.PP
Definition at line 56 of file MessageContext\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.MessageContext\&.m_context\&.
.SS "void org\&.jgap\&.distr\&.grid\&.MessageContext\&.setModule (Stringa_module)\fC [inline]\fP"

.PP
Definition at line 52 of file MessageContext\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.MessageContext\&.m_module\&.
.SS "void org\&.jgap\&.distr\&.grid\&.MessageContext\&.setUserGrp (Stringa_userGrp)\fC [inline]\fP"

.PP
Definition at line 68 of file MessageContext\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.MessageContext\&.m_userGrp\&.
.SS "void org\&.jgap\&.distr\&.grid\&.MessageContext\&.setUserID (Stringa_userID)\fC [inline]\fP"

.PP
Definition at line 72 of file MessageContext\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.MessageContext\&.m_userID\&.
.SS "void org\&.jgap\&.distr\&.grid\&.MessageContext\&.setVersion (Stringa_version)\fC [inline]\fP"

.PP
Definition at line 80 of file MessageContext\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.MessageContext\&.m_version\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.grid\&.MessageContext\&.CVS_REVISION = '$Revision: 1\&.4 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 23 of file MessageContext\&.java\&.
.SS "String org\&.jgap\&.distr\&.grid\&.MessageContext\&.m_context\fC [private]\fP"

.PP
Definition at line 27 of file MessageContext\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.MessageContext\&.getContext(), org\&.jgap\&.distr\&.grid\&.MessageContext\&.MessageContext(), and org\&.jgap\&.distr\&.grid\&.MessageContext\&.setContext()\&.
.SS "String org\&.jgap\&.distr\&.grid\&.MessageContext\&.m_module\fC [private]\fP"

.PP
Definition at line 25 of file MessageContext\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.MessageContext\&.getModule(), org\&.jgap\&.distr\&.grid\&.MessageContext\&.MessageContext(), and org\&.jgap\&.distr\&.grid\&.MessageContext\&.setModule()\&.
.SS "String org\&.jgap\&.distr\&.grid\&.MessageContext\&.m_userGrp\fC [private]\fP"

.PP
Definition at line 29 of file MessageContext\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.MessageContext\&.getUserGrp(), and org\&.jgap\&.distr\&.grid\&.MessageContext\&.setUserGrp()\&.
.SS "String org\&.jgap\&.distr\&.grid\&.MessageContext\&.m_userID\fC [private]\fP"

.PP
Definition at line 31 of file MessageContext\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.MessageContext\&.getUserID(), and org\&.jgap\&.distr\&.grid\&.MessageContext\&.setUserID()\&.
.SS "String org\&.jgap\&.distr\&.grid\&.MessageContext\&.m_version\fC [private]\fP"

.PP
Definition at line 33 of file MessageContext\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.MessageContext\&.getVersion(), and org\&.jgap\&.distr\&.grid\&.MessageContext\&.setVersion()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
