.TH "org.jgap.impl.FittestPopulationMerger" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.FittestPopulationMerger \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits IPopulationMerger\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFitnessChromosomeComparator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPopulation\fP \fBmergePopulations\fP (final \fBPopulation\fP a_population1, final \fBPopulation\fP a_population2, final int a_new_population_size)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.17 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
A implementation of the IPopulationMerger interface that merges two populations as specified based on the fitness function, that is, the n fittest chromosomes are returned in the new population, where n is supplied by parameter\&.
.PP
\fBAuthor:\fP
.RS 4
Henrique Goulart 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 25 of file FittestPopulationMerger\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPopulation\fP org\&.jgap\&.impl\&.FittestPopulationMerger\&.mergePopulations (final \fBPopulation\fPa_population1, final \fBPopulation\fPa_population2, final inta_new_population_size)\fC [inline]\fP"

.PP
\fBTodo\fP
.RS 4
check if configurations of both pops are equal resp\&. their fitness evaluators! 
.RE
.PP

.PP
Definition at line 30 of file FittestPopulationMerger\&.java\&.
.PP
References org\&.jgap\&.Population\&.getConfiguration()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.FittestPopulationMerger\&.CVS_REVISION = '$Revision: 1\&.17 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 28 of file FittestPopulationMerger\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
