.TH "org.jgap.util.UniqueRandomGenerator" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.util.UniqueRandomGenerator \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUniqueRandomGenerator\fP (int a_upperBoundary, \fBRandomGenerator\fP a_generator)"
.br
.ti -1c
.RI "int \fBnextInt\fP ()  throws IllegalStateException "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_upper\fP"
.br
.ti -1c
.RI "List \fBm_resultSet\fP"
.br
.ti -1c
.RI "\fBRandomGenerator\fP \fBm_generator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file UniqueRandomGenerator\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.util\&.UniqueRandomGenerator\&.UniqueRandomGenerator (inta_upperBoundary, \fBRandomGenerator\fPa_generator)\fC [inline]\fP"

.PP
Definition at line 13 of file UniqueRandomGenerator\&.java\&.
.PP
References org\&.jgap\&.util\&.UniqueRandomGenerator\&.m_generator, org\&.jgap\&.util\&.UniqueRandomGenerator\&.m_resultSet, and org\&.jgap\&.util\&.UniqueRandomGenerator\&.m_upper\&.
.SH "Member Function Documentation"
.PP 
.SS "int org\&.jgap\&.util\&.UniqueRandomGenerator\&.nextInt () throws IllegalStateException\fC [inline]\fP"

.PP
Definition at line 22 of file UniqueRandomGenerator\&.java\&.
.PP
References org\&.jgap\&.util\&.UniqueRandomGenerator\&.m_resultSet\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBRandomGenerator\fP org\&.jgap\&.util\&.UniqueRandomGenerator\&.m_generator\fC [private]\fP"

.PP
Definition at line 11 of file UniqueRandomGenerator\&.java\&.
.PP
Referenced by org\&.jgap\&.util\&.UniqueRandomGenerator\&.UniqueRandomGenerator()\&.
.SS "List org\&.jgap\&.util\&.UniqueRandomGenerator\&.m_resultSet\fC [private]\fP"

.PP
Definition at line 9 of file UniqueRandomGenerator\&.java\&.
.PP
Referenced by org\&.jgap\&.util\&.UniqueRandomGenerator\&.nextInt(), and org\&.jgap\&.util\&.UniqueRandomGenerator\&.UniqueRandomGenerator()\&.
.SS "int org\&.jgap\&.util\&.UniqueRandomGenerator\&.m_upper\fC [private]\fP"

.PP
Definition at line 7 of file UniqueRandomGenerator\&.java\&.
.PP
Referenced by org\&.jgap\&.util\&.UniqueRandomGenerator\&.UniqueRandomGenerator()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
