.TH "org.jgap.xml.GeneCreationException" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.xml.GeneCreationException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeneCreationException\fP (final String a_message)"
.br
.ti -1c
.RI "\fBGeneCreationException\fP (final Class a_geneClass, Throwable cause)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.8 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBGeneCreationException\fP is a bit of a catch-all exception for representing problems encountered during the creation of a \fBGene\fP object with a value (allele) representation found in an XML document\&. Typically, this exception will be thrown if the concrete class indicated in the XML file cannot be found or instantiated for some reason, or if the class does not support the methods related to XML persistence\&. Consult the error message for details on the specific reason for failure\&.
.PP
\fBAuthor:\fP
.RS 4
Neil Rotstan 
.PP
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 26 of file GeneCreationException\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.xml\&.GeneCreationException\&.GeneCreationException (final Stringa_message)\fC [inline]\fP"
Constructs a new \fBGeneCreationException\fP instance with the given error message\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_message\fP an error message describing the reason this exception is being thrown
.RE
.PP
\fBAuthor:\fP
.RS 4
Neil Rotstan 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 41 of file GeneCreationException\&.java\&.
.SS "org\&.jgap\&.xml\&.GeneCreationException\&.GeneCreationException (final Classa_geneClass, Throwablecause)\fC [inline]\fP"
Constructs a new \fBGeneCreationException\fP instance with the given error message\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_message\fP an error message describing the reason this exception is being thrown 
.br
\fIa_geneClass\fP the class of the gene that should be instantiated
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 56 of file GeneCreationException\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.xml\&.GeneCreationException\&.CVS_REVISION = '$Revision: 1\&.8 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 29 of file GeneCreationException\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
