.TH "org.jgap.distr.grid.DefaultGenotypeInitializer" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.grid.DefaultGenotypeInitializer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.distr\&.grid\&.IGenotypeInitializer\fP, and Comparable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenotype\fP \fBsetupGenotype\fP (\fBJGAPRequest\fP a_req, \fBPopulation\fP a_initialPop)  throws Exception "
.br
.ti -1c
.RI "int \fBcompareTo\fP (Object a_other)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.4 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Default implementation of \fBIGenotypeInitializer\fP\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 20 of file DefaultGenotypeInitializer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int org\&.jgap\&.distr\&.grid\&.DefaultGenotypeInitializer\&.compareTo (Objecta_other)\fC [inline]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIa_other\fP sic 
.RE
.PP
\fBReturns:\fP
.RS 4
as always
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 63 of file DefaultGenotypeInitializer\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.DefaultGenotypeInitializerTest\&.testCompareTo_0()\&.
.SS "\fBGenotype\fP org\&.jgap\&.distr\&.grid\&.DefaultGenotypeInitializer\&.setupGenotype (\fBJGAPRequest\fPa_req, \fBPopulation\fPa_initialPop) throws Exception\fC [inline]\fP"
Sets up a \fBGenotype\fP by adding the content of the given \fBPopulation\fP to it and initializing the missing Chromosomes of the \fBGenotype\fP randomly\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_req\fP a \fBJGAPRequest\fP object containing useful information 
.br
\fIa_initialPop\fP the \fBPopulation\fP to consider 
.RE
.PP
\fBReturns:\fP
.RS 4
the initialized \fBGenotype\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.distr\&.grid\&.IGenotypeInitializer\fP\&.
.PP
Definition at line 37 of file DefaultGenotypeInitializer\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.grid\&.DefaultGenotypeInitializer\&.CVS_REVISION = '$Revision: 1\&.4 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 23 of file DefaultGenotypeInitializer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
