.TH "org.jgap.gp.CommandGene.COMMAND_TYPE" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.CommandGene.COMMAND_TYPE \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBintValue\fP ()"
.br
.ti -1c
.RI "\fBCOMMAND_TYPE\fP (int a_value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCOMMAND_TYPE_UNDEFINED\fP =(0)"
.br
.ti -1c
.RI "\fBCOMMAND_TYPE_LOOP\fP =(8)"
.br
.ti -1c
.RI "\fBCOMMAND_TYPE_CONDITIONAL\fP =(16)"
.br
.ti -1c
.RI "\fBCOMMAND_TYPE_OPERATION\fP =(32)"
.br
.ti -1c
.RI "\fBCOMMAND_TYPE_MATH_OPERATION\fP =(33)"
.br
.ti -1c
.RI "\fBCOMMAND_TYPE_DECLARATION\fP =(64)"
.br
.ti -1c
.RI "\fBCOMMAND_TYPE_ASSIGNMENT\fP =(128)"
.br
.ti -1c
.RI "\fBCOMMAND_TYPE_ANALYSIS\fP =(256)"
.br
.ti -1c
.RI "\fBCOMMAND_TYPE_EXECUTION\fP =(512)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 63 of file CommandGene\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.gp\&.CommandGene\&.COMMAND_TYPE\&.COMMAND_TYPE (inta_value)\fC [inline]\fP"

.PP
Definition at line 80 of file CommandGene\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int org\&.jgap\&.gp\&.CommandGene\&.COMMAND_TYPE\&.intValue ()\fC [inline]\fP"

.PP
Definition at line 76 of file CommandGene\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "org\&.jgap\&.gp\&.CommandGene\&.COMMAND_TYPE\&.COMMAND_TYPE_ANALYSIS =(256)"

.PP
Definition at line 71 of file CommandGene\&.java\&.
.SS "org\&.jgap\&.gp\&.CommandGene\&.COMMAND_TYPE\&.COMMAND_TYPE_ASSIGNMENT =(128)"

.PP
Definition at line 70 of file CommandGene\&.java\&.
.SS "org\&.jgap\&.gp\&.CommandGene\&.COMMAND_TYPE\&.COMMAND_TYPE_CONDITIONAL =(16)"

.PP
Definition at line 66 of file CommandGene\&.java\&.
.SS "org\&.jgap\&.gp\&.CommandGene\&.COMMAND_TYPE\&.COMMAND_TYPE_DECLARATION =(64)"

.PP
Definition at line 69 of file CommandGene\&.java\&.
.SS "org\&.jgap\&.gp\&.CommandGene\&.COMMAND_TYPE\&.COMMAND_TYPE_EXECUTION =(512)"

.PP
Definition at line 72 of file CommandGene\&.java\&.
.SS "org\&.jgap\&.gp\&.CommandGene\&.COMMAND_TYPE\&.COMMAND_TYPE_LOOP =(8)"

.PP
Definition at line 65 of file CommandGene\&.java\&.
.SS "org\&.jgap\&.gp\&.CommandGene\&.COMMAND_TYPE\&.COMMAND_TYPE_MATH_OPERATION =(33)"

.PP
Definition at line 68 of file CommandGene\&.java\&.
.SS "org\&.jgap\&.gp\&.CommandGene\&.COMMAND_TYPE\&.COMMAND_TYPE_OPERATION =(32)"

.PP
Definition at line 67 of file CommandGene\&.java\&.
.SS "org\&.jgap\&.gp\&.CommandGene\&.COMMAND_TYPE\&.COMMAND_TYPE_UNDEFINED =(0)"

.PP
Definition at line 64 of file CommandGene\&.java\&.
.PP
Referenced by org\&.jgap\&.gp\&.CommandGene\&.getCommandType()\&.
.SS "int org\&.jgap\&.gp\&.CommandGene\&.COMMAND_TYPE\&.m_value\fC [private]\fP"

.PP
Definition at line 74 of file CommandGene\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
