.TH "org.jgap.gp.function.ArcCosine.Compatible" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.function.ArcCosine.Compatible \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Object \fBexecute_arccosine\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 61 of file ArcCosine\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Object org\&.jgap\&.gp\&.function\&.ArcCosine\&.Compatible\&.execute_arccosine ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
