.TH "org.jgap.InvalidConfigurationException" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.InvalidConfigurationException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInvalidConfigurationException\fP (final String a_message)"
.br
.ti -1c
.RI "\fBInvalidConfigurationException\fP (final Throwable a_exception)"
.br
.ti -1c
.RI "\fBInvalidConfigurationException\fP (final String a_message, final Throwable a_exception)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.9 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
This exception is typically thrown when an invalid value has been passed to a \fBConfiguration\fP object, an attempt is made to lock a \fBConfiguration\fP object before all required settings have been provided, or an attempt is made to alter a setting in a \fBConfiguration\fP object after it has been successfully locked\&.
.PP
\fBAuthor:\fP
.RS 4
Neil Rotstan 
.PP
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 23 of file InvalidConfigurationException\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.InvalidConfigurationException\&.InvalidConfigurationException (final Stringa_message)\fC [inline]\fP"
Constructs a new \fBInvalidConfigurationException\fP instance with the given error message\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_message\fP An error message describing the reason this exception is being thrown
.RE
.PP
\fBAuthor:\fP
.RS 4
Neil Rotstan 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 38 of file InvalidConfigurationException\&.java\&.
.SS "org\&.jgap\&.InvalidConfigurationException\&.InvalidConfigurationException (final Throwablea_exception)\fC [inline]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIa_exception\fP Throwable
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 48 of file InvalidConfigurationException\&.java\&.
.SS "org\&.jgap\&.InvalidConfigurationException\&.InvalidConfigurationException (final Stringa_message, final Throwablea_exception)\fC [inline]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIa_message\fP An error message describing the reason this exception is being thrown 
.br
\fIa_exception\fP Throwable
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.5 
.RE
.PP

.PP
Definition at line 60 of file InvalidConfigurationException\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.InvalidConfigurationException\&.CVS_REVISION = '$Revision: 1\&.9 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file InvalidConfigurationException\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
