.TH "org.jgap.gp.function.Multiply.Compatible" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.function.Multiply.Compatible \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Object \fBexecute_multiply\fP (Object o)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 91 of file Multiply\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Object org\&.jgap\&.gp\&.function\&.Multiply\&.Compatible\&.execute_multiply (Objecto)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
