.TH "org.jgap.distr.CultureMemoryCellTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.CultureMemoryCellTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestToString_0\fP ()"
.br
.ti -1c
.RI "void \fBtestToString_1\fP ()"
.br
.ti -1c
.RI "void \fBtestToString_2\fP ()"
.br
.ti -1c
.RI "void \fBtestSetDouble_0\fP ()"
.br
.ti -1c
.RI "void \fBtestSetValue_0\fP ()"
.br
.ti -1c
.RI "void \fBtestSerialize_0\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.11 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBCultureMemoryCell\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 22 of file CultureMemoryCellTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.distr\&.CultureMemoryCellTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 27 of file CultureMemoryCellTest\&.java\&.
.SS "void org\&.jgap\&.distr\&.CultureMemoryCellTest\&.testSerialize_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 141 of file CultureMemoryCellTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.doSerialize()\&.
.SS "void org\&.jgap\&.distr\&.CultureMemoryCellTest\&.testSetDouble_0 ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 85 of file CultureMemoryCellTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.DELTA, org\&.jgap\&.distr\&.CultureMemoryCell\&.getCurrentValue(), and org\&.jgap\&.distr\&.CultureMemoryCell\&.getCurrentValueAsDouble()\&.
.SS "void org\&.jgap\&.distr\&.CultureMemoryCellTest\&.testSetValue_0 ()\fC [inline]\fP"

.PP
Definition at line 99 of file CultureMemoryCellTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.distr\&.CultureMemoryCell\&.getCurrentValue(), org\&.jgap\&.distr\&.CultureMemoryCell\&.getReadAccessed(), and org\&.jgap\&.distr\&.CultureMemoryCell\&.getVersion()\&.
.SS "void org\&.jgap\&.distr\&.CultureMemoryCellTest\&.testToString_0 ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 36 of file CultureMemoryCellTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.distr\&.CultureMemoryCell\&.toString()\&.
.SS "void org\&.jgap\&.distr\&.CultureMemoryCellTest\&.testToString_1 ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 53 of file CultureMemoryCellTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.distr\&.CultureMemoryCell\&.toString()\&.
.SS "void org\&.jgap\&.distr\&.CultureMemoryCellTest\&.testToString_2 ()\fC [inline]\fP"
Empty cell\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 74 of file CultureMemoryCellTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.distr\&.CultureMemoryCell\&.toString()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.CultureMemoryCellTest\&.CVS_REVISION = '$Revision: 1\&.11 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file CultureMemoryCellTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
