.TH "org.jgap.distr.grid.RequestSplitStrategy" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.grid.RequestSplitStrategy \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRequestSplitStrategy\fP (\fBConfiguration\fP a_config)"
.br
.ti -1c
.RI "\fBConfiguration\fP \fBgetConfiguration\fP ()"
.br
.ti -1c
.RI "\fBJGAPRequest\fP[] \fBsplit\fP (\fBJGAPRequest\fP a_request)  throws Exception "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBConfiguration\fP \fBm_config\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.4 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of \fBIRequestSplitStrategy\fP to split a single request into multiple requests for workers\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 23 of file RequestSplitStrategy\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.distr\&.grid\&.RequestSplitStrategy\&.RequestSplitStrategy (\fBConfiguration\fPa_config)\fC [inline]\fP"

.PP
Definition at line 30 of file RequestSplitStrategy\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.RequestSplitStrategy\&.m_config\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBConfiguration\fP org\&.jgap\&.distr\&.grid\&.RequestSplitStrategy\&.getConfiguration ()\fC [inline]\fP"

.PP
Definition at line 34 of file RequestSplitStrategy\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.RequestSplitStrategy\&.m_config\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.RequestSplitStrategy\&.split()\&.
.SS "\fBJGAPRequest\fP [] org\&.jgap\&.distr\&.grid\&.RequestSplitStrategy\&.split (\fBJGAPRequest\fPa_request) throws Exception\fC [inline]\fP"
Creates single requests to be sent to workers\&.
.PP
\fBReturns:\fP
.RS 4
single requests to be computed by workers 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.01 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
support cloning of m_config 
.RE
.PP

.PP
Definition at line 46 of file RequestSplitStrategy\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.RequestSplitStrategy\&.getConfiguration(), and org\&.jgap\&.distr\&.grid\&.JGAPRequest\&.newInstance()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.grid\&.RequestSplitStrategy\&.CVS_REVISION = '$Revision: 1\&.4 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file RequestSplitStrategy\&.java\&.
.SS "\fBConfiguration\fP org\&.jgap\&.distr\&.grid\&.RequestSplitStrategy\&.m_config\fC [private]\fP"

.PP
Definition at line 28 of file RequestSplitStrategy\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.RequestSplitStrategy\&.getConfiguration(), and org\&.jgap\&.distr\&.grid\&.RequestSplitStrategy\&.RequestSplitStrategy()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
