.TH "org.jgap.distr.grid.common.ResultVerification" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.grid.common.ResultVerification \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResultVerification\fP ()"
.br
.ti -1c
.RI "void \fBaddResultData\fP (\fBResultData\fP a_data)"
.br
.ti -1c
.RI "List \fBgetResultData\fP ()"
.br
.ti -1c
.RI "boolean \fBisVerifiedByWorker\fP (String a_workerGUID)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "List< \fBResultData\fP > \fBm_resultData\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.1 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds information about how a result was verified\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 20 of file ResultVerification\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.distr\&.grid\&.common\&.ResultVerification\&.ResultVerification ()\fC [inline]\fP"

.PP
Definition at line 26 of file ResultVerification\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.common\&.ResultVerification\&.m_resultData\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.distr\&.grid\&.common\&.ResultVerification\&.addResultData (\fBResultData\fPa_data)\fC [inline]\fP"

.PP
Definition at line 30 of file ResultVerification\&.java\&.
.SS "List org\&.jgap\&.distr\&.grid\&.common\&.ResultVerification\&.getResultData ()\fC [inline]\fP"

.PP
Definition at line 34 of file ResultVerification\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.common\&.ResultVerification\&.m_resultData\&.
.SS "boolean org\&.jgap\&.distr\&.grid\&.common\&.ResultVerification\&.isVerifiedByWorker (Stringa_workerGUID)\fC [inline]\fP"

.PP
Definition at line 38 of file ResultVerification\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.common\&.ResultVerification\&.m_resultData\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.grid\&.common\&.ResultVerification\&.CVS_REVISION = '$Revision: 1\&.1 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 22 of file ResultVerification\&.java\&.
.SS "List<\fBResultData\fP> org\&.jgap\&.distr\&.grid\&.common\&.ResultVerification\&.m_resultData\fC [private]\fP"

.PP
Definition at line 24 of file ResultVerification\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.common\&.ResultVerification\&.getResultData(), org\&.jgap\&.distr\&.grid\&.common\&.ResultVerification\&.isVerifiedByWorker(), and org\&.jgap\&.distr\&.grid\&.common\&.ResultVerification\&.ResultVerification()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
