.TH "org.jgap.audit.PermutingConfigurationTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.audit.PermutingConfigurationTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtestConstruct_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPermute_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPermute_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestNotSupported_1\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.5 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBPermutingConfiguration\fP class
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 15 of file PermutingConfigurationTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.audit\&.PermutingConfigurationTest\&.setUp ()\fC [inline]\fP"

.PP
Definition at line 20 of file PermutingConfigurationTest\&.java\&.
.SS "static Test org\&.jgap\&.audit\&.PermutingConfigurationTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 25 of file PermutingConfigurationTest\&.java\&.
.SS "void org\&.jgap\&.audit\&.PermutingConfigurationTest\&.testConstruct_0 () throws Exception\fC [inline]\fP"
Test construction with empty fitness function, population size 0, random generator initial, sample chromosome initial of reference configuration\&. No error should occur\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 39 of file PermutingConfigurationTest\&.java\&.
.SS "void org\&.jgap\&.audit\&.PermutingConfigurationTest\&.testConstruct_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 51 of file PermutingConfigurationTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.audit\&.PermutingConfigurationTest\&.testNotSupported_1 () throws Exception\fC [inline]\fP"
Ensures that not supported methods throw an exception 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 144 of file PermutingConfigurationTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.audit\&.PermutingConfigurationTest\&.testPermute_0 () throws Exception\fC [inline]\fP"
Tests if the correct number of permutations appears and that they are unique\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 77 of file PermutingConfigurationTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.audit\&.PermutingConfiguration\&.hasNext()\&.
.SS "void org\&.jgap\&.audit\&.PermutingConfigurationTest\&.testPermute_1 () throws Exception\fC [inline]\fP"
Permutation without chromosome pool 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 121 of file PermutingConfigurationTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.audit\&.PermutingConfigurationTest\&.CVS_REVISION = '$Revision: 1\&.5 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 18 of file PermutingConfigurationTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
