.TH "org.jgap.distr.grid.JGAPServer" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.grid.JGAPServer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJGAPServer\fP (String[] args)  throws Exception "
.br
.ti -1c
.RI "void \fBaddFile\fP (String a_filename)  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBcopyFile\fP (String source, String dest)  throws Exception "
.br
.ti -1c
.RI "static void \fBmain\fP (String[] args)  throws Exception "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "GridServer \fBm_gs\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.7 $'"
.br
.ti -1c
.RI "static final String \fBclassName\fP = JGAPServer\&.class\&.getName()"
.br
.ti -1c
.RI "static Logger \fBlog\fP = Logger\&.getLogger(\fBclassName\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A grid server is able to:
.PP
a) receive work requests from JGAPClients b) send work units to \fBJGAPWorkers\fP c) receive solutions from \fBJGAPWorkers\fP, and d) send back these solutions to the requesting \fBJGAPClient\fP\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.01 
.RE
.PP

.PP
Definition at line 29 of file JGAPServer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.distr\&.grid\&.JGAPServer\&.JGAPServer (String[]args) throws Exception\fC [inline]\fP"

.PP
Definition at line 39 of file JGAPServer\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.JGAPServer\&.m_gs\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.JGAPServer\&.main()\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.distr\&.grid\&.JGAPServer\&.addFile (Stringa_filename) throws Exception\fC [inline]\fP"

.PP
Definition at line 52 of file JGAPServer\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.JGAPServer\&.copyFile()\&.
.SS "static void org\&.jgap\&.distr\&.grid\&.JGAPServer\&.copyFile (Stringsource, Stringdest) throws Exception\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 64 of file JGAPServer\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.JGAPServer\&.addFile()\&.
.SS "static void org\&.jgap\&.distr\&.grid\&.JGAPServer\&.main (String[]args) throws Exception\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 88 of file JGAPServer\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.JGAPServer\&.JGAPServer()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.grid\&.JGAPServer\&.className = JGAPServer\&.class\&.getName()\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 33 of file JGAPServer\&.java\&.
.SS "final String org\&.jgap\&.distr\&.grid\&.JGAPServer\&.CVS_REVISION = '$Revision: 1\&.7 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 31 of file JGAPServer\&.java\&.
.SS "Logger org\&.jgap\&.distr\&.grid\&.JGAPServer\&.log = Logger\&.getLogger(\fBclassName\fP)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 35 of file JGAPServer\&.java\&.
.SS "GridServer org\&.jgap\&.distr\&.grid\&.JGAPServer\&.m_gs\fC [private]\fP"

.PP
Definition at line 37 of file JGAPServer\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.JGAPServer\&.JGAPServer()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
