.TH "org.jgap.impl.DefaultCloneHandlerTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.DefaultCloneHandlerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyAppDataForTesting\fP"
.br
.ti -1c
.RI "class \fBMyClassForTesting\fP"
.br
.ti -1c
.RI "class \fBMyCloneHandlerForTesting\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestIsHandlerFor_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestIsHandlerFor_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestIsHandlerFor_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestIsHandlerFor_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPerform_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPerform_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPerform_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPerform_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPerform_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPerform_6\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.8 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBDefaultCloneHandler\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 23 of file DefaultCloneHandlerTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.impl\&.DefaultCloneHandlerTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 28 of file DefaultCloneHandlerTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.DefaultCloneHandlerTest\&.testIsHandlerFor_0 () throws Exception\fC [inline]\fP"
Handler implementing Cloneable without clone() method\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 40 of file DefaultCloneHandlerTest\&.java\&.
.PP
References org\&.jgap\&.IHandler\&.isHandlerFor()\&.
.SS "void org\&.jgap\&.impl\&.DefaultCloneHandlerTest\&.testIsHandlerFor_1 () throws Exception\fC [inline]\fP"
Handler not implementing Cloneable\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 53 of file DefaultCloneHandlerTest\&.java\&.
.PP
References org\&.jgap\&.IHandler\&.isHandlerFor()\&.
.SS "void org\&.jgap\&.impl\&.DefaultCloneHandlerTest\&.testIsHandlerFor_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 65 of file DefaultCloneHandlerTest\&.java\&.
.PP
References org\&.jgap\&.IHandler\&.isHandlerFor()\&.
.SS "void org\&.jgap\&.impl\&.DefaultCloneHandlerTest\&.testIsHandlerFor_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 78 of file DefaultCloneHandlerTest\&.java\&.
.PP
References org\&.jgap\&.IHandler\&.isHandlerFor()\&.
.SS "void org\&.jgap\&.impl\&.DefaultCloneHandlerTest\&.testPerform_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 90 of file DefaultCloneHandlerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.IHandler\&.perform()\&.
.SS "void org\&.jgap\&.impl\&.DefaultCloneHandlerTest\&.testPerform_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 105 of file DefaultCloneHandlerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.IHandler\&.perform()\&.
.SS "void org\&.jgap\&.impl\&.DefaultCloneHandlerTest\&.testPerform_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 120 of file DefaultCloneHandlerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.IHandler\&.perform()\&.
.SS "void org\&.jgap\&.impl\&.DefaultCloneHandlerTest\&.testPerform_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 134 of file DefaultCloneHandlerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.IHandler\&.perform()\&.
.SS "void org\&.jgap\&.impl\&.DefaultCloneHandlerTest\&.testPerform_5 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 148 of file DefaultCloneHandlerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.IHandler\&.perform()\&.
.SS "void org\&.jgap\&.impl\&.DefaultCloneHandlerTest\&.testPerform_6 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 162 of file DefaultCloneHandlerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.IHandler\&.perform()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.DefaultCloneHandlerTest\&.CVS_REVISION = '$Revision: 1\&.8 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file DefaultCloneHandlerTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
