.TH "org.jgap.impl.FixedBinaryGeneTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.FixedBinaryGeneTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGeneConstraintChecker\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestConstruct_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestToString_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestToString_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestToString_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetAllele_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetAllele_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetAllele_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_7\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_8\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetIntValues_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetIntValues_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetIntValues_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetIntValues_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_7\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetConstraintChecker_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_3_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_3_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValueFromPersistentRepresentation_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValueFromPersistentRepresentation_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValueFromPersistentRepresentation_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValueFromPersistentRepresentation_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValueFromPersistentRepresentation_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValueFromPersistentRepresentation_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValueFromPersistentRepresentation_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetPersistentRepresentation_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetPersistentRepresentation_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetPersistentRepresentation_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestClone_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestClone_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetBit_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetBit_0_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetBit_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetBit_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetBit_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetBit_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetBit_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetBit_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSubbString_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSubString_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestFlip_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestFlip_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestNewGene_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestHashCode_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestHashCode_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestHashCode_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestHashCode_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetEnergy_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetEnergy_1\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.34 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBFixedBinaryGene\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.PP
vamsi 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 22 of file FixedBinaryGeneTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 27 of file FixedBinaryGeneTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testApplyMutation_0 () throws Exception\fC [inline]\fP"
Apply Mutation (index,percentage)\&. if >0 make 1(0) if <0 make 0(1)
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 646 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.toString()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testApplyMutation_1 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 659 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.toString()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testApplyMutation_2 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 672 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testApplyMutation_3 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 691 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.toString()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testApplyMutation_4 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 704 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.toString()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testApplyMutation_5 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 719 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.toString()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testClone_0 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 899 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.FixedBinaryGene\&.clone(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testClone_1 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 912 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.FixedBinaryGene\&.clone(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testCompareTo_0 () throws Exception\fC [inline]\fP"
Comparison should return 0 if same, -1 if less 1 if more\&.
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 548 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.FixedBinaryGene\&.compareTo(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testCompareTo_1 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 564 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.FixedBinaryGene\&.compareTo(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testCompareTo_2 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 577 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.FixedBinaryGene\&.compareTo(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testCompareTo_3_1 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 596 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testCompareTo_3_2 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 614 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testCompareTo_4 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 632 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.FixedBinaryGene\&.compareTo(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testConstruct_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 38 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testConstruct_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 52 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testConstruct_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 68 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testConstruct_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP

.PP
Definition at line 84 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.impl\&.FixedBinaryGene\&.getBit(), and org\&.jgap\&.impl\&.FixedBinaryGene\&.toString()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testConstruct_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP

.PP
Definition at line 100 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.impl\&.FixedBinaryGene\&.getValue(), org\&.jgap\&.impl\&.FixedBinaryGene\&.size(), and org\&.jgap\&.impl\&.FixedBinaryGene\&.toString()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testConstruct_5 () throws Exception\fC [inline]\fP"
Buffer allocation test case\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP

.PP
Definition at line 115 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.size()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testConstruct_6 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 130 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testEquals_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP

.PP
Definition at line 229 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testEquals_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP

.PP
Definition at line 241 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testEquals_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP

.PP
Definition at line 252 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testEquals_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP

.PP
Definition at line 267 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testEquals_4 () throws Exception\fC [inline]\fP"

.PP
Definition at line 273 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testEquals_5 () throws Exception\fC [inline]\fP"

.PP
Definition at line 281 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testEquals_6 () throws Exception\fC [inline]\fP"

.PP
Definition at line 289 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testEquals_7 () throws Exception\fC [inline]\fP"

.PP
Definition at line 297 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testEquals_8 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 311 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testFlip_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 1120 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.getBit()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testFlip_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 1138 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testGetAllele_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP

.PP
Definition at line 177 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testGetAllele_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP

.PP
Definition at line 194 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testGetAllele_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 212 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testGetIntValues_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.3 
.RE
.PP

.PP
Definition at line 327 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.getIntValues()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testGetIntValues_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP

.PP
Definition at line 339 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.getIntValues()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testGetIntValues_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP

.PP
Definition at line 350 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testGetIntValues_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP

.PP
Definition at line 365 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.impl\&.FixedBinaryGene\&.getBit(), and org\&.jgap\&.impl\&.FixedBinaryGene\&.getLength()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testGetPersistentRepresentation_0 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 854 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testGetPersistentRepresentation_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 868 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testGetPersistentRepresentation_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 886 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testHashCode_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
implement checks for uniqueness 
.RE
.PP

.PP
Definition at line 1233 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testHashCode_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.5 
.RE
.PP

.PP
Definition at line 1250 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testHashCode_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.5 
.RE
.PP

.PP
Definition at line 1267 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testHashCode_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.5 
.RE
.PP

.PP
Definition at line 1282 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testNewGene_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 1216 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.BaseGene\&.equals(), and org\&.jgap\&.BaseGene\&.newGene()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetAllele_0 () throws Exception\fC [inline]\fP"
Allele is null\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP

.PP
Definition at line 382 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetAllele_1 () throws Exception\fC [inline]\fP"
Allele is of wrong type\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP

.PP
Definition at line 401 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetAllele_2 () throws Exception\fC [inline]\fP"
Set Allele to int values, no exception should occur\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP

.PP
Definition at line 420 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetAllele_3 () throws Exception\fC [inline]\fP"
The implementation should throw an exception if the alle size is more than the size of the created gene\&.
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 433 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetAllele_4 () throws Exception\fC [inline]\fP"
Allele contains illegal characters\&.
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 451 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetAllele_5 () throws Exception\fC [inline]\fP"
Allele is of wrong length\&.
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 469 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetAllele_6 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 487 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.getBit()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetAllele_7 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 508 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.getBit()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetBit_0 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 925 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.getBit()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetBit_0_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.3 
.RE
.PP

.PP
Definition at line 944 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.getBit()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetBit_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 963 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.getBit()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetBit_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 980 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetBit_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 999 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetBit_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 1018 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetBit_5 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 1037 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetBit_6 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 1060 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetConstraintChecker_0 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 529 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getConstraintChecker()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetEnergy_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 1299 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.BaseGene\&.getEnergy()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetEnergy_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 1311 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.BaseGene\&.getEnergy()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetToRandomValue_0 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 1157 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetToRandomValue_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 1175 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetToRandomValue_2 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 1187 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.getBit()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetToRandomValue_3 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 1202 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.getBit()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetValueFromPersistentRepresentation_0 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 736 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetValueFromPersistentRepresentation_1 () throws Exception\fC [inline]\fP"

.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 752 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetValueFromPersistentRepresentation_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 770 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.getBit()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetValueFromPersistentRepresentation_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 786 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.getBit()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetValueFromPersistentRepresentation_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 802 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.FixedBinaryGene\&.getBit()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetValueFromPersistentRepresentation_5 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 819 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSetValueFromPersistentRepresentation_6 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 837 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSubbString_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 1081 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testSubString_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 1101 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testToString_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP

.PP
Definition at line 141 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.toString()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testToString_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
vamsi 
.RE
.PP

.PP
Definition at line 153 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.toString()\&.
.SS "void org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.testToString_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 166 of file FixedBinaryGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.toString()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.FixedBinaryGeneTest\&.CVS_REVISION = '$Revision: 1\&.34 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file FixedBinaryGeneTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
