.TH "org.jgap.distr.MasterInfo" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.MasterInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMasterInfo\fP ()  throws Exception "
.br
.ti -1c
.RI "\fBMasterInfo\fP (boolean a_preset)  throws Exception "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "String \fBm_IPAddress\fP"
.br
.ti -1c
.RI "String \fBm_username\fP"
.br
.ti -1c
.RI "String \fBm_name\fP"
.br
.ti -1c
.RI "String \fBm_GUID\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.5 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds information about a computing entity\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 22 of file MasterInfo\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.distr\&.MasterInfo\&.MasterInfo () throws Exception\fC [inline]\fP"

.PP
Definition at line 46 of file MasterInfo\&.java\&.
.SS "org\&.jgap\&.distr\&.MasterInfo\&.MasterInfo (booleana_preset) throws Exception\fC [inline]\fP"

.PP
Definition at line 51 of file MasterInfo\&.java\&.
.PP
References org\&.jgap\&.distr\&.MasterInfo\&.m_GUID, org\&.jgap\&.distr\&.MasterInfo\&.m_IPAddress, and org\&.jgap\&.distr\&.MasterInfo\&.m_name\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.MasterInfo\&.CVS_REVISION = '$Revision: 1\&.5 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 24 of file MasterInfo\&.java\&.
.SS "String org\&.jgap\&.distr\&.MasterInfo\&.m_GUID"
Unique ID of a worker 
.PP
Definition at line 44 of file MasterInfo\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.MasterInfo\&.MasterInfo()\&.
.SS "String org\&.jgap\&.distr\&.MasterInfo\&.m_IPAddress"
The computer's address over which it is reachable in the network 
.PP
Definition at line 29 of file MasterInfo\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.MasterInfo\&.MasterInfo()\&.
.SS "String org\&.jgap\&.distr\&.MasterInfo\&.m_name"
Host name of the computer 
.PP
Definition at line 39 of file MasterInfo\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.MasterInfo\&.MasterInfo()\&.
.SS "String org\&.jgap\&.distr\&.MasterInfo\&.m_username"
Name of the grid user associated with the IP address 
.PP
Definition at line 34 of file MasterInfo\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
