.TH "org.jgap.gp.function.Modulo.Compatible" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.function.Modulo.Compatible \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Object \fBexecute_mod\fP (Object o)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 93 of file Modulo\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Object org\&.jgap\&.gp\&.function\&.Modulo\&.Compatible\&.execute_mod (Objecto)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
