.TH "org.jgap.impl.TournamentSelectorTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.TournamentSelectorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestConstruct_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestAdd_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEmpty_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEmpty_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEmpty_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestReturnsUniqueChromosomes_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetTournametSize_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetProbability_0\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.16 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBTournamentSelector\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 24 of file TournamentSelectorTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.impl\&.TournamentSelectorTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 29 of file TournamentSelectorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testAdd_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 125 of file TournamentSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.privateAccessor\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testConstruct_0 () throws Exception\fC [inline]\fP"
Valid construction 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 41 of file TournamentSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.privateAccessor\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testConstruct_1 () throws Exception\fC [inline]\fP"
Invalid construction\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 60 of file TournamentSelectorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testConstruct_2 () throws Exception\fC [inline]\fP"
Invalid construction, 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 78 of file TournamentSelectorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testConstruct_3 () throws Exception\fC [inline]\fP"
Invalid construction\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 96 of file TournamentSelectorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testConstruct_4 () throws Exception\fC [inline]\fP"
Invalid construction\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 114 of file TournamentSelectorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testEmpty_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 142 of file TournamentSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.privateAccessor\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testEmpty_1 () throws Exception\fC [inline]\fP"
Test if clear()-method does not affect original \fBPopulation\fP\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 161 of file TournamentSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testEmpty_2 () throws Exception\fC [inline]\fP"
Test if clear()-method does not affect return value\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 183 of file TournamentSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testReturnsUniqueChromosomes_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 492 of file TournamentSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.TournamentSelector\&.returnsUniqueChromosomes()\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testSelect_0 () throws Exception\fC [inline]\fP"
Test if below functionality working without error\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 206 of file TournamentSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testSelect_1 () throws Exception\fC [inline]\fP"
Always select best chromosome for granted if prob is 1\&.0 and index for selected chromosomes in tournament is equal to index of best chromosome\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 230 of file TournamentSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testSelect_2 () throws Exception\fC [inline]\fP"
Always select best chromosome for granted if prob is 1\&.0 and index for selected chromosomes in tournament is equal to index of best chromosome\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 283 of file TournamentSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testSelect_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 327 of file TournamentSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testSelect_4 () throws Exception\fC [inline]\fP"
Ensure that selected \fBChromosome\fP's are not equal to added \fBChromosome\fP's\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 365 of file TournamentSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.privateAccessor\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testSelect_5 () throws Exception\fC [inline]\fP"
Never select best chromosome if prob is 0\&.0d\&. it is not allowed to select probability to 0\&.0d therefor we set it via reflection\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 400 of file TournamentSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.setNestedField()\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testSelect_6 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 436 of file TournamentSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testSetProbability_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 527 of file TournamentSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.impl\&.TournamentSelector\&.getProbability()\&.
.SS "void org\&.jgap\&.impl\&.TournamentSelectorTest\&.testSetTournametSize_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 505 of file TournamentSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.TournamentSelector\&.getTournamentSize()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.TournamentSelectorTest\&.CVS_REVISION = '$Revision: 1\&.16 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 27 of file TournamentSelectorTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
