.TH "org.jgap.DefaultFitnessEvaluatorTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.DefaultFitnessEvaluatorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestIsFitter_0\fP ()"
.br
.ti -1c
.RI "void \fBtestIsFitter_1\fP ()"
.br
.ti -1c
.RI "void \fBtestIsFitter_2\fP ()"
.br
.ti -1c
.RI "void \fBtestIsFitter_3\fP ()"
.br
.ti -1c
.RI "void \fBtestIsFitter_4\fP ()"
.br
.ti -1c
.RI "void \fBtestIsFitter_5\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.7 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Test cases for clasfs \fBDefaultFitnessEvaluator\fP
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 20 of file DefaultFitnessEvaluatorTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.DefaultFitnessEvaluatorTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 26 of file DefaultFitnessEvaluatorTest\&.java\&.
.SS "void org\&.jgap\&.DefaultFitnessEvaluatorTest\&.testIsFitter_0 ()\fC [inline]\fP"

.PP
Definition at line 31 of file DefaultFitnessEvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.FitnessEvaluator\&.isFitter()\&.
.SS "void org\&.jgap\&.DefaultFitnessEvaluatorTest\&.testIsFitter_1 ()\fC [inline]\fP"

.PP
Definition at line 37 of file DefaultFitnessEvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.FitnessEvaluator\&.isFitter()\&.
.SS "void org\&.jgap\&.DefaultFitnessEvaluatorTest\&.testIsFitter_2 ()\fC [inline]\fP"

.PP
Definition at line 43 of file DefaultFitnessEvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.FitnessEvaluator\&.isFitter()\&.
.SS "void org\&.jgap\&.DefaultFitnessEvaluatorTest\&.testIsFitter_3 ()\fC [inline]\fP"

.PP
Definition at line 49 of file DefaultFitnessEvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.FitnessEvaluator\&.isFitter()\&.
.SS "void org\&.jgap\&.DefaultFitnessEvaluatorTest\&.testIsFitter_4 ()\fC [inline]\fP"

.PP
Definition at line 54 of file DefaultFitnessEvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.FitnessEvaluator\&.isFitter()\&.
.SS "void org\&.jgap\&.DefaultFitnessEvaluatorTest\&.testIsFitter_5 ()\fC [inline]\fP"

.PP
Definition at line 59 of file DefaultFitnessEvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.FitnessEvaluator\&.isFitter()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.DefaultFitnessEvaluatorTest\&.CVS_REVISION = '$Revision: 1\&.7 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 24 of file DefaultFitnessEvaluatorTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
