.TH "org.jgap.impl.CompositeGeneTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.CompositeGeneTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGeneConstraintChecker\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestCompareTo_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestAddGene_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestAddGene_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestAddGene_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestAddGene_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestAddGene_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestAddGene_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestAddGene_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestAddGene_7\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestToString_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestToString_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetAllele_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetAllele_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetAllele_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_4_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_5_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_7\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_8\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestNewGene_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentPresentation_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentPresentation_0_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentPresentation_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentPresentation_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentPresentation_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentPresentation_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentPresentation_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentPresentation_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestPersistentPresentation_7\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestRemoveGeneByIdentity_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestRemoveGeneByIdentity_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCleanup_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCleanup_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetConstraintChecker_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetToRandomValue_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetEnergy_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetEnergy_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_3_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestApplyMutation_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetAllele_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestHashCode_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetGenes_1\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.52 $'"
.br
.ti -1c
.RI "static int \fBcleanedUp\fP = 0"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBCompositeGene\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 22 of file CompositeGeneTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.impl\&.CompositeGeneTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 29 of file CompositeGeneTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testAddGene_0 () throws Exception\fC [inline]\fP"
Ensures that a \fBCompositeGene\fP may be added to a \fBCompositeGene\fP
.PP
\fBAuthor:\fP
.RS 4
Audrius Meskauskas 
.PP
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 91 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.CompositeGene\&.size()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testAddGene_1 () throws Exception\fC [inline]\fP"

.PP
Definition at line 98 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.CompositeGene\&.size()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testAddGene_2 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 125 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.impl\&.CompositeGene\&.getGeneTypeAllowed(), and org\&.jgap\&.impl\&.CompositeGene\&.size()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testAddGene_3 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 139 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testAddGene_4 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 157 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.CompositeGene\&.size()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testAddGene_5 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 170 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testAddGene_6 () throws Exception\fC [inline]\fP"
Adding two different initial genes with strict parameter set is not allowed\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 191 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testAddGene_7 () throws Exception\fC [inline]\fP"
Adding an initial \fBCompositeGene\fP twice should be possible, if they are two newly created instances\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 212 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testApplyMutation_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 1089 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testCleanup_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 803 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.CompositeGeneTest\&.cleanedUp, org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.CompositeGene\&.size()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testCleanup_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 830 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.CompositeGene\&.size()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testCompareTo_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 947 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.CompositeGene\&.compareTo(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testCompareTo_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 967 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.CompositeGene\&.compareTo(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testCompareTo_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 985 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.CompositeGene\&.compareTo(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testCompareTo_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 1004 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testCompareTo_3_2 () throws Exception\fC [inline]\fP"

.PP
Definition at line 1015 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.CompositeGene\&.compareTo(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testCompareTo_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 39 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.CompositeGene\&.compareTo(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testCompareTo_5 () throws Exception\fC [inline]\fP"
Using application data\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 1037 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.CompositeGene\&.compareTo(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testCompareTo_6 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 1071 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.CompositeGene\&.compareTo(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testConstruct_0 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 63 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.CompositeGene\&.getGeneTypeAllowed()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testConstruct_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.1 
.RE
.PP

.PP
Definition at line 76 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testEquals_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 287 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testEquals_1 () throws Exception\fC [inline]\fP"

.PP
Definition at line 295 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testEquals_2 () throws Exception\fC [inline]\fP"

.PP
Definition at line 301 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testEquals_3 () throws Exception\fC [inline]\fP"

.PP
Definition at line 307 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testEquals_4_2 () throws Exception\fC [inline]\fP"
Tests that no NullPointerException arises\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 320 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testEquals_5 () throws Exception\fC [inline]\fP"

.PP
Definition at line 332 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.equals()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testEquals_5_2 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 349 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.equals()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testEquals_6 () throws Exception\fC [inline]\fP"

.PP
Definition at line 362 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testEquals_7 () throws Exception\fC [inline]\fP"

.PP
Definition at line 374 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testEquals_8 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 392 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testGetAllele_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 250 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testGetAllele_1 () throws Exception\fC [inline]\fP"

.PP
Definition at line 257 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.CompositeGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testGetAllele_2 () throws Exception\fC [inline]\fP"

.PP
Definition at line 270 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.CompositeGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testGetAllele_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 1108 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.CompositeGene\&.getInternalValue()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testGetGenes_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2\&.2 
.RE
.PP

.PP
Definition at line 1151 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.impl\&.CompositeGene\&.geneAt(), org\&.jgap\&.impl\&.CompositeGene\&.getGenes(), and org\&.jgap\&.impl\&.CompositeGene\&.size()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testHashCode_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 1120 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.CompositeGene\&.hashCode()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testNewGene_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 501 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.BaseGene\&.equals(), and org\&.jgap\&.BaseGene\&.newGene()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testPersistentPresentation_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 525 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testPersistentPresentation_0_2 () throws Exception\fC [inline]\fP"
Use special characters in alphabet\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 558 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testPersistentPresentation_1 () throws Exception\fC [inline]\fP"
Test a nested persistent representation, including strings\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Audrius Meskauskas 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 586 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.impl\&.CompositeGene\&.geneAt(), and org\&.jgap\&.BaseGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testPersistentPresentation_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 647 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.CompositeGene\&.size()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testPersistentPresentation_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 661 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testPersistentPresentation_4 () throws Exception\fC [inline]\fP"
Invalid \fBGene\fP class\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 683 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testPersistentPresentation_5 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 704 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testPersistentPresentation_6 () throws Exception\fC [inline]\fP"
No closing tag\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 724 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testPersistentPresentation_7 () throws Exception\fC [inline]\fP"
Empty representation\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 746 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.CompositeGene\&.size()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testRemoveGeneByIdentity_0 () throws Exception\fC [inline]\fP"
Tests if removal from empty list returns false no matter what to remove\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 771 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.CompositeGene\&.removeGeneByIdentity()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testRemoveGeneByIdentity_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 785 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.impl\&.CompositeGene\&.removeGeneByIdentity(), and org\&.jgap\&.impl\&.CompositeGene\&.size()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testSetAllele_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 406 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testSetAllele_1 () throws Exception\fC [inline]\fP"

.PP
Definition at line 418 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testSetAllele_2 () throws Exception\fC [inline]\fP"
Set Allele to empty Vector, no exception should occur\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 435 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testSetAllele_3 () throws Exception\fC [inline]\fP"

.PP
Definition at line 441 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testSetAllele_4 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 459 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.BaseGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testSetAllele_5 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 483 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.BaseGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testSetConstraintChecker_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 844 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getConstraintChecker()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testSetEnergy_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 915 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.BaseGene\&.getEnergy()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testSetEnergy_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 928 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.BaseGene\&.getEnergy()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testSetToRandomValue_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 864 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testSetToRandomValue_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 883 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.impl\&.DoubleGene\&.doubleValue()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testSetToRandomValue_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 899 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.impl\&.DoubleGene\&.doubleValue()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testToString_0 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 224 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.CompositeGene\&.toString()\&.
.SS "void org\&.jgap\&.impl\&.CompositeGeneTest\&.testToString_1 () throws Exception\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 244 of file CompositeGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.CompositeGene\&.toString()\&.
.SH "Member Data Documentation"
.PP 
.SS "int org\&.jgap\&.impl\&.CompositeGeneTest\&.cleanedUp = 0\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 27 of file CompositeGeneTest\&.java\&.
.PP
Referenced by org\&.jgap\&.impl\&.CompositeGeneTest\&.testCleanup_0()\&.
.SS "final String org\&.jgap\&.impl\&.CompositeGeneTest\&.CVS_REVISION = '$Revision: 1\&.52 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file CompositeGeneTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
