.TH "org.jgap.data.config.Configurable" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.data.config.Configurable \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.4 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
This interface must be implemented for any class to be \fBConfigurable\fP\&.
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.PP
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 19 of file Configurable\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.data\&.config\&.Configurable\&.CVS_REVISION = '$Revision: 1\&.4 $'\fC [static]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 21 of file Configurable\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
