.TH "org.jgap.gui.MockConfigInfoForTesting" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gui.MockConfigInfoForTesting \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits IConfigInfo\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMockConfigInfoForTesting\fP ()"
.br
.ti -1c
.RI "ConfigData \fBgetConfigData\fP ()"
.br
.ti -1c
.RI "String \fBgetFileName\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "ConfigData \fBm_conData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A Mock implementation of IConfigInfo to test the proper generation of a Config File\&.
.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 23 of file MockConfigInfoForTesting\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.gui\&.MockConfigInfoForTesting\&.MockConfigInfoForTesting ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.3 
.RE
.PP

.PP
Definition at line 34 of file MockConfigInfoForTesting\&.java\&.
.PP
References org\&.jgap\&.gui\&.MockConfigInfoForTesting\&.m_conData\&.
.SH "Member Function Documentation"
.PP 
.SS "ConfigData org\&.jgap\&.gui\&.MockConfigInfoForTesting\&.getConfigData ()\fC [inline]\fP"

.PP
Definition at line 55 of file MockConfigInfoForTesting\&.java\&.
.PP
References org\&.jgap\&.gui\&.MockConfigInfoForTesting\&.m_conData\&.
.SS "String org\&.jgap\&.gui\&.MockConfigInfoForTesting\&.getFileName ()\fC [inline]\fP"
Get the config file to write to\&. 
.PP
\fBReturns:\fP
.RS 4
the config file name to write to 
.RE
.PP

.PP
Definition at line 63 of file MockConfigInfoForTesting\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "ConfigData org\&.jgap\&.gui\&.MockConfigInfoForTesting\&.m_conData\fC [private]\fP"

.PP
Definition at line 28 of file MockConfigInfoForTesting\&.java\&.
.PP
Referenced by org\&.jgap\&.gui\&.MockConfigInfoForTesting\&.getConfigData(), and org\&.jgap\&.gui\&.MockConfigInfoForTesting\&.MockConfigInfoForTesting()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
