.TH "org.jgap.data" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.data \- 
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBconfig\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataElement\fP"
.br
.ti -1c
.RI "class \fBDataElementList\fP"
.br
.ti -1c
.RI "class \fBDataElementsDocument\fP"
.br
.ti -1c
.RI "class \fBDataTreeBuilder\fP"
.br
.ti -1c
.RI "class \fBDocumentBuilderBase\fP"
.br
.ti -1c
.RI "interface \fBIDataCreators\fP"
.br
.ti -1c
.RI "interface \fBIDataElement\fP"
.br
.ti -1c
.RI "interface \fBIDataElementList\fP"
.br
.ti -1c
.RI "class \fBAllDataTests\fP"
.br
.ti -1c
.RI "class \fBDataElementsDocumentTest\fP"
.br
.ti -1c
.RI "class \fBDataElementTest\fP"
.br
.ti -1c
.RI "class \fBDataTreeBuilderTest\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
