.TH "org.jgap.distr.grid.request.Status" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.grid.request.Status \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Serializable\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcode\fP"
.br
.ti -1c
.RI "String \fBdescription\fP"
.br
.ti -1c
.RI "byte[] \fBbuffer\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds status information of a request\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 19 of file Status\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "byte [] org\&.jgap\&.distr\&.grid\&.request\&.Status\&.buffer"

.PP
Definition at line 28 of file Status\&.java\&.
.SS "int org\&.jgap\&.distr\&.grid\&.request\&.Status\&.code"

.PP
Definition at line 24 of file Status\&.java\&.
.SS "final String org\&.jgap\&.distr\&.grid\&.request\&.Status\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 22 of file Status\&.java\&.
.SS "String org\&.jgap\&.distr\&.grid\&.request\&.Status\&.description"

.PP
Definition at line 26 of file Status\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
