.TH "org.jgap.gp.impl.GPPopulationTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.impl.GPPopulationTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.gp\&.GPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtestConstruct_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCreate_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCreate_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCreate_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCreate_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSerialize_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSort_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetPrototype_0\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.5 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBGPPopulation\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 25 of file GPPopulationTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.gp\&.impl\&.GPPopulationTest\&.setUp ()\fC [inline]\fP"

.PP
Definition at line 35 of file GPPopulationTest\&.java\&.
.SS "static Test org\&.jgap\&.gp\&.impl\&.GPPopulationTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 30 of file GPPopulationTest\&.java\&.
.SS "void org\&.jgap\&.gp\&.impl\&.GPPopulationTest\&.testConstruct_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 45 of file GPPopulationTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.gp\&.impl\&.GPPopulation\&.getPopSize(), org\&.jgap\&.gp\&.GPTestCase\&.m_gpconf, and org\&.jgap\&.gp\&.impl\&.GPPopulation\&.size()\&.
.SS "void org\&.jgap\&.gp\&.impl\&.GPPopulationTest\&.testCreate_0 () throws Exception\fC [inline]\fP"
Create population with no nodes available\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 60 of file GPPopulationTest\&.java\&.
.PP
References org\&.jgap\&.gp\&.GPTestCase\&.m_gpconf\&.
.SS "void org\&.jgap\&.gp\&.impl\&.GPPopulationTest\&.testCreate_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
adapt 
.RE
.PP

.PP
Definition at line 85 of file GPPopulationTest\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.IntegerClass, and org\&.jgap\&.gp\&.GPTestCase\&.m_gpconf\&.
.SS "void org\&.jgap\&.gp\&.impl\&.GPPopulationTest\&.testCreate_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
adapt 
.RE
.PP

.PP
Definition at line 112 of file GPPopulationTest\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.IntegerClass, and org\&.jgap\&.gp\&.GPTestCase\&.m_gpconf\&.
.SS "void org\&.jgap\&.gp\&.impl\&.GPPopulationTest\&.testCreate_3 () throws Exception\fC [inline]\fP"
Given nodeset doesn't allow to build a valid program\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 146 of file GPPopulationTest\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.IntegerClass, and org\&.jgap\&.gp\&.GPTestCase\&.m_gpconf\&.
.SS "void org\&.jgap\&.gp\&.impl\&.GPPopulationTest\&.testSerialize_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 175 of file GPPopulationTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.doSerialize(), and org\&.jgap\&.gp\&.GPTestCase\&.m_gpconf\&.
.SS "void org\&.jgap\&.gp\&.impl\&.GPPopulationTest\&.testSetPrototype_0 () throws Exception\fC [inline]\fP"

.PP
\fBTodo\fP
.RS 4
assert that prototype is only set automatically if none is preset 
.RE
.PP

.PP
Definition at line 210 of file GPPopulationTest\&.java\&.
.SS "void org\&.jgap\&.gp\&.impl\&.GPPopulationTest\&.testSort_0 () throws Exception\fC [inline]\fP"
Sorting with population having null programs, which is allowed\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 198 of file GPPopulationTest\&.java\&.
.PP
References org\&.jgap\&.gp\&.GPTestCase\&.m_gpconf\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.gp\&.impl\&.GPPopulationTest\&.CVS_REVISION = '$Revision: 1\&.5 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 28 of file GPPopulationTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
