.TH "org.jgap.distr.WorkerListener" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.WorkerListener \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBlisten\fP ()  throws IOException"
.br
.ti -1c
.RI "abstract void \fBstop\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.5 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a listener for requests from workers to the master\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 20 of file WorkerListener\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract void org\&.jgap\&.distr\&.WorkerListener\&.listen () throws IOException\fC [pure virtual]\fP"
Listens to a request\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIIOException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.SS "abstract void org\&.jgap\&.distr\&.WorkerListener\&.stop ()\fC [pure virtual]\fP"
Stops the listener\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.WorkerListener\&.CVS_REVISION = '$Revision: 1\&.5 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 22 of file WorkerListener\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
