.TH "org.jgap.impl.DefaultInitializer" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.DefaultInitializer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.IInitializer\fP, \fBorg\&.jgap\&.util\&.ICloneable\fP, and Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBisHandlerFor\fP (final Object a_obj, final Class a_class)"
.br
.ti -1c
.RI "Object \fBperform\fP (final Object a_obj, final Class a_class, final Object a_params)  throws Exception "
.br
.ti -1c
.RI "Object \fBclone\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.10 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Default implementation for initializing Chromosomes\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 23 of file DefaultInitializer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Object org\&.jgap\&.impl\&.DefaultInitializer\&.clone ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
deep clone of this instance
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.util\&.ICloneable\fP\&.
.PP
Definition at line 63 of file DefaultInitializer\&.java\&.
.SS "boolean org\&.jgap\&.impl\&.DefaultInitializer\&.isHandlerFor (final Objecta_obj, final Classa_class)\fC [inline]\fP"

.PP
Definition at line 28 of file DefaultInitializer\&.java\&.
.SS "Object org\&.jgap\&.impl\&.DefaultInitializer\&.perform (final Objecta_obj, final Classa_class, final Objecta_params) throws Exception\fC [inline]\fP"

.PP
Definition at line 43 of file DefaultInitializer\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.DefaultInitializer\&.CVS_REVISION = '$Revision: 1\&.10 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file DefaultInitializer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
