.TH "org.jgap.distr.grid.gp.IClientEvolveStrategyGP" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.grid.gp.IClientEvolveStrategyGP \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP (\fBIGridClientMediator\fP a_gc, \fBGPConfiguration\fP a_config, \fBIClientFeedbackGP\fP a_clientFeedback)  throws Exception"
.br
.ti -1c
.RI "\fBJGAPRequestGP\fP[] \fBgenerateWorkRequests\fP (\fBJGAPRequestGP\fP m_workReq, \fBIRequestSplitStrategyGP\fP m_splitStrategy, Object a_genericData)  throws Exception"
.br
.ti -1c
.RI "void \fBresultReceived\fP (\fBJGAPResultGP\fP a_result)  throws Exception"
.br
.ti -1c
.RI "boolean \fBisEvolutionFinished\fP (int a_evolutionsDone)"
.br
.ti -1c
.RI "void \fBonFinished\fP ()"
.br
.ti -1c
.RI "void \fBafterWorkRequestsSent\fP ()  throws Exception"
.br
.ti -1c
.RI "void \fBevolve\fP ()  throws Exception"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.4 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for defining a strategy that controls how a client evolves generations of GP's\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 23 of file IClientEvolveStrategyGP\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.distr\&.grid\&.gp\&.IClientEvolveStrategyGP\&.afterWorkRequestsSent () throws Exception"

.SS "void org\&.jgap\&.distr\&.grid\&.gp\&.IClientEvolveStrategyGP\&.evolve () throws Exception"

.SS "\fBJGAPRequestGP\fP [] org\&.jgap\&.distr\&.grid\&.gp\&.IClientEvolveStrategyGP\&.generateWorkRequests (\fBJGAPRequestGP\fPm_workReq, \fBIRequestSplitStrategyGP\fPm_splitStrategy, Objecta_genericData) throws Exception"

.SS "void org\&.jgap\&.distr\&.grid\&.gp\&.IClientEvolveStrategyGP\&.initialize (\fBIGridClientMediator\fPa_gc, \fBGPConfiguration\fPa_config, \fBIClientFeedbackGP\fPa_clientFeedback) throws Exception"

.SS "boolean org\&.jgap\&.distr\&.grid\&.gp\&.IClientEvolveStrategyGP\&.isEvolutionFinished (inta_evolutionsDone)"

.SS "void org\&.jgap\&.distr\&.grid\&.gp\&.IClientEvolveStrategyGP\&.onFinished ()"

.SS "void org\&.jgap\&.distr\&.grid\&.gp\&.IClientEvolveStrategyGP\&.resultReceived (\fBJGAPResultGP\fPa_result) throws Exception"

.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.grid\&.gp\&.IClientEvolveStrategyGP\&.CVS_REVISION = '$Revision: 1\&.4 $'\fC [static]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file IClientEvolveStrategyGP\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
