.TH "org.jgap.gp.function.GreaterThanTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.function.GreaterThanTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.gp\&.GPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestConstruct_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestClone_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestClone_1\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.1 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBGreaterThan\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Frank Pape 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.3 
.RE
.PP

.PP
Definition at line 22 of file GreaterThanTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.gp\&.function\&.GreaterThanTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 27 of file GreaterThanTest\&.java\&.
.SS "void org\&.jgap\&.gp\&.function\&.GreaterThanTest\&.testClone_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Frank Pape 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.3 
.RE
.PP

.PP
Definition at line 78 of file GreaterThanTest\&.java\&.
.SS "void org\&.jgap\&.gp\&.function\&.GreaterThanTest\&.testClone_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Frank Pape 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.3 
.RE
.PP

.PP
Definition at line 99 of file GreaterThanTest\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.getArity()\&.
.SS "void org\&.jgap\&.gp\&.function\&.GreaterThanTest\&.testConstruct_0 () throws Exception\fC [inline]\fP"
Following should be possible without exception\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Frank Pape 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.3 
.RE
.PP

.PP
Definition at line 40 of file GreaterThanTest\&.java\&.
.PP
References org\&.jgap\&.gp\&.GPTestCase\&.m_gpconf\&.
.SS "void org\&.jgap\&.gp\&.function\&.GreaterThanTest\&.testEquals_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Frank Pape 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4\&.3 
.RE
.PP

.PP
Definition at line 63 of file GreaterThanTest\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.equals()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.gp\&.function\&.GreaterThanTest\&.CVS_REVISION = '$Revision: 1\&.1 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file GreaterThanTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
