.TH "org.jgap.NaturalSelector.FitnessValueComparator" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.NaturalSelector.FitnessValueComparator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Comparator, and Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBcompare\fP (Object first, Object second)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Comparator regarding only the fitness value\&. Best fitness value will be on first position of resulting sorted list
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 89 of file NaturalSelector\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int org\&.jgap\&.NaturalSelector\&.FitnessValueComparator\&.compare (Objectfirst, Objectsecond)\fC [inline]\fP"

.PP
Definition at line 91 of file NaturalSelector\&.java\&.
.PP
References org\&.jgap\&.NaturalSelector\&.getConfiguration()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
