.TH "org.jgap.gp.function.ForLoop" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.function.ForLoop \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.gp\&.CommandGene\fP, and \fBorg\&.jgap\&.util\&.ICloneable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForLoop\fP (final GPConfiguration a_conf, Class a_typeVar, int a_maxLoop)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBForLoop\fP (final GPConfiguration a_conf, Class a_typeVar, int a_startIndex, int a_maxLoop)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBForLoop\fP (final GPConfiguration a_conf, Class a_typeVar, int a_startIndex, int a_maxLoop, String a_varName)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBForLoop\fP (final GPConfiguration a_conf, Class a_typeVar, int a_startIndex, int a_endIndex, int a_increment, String a_varName)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBForLoop\fP (final GPConfiguration a_conf, Class a_typeVar, int a_startIndex, int a_endIndex, int a_increment, String a_varName, int a_subReturnType, int a_subChildType)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "Object \fBexecute_object\fP (ProgramChromosome c, int n, Object[] args)"
.br
.ti -1c
.RI "void \fBexecute_void\fP (ProgramChromosome c, int n, Object[] args)"
.br
.ti -1c
.RI "boolean \fBisValid\fP (ProgramChromosome a_program)"
.br
.ti -1c
.RI "Class \fBgetChildType\fP (\fBIGPProgram\fP a_ind, int a_chromNum)"
.br
.ti -1c
.RI "String \fBgetVarName\fP ()"
.br
.ti -1c
.RI "int \fBcompareTo\fP (Object a_other)"
.br
.ti -1c
.RI "boolean \fBequals\fP (Object a_other)"
.br
.ti -1c
.RI "String \fBgetCounterMemoryName\fP ()"
.br
.ti -1c
.RI "Object \fBclone\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Class \fBm_typeVar\fP"
.br
.ti -1c
.RI "int \fBm_startIndex\fP"
.br
.ti -1c
.RI "int \fBm_endIndex\fP"
.br
.ti -1c
.RI "int \fBm_increment\fP"
.br
.ti -1c
.RI "int \fBm_maxLoop\fP"
.br
.ti -1c
.RI "String \fBm_memory_name_int\fP"
.br
.ti -1c
.RI "String \fBm_varName\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.20 $'"
.br
.ti -1c
.RI "static String \fBINTERNAL_COUNTER_STORAGE\fP = 'FORLOOPSTORAGE_INT'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The for-loop\&. You can preset the start index and the end index\&. \fBIf\fP the latter is not given, it is dynamically computed from a child\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 25 of file ForLoop\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.gp\&.function\&.ForLoop\&.ForLoop (final GPConfigurationa_conf, Classa_typeVar, inta_maxLoop) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_conf\fP the configuration to use 
.br
\fIa_typeVar\fP Class of the loop counter terminakl (e\&.g\&. IntegerClass) 
.br
\fIa_maxLoop\fP the maximum number of loops to perform 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBInvalidConfigurationException\fP\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 57 of file ForLoop\&.java\&.
.PP
Referenced by org\&.jgap\&.gp\&.function\&.ForLoop\&.clone(), org\&.jgap\&.gp\&.function\&.ForLoop\&.compareTo(), and org\&.jgap\&.gp\&.function\&.ForLoop\&.equals()\&.
.SS "org\&.jgap\&.gp\&.function\&.ForLoop\&.ForLoop (final GPConfigurationa_conf, Classa_typeVar, inta_startIndex, inta_maxLoop) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"
Constructor allowing to preset the starting index of the loop\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_conf\fP the configuration to use 
.br
\fIa_typeVar\fP Class of the loop counter terminakl (e\&.g\&. IntegerClass) 
.br
\fIa_startIndex\fP index to start the loop with (normally 0) 
.br
\fIa_maxLoop\fP the maximum number of loops to perform 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBInvalidConfigurationException\fP\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 74 of file ForLoop\&.java\&.
.SS "org\&.jgap\&.gp\&.function\&.ForLoop\&.ForLoop (final GPConfigurationa_conf, Classa_typeVar, inta_startIndex, inta_maxLoop, Stringa_varName) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 80 of file ForLoop\&.java\&.
.PP
References org\&.jgap\&.gp\&.function\&.ForLoop\&.init(), org\&.jgap\&.gp\&.function\&.ForLoop\&.m_endIndex, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_increment, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_maxLoop, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_startIndex, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_typeVar, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_varName, and org\&.jgap\&.gp\&.CommandGene\&.VoidClass\&.
.SS "org\&.jgap\&.gp\&.function\&.ForLoop\&.ForLoop (final GPConfigurationa_conf, Classa_typeVar, inta_startIndex, inta_endIndex, inta_increment, Stringa_varName) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"
Constructor allowing to preset the starting and the ending index of the loop\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_conf\fP the configuration to use 
.br
\fIa_typeVar\fP Class of the loop counter terminal (e\&.g\&. IntegerClass) 
.br
\fIa_startIndex\fP index to start the loop with 
.br
\fIa_endIndex\fP index to end the loop with 
.br
\fIa_increment\fP the maximum number of loops to perform 
.br
\fIa_varName\fP informal textual name of the loop counter variable 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBInvalidConfigurationException\fP\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 108 of file ForLoop\&.java\&.
.SS "org\&.jgap\&.gp\&.function\&.ForLoop\&.ForLoop (final GPConfigurationa_conf, Classa_typeVar, inta_startIndex, inta_endIndex, inta_increment, Stringa_varName, inta_subReturnType, inta_subChildType) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 116 of file ForLoop\&.java\&.
.PP
References org\&.jgap\&.gp\&.function\&.ForLoop\&.init(), org\&.jgap\&.gp\&.function\&.ForLoop\&.m_endIndex, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_increment, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_startIndex, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_typeVar, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_varName, and org\&.jgap\&.gp\&.CommandGene\&.VoidClass\&.
.SH "Member Function Documentation"
.PP 
.SS "Object org\&.jgap\&.gp\&.function\&.ForLoop\&.clone ()\fC [inline]\fP"
Clones the object\&. Simple and straight forward implementation here\&.
.PP
\fBReturns:\fP
.RS 4
cloned instance of this object
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.util\&.ICloneable\fP\&.
.PP
Definition at line 329 of file ForLoop\&.java\&.
.PP
References org\&.jgap\&.gp\&.function\&.ForLoop\&.ForLoop(), org\&.jgap\&.gp\&.CommandGene\&.getArity(), org\&.jgap\&.gp\&.CommandGene\&.getGPConfiguration(), org\&.jgap\&.gp\&.CommandGene\&.getSubChildType(), org\&.jgap\&.gp\&.CommandGene\&.getSubReturnType(), org\&.jgap\&.gp\&.function\&.ForLoop\&.m_endIndex, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_increment, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_maxLoop, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_startIndex, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_typeVar, and org\&.jgap\&.gp\&.function\&.ForLoop\&.m_varName\&.
.SS "int org\&.jgap\&.gp\&.function\&.ForLoop\&.compareTo (Objecta_other)\fC [inline]\fP"
The compareTo-method\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_other\fP the other object to compare 
.RE
.PP
\fBReturns:\fP
.RS 4
-1, 0, 1
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 271 of file ForLoop\&.java\&.
.PP
References org\&.jgap\&.gp\&.function\&.ForLoop\&.ForLoop(), org\&.jgap\&.gp\&.function\&.ForLoop\&.m_endIndex, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_increment, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_maxLoop, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_startIndex, and org\&.jgap\&.gp\&.function\&.ForLoop\&.m_typeVar\&.
.SS "boolean org\&.jgap\&.gp\&.function\&.ForLoop\&.equals (Objecta_other)\fC [inline]\fP"
The equals-method\&.
.PP
\fBParameters:\fP
.RS 4
\fIa_other\fP the other object to compare 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the objects are seen as equal
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 295 of file ForLoop\&.java\&.
.PP
References org\&.jgap\&.gp\&.function\&.ForLoop\&.ForLoop(), org\&.jgap\&.gp\&.function\&.ForLoop\&.m_endIndex, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_increment, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_maxLoop, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_startIndex, and org\&.jgap\&.gp\&.function\&.ForLoop\&.m_typeVar\&.
.SS "Object org\&.jgap\&.gp\&.function\&.ForLoop\&.execute_object (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 166 of file ForLoop\&.java\&.
.PP
References org\&.jgap\&.gp\&.function\&.ForLoop\&.m_endIndex, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_startIndex, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_varName, and org\&.jgap\&.gp\&.CommandGene\&.size()\&.
.SS "void org\&.jgap\&.gp\&.function\&.ForLoop\&.execute_void (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 184 of file ForLoop\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.DoubleClass, org\&.jgap\&.gp\&.CommandGene\&.FloatClass, org\&.jgap\&.gp\&.CommandGene\&.getGPConfiguration(), org\&.jgap\&.gp\&.CommandGene\&.IntegerClass, org\&.jgap\&.gp\&.function\&.ForLoop\&.INTERNAL_COUNTER_STORAGE, org\&.jgap\&.gp\&.CommandGene\&.LongClass, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_endIndex, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_increment, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_maxLoop, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_startIndex, and org\&.jgap\&.gp\&.function\&.ForLoop\&.m_typeVar\&.
.SS "Class org\&.jgap\&.gp\&.function\&.ForLoop\&.getChildType (\fBIGPProgram\fPa_ind, inta_chromNum)\fC [inline]\fP"

.PP
Definition at line 232 of file ForLoop\&.java\&.
.PP
References org\&.jgap\&.gp\&.function\&.ForLoop\&.m_endIndex, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_typeVar, and org\&.jgap\&.gp\&.CommandGene\&.VoidClass\&.
.SS "String org\&.jgap\&.gp\&.function\&.ForLoop\&.getCounterMemoryName ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
name of the memory cell where the current value of the loop variable is stored
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 317 of file ForLoop\&.java\&.
.PP
References org\&.jgap\&.gp\&.function\&.ForLoop\&.m_memory_name_int\&.
.SS "String org\&.jgap\&.gp\&.function\&.ForLoop\&.getName ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
textual name of this command
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 162 of file ForLoop\&.java\&.
.SS "String org\&.jgap\&.gp\&.function\&.ForLoop\&.getVarName ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
symbolic name of the variable name used in the for header\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4 
.RE
.PP

.PP
Definition at line 258 of file ForLoop\&.java\&.
.PP
References org\&.jgap\&.gp\&.function\&.ForLoop\&.m_varName\&.
.SS "void org\&.jgap\&.gp\&.function\&.ForLoop\&.init ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 129 of file ForLoop\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.getGPConfiguration(), org\&.jgap\&.gp\&.function\&.ForLoop\&.INTERNAL_COUNTER_STORAGE, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_memory_name_int, and org\&.jgap\&.gp\&.function\&.ForLoop\&.m_varName\&.
.PP
Referenced by org\&.jgap\&.gp\&.function\&.ForLoop\&.ForLoop()\&.
.SS "boolean org\&.jgap\&.gp\&.function\&.ForLoop\&.isValid (ProgramChromosomea_program)\fC [inline]\fP"

.PP
Definition at line 228 of file ForLoop\&.java\&.
.SS "String org\&.jgap\&.gp\&.function\&.ForLoop\&.toString ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
the string representation of the command\&. Especially usefull to output a resulting formula in human-readable form\&. 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.gp\&.CommandGene\fP\&.
.PP
Definition at line 138 of file ForLoop\&.java\&.
.PP
References org\&.jgap\&.gp\&.function\&.ForLoop\&.m_endIndex, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_increment, org\&.jgap\&.gp\&.function\&.ForLoop\&.m_startIndex, and org\&.jgap\&.gp\&.function\&.ForLoop\&.m_varName\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.gp\&.function\&.ForLoop\&.CVS_REVISION = '$Revision: 1\&.20 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 28 of file ForLoop\&.java\&.
.SS "String org\&.jgap\&.gp\&.function\&.ForLoop\&.INTERNAL_COUNTER_STORAGE = 'FORLOOPSTORAGE_INT'\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 30 of file ForLoop\&.java\&.
.PP
Referenced by org\&.jgap\&.gp\&.function\&.ForLoop\&.execute_void(), and org\&.jgap\&.gp\&.function\&.ForLoop\&.init()\&.
.SS "int org\&.jgap\&.gp\&.function\&.ForLoop\&.m_endIndex\fC [private]\fP"

.PP
Definition at line 36 of file ForLoop\&.java\&.
.PP
Referenced by org\&.jgap\&.gp\&.function\&.ForLoop\&.clone(), org\&.jgap\&.gp\&.function\&.ForLoop\&.compareTo(), org\&.jgap\&.gp\&.function\&.ForLoop\&.equals(), org\&.jgap\&.gp\&.function\&.ForLoop\&.execute_object(), org\&.jgap\&.gp\&.function\&.ForLoop\&.execute_void(), org\&.jgap\&.gp\&.function\&.ForLoop\&.ForLoop(), org\&.jgap\&.gp\&.function\&.ForLoop\&.getChildType(), and org\&.jgap\&.gp\&.function\&.ForLoop\&.toString()\&.
.SS "int org\&.jgap\&.gp\&.function\&.ForLoop\&.m_increment\fC [private]\fP"

.PP
Definition at line 38 of file ForLoop\&.java\&.
.PP
Referenced by org\&.jgap\&.gp\&.function\&.ForLoop\&.clone(), org\&.jgap\&.gp\&.function\&.ForLoop\&.compareTo(), org\&.jgap\&.gp\&.function\&.ForLoop\&.equals(), org\&.jgap\&.gp\&.function\&.ForLoop\&.execute_void(), org\&.jgap\&.gp\&.function\&.ForLoop\&.ForLoop(), and org\&.jgap\&.gp\&.function\&.ForLoop\&.toString()\&.
.SS "int org\&.jgap\&.gp\&.function\&.ForLoop\&.m_maxLoop\fC [private]\fP"

.PP
Definition at line 40 of file ForLoop\&.java\&.
.PP
Referenced by org\&.jgap\&.gp\&.function\&.ForLoop\&.clone(), org\&.jgap\&.gp\&.function\&.ForLoop\&.compareTo(), org\&.jgap\&.gp\&.function\&.ForLoop\&.equals(), org\&.jgap\&.gp\&.function\&.ForLoop\&.execute_void(), and org\&.jgap\&.gp\&.function\&.ForLoop\&.ForLoop()\&.
.SS "String org\&.jgap\&.gp\&.function\&.ForLoop\&.m_memory_name_int\fC [private]\fP"

.PP
Definition at line 42 of file ForLoop\&.java\&.
.PP
Referenced by org\&.jgap\&.gp\&.function\&.ForLoop\&.getCounterMemoryName(), and org\&.jgap\&.gp\&.function\&.ForLoop\&.init()\&.
.SS "int org\&.jgap\&.gp\&.function\&.ForLoop\&.m_startIndex\fC [private]\fP"

.PP
Definition at line 34 of file ForLoop\&.java\&.
.PP
Referenced by org\&.jgap\&.gp\&.function\&.ForLoop\&.clone(), org\&.jgap\&.gp\&.function\&.ForLoop\&.compareTo(), org\&.jgap\&.gp\&.function\&.ForLoop\&.equals(), org\&.jgap\&.gp\&.function\&.ForLoop\&.execute_object(), org\&.jgap\&.gp\&.function\&.ForLoop\&.execute_void(), org\&.jgap\&.gp\&.function\&.ForLoop\&.ForLoop(), and org\&.jgap\&.gp\&.function\&.ForLoop\&.toString()\&.
.SS "Class org\&.jgap\&.gp\&.function\&.ForLoop\&.m_typeVar\fC [private]\fP"

.PP
Definition at line 32 of file ForLoop\&.java\&.
.PP
Referenced by org\&.jgap\&.gp\&.function\&.ForLoop\&.clone(), org\&.jgap\&.gp\&.function\&.ForLoop\&.compareTo(), org\&.jgap\&.gp\&.function\&.ForLoop\&.equals(), org\&.jgap\&.gp\&.function\&.ForLoop\&.execute_void(), org\&.jgap\&.gp\&.function\&.ForLoop\&.ForLoop(), and org\&.jgap\&.gp\&.function\&.ForLoop\&.getChildType()\&.
.SS "String org\&.jgap\&.gp\&.function\&.ForLoop\&.m_varName\fC [private]\fP"

.PP
Definition at line 44 of file ForLoop\&.java\&.
.PP
Referenced by org\&.jgap\&.gp\&.function\&.ForLoop\&.clone(), org\&.jgap\&.gp\&.function\&.ForLoop\&.execute_object(), org\&.jgap\&.gp\&.function\&.ForLoop\&.ForLoop(), org\&.jgap\&.gp\&.function\&.ForLoop\&.getVarName(), org\&.jgap\&.gp\&.function\&.ForLoop\&.init(), and org\&.jgap\&.gp\&.function\&.ForLoop\&.toString()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
