.TH "org.jgap.supergenes.InstantiableSupergeneForTesting" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.supergenes.InstantiableSupergeneForTesting \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.supergenes\&.AbstractSupergene\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInstantiableSupergeneForTesting\fP (final \fBConfiguration\fP a_config, \fBGene\fP[] a_genes)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBInstantiableSupergeneForTesting\fP (final \fBConfiguration\fP a_config)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBInstantiableSupergeneForTesting\fP ()  throws InvalidConfigurationException "
.br
.ti -1c
.RI "boolean \fBisValid\fP (\fBGene\fP[] a_gene)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.1 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Non-abstract \fBSupergene\fP ued for testing purposes only\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 20 of file InstantiableSupergeneForTesting\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.supergenes\&.InstantiableSupergeneForTesting\&.InstantiableSupergeneForTesting (final \fBConfiguration\fPa_config, \fBGene\fP[]a_genes) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 25 of file InstantiableSupergeneForTesting\&.java\&.
.SS "org\&.jgap\&.supergenes\&.InstantiableSupergeneForTesting\&.InstantiableSupergeneForTesting (final \fBConfiguration\fPa_config) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 31 of file InstantiableSupergeneForTesting\&.java\&.
.SS "org\&.jgap\&.supergenes\&.InstantiableSupergeneForTesting\&.InstantiableSupergeneForTesting () throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 36 of file InstantiableSupergeneForTesting\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean org\&.jgap\&.supergenes\&.InstantiableSupergeneForTesting\&.isValid (\fBGene\fP[]a_gene)\fC [inline]\fP"

.PP
Definition at line 41 of file InstantiableSupergeneForTesting\&.java\&.
.PP
Referenced by org\&.jgap\&.supergenes\&.SupergenePersistentRepresentationTest\&.testIsValid_0()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.supergenes\&.InstantiableSupergeneForTesting\&.CVS_REVISION = '$Revision: 1\&.1 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 23 of file InstantiableSupergeneForTesting\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
