.TH "org.jgap.xml.XMLManagerTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.xml.XMLManagerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtestGetChromosomeFromDocument_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetChromosomeFromDocument_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetChromosomeFromElement_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetChromosomeFromElement_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetGenesFromElement_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetGenesFromElement_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetGenesFromElement_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetGenotypeFromDocument_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetGenotypeFromDocument_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetGenotypeFromElement_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetGenotypeFromElement_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestRepresentChromosomeAsDocument_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestRepresentChromosomeAsElement_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestRepresentGenesAsElement_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestRepresentGenotypeAsDocument_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestRepresentGenotypeAsElement_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestReadFile_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestReadFile_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestWriteFile_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestWriteFile_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestChromosome_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGenotype_0\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBConfiguration\fP \fBm_conf\fP"
.br
.ti -1c
.RI "\fBChromosome\fP \fBm_chrom\fP"
.br
.ti -1c
.RI "\fBChromosome\fP \fBm_supergenechrom\fP"
.br
.ti -1c
.RI "\fBGene\fP[] \fBm_genes\fP"
.br
.ti -1c
.RI "\fBGene\fP[] \fBm_supergenes\fP"
.br
.ti -1c
.RI "\fBGenotype\fP \fBm_genotype\fP"
.br
.ti -1c
.RI "String \fBm_chromosome_tag\fP"
.br
.ti -1c
.RI "String \fBm_genes_tag\fP"
.br
.ti -1c
.RI "String \fBm_genotype_tag\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.20 $'"
.br
.ti -1c
.RI "static final String \fBFILENAME_WRITE\fP = 'GAtestWrite\&.xml'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBXMLManager\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 26 of file XMLManagerTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.setUp ()\fC [inline]\fP"

.PP
Definition at line 54 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.xml\&.XMLManagerTest\&.m_chrom, org\&.jgap\&.xml\&.XMLManagerTest\&.m_chromosome_tag, org\&.jgap\&.xml\&.XMLManagerTest\&.m_conf, org\&.jgap\&.xml\&.XMLManagerTest\&.m_genes, org\&.jgap\&.xml\&.XMLManagerTest\&.m_genes_tag, org\&.jgap\&.xml\&.XMLManagerTest\&.m_genotype, org\&.jgap\&.xml\&.XMLManagerTest\&.m_genotype_tag, org\&.jgap\&.xml\&.XMLManagerTest\&.m_supergenechrom, org\&.jgap\&.xml\&.XMLManagerTest\&.m_supergenes, and org\&.jgap\&.JGAPTestCase\&.privateAccessor\&.
.SS "static Test org\&.jgap\&.xml\&.XMLManagerTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 33 of file XMLManagerTest\&.java\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testChromosome_0 () throws Exception\fC [inline]\fP"
Tests XML capabilities of JGAP\&. Moved from examples\&.simpleBoolean\&.TestXML\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 316 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Configuration\&.PROPERTY_SAMPLE_CHROM_INST\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testGenotype_0 () throws Exception\fC [inline]\fP"
Tests XML capabilities of JGAP\&. Moved from examples\&.simpleBoolean\&.TestXML\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 341 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Configuration\&.PROPERTY_SAMPLE_CHROM_INST\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testGetChromosomeFromDocument_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 85 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.xml\&.XMLManagerTest\&.m_conf\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testGetChromosomeFromDocument_1 () throws Exception\fC [inline]\fP"

.PP
Definition at line 96 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.Chromosome\&.equals(), org\&.jgap\&.xml\&.XMLManagerTest\&.m_chrom, and org\&.jgap\&.xml\&.XMLManagerTest\&.m_conf\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testGetChromosomeFromElement_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 103 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.xml\&.XMLManagerTest\&.m_chrom, and org\&.jgap\&.xml\&.XMLManagerTest\&.m_conf\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testGetChromosomeFromElement_1 () throws Exception\fC [inline]\fP"

.PP
Definition at line 116 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.xml\&.XMLManagerTest\&.m_chrom, and org\&.jgap\&.xml\&.XMLManagerTest\&.m_conf\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenesFromElement_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 124 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.xml\&.XMLManagerTest\&.m_chrom, org\&.jgap\&.xml\&.XMLManagerTest\&.m_conf, org\&.jgap\&.xml\&.XMLManagerTest\&.m_genes, and org\&.jgap\&.xml\&.XMLManagerTest\&.m_genes_tag\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenesFromElement_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 163 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.xml\&.XMLManagerTest\&.m_conf\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenesFromElement_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 144 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.xml\&.XMLManagerTest\&.m_conf, org\&.jgap\&.xml\&.XMLManagerTest\&.m_genes_tag, org\&.jgap\&.xml\&.XMLManagerTest\&.m_supergenechrom, and org\&.jgap\&.xml\&.XMLManagerTest\&.m_supergenes\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenotypeFromDocument_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 174 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.xml\&.XMLManagerTest\&.m_chrom, and org\&.jgap\&.xml\&.XMLManagerTest\&.m_conf\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenotypeFromDocument_1 () throws Exception\fC [inline]\fP"

.PP
Definition at line 186 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.Genotype\&.equals(), org\&.jgap\&.xml\&.XMLManagerTest\&.m_conf, and org\&.jgap\&.xml\&.XMLManagerTest\&.m_genotype\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenotypeFromElement_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 194 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.xml\&.XMLManagerTest\&.m_conf, and org\&.jgap\&.xml\&.XMLManagerTest\&.m_genotype\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenotypeFromElement_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 208 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.xml\&.XMLManagerTest\&.m_conf\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testReadFile_0 () throws Exception\fC [inline]\fP"
Attention: This test generates a console output with Java 5: '[Fatal Error] : -1:-1: Premature end of file\&.' This is OK, but kinda weird and unwanted\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 265 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.xml\&.XMLManagerTest\&.FILENAME_WRITE\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testReadFile_1 () throws Exception\fC [inline]\fP"

.PP
Definition at line 276 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.xml\&.XMLManagerTest\&.FILENAME_WRITE, org\&.jgap\&.xml\&.XMLManagerTest\&.m_conf, and org\&.jgap\&.xml\&.XMLManagerTest\&.m_genotype\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testRepresentChromosomeAsDocument_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 219 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.xml\&.XMLManagerTest\&.m_chrom, and org\&.jgap\&.xml\&.XMLManagerTest\&.m_chromosome_tag\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testRepresentChromosomeAsElement_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 226 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.xml\&.XMLManagerTest\&.m_chrom, and org\&.jgap\&.xml\&.XMLManagerTest\&.m_chromosome_tag\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testRepresentGenesAsElement_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 235 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.xml\&.XMLManagerTest\&.m_chrom, org\&.jgap\&.xml\&.XMLManagerTest\&.m_genes, and org\&.jgap\&.xml\&.XMLManagerTest\&.m_genes_tag\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testRepresentGenotypeAsDocument_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 242 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.xml\&.XMLManagerTest\&.m_genotype, and org\&.jgap\&.xml\&.XMLManagerTest\&.m_genotype_tag\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testRepresentGenotypeAsElement_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 249 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.xml\&.XMLManagerTest\&.m_genotype, and org\&.jgap\&.xml\&.XMLManagerTest\&.m_genotype_tag\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testWriteFile_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 287 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.xml\&.XMLManagerTest\&.FILENAME_WRITE, and org\&.jgap\&.xml\&.XMLManagerTest\&.m_genotype\&.
.SS "void org\&.jgap\&.xml\&.XMLManagerTest\&.testWriteFile_1 () throws Exception\fC [inline]\fP"
Do the same as above test to verify that overriding existing file works\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 300 of file XMLManagerTest\&.java\&.
.PP
References org\&.jgap\&.xml\&.XMLManagerTest\&.FILENAME_WRITE, and org\&.jgap\&.xml\&.XMLManagerTest\&.m_genotype\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.xml\&.XMLManagerTest\&.CVS_REVISION = '$Revision: 1\&.20 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 29 of file XMLManagerTest\&.java\&.
.SS "final String org\&.jgap\&.xml\&.XMLManagerTest\&.FILENAME_WRITE = 'GAtestWrite\&.xml'\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 31 of file XMLManagerTest\&.java\&.
.PP
Referenced by org\&.jgap\&.xml\&.XMLManagerTest\&.testReadFile_0(), org\&.jgap\&.xml\&.XMLManagerTest\&.testReadFile_1(), org\&.jgap\&.xml\&.XMLManagerTest\&.testWriteFile_0(), and org\&.jgap\&.xml\&.XMLManagerTest\&.testWriteFile_1()\&.
.SS "\fBChromosome\fP org\&.jgap\&.xml\&.XMLManagerTest\&.m_chrom\fC [private]\fP"

.PP
Definition at line 40 of file XMLManagerTest\&.java\&.
.PP
Referenced by org\&.jgap\&.xml\&.XMLManagerTest\&.setUp(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetChromosomeFromDocument_1(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetChromosomeFromElement_0(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetChromosomeFromElement_1(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenesFromElement_0(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenotypeFromDocument_0(), org\&.jgap\&.xml\&.XMLManagerTest\&.testRepresentChromosomeAsDocument_0(), org\&.jgap\&.xml\&.XMLManagerTest\&.testRepresentChromosomeAsElement_0(), and org\&.jgap\&.xml\&.XMLManagerTest\&.testRepresentGenesAsElement_0()\&.
.SS "String org\&.jgap\&.xml\&.XMLManagerTest\&.m_chromosome_tag\fC [private]\fP"

.PP
Definition at line 48 of file XMLManagerTest\&.java\&.
.PP
Referenced by org\&.jgap\&.xml\&.XMLManagerTest\&.setUp(), org\&.jgap\&.xml\&.XMLManagerTest\&.testRepresentChromosomeAsDocument_0(), and org\&.jgap\&.xml\&.XMLManagerTest\&.testRepresentChromosomeAsElement_0()\&.
.SS "\fBConfiguration\fP org\&.jgap\&.xml\&.XMLManagerTest\&.m_conf\fC [private]\fP"

.PP
Definition at line 38 of file XMLManagerTest\&.java\&.
.PP
Referenced by org\&.jgap\&.xml\&.XMLManagerTest\&.setUp(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetChromosomeFromDocument_0(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetChromosomeFromDocument_1(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetChromosomeFromElement_0(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetChromosomeFromElement_1(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenesFromElement_0(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenesFromElement_1(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenesFromElement_2(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenotypeFromDocument_0(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenotypeFromDocument_1(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenotypeFromElement_0(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenotypeFromElement_1(), and org\&.jgap\&.xml\&.XMLManagerTest\&.testReadFile_1()\&.
.SS "\fBGene\fP [] org\&.jgap\&.xml\&.XMLManagerTest\&.m_genes\fC [private]\fP"

.PP
Definition at line 43 of file XMLManagerTest\&.java\&.
.PP
Referenced by org\&.jgap\&.xml\&.XMLManagerTest\&.setUp(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenesFromElement_0(), and org\&.jgap\&.xml\&.XMLManagerTest\&.testRepresentGenesAsElement_0()\&.
.SS "String org\&.jgap\&.xml\&.XMLManagerTest\&.m_genes_tag\fC [private]\fP"

.PP
Definition at line 50 of file XMLManagerTest\&.java\&.
.PP
Referenced by org\&.jgap\&.xml\&.XMLManagerTest\&.setUp(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenesFromElement_0(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenesFromElement_2(), and org\&.jgap\&.xml\&.XMLManagerTest\&.testRepresentGenesAsElement_0()\&.
.SS "\fBGenotype\fP org\&.jgap\&.xml\&.XMLManagerTest\&.m_genotype\fC [private]\fP"

.PP
Definition at line 46 of file XMLManagerTest\&.java\&.
.PP
Referenced by org\&.jgap\&.xml\&.XMLManagerTest\&.setUp(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenotypeFromDocument_1(), org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenotypeFromElement_0(), org\&.jgap\&.xml\&.XMLManagerTest\&.testReadFile_1(), org\&.jgap\&.xml\&.XMLManagerTest\&.testRepresentGenotypeAsDocument_0(), org\&.jgap\&.xml\&.XMLManagerTest\&.testRepresentGenotypeAsElement_0(), org\&.jgap\&.xml\&.XMLManagerTest\&.testWriteFile_0(), and org\&.jgap\&.xml\&.XMLManagerTest\&.testWriteFile_1()\&.
.SS "String org\&.jgap\&.xml\&.XMLManagerTest\&.m_genotype_tag\fC [private]\fP"

.PP
Definition at line 52 of file XMLManagerTest\&.java\&.
.PP
Referenced by org\&.jgap\&.xml\&.XMLManagerTest\&.setUp(), org\&.jgap\&.xml\&.XMLManagerTest\&.testRepresentGenotypeAsDocument_0(), and org\&.jgap\&.xml\&.XMLManagerTest\&.testRepresentGenotypeAsElement_0()\&.
.SS "\fBChromosome\fP org\&.jgap\&.xml\&.XMLManagerTest\&.m_supergenechrom\fC [private]\fP"

.PP
Definition at line 41 of file XMLManagerTest\&.java\&.
.PP
Referenced by org\&.jgap\&.xml\&.XMLManagerTest\&.setUp(), and org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenesFromElement_2()\&.
.SS "\fBGene\fP [] org\&.jgap\&.xml\&.XMLManagerTest\&.m_supergenes\fC [private]\fP"

.PP
Definition at line 44 of file XMLManagerTest\&.java\&.
.PP
Referenced by org\&.jgap\&.xml\&.XMLManagerTest\&.setUp(), and org\&.jgap\&.xml\&.XMLManagerTest\&.testGetGenesFromElement_2()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
