.TH "org.jgap.distr" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr \- 
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBgrid\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBreeder\fP"
.br
.ti -1c
.RI "class \fBMeanBuffer\fP"
.br
.ti -1c
.RI "class \fBCulture\fP"
.br
.ti -1c
.RI "class \fBCultureMemoryCell\fP"
.br
.ti -1c
.RI "class \fBDistributedGenotype\fP"
.br
.ti -1c
.RI "interface \fBIPopulationMerger\fP"
.br
.ti -1c
.RI "interface \fBIWorker\fP"
.br
.ti -1c
.RI "class \fBMaster\fP"
.br
.ti -1c
.RI "class \fBMasterInfo\fP"
.br
.ti -1c
.RI "class \fBMasterListener\fP"
.br
.ti -1c
.RI "class \fBProblem\fP"
.br
.ti -1c
.RI "class \fBRequestDispatcher\fP"
.br
.ti -1c
.RI "class \fBWorker\fP"
.br
.ti -1c
.RI "class \fBWorkerCommand\fP"
.br
.ti -1c
.RI "class \fBWorkerListener\fP"
.br
.ti -1c
.RI "class \fBAllDistrTests\fP"
.br
.ti -1c
.RI "class \fBCultureMemoryCellTest\fP"
.br
.ti -1c
.RI "class \fBCultureTest\fP"
.br
.ti -1c
.RI "class \fBProblemTest\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
