.TH "org.jgap.util.LRUCache" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.util.LRUCache \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits LinkedHashMap\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLRUCache\fP (int a_maxExtries)"
.br
.ti -1c
.RI "boolean \fBremoveEldestEntry\fP (Map\&.Entry eldest)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_maxEntries\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file LRUCache\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.util\&.LRUCache\&.LRUCache (inta_maxExtries)\fC [inline]\fP"

.PP
Definition at line 10 of file LRUCache\&.java\&.
.PP
References org\&.jgap\&.util\&.LRUCache\&.m_maxEntries\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean org\&.jgap\&.util\&.LRUCache\&.removeEldestEntry (Map\&.Entryeldest)\fC [inline]\fP"

.PP
Definition at line 15 of file LRUCache\&.java\&.
.PP
References org\&.jgap\&.util\&.LRUCache\&.m_maxEntries\&.
.SH "Member Data Documentation"
.PP 
.SS "int org\&.jgap\&.util\&.LRUCache\&.m_maxEntries\fC [private]\fP"

.PP
Definition at line 8 of file LRUCache\&.java\&.
.PP
Referenced by org\&.jgap\&.util\&.LRUCache\&.LRUCache(), and org\&.jgap\&.util\&.LRUCache\&.removeEldestEntry()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
