.TH "org.jgap.gp.function.Abs" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.function.Abs \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.gp\&.MathCommand\fP, and \fBorg\&.jgap\&.util\&.ICloneable\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBCompatible\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAbs\fP (final GPConfiguration a_conf, Class a_returnType)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "float \fBexecute_float\fP (ProgramChromosome c, int n, Object[] args)"
.br
.ti -1c
.RI "double \fBexecute_double\fP (ProgramChromosome c, int n, Object[] args)"
.br
.ti -1c
.RI "Object \fBexecute_object\fP (ProgramChromosome c, int n, Object[] args)"
.br
.ti -1c
.RI "Object \fBclone\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.3 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Returns the absolute value of a number\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 23 of file Abs\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.gp\&.function\&.Abs\&.Abs (final GPConfigurationa_conf, Classa_returnType) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 28 of file Abs\&.java\&.
.PP
Referenced by org\&.jgap\&.gp\&.function\&.Abs\&.clone()\&.
.SH "Member Function Documentation"
.PP 
.SS "Object org\&.jgap\&.gp\&.function\&.Abs\&.clone ()\fC [inline]\fP"
Clones the object\&. Simple and straight forward implementation here\&.
.PP
\fBReturns:\fP
.RS 4
cloned instance of this object
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.4 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.util\&.ICloneable\fP\&.
.PP
Definition at line 72 of file Abs\&.java\&.
.PP
References org\&.jgap\&.gp\&.function\&.Abs\&.Abs(), org\&.jgap\&.gp\&.CommandGene\&.getGPConfiguration(), and org\&.jgap\&.gp\&.CommandGene\&.getReturnType()\&.
.SS "double org\&.jgap\&.gp\&.function\&.Abs\&.execute_double (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 52 of file Abs\&.java\&.
.SS "float org\&.jgap\&.gp\&.function\&.Abs\&.execute_float (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 47 of file Abs\&.java\&.
.SS "Object org\&.jgap\&.gp\&.function\&.Abs\&.execute_object (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 57 of file Abs\&.java\&.
.SS "String org\&.jgap\&.gp\&.function\&.Abs\&.getName ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
textual name of this command
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 43 of file Abs\&.java\&.
.SS "String org\&.jgap\&.gp\&.function\&.Abs\&.toString ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
the string representation of the command\&. Especially usefull to output a resulting formula in human-readable form\&. 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.gp\&.CommandGene\fP\&.
.PP
Definition at line 33 of file Abs\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.gp\&.function\&.Abs\&.CVS_REVISION = '$Revision: 1\&.3 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file Abs\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
