.TH "org.jgap.data.DataTreeBuilderTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.data.DataTreeBuilderTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtestRepresentGenotypeAsDocument_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestRepresentChromosomeAsDocument_0\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.12 $'"
.br
.ti -1c
.RI "static final int \fBNUM_CHROMS\fP = 5"
.br
.ti -1c
.RI "static final int \fBNUM_GENES\fP = 2"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBDataTreeBuilder\fP class
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.PP
Siddhartha Azad 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 23 of file DataTreeBuilderTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.data\&.DataTreeBuilderTest\&.setUp ()\fC [inline]\fP"

.PP
Definition at line 39 of file DataTreeBuilderTest\&.java\&.
.SS "static Test org\&.jgap\&.data\&.DataTreeBuilderTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 34 of file DataTreeBuilderTest\&.java\&.
.SS "void org\&.jgap\&.data\&.DataTreeBuilderTest\&.testRepresentChromosomeAsDocument_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 112 of file DataTreeBuilderTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.data\&.IDataElementList\&.getLength(), org\&.jgap\&.data\&.IDataElement\&.getTagName(), and org\&.jgap\&.data\&.DataTreeBuilderTest\&.NUM_GENES\&.
.SS "void org\&.jgap\&.data\&.DataTreeBuilderTest\&.testRepresentGenotypeAsDocument_0 () throws Exception\fC [inline]\fP"
Create a \fBGenotype\fP and represent it as a document, and verify that the representation is as expected\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 49 of file DataTreeBuilderTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.data\&.IDataElementList\&.getLength(), org\&.jgap\&.data\&.IDataElement\&.getTagName(), org\&.jgap\&.data\&.DataTreeBuilderTest\&.NUM_CHROMS, and org\&.jgap\&.data\&.DataTreeBuilderTest\&.NUM_GENES\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.data\&.DataTreeBuilderTest\&.CVS_REVISION = '$Revision: 1\&.12 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file DataTreeBuilderTest\&.java\&.
.SS "final int org\&.jgap\&.data\&.DataTreeBuilderTest\&.NUM_CHROMS = 5\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 29 of file DataTreeBuilderTest\&.java\&.
.PP
Referenced by org\&.jgap\&.data\&.DataTreeBuilderTest\&.testRepresentGenotypeAsDocument_0()\&.
.SS "final int org\&.jgap\&.data\&.DataTreeBuilderTest\&.NUM_GENES = 2\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 32 of file DataTreeBuilderTest\&.java\&.
.PP
Referenced by org\&.jgap\&.data\&.DataTreeBuilderTest\&.testRepresentChromosomeAsDocument_0(), and org\&.jgap\&.data\&.DataTreeBuilderTest\&.testRepresentGenotypeAsDocument_0()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
