.TH "org.jgap.distr.grid.wan.RequestInformation" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.grid.wan.RequestInformation \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRequestInformation\fP ()"
.br
.ti -1c
.RI "int \fBgetChunk\fP ()"
.br
.ti -1c
.RI "void \fBsetChunk\fP (int a_chunk)"
.br
.ti -1c
.RI "String \fBgetID\fP ()"
.br
.ti -1c
.RI "void \fBsetID\fP (String a_id)"
.br
.ti -1c
.RI "void \fBsetRequestDate\fP (Date a_date)"
.br
.ti -1c
.RI "Date \fBgetRequestDate\fP ()"
.br
.ti -1c
.RI "void \fBsetDescription\fP (String a_descr)"
.br
.ti -1c
.RI "String \fBgetDescription\fP ()"
.br
.ti -1c
.RI "void \fBsetTitle\fP (String a_title)"
.br
.ti -1c
.RI "String \fBgetTitle\fP ()"
.br
.ti -1c
.RI "int \fBgetPopSize\fP ()"
.br
.ti -1c
.RI "void \fBsetPopSize\fP (int popSize)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMasterInfo\fP \fBrequesterInfo\fP"
.br
.ti -1c
.RI "\fBMasterInfo\fP \fBworkerInfo\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "String \fBm_id\fP"
.br
.ti -1c
.RI "String \fBm_title\fP"
.br
.ti -1c
.RI "Date \fBm_requestDate\fP"
.br
.ti -1c
.RI "String \fBm_description\fP"
.br
.ti -1c
.RI "int \fBm_chunk\fP"
.br
.ti -1c
.RI "int \fBm_popSize\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.1 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Meta-Information about a request\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 22 of file RequestInformation\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.RequestInformation ()\fC [inline]\fP"

.PP
Definition at line 44 of file RequestInformation\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.getChunk ()\fC [inline]\fP"

.PP
Definition at line 47 of file RequestInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_chunk\&.
.SS "String org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.getDescription ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
arbitrary description of the request
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 99 of file RequestInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_description\&.
.SS "String org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.getID ()\fC [inline]\fP"

.PP
Definition at line 55 of file RequestInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_id\&.
.SS "int org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.getPopSize ()\fC [inline]\fP"

.PP
Definition at line 123 of file RequestInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_popSize\&.
.SS "Date org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.getRequestDate ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
the date the request was initialized
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 79 of file RequestInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_requestDate\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.wan\&.WANUtils\&.outputRequestInformation()\&.
.SS "String org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.getTitle ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
the title set
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 119 of file RequestInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_title\&.
.SS "void org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.setChunk (inta_chunk)\fC [inline]\fP"

.PP
Definition at line 51 of file RequestInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_chunk\&.
.SS "void org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.setDescription (Stringa_descr)\fC [inline]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIa_descr\fP arbitrary description of the request
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 89 of file RequestInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_description\&.
.SS "void org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.setID (Stringa_id)\fC [inline]\fP"

.PP
Definition at line 59 of file RequestInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_id\&.
.SS "void org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.setPopSize (intpopSize)\fC [inline]\fP"

.PP
Definition at line 127 of file RequestInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_popSize\&.
.SS "void org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.setRequestDate (Datea_date)\fC [inline]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIa_date\fP date the request was initialized
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 69 of file RequestInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_requestDate\&.
.SS "void org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.setTitle (Stringa_title)\fC [inline]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIa_title\fP the title to set
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 109 of file RequestInformation\&.java\&.
.PP
References org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_title\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.CVS_REVISION = '$Revision: 1\&.1 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 24 of file RequestInformation\&.java\&.
.SS "int org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_chunk\fC [private]\fP"

.PP
Definition at line 40 of file RequestInformation\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.getChunk(), and org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.setChunk()\&.
.SS "String org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_description\fC [private]\fP"

.PP
Definition at line 38 of file RequestInformation\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.getDescription(), and org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.setDescription()\&.
.SS "String org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_id\fC [private]\fP"

.PP
\fBTodo\fP
.RS 4
worker gibt durch Datei an, dass er Request bearbeitet 
.RE
.PP

.PP
Definition at line 32 of file RequestInformation\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.getID(), and org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.setID()\&.
.SS "int org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_popSize\fC [private]\fP"

.PP
Definition at line 42 of file RequestInformation\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.getPopSize(), and org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.setPopSize()\&.
.SS "Date org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_requestDate\fC [private]\fP"

.PP
Definition at line 36 of file RequestInformation\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.getRequestDate(), and org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.setRequestDate()\&.
.SS "String org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.m_title\fC [private]\fP"

.PP
Definition at line 34 of file RequestInformation\&.java\&.
.PP
Referenced by org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.getTitle(), and org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.setTitle()\&.
.SS "\fBMasterInfo\fP org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.requesterInfo"

.PP
Definition at line 26 of file RequestInformation\&.java\&.
.SS "\fBMasterInfo\fP org\&.jgap\&.distr\&.grid\&.wan\&.RequestInformation\&.workerInfo"

.PP
Definition at line 28 of file RequestInformation\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
