.TH "org.jgap.AllTests" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.AllTests \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestSuite\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.17 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Test suite for all test cases\&. Start this class to execute all Tests\&. Required are junit\&.jar and junit-addons_1\&.4\&.jar\&. In here, only test suites will be referenced (see method \fBsuite()\fP)\&. Don't add any test cases to this class!
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 37 of file AllTests\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.AllTests\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 42 of file AllTests\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.AllTests\&.CVS_REVISION = '$Revision: 1\&.17 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 40 of file AllTests\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
