.TH "org.jgap.impl.GaussianRandomGeneratorTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.GaussianRandomGeneratorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestGeneral\fP ()"
.br
.ti -1c
.RI "void \fBtestConstruct_0\fP ()"
.br
.ti -1c
.RI "void \fBtestConstruct_1\fP ()"
.br
.ti -1c
.RI "void \fBtestGetGaussianStdDeviation_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestNextInt_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestNextInt_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestNextInt_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestNextLong_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestNextDouble_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestNextFloat_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSerialize_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSerialize_1\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.18 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBGaussianRandomGenerator\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 23 of file GaussianRandomGeneratorTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.impl\&.GaussianRandomGeneratorTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 28 of file GaussianRandomGeneratorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.GaussianRandomGeneratorTest\&.testConstruct_0 ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 50 of file GaussianRandomGeneratorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.GaussianRandomGeneratorTest\&.testConstruct_1 ()\fC [inline]\fP"

.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 63 of file GaussianRandomGeneratorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.DELTA\&.
.SS "void org\&.jgap\&.impl\&.GaussianRandomGeneratorTest\&.testGeneral ()\fC [inline]\fP"
Check if construction and calculation in general possible 
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 37 of file GaussianRandomGeneratorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.GaussianRandomGeneratorTest\&.testGetGaussianStdDeviation_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
finish 
.RE
.PP

.PP
Definition at line 82 of file GaussianRandomGeneratorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.impl\&.GaussianRandomGenerator\&.getGaussianStdDeviation()\&.
.SS "void org\&.jgap\&.impl\&.GaussianRandomGeneratorTest\&.testNextDouble_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 186 of file GaussianRandomGeneratorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.DELTA\&.
.SS "void org\&.jgap\&.impl\&.GaussianRandomGeneratorTest\&.testNextFloat_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 214 of file GaussianRandomGeneratorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.DELTA\&.
.SS "void org\&.jgap\&.impl\&.GaussianRandomGeneratorTest\&.testNextInt_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 98 of file GaussianRandomGeneratorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.GaussianRandomGeneratorTest\&.testNextInt_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 114 of file GaussianRandomGeneratorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.GaussianRandomGeneratorTest\&.testNextInt_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 138 of file GaussianRandomGeneratorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.GaussianRandomGeneratorTest\&.testNextLong_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 162 of file GaussianRandomGeneratorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.GaussianRandomGeneratorTest\&.testSerialize_0 () throws Exception\fC [inline]\fP"
Tests serializability capabilities with default constructor\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.01 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
fix test as Java 5 uses java\&.util\&.concurrent\&.AtomicLong instead of sun\&.misc\&.AtomicLong 
.RE
.PP

.PP
Definition at line 254 of file GaussianRandomGeneratorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.doSerialize(), and org\&.jgap\&.JGAPTestCase\&.privateAccessor\&.
.SS "void org\&.jgap\&.impl\&.GaussianRandomGeneratorTest\&.testSerialize_1 () throws Exception\fC [inline]\fP"
Tests serializability capabilities with non-default constructor\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.01 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
fix test as Java 5 uses java\&.util\&.concurrent\&.AtomicLong instead of sun\&.misc\&.AtomicLong 
.RE
.PP

.PP
Definition at line 277 of file GaussianRandomGeneratorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.doSerialize(), and org\&.jgap\&.JGAPTestCase\&.privateAccessor\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.GaussianRandomGeneratorTest\&.CVS_REVISION = '$Revision: 1\&.18 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file GaussianRandomGeneratorTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
