.TH "org.jgap.distr.grid.gp.IGPPopulationInitializer" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.grid.gp.IGPPopulationInitializer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBexamples\&.grid\&.mathProblemDistributed\&.GPPopulationInitializer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP (\fBGPConfiguration\fP a_conf, Class[] a_types, Class[][] argTypes, \fBCommandGene\fP[][] a_nodeSets, int a_maxNodes, boolean a_verboseOutput)  throws Exception"
.br
.ti -1c
.RI "\fBGPGenotype\fP \fBexecute\fP ()  throws InvalidConfigurationException"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allows to initialize a GP population right when creating a GPGenotype\&. Is called within constructor of GPGenotype\&.
.PP
See examples\&.grid\&.mathProblemDistrubuted for an example\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.6 
.RE
.PP

.PP
Definition at line 26 of file IGPPopulationInitializer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBGPGenotype\fP org\&.jgap\&.distr\&.grid\&.gp\&.IGPPopulationInitializer\&.execute () throws \fBInvalidConfigurationException\fP"

.PP
Implemented in \fBexamples\&.grid\&.mathProblemDistributed\&.GPPopulationInitializer\fP\&.
.SS "void org\&.jgap\&.distr\&.grid\&.gp\&.IGPPopulationInitializer\&.setUp (\fBGPConfiguration\fPa_conf, Class[]a_types, ClassargTypes[][], \fBCommandGene\fPa_nodeSets[][], inta_maxNodes, booleana_verboseOutput) throws Exception"

.PP
Implemented in \fBexamples\&.grid\&.mathProblemDistributed\&.GPPopulationInitializer\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.distr\&.grid\&.gp\&.IGPPopulationInitializer\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 28 of file IGPPopulationInitializer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
