.TH "org.jgap.impl.RandomFitnessFunction" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.RandomFitnessFunction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.FitnessFunction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandomFitnessFunction\fP ()"
.br
.ti -1c
.RI "double \fBevaluate\fP (\fBIChromosome\fP a_chrom)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Random \fBm_rand\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.7 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Fitness function returning random values\&. Only for testing purposes!
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 23 of file RandomFitnessFunction\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.impl\&.RandomFitnessFunction\&.RandomFitnessFunction ()\fC [inline]\fP"

.PP
Definition at line 31 of file RandomFitnessFunction\&.java\&.
.PP
References org\&.jgap\&.impl\&.RandomFitnessFunction\&.m_rand\&.
.SH "Member Function Documentation"
.PP 
.SS "double org\&.jgap\&.impl\&.RandomFitnessFunction\&.evaluate (\fBIChromosome\fPa_chrom)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIa_chrom\fP ignored: the \fBChromosome\fP to evaluate 
.RE
.PP
\fBReturns:\fP
.RS 4
randomized fitness value 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 (until 1\&.1: return type int) 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.FitnessFunction\fP\&.
.PP
Definition at line 40 of file RandomFitnessFunction\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.RandomFitnessFunction\&.CVS_REVISION = '$Revision: 1\&.7 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 27 of file RandomFitnessFunction\&.java\&.
.SS "Random org\&.jgap\&.impl\&.RandomFitnessFunction\&.m_rand\fC [private]\fP"

.PP
Definition at line 29 of file RandomFitnessFunction\&.java\&.
.PP
Referenced by org\&.jgap\&.impl\&.RandomFitnessFunction\&.RandomFitnessFunction()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
