.TH "org.jgap.impl.NumberGeneTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.NumberGeneTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNumberGeneImpl\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestConstruct_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestToString_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestToString_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetAllele_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetAllele_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetAllele_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestHashCode_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestHashCode_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestHashCode_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetAllele_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestNewGene_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetConstraintChecker_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetEnergy_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetEnergy_1\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.27 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the (abstract) \fBNumberGene\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 24 of file NumberGeneTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.impl\&.NumberGeneTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 29 of file NumberGeneTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testCompareTo_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 342 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testCompareTo_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 360 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testCompareTo_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 380 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testCompareTo_3 () throws Exception\fC [inline]\fP"
Using application data\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 402 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testConstruct_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 40 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testEquals_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 164 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testEquals_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 178 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testEquals_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 190 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testEquals_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 202 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testEquals_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 214 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testEquals_5 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 228 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testGetAllele_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 82 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testGetAllele_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 95 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testGetAllele_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 108 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.Gene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testHashCode_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 121 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testHashCode_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 134 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testHashCode_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 149 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testNewGene_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 319 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.privateAccessor\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testSetAllele_0 () throws Exception\fC [inline]\fP"
Set Allele to null, no exception should occur 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 245 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testSetAllele_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 257 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testSetAllele_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 275 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testSetAllele_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 294 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testSetConstraintChecker_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 420 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.BaseGene\&.getConstraintChecker()\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testSetEnergy_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 439 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.BaseGene\&.getEnergy()\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testSetEnergy_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 451 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.BaseGene\&.getEnergy()\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testToString_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 53 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.BaseGene\&.S_APPLICATION_DATA, and org\&.jgap\&.Gene\&.toString()\&.
.SS "void org\&.jgap\&.impl\&.NumberGeneTest\&.testToString_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 67 of file NumberGeneTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.NumberGeneTest\&.CVS_REVISION = '$Revision: 1\&.27 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 27 of file NumberGeneTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
