.TH "org.jgap.gp.terminal.NOP" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.terminal.NOP \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.gp\&.MathCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNOP\fP (final GPConfiguration a_conf)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBNOP\fP (final GPConfiguration a_conf, int a_subReturnType)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "\fBNOP\fP (final GPConfiguration a_conf, Class a_returnType, int a_subReturnType)  throws InvalidConfigurationException "
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBexecute_void\fP (ProgramChromosome c, int n, Object[] args)"
.br
.ti -1c
.RI "Object \fBexecute_object\fP (ProgramChromosome c, int n, Object[] args)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.9 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
NO Operation\&. Does exactly nothing\&. Useful when a terminal with return type void is needed\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 23 of file NOP\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.gp\&.terminal\&.NOP\&.NOP (final GPConfigurationa_conf) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 28 of file NOP\&.java\&.
.SS "org\&.jgap\&.gp\&.terminal\&.NOP\&.NOP (final GPConfigurationa_conf, inta_subReturnType) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 33 of file NOP\&.java\&.
.PP
References org\&.jgap\&.gp\&.CommandGene\&.VoidClass\&.
.SS "org\&.jgap\&.gp\&.terminal\&.NOP\&.NOP (final GPConfigurationa_conf, Classa_returnType, inta_subReturnType) throws \fBInvalidConfigurationException\fP\fC [inline]\fP"

.PP
Definition at line 38 of file NOP\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Object org\&.jgap\&.gp\&.terminal\&.NOP\&.execute_object (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"
Executes this node as an object\&.
.PP
\fBParameters:\fP
.RS 4
\fIc\fP ignored here 
.br
\fIn\fP ignored here 
.br
\fIargs\fP ignored here 
.RE
.PP
\fBReturns:\fP
.RS 4
nothing but exception 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIUnsupportedOperationException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2\&.1 
.RE
.PP

.PP
Definition at line 76 of file NOP\&.java\&.
.SS "void org\&.jgap\&.gp\&.terminal\&.NOP\&.execute_void (ProgramChromosomec, intn, Object[]args)\fC [inline]\fP"

.PP
Definition at line 58 of file NOP\&.java\&.
.SS "String org\&.jgap\&.gp\&.terminal\&.NOP\&.getName ()\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
textual name of this command
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 54 of file NOP\&.java\&.
.SS "String org\&.jgap\&.gp\&.terminal\&.NOP\&.toString ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
the string representation of the command\&. Especially usefull to output a resulting formula in human-readable form\&. 
.RE
.PP

.PP
Implements \fBorg\&.jgap\&.gp\&.CommandGene\fP\&.
.PP
Definition at line 44 of file NOP\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.gp\&.terminal\&.NOP\&.CVS_REVISION = '$Revision: 1\&.9 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 26 of file NOP\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
