.TH "org.jgap.audit.EvaluatorTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.audit.EvaluatorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtestStoreGenotype_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCalcPerformance_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCalcPerformance_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestGetNumberOfRuns_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCalcPerformance_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestHasNext_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestNext_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValue_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValue_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValue_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetValue_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCalcAvgFitness_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCalcAvgFitness_1\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.14 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBEvaluator\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 22 of file EvaluatorTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.audit\&.EvaluatorTest\&.setUp ()\fC [inline]\fP"

.PP
Definition at line 27 of file EvaluatorTest\&.java\&.
.SS "static Test org\&.jgap\&.audit\&.EvaluatorTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 31 of file EvaluatorTest\&.java\&.
.SS "void org\&.jgap\&.audit\&.EvaluatorTest\&.testCalcAvgFitness_0 () throws Exception\fC [inline]\fP"
Consider one permutation\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.1 
.RE
.PP

.PP
Definition at line 436 of file EvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.DELTA\&.
.SS "void org\&.jgap\&.audit\&.EvaluatorTest\&.testCalcAvgFitness_1 () throws Exception\fC [inline]\fP"
Consider all permutations\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.1 
.RE
.PP

.PP
Definition at line 466 of file EvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.DELTA\&.
.SS "void org\&.jgap\&.audit\&.EvaluatorTest\&.testCalcPerformance_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 72 of file EvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.Population\&.determineFittestChromosome()\&.
.SS "void org\&.jgap\&.audit\&.EvaluatorTest\&.testCalcPerformance_1 () throws Exception\fC [inline]\fP"

.PP
Definition at line 102 of file EvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.DELTA\&.
.SS "void org\&.jgap\&.audit\&.EvaluatorTest\&.testCalcPerformance_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.4 
.RE
.PP

.PP
Definition at line 183 of file EvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.Population\&.determineFittestChromosome()\&.
.SS "void org\&.jgap\&.audit\&.EvaluatorTest\&.testConstruct_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 286 of file EvaluatorTest\&.java\&.
.SS "void org\&.jgap\&.audit\&.EvaluatorTest\&.testConstruct_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 302 of file EvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.audit\&.Evaluator\&.getData()\&.
.SS "void org\&.jgap\&.audit\&.EvaluatorTest\&.testGetNumberOfRuns_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 153 of file EvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.audit\&.Evaluator\&.getNumberOfRuns()\&.
.SS "void org\&.jgap\&.audit\&.EvaluatorTest\&.testHasNext_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 317 of file EvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.audit\&.PermutingConfiguration\&.hasNext()\&.
.SS "void org\&.jgap\&.audit\&.EvaluatorTest\&.testNext_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 331 of file EvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.audit\&.EvaluatorTest\&.testSetValue_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 351 of file EvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.audit\&.Evaluator\&.getValue()\&.
.SS "void org\&.jgap\&.audit\&.EvaluatorTest\&.testSetValue_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 370 of file EvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.audit\&.Evaluator\&.getValue()\&.
.SS "void org\&.jgap\&.audit\&.EvaluatorTest\&.testSetValue_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 390 of file EvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.audit\&.Evaluator\&.getValue()\&.
.SS "void org\&.jgap\&.audit\&.EvaluatorTest\&.testSetValue_3 () throws Exception\fC [inline]\fP"
Test for overwriting an already set value\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 414 of file EvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.audit\&.Evaluator\&.getValue()\&.
.SS "void org\&.jgap\&.audit\&.EvaluatorTest\&.testStoreGenotype_0 () throws Exception\fC [inline]\fP"

.PP
Definition at line 36 of file EvaluatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.DELTA\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.audit\&.EvaluatorTest\&.CVS_REVISION = '$Revision: 1\&.14 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file EvaluatorTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
