.TH "org.jgap.impl.BestChromosomesSelectorTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.BestChromosomesSelectorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestConstruct_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestDoubletteChromosomesAllowed_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestAdd_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSelect_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEmpty_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEmpty_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEmpty_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetOriginalRate_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetOriginalRate_0_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestSetOriginalRate_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestReturnsUnique_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestIsSerializable_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestDoSerialize_0\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.35 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBBestChromosomesSelector\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 22 of file BestChromosomesSelectorTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 27 of file BestChromosomesSelectorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testAdd_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 89 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.privateAccessor\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testConstruct_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 38 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.NaturalSelectorExt\&.getDoubletteChromosomesAllowed(), org\&.jgap\&.JGAPTestCase\&.privateAccessor, and org\&.jgap\&.impl\&.BestChromosomesSelector\&.returnsUniqueChromosomes()\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testConstruct_3 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.1 
.RE
.PP

.PP
Definition at line 57 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testDoSerialize_0 () throws Exception\fC [inline]\fP"
Ensures that BCS implements Serializable correctly\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 488 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.doSerialize()\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testDoubletteChromosomesAllowed_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 70 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.NaturalSelectorExt\&.getDoubletteChromosomesAllowed()\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testEmpty_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 348 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.privateAccessor\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testEmpty_1 () throws Exception\fC [inline]\fP"
Test if clear()-method does not affect original \fBPopulation\fP\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 370 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testEmpty_2 () throws Exception\fC [inline]\fP"
Test if clear()-method does not affect return value\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 391 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testIsSerializable_0 () throws Exception\fC [inline]\fP"
Ensures BCS is implementing Serializable\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 474 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.isSerializable()\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testReturnsUnique_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 460 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.BestChromosomesSelector\&.returnsUniqueChromosomes()\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testSelect_0 () throws Exception\fC [inline]\fP"
Test if below functionality available without error\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 121 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testSelect_1 () throws Exception\fC [inline]\fP"
Test selection algorithm\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 145 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testSelect_2 () throws Exception\fC [inline]\fP"
Test selection algorithm\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 196 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testSelect_3 () throws Exception\fC [inline]\fP"
Ensure that selected Chromosomes are not equal to added Chromosomes\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 242 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.privateAccessor\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testSelect_4 () throws Exception\fC [inline]\fP"
Test selection algorithm with allowed doublettes\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 280 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testSetOriginalRate_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 411 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testSetOriginalRate_0_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 429 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.testSetOriginalRate_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.2 
.RE
.PP

.PP
Definition at line 447 of file BestChromosomesSelectorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, and org\&.jgap\&.impl\&.BestChromosomesSelector\&.getOriginalRate()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.BestChromosomesSelectorTest\&.CVS_REVISION = '$Revision: 1\&.35 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file BestChromosomesSelectorTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
