.TH "org.jgap.impl.CrossoverOperatorTest" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.CrossoverOperatorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.JGAPTestCase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGeneticOperatorConstraintForTesting\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtestConstruct_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_4\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_5\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_6\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_7\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_8\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestConstruct_9\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestOperate_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestOperate_0_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestOperate_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestOperate_2\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestOperate_3\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestIsSerializable_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestDoSerialize_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestDoSerialize_1\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEquals_0\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestCompareTo_0\fP ()  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.33 $'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests the \fBCrossoverOperator\fP class\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 22 of file CrossoverOperatorTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.setUp ()\fC [inline]\fP"

.PP
Definition at line 32 of file CrossoverOperatorTest\&.java\&.
.SS "static Test org\&.jgap\&.impl\&.CrossoverOperatorTest\&.suite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 27 of file CrossoverOperatorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testCompareTo_0 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 557 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.impl\&.CrossoverOperator\&.compareTo(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testConstruct_0 () throws Exception\fC [inline]\fP"
Following should be possible without error\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 43 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testConstruct_1 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 57 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testConstruct_2 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP

.PP
Definition at line 72 of file CrossoverOperatorTest\&.java\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testConstruct_4 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.2 
.RE
.PP

.PP
Definition at line 88 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.BaseGeneticOperator\&.getConfiguration(), org\&.jgap\&.impl\&.CrossoverOperator\&.getCrossOverRate(), and org\&.jgap\&.impl\&.CrossoverOperator\&.isAllowFullCrossOver()\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testConstruct_5 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.2 
.RE
.PP

.PP
Definition at line 102 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.BaseGeneticOperator\&.getConfiguration(), org\&.jgap\&.impl\&.CrossoverOperator\&.getCrossOverRate(), and org\&.jgap\&.impl\&.CrossoverOperator\&.isAllowFullCrossOver()\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testConstruct_6 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.2 
.RE
.PP

.PP
Definition at line 116 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.BaseGeneticOperator\&.getConfiguration(), org\&.jgap\&.impl\&.CrossoverOperator\&.getCrossOverRate(), and org\&.jgap\&.impl\&.CrossoverOperator\&.isAllowFullCrossOver()\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testConstruct_7 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.2 
.RE
.PP

.PP
Definition at line 130 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, org\&.jgap\&.BaseGeneticOperator\&.getConfiguration(), org\&.jgap\&.impl\&.CrossoverOperator\&.getCrossOverRatePercent(), and org\&.jgap\&.impl\&.CrossoverOperator\&.isAllowFullCrossOver()\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testConstruct_8 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.2 
.RE
.PP

.PP
Definition at line 144 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, org\&.jgap\&.BaseGeneticOperator\&.getConfiguration(), org\&.jgap\&.impl\&.CrossoverOperator\&.getCrossOverRatePercent(), and org\&.jgap\&.impl\&.CrossoverOperator\&.isAllowFullCrossOver()\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testConstruct_9 () throws Exception\fC [inline]\fP"

.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.2 
.RE
.PP

.PP
Definition at line 158 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, org\&.jgap\&.JGAPTestCase\&.DELTA, org\&.jgap\&.BaseGeneticOperator\&.getConfiguration(), org\&.jgap\&.impl\&.CrossoverOperator\&.getCrossOverRatePercent(), and org\&.jgap\&.impl\&.CrossoverOperator\&.isAllowFullCrossOver()\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testDoSerialize_0 () throws Exception\fC [inline]\fP"
Ensures that the operator and all objects contained implement Serializable\&. Here, we use a null configuration\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 493 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.doSerialize()\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testDoSerialize_1 () throws Exception\fC [inline]\fP"
Ensures that the operator and all objects contained implement Serializable\&. Here, we set a configuration\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 512 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.doSerialize()\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testEquals_0 () throws Exception\fC [inline]\fP"
Test equals with classcast object\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 545 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testIsSerializable_0 () throws Exception\fC [inline]\fP"
Ensures the operator is implementing Serializable\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 479 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.isSerializable()\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testOperate_0 () throws Exception\fC [inline]\fP"
Use flat crossover rate and just exchange two alleles via crossover\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition at line 174 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testOperate_0_2 () throws Exception\fC [inline]\fP"
Consider crossover rate calculator\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 240 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testOperate_1 () throws Exception\fC [inline]\fP"
Tests if crossing over produces same results for two operate-runs\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 306 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.Chromosome\&.clone(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.JGAPTestCase\&.isChromosomesEqual()\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testOperate_2 () throws Exception\fC [inline]\fP"
Test with \fBCompositeGene\fP\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.1 
.RE
.PP

.PP
Definition at line 357 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), org\&.jgap\&.JGAPTestCase\&.conf, and org\&.jgap\&.impl\&.CompositeGene\&.getAllele()\&.
.SS "void org\&.jgap\&.impl\&.CrossoverOperatorTest\&.testOperate_3 () throws Exception\fC [inline]\fP"
Considers \fBIGeneticOperatorConstraint\fP\&. Here, the crossing over of a \fBBooleanGene\fP is forbidden by that constraint\&.
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.6 
.RE
.PP

.PP
Definition at line 416 of file CrossoverOperatorTest\&.java\&.
.PP
References org\&.jgap\&.JGAPTestCase\&.assertEquals(), and org\&.jgap\&.JGAPTestCase\&.conf\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.CrossoverOperatorTest\&.CVS_REVISION = '$Revision: 1\&.33 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 25 of file CrossoverOperatorTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
