.TH "org.jgap.gp.GPPopulationConverter" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.gp.GPPopulationConverter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits XStreamPassThruConverter, and Converter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGPPopulationConverter\fP (XStream a_xstream, GPConfiguration a_conf)"
.br
.ti -1c
.RI "Object \fBdoUnmarshal\fP (UnmarshallingContext context)  throws Exception "
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.3 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Converts an XStream to a GPPopulation object\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.3\&.4 
.RE
.PP

.PP
Definition at line 24 of file GPPopulationConverter\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.gp\&.GPPopulationConverter\&.GPPopulationConverter (XStreama_xstream, GPConfigurationa_conf)\fC [inline]\fP"

.PP
Definition at line 29 of file GPPopulationConverter\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Object org\&.jgap\&.gp\&.GPPopulationConverter\&.doUnmarshal (UnmarshallingContextcontext) throws Exception\fC [inline]\fP"

.PP
Definition at line 34 of file GPPopulationConverter\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.gp\&.GPPopulationConverter\&.CVS_REVISION = '$Revision: 1\&.3 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 27 of file GPPopulationConverter\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
