.TH "org.jgap.data.IDataElementList" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.data.IDataElementList \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg\&.jgap\&.data\&.DataElementList\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIDataElement\fP \fBitem\fP (int a_index)"
.br
.ti -1c
.RI "int \fBgetLength\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (\fBIDataElement\fP a_element)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.4 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBIDataElementList\fP is an interface describing a list of \fBIDataElement\fP elements
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
2\&.0 
.RE
.PP

.PP
Definition at line 18 of file IDataElementList\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void org\&.jgap\&.data\&.IDataElementList\&.add (\fBIDataElement\fPa_element)"

.SS "int org\&.jgap\&.data\&.IDataElementList\&.getLength ()"

.PP
Implemented in \fBorg\&.jgap\&.data\&.DataElementList\fP\&.
.PP
Referenced by org\&.jgap\&.data\&.DataTreeBuilderTest\&.testRepresentChromosomeAsDocument_0(), and org\&.jgap\&.data\&.DataTreeBuilderTest\&.testRepresentGenotypeAsDocument_0()\&.
.SS "\fBIDataElement\fP org\&.jgap\&.data\&.IDataElementList\&.item (inta_index)"

.PP
Referenced by org\&.jgap\&.data\&.DataElement\&.getElementsByTagName()\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.data\&.IDataElementList\&.CVS_REVISION = '$Revision: 1\&.4 $'\fC [static]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 20 of file IDataElementList\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
