.TH "org.jgap.distr.grid.common" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.distr.grid.common \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBasicContext\fP"
.br
.ti -1c
.RI "class \fBClientStatus\fP"
.br
.ti -1c
.RI "class \fBCommonConfiguration\fP"
.br
.ti -1c
.RI "class \fBNoWorkResultsFoundException\fP"
.br
.ti -1c
.RI "class \fBResultData\fP"
.br
.ti -1c
.RI "class \fBResultVerification\fP"
.br
.ti -1c
.RI "class \fBWorkRequestsSendException\fP"
.br
.ti -1c
.RI "class \fBWorkResultNotFoundException\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
