.TH "org.jgap.impl.job.EvolveData" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.impl.job.EvolveData \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.jgap\&.impl\&.job\&.JobData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEvolveData\fP (\fBConfiguration\fP a_config)"
.br
.ti -1c
.RI "\fBPopulation\fP \fBgetPopulation\fP ()"
.br
.ti -1c
.RI "void \fBsetPopulation\fP (\fBPopulation\fP a_pop)"
.br
.ti -1c
.RI "void \fBsetBreeder\fP (\fBIBreeder\fP a_breeder)"
.br
.ti -1c
.RI "\fBIBreeder\fP \fBgetBreeder\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBPopulation\fP \fBm_pop\fP"
.br
.ti -1c
.RI "\fBIBreeder\fP \fBm_breeder\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.5 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data needed by a \fBIEvolveJob\fP implementation to evolve\&.
.PP
\fBAuthor:\fP
.RS 4
Klaus Meffert 
.RE
.PP
\fBSince:\fP
.RS 4
3\&.2 
.RE
.PP

.PP
Definition at line 21 of file EvolveData\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.jgap\&.impl\&.job\&.EvolveData\&.EvolveData (\fBConfiguration\fPa_config)\fC [inline]\fP"

.PP
Definition at line 29 of file EvolveData\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIBreeder\fP org\&.jgap\&.impl\&.job\&.EvolveData\&.getBreeder ()\fC [inline]\fP"

.PP
Definition at line 45 of file EvolveData\&.java\&.
.PP
References org\&.jgap\&.impl\&.job\&.EvolveData\&.m_breeder\&.
.SS "\fBPopulation\fP org\&.jgap\&.impl\&.job\&.EvolveData\&.getPopulation ()\fC [inline]\fP"

.PP
Definition at line 33 of file EvolveData\&.java\&.
.PP
References org\&.jgap\&.impl\&.job\&.EvolveData\&.m_pop\&.
.SS "void org\&.jgap\&.impl\&.job\&.EvolveData\&.setBreeder (\fBIBreeder\fPa_breeder)\fC [inline]\fP"

.PP
Definition at line 41 of file EvolveData\&.java\&.
.PP
References org\&.jgap\&.impl\&.job\&.EvolveData\&.m_breeder\&.
.SS "void org\&.jgap\&.impl\&.job\&.EvolveData\&.setPopulation (\fBPopulation\fPa_pop)\fC [inline]\fP"

.PP
Definition at line 37 of file EvolveData\&.java\&.
.PP
References org\&.jgap\&.impl\&.job\&.EvolveData\&.m_pop\&.
.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.impl\&.job\&.EvolveData\&.CVS_REVISION = '$Revision: 1\&.5 $'\fC [static]\fP, \fC [private]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 24 of file EvolveData\&.java\&.
.SS "\fBIBreeder\fP org\&.jgap\&.impl\&.job\&.EvolveData\&.m_breeder\fC [private]\fP"

.PP
Definition at line 27 of file EvolveData\&.java\&.
.PP
Referenced by org\&.jgap\&.impl\&.job\&.EvolveData\&.getBreeder(), and org\&.jgap\&.impl\&.job\&.EvolveData\&.setBreeder()\&.
.SS "\fBPopulation\fP org\&.jgap\&.impl\&.job\&.EvolveData\&.m_pop\fC [private]\fP"

.PP
Definition at line 26 of file EvolveData\&.java\&.
.PP
Referenced by org\&.jgap\&.impl\&.job\&.EvolveData\&.getPopulation(), and org\&.jgap\&.impl\&.job\&.EvolveData\&.setPopulation()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
