.TH "org.jgap.util.tree.TreeBranchRenderer" 3 "Sat Nov 23 2013" "Version 1.2" "Práctica_5_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.jgap.util.tree.TreeBranchRenderer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Color \fBgetBranchColor\fP (Object node, int level)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBCVS_REVISION\fP = '$Revision: 1\&.2 $'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file TreeBranchRenderer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Color org\&.jgap\&.util\&.tree\&.TreeBranchRenderer\&.getBranchColor (Objectnode, intlevel)"

.SH "Member Data Documentation"
.PP 
.SS "final String org\&.jgap\&.util\&.tree\&.TreeBranchRenderer\&.CVS_REVISION = '$Revision: 1\&.2 $'\fC [static]\fP"
String containing the CVS revision\&. Read out via reflection! 
.PP
Definition at line 27 of file TreeBranchRenderer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Práctica_5_LDH from the source code\&.
